### ISSUE TITLE
tty_file fails on alpine34

### ISSUE THREAD

**Issue by jbergstroem** [libuv/libuv#1004]
This is because `/dev/tty` isn't available. I will look at changing mode on our test boxes but I'll file a PR to skip similar to the tty test as well.

**Comment by jbergstroem** [comment]
Example run: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-linux/nodes=alpine34-x64/103/console

**Comment by saghul** [comment]
Hum, I don't see that one failing, but I do see tty_pty fail, is that the one you meant?

~~~~
ok 30 - tty_file
not ok 31 - tty_pty
# Output from process `tty_pty`:
# Assertion failed in test/test-tty.c on line 277: 0 == uv_tty_init(&loop, &master_tty, master_fd, 0)
~~~~

**Comment by saghul** [comment]
Superseded by https://github.com/libuv/libuv/issues/1206
