### ISSUE TITLE
test runner: support writing to file

### ISSUE THREAD

**Issue by jbergstroem** [libuv/libuv#1006]
The "final" step in getting jenkins to eat tap test output is writing it to a file so we can have the tap parser pick it up.

**Comment by saghul** [comment]
Can't Jenkins do: `make check > foo 2>&1` ?

**Comment by jbergstroem** [comment]
Yes, but that would mean that reviewing the console logs won't be available which is at least pretty common in nodejs land. If you're cool with it I can set it up!

**Comment by jbergstroem** [comment]
Also, I recall `make check` outputting some debug info as well -- we probably need to move that out -- perhaps introduce a `make check-ci`?

**Comment by saghul** [comment]
Hum. How did we do this in the past? I recall we did have TAP output at some point. (or am I mistaken?)

**Comment by jbergstroem** [comment]
@saghul the current stdout is tap, we just haven't picked it up from jenkins.

**Comment by saghul** [comment]
Oh. Then I guess I dreamed about it :-) I would have sworn we had TAP interpretation / processing in the past.

**Comment by jbergstroem** [comment]
Perhaps Ben worked with the jobs; I didn't at least.

**Comment by cjihrig** [comment]
Is anyone opposed to closing this?

**Comment by bnoordhuis** [comment]
No, I'll close this out.
