### ISSUE TITLE
Prepare next release: 1.1.1

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#101]
I don't have anything pending for making a new release, let's make one :-)

Any objections @bnoordhuis, @piscisaureus ?

**Comment by piscisaureus** [comment]
No objections from me.

**Comment by bnoordhuis** [comment]
None from me either.

**Comment by piscisaureus** [comment]
Should it be 1.2.0 because of  
https://github.com/libuv/libuv/commit/025602da138ec9ca908f9303427903ea1dc06494 ?

**Comment by saghul** [comment]
It's kind of a bugfix + a feature, we can make it 1.2.0 no problem.

Since you just landed the MinGW build fix I plan to make the release tonight.

**Comment by bnoordhuis** [comment]
025602d tries very hard to be both binary and source compatible.  But bumping either minor or patch is fine by me.

**Comment by saghul** [comment]
1.2.0 it is! https://groups.google.com/forum/#!topic/libuv/czPFocTAn_c
