### ISSUE TITLE
RFC: single "base class" for uv_handle_t and uv_req_t

### ISSUE THREAD

**Issue by piscisaureus** [libuv/libuv#102]
I would like to have a single base type for handles and requests, and the `uv_handle_type` and `uv_req_type` types should share a name space.

The reason for this move is that it'll allow me to put requests and handles in the same queue, so I can get rid of a separate "endgame queue". That will quite easily let unix and windows share the same event loop core.

```
typedef struct {
  uv_object_type_t type;
  void* queue[2];
   void* data;
} uv_object_t;
```

**Comment by trevnorris** [comment]
Instead will the fields be contained within a macro, much like it is now?

**Comment by saghul** [comment]
Sounds like a good idea to me!

**Comment by bnoordhuis** [comment]
No objections, as long as I don't have to do the work. :-)

**Comment by piscisaureus** [comment]
I was thinking of https://github.com/libuv/libuv/commit/91a702aab1ea2e24aaee6c77a2764e74cc8fe846#diff-6

**Comment by trevnorris** [comment]
Total nit, but is "object" the best word choice? This is coming from the
massively confused JS side of me. :-P

**Comment by saghul** [comment]
> I was thinking of 91a702a#diff-6

I looked at the whole diff and it looks good!

**Comment by saghul** [comment]
> Total nit, but is "object" the best word choice? This is coming from the massively confused JS side of me. :-P

In a way we are emulating some OO hierarchy with that, so find "object" appropriate here IMHO.

**Comment by txdv** [comment]
uv_guess_handle still has the word handle in it, but i can't come up with a better name

**Comment by piscisaureus** [comment]
Continuing in #116
