### ISSUE TITLE
[v2] remove suggested_size from alloc_cb?

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#1025]
Our allocation callback has got that `suggested_size` parameter since the dawn of time, but it doesn't really do much since for the most part (except Windows in a couple of places) it's set to 64K.  It seems to throw some pople off, thinking they always need 64K.

So I wonder: should we remove it and have the user allocate as much as they want?  We can just work with it no problem.

I thought if maybe in the future we could do something to make it more accurate... but it hasn't happened in the past 5 years so I guess it wouldn't be happening any time soon.  Technically users can already use `uv_fileno` and then `ioctl(fd, FIONREAD)` (on supported platforms) in the callback to allocate size, so we're not that away.

Thoughts? @libuv/collaborators

**Comment by bnoordhuis** [comment]
I think I'm okay with removing it as long as the documentation suggests some good default so people aren't left guessing.

> I thought if maybe in the future we could do something to make it more accurate... but it hasn't happened in the past 5 years so I guess it wouldn't be happening any time soon.

I agree.  On kqueue-based systems we know how much data is available (it's in `ev->data` and we record it as `w->rcount`) but we don't act on it because by the time we process it more data may be available, necessitating more system calls to drain the kernel buffer.

**Comment by txdv** [comment]
It was discussed that on linux ioctl FIONREAD was too much overhead for no benefit. Ram is cheap, allocating enough of a buffer in userspace is good enough.

**Comment by jessicaquynh** [comment]
Hello! I am new to this project and C, but I would love to learn more. 

Does anybody mind if I take this as my first contribution?

**Comment by txdv** [comment]
Go ahead.

**Comment by jessicaquynh** [comment]
Hi there, 

I'm still getting familiar with the codebase etc. I just wanted to make sure I'm on the right path.

Thus far I've [removed](https://github.com/jessicaquynh/libuv/commit/94bc9caa5b15dc39d9d67ab17618719c6e69ff59) `suggested_size` from the typedef. And I'm working on removing the parameter from the `src` and `tests`; but I am encountering allocation failures on the tests where I've replaced the suggested size with 65536. 

Perhaps it's not as simple as this implementation. If anyone can shed light on this, I'd very much appreciate it.

**Comment by bnoordhuis** [comment]
@jessicaquynh Can you define "allocation failures" or give an example of where it's failing for you now?

**Comment by jessicaquynh** [comment]
Yes certainly.

This is one error output from `test-ping-pong.c`:
```
not ok 42 - tcp_ping_pong
# exit code 6
# Output from process `tcp_ping_pong`:
# run-tests(97868,0x7fff7c363000) malloc: *** error for object 0x10dc43f10: pointer being freed was not allocated
# *** set a breakpoint in malloc_error_break to debug
Output from process `tcp_ping_pong`:
# PING
# PONG 0
# PING
# got EOF
# Assertion failed in test/test-ping-pong.c on line 60: NUM_PINGS == pinger->pongs
```
Similar error output occurs for the tests `tcp_ping_pong_v6` and `pipe_ping_pong`.

**Comment by bnoordhuis** [comment]
That message suggests you introduced a bug somewhere.  Perhaps round up your current work-in-progress and open a pull request so others can help you look at it.

**Comment by jessicaquynh** [comment]
Thanks @bnoordhuis, I have taken your recommendation and opened a [pull request](https://github.com/libuv/libuv/pull/1114). I look forward to any feedback!

**Comment by kroggen** [comment]
I suggest to pause this for a while.

The reason the suggested_size is not used is mainly because it is not required on streams, but it is required on message-based communication.

I implemented a length-prefixed message framing for libuv with an alloc_cb in which the suggested_size must be respected, at least as the minimum size.

Even if this message framing code is not integrated in libuv but used on top of it, it would be good to keep the alloc_db in this way so it will remain compatible with implementations that require a suggested_size on the allocation.

**Comment by saghul** [comment]
@kroggen 

> I suggest to pause this for a while.
> 
> The reason the suggested_size is not used is mainly because it is not required on streams, but it is required on message-based communication.
> 
> I implemented a length-prefixed message framing for libuv with an alloc_cb in which the suggested_size must be respected, at least as the minimum size.

The suggested size can still be picked by you, currently libuv suggests a hardcoded value, which doesn't give us much.  libuv won't do anything with that suggested size, it will use the size for the buffer you initialized, be that larger or smaller than the suggested one.

> Even if this message framing code is not integrated in libuv but used on top of it, it would be good to keep the alloc_db in this way so it will remain compatible with implementations that require a suggested_size on the allocation.

The API change is minimal, it will happen in a *major* release, and you'll be able to easily ifdef it.  We'll have migration documentation, when time comes.

**Comment by InsidiousMind** [comment]
Has this been solved yet? I'm on break and will be for the next 5ish weeks. I'd love to start contributing, and I would be more then willing to tackle this issue as a first. I see that @jessicaquynh has opened a pull request, but i'm not entirely sure of the status. It seems that it has not been totally finished. Is this still a work-in-progress?

**Comment by txdv** [comment]
Just no follow up by jessica.

**Comment by jessicaquynh** [comment]
Hey! I believe the last review I received was on some documentation changes. I squashed the changes so I don't think it showed up (I'm quite new to contributing, so I'm not sure how the process goes!). 

Would anybody be able point to anymore changes to be done to land this?

**Comment by txdv** [comment]
I'm sorry! I guess no follow up by the libuv maintainers, the patch compiles, the test do not return anything, the code looks ok.

**Comment by saghul** [comment]
@jessicaquynh Sorry for the silence.  It's definitely on the radar.  I've personally been quite overworked lately so I didn't have much time to review, but I'll eventually get to it.

**Comment by jessicaquynh** [comment]
@saghul No problem! Thank you for the review sent in.

**Comment by vtjnash** [comment]
In progress (maybe) in https://github.com/libuv/libuv/pull/1114
