### ISSUE TITLE
[v2] reevaluate uv_buf_init?

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#1034]
While working on some doc updates I noticed `uv_buf_init` feels a bit weird now. In the past (0.x) the buffer members where deemed "readonly" and this function was used all across, both for writing (when creating the uv_buf_t for uv_write) and reading (since alloc_cb had to return a uv_buf_t struct). Now that's no longer the case for reading, since alloc_cb already provides a buffer struct which the user must fill. When writing, it just saves us one line.

One thing we could do is change it a bit to:

~~~~
void uv_buf_init(uv_buf_t*buf, char*data, size_t size)
~~~~

And then its use would maybe be more consistent in reading / writing. Another possibility is to completely get rid of it of course.

Or we could do nothing.

Thought? @libuv/collaborators

**Comment by indutny** [comment]
I think this change has much bigger complications for old users than profits.

**Comment by indutny** [comment]
Also, consider cross-version support. People may want to support multiple versions of libuv at once.

**Comment by saghul** [comment]
> Also, consider cross-version support. People may want to support multiple versions of libuv at once.

That shouldn't be an issue, you can define this function with another name and use it, it's 2 lines!

**Comment by indutny** [comment]
Let's pile up defines! :)

**Comment by bnoordhuis** [comment]
The main reason we have `uv_buf_init()` is because the order of the fields is different on Windows (len+base instead of base+len.)

I'm fine really with its current prototype.  It's a little inconvenient to use from a FFI because it returns a struct but that is really just a paper-cut issue.

**Comment by saghul** [comment]
> The main reason we have uv_buf_init() is because the order of the fields is different on Windows (len+base instead of base+len.)

I know, but that's so we can cast them, right? It doesn't affect how we initialize the fields.

> I'm fine really with its current prototype. It's a little inconvenient to use from a FFI because it returns a struct but that is really just a paper-cut issue.

Ok then, since you and Fedor are not much in favor and I'm not dead set on it, let's drop it.
