### ISSUE TITLE
[v2] rename uv_idle_t

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#1035]
Its name has always been really misleading, let's fix that now that we can. Strawman proposal: **uv_spin_t**, since that's what it does: it makes the loop spin.

Thoughts? @libuv/collaborators

**Comment by indutny** [comment]
idk, if this is less confusing... Leaving this up to the rest of @libuv/collaborators

**Comment by bnoordhuis** [comment]
We could simply remove it.  Idle handles duplicate timers with a zero timeout, the only difference is that they run after pending callbacks instead of before.

Node.js uses them to implement `setImmediate()` but I think it could - and should - hang them off the big `setTimeout()` timer.  Right now you have this weird situation where a) `setTimeout()` timers run, b) some other callbacks run (mostly close callbacks), then c) `setImmediate()` timers run.

**Comment by saghul** [comment]
I have used them when integrating the libuv event loop with others, such as Python's asyncio.  I used it to drain a callback queue, while allowing some other stuff to run.

Now, truth be told, I could have probably used a repeating timer with zero timeout, yeah.

I'd be cautious about removing the handle, but the fact that Node doesn't actually need it makes a good point.

**Comment by kroggen** [comment]
Hi guys!

Will this not affect `process.nextTick()`?

The node.js documentation says:

> This is not a simple alias to setTimeout(fn, 0), it's much more efficient. It runs before any additional I/O events (including timers) fire in subsequent ticks of the event loop.

**Comment by InsidiousMind** [comment]
Took this as my first contribution, and as an opportunity to learn the codebase a bit. I felt as if uv_spin_t was the name to use considering the situation and so implemented it accordingly (at least so I think, i'm sure you guys will have a better idea). 
#1173 for the PR

**Comment by davisjam** [comment]
I agree the name is confusing. At a minimum it could be changed -- cosmetic, but suited for v2 (could add in v1 as an alias and mark the idle APIs as deprecated).

My two cents: I don't think it should be removed entirely. I think it's useful to differentiate between zero-time timers and a "run every loop" callback. The contract for timers is "run this no earlier than X seconds in the future", and *it just so happens* that this is implemented as "on the next turn of the loop". But this is an accident of implementation, and it seems cleaner to me to have a separate, loop-centric, way to schedule per-iteration CBs.

Now, we could change the *implementation* of `uv_idle_t` to use a zero-timeout timer. But this would require changing the [loop spec](http://docs.libuv.org/en/v1.x/design.html#the-i-o-loop).

**Comment by saghul** [comment]
> My two cents: I don't think it should be removed entirely. I think it's useful to differentiate between zero-time timers and a "run every loop" callback.

But these 2 are the exact same thing. 

> The contract for timers is "run this no earlier than X seconds in the future", and it just so happens that this is implemented as "on the next turn of the loop". But this is an accident of implementation, and it seems cleaner to me to have a separate, loop-centric, way to schedule per-iteration CBs.

I'm not sure I follow. The event loop has a number of phases, timers and idle handles being 2 of those. The fact that a 0 timeout timer will make the loop not block (same goes for idle handles) and go to the next iteration is not an implementation detail, but a conscious decision.

**Comment by davisjam** [comment]
## Let me revise my stance.

I thought that the only guarantee libuv offered for timers was that they would go off "no earlier than X seconds in the future", in which case a 0-timeout timer and a "run every loop" CB have different implications. But I was thinking of the guarantee from Node's [timer docs](https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args): "Node.js makes no guarantees about the exact timing of when callbacks will fire, nor of their ordering. The callback will be called as close as possible to the time specified."

The libuv [timer docs](http://docs.libuv.org/en/v1.x/timer.html#c.uv_timer_start) offer a much more precise guarantee for 0-timeout timers: "If timeout is zero, the callback fires on the next event loop iteration". Based on this, a 0-timeout repeating timer has exactly the same guarantee as a "run every loop" CB.

## Performance implications?

I would be interested to see a performance comparison of 0-timeout repeating timers vs. `uv_idle_t`. Seems like timers would have more overhead.

**Comment by bnoordhuis** [comment]
> Seems like timers would have more overhead.

Probably not measurable outside contrived benchmarks.  Timers use a heap, idle handles a doubly linked list, so insertion and removal is O(log n) vs. O(1), but that makes little practical difference until you have 1,000s of handles.
