### ISSUE TITLE
add platform-specific issue/PR labels

### ISSUE THREAD

**Issue by misterdjules** [libuv/libuv#1036]
[As discussed in the PR that documented supported platforms](https://github.com/libuv/libuv/pull/991#issuecomment-239249436), I'd like the libuv project to add platform-specific issue/PR labels for all supported platforms, and libuv collaborators to use these labels when an issue/PR is specific to one or more of these platforms.

The primary motivation for me is to make searching through SmartOS specific issues/PRs easier, so that I can check periodically for those that require my attention.

**Comment by bnoordhuis** [comment]
I added a few labels and gave them the same name and colors as their nodejs/node counterparts.

nodejs/node only seems to have 'solaris', not 'smartos', so I followed that here but feel free to create one.

**Comment by misterdjules** [comment]
> I added a few labels

Thank you!

> nodejs/node only seems to have 'solaris', not 'smartos', so I followed that here but feel free to create one.

It seems I don't have permissions to create labels, probably because I'm not part of any team with access to the libuv/libuv repository.

**Comment by bnoordhuis** [comment]
Okay, added a smartos label.  The color was scientifically derived with `echo -n smartos | sha1sum | cut -b1-6`.

I added a 'linux' label using the same process because apparently we didn't have one.  I'll close but let me know if anything else needs to be done.
