### ISSUE TITLE
Download binaries?

### ISSUE THREAD

**Issue by justinmchase** [libuv/libuv#1042]
According to the documentation it says:

> Starting with libuv 1.7.0, binaries for Windows are also provided. 

As far as I can see there is only a windows installer available.  Is it possible to just get the binaries in a zip? I looked for a little while but haven't been able to find them.

Thanks.

**Comment by saghul** [comment]
This was brought up once in the past, and IIRC the resolution was that they can be easily extracted from the exe.  Have tried looking into that?  I really don't see the point in releasing 2 sets of binaries for Windows...

**Comment by justinmchase** [comment]
I just ran the installer and pulled out the binaries into my repo and then uninstalled.

If I had a say I'd vote for just a zip or tar.gz with the binaries in it. Preferably one for each platform and deployed to github as a release. If the binaries were available per platform then I could easily write a script that just pulls them down during initialization.

The way it is now, I will have to manually push the binaries into my repo from time to time. Not a big deal but it could be a little nicer I think.

**Comment by saghul** [comment]
> I just ran the installer and pulled out the binaries into my repo and then uninstalled.

I was under the impression you could "unzip" the installer.  I may off base here though.

> If I had a say I'd vote for just a zip or tar.gz with the binaries in it. Preferably one for each platform and deployed to github as a release. If the binaries were available per platform then I could easily write a script that just pulls them down during initialization.
> 
> The way it is now, I will have to manually push the binaries into my repo from time to time. Not a big deal but it could be a little nicer I think.

We don't really ship binaries.  We just release the source, except for that Windows installer, which is deemed "experimental".  We also don't use (nor plan to switch to using) GitHub releases, so that's most likely not going to happen.

Out of curiosity: is there a reason why you rather have binary libuv releases?  What if we generate them with a different MSVC version than your project uses?

**Comment by justinmchase** [comment]
Thanks for talking it through.

I never thought to try to unzip the .exe I'll give it a try and see what happens. It's a little strange, but if it works that's cool.

I'm actually trying to see how far I can get without having VS installed at all. I'm using this:
http://landinghub.visualstudio.com/visual-cpp-build-tools

It basically installs the compile tools and libs and headers but no visual studio at all. It's just that this one lib requires one way of building, another requires some other way. Different versions of VS, etc. etc. Building native can be hard, the more so depending on how many dependencies you have :)

Perhaps I'm just spoiled by package managers at this point but I can't help but think how easy it would be to just download the binaries and go. It would be very easy for me to write a script that only has a version number in it and then when I'm ready just bump that and I'm done.

Other options are to build the binaries myself once, then commit them into my repo or to hook up submodules and deal with building them all every time someone checks out the repo. The latter can be hard with all the environmental setup and slow.

One other dependency I want to take, for example, is LLVM which is very large and takes quite a bit of time to build and also doesn't ship prebuilt binaries. So I am already dealing with this same situation there. I mean it also has an installer but I want to depend on some of the libs that you can only get from building.

I just wish everyone had their binaries up for each platform and then I could save quite a bit of hassle and time. I've had luck automating this in the past on Travis-ci and AppVeyor. Whenever a tagged build lands into a branch in github it would trigger an official build and package and pub the binaries for darwin/linux/win32 x x86/x64 x debug/release automatically.

I'm not saying its easy but it is possible and pretty slick.

For example, building a matrix for win32 on appveyor:
https://github.com/EvolveLabs/node-mumble-audio/blob/master/appveyor.yml

Similar build for darwin on travis-ci:
https://github.com/EvolveLabs/node-mumble-audio/blob/master/.travis.yml

I never quite got to linux but it should work if the code compiles. 

The publish step then uploaded them to s3 in this pattern:
https://s3.amazonaws.com/evolve-bin/node-mumble-audio/node-mumble-audio-0.2.5-win32-ia32-debug.tgz

I then had scripts used during the npm "preinstall" step which would pull down the binaries for that platform/architechture/version and use those. Anyway, it was tricky but having the binaries up can open up all kinds of automation possibilities. 

Thanks for listening and talking.

**Comment by saghul** [comment]
It's really hard to provide binaries for Unix platforms, so we just don't. Also, for better or worse, many applications seem to statically link libuv so that also helps.

On Windows, however, the situation is trickier.  With the package you mentioned you should be able to compile libuv, except for the fact we require Python.  The alternative would be to include the VS solution file in the repo, but not enough people complained about it for us to make a desicion on that :-)

In the v1.x branch we support VS >= 2008.  That's a lot of versions that would need binaries and we just don't have the inclination nor the manpower to do that.

Last, libuv is not and end user piece of software, it's a library, so IMHO it's not unreasonable to expect developers to have the necessary tools to build it.

Please send an email to the mailing list and maybe we can find some critical mass which feels like we could improve this on Windows.  I know the Kestrel folks mentioned something about releasing unmodified libuv binaries on Nuget, but I'm not sure what's the state of that, or if they made any other advancements.

I hope you understand. Cheers!

**Comment by justinmchase** [comment]
I understand, I have a dream that one day we will all be using package managers for native libraries... but until that day I'll keep building these things as I need them. Thanks.

**Comment by txdv** [comment]
Microsoft releases a binary nuget package with libuv  linux(x64), osx, windows(arm, x86, x64) binaries: https://www.nuget.org/packages/Libuv/

Just press Download and then open the downloaded file with a zip archiver of your choice. The linux binaries are all the same on 1.9.0.

Not the most official way, but better than nothing.

**Comment by justinmchase** [comment]
Wow that's awesome! Exactly what I was looking for. I didn't think to look there. I suppose they use it for their forked node builds?

Msft for the win?

**Comment by YurySolovyov** [comment]
If I want to link libuv on all major platforms - Linux x64, MacOS, Windows x64, but I don't want to build it form source on all of them, what are my options?

**Comment by bnoordhuis** [comment]
> One way I can see would be to have a CI service build this repo for me on all the platforms and then upload results somewhere, but it seems like something that should happen on the official level.

While it's not completely out of the question, there are a lot of subtle, nasty issues, like .a or .so files compiled against a newer glibc not working with older glibc versions. It took us years to work out all the kinks for Node.js and it's still an ongoing effort.

**Comment by YurySolovyov** [comment]
Publishing ones from official Tier 1 CI runs on release cuts could be a start.
Provided as a "best effort" kind of guarantees.
(I'm not demanding anything tho)

**Comment by saghul** [comment]
We had that for Windows and ended up removing it, FWIW.

**Comment by YurySolovyov** [comment]
@txdv any idea who at MS we can poke to make them publish more recent versions?

**Comment by justinmchase** [comment]
@YurySolovyov On the nuget package page there is a link to "Contact Owners"; I went ahead and sent them this message:

> Hello!
>
> I was wondering if you could publish an updated version of a package that you maintain?
> 
> Specifically this package:
> https://www.nuget.org/packages/Libuv/
>
> It appears that you are the only known publisher of precompiled binaries for libuv on multiple platforms and it would help the community out quite a bit if you were to update it, however infrequently.
>
> Here is a link to the discussion thread that prompted this email in case you are interested:
> https://github.com/libuv/libuv/issues/1042

If I get no response I'll try to poke a few people directly.

**Comment by justinmchase** [comment]
Its been a long time since I looked at this but I just wanted to say that since this is an open source project you can hook it up to travis-ci and appveyor for free.

travis-ci supports building in linux and darwin while appveyor supports building on windows and they both have good continuous integration with github. You can easily configure it so that on any branch or tag or whatever it will trigger a full build and publish automatically. You can also run docker containers from within travis during the build to increase your build matrix to even more specific flavors of linux.

Once compiled simply zip the binaries, libs and headers and publish them as a release to github here, who has an api for that purpose. People can then rely on those packages being in place simply by knowing the version number, which github also has an API to get.

That's how I would do it, it has a cost in terms of time, but should be free in terms of additional fees.

**Comment by Eilon** [comment]
Hi folks, I'm the engineering manager for the ASP.NET Core team at Microsoft, where we use Libuv as an option for ASP.NET Core's Kestrel cross-platform web server. We're the ones who own the Libuv package on NuGet.org (which I believe was done in consultation with Libuv reps at the time we first created the package several years ago).

I logged an issue for the ASP.NET Core team to publish a newer version of the Libuv package: https://github.com/aspnet/AspNetCore/issues/9307

Feel free to track that issue to monitor its status.

Thanks,
Eilon

**Comment by justinmchase** [comment]
@Eilon And now I know about Kestrel too, very cool. Keep up the good work.

**Comment by YurySolovyov** [comment]
Didn't last long:
> [Kestrel's libuv transport is now obsolete so we don't plan to update this dependency.](https://github.com/dotnet/aspnetcore/issues/9307#issuecomment-724308513)

**Comment by techno-express** [comment]
windows binaries directly from github actions build https://github.com/symplely/libuv/releases/latest
