### ISSUE TITLE
Enforcing poll timeout without a timer

### ISSUE THREAD

**Issue by eladn** [libuv/libuv#1043]
Is it possible to set a timeout for a poll event, so that if the event has not been triggered by the time the timeout reached, the handler would be called with a 'timeout' status? (In libevent, one can pass a timeout value to the event_add(...) method, so I'm wondering if it is possible in libuv as well)
If not, i thought to create a dedicated timer that would cancel the poll event after timeout reached. Is that the correct way to solve that problem? In that case, is it sufficient to call uv_close on the poll handler from the timer cb for that purpose?

**Comment by bnoordhuis** [comment]
> If not, i thought to create a dedicated timer that would cancel the poll event after timeout reached. Is that the correct way to solve that problem? In that case, is it sufficient to call uv_close on the poll handler from the timer cb for that purpose?

Yes and yes, that is the way to do it in libuv.

Can you post questions to the mailing list next time?  We try to keep the issue tracker focused to just bug reports and feature requests.  Thanks!
