### ISSUE TITLE
Document uv_handle_t.type

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#1044]
It's missing from the documentation: http://docs.libuv.org/en/v1.x/handle.html?highlight=uv_handle_t#public-members

**Comment by txdv** [comment]
https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L407

**Comment by saghul** [comment]
@txdv so?

**Comment by txdv** [comment]
Just putting a direct link to the field in the code
