### ISSUE TITLE
unix: don't use alphasort in uv_fs_scandir()

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#1045]
alphasort() uses strcoll() in some libcs (notably glibc and musl) which makes it locale-sensitive.

Replace it with a simple strcmp-based lexicographic comparison for consistent behavior across platforms.

**Comment by Xaekai** [comment]
I'm curious what the impetus for applying any sort of sorting was in the first place? Found this digging from rabbit hole of https://github.com/nodejs/node/issues/3232.

**Comment by bnoordhuis** [comment]
It was to harmonize the behavior of node's sync and async versions of `fs.readdir()`. One returned results in directory order, the other in sorted order.

Before the switch to libuv, the sync version was implemented in terms of `readdir()` or `scandir()`, whereas the async version was a thin wrapper around libeio's `eio_readdir()`.

**Comment by Xaekai** [comment]
Thank you for the insight into this behaviors origins.
