### ISSUE TITLE
libuv fails to be built with android-ndk

### ISSUE THREAD

**Issue by swat-cat** [libuv/libuv#1051]
Output of android-configure:
['-Dtarget_arch=arm', '-DOS=android', '-f', 'make-android', '/Users/max_ermakov/libuv/uv.gyp', '-I', '/Users/max_ermakov/libuv/common.gypi', '--depth=.', '-Goutput_dir=/Users/max_ermakov/libuv/out', '--generator-output', '/Users/max_ermakov/libuv/out', '-Dhost_arch=x64', '-Duv_library=static_library']

Output of make -C out:
In file included from ../test/test-fs.c:23:0:
../test/test-fs.c: In function 'run_test_fs_fstat':
../test/test-fs.c:1143:32: error: 'struct stat' has no member named 'st_atim'
   ASSERT(s->st_atim.tv_sec == t.st_atim.tv_sec); ...

**Comment by baremetalfreak** [comment]
@swat-cat could you test if #1056 solves the problem?

**Comment by swat-cat** [comment]
#1056 solves the problem. Thank you. Issue could be closed.
