### ISSUE TITLE
PIPE BIND error  Address already in use

### ISSUE THREAD

**Issue by lonerwolf** [libuv/libuv#106]
for(XXX)
          uv_pipe_bind(xxxx)
error Address already in use
in uv_pipe_bind
 err = uv__socket(AF_UNIX, SOCK_STREAM, 0);
is it need int opt = 1;
   setsockopt(socket_fd,SOL_SOCKET,SO_REUSEADDR,&opt,sizeof(opt));????

**Comment by lonerwolf** [comment]
i find problem. uv_pipe_bind will create a file.if program is exit without close, the file will no delete.can libuv use AF_INET Instead of AF_UNIX

**Comment by saghul** [comment]
> is it need int opt = 1;
> setsockopt(socket_fd,SOL_SOCKET,SO_REUSEADDR,&opt,sizeof(opt));????

AFAIS the SO_REUSEADDR socket option doesn't work for Unix domain sockets, which is the case. If there is a stalled file you'll need to unlink it yourself.

> i find problem. uv_pipe_bind will create a file.if program is exit without close, the file will no delete.can libuv use AF_INET Instead of AF_UNIX

In libuv pipes are implemented as Unix domain sockets, which do create a file, so using AF_INET is not an option, you can use a TCP handle for that. There are, however, abstract Unix domain sockets in Linux, which don't create a file. libuv doesn't support those right now, but you could open the fd yourself and then use `uv_pipe_open`.

**Comment by lonerwolf** [comment]
@saghul thanks
