### ISSUE TITLE
[v2] uv_pipe_connect

### ISSUE THREAD

**Issue by txdv** [libuv/libuv#1063]
I don't know if I am allowed to make v2 proposals, but the definition of [uv_pipe_connect](https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L695) was always a thorn in my eye and it was a rather small annoyance, too little for breaking api changes. [uv_tcp_connect](https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L538) returns an int, uv_pipe_connect doesn't (it queues all errors encountered immediately and passes them to the callback).

``` c
UV_EXTERN void uv_pipe_connect(uv_connect_t* req,
                               uv_pipe_t* handle,
                               const char* name,
                               uv_connect_cb cb);
UV_EXTERN int uv_tcp_connect(uv_connect_t* req,
                             uv_tcp_t* handle,
                             const struct sockaddr* addr,
                             uv_connect_cb cb);
```

Maybe making both signatures a bit more equal and make uv_pipe_connect return an int is a move in the right direction?

**Comment by saghul** [comment]
Yep, that's a welcome improvement! Since we are here though, we should also take a size, so abstract sockets work out of the box.

**Comment by txdv** [comment]
How do abstract sockets work now?

**Comment by txdv** [comment]
```c
V_EXTERN int uv_pipe_bind(uv_pipe_t* handle, const char* name);
UV_EXTERN int uv_pipe_connect(uv_connect_t* req,
                              uv_pipe_t* handle,
                              const char* name,
                              uv_connect_cb cb);
```

If we the connect signature is changed (size_t len added) then the bind signature has to be changed too?

**Comment by saghul** [comment]
> How do abstract sockets work now?

They kinda don't.  You have to create them yourself and then pass the fd to `uv_pipe_open`.

> If the connect signature is changed (size_t len added) then the bind signature has to be changed too?

Yep.  We should use some special value like -1 if you don't want to compute the length yourself, maybe.

**Comment by txdv** [comment]
0 maybe? Or just <= 0 ?

**Comment by kroggen** [comment]
So the changing of signature was cancelled due to an inconsistency with the return value, but what do you plan for abstract sockets support on v2?

Will `uv_pipe_connect` and `uv_pipe_bind`  accept a length/size argument?

Or continue with the same function and create a `uv_pipe_connect_2` for this?

What about the support of abstract sockets on v1? I sent a PR but we can also use another approach as having `uv_pipe_connect_2` or `uv_pipe_connect_ex`.

**Comment by txdv** [comment]
I don't know man, it looks it is really hard to get past the collaborators, so you really have to target their questions at them.

**Comment by neoxic** [comment]
Abstract sockets are easily implemented the "natural" way, i.e. the way they are listed by netstat on Linux.

If the first symbol of the path is '@' then it is substituted with '\0' internally leading to an abstract socket on Linux. This way it will be seamless for all **existing** and future usages to support abstract sockets without the hassle of doing the same (or similar) thing.
