### ISSUE TITLE
Put libuv on a diet

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#1065]
So far the diet libuv has been doing is working:

```
 $  git diff --shortstat v1.x..master
 56 files changed, 635 insertions(+), 2495 deletions(-)
```

But we can do better.  LESS CODE, MOAR BETTER.
- [x] Unify `uv__req_init`
- [ ] Use a queue to store requests on Windows
- [ ] Try to unify handle flags?
- [ ] Remove duplicated structture field definition

This is an ongoing effort, if you see an opportunity for unifying code and reducing duplication please leave a comment to update the list.

**Comment by txdv** [comment]
Maybe pull out the same stuff out of UV_LOOP_PRIVATE_FIELDS in uv-win.h and uv-unix.h?

**Comment by NatalieWolfe** [comment]
Unifying the idle, prepare, and check handles into a single handle distinguished by some enumeration may be good. Their interfaces are all the same, differing only in which queue they go into. Something like:

```c
void callback(uv_hook_t* hook, uv_queue_hook queue) {
  switch (queue) {
  case UV_PREPARE_HOOK: /* ... */; break;
  case UV_CHECK_HOOK: /* ... */; break;
  }
}

uv_hook_t hook;
uv_hook_init(uv_default_loop(), &hook);

// Hook the callback into _both_ prepare and check.
uv_hook_start(&hook, callback, UV_PREPARE_HOOK | UV_CHECK_HOOK);

// Remove the hook from _just_ the prepare queue.
uv_hook_stop(&hook, UV_PREPARE_HOOK);

// Remove the hook from all queues.
uv_hook_stop(&hook, UV_ALL_HOOK);
```

**Comment by bnoordhuis** [comment]
@NatalieWolfe Their implementations are generated through x-macros so they are already pretty compact (before macro expansion at least.)

It's probably possible to unify the Windows and UNIX implementations though.  src/unix/loop-watcher.c and src/win/loop-watcher.c have many commonalities.

**Comment by saghul** [comment]
> It's probably possible to unify the Windows and UNIX implementations though. src/unix/loop-watcher.c and src/win/loop-watcher.c have many commonalities.

THat's already the case :-) https://github.com/libuv/libuv/commit/3118e5a4e47c7376dfb191b928d23ec1a2a2b8a2

**Comment by cjihrig** [comment]
I'm going to remove the v2 label. These things can be done in any semver major, and don't need to hold up v2.

**Comment by txdv** [comment]
Isn't this easier to accomplish when you don't need to preserve the structure?

**Comment by cjihrig** [comment]
Yes. That's any semver major bump though, not just 2.0.0. If we start having yearly major releases, as proposed in https://github.com/libuv/libuv/issues/1597, then there's no need to keep delaying v2. This issue is almost a year and a half old now, so it's not like it's rapidly being implemented anyway.
