### ISSUE TITLE
Linux: uv_timer_start seems to depend on last known time point

### ISSUE THREAD

**Issue by alexhultman** [libuv/libuv#1068]
I have found this strange behavior with timers in libuv:

```c++
#include <iostream>
#include <chrono>
using namespace std;

#include <uv.h>
#include <unistd.h>

std::chrono::time_point<std::chrono::high_resolution_clock> start;

int main()
{
    uv_loop_t *loop = uv_default_loop();

    // trigger bug: block here!
    sleep(5);

    uv_timer_t timer;
    uv_timer_init(loop, &timer);
    start = std::chrono::high_resolution_clock::now();
    uv_timer_start(&timer, [](uv_timer_t *timer) {
        std::cout << "Timer timed out now: " << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now() - start).count() << " ms after call to uv_timer_start" << std::endl;
    }, 5000, 0);

    uv_run(loop, UV_RUN_DEFAULT);
}
```

The timer callback is called 0ms after call to uv_timer_start, but if I remove the sleep it triggers 5 seconds after call to uv_timer_start. It seems the time point is not updated when calling uv_timer_start. I can "fix" this by running the loop before calling uv_timer_start.

I'm using this Fedora package: libuv-devel-1:1.7.5-2.fc24.x86_64

**Comment by bnoordhuis** [comment]
Call `uv_update_time(loop)` in scenarios like that.  Updating libuv's idea of "now" can be expensive so it postpones that until it must (mostly around polling for events.)

**Comment by alexhultman** [comment]
Do you get this report often? I couldn't find any documentation of the behavior here http://docs.libuv.org/en/v1.x/timer.html

**Comment by saghul** [comment]
@alexhultman We actually don't.  Adding a note to the documentation never hurts.  Would you be up to making a documentation PR?

**Comment by alexhultman** [comment]
Yeah I could add it in a while.
