### ISSUE TITLE
win: uv_fs_read & uv_fs_write may leak request data buffers

### ISSUE THREAD

**Issue by jasongin** [libuv/libuv#1069]
I found the source of the memory leak reported at https://github.com/nodejs/node/issues/7191

When a large number of buffers (>4) is passed into [uv_fs_read()](https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L1943) or [uv_fs_write()](https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L1979), a new buffer is [dynamically](https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L1960) [allocated](https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L1996) to hold a copy of the request data. But, that buffer never gets freed. It should be freed by [uv_fs_req_cleanup()](https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L1882).

I'm verifying a fix and will submit a PR shortly.

**Comment by saghul** [comment]
Good catch! Can you add a "Refs" pointing to the node issue in the PR?  Thanks!

**Comment by jasongin** [comment]
OK, I added the "Refs" line to the commit description.
