### ISSUE TITLE
where the uv_prepare_invoke function's body?

### ISSUE THREAD

**Issue by ilimei** [libuv/libuv#1071]
these functions only find define no body 
void uv_prepare_invoke(uv_loop_t* loop);
void uv_check_invoke(uv_loop_t* loop);
void uv_idle_invoke(uv_loop_t* loop);

**Comment by ilimei** [comment]
i found it
UV_LOOP_WATCHER_DEFINE

**Comment by bnoordhuis** [comment]
Correct.  Can you post questions to the mailing list next time?  Thanks.

**Comment by ilimei** [comment]
ok,im sorry for that
