### ISSUE TITLE
win: uv_poll_init not discriminating between file and socket descriptors

### ISSUE THREAD

**Issue by CurlyMoo** [libuv/libuv#1077]
Calling `uv_poll_init` with a socket fd fails with an invalid socket message. This happens because inside the `uv_poll_init` an `uv__get_osfhandle` is used to translate the file descriptor to an os handle. This however, should not happen in case of socket handlers.

```
int uv_poll_init(uv_loop_t* loop, uv_poll_t* handle, int fd) {
  return uv_poll_init_socket(loop, handle, (SOCKET) uv__get_osfhandle(fd));
}
```

The `uv_poll_init` call should therefor descriminate between the two handlers and based on the result, do the translation.

I was about to do a PR on this directly, but thought to get a confirmation on the issue first.

I tested this on windows by directly passing the `fd` variable and that fixed the issue (in case of sockets).

**Comment by saghul** [comment]
On Windows we work with `SOCKET` handles, not CTR fds, hence the call to `uv__get_osfhandle`.  Where did you get the fd from?

Alternatively, if you already have a `SOCKET` you can pass it to `uv_poll_init_socket`.

**Comment by CurlyMoo** [comment]
> Where did you get the fd from?

```
uv_tcp_init(uv_default_loop(), client_req);
uv_ip4_addr(ip, port, &addr);
uv_tcp_connect(connect_req, client_req, (const struct sockaddr *)&addr, connect_cb);
```
In connect_cb
```
uv_fileno((uv_handle_t*)req->handle, &fd);
uv_poll_init(uv_default_loop(), poll_req, fd);
```

But indeed `uv_poll_init_socket` is probably what i was looking for.

**Comment by saghul** [comment]
Note that what you are trying to do is not supported.

A handle "owns" its fd, so if you "steal" it you'd be dancing in undefined
behavior territory.

**Comment by CurlyMoo** [comment]
> A handle "owns" its fd, so if you "steal" it you'd be dancing in undefined behavior territory.

Understood, After i start the poll, i stop using the other handles. I believe that should be safe. This is the best solution for handling ssl for now, because it works on both Windows and Unix.

**Comment by saghul** [comment]
> I believe that should be safe.

It's not.  It may abort() on Unix, because having 2 handles for the same fd is not supported.  Windows can be a bit more forgiving due to its structure, but as I said, you are on your  own.

I really encourage you to check `uv_link_t`.  It's the implementartion we are going to "bless" and it doesn't use any undefined behavior in libuv.

**Comment by saghul** [comment]
Closing this sinde it's not a libuv issue.  On Windows `uv_poll_init` should be used for CRT fds and `uv_poll_init_socket` for `SOCKET` handles.

**Comment by CurlyMoo** [comment]
> because having 2 handles for the same fd is not supported.

So the other option would be to setup the socket outside libuv and passing the fd to the poll init?

**Comment by saghul** [comment]
> So the other option would be to setup the socket outside libuv and passing the fd to the poll init?

Correct.
