### ISSUE TITLE
Lacks in documentation of `uv_poll_t`

### ISSUE THREAD

**Issue by eladn** [libuv/libuv#1078]
I think the official documentaion should address the following issues:
1. The callback will be called over-and-over again, AS LONG AS the given fd/socket is still readable/writable (depending on the given events given to poll). Particullary in each of the following scenerios:
   (a) The callback did not conduct a read/write at all when the socket is readable/writable.
   (b) The callback made a read on the socket, and have not read all the available data. or the callback made a write but the socket remained writable afterwards.
   (c) The socket has already became readable/writable before even starting the poll handle on this socket, and since then the state of the socket did not changed.
   In all of the above listed scenerios, the socket remains readable/writable and hence the callback will be called again.
2. It state that after stopping the poll handle, the callback will not be called. I think it is important to mentaion that it won't be called even if the socket has already become readable/writable before the handle was stopped, and the callback event was already pending.

Reference to posts in the mailing list:
https://groups.google.com/forum/#!topic/libuv/3COSl39ZkEY
https://groups.google.com/forum/#!topic/libuv/n-m0KBz0-fo

Elad.

**Comment by cjihrig** [comment]
@eladn would you care to open a PR?

**Comment by eladn** [comment]
I will.
1. Should I commit into master or v1.x ?
2. Is that the last relevant version?
https://github.com/libuv/libuv/blob/v1.x/docs/src/poll.rst
I noticed here: http://docs.libuv.org/en/v1.x/poll.html the `API` section is written, but it's not appears to be in git.

**Comment by saghul** [comment]
> I will.

Thanks!

> 1. Should I commit into master or v1.x ?

v1.x please.

> 2. Is that the last relevant version?
> https://github.com/libuv/libuv/blob/v1.x/docs/src/poll.rst

Yes.

> I noticed here: http://docs.libuv.org/en/v1.x/poll.html the API section is written, but it's not appears to be in git.

Note that GitHub doesn't render RST very well, open it in raw mode or with your editor of choice and you'll see the content.

**Comment by saghul** [comment]
Closing in favor of the PR.
