### ISSUE TITLE
[v1.9.1] uv_pipe_init(loop, &queue, 1) fails in windows, why?

### ISSUE THREAD

**Issue by CompileMaster** [libuv/libuv#1084]
i want use ipc 1 to pass  handles.
uv_pipe_init(loop, &queue, 0) is success,but it can't pass handles.

**Comment by saghul** [comment]
You must specify the ipc parameter to 1 in order to pass handles.  If you set it to zero it won't work.  That's what the parameter is for.

PS: Please, use the mailing list for questions.
