### ISSUE TITLE
uv__epoll_create1 does no return -1 on redhat5

### ISSUE THREAD

**Issue by ugiwgh** [libuv/libuv#1086]
The uv__epoll_create1 does not return -1 on redhat5, so uv__epoll_create won't be run forever.

Linux localhost.localdomain 2.6.18-8.el5 #1 SMP Fri Jan 26 14:15:14 EST 2007 x86_64 x86_64 x86_64 GNU/Linux

**Comment by saghul** [comment]
Have you tried updating the kernel to some version from this decade as Ben
suggested? :-)

**Comment by ugiwgh** [comment]
I code a standard OS program. So, I cannot update the kernel.

**Comment by bnoordhuis** [comment]
You don't even need to update to a newer version but at least update to the latest patch release, 2.6.18-398.

**Comment by ugiwgh** [comment]
The problem is that my customers donot want to update the kernel.

**Comment by bnoordhuis** [comment]
That's too bad but it means we can't offer support.  I'll close the issue.

**Comment by txdv** [comment]
It is impossible to fix this without using a newer kernel version.

**Comment by ugiwgh** [comment]
OK. Thanks a lot.
