### ISSUE TITLE
uv_getaddrinfo memory leak

### ISSUE THREAD

**Issue by AaronCAlbers** [libuv/libuv#1087]
According to Mac Instruments there appears to be a memory leak in uv_getaddrinfo().

Even a bare bones simple example appears to leak. The culprit seems to be from "uv__getaddrinfo_work" .

```c
#include <uv.h>
#include <stdio.h>
#include <stdlib.h>

uv_loop_t* loop;
uv_getaddrinfo_t handle;
const char* name = "localhost";

void getaddrinfo_cb(uv_getaddrinfo_t* handle, int status, struct addrinfo* res) {
    uv_freeaddrinfo(res);
}

int main() {
    loop = uv_default_loop();
    uv_getaddrinfo(loop, &handle, getaddrinfo_cb, name, "80", NULL);
    uv_run(loop, UV_RUN_DEFAULT);
    return 0;
}
```

![screen shot 2016-10-11 at 6 02 52 pm](https://cloud.githubusercontent.com/assets/20759340/19292955/29bf8da2-8fdd-11e6-88c4-208f7b6d6701.png)

**Comment by saghul** [comment]
I think that's a false positive.  Since you are using the default loop and never destroying it, there is stuff which is allocated but never freed. I had a quick look at our getaddringo code and I can't find any memory allocation we don't free.

Any chance Instruments can give some better information? As in, where was the memory allocated, for example.

**Comment by bnoordhuis** [comment]
Can you `uv_loop_delete(loop)` on exit and retry?  Also, valgrind (when it works on OS X) might give more useful output.

**Comment by AaronCAlbers** [comment]
No effect.

```c
#include <uv.h>
#include <stdio.h>
#include <stdlib.h>

uv_loop_t* loop;
uv_getaddrinfo_t handle;
const char* name = "localhost";

void getaddrinfo_cb(uv_getaddrinfo_t* handle, int status, struct addrinfo* res) {
  uv_freeaddrinfo(res);
}

int main() {
  loop = (uv_loop_t*)malloc(sizeof(uv_loop_t));
  
  uv_loop_init(loop);
  
  uv_getaddrinfo(loop, &handle, getaddrinfo_cb, name, "80", NULL);
  uv_run(loop, UV_RUN_DEFAULT);
  
  uv_loop_close(loop);
  
  free(loop);
  return 0;
}
```
![screen shot 2016-10-12 at 2 41 04 am](https://cloud.githubusercontent.com/assets/20759340/19303336/79a8ebea-9025-11e6-86fc-00593bd5e992.png)

Instruments does give more information but I am not sure what all you need.
![screen shot 2016-10-12 at 2 44 44 am](https://cloud.githubusercontent.com/assets/20759340/19303433/e5a06314-9025-11e6-8bd3-c51e34dbd178.png)

**Comment by bnoordhuis** [comment]
> Instruments does give more information but I am not sure what all you need.

The stack trace leading up to the allocation would help.  Valgrind records it; don't know about Instruments.

**Comment by AaronCAlbers** [comment]
Bytes Used	Count		Symbol Name
 273.69 KB     100.0%	67	 	thread_start
 273.69 KB     100.0%	67	 	 _pthread_start
 273.69 KB     100.0%	67	 	  _pthread_body
 273.69 KB     100.0%	67	 	   uv__thread_start
 273.69 KB     100.0%	67	 	    worker
 273.69 KB     100.0%	67	 	     uv__getaddrinfo_work
 273.69 KB     100.0%	67	 	      getaddrinfo
 258.39 KB      94.4%	22	 	       si_addrinfo
 257.94 KB      94.2%	16	 	        _gai_sort_list
 257.94 KB      94.2%	16	 	         _qsort
 257.94 KB      94.2%	16	 	          sa_dst_compare_internal
 257.00 KB      93.9%	13	 	           nwlog_is_debug_logging_enabled
 257.00 KB      93.9%	13	 	            pthread_once
 257.00 KB      93.9%	13	 	             _os_once
 257.00 KB      93.9%	13	 	              __pthread_once_handler
 257.00 KB      93.9%	13	 	               nwlog_legacy_init_once
 257.00 KB      93.9%	13	 	                os_log_create
 256.12 KB      93.5%	2	 	                 dispatch_once_f
 256.12 KB      93.5%	2	 	                  _dispatch_client_callout
 256.00 KB      93.5%	1	 	                   _os_trace_init
 256.00 KB      93.5%	1	 	                    voucher_activity_get_metadata_buffer
 256.00 KB      93.5%	1	 	                     dispatch_once_f
 256.00 KB      93.5%	1	 	                      _dispatch_client_callout
 256.00 KB      93.5%	1	 	                       _firehose_task_buffer_init
 256.00 KB      93.5%	1	 	                        firehose_buffer_create
 256.00 KB      93.5%	1	 	                         mach_vm_map
    128 Bytes    0.0%	1	 	                   ___os_log_preference_queue_block_invoke
    128 Bytes    0.0%	1	 	                    _dispatch_queue_create_with_target
    128 Bytes    0.0%	1	 	                     _os_object_alloc_realized
    128 Bytes    0.0%	1	 	                      class_createInstance
    128 Bytes    0.0%	1	 	                       calloc
    128 Bytes    0.0%	1	 	                        malloc_zone_calloc
    432 Bytes    0.1%	6	 	                 _os_log_preference_check
    352 Bytes    0.1%	5	 	                  dispatch_once_f
    352 Bytes    0.1%	5	 	                   _dispatch_client_callout
    352 Bytes    0.1%	5	 	                    notify_register_check
    352 Bytes    0.1%	5	 	                     client_registration_create
    208 Bytes    0.0%	3	 	                      name_node_for_name
    128 Bytes    0.0%	1	 	                       calloc
    128 Bytes    0.0%	1	 	                        malloc_zone_calloc
     48 Bytes    0.0%	1	 	                       strdup
     48 Bytes    0.0%	1	 	                        malloc
     48 Bytes    0.0%	1	 	                         malloc_zone_malloc
     32 Bytes    0.0%	1	 	                       _nc_table_insert_type
     32 Bytes    0.0%	1	 	                        malloc
     32 Bytes    0.0%	1	 	                         malloc_zone_malloc
    112 Bytes    0.0%	1	 	                      calloc
    112 Bytes    0.0%	1	 	                       malloc_zone_calloc
     32 Bytes    0.0%	1	 	                      _nc_table_insert_64
     32 Bytes    0.0%	1	 	                       malloc
     32 Bytes    0.0%	1	 	                        malloc_zone_malloc
     80 Bytes    0.0%	1	 	                  _os_log_preferences_refresh_process
     80 Bytes    0.0%	1	 	                   dispatch_once_f
     80 Bytes    0.0%	1	 	                    _dispatch_client_callout
     80 Bytes    0.0%	1	 	                     _objc_msgSend_uncached
     80 Bytes    0.0%	1	 	                      lookUpImpOrForward
     80 Bytes    0.0%	1	 	                       cache_fill
     80 Bytes    0.0%	1	 	                        cache_t::reallocate(unsigned int, unsigned int)
     80 Bytes    0.0%	1	 	                         allocateBuckets(unsigned int)
     80 Bytes    0.0%	1	 	                          calloc
     80 Bytes    0.0%	1	 	                           malloc_zone_calloc
    384 Bytes    0.1%	4	 	                 _os_log_preferences_refresh
    384 Bytes    0.1%	4	 	                  _os_log_preferences_load
    384 Bytes    0.1%	4	 	                   _os_log_preferences_read_file
    384 Bytes    0.1%	4	 	                    xpc_create_from_plist
    304 Bytes    0.1%	3	 	                     dispatch_data_create_with_transform
    224 Bytes    0.0%	2	 	                      -[NSObject release]
    144 Bytes    0.0%	1	 	                       _objc_msgSend_uncached
    144 Bytes    0.0%	1	 	                        lookUpImpOrForward
    144 Bytes    0.0%	1	 	                         cache_fill
    144 Bytes    0.0%	1	 	                          cache_t::reallocate(unsigned int, unsigned int)
    144 Bytes    0.0%	1	 	                           allocateBuckets(unsigned int)
    144 Bytes    0.0%	1	 	                            calloc
    144 Bytes    0.0%	1	 	                             malloc_zone_calloc
     80 Bytes    0.0%	1	 	                       -[OS_dispatch_data dealloc]
     80 Bytes    0.0%	1	 	                        _objc_msgSend_uncached
     80 Bytes    0.0%	1	 	                         lookUpImpOrForward
     80 Bytes    0.0%	1	 	                          cache_fill
     80 Bytes    0.0%	1	 	                           cache_t::reallocate(unsigned int, unsigned int)
     80 Bytes    0.0%	1	 	                            allocateBuckets(unsigned int)
     80 Bytes    0.0%	1	 	                             calloc
     80 Bytes    0.0%	1	 	                              malloc_zone_calloc
     80 Bytes    0.0%	1	 	                      _dispatch_data_subrange_map
     80 Bytes    0.0%	1	 	                       dispatch_data_create_subrange
     80 Bytes    0.0%	1	 	                        _objc_msgSend_uncached
     80 Bytes    0.0%	1	 	                         lookUpImpOrForward
     80 Bytes    0.0%	1	 	                          cache_fill
     80 Bytes    0.0%	1	 	                           cache_t::reallocate(unsigned int, unsigned int)
     80 Bytes    0.0%	1	 	                            allocateBuckets(unsigned int)
     80 Bytes    0.0%	1	 	                             calloc
     80 Bytes    0.0%	1	 	                              malloc_zone_calloc
     80 Bytes    0.0%	1	 	                     _xpc_plist_parse_xml
     80 Bytes    0.0%	1	 	                      _objc_msgSend_uncached
     80 Bytes    0.0%	1	 	                       lookUpImpOrForward
     80 Bytes    0.0%	1	 	                        cache_fill
     80 Bytes    0.0%	1	 	                         cache_t::reallocate(unsigned int, unsigned int)
     80 Bytes    0.0%	1	 	                          allocateBuckets(unsigned int)
     80 Bytes    0.0%	1	 	                           calloc
     80 Bytes    0.0%	1	 	                            malloc_zone_calloc
     80 Bytes    0.0%	1	 	                 _dispatch_barrier_sync_f_invoke
     80 Bytes    0.0%	1	 	                  _dispatch_client_callout
     80 Bytes    0.0%	1	 	                   __os_log_create_block_invoke
     80 Bytes    0.0%	1	 	                    _os_object_alloc_realized
     80 Bytes    0.0%	1	 	                     class_createInstance
     80 Bytes    0.0%	1	 	                      calloc
     80 Bytes    0.0%	1	 	                       malloc_zone_calloc
    960 Bytes    0.3%	3	 	           sa_dst_lookup
    960 Bytes    0.3%	3	 	            malloc
    960 Bytes    0.3%	3	 	             malloc_zone_malloc
    464 Bytes    0.1%	6	 	        search_addrinfo
    464 Bytes    0.1%	6	 	         mdns_addrinfo
    464 Bytes    0.1%	6	 	          _mdns_search
    352 Bytes    0.1%	5	 	           si_inet_config
    352 Bytes    0.1%	5	 	            notify_register_check
    352 Bytes    0.1%	5	 	             client_registration_create
    208 Bytes    0.0%	3	 	              name_node_for_name
    128 Bytes    0.0%	1	 	               calloc
    128 Bytes    0.0%	1	 	                malloc_zone_calloc
     48 Bytes    0.0%	1	 	               strdup
     48 Bytes    0.0%	1	 	                malloc
     48 Bytes    0.0%	1	 	                 malloc_zone_malloc
     32 Bytes    0.0%	1	 	               _nc_table_insert_type
     32 Bytes    0.0%	1	 	                malloc
     32 Bytes    0.0%	1	 	                 malloc_zone_malloc
    112 Bytes    0.0%	1	 	              calloc
    112 Bytes    0.0%	1	 	               malloc_zone_calloc
     32 Bytes    0.0%	1	 	              _nc_table_insert_64
     32 Bytes    0.0%	1	 	               malloc
     32 Bytes    0.0%	1	 	                malloc_zone_malloc
    112 Bytes    0.0%	1	 	           DNSServiceCreateConnection
    112 Bytes    0.0%	1	 	            ConnectToServer
    112 Bytes    0.0%	1	 	             malloc
    112 Bytes    0.0%	1	 	              malloc_zone_malloc
  15.30 KB       5.5%	45	 	       si_module_with_name
  15.30 KB       5.5%	45	 	        si_module_static_search
  15.30 KB       5.5%	45	 	         dispatch_once_f
  15.30 KB       5.5%	45	 	          _dispatch_client_callout
  15.30 KB       5.5%	45	 	           __si_module_static_search_block_invoke
  14.84 KB       5.4%	43	 	            si_module_config_modules_for_category
  14.80 KB       5.4%	41	 	             si_module_with_name
  10.17 KB       3.7%	36	 	              si_module_static_ds
  10.17 KB       3.7%	36	 	               dispatch_once_f
  10.17 KB       3.7%	36	 	                _dispatch_client_callout
  10.17 KB       3.7%	36	 	                 __si_module_static_ds_block_invoke
  10.14 KB       3.7%	34	 	                  notify_register_check
   4.03 KB       1.4%	4	 	                   _os_alloc_once
   4.03 KB       1.4%	4	 	                    _os_once
   4.03 KB       1.4%	4	 	                     _notify_init_globals
   4.03 KB       1.4%	4	 	                      _nc_table_new
   4.00 KB       1.4%	2	 	                       calloc
   4.00 KB       1.4%	2	 	                        malloc_zone_calloc
     32 Bytes    0.0%	2	 	                       malloc
     32 Bytes    0.0%	2	 	                        malloc_zone_malloc
   4.00 KB       1.4%	1	 	                   mmap
   1.44 KB       0.5%	20	 	                   client_registration_create
    896 Bytes    0.3%	12	 	                    name_node_for_name
    512 Bytes    0.1%	4	 	                     calloc
    512 Bytes    0.1%	4	 	                      malloc_zone_calloc
    256 Bytes    0.0%	4	 	                     strdup
    256 Bytes    0.0%	4	 	                      malloc
    256 Bytes    0.0%	4	 	                       malloc_zone_malloc
    128 Bytes    0.0%	4	 	                     _nc_table_insert_type
    128 Bytes    0.0%	4	 	                      malloc
    128 Bytes    0.0%	4	 	                       malloc_zone_malloc
    448 Bytes    0.1%	4	 	                    calloc
    448 Bytes    0.1%	4	 	                     malloc_zone_calloc
    128 Bytes    0.0%	4	 	                    _nc_table_insert_64
    128 Bytes    0.0%	4	 	                     malloc
    128 Bytes    0.0%	4	 	                      malloc_zone_malloc
    688 Bytes    0.2%	9	 	                   _notify_lib_init
    688 Bytes    0.2%	9	 	                    dispatch_once_f
    688 Bytes    0.2%	9	 	                     _dispatch_client_callout
    688 Bytes    0.2%	9	 	                      ___notify_lib_init_block_invoke
    688 Bytes    0.2%	9	 	                       bootstrap_look_up2
    688 Bytes    0.2%	9	 	                        bootstrap_look_up3
    400 Bytes    0.1%	5	 	                         _xpc_dispose
    400 Bytes    0.1%	5	 	                          _xpc_dictionary_dispose
    400 Bytes    0.1%	5	 	                           _xpc_dictionary_node_free
    400 Bytes    0.1%	5	 	                            _objc_msgSend_uncached
    400 Bytes    0.1%	5	 	                             lookUpImpOrForward
    400 Bytes    0.1%	5	 	                              cache_fill
    400 Bytes    0.1%	5	 	                               cache_t::reallocate(unsigned int, unsigned int)
    400 Bytes    0.1%	5	 	                                allocateBuckets(unsigned int)
    400 Bytes    0.1%	5	 	                                 calloc
    400 Bytes    0.1%	5	 	                                  malloc_zone_calloc
    208 Bytes    0.0%	3	 	                         _xpc_interface_routine
    208 Bytes    0.0%	3	 	                          xpc_pipe_routine
     80 Bytes    0.0%	1	 	                           _objc_msgSend_uncached
     80 Bytes    0.0%	1	 	                            lookUpImpOrForward
     80 Bytes    0.0%	1	 	                             cache_fill
     80 Bytes    0.0%	1	 	                              cache_t::reallocate(unsigned int, unsigned int)
     80 Bytes    0.0%	1	 	                               allocateBuckets(unsigned int)
     80 Bytes    0.0%	1	 	                                calloc
     80 Bytes    0.0%	1	 	                                 malloc_zone_calloc
     80 Bytes    0.0%	1	 	                           _xpc_dispose
     80 Bytes    0.0%	1	 	                            _xpc_serializer_dispose
     80 Bytes    0.0%	1	 	                             _objc_msgSend_uncached
     80 Bytes    0.0%	1	 	                              lookUpImpOrForward
     80 Bytes    0.0%	1	 	                               cache_fill
     80 Bytes    0.0%	1	 	                                cache_t::reallocate(unsigned int, unsigned int)
     80 Bytes    0.0%	1	 	                                 allocateBuckets(unsigned int)
     80 Bytes    0.0%	1	 	                                  calloc
     80 Bytes    0.0%	1	 	                                   malloc_zone_calloc
     48 Bytes    0.0%	1	 	                           object_dispose
     48 Bytes    0.0%	1	 	                            objc_destructInstance
     48 Bytes    0.0%	1	 	                             _object_remove_assocations
     48 Bytes    0.0%	1	 	                              malloc
     48 Bytes    0.0%	1	 	                               malloc_zone_malloc
     80 Bytes    0.0%	1	 	                         _objc_msgSend_uncached
     80 Bytes    0.0%	1	 	                          lookUpImpOrForward
     80 Bytes    0.0%	1	 	                           cache_fill
     80 Bytes    0.0%	1	 	                            cache_t::reallocate(unsigned int, unsigned int)
     80 Bytes    0.0%	1	 	                             allocateBuckets(unsigned int)
     80 Bytes    0.0%	1	 	                              calloc
     80 Bytes    0.0%	1	 	                               malloc_zone_calloc
     16 Bytes    0.0%	1	 	                  calloc
     16 Bytes    0.0%	1	 	                   malloc_zone_calloc
     16 Bytes    0.0%	1	 	                  strdup
     16 Bytes    0.0%	1	 	                   malloc
     16 Bytes    0.0%	1	 	                    malloc_zone_malloc
   4.52 KB       1.6%	2	 	              si_module_static_cache
   4.52 KB       1.6%	2	 	               dispatch_once_f
   4.52 KB       1.6%	2	 	                _dispatch_client_callout
   4.52 KB       1.6%	2	 	                 __si_module_static_cache_block_invoke
   4.50 KB       1.6%	1	 	                  calloc
   4.50 KB       1.6%	1	 	                   malloc_zone_calloc
     16 Bytes    0.0%	1	 	                  strdup
     16 Bytes    0.0%	1	 	                   malloc
     16 Bytes    0.0%	1	 	                    malloc_zone_malloc
     96 Bytes    0.0%	2	 	              si_module_static_file
     96 Bytes    0.0%	2	 	               dispatch_once_f
     96 Bytes    0.0%	2	 	                _dispatch_client_callout
     96 Bytes    0.0%	2	 	                 __si_module_static_file_block_invoke
     80 Bytes    0.0%	1	 	                  calloc
     80 Bytes    0.0%	1	 	                   malloc_zone_calloc
     16 Bytes    0.0%	1	 	                  strdup
     16 Bytes    0.0%	1	 	                   malloc
     16 Bytes    0.0%	1	 	                    malloc_zone_malloc
     16 Bytes    0.0%	1	 	              si_module_static_mdns
     16 Bytes    0.0%	1	 	               dispatch_once_f
     16 Bytes    0.0%	1	 	                _dispatch_client_callout
     16 Bytes    0.0%	1	 	                 __si_module_static_mdns_block_invoke
     16 Bytes    0.0%	1	 	                  strdup
     16 Bytes    0.0%	1	 	                   malloc
     16 Bytes    0.0%	1	 	                    malloc_zone_malloc
     48 Bytes    0.0%	2	 	             calloc
     48 Bytes    0.0%	2	 	              malloc_zone_calloc
    448 Bytes    0.1%	1	 	            calloc
    448 Bytes    0.1%	1	 	             malloc_zone_calloc
     16 Bytes    0.0%	1	 	            strdup
     16 Bytes    0.0%	1	 	             malloc
     16 Bytes    0.0%	1	 	              malloc_zone_malloc

**Comment by bnoordhuis** [comment]
It's a bit hard to interpret but it looks like internal bookkeeping not being freed.  What does it look like when you call getaddrinfo() and freeaddrinfo() directly?  For better fidelity, try calling getaddrinfo() from uv_queue_work() so it runs in a separate thread.

**Comment by AaronCAlbers** [comment]
It appears the leak happens in this implementation of getaddrinfo() on Mac OS X Sierra. Any recommendations?

```c
#include <uv.h>
#include <stdio.h>
#include <stdlib.h>

const char* name = "localhost";

int main() {
  struct addrinfo *servinfo;
  int rv;
  
  if ((rv = getaddrinfo(name, "3490", NULL, &servinfo)) != 0) {
    fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(rv));
    exit(1);
  }
  
  freeaddrinfo(servinfo);
  
  return 0;
}
```
![screen shot 2016-10-12 at 1 09 52 pm](https://cloud.githubusercontent.com/assets/20759340/19324178/7ad56068-907d-11e6-96b2-abd8399cf456.png)

**Comment by bnoordhuis** [comment]
If it is a one-time leak, it's probably nothing to worry about.  If it happens on every getaddrinfo() call, your best (and probably only) option is to report it Apple and hope for the best.

Since this is not under libuv's control, I'll go ahead and close the issue.
