### ISSUE TITLE
Cross platform passwd functions

### ISSUE THREAD

**Issue by sindresorhus** [libuv/libuv#11]
Moved from https://github.com/joyent/libuv/issues/468

-

@isaacs said:

> Regarding: joyent/node#2857

> It'd be lovely if there was a way to call a uv_* version of the pwnam family of functions. See man 3 pwnam.

-

This is needed to reliably and quickly get the home directory path. The home directory path is needed by a lot of node modules, but in some environments the `$HOME` environment variable is not defined. This can make all kinds of things fail as most code depend on it being defined. The same applies for getting the username of the current user, which is also currently [slow and convoluted](https://github.com/sindresorhus/username/blob/ee35f7587af541b81bb31340565612080e485b07/index.js).

**Comment by silverwind** [comment]
> Does Windows have a concept of group names or user ids?

From my little research, user group names seem to be the primary key of indexing a user group on Windows, and there's a scarcely-documented part of a [SID](http://pcsupport.about.com/od/termss/g/security-identifier.htm) called the RID (Relative Identifier), which looks to be pretty similar to Unix UIDs (System accounts < 1000, regular users at 1000+).

**Comment by saghul** [comment]
We now have `uv_os_homedir` thanks to @cjihrig. Can we close this now or is anything else wanted? NOte that if you ask for it you are implicitly volunteering to write the code! ;-)

**Comment by cjihrig** [comment]
I'd like to work on a `uv_getlogin()`, since I already have the code mostly written elsewhere.

**Comment by saghul** [comment]
@cjihrig kewl, lets keep it open then!

**Comment by isaacs** [comment]
Just to be clear, the original request is not *just* to get the currently logged-in user's info, but rather to get info about any arbitrary user.

For example, in node-glob, I'd like to be able to expand paths like `~someuser/foo/bar` to `/home/someuser/foo/bar`, or get the uid/gid/groups for a user by name, or get a username by uid, or a group name by gid.

**Comment by sindresorhus** [comment]
I agree with above. These are basic platform primitives that are currently missing from Node. I currently use [`uid-number`](https://github.com/npm/uid-number), but it comes with some overhead. I could also use the `~someuser` expanding for https://github.com/sindresorhus/untildify/issues/1.

**Comment by Pagghiu** [comment]
Hi all, maybe there is a small problem as SHGetKnownFolderPath used by uv_os_homedir is defined only on Windows Vista and successive OS.
https://msdn.microsoft.com/en-us/library/windows/desktop/bb762188%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by saghul** [comment]
@Pagghiu You're right! I guess we need a fallback SHGetFolderPath to with CSIDL_PROFILE.

Refs: https://msdn.microsoft.com/en-us/library/windows/desktop/ee417685%28v=vs.85%29.aspx and https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457%28v=vs.85%29.aspx

**Comment by cjihrig** [comment]
Regarding the ability to look up information for arbitrary users, the challenge is on the Windows side. From my research, it seems like you either need an access token for the user in question, or need to dig through the registry. [Here](https://groups.google.com/d/msg/microsoft.public.win32.programmer.kernel/jyRFoyjfNH0/mspUjI6AfkUJ) is a good explanation. If anyone knows of a simpler/better way to do this on Windows, I'd love to know. I also didn't find a cross platform way for doing this in Python, likely for the same reasons.

**Comment by kthelgason** [comment]
Can this issue be closed now that 217f81b has landed?

**Comment by cjihrig** [comment]
Probably. But, `uv_get_passwd()` only works for the current user. It would be nice to work for arbitrary users, but I ran into some trouble with the Windows implementation.

**Comment by saghul** [comment]
Let's close it with "patches with more enhancements are welcome". There is no better way to start the week than with less issues :-)

**Comment by isaacs** [comment]
Is it worth opening a new issue to do this for arbitrary users, or is that a `WONTFIX` feature?

I get asked occasionally to support `~username/some/path` in node-glob, and that'd require arbitrary user support.  If we're never going to get it, then I can just say "sorry, not happening".  But if that's worth digging into and supporting eventually, it seems like a new issue?

**Comment by cjihrig** [comment]
I'd love to support arbitrary users.

@piscisaureus or @orangemocha any clue how this would work, or if it is really feasible on Windows?

**Comment by saghul** [comment]
@isaacs FWIW, here is how Python does it on Windows: https://github.com/python/cpython/blob/master/Lib/ntpath.py#L295-L337

I wouldn't mind having this in libuv, on Unix we'd use the pw family of functions.

**Comment by cjihrig** [comment]
@saghul is there an alternative that doesn't rely on environment variables? It looks like that code assumes that all users home directories are in the same place. Can Windows users move their home directories?

**Comment by saghul** [comment]
@cjihrig TBH I have no idea.

**Comment by silverwind** [comment]
> Can Windows users move their home directories?

Yes, that's possible through the registry. To get a certain user's homedir, we would have to obtain the user's SID and then look up the `ProfileImagePath` value in the registry path below and possibly expand things like `%SystemDrive%` in the value:

![](http://www.top-password.com/blog/wp-content/uploads/2015/12/profile-image-path.png)
