### ISSUE TITLE
uv_timer comes 1ms early

### ISSUE THREAD

**Issue by ugiwgh** [libuv/libuv#1105]
I use clock_gettime to get time. 
I set 999ms interval at 1477277026001. But it comes at 1477277026999, 1ms early.

**Comment by txdv** [comment]
just pass 999 + 1

**Comment by ugiwgh** [comment]
Why to pass 999 + 1 ?

**Comment by txdv** [comment]
to come 1ms later

**Comment by ugiwgh** [comment]
That's not a good idea. The 1ms early comes from a test data. There is no theory support.

**Comment by ugiwgh** [comment]
If I set after 999ms to run, it's easly to understand after 1000ms to run. But it's hard to understand after 998ms to run.

**Comment by bnoordhuis** [comment]
Your bug report is rather incomplete.  Can you post:

1. A standalone test case.
2. The output of `uname -a`.
3. The version of libuv that you are using.
4. Everything else that might be relevant.

**Comment by ugiwgh** [comment]
gcc test_uvtimer.c -I /usr/local/Cellar/libuv/1.9.1/include  /usr/local/Cellar/libuv/1.9.1/lib/libuv.a -lpthread -lrt
`include <uv.h>

#include <stdio.h>
#include <sys/types.h>
#include <time.h>

static uv_timer_t g_sched_timer;
static struct timespec time_offset = {0, 0};
int64_t utils_timer_now_ms() {
  struct timespec ts;
  clock_gettime(CLOCK_REALTIME, &ts);
  ts.tv_sec += time_offset.tv_sec;
  ts.tv_nsec += time_offset.tv_nsec;
  return (int64_t)ts.tv_sec * 1000 + (int64_t)ts.tv_nsec / 1000000;
}
static long g_score=0;
static long g_interval=1000;

static void test_uv_timer_cb(uv_timer_t *timer)
{
  static long count=0;
  static long tcount=0;
  int64_t now = utils_timer_now_ms();
  if(g_score>now)count++;
  tcount++;
  printf("test_uv_timer_cb g_score(%ld) - now(%ld) = %ld exit=%ld/%ld(%lf %%)\n",g_score,now,g_score-now,count,tcount,(double)count*100/tcount);
  //Do something
  g_score=((now+g_interval)/g_interval)*g_interval;

  printf("test_uv_timer_cb setting g_score(%ld) - now(%ld) = %ld\n",g_score,now,g_score-now);
  uv_timer_start(timer, test_uv_timer_cb, (uint64_t) g_score - now, 0);
}

// gcc test_uvtimer.c -I /usr/local/Cellar/libuv/1.9.1/include  /usr/local/Cellar/libuv/1.9.1/lib/libuv.a -lpthread -lrt
int main(int argc, char *argv[]) {


  uv_loop_t *loop = uv_default_loop();

  uv_timer_init(loop, &g_sched_timer);

  g_score=utils_timer_now_ms();
  g_score+=1000;
  uv_timer_start(&g_sched_timer, test_uv_timer_cb, 1000, 0);

  int retval = uv_run(loop, UV_RUN_DEFAULT);
  if (retval != 0) {
  } else {
  }

  uv_loop_close(loop);

  return 0;
}
`
uname -a
Linux dev.el6 2.6.32-71.el6.x86_64 #1 SMP Wed Sep 1 01:33:01 EDT 2010 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bnoordhuis** [comment]
I'm a little confused.  `/usr/local/Cellar` suggests OS X + Homebrew but your uname says it's a RHEL6 box.

Regardless, I think you have a bug in your calculations.  Here is a revised test case:
```c
#include <uv.h>
static uint64_t then;
static void timer_cb(uv_timer_t* handle) {
  uv_update_time(handle->loop);
  uint64_t now = uv_now(handle->loop);
  unsigned ms = now - then;
  unsigned slack = ms - 1000;
  then = now;
  uv_timer_start(handle, timer_cb, ms-slack, 0);
  printf("ms=%u slack=%u\n", ms, slack);
} 
int main(void) {
  uv_timer_t timer_handle;
  uv_timer_init(uv_default_loop(), &timer_handle);
  uv_update_time(uv_default_loop());
  then = uv_now(uv_default_loop());
  uv_timer_start(&timer_handle, timer_cb, 1000, 0);
  uv_run(uv_default_loop(), UV_RUN_DEFAULT);
  return 0;
}
```
You may (and probably will) see timer overruns on the order of 10 ms but that is courtesy of your operating system's scheduler, not libuv.  You could try tweaking `prctl(PR_SET_TIMERSLACK)` and the scheduling policy for your program or thread, that's not something libuv does for you.

On reasonably modern linux kernels we might be able to better than we do now by using hrtimers or a timerfd but that isn't portable to other operating systems and it might actually be detrimental to overall performance because of the extra system calls to arm and disarm the timer.

Most applications don't need really high precision - if you are waiting for a socket to time out you don't care if it's a few milliseconds late - so maybe we need a toggle or flag that selects between best performance and best precision.

**Comment by ugiwgh** [comment]
If it comes early, it won't runs function. And thus, it will drop one second data.

**Comment by ugiwgh** [comment]
It's do RHEL6. I just throw it to /usr/local/Cellar.

**Comment by bnoordhuis** [comment]
Ah, okay.  I don't quite understand this though:

> If it comes early, it won't runs function. And thus, it will drop one second data.

Timer overruns are a fact of life; you should expect them and be prepared to deal with them.  Timers firing early however should never happen.  Do you see that with the code I posted?

**Comment by ugiwgh** [comment]
I have just test your code.
ms=1000 slack=0
ms=1000 slack=0
ms=1000 slack=0
ms=1001 slack=1
ms=1000 slack=0
ms=1000 slack=0

**Comment by ugiwgh** [comment]
The os is vmware machine. It's that reason?

**Comment by bnoordhuis** [comment]
That could very well be it.  Virtualization software emulates the system clock.  Maybe it's misconfigured or has a bug.

The fact that you get good numbers with the code I posted is encouraging though.

**Comment by ugiwgh** [comment]
I have use uv_now. And it much more better.

**Comment by bnoordhuis** [comment]
Good.  By the way, you were using CLOCK_REALTIME but that clock may be subject to skew, i.e., it can jump back and forth in time.  Next time you probably want to use CLOCK_MONOTONIC.

I'll go ahead and close out the issue.
