### ISSUE TITLE
When the server is sending a large amount of data to the client, the client is suddenly closed.

### ISSUE THREAD

**Issue by Remainfox** [libuv/libuv#1107]
my program is liking this. 

when server is running, if new  client connect server, the connect_cb  will create a timer to send media data to client on time, but the media data is big , when client closed

the question is appear !  

=====   uv_write error :  ECANCELED - operation cancled  =====

my libuv version is V1.9.1,  i  run pragram on ubuntu 16.04 .

Wrong print information is located in after_write.

how can i solve this problem , thanks for answer

**Comment by bnoordhuis** [comment]
Can you post your question to the libuv mailing list?  We use the issue tracker for tracking bug reports against libuv, not for general support.  Thanks.

**Comment by Remainfox** [comment]
ok
