### ISSUE TITLE
inconsistently between windows and gnu for static lib

### ISSUE THREAD

**Issue by ayuval** [libuv/libuv#1108]
In the uv.h file we have a definition for UV_EXTERN

for windows if we do not define `BUILDING_UV_SHARED` or `USING_UV_SHARED` the result will be 
`define UV_EXTERN /* nothing */`
But...
for `__GNUC__ >= 4`
we will get 
`# define UV_EXTERN __attribute__((visibility("default")))`
so if we want to build a **static lib** for windows and android
for windows there will be no decorators
but for Android
we will use
`__attribute__((visibility("default")))`
and the functions will be exported

**Comment by bnoordhuis** [comment]
Yes, and?

**Comment by ayuval** [comment]
I suggest to make a change to UV_EXTERN definition in uv.h
Add new ifdef UV_STATICLIB

In case the sorce is compiled with the UV_STATICLIB definition
the value of UV_EXTERN for **all** the plafrorm will be
#define UV_EXTERN /* nothing */

I will add the change in the pull requests

the change is backword compatible



This is my suggestain for the new definition for UV_EXTERN
#ifdef UV_STATICLIB
# define UV_EXTERN /* nothing */
#elif defined(_WIN32)
  /* Windows - set up dll import/export decorators. */
# if defined(BUILDING_UV_SHARED)
    /* Building shared library. */
#   define UV_EXTERN __declspec(dllexport)
# elif defined(USING_UV_SHARED)
    /* Using shared library. */
#   define UV_EXTERN __declspec(dllimport)
# else
    /* Building static library. */
#   define UV_EXTERN /* nothing */
# endif
#elif __GNUC__ >= 4
# define UV_EXTERN __attribute__((visibility("default")))
#else
# define UV_EXTERN /* nothing */
#endif

**Comment by ayuval** [comment]
going to add new pull request

**Comment by txdv** [comment]
can you put the code in comments between ``` ```?

**Comment by ayuval** [comment]
not sure i understand what do you mean

**Comment by txdv** [comment]
The difference between:

```c
#tag
```

and

#TAG

**Comment by ayuval** [comment]
done
