### ISSUE TITLE
is it possible to open a pipe only for writes?

### ISSUE THREAD

**Issue by mbroadst** [libuv/libuv#1109]
It would appear that libuv hardcodes's the created stream to read/write, as well as signs up the fd for POLLIN/POLLOUT: https://github.com/libuv/libuv/blob/1a96fe33343f82721ba8bc93adb5a67ddcf70ec4/src/unix/pipe.c#L155

Is this just a limitation, or something nobody ever needed before? :) 

Thanks!

**Comment by txdv** [comment]
I have trouble understanding this question.

**Comment by mbroadst** [comment]
@txdv `uv_pipe_connect` currently calls `uv__stream_open` with `UV_STREAM_READABLE | UV_STREAM_WRITABLE`, and `uv__io_start` with `POLLIN | POLLOUT` in a non-configurable way. Is that because nobody has needed to open the pipe as a "simplex" socket before, or because there are existing limitations that require the pipe be opened duplex like this?

**Comment by txdv** [comment]
Can you elaborate on the advantages on having a simplex socket?

**Comment by bnoordhuis** [comment]
> Is that because nobody has needed to open the pipe as a "simplex" socket before

Yes.  If you have a reasonable use case we can look into it.  Alternatively, if you call socket() + connect() yourself, you can create a uv_poll_t handle with the polling mode you want.
