### ISSUE TITLE
EL5 unsupported due to old libtool

### ISSUE THREAD

**Issue by rvagg** [libuv/libuv#111]
io.js / node compiles fine on EL5 (CentOS5), but something about autoconf in libuv is borking because of an older libtool (not that neither libtool nor autoconf are needed to make io.js compile):

https://jenkins-iojs.nodesource.com/job/libuv+any-pr+multi/nodes=iojs-centos5-64/lastBuild/console

```
autoconf (GNU Autoconf) 2.59
libtoolize (GNU libtool) 1.5.22
```

I'm already pulling in the CERN Software Collections to get the devtoolset-2 colleciton for an updated GCC but it doesn't seem to come along with updated libtool so this is the best I can do without hunting around for an RPM from somewhere else.

It'd be nice if libuv just compiled with vanilla EL5 tools including GCC 4.4, the libtool and autoconf. Surely this is possible and it's just the autogen.sh script that's being overly prescriptive? If this is possible then I'd like to add another Jenkins slave for GCC 4.4 on top of the 4.8 that I'm pulling in from CERN.

**Comment by saghul** [comment]
#113 landed, closing.
