### ISSUE TITLE
Does libuv simultaneous accept has the thundering herd problem on linux?

### ISSUE THREAD

**Issue by shuguoyang** [libuv/libuv#1111]
Does libuv simultaneous accept has the thundering herd problem on linux?  and how can I custom the simultaneous accpet load balance? thanks!

**Comment by bnoordhuis** [comment]
> Does libuv simultaneous accept has the thundering herd problem on linux?

If you add the same listen socket to multiple event loops, yes.

If your kernel is new enough, you can create the file descriptor yourself and set the SO_REUSEPORT socket option on it, then pass it to libuv with `uv_tcp_open()`.

Can you post questions to the mailing list next time?  We use the issue tracker strictly for bug reports.  Thanks.
