### ISSUE TITLE
Ignoring error on pipe cleanup

### ISSUE THREAD

**Issue by rvagg** [libuv/libuv#1115]
This is not something I've actually encountered, I'm mainly interested in the philosophical reasoning behind this, if there is one.

In src/unix/pipe.c:

```c
void uv__pipe_close(uv_pipe_t* handle) {
  if (handle->pipe_fname) {
    /*
     * Unlink the file system entity before closing the file descriptor.
     * Doing it the other way around introduces a race where our process
     * unlinks a socket with the same name that's just been created by
     * another thread or process.
     */
    unlink(handle->pipe_fname);
    uv__free((void*)handle->pipe_fname);
    handle->pipe_fname = NULL;
  }

  uv__stream_close((uv_stream_t*)handle);
}
```

The `unlink` could fail but it's ignored. This is most probably safe to do but such a failure could also be passed back up to the caller to let them know all is not right. Is it ignored because it's too hard to do this or because it's not considered a big deal if the `unlink` fails or is this an oversight?

**Comment by saghul** [comment]
It may mean another process opened the pipe themselves. In addition, we
have no way of reporting this since it happens as part of closing the pipe.

Saúl

**Comment by rvagg** [comment]
thanks!
