### ISSUE TITLE
fs.watch prevents a directory being cleaned on Windows OS

### ISSUE THREAD

**Issue by xsq007** [libuv/libuv#1118]
Use fs.watch  to build a tool to watch files and folder changes.
Now there is  a folder with 2 subfolders and tens of files. 
When I tried to remove the folder by pressing Shift+Delete keys (Windows OS),  the files were removed but the folders still existed.

Someone told me it was related with file locking mechanism on Windows and possibly dependent on libuv.  Wondering if it is possible to clean the folder with only one-time Shift+Delete key press.

My  environment is Windows 10 x64 and Nodejs 6.6.0.
Any suggestions and clues are welcome.

**Comment by txdv** [comment]
stop  watching the dir?

**Comment by xsq007** [comment]
Need to watch file and folder changes continuously,  and even monitor file deletions, so cannot stop watching.

**Comment by saghul** [comment]
This was addressed back in the day in https://github.com/nodejs/node-v0.x-archive/issues/1449, please provide a failing test case and we'll reopen and further investigate.
