### ISSUE TITLE
Pass Windows handles as STDIO to child process.

### ISSUE THREAD

**Issue by moteus** [libuv/libuv#1119]
Now it possible send only file descriptors but not real HANDLE.
My usecase is run `php-cgi` which expect SOCKET as stdin handle
and INVALID_HANDLE_VALUE as stdout/stderr.
Yes in such case you can not use regular IO function to work with such
handle and have to use `send`/`recv`.
For now I use `_open_osfhandle` to wrap HANDLE. But it requires build
libuv and target app with same C runtime. And it does not work if build
with static C runtime.

**Comment by bnoordhuis** [comment]
Can you post a detailed outline of what you think needs to be changed?

**Comment by moteus** [comment]
This is example how to [pass socket to `php-cgi.exe`](https://github.com/deemru/php-cgi-spawner/blob/master/src/php-cgi-spawner.c#L78-L82). So we have SOCKET object and we need just use it as stdio handle. SOCKET is inheritable so we do not need duplicate it but if use some other types may be it require also duplicate it. It needs only if you build libuv with static C runtime. Then there no way use `_open_osfhandle`

PS. This [part of code](https://github.com/libuv/libuv/blob/v1.x/src/win/process-stdio.c#L374) seems useless. Do there need `break`?

**Comment by bnoordhuis** [comment]
What I mean is, can you post a concrete proposal for improving the libuv API?  Keep in mind that if you want to see it land in v1.x, it can't break API or ABI.

> PS. This part of code seems useless. Do there need break?

Yes, that looks like a bug to me.

**Comment by moteus** [comment]
I think about just add one more flag `UV_INHERIT_HANDLE` wich may be same as `UV_INHERIT_FD` for non Windows systems.

**Comment by bnoordhuis** [comment]
I think that is acceptable.  Do you want to open a pull request?

**Comment by sam-github** [comment]
Why not make `UV_INHERIT_FD` do on Windows what it does on non-Windows? Why another flag?

**Comment by bnoordhuis** [comment]
Because that would be a backwards incompatible change.

**Comment by sam-github** [comment]
Ah, right, its a no-op right now on Windows?

If this lands, maybe for the next major the two flags can be made identical.

**Comment by bnoordhuis** [comment]
No, it's not a no-op.  It extracts the underlying HANDLE from a CRT file descriptor.

**Comment by moteus** [comment]
Windows has both `file descriptors` and `HANDLES` and they may have some usage.
E.g. fs 0,1 and 2 is quite safe use to pass current stdio handles because they usially not changed during
execution and all copies of CRT point to same handles. Without this it require calls `GetStdHandle` to get 
this handles. But when you want pass some other handle and safer use HANDLE.

**Comment by saghul** [comment]
I'm closing this since https://github.com/libuv/libuv/pull/1166 will make libuv deal with HANDLEs only.
