### ISSUE TITLE
uv__signal_lock may hang up on linux.

### ISSUE THREAD

**Issue by cynron** [libuv/libuv#112]
`uv__signal_lock` blockingly reads from pipe `uv__signal_lock_pipe`  written by uv__signal_unlock.
so, if we do
 
    $ cat /proc/<pid>/fd/<uv_signal_lock_pipefd[0]>

before `uv__signal_lock` and after `uv__signal_unlock` in some case, then `uv__signal_lock` will hang infinitely on syscall `read`,  unless we write something to `<uv__signal_lock_pipefd[1]>` mannually such as:

    $ echo > /proc/<pid>/fd/<uv_signal_lock_pipefd[1]>

I think maybe we should do something to avoid this issue, because we may do a `cat /proc/<pid>/fd/<uv_signal_lock_pipefd[0]`-like operation unintentionally. I did it several days ago, :(.

@saghul 

Thanks!

**Comment by cynron** [comment]
@saghul  if you think this is insignificant, just ignore and close this issue.

**Comment by saghul** [comment]
@cynron how did you do that "unintentionally"?! If you fiddle with other process fds Bad Things (TM) can happen, and I don't think we can / should do anything about it. Basically you voided the warranty! :-)

@bnoordhuis WDYT?

**Comment by bnoordhuis** [comment]
@cynron What do you propose libuv should do in such cases?  You are manipulating file descriptors that you don't own, that's unambiguously undefined behavior.

**Comment by cynron** [comment]
@saghul  @bnoordhuis You are right, thx.

**Comment by cynron** [comment]
@bnoordhuis Hi, Ben, I have a question, I wonder why not use pthread_mutex_t here? Could you give me an explanation? Thanks.

**Comment by bnoordhuis** [comment]
@cynron uv_tty_reset_mode() is async signal-safe but pthreads mutexes are not.  You can't call pthread_mutex_* functions from inside a signal handler.

**Comment by cynron** [comment]
@bnoordhuis  Gotha, Thank you very much,:-)
