### ISSUE TITLE
getaddrinfo on Windows segfaults when node == service == null

### ISSUE THREAD

**Issue by XeCycle** [libuv/libuv#1122]
[This line](https://github.com/libuv/libuv/blob/v1.x/src/win/getaddrinfo.c#L264) checks the input, and should return an EINVAL if `node == service == null`; [here](https://github.com/libuv/libuv/blob/v1.x/src/win/getaddrinfo.c#L381) we tries to free a possibly allocated buffer, but if we came from that check line, `req->alloc` is very likely uninitialized, and can contain values other than null.

If I am not mistaken, this function does not expect a zeroed-out input request, right?

**Comment by bnoordhuis** [comment]
Looks like a bug to me.  The check should just `return UV_EINVAL` instead of `goto error`.

**Comment by bnoordhuis** [comment]
https://github.com/libuv/libuv/pull/1123
