### ISSUE TITLE
win: uv__loops_remove memory leak

### ISSUE THREAD

**Issue by mad-rain** [libuv/libuv#1125]
Hi.

There is a memory leak in uv__loops_remove, appears when removing last loop from the list.

Execution goes to loop_removed label without freeing uv__loops list.

```
  if (uv__loops_capacity < 4 * UV__LOOPS_CHUNK_SIZE)
    goto loop_removed;
```

Andrew.

**Comment by bnoordhuis** [comment]
I think that's intentional, the idea is to avoid allocating/freeing too much.  Is that a problem for you?

**Comment by mad-rain** [comment]
Thanks for reply. I don't think that memory leak can be intentional. I see it every time when my app exists.  I'm using only one default loop and uv_loop_close is called at the end.

If you check logic of the uv__loops_remove function, you will find out that it doesn't free uv__loops array when no loops are left.

```
WARNING: Visual Leak Detector detected memory leaks!
---------- Block 11323 at 0x042009A8: 68 bytes ----------
  Leak Hash: 0x5F0BAC66, Count: 1, Total 68 bytes
  Call Stack (TID 16900):
    0x77EC0DE0 (File and line number not available): ntdll.dll!RtlAllocateHeap
    d:\th\minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp (359): Server.exe!heap_alloc_dbg_internal + 0x12 bytes
    d:\th\minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp (450): Server.exe!heap_alloc_dbg + 0x15 bytes
    d:\th\minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp (511): Server.exe!_calloc_dbg + 0x15 bytes
    d:\th\minkernel\crts\ucrt\src\appcrt\heap\calloc.cpp (21): Server.exe!calloc + 0x13 bytes
    d:\gdev_svn\gameengine\libuv\src\uv-common.c (90): Server.exe!uv__calloc + 0x10 bytes
    ...\libuv\src\win\core.c (92): Server.exe!uv__loops_init + 0x9 bytes
    ...\libuv\src\win\core.c (203): Server.exe!uv_init
    ...\libuv\src\win\thread.c (65): Server.exe!uv__once_inner + 0x5 bytes
    ...\libuv\src\win\thread.c (87): Server.exe!uv_once + 0xD bytes
    ...\libuv\src\win\core.c (298): Server.exe!uv__once_init + 0xF bytes
    ...\libuv\src\win\core.c (232): Server.exe!uv_loop_init
    ...\libuv\src\uv-common.c (589): Server.exe!uv_default_loop + 0xA bytes

```

Andrew.

**Comment by bnoordhuis** [comment]
Yes, that's the idea: for programs that start one or more loops, do some work, close them again, repeat, it would result in unnecessary allocate-free-allocate cycles.  I'm not saying it's a worthwhile optimization per se but that's the motivation behind it.

That's why I asked if it was a problem for you.  Changing the implementation is less compelling when it's because of a tool complaint than when it's because your application comes crashing down for some reason.  That said, you are welcome to file a pull request if it bothers you.
