### ISSUE TITLE
SSIZE_T redefinition is (again?) a problem on win32

### ISSUE THREAD

**Issue by gabrielschulhof** [libuv/libuv#1126]
I'm trying to build an addon on appveyor, and I'm getting the error mentioned in joyent/libuv#702. Node.js version is 6.9.1.

https://ci.appveyor.com/project/gabrielschulhof/iotivity-node/build/1.0.7#L330

**Comment by cjihrig** [comment]
From reading the linked issue, it seems like the reporter fixed the problem by removing a `#define` from their code.

**Comment by gabrielschulhof** [comment]
Aaah, I see that one of the libraries on which I depend has that line in it. I was under the mistaken impression that it was an old version of libuv from which the line had to be removed. Thanks for setting me straight!
