### ISSUE TITLE
uv-win.h should include fcntl.h

### ISSUE THREAD

**Issue by skypjack** [libuv/libuv#1127]
`uv-unix.h` explicitly includes `fcntl.h` and flags like `O_CREAT`, `O_RDWR` and some others are accessible to the users by simply including `uv.h`.
On the other side, `uv-win.h` doesn't include `fcntl.h` and `_O_CREAT`, `_O_RDWR` and the others are not imported. Users must include both `uv.h` **and** `fcntl.h` in their sources.
I'd suggest to explicitly include `fcntl.h` in `uv-win.h` for consistency.

**Comment by santigimeno** [comment]
Fix landed in https://github.com/libuv/libuv/commit/2e5ad25cadd9c12463f4150f04a6e99f40c3f880
