### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by knanu** [libuv/libuv#1128]
It's very annoying that there's no maintained SSL support for libuv. There's tls-evt, but it's buggy and not maintained anymore.

I want to move away from libevent for various reasons, and libuv would be a no-brainer, if it had SSL support.

**Comment by bnoordhuis** [comment]
TLS support was discussed at the summit in Amsterdam last September.  Our position is that we are unlikely to integrate TLS in libuv itself but we are open to hosting external contributions under the libuv umbrella in the https://github.com/libuv/libuv-extras repository.

The problem I see with TLS in libuv core is that we either say "we only support openssl" (or gnutls, or nss, or gskit, or mbedtls, or wolfssl, or...) or we write a leaky abstraction layer.

It's already difficult enough to paper over the differences between openssl, libressl and boringssl that I'm skeptical it would work for libraries without a shared heritage.

libcurl does it but libcurl ruthlessly trades features for interoperability and even then it's mostly about making other libraries look like openssl.

The bar for libuv should be higher: it's not interesting to me personally until it's a mostly drop-in replacement for the tls module in node.js.

**Comment by nuuman** [comment]
> The problem I see with TLS in libuv core is that we either say "we only support openssl" (or gnutls, or nss, or gskit, or mbedtls, or wolfssl, or...) or we write a leaky abstraction layer.

Just my 2 cents: A leaky abstraction layer is a *lot* better than no SSL support.

**Comment by qipeng090** [comment]
polarssl can use

**Comment by nuuman** [comment]
@qipeng090 how? bio's?
