### ISSUE TITLE
Check noatime in uv__make_pipe

### ISSUE THREAD

**Issue by JackDrogon** [libuv/libuv#1132]
In the skip condition， only check nonblocking。 I think that using pipe with atime is high overhead.
So Should libuv  check it in uv__make_pipe?

**Comment by txdv** [comment]
Can you link to the lines of codes you are referring to?

**Comment by JackDrogon** [comment]
Ok. [uv__make_pipe](https://github.com/libuv/libuv/blob/v1.x/src/unix/process.c#L151-L181)。 In the code， not check atime. I find libuv using pipe to passing message in the prcoess, this don't need atime. It's better to set noatime for the pipe.

**Comment by bnoordhuis** [comment]
Are you talking about `fcntl(fd, F_SETFL, O_NOATIME)`?  You will have to convince me with numbers that it makes an actual difference on file descriptors created with pipe2().

**Comment by JackDrogon** [comment]
@bnoordhuis, I didn't test pipe2, I tested pip before a long time. This is the data before on linux kernel 2.6.18-164.el5.  See this [gist](https://gist.github.com/JackDrogon/b9571701c7df15b19311e1f96c94007d).
touch_atime need a bit more time than pipe_writev && pipe_readv.

**Comment by txdv** [comment]
Can't you just call fcntl(fd, F_SETFL, O_NOATIME) on the pipe fd after you created it with libuv? I grepped through the linux kernel for NOATIME and it seems like only ext4 supports it. I feel like this an optimization that the user should do on his own.

**Comment by JackDrogon** [comment]
Pipe's noatime isn't related to fiesystem. It only  depends on os. I think uv__make_pipe should check noatime flag. In uv__make__pipe function, it only checks nonblock. Users maybe set flag to be noatime which is passing to uv__make_pipe, but libuv ignore it. And libuv use pipe as signal locking and uv__async. I think these should be setting to be noatime.

**Comment by bnoordhuis** [comment]
I ran `perf record -c 25000 -e cpu-clock ./a.out 2500000` on your benchmark and did `perf diff` afterwards but I don't see a discernible difference on my 4.7.9-200.fc24.x86_64 system.

I changed your code to call fcntl() on both pipe descriptors but that made no difference.  The with/without O_NOATIME output of `perf stat -r25 ./a.out 2500000` isn't markedly different either.

Maybe there is a atime scalability issue in older kernels that doesn't exist in newer kernels?

**Comment by JackDrogon** [comment]
In the example, most time is wasted on `.text.acpi_processor_idle`. It's about 95.2466%s. I give all the data.
with pipe
```
samples  %        app name                 symbol name
378654   92.7742  vmlinux                  .text.acpi_processor_idle
12978     3.1797  vmlinux                  current_fs_time
2530      0.6199  vmlinux                  thread_return
2345      0.5745  vmlinux                  touch_atime
2253      0.5520  vmlinux                  .text.acpi_safe_halt
1597      0.3913  vmlinux                  timespec_trunc
1368      0.3352  vmlinux                  file_update_time
1253      0.3070  vmlinux                  __mark_inode_dirty
901       0.2208  vmlinux                  pipe_writev
768       0.1882  vmlinux                  __mutex_lock_slowpath
763       0.1869  vmlinux                  try_to_wake_up
270       0.0662  vmlinux                  copy_user_generic_unrolled
254       0.0622  vmlinux                  acpi_set_register
254       0.0622  vmlinux                  system_call
233       0.0571  vmlinux                  pipe_readv
188       0.0461  vmlinux                  dnotify_parent
167       0.0409  vmlinux                  mutex_unlock
```

without atime
```
samples  %        app name                 symbol name
599018   95.2466  vmlinux                  .text.acpi_processor_idle
4140      0.6583  vmlinux                  .text.acpi_safe_halt
3281      0.5217  vmlinux                  thread_return
2812      0.4471  vmlinux                  current_fs_time
2615      0.4158  vmlinux                  file_update_time
1790      0.2846  vmlinux                  __mutex_lock_slowpath
1657      0.2635  vmlinux                  timespec_trunc
1341      0.2132  vmlinux                  try_to_wake_up
1281      0.2037  vmlinux                  mutex_unlock
1080      0.1717  vmlinux                  mutex_lock
1001      0.1592  vmlinux                  pipe_readv
925       0.1471  vmlinux                  pipe_writev
```

There is some difference between them, but is little. I think it's meaningful to optimize， because it's easy to write the releated code and libuv is a  underlying network library that can do more to imporve the performance. I will test it in the new kernel.

**Comment by JackDrogon** [comment]
I use oprofile to profile the difference. @bnoordhuis  You can try to use it to benchmark.
I will use a newer kernel to test it.

**Comment by bnoordhuis** [comment]
@JackDrogon Any luck testing on a newer kernel?

**Comment by bnoordhuis** [comment]
No follow-up.  I'll go ahead and close the issue.
