### ISSUE TITLE
Introduced regression on windows Node.js v7.1.0

### ISSUE THREAD

**Issue by iWuzHere** [libuv/libuv#1135]
My change here https://github.com/libuv/libuv/pull/889 has caused some issues to pop up in node 7.1.0

See https://github.com/nodejs/node/issues/9542

**Comment by cjihrig** [comment]
@bnoordhuis is https://github.com/nodejs/node/issues/9542#issuecomment-259813312 the proper fix for this?

**Comment by iWuzHere** [comment]
Thats a quick fix. sets it to `UV_UNSUPPORTED` so my code is never called.

**Comment by bnoordhuis** [comment]
What @iWuzHere said.  I think we should revert 58ccfd4 for now, do a release, then revisit.

**Comment by digitalinfinity** [comment]
I'm no expert in this codebase, but I took a look at the original commit and also debugged the react-native scenario. What I see is that, in the problematic case, uv_tty_write_bufs is getting called with a buffer whose length is 0. Before #889, this was ok- however, after #889, MultiByteToWideChar is being called with cbMultibyte set to 0 in the problematic case, and it returns an error which cascades down. If I change the guard to the following, everything seems happy again:
`if (uv__vterm_state == UV_SUPPORTED && buf.len > 0) {`

Happy to submit a PR if anyone's interested but as mentioned before, I have very little experience with libuv and given the urgency of the change, someone else might be able to get a fix out quicker.

cc @joaocgreis @joshgav

**Comment by digitalinfinity** [comment]
On second thoughts, decided to learn how to contribute to libuv- opened #1139- please let me know if I made any mistakes

**Comment by bnoordhuis** [comment]
The discussion in https://github.com/nodejs/node/issues/9542 suggests there is still a regressions so I'm reopening the issue.  I've updated the revert in #1138 to include the changes from #1139.

**Comment by cjihrig** [comment]
Closed in #1138 by https://github.com/libuv/libuv/commit/8cbabaa81709562de68bcac0554e4e7af2f72cf6.
