### ISSUE TITLE
uv.errname crashing on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by kayakyakr** [libuv/libuv#1137]
Trying to use node on WSL, aka Bash on Windows, specifically with the ember-cli. I'm receiving an exception in net.js which is not surprising considering that Windows hasn't implemented all of the subsystem calls.

The issue is that libuv seems to be crashing when it goes to look up the error code being thrown by net.js. Here is the error:

```
util.js:1018
  var errname = uv.errname(err);
                   ^

Error: err >= 0
    at Object.exports._errnoException (util.js:1018:20)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

This occurs in node 4, 6, and 7 across a bunch of minor versions. Please offer any suggestions you may have on how I can debug the issue. I'm unfortunately not familiar with the operation of libuv.

**Comment by bnoordhuis** [comment]
Can you use `node debug` to check what the value of `err` is at the time of the exception?

**Comment by kayakyakr** [comment]
@bnoordhuis I'm not familiar with node's debug. I can launch into the debugger, but can't seem to attach it to the right line of code deep in node's native execution. 

```
setBreakpoint('??/??/util.js', 1018)
```

None of the combinations I can think of work. I would have to rebuild node to set a debugger statement in there and I'm not really set up to rebuild node right now.

**Comment by kayakyakr** [comment]
Looks like the call for node 8.0.0 pre (node master) gives more information.  

`Error: connect Unknown system error -32767 /usr/local/var/run/watchman/kayakyakr-state/sock`

But that's a good enough improvement: it no longer crashes and tells what is going wrong.
