### ISSUE TITLE
Public key for signing libuv-v1.10.0.tar.gz file?

### ISSUE THREAD

**Issue by Qantas94Heavy** [libuv/libuv#1140]
Hi, I've followed the steps in [MAINTAINERS.md](https://github.com/libuv/libuv/blob/v1.x/MAINTAINERS.md) in order to try and verify "libuv-v1.10.0.tar.gz", including importing all of the keys listed by using the git blobs, but can't seem to find one that matches "RSA key FF47D5E4AD8B4FDC", which is what is show using the command `gpg --verify libuv-v1.10.0.tar.gz.sign`. Was one of the keys listed the one used to sign the package, and if so, which one? Thanks!

**Comment by cjihrig** [comment]
That was me. I have two keys, and apparently used the wrong one. I'll update the MAINTAINERS file.
