### ISSUE TITLE
Does libuv receive multicast packets from local network without subscription?

### ISSUE THREAD

**Issue by sledgeh** [libuv/libuv#1145]
We know: in flat network every packet is send to all ETH ports. So multicast packets could be received without subscription. Does libuv operate with them?
How can I know target address of UDP packet if it is multicast?

**Comment by bnoordhuis** [comment]
Can you post questions to the mailing list?  We reserve the bug tracker for, well, bugs.  Thanks.

**Comment by sledgeh** [comment]
Here is the best place to place questions. Somebody will find your answer with search engine. Mailing list are for 90s.

**Comment by bnoordhuis** [comment]
Either use the mailing list or don't but please don't comment in this issue again.  Next time I'll simply lock the conversation and block you from posting here.
