### ISSUE TITLE
Get notified when all polls have been handled

### ISSUE THREAD

**Issue by alexhultman** [libuv/libuv#1146]
A missing feature I would like to see is the ability to register a callback that gets called after all polls have had their callbacks handled after epoll_wait returned. This is useful when trying to batch multiple ready polls into bursts of broadcasts or anything similar.

Currently I use a timer to simulate a rough equivalent but it has a lot of latency compared to what this feature could offer.

uv_post_poll_cb

**Comment by alexhultman** [comment]
Well, a more general feature would be a "tick callback" - something called right before the loop will block again. That way you know that everything that was ready has been handled. Alternative names can be "sleep callback", "block callback", etc.

**Comment by bnoordhuis** [comment]
Don't uv_prepare_t and uv_check_t handles work for you?

**Comment by alexhultman** [comment]
Oh wow. *facepalm*
