### ISSUE TITLE
uv_poll_close should invalidate the FD immediately

### ISSUE THREAD

**Issue by 1st1** [libuv/libuv#1148]
`uv_stream_close` calls `uv__io_close`, which, in turn, calls `uv__platform_invalidate_fd` which removes the FD from epoll.  So as soon as we close the stream, the underlying FD is removed from epoll.

`uv_poll_close` doesn't call `uv__io_close`, which causes issues like https://github.com/MagicStack/uvloop/issues/61.   In the linked issue, the FD (let's call it `FD{poll}`) that was used with a poll handle, is a duplicate of another FD (let's call it `FD{stream}`) wrapped in a stream.  If we close `FD{poll}` and keep the `FD{stream}` alive, epoll will spit out `EBADF` for `FD{poll}`, because it will try to be removed **after** it's already closed by the caller of `uv_poll_close`.

So I propose to modify `uv_poll_close` to call `uv__io_close` internally, like stream handlers already do.

**Comment by bnoordhuis** [comment]
Do you mean `uv_poll_stop()` rather than `uv_poll_close()`?  I don't think that's an acceptable change.  The contract with the user is that libuv borrows the file descriptor until `uv_poll_stop()` is called, after which ownership returns to the user.

From the documentation:

> The user should not close a file descriptor while it is being polled by an active poll handle. This can cause the handle to report an error, but it might also start polling another socket. However the fd can be safely closed immediately after a call to :c:func:`uv_poll_stop` or :c:func:`uv_close`.

**Comment by moteus** [comment]
I am not sure that uv_poll should close FD. E.g. I use libuv to poll ZeroMQ sockets. To do this ZeroMQ provide some internal descriptor. This is from doc

>The returned file descriptor is intended for use with a poll or similar system call only. Applications must never attempt to read or write data to it directly, neither should they try to close it.

**Comment by saghul** [comment]
Agreed with @bnoordhuis on not actually closing the fd.  `uv__io_close` doesn't close the fd though: https://github.com/libuv/libuv/blob/v1.x/src/unix/core.c#L890-L896  So I think @1st1 is right and we should *forget* about the fd while not closing it.

**Comment by 1st1** [comment]
> The contract with the user is that libuv borrows the file descriptor until uv_poll_stop() is called, after which ownership returns to the user.

> I am not sure that uv_poll should close FD. E.g. I use libuv to poll ZeroMQ sockets. To do this ZeroMQ provide some internal descriptor. This is from doc

I'm not talking about closing the FD. I'm talking about immediately stopping epolling it in `uv_poll_stop` and `uv_poll_close`. The current code in libuv causes bugs/CPU burn if the duped socket is closed **after** calling `uv_poll_close` - this needs to be fixed.

> So I think @1st1 is right and we should forget about the fd while not closing it.

Thanks! I'll make a PR.

**Comment by srikawnth** [comment]
Is this fixed?

**Comment by 1st1** [comment]
I'll update my PR

**Comment by srikawnth** [comment]
Sure.. Please let me know the libuv version once it is fixed.
