### ISSUE TITLE
Support creating symlinks without elevated privileges

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#1157]
https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/

**Comment by jasongin** [comment]
Directory symlinks already can be created without admin privileges on Windows by using the `UV_FS_SYMLINK_JUNCTION` flag with `uv_fs_symlink()`. The Node.js `fs.symlink()` API exposes that functionality using a type of `'junction'`.

Is this request referring to *file* symlinks?

**Comment by saghul** [comment]
@jasongin Yes, this refers to file symlinks.  Ideally we'd always use the flag to do it without elevation, if it's supported, making it transparent to the user.

**Comment by piscisaureus** [comment]
+100

**Comment by bzoz** [comment]
I've made PR for this: https://github.com/libuv/libuv/pull/1346
