### ISSUE TITLE
pthread barrier header not installed on unix'like platform

### ISSUE THREAD

**Issue by debosvi** [libuv/libuv#1159]
Unix dedicated header 'uv-unix.h' needs 'pthread_barrier.h', nut not accessible in '/usr/include'.
It seems that pthread_barrier.h is not installed on unix platform.
Should it be? I think so.

On windows platform (mingw32), no particular issue.

Issue found on v1.10.1 release.

**Comment by saghul** [comment]
What platform are you running on?  Currently that header is installed only on Android, macOS and AIX.

**Comment by debosvi** [comment]
on mingw32, built by vcbuild script

**Comment by saghul** [comment]
Sorry, that is not supported.  On MinGW we support the Makefile.mingw makefile and autotools.
