### ISSUE TITLE
pthread_rwlock_t undefined on unix platform (ubuntu 16.10) with libuv 1.10.1 rebuild

### ISSUE THREAD

**Issue by debosvi** [libuv/libuv#1160]
With simple inclusion of 'uv.h', gcc complains about 'pthread_rwlock_t' type unknown.

In file included from /home/vincent/usr/include/uv.h:62:0,
                 from /home/vincent/bozCommand/comps/libuv/files/test/helloworld.c:3:
/home/vincent/usr/include/uv-unix.h:137:9: error: unknown type name ‘pthread_rwlock_t’
 typedef pthread_rwlock_t uv_rwlock_t;
         ^~~~~~~~~~~~~~~~

**Comment by saghul** [comment]
How are you compiling your application?  Does libuv (and the test suite) compile?

**Comment by debosvi** [comment]
of course my lib is built and installed.
I used autogen and configure (by default) to install on $HOME/usr prefix.
'make check' succeeded without any issues.

/home/vincent/usr/include/uv.h installed header.
/home/vincent/bozCommand/comps/libuv/files/test/helloworld.c is my file to compile.

**Comment by debosvi** [comment]
my platform is ubuntu x64 16.10 with only native compiler gcc.

**Comment by saghul** [comment]
Can you paste your example code and how you're compiling it?  The test suite uses locks, so the problem must be elsewhere.

**Comment by debosvi** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <uv.h>

int main() {
    uv_loop_t *loop = malloc(sizeof(uv_loop_t));
    uv_loop_init(loop);

    printf("Now quitting.\n");
    uv_run(loop, UV_RUN_DEFAULT);

    uv_loop_close(loop);
    free(loop);
    return 0;
}

**Comment by txdv** [comment]
what is the exact command line you are using to compile?

**Comment by debosvi** [comment]
gcc -Wall -Werror -o test main.c

**Comment by debosvi** [comment]
sorry complete command line is
/usr/bin/cc   -I.include/public -I.include -I./comps/fork/files/include -I/usr/include  -Wmissing-prototypes -Wbad-function-cast -Wshadow -Wfloat-equal -Wswitch-default -Wno-unused-result -O0 -ggdb   -std=c99 -Wall -Wextra -Wmissing-declarations -Wwrite-strings -Wunknown-pragmas -Wformat-security -Wstrict-aliasing -Wreturn-type -Wmissing-noreturn -o comps/fork/files/app/child.c.o   -c comps/fork/files/app/child.c

**Comment by saghul** [comment]
You need to have -lpthread.  Or use pkg-config and get the required flags out of the installed pc file.

Closing since it's not a libuv issue.

**Comment by anko** [comment]
For future searchers with the same problem:

`-std=c99` requests strict POSIX compliance; no extensions like `pthread_rwlock_t`.  Use `-std=gnu99` instead.

(Same for `-std=c11`: use `-std=gnu11`.)

**Comment by nicolasnoble** [comment]
This resolution is wrong. If using posix read write locks, which are not a gnu extension, but a late posix addition, the source code (libuv's in this case) is supposed to tell the posix libraries of the minimum version of the posix standard using [features](https://linux.die.net/man/7/feature_test_macros). In this case exactly, since read write locks [have been added in POSIX.1-2001](https://linux.die.net/man/3/pthread_rwlock_init), one would have to do something like this, very early on in libuv's source code, before including any posix header:

```c
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 600
#endif

#if _XOPEN_SOURCE < 600
#undef _XOPEN_SOURCE
#define _XOPEN_SOURCE 600
#endif
```
