### ISSUE TITLE
what's about installing headers with prefix

### ISSUE THREAD

**Issue by debosvi** [libuv/libuv#1161]
Since there are many headers files, what's about using a prefix suc as 'uv'.

for example in C source file,

#include <uv/uv.h>

which is also applicable for all others
#include <uv/tree.h>
#include <uv/uv-win.h>
#include <uv/uv-unix.h>
#include <uv/uv-threadpool.h>

**Comment by saghul** [comment]
I wouldn't oppose such change, but I'd keep the mail file uv.h. The rest of the files can go inside a uv/ folder.  tree.h might be too generic to have without a prefix, for one.

**Comment by saghul** [comment]
@libuv/collaborators WDYT about this for v2?

**Comment by cjihrig** [comment]
> mail file uv.h

Did you mean main file? I'd be ok with it, as long as I could still `#include <uv.h>` to get the whole thing.

**Comment by bnoordhuis** [comment]
Me too post.  Stipulated that `#include "uv.h"` keeps working I'm okay with the proposal.

**Comment by saghul** [comment]
Take a look at #1429

**Comment by cjihrig** [comment]
It looks like this was fixed in https://github.com/libuv/libuv/pull/1429. This should be in libuv 2.0.0. Closing.
