### ISSUE TITLE
FIOCLEX and FIONCLEX undefined building under MSYS2

### ISSUE THREAD

**Issue by charlesUnixPro** [libuv/libuv#1163]
git clone https://github.com/libuv/libuv.git
cd libuv
sh autogen.sh
./configure
make
  CC       src/unix/libuv_la-core.lo
src/unix/core.c: In function ‘uv__cloexec_ioctl’:
src/unix/core.c:542:25: error: ‘FIOCLEX’ undeclared (first use in this function)
     r = ioctl(fd, set ? FIOCLEX : FIONCLEX);
                         ^
src/unix/core.c:542:25: note: each undeclared identifier is reported only once for each function it appears in
src/unix/core.c:542:35: error: ‘FIONCLEX’ undeclared (first use in this function)
     r = ioctl(fd, set ? FIOCLEX : FIONCLEX);
                                   ^
make: *** [Makefile:1962: src/unix/libuv_la-core.lo] Error 1

**Comment by saghul** [comment]
Are you using the MSYS shell of the MinGW shell?

**Comment by charlesUnixPro** [comment]
MSYS.

**Comment by bnoordhuis** [comment]
Can you try this patch?  You'll need to do the autogen+configure+make dance afterwards.
```diff
diff --git a/configure.ac b/configure.ac
index d3787c0..074f00f 100644
--- a/configure.ac
+++ b/configure.ac
@@ -60,8 +60,8 @@ AM_CONDITIONAL([NETBSD],   [AS_CASE([$host_os],[netbsd*],       [true], [false])
 AM_CONDITIONAL([OPENBSD],  [AS_CASE([$host_os],[openbsd*],      [true], [false])])
 AM_CONDITIONAL([OS390],    [AS_CASE([$host_os],[openedition*],  [true], [false])])
 AM_CONDITIONAL([SUNOS],    [AS_CASE([$host_os],[solaris*],      [true], [false])])
-AM_CONDITIONAL([WINNT],    [AS_CASE([$host_os],[mingw*],        [true], [false])])
-AS_CASE([$host_os],[mingw*], [
+AM_CONDITIONAL([WINNT],    [AS_CASE([$host_os],[mingw*|msys*],  [true], [false])])
+AS_CASE([$host_os],[mingw*|msys*], [
     LIBS="$LIBS -lws2_32 -lpsapi -liphlpapi -lshell32 -luserenv -luser32"
 ])
 AC_CHECK_HEADERS([sys/ahafs_evProds.h])
```

**Comment by charlesUnixPro** [comment]
Many errors, starting with:

  CC       src/win/libuv_la-async.lo
In file included from src/win/internal.h:29:0,
                 from src/win/async.c:25:
src/win/winapi.h:4151:6: warning: ISO C90 doesn’t support unnamed structs/unions [-Wpedantic]
     };
      ^
src/win/winapi.h:4157:5: error: unknown type name ‘NTSTATUS’
     NTSTATUS Status;
     ^

Many of the subsequent errors look like they are consequent of NTSTATUS

**Comment by bnoordhuis** [comment]
What is CC?  `make V=1` should tell you.  If it's mingw, does `make -f Makefile.mingw` work?

**Comment by charlesUnixPro** [comment]
make V=1

libtool: compile:  gcc  ....

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/5.3.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-5.3.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 5.3.0 (GCC)

Admin@Admin-PC MSYS ~/libuv
$ make -f Makefile.mingw
cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/fs-poll.o src/fs-poll.c
cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/inet.o src/inet.c
cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/threadpool.o src/threadpool.c
cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/uv-common.o src/uv-common.c
cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/version.o src/version.c
cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/win/async.o src/win/async.c
In file included from src/win/internal.h:29:0,
                 from src/win/async.c:25:
src/win/winapi.h:4154:5: error: unknown type name ‘NTSTATUS’
     NTSTATUS Status;
     ^

**Comment by saghul** [comment]
I don't think we support the MSYS gcc. We do support MinGW (the w64 variant).  Why are you using MSYS gcc?

**Comment by bnoordhuis** [comment]
Does this patch help?
```diff
diff --git a/src/win/winapi.h b/src/win/winapi.h
index 341fcd0..0b87c3f 100644
--- a/src/win/winapi.h
+++ b/src/win/winapi.h
@@ -24,6 +24,9 @@

 #include <windows.h>

+#ifdef __MINGW32__
+#include <ntdef.h>
+#endif

 /*
  * Ntdll headers
```
I'll second what @saghul said that we don't support mingw32 (and therefore msys-gcc) so if this doesn't fix it, you should switch to mingw-w64.

**Comment by charlesUnixPro** [comment]
At some point, some piece of documentation said (or I read it as saying) to use the MSYS shell..

I am a UNIX guy; I know *nothing* about Windows. I don't know the difference between the two shells.

I have a *huge* UNIX application that I would like to get running under windows. It was written with portability in mind; i.e. using libraries like libuv  to isolate the OS specific functions, so this should all be feasible.

I would prefer a MinGW like solution that would allow me to cross-compile on my UNIX build engines; also my experiments with VS make me want to hang myself.

So assume I know nothing about the development environment, and that I will make bad assumptions. and stupid mistakes.

Switched to the mingw shell; prompt is now "Admin@Admin-PC MINGW64 ~/libuv"

Restored to unpatched configure.ac, sysgen, configure, make clean, make yields NTSTATUS undefined.

Applied the first patch, sysgen, configure, make clean, make: same error.

Reverted, applied second patch; "patch" rejects it, I think because the git index is for a unknown (to me) branch; applied the patch manually, sysgen, configure, make clean, make: NTSTATUS still undefined.

-- Charles

**Comment by saghul** [comment]
Hey @charlesUnixPro, let's see if we can sort this out :-)

Yes, you want to use MSYS2, but when compiling stuff you plan on distributing, you want to use the MinGW-w64 toolchain.  It's confusing, I know, but that's the way it is.

I think you are missing the `win32api-headers` package, which you can install with `pacman`.  Install it and let's see if that works.

**Comment by bnoordhuis** [comment]
Also, use `make -f Makefile.mingw` when building with mingw-w64.

**Comment by charlesUnixPro** [comment]
With the second patch, sysgen, configure, make clean -f Makefile.mingw, make -f Makefile.mingw: NTSTATUS undefined.

pacman -Q shows:

msys2-w32api-headers 5.0.0.4732.6172d2f-1

pacman -Ss doesn't show any other w32api headers.

-- Charles

**Comment by charlesUnixPro** [comment]
I suspect the problem is a broken MinGW-64 install -- the installer gave me a lot of grief, and I may very well have busted something, so I think that should wait until the broken installer gets sorted.

So I'm solving this from the other direction. I have successfully built my application (and libuv) on a UNIX box using the MinGW cross-compiling tools, and am perfectly content with not being able to build on Windows if I can do it from UNIX, as Windows makes my eyes bleed.

I copy the .exe over to Windows and run it: fails with "libuv-1.dll" missing. That makes sense; I need to copy the DLL over to the windows box, but I don't know where to copy it to,

-- Charles

**Comment by bnoordhuis** [comment]
Google for "dll load order", there are some good articles out there.  The directory of the .exe is usually a safe bet.

**Comment by charlesUnixPro** [comment]
Copied libuv-1.dll to the cwd...

Operator's console...

```
C:\Users\Admin\Desktop\QuickStart_MR12.6e>dps8.exe  MR12.6e_boot.ini
DPS8/M emulator (git d496e423)
Production build
Please register your system at https://ringzero.wikidot.com/wiki:register
or create the file 'serial.txt' containing the line 'sn: 0'.

DPS8M simulator V4.0-0 Beta
base_system.ini-54> set absi nunits=1
Non-existent device
! was unexpected at this time.
error: sys_cable: invalid switch name <absi>
base_system.ini-1004> cable absi,0,0,032,0
Invalid argument
SUPER_USER deprecated
TRLSB deprecated
TAPE: unit is read only
FNP telnet server port set to 6180
listening to 6180
Debug output to "STDOUT"
Debug output to "STDOUT" at Fri Dec 09 12:00:35 2016
CONSOLE: ALERT
bootload_0: Booting system MR12.6e generated 04/10/16 2159.2 pdt Sun.
2000.6  announce_chwm: 428. pages used of 512. in wired environment.
2000.6  announce_chwm: 706. words used of 1024. in int_unpaged_page_tables.
find_rpv_subsystem: Enter RPV data: M-> [auto-input] rpv a11 ipc 3381 0a

2000.6  load_mst: 946. out of 1048. pages used in disk mst area.
bce (early) 2000.6: M-> [auto-input] bce

Multics Y2K.  System was last shudown/ESD at:
Saturday, April 16, 2016 16:00:20 pst
Current system time is: Friday, December 9, 2016 12:00:40 pst.
Is this correct? M-> [auto-input] yes

The current time is more than the supplied boot_delta hours beyond the
unmounted time recorded in the RPV label.  Is this correct? M-> [auto-input] yes


The current time I'm using is more than 12 hours
after the last shutdown time recorded in the RPV label.
Are you sure this is correct? M-> [auto-input] yes

bce (boot) 1200.6: M-> [auto-input] boot star

Multics MR12.6e - 12/09/16  1201.0 pst Fri
1201.1  Loading FNP d, >system_library_unbundled>site_mcs 7.6c
Received BOOTLOAD command...
1201.1  FNP d loaded successfully


Volumes to be Scavenged:

   rpv    (root)
   root2  (root)
   root3  (root)

Ready
 1201  as   as_init_: Multics MR12.6e; Answering Service 17.0
 1201  as   LOGIN              IO.SysDaemon dmn cord (create)
 1201  as   LOGIN              Backup.SysDaemon dmn bk (create)
 1201  as   LOGIN              IO.SysDaemon dmn prta (create)
 1201  as   LOGIN              Utility.SysDaemon dmn ut (create)
 1201  as   LOGIN              Volume_Dumper.Daemon dmn vinc (create)
 1201  as   LOGIN              Scavenger.SysDaemon dmn scav1 (create)
 1201  as   as_mcs_mpx_: Load signalled for FNP d.
M-> CONSOLE: RELEASED

 1201  cord Enter command:  coordinator, driver, or logout:
-->  cord
 1201  prta Enter command:  coordinator, driver, or logout:
-->  prta
 1201  vinc
 1201  vinc r 12:01 0.687 31
 1201  vinc
-->  vinc
 1201  scav1 Created >system_control_1>scav1.message
 1201  bk
1201.2  scavenger: Begin scavenge of dska_00a by Scavenger.SysDaemon.z
 1201  scav1 Scavenging volume rpv of logical volume root
 1201  bk   r 12:01 0.613 24
 1201  bk
-->  bk
 1201  ut   copy_dump: Attempt to re-copy an invalid dump.
1201.9  scavenger: Scavenge of dska_00a by Scavenger.SysDaemon.z completed.
 1201  scav1 Scavenging volume root2 of logical volume root
1201.9  scavenger: Begin scavenge of dska_00b by Scavenger.SysDaemon.z
1202.6  scavenger: Scavenge of dska_00b by Scavenger.SysDaemon.z completed.
 1202  scav1 Scavenging volume root3 of logical volume root
1202.6  scavenger: Begin scavenge of dska_00c by Scavenger.SysDaemon.z
 1202  as   sc_admin_command_: Utility.SysDaemon.z: delete_old_pdds
 1202  ut   send_admin_command: Execution started ...
 1202  ut   completed.
 1202  ut   monitor_quota: The requested action was not performed.
 1202  ut   The quota of >dumps is 0, a record limit needs to be specified.
 1202  ut
 1202  ut   Records   Left  %    VTOCEs   Left  %   PB/PD  LV Name
 1202  ut
 1202  ut   166172   99898  60   42218   34090  81  pb     root
 1202  ut
 1202  ut   r 12:02 3.428 494
 1202  ut
-->  ut
1202.7  RCP: Attached tapa_00 for Utility.SysDaemon.z
1202.7  RCP: Detached tapa_00 from Utility.SysDaemon.z
1202.7  RCP: Attached rdra for Utility.SysDaemon.z
1202.7  RCP: Detached rdra from Utility.SysDaemon.z
1202.7  RCP: Attached puna for Utility.SysDaemon.z
1202.7  RCP: Detached puna from Utility.SysDaemon.z
1202.7  RCP: Attached prta for Utility.SysDaemon.z
1202.7  RCP: Detached prta from Utility.SysDaemon.z
CONNECT 127.0.0.1
evHandler WILL 3
CONNECT 127.0.0.1 to d.h000
1203.4  scavenger: Scavenge of dska_00c by Scavenger.SysDaemon.z completed.
 1203  as   LOGOUT             Scavenger.SysDaemon.z dmn scav1   1:52 $7.52 (log
o)
 1203  as   LOGIN              Repair.SysAdmin int d.h000 (create)
```

Telneting in:

```
HSLA Port (d.h000,d.h001,d.h002,d.h003,d.h004,d.h005,d.h006,d.h007,d.h008,d.h009,d.h010,d.h011,d.h012,d.h013,d.h014,d.h015,d.h016,d.h017,d.h018,d.h019,d.h020,d.h021,d.h022,d.h023,d.h024,d.h025,d.h026,d.h027,d.h028,d.h029,d.h031)? 
Attached to line d.h000

Multics MR12.6e: Installation and location (Channel d.h000)
Load = 5.0 out of 90.0 units: users = 5, 12/09/16  1209.3 pst Fri
l Repair

Password:
You are protected from preemption.
Repair.SysAdmin logged in 12/09/16  1209.4 pst Fri from ASCII terminal "none".
Last login 12/09/16  1203.6 pst Fri from ASCII terminal "none".

r 12:09 0.534 19

```

It works...

libuv rocks!

Thank you all very much for the help and advice.

-- Charles

**Comment by saghul** [comment]
I'm glad you go it working Charles! Closing this then.

**Comment by charlesUnixPro** [comment]
I scrubbed every trace of MSYS and MinGW from my system and reinstalled MSYS2, carefully following the instructions, and am now able to build.

This issue was apparently caused by an installation error on my part.

-- Charles

**Comment by saghul** [comment]
Good to know! 👍
