### ISSUE TITLE
support destructor in uv_key_create.

### ISSUE THREAD

**Issue by yihuang** [libuv/libuv#1164]
It's useful to cleanup thread local objects.

**Comment by saghul** [comment]
Is this a request? An intention to write the code yourself? An order? IIRC this isn't easy to implement on Windows.

**Comment by yihuang** [comment]
Sorry for the poor info. I'm willing to write the code, it would be quite simple for pthread. I don't know about windows though.

**Comment by saghul** [comment]
Good to hear :-)  Being a cross-platform library, we need support for Windows too before merging.

**Comment by bnoordhuis** [comment]
On Windows, we use TlsAlloc/TlsFree.  I don't think there is a documented way to have per-thread destructors that wouldn't be libuv-specific (i.e., that extends to threads not created by libuv.)

**Comment by yihuang** [comment]
The library pthread-win32 has implemented key destructor, would you consider to use that library for win32?

**Comment by saghul** [comment]
> The library pthread-win32(https://github.com/GerHobbelt/pthread-win32) has implemented key destructor, would you consider to use that library for win32?

I don't think so, it's LGPL licensed:

> Pthreads-win32 is free software, distributed under the GNU Lesser
General Public License (LGPL).

Also, I'm reasonably sure (I just took a quick look) that the only way for destructors to work is if threads were started with that library only similar to what Ben said earlier.

**Comment by yihuang** [comment]
Yes, it's simulated that way like Ben said earlier. I guess I should close this issue, and people can still implement their own destruction if the thread is created by themselves.
