### ISSUE TITLE
about memory manage, alloc_cb and write_cb

### ISSUE THREAD

**Issue by whisper-bye** [libuv/libuv#1169]
My program recorded some logs, I noticed some times that write_cb callback function not very timely, I mean it is not malloc-free-malloc-free repeats, it is malloc-malloc-malloc and after a while free-free-free. sorry for my poor English, I hope I have made it clear.

```
// just write to an other stream immediately,
// for memory-constrained systems memory usage is not optimal
void read_cb(uv_stream_t *stream, ssize_t nread, const uv_buf_t *buf) {
    ...
    write_req_t *write_req = uv_malloc(sizeof (write_req_t));
    write_req->buf = uv_buf_init(buf->base, (unsigned int)nread);
    uv_check(uv_write(&write_req->req, other_stream, &write_req->buf, 1, write_cb));
    ...
}

void write_cb(uv_write_t *req, int status) {
    write_req_t *write_req = (write_req_t *)req;
    uv_free(write_req->buf.base);
    uv_free(write_req);
}
```

**Comment by saghul** [comment]
You seem to be writing a proxy-like application.  If you cannot write as fast as you read then this will happen, you need to deal with the backpreassure.  Writes are queued in libuv if writing inline doesn't work.  If you don't want to queue writes you can use `uv_try_write` to attempt to make a write inline.

PS: Please use the mailing list for questions, we use the GH bug tracker for issues and feature requests, thanks!
