### ISSUE TITLE
Ship releases with generated autoconf* environment

### ISSUE THREAD

**Issue by jbergstroem** [libuv/libuv#117]
Not sure if we discussed this previously, but it'd be good to ship releases with a full autoconf system (something similar to what you'd get while running `make dist`) since it removes a lot of dependencies from the equation on target machines. Here's the minimum list required on FreeBSD 10.1-RELEASE:
```
	libtool: 2.4.2.418
	autoconf: 2.69
	automake: 1.14_1
	m4: 1.4.17_1,1
	perl5: 5.18.4_11
	autoconf-wrapper: 20131203
	automake-wrapper: 20131203
```

**Comment by saghul** [comment]
This pops up every now and then. I'm personally -1 on it. If a user wants to develop an application using libuv an actual development environment is expected IMHO. In addition, autoconf is not the only supported building method, those using GYP don't have this problem. Last, releasing the result of `make dist` would mean we cannot make a release on Windows (not that it's a deal breaker for me, but still).

/cc @bnoordhuis @piscisaureus WDYT?

**Comment by bnoordhuis** [comment]
No strong opinion.  The EUR 64 question is how many people download (or will download) libuv that don't have a development environment set up.

**Comment by jbergstroem** [comment]
Why would `make dist` ruin windows releases? Couldn't we possibly add steps/instructions in the autoconf environment to bundle whatever's needed - similar to how you treat additional files needed in the distfile? I see generating the auto* as good practise and would argue the other way since it only adds benefits by simplifying. Almost all open source built on auto* I've come across follows the same procedure.

**Comment by jbergstroem** [comment]
Ok, so the `make dist` tarball lacks most gyp stuff (as well as files like vcbuild.bat) - but that's easily added. libuv-1.2.0.tar.gz generated on a fbsd machine at least built and tested cleanly on os x through auto*, next step is getting gyp working and finally vc. Would you accept a patch against auto* that at least allows for this?

**Comment by saghul** [comment]
> Why would make dist ruin windows releases?

You misunderstood me. My point is that if we depend on `make dist` for making releases, it becomes more difficult to do so on Windows. The person making such releases would need to have a proper MinGW environment, which is not the case today.

I need to think about this some more.

**Comment by jbergstroem** [comment]
@saghul Gotcha. I personally prefer automating releases and `make dist` fits neatly into that. Not saying that argument shouldn't hold for Windows as well, but it always feels like the exception to a rule rather than the default. I guess that if your release manager is on Windows only (which this script mainly would serve) it'd be a less attractive option.

**Comment by saghul** [comment]
@jbergstroem we currently have automated releases, but use `git archive` for that: https://github.com/libuv/libuv-release-tool/blob/master/release.js#L366

Windows is a first class citizen in libuv, so it shouldn't come to a surprise that some developers are on Windows. While not my case (I develop and make the releases on my main Linux box), @piscisaureus can make releases too (and he usually uses Windows), and I'd rather not make it difficult for him or anyone else.

**Comment by jbergstroem** [comment]
@saghul Another way of looking at the "convenience" argument would be comparing the number of users that benefits from a simpler setup/compilation/packaging versus the number of developers being able to create the distributed release. Anyway, it's not really my call :) I think I've made myself clear enough! Appreciate the tone of the discussion.

**Comment by jbergstroem** [comment]
@saghul Come to think of it, you could even automate releases further by having a buildbot bake it for you. I could look into creating a jenkins artifact as a result of `make dist` which is then uploaded to github releases with changelog attached? Shouldn't be too hard.

**Comment by saghul** [comment]
@jbergstroem yes, that could indeed be done. However, the current release process replies on human verification, just in case I guess. See below for another reason why we cannot probably automate all of it.

I'm pretty convinced this is a good thing in the end. Also, making the tarball first puts us one step closer to signing it (we cannot automate that, each core member would have its own key), which would probably also be a problem on Windows anyway.

@piscisaureus would requiring some Unix system to make the build be a huge problem for you?

**Comment by jbergstroem** [comment]
Ping. Still keen on lowering the bar for packagers!

**Comment by saghul** [comment]
I'm going to close this as "wontfix". libuv is packaged for many distros and we haven't heard any problems so far, this just complicates the release process without giving us much in exchange.

**Comment by jbergstroem** [comment]
Not disagreeing but the win is that every system that wants to build this would need less dependencies for the added action of `make dist`.
