### ISSUE TITLE
CTRL_LOGOFF_EVENT and CTRL_SHUTDOWN_EVENT should be mapped to SIGHUP on Windows

### ISSUE THREAD

**Issue by mika-fischer** [libuv/libuv#1174]
The comments in [src/win/signal.c](https://github.com/libuv/libuv/blob/v1.x/src/win/signal.c#L116-L119) say: `These signals are only sent to services. Services have their own notification mechanism, so there's no point in handling these.`

Unfortunately it's not correct that these signals are only sent to services. In fact they are also sent to normal console applications when the user logs out or the system shuts down.

In effect they are very similar to `CTRL_CLOSE_EVENT`, and so it would make sense to also map them to `SIGHUP`.

Also note that they have the same effect of instantly killing the process after returning from the handler. So, just as with `CTRL_CLOSE_EVENT`, the handler needs to call `Sleep(INFINITE)` to keep the process alive and allow the handlers to perform any work. Windows will unconditionally kill the process after some seconds if it does not shut down quickly enough.

**Comment by bzoz** [comment]
SGTM!

**Comment by piscisaureus** [comment]
No objection per se, but according to [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683242(v=vs.85).aspx) (emphasis mine) -

> CTRL_LOGOFF_EVENT 5
> A signal that the system sends to all console processes when a user is logging off. This signal does not indicate which user is logging off, so no assumptions can be made.
> Note that this signal is received only by services. **Interactive applications are terminated at logoff, so they are not present when the system sends this signal**.

> CTRL_SHUTDOWN_EVENT 6
> A signal that the system sends when the system is shutting down. **Interactive applications are not present by the time the system sends this signal, therefore it can be received only be services in this situation**. Services also have their own notification mechanism for shutdown events. For more information, see Handler.
> This signal can also be generated by an application using GenerateConsoleCtrlEvent.

Is msdn wrong here?

**Comment by piscisaureus** [comment]
@mika-fischer ^

**Comment by mika-fischer** [comment]
@piscisaureus Well, the part "received only by services" is demonstrably wrong. You can try for yourself with this [small test](https://gist.github.com/mika-fischer/1c04a29c737ae6d3921921394d598e62). At least on Windows 8.1 and 10 I receive both LOGOFF and SHUTDOWN events.

The part about "interactive applications" might be accurate given a specific meaning for "interactive". See the last remarks of the [SetConsoleCtrlHandler](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686016(v=vs.85).aspx) docs:

> If a console application loads the gdi32.dll or user32.dll library, the HandlerRoutine function that you specify when you call SetConsoleCtrlHandler does not get called for the CTRL_LOGOFF_EVENT and CTRL_SHUTDOWN_EVENT events. The operating system recognizes processes that load gdi32.dll or user32.dll as Windows applications rather than console applications. This behavior also occurs for console applications that do not call functions in gdi32.dll or user32.dll directly, but do call functions such as Shell functions that do in turn call functions in gdi32.dll or user32.dll.

> To receive events when a user signs out or the device shuts down in these circumstances, create a hidden window in your console application, and then handle the WM_QUERYENDSESSION and WM_ENDSESSION window messages that the hidden window receives. You can create a hidden window by calling the CreateWindowEx method with the dwExStyle parameter set to 0.

Depending on whether libuv by itself already pulls in user32.dll, it might even make sense to go the hidden window route in order to be able to get notified about logout...

**Comment by piscisaureus** [comment]
@mika-fischer I don't have a windows box handy at the moment so I can't run the test. But I'll take your word for it that these events are actually received. So, I'm convinced, go ahead and forge a patch.

Two notes though:

* I mapped `CTRL_CLOSE_EVENT` to `SIGHUP` because I considered 'closing the console window' semantically similar to 'closing the controlling terminal'. In the case of logout/reboot, you might want to emulate the signal that various flavours of unix send upon logout/reboot, which is `SIGTERM` I believe.

* The `Sleep(INFINITE)` appears to have the undesirable side effect seems to have the undesirable side effect that a process can no longer gracefully exit - [node.js issue](https://github.com/nodejs/node/issues/10165). If you have a better idea to deal with this, that'd be awesome.

**Comment by mika-fischer** [comment]
@piscisaureus OK, SIGTERM sounds fine as well. I'll see what I can do.

And yes, the `Sleep(INFINITE)` is fine, removing the handler at shutdown was the problem, and that should be fixed now.

**Comment by bzoz** [comment]
After more investigation I've found that "interactive applications" mean apps that import USER32. Libuv imports that lib, from which we are using only `MapVirtualKey` (https://github.com/libuv/libuv/pull/866, function used to setup a call to `WriteConsoleInput`). This means that libuv handler does not receive `CTRL_LOGOFF_EVENT`  nor `CTRL_SHUTDOWN_EVENT`.

AFAIR we do no necessary need `MapVirtualKey` result for that `WriteConsoleInput` to work, but that would require more testing. It also looks like node will link user32 anyway ([deps/openssl/openssl.gypi](https://github.com/nodejs/node/blob/495d688e069f97e8135a877773cd12cb52617e92/deps/openssl/openssl.gypi#L1279)). I also think it would be surprising for users if catching those events worked would depend on compile options. I'm not sure if we should implement that.

**Comment by bzoz** [comment]
I will go ahead and close this issue.

**Comment by mika-fischer** [comment]
@bzoz Ah, that's a bummer... However this means that currently there's no way for a libuv application on Windows to correctly handle a user logging off or shutting down the computer. It will just be killed by Windows. Or am I understanding that wrong?

**Comment by bzoz** [comment]
Not in libuv. For desktop apps you can make a hidden window and detect [WM_ENDSESSION](https://msdn.microsoft.com/en-us/library/windows/desktop/aa376889.aspx), for services there is [different mechanism for that](https://msdn.microsoft.com/en-us/library/windows/desktop/ms685149.aspx).
