### ISSUE TITLE
Feature request: System time change notification

### ISSUE THREAD

**Issue by fhalde** [libuv/libuv#1176]
Will it be great to have a feature wherein our node apps can detect change in system time? I recently came across a `time_change_notify` system call, but it doesn't seem to be available in all linux kernels.

[time change notify](https://lwn.net/Articles/403004/)

**Comment by cjihrig** [comment]
To get into libuv it would likely have to be supported in some fashion on all platforms that we support, including Windows.

**Comment by fhalde** [comment]
@cjihrig makes sense! I don't think such feature is adopted in other os's
closing this issue

**Comment by sam-github** [comment]
I don't even think its adopted by linux, its just a proposal at this point, near as I can tell.

**Comment by jeroenvollenbrock** [comment]
> @cjihrig makes sense! I don't think such feature is adopted in other os's
closing this issue

Actually, Linux was the more difficult platform, Linux and Windows have APIs available, while Linux requires some workarrounds like file watchers or optional packages to be installed like systemd/dbus.
