### ISSUE TITLE
[question] edge or level triggered

### ISSUE THREAD

**Issue by defunctzombie** [libuv/libuv#1177]
Is the interface on linux/osx edge or level triggered?

Looking at the TCP/Stream api I am trying to find a way to be notified when a socket is "ready for reading" and then do a pull based read on however much data can be read at that time. The only interface I see in the docs is a two step, allocate callback and data callback.

**Comment by txdv** [comment]
Are you using uv_poll?

**Comment by defunctzombie** [comment]
Not explicitly, just using the standard uv_run and default loop.

**Comment by saghul** [comment]
@defunctzombie libuv uses level triggering internally.  If you want an interface to that to manually do reads and writes yourself have a look at [the poll handle](http://docs.libuv.org/en/v1.x/poll.html).  Cheers!
