### ISSUE TITLE
support unix domain socket of type SOCK_DGRAM (UDP) ?

### ISSUE THREAD

**Issue by cedarwu** [libuv/libuv#1178]
Unix domain is provided through uv_pipe in libuv, and uv_pipe_t is a subclass of uv_stream_t.
Then how can I implement unix domain socket based on DGRAM(UDP) ?
I found some advise to create the socket manually and pass it to uv_pipe_open. However, when I try this way, uv_pipe_bind return EINVAL. If I bind the socket myself without uv_pipe_bind, then uv_listen return ENOTSUP.
Anyone could give an example ?

**Comment by sam-github** [comment]
Is https://github.com/bnoordhuis/node-unix-dgram/blob/master/src/unix_dgram.cc the example you are looking for?

**Comment by cedarwu** [comment]
Thanks a lot.
The example is exactly what I need~
It comes from nodejs unix dgram module, what a good idea.
