### ISSUE TITLE
uv_fs_event_getpath returns wrong size

### ISSUE THREAD

**Issue by syberrus** [libuv/libuv#1179]
doc says:
int uv_fs_event_getpath(uv_fs_event_t* handle, char* buffer, size_t* size)
Changed in version 1.3.0: the returned length no longer includes the terminating null byte, and the buffer is not null terminated.

however that is not true in case if buffer is not enough:

  if (required_len >= *size) {
    *size = required_len + 1;
    return UV_ENOBUFS;
  }

in that case, length still includes null byte.

If buffer is enough then returned length does not include null byte. some kind of inconsistency :(

  memcpy(buffer, handle->path, required_len);
  *size = required_len;
  buffer[required_len] = '\0';

and note that buffer is still null-terminated in constrast to docs.

**Comment by syberrus** [comment]
the same applies for uv_fs_poll_getpath

**Comment by txdv** [comment]
Do you want to write a fix for this?

**Comment by cjihrig** [comment]
This was discussed in #674 and #690. Probably elsewhere too. I think we settled on null terminating and returning string length on success, and returning buffer size on `UV_ENOBUFS`.
