### ISSUE TITLE
Make a new 1.x release?

### ISSUE THREAD

**Issue by targos** [libuv/libuv#1182]
There are several issues in Node.js waiting for it:
https://github.com/nodejs/node/issues/9464
https://github.com/nodejs/node/issues/9690

**Comment by cjihrig** [comment]
@libuv/collaborators thoughts? I can do it tomorrow if no one opposes.

**Comment by bnoordhuis** [comment]
Positively charged.

(That is, +1.)

**Comment by santigimeno** [comment]
+1

**Comment by cjihrig** [comment]
Just released version 1.10.2. PR to Node on the way.

**Comment by cjihrig** [comment]
I'm running into a [problem](https://github.com/libuv/libuv/pull/1073#issuecomment-271381671) on my Mac with the new release, so holding off on updating Node for now.

**Comment by cjihrig** [comment]
I believe this was just an issue with my machine, and have opened a Node PR at https://github.com/nodejs/node/pull/10717.

**Comment by saghul** [comment]
@cjihrig that could be caused by my patch which added using clock_gettime on macOS >= 10.12.  However, it shouldn't have been compiled in your machine which was running 10.11...

**Comment by cjihrig** [comment]
@saghul yea, see my comments on #1073.
