### ISSUE TITLE
make check failed

### ISSUE THREAD

**Issue by Titanarthas** [libuv/libuv#1186]
my os is ubuntu14, i download the last version on github,  do like
$ sh autogen.sh
$ ./configure
$ make
$ make check

failed when make check

ok 279 - threadpool_cancel_getnameinfo
ok 280 - threadpool_cancel_work
ok 281 - threadpool_cancel_fs
ok 282 - threadpool_cancel_single
ok 283 - thread_local_storage
ok 284 - thread_stack_size # SKIP OSX only test
ok 285 - thread_mutex
ok 286 - thread_rwlock
ok 287 - thread_rwlock_trylock
ok 288 - thread_create
ok 289 - thread_equal
ok 290 - dlerror
ok 291 - ip4_addr
ok 292 - ip6_addr_link_local
ok 293 - queue_foreach_delete
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================

**Comment by santigimeno** [comment]
@Titanarthas there's some missing info here. You should see some test failing in the output with the following format: 
```
not ok XXX - test-name
```

**Comment by SzAmmi** [comment]
I compiled libuv on Ubuntu 16 without any problems.

**Comment by txdv** [comment]
can this be closed?

**Comment by bnoordhuis** [comment]
Seeing the OP didn't follow up, I assume it's safe to close.
