### ISSUE TITLE
"You need to install gyp in build/gyp first. See the README." on Linux

### ISSUE THREAD

**Issue by sledgeh** [libuv/libuv#1190]
As I read in `README.md` this is only for Windows. What is the problem, how to fix?

**Comment by sledgeh** [comment]
OK. `gyp` is installed in my system. I don't need local copy. But let's do.
```
$ git clone https://chromium.googlesource.com/external/gyp.git build/gyp
$ ./gyp_uv.py -f ninja
Traceback (most recent call last):
  File "./gyp_uv.py", line 21, in <module>
    import gyp
  File "./build/gyp/pylib/gyp/__init__.py", line 37
    print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
                         ^
SyntaxError: invalid syntax
```
Very bad.

**Comment by bnoordhuis** [comment]
gyp needs python 2, it doesn't work with python 3.  You can use autotools or Makefile.mingw if gyp doesn't work for you.

**Comment by sledgeh** [comment]
Thanks for support. 👎

**Comment by bnoordhuis** [comment]
You're the guy from #1145, aren't you?  If you keep up the negative attitude, just stay away, will you?

**Comment by sledgeh** [comment]
I believe can configure system to use python2. Thank you for idea.
You marked issue as invalid but it is not. Problem touches `libuv`. And I'll provide good answer if 'll find.

Your 1st answer sounds like second "keep away". Is this your usual manner to provide support and help people? Very angry.

I met a problem and need help. If you don't want solve the problem or don't know how to make it work please let others to answer, don't close quickly, don't hurry to mark it as rubbish.

**Comment by bnoordhuis** [comment]
> You marked issue as invalid but it is not.

I tagged it invalid because it's not an issue with libuv itself but with gyp and your local setup.

> Your 1st answer sounds like second "keep away".

I told you what the issue was and how to fix it.  I even gave you a workaround for when python 2 is not an option.  You seem to expect more but we're not a free support hotline.

> I met a problem and need help [...] don't close quickly

I've told you before that the mailing list should be your first go-to resource.  We try to keep a high S/R ratio on this bug tracker and that means closing out reports that aren't actual bugs quickly.

**Comment by sledgeh** [comment]
Understand. I did not know about ratio. Sorry.

**Comment by bnoordhuis** [comment]
No problem.  Glad it's cleared up.

**Comment by sledgeh** [comment]
*May be this can help somebody.* [Here](https://wiki.archlinux.org/index.php/Python#Python_2) described a way how to temporary change **default python version**.  This way should be the same for all `*nix`es.
I tried, but did not use this solution, because I switched to [`CMake`](https://github.com/jen20/libuv-cmake).

**Comment by mianaliasjad** [comment]
i am also facing the same problem.

Any solution?

You need to install gyp in build/gyp first. See the README.

**Comment by bnoordhuis** [comment]
@mianaliasjad we dropped support for gyp back in early 2020.

**Comment by mianaliasjad** [comment]
Hi @bnoordhuis i was rebuilding a project from 2020 that's why i faced this other because back then gyp was used.

Can you guide me then how do i build the libuv for android arm64 now?
