### ISSUE TITLE
uv_fs_event_t API cannot stop without interrupting the watch?

### ISSUE THREAD

**Issue by cheery** [libuv/libuv#1192]
I expose the `watch` in my language like this:

    stream = fs.watch("./")
    for entry in stream
        print(entry.type, entry.path)

This is a nice way to expose the functionality, but it means I have to keep up the items in a queue. The queue starts to fill up if nothing is reading from it. It seems like I cannot stop it when that happens because:

    int uv_fs_event_start(uv_fs_event_t* handle, uv_fs_event_cb cb, const char* path, unsigned int flags)
    int uv_fs_event_stop(uv_fs_event_t* handle)

The source of notifications is selected at the `uv_fs_event_start`, so if I call `uv_fs_event_stop`, by quick glance it'd seem I will be losing file change events that come either before `uv_fs_event_stop` or after it when I call it to wait.

I don't particularly like the idea of keeping a queue here, because the OS and/or libuv already has to keep a queue for the same thing for the same reason.

If you do something for this, correct it in uv_fs_poll_t as well.

**Comment by saghul** [comment]
I'm afraid I don't fully understand your use case.  When you call `uv_fs_event_stop` no further events will be generated, since you asked libuv to stop doing so.

Your API looks nice, but I don't see how you would stop listening for events since you seem to have an infinite iterator over fs events.

I'm going to close this since it's not a libuv issue.  Please use the mailing list for this kind of questions, thanks!

**Comment by bnoordhuis** [comment]
> After all, there's already a queue inside or under the libuv. 

There isn't (and won't be) one in libuv.  If by "under" you mean "the operating system", they don't have an observable queue either.  If you want a backlog of events, you have to do it yourself.

**Comment by saghul** [comment]
> Do you understand how the 'stop' relates to the example now?

I do.  As Ben said there is no queue, so if you want to queue events it's up to your application.  By infinite I meant that the for loop could stall forever if there is no new event.  Stopping and starting the handle is definitely a recipe for loosing events, I suggest you go with your own queuing.
