### ISSUE TITLE
Req : set/get environment variables

### ISSUE THREAD

**Issue by jdonaldson** [libuv/libuv#1198]
Libuv will [check certain environment variable indirectly](http://docs.libuv.org/en/v1.x/misc.html?highlight=environment#c.uv_os_homedir).  It would be great to have ways of setting/getting arbitrary environment variables.

**Comment by cjihrig** [comment]
I was interested in having this before. I forget why I never got around to it. I'd be willing to do the work if this is something we want.

**Comment by saghul** [comment]
I'd be ok with those, as long as we clearly document the multi-threading safety limitations (or not) that apply.

**Comment by txdv** [comment]
Musl and glibc environment variables is simply a pointer to a string called __environ and environ respectively.

glibcs setenv/getenv implementation is thread safe while musls is not. And there are probably many more libcs with their weird semantics ...

**Comment by cjihrig** [comment]
@saghul On non-Windows, should `uv_getenv()` just be a wrapper around `getenv()` (or maybe `secure_getenv()`?), or should we make it more like some of the other uv functions. Maybe `int uv_getenv(char* name, char* buffer, size_t* size)` that copies the string, and returns `UV_ENOENT` if the environment variable is not found. I think the latter would be more compatible with what we'll need to do with `GetEnvironmentVariableW()` on Windows.

**Comment by kroggen** [comment]
Sorry for my lack of knowledge, but why not use `getenv()` on Windows too? It is there for Visual Studio and Mingw. Is it not available on other compilers? Returning a pointer appears to be easier and copy free.
