### ISSUE TITLE
compilation failed - make check failed on MinGW64

### ISSUE THREAD

**Issue by SzAmmi** [libuv/libuv#1200]
Hello (again). I'm using MinGW64.
I want to compile `libuv`, but I don't know why `make check` fails.
```bash
ok 1 ... ok 209
not ok 210 - spawn_reads_child_path
# exit code 3
# Output from process `spawn_reads_child_path`:
# exit_cb
# Assertion failed in test/test-spawn.c on line 68: exit_status == 1
#
# This application has requested the Runtime to terminate it in an unusual way.
# Please contact the application's support team for more information.
ok 211 ... ok 289
FAIL: test/run-tests.exe
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:4190: check-TESTS] Error 1
make[1]: Leaving directory '/c/libuv-1.x'
make: *** [Makefile:4447: check-am] Error 2
```
Full `make check`: http://pastebin.com/F7yS5GTR.

BTW, between `ok 36` and `ok 40` I can hear Windows Foreground sound.

"unusual way" means "crash" IMO

**Comment by SzAmmi** [comment]
IDK why it terminated the process in the "unusual way". I've passed this test on Ubuntu 16 without any problems. Anyone knows how to fix this?

**Comment by SzAmmi** [comment]
"unusual way" means "crash" IMO

**Comment by SzAmmi** [comment]
Where's located the file connected to `test-spawn.c`?

**Comment by saghul** [comment]
I don't know why the test fails.  MinGW is not a tier 1 platform.  We support it, but not all tests pass as you discovered.  That said, it's more often than not a problem in the test, so don't worry too much.  If you feel like fixing it, by all means, go ahead and submit a PR, but I cannot help you pinpoint the issue.

**Comment by SzAmmi** [comment]
Ok, I'll try.

**Comment by SzAmmi** [comment]
On Windows 10 `make check` says:
```
not ok 210 - spawn_reads_child_path
# exit code 3
# Output from process `spawn_reads_child_path`:
# exit_cb
# Assertion failed in test/test-spawn.c on line 68: exit_status == 1
#
# This application has requested the Runtime to terminate it in an unusual way.
# Please contact the application's support team for more information.
```
I'm sure in 99% the code is wrong. Invalid code has undefined behavior.

**Comment by SzAmmi** [comment]
I discovered, the crash is caused by (`test/test-spawn.c` lines `1546-1550`):
```
  r = uv_spawn(uv_default_loop(), &process, &options);
  ASSERT(r == 0);

  r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
  ASSERT(r == 0);
```
Now I'm trying to figure out is it `uv_spawn` or `uv_run`.

**Comment by SzAmmi** [comment]
I just was placing `return 0;` in `TEST_IMPL(spawn_reads_child_path)` line after line to figure out which line is "wrong".

**Comment by SzAmmi** [comment]
Ok, so this line (`1549` in `test-spawn.c`) causes the crash:
```C++
r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
```

**Comment by SzAmmi** [comment]
IDK why func `uv_run` crash the spawn test.

**Comment by SzAmmi** [comment]
I don't think it's `uv_run`, that's probs a bug.

**Comment by SzAmmi** [comment]
I don't understand anything.
```
TEST_IMPL(spawn_reads_child_path) {
  int r;
  int len;
  char file[64];
  char path[1024];
  char* env[3];

  /* Need to carry over the dynamic linker path when the test runner is
   * linked against libuv.so, see https://github.com/libuv/libuv/issues/85.
   */
#if defined(__APPLE__)
  static const char dyld_path_var[] = "DYLD_LIBRARY_PATH";
#elif defined __MVS__
  static const char dyld_path_var[] = "LIBPATH";
#else
  static const char dyld_path_var[] = "LD_LIBRARY_PATH";
#endif

  /* Set up the process, but make sure that the file to run is relative and */
  /* requires a lookup into PATH */
  init_process_options("spawn_helper1", exit_cb);

  /* Set up the PATH env variable */
  for (len = strlen(exepath);
       exepath[len - 1] != '/' && exepath[len - 1] != '\\';
       len--);
  strcpy(file, exepath + len);
  exepath[len] = 0;
  strcpy(path, "PATH=");
  strcpy(path + 5, exepath);

  env[0] = path;
  env[1] = getenv(dyld_path_var);
  env[2] = NULL;

  if (env[1] != NULL) {
    static char buf[1024 + sizeof(dyld_path_var)];
    snprintf(buf, sizeof(buf), "%s=%s", dyld_path_var, env[1]);
    env[1] = buf;
  }

  options.file = file;
  options.args[0] = file;
  options.env = env;

  r = uv_spawn(uv_default_loop(), &process, &options);
  ASSERT(r == 0);

  r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
  ASSERT(r == 0);

  ASSERT(exit_cb_called == 1);
  ASSERT(close_cb_called == 1);

  MAKE_VALGRIND_HAPPY();
  return 0;
}
```
The code above will fail.
```
TEST_IMPL(spawn_reads_child_path) {
  int r;

  r = uv_spawn(uv_default_loop(), &process, &options);
  ASSERT(r == 0);
  r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
  ASSERT(r == 0);
return 0;
}
```
This will fail too.
TEST_IMPL(spawn_reads_child_path) {
  int r;

  r = uv_spawn(uv_default_loop(), &process, &options);
  r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
return 0;
}
This won't fail.
So what's the problem? I can't understand anything.

**Comment by SzAmmi** [comment]
BTW, how I can compile it in another way?

**Comment by saghul** [comment]
Randomly removing lines from the test won't fix it.  If you want to fix it you'll need to take the time and **understand** what the test is trying to do and exactly where it fails.  Sometimes these are obscure, however, maybe so in this case, which deals with paths on Windows.

**Comment by fdopen** [comment]
Your are probably building a dynamic library (libuv-1.dll) and because PATH is overwritten ( https://github.com/libuv/libuv/blob/011e02e3e5bfde5aae662fbc72608fa98122682f/test/test-spawn.c#L1532 ), the dynamic library can't be located by the child process.
If you copy `./.libs/libuv-1.dll` to `./.test/.libs` or `.`, everything should work as expected. Or just build a static library instead of a dynamic one.

**Comment by SzAmmi** [comment]
@saghul You're right. Do you have any docs where the tests are explained? Keywords doesn't say too much. Or maybe there is another way to compile `libuv`?

**Comment by SzAmmi** [comment]
Nevermind. @fdopen, thank you! You just saved me lots of hours! I mean everything works for now. I'm gonna submit a PR tomorrow.
