### ISSUE TITLE
Test failures on Alpine bot in CI

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#1206]
The following tests have been failing consistently in the [alpine bot in the ci](https://ci.nodejs.org/view/libuv/job/libuv-test-commit-linux/nodes=alpine34-x64/):
```
not ok 31 - tty_pty
# exit code 134
# Output from process `tty_pty`:
# Assertion failed in test/test-tty.c on line 369: 0 == uv_tty_init(&loop, &master_tty, master_fd, 0)

not ok 101 - udp_multicast_join6
# exit code 134
# Output from process `udp_multicast_join6`:
# Assertion failed in test/test-udp-multicast-join6.c on line 135: r == 0

not ok 112 - pipe_getsockname_abstract
# exit code 134
# Output from process `pipe_getsockname_abstract`:
# Assertion failed in test/test-pipe-getsockname.c on line 191: memcmp(buf, abstract_pipe, sizeof abstract_pipe) == 0

not ok 192 - poll_bad_fdtype
# exit code 134
# Output from process `poll_bad_fdtype`:
# Assertion failed in test/test-poll.c on line 607: 0 != uv_poll_init(uv_default_loop(), &poll_handle, fd)

not ok 194 - socket_buffer_size
# exit code 134
# Output from process `socket_buffer_size`:
# Assertion failed in test/test-socket-buffer-size.c on line 52: value == 10000 || value == 20000
```
I tried to reproduce the issue in an alpine docker image on a Debian Jessie host with no luck. All the tests passed correctly.

After getting access to the Alpine bot and with the help of @jbergstroem we found out that some syscalls were behaving differently on the docker image than on the bot and that the reason for that could be that the docker image is using the Debian kernel whereas the Alpine bot, that is running on a SmartOS LX Zone, uses whatever kernel it uses, and they behave differently.

As an example: in the `poll_bad_fdtype` test, polling on a directory is not supported on Linux, but apparently is supported on the Alpine running on the SmartOS. To confirm this theory, we started a Debian Jessie instance on a SmartOS zone, and the same tests failed (well, all of them but the `tty_pty`).

In case this explanation is correct, should we do something about it? The options I can think of:
- Do nothing. It's a tier 2 platform so it doesn't have to be run on the CI.
- Ask the nodejs build group to move the bot to some other container platform that behaves correctly.

/cc @libuv/collaborators @libuv/sunos

**Comment by saghul** [comment]
> Ask the nodejs build group to move the bot to some other container platform that behaves correctly.

I'd do this.  Alpine is based on musl so I guess it's a good idea to have it around.

**Comment by imran-iq** [comment]
+1 to moving to another container

**Comment by bnoordhuis** [comment]
Another +1 for moving.  LX Zone is based on an ancient version of KVM, not surprising it's buggy.

**Comment by jbergstroem** [comment]
I'll look at moving it; joyent is the only platform that gives us alpine out of the box :( It'd be pretty awesome if we had a sponsor that gave us the possibility to provide a iso.

**Comment by jbergstroem** [comment]
@geek, @chorrell: Are there any plans of improving the lx zone in smartos?

**Comment by misterdjules** [comment]
@bnoordhuis 

>  LX Zone is based on an ancient version of KVM

LX zones have nothing to do with KVM, they are a fundamentally different approach to virtualization. You might want to do some research about them before making any recommendation in this thread.

@santigimeno @jbergstroem There are bugs in LX, and the LX maintainers usually fix them fairly quickly. I will forward that info to the LX maintainers, and I'll report their assessment of the problem.

**Comment by bnoordhuis** [comment]
Don't get your panties in a bunch.  KVM-based or not, it's still crappy and we have better things to do than chase down bugs in the platform.

@jbergstroem What would you need?  I can probably get IBM to donate some resources.

**Comment by jbergstroem** [comment]
@bnoordhuis can we upload custom install iso's to softlayer? we're hitting limit at our spend there but i reckon two minimal setups would fit.

**Comment by bnoordhuis** [comment]
@mhdawson Do you happen to know the answer to Johan's question?

**Comment by jbergstroem** [comment]
Afaik here's a list of the supported OS'es: http://www.softlayer.com/software. There's this but yeah, I don't think that's going to be a way to get alpine going: https://knowledgelayer.softlayer.com/procedure/import-image

**Comment by mhdawson** [comment]
I also found this https://knowledgelayer.softlayer.com/procedure/mounting-local-iso-ipmi which has some instructions for mounting an iso.  So I'm thinking it would be possible.  However, I'm thinking it might be easier though to use something like ubuntu running docker, I think that was are original plan for alpine.

**Comment by chorrell** [comment]
@jbergstroem Yes, lx-brand is under active development and the engineers are regularly working to improve it. I'll pass on the relevant failures to our engineers to take a look. It's quite possible this was already fixed but the instance being used is on an older platform.

I think, maybe a year ago, you and I had a discussion about whether to use the lx-brand image for libuv testing. I'm pretty sure it was in a PR or issue either under `build` or `LTS` but I can't find it for the life of me. We also chatted on IRC :). It's so long ago that it probably doesn't matter at this point but I expressed some concern about testing libuv under lx-brand since the test would more than likely hit some lx-brand related quirks.

Ultimately the take away was that I was going to produce a KVM (non lx-brand) image that would be available in the Joyent Public Cloud that could be used instead. There's no firm ETA for that, but it's on my roadmap. I think for the short term I would go with what @mhdawson suggests and use Ubuntu + Docker. That seems like the quickest solution and given that one of the main use cases for Alpine is to use it in the docker-node image, I think that works out nicely.

**Comment by jbergstroem** [comment]
@chorrell just checked our logs and yeah; the consensus was that the best scenario was using alpine on baremetal [at joyent]. I will look at expanding our "alpine through docker" testing instead.

**Comment by jbergstroem** [comment]
Also, when we were discussing this was mainly about node where tests basically passed for this specific combo.

**Comment by chorrell** [comment]
That sounds about right.

**Comment by chorrell** [comment]
Also fwiw I spun up an alpine-3 lx-brand instance and ran the tests (per https://github.com/libuv/libuv#running-tests) and I got the same failures except for `31 - tty_pty`. My instance is more than likely on a newer platform (joyent_20161110T013016Z) than the one you have in you CI setup which probably explains why I got `ok 31 - tty_pty`

I'll follow up with our engineers about those failures.

**Comment by chorrell** [comment]
I raised the issue (RE the failing libuv tests on lx-brand) with our engineers. I don't have an ETA or time frame yet as to when they'll be able to dig into this though.

**Comment by txdv** [comment]
Can you describe the setup @chorrell you are using?

**Comment by chorrell** [comment]
I'm using an lx-brand Alpine Linux 3.5 instance (release 20161222) in the Joyent Public Cloud. Specifically, an instance in the us-east-3b DC. That is our "beta" DC that get's updated on a daily basis and will always get the latest patches and updates.

An lx-brand instance is basically a SmartOS container pretending to have a Linux kernel. There are better explanations though:

http://www.slideshare.net/bcantrill/illumos-lx
http://www.slideshare.net/mrbruning/lxbrand

I suspect that the libuv test failures are either a result of a bug in the kernel emulation or the specific tests rely on something that's not supported yet under lx-brand. 

For running the libuv tests I install a bunch of required packages:

```
apk update
apk add build-base git python
```

Then I clone the libuv and gyp repositories and run `./out/Debug/run-tests`:

```
cd /var
git clone https://github.com/libuv/libuv.git
cd libuv/
git clone https://chromium.googlesource.com/external/gyp.git build/gyp

# Run test. Output will be in /var/log/mdata-user-script.log
./gyp_uv.py -f make
make -C out
./out/Debug/run-tests
```

**Comment by txdv** [comment]
O you do work at joyent... is there a possibility to get a box to play around with?

I wrote the socket_buffer_size test and it is failing. My guess is that it just doesn't allow to set a new buffer size or the default maximum settings are smaller than what is being set. However, it is hard for me to debug because I do not have a box running with smartos.

**Comment by saghul** [comment]
@chorrell Thanks for explaining that.  Personally I'd rather have a real Linux kernel under the hood, to rule out any possible emulation layer problem in our CI environment.  That way we can focus on the real problem instead of wondering if there is an issue in the emulation layer.

My 2 cents.

**Comment by jbergstroem** [comment]
For now, docker is the best we can get. The current instance is lacking dependecies so I need to fix that first.

**Comment by chorrell** [comment]
@saghul Yes, that was the same conclusion @jbergstroem and I came to last year (see https://github.com/nodejs/build/pull/476#issuecomment-243144629). 

I think the short term goal is to use docker for the Alpine tests makes the most sense. Eventually you should be able to use a KVM Alpine image once I can make that available. I don't have a timeline for that though. Alpine is pretty different from CentOS, Debian etc, so it looks like I might need to come up with a new build process for it.

**Comment by chorrell** [comment]
@txdv Sure, I can probably work something out. I'm usually on IRC in #node-build (chorrell)

**Comment by saghul** [comment]
@chorrell @jbergstroem Thanks for working on making this better! ❤️

**Comment by bnoordhuis** [comment]
I think this can be closed now that the alpine bot has been removed.
