### ISSUE TITLE
Uninitialized value in debug version make system crash. (Assertion failed: handle->write_queue_size >= req->queued_bytes)

### ISSUE THREAD

**Issue by gzz100** [libuv/libuv#1209]
this crash only happen in Windows debug version.

in win/tcp.c:
```
int uv_tcp_write(uv_loop_t* loop,
                 uv_write_t* req,
                 uv_tcp_t* handle,
                 const uv_buf_t bufs[],
                 unsigned int nbufs,
                 uv_write_cb cb) 
```
 this function  `uv_req_init(loop, (uv_req_t*) req);`  uninitialized `req->u.io.queued_bytes` (in debug version it will be 0xCDCDCDCD, release version is  0x0,so it will not make crash). sometimes after WSASend and before initialized this value. the pGetQueuedCompletionStatusEx will immediately push the the uninitialized request to loop->pending_reqs_tail , it will have assest failed in `uv_process_tcp_write_req` . The probability of triggering this bug is very small. so I suggest add `req->u.io.queued_bytes = 0` in the function  `uv_req_init`

**Comment by bnoordhuis** [comment]
With what version is this?  I ask because I'm not sure I follow.

`uv_tcp_write()` always sets `req->u.io.queued_bytes` after calling `WSASend()`.  How then would it be possible to observe an uninitialized value after a call to GetQueuedCompletionStatusEx?

Are you calling `uv_write()` and `uv_run()` from different threads?

**Comment by gzz100** [comment]
yes, different thread

**Comment by bnoordhuis** [comment]
Right, you can't do that - libuv is not thread-safe.  Use `uv_async_send()` if you need to communicate between threads.

I'll go ahead and close this.
