### ISSUE TITLE
Support for IP_PKTINFO control message

### ISSUE THREAD

**Issue by fcelda** [libuv/libuv#1213]
We are looking into a possibility of adding [`IP_PKTINFO`](http://man7.org/linux/man-pages/man7/ip.7.html) /[`IPV6_PKTINFO`](http://man7.org/linux/man-pages/man7/ipv6.7.html)  control message support into libuv. And I would like to consult this change before writing any code.

### Problem

We have an application that responds on UDP. The listening UDP sockets are bound to `INADDR`/`in6addr_any` because we occasionally need to change IPs without restarting the application. In this setup, the source IP of the outgoing message can be chosen incorrectly as the operating system will take first address valid for the destination route.

This is what `IP_PKTINFO` solves for us. When this socket option is enabled and a datagram is received via `recvmsg()`, the destination address/interface is included in the control message. This control message can be then passed to `sendmsg()` and correct source IP is chosen as a result.

It seems that all supported platforms have similar socket option. I know (and have tested) on Linux, FreeBSD, and macOS.

### Questions

- Will you consider including this features into libuv upstream?
- How do you think the API should look like? Can we do it without changing the API? Or should we add a new variant of receive and send? 

### Other past efforts

I have found some efforts to add this interface, none successful:

- https://groups.google.com/forum/#!topic/libuv/YQBkiHG2bMk (adds new API)
- https://github.com/nodejs/node-v0.x-archive/issues/6589#issuecomment-29289512 (modifies existing API)

**Comment by bnoordhuis** [comment]
It's come up a few times before (as you've seen) but the stumbling block has been cross-platform support.  With that in mind:

> Will you consider including this features into libuv upstream?

Only if if it can be reasonably supported on a majority of supported platforms.  See https://github.com/nodejs/node-v0.x-archive/issues/6589#issuecomment-29287181 - I think that's still the state of things.

cc @libuv/collaborators

**Comment by fcelda** [comment]
> Only if if it can be reasonably supported on a majority of supported platforms. See nodejs/node-v0.x-archive#6589 (comment) - I think that's still the state of things.

I have seen this working reliably on Linux, FreeBSD, and OS X. We enabled this feature in Knot DNS some time ago, and yes - there was [small workaround](https://github.com/CZ-NIC/knot/blob/master/src/knot/server/udp-handler.c#L131-L142) needed for OS X but it works fine to my knowledge. I cannot speak for Windows and Solaris.

So assuming we can make it work on these platforms, how do you think the API should look like?

**Comment by saghul** [comment]
> how do you think the API should look like?

I don't have a proposal in mind ATM, ideally you can come up with something and we can comment on it to reach a point where we are all happy with it.  Some thoughts:

- Consider making this for v2, that lifts the backwards compatible API / stable ABI requirement
- I will request a [LEP](https://github.com/libuv/leps)
- Don't forget about Windows when making your design, it's a fundamentally different beast sometimes

Cheers!

**Comment by fcelda** [comment]
Awesome. Thank you.

**Comment by krisives** [comment]
We need support for this in NodeJS. Anything that gives us the ability to get this information would be good. If the information is not available due to platform issues have those platforms return NULL or throw an error when specifying the option.

**Comment by bnoordhuis** [comment]
@krisives You've seen https://github.com/libuv/libuv/issues/1213#issuecomment-276896697, yes?  If you want to see this happen, that's where you should start.

**Comment by fcelda** [comment]
Hey. I've workaround the missing IP_PKTINFO by implementing custom read/write operations and uv_pool_t as suggested by Saúl in offline conversation. There are some differences in how the control messages are interpreted on Linux and macOS. But once this is understood, it works very well. I don't have a code for Windows though.

I still would like to turn this into abstract libuv interface. I will do my best to find some time ASAP to write a proposal how the API could look like.

**Comment by krisives** [comment]
@fcelda Where is the code for IP_PKTINFO I wanted to check it? Thank you!

**Comment by bmagistro** [comment]
@saghul, was a LEP ever drafted?

Is there an active branch/fork somewhere where this is being developed?

We are in need of this to support a transparent proxy but from a time perspective, we may end up implementing our own solution using poll on a descriptor as an interim solution while we work through the libuv/uvw changes to support in the long term.

**Comment by krisives** [comment]
@bmagistro For what it's worth I ended up writing a C++ solution because of this not being ultimately available on nodejs as well as doing something like what you are talking about with a thin layer to do the ipv6 stuff.

**Comment by bmagistro** [comment]
Thanks for the info.

I took a closer look at IP_PKTINFO the other day and it doesn't quite meet our needs.  For the proxy we will need IP_RECVORIGDSTADDR since we also need to get the original destination port so going to put things on hold and just roll our own for now using poll_t.

**Comment by krisives** [comment]
@bmagistro Just to be clear (mostly for other readers) IP_RECVORIGDSTADDR is for BSD whereas you can get this info using IP_PKTINFO in Linux. On Linux you want to set the socket option IPV6_RECVPKTINFO to 1 then use the CMSG macros to pull out the `cmsg_type == IP_PKTINFO`

I only mention this because the flags and constants are frankly confusing and not amazingly documented, and they vary between platform.

**Comment by hirenp** [comment]
Hi all, this seems like a much needed functionality. @fcelda do you know why is this conversation stalled? Is it 'windows' part? I can test this on FreeBSD/Linux/OSX if that can help moving this forward. @fcelda also, Is it possible for you to share the patch? Thanks!

**Comment by fcelda** [comment]
Thanks for the patience. I'm not bringing any good news. I cannot share the code for uv_pool_t with IP_PKTINFO (IPV6_RECVPKTINFO) as it is, sorry. Also, I didn't get far in turning it into a LEP or patch. The Windows support is huge unknown for me, I didn't find time to research if there is an equivalent interface in Windows and I even don't have environment to test in.

**Comment by nbolyard** [comment]
fcelda wrote:
I have seen this working reliably on Linux, FreeBSD, and OS X. We enabled this feature in Knot DNS some time ago, and yes - there was small workaround needed for OS X but it works fine to my knowledge.

How did you get it to work on MacOSX?
When I do "rc = setsockopt(s, IPPROTO_IP, IP_PKTINFO, &opt, sizeof opt);
with opt being aqn unsigned int containing 1, rc = -1 and errno gets INVALIDARG.

**Comment by fcelda** [comment]
@nbolyard It works for me. It's difficult to tell what's different in your setup with the amount of context you gave. Do you really have IPv4 UDP socket? For IPv6, you need to pass `IPPROTO_IPV6` and `IPV6_RECVPKTINFO` into `setsockopt`.

```c
#include <netinet/in.h>
#include <stdio.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
	int sock = socket(AF_INET, SOCK_DGRAM, 0);
	if (sock < 0) {
		perror("socket");
		return 1;
	}

	int on = 1;
	int ret = setsockopt(sock, IPPROTO_IP, IP_PKTINFO, &on, sizeof(on));
	if (ret != 0) {
		perror("setsockopt");
		close(sock);
		return 1;
	}

	close(sock);

	return 0;
}
```
```
$ gcc -Wall ./pktinfo.c && ./a.out; echo $?
0
$ uname -v
Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
```
