### ISSUE TITLE
Chinese great firewall cause test-tcp-connect-timeout fail

### ISSUE THREAD

**Issue by harmoniouscrab** [libuv/libuv#1219]
test-tcp-connect-timeout.c has a hard coded google dns 8.8.8.8 .  Test passed after I changed this address to a Chinese local dns address. It seems great firewall dns pollution on google dns cause the test failed.

**Comment by bnoordhuis** [comment]
It's a sort-of known issue in that we're aware that hard-coding IP addresses is not a good idea.  I'm afraid I don't know of a good way to fix it, though - we still need a way to test that functionality.

**Comment by saghul** [comment]
Do the OpenDNS servers work there? That's 208.67.222.222 and 208.67.220.220.  I wouldn't mind changing to one of those.
