### ISSUE TITLE
fs.watch crashes process if filename is a shared SharePoint folder

### ISSUE THREAD

**Issue by vladima** [libuv/libuv#1221]
Initially reported as https://github.com/Microsoft/TypeScript/issues/13874
Turned out node crashes if fs.watch is called for a folder which is SharePoint shared folder.

At glance the problem seems to be in `fs-event.c`
- [here](https://github.com/libuv/libuv/blob/v1.x/src/win/fs-event.c#L189-L192) `uv_fs_event_start` sets `handle->dirw` to `pathw`
- then `ReadDIrectoryChangesW` [fails](https://github.com/libuv/libuv/blob/v1.x/src/win/fs-event.c#L258) and error handling logic [here](https://github.com/libuv/libuv/blob/v1.x/src/win/fs-event.c#L296) frees `pathw` making `handle-dirw` point to a released memory.
- as a final step `uv_fs_event_stop` [checks](https://github.com/libuv/libuv/blob/v1.x/src/win/fs-event.c#L338-L341) if `handle->dirw` is not null (which it true) and if yes - tries to free it which fails since it was already freed on the previous step

**Comment by saghul** [comment]
Your logic looks sound 👍 can you send a PR? Thanks!
