### ISSUE TITLE
when uv_pipe_pending_count() returns greater than 1

### ISSUE THREAD

**Issue by williamhong163** [libuv/libuv#1224]
Is it necessary to call uv_pipe_pending_type and uv_accept repeatedly in a loop?

**Comment by txdv** [comment]
Pending type only if you are not sure what type you accepting

**Comment by saghul** [comment]
Yes, the on_connection callback won't be called again unless there is a new connection. Note that connections were already technically accepted, you'd be just building the uv handles for them.

PS: Please use the mailing list for questions.
