### ISSUE TITLE
Support SO_REUSEPORT for tcp on linux?

### ISSUE THREAD

**Issue by cynron** [libuv/libuv#1229]
Socket option SO_REUSEPORT is available for `tcp` on linux  since 3.9,  it  permits multiple tcp/tcp6 sockets created by multiple nodejs processes to be bound to an identical socket address simultaneously. And the kernel will do the load balancing between these sockets.

I think it may be an alternative for `nodejs cluster` in some case which we just want to use multicore capacity. 

Shall we support it in the future?

**Comment by bnoordhuis** [comment]
It's been discussed before, see #386 and #400.  To summarize: libuv doesn't and won't support it explicitly due to cross-platform issues but it makes it easy for you create sockets with the flag set.
