### ISSUE TITLE
hiredis adapters libuv error for help

### ISSUE THREAD

**Issue by zhjzjnb** [libuv/libuv#1232]
Hello everyone.
I'm trying to use libuv to connect redis with hiredis,but there are some differences between macos 10.11.3 and ubuntu 12.04 LTS,if my redis-server is down,when I try to connect redis,the 'ConnectCallback' will work OK in macos,it returns 'connectCallback Error: Connection refused', however in ubuntu it returns nothing.I see the hiredis-libuv-adapters,here is a function 'static void redisLibuvPoll(uv_poll_t* handle, int status, int events)',the 'status' is not 0 in ubuntu, and I can't find why.
ask for help.thanks.
my libuv version is v1.11.0: 2017.02.02, Version 1.11.0 (Stable)
hiredis version is v0.13.3(github:https://github.com/redis/hiredis)

**Comment by bnoordhuis** [comment]
Can you post your question to the libuv mailing list?  We try to keep this bug tracker focused on development of libuv itself.  Thanks.
