### ISSUE TITLE
Enabling / disabling features in libuv

### ISSUE THREAD

**Issue by gaspardpetit** [libuv/libuv#1242]
I would like to compile only a subset of libuv and I see no way to disable parts of it. For instance, I would like to compile libuv without sockets, or without support for external processes. Would it be ok to submit a pull request for macros that enable/disable parts of libuv?

**Comment by txdv** [comment]
libuv is the *socket* part with some other platform independent stuff.

**Comment by gaspardpetit** [comment]
I understand that sockets are a major use case for libuv, but I see libuv as a single-threaded event loop framework and I have a good use case for only using the event loop + async + timers.

**Comment by txdv** [comment]
Can you describe your use case? Sounds like you are using it in an embedded environment?

**Comment by gaspardpetit** [comment]
Indeed - I am porting a windows code base to ios and game consoles (xbox/ps4) where sockets are restricted. I really like the architecture of libuv when it comes to the event loop and the handling of timers and async.  I am making local modifications to isolate and disable parts of libuv for what works on those. I would prefer to share these modifications to make the update process easier on my end later.

**Comment by sam-github** [comment]
A couple of ifdefs won't be as hard to sell as lots of ifdefs and large modifications to the build tooling. Maybe a strawman PR would be helpful to show what you think would work.

**Comment by txdv** [comment]
game consoles and ios devices have actually gigabytes of memory, I personally don't see the benefit of shaving off 200kb off...

**Comment by gaspardpetit** [comment]
You are absolutely right, I am not trying to shave off bytes, it's more an issue of some headers/functions/structures not being available on some platforms. For example, IOs on filesystem are very different on mobiles. Another is the windows port which relies on mswsock.h instead of mswsock2.h which I think is not available on UWP.

**Comment by bnoordhuis** [comment]
Although I don't think it's a completely unreasonable request, I can think of a couple issues that make me lean towards -1: more #ifdefs make code harder to reason about, it would probably bitrot quickly because we don't test such configurations, you'd have to devise something for the soname because a custom build won't be ABI-compatible with a regular build, etc.

Fixes to make it work with UWP are probably much more palatable.

**Comment by gaspardpetit** [comment]
Update on my progress - it turns out being almost impossible to disable specific parts of libuv.  Some files like core.c have utility functions referring to features that are all over the place.  Maybe this should become a suggestion for v2, I think the entities of libuv should be more isolated - more plugin-like.  I'll play in my own branch and see if I can come up with a proposal, but it won't be a simple changelist.

**Comment by saghul** [comment]
@gaspardpetit That sounds reasonable. Please do experiment, and if you come up with something please write a LEP so we can take a look! I'm closing this for now then.

**Comment by ad34** [comment]
@gaspardpetit curious about how goes the integration as I m currently working on a windows project with possible port to ps4 and libuv is used in the project.
