### ISSUE TITLE
libuv Windows CI: Windows server 2016

### ISSUE THREAD

**Issue by kunalspathak** [libuv/libuv#1245]
We would like to add below configuration in `libuv-test-commit-windows`:
* Windows server 2016 with Visual Studio 2015

This covers new SKU of windows with existing supported compiler.

I started a test run for this at https://ci.nodejs.org/job/kunalspathak-libuv-test-commit-windows/2/. Windows server 2016 is good.

**Comment by bnoordhuis** [comment]
Good idea, +1.

**Comment by saghul** [comment]
+1 👍

**Comment by cjihrig** [comment]
@kunalspathak what ever happened with this?

**Comment by kunalspathak** [comment]
I thought it needs more approval. I will add the label and update the issue.

**Comment by cjihrig** [comment]
I think there is enough approval (+1 from me too).

cc @libuv/collaborators in case anyone wants to object.

**Comment by kunalspathak** [comment]
Added `Windows server 2016 with VS2015` machine for `libuv-test-commit-windows` and ran the CI https://ci.nodejs.org/job/libuv-test-commit-windows/331/
It looks good. We can close the issue.

**Comment by cjihrig** [comment]
Awesome. Thanks!
