### ISSUE TITLE
FAIL: test/run-tests.(Install the libuv have an issue that be  print some messages in this repository.) 

### ISSUE THREAD

**Issue by yoeser** [libuv/libuv#1247]
ok 289 - thread_mutex
ok 290 - thread_rwlock
ok 291 - thread_rwlock_trylock
ok 292 - thread_create
ok 293 - thread_equal
ok 294 - dlerror
ok 295 - ip4_addr
ok 296 - ip6_addr_link_local
ok 297 - queue_foreach_delete
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory `/opt/libuv'
make: *** [check-am] Error 2

**Comment by saghul** [comment]
Please paste the test that actually failed. Those you pasted all show as "ok", which means they didn't fail.

**Comment by yoeser** [comment]
Thank you for your help,this problem have been soluted.

At 2017-03-14 15:48:45, "Saúl Ibarra Corretgé" <notifications@github.com> wrote:


Please paste the test that actually failed. Those you pasted all show as "ok", which means they didn't fail.
