### ISSUE TITLE
Please, make dist.libuv.org sorted by date!

### ISSUE THREAD

**Issue by notorand-it** [libuv/libuv#1249]
Please, make http://dist.libuv.org/dist sorted by descending date, so the newer releases are on top of the page.
Now it's sorted by name with no user sorting choice.
But, by doing so v1.11.0 comes before v1.2.0 and after v1.1.0 which makes the search for newer versions rather difficult.

**Comment by bnoordhuis** [comment]
It's nginx's default directory listing.  I don't think it lets you customize it like you want.

**Comment by saghul** [comment]
Maybe we could use https://github.com/aperezdc/ngx-fancyindex (if it's packaged for Ubuntu, that is)

**Comment by notorand-it** [comment]
I see that nginx is not as flexible as Apache:
https://www.nginx.com/resources/wiki/modules/fancy_index/

But in my opinion this is not just "fanciness": the usability of that website would improve greatly!

**Comment by saghul** [comment]
Well, we're not switching web servers, that's for sure :-)


-Saúl

**Comment by notorand-it** [comment]
> Well, we're not switching web servers, that's for sure :-)

Sure, you're not: it'd make no sense as there seems to be an easier solution.
I think it makes sense to have a different file sorting, though.
Or at least a "usual user selectable" as seen in http://www.dm.unipi.it/~carminat/CP2014/

**Comment by bnoordhuis** [comment]
We could put up a static HTML page that is regenerated hourly or so from the git tags.  Wouldn't be hard to write and could run as a cron job but I don't know who actually administers dist.libuv.org.  Is that your machine, Saúl?

**Comment by saghul** [comment]
Nope, it used to be a SmartOS zone, but it's now some ubuntu. You should be able to SSH into it.

How about creating some "latest" symlink as part of the dist process? Coincidentally, it will always be the first entry.


-Saúl

**Comment by bnoordhuis** [comment]
#1251

**Comment by jbergstroem** [comment]
The build group hosts `dist.libuv.org`. Happy to help out. I think the fancy index module is available through `nginx-extras` but I need to do some testing before we start using it (if that's what we would prefer).

**Comment by notorand-it** [comment]
I think the fancy indexing module is the correct solution.
But, of course, I also think it's not up to me to decide.
Whatever solution is better, in my opinion, than the current weird sorting.

**Comment by bnoordhuis** [comment]
I rather like the scripted approach.  It lets us add things like release notes later on.

**Comment by saghul** [comment]
> I rather like the scripted approach. It lets us add things like release notes later on.

Right on!

**Comment by notorand-it** [comment]
Correct! But there will be a delay between updates and any error in the script will produce bad HTML.
But, anything is better than nothing!

**Comment by notorand-it** [comment]
I think this can be done at the configuration level:
https://www.nginx.com/resources/wiki/modules/fancy_index/

Please, do so as it makes more sense.
And in my opinion, you should sort with "date descending" so newer stuff is on top.

**Comment by notorand-it** [comment]
The current situation in the https://dist.libuv.org/dist/ site is really confusing.
Latest version download link (v1.20.0) is buried deep into the list, between v1.2.1 and v1.3.0.
The webserver can do a "fancy indexing" with latest timestamp on top thanks to an [open source module](https://github.com/aperezdc/ngx-fancyindex).
One could even create a symlink called "000LATEST" pointing to the latest file and being displayed at the top.

**Comment by notorand-it** [comment]
Is it just me or the lexicographical sort order is something **confusing** and **useless** in this very case? If it's just me, please comment and close this issue.
If it's not, then please react.
