### ISSUE TITLE
uv__loops_init allocates memory which cannot be freed

### ISSUE THREAD

**Issue by gaspardpetit** [libuv/libuv#1252]
On Windows, changelist https://github.com/libuv/libuv/commit/6fa3524ea7ad8d54ce733a6e7da283701c9c06fc introduced a dynamic allocation to keep track of uv_loops.  Unfortunately, libuv provides no mechanism to free this memory and it causes my unit tests to fail because they detect a memory leak.  

I would like to provide a pull request where either: 

 - uv__loops_remove deallocates the uv__loops structure when the last loop is closed.  Then, of course, when a new loop is created, uv_loop_init should check if the structure is allocated and allocates it if necessary.  There would be a little bit of extra overhead, but considering that creating/closing loops is no something that gets done very often, I don't think it's a concern;
 - alternatively, I would add a uv_loops_cleanup which frees the memory and resets the global variables in such a way that the uv_once will be executed again.  The client application could then explicitly call this function to cleanup libuv.

I believe the first option is more sensible.  Let me know if such pull request would make it to the master branch.

**Comment by bnoordhuis** [comment]
See #1125, a pull request for the first option would be welcome.

**Comment by cjihrig** [comment]
@gaspardpetit does https://github.com/cjihrig/libuv/commit/d9a0c45cea353067f9cb34603add36482a42d974 work for you?

**Comment by gaspardpetit** [comment]
Perfect!
