### ISSUE TITLE
doc: re-license documentation as CC By 4.0

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#1254]
I propose we change the license for the documentation to this: https://creativecommons.org/licenses/by/4.0/

I guess this needs approval from everyone who contributed to docs/, so here it goes, in order of contribution:

@saghul, @cjihrig, @neojski, @orangemocha, @bnoordhuis, @mkrufky, @jgeralnik, @creationix, @wavexx, @almosnow, @txdv, @beevik, @coreyfarrell, @dharesign, @Soarez, @yosuke-furukawa, @MostAwesomeDude, @btrask, @mscdex, @deleisha, @skeggse, @petkaantonov, @jhamhader, @bonifaido, @santigimeno, @Gottox, @imran-iq, @jasongin, @pmderodat, @neevek, @skypjack, @lomew, @baremetalfreak, @vcunat, @alexhultman, @plafer, @danbev, @hhellyer

If someone knows that is not required, please let me know and @libuv/collaborators will make the decision then :-)

If agreement is reached I'll follow up with a PR.

**Comment by txdv** [comment]
You have my sword.

**Comment by plafer** [comment]
And my axe.

**Comment by mkrufky** [comment]
And my Axe!

**Comment by bonifaido** [comment]
Fine by me.

**Comment by baremetalfreak** [comment]
Sure, no problem.


On 16 March 2017 at 13:21:53, Nándor István Krácser (
notifications@github.com) wrote:

Fine by me.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/libuv/libuv/issues/1254#issuecomment-287040710>, or mute
the thread

**Comment by alexhultman** [comment]
I added one line, don't think I have anything to say. I'm neutral

**Comment by neevek** [comment]
And my spear.


-----------------------

Best Regards.

谢佳敏

On Thu, Mar 16, 2017 at 6:44pm, Saúl Ibarra Corretgé < notifications@github.com [notifications@github.com] > wrote:
I propose we change the license for the documentation to this: https://creativecommons.org/licenses/by/4.0/ [https://creativecommons.org/licenses/by/4.0/]

I guess this needs approval from everyone who contributed to docs/, so here it goes, in order of contribution:

@saghul [https://github.com/saghul] , @cjihrig [https://github.com/cjihrig] , @neojski [https://github.com/neojski] , @orangemocha [https://github.com/orangemocha] , @bnoordhuis [https://github.com/bnoordhuis] , @mkrufky [https://github.com/mkrufky] , @jgeralnik [https://github.com/jgeralnik] , @creationix [https://github.com/creationix] , @wavexx [https://github.com/wavexx] , @almosnow [https://github.com/almosnow] , @txdv [https://github.com/txdv] , @beevik [https://github.com/beevik] , @coreyfarrell [https://github.com/coreyfarrell] , @dharesign [https://github.com/dharesign] , @Soarez [https://github.com/Soarez] , @yosuke-furukawa [https://github.com/yosuke-furukawa] , @MostAwesomeDude [https://github.com/MostAwesomeDude] , @btrask [https://github.com/btrask] , @mscdex [https://github.com/mscdex] , @deleisha [https://github.com/deleisha] , @skeggse [https://github.com/skeggse] , @petkaantonov [https://github.com/petkaantonov] , @jhamhader [https://github.com/jhamhader] , @bonifaido [https://github.com/bonifaido] , @santigimeno [https://github.com/santigimeno] , @Gottox [https://github.com/Gottox] , @imran-iq [https://github.com/imran-iq] , @jasongin [https://github.com/jasongin] , @pmderodat [https://github.com/pmderodat] , @neevek [https://github.com/neevek] , @skypjack [https://github.com/skypjack] , @lomew [https://github.com/lomew] , @baremetalfreak [https://github.com/baremetalfreak] , @vcunat [https://github.com/vcunat] , @alexhultman [https://github.com/alexhultman] , @plafer [https://github.com/plafer] , @danbev [https://github.com/danbev] , @hhellyer [https://github.com/hhellyer]

If someone knows that is not required, please let me know and @libuv/collaborators [https://github.com/orgs/libuv/teams/collaborators] will make the decision then :-)

If agreement is reached I'll follow up with a PR.

**Comment by vcunat** [comment]
And all my orcs.  (My contribution was probably too small to need my approval, but I'm no lawyer.)

**Comment by coreyfarrell** [comment]
Fine by me.

**Comment by Gottox** [comment]
Feel free to relicense my contributions.

**Comment by orangemocha** [comment]
Fine by me.

**Comment by creationix** [comment]
Sounds great.

**Comment by Soarez** [comment]
Approval hereby granted

**Comment by alexhultman** [comment]
What happens if someone disagrees or don't respond? Can't you just revert their changes and go from there? That's how I interpret copyright/licenses.

**Comment by skeggse** [comment]
Granted.

**Comment by saghul** [comment]
> What happens if someone disagrees or don't respond? Can't you just revert their changes and go from there? That's how I interpret copyright/licenses.

Yes, that's my understanding too. We would be forced to do that, I guess, but I'm hoping nobody disagrees :-)

**Comment by txdv** [comment]
I'll just add a list in here who already has given approval:

- [X] @saghul
- [ ] @cjihrig
- [ ]  @neojski
- [X] @orangemocha 
- [ ] @bnoordhuis
- [X] @mkrufky 
- [ ] @jgeralnik 
- [X] @creationix 
- [ ] @wavexx 
- [ ] @almosnow 
- [ ] @txdv
- [ ] @beevik 
- [X] @coreyfarrell 
- [ ] @dharesign 
- [X] @Soarez 
- [ ] @yosuke-furukawa 
- [ ] @MostAwesomeDude 
- [ ] @btrask 
- [ ] @mscdex 
- [ ] @deleisha 
- [X] @skeggse 
- [ ] @petkaantonov 
- [ ] @jhamhader 
- [X] @bonifaido 
- [ ] @santigimeno 
- [X] @Gottox 
- [ ] @imran-iq 
- [ ] @jasongin 
- [ ] @pmderodat 
- [X] @neevek 
- [ ] @skypjack 
- [ ] @lomew 
- [X] @baremetalfreak 
- [X] @vcunat 
- [X] @alexhultman 
- [X] @plafer 
- [ ] @danbev 
- [ ] @hhellyer

**Comment by pmderodat** [comment]
Sounds great, that’s fine by me!

**Comment by santigimeno** [comment]
Fine by me

**Comment by bnoordhuis** [comment]
Pro forma +1.

**Comment by indutny** [comment]
👍

**Comment by hhellyer** [comment]
Yes, that's fine.

**Comment by mscdex** [comment]
Sure.

**Comment by beevik** [comment]
works for me.

**Comment by jasongin** [comment]
👍

**Comment by indutny** [comment]
@saghul what is substantial difference between MIT that we currently have, and CC4.0? Both require attribution, and both allow sharing/editing. Why should we bother then?

**Comment by saghul** [comment]
@indutny My understanding is that MIT is more targeted towards software, whereas CC isn't. CC even used to discourage its use in software, and since this part is documentation I thought it applies better.

**Comment by saghul** [comment]
Thanks for that @txdv!

**Comment by indutny** [comment]
@saghul so, there is no substantial benefit of using CC over MIT? Please disregard my 👍 then.

**Comment by txdv** [comment]
Maybe the discussion of choosing the right license should have happened before naming everyone.

I did a blame on all the files though and it seems like there is no documentation left by indutny, or all his commits have been overwritten.

**Comment by alexhultman** [comment]
Why oppose this? It makes no difference at all and only creates discussion. CC is clearly more suited for documentation while MIT is an overused and ambiguous software license.

**Comment by indutny** [comment]
@alexhultman because this is quite a massive change and requires confirmation from many people? This is the reason for me to oppose this. Could you please elaborate on _clearly more suited for documentation_?

**Comment by alexhultman** [comment]
*unsubscribe*

**Comment by indutny** [comment]
@alexhultman I'm sorry?

**Comment by alexhultman** [comment]
Don't @at me, I'm unsubscribed

**Comment by indutny** [comment]
Ok.

**Comment by almosnow** [comment]
Fine with me. Best regards.

**Comment by saghul** [comment]
Keep calm everyone, @indutny gave his 👍 and then asked a question, that's ok. Not everyone knows all the details those licenses entail, me included, that's why having a community helps here.

Sorry if anyone felt uncomfortable, I asked the question like this in the interest of full-transparency.

**Comment by vcunat** [comment]
>  indutny gave his :+1: and then asked a question, that's ok.

I understood it as him *revoking* his :+1: afterwards, but it's likely irrelevant anyway, as pointed out by others.

**Comment by saghul** [comment]
@vcunat Correct. At any rate he hasn't contributed to docs/ so we don't need his blessing.

**Comment by saghul** [comment]
@dharesign do I take that as a yes? :-)

**Comment by indutny** [comment]
I certainly wrote some of the original documentation :wink:

Even if you would like to disregard my vote, please at least take my opinion seriously. There has been no discussion about particular target license, and there is no reasoning mentioned anywhere here.

I don't want to stop anyone from doing whatever they sincerely believe in, but it would be great to base our decisions on factual differences instead of just belief.

**Comment by saghul** [comment]
@indutny Man, why are you doing this?! They are equivalent licenses to some extent, but CC is designed for documents and the like whereas MIT is designed for software. It's a no brainer.

I hate to write this, but you are giving me no other choice: I rewrote all "documentation" (the header file comments) when I started the Sphinx part, so I technically I don't need your permission.

The main reason why I want to do this is to help our users. The user guide I'm trying to merge (see #1246) is licensed under CC so we need to find a way to make that work. I never gave the docs license a thought before, but upon being confronted with the problem CC makes a lot more sense so I decided to ask everyone about it, and here we are.

By even attempting to block this you are essentially hindering my ability to make libuv more approachable for users by merging a user guide we can all continue improving. This is not cool, and I expected higher from you.

**Comment by indutny** [comment]
@saghul #1246 is a good reason to move to CC, this is all I wanted to know. Not sure why the conversation has suddenly turned out this way...

**Comment by baremetalfreak** [comment]
@saghul I personally do not care about a particular license and my
contribution is close to zero.

But I already happen to be part of this discussion and @indutny asked a
legitimate question and should not be ostracized for that.

Having said that, I believe the reasoning you just provided is good enough
and if it was posted somewhere before and pointed to in the original email
we could have avoided this discussion.

Thanks for all the hard work you are putting into libuv!!!

All the best.

On 17 March 2017 at 11:17:50, Saúl Ibarra Corretgé (notifications@github.com)
wrote:

@indutny <https://github.com/indutny> Man, why are you doing this?! They
are equivalent licenses to some extent, but CC is designed for documents
and the like whereas MIT is designed for software. It's a no brainer.

I hate to write this, but you are giving me no other choice: I rewrote all
"documentation" (the header file comments) when I started the Sphinx part,
so I technically I don't need your permission.

The main reason why I want to do this is to help our users. The user guide
I'm trying to merge (see #1246 <https://github.com/libuv/libuv/pull/1246>)
is licensed under CC so we need to find a way to make that work. I never
gave the docs license a thought before, but upon being confronted with the
problem CC makes a lot more sense so I decided to ask everyone about it,
and here we are.

By even attempting to block this you are essentially hindering my ability
to make libuv more approachable for users by merging a user guide we can
all continue improving. This is not cool, and I expected higher from you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/libuv/libuv/issues/1254#issuecomment-287317170>, or mute
the thread

**Comment by saghul** [comment]
Thanks for that @indutny! I'm glad we are on the same boat! ❤️ 

Also, I apologize for not being clear about the reasoning from the start, I see I failed to link to #1246 on this PR. It all made sense in my head but I didn't communicate it as effectively as I could have.

**Comment by wavexx** [comment]
Fine for me.

**Comment by vcunat** [comment]
I don't care really, am no laywer and haven't contributed non-negligibly, but I believe even the current license text is OK.

It explicitly includes documentation in the definition of "Software", and IMHO the whole text is extremely short without mentioning anything that would seem to apply differently to "different kind of data".   The full text of CC-BY is much longer, but it's also a very well known license.

**Comment by skypjack** [comment]
:+1:

**Comment by jhamhader** [comment]
:+1:

**Comment by neojski** [comment]
Ok.

**Comment by deleisha** [comment]
Count me in

**Comment by btrask** [comment]
Sounds good.

**Comment by saghul** [comment]
Gentle reminder: @cjihrig, @jgeralnik, @dharesign, @yosuke-furukawa, @MostAwesomeDude, @petkaantonov, @lomew, @danbev

**Comment by lomew** [comment]
👍

**Comment by jgeralnik** [comment]
Sounds

**Comment by jgeralnik** [comment]
Sounds good

**Comment by danbev** [comment]
👍

**Comment by petkaantonov** [comment]
approvee

**Comment by petkaantonov** [comment]
approved

**Comment by cjihrig** [comment]
SGTM

**Comment by dharesign** [comment]
I am not opposed to changing the license.

**Comment by yosuke-furukawa** [comment]
SGTM2

**Comment by cjihrig** [comment]
@MostAwesomeDude you're the only one that hasn't responded 😄

**Comment by santigimeno** [comment]
@MostAwesomeDude any thoughts on this? Thanks!

**Comment by saghul** [comment]
I completed #1246, including the license change. Since @MostAwesomeDude hasn't replied let's go ahead as is, and if he refuses to relicense his contribution in the future I'll rewrite the one sentence: fc556acb.

Thanks everyone!

**Comment by vcunat** [comment]
I personally don't think this commit is large enough to affect copyright and thus require approval (but I'm no lawyer).
