### ISSUE TITLE
Can I pass some arguments from uv_async_send to main loop?

### ISSUE THREAD

**Issue by uudiin** [libuv/libuv#1261]
Can I pass some arguments from uv_async_send to main loop on windows?
Thanks.

**Comment by mkrufky** [comment]
it's up to your own mechanism to send data to the main loop.  `uv_async_send` will alert the main loop of the fact that there is data waiting, but keep in mind that if you call `uv_async_send` multiple times, there is no guarantee that the main loop will be woken more than once.  See the documentation for  [uv_async_t](http://docs.libuv.org/en/v1.x/async.html)

**Comment by cjihrig** [comment]
Can you ask these types of questions on the mailing list. This issue tracker is for bug reports and feature requests.

**Comment by uudiin** [comment]
Thank you
