### ISSUE TITLE
Overclocked AMD causes NPM to respond Assertion failed: new_time >= loop->time ...

### ISSUE THREAD

**Issue by metalvexis** [libuv/libuv#1268]
* **Version: 7.7.3**:
* **Platform: Win 64**:
* **Subsys: Not Sure**:

I discovered that when I OC my AMD A6-7400k processor from 3.5ghz to 3.9ghz, node and npm fails to start and respond with:

Assertion failed: new_time >= loop->time, file src\win\timer.c, line 37

![Overclocked](https://cloud.githubusercontent.com/assets/20812784/24146019/c25558de-0e6e-11e7-99ec-c891ba084401.PNG "Overclocked")

but after turning the core speed, npm goes back to normal.

![Not Overclocked](https://cloud.githubusercontent.com/assets/20812784/24146003/b175a8b6-0e6e-11e7-9c13-2f705af58768.PNG "Not Overclocked")

**Can anyone explain this?**

**Comment by bnoordhuis** [comment]
Libuv uses QueryPerformanceCounter().  Looks like it starts to drift on your system when overclocking.

**Comment by jespersm** [comment]
For posterity: I had this happen on a (non-overclocked) AWS instance. The Windows uptime at the time was around 167 days and 10 hours. After a reboot, the problem disappeared. YMMV.

**Comment by elierrgm** [comment]
Hi jespersm,

I am getting the same error on a AWS instance with Windows Server 2016, it has happened twice in the last month. Were you able to find the cause of the issue? Is it not happening anymore to you after rebooting? How long has it been working fine after the reboot?

**Comment by jespersm** [comment]
@elierrgm: I haven't tried since then on that server, but will shortly... I have a different AWS instance, also Windows Server 2016, up for 188 days, which has had no such problem.

**Comment by hikeeba** [comment]
I had this problem appear also on a Windows EC2 instance. Restarting the instance solved it.

**Comment by gaperton** [comment]
Same thing just happened on our (non-overclocked) EC2 instances.

> Libuv uses QueryPerformanceCounter(). Looks like it starts to drift on your system when overclocking.

Was that the really strong reason to close this ticket?

**Comment by gaperton** [comment]
https://github.com/libuv/libuv/issues/1633

https://github.com/nodejs/node/issues/8234

I see. Not a bug, and not a support forum :). Thanks for the clarification.
