### ISSUE TITLE
Add hook for custom configuration of the child process in uv_spawn

### ISSUE THREAD

**Issue by netrounds-fredrik** [libuv/libuv#1272]
libuv has the possibility to do some configuration of the child process created in `uv_spawn` using the fields in the `uv_process_options_t` struct. However there is no way to cover all possible configuration that a user of libuv might want to do to the child process.

Therefore I propose to add a function pointer in the `uv_process_options_t` struct that will be called early in `uv__process_child_init`, before all other configurations are applied, to allow the user of libuv to do custom configurations of the child process. Also, to make it possible to pass custom configuration options to that function, a `void *user_data` can be added to the struct as well.

For example:
```
typedef void (*uv_spawn_cb)(uv_process_t*);

typedef struct uv_process_options_s {
  uv_spawn_cb spawn_cb; /* Called from the child process, before the command is executed. */
  void *user_data; /* User data associated with this process */

  ...
}
```

This will only work on unix systems that does forking.

**Comment by bnoordhuis** [comment]
That's one reason not to do it.  Another is that only a handful of functions are safe to call after forking.

**Comment by saghul** [comment]
@netrounds-fredrik what kind of processing would you want to do in this function?

**Comment by netrounds-fredrik** [comment]
I have a use case where I need to change the network namespace of the child process. It can not be done in the parent process before forking since it would terminate all open network connections.

**Comment by netrounds-fredrik** [comment]
> That's one reason not to do it.

Are you referring to the fact that it will only work on UNIX systems? There are already other options that are only valid for some platforms, for example `uid`/`gid` and `UV_PROCESS_WINDOWS_HIDE`.

**Comment by bnoordhuis** [comment]
Yes, but those are common options that you can't really do without on those platforms.  The rule of thumb is that we only implement what can be implemented on all platforms, everything else is "no, unless."

On to practical matters: extending the `uv_process_options_t` struct changes the ABI, meaning it can't land in the v1.x release branch.

**Comment by netrounds-fredrik** [comment]
Still a valid feature request. But if you see that it won't be accepted you can close it.

**Comment by bnoordhuis** [comment]
It's been open for over two years and no one else requested it so I'll go ahead and close it.
