### ISSUE TITLE
Segmentation fault when uv_timer_stop->heap_remove

### ISSUE THREAD

**Issue by vertextao** [libuv/libuv#1286]
* I use **libuv-1.11.0** on Linux(3.10.0-327.13.1.el7.x86_64)
* heap was crashed on access ```child``` of NULL pointer at [here](https://github.com/libuv/libuv/blob/v1.x/src/heap-inl.h#L196).

Details:
* heap info
```
(gdb) p *heap
$1 = {min = 0x3379718, nelts = 26733}
```
convert ```nelts = 26733``` to binary format ```‭0110100001101101‬```

I'm trying to replay the ```heap_remove```, 
according to the [code](https://github.com/libuv/libuv/blob/v1.x/src/heap-inl.h#L181), ```nelts``` has just been decreased by 1, so add it back to ```nelts```.

before ```heap_remove```, it should be 26734 -> ```‭0110 1000 0110 1110‬```

* first, according to the path calculation:

```c
  path = 0;
  for (k = 0, n = heap->nelts; n >= 2; k += 1, n /= 2)
    path = (path << 1) | (n & 1);
```

the ```path``` should be ```10 1000 0110 1110```.

* next, according to the traverse:

```c
  max = &heap->min;
  while (k > 0) {
    if (path & 1)
      max = &(*max)->right;
    else
      max = &(*max)->left;
    path >>= 1;
    k -= 1;
  }
```

I replayed it from GDB:

```
(gdb) p *heap->min->left->right->right->right ->left->right->right->left ->left->left->left->right ->left->right 
$4 = {left = 0x0, right = 0x0, parent = 0x1de4eb8}
```

more info about the timer handle:

```
$6 = {
  data = 0x32331b0, 
  loop = 0x17f3f48, 
  type = UV_TIMER, 
  close_cb = 0x40f7a2 <c_uvw_timer::~c_uvw_timer()::{lambda(uv_handle_s*)#1}::_FUN(uv_handle_s*)>, 
  handle_queue = {0x331bbc0, 0x33799c0}, 
  u = {
    fd = 0, 
    reserved = {0x0, 0x33793e0, 0x1490d, 0x3379578}
  }, 
  next_closing = 0x0, 
  flags = 24576, 
  timer_cb = 0x40f8da <c_uvw_timer::start()::{lambda(uv_timer_s*)#1}::_FUN(uv_timer_s*)>, 
  heap_node = {0x331bc08, 0x35332c8, 0x0}, 
  timeout = 355889213, 
  repeat = 15000, 
  start_id = 120334
}
```

**NOTE**: c_uvw_timer is up layer wrapper for uv timer in C++11. 

The timers are repeat, and when some condition valid, they will be stopped and closed, then handle will be freed in close_cb.

When I run this application in [10,1000] of timer instances, it's fine. But when I let the number of instances beyond 10000, this issue will occur in minutes.

---

I'm not sure this is a issue of the heap or I get involved in wrong usage or any other issues which are far away from here.

I've checked my wrapper code several times, now I'm checking the heap's implementation...

Hope this message to be helpful!

Thanks!

**Comment by vertextao** [comment]
**AGAIN** it's crashed at [here](https://github.com/libuv/libuv/blob/v1.x/src/heap-inl.h#L133) when doing ```heap_insert```.

So, there's high probability that the heap's structure was corrupted!

More info in GDB:

```
(gdb) p *heap
$1 = {min = 0x2382d98, nelts = 25509}
(gdb) p k
$2 = 7
```

**Comment by vertextao** [comment]
I probably found the reason.

some ```uv_timer_start``` calls come from different thread, cause libuv's loop is not thread safe. So, I'm going to handle this issue.

**Comment by kenshinx** [comment]
@vertextao 
Do you have any  update about this issue?
I meet totally the same problem with you, segmentation fault at `heap_remove` or `heap_insert ` function and gdb show  crash at the line of 
> child->left = node->left;

or
> child = &(*child)->right;

You have mentioned non thread-safe uv_pool maybe caused this problem, could you provide more  evidence to support this judgement? And do you mind further explanation how fix this issue eventually.

Thanks a lot.

**Comment by bnoordhuis** [comment]
@kenshinx Libuv is explicitly not thread-safe, it's in the documentation.

**Comment by kenshinx** [comment]
@bnoordhuis  Thanks.
Yes, i know libuv is not thread-safe,  i just want confirm this issue is caused by multi-thread at here. 

In my approach , i indeed used multi thread, but each thread maintain a separate uv_loop_t object, and there is no shared memory or race competition  between these different thread.

**Comment by bnoordhuis** [comment]
One loop per thread should be safe.  If you get segfaults, usually that's because of freeing the handle's memory before libuv is done with it.  Free it from the uv_close() callback.

**Comment by kenshinx** [comment]
Thanks @bnoordhuis , you give me a good inspiration, i have fixed the problem now.

In my case, uv_timer_start() be called firstly, subsequently handler memory be freed in uv_close() callback, and the uv_timer_stop() just  be skip over in some condition,  all of these situations together lead to the end segment faults.

Make sure the uv_timer_stop() be called  before free handler memory in any situation solved my problem.

**Comment by vertextao** [comment]
@kenshinx I'm very sorry about missing your messages.

Glad to see you've solved your problem. More comments:
Indeed, multi-thread is devil! There's high probability you will make mistakes even if you pay a lot attentions on it.

As @bnoordhuis said "One loop per thread should be safe.", I designed my program in this way, BUT this CANNOT prevent you to operate the objects across threads (I was very clear about the object is not thread safe, but that happened in an accident). So, you must be careful all the time.

At a higher level view, is multi-thread really needed should be considered in advance.

**Comment by vertextao** [comment]
@kenshinx In my case, [threads](https://github.com/vertextao/uv_wrapper/blob/master/uvw_thread.h) interact via a thread-safe  [task queue](https://github.com/vertextao/uv_wrapper/blob/master/uvw_thread.h#L207), I called the ```uv_timer_start``` accidentally from another thread (not the loop's owner). So I have 2 ways to correct it:
* start the timer before the loop's owner (thread) run.
* [post](https://github.com/vertextao/uv_wrapper/blob/master/uvw_thread.h#L91) a [task](https://github.com/vertextao/uv_wrapper/blob/master/uvw_task.h) to the loop's owner to start the timer ( I chose this way).

**Comment by kenshinx** [comment]
Thanks your kind comment @vertextao
