### ISSUE TITLE
Make uv__get_osfhandle() public 

### ISSUE THREAD

**Issue by jviotti** [libuv/libuv#1291]
MSVCR is statically linked into node, which means that users can't pass file descriptors from nodejs add-ons to the JavaScript code, given that the file descriptor to handle map in the add-on is separate to the one statically linked into the node executable.

This was initially reported in https://github.com/nodejs/node/issues/6369, where the suggestion was to make `uv__get_osfhandle()` public, so add-ons can make use of it, and resolve the file descriptor correctly.

Would such a change be accepted?

The contributing guide says:

> The stable branch is effectively frozen; patches that change the libuv API/ABI or affect the run-time behavior of applications get rejected.

However I wonder what are your thoughts here, given that the public API will remain backwards compatible.

If this is not something you'd accept, would you mind suggesting an alternative to mitigate this issue?

Thanks in advance!

**Comment by moteus** [comment]
I think this related with #1121, #1119 and #1166

**Comment by saghul** [comment]
@jviotti Yeah, I think it's an acceptable change, specially since we are adding it in #1166. If you write a PR, take the code from there so we don't diverge master from v1.x.
