### ISSUE TITLE
inconsistent value types from uv_uptime

### ISSUE THREAD

**Issue by refack** [libuv/libuv#1294]
On Windows returned value is really a double (with fractions).
[`uptime = (double) (object_type->PerfTime.QuadPart - value) / (double) object_type->PerfFreq.QuadPart;`](https://github.com/libuv/libuv/blob/v1.x/src/win/util.c#L577)

On others it's an integer (upcast to double):
```
struct timespec
	time_t  tv_sec    Seconds. 
	long    tv_nsec   Nanoseconds. 
```
[`*uptime = now.tv_sec;`](https://github.com/libuv/libuv/blob/v1.x/src/unix/linux-core.c#L601)

**Comment by gibfahn** [comment]
Most recent change: https://github.com/libuv/libuv/commit/556fe1a6598bbd1bee4a98587b4a2329697963d0
