### ISSUE TITLE
msg_zerocopy support

### ISSUE THREAD

**Issue by rektide** [libuv/libuv#1297]
It would be neat to see what performance gains may be possible if Node.js could use msg_zerocopy to reduce net system load while sending network data.

For large transfers in particular, significant cpu cycles have been saved in some performance testing that's been done outside Node.js realms-
https://lwn.net/Articles/655299/

**Comment by saghul** [comment]
Feel free to experiment with it and come back with some numbers. If there is a net benefit I don't see why we wouldn't want to have it!

**Comment by rektide** [comment]
Some reference material links, both of which happen to be from the author of msg_zerocopy Willem de Bruijn,
* [slides](http://netdevconf.org/2.1/slides/apr6/msgzerocopy-willemdebruijn-20170405.pdf) 
* [example](https://github.com/wdebruij/linux/blob/zerocopy-sendmsg-rfcv2/tools/testing/selftests/net/snd_zerocopy.c)

I started poking around udp.c, thinking it might be one of the easier places to do this. The heaviest part of the work, it seems, would come from implementing read notifications- knowing when the read is done. I think this is blocking, "fast" code that can be looped over regularly. The example from snd_zerocopy.c is [here](https://github.com/wdebruij/linux/blob/zerocopy-sendmsg-rfcv2/tools/testing/selftests/net/snd_zerocopy.c#L54). I'm new to libuv, and only starting to investigate options for where in libuv's looping to add this completion check.
