### ISSUE TITLE
Allow NULL callback in uv_async_init 

### ISSUE THREAD

**Issue by supercairos** [libuv/libuv#1298]
Hi,

Would be very handy to use async to only wakeup the loop. 
I use a lot the `uv_prepare_t` to send/process my datas that came from an other thread witch use the `uv_async_send(...)` to wakeup the loop and don't do any processing in the callback.

R.

**Comment by saghul** [comment]
We could indeed do that, which I guess might benefit some like yourself. I'd +1 to a patch.

**Comment by cjihrig** [comment]
Isn't that what 1510ce81fde8f07a4f692274de467dfdad33c604 did?

**Comment by bnoordhuis** [comment]
Yep.  It's even documented as such:

> A NULL callback is allowed.

I'll go ahead and close this out.

**Comment by saghul** [comment]
LoL memory, thanks guys!
