### ISSUE TITLE
meta: https://github.com/libuv/help?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#1305]
Proposal: create a forum similar to https://github.com/nodejs/help/issues where users can post and answer support questions, i.e., a self-help thing.

Motivation: we redirect users to the mailing list now but in this age of GitHub that's arguably an unreasonable barrier to entry.

cc @libuv/collaborators

**Comment by cjihrig** [comment]
+1

**Comment by santigimeno** [comment]
+1

**Comment by saghul** [comment]
+1 Let's do it!

**Comment by bnoordhuis** [comment]
Closing, this is done.
