### ISSUE TITLE
uv_tty_set_mode regression (v1.2.0, unix)

### ISSUE THREAD

**Issue by TomCrypto** [libuv/libuv#131]
In v1.1.0 we are able to create a readable `uv_tty` to stdin using:

    uv_tty_init(loop, &tty, 0, 1);

And then set its mode to 0 (aka "normal") via:

    uv_tty_set_mode(&tty, 0);

Which in v1.1.0 with a clean terminal state is a no-op, as expected. In v1.2.0, this no longer works:

    uv_tty_init(loop, &tty, 0, 1);
    uv_tty_set_mode(&tty, UV_TTY_MODE_NORMAL);

This causes the terminal state to become corrupt on Linux. It seems to occur because in that particular case the tty's `orig_termios` member is not initialized by a previous call to `uv_tty_set_mode` with a non-normal mode, yet a `tcsetattr` call is performed with it at the end, happily corrupting the terminal state and then returning success. The logic of v1.1.0's `uv_tty_set_mode` implementation at `src/unix/tty.c` avoided this.

Now I realise setting the tty mode to normal is kind of redundant in this case (or is it? it's not clear to me whether a mode *must* be set before use or if normal is the implied default mode) but I think it is reasonable to expect `uv_tty_set_mode` to behave consistently especially in such a simple use case, and it certainly should never trash the terminal state given sensible parameters.

The commit which introduced the regression is [025602da138ec9ca908f9303427903ea1dc06494](https://github.com/libuv/libuv/commit/025602da138ec9ca908f9303427903ea1dc06494).

**Comment by saghul** [comment]
> Now I realise setting the tty mode to normal is kind of redundant in this case (or is it? it's not clear to me whether a mode must be set before use or if normal is the implied default mode) but I think it is reasonable to expect uv_tty_set_mode to behave consistently especially in such a simple use case, and it certainly should never trash the terminal state given sensible parameters.

AFAIS, it is redundant, though the way it behaves now it's a bug. I'll make a fix.
