### ISSUE TITLE
uv_ip6_addr() ignores invalid interface name

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#1313]
Test case:
```c
struct sockaddr_in6 s;
int r = uv_ip6_addr("::0%bad", 0, &s);
assert(r < 0);  /* Fails because r == 0. */
```
`uv_ip6_addr()` calls `if_nametoindex()` internally (on UNIX, not Windows) but does not check for errors.  Might be a security liability in certain circumstances.

We could shift responsibility to the caller:
```c
struct sockaddr_in6 s;
s.sin6_scope_id = -1;  /* Sentinel value. */
int r = uv_ip6_addr("::0%bad", 0, &s);
assert(r == 0);  /* OK */
assert(s.sin6_scope_id == 0);  /* OK, indicates error. */
```
The upside is that it lets callers parse bad link-local addresses, the downside is that it's more laborious and therefore easier to forget about proper validation.  It should be documented, though, if we decide to take this approach.

**Comment by santigimeno** [comment]
Maybe I'm missing something evident but why aren't we checking for errors on `if_nametoindex() `, wouldn't that solve the problem altogether?

**Comment by bnoordhuis** [comment]
I can't say, @bajtos wrote that.  It has this going for it:

> The upside is that it lets callers parse bad link-local addresses

Which is useful if you don't care about the interface.

**Comment by cjihrig** [comment]
I think I'm in favor of just checking the error code from `if_nametoindex()`. I'll do the work if we want to go in that direction.

**Comment by cjihrig** [comment]
Closing this, as #1350 landed on master (not v1.x) a while back.
