### ISSUE TITLE
Req: Method that returns local hostname

### ISSUE THREAD

**Issue by jdonaldson** [libuv/libuv#1315]
There's some nice DNS wrappers for gethostname and getaddrinfo, but I'm not seeing a good way of getting the hostname of the local machine.  If that were made available through libuv, I'd use it and get rid of another dependency in my projects.

**Comment by saghul** [comment]
You mean as a wrapper for `gethostname(3)`? I think I'd like that. Are you up for writing a patch?

**Comment by bnoordhuis** [comment]
You could lift the implementation from node.js, it's the GetHostname() function in src/node_os.cc.

**Comment by cjihrig** [comment]
@jdonaldson are you planning to work on this? If not, I'd like to take a shot.

**Comment by jdonaldson** [comment]
Sorry, on vacation here last few days.  By all means give it a shot, I won't have a good chance to work on this for some time.
