### ISSUE TITLE
uv_spawn on windows with caret char in argument

### ISSUE THREAD

**Issue by Speedy37** [libuv/libuv#1319]
I was trying to pass 'module@^version' as argument to npm with node but this resulted in the caret being "removed".

I think `quote_cmd_arg` should add quotes if '^' is present.

* **Version**: 1.9.1
* **Platform**: Windows 10 x64

**Comment by justinmk** [comment]
Was the argument sent to cmd.exe? If so, it considers "^" to be an escape character.

> I think quote_cmd_arg should add quotes if '^' is present.

That doesn't conform to [CommandLineToArgvW](https://msdn.microsoft.com/bb776391) so it will just cause different problems.

**Comment by Speedy37** [comment]
The argument wasn't sent to cmd.exe.

Here is my test:

```js
child_process.spawnSync('npm.cmd', ['--loglevel', 'verbose', 'install', '@openmicrostep/async@^0.1.0'], { }).stderr.toString().split('\n')

[ ...,
  'npm verb cli [ \'C:\\\\Program Files (x86)\\\\nodejs\\\\node.exe\',',
  'npm verb cli   \'C:\\\\Program Files (x86)\\\\nodejs\\\\node_modules\\\\npm\\\\bin\\\\npm-cli.js\',',
  'npm verb cli   \'--loglevel\',',
  'npm verb cli   \'verbose\',',
  'npm verb cli   \'install\',',
  'npm verb cli   \'@openmicrostep/async@0.1.0\' ]',
  ...]
```

The following commands works:

 - in shell: `npm install "@openmicrostep/async@^0.1.0"`
 - in node: 
```js
child_process.spawnSync('npm.cmd', ['--loglevel', 'verbose', 'install', '@openmicrostep/async@^^^^0.1.0'], { }).stderr.toString().split('\n')
```

both output: `'npm verb cli   \'@openmicrostep/async@^0.1.0\'`

**Comment by vtjnash** [comment]
It seems like you are mistakenly calling a batch script (`npm.cmd`) rather than the package manager (`npm.exe`)? If you are going through the DOS shell, you need to pass all of your arguments as a single argument string and set the UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS  (https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L929) flag.

**Comment by Speedy37** [comment]
You are right, I just did a test with a simple program, and the '^' char is as expected.
