### ISSUE TITLE
add -Wstrict-prototypes flag

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#1320]
I noticed that many of the functions declarations in src/win/internal.h are using old K&R-style function definitions, rather than ANSI C declarations. The `-Wstrict-prototypes` flag would enable warning when the code accidentally declares a function as unprototyped (`void uv__func();`) instead of as taking zero arguments (`void uv__func(void)`). In practice, this doesn't usually matter (the calling-convention for zero arguments is the same either way), although it does somewhat reduce the type-safety one would usually get from declaring the function in a header.

https://stackoverflow.com/questions/693788/is-it-better-to-use-c-void-arguments-void-foovoid-or-not-void-foo

**Comment by saghul** [comment]
SGTM! @libuv/collaborators WDYT?

**Comment by bnoordhuis** [comment]
That would be for the msys2 autotools build?  SGTM.  Compatibility shouldn't be an issue because the flag has been around since at least gcc 3.3.

**Comment by cjihrig** [comment]
SGTM
