### ISSUE TITLE
libuv suppresses Windows Error Reporting   

### ISSUE THREAD

**Issue by ptlomholt** [libuv/libuv#1327]
On Windows, uv_init() calls SetErrorMode() passing `SEM_NOGPFAULTERRORBOX` as one of the flags:

```
static void uv_init(void) {
  /* Tell Windows that we will handle critical errors. */
  SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX |
               SEM_NOOPENFILEERRORBOX);
```
This presumably disables Windows Error Reporting from gathering its crash reports, reporting crash summary to the Windows Application Event log or even impossible to configure a post-mortem debugger via the AEDebug Registry key: <https://msdn.microsoft.com/en-us/library/windows/desktop/bb204634(v=vs.85).aspx>. Troubleshooting customer issues (libuv related or otherwise) becomes a lot more tedious without this information!

The MSDN documentation, <https://msdn.microsoft.com/en-us/library/windows/desktop/ms680621(v=vs.85).aspx>, is a bit vague on this point as it says that the flag disables the dialog box from popping up, but I have found that it disables WER entirely for the process.

There is a comment in the code that 'we will handle critical errors' but I don't see anywhere where libuv is catching any Win32 structured exceptions, so I am not sure why it is necessary to pass `SEM_NOGPFAULTERRORBOX`. Can we remove this flag? 

In general I also think it is bad practice for a library to make process wide configuration changes.

* **Version**: any up till 1.11.0
* **Platform**: Windows

**Comment by saghul** [comment]
@bzoz thoughts? @piscisaureus any chance you remember why that is there?

**Comment by bzoz** [comment]
This was added by https://github.com/libuv/libuv/commit/7a53924aede6415898a5f4a01b5d0345cf125c9a, I can only guess it is to suppress `app.exe has stopped working` dialog. Without this if the app crashes in a batch script and there is no one to click `Close application` button, the script will hang.

I agree that applications should set this themselves, but it is already here so I don't think we can remove it without breaking something somewhere.

@ptlomholt you can call `SetErrorMode(0)` yourself after `uv_init` to restore WER. You can also use `SetUnhandledExceptionFilter` to add your own exception handler that would call `MiniDumpWriteDump` to write memory dump. Complete code example can be found [in this stackoverflow answer](https://stackoverflow.com/a/5028973)

**Comment by bzoz** [comment]
I'll go ahead and close the issue. Feel free to reopen the issue.
