### ISSUE TITLE
uv_close() unconditional unlink() of UDS

### ISSUE THREAD

**Issue by vedadkajtaz** [libuv/libuv#1332]
* **Version**: libuv-1.11.0
* **Platform**: FreeBSD 11.0-RELEASE

Hello,

uv_close() on uv_pipe_bind()'ed uv_pipe_t currently unconditionally unlink()s the unix domain socket.

I found this to be an issue in a deployment scenario where a daemon is being gracefully shut down (serving accepted clients, while stopping accepting new connections) and another instance being launched - with identical socket paths - before the previous instance effective shutdown. In this scenario, the daemon instance being shut down eventually unlink()s the sockets created by the new daemon instance.

Would it be possible to add an option/workaround to prevent this default behavior?

Kind regards,

**Comment by santigimeno** [comment]
@vedadkajtaz IIUC, in the scenario you describe, when the new instance is launched, the file in the path where the deamon listens should exist because the previous instance hasn't still _unlinked_ it. If that's the case, why calling bind in the new instance isn't returning `EADDRINUSE` ?

**Comment by vedadkajtaz** [comment]
Indeed, unlink() is being explicitly invoked before binding, so there is a short interval where the socket doesn't exist. Yet, with the scenario described above, I'm left with a running daemon (and matching pidfile) but no sockets.

**Comment by santigimeno** [comment]
In case you wouldn't call `unlink()` before binding you would receive the error and act upon (maybe retrying a little bit later). This is what you would have to do if you were using TCP sockets for example.

**Comment by vedadkajtaz** [comment]
The issue with that suggestion is that I'd wait indefinitely should the previous daemon instance crash, leaving the socket `unlink()`ed.

**Comment by santigimeno** [comment]
Doh, you're right :(.

One more question, why is it a problem that the new instance unlinks the socket if the previous instance is only serving accepted connections and not accepting new ones? Shouldn't that just work?

**Comment by vedadkajtaz** [comment]
Also, in my specific case, the scripts managing the daemons have no knowledge of the sockets paths (they're in a config file), hence it'd be quite difficult and redundant to move that logic into those daemon management scripts.

**Comment by santigimeno** [comment]
I mean, why not close the `uv_pipe_t` server handle soon and wait for the daemon to exit once the pending connections are done

**Comment by vedadkajtaz** [comment]
It's a proxy daemon, and the pending connections may take minutes to terminate, that's why waiting wasn't an option. I originally wanted nearly-zero downtime using the following restart process:

1. OLD_PIDFILE=`cat <pidfile>`
2. /path/to/daemon --config <configfile> --pidfile <pidfile>
3. kill -USR1 $OLD_PIDFILE

Where the sockets would be unavailable only for a couple of milliseconds, while the socket is being unlinked and re-binded in step 2.

**Comment by vedadkajtaz** [comment]
FYI the `uv_pipe_t` server is effectively closed as soon as the signal is processed.

**Comment by santigimeno** [comment]
> FYI the uv_pipe_t server is effectively closed as soon as the signal is processed.

This is what's not completely clear to me (sorry for so many questions): if the server is closed as soon as the signal is processed (and so the path should be unlinked) and then the new deamon is started, the window where the issue can happen is very narrow right?

**Comment by vedadkajtaz** [comment]
Indeed, it is narrow, but it did happen. Note that, in the above scenario, the new daemon used to be started *before* the signal was sent to the previous instance, in order to make the window as narrow as possible. I now did reverse the order to get rid of the issue, yet it isn't as perfect as it would be if `unlink()` didn't happen when closing `uv_pipe_t` server.

**Comment by saghul** [comment]
> Would it be possible to add an option/workaround to prevent this default behavior?

I don't really have any suggestion here :-( If you have any ideas, they would be welcome :-)

**Comment by vedadkajtaz** [comment]
Well, since the single uv_close() method is being used for all the handle types, I guess modifying it's signature for this specific case wouldn't be appropriate. Perhaps an additional bitfield argument with "unlink before bind" and "unlink after close" bits (defaulting to the current behavior) to uv_pipe_bind() ? I'm not familiar with Windows pipes so don't know whether this makes sense in Windows.
