### ISSUE TITLE
Time is slower than date output

### ISSUE THREAD

**Issue by ugiwgh** [libuv/libuv#1345]
I use the libuv's time function. But as the program runs, the time is much slower than the date output. I have test the clock_gettime function, it's also slower.

**Comment by bnoordhuis** [comment]
It's completely unclear to me what you mean.  Can you post a test case and/or expected vs. actual output?

**Comment by ugiwgh** [comment]
**actual output:**
# date 
Tue May 16 10:00:02 CST 2017
# ./myprogram
Tue May 16 10:00:03 CST 2017
Tue May 16 10:00:04 CST 2017
... a long time ...
Tue May 17 8:00:50 CST 2017
# date
Tue May 17 9:00:50 CST 2017

**expected output:**
# date 
Tue May 16 10:00:02 CST 2017
# ./myprogram
Tue May 16 10:00:03 CST 2017
Tue May 16 10:00:04 CST 2017
... a long time ...
Tue May 17 9:00:50 CST 2017
# date
Tue May 17 9:00:50 CST 2017

**Comment by bnoordhuis** [comment]
You probably have a bug in your timestamp-to-date conversion but that is not a libuv issue.

**Comment by bnoordhuis** [comment]
No follow-up, closing.
