### ISSUE TITLE
Makefile:3992: recipe for target 'check-TESTS' failed

### ISSUE THREAD

**Issue by gunjanmk** [libuv/libuv#1351]
Correct me if i am at wrong place and direct me accordingly.

I tried to go to below link provided to raise question but that goes to "404 not found" - https://github.com/libuv/help/new

I came across this issue when installing libuv-1.8.0. Can someone explain what below means and how can i fix it ? 

My system : Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1 (2016-12-30)

=============================================================
[%  33|+  94|-   0|T   0|S   0]: udp_multicast_interface
`udp_multicast_interface` failed: exit code 6
Output from process `udp_multicast_interface`:
Assertion failed in test/test-udp-multicast-interface.c on line 47: status == 0 || status == UV_ENETUNREACH
=============================================================
[%  35|+  97|-   1|T   0|S   0]: udp_multicast_ttl
`udp_multicast_ttl` failed: exit code 6
Output from process `udp_multicast_ttl`:
Assertion failed in test/test-udp-multicast-ttl.c on line 47: status == 0 || status == UV_ENETUNREACH
=============================================================
[%  86|+ 239|-   2|T   0|S   0]: fs_event_watch_dir_recursive
`fs_event_watch_dir_recursive` skipped
Output from process `fs_event_watch_dir_recursive`:
Recursive directory watching not supported on this platform.
=============================================================
[% 100|+ 276|-   2|T   0|S   1]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:3992: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/usr/src/libuv-1.8.0'
Makefile:4248: recipe for target 'check-am' failed
make: *** [check-am] Error 2

* **Version**: 
* **Platform**:

**Comment by saghul** [comment]
There seems to be some multicast related problem in your system. How are you running the tests? As which user?
