### ISSUE TITLE
How do you make sure that async fires callbacks every time?

### ISSUE THREAD

**Issue by zero-rp** [libuv/libuv#1355]
* **Version**: 1.x
* **Platform**: UNIX
I use the following method at window,However, UNIX did not find a good solution.
  struct uv_req_s *req = (void *)malloc(sizeof(*req));
  UV_REQ_INIT(req, UV_WAKEUP);
  req->data = handle;

  //if (!uv__atomic_exchange_set(&handle->async_sent)) {
    POST_COMPLETION_FOR_REQ(loop, req);
  //}

**Comment by kroggen** [comment]
check [uv_callback](https://github.com/litesync/uv_callback)

**Comment by bnoordhuis** [comment]
Please post questions to https://github.com/libuv/help next time, that is what it is for.
