### ISSUE TITLE
uv_get_process_title ends with a segfault if process_title.len is 0

### ISSUE THREAD

**Issue by skypjack** [libuv/libuv#1359]
* **Version**: v1.x
* **Platform**: x86_64 GNU/Linux

[`uv_get_process_title`](https://github.com/libuv/libuv/blob/f9484cf5152ce89bba3d52aea661e6f1fff27e54/src/unix/proctitle.c#L95) terminates with a segfault when `process_title.str` is null and `process_title.len` is 0.  
I got it by running the tests of [`uvw`](https://github.com/skypjack/uvw) through gtest in a local branch. If you need to reproduce the error, I can push the branch and it will be a matter of compiling the project and running the tests.  
Anyway it's pretty simple to reproduce: do not call `uv_setup_args` and invoke `uv_get_process_title`. That's all.

That being said, [`uv_set_process_title`](https://github.com/libuv/libuv/blob/f9484cf5152ce89bba3d52aea661e6f1fff27e54/src/unix/proctitle.c#L83) does a check on `process_title.len` before to call `strncpy` and perform its tasks.  
Shouldn't `uv_get_process_title` do something similar before to use `memcpy`?  

Consider the [following line](https://github.com/libuv/libuv/blob/f9484cf5152ce89bba3d52aea661e6f1fff27e54/src/unix/proctitle.c#L101) from `proctitle.c`:

    memcpy(buffer, process_title.str, process_title.len + 1);

In case of `process_title.str` null and `process_title.len` 0, libuv keeps asking to read a byte from a null pointer.  
Isn't it an error?

A possible alternative implementation of `uv_get_process_title` could be:

    int uv_get_process_title(char* buffer, size_t size) {
      if (buffer == NULL || size == 0)
        return -EINVAL;
      else if (size <= process_title.len)
        return -ENOBUFS;

      if (process_title.len != 0) {
        memcpy(buffer, process_title.str, process_title.len + 1);
      }

      buffer[process_title.len] = '\0';

      return 0;
    }

That is, if `process_title.str` is null and thus `process_title.line` is 0, skip the `memcpy` step.  
I tested it locally and it works just fine as expected. If it sounds good for you, I can create a PR for that. Let me know.

**Comment by bnoordhuis** [comment]
I'm going to guess you didn't call `uv_setup_args()`, otherwise `process_title.str` cannot reasonably be NULL.  From the documentation:

> Store the program arguments. Required for getting / setting the process title.

It's right above the entries for `uv_get_process_title()` and `uv_set_process_title()` but perhaps they should call it out too.

**Comment by skypjack** [comment]
As I said in the issue:

>Anyway it's pretty simple to reproduce: do not call `uv_setup_args` and invoke `uv_get_process_title`.

Therefore yes, I didn't call it.  
Actually gtest doesn't give you access to `argc`/`argv`.

Is it normal that the library crashes in this case?  
At least it should be documented. A segfault is quite annoying usually.

**Comment by bnoordhuis** [comment]
Oh, I see you edited your comment.  It originally said this:

> Anyway, uv_set_process_title does a check on process_title.len before to call strncpy and perform its tasks.  Shouldn't uv_get_process_title do something similar?

Which seems okay to me (i.e., PR welcome) but the point about needing to call `uv_setup_args()` first remains, and yes, that could be improved in the documentation.

**Comment by skypjack** [comment]
Got it. So both a check on `process_title.len` in `uv_get_process_title` **and** a call to `uv_setup_args` in the setter and the getter.  
What arguments should I use to call it if I don't have them exactly?

**Comment by bnoordhuis** [comment]
> So both a check on process_title.len in uv_get_process_title and a call to uv_setup_args in the setter and the getter.

No, just a check.  It makes no sense to call `uv_setup_args()` if you don't have access to argv.

If `process_title.len == 0`, `uv_get_process_title()` should probably just copy out an empty string.  The alternative is to return an error but `uv_set_process_title()` doesn't do that either.

**Comment by skypjack** [comment]
Oh, I thought you meant to call `uv_setup_args` in those functions. Sorry. You were referring to the client code instead. My fault.  
Good. I'll create a PR tomorrow morning with both code and improved doc.  
Thank you very much.

**Comment by cjihrig** [comment]
> The alternative is to return an error but uv_set_process_title() doesn't do that either.

`uv_get_process_title()` already returns errors, so maybe we should.

**Comment by skypjack** [comment]
As you prefer. They both make sense.  
For you know better than me what are the errors in libuv and what they mean, can you suggest the right one in this case?

Let me know what should I put in the PR.  
Either an error or an empty strings are acceptable from my point of view.  
Anyway, probably it would be better if both the getter and the setter do the same thing, that is (for the setter at least) silently return successfully. Wouldn't it?

**Comment by bnoordhuis** [comment]
> uv_get_process_title() already returns errors, so maybe we should.

`uv_set_process_title()` has a `if (process_title.len == 0) return 0;` guard.  It's inexplicably inconsistent to make the same condition an error in `uv_get_process_title()`, IMO.

**Comment by cjihrig** [comment]
Fair enough. Maybe something for v2.

**Comment by saghul** [comment]
Fixed in f2756500
