### ISSUE TITLE
brew install libuv  Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by haijianyang** [libuv/libuv#1367]
hi guys,

while using brew install libuv

there is:

Undefined symbols for architecture i386:
  "_uv_loop_close", referenced from:
      _main in main-fd66b4.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bnoordhuis** [comment]
Can you post your question https://github.com/libuv/help/issues?  It's almost certainly not an issue with libuv itself.  Cheers.

**Comment by TisonKun** [comment]
@bnoordhuis Any where can track this? I meet it today and find no any help info.

**Comment by TisonKun** [comment]
resolve by `gcc main.c -luv`
