### ISSUE TITLE
question: how to build for ios

### ISSUE THREAD

**Issue by ando-takahiro** [libuv/libuv#137]
Does anyone know how to build for ios?  I generated .xcodeproj by ./gyp_uv.py -f xcode, and then made the ios target by hand on xcode.  It's painful...  Is there a better way?

**Comment by saghul** [comment]
Please use mailing list for questions. As for how to create those xcode files, I don't really know, hopefully this helps: https://groups.google.com/forum/#!topic/gyp-developer/9oOuEaVDAbE

**Comment by ando-takahiro** [comment]
thanks
