### ISSUE TITLE
android build error with ndk r14b

### ISSUE THREAD

**Issue by fanzhengchen** [libuv/libuv#1370]
I modified the default android-configure shell script, because the original shell cannot write files into an existing directory
```
#!/bin/sh
export TOOLCHAIN=$PWD/android-toolchain
rm -rf $TOOLCHAIN
$1/build/tools/make-standalone-toolchain.sh \
    --toolchain=arm-linux-androideabi-4.9 \
    --arch=arm \
    --install-dir=$TOOLCHAIN \
    --platform=android-21 \
    --force
export PATH=$TOOLCHAIN/bin:$PATH
export AR=arm-linux-androideabi-ar
export CC=arm-linux-androideabi-gcc
export CXX=arm-linux-androideabi-g++
export LINK=arm-linux-androideabi-g++
export PLATFORM=android
if [[ $2 == 'gyp' ]]
  then
    ./gyp_uv.py -Dtarget_arch=arm -DOS=android -f make-android
fi
```

then when I run the shell script 

`
source ./android-configure $NDK_PATH gyp && make -C out
`
and make command failed that 
```
make: *** No rule to make target `/home/mark/libuv-1.12.0/out/Debug/obj.target/libuv/src/unix/pthread-barrier.csrc/unix/procfs-exepath.o', needed by `/home/mark/libuv-1.12.0/out/Debug/obj.target/libuv.a'.  Stop.
make: Leaving directory `/home/mark/libuv-1.12.0/out'
```
/home/mark is the HOME directory  and I compile libuv on Ubunutu 16.04
the obj file is dependent by libuv.a which does not built yet.  
I compile the libuv with version of 1.12.0 and NDK 14.1.3816874

**Comment by fanzhengchen** [comment]
I compile libuv successfully with version of 1.11.0 and obtain a static library libuv.a

**Comment by cjihrig** [comment]
`src/unix/procfs-exepath.c` is a new file. Does adding it around [here](https://github.com/libuv/libuv/blob/f2756500ed8fc14ba11cf5bf0a3cee6f3b66eecb/Makefile.am#L332-L338) help?

**Comment by fanzhengchen** [comment]
In libuv.target.mk the line $(obj).target/$(TARGET)/src/unix/pthread-barrier.csrc/unix/procfs-exepath.o  maybe a mistake. I shall be 
```
$(obj).target/$(TARGET)/src/unix/pthread-barrier.o
$(obj).target/$(TARGET)/src/unix/procfs-exepath.o
```
I sugguest that the libuv.target.mk generated by gyp has made a mistake
