### ISSUE TITLE
Make 'subclasses' actual subclasses when compiling with C++?

### ISSUE THREAD

**Issue by jmgao** [libuv/libuv#1378]
Right now, to use libuv APIs with C++ (or with C with -Wall), it's necessary to do manual casts to use functions defined for base classes with their specializations. There's nothing that can be done about this for C users, but it should be possible to make this better in C++-land.

As an strawman example (there's probably a better way of doing things than this), the current definitions:
```c
struct uv_handle_s {
  UV_HANDLE_FIELDS
};

struct uv_stream_s {
  UV_HANDLE_FIELDS
  UV_STREAM_FIELDS
};

struct uv_pipe_s {
  UV_HANDLE_FIELDS
  UV_STREAM_FIELDS
  int ipc; /* non-zero if this pipe is used for passing handles */
  UV_PIPE_PRIVATE_FIELDS
};
```

could become something along the lines of:
```c++
#if defined(__cplusplus)
#define C_STRUCT_NAME(name) __c_ ## name
#else
#define C_STRUCT_NAME(name) name
#endif

struct C_STRUCT_NAME(uv_handle_s) {
  UV_HANDLE_FIELDS
};

struct C_STRUCT_NAME(uv_stream_s) {
  UV_HANDLE_FIELDS
  UV_STREAM_FIELDS
};

struct C_STRUCT_NAME(uv_pipe_s) {
  UV_HANDLE_FIELDS
  UV_STREAM_FIELDS
  int ipc;
  UV_PIPE_PRIVATE_FIELDS
};

#if defined(__cplusplus)
struct uv_handle_s {
  UV_HANDLE_FIELDS
};
struct uv_stream_s : public uv_handle_s {
  UV_STREAM_FIELDS
};
struct uv_pipe_s : public uv_stream_s {
  int ipc;
  UV_PIPE_PRIVATE_FIELDS
};
static_assert(sizeof(uv_handle_s) == sizeof(C_STRUCT_NAME(uv_handle_s)));
static_assert(sizeof(uv_stream_s) == sizeof(C_STRUCT_NAME(uv_stream_s)));
static_assert(sizeof(uv_pipe_s) == sizeof(C_STRUCT_NAME(uv_pipe_s)));
// with the assumption that sizeof being the same implies that the internal layout is the same
// TODO: find the actual language rules to support this
#endif
```

It adds a bit of noise to the header, but in my opinion, it's a pretty substantial quality of life/safety improvement for people using libuv from C++. Would you be interested in patches that implement something along these lines?

**Comment by cjihrig** [comment]
Do any of the projects listed in https://github.com/libuv/libuv/wiki/Projects-that-use-libuv accomplish something similar?

**Comment by jmgao** [comment]
uvw wraps all of the libuv's types in its own parallel inheritance hierarchy, which solves the problem, but it also doesn't expose any of the libuv types and the README says it doesn't expose everything in libuv (and new APIs that get added obviously won't immediately show up there).

Looking at node.js, there's over a hundred instances of `reinterpret_cast<uv_`, and I can count maybe 5 that are actually needed (and those might only be needed because the handles were stored as `uv_handle_t*` to avoid doing even more casts)

**Comment by bnoordhuis** [comment]
I remember we (@saghul, @piscisaureus and yours truly, IIRC?) discussed something similar years ago but we concluded it would be one giant slippery slope.  You start with a simple inheritance tree, but then comes proper RAII because that is what C++ programmers expect, copy constructors for non-trivially copyable types, and so on.  It would also make ABI stability that much harder.

**Comment by jmgao** [comment]
> yours truly, IIRC?

I don't think so, the first time I've actually taken a look into libuv was this week. (Thanks for the awesome library by the way!)

> we concluded it would be one giant slippery slope. You start with a simple inheritance tree, but then comes proper RAII because that is what C++ programmers expect, copy constructors for non-trivially copyable types, and so on.

I think there's a significant difference in the cost/benefit ratio for those other things, though. The cost seems relatively low (I think this is way closer in scope to wrapping your declarations with `extern "C"` than any of those other things), and it's basically impossible to use libuv without casting between these types, as is.

> It would also make ABI stability that much harder.
Do you mean that it would make changing the definitions of the structs harder? Isn't that essentially impossible already, since all of the struct definitions are public?

If you mean maintaining compatibility between C and C++, that depends on whether you consider a static_assert per type as being good enough of a check. I'll do some reading of the standards and ask some people who would know better than I tomorrow. (I think in practice, no platform is crazy enough to make it not enough, but you never know...)

The `UV_*_FIELDS` macros could also be turned into X-macros that could be used to assert that every field is in the right spot, but it'd be a bit messier:

```c++
#define UV_FOO_FIELDS \
    UV_FIELD_DECL(int, foo1); \
    UV_FIELD_DECL(char, foo2);

#define UV_BAR_FIELDS \
    UV_FIELD_DECL(int, bar1); \
    UV_FIELD_DECL(char, bar2);

#define UV_FIELD_DECL(type, name) type name
struct C_STRUCT_NAME(uv_foo_s) {
  UV_FOO_FIELDS
};
struct C_STRUCT_NAME(uv_bar_s) {
  UV_BAR_FIELDS
};

#if defined(__cplusplus)
struct uv_foo_s {
  UV_FOO_FIELDS
};
struct uv_bar_s : public uv_foo_s {
  UV_BAR_FIELDS
};

#undef UV_FIELD_DECL
#define UV_FIELD_DECL(type, name) static_assert(offsetof(uv_foo_s, name) == offsetof(uv_bar_s, name))
UV_FOO_FIELDS
```

Now that I've typed it out, it's not quite as bad as I was expecting? YMMV.

**Comment by bnoordhuis** [comment]
'Yours truly' means 'me'. :-)

> Do you mean that it would make changing the definitions of the structs harder? Isn't that essentially impossible already, since all of the struct definitions are public?

I was referring to non-trivial types (types with constructors/destructors, methods or containing non-trivial / non-default-constructible types); those impose additional ABI restrictions that plain structs don't.

> I think there's a significant difference in the cost/benefit ratio for those other things, though.

Right, but it's almost a dead certainty that other programmers will feel differently and make passionate arguments that, since libuv supports C++ language feature X, it should also support feature Y because valid reason Z.  That's the slippery slope.

**Comment by jmgao** [comment]
> 'Yours truly' means 'me'. :-)

Oops, my reading comprehension abilities at 2 AM isn't the greatest.

> I was referring to non-trivial types (types with constructors/destructors, methods or containing non-trivial / non-default-constructible types); those impose additional ABI restrictions that plain structs don't.

Ah. Well, don't do that, then? :-)

> Right, but it's almost a dead certainty that other programmers will feel differently and make passionate arguments that, since libuv supports C++ language feature X, it should also support feature Y because valid reason Z. That's the slippery slope.

Sure, I think it should be up to whether you think this is beneficial enough to be worth the cost (including the cost of saying no to annoying C++ zealots like myself).

**Comment by cjihrig** [comment]
I'm going to close this. It sounds like the decision has been made. If I'm wrong, feel free to reopen.

**Comment by dharesign** [comment]
How about providing a bunch of overloads for casting, which allows C++ users to avoid having to do a C-style cast or reinterpret_cast directly:

```
uv_handle_t *uv_handle_cast(uv_stream_t *handle) {
    return (uv_handle_t *)handle;
}
// etc...
```

Then users could simply do:

```
uv_close(uv_handle_cast(&streamHandle), nullptr);
```

**Comment by saghul** [comment]
TBH I'd rather see that as a standalone (maybe even header only) little library rather than in libuv per se.

**Comment by dharesign** [comment]
Maybe it'd actually be better if there were just overloads of all the `uv_handle_t` methods:

```
int uv_is_active(const uv_handle_t *handle);
int uv_is_active(const uv_stream_t *handle);
...
int uv_close(uv_handle_t *handle, uv_close_cb close_cb);
int uv_close(uv_stream_t *handle, uv_close_cb close_cb);
  // Note: 'close_cb' takes a 'uv_handle_t *' still, not 'uv_stream_t *'.
...
```

**Comment by jmgao** [comment]
I've been using the following in the codebase that I'm rewriting to use libuv:

```cpp
template <typename T>
struct uv_cast;

#define ALLOW_CAST(FromType) \
  explicit uv_cast(FromType from) : value(reinterpret_cast<decltype(value)>(from)) {}

template <>
struct uv_cast<uv_handle_t*> {
  ALLOW_CAST(uv_async_t*);
  ALLOW_CAST(uv_stream_t*);
  ALLOW_CAST(uv_pipe_t*);
  ALLOW_CAST(uv_tcp_t*);

  operator uv_handle_t*() { return value; }

  uv_handle_t* value;
};

template <>
struct uv_cast<uv_stream_t*> {
  ALLOW_CAST(uv_pipe_t*);
  ALLOW_CAST(uv_tcp_t*);

  operator uv_stream_t*() { return value; }

  uv_stream_t* value;
};
```

**Comment by ADENHAM** [comment]
FBI is now watching my home, home server, and phone and the emails that's
been sent and by whom. Lots of cyber crime going on. Leave me alone

Be blessed.

On Jul 26, 2017 11:31 AM, "Daryl Haresign" <notifications@github.com> wrote:

How about providing a bunch of overloads for casting, which allows C++
users to avoid having to do a C-style cast or reinterpret_cast directly:

uv_handle_t *uv_handle_cast(uv_stream_t *handle) {
    return (uv_handle_t *)handle;
}
// etc...

Then users could simply do:

uv_close(uv_handle_cast(&streamHandle), nullptr);

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/libuv/libuv/issues/1378#issuecomment-318108810>, or mute
the thread
