### ISSUE TITLE
[info] LICENSE for logo

### ISSUE THREAD

**Issue by skypjack** [libuv/libuv#1379]
I'm the maintainer of `uvw`. I'd like to create a simple logo for the project and add it to the `README`. The idea was to create it out of the one of `libuv`.  
Because of that I want to know exactly what license is applied to the logo, the MIT one or the CC BY 4.0 license?  
In other terms, can I freely use the unicorn velociraptor for that? If yes, have you any preference regarding the logo?  
Note that my sole purpose is to recall to the mind that `libuv` is the engine that runs under the hood. If you prefer not to have your logo used in another project, there are no problems. I can do it differently.  
I'm looking forward to having a feedback from you. Thank you in any case.

**Comment by saghul** [comment]
Given It's not code I'd say CC-BY-4.0. Since @indutny and I were involved in the logo, WDYT Fedor?

**Comment by indutny** [comment]
I agree.

**Comment by skypjack** [comment]
So far so good. I can use it because of the license and I know what are the terms now.
Is there any problem if I do that? I mean, I can use the logo of libuv, but if you don't agree I can do it differently.
Do I have your approval?

**Comment by indutny** [comment]
@skypjack As long as it doesn't violate [license][https://creativecommons.org/licenses/by/4.0/] - I don't see any problem with this.

**Comment by skypjack** [comment]
It sounds good. Then I'll be back when published to check with you if it violates the license.
Thank you very much.

**Comment by skypjack** [comment]
If you haven't comments to add, we can close the issue.

**Comment by saghul** [comment]
Thanks for asking, much appreciated!
