### ISSUE TITLE
Windows DLL Version Information

### ISSUE THREAD

**Issue by genio** [libuv/libuv#1382]
In the [Windows builds](http://dist.libuv.org/dist/v1.12.0/) you guys provide, would it be possible to get the version information and other metadata filled in directly in the DLL so commands like ``` (Get-Command "C:\Program Files\libuv\libuv.dll").Version``` will function as expected?

**Comment by bnoordhuis** [comment]
I think the answer is 'kind of.'  Adding the major version is relatively straightforward (see diff) but minor and patch needs changes to [libuv-release-tool](https://github.com/libuv/libuv-release-tool) or it's going to be a maintenance hassle.
```diff
diff --git a/uv.gyp b/uv.gyp
index 55edf22..0187d11 100644
--- a/uv.gyp
+++ b/uv.gyp
@@ -1,4 +1,8 @@
 {
+  'variables': {
+    # Must correspond with UV_VERSION_MAJOR in include/uv-version.h.
+    'uv_version_major': '1',
+  },
   'target_defaults': {
     'conditions': [
       ['OS != "win"', {
@@ -66,6 +70,11 @@
           }],
         ],
       },
+      'msvs-settings': {
+        'VCLinkerTool': {
+          'Version': '<(uv_version_major)',
+        },
+      },
       'sources': [
         'common.gypi',
         'include/uv.h',
@@ -191,10 +200,7 @@
               ],
             }],
             ['uv_library=="shared_library" and OS!="mac" and OS!="os390"', {
-              # This will cause gyp to set soname
-              # Must correspond with UV_VERSION_MAJOR
-              # in include/uv-version.h
-              'product_extension': 'so.1',
+              'product_extension': 'so.<(uv_version_major)',
             }],
           ],
         }],
```

**Comment by saghul** [comment]
@bnoordhuis I'd be +1 to adding that. Right now that must be changed manually for major versions anyway.

**Comment by genio** [comment]
A ```pkgconfig/libuv.pc``` would be awesome as well :)

**Comment by bnoordhuis** [comment]
I think this would still be good to have, reopening.

**Comment by bnoordhuis** [comment]
No one else requested this in the five years since this issue was opened and we later "solved" it pragmatically by no longer distributing a DLL. I'll go ahead and close it out.
