### ISSUE TITLE
fs_event watcher stops calling callback after first file modification

### ISSUE THREAD

**Issue by bopwerks** [libuv/libuv#1383]
The `fs_event` watcher seems to get in a bad state after invoking the event callback with a `UV_RENAME` `events` parameter, and will not trigger the callback on subsequent changes to the watched file.

The first time this problem occurred, I noticed that if I modified the watched file with `emacs`, the callback was invoked twice, and each time the `events` parameter in the callback was set to `UV_CHANGE`. This worked fine; the callback would be invoked each time I wrote the file with `emacs`.

However, if I used `vim` or `sed -i` to modify the file, the callback seems to be triggered 4 times with the following `events`: `UV_RENAME`, `UV_CHANGE`, `UV_RENAME`, `UV_RENAME`.

After rebooting my machine, even writing the file with `emacs` causes the callback to be invoked once, and no more after that. The problem seems to persist whether I use a debug or release build. Here's a minimal test program:

```
#include <stdio.h>
#include <stdlib.h>
#include <uv.h>

static void on_change(uv_fs_event_t *handle, const char *path, int events, int status);

static uv_fs_event_t handle;

int
main(int argc, char *argv[])
{
    if (argc != 2) {
        fprintf(stderr, "Usage: %s filename\n", argv[0]);
        return EXIT_FAILURE;
    }
    uv_fs_event_init(uv_default_loop(), &handle);
    uv_fs_event_start(&handle, on_change, argv[1], UV_FS_EVENT_RECURSIVE);
    uv_run(uv_default_loop(), UV_RUN_DEFAULT);
    uv_loop_close(uv_default_loop());
    return EXIT_SUCCESS;
}

static void
on_change(uv_fs_event_t *handle, const char *path, int events, int status)
{
    char buf[128];
    size_t len;

    len = 0;
    if (events & UV_CHANGE)
        len += sprintf(buf, "UV_CHANGE");
    if (events & UV_RENAME) {
        if (len > 0)
            len += sprintf(buf+len, " | ");
        sprintf(buf+len, "UV_RENAME");
    }
    fprintf(stderr, "%s\n", buf);
}
```
Example output:
```
$ touch hello.txt
$ ./eventtest hello.txt # then modify the file with emacs
UV_RENAME
# C-c
$ ./eventtest hello.txt # then modify the file with vim or sed
UV_RENAME
UV_CHANGE
UV_RENAME
UV_RENAME
# C-c
```
I built `libuv` using GYP, and used this `gcc` incantation to compile and link the test program:
```
gcc -Wl,-export-dynamic -o eventtest eventtest.c ./lib/libuv/out/Debug/libuv.a -lpthread -ldl -I./lib/libuv/include -Wall -Werror -g
```
Let me know if there's any other information I can provide that might help. Thanks.

* **Version**: v1.x
* **Commit**: f2756500ed8fc14ba11cf5bf0a3cee6f3b66eecb
* **Platform**: Linux vagrant 3.13.0-103-generic #150-Ubuntu SMP Thu Nov 24 10:34:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 14.04)
* **Compiler**: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by bopwerks** [comment]
I tried monitoring the file using `inotifywait`. Here's the output from when I open and edit the file with `vim`:
```
$ inotifywait -m ./hello.txt
Setting up watches.
Watches established.
./hello.txt OPEN
./hello.txt CLOSE_NOWRITE,CLOSE 
./hello.txt OPEN 
./hello.txt ACCESS 
./hello.txt CLOSE_NOWRITE,CLOSE 
./hello.txt MOVE_SELF 
./hello.txt ATTRIB 
./hello.txt DELETE_SELF 
```
And here's the output when I open and edit with `emacs`:
```
$ inotifywait -m ./hello.txt
Setting up watches.
Watches established.
./hello.txt OPEN 
./hello.txt ACCESS 
./hello.txt CLOSE_NOWRITE,CLOSE 
./hello.txt MOVE_SELF 
```
So it seems that DELETE_SELF and MOVE_SELF events are generated by `inotify` on file modification, and these events cause monitoring to stop. It would be easy enough for `libuv` to relaunch the file watcher if the file still exists, but perhaps it's a user responsibility?

**Comment by bnoordhuis** [comment]
Yes, pretty much.  File monitoring is intrinsically race-y.  There is a time gap between the event and the action that caused the event wherein the watched file may have changed again.  Libuv doesn't make policy on what to do in such cases, it leaves that up to the user.

**Comment by bopwerks** [comment]
Fair enough! Thanks :)
