### ISSUE TITLE
[1.12.0] [linux] uv_interface_addresses failed to get right physical address

### ISSUE THREAD

**Issue by jack2007** [libuv/libuv#1384]
Hi,
When I prepare upgrade to 1.12.0, I find that uv_interface_addresses is not working properly on linux.
my card mac address is 56:00:00:76:27:4f, but with uv_interface_addresses I get  00:00:00:00:54:00
```
ip addr show
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 56:00:00:76:27:4f brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/23 brd 45.63.59.255 scope global eth0
    inet6 fe80::5400:ff:fe76:274f/64 scope link
       valid_lft forever preferred_lft forever
```

when I run _run-tests_ , I get the following output
```
uv_interface_addresses:
name: eth0
internal: 0
physical address: 00:00:00:00:54:00
address: xx.xx.xx.xx
netmask: 255.255.254.0
```
I make a test comparison between 1.11.0 and 1.12.0, and 1.11.0 works correctly.

I make a code comparison between 1.11.0 and 1.12.0, and find the cause:

1.11.0 linux-core.c  944-949
```
  for (ent = addrs; ent != NULL; ent = ent->ifa_next) {
    if (!((ent->ifa_flags & IFF_UP) && (ent->ifa_flags & IFF_RUNNING)) ||
        (ent->ifa_addr == NULL) ||
        (ent->ifa_addr->sa_family != PF_PACKET)) {
      continue;
    }
```

1.12.0 linux-core.c 913-915
```
  for (ent = addrs; ent != NULL; ent = ent->ifa_next) {
    if (uv__ifaddr_exclude(ent))
      continue;
```

then I get into uv__ifaddr_exclude, 
```
static int uv__ifaddr_exclude(struct ifaddrs *ent) {
  if (!((ent->ifa_flags & IFF_UP) && (ent->ifa_flags & IFF_RUNNING)))
    return 1;
  if (ent->ifa_addr == NULL)
    return 1;
  if (ent->ifa_addr->sa_family == PF_PACKET)
    return 1;
  return 0;
}
```

Look out , in 1.11.0 when copy the physical address, the filter is _ent->ifa_addr->sa_family != PF_PACKET_ , which in 1.12.0 it becomes _ent->ifa_addr->sa_family == PF_PACKET_ .
I make a change on my local libuv code, and it works fine now.

**Comment by bnoordhuis** [comment]
Known issue, will be fixed in the next libuv release, see #1375.  Thanks for the bug report though.
