### ISSUE TITLE
`getaddrinfo_fail` failed: exit code 134 while running make check

### ISSUE THREAD

**Issue by Ecno92** [libuv/libuv#139]
```
[%  61|+ 151|-   0|T   0|S   0]: getaddrinfo_fail
`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
=============================================================
[% 100|+ 244|-   1|T   0|S   0]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:3796: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/username/Code/libuv'
Makefile:4052: recipe for target 'check-am' failed
```

When running `make check` if fails with this output. It fails both on v1.2.1 and the latest master. 
I've used autotools and gyp on a Ubuntu 14.10 system, but it makes no difference for the failing test. 

Any ideas why this test fails?

**Comment by saghul** [comment]
Where are you running the tests? The test which fails for you tests that getaddrinfo fails when trying to resolve "xyzzy.xyzzy.xyzzy", which obviously doesn't exist, so it must be something in your network configuration, I suppose.

**Comment by Ecno92** [comment]
After reading your comment I ended up here: https://github.com/joyent/libuv/issues/974
It seems that "xyzzy.xyzzy.xzzy" also resolves for me if I use my home network. 
When I use the mobile network of my phone it resolves without any failing tests. 

I don't know any solution to work around this problem if the network resolves things that should not resolve. 

If more people expirience this problem it may be an idea to print an additional message which references this or a similair issue report. It also may be to much... What do you think?

**Comment by saghul** [comment]
Honestly, I think that's too much. It does happen, but very rarely. I suggest you change your name servers though :-)
