### ISSUE TITLE
stderr: libuv/src/unix/stream.c:1396: uv_write2: Assertion

### ISSUE THREAD

**Issue by 2002demon** [libuv/libuv#1392]
Hello,
my system is debian 8 64 bit with node 8, **libuv 1.12**.
I have daily worker crash with this error:
stderr: libuv/src/unix/stream.c:1396: uv_write2: Assertion `(stream->type == UV_TCP || stream->type == UV_NAMED_PIPE || stream->type == UV_TTY) && "uv_write (unix) does not yet support other types of streams"' failed.
Error: child process exited [id:fjwvfqjw#1, code:null, signal:SIGABRT]

What can be reason of it?
Please help.

**Comment by saghul** [comment]
Looks like you are trying to send a handle type which we don't support. How does your code look like? What handle are you trying to send with uv_write2?

**Comment by 2002demon** [comment]
I just use mediasoup library that usees libuv, i think this is the worker class:
https://github.com/versatica/mediasoup/blob/master/lib/Worker.js

From where is called uv_write2 function? Can we ignore or catch bad unsupportet types?
(if there does not give us new problems)

**Comment by saghul** [comment]
Heh, mediasoup is written by my good friend @ibc :-) AFAIK it doesn't do anything wrong, but maybe there is a race and an uninitialized handle gets passed or something alike. At any rate, you are better off reporting it to mediasoup since there is no actionable item here in libuv. Cheers!
