### ISSUE TITLE
Libuv thread does work sometimes and sometimes not.

### ISSUE THREAD

**Issue by nomonstershit** [libuv/libuv#1393]
I have found an thread example using libuv on the internet but it sometimes work and sometimes not. See the picture for details
here is the project file (for 30 days)
https://ufile.io/ge2rc
here is the image explaining stuff
https://ufile.io/bk4ye

* **Version**: libuv-x64-v1.9.1.build10.exe
* **Platform**: Windows 10 x64
* **Visual Studio Version**: 2015
* **Project Settings**: x64
downloaded libuv from http://dist.libuv.org/dist/v1.9.1/

ps:is there any way to upload project file and image to github so it can be accesisble even after 30 days?

**Comment by bnoordhuis** [comment]
Please post questions to https://github.com/libuv/help, that's what it's for.
