### ISSUE TITLE
Process title setting inconsistencies between platforms

### ISSUE THREAD

**Issue by 64** [libuv/libuv#1395]
The first issue is that `uv_set_process_title` [is thread safe on windows](https://github.com/libuv/libuv/blob/v1.x/src/win/util.c#L406-L409), [on unix it is not.](https://github.com/libuv/libuv/blob/master/src/unix/proctitle.c#L82) By the looks of things this was mentioned a few years ago in https://github.com/libuv/libuv/issues/271.

The second issue is that`uv_setup_args` on unix cheats a little bit and [reuses the pointer from `argv[0]`](https://github.com/libuv/libuv/blob/master/src/unix/proctitle.c#L51). This would probably be fine if every time the arguments passed in were the same ones directly passed down from `main`, but that's not always the case. If a user for whatever reason passes in a pointer to some memory which they later free, calling `uv_get_process_title` would then read from invalid memory. The fix for this would be to make a copy of the string and set that as the title instead.

Even if these things aren't going to be addressed I would still recommend that some sort of warning be added to the documentation to avoid future confusion.

**Comment by bnoordhuis** [comment]
A documentation pull request would be welcome.  A fix for #271 is most welcome too.
