### ISSUE TITLE
threadpool_multiple_event_loops fails on Linux/ppc musl

### ISSUE THREAD

**Issue by awilfox** [libuv/libuv#1398]
On a Linux computer with a PowerPC CPU using the musl libc, the `threadpool_multiple_event_loops` test fails.  This does not happen on an x86_64 Linux using the musl libc, nor does it happen on a PowerPC Linux using glibc.

```
awilcox on elaine ~/aports/main/libuv/src/libuv-v1.12.0/test $ ./run-tests threadpool_multiple_event_loops
not ok 1 - threadpool_multiple_event_loops
# exit code 6
# Output from process `threadpool_multiple_event_loops`:
# Assertion failed in test/test-thread.c on line 79: status == 0
```

I am not sure if this is a bug in libuv or if it is a bug in musl libc.

* **Version**: 1.12.0
* **Platform**: `Linux elaine 4.5.0 #1 SMP Sat Feb 6 18:32:12 AEDT 2016 ppc Linux`

**Comment by bnoordhuis** [comment]
That assertion means a uv_getaddrinfo() call for localhost failed for some reason.  Hope that points you in the right direction because I'm afraid I can't investigate myself.  Maybe try printing the status code.

**Comment by awilfox** [comment]
Yeah, that did help.  `status == -3001`, or `UV_EAI_AGAIN`.  I ended up finding out that this is actually a really weird "perfect storm" of conditions:

* My ISP intercepts DNS requests (to attempt to show ads when domains can't be found).
* During network maintenance their interception engine was corrupting some of the responses.
* When musl found the corrupted responses it considered it the same as SERVFAIL (even though it wasn't SERVFAIL, the length didn't match the actual bytes on the wire); which it then returns as EAI_AGAIN.
* `uv_getaddrinfo` was then returning `UV_EAI_AGAIN`.

Running the test on a PowerPC machine on a different network fixed this.  Apologies for the noise!
