### ISSUE TITLE
UDP recv data in wrong handle!

### ISSUE THREAD

**Issue by redxu** [libuv/libuv#1399]
Version: 1.12.0
Platform:Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux (Windows also have same problem)

Hi:
     my program like a echo-server-client, there are hundreds client in program, each client has it's own uv_udp_t handle, each client send data to server and deal server reply. 
     for example client 1 send data 1 to server,and server reply 1 to client 1.but in my code i found that 
 sometimes client n recv data not equal n, I debug the route found client A send data used it's own handle A,but reply data maybe on handle A or handle B in other client.
    there is my test code,tested on linux debian.in "client_recv_cb" i valid the data. it's there anything in my code?

[udp_echo.zip](https://github.com/libuv/libuv/files/1117644/udp_echo.zip)

**Comment by bnoordhuis** [comment]
Please post questions to https://github.com/libuv/help/issues.
