### ISSUE TITLE
uv_default_loop is never deleted

### ISSUE THREAD

**Issue by mad-rain** [libuv/libuv#140]
Hi,

I have found memory leak in libuv under Ubuntu Linux:

libuv/src/unix/core.c:741:
    watchers = realloc(loop->watchers, (nwatchers + 2) * sizeof(loop->watchers[0]));

After looking into source code. I relalized that default loop is actually never got deleted.

Is it ok to call uv_loop_close for default loop at the end of main?

Thanks.

**Comment by saghul** [comment]
Yes, you can close the default loop just like any other loop. When you call `uv_loop_close` the watchers array is freed, thus there is no real leak.

**Comment by mad-rain** [comment]
I think something is wrong here. 

I haven't created default loop, why should explicitly close it?

Also there is not mention about this behaviour in documentation or header files, and there is no any  guarentees that the behaviour won't be changed in future.

**Comment by bnoordhuis** [comment]
> I haven't created default loop

It's created when you call uv_default_loop() for the first time.

> why should explicitly close it?

Because libuv can't tell when you're done with it.

> Also there is not mention about this behaviour in documentation or header files

It looks like it.  Want to file a PR?

**Comment by saghul** [comment]
> Also there is not mention about this behaviour in documentation or header files, and there is no any guarentees that the behaviour won't be changed in future.

What is the undocumented behavior? The fact that `uv_default_loop` creates a new loop? Its documentation could use some clarification ideed. FWIW, the default loop is no longer "special" in any way, other than being accessible through that function.

**Comment by mad-rain** [comment]
Yes, uv_default_loop creates a new loop. But calling it 100 times, doesn't create 100 loops, right? Sure, because its a singleton. But very strange kind of singleton with implicit creation and explicit destruction.

I have checked out tests, there is no call of uv_loop_close for default loop. I believe that every single example with default loop on the net contains this bug.

**Comment by mad-rain** [comment]
I found out that MAKE_VALGRIND_HAPPY is actually closing default loop. I thought before that this macro is unrelated to UV.

**Comment by saghul** [comment]
Most if not all examples out there don't indeed close libuv loops. However, this is not a problem most of the time, since the loop's lifetime is tied to the application, so when it ends the OS would free al resources.

I opened a PR which hopefully helps clarify this: https://github.com/libuv/libuv/pull/147

**Comment by mad-rain** [comment]
Thank you so much!
