### ISSUE TITLE
[doc] uv_timer_start for active timer

### ISSUE THREAD

**Issue by moteus** [libuv/libuv#1401]
Documentation does not mention this case.
I think this [commit](https://github.com/libuv/libuv/commit/028fef84b8244501f644732b83a2faaef3600820) describe curren bihavior

**Comment by cjihrig** [comment]
Would you care to open a documentation PR?

**Comment by vcunat** [comment]
@cjihrig: here https://github.com/libuv/libuv/pull/1538
