### ISSUE TITLE
make check fails 

### ISSUE THREAD

**Issue by richardpringle** [libuv/libuv#1402]
* **Version**: 
v1.3.0 ([uvbook](https://github.com/nikhilm/uvbook) master branch)
* **Platform**: 
```
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```
Error from `make check`:
```bash
[%  90|+ 227|-   0|T   0|S   0]: fs_event_error_reporting
`fs_event_error_reporting` failed: exit code 6
Output from process `fs_event_error_reporting`: (no output)
```

**Comment by richardpringle** [comment]
let me know if this has been solved or you need more info

**Comment by cjihrig** [comment]
> v1.3.0 (uvbook master branch)

The uvbook was recently added to our documentation. Can you try with the latest `v1.x` branch from this repo.

**Comment by richardpringle** [comment]
thanks @cjihrig
