### ISSUE TITLE
Adding Complete Haiku Support

### ISSUE THREAD

**Issue by CodeforEvolution** [libuv/libuv#1414]
Hello! I'm working on finishing Haiku support to the point where Haiku should support all functions except fs events. I have gotten pretty far, though now need to put my changes on an actual git repo. The one problem I'm having is when running the test, I'm getting undefined references to functions such as uv__strdup. Any ideas?

**Comment by bnoordhuis** [comment]
Can you post the build output?  Are you using uv__strdup() in tests?

**Comment by CodeforEvolution** [comment]
Well, I'm just running the tests through "make check" on the libuv source. Otherwise I attatched logs of the build and check, I can get a more verbose log if need be.

**Comment by CodeforEvolution** [comment]
Log for build:
  CC       src/libuv_la-fs-poll.lo
  CC       src/libuv_la-inet.lo
  CC       src/libuv_la-threadpool.lo
  CC       src/libuv_la-uv-common.lo
  CC       src/libuv_la-version.lo
  CC       src/unix/libuv_la-async.lo
  CC       src/unix/libuv_la-core.lo
  CC       src/unix/libuv_la-dl.lo
  CC       src/unix/libuv_la-fs.lo
  CC       src/unix/libuv_la-getaddrinfo.lo
  CC       src/unix/libuv_la-getnameinfo.lo
  CC       src/unix/libuv_la-loop-watcher.lo
  CC       src/unix/libuv_la-loop.lo
  CC       src/unix/libuv_la-pipe.lo
  CC       src/unix/libuv_la-poll.lo
  CC       src/unix/libuv_la-process.lo
  CC       src/unix/libuv_la-signal.lo
  CC       src/unix/libuv_la-stream.lo
  CC       src/unix/libuv_la-tcp.lo
  CC       src/unix/libuv_la-thread.lo
  CC       src/unix/libuv_la-timer.lo
  CC       src/unix/libuv_la-tty.lo
  CC       src/unix/libuv_la-udp.lo
  CC       src/unix/libuv_la-bsd-ifaddrs.lo
  CXX      src/unix/haiku.lo
  CC       src/unix/libuv_la-no-fsevents.lo
  CC       src/unix/libuv_la-posix-hrtime.lo
  CC       src/unix/libuv_la-posix-poll.lo
  CXXLD    libuv.la

Log for check:
make  test/run-tests
make[1]: Entering directory '/boot/home/Desktop/libuv'
  CC       test/test_run_tests-blackhole-server.o
  CC       test/test_run_tests-dns-server.o
  CC       test/test_run_tests-echo-server.o
  CC       test/test_run_tests-run-tests.o
  CC       test/test_run_tests-runner.o
  CC       test/test_run_tests-test-active.o
  CC       test/test_run_tests-test-async.o
  CC       test/test_run_tests-test-async-null-cb.o
  CC       test/test_run_tests-test-barrier.o
  CC       test/test_run_tests-test-callback-order.o
  CC       test/test_run_tests-test-callback-stack.o
  CC       test/test_run_tests-test-close-fd.o
  CC       test/test_run_tests-test-close-order.o
  CC       test/test_run_tests-test-condvar.o
  CC       test/test_run_tests-test-connection-fail.o
  CC       test/test_run_tests-test-cwd-and-chdir.o
  CC       test/test_run_tests-test-default-loop-close.o
  CC       test/test_run_tests-test-delayed-accept.o
  CC       test/test_run_tests-test-dlerror.o
  CC       test/test_run_tests-test-eintr-handling.o
  CC       test/test_run_tests-test-embed.o
  CC       test/test_run_tests-test-emfile.o
  CC       test/test_run_tests-test-env-vars.o
  CC       test/test_run_tests-test-error.o
  CC       test/test_run_tests-test-fail-always.o
  CC       test/test_run_tests-test-fs-event.o
  CC       test/test_run_tests-test-fs-poll.o
  CC       test/test_run_tests-test-fs.o
  CC       test/test_run_tests-test-fork.o
  CC       test/test_run_tests-test-get-currentexe.o
  CC       test/test_run_tests-test-get-loadavg.o
  CC       test/test_run_tests-test-get-memory.o
  CC       test/test_run_tests-test-get-passwd.o
  CC       test/test_run_tests-test-getaddrinfo.o
  CC       test/test_run_tests-test-gethostname.o
  CC       test/test_run_tests-test-getnameinfo.o
  CC       test/test_run_tests-test-getsockname.o
  CC       test/test_run_tests-test-handle-fileno.o
  CC       test/test_run_tests-test-homedir.o
  CC       test/test_run_tests-test-hrtime.o
  CC       test/test_run_tests-test-idle.o
  CC       test/test_run_tests-test-ip4-addr.o
  CC       test/test_run_tests-test-ip6-addr.o
  CC       test/test_run_tests-test-ipc-send-recv.o
  CC       test/test_run_tests-test-ipc.o
  CC       test/test_run_tests-test-loop-handles.o
  CC       test/test_run_tests-test-loop-alive.o
  CC       test/test_run_tests-test-loop-close.o
  CC       test/test_run_tests-test-loop-stop.o
  CC       test/test_run_tests-test-loop-time.o
  CC       test/test_run_tests-test-loop-configure.o
  CC       test/test_run_tests-test-multiple-listen.o
  CC       test/test_run_tests-test-mutexes.o
  CC       test/test_run_tests-test-osx-select.o
  CC       test/test_run_tests-test-pass-always.o
  CC       test/test_run_tests-test-ping-pong.o
  CC       test/test_run_tests-test-pipe-bind-error.o
  CC       test/test_run_tests-test-pipe-connect-error.o
  CC       test/test_run_tests-test-pipe-connect-multiple.o
  CC       test/test_run_tests-test-pipe-connect-prepare.o
  CC       test/test_run_tests-test-pipe-getsockname.o
  CC       test/test_run_tests-test-pipe-pending-instances.o
  CC       test/test_run_tests-test-pipe-sendmsg.o
  CC       test/test_run_tests-test-pipe-server-close.o
  CC       test/test_run_tests-test-pipe-close-stdout-read-stdin.o
  CC       test/test_run_tests-test-pipe-set-non-blocking.o
  CC       test/test_run_tests-test-platform-output.o
  CC       test/test_run_tests-test-poll-close.o
  CC       test/test_run_tests-test-poll-close-doesnt-corrupt-stack.o
  CC       test/test_run_tests-test-poll-closesocket.o
  CC       test/test_run_tests-test-poll.o
  CC       test/test_run_tests-test-process-title.o
  CC       test/test_run_tests-test-queue-foreach-delete.o
  CC       test/test_run_tests-test-ref.o
  CC       test/test_run_tests-test-run-nowait.o
  CC       test/test_run_tests-test-run-once.o
  CC       test/test_run_tests-test-semaphore.o
  CC       test/test_run_tests-test-shutdown-close.o
  CC       test/test_run_tests-test-shutdown-eof.o
  CC       test/test_run_tests-test-shutdown-twice.o
  CC       test/test_run_tests-test-signal-multiple-loops.o
  CC       test/test_run_tests-test-signal.o
  CC       test/test_run_tests-test-socket-buffer-size.o
  CC       test/test_run_tests-test-spawn.o
  CC       test/test_run_tests-test-stdio-over-pipes.o
  CC       test/test_run_tests-test-tcp-alloc-cb-fail.o
  CC       test/test_run_tests-test-tcp-bind-error.o
  CC       test/test_run_tests-test-tcp-bind6-error.o
  CC       test/test_run_tests-test-tcp-close-accept.o
  CC       test/test_run_tests-test-tcp-close-while-connecting.o
  CC       test/test_run_tests-test-tcp-close.o
  CC       test/test_run_tests-test-tcp-create-socket-early.o
  CC       test/test_run_tests-test-tcp-connect-error-after-write.o
  CC       test/test_run_tests-test-tcp-connect-error.o
  CC       test/test_run_tests-test-tcp-connect-timeout.o
  CC       test/test_run_tests-test-tcp-connect6-error.o
  CC       test/test_run_tests-test-tcp-flags.o
  CC       test/test_run_tests-test-tcp-open.o
  CC       test/test_run_tests-test-tcp-read-stop.o
  CC       test/test_run_tests-test-tcp-shutdown-after-write.o
  CC       test/test_run_tests-test-tcp-unexpected-read.o
  CC       test/test_run_tests-test-tcp-oob.o
  CC       test/test_run_tests-test-tcp-write-to-half-open-connection.o
  CC       test/test_run_tests-test-tcp-write-after-connect.o
  CC       test/test_run_tests-test-tcp-writealot.o
  CC       test/test_run_tests-test-tcp-write-fail.o
  CC       test/test_run_tests-test-tcp-try-write.o
  CC       test/test_run_tests-test-tcp-write-queue-order.o
  CC       test/test_run_tests-test-thread-equal.o
  CC       test/test_run_tests-test-thread.o
  CC       test/test_run_tests-test-threadpool-cancel.o
  CC       test/test_run_tests-test-threadpool.o
  CC       test/test_run_tests-test-timer-again.o
  CC       test/test_run_tests-test-timer-from-check.o
  CC       test/test_run_tests-test-timer.o
  CC       test/test_run_tests-test-tmpdir.o
  CC       test/test_run_tests-test-tty.o
  CC       test/test_run_tests-test-udp-alloc-cb-fail.o
  CC       test/test_run_tests-test-udp-bind.o
  CC       test/test_run_tests-test-udp-create-socket-early.o
  CC       test/test_run_tests-test-udp-dgram-too-big.o
  CC       test/test_run_tests-test-udp-ipv6.o
  CC       test/test_run_tests-test-udp-multicast-interface.o
  CC       test/test_run_tests-test-udp-multicast-interface6.o
  CC       test/test_run_tests-test-udp-multicast-join.o
  CC       test/test_run_tests-test-udp-multicast-join6.o
  CC       test/test_run_tests-test-udp-multicast-ttl.o
  CC       test/test_run_tests-test-udp-open.o
  CC       test/test_run_tests-test-udp-options.o
  CC       test/test_run_tests-test-udp-send-hang-loop.o
  CC       test/test_run_tests-test-udp-send-and-recv.o
  CC       test/test_run_tests-test-udp-send-immediate.o
  CC       test/test_run_tests-test-udp-send-unreachable.o
  CC       test/test_run_tests-test-udp-try-send.o
  CC       test/test_run_tests-test-walk-handles.o
  CC       test/test_run_tests-test-watcher-cross-stop.o
  CC       test/test_run_tests-runner-unix.o
  CCLD     test/run-tests
make[1]: Leaving directory '/boot/home/Desktop/libuv'
make  check-TESTS
make[1]: Entering directory '/boot/home/Desktop/libuv'
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:4520: recipe for target 'check-TESTS' failed
make[1]: Leaving directory '/boot/home/Desktop/libuv'
Makefile:4776: recipe for target 'check-am' failed

**Comment by bnoordhuis** [comment]
I don't see build or link errors.  When do you see those undefined reference errors?

**Comment by CodeforEvolution** [comment]
Oops, ended up I didn't make the output verbose enough take a look again specifically at the check log. This time, I attached the logs as text files due to a lot more output being included in these:
[log-build.txt](https://github.com/libuv/libuv/files/1137311/log-build.txt)
[log-check.txt](https://github.com/libuv/libuv/files/1137310/log-check.txt)

.

**Comment by bnoordhuis** [comment]
Thanks.  The relevant bits:
```
   CXX      src/unix/haiku.lo
...
runtime_loader: /boot/home/Desktop/libuv/.libs/libuv.so.1.0.0: Could not resolve symbol '_Z10uv__strdupPKc'
resolve symbol "_Z10uv__strdupPKc" returned: -2147478780
runtime_loader: /boot/home/Desktop/libuv/.libs/libuv.so.1.0.0: Troubles relocating: Symbol not found
```
You compiled a file as C++.  You probably `#include "internal.h"` or another header without wrapping it in `extern "C" { ... }`.

**Comment by CodeforEvolution** [comment]
That fixed it, the only problem now are the included libuv tests are running, but many are not passing with an error code 1536, is this normal or should this be looked at?

**Comment by bnoordhuis** [comment]
I don't know what that error code signifies.  Is that the exit code or something else?  Can you post the output of a complete run?

**Comment by CodeforEvolution** [comment]
Here, I have attached a log of all the checks running, hopefully this should help. By the way, I haven't implemented fs-events or the process title mechanism yet:
[log-check.txt](https://github.com/libuv/libuv/files/1146427/log-check.txt)

**Comment by bnoordhuis** [comment]
Right, it's the exit code.  The tests that print "Assertion failed" have failing checks, the ones that simply abort probably hit sanity checks in libuv itself.

Time to fire up your debugger.  You can run most tests in isolation with `run-tests <name> <name>`, e.g.`run-tests kill kill` to run just the kill test.

**Comment by CodeforEvolution** [comment]
After running through the debugger, it seems by looking at one test and examining others, I have found the problem. The error seems to come from MAKE_VALGRIND_HAPPY() in all the non-working tests. Does this function return any values?

**Comment by bnoordhuis** [comment]
No, it's a macro that cleans up the event loop.  You can find its definition in test/task.h.  It sounds like the uv_loop_close() call is failing.

**Comment by CodeforEvolution** [comment]
Ok, well I've been trying to debug the macro, but the platform debugger can't debug from within a macro...is their an alternative way to solve this problem?

**Comment by bnoordhuis** [comment]
Manually inline the macro in the test you want to debug and rebuild?

**Comment by CodeforEvolution** [comment]
That’d work now seeing, though it may be a while since I’m having some issues with my computer...
