### ISSUE TITLE
Call uv_fs_open faild

### ISSUE THREAD

**Issue by locobrain** [libuv/libuv#1420]
* **Version**: 1.13.1
* **Platform**: Windows 10 professional 15063

Call uv_fs_open failed, return UV_UNKNOWN. The file is a HID device file.
After traced calling back, I found call _open_osfhandle failed in fs__open and  GetLastError return ERROR_SUCCESS.
I think to implement a function like _open_osfhandle to solve this issue.
Thank you gread job.

**Comment by bnoordhuis** [comment]
That sounds like a bug in the CRT, the C runtime.  I don't know if libuv can do anything about that.

**Comment by bzoz** [comment]
@locobrain can you provide a minimal repro for the issue?

**Comment by vtjnash** [comment]
I think this may be fixed by #1166: `_open_osfhandle` is no longer part of the `uv_fs_open` code path.

**Comment by bnoordhuis** [comment]
Closing, no follow-up by OP.

**Comment by rc452860** [comment]
I have same problem,use uv_fs_open to open openvpn provide tap-windows will get same error. _open_osfhandle return -1 but GetLastError is ERROR_SUCCESS.
