### ISSUE TITLE
Windows - `search_path` crash when %Path% has ";";

### ISSUE THREAD

**Issue by refack** [libuv/libuv#1422]
* **Version**: 1.13.1
* **Platform**: Windows

I have a `node` snippet but I directly maps to `uv_spawn` -> [`seach_path`](https://github.com/libuv/libuv/blob/v1.x/src/win/process.c#L409)

```js
d:\code\node-cur$ node
> process.env.Path = String.raw`"";`
'"";'
> require('child_process').spawnSync('cmd.exe') !== null
true
> process.env.Path = String.raw`";";`
'";";'
> require('child_process').spawnSync('cmd.exe') !== null

d:\code\node-cur$ echo %ERRORLEVEL%
-1073741819
```

Now the even XP is EOL is there a reason not to use WIN32's [SearchPath](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365527(v=vs.85).aspx)

**Comment by refack** [comment]
> @refack great find. I've already started making a patch for that for libuv

 @bzoz any reason not to use WIN32's [SearchPath](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365527(v=vs.85).aspx)?

**Comment by bzoz** [comment]
TBH, I don't know `SearchPath`.

If you want go ahead and fix this. I have a test that dies with current implementation:

```c
TEST_IMPL(spawn_quoted_path) {
#ifndef _WIN32
  RETURN_SKIP("Test for Windows")
#else
  char* quoted_path_env[2];
  options.file = "not_existing";
  args[0] = options.file;
  args[1] = NULL;
  options.args = args;
  options.exit_cb = exit_cb;
  options.flags = 0;
  /* We test if search_path works correctly with semicolons in quoted path. */
  /* We will use invalid drive, so we are sure no executable is spawned */
  quoted_path_env[0] = "PATH=\"xyz:\\test;\";xyz:\\other";
  quoted_path_env[1] = NULL;
  options.env = quoted_path_env;

  /* We test if libuv will not segfaul */
  uv_spawn(uv_default_loop(), &process, &options);

  MAKE_VALGRIND_HAPPY();
  return 0;
#endif
}
```

**Comment by refack** [comment]
> TBH, I don't know SearchPath.
> 
> If you want go ahead and fix this. I have a test that dies with current implementation:
> 
> TEST_IMPL(spawn_quoted_path) {
> #ifndef _WIN32
>   RETURN_SKIP("Test for Windows")
> #else
>   char* quoted_path_env[2];
>   options.file = "not_existing";
>   args[0] = options.file;
>   args[1] = NULL;
>   options.args = args;
>   options.exit_cb = exit_cb;
>   options.flags = 0;
>   /* We test if search_path works correctly with semicolons in quoted path. */
>   /* We will use invalid drive, so we are sure no executable is spawned */
>   quoted_path_env[0] = "PATH=\"xyz:\\test;\";xyz:\\other";
>   quoted_path_env[1] = NULL;
>   options.env = quoted_path_env;
> 
>   /* We test if libuv will not segfaul */
>   uv_spawn(uv_default_loop(), &process, &options);
> 
>   MAKE_VALGRIND_HAPPY();
>   return 0;
> #endif
> }

Cool.
Let's do both, replacing the exsisting logic with [SearchPath](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365527(v=vs.85).aspx) might be `semver-major`

**Comment by saghul** [comment]
Yep, this should land in master.
