### ISSUE TITLE
There is a double CloseHandle in runner-win.c

### ISSUE THREAD

**Issue by tom-seddon** [libuv/libuv#1426]
* **Version**: 1.13.1
* **Platform**: Windows x64 build 1607; Visual Studio 2017

`process_copy_output` in `runner-win.c` creates a POSIX-style file descriptor from the process's stdout Win32 HANDLE using [`open_osfhandle`](https://msdn.microsoft.com/en-us/library/bdts1c9x.aspx), then closes the file descriptor, which closes the HANDLE. There's then a double close in `process_cleanup`. I imagine this normally isn't noticeable, but if you're running in the VS2017 debugger then it causes the process to stop in the debugger with a warning popup.

I don't know what the best solution for this is, but what I've done in my copy is make `process_copy_output` first duplicate the handle using [`DuplicateHandle`](https://msdn.microsoft.com/en-gb/library/windows/desktop/ms724251(v=vs.85).aspx). (See the code below. I also added a couple of fclose calls that looked to be missing.)

The tests then run to completion under the debugger without throwing up any obvious errors.

Thanks,

--Tom

```
int process_copy_output(process_info_t* p, FILE* stream) {
  char buf[1024];
  int fd, r;
  FILE* f;
  HANDLE dup;

  if (!DuplicateHandle(GetCurrentProcess(), p->stdio_out, GetCurrentProcess(), &dup, 0, FALSE, DUPLICATE_SAME_ACCESS))
    return -1;

  fd = _open_osfhandle((intptr_t)dup, _O_RDONLY | _O_TEXT);
  if (fd == -1) {
    CloseHandle(dup);
    return -1;
  }
  f = _fdopen(fd, "rt");
  if (f == NULL) {
    _close(fd);
    return -1;
  }

  r = fseek(f, 0, SEEK_SET);
  if (r < 0) {
    fclose(f);
    return -1;
  }

  while (fgets(buf, sizeof(buf), f) != NULL)
    print_lines(buf, strlen(buf), stream);
  
  if (ferror(f)) {
    fclose(f);
    return -1;
  }

  fclose(f);
  return 0;
}
```

**Comment by saghul** [comment]
Hi Tom! Mind sending it as a PR?

**Comment by tom-seddon** [comment]
Yes, though I can't promise a timely one. But it's on my to do list, so it will get done eventually (apologies - I'm not working with a setup that makes PRs quick to create).

Thanks,

--Tom

**Comment by cjihrig** [comment]
@tom-seddon did you mean to close this?
