### ISSUE TITLE
Source code blocks missing from documentation

### ISSUE THREAD

**Issue by anticrisis** [libuv/libuv#1427]
For example, this page in the User guide: http://docs.libuv.org/en/v1.x/guide/threads.html

The label `thread-create/main.c` is not followed by actual source code.

The problem appears to be that the relative paths in `docs/src/guide/threads.rst` are incorrect.

For example, in `docs/src/guide/threads.rst`, line 215:

```
.. literalinclude:: ../code/queue-work/main.c
```

should be this:

```
.. literalinclude:: ../../code/queue-work/main.c
```

There are a dozen or two warnings about include files that could not be found when `make html` is used.

I can provide a pull request which adds the necessary levels of relative paths to each `literalinclude`, but I'm not sure if that's the proper fix. For instance, maybe there's a build setting to fix this without touching every `.rst` file.

**Comment by cjihrig** [comment]
I think we probably want to adjust the paths. The user guide stuff comes from the uvbook, and it's a fairly recent addition that still has some kinks to work out.

**Comment by vcunat** [comment]
Fixed, I guess?

**Comment by saghul** [comment]
Indeed!
