### ISSUE TITLE
Is it safe to run uv_run from a different thread?

### ISSUE THREAD

**Issue by winterland1989** [libuv/libuv#1430]
Sorry to ask here but it seems https://github.com/libuv/help/new just doesn't work...

This question [has been asked before](https://github.com/joyent/libuv/issues/423) but i still want to make sure what the status quo is. 

I'm try to bring libuv to haskell's multi-threaded RTS, the problems is that haskell thread is N:M mapped into OS thread, and they can be migrate between different OS thread. That means if i start a uvloop on thread A, call `uv_run` once, the next time i call `uv_run` it may be a in a completely different OS thread. Is this safe? what about things like `cancelio` on windows?

From what i understand, it should be fine since libuv doesn't use thread local state, and `uv_close` is not thread safe anyway so i will use `uv_async_send`, but i just want to be sure about this.

Again, i'm sorry to ask this with an github issue, cheers!

**Comment by saghul** [comment]
Please open an issue here: https://github.com/libuv/help/issues/new

**Comment by winterland1989** [comment]
Thanks, sorry for the noise!

**Comment by bnoordhuis** [comment]
Apologies, the link in the issue template is broken.  #1431
