### ISSUE TITLE
can't stop uv loop

### ISSUE THREAD

**Issue by yjjnls** [libuv/libuv#1434]
> ```
> #include <thread>
> #include <libuv/uv.h>
> uv_loop_t *loop;
> bool stop = false;
> 
> void run()
> {
> 	while (!stop) {
> 		uv_run(loop, UV_RUN_DEFAULT);
> 	}
> }
> void print_progress(uv_async_t *handle) {
> 
> }
> int main()
> {
>         loop = new uv_loop_t;
> 	uv_loop_init(loop);
> 	uv_async_t *async = new uv_async_t;
> 	uv_async_init(loop, async, print_progress);
> 
>         std::thread t(run);
> 
>         while (1)
> 	{
> 		char c = getchar();
> 		if (c == 'q' || c == 'Q')
> 			break;
> 	};
> 	stop = true;
> 	uv_stop(loop);
> 	t.join();
> 	uv_close((uv_handle_t*)async, NULL);
> 
>         uv_loop_close(loop);
> 
> 
> 	delete async;
> 	async = NULL;
> 	delete loop;
> 	loop = NULL;
> 
> 	return 0;
> }
> ```

* **Version**: 1.12.0
* **Platform**: Windows

Just a simple sample. But the thread can't be stopped after  adding an async to the loop.
Why?

**Comment by bnoordhuis** [comment]
Please post questions to https://github.com/libuv/help/issues, this tracker is strictly for reporting bugs.
