### ISSUE TITLE
Make fails in Cygwin with v1.13.1 

### ISSUE THREAD

**Issue by aruntejasvi** [libuv/libuv#1448]
* **Version**: v1.13.1 
* **Platform**: Cygwin

make fails with
```
  CC       src/unix/libuv_la-bsd-ifaddrs.lo
src/unix/bsd-ifaddrs.c: In function ‘uv__ifaddr_exclude’:
src/unix/bsd-ifaddrs.c:45:41: error: ‘AF_LINK’ undeclared (first use in this function)
     return (ent->ifa_addr->sa_family != AF_LINK);
                                         ^
src/unix/bsd-ifaddrs.c:45:41: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:2235: src/unix/libuv_la-bsd-ifaddrs.lo] Error 1


```

**Comment by INRIX-joel-winarske** [comment]
The only place I see this defined is here:
joel@WAYWARD /cygdrive/c/Program Files (x86)/Windows Kits/8.1/Include
$ grep -r AF_LINK
shared/ws2def.h:#define AF_LINK         33

Adding "#define AF_LINK         33" to bsd-ifaddrs.c enables the build to succeed.


Two of the 315 test cases fail:

not ok 199 - poll_oob
# exit code 134
# Output from process `poll_oob`:
# Assertion failed in test/test-poll-oob.c on line 99: n == 4

not ok 303 - dlerror
# exit code 134
# Output from process `dlerror`:
# Assertion failed in test/test-dlerror.c on line 45: strstr(msg, path) != NULL

**Comment by Yamakuzure** [comment]
Hmm... I do not think that this AF_LINK is correct. I used the following patch to build libuv-1.18.0 on cygwin using a gentoo linux prefix, and it *seems* to work.

````
--- a/src/unix/bsd-ifaddrs.c	2018-01-09 17:16:22.000000000 +0100
+++ b/src/unix/bsd-ifaddrs.c	2018-01-09 17:23:03.769838400 +0100
@@ -41,8 +41,11 @@
    * equals to `AF_LINK` or not. Otherwise, the result depends on the operation
    * system with `AF_LINK` or `PF_INET`.
    */
+#if defined(AF_LINK)
   if (exclude_type == UV__EXCLUDE_IFPHYS)
     return (ent->ifa_addr->sa_family != AF_LINK);
+#endif /* AF_LINK */
+
 #if defined(__APPLE__) || defined(__FreeBSD__) || defined(__DragonFly__)
   /*
    * On BSD getifaddrs returns information related to the raw underlying
````
