### ISSUE TITLE
send udp to a closed endpoint,  frequently received error (10054) after the step "WSARecvFrom".  my OS is Win7

### ISSUE THREAD

**Issue by shen1985** [libuv/libuv#1449]
* **Version**: 
* **Platform**:

**Comment by bnoordhuis** [comment]
Test case?  Or really, just any kind of steps to reproduce?

**Comment by shen1985** [comment]
a method to ignore this error , on windows 7 

#include <Winsock2.h>
#include <Mstcpip.h>
#include <stdio.h>

#pragma comment(lib, "ws2_32.lib")
#define SIO_UDP_CONNRESET _WSAIOW(IOC_VENDOR, 12)

BOOL bNewBehavior = FALSE;
DWORD dwBytesReturned = 0;
WSAIoctl(iSock, SIO_UDP_CONNRESET, &bNewBehavior, sizeof bNewBehavior, NULL, 0, &dwBytesReturned, NULL, NULL);

**Comment by shen1985** [comment]
my libuv udp client, send msg to a server( off line).  everytime after i send， the recvive callback function will receive a zero message from win/udp.c  line 549.

**Comment by bzoz** [comment]
The [documentation](http://docs.libuv.org/en/v1.x/udp.html) says that:

> The receive callback will be called with nread == 0 and addr == NULL when there is nothing to read, and with nread == 0 and addr != NULL when an empty UDP packet is received.

So, isn't this expected behavior?

(for reference, this was added as fix for https://github.com/joyent/libuv/issues/1426)
