### ISSUE TITLE
Please provide a more lightweight accept

### ISSUE THREAD

**Issue by winterland1989** [libuv/libuv#1455]
Currently `uv_stream_accept` will setup the client handle with the restriction that server and client should be on the same loop, this is far too limited for multiple event loop usage.

I propose adding a `uv_tcp_accept` function which directly return the queued `SOCKET/fd` and `sockaddr`(either via sync return struct or aysnc callback is ok). Then user can pass them to other loops doing real work.

**Comment by bnoordhuis** [comment]
Doesn't `uv_poll_start()` do what you want?

**Comment by winterland1989** [comment]
Yes, but the document imply there're perfomance trade-off, which lead me to think if it's implemented with something like `poll/WSAPool` . But after reading the source i found it suit my need perfectly, thanks.

**Comment by saghul** [comment]
I think exploring this is interesting. We'd need a reject API too, in case you cannot create the handle for whatever reason. Since we have the `uv_*_open` APIs, something to get the `uv_od_fd_t` and then manually creating the handle should work.

Is this something you're interested in working on? If so, please make an API proposal in the form of a LEP: https://github.com/libuv/leps

**Comment by winterland1989** [comment]
>  We'd need a reject API too, in case you cannot create the handle for whatever reason. 
I guess you mean close sync/async ? That's definitely good.

Is this something you're interested in working on? If so, please make an API proposal in the form of a LEP: https://github.com/libuv/leps

> I'll try to make a formal proposal when i get time ; )

**Comment by saghul** [comment]
> BTW, why listen/accept is a stream api which include uv_tty_t?

Those are not supported for uv_tty_t, you'd get an error if you use them. uv_tty_t has the same stream semantics when it comes to reading and writing data, for example.

**Comment by bnoordhuis** [comment]
> We'd need a reject API too, in case you cannot create the handle for whatever reason.

Sounds a little clunky.  I'd make it report the fact that there is a connection to accept and then leave it up to the application to either accept it or stop the listen handle.

**Comment by saghul** [comment]
What if the application cannot deal with the connection at this time? We'd have handed over a `uv_os_fd_t`, it would be nice if they have a way to close it IMHO. Maybe we can make some opaque thing instead like `uv_connection_t` and then you `uv_tcp_init_from_connection` or something. That way failure can be handled there and we don't need a rejection thing... This is the first thing that crossed my mind, take it with 750gr of salt :-P

**Comment by bnoordhuis** [comment]
The, hah, salient part is this:

> report the fact that there is a connection to accept

I.e., report but not actually accept - that's left to the application.

**Comment by saghul** [comment]
I see what you mean there. That is indeed another interesting possibility.

**Comment by perfhunter** [comment]
I am also missing such "lightweight" accept, but I would rather vote for decoupling handles from the event loop and implementing a mechanism to attach/detach a handle to a specific event loop. That will be useful not only for passing accepted sockets to another event loop, but, for example, do some load balancing and workload dispatching.
