### ISSUE TITLE
[android O] /proc/stat access denied

### ISSUE THREAD

**Issue by enricogior** [libuv/libuv#1459]
* **Version**: 1.13.1
* **Platform**: Android O

With reference to https://issuetracker.google.com/issues/37140047
on Android O, for security reason, access to `/proc/stat` is denied, therefore [`uv_cpu_info()`](https://github.com/libuv/libuv/blob/v1.13.1/src/unix/linux-core.c#L579) fails at [line 588](https://github.com/libuv/libuv/blob/v1.13.1/src/unix/linux-core.c#L588).

**Comment by saghul** [comment]
From the same email:

> It is no longer possible to determine the CPU utilization of the device.   
> This has severe negative consequences for system and battery monitoring applications and denies the user the ability to correct problems with his/her device. 

I don't see how libuv can solve anything here. We gracefully fail with an error, which is about as much as we can do.

**Comment by enricogior** [comment]
Sure, I agree, I only wanted to report it, so it's tracked.

**Comment by cjihrig** [comment]
Closing as "we're doing as much as we can do"

**Comment by Quasic** [comment]
I started patching libuv to handle this in my fork. I plan to submit the patch to termux, if it is not incorporated upstream. It's a whole different setup, though.

**Comment by Quasic** [comment]
Note: While testing this on an octocore running Nougat, I get various numbers returned, usually 3 when idle. It seems that cores are omitted from /proc/stat when turned off individually to save battery.
