### ISSUE TITLE
async: uv_async_cb is not called

### ISSUE THREAD

**Issue by yorkie** [libuv/libuv#1460]
* **Version**: 1.11.0
* **Platform**: armv64

I used the `uv_async_t` to integrate 2 callback-based C/C++ libraries to Node.js, but a weird case is here, when I call `uv_async_send` between the 2 `uv_async_t`s, the callback of one `uv_async_t` doesn't get fired, the `uv_async_send` returns 0 before that.

**Comment by yorkie** [comment]
For more details, take the following code:

```c
uv_async_t a1;
uv_async_t a2;

uv_async_init(a1);
uv_async_init(a2);

uv_async_send(a1); // working
uv_async_send(a2); // working
uv_async_send(a1); // working
uv_async_send(a2); // working
uv_async_send(a1); // not working, the corresponding is not called
.....
.....
uv_async_send(a1); // working again, weird....
```

**Comment by bnoordhuis** [comment]
Are you getting tripped up by the fact that `uv_async_send()` can coalesce calls?  There won't be a callback for every call if the calls are close enough in time.

**Comment by yorkie** [comment]
> There won't be a callback for every call if the calls are close enough in time.

This is for all `uv_async_t`? Do we have another way without this effect?

**Comment by bnoordhuis** [comment]
Not directly in libuv but you can use e.g. a mutex-protected counter in addition to the uv_async_t handle.

I'm going to close this as working-as-intended but feel free to take it to libuv's help repo if you have further questions.

**Comment by yorkie** [comment]
No, I think the calls are in least 5s.

**Comment by Globik** [comment]
@yorkie  the same in nodejs part of addon n-api async tests.

**Comment by yorkie** [comment]
@Globik Do you have any links relevant?
