### ISSUE TITLE
uv_default_loop is not thread safe

### ISSUE THREAD

**Issue by sharvil** [libuv/libuv#1461]
It seems useful to want to get the default loop from multiple threads. However the implementation is not currently thread safe and multiple threads can initialize the global object. 

If this function is not intended to be called from multiple threads, it would be good to reflect that in the documentation. 

* **Version**: 
* **Platform**:

**Comment by bnoordhuis** [comment]
I suppose the documentation could be less roundabout: it hints at it but doesn't say it explicitly.  PR welcome!
