### ISSUE TITLE
make check fail on centos7

### ISSUE THREAD

**Issue by duuyia** [libuv/libuv#1463]
Issues: 
ok 181 - hrtime
not ok 182 - getaddrinfo_fail
# exit code 134
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
not ok 183 - getaddrinfo_fail_sync
# exit code 134
# Output from process `getaddrinfo_fail_sync`:
# Assertion failed in test/test-getaddrinfo.c on line 117: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy.", NULL, NULL)
ok 184 - getaddrinfo_basic

Vers:  libuv version  1.13.1
Platform:  centos7

**Comment by saghul** [comment]
We see these fail from time to time. It's because your resolver somehow thinks "xyzzy.xyzzy.xyzzy." is a valid domain. It's not.

Closing as it's not a libuv issue.
