### ISSUE TITLE
threadpool_multiple_event_loops timeouts on x86_64 GNU/Linux

### ISSUE THREAD

**Issue by SantjagoCorkez** [libuv/libuv#1471]
Building with debug:

ok 285 - threadpool_queue_work_simple
ok 286 - threadpool_queue_work_einval
not ok 287 - threadpool_multiple_event_loops
`# timeout`
`# Output from process` `threadpool_multiple_event_loops`: (no output)

ok 288 - threadpool_cancel_getaddrinfo

FAIL: test/run-tests
`======================================================
1 of 1 test failed

* **Version**: 1.13.1
* **Platform**: Linux my 4.9.39-1-MANJARO #1 SMP PREEMPT Fri Jul 21 08:25:24 UTC 2017 x86_64 GNU/Linux

**Comment by bnoordhuis** [comment]
That test is unfortunately somewhat timing sensitive: the test runner imposes a hard deadline and that test does a lot.  Does it fail consistently for you or is it just flaky?

**Comment by SantjagoCorkez** [comment]
Tried 3 times so far. No luck. BTW, the partition on which the source code is built is an SSD.

**Comment by SantjagoCorkez** [comment]
Still suffering of this bug (can't build a PKGBUILD).

I've also getting a strange bug on my project:

An instance's runtime consists of 3 threads each running its own loop. One loop runs a timer that invokes a send of a chunk of bytes to another instance via uv_tcp_t handle. First attempt to send a message succeeds (another instance prints the message's information appropriately), but all subsequent  attempts do nothing except enqueueing all the bytes into `handle->write_queue`. While the handle is run on the same loop as the whole thread it 'belongs' to, the timer of this thread works just as planned - it yields a send attempt every given delay interval. Do these bugs have anything in common of a cause?

**Comment by awilfox** [comment]
I am seeing this same test failure on our Adélie Linux x86 builder.

```
cpu family      : 15
model           : 2
model name      : Intel(R) Pentium(R) 4 CPU 2.40GHz
stepping        : 9
```

Won't win any speed awards, but I surely wouldn't expect it to fail tests either.  128 GB SSD with 4 GB DDR2-400.

**Comment by bnoordhuis** [comment]
@SantjagoCorkez @awilfox Does #1634 fix it for you?

**Comment by awilfox** [comment]
Works flawlessly now, thank you for the quick resolution!
