### ISSUE TITLE
Mispelled parameter name prerelase -> prerelease

### ISSUE THREAD

**Issue by 3DHDSoft** [libuv/libuv#1475]
Mispelled parameter name prerelase -> prerelease at https://github.com/libuv/libuv/blob/ce56a85b19e13287d2613f8de33f479a9c1104b5/tools/vswhere_usability_wrapper.cmd#L20

**Comment by cjihrig** [comment]
Looks like this was fixed in https://github.com/libuv/libuv/commit/66b8b2f76d457ac50778a3d363183fe6d2fd063b#diff-169d858a6ae9b91d987b52bd7a51d86f.
