### ISSUE TITLE
Cygwin install doesn't copy uv-posix.h to ${prefix}/include

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [libuv/libuv#1480]
* **Version**: 1.13.1
* **Platform**: Cygwin64

When building on Cygwin the install step does not copy uv-posix.h.  uv-unix.h has a pound define conditional for Cygwin, which refers to uv-posix.h.

Joel

**Comment by saghul** [comment]
Looks like we need a `include_HEADERS` here: https://github.com/libuv/libuv/blob/v1.x/Makefile.am#L341 mind sending in a PR?

**Comment by jwinarske** [comment]
PR [1482](https://github.com/libuv/libuv/pull/1482)
