### ISSUE TITLE
Shall I unlock after trylock if failed?

### ISSUE THREAD

**Issue by XadillaX** [libuv/libuv#1481]
* **Version**: 1.13.1
* **Platform**: Darwin zanarpro 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin

If I do `uv_rwlock_trywrlock()` and failed, shall I do `uv_rwlock_unlock()` after it failed?

eg.

```c
if(uv_rwlock_trywrlock(handle)) {
    uv_rwlock_wrunlock(handle);
    return;
}
```

V.S.

```c
if(uv_rwlock_trywrlock(handle)) {
    // uv_rwlock_wrunlock(handle);
    return;
}
```

**Comment by bnoordhuis** [comment]
No, because you didn't take out the look.

Can you post questions to the help repo next time?  Thanks.
