### ISSUE TITLE
Segmentation Fault on uv_timer_init

### ISSUE THREAD

**Issue by Nishith8** [libuv/libuv#1485]
I'm using Ubuntu 16.04, 64bit, and I've recently installed libuv (master branch). I followed the exact instructions in the readme, build was successful and all tests passed. I'm trying to get libuv working with a uWebSockets project that I'm working on. 

As recommended in the libuv installation, I'm using the '-Wl,-rpath -Wl,LIBDIR' linker flag when compiling the project. I'm using g++ to compile, including all flags, the command looks like this, `g++ -std=c++11 *.cpp -O0 -luWS -lz -lssl -luv -DUSE_LIBUV -Wl,-rpath -Wl,LIBDIR`

My project compiles just fine, however when I'm running it, it immediately segfaults. The gdb backtrace shows the following:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7518366 in uv_timer_init (loop=0x61a220, handle=0x61ebb0)
    at src/unix/timer.c:55
55	  uv__handle_init(loop, (uv_handle_t*)handle, UV_TIMER);
(gdb) bt
#0  0x00007ffff7518366 in uv_timer_init (loop=0x61a220, handle=0x61ebb0)
    at src/unix/timer.c:55
#1  0x0000000000401aaf in Timer::Timer(Loop*) ()
#2  0x0000000000401494 in main ()

```
I have heavily simplified my project code down to the part that throws the error, it looks like this:
```
int main(){
    uWS::Hub h;

    Timer *timer = new Timer(h.getLoop());
    timer->setData(&h);
    timer->start([](Timer *timer){
	    //loop logic here
    }, 40, 40);
	
    return 0;
}
```
The project compiles and executes perfectly, without libuv, it'll only segfault when libuv is involved.

**Comment by bnoordhuis** [comment]
If you have a libuv-only test case, I'll be happy to look at it, but if it goes through uWS, you should report it to that project, not here.

Closing, can reopen if you post a new test case.
