### ISSUE TITLE
including downstream projects in regression tests

### ISSUE THREAD

**Issue by refack** [libuv/libuv#1486]
Continuation of https://github.com/libuv/libuv/pull/1396#issuecomment-323132397
tl;dr
There are several situation that a hard to minimize into a libuv test case. Also since the product is a lib, testing it as part of a downstream product makes allot of sense.

**Comment by refack** [comment]
What I had in might is a little bit similar to node's CitGM, and I see two simple options:
1. Build libuv as a shared library:
   1. Have pre built downstream projects (node, pyuv, etc.) linked to a shared libuv.
   2. run the downstream project's test suite with latest libuv dll
2. Rebuild everything as static:
   1. auto-vendor subject libuv code into a working copy of downstream project
   2. build & test

**Comment by bnoordhuis** [comment]
The problem with node's citgm is that it's a buggy test or shoddy module as often (probably more often) than a genuine node issue.  I have no reason to believe a libuv citgm is going to be any different and I, for one, don't enjoy wasting time on other people's buggy code.

**Comment by cjihrig** [comment]
I agree, that I'd rather not go down the CITGM path again.

@bnoordhuis would you feel differently about something like https://github.com/nodejs/node-v8, but for libuv instead of V8?

**Comment by bnoordhuis** [comment]
Integration with node?  Yes, good idea.

**Comment by cjihrig** [comment]
cc @gibfahn - this is what I was discussing with you at Node Interactive.

**Comment by cjihrig** [comment]
cc @mhdawson. It would be extremely helpful to be able to build and test Node with a given libuv commit. Is there any way this could get on the Build WG's agenda?

**Comment by mhdawson** [comment]
@cjihrig I'd say open an issue in the build WG.

In that issue if you can outline the best way to the libuv from the commit into the node build that would be helpful.  I may be as simple as cloning the libuv repo, checking out the commit and then doing a copy into the node.js tree that was earlier cloned, but would be good you have your insight on that.

**Comment by cjihrig** [comment]
Closing this in favor of https://github.com/nodejs/build/issues/1019.
