### ISSUE TITLE
uv_fs_scandir crashed.

### ISSUE THREAD

**Issue by kod21236** [libuv/libuv#1488]
* **Version**: v1.13.1
* **Platform**: Windows

Below code is crashed. uv_fs_scandir(sync) calls pNtQueryDirectoryFile but pNtQueryDirectoryFile function pointer is NULL. Because uv_init() -> uv_winapi_init() was not called.
    int r;
    uv_fs_t req;
    r = uv_fs_scandir(NULL, &req, path, 0, NULL);

I use the below workaround code, but It seems to be minor bug.
    uv_loop_t* loop;
    int r;
    uv_fs_t req;
    loop = uv_default_loop();
    r = uv_fs_scandir(NULL, &req, path, 0, NULL);

**Comment by bzoz** [comment]
You have to pass a pointer to loop instance when calling `uv_fs_scandir` - either a `uv_default_loop` or loop instance has to be initialized by `uv_loop_init`.

I will close this, if you manage to reproduce this with initialized loop feel free to reopen,

**Comment by cjihrig** [comment]
It feels like a bug to me. We allow `NULL` to be passed as the first argument, but then the Windows API isn't initialized.

**Comment by bzoz** [comment]
I thought that we don't. Anyhow, we can easily fix this by adding a call `uv__once_init();` to `uv_fs_scandir`. If so we should add this to all other functions that support `NULL` as loop parameter.
