### ISSUE TITLE
make android-ifaadrs.c and pthread-fixes.c be optional for Android?

### ISSUE THREAD

**Issue by cynron** [libuv/libuv#149]
On android, some other 3rd part library also adds `getifaddrs/freeifaddrs` and `pthread_barrier_*` support, which will lead to linkage conflicting.

I think maybe we can make them be compile-time optional in libuv.

**Comment by saghul** [comment]
Since they are only used internally, maybe we could prefix them with `uv__`? Thoughts @bnoordhuis ?

**Comment by bnoordhuis** [comment]
That sounds reasonable.  However, libuv builds with -fvisibilty=hidden by default.  That makes me wonder how and why link-time errors happen.  Do we have a missing check in configure.ac?

**Comment by saghul** [comment]
Closing since #164 landed.

**Comment by cynron** [comment]
Thanks!
