### ISSUE TITLE
Increase thread stack size on musl systems

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#1507]
Reported on IRC:

```
<timotimo> greetings
<timotimo> we're having a trouble with alpine linux drastically reducing the stack size of additional threads created
<timotimo> (we the perl6 devs)
<timotimo> there's already a piece of code in libuv that makes sure threads get the RLIMIT_STACK on mac osx, but i don't see any way to ask libuv to build a bigger stack for newly created threads
```

According to [this](http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#Thread_stack_size):

> musl provides a default stack size of 80k. This does not include the guard page, nor does it include the space used for TLS unless total TLS size is very small. So the actual map size may appear closer to 90k, with around 80k usable by the application. This size was determined empirically with the goals of not gratuitously breaking applications but also not causing large amounts of memory and virtual address space to be committed in programs with large numbers of threads. Programs needing larger stacks, or which explicitly want a smaller stack, should make this explicit with pthread_attr_setstacksize. For largely unrestrained use of the standard library, a minimum of 12k is recommended, but stack sizes down to 2k are allowed. 

So probably it's a good idea to increase the thread stack size to `RLIMIT_STACK`  as we do for `OS X`.

**Comment by bnoordhuis** [comment]
That might cause regressions.  See #429 for an example where libuv had to lower the stack size of new thread.

What we could do is set the stack size to 2 MB (4 MB on ppc) if RLIMIT_STACK is not RLIM_INFINITY because that is what glibc does.  It would make libuv's behavior consistent across libcs.

Happy to code up a PR if there is consensus.

**Comment by timo** [comment]
i believe we expect a stack size of around 1 MB, so getting 2 would be all right for us

**Comment by Julio-Guerra** [comment]
We are currently getting random segfault crashes when libuv dlopens a library on `node:14-alpine` on heroku.
My only hint is the stack size, but it seems the stack size issue has been solved here.
Do you have any thoughts?

I am thinking of re-compiling node with `-fstack-check` and `-fstack-protector-all` to try confirm it's still a stack size issue :thinking:

**Comment by bnoordhuis** [comment]
What do the backtraces in gdb look like? Does valgrind print anything that might be relevant?

**Comment by Julio-Guerra** [comment]
We have no debugging information yet.

But I can tell that running `ulimit -s` on a docker container running on heroku gives 8192, which seems to be the value returned in https://github.com/libuv/libuv/blob/v1.x/src/unix/thread.c#L194-L196.

This is so far from 128 times less than the default 2^20 value returned at https://github.com/libuv/libuv/blob/v1.x/src/unix/thread.c#L205.

So I am wondering what made you choose 8192 as a large enough value here?

**Comment by bnoordhuis** [comment]
> what made you choose 8192 as a large enough value 

I think you're conflating units. :-)

`ulimit -s` reports the stack size in kilobytes, i.e., 8192 means 8 MB. Libuv honors that setting.

That 8192 you see in libuv's source code is the absolute lower bound that libuv accepts and it's in bytes, not kilobytes.
