### ISSUE TITLE
EINVAL behavior for fs functions

### ISSUE THREAD

**Issue by cjihrig** [libuv/libuv#1508]
On Unix, `uv_fs_write()`, `uv_fs_read()`, and `uv_fs_copyfile()` can all return `EINVAL` before the `INIT` macro. Should these `EINVAL` returns be moved after `INIT` so that consumers don't get unexpected malloc errors when trying to clean up the req objects? If so, I'll send a patch.

* **Version**: v1.x
* **Platform**: unix, maybe Windows too

**Comment by saghul** [comment]
Sounds reasonable.
