### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by Polyergic** [libuv/libuv#1518]
macOS 10.12.6 (16G29) with macports and /opt/local/libexec/gnubin/ in my path.

output from `./configure`:

```
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... configure: error: ls -t appears to fail.  Make sure there is not a broken
  alias in your environment
configure: error: newly created file is older than distributed files!
Check your system clock
```

This came out of [julia issue #23425](https://github.com/JuliaLang/julia/issues/23425#issuecomment-326051334), where the build failure of julia was due to the build failure of libuv.

When I run `ls -t` it seems to work; `ls` is aliased to `ls $LS_OPTIONS`, which expands to `ls -N --color=tty -T 0`, and removing the alias has no effect. My system clock seems to be set and working correctly.

Where can I see what the sanity checks on `ls -t` and file times actually do?

**Comment by bnoordhuis** [comment]
That looks like an autotools issue to me.  That check is a standard autoconf check, it's not specific to libuv.

**Comment by Polyergic** [comment]
I'm not familiar with autotools; searching for that, the best result was at [Explain XKCD #371 Discussion](https://www.explainxkcd.com/wiki/index.php/371:_Compiler_Complaint#Discussion).  Apparently I had my own long forgotten `~/bin/ls` which was forcing color output and making the test fail.  Removing that (hopefully I don't need it anymore) fixed both the `libuv` build (although `make check` still reports a few errors) and the `julia` build.
