### ISSUE TITLE
Gutting joyent/libuv, "moving" to libuv/libuv broke GitHub code searching

### ISSUE THREAD

**Issue by apaprocki** [libuv/libuv#152]
Because `libuv/libuv` was forked from `joyent/libuv` instead of the original repo being moved to the `libuv` organization, the original parent repository now exists as an empty repo with a `README` pointing to the new location.

GitHub was not designed to work this way and it breaks code search. Attempting to search for code in `libuv/libuv` fails saying that it is forked and searches must be done in the parent repo. Attempting to search in the parent repo never finds any results because the repo was gutted to just contain the `README` redirect.

I'm not sure how best to fix this without GitHub's help.. technically I assume the `joyent/libuv` repo must move, but that would affect issues/pull requests that have since happened in the meantime. I think GitHub might need to break the *forked from `joyent/libuv`* link on the new repo. Or if someone else has a better idea...

Search fails: https://github.com/libuv/libuv/search?q=uv&type=Code&utf8=%E2%9C%93
Search has no results: https://github.com/joyent/libuv/search?q=uv&type=Code&utf8=%E2%9C%93

**Comment by saghul** [comment]
Well, only the owner of the repo can do that. We requested it and got no response. Please see https://github.com/joyent/libuv/issues/1573

**Comment by saghul** [comment]
> I think GitHub might need to break the forked from joyent/libuv link on the new repo.

This would be great IMHO.

**Comment by piscisaureus** [comment]
The inability to use search has me bothered for some time as well. I am afraid that breaking the ties would also destroy all pull request against this repository. It'd be nice if they could invert the relationship (so joyent/libuv becomes a fork of libuv/libuv).

**Comment by bnoordhuis** [comment]
>  It'd be nice if they could invert the relationship (so joyent/libuv becomes a fork of libuv/libuv).

GH has done that a few times for StrongLoop projects but of course SL is a paying customer.  I'll contact GH support and see what they say.

**Comment by saghul** [comment]
Thanks for trying guys! :heart_eyes:

**Comment by jbergstroem** [comment]
I talked to github support about this weeks ago (december 30 if any githubbers want to find the whole thread). I essentially summarised the situation and how this repo most likely would be preferred repo as a consumer. Here's the reply:
> Thanks for the feedback. It's not currently possible to change this, but I'll add a +1 to this suggestion on our internal Feature Request List. No promises if we might allow this, however we appreciate your input.

**Comment by bnoordhuis** [comment]
Good news, Steven from GH support broke the fork relationship with joyent/node.  The only thing is that people may need to recreate their personal fork of libuv/libuv because it's going to get reparented to joyent/libuv.  Should be easy: delete your repository, fork from libuv/libuv, then `git push --all` from your local copy.

**Comment by saghul** [comment]
Oh yeah! Thanks Ben! I guess we can close this now :-)
