### ISSUE TITLE
Define for `ERROR_MUI_FILE_NOT_FOUND` missing in at least one version of MinGW

### ISSUE THREAD

**Issue by darkuranium** [libuv/libuv#153]
**Note:** *While this is technically a MinGW issue, it would probably be a good idea to work around the problem for versions that do not define this.*

It would appear that some (all?) versions of MinGW do not define `ERROR_MUI_FILE_NOT_FOUND` in the `winerr.h` header.

A simple workaround is to check for presence of that `#define` and, if missing:

```c
#ifndef ERROR_MUI_FILE_NOT_FOUND /* if not defined in MinGW headers */
#define ERROR_MUI_FILE_NOT_FOUND    0x3AFC
#endif
```

My MinGW version, for the record:

```
>gcc --version
gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 4.8.3
```

**Comment by saghul** [comment]
Have you tried using the latest libuv release? A fix for this landed a couple of weeks ago: https://github.com/libuv/libuv/commit/6da887f416d4aa5bd6a54b8e7fb7001111c159f7 It's available on libuv >= 1.2.0.

**Comment by darkuranium** [comment]
I see now, my mistake. Apologies.

I was using another project, which had libuv as a submodule; apparently, it was an older revision in the submodule.

**Comment by saghul** [comment]
No worries!
