### ISSUE TITLE
tcp4_echo_start bind bug lead cpu100% 

### ISSUE THREAD

**Issue by danielshaving** [libuv/libuv#1531]
for(int i = 0; i < 2; i ++)
  {
	  ASSERT(0 == uv_ip4_addr("0.0.0.0", i + port, &addr));

	  server = (uv_handle_t*)&tcpServer;
	  serverType = TCP;

	  r = uv_tcp_init(loop, &tcpServer);
	  if (r) {
		/* TODO: Error codes */
		fprintf(stderr, "Socket creation error\n");
		return 1;
	  }
	  

	  r = uv_tcp_bind(&tcpServer, (const struct sockaddr*) &addr, 0);
	  if (r) {
		/* TODO: Error codes */
		fprintf(stderr, "Bind error\n");
		return 1;
	  }

	  r = uv_listen((uv_stream_t*)&tcpServer, SOMAXCONN, on_connection);
	  if (r) {
		/* TODO: Error codes */
		fprintf(stderr, "Listen error %s\n", uv_err_name(r));
		return 1;
	  }
  }

**Comment by saghul** [comment]
You cannot reuse the handles like that. You need a new handle on each iteration.
