### ISSUE TITLE
Integration with custom Overlapped/IOCP handles on Windows

### ISSUE THREAD

**Issue by ambrop72** [libuv/libuv#1541]
I want to use a TAP-Windows device via libuv but it seems impossible to integrate properly (without extra threads). I propose to add a facility which allows the application to associate IOCP-capable handles with the IOCP handle used by libuv and receive callbacks when `GetQueuedCompletionStatusEx` returns associated events.

The interface could look something like this:

```c
HANDLE uv_loop_get_iocp_handle(uv_loop_t *);

typedef struct uv_overlapped_t {
    ...
    // Contained OVERLAPPED structure is exposed to users
    OVERLAPPED overlapped;
    ...
} uv_overlapped_t;

typedef void (*uv_overlapped_cb)(uv_overlapped_t *);

int uv_overlapped_init(uv_loop_t *, uv_overlapped_t *, uv_overlapped_cb callback);
void uv_overlapped_close(uv_overlapped_t *);
```

This would be used like this:
- The application calls `uv_overlapped_init`. The newly initialized uv_overlapped_t structure includes an `OVERLAPPED` structure which the application will write and read before/after I/O operations as appropriate.
- The application calls `uv_loop_get_iocp_handle()` to retrieve the IOCP handle used by the event loop and then uses `CreateIoCompletionPort()` to associate their HANDLE to the IOCP handle.
- After that the application can start I/O operations. Whenever libuv retrieves an event associated with that `OVERLAPPED` instance it will call the callback provided to `uv_overlapped_init()`.
- The application calls `uv_overlapped_close()` when it is done with all I/O operations associated with that `OVERLAPPED` structure.
- The application is responsible to wait for any associated ongoing I/O operations to complete before calling `uv_overlapped_close()`. This restriction is imposed by IOCP design, because so long as there is potential that an event will be returned, the `OVERLAPPED` structure must still be valid and libuv must be able to handle events associated with it.

For `uv_overlapped_t` objects, asynchronous `uv_close()` with a callback does not make sense because only the application knows which I/O operations are in progress and when they have all completed.

Actually, it is not even technically necessary for `uv_overlapped_close` to exist because libuv does not need to keep track of `uv_overlapped_t` objects. But if `uv_overlapped_t` is to inherit from `uv_handle_t` then a close is needed to remove it from the handle list.

**Comment by vtjnash** [comment]
We should perhaps consolidate these feature requests, since there's also #1688 and a couple PR attempts.
