### ISSUE TITLE
Building in Windows VS2017, calling vcvarsall.bat will change working directory.

### ISSUE THREAD

**Issue by darobs** [libuv/libuv#1545]
* **Version**: v1.13.0
* **Platform**: Windows x64, Visual Studio 2017

The default architecture in a Visual Studio 2017 Developer Command Prompt is x86.  When you want to build libuv for x64, the `vcbuild.bat` script calls `vcvarsall.bat` to change the architecture.  However, `vcvarsall.bat` changes the current working directory to whatever is set in `VSCMD_START_DIR`.

The workaround is to set up the environment correctly before calling `vcbuild.bat`.

**Comment by refack** [comment]
@darobs thanks for reporting and fixing 🥇
