### ISSUE TITLE
API nitpick.

### ISSUE THREAD

**Issue by txdv** [libuv/libuv#155]
We have stuff that returns strings, usually we have a pointer to length which gives the function an idea of how big a given buffer is and then puts the real size of the string into the pointer, the signature looks something like this:

```c
int function(char* buf, size_t* len);
```

Sometimes there are more parameters, a pointer to handle or  such, sometimes not.

We have in total 5 functions which fit this:

```c
UV_EXTERN int uv_fs_poll_getpath(uv_fs_poll_t* handle, char* buf, size_t* len);
UV_EXTERN int uv_exepath(char* buffer, size_t* size);
UV_EXTERN int uv_cwd(char* buffer, size_t* size);
UV_EXTERN int uv_pipe_getsockname(const uv_pipe_t* handle,
                                  char* buf,
                                  size_t* len);
UV_EXTERN int uv_fs_event_getpath(uv_fs_event_t* handle,
                                  char* buf,
                                  size_t* len);
```

To begin with, we have inconsistent names. buf - buffer, len - size.

The more disturbing part is that uv_cwd and uv_exepath return the exact length of the string and uv_fs_poll_getpath returns +1(it probably counts the 0 terminating symbol as well), so I need to manually decrease it by 1, which is suboptimal.

The len+1 happens on ubuntu 14.04 64bit.

Should we make the names more consistent?

Should we return the exact size of the string?

**Comment by txdv** [comment]
getsockname has a trailing 0 as well.

**Comment by saghul** [comment]
I added 3 of those functions, and with uv_exepath and uv_cwd we wen't back and forth :-S I'll take a look.

**Comment by txdv** [comment]
uv_fs_event_getpath has a trailing 0 as well

**Comment by txdv** [comment]
Will a change for this 'break' the API? If we return the real size in the buffer?

**Comment by saghul** [comment]
> Will a change for this 'break' the API? Returning the real size of the buffer?

I don't think so.

**Comment by bnoordhuis** [comment]
I don't know, it can introduce some pretty insidious bugs.  Probably warrants at least a minor bump and a mention in the release notes.

**Comment by txdv** [comment]
So what about the naming of the variables? Should we use (void* buf, size_t* len) or (void* buffer, size_t* size) ?

**Comment by bnoordhuis** [comment]
I like buffer and size.
