### ISSUE TITLE
win: fs__open: support FILE_FLAG_WRITE_THROUGH and FILE_FLAG_NO_BUFFERING

### ISSUE THREAD

**Issue by jorangreef** [libuv/libuv#1550]
On Windows, `fs__open()` does not yet support setting `FILE_FLAG_WRITE_THROUGH` and `FILE_FLAG_NO_BUFFERING`. These are the Windows equivalents of `O_SYNC` and `O_DIRECT` respectively and provide a significant performance boost on Windows for certain applications.

It's not recommended to add support for these using a native add on due to conversion issues between handles and file descriptors, see https://github.com/nodejs/node/issues/15433 for context.

Would it be okay for me to go ahead and open a PR to add support for these flags?

My intention is to implement `FILE_FLAG_WRITE_THROUGH` and `FILE_FLAG_NO_BUFFERING` via the unused `_O_TEXT` and `_O_BINARY` flags respectively. These flags are not likely to be used since they don't apply to Linux and I don't know if anyone actually uses them on Windows? Libuv has also conveniently already explicitly not supported `_O_TEXT` and `_O_BINARY` as per the docs:

```
On Windows libuv uses CreateFileW and thus the file is always opened in binary mode.
Because of this the O_BINARY and O_TEXT flags are not supported.
```

In Node, my intention is then to expose three new constants (`O_DSYNC`, `O_SYNC` and `O_DIRECT`) for Windows, mapped to `_O_TEXT` and `_O_BINARY` behind the scenes.

**Comment by jorangreef** [comment]
Or perhaps there's a better way to implement it?

**Comment by bzoz** [comment]
Why won't you use `O_SYNC` and `O_DIRECT` for `FILE_FLAG_WRITE_THROUGH` and `FILE_FLAG_NO_BUFFERING`?

**Comment by jorangreef** [comment]
> Why won't you use O_SYNC and O_DIRECT for FILE_FLAG_WRITE_THROUGH and FILE_FLAG_NO_BUFFERING?

They are not defined on Windows? Or do you mean why don't we define them in Libuv?

**Comment by jorangreef** [comment]
Libuv expects the user to pass in flags defined in `fcntl.h` on Windows.

Of those, `_O_TEXT` and `_O_BINARY` are unused and likely to remain unused forever.

I don't want to define `O_DIRECT` and `O_SYNC` flags on Windows in case the user uses these as a proxy for platform feature detection.

I'm wary of trying to pick a value that won't collide with those in `fcntl.h`.

I'm not sure if Libuv exposes it's own flag constants, e.g. `UV_O_RDWR`, `UV_O_DIRECT` etc. of course if it already does that then that would be a better way to go.

But if it's just flags defined in `fcntl.h` then I think using the unused flags is better than mixing others in.

**Comment by bnoordhuis** [comment]
I think introducing `UV_O_DIRECT` and friends is a better approach than repurposing existing constants with different semantics.

**Comment by jorangreef** [comment]
> I think introducing UV_O_DIRECT and friends is a better approach than repurposing existing constants with different semantics.

Agreed. Can I start on this? I'm going to map all the existing flags out to `UV_O_` equivalents to ensure backwards compatibility.

Would this be okay on the stable branch then?

**Comment by bzoz** [comment]
That sounds like the best solution.

If the old flags keep working, I don't see a reason why this shouldn't be added to v1.x
