### ISSUE TITLE
Intermitent failure - zOS

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#1556]
* **Version**: v1.x
* **Platform**: z/OS

Failed in https://ci.nodejs.org/view/libuv/job/libuv-test-commit-zos/153/nodes=zos-s390x/console

Did not repeat in next run:
```
[5:59] 
not ok 236 - signal_multiple_loops
# timeout
# Output from process `signal_multiple_loops`:
# CEE3204S The system detected a protection exception (System Completion Code=0C4).
#          From entry point epoll_file_close at compile unit offset +000000001A2EA1D6 at entry offset +00000000000000FE at address 000000001A2EA1D6.
```

**Comment by mhdawson** [comment]
@jBarz

**Comment by jBarz** [comment]
I am investigating this

**Comment by jBarz** [comment]
Submitted a potential fix. https://github.com/libuv/libuv/pull/1560

**Comment by jBarz** [comment]
should be fixed

**Comment by bnoordhuis** [comment]
Drat, I didn't add a `Fixes:` tag.  Oh well, closing.
