### ISSUE TITLE
win,build: CI on VS2017

### ISSUE THREAD

**Issue by refack** [libuv/libuv#1562]
* **Version**: *
* **Platform**: Windows (VS2017)

We should have a job that builds on VS2017.
/cc @joaocgreis, I can help set that up.

**Comment by joaocgreis** [comment]
I ran a few test jobs and saw failures in about 1/3 of them, all in different tests:
- [`threadpool_cancel_fs`](https://ci.nodejs.org/view/All/job/reis-uv-2017/2/nodes=win2012r2-vs2017/console)
- [`threadpool_cancel_getnameinfo`](https://ci.nodejs.org/view/All/job/reis-uv-2017/3/nodes=win2012r2-vs2017/console)
- [`threadpool_cancel_work`](https://ci.nodejs.org/view/All/job/reis-uv-2017/4/nodes=win2012r2-vs2017/console)
- [`fs_poll_ref`](https://ci.nodejs.org/view/All/job/reis-uv-2017/10/nodes=win2012r2-vs2017/console)

I was not able to reproduce locally. Are these known flaky tests? Should I make the changes in the real job even with these failures unsolved?

cc @saghul @bzoz

**Comment by joaocgreis** [comment]
Should I go ahead and change the job or is this blocking?

**Comment by bzoz** [comment]
Go ahead!

**Comment by joaocgreis** [comment]
Done, added to the main job.

**Comment by Himself65** [comment]
I think this issue has done
