### ISSUE TITLE
win: fs__stat_handle() sets st_blksize = 2048 (suboptimal)

### ISSUE THREAD

**Issue by jorangreef** [libuv/libuv#1563]
On Windows, `fs__stat_handle()` sets `st_blksize` to `2048` regardless of the underlying physical sector size of the disk:

```
  /* The st_blksize is supposed to be the 'optimal' number of bytes for reading
   * and writing to the disk. That is, for any definition of 'optimal' - it's
   * supposed to at least avoid read-update-write behavior when writing to the
   * disk.
   *
   * However nobody knows this and even fewer people actually use this value,
   * and in order to fill it out we'd have to make another syscall to query the
   * volume for FILE_FS_SECTOR_SIZE_INFORMATION.
   *
   * Therefore we'll just report a sensible value that's quite commonly okay
   * on modern hardware.
   */
  statbuf->st_blksize = 2048;
```

For newer Advanced Format drives, `4096` would be much better than `2048` since `2048` will still incur read-update-write behavior on AF drives which have a `4096` physical sector size.

**Comment by jorangreef** [comment]
If anyone does ever happen to rely on `st_blksize`, then `4096` would be much more reliable.

**Comment by jorangreef** [comment]
Does anyone actually know where `2048` came from?

**Comment by bzoz** [comment]
The commit for `2048` is here: https://github.com/libuv/libuv/commit/20a8e58adb2a3fc2e92ceb6e1ceb6f05d7e0d439. No PR link, I guess the comment says it all - `2048` is just good enough.

If there are 4k drives out there I guess we should at least bum this to `4096`. But I don't see any reason not to query the OS for the actual sector size.

**Comment by jorangreef** [comment]
> If there are 4k drives out there I guess we should at least bum this to 4096.

I will submit a PR to do that.

> But I don't see any reason not to query the OS for the actual sector size.

That might impact the performance of `fs__stat_handle()` too much, without much benefit.

Would anyone be interested in a separate libuv call to get block device stats properly? At present, `fs.fstat()` on a block device on Windows just returns an error.

I released a native add on yesterday for detecting block device size, physical sector size and logical sector size (cross-platform) https://github.com/ronomon/direct-io

Almost everything is in there already, if someone wants to do the PR work to bring it in.
