### ISSUE TITLE
uv_backend_timeout() should return 0 after watcher queue updated

### ISSUE THREAD

**Issue by c0nk** [libuv/libuv#1565]
Hi,
I am trying to embed libuv into another event loop. After the watcher queue is modified uv_backend_timeout() should return 0 so that uv_run can be called again immediately to add the fds to the poll set. Otherwise, the embed thread can't be notified of events on these fds. Electron has solved this with an ugly hack:
https://github.com/electron/node/commit/693b35014efe6416d52e3ae0c1bcfa173670e45b#diff-2f99e28360b27d4873b9a7678227d11c

I think if uv_backend_timeout() would return 0 in this case, it would be feasible to embed libuv without relying on custom patches.

**Comment by cjihrig** [comment]
Just FYI, https://github.com/libuv/libuv/issues/965 looked at how libuv is embedded in Electron. That commit was addressed, and resulted in https://github.com/libuv/libuv/pull/1007. Unfortunately, that commit is in master, not v1.x, so it won't be available until libuv 2.

**Comment by c0nk** [comment]
This issue is unrelated to #1007 which only adds a "blessed" way to embed libuv on windows. Electron still relies on the on_watcher_queue_updated hack on Linux/Mac. It would be nice if this could be addressed, so no hack is needed.

**Comment by vtjnash** [comment]
Does Electron still use that hack? I won't pretend to understand it, but seems worthwhile trying to upstream something if Electron has found it to be needed.

**Comment by bnoordhuis** [comment]
There's a PR from an Electron maintainer (#1921) but that seems to have stalled.

**Comment by codebytere** [comment]
I'd let that slip me by, but i can try to get back to and reinvigorate it sometime in the next few weeks i believe.

**Comment by bnoordhuis** [comment]
@codebytere That'd be great. I've reopend the PR, it was auto-closed.

**Comment by codebytere** [comment]
thanks @bnoordhuis 🙇‍♀
