### ISSUE TITLE
z/OS threadpool cleanup

### ISSUE THREAD

**Issue by jBarz** [libuv/libuv#1569]
On z/OS, we are seeing issues with the threadpool cleanup function.

`UV_DESTRUCTOR(static void cleanup(void))`

This is because on the platform, we are not allowed to call pthread functions inside the exit handler and/or the destructor functions.
Is there a mechanism for the libuv user to safely terminate the threadpool?
If not, would it be ok to expose an API call to do this?

* **Version**: 1.14.1
* **Platform**: z/OS

**Comment by bnoordhuis** [comment]
Short, flippant answer: no (to both questions.)

Longer answer: IIRC (which I might not - it was 5 years ago), I only added the destructor to shut up valgrind when running the test suite.  Unless you actually need this, I'd suggest simply #ifdef'ing it out on z/os.
