### ISSUE TITLE
uv_pipe_peername

### ISSUE THREAD

**Issue by txdv** [libuv/libuv#157]
Since we have uv_pipe_sockname, wouldn't it be nice to have for simple pipes uv_pipe_peername to return the string to which it connected?

**Comment by bnoordhuis** [comment]
If it returns a string, how is it going to interact with Linux abstract sockets?

**Comment by txdv** [comment]
It is a pointer to a buffer and a pointer to the length of the buffer.

It doesn't matter whether its a string or some other bock of information.

**Comment by saghul** [comment]
> If it returns a string, how is it going to interact with Linux abstract sockets?

It could be just like `uv_pipe_getsockname`:

~~~~
int uv_pipe_getpeername(const uv_pipe_t* handle, char* buf, size_t* len)
~~~~

`len` would contain the length so it works for abstract sockets too.

I'm +1, and in retrospect I'm not sure why I didn't write it when I added `uv_pipe_getsockname`. Are you going to provide a patch?

**Comment by bnoordhuis** [comment]
The 'returns a string' bit threw me off; a `char* uv_pipe_getpeername(uv_pipe_t* handle)` for example would not be useful with abstract sockets.

> in retrospect I'm not sure why I didn't write it when I added uv_pipe_getsockname

Because it just returns the path you passed to uv_pipe_connect()? :-)

**Comment by saghul** [comment]
> Because it just returns the path you passed to uv_pipe_connect()? :-)

I guess that was the reason, but if we want to know it in the handle where we called `uv_accept`, `getsockname` won't do...

**Comment by bnoordhuis** [comment]
Not sure I understand.  For the server, it's server_handle->pipe_fname.

**Comment by saghul** [comment]
That's a private field, right? Also, it won't contain anything in case handle had the fd assigned with `uv_pipe_open`.

**Comment by bnoordhuis** [comment]
Sure, but I mean that you know the address because it's what was passed to uv_pipe_bind().

I concede the point about uv_pipe_open().  About that: uv_pipe_getpeername() would probably do well to check that sa_family == AF_UNIX because people do sometimes pass non-UDS file descriptors to uv_pipe_open().

**Comment by saghul** [comment]
> uv_pipe_getpeername() would probably do well to check that sa_family == AF_UNIX because people do sometimes pass non-UDS file descriptors to uv_pipe_open().

Good point!

**Comment by saghul** [comment]
#166 landed, closing.
