### ISSUE TITLE
Node/libuv isn't picking up the default shell if /etc/passwd is blank

### ISSUE THREAD

**Issue by gibfahn** [libuv/libuv#1570]
* **Version**: 1.14.1
* **Platform**: Linux foo 3.13.0-123-generic #172-Ubuntu SMP Mon Jun 26 18:03:29 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux (Ubuntu 14.04)

I was debugging a test failure in Node:

[This line](https://github.com/nodejs/node/blob/4843c2f41571088b16e673c1f996bc361ab526a6/test/parallel/test-os.js#L196
) failed:

```js
const pwd = os.userInfo();
assert.ok(pwd.shell.includes(path.sep));
```

`pwd.shell` is empty.

Turns out this is because my user's entry in `/etc/passwd` doesn't contain a shell:

```
gib:x:1234:3210:Gibson Fahnestock:/home/gib:
```

Thus I get the default shell, which either coming from `/etc/adduser.conf`:

```
# The DSHELL variable specifies the default login shell on your
# system
DSHELL=/bin/bash
```

or is just defaulting to `/bin/sh`, which on this system (Ubuntu 14.04) is a symlink to `/bin/bash`.

Looks like Node `os.userInfo()` calls `uv__getpwuid_r`, which just calls `getpwuid_r(3)`

https://github.com/nodejs/node/blob/8485a7c0b71fd1dd36947a6dd02b75387805d9b7/deps/uv/src/unix/core.c#L1153

I think `os.userInfo()` should return my shell (either by checing `/etc/adduser.conf`, or just by checking `process.env.SHELL`). However I'm not sure whether this should be in Node or in libuv. I'm happy to submit a PR to either.

**Comment by cjihrig** [comment]
Out of curiosity, what value is returned by libuv and Node in this case? Is it `NULL` or empty string?

I'm not sure that this should be fixed in libuv because the `uv_os_get_passwd()` docs state:

> Gets a subset of the password file entry for the current effective uid

Since that data isn't in the password file entry, I think it makes sense not to return it.

**Comment by cjihrig** [comment]
Actually, it looks like the `os.userInfo()` docs also state that the data comes from the password file. So, it might just make sense to update the test.

**Comment by gibfahn** [comment]
Node returns the empty string.

I'm not sure how one would update the test, you'd basically have to just stop testing it.

I guess it comes down to whether `os.userInfo().shell` is supposed to return the user's shell, or if it's just supposed to tell you what was in `/etc/passwd`.

However that's a discussion we should probably have in node, so assuming there's no plan to fix this in libuv (which seems reasonable), I'll open this in node instead.

**Comment by gibfahn** [comment]
Continued in https://github.com/nodejs/node/issues/15684
