### ISSUE TITLE
uv_pipe_t, uv_write2(), uv_pipe_pending_{count,type}(): why is it designed the way it is?

### ISSUE THREAD

**Issue by EdSchouten** [libuv/libuv#1587]
Hi there,

I'm interested in using libuv inside of sandboxed applications ([Capsicum](https://wiki.freebsd.org/Capsicum)). One of the things I was happy to see is that libuv provides some support for UNIX file descriptor passing (i.e., `sendmsg()` and `recvmsg()` with `SCM_RIGHTS`). That said, the way it's been designed, it has some restrictions:

- There is only support for attaching a single file descriptor to a write. `uv_write2()` doesn't take an array of file descriptors; just a single descriptor.
- On the receiving side, file descriptors have to be fetched using `uv_accept()`. This function can only accept streams; not arbitrary handles. This means you can't use this approach to pass in regular files, directories, etc.

Before sending pull requests or discussing any API changes, I'm actually interested in knowing what the intended use case of this API is. Is any piece of software out there making use of this?

**Comment by bnoordhuis** [comment]
> Is any piece of software out there making use of this?

Most certainly.  Node.js, its child_process and cluster modules in particular, are pretty much built around it.

The answer to your other question, why it works the way it does, is essentially 'Windows.'

**Comment by EdSchouten** [comment]
> The answer to your other question, why it works the way it does, is essentially 'Windows.'

That explains things. Thanks for clarifying!

For now I'll be able to make use of `uv_poll_t` + `sendmsg()`/`recvmsg()`, so there's no immediate rush to address this. I'll keep this on my (by now infinitely long) todo list... ;-)
