### ISSUE TITLE
uv_timer_again(): documentation contradicts implementation

### ISSUE THREAD

**Issue by EdSchouten** [libuv/libuv#1591]
The `uv_timer_again()` function is implemented as follows (in master):

```
int uv_timer_again(uv_timer_t* handle) {
  if (handle->timer_cb == NULL)
    return -EINVAL;

  if (handle->repeat) {
    uv_timer_stop(handle);
    uv_timer_start(handle, handle->timer_cb, handle->repeat, handle->repeat);
  }

  return 0;
}
```

And it as documented like this:

> int uv_timer_again(uv_timer_t* handle)
> Stop the timer, and if it is repeating restart it using the repeat value as the timeout. If the timer has never been started before it returns UV_EINVAL.

The documentation is different from the implementation, in the sense that the timer is only stopped if the timer is repeating. Two ways of resolving this:

1. Change the code:

```
int uv_timer_again(uv_timer_t* handle) {
  if (handle->timer_cb == NULL)
    return -EINVAL;

  uv_timer_stop(handle);
  if (handle->repeat)
    uv_timer_start(handle, handle->timer_cb, handle->repeat, handle->repeat);

  return 0;
}
```

2. Change the documentation:

> int uv_timer_again(uv_timer_t* handle)
> If the timer is repeating, stop it and restart it using the repeat value as the timeout. If the timer has never been started before it returns UV_EINVAL.

Which approach would be correct in this case?

**Comment by bnoordhuis** [comment]
I think it would make sense to follow the documentation, i.e.:
```c
uv_timer_stop(handle);
if (handle->repeat)
  uv_timer_start(handle, ...);
```
Although you could argue it only makes sense to call `uv_timer_again()` for repeating timers, in which case returning an error is more appropriate:
```c
if (handle->repeat == 0)
  return UV_EINVAL;
```
@libuv/collaborators Thoughts?

**Comment by santigimeno** [comment]
> Although you could argue it only makes sense to call uv_timer_again() for repeating timers, in which case returning an error is more appropriate

This makes more sense to me.

**Comment by cjihrig** [comment]
I would prefer to follow the existing documentation, at least in v1.x.

**Comment by cjihrig** [comment]
Fixed in master by https://github.com/libuv/libuv/commit/f8abdf67f8c91154225c799b3964d9d89c38a9e4.
