### ISSUE TITLE
uv_loop_alive(): documentation contradicts implementation

### ISSUE THREAD

**Issue by EdSchouten** [libuv/libuv#1592]
The `uv_loop_alive()` function is implemented as follows (in master):

```
static int uv__loop_alive(const uv_loop_t* loop) {
  return uv__has_active_handles(loop) ||
         uv__has_active_reqs(loop) ||
         loop->closing_handles != NULL;
}

int uv_loop_alive(const uv_loop_t* loop) {
    return uv__loop_alive(loop);
}
```

And it as documented like this:

> int uv_loop_alive(const uv_loop_t* loop)
> Returns non-zero if there are active handles or request in the loop.

The documentation is different from the implementation, in the sense that the loop is also considered alive when there are handles being closed. Two ways of resolving this:

1. Change the code:

```
static int uv__loop_alive(const uv_loop_t* loop) {
  return uv__has_active_handles(loop) ||
         uv__has_active_reqs(loop);
}
```

2. Change the documentation:

> int uv_loop_alive(const uv_loop_t* loop)
> Returns non-zero if there are active handles, active requests or closing handles in the loop.

Which approach would be correct in this case?

**Comment by bnoordhuis** [comment]
Option 2.  A closing handle is considered active because its close callback must be invoked.

(The documentation for `uv_close()` hints at that but it might be good to call it out explicitly.)
