### ISSUE TITLE
uv_interface_addresses misses usb wifi devices

### ISSUE THREAD

**Issue by mwillbanks** [libuv/libuv#160]
From what I understand, uv_interface_addresses will miss items that it believes are not active as seen in #158, however, I am filing this issue because this one is indeed active and is not parsed.  This is running on a BeagleBone Black device with a wifi usb card.

Take note of the following output (excluded certain items around lo and eth0 except in the node output):

*/etc/network/interfaces*
```
iface usb0 inet static
    address 192.168.7.2
    netmask 255.255.255.0
    network 192.168.7.0
    gateway 192.168.7.1
```

*ifconfig*
```
usb0      Link encap:Ethernet  HWaddr a2:b2:8b:b9:00:50
          inet addr:192.168.7.2  Bcast:192.168.7.3  Mask:255.255.255.252
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

*node*
```
var os = require('os');
console.log(JSON.stringify(os.networkInterfaces(), null, 4));
```

which leads to the incorrect output:
```
{
    "lo": [
        {
            "address": "127.0.0.1",
            "family": "IPv4",
            "internal": true
        },
        {
            "address": "::1",
            "family": "IPv6",
            "internal": true
        }
    ],
    "eth0": [
        {
            "address": "192.168.4.2",
            "family": "IPv4",
            "internal": false
        },
        {
            "address": "fe80::7aa5:4ff:feca:d9bd",
            "family": "IPv6",
            "internal": false
        }
    ]
}
```

This should be the following output:
```
{
    "lo": [
        {
            "address": "127.0.0.1",
            "family": "IPv4",
            "internal": true
        },
        {
            "address": "::1",
            "family": "IPv6",
            "internal": true
        }
    ],
    "eth0": [
        {
            "address": "192.168.4.2",
            "family": "IPv4",
            "internal": false
        },
        {
            "address": "fe80::7aa5:4ff:feca:d9bd",
            "family": "IPv6",
            "internal": false
        }
    ],
    "usb0": [
        {
            "address": "192.168.7.2",
            "family": "IPv4",
            "internal": false
        }
    ]
}
```

**Comment by bnoordhuis** [comment]
I'm not 100% sure but I suspect that `ifa_flags & IFF_RUNNING` is false for that device because it hasn't seen any traffic yet.

**Comment by mwillbanks** [comment]
Yeah, I might suspect the same, I'm debugging it right now via regular C w/o libuv to determine what is going on.  Initially it looks like there is nothing wrong at the libuv level and that it is working properly.  From the standpoint of usb wifi items; it is certainly a wash with odd responses coming from the underlying libs.

**Comment by saghul** [comment]
@bnoordhuis shouldn't we relax that a bit? According to http://stackoverflow.com/questions/11679514/what-is-the-difference-between-iff-up-and-iff-running, if an interface is configured but the cable is not plugged we wouldn't list it, would we? Maybe just checking for `IFF_UP` is enough, since we then check if `ifa_addr` is NULL or not?

**Comment by bnoordhuis** [comment]
@saghul I wish there was a good word for expressing ambivalence without implying indifference, because that's what I'm feeling right now.  :-)  If you think it's a good idea, sure, go ahead.

**Comment by saghul** [comment]
@bnoordhuis you made yourself pretty clear Ben :-) I'll keep it somewhere at the back of my head.
