### ISSUE TITLE
Assert failed in the s5 proxy sample.

### ISSUE THREAD

**Issue by ssrlive** [libuv/libuv#1604]
When the `nread` is equal to `UV_EOF` or `UV_ECONNRESET`, the `buf->base` is `NULL`. Please fix the assert.

http://docs.libuv.org/en/v1.x/stream.html#c.uv_read_cb

https://github.com/libuv/libuv/blob/719dfecf95b0c74af6494f05049e56d5771ebfae/samples/socks5-proxy/client.c#L668

**Comment by ssrlive** [comment]
I have fixing the assert fail and lots of memory leak. Please look at https://github.com/ssrlive/s5proxy

**Comment by bnoordhuis** [comment]
If you have a fix, please open a pull request and we'll take it from there.

**Comment by ssrlive** [comment]
I have changed the code base many points.

**Comment by ssrlive** [comment]
I have committed a PR https://github.com/libuv/libuv/pull/1608
