### ISSUE TITLE
win: fs__open(): map UV_FS_O_EXLOCK to exclusive sharing mode to enable raw block device access on Windows

### ISSUE THREAD

**Issue by jorangreef** [libuv/libuv#1605]
On Windows, `fs__open()` sets the requested sharing mode of the file as follows:

```
share = FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE;
```

This is to ensure that a file can be deleted on Windows even while open (see https://github.com/nodejs/node-v0.x-archive/issues/1449).

This is fine, but sometimes on Windows it is also necessary to open a file or block device for exclusive access, not for the sake of locking per se but for writing:

For example, one cannot write past a raw block device MBR on Windows, without an exclusive file handle (see https://support.microsoft.com/en-us/help/942448/changes-to-the-file-system-and-to-the-storage-stack-to-restrict-direct).

Since we now have all open flags mapped to `UV_FS_O_` constants, would it be fine for me to do a PR to map `UV_FS_O_EXLOCK` to exclusive sharing mode on Windows?

**Comment by bzoz** [comment]
SGTM

Can `UV_FS_O_EXLOCK` be also implemented on Linux?

**Comment by bnoordhuis** [comment]
It's... complicated.  Unices in general only support advisory ("play nice") locks.  Linux in specific supports mandatory locks but they are riddled with pitfalls.

From https://www.kernel.org/doc/Documentation/filesystems/mandatory-locking.txt:
```
0. Why you should avoid mandatory locking
-----------------------------------------

The Linux implementation is prey to a number of difficult-to-fix race
conditions which in practice make it not dependable:

	- The write system call checks for a mandatory lock only once
	  at its start.  It is therefore possible for a lock request to
	  be granted after this check but before the data is modified.
	  A process may then see file data change even while a mandatory
	  lock was held.
	- Similarly, an exclusive lock may be granted on a file after
	  the kernel has decided to proceed with a read, but before the
	  read has actually completed, and the reading process may see
	  the file data in a state which should not have been visible
	  to it.
	- Similar races make the claimed mutual exclusion between lock
	  and mmap similarly unreliable.
```

**Comment by jorangreef** [comment]
This issue is not intended to be about the merits or pitfalls of mandatory locking per se, but **specifically about opening a raw block device on Windows for writing which requires exclusive access on Windows according to policy changes by Microsoft detailed in https://support.microsoft.com/en-us/help/942448/changes-to-the-file-system-and-to-the-storage-stack-to-restrict-direct**.

> Can UV_FS_O_EXLOCK be also implemented on Linux?

No, while `O_EXLOCK` can be used to open a block device for exclusive access on Darwin, the equivalent to `O_EXLOCK` for opening a block device for exclusive access on Linux is surprisingly `O_EXCL`:

From the Linux man page for open, http://man7.org/linux/man-pages/man2/open.2.html:

```
In general, the behavior of O_EXCL is undefined if it is used without O_CREAT.  There is one exception: on Linux 2.6 and later, O_EXCL can be used without O_CREAT if pathname refers to a block device.  If the block device is in use by the system (e.g., mounted), open() fails with the error EBUSY.
```

More and more block device utilities (CD writers etc.) have started using either `O_EXCL` or `O_EXLOCK` when opening block devices, depending on the platform. This is probably why kernel 2.6 started addressing the lack of exclusive block device access through `O_EXCL`.

**Again, this issue is not really about `O_EXLOCK` vs `O_EXCL` for block devices, but about enabling writes to block devices on Windows, which requires a sharing mode of 0.** Windows explicitly requires a block device to be opened for exclusive access before you can write past the MBR.

The proposal then is to map `UV_FS_O_EXLOCK` to a sharing mode of 0 on Windows. This would behave the same as `O_EXLOCK` for a block device on Darwin, and as `O_EXCL` for a block device on Linux.

The motivation for mapping `O_EXLOCK` rather than `O_EXCL` is that `O_EXCL` is ambiguous and carries other semantics (Linux probably should have gone with `O_EXLOCK` for exclusive block device access).
