### ISSUE TITLE
Feature Request : API for *blocking* socket api

### ISSUE THREAD

**Issue by jdonaldson** [libuv/libuv#1606]
Yes, this is totally antithetical to the very nature of the library, but hear me out...

Libuv is quickly becoming a default system layer for many toolkits.  Most of these toolkits have some sort of legacy support for synchronous operations.  While Libuv provides optional synchronous functionality in some cases (e.g. reading files), the socket api does not have anything like that.

If a synchronous api for sockets were provided via libuv, I would use it in some of my own projects, and be able to drop some extra os-specific socket-related dependencies.

Thanks again for this amazing library!

**Comment by bnoordhuis** [comment]
I've added the feature-request label although I predict there won't be much enthusiasm.

FWIW, you can already kind of fake blocking I/O: create a new event loop with `uv_loop_new()` or `uv_loop_init()`, create a socket and call `uv_run()`.  Run it in a separate thread if you want traditional read/write/accept semantics in your main thread.

Not super elegant or efficient but workable.

**Comment by jdonaldson** [comment]
Good to know it's a suggested workaround, I already have something like that in place in an experimental branch.  It can cause surprising side effects if one mixes sync/async code though.  I'll think about ways of keeping surprises to a minimum.

**Comment by bnoordhuis** [comment]
It's been three weeks and no collaborators spoke out in favor.  I'm closing this out but let me know if  it should be reopened.

**Comment by jdonaldson** [comment]
Yeah, I'm guessing my situation is pretty unique then.  If others stumble across this thread later, they can add a comment, and we can reopen.  Thanks for considering.
