### ISSUE TITLE
We should check r together with errno, or force errno to zero before a call to clock_gettime()

### ISSUE THREAD

**Issue by vitalyvch** [libuv/libuv#1614]
https://github.com/libuv/libuv/blob/6445cc63080f35370d38434666fa4ae9f7b3f41c/src/unix/linux-core.c#L544

In this code, the call to clock_gettime() is only the reason of value of errno if "r == -1".

**Comment by cjihrig** [comment]
Care to elaborate? The current logic seems correct to me. If `clock_gettime()` succeeds, it returns `0`, and the `errno` comparison is never executed.

**Comment by vitalyvch** [comment]
@cjihrig I'm sorry, yes you are right - it is correct. I was confused with the assignment in condition.

> and the errno comparison is never executed.

Usually, it's true but not always.
