### ISSUE TITLE
Tests may fail nondeterministically on machines with slow IO

### ISSUE THREAD

**Issue by lheckemann** [libuv/libuv#1615]
* **Version**: 1.15.0
* **Platform**: Linux green 4.13.8 #26 SMP Thu Nov 2 19:46:09 GMT 2017 armv7l GNU/Linux

`make check` failed for me on `ipc_send_recv_pipe` and `fs_copyfile` with timeouts. Rerunning it fixed the issue. I suspect this is linked to having my rootfs on a USB stick and simultaneously running other builds the first time round.

**Comment by bnoordhuis** [comment]
Thanks for the report.  Some of the tests are timing sensitive by nature.  Unfortunately there isn't much that can be done about that.
