### ISSUE TITLE
Intermittent failure in fs_copyfile on windows

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#1618]
* **Version**: v.1x
* **Platform**: win10-vs2015

Intermittent failure seen a few times on runs for different PRs:

https://ci.nodejs.org/job/libuv-test-commit-windows/635/
https://ci.nodejs.org/view/libuv/job/libuv-test-commit/554/

```
not ok 33 - fs_copyfile
# exit code 3
# Output from process `fs_copyfile`: (no output)
```

**Comment by cjihrig** [comment]
I haven't seen this recently. If it becomes an issue again, we can reopen.
