### ISSUE TITLE
named constants introduced by uv_poll_event used for pipe handles

### ISSUE THREAD

**Issue by skypjack** [libuv/libuv#1621]
Note: This isn't a bug in libuv, probably the issue should be marked as _discussion_.

---

`UV_WRITABLE` and `UV_READABLE` are introduced by the enum `uv_poll_event`.
Recently, because of `uv_pipe_chmod`, they have been used for pipe handles.
Set aside the fact that _it works_ because of how enums work in general, isn't it a bit misleading at least?
It's also error-prone at some extent. A future change or PR or whatever could address those values concerning the sole poll event stuff and thus with the risk of breaking the pipe stuff.

Could it worth it changing the name of the enum to a more opaque one (actually I suspect it's a breaking change) or define a different enum for pipe handles, with its own constants?

**Comment by Amirhosein835** [comment]
I want the for beta free data >.>Thank uou

**Comment by Giangiui** [comment]
I have this issue recently, the UV_WRITABLE/UV_READABLE variables is in conflict with same variables in another library and I can't resolve this issues
