### ISSUE TITLE
Application core dump

### ISSUE THREAD

**Issue by xajhuang** [libuv/libuv#1628]
when application running a long time:

Assertion failed: loop->watchers[w->fd] == w (src/unix/core.c: uv__io_stop: 881) 
Aborted (core dumped)

Version: 1.11.0 
Platform: OpenWrt Linux

**Comment by bnoordhuis** [comment]
Are you reporting a bug in libuv or just looking for help?  For the former we'll need a way to reproduce.  For the latter, please go to the help repo.

**Comment by bnoordhuis** [comment]
Closing, no follow-up.
