### ISSUE TITLE
Add z/OS test subjob to main libuv test job

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#1643]
* **Version**: all
* **Platform**: z/OS

Thanks to the hard work of @jBarz the test job for z/OS is now green. https://ci.nodejs.org/view/libuv/job/libuv-test-commit-zos/

I'd like to add that job as one of the sub-jobs for the main test job [libuv-test-commit[(https://ci.nodejs.org/view/libuv/job/libuv-test-commit/)

@saghul @bnoordhuis @cjihrig any objections ? 

@jBarz - FYI

**Comment by bnoordhuis** [comment]
Good idea, let's.

**Comment by cjihrig** [comment]
SGTM!

**Comment by mhdawson** [comment]
Added  and passed in https://ci.nodejs.org/view/libuv/job/libuv-test-commit/, Closing
