### ISSUE TITLE
IRC URL in Contributing guide is incorrect

### ISSUE THREAD

**Issue by mtharrison** [libuv/libuv#1646]
It says `http://webchat.freelibuv.net/?channels=libuv`. Guess a find and replace at some point s/node/libuv.

**Comment by refack** [comment]
I see you had the same intuition I had.

**Comment by cjihrig** [comment]
Missed this. Closed by https://github.com/libuv/libuv/commit/dadad46d70ab0f5c8aebce33c7c313b03d12f197.
