### ISSUE TITLE
How to install after compiling with Ninja?

### ISSUE THREAD

**Issue by concatime** [libuv/libuv#1652]
In the [instructions](//github.com/libuv/libuv#using-ninja), you only provide how to generate and build with ninja. Actully, how do I install LibUV after building it with ninja? There is no `ninja install`.

**Comment by bnoordhuis** [comment]
Short answer is "you don't" - ninja is a build tool, not a packaging tool.

Use autotools if you want install functionality.  GYP+ninja is predominantly for projects where libuv is embedded as a component in a larger project, such as in Node.js.

**Comment by concatime** [comment]
Ok, I understand. That's why it produces only a `libuv.a` static library. Thank you ;)
