### ISSUE TITLE
Get master branch of libuv compiling for z/OS (shipping v1.x is fine)

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#1663]
* **Version**: master
* **Platform**: z/OS

Master is failing with

```bash
FSUM3212 xlc: Command option -p is incorrect for z/OS platform - ignored.
FSUM3210 xlc: Command option -thread contains an incorrect subargument.
FSUM3212 xlc: Command option -fvisibility=hidden is incorrect for z/OS platform - ignored.
FSUM3216 xlc: Command option --std=gnu99 is not recognized - passed to ld.
FSUM3212 xlc: Command option -p is incorrect for z/OS platform - ignored.
FSUM3210 xlc: Command option -Wall contains an incorrect subargument.
```

We probably just need to backport the changes from v1.x.  I'm not sure how this would normally happen, but I saw at least one end user CI job fail (obviously testing master) so its probably good to at least get the basics backported.  

@jBarz can you take a look at this.

**Comment by jBarz** [comment]
https://github.com/libuv/libuv/pull/1664

**Comment by bnoordhuis** [comment]
See #1630, master is quite a bit behind v1.x.  Getting them in sync again however is turning out to be a giant pain in the neck.

**Comment by cjihrig** [comment]
This is no longer an issue per https://github.com/libuv/libuv/pull/1664#issuecomment-370798788
