### ISSUE TITLE
uv_tcp_getsockname() always get "bad address in system call argument"?

### ISSUE THREAD

**Issue by ohsorry** [libuv/libuv#1666]
* **Version**: 1.15.0
* **Platform**: Windows Server 2008 R2 Datacenter with sp1

i try uv_tcp_getsockname() with official demo "tcp-echo-server" and my own testing demo, both not work.
here is the code in tcp-echo-server demo:

![uvtest](https://user-images.githubusercontent.com/6219683/33495760-a0244fb0-d702-11e7-94d0-b738bf68c97c.PNG)

**Comment by bnoordhuis** [comment]
You need to set `int addrClientLen = sizeof(addrClient);`.  Please post questions to the help repo next time, that's what it's for.

**Comment by ohsorry** [comment]
got it.
thank you.
both uv_tcp_getpeername and uv_tcp_getsockname works
