### ISSUE TITLE
error: IF_MAX_STRING_SIZE undeclared 

### ISSUE THREAD

**Issue by s97712** [libuv/libuv#1667]
* **Version**: libuv-1.x
* **Platform**: MINGW32_NT-6.0

I tried to build libuv with MSYS2, but It fails.
log:
`src/win/getaddrinfo.c:79:33: error: 'IF_MAX_STRING_SIZE' undeclared (first use in this function)
`

How should I define it?

**Comment by bnoordhuis** [comment]
Libuv looks for `NDIS_IF_MAX_STRING_SIZE` and `IF_MAX_STRING_SIZE`.  Apparently msys2 provides neither?  Does it work when you `#include <ifdef.h>` directly in getaddrinfo.c?

**Comment by s97712** [comment]
`/d/item/libuv-1.x $ make
CC     src/win/libuv_la-getaddrinfo.lo
src/win/getaddrinfo.c:22:19: fatal error: ifdef.h: No such file or directory
compilation terminated.
make: *** [src/win/libuv_la-getaddrinfo.lo] Error 1`

To correct my questions,I use msys instead of msys2.
Now I using msys2 and it can work.
