### ISSUE TITLE
coredump on reboot with error in SAVE_ERRNO(uv__updatetime(loop)

### ISSUE THREAD

**Issue by xingmu1978** [libuv/libuv#1668]
libuv1.17.1

void OnSigQuit(int sigNo)
    {
        if (s_uv_loop)
        {
            uv_stop(s_uv_loop);
        }
    }

...

int main() {
    s_uv_loop = uv_default_loop();

    Signal(SIGINT, OnSigQuit);
    Signal(SIGQUIT, OnSigQuit);
    Signal(SIGTERM, OnSigQuit);
    Signal(SIGHUP, OnSigQuit);
    Signal(SIGPIPE, OnSIGPIPE);

    s_uvdataParam.watchdog = &watchDog;
    s_uvdataParam.frontLightCtrl = &frontLightController;

    uv_timer_t wd_timer;
    uv_timer_init(s_uv_loop, &wd_timer);
    wd_timer.data = (void *)&s_uvdataParam;
    uv_timer_start(&wd_timer, WDTimerFunc, 1000, 1000);
    uv_run(s_uv_loop, UV_RUN_DEFAULT);
}

It's ok to send signal TERM/INT/QUIT to it, but a core dump file will be generated on a reboot.

gdb mytest core.mytest.xxx will report error on linux-core.c:305

**Comment by bnoordhuis** [comment]
Can you post exact steps to reproduce and fill out the issue template?  It's not clear to me if you are reporting an issue with libuv or your application - and what that issue is.

**Comment by xingmu1978** [comment]
It's probably a header-lib mismatch issue. So I'll close it. Sorry for the nosie
