### ISSUE TITLE
_WIN32_WINNT on uv-win.h need upgrade

### ISSUE THREAD

**Issue by apexliu** [libuv/libuv#1671]
* **Version**: 1.18.0
* **Platform**: Windows

I upgrade libuv from 1.11.0 to 1.18.0, my project can not compile because **ConvertInterfaceIndexToLuid** and **ConvertInterfaceLuidToNameA** can not resolved.

So I checked the function documentation from MSDN, it said "The ConvertInterfaceIndexToLuid function is available on Windows Vista and later."

But in uv-win.h, _WIN32_WINNT set to 0x0502, to fit these two functions, it should be 0x0600.

FYI.

**Comment by bzoz** [comment]
SGTM, PRs are always welcomed!

**Comment by bnoordhuis** [comment]
@apexliu The define in include/uv-win.h is a fallback for libuv users, not libuv itself.  (And perhaps we should simply remove it - seems like an anti-feature to me.)

I suspect you build libuv yourself?  Our own build files set `-D_WIN32_WINNT=0x0600` when compiling the files in src/.

**Comment by apexliu** [comment]
That's all right....  And yes I made a VisualStudio Project by hand because I can not install GYP from China Mainland... I can not visit code.google.com... :(

BTW, it's great if CMake supported by libuv build system.  :)

**Comment by refack** [comment]
@apexliu I keep a fairly updated GYP mirror at https://github.com/refack/gyp

**Comment by apexliu** [comment]
@refack Thanks a lot.
