### ISSUE TITLE
vcbuild.bat is terminated by "lf" end of line

### ISSUE THREAD

**Issue by pcorbineau** [libuv/libuv#1673]
Since "vcbuild.bat" is always used on Windows, this file should be end terminated by "crlf".

if vcbuild.bat is set with "lf" the script always end with :

`the system cannot find the batch label specified - exit`

so my script handle error but the build is ok

**Comment by bzoz** [comment]
`vcbuild` is stored as a text file, make sure you have proper line ending option selected:

```console
git config --global core.autocrlf true
```

See https://help.github.com/articles/dealing-with-line-endings/.
