### ISSUE TITLE
FR: add real-time clock version of uv_hrtime()

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#1674]
`uv_hrtime()` always uses a monotonic clock but that is not sufficient for all applications.

Example: `new Date()` in node.js currently needs platform-specific code because the spec mandates the use of a real-time clock (i.e., human time.)

My proposal:
```c
struct uv_timespec {
  int64_t sec;  /* Seconds since UNIX epoch.  Negative for dates < 1970. */
  uint32_t nsec;
};

enum uv_clock_id {
  UV_CLOCK_MONOTONIC,
  UV_CLOCK_MONOTONIC_COARSE,  // XXX define as "at least 1 ms precision"?
  UV_CLOCK_REALTIME,
  UV_CLOCK_REALTIME_COARSE
 };

int uv_clock_gettime(enum uv_clock_id id, struct uv_timespec* ts);
```
[Look familiar](http://man7.org/linux/man-pages/man2/clock_gettime.2.html)?  `uv_hrtime()` can be reimplemented in terms of `uv_clock_gettime()`.

Other interesting clocks can be added later if we error with UV_EINVAL for invalid clock ids so that downstream users can detect their (lack of) support at run-time.

The Windows implementation would probably use ` GetSystemTimePreciseAsFileTime()` or `GetSystemTimeAsFileTime()` for the real-time clock.

Like `gettimeofday()` and `clock_gettime(CLOCK_REALTIME)`, they return the time in UTC, but in "100-nanosecond intervals since January 1, 1601 (UTC)" according to MSDN.

**Comment by davisjam** [comment]
This design seems reasonable.

**Comment by santigimeno** [comment]
SGTM.

We could add `UV_CLOCK_BOOTTIME` as `CLOCK_BOOTTIME` is already in use in the [code](https://github.com/libuv/libuv/blob/v1.x/src/unix/linux-core.c#L544).

**Comment by bnoordhuis** [comment]
> We could add UV_CLOCK_BOOTTIME as CLOCK_BOOTTIME is already in use in the code.

Subsuming `uv_uptime()` is part of the master plan but I figured I'd start with the basics.

**Comment by cjihrig** [comment]
This looks good. I'd like to take a shot at it.

**Comment by bzoz** [comment]
SGTM

**Comment by bnoordhuis** [comment]
I'll never pass on an opportunity to foist work onto others.  Go for it, Colin!

The only thing I wasn't sure about is `UV_CLOCK_*_COARSE`.  I was thinking that maybe we should reserve one or two additional values so that `UV_CLOCK_*_COARSE+1` can be used in the future for e.g. microsecond granularity and `UV_CLOCK_*_COARSE+2` for, say, hectonanoseconds (decimicroseconds?  100 ns intervals.)

On the other hand, we can always append enums at the end later.  I'm probably overthinking things.

**Comment by cjihrig** [comment]
Just noting that I don't think macOS will be able to move to pure `clock_gettime()` yet. There was an attempt in #1073 and a subsequent revert in #1202. Even on more up to date versions, it looks like the coarse clock definitions aren't there.

**Comment by Meha555** [comment]
Apologies for replying to this closed thread. Since `GetSystemTimePreciseAsFileTime()` is unavailable on versions below Windows 8 and Windows Server 2012, I'm unable to use the libuv release that includes this particular commit. 

Is there a version-specific supported platforms document available? I've come across [`SUPPORTED_PLATFORMS.md`](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md), but it appears to only cover the latest stable release.

**Comment by saghul** [comment]
You'll need to go and check the history for the file to find when we dropped Windows 8 support. We don't have another document, sorry.

**Comment by bnoordhuis** [comment]
v1.44.2 from July 2022 was the last release that did _not_ use `GetSystemTimePreciseAsFileTime`.
