### ISSUE TITLE
UV_IF_NAMESIZE incorrect on Windows - make fallback larger?

### ISSUE THREAD

**Issue by Robmaister** [libuv/libuv#1677]
`UV_IF_NAMESIZE` appears to be defined as the fallback (16 + 1) on my standard VS 2017 setup. I'm trying to use this to convert an IPv6 address to a string, which is failing since `char str_addr[UV_IF_NAMESIZE];` isn't large enough.

I can provide more information about my system/build setup if needed

Ideally I'd dig deeper and see what the actual issue is (my guess is either a missing header or that I have to specify a `WINVER` in my project or something silly like that).

For now, would it be reasonable to bump the fallback value from (16 + 1) up to (39 + 1) so that it would at least cover a regular IPv6 address, or (45 + 1) to cover IPv4-mapped IPv6? I can throw up a PR for that quickly if desired.

My impression [from the documentation](http://docs.libuv.org/en/v1.x/misc.html#c.UV_IF_NAMESIZE) was that it would be that length:

 >Maximum IPv6 interface identifier name length. Defined as IFNAMSIZ on Unix and IF_NAMESIZE on Linux and Windows.

PS - so far my impression of libuv is excellent! Thank you guys for making all of this available and maintaining it 😄 

* **Version**: v1.18.0 tag
* **Platform**: Windows 10 built on VS 2017

**Comment by cjihrig** [comment]
Out of curiosity, what does your failing code look like? `UV_IF_NAMESIZE` isn't used in the Windows code, and 16 seems to be an OK fallback on other OSes, although I agree it seems small.

**Comment by bnoordhuis** [comment]
> Maximum IPv6 interface identifier name length.

"Interface" here means "network interface", not "network address".

It's the part after the % in a `::0%eth0` link-local address.

**Comment by Robmaister** [comment]
@bnoordhuis oh that makes sense, I saw the constant next to `uv_ip6_name` in the documentation and assumed it could be used to store the whole address name. Thanks for the clarification, I'll just go ahead and set up a constant in my own project for that.

**Comment by cjihrig** [comment]
Closing as answered. Let me know if that's not correct.
