### ISSUE TITLE
using the libuv for proxy on windows, the last client can send the first messages to the server. 

### ISSUE THREAD

**Issue by getingskill** [libuv/libuv#1678]
void on_client_tcp_read_done(uv_stream_t *handle, ssize_t nread,
	const uv_buf_t *buf) {
	if (nread == 0) { // EAGAIN || EWOULDBLOCK
		return;
	}
	Session *sess = (Session *)handle->data;
	if (sess == NULL || sess->state == S5_CLOSING) {
		return;
	}

	// stop reading so the buf can be reused and not overrun
	uv_read_stop(handle);
	if (nread < 0) {
		if (nread != UV_EOF) {
			LOG_E("client read failed: %s", uv_strerror(nread));
		}
		printf("close %X\n", sess);
		printf("377 tcp rd\n");
		close_session(sess);
		return;
	}

	if (sess->state == S5_METHOD_IDENTIFICATION) {
	       // the fun of handle_socks5_request finishs  the connection of server and change the state for
              // sS5_STREAMING, and then excutes client_tcp_read_start and upstream_tcp_read_start.
             // client_tcp  for the proxy server ,upstream_tcp for the proxy client
		handle_socks5_request(handle, nread, buf, sess);
	}
	else {
		if (sess->state == S5_STREAMING) {
                upstream_tcp_write_start((uv_stream_t *)((TCPSession *)sess)->upstream_tcp,
					((uv_buf_t*)buf));
		}
		else {
			// unreachable code
			LOG_W("unepxected state: %d", sess->state);
			close_session(sess);
		}
	}

}

**Comment by bnoordhuis** [comment]
I don't follow.  Can you elaborate if you are reporting a bug in libuv or move it to the help repo if you are looking for help with your code?
