### ISSUE TITLE
udp_send_hang_loop not ok!

### ISSUE THREAD

**Issue by fast01** [libuv/libuv#1680]
**compile libuv and then make check, output  reports:     udp_send_hang_loop not ok!**

gcc version: 
Thread model: posix
gcc version 4.8.2 (GCC) 
CentOS release 6.3 (Final) 

```
some outputs: 

ok 310 - udp_send_and_recv
not ok 311 - udp_send_hang_loop
# exit code 134
# Output from process `udp_send_hang_loop`:
# Assertion failed in test/test-udp-send-hang-loop.c on line 70: status == 0
ok 312 - udp_send_immediate
ok 313 - udp_send_unreachable
 ```

* **Version**:  libuv-1.18.0
* **Platform**:  Linux  2.6.32_1-13-0-0 #24 SMP Thu Dec 26 12:28:11 CST 2013 x86_64 x86_64 x86_64 GNU/Linux 

@bnoordhuis 

Thanks for your quick reply,  and  sorry for my late update!     I made an output, and print out the status value. 

**the status value is :    -101    when the above test check fail!** 

```
ok 310 - udp_send_and_recv
not ok 311 - udp_send_hang_loop
# exit code 134
# Output from process `udp_send_hang_loop`:
# status=-101
# Assertion failed in test/test-udp-send-hang-loop.c on line 71: status == 0

```

**Comment by bnoordhuis** [comment]
Can you find out what the value of `status` is at the time of the assert?

**Comment by bnoordhuis** [comment]
No follow-up.  I'll close this out but thanks for the bug report.

**Comment by fast01** [comment]
the newest output, when check failed! 

ok 310 - udp_send_and_recv
not ok 311 - udp_send_hang_loop
# exit code 134
# Output from process `udp_send_hang_loop`:
# status=-101
# Assertion failed in test/test-udp-send-hang-loop.c on line 71: status == 0

**Comment by bnoordhuis** [comment]
Thanks!  Looking at the test, I guess that status code makes sense.  Can you check if this patch helps?
```diff
diff --git a/test/test-udp-send-hang-loop.c b/test/test-udp-send-hang-loop.c
index 6253ff7a4..bf4dfebfb 100644
--- a/test/test-udp-send-hang-loop.c
+++ b/test/test-udp-send-hang-loop.c
@@ -67,7 +67,7 @@ static void idle_cb(uv_idle_t* handle) {
 
 static void send_cb(uv_udp_send_t* req, int status) {
   ASSERT(req != NULL);
-  ASSERT(status == 0);
+  ASSERT(status == 0 || status == UV_ENETUNREACH);
   CHECK_OBJECT(req->handle, uv_udp_t, client);
   CHECK_OBJECT(req, uv_udp_send_t, send_req);
   req->handle = NULL;
```

**Comment by fast01** [comment]
@bnoordhuis , this patch works fine , all tests passed!   Thanks your time for fix this!

**Comment by cjihrig** [comment]
Should the test be updated with that patch?

**Comment by santigimeno** [comment]
I would say so. I'll reopen the issue.

**Comment by cjihrig** [comment]
@bnoordhuis or @fast01 do either of you want to PR this change? Otherwise, I'll do it.

**Comment by bnoordhuis** [comment]
#1695
