### ISSUE TITLE
Feature request: Windows named pipe support in `uv_poll_t`

### ISSUE THREAD

**Issue by DemiMarie** [libuv/libuv#1688]
This is a feature request to support Windows named pipes open in overlapped mode in `uv_poll_t`.  I can think of a few ways to do this; the simplest is to use overlapped IO with a zero byte count and with the pipe set to nonblocking mode.

**Comment by bnoordhuis** [comment]
Doesn't seem objectionable to me as long as it can be done robustly without being a maintenance hassle.  Pull requests welcome.

**Comment by vtjnash** [comment]
under consideration in PRs https://github.com/libuv/libuv/pull/484 and https://github.com/libuv/libuv/pull/1544
