### ISSUE TITLE
Errors in Visual Studio 2013 Community

### ISSUE THREAD

**Issue by devmetal** [libuv/libuv#169]
Hi,

Im Adam, im new with libuv, and im not a big windows c programmer, but i wanted to try libuv hello world project, and when i compile i get this error and warning messages:

 Warning	1	warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification	D:\Programing\C\libuv\libuv_hello\libuv_hello\LINK	libuv_hello
Warning	2	warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	D:\Programing\C\libuv\libuv_hello\libuv_hello\main.obj	libuv_hello
Error	3	error LNK2005: ___xi_a already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Error	4	error LNK2005: ___xi_z already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Error	5	error LNK2005: ___xc_a already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Error	6	error LNK2005: ___xc_z already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Warning	7	warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library	D:\Programing\C\libuv\libuv_hello\libuv_hello\LINK	libuv_hello
Warning	8	warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library	D:\Programing\C\libuv\libuv_hello\libuv_hello\LINK	libuv_hello
Error	9	error LNK2001: unresolved external symbol __imp__htons@4	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(uv-common.obj)	libuv_hello
Error	10	error LNK2001: unresolved external symbol __imp__getsockopt@20	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(core.obj)	libuv_hello
Error	11	error LNK2001: unresolved external symbol __imp__closesocket@4	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(core.obj)	libuv_hello
Error	12	error LNK2001: unresolved external symbol __imp__setsockopt@20	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(core.obj)	libuv_hello
Error	13	error LNK2001: unresolved external symbol __imp__WSAGetLastError@0	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(core.obj)	libuv_hello
Error	14	error LNK2001: unresolved external symbol __imp__WSASendTo@36	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	15	error LNK2001: unresolved external symbol __imp__socket@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	16	error LNK2001: unresolved external symbol __imp__bind@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	17	error LNK2001: unresolved external symbol __imp__getsockname@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	18	error LNK2001: unresolved external symbol __imp__WSARecvFrom@36	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	19	error LNK2001: unresolved external symbol __imp__WSARecv@28	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	20	error LNK2001: unresolved external symbol __imp__htonl@4	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	21	error LNK2001: unresolved external symbol __imp__ioctlsocket@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(udp.obj)	libuv_hello
Error	22	error LNK2001: unresolved external symbol __imp__listen@8	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(tcp.obj)	libuv_hello
Error	23	error LNK2001: unresolved external symbol __imp__WSADuplicateSocketW@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(tcp.obj)	libuv_hello
Error	24	error LNK2001: unresolved external symbol __imp__shutdown@8	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(tcp.obj)	libuv_hello
Error	25	error LNK2001: unresolved external symbol __imp__WSASend@28	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(tcp.obj)	libuv_hello
Error	26	error LNK2001: unresolved external symbol __imp__WSASocketW@24	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(tcp.obj)	libuv_hello
Error	27	error LNK2001: unresolved external symbol __imp__WSAIoctl@36	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(tcp.obj)	libuv_hello
Error	28	error LNK2001: unresolved external symbol __imp__getpeername@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(tcp.obj)	libuv_hello
Error	29	error LNK2001: unresolved external symbol __imp__WSASetLastError@4	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(winsock.obj)	libuv_hello
Error	30	error LNK2001: unresolved external symbol __imp__WSAStartup@8	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(winsock.obj)	libuv_hello
Error	31	error LNK2001: unresolved external symbol _GetProcessMemoryInfo@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(util.obj)	libuv_hello
Error	32	error LNK2001: unresolved external symbol _GetAdaptersAddresses@20	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(util.obj)	libuv_hello
Error	33	error LNK2001: unresolved external symbol __imp__select@20	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(poll.obj)	libuv_hello
Error	34	error LNK1120: 25 unresolved externals	D:\Programing\C\libuv\libuv_hello\Debug\libuv_hello.exe	libuv_hello

I downloaded the libuv, and i run the vcbuild.bat, and it was fine and generated the sln files.

![step1](https://cloud.githubusercontent.com/assets/3758485/5929207/de5af658-a681-11e4-934c-2b0aae512967.png)

After i builded it and it worked too. The vs generated the Release/lib/libuv.lib file. After i created a new project, and added the include folder to Additional Included Directories, and under the linker options i added the Release/lib/ dir to Additional Library Directories, and finaly i added the libuv.lib to linker->input options.

But when i builded the hello world project, i got error messages.

In that case if im wrong pls tell me where i failed. Thx :)

**Comment by cynron** [comment]
add `ws2_32.lib` to linker->input

**Comment by devmetal** [comment]
I added, but still not working. Here is the errors:

Warning	1	warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification	D:\Programing\C\libuv\libuv_hello\libuv_hello\LINK	libuv_hello
Warning	2	warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	D:\Programing\C\libuv\libuv_hello\libuv_hello\main.obj	libuv_hello
Error	3	error LNK2005: ___xi_a already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Error	4	error LNK2005: ___xi_z already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Error	5	error LNK2005: ___xc_a already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Error	6	error LNK2005: ___xc_z already defined in MSVCRTD.lib(cinitexe.obj)	D:\Programing\C\libuv\libuv_hello\libuv_hello\LIBCMT.lib(crt0init.obj)	libuv_hello
Warning	7	warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library	D:\Programing\C\libuv\libuv_hello\libuv_hello\LINK	libuv_hello
Warning	8	warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library	D:\Programing\C\libuv\libuv_hello\libuv_hello\LINK	libuv_hello
Error	9	error LNK2001: unresolved external symbol _GetProcessMemoryInfo@12	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(util.obj)	libuv_hello
Error	10	error LNK2001: unresolved external symbol _GetAdaptersAddresses@20	D:\Programing\C\libuv\libuv_hello\libuv_hello\libuv.lib(util.obj)	libuv_hello
Error	11	error LNK1120: 2 unresolved externals	D:\Programing\C\libuv\libuv_hello\Debug\libuv_hello.exe	libuv_hello

**Comment by bnoordhuis** [comment]
The list of libraries that you have to link to is [here](https://github.com/libuv/libuv/blob/150dfdd/uv.gyp#L109-113).  By the look of it, you are missing at least iphlpapi.dll.

**Comment by devmetal** [comment]
Thank you for help, its now working. I added the lib files to linker input, and i set the C/C++ -> Code Generation to Multi Threaded /MT. Now its working :) Thanks for the help :)
