### ISSUE TITLE
Windows: uv_spawn() fails if null device is not present

### ISSUE THREAD

**Issue by ptlomholt** [libuv/libuv#1690]
On Windows, `uv_spawn()` fails when specifying `UV_IGNORE` for one or more of the child i/o handles (or not specifying any) and the system has no null device

from the libuv sources:

```
int uv_spawn(uv_loop_t* loop,
             uv_process_t* process,
             const uv_process_options_t* options) {
[...]
  err = uv__stdio_create(loop, options, &process->child_stdio_buffer);
  if (err)
    goto done;
```

with
```

int uv__stdio_create(uv_loop_t* loop,
                     const uv_process_options_t* options,
                     BYTE** buffer_ptr) {
[...]
    switch (fdopt.flags & (UV_IGNORE | UV_CREATE_PIPE | UV_INHERIT_FD |
            UV_INHERIT_STREAM)) {
      case UV_IGNORE:
        /* Starting a process with no stdin/stout/stderr can confuse it. */
        /* So no matter what the user specified, we make sure the first */
        /* three FDs are always open in their typical modes, e.g. stdin */
        /* be readable and stdout/err should be writable. For FDs > 2, don't */
        /* do anything - all handles in the stdio buffer are initialized with */
        /* INVALID_HANDLE_VALUE, which should be okay. */
        if (i <= 2) {
          DWORD access = (i == 0) ? FILE_GENERIC_READ :
                                    FILE_GENERIC_WRITE | FILE_READ_ATTRIBUTES;

          err = uv__create_nul_handle(&CHILD_STDIO_HANDLE(buffer, i),
                                      access);
          if (err)
            goto error;
```

and 
```

int uv__create_nul_handle(HANDLE* handle_ptr,
    DWORD access) {
  HANDLE handle;
  SECURITY_ATTRIBUTES sa;

  sa.nLength = sizeof sa;
  sa.lpSecurityDescriptor = NULL;
  sa.bInheritHandle = TRUE;

  handle = CreateFileW(L"NUL",
                       access,
                       FILE_SHARE_READ | FILE_SHARE_WRITE,
                       &sa,
                       OPEN_EXISTING,
                       0,
                       NULL);
  if (handle == INVALID_HANDLE_VALUE) {
    return GetLastError();

```

Several of our customers are suffering from this problem where, for unknown reasons, the `CreateFile(L"NUL",...` fails. This is especially seen on some variations of embedded Windows XP but also newer versions of Windows.

It seems that `uv_spawn()` should continue to function despite nul device not being present, for example by not inheriting any handles at all (e.g. set `bInheritHandles` to FALSE in the argument to `CreateProcessW()`),   

Do you think it would be possible to address this problem in a future version of libuv?

* **Version**: - 1.18.0
* **Platform**: Windows all

**Comment by bnoordhuis** [comment]
The comment explains why libuv does what it does, so no, I wouldn't say that it's a good idea to stop doing that, certainly not without understanding what is causing the failures.  If you or anyone else has more info, we can look into it.

**Comment by bzoz** [comment]
Similar issue was reported here https://github.com/ipython/ipython/issues/9023. It looks like `NUL` is implemented as service/driver, and embedded Windows XP does not include it by default: https://stackoverflow.com/questions/997830/how-do-i-add-the-null-device-to-windows-xp-embedded.

I'm not sure what can be done with that. Maybe we can create dummy pipes if `NUL` is not present on the machine?

**Comment by bnoordhuis** [comment]
Dummy pipe as in a pipe that isn't connected to anything?  Is that possible?  Wouldn't it fill up in no time?

**Comment by piscisaureus** [comment]
As Ben said, a dummy pipe would fill up in no time. Maybe it's better to create an (empty) temp file with FILE_FLAG_DELETE_ON_CLOSE set.

(Also I thought XP support had been dropped?)

**Comment by refack** [comment]
@computerquip-streamlabs checking on my (assumed to be a healthy Windows 10) system, it seems like `start= system` is the default for the `Null` driver:
```cmd
D:\refael>sc qc Null
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: Null
        TYPE               : 1  KERNEL_DRIVER
        START_TYPE         : 1   SYSTEM_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   :
        LOAD_ORDER_GROUP   : Base
        TAG                : 1
        DISPLAY_NAME       : Null
        DEPENDENCIES       :
        SERVICE_START_NAME :
```

---

Since 8 months passed since Ben's call for action, and since the OP is about a specially configured systems (or embedded XP which is not supported), I'm closing this issue. (I would assume many other drivers being stopped will cause uv to fail, for example `tcpip` or `npsvctrig`...)

If anyone feels differently, I'd be to reopen and discuss.
