### ISSUE TITLE
uv_cpu_info for FreeBSD

### ISSUE THREAD

**Issue by gczuczy** [libuv/libuv#1694]
NodeJS's os.cpus() fails at some places, because some call is not implemented here.

NodeJS issue with dev comments: https://github.com/nodejs/node/issues/17995#issuecomment-355492434

Some FreeBSD specific hints:

The number of CPUs can be found in sysctl hw.ncpu. The topology can be found in kern.sched.topology_spec:

```
$ sysctl kern.sched.topology_spec
kern.sched.topology_spec: <groups>
 <group level="1" cache-level="0">
  <cpu count="4" mask="f,0">0, 1, 2, 3</cpu>
 </group>
</groups>
```

A description of the XML structure can be found in [smp(4)](https://www.freebsd.org/cgi/man.cgi?query=smp&apropos=0&sektion=4&manpath=FreeBSD+12-current&arch=default&format=html).

Please let me know if it's actually libuv, or I should open a ticket somewhere else.

**Comment by bnoordhuis** [comment]
Likely relevant: the bug report is against freebsd/arm64 (a.k.a aarch64.)

freebsd/amd64 works okay to the best of my knowledge.

**Comment by elephantp** [comment]
The problem is because of the uv_cpu_info() implementation in freebsd/arm (aarch64).
The key name `hw.model` and `hw.clockrate` are not available in freebsd/arm, I'll fix it later :)

**Comment by gczuczy** [comment]
@elephantp Let me know if I can provide any help. I've got a pine64 setting around for testing/checking stuff.

**Comment by elephantp** [comment]
@gczuczy Thanks!
Just type `sysctl -a | grep -E "(hw\.(model|machine|clockrate|ncpu)|(kern\.(cp_time|smp)))"` on shell, and show me what it shows.
BTW, it would be great if you knew how to build libuv on FreeBSD arm. Check out my aarch64_cpu_info branch and build it. Run check if everything is okay, it will show cpu_info.
It‘s my cpu_info shows on my raspberry pi 3(FreeBSD 12).
![20180113182248](https://user-images.githubusercontent.com/35268331/34905212-11876fe0-f88f-11e7-9b66-23afab483a01.png)

**Comment by gczuczy** [comment]
Here's the output:

```
# sysctl -a | grep -E "(hw\.(model|machine|clockrate|ncpu)|(kern\.(cp_time|smp)))"
kern.smp.forward_signal_enabled: 1
kern.smp.topology: 0
kern.smp.cpus: 4
kern.smp.disabled: 0
kern.smp.active: 1
kern.smp.maxcpus: 96
kern.smp.maxid: 3
kern.cp_times: 8229000 32 862740 503647 93804497 12913580 23 700665 6047 89779593 12813813 27 699138 44949 89841981 12794069 16 708008 6168 89891646
kern.cp_time: 46750462 98 2970551 560811 363317717
hw.machine: arm64
hw.ncpu: 4
hw.machine_arch: aarch64

```

**Comment by elephantp** [comment]
Thank you!
Obviously, as I said, `hw.model` and `hw.clockrate` are not available, the others are same to x86
