### ISSUE TITLE
Build Android from MINGW64?

### ISSUE THREAD

**Issue by Robmaister** [libuv/libuv#1699]
* **Version**:  1.18.0
* **Platform**: MINGW64_NT-10.0 HOSTNAME 2.8.0(0.310/5/3) 2017-04-02 13:38 x86_64 Msys

I seem to be having some issues building Android from a Windows host (running from Git Bash). I have a standard NDK installation (via a fresh install of Android Studio), with `<android-sdk>/tools`, `<android-sdk>/platform-tools`, and `<android-sdk>/ndk-bundle` in my path. I've defined `ANDROID_HOME` and `ANDROID_NDK_HOME` as environment variables.

My copy of make is pretty old, but it looks like this is intentional from looking through `android-configure`:

```
user@HOSTNAME MINGW64 /c/app/lib/libuv ((v1.18.0))
$ which make
/c/app/lib/libuv/android-toolchain/bin/make

user@HOSTNAME MINGW64 /c/app/lib/libuv ((v1.18.0))
$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i586-pc-mingw32
```

The issue itself is that the makefile appears to do nothing. Following the instructions in the README:

```
user@HOSTNAME MINGW64 /c/app/lib/libuv ((v1.18.0))
$ source ./android-configure $ANDROID_NDK_HOME gyp 24
HOST_OS=windows
HOST_EXE=.exe
HOST_ARCH=x86_64
HOST_TAG=windows-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
Toolchain installed to /c/app/lib/libuv/android-toolchain.
['-Dtarget_arch=arm', '-DOS=android', '-f', 'make-android', '.\\uv.gyp', '-I', '.\\common.gypi', '--depth=.', '-Dhost_arch=x64', '-Duv_library=static_library']

user@HOSTNAME MINGW64 /c/app/lib/libuv ((v1.18.0))
$ make
make: Nothing to be done for `all'.
```

Note that I'm doing `make` instead of `make -C out` since it seems like Windows just won't generate an out folder and instead dumps the Makefile to the root dir. (Based on looking through `gyp_uv.py`). If I manually create an out folder and and edit `gyp_uv.py` to force the -Goutput_dir and --generator-output args, it will put the makefiles in the out directory, and `make -C out` will do the same thing, just with two extra lines for entering/leaving the out dir.

`make V=1` doesn't change the output, I can include output for `make -d` if necessary.

**EDIT**: I got the latest NDK through Android Studio. `source.properties` version is `16.1.4479499`

hostname and paths were modified, which should be inconsequential. This is on a work machine, so I won't be able to do any further digging until Tuesday.

**Comment by bnoordhuis** [comment]
I think it's safe to say you're deep in uncharted territory here.  AFAIK, the android-configure script is only used to cross-compile from linux and maybe macos.

I've never tried it but perhaps you can make it work using the autotools build (`sh autogen.sh && ./configure <options> && make`).  See [this SO question](https://stackoverflow.com/questions/46678795/cross-compile-with-autoconf-with-android-toolchain) for an example of how to configure the toolchain.

**Comment by Robmaister** [comment]
If I have the time for it, I'll try and modify the scripts to detect and correctly configure Windows via MINGW and submit a PR for it - thanks for the quick response :)

**Comment by Robmaister** [comment]
Update: The toolchain downloaded the correct Windows cross-compile binaries, it just looks like gyp's Makefile template really hates Windows paths. After a lot of tweaking I got it to work properly!

![image](https://user-images.githubusercontent.com/1067411/35406921-37815a2e-01d8-11e8-8147-4e3031fdf923.png)

I can include a copy of my modified Makefile, but the general issues I fixed were:

 1. Towards the bottom, replaced `all:` with `all:  libuv`, for whatever reason it wasn't concatenating this in `libuv.target.mk` as the comment above it implied. This is why make told me "Nothing to be done for all" initially.
 2. `builddir_name ?= C:\<full Windows path>\libuv\out` should be replaced with `builddir_name ?= ./`
 3. Replace all backslashes in `OBJS` in `libuv.target.mk` with forward slashes

It looks like sed is still a little unhappy, the second instance of it in `fixup_dep` emits this on the console output of make:

```
sed: -e expression #1, char 5: unterminated `s' command
```

for essentially every target. But this doesn't appear to cause any issues.

I'll see if I can get these changes to be made via gyp instead of manually after generation

**Comment by cjihrig** [comment]
@Robmaister is there anything to be done here, or can this be closed?

**Comment by Robmaister** [comment]
I might eventually submit a PR that tries to detect MINGW and fixes this, but I think the real issue is upstream in gyp.

Either way, if anyone else is trying to do this, my instructions above should work for the foreseeable future, so yeah should be fine to close
