### ISSUE TITLE
fs: uv_fs_{open,read,close}_dir (or whatever is necessary for a streaming fs.readdir() in node)

### ISSUE THREAD

**Issue by jonathanong** [libuv/libuv#170]
i'd like https://github.com/iojs/io.js/issues/583. seems like it requires https://github.com/joyent/libuv/pull/1574, but i don't see that as a PR int his repo.

you can close this if this is already in. can't really help with a PR in C++ land. just a feature request :)

**Comment by saghul** [comment]
@misterdjules mind reopening your PR here? Thanks!

**Comment by vkurchatkin** [comment]
:+1:

**Comment by misterdjules** [comment]
@saghul Yes, I'll do that later, hopefully today and for sure before the end of this week!

**Comment by jonathanong** [comment]
:+1:

**Comment by vkurchatkin** [comment]
@misterdjules thank you! Once it's in io.js I volunteer to implement both sync and async bindings

**Comment by saghul** [comment]
Thank you all!

**Comment by misterdjules** [comment]
The PR is [up](https://github.com/libuv/libuv/pull/175). This is a work in progress, I'll update it asap so that all tests pass, and then we can discuss it further. Thank you!

**Comment by saghul** [comment]
Fantastic! Let's continue the discussion there then.
