### ISSUE TITLE
Using RTLD_GLOBAL in uv_dlopen

### ISSUE THREAD

**Issue by BotellaA** [libuv/libuv#1705]
I am not using directly libuv but Node.js. 

I would like to know why you are not using the RTLD_GLOBAL flag at library loading on linux?
This question is related to this line: https://github.com/libuv/libuv/blob/v1.x/src/unix/dl.c#L36

It will ease so much the issue with dependencies between C/C++ addons in Node.js.

Thanks for your answer

**Comment by bnoordhuis** [comment]
> I would like to know why you are not using the RTLD_GLOBAL flag at library loading on linux?

Because it's a bad idea, symbol clashes are a thing.  You can pass flags to `process.dlopen()` in recent node.js versions but you should only do that in an application, not in a library.

I'll close this out.  If you have follow-up questions, please open an issue over at nodejs/help.
