### ISSUE TITLE
Performance workaround for MetltDown and Spectre

### ISSUE THREAD

**Issue by unicomp21** [libuv/libuv#1710]
Not sure this is the best place to start, but here goes anyway.

Security patches for MarkDown and Spectre have dramatically increased the cost of user/kernel context switch.  Which means we need to pack more pending i/o operations into each context switch, in order to get good throughput.  The argument being made, we need new versions of GetQueuedCompletionStatus(Ex) and epollXXX on Windows and Linux respectively.  The new method(s) will allow a cpu TickCount or millisecond argument telling the kernel how long it should wait, batching completed i/o operations in the meantime, before returning to user-mode w/ the completed i/o operations.  This will create a latency/throughput tradeoff, but for non-latency sensitive apps, which I would argue is 99.9% of the time, the increase in throughput will be dramatic.

Thoughts?

**Comment by bnoordhuis** [comment]
I don't really understand what you are asking or suggesting.  Libuv already tries to coalesce system calls as much as is reasonably possible.

**Comment by unicomp21** [comment]
This is a push for changes on the kernel side to coalesce even more.

**Comment by unicomp21** [comment]
I don't know who the owners are for GetQueuedCompletionStats (windows) and epoll (linux), hoping someone here can point me in the right direction.  Kernel side issues can then be opened and linked back here for tracking.

**Comment by saghul** [comment]
> I don't know who the owners are for GetQueuedCompletionStatus(Ex) (windows) and epoll (linux),

The Windows and Linux kernel, respectively. I don't understand what you aim to accomplish with this issue. What's actionable here? Everyone is well aware of the implications of Meltdown / Spectre, I don't see how this issue can help.

**Comment by cjihrig** [comment]
I'll close this, as there isn't really anything to be done in libuv.
