### ISSUE TITLE
Android 5.0 does not have pthread_cond_timedwait_monotonic_np

### ISSUE THREAD

**Issue by ljbade** [libuv/libuv#172]
In the Android 5 NDK `pthread_cond_timedwait_monotonic_np` was removed from the new 64-bit platforms. Instead `pthread_condattr_setclock`/`pthread_condattr_setclock` was added.

`src/unix/thread.c` currently uses this so breaks on 64-bit builds.

I will patch this, but please let me know which branch to work on.

We are using 0.11.29 for Android but it looks like this is not maintained now?

**Comment by ljbade** [comment]
OK I created a fix in https://github.com/ljbade/libuv-1/tree/fix-android-clock

I am waiting to test in on a Nexus 9 (arm64) to see if it is fixed.

**Comment by saghul** [comment]
0.11 became 1.x. Can you please send a PR against the v1.x branch?

**Comment by ljbade** [comment]
@saghul thats what I am doing

**Comment by saghul** [comment]
#176 landed, closing!
