### ISSUE TITLE
14bfc27e641aff178c431083c0c0eada4d6f02dd broke reading from stdin

### ISSUE THREAD

**Issue by burgerrg** [libuv/libuv#1720]
Commit 14bfc27e641aff178c431083c0c0eada4d6f02dd broke reading from stdin on UNIX systems. Before this commit, uv_fs_read on stdin would return with the number of characters available after the user presses enter. Now it doesn't return until the buffer is filled. I expect this commit also breaks reading from pipes for the same reason.

**Comment by burgerrg** [comment]
Perhaps you could add a flag to uv_fs_read to disable this read-until-the-buffers-are-full behavior? Thanks!

**Comment by bnoordhuis** [comment]
I had a feeling something was up with that commit in #1717.  Nice to be vindicated, I've added its revert back to that PR.

**Comment by burgerrg** [comment]
Thanks, uv_fs_read of stdin now works as expected!
