### ISSUE TITLE
Callback sequence inconsistency between timers and idle-prepare-check handles

### ISSUE THREAD

**Issue by neoxic** [libuv/libuv#1728]
Being in favour of _idle_ handles as equivalents of self-rearming timers with zero timeout (as @bnoordhuis mentioned [here](https://github.com/libuv/libuv/issues/1035) with which I completely agree), I use them to suspend and resume coroutines (green threads) on an event loop. As of today, I have been happy with the general ability of handles to queue their callbacks in a sequence which helps avoid implementing an additional (internal) queue for coroutines. It seems to be enough to just attach a coroutine to its own _idle_ handle and start/stop it when the coroutine needs to be resumed/suspended.

However, I recently discovered that _idle_ handles (along with their siblings, _check_ and _prepare_ handles) are inconsistent with other handles in regards to callback sequencing. In particular, when an _idle_ handle is started, its callback is queued **first** (not **last** as is the case for timers and other handles). This is implemented in `loop-watcher.c` as a call to `QUEUE_INSERT_HEAD()`. Please note that all other handles including timers are (re)queued via a call to `QUEUE_INSERT_TAIL()`. Is there a particular reason for such inconsistency? Why not use the same FIFO approach everywhere? For now, I'm forced to switch to zero-timeout timers instead because there's no way to predict in what order _idle_ callbacks are fired.

The code snippet that demonstrates the problem:
```c
#include <uv.h>

typedef struct {
	uv_timer_t _;
	int n;
} Timer;

typedef struct {
	uv_idle_t _;
	int n;
} Idle;

static void timer_cb(uv_timer_t *handle) {
	printf("n: %d\n", ((Timer *)handle)->n);
	/* If uncommented, the produced sequence is 1,2,3,1,2,3... as expected */
	// uv_timer_start(handle, timer_cb, 0, 0);
}

static void idle_cb(uv_idle_t *handle) {
	printf("n: %d\n", ((Idle *)handle)->n);
	uv_idle_stop(handle);
	/* If uncommented, the produced sequence is messed up as 3,2,1,1,2,3,3,2,1,1,2,3...  */
	// uv_idle_start(handle, idle_cb);
}

static void startTimer(void *p) {
	uv_timer_init(uv_default_loop(), p);
	uv_timer_start(p, timer_cb, 0, 0);
}

static void startIdle(void *p) {
	uv_idle_init(uv_default_loop(), p);
	uv_idle_start(p, idle_cb);
}

int main() {
	Timer t1, t2, t3;
	Idle i1, i2, i3;
	t1.n = i1.n = 1;
	t2.n = i2.n = 2;
	t3.n = i3.n = 3;

	printf("Timer:\n");
	startTimer(&t1);
	startTimer(&t2);
	startTimer(&t3);
	uv_run(uv_default_loop(), UV_RUN_DEFAULT);

	printf("Idle:\n");
	startIdle(&i1);
	startIdle(&i2);
	startIdle(&i3);
	uv_run(uv_default_loop(), UV_RUN_DEFAULT);

	/* Omit cleanup */
	return 0;
}
```
Output:
```
Timer:
n: 1
n: 2
n: 3
Idle:
n: 3
n: 2
n: 1
```

**Comment by neoxic** [comment]
I am aware that _idle_ handles could go away in the future. Nonetheless, _prepare_/_check_ handles don't seem to be going anywhere anytime soon. Personally, I find _idle_ handles useful and vote for them. If the name looks unfortunate, I'd suggest renaming them to `uv_repeat_t` ("spin" doesn't look better than "idle").😜

**Comment by neoxic** [comment]
It also appears that the documentation lacks any information regarding callback queueing fashion/guarantees, or I'm missing something badly...

**Comment by davisjam** [comment]
> It also appears that the documentation lacks any information regarding callback queueing fashion/guarantees, or I'm missing something badly...

The order of the different *classes* of callbacks is well defined. See [here](http://docs.libuv.org/en/v1.x/design.html#the-i-o-loop) or look at the `uv_run` function.

I think the docs are silent on the order in which callbacks of the same class will fire (although I remember some assumptions about the order in which timers will fire, either in libuv or in Node).

I'm not opposed to providing some order guarantees. This is similar to Node's guarantee that event handlers on the same event will fire in registration order.

**Comment by saghul** [comment]
> However, I recently discovered that idle handles (along with their siblings, check and prepare handles) are inconsistent with other handles in regards to callback sequencing. In particular, when an idle handle is started, its callback is queued first (not last as is the case for timers and other handles). This is implemented in loop-watcher.c as a call to QUEUE_INSERT_HEAD(). Please note that all other handles including timers are (re)queued via a call to QUEUE_INSERT_TAIL(). Is there a particular reason for such inconsistency?

I agree this is inconsistent. From the looks of it, I'd say it's not intentional, so I'd say let's discuss switching those to a FIFO model.

**Comment by neoxic** [comment]
> The order of the different classes of callbacks is well defined. See here or look at the uv_run function.
Yep, I am aware of that. No question here.
