### ISSUE TITLE
uv_write() for pipes on Windows does not always call callback

### ISSUE THREAD

**Issue by addaleax** [libuv/libuv#1729]
* **Version**: 1.19.1 (Node master)
* **Platform**: Windows 10

Hi everyone! I'm currently debugging some of my Node work, and I'm pretty sure `uv_write()` callbacks for Windows pipes don't always get called (even though the other side of the pipe fully received the data).

I'll try to get a pure libuv reproduction together, but the easiest way to reproduce would be something along the lines of adding a `fprintf(stderr, "foobar\n");` to Node's `LibuvStreamWrap::AfterWrite()`, then running a test like `test\parallel\test-cluster-cwd.js` -- it writes data, the other side receives it, and it does use `uv_write()` for writing, but there's no extra output.

**Comment by bzoz** [comment]
@addaleax  if you change slaves `process.send` to
```javascript
  process.send(process.cwd(), () => {
    process.disconnect();
  });
```
the `fprint`s start to appear. Does this makes sense, or do you still think there is some issue here?

**Comment by addaleax** [comment]
@bzoz I don’t think that’s a solution, no… the writes should still be reported back as finished, even without an explicit disconnect, right? That’s true for all other kinds of libuv streams

**Comment by bzoz** [comment]
I mean, it looks like the process exits before callbacks can be called. If you drop the `process.disconnect()` altogether, the `fprint`s also start to appear (but the test never finishes).
