### ISSUE TITLE
fs_fstat test fails in 1.3.0

### ISSUE THREAD

**Issue by mtorromeo** [libuv/libuv#173]
When building version 1.3.0 on ArchLinux (gcc 4.9.2, glibc 2.20) the `fs_stat` test fails like this:

    `fs_fstat` failed: exit code 134
    Output from process `fs_fstat`:
    Assertion failed in test/test-fs.c on line 1107: s->st_atim.tv_nsec == 0

**Comment by saghul** [comment]
This sonds like #43. Did you build with autotools or GYP?

**Comment by mtorromeo** [comment]
We use autotools: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/libuv

**Comment by mtorromeo** [comment]
Still failing in 1.4.0. Any news?

**Comment by saghul** [comment]
Not really. I can't event test it myself as I don't have a system with glibc 2.20, which seems to be the culprit.

**Comment by mtorromeo** [comment]
Archlinux is now at glibc 2.21 and still failing.

**Comment by mtorromeo** [comment]
After some debugging I found the culprit of this bug.
The _SVID_SOURCE macro is deprecated since glibc 2.20 and _DEFAULT_SOURCE (available since 2.19) should be used instead.
This caused the test to use the wrong asserts and to fail.

I used this quick & dirty hack to make it pass the tests:

    sed -i 's/_SVID_SOURCE/_DEFAULT_SOURCE/g' test/test-fs.c

You should probably add "|| defined(_DEFAULT_SOURCE)" instead but you get the point...

**Comment by saghul** [comment]
Thanks for digging! Mind sending the fix as a pull request?

**Comment by saghul** [comment]
Closing, fixed by https://github.com/libuv/libuv/commit/fd3cf20a37b95fe8a3cb4be045b5a1bad9e53cde.
