### ISSUE TITLE
uv_fs_event: inconsistency when watching for changes on a directory

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#1730]
After looking into https://github.com/libuv/libuv/pull/1649 I've observed that the behavior when watching on a directory differs on platforms when modifying an already existing file:
- `linux`, `windows` and `os x` report an `UV_CHANGE` event.
- `FreeBSD`, `aix`, `smartOS` and `zos` do not.

Was this a known limitation? Should we try to fix it or just documenting it?

**Comment by bzoz** [comment]
Fix would be better, but until one is found we should document this.

**Comment by vtjnash** [comment]
See also https://github.com/libuv/libuv/pull/2313#issuecomment-496722565
