### ISSUE TITLE
Child process throws fatal error when closed

### ISSUE THREAD

**Issue by tversteeg** [libuv/libuv#1731]
* **Version**: 1.19.1 release
* **Platform**: Windows 10, 64bit, VC++ 2017

When I spawn a child process using `uv_spawn` and close the process after I've opened a Windows `GetOpenFileDialog` dialog I get the following error:

> PostQueuedCompletionStatus: (6) The handle is invalid.

This doesn't happen when I spawn the child process directly; it also doesn't matter if the child process is spawned before or after the dialog is opened.

I'm using the [nativefiledialog](https://github.com/mlabbe/nativefiledialog) library but I've also tried it with [noc_file_dialog](https://github.com/guillaumechereau/noc/blob/master/noc_file_dialog.h) and then the same thing happens.

Sometimes I also get a `read access violation.` in process.c on line 856:

    POST_COMPLETION_FOR_REQ(loop, &process->exit_req);

which either says `loop was 0x000000000000` or `loop was 0xFFFFFFFFFFFFFFC7`..

**Comment by bzoz** [comment]
Does this error  happen in the parent or in the child process?

**Comment by tversteeg** [comment]
It happens in the parent process when the child process is closed.

**Comment by bzoz** [comment]
Thanks,

Could you prepare a simplified repro of this? That would be a great help for debugging this.

**Comment by tversteeg** [comment]
I've create a repo to showcase this with instructions here: https://github.com/tversteeg/libuv-process-bug

**Comment by bzoz** [comment]
Use `&parent` instead of `&child_req` in https://github.com/tversteeg/libuv-process-bug/blob/master/Parent/Parent.cpp#L44 and the problem will go away.

**Comment by vtjnash** [comment]
I think you mean `&process`, but I concur with bzoz that using stack memory there (and later copying the struct to `process`) won't work, and is likely the source of your problem.

**Comment by bzoz** [comment]
I can't seem to find any mention of this in the docs. Is it there somewhere?

**Comment by bzoz** [comment]
I've opened a doc PR in https://github.com/libuv/libuv/pull/1749. I'm gonna close this now.
