### ISSUE TITLE
Fix compilation warnings for "make check"

### ISSUE THREAD

**Issue by notorand-it** [libuv/libuv#174]
Under Linux I get a number of warnings like this:

  CC       test/test_run_tests-test-walk-handles.o
In file included from test/test-walk-handles.c:23:0:
test/task.h:80:13: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define LOG(...)                        \
             ^

I am using (gcc -v):

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by bnoordhuis** [comment]
It's a harmless warning, you can ignore it.  I plan to ditch the LOG and LOGF macros, I just haven't gotten around to it yet.

**Comment by notorand-it** [comment]
You should be right also because I have got the following from "make check":

=============================================================
[% 100|+ 248|-   0|T   0|S   0]: Done.
PASS: test/run-tests
=============
1 test passed
=============

Reading those warnings it's not a good thing, anyway. You should be able get rid of them by adding a "-std=c99" argument to the compiler invocation.

**Comment by bnoordhuis** [comment]
I know, but I don't want to do that.  The warnings make sure I don't forget about my plans to remove the macros. :-)

**Comment by simar7** [comment]
@bnoordhuis : So if going forward LOG and LOGF aren't in the plan, what is the new take? I'm trying to get into this project and feel this is a good-first-bug for me to try things out. Let me know your thoughts and I can submit a pull request with the necessary changes. Thanks! :+1:

**Comment by bnoordhuis** [comment]
@simar7 I'd be okay with just replacing them with `fprintf(stderr, ...)` statements.  Thanks!

**Comment by saghul** [comment]
+1

**Comment by simar7** [comment]
@bnoordhuis Cool, created PR https://github.com/libuv/libuv/pull/185 to track it.

**Comment by simar7** [comment]
Can I be assigned to fix this @bnoordhuis ?

**Comment by txdv** [comment]
@simar7 If you provide a good enough patch, it will just get accepted, no need for 'assignment'.

**Comment by simar7** [comment]
@bnoordhuis @txdv Call me weird but I just wanted to have the "collaborator badge" for contributing to the project. If there are different requirements to get that, I'm fine with it.

**Comment by txdv** [comment]
Here you go :name_badge:

**Comment by saghul** [comment]
Once the patch lands you'll be listed as an author, and GitHub will list
you in the contributors tab.

Alas, GH doesn't allow to assign issues to non committers. Not that we use
the feature anyway...

**Comment by saghul** [comment]
Closing, continues on #185
