### ISSUE TITLE
compiling and installing libuv creates v1.0.0 library 

### ISSUE THREAD

**Issue by crusader-mike** [libuv/libuv#1745]
* **Version**: 1.19.1
* **Platform**: CentOS 7

I've downloaded, built and installed libuv:
```
git clone https://github.com/libuv/libuv.git
cd libuv
git reset --hard v1.19.1
sh autogen.sh
./configure
make
make check
sudo make install
```

Ended up with v1.0.0 libuv in my system:
```
ls -l /usr/local/lib/libuv.*

libuv.a
libuv.la -> ../libuv.la
libuv.lai
libuv.so -> libuv.so.1.0.0
libuv.so.1 -> libuv.so.1.0.0
libuv.so.1.0.0
```

did I miss something?

**Comment by bnoordhuis** [comment]
Makefile.am builds libuv with `-version-info 1:0:0`.  It's probably not quite correct but if you expected it to be the version number, [that's not correct either](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html).

**Comment by crusader-mike** [comment]
I am not particularly familiar with makefiles/libtool/etc. What is the easiest way to build and install libuv in such way that related lib has correct version? It doesn't need to be automatically detected (e.g. from Git tag) -- I am fine with entering it myself.

**Comment by bnoordhuis** [comment]
Define "correct version"?  The soname (what `-version-info` sets) doesn't have a 1-to-1 correspondence with the version number.

Phrased differently: what are you trying to accomplish that makes encoding the version number in the filename important?  Be aware that `-version-info` affects more than just the filename, it also adds a DT_SONAME record to the ELF header.

**Comment by crusader-mike** [comment]
> what are you trying to accomplish that makes encoding the version number in the filename important?

I want installation step (`sudo make install` or anything else) to produce following structure in target directory (`/usr/local/lib` by default):
```
libuv.so -> libuv.so.1
libuv.so.1 -> libuv.so.1.19.1
libuv.so.1.19.1
```
of maybe:
```
libuv.so -> libuv.so.1
libuv.so.1 -> libuv.so.1.19
libuv.so.1.19 -> libuv.so.1.19.1
libuv.so.1.19.1
```
where 1.19.1 is the version of libuv I built. `libuv.so.1.19.1` should have soname `libuv.so.1`. I thought this versioning convention is considered to be standard on Linux? To be able to install different versions of same lib side by side.

Not sure about versioning .a files... I imagine similar naming conventions can be (or should  be?) used.

**Comment by bnoordhuis** [comment]
> To be able to install different versions of same lib side by side.

Incompatible versions, yes, bu libuv's v1.x releases are backwards-compatible.  Generally speaking, you overwrite libuv.so.1 when you upgrade, you don't install (for example) 1.8.0 and 1.9.0 side by side.

**Comment by crusader-mike** [comment]
I see... Well, having each 1.x.x version produce 1.0.0 binary is kinda "over-simplification". But if you don't really need to distinguish between them -- I could see it working :-)

Please, nevermind then. If this becomes a problem -- I'll just link with static lib.
