### ISSUE TITLE
wrong default install location on Linux x64

### ISSUE THREAD

**Issue by crusader-mike** [libuv/libuv#1755]
* **Version**: 1.19.1
* **Platform**: Linux, x64

`make install` installs libuv into `/usr/local/lib` by default. I could be wrong, but it should be `/usr/local/lib64` on x64 Linux.

Note: using `./configure --libdir=/usr/local/lib64` fixes that, but then libtool generates a warning during install.

**Comment by bnoordhuis** [comment]
That's really an autotools issue.  Libuv doesn't set the libdir, it comes from automake.  Since that isn't under our control, I'll go ahead and close this out.

> I could be wrong, but it should be /usr/local/lib64 on x64 Linux.

Neither right nor wrong, it depends on the distro.

**Comment by crusader-mike** [comment]
Turned out this problem is a result of some conflict between CentOS/Redhat/etc Linux distro maintainers and `autotools` authors. Solution is:
- either specify `--libdir=/usr/local/lib64` when running `./configure`
- or create `/usr/local/share/config.site` file with this content (not sure how this is going to affect 32-bit builds, though):
```
# /usr/local/share/config.site for platforms that prefer 
# the directory /usr/local/lib64 over /usr/local/lib. 
test "$libdir" = '${exec_prefix}/lib' && libdir='${exec_prefix}/lib64'
```

problem happens on x86_64 platform (which supports both 32- and 64-bit binaries) and without explicit instructions `autotools` always defaults to `/usr/local/lib`.

Related reading:
https://groups.google.com/forum/#!topic/comp.lang.tcl/VqOYBRteEOI
https://lists.gnu.org/archive/html/autoconf/2009-02/msg00014.html
https://stackoverflow.com/questions/46837809/how-to-get-automake-to-set-libdir-to-usr-lib64-on-dual-arch-linux-platforms
https://bugzilla.redhat.com/show_bug.cgi?id=772997
