### ISSUE TITLE
new_socket() loses errno code in some cases

### ISSUE THREAD

**Issue by crusader-mike** [libuv/libuv#1756]
* **Version**: 1.19.1
* **Platform**: Unix

See src/tcp/unix.c, lines 55 and 61. Instead of negated errno it'll return -1, thus obscuring reason for failure from end user.

**Comment by bnoordhuis** [comment]
Right, that's a bug.  Pull request welcome.

**Comment by crusader-mike** [comment]
Question -- it seems that `uv__close()` aims to preserve `errno`. But if `__MVS__` is defined -- `epoll_file_close()` gets called and it doesn't seem to make any attempt to preserve `errno`. Can I rely on `uv__close()` to preserve `errno`?

**Comment by bnoordhuis** [comment]
Yes, that looks like a bug.  The call should have been wrapped in `SAVE_ERRNO()`.
