### ISSUE TITLE
Feature request: Ability to override the default allocator

### ISSUE THREAD

**Issue by beevik** [libuv/libuv#177]
In many projects, it's important to have full control of all memory allocations. Unfortunately, libuv supports allocation only through the C standard library's malloc and free routines.

It would be nice if there were a way to override the allocator in use by libuv. I have forked libuv and made this change [here](https://github.com/beevik/libuv/commit/f7ca455859a6200cf5376bab8bd46af90ee67ce2). I didn't submit this as a pull request, because I wasn't sure if my approach matched the authors' preferred style.

**Comment by bnoordhuis** [comment]
I don't object to the general thrust of that change although I do have some suggestions for improvement.  Can you file it as a pull request?

**Comment by txdv** [comment]
Is there a specific use case you are thinking about?

**Comment by saghul** [comment]
I think this can be useful, for instance, Python has its own allocator so pyuv could use PyMem_Malloc / PyMem_Free instead.

**Comment by txdv** [comment]
Why are pythons allocators so special?

By the way, aren't you supposed to look at some talk right now?

**Comment by beevik** [comment]
Common use cases for allocator overrides:
 - Your project uses a custom memory allocator
 - You'd like to tag memory allocations with their purpose so you can track memory with tools
 - You wish to control the amount of memory used by any one subsystem in a memory-constrained platform.
 - You'd like to control how memory is allocated so that it has better fragmentation or other performance characteristics.

I'll submit the pull request.

**Comment by saghul** [comment]
Lets continue the discussion on #178, now that the PR is open.

**Comment by beevik** [comment]
Closing since the PR is submitted.
