### ISSUE TITLE
Update description of uv_fs_readlink and uv_fs_realpath to describe where the output goes

### ISSUE THREAD

**Issue by burgerrg** [libuv/libuv#1771]
In the API documentation, the `uv_fs_readlink` and `uv_fs_realpath` function descriptions should state that the resulting path (when successful) is returned in `uv_fs_t.ptr`. The description of `uv_fs_t.ptr` mentions `uv_fs_readlink` but not `uv_fs_realpath`.

**Comment by cjihrig** [comment]
Documentation PRs are welcome.
