### ISSUE TITLE
UV_FS_EVENT_RECURSIVE Linux Implementation

### ISSUE THREAD

**Issue by jeremyong** [libuv/libuv#1778]
* **Version**: latest
* **Platform**: Linux

I noticed there wasn't an issue open for this so thought I would raise it for consideration. Historically, inotify does not natively support recursive watching because the original kernel implementers expected this to be done in userland (see [here](https://www.quora.com/Inotify-monitoring-of-directories-is-not-recursive-Is-there-any-specific-reason-for-this-design-in-Linux-kernel)). These days, modern linuxes generally ship with a much higher max_user_watches system setting so that barring an unreasonable number of files being watched, it will consume memory but not otherwise run into issues (I believe a watch consumes maybe a kilobyte of memory on a 64-bit platform but this can be measured). My machine, without me touching the setting right now running Archlinux permits 524288 watches. Even at the conservative 8192 in the kernel source of inotify_user.c, I believe libuv is a natural home for this functionality, provided it surfaces an error handling event if necessary (the buck needs to stop somewhere, and given that we have this functionality on MacOS and Windows and it's useful, we should add it here too).

The algorithm is pretty straightforward and not too unlike what other OS's do. Watch for changes on a node, if a rename occurs, check if it's a directory and add a watch. If a directory was removed, remove the watch, and perform this recursively.

For the event that adding a watch fails due to some error, I recommend invoking a uv_fs_event with an error event explaining what happened so it can be handled by the developer.

Having a fully platform agnostic implementation of this would expand the available API's surface area to provide a number of additional features in libraries/executables that run on top of libUV, without needing to rely on an external file monitor (which is generally what people do today).

I'm comfortable taking an initial stab at the implementation, but wanted to poll the thoughts of the development community here first before doing so or just falling back to my userland implementation instead.

**Comment by davisjam** [comment]
Nice idea, and certainly feasible on modern machines.

Some questions:
1a. Getting some more realistic memory usage numbers would be helpful to evaluate how risky such an API would be for unwitting users. How hard would it be to obtain these?
1b. Is libuv used in embedded contexts where memory constraints are a concern?
2. Could/should this functionality be implemented as a "libuv plugin" instead?

**Comment by jeremyong** [comment]
1. https://stackoverflow.com/questions/535768/what-is-a-reasonable-amount-of-inotify-watches-with-linux indicates that for almost all users that have more than a couple gigabytes of RAM, even half a million watches isn't a problem
2. Libuv may be used all over the place, but I doubt that embedded environments have deep subdirectory graphs of hundreds of thousands of directories or more
3. I believe not because the feature exists on MacOS and Windows as well (and is useful). I'm sure people in Node.js land would love to provide a way to watch a directory recursively (note: I am not on the Node team)

**Comment by davisjam** [comment]
Disclaimer: I don't call the shots around here, I'm just an interested observer.

>  the feature exists on MacOS and Windows as well (and is useful)

Sure. But if the Linux implementation:
- would be more complex than calling an OS API, and
- could be built on top of the existing libuv interface,

then this might be a good fit for a separate library that libuv users could add as a dependency.
Note that libuv also supports more than MacOS, Windows, and Linux -- e.g. AIX.

**Comment by jeremyong** [comment]
How do you propose that would work given that UV_FS_EVENT_RECURSIVE is already a flag to a libuv API call (which currently is unused by Linux)?

AIX is tier 2 as far as I'm aware but this implementation may work there (not having ever programmed for it).

**Comment by davisjam** [comment]
> How do you propose that would work given that UV_FS_EVENT_RECURSIVE is already a flag to a libuv API call (which currently is unused by Linux)?

I was unaware of this. But I don't see any reason why a plug-in would be impossible -- route to the libuv implementation where UV_FS_EVENT_RECURSIVE is supported, and otherwise implement it directly.

**Comment by jeremyong** [comment]
We must be talking through each other. Unless I'm missing something, there is no plugin/trampoline layer to hook into. The usage of inotify watches is already so integrated in, at that point, it'd be easier to do it externally to libuv altogether. In fact, looking at the implementation here, I decided to just drop libuv, at least for my personal projects in favor of a simpler standalone implementation that works the same on all the platforms I care about.

**Comment by davisjam** [comment]
> Unless I'm missing something, there is no plugin/trampoline layer to hook into.

Nothing official, no, but you could create a project that sits above libuv and offers recursive monitoring. "Externally to libuv altogether", yes.

**Comment by bnoordhuis** [comment]
Given that there hasn't been much feedback from maintainers, I'm going to assume there isn't much animo.

Speaking for myself, I agree with @davisjam's reasoning that this can sit on top of libuv, it doesn't need to be part of it.

**Comment by kirill-berezin-ringcentral** [comment]
Wrapping this up: because it's a bit complicated to build on some platform, we will just release inconsistent API and document that this is not supported. In NodeJS because libuv doesn't support it, in libuv, because it expects upper layers to wrap around it.

There a lot of flows differences between Windows Mac and Linux. Some of them simpler on some platforms. But because their behavior internally different, it doesn't mean that we should release library that MAY work the same in SOME cases. (Luckily now most of the times, but still).

@bpasero If MR appear for linux support, will it be merged, or the team internally against idea of handling thousands of IO handles in the library, and rather pass it to depended systems?

#198

**Comment by bpasero** [comment]
I think you did not mean to ping me?

**Comment by kirill-berezin-ringcentral** [comment]
To be honest I am not sure who I should ping. You were the one who originally made recursive support on windows. I wanted to know your opinion.

**Comment by bpasero** [comment]
Oh, I forgot about it. I am no longer very active in this area and cannot allocate resources, sorry.

**Comment by kirill-berezin-ringcentral** [comment]
No, I am willing to contribute, but I want to know, if the merge request like that going to be accepted, or it is not desired by design.

**Comment by bnoordhuis** [comment]
@kirill-berezin-ringcentral Libraries that take care of recursive directory monitoring exist for Node.js. https://www.npmjs.com/package/chokidar is probably the most popular one.

The reason why I don't think that kind of support will ever appear in libuv is that monitoring is inherently race-y and lossy. That forces the library to adopt policies to deal with such conditions but libuv doesn't want to be in the policy business, it just wants to be mechanism.

Besides, file monitoring is complex enough that it could make up a library of its own.

**Comment by kirill-berezin-ringcentral** [comment]
@bnoordhuis I am aware of nodejs libraries, but I am not fully supportive of that. Let's remove windows and macos support from libuv, and make new nodejs libraries for that as well. I am not following the logic.

The library successfully rely on libc and c-ares, in similar cases. (For example recursive dns lookups is not performed with nodejs libraries, and available from the box).

Imo it should rely on inotify library. And if it does already: http://docs.libuv.org/en/v1.x/fs_event.html#c.uv_fs_event_flags we should update documentation
