### ISSUE TITLE
How to build libuv on windows and add it to some code:::blocks project?

### ISSUE THREAD

**Issue by sergorl** [libuv/libuv#1788]
I'm novice in c/c++ programming, but I want to make my own multithreaded tcp-server with ***libuv***. I work on windows 7, so I followed build instructions on winfows and execute comand ***vcbuild*** after cloning library from git. Now I don't understand how to connect ***libuv*** to some code:::blocks project... More precisely I don't understand where I should look the folder with source code for a linker...

I added absolute paths contains `\libuv\include` to compiler directories and `\libuv\src` to linker directories of my code::blocks project and tested it with code snippet below:

```c
#include <stdio.h>
#include <unistd.h>

#include <uv.h>

int main() {
    uv_loop_t *loop = malloc(sizeof(uv_loop_t));
    uv_loop_init(loop);

    printf("Now quitting.\n");
    uv_run(loop, UV_RUN_DEFAULT);

    uv_loop_close(loop);
    free(loop);
    printf("%s", "Hello, World!");
    return 0;
}

```

But I catched the error of linker: `undefined reference to uv_loop_init`.
Can someboby explain me, what I do wrong? How to build libuv on windows and add it to some code:::blocks project?

**Comment by bzoz** [comment]
Get a release from https://github.com/libuv/libuv/releases. Build it - from the command prompt in the libuv folder run `vcbuild release`. A `libuv.lib` will be placed in `libuv\Release\lib\libuv.lib`, add this to your project.

**Comment by sergorl** [comment]
@bzoz, I've done all instructions you gave me:
- `vcbuild release`
- add `C:\libuv-1.19.1\include` to compiler directories
- add `C:\libuv-1.19.1\Release\lib` to linker directories
- add `C:\libuv-1.19.1\Release\lib\libuv.lib` to link libraries

But there is no effect and I have the same error of linker about `undefined reference to uv_loop_init`.
What do I do wrong?

**Comment by bnoordhuis** [comment]
Closing out since it's not really a libuv issue.  Please go to the libuv/help repo if you have follow-up questions.
