### ISSUE TITLE
watcher_cross_stop test fails

### ISSUE THREAD

**Issue by ericecook** [libuv/libuv#179]
Compiled via GCC, ubuntu 14.04

```
=============================================================
[%  56|+ 139|-   0|T   0|S   0]: watcher_cross_stop
`watcher_cross_stop` failed: exit code 6
Output from process `watcher_cross_stop`:
Assertion failed in test/test-watcher-cross-stop.c on line 78: 0 == uv_udp_bind(&sockets[i], (const struct sockaddr*) &addr, UV_UDP_REUSEADDR)
=============================================================
[% 100|+ 247|-   1|T   0|S   0]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory `/home/block/libuv'
make: *** [check-am] Error 2
```

**Comment by ericecook** [comment]
update - Only fails on a server, and seems to fail on older releases as well, since it compiles fine on my desktop it is likely something system specific, but I'm a bit out of my depth on where to troubleshoot this

**Comment by saghul** [comment]
Is it possible you have some process listening for UDP on port 1234?

**Comment by ericecook** [comment]
Negative

**Comment by ericecook** [comment]
One of the few differences between the environments is the kernel version, 2.6.32-042stab094.7 (which appears to be a OpenVZ specific fork). Does libuv depend on a 3.x kernel?

**Comment by bnoordhuis** [comment]
@ericecook It should work with kernels as old as 2.6.18, probably even 2.6.9.

If the failure is repeatable, can you post the output of `strace -f test/.libs/run-tests`?  You may have to point the dynamic linker to libuv.so with LD_LIBRARY_PATH.

**Comment by ericecook** [comment]
Its a bit large, but here ya go https://mega.co.nz/#!vcISGAIT!OVrZoRrGfb3cKg40Tmqa57cx-CaqLvXv5gxGlRzMDZ4

**Comment by bnoordhuis** [comment]
@ericecook Thanks.  I think I found the culprit:

```
[pid 23747] socket(PF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = -1 ENOBUFS (No buffer space available)
```

The ENOBUFS error means the kernel ran out of resources (memory, presumably.)  I don't think there's anything libuv can do about that.  The test creates 2,500 UDP sockets; that's a lot but not an unreasonably large number (and it was chosen to stress-test a particular libuv subsystem; lowering it would make the test a no-op.)

**Comment by ericecook** [comment]
@bnoordhuis Interesting, thanks!

I'm doubtful that memory is the issue, the VPS has 4GB of ram - and usage did not exceed 1.5GB while running the tests

Could this be a file descriptor issue? I'll play with the limits a bit and report back

My quick google search on ENOBUFS indicates it could also be returned if the network interface output queue is full. I'd like to eliminate this possibility, but I'm having a hard time finding a tool to give me info about the current queue. `netstat -m` is what I see recommended, but the `-m` flag is not in my netstat manual. Any pointers here would be appreciated

**Comment by bnoordhuis** [comment]
@ericecook It's possible you're hitting a sysctl limit, although I can't think of a likely candidate off the top of my head.

**Comment by saghul** [comment]
@ericecook ping

**Comment by ericecook** [comment]
@saghul sorry I haven't had time to dig into this, its dropped a lot on my priorities. Please feel free to close it w/ the assumption that it is a system specific issue and I'll update it if I get time to poke around more

**Comment by saghul** [comment]
Closing then, thanks!
