### ISSUE TITLE
uv_fs_futime implementation for linux

### ISSUE THREAD

**Issue by ryzokuken** [libuv/libuv#1790]
`lchown` isn't implemented in linux yet, because it wasn't possible to do so on older kernels in the first place. That said, now the baseline has moved to `2.6.18` and it can (and may I say, should) be implemented on Linux.

References:
1. https://github.com/nodejs/node/issues/19868
2. https://github.com/nodejs/node/issues/16695

**Comment by cjihrig** [comment]
Closed by https://github.com/libuv/libuv/pull/1826
