### ISSUE TITLE
Strange thread id within different threads

### ISSUE THREAD

**Issue by sergorl** [libuv/libuv#1791]
I try to make multithreaded tcp-server: on each accept incoming connection I make thread which reads from client and prints it on server side. I made my project based on [example](https://github.com/libuv/libuv/blob/v1.x/docs/code/tcp-echo-server/main.c). So here is my idea in the code snippet below:

```C
typedef struct {
    uv_stream_t* stream;
    uv_alloc_cb alloc_cb;
    uv_read_cb read_cb;
} info_t;

void work_thread(void* info_) {
    info_t* info = (info_t*) info_;
    uv_read_start(info->stream, info->alloc_cb, info->read_cb);
}

void on_new_connection(uv_stream_t *server, int status) {
    if (status < 0) {
        fprintf(stderr, "New connection error %s\n", uv_strerror(status));
        // error!
        return;
    }

    uv_tcp_t *client = (uv_tcp_t*) malloc(sizeof(uv_tcp_t));
    uv_tcp_init(loop, client);

    if (uv_accept(server, (uv_stream_t*) client) == 0) {

        info_t* info = (info_t*) malloc(sizeof(info_t));

        info->stream = (uv_stream_t*) client;
        info->alloc_cb = alloc_buffer;
        info->read_cb = echo_read;

        uv_thread_t thread_id;
        uv_thread_create(&thread_id, work_thread, info);
        uv_thread_join(&thread_id);
    }
    else {
        uv_close((uv_handle_t*) client, on_close);
    }
}

```

And inside `echo_read()` I call `uv_thread_self()` to get to know thread id:

```C
void echo_read(uv_stream_t *client, ssize_t nread, const uv_buf_t *buf) {

    if (nread > 0) {
            ...

            printf("Send from thread %d\n", uv_thread_self());

            ...

            return;
        }
    }
    if (nread < 0) {
        if (nread != UV_EOF)
            fprintf(stderr, "Read error %s\n", uv_err_name(nread));
        uv_close((uv_handle_t*) client, on_close);
    }

    free(buf->base);
}
```
Then I connect with two different telnets (imitate client side) and print some data to client. But on the server side I see that thread ids in different client connectios are the same and always equals `0`. Why does it happen? Where did I make a mistake?

**Comment by bnoordhuis** [comment]
Can you fill out the issue template?  We ask it for a reason.

**Comment by sergorl** [comment]
@bnoordhuis, excuse me, but I don't understand what you ask... Could you ask more precisely what should I do to figure out my problem?

**Comment by gireeshpunathil** [comment]
Basically, provide these info:

* **Version**:  libuv version
* **Platform**: `uname -a` (UNIX), or Windows version and machine type

**Comment by sergorl** [comment]
Ok, it's clear to me:
- `uv_version_string() `returns this **1.9.1**;
- os: windows 7 64-bit;
- compiler:  `gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 7.3.0`.

**Comment by bnoordhuis** [comment]
So, couple of things:

* `uv_thread_self()` only returns meaningful results for threads started by libuv, not the main thread

* libuv is not thread-safe; you're not supposed to call libuv functions from a different thread except when otherwise noted in the documentation

Can you file support questions to libuv/help next time?

**Comment by bnoordhuis** [comment]
Yes, if you have follow-up questions.

**Comment by sergorl** [comment]
How do I place my question in libuv/help?

**Comment by bnoordhuis** [comment]
Go to https://github.com/libuv/help/issues/new.

**Comment by sergorl** [comment]
I did it, but I can't make label "**help**" for this issue!
