### ISSUE TITLE
What logic is behind uv_is_readable/writable applicable to tcp sockets?

### ISSUE THREAD

**Issue by OleksandrKvl** [libuv/libuv#1798]
* **Version**: 1.15
* **Platform**: windows, unix(android) 

Hi, I observe behavior that looks confusing to me with these functions.

1. On windows when connection has been reset by remote side, in read callback that got error socket still remains readable and writable. But obviously we can do nothing else with it except close.

2. On windows immediately after uv_shutdown(), socket becomes not writable. 
But on unix(in my case it was Android, but source file for that is the same) after uv_shutdown(), it's still writable.

I check latest source files and have not found any changes related to those flags.

**Comment by bnoordhuis** [comment]
> On windows when connection has been reset by remote side, in read callback that got error socket still remains readable and writable.

A borderline bug.  You're supposed to close it on error (as you say), you wouldn't try to read or write.

> On windows immediately after uv_shutdown(), socket becomes not writable.  But on unix [..] after uv_shutdown(), it's still writable.

I'd say that's a UNIX bug.  The Windows behavior is correct.

Pull requests welcome, of course.
