### ISSUE TITLE
[Suggestion] Use Meson instead of GYP

### ISSUE THREAD

**Issue by jclc** [libuv/libuv#1799]
Hi, I'm porting a certain project's Python2 scripts to Python3 but irritatingly have to require Python2 anyway due to the libuv dependency. I've never even heard of GYP before so after some very brief research, this has apparently been the woe of many other GYP users and is a long-standing issue that will probably not be fixed before Python2's end of life in 2020. In fact, seems like some projects using GYP have moved to other build systems.

Meson is another build system based on Python, but it uses Python3 instead. Have you considered that as a replacement for GYP?

**Comment by bnoordhuis** [comment]
Thanks for the suggestion but there are no plans to switch to meson at this time.  Libuv is developed in close tandem with node.js, an as node.js uses gyp, so too does libuv.

Node.js may switch to cmake in the future and then libuv will follow suit.  Meson however is not on the table.

**Comment by refack** [comment]
@jclc meanwhile there is some movement toward [making GYP python3 compatible](https://groups.google.com/forum/#!topic/gyp-developer/U66xtisrYRM). Hope it matures.

**Comment by jclc** [comment]
Thanks for the responses. Hopefully the efforts will lead somewhere.
