### ISSUE TITLE
Crash on uv_loop_close after freeing watcher handle

### ISSUE THREAD

**Issue by beevik** [libuv/libuv#180]
I'm seeing crashes in `uv_loop_close` when closing a loop that's had all its watchers stopped. This happens when the memory allocated for the watcher handle is released before the loop is closed.

Here is a slightly contrived example to illustrate the problem:

```C
static void timer_callback(uv_timer_t * handle) {
    uv_timer_stop(handle);
}

void test() {
    uv_loop_t loop;
    uv_loop_init(&loop);

    uv_timer_t * timer = (uv_timer_t*)malloc(sizeof(uv_timer_t));
    uv_timer_init(&loop, timer);
    uv_timer_start(timer, timer_callback, 0, 1000);
    uv_run(&loop, UV_RUN_DEFAULT);
    free(timer);

    uv_loop_close(&loop);  /* crash occurs here */
}
```

It seems that `uv_timer_stop` is not enough to remove the watcher from the loop's internal list of watchers. Is this an error, or am I just using the API incorrectly?

**Comment by bnoordhuis** [comment]
> Is this an error, or am I just using the API incorrectly?

User error. :-)  You should not free the timer until you have either uv_close'd it and the close callback has been called, or the event loop has been shut down with uv_loop_close().

**Comment by beevik** [comment]
Ah, thanks. I knew there must be something. I didn't realize uv_close applied to timers too.  Now I know!  Thanks.
