### ISSUE TITLE
uv_close_cb cann't trigger

### ISSUE THREAD

**Issue by tekenuo** [libuv/libuv#1804]
As a server, In following conditions,uv_close_cb cann't be triggered.
1.client has been offline, and then onLine.Server will receive UV_EOF from client ,server then call uv_close to close the last socket.
2.When server receive more than one socket from the same client, in uv_connection_cb, server try to close the ealier socket. 

* **v1.8.1**: 
* **Windows**:

**Comment by bnoordhuis** [comment]
It's unclear to me what you mean.  Can you:

1. post a test case, and
2. try with the latest libuv?

**Comment by tekenuo** [comment]
Thank you for your reply .
In the connection_cb, I will check if the server has the same IP connected, if yes.Then The server will close the previous socket like following:
void connection_cb(uv_stream_t *server, int status)
{
   //Search for the socket list ,if the IP has ever connected to the server, Then close the earlier handle
   uv_close((uv_handle_t*) ealier_handle, uv_close_cb);
}

But the uv_close_cb cann't trigger

**Comment by bnoordhuis** [comment]
I'm afraid that's still too fragmentary to comment on.  Do you have a reduced, ready-to-run test case I can look at?

**Comment by cjihrig** [comment]
Closing pending follow up.
