### ISSUE TITLE
Server handle just a single request

### ISSUE THREAD

**Issue by koshinus** [libuv/libuv#1812]
* **Version**: 1.18
* **Platform**: Linux 4.13.0-38-generic 16.04.1-Ubuntu
I would like to implement the logic of the following type: [https://imgur.com/a/8hGw3Rr](url)
Allocating of internal resources and data parsing tested and working normally, but i can not get the network part to work. Actual version of this code could be find here: [https://github.com/koshinus/C_programs/tree/master/diploma](url)

**Comment by cjihrig** [comment]
Both of the links in this issue now 404. Can you open support questions at https://github.com/libuv/help.
