### ISSUE TITLE
Data error while calling uv_write in Linux

### ISSUE THREAD

**Issue by ssrlive** [libuv/libuv#1816]
I found a trap, when I call the uv_write function to write data, and then release the `uv_buf_t` which containing pointers to the `base` data immediately. 

These operations work very well under Windows and macOS, but it's often errors occur under Linux.

Can we do include copy-and-hold data in this line
https://github.com/libuv/libuv/blob/v1.x/src/unix/stream.c#L1466

and release data in this lines?
https://github.com/libuv/libuv/blob/v1.x/src/unix/stream.c#L725
https://github.com/libuv/libuv/blob/v1.x/src/unix/stream.c#L960

**Comment by bnoordhuis** [comment]
Libuv makes copies of the `uv_buf_t` structs but not the data they point to.

If you're saying the first case crashes for you, can you post a test case demonstrating that?  If it's the second, then it's working as expected.

**Comment by ssrlive** [comment]
if i write the following code. there maybe some error in linux.
```
{
            uv_buf_t tmp;
            char *p = (char *) calloc(257, sizeof(char));
            sprintf(p, "echo reply %d\n", i);

            tmp = uv_buf_init(p, strlen(p));

            uv_write_t *req = (uv_write_t *) calloc(1, sizeof(uv_write_t));
            uv_write(req, stream, &tmp, 1, &client_write_done_cb);

            memset(p, 0, 257);
            free(p);
        }
```

**Comment by bnoordhuis** [comment]
Yes, that's working as expected.  Making copies of the pointed-to data is prohibitively expensive if the data is large, hence libuv doesn't do it.  Free the data in the callback, not before.

**Comment by ssrlive** [comment]
Therefore, please specify this situation in the libuv documentation. Thank
you.

**Comment by bnoordhuis** [comment]
It's right there in the section on uv_write():

> The memory pointed to by the buffers must remain valid until the callback gets called.
