### ISSUE TITLE
docs: adding public members for sync getnameinfo result

### ISSUE THREAD

**Issue by creationix** [libuv/libuv#182]
According to the docs, the only public member of `uv_getnameinfo_t` is `loop`, but in order to use the new sync interface added in v1.3.0, you need to read the results at `req.host` and `req.service`.  I found this info by digging through the unit tests, it would be nice if the docs mentioned this as well.

**Comment by saghul** [comment]
@creationix can you please review https://github.com/libuv/libuv/pull/233 ?

**Comment by creationix** [comment]
@saghul perfect, +1

**Comment by saghul** [comment]
Thanks Tim, landed!
