### ISSUE TITLE
Header file name "winsock.h" conflicts with the system header file "winsock.h" on windows

### ISSUE THREAD

**Issue by sighingnow** [libuv/libuv#1821]
* **Version**: libuv1.x (current HEAD)
* **Platform**: Windows

We have a header file named with `winsock.h` under the `src/win` directory. However, on Windows, there's also a header file from system runtime named with `winsock.h`.

Generally specking, this shouldn't be a problem, since the `winsock.h` is placed inside the `src/win` folder and is treated as a internal header file. However, under certain circumstances, when we want to hack with libuv, we expose the internal include directories to external c files, then the c compiler will get confused and include the wrong header files.

This issue is a request to rename our `winsock.h` (may as well as `winsock.c`) to avoid the conflict and the confusion with system's header file on Windows. Since our `winsock.h` is only used internally, the renaming shouldn't cause any uncomfortable backwards compatibility issue.

**Comment by bzoz** [comment]
I don't think changing names will help with anything. If you expose internal headers sooner or later you will get some kind of name clash. You can always use relative paths in your C files - like `#include "deps/libuv/src/win/winsock.h"` or something similar.

That said, I think that having more descriptive name like `winsock_wrap.h` or something similar would make it slightly more readable. I would be +0 on such change.

I will close this issue. If you have time, feel free to open a PR with this change.

**Comment by bnoordhuis** [comment]
I'm -1 personally.  It means we need to invest time and accept churn for no value to libuv.
