### ISSUE TITLE
win: spawn() hangs when PATH starts with semicolon

### ISSUE THREAD

**Issue by piscisaureus** [libuv/libuv#183]
Reported here: https://github.com/joyent/node/issues/8441#issuecomment-73100021

**Comment by cjihrig** [comment]
Potentially relevant - https://github.com/joyent/libuv/issues/909

**Comment by piscisaureus** [comment]
Nevermind. @cjihrig is right, this has been fixed already.

**Comment by saghul** [comment]
@piscisaureus can we close this then?

**Comment by piscisaureus** [comment]
:)
