### ISSUE TITLE
uv_spawn: child pipes left non-blocking on Linux/sparc64

### ISSUE THREAD

**Issue by bradking** [libuv/libuv#1830]
* **Version**: 1.19.1
* **Platform**: Linux/sparc64

There is an asymmetry in the way the non-blocking flag is set and cleared on this platform.  It is set in the parent process by `ioctl/FIONBIO` (since commit ed2b5e60cbfa6ca824408dc792d9282e5b8e9bfd).  Then in the child between fork and exec it is cleared by `fcntl/O_NONBLOCK` (since #1167).  The latter step fails on Linux/sparc64.

For reference, here are relevant definitions on the platform:

```c
#define O_NONBLOCK      0x4000
#define O_NDELAY        (0x0004 | O_NONBLOCK)
```

The Linux/sparc64 behavior can be demonstrated in a small example:

```console
$ uname -s
Linux

$ uname -r
4.16.0-trunk-sparc64-smp

$ cat test_nonblock.c
#include <fcntl.h>
#include <stddef.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <unistd.h>

static int make_pipe() {
  int p[2];
  pipe(p);
  close(p[0]);
  return p[1];
}

int main(int argc, const char* argv_[]) {
  int nbio;
  int fd;
  int flags;

  fd = make_pipe();

  flags = fcntl(fd, F_GETFL);
  printf("fd %d flags=0x%x on creation\n", fd, flags);

  nbio = 1;
  ioctl(fd, FIONBIO, &nbio);

  flags = fcntl(fd, F_GETFL);
  printf("fd %d flags=0x%x after setting nbio\n", fd, flags);

#if defined(CLEAR_FIONBIO)
  printf("fd %d clearing nbio using ioctl/FIONBIO\n", fd);
  nbio = 0;
  ioctl(fd, FIONBIO, &nbio);
#elif defined(CLEAR_NDELAY)
  printf("fd %d clearing nbio using fcntl/O_NDELAY\n", fd);
  fcntl(fd, F_SETFL, flags & ~O_NDELAY);
#else
  printf("fd %d clearing nbio using fcntl/O_NONBLOCK\n", fd);
  fcntl(fd, F_SETFL, flags & ~O_NONBLOCK);
#endif

  flags = fcntl(fd, F_GETFL);
  printf("fd %d flags=0x%x after clearing nbio\n", fd, flags);

  if (flags & O_NONBLOCK) {
    printf("fd %d has O_NONBLOCK set\n", fd);
  } else {
    printf("fd %d has O_NONBLOCK clear\n", fd);
  }

  return 0;
}

$ cc test_nonblock.c && ./a.out
fd 4 flags=0x1 on creation
fd 4 flags=0x4005 after setting nbio
fd 4 clearing nbio using fcntl/O_NONBLOCK
fd 4 flags=0x4005 after clearing nbio
fd 4 has O_NONBLOCK set

$ cc test_nonblock.c -DCLEAR_NDELAY && ./a.out
fd 4 flags=0x1 on creation
fd 4 flags=0x4005 after setting nbio
fd 4 clearing nbio using fcntl/O_NDELAY
fd 4 flags=0x1 after clearing nbio
fd 4 has O_NONBLOCK clear

$ cc test_nonblock.c -DCLEAR_FIONBIO && ./a.out
fd 4 flags=0x1 on creation
fd 4 flags=0x4005 after setting nbio
fd 4 clearing nbio using ioctl/FIONBIO
fd 4 flags=0x1 after clearing nbio
fd 4 has O_NONBLOCK clear
```

Note that in the `fcntl/O_NONBLOCK` case the nbio flag remains set!

The observed behavior on Linux/sparc64 is that setting nbio via `ioctl/FIONBIO` actually sets flags using both bits from `O_NDELAY`.  Clearing with only `fcntl/O_NONBLOCK` is silently ignored, while clearing with `fcntl/O_NDELAY` or `ioctl/FIONBIO` succeeds.

According to #1167 we cannot switch back to `ioctl/FIONBIO` for clearing nbio.  That leaves either clearing with `fcntl/O_NDELAY` or setting and clearing with only `fcntl/O_NONBLOCK`.

**Comment by bnoordhuis** [comment]
Thanks for the bug report.  Can you check if #1832 addresses it?

**Comment by DerDakon** [comment]
For reference: https://marc.info/?l=linux-sparc&m=159074529321551&w=2
