### ISSUE TITLE
[feature request] Support cross-platform sendfile?

### ISSUE THREAD

**Issue by winterland1989** [libuv/libuv#1831]
I think adding a cross platform `sendfile` with the ability to prepend header bytes will be very useful. Window support this natively with [`TransmitFile `](https://msdn.microsoft.com/en-us/library/ms740565(VS.85).aspx), and under unix we can first send header bytes using `send` with `MSG_MORE` flag, then use `sendfile` to send actually file.

Doing this outside libuv is difficult, since we have to access complete port(win) or poll the writability(unix).  One solution is to use `uv_poll`, but making an extra `uv_poll_t` for the socket just for  sending file seems too expensive.

**Comment by bnoordhuis** [comment]
Do you have suggestions for what the API should look like?  I assume it operates on a `uv_stream_t` and for maximum efficiency takes a:

1. list of buffers to prepend
2. list of structs with `uv_os_fd_t` + start + length to send (flags too?)
3. list of buffers to append

Cancellation and error reporting might get a tad unwieldy.  The callback should be informed what has been consumed and what hasn't.

**Comment by winterland1989** [comment]
I'll focus on common case rather than generality, so it should take

1. a buffer to prepend
2. a uv_os_fd_t (which should be a regular file)
3. start 
4. length to send (automatically call fs_stat when length is 0)
5. callback which get send status (libuv should loop writing until the whole file section get sent).

I don't see much use case for sending appended bytes, and i always prefer user space buffer filling rather than let glib or kernel do that for you since it's no faster anyway, so let's keep things as simple as possible for common use case.

**Comment by bnoordhuis** [comment]
@libuv/collaborators Your thoughts?

**Comment by santigimeno** [comment]
I like Ben suggestion better. Having a list of buffers matches other similar functions in the API and I guess that leads to supporting multiple files as well. No strong opinion on the appending buffers case, though fwict `TransmitFile` supports it. How would we call this new function?

**Comment by bnoordhuis** [comment]
Apropos appending buffers: I mention that because of trailing HTTP headers.  Seems like a reasonable thing to support.

**Comment by santigimeno** [comment]
> uv_stream_splice()

I like it

**Comment by cjihrig** [comment]
SGTM

**Comment by vtjnash** [comment]
It feels a shame to lose the discussion context here, especially because it might not happen anytime soon.

**Comment by bnoordhuis** [comment]
This issue has been open for years with no progress and with the increasing shift to end-to-end encryption, plaintext sendfile() serves no purpose. I'm going to close it out.

(Linux of course has a kTLS-aware sendfile() but it's very much non-portable.)

**Comment by septatrix** [comment]
> ...and with the increasing shift to end-to-end encryption, plaintext sendfile() serves no purpose.

A lot of servers have a reverse proxy in front of them which handles TLS termination so plaintext sendfile is very much still relevant

**Comment by bnoordhuis** [comment]
You're about 4 years late to this discussion but okay, to your point, I'd argue even TLS termination is slowly dying out. Encryption is cheap enough nowadays that there's hardly ever a reason not to encrypt end-to-end.

Unless you're specifically talking about TLS termination on the same machine between different processes. Sure, that's a thing. Not a thing we have to bend over backwards to support though, IMO.

**Comment by midn1** [comment]
> Encryption is cheap enough nowadays that there's hardly ever a reason not to encrypt end-to-end.

In your bubble, perhaps.
