### ISSUE TITLE
make check failed with "Assertion failed in test/test-getaddrinfo.c on line 43: status < 0"

### ISSUE THREAD

**Issue by abaelhe** [libuv/libuv#1838]
this is DNS hijack？ it's not technology factor.

* **Version**: `libuv-1.20.2`
* **Platform**: `Darwin Abael.lan 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64`

**REPRODUCE STEP:** 
`     ./autogen.sh`
`    ./configure  --prefix=/usr/local`
`    make -j8`
`    make check`
    then will reproduce the issue

**ERROR MESSAGE:**
`not ok 103 - getaddrinfo_fail`
`# exit code 6`
`# Output from process getaddrinfo_fail:`
`# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0`
`not ok 104 - getaddrinfo_fail_sync`
`# exit code 6`
`# Output from process `getaddrinfo_fail_sync`:`
`# Assertion failed in test/test-getaddrinfo.c on line 117: 0 > uv_getaddrinfo(uv_default_loop(), &req,` `NULL, "xyzzy.xyzzy.xyzzy.", NULL, NULL)`

**INVESTIGATION:**
both test implements `getaddrinfo_fail` and `getaddrinfo_fail_sync` in source file: test/test-getaddrinfo.c using same hostname `"xyzzy.xyzzy.xyzzy."`; 

and here in Beijing, we got:
`(finup) Abael:libuv-1.20.2 abael$ ping "xyzzy.xyzzy.xyzzy."`
`PING xyzzy.xyzzy.xyzzy (111.63.112.254): 56 data bytes`
`......`

and the hostname "xyzzy.xyzzy.xyzzy." been resolved to `"111.63.112.254"` here in Beijing can be confirmed by debug  libuv-1.20.2 source code, src/unix/getaddrinfo.c:104  
`        err = getaddrinfo(req->hostname, req->service, req->hints, &req->addrinfo);`
after above line been executed, do got :
    `"err" = 0`
    `"111.63.112.254"` filled in `req->addrinfo`;

**RESOLUTION**:
    macOS: `sed -i '' 's/xyzzy\.xyzzy\.xyzzy\./xyzzy/' test/test-getaddrinfo.c`
    Linux: `sed -i  's/xyzzy\.xyzzy\.xyzzy\./xyzzy/' test/test-getaddrinfo.c`

then confirm:
    `make clean`
    `make`
    `make check`

 
ADDITIONAL INFO.:

`% [whois.apnic.net]`
`% Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html`

`% Information related to '111.0.0.0 - 111.63.255.255'`

`% Abuse contact for '111.0.0.0 - 111.63.255.255' is 'abuse@chinamobile.com'`

`inetnum:        111.0.0.0 - 111.63.255.255`
`netname:        CMNET`
`descr:          China Mobile Communications Corporation`
`descr:          Mobile Communications Network Operator in China`
`descr:          Internet Service Provider in China`
`country:        CN`
`org:            ORG-CM1-AP`
`admin-c:        JS686-AP`
`tech-c:         HL1318-AP`
`remarks:        service provider`
`status:         ALLOCATED PORTABLE`
`mnt-by:         APNIC-HM`
`mnt-lower:      MAINT-CN-CMCC`
`mnt-routes:     MAINT-CN-CMCC`
`remarks:        --------------------------------------------------------`
`remarks:        To report network abuse, please contact mnt-irt`
`remarks:        For troubleshooting, please contact tech-c and admin-c`
`remarks:        Report invalid contact via www.apnic.net/invalidcontact`
`remarks:        --------------------------------------------------------`
`last-modified:  2017-08-30T07:22:04Z`
`source:         APNIC`
`mnt-irt:        IRT-CHINAMOBILE-CN`

`irt:            IRT-CHINAMOBILE-CN`
`address:        China Mobile Communications Corporation`
`address:        29, Jinrong Ave., Xicheng District, Beijing, 100032`
`e-mail:         abuse@chinamobile.com`
`abuse-mailbox:  abuse@chinamobile.com`
`admin-c:        CT74-AP`
`tech-c:         CT74-AP`
`auth:           # Filtered`
`mnt-by:         MAINT-CN-CMCC`
`last-modified:  2014-11-18T02:41:02Z`
`source:         APNIC`

`organisation:   ORG-CM1-AP`
`org-name:       China Mobile`
`country:        CN`
`address:        29, Jinrong Ave.`
`phone:          +86-10-5260-6688`
`fax-no:         +86-10-5261-6187`
`e-mail:         hostmaster@chinamobile.com`
`mnt-ref:        APNIC-HM`
`mnt-by:         APNIC-HM`
`last-modified:  2017-08-23T12:56:36Z`
`source:         APNIC`

`person:         haijun li`
`nic-hdl:        HL1318-AP`
`e-mail:         hostmaster@chinamobile.com`
`address:        29,Jinrong Ave, Xicheng district,beijing,100032`
`phone:          +86 1052686688`
`fax-no:         +86 10 52616187`
`country:        CN`
`mnt-by:         MAINT-CN-CMCC`
`abuse-mailbox:  abuse@chinamobile.com`
`last-modified:  2016-11-29T09:38:38Z`
`source:         APNIC`

`person:         Jinxia Sun`
`address:        China Mobile Communications Corporation`
`address:        29, Jinrong Ave., Xicheng District, Beijing, 100032`
`country:        CN`
`phone:          +86-10-52686688`
`fax-no:         +86-10-66006012`
`e-mail:         hostmaster@chinamobile.com`
`nic-hdl:        JS686-AP`
`remarks:        ------------------------------`
`remarks:        Please send abuse e-mail to`
`remarks:        abuse@chinamobile.com`
`remarks:        Please send probe e-mail to`
`remarks:        security@chinamobile.com`
`remarks:        -------------------------------`
`mnt-by:         MAINT-CN-CMCC`
`last-modified:  2014-11-18T02:47:03Z`
`source:         APNIC`

`% Information related to '111.0.0.0/10AS9808'`

`route:          111.0.0.0/10`
`descr:          China Mobile communications corporation`
`origin:         AS9808`
`mnt-by:         MAINT-CN-CMCC`
`last-modified:  2012-02-15T08:47:26Z`
`source:         APNIC`

`% This query was served by the APNIC Whois Service version 1.88.15-46 (WHOIS-US4)`

**Comment by bnoordhuis** [comment]
Thanks for the bug report.  Yes, you're right, it's a kind of DNS hijacking.

Your suggestion of using bare `"xyzzy"` introduces a different issue.  Such queries are resolved relative to the current search domain (ex. `xyzzy.example.com` when `search=example.com`) and could therefore resolve to a real host.

Since there isn't really anything we can do to improve matters, I'll go ahead and close this out.
