### ISSUE TITLE
in uv_default_loop have pipe handle leak?

### ISSUE THREAD

**Issue by huangchouchou** [libuv/libuv#1844]
i use udp default loop, empty work, but find the handle not close.

source code
`
uv_loop_t* loop = uv_default_loop();

uv_udp_t udp;

uv_udp_init(loop, &udp);

uv_close_all(loop, NULL);

uv_loop_close(loop);
`
use lsof find FIFO leak.
test    17088 root    5r  FIFO   0,10      0t0 1011624 pipe
test    17088 root    6w  FIFO   0,10      0t0 1011624 pipe

**Comment by bnoordhuis** [comment]
Two observations:

1. You don't check return values.
2. There's no such thing as `uv_close_all()`.

I see no reason to believe it's a libuv bug.  If you still have questions, can you post them to libuv/help?  Please include (or link to) full source code.  Cheers.
