### ISSUE TITLE
Assertion failed in test/test-poll.c on line 212: events & context->events on linux-sparc64

### ISSUE THREAD

**Issue by glaubitz** [libuv/libuv#1859]
Starting with 1.20.2 the testsuite for libuv fails on linux-sparc64 with:

```
not ok 167 - poll_duplex
# exit code 6
# Output from process `poll_duplex`:
# Assertion failed in test/test-poll.c on line 212: events & context->events
ok 168 - poll_nested_epoll
ok 169 - poll_oob
not ok 170 - poll_unidirectional
# exit code 6
# Output from process `poll_unidirectional`:
# Assertion failed in test/test-poll.c on line 212: events & context->events
```

Full build log in: https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=sparc64&ver=1.20.3-2&stamp=1527934577&raw=0

I have not done any inspection yet what could be the culprit. Maybe @bradking has an idea?

CC @jrtc27 who is another Debian sparc64 porter.

**Comment by bnoordhuis** [comment]
Thanks for the report.  When you say "starting 1.20.2", does that mean 1.20.1 is okay?  Or did you upgrade from an older version?

**Comment by bradking** [comment]
I caught the failure in a debugger.  `epoll` is returning just `POLLHUP` and triggering [this workaround](https://github.com/libuv/libuv/blob/v1.20.3/src/unix/linux-core.c#L375-L391).  However, none of `POLLIN | POLLOUT | UV__POLLPRI` is set so no other flags are added.  Then [this code](https://github.com/libuv/libuv/blob/v1.20.3/src/unix/poll.c#L54-L64) produces `pevents == 0`.

I think the problem is that #691 did not update the workaround linked above.  This patch fixes it:

```patch
diff --git a/src/unix/linux-core.c b/src/unix/linux-core.c
index b63c25f3..0c401276 100644
--- a/src/unix/linux-core.c
+++ b/src/unix/linux-core.c
@@ -388,7 +388,7 @@ void uv__io_poll(uv_loop_t* loop, int timeout) {
        * free when we switch over to edge-triggered I/O.
        */
       if (pe->events == POLLERR || pe->events == POLLHUP)
-        pe->events |= w->pevents & (POLLIN | POLLOUT | UV__POLLPRI);
+        pe->events |= w->pevents & (POLLIN | POLLOUT | UV__POLLRDHUP | UV__POLLPRI);
 
       if (pe->events != 0) {
         /* Run signal watchers last.  This also affects child process watchers
```

**Comment by bradking** [comment]
@santigimeno the patch in my previous comment here is a fixup to your PR #691.  Does it look correct to you?

**Comment by santigimeno** [comment]
Yeah, SGTM

**Comment by glaubitz** [comment]
@santigimeno Any chance this can get merged?

**Comment by santigimeno** [comment]
@glaubitz I was expecting @bradking would send a PR :)

**Comment by glaubitz** [comment]
Ah, sorry. I thought I was inside a PR here -.-. I should have another coffee.
