### ISSUE TITLE
help: tty example Segmentation fault？

### ISSUE THREAD

**Issue by lazebird** [libuv/libuv#1865]
* **Version**: 
ii  libuv1:amd64                    1.9.1-3                                 amd64        asynchronous event notification library - runtime library
ii  libuv1-dev:amd64                1.9.1-3                                 amd64        asynchronous event notification library - development files
* **Platform**: 
Linux vm 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

I am new to libuv, is there something wrong used by me or a bug in lib? thanks for your help.

* environment
ii  libuv1:amd64                    1.9.1-3                                 amd64        asynchronous event notification library - runtime library
ii  libuv1-dev:amd64                1.9.1-3                                 amd64        asynchronous event notification library - development files
Linux vm 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

* operation
gcc libuv_sample_tty.c -luv -g -Wall -DDEBUG=1
./a.out

* code
```
#include <stdio.h>
#include <string.h>
#include <uv.h>

uv_tty_t g_tty;
uv_timer_t g_tick;
int g_width, g_height, g_pos;

static void __update(uv_timer_t* req)
{
    uv_write_t wreq;
    char data[64];
    const char* msg = "    Hello TTY    ";
    uv_buf_t buf;   
    buf.base = data;
#if DEBUG
    buf.len = snprintf(data, sizeof(data), "%s\n", msg); 	// cause segmentation fault!??
#else	
    buf.len = snprintf(data, sizeof(data),
		"\033[2J" 
		"\033[H"
		"\033[%dB\033[%luC"
		"\033[42;37m%s"
		, g_pos, (g_width - strlen(msg))/2, msg); 
#endif	
    uv_write(&wreq, (uv_stream_t*)&g_tty, &buf, 1, NULL);
    
    if(++g_pos > g_height){
        uv_tty_reset_mode();
        uv_timer_stop(&g_tick);
    }   
}

int main(void)
{
    uv_loop_t* loop = uv_default_loop();
    
    uv_tty_init(loop, &g_tty, 1, 0); 
    uv_tty_set_mode(&g_tty, 0); 
    
    if(uv_tty_get_winsize(&g_tty, &g_width, &g_height)){
        puts("Could not get TTY information");
        uv_tty_reset_mode();
        return 1;
    }   
    
    printf("Width %d, height %d\n", g_width, g_height);
    uv_timer_init(loop, &g_tick);
    uv_timer_start(&g_tick, __update, 200, 200);    

    uv_run(loop, UV_RUN_DEFAULT);
	printf("\033[0m\n"); // reset color
	return 0;
}
```

**Comment by lazebird** [comment]
wreq cannot be a local variable...

**Comment by handicraftsman** [comment]
@bnoordhuis that needs to be stated in documentation.
