### ISSUE TITLE
uv_async_send heavily hurts main thread performance when many async handles exist

### ISSUE THREAD

**Issue by CFSworks** [libuv/libuv#1866]
The [async_send handler on UNIX](https://github.com/libuv/libuv/blob/v1.20.3/src/unix/async.c#L105) involves a while loop which iterates over every created `uv_async_t` handle when a wakeup event is processed, regardless of whether the handles have pending events or not. The loop has a linear per-handle cost, which becomes significant for applications that use many async events for thread messaging and deferred processing.

A small example case that demonstrates this can be found [here](https://gist.github.com/CFSworks/08233b949db79d7d9e8213c64523ade9). Also attached is a log of runs with "created handle" counts at several multiples of 1,000, where the linear increase in CPU time can be seen.

This caveat is [not documented](http://docs.libuv.org/en/v1.x/async.html) in the manual, and isn't typical of this kind of framework: it is theoretically possible - and indeed customarily expected - that the handler require (close to) constant time, thus I believe this performance cost to be an unintended bug.

* **Version**: v1.20.3
* **Platform**: Any UNIX; tested on Linux (did not test Win32)

**Comment by bnoordhuis** [comment]
Thanks for the suggestion, but there are reasons why `uv_async_send()` works the way it does.  If you think the O(n) processing caveat should be noted in the docs, please open a pull request.

**Comment by CFSworks** [comment]
@bnoordhuis What should be stated in the docs? "There are reasons this works the way it does."?

**Comment by bnoordhuis** [comment]
Reference documentation doesn't have to explain every last little thing.  It just has to document _what_ is, not _why_ that is.

**Comment by CFSworks** [comment]
But I don't know if I'm supposed to say "currently there's this limitation" (e.g. if the reasons are "we don't have the manpower to fix it") or "there's a limitation by design" (e.g. "there's a big performance boost in another part of the system to do it this way") or anything. My question was meant to illustrate the paradox of withholding reasons about intended behavior from the person you're asking to describe intended behavior.


If somebody were to submit a PR addressing the underlying performance issue, would it simply be closed with the same message? Or is there some list of criteria it would have to hit to be regarded as an improvement?

**Comment by bnoordhuis** [comment]
I wasn't asking you to describe the intended behavior though, only the actual behavior. :-)

Okay, the reasons things work the way they do are, in decreasing order of importance:

1. Correctness: events should never get lost.
2. Performance: make as few system calls as necessary (that includes taking out locks)
3. Portability/maintainability: it should work everywhere without too much hassle.

Sit down and think about it for a while, or look at other I/O libraries, and you'll see there isn't much room for improvement that doesn't violate some of those rules.

**Comment by CFSworks** [comment]
> Okay, the reasons things work the way they do are, in decreasing order of importance:

These are good design constraints; nothing on this list is surprising at all to me. But I don't see how these are reasons justifying the current implementation in particular? There's a bunch of solutions that could fit those constraints, no?

> Sit down and think about it for a while, or look at other I/O libraries

Following this advice, I came up with the following alternative strategies, all of which have equal correctness/portability, but better performance (average case close to constant-time and uses no more syscalls than the current implementation):

* **Send the pointer**: Instead of [writing a zero byte](https://github.com/libuv/libuv/blob/v1.20.3/src/unix/async.c#L129-L130) to the async watcher pipe, write the pointer to the `uv_async_t`. If the pipe is full, set a flag on the `uv_loop_t` that triggers the old behavior: a full rescan of all created `uv_async_t`s. (This will be an uncommon condition, so in most cases, the performance will be better than O(n).)
* **Circular buffer**: To solve the "the pipe is full" problem, allocate a circular buffer large enough to hold all pointers to all `uv_async_t`s. The `uv_async_send()` implementation atomically increments the "head" position in the buffer, writes the async pointer to the head element, inserts a memory fence, then wakes up the main thread. The main thread stops upon discovering a null pointer (waiting instead for the wakeup event from `av_async_send()`). The circular buffer will have to be resized when too many new handles are created - this can be done in a safe way (create a fresh buffer, swap, and drain the old buffer in the main thread), but it might be more trouble than it's worth.
* **Linked list**: Give every `uv_async_t` a "next_scheduled" pointer, initialized to point to itself. Give the loop a pointer to the head of the linked list of pending async handles. After setting `handle->pending = 1`, atomically swap the "handle->next_scheduled" pointer with the linked list's head (this doesn't necessarily have to be implemented as a memory<->memory swap), then wake up the main thread, which exchanges the head pointer for NULL and walks (and resets) the linked list of scheduled handles.

...these are just what I was able to come up with. I'm sure others could brainstorm even more ideas, but being immediately closed as a wontfix issue definitely won't inspire that kind of discussion, which brings me back to my question:

> there are reasons why `uv_async_send()` works the way it does

_What are these reasons?_

Why does it work the way it does, and not one of these other ways? What is the rationale for closing an issue like this immediately as wontfix, without even any investigation/discussion about alternatives?

**Comment by bnoordhuis** [comment]
> Send the pointer

I knew you were going to bring that up because it's the "obvious" solution.  It's not bulletproof however because threads can have different memory mappings: address _x_ in thread 1 might be mapped at address _y_ in thread 2.

> Circular buffer

Design constraint: libuv tries to avoid allocating memory.

> Linked list

It's something I've considered but compare-and-swap has no forward progress guarantees and you probably can't implement it with just atomic exchange.

**Comment by CFSworks** [comment]
**Now** we're making progress!

> threads can have different memory mappings: address x in thread 1 might be mapped at address y in thread 2

What prevents thread 1 storing x inside the `uv_async_t` at init time so thread 2 knows x, and sends it instead of y? (It's also possible to compile this out on platforms where threads cannot have different memory mappings, which to be honest, I have never encountered.)

> Design constraint: libuv tries to avoid allocating memory.

I didn't like it either, and it has the same problems as sending the pointer through the pipe. I'll retract that one.

> compare-and-swap has no forward progress guarantees

N.B. the current implementation does use a compare-and-swap operation. Although I suspect you're referring to compare-and-swap in a loop. Note however that the only variable under contention is the head to the linked list. The only thread that will be writing to the "next_scheduled" pointer is the thread that has just enqueued the async handle for processing. The caveat is that there is a data race wherein the main thread can see the "next_scheduled" pointer in its "I don't know the next scheduled handle" state, but as long as this has a well-defined sentinel value (distinct from "end of list") the main thread can just spinwait for the operation to complete (as `uv_async_send()` provides a guarantee that this will happen).

However, per your edit, this does require being able to find the loop from a pointer stored in the async handle, and if the system could have different per-thread memory mappings, it might need to be stored as an offset rather than a memory address.

**Comment by bnoordhuis** [comment]
Sorry, it seems I missed the notification for your last comment. Better late than never, I suppose. :-)

> What prevents thread 1 storing x inside the uv_async_t at init time so thread 2 knows x, and sends it instead of y?

That's a clever idea and something I've considered for libuv v2.

In v1.x it's hampered by our ABI stability guarantee: `uv_async_t` is too crowded to store an additional pointer.

I guess it might be possible if we got rid of the `loop->async_handles` tail queue altogether, that would free up enough space. I'll have to think about that.

> It's also possible to compile this out on platforms where threads cannot have different memory mappings, which to be honest, I have never encountered.

Linux has [remap_file_pages(2)](http://man7.org/linux/man-pages/man2/remap_file_pages.2.html), although you can be forgiven for not deducing that possibility from the man page. [Here](https://bitbucket.org/pypy/stmgc/raw/c7/c7/README.txt) is a document that describes one possible approach.

> Although I suspect you're referring to compare-and-swap in a loop.

That's correct. The problem with a loop is that other threads can indefinitely keep "stealing" the head pointer, blocking the victimized thread from making forward progress.

**Comment by CFSworks** [comment]
> Sorry, it seems I missed the notification for your last comment. Better late than never, I suppose. :-)

The delay really didn't affect me. Your immediate closure of this issue and lack of eagerness to discuss alternatives last year sent a strong message that the libuv project was not interested in changing the async machinery, and I implemented my own workaround in my downstream project.

> That's a clever idea and something I've considered for libuv v2.

Thanks for the compliment, though since the idea just amounts to sending a unique identifier down the pipe to the main thread, I'm surprised that this is seen as "clever" while using the base address of the uv_async_t as the identifier (thereby eliminating any need for extra storage) is called "obvious."

> In v1.x it's hampered by our ABI stability guarantee: uv_async_t is too crowded to store an additional pointer.

Have you already considered sending the callback pointer to the main thread? That's already in the struct, and should produce expected results even when the callback pointer isn't unique. This also solves the problem of duplicated send calls being coalesced, should that be a caveat that the libuv project wishes to remove.

> Linux has remap_file_pages(2), although you can be forgiven for not deducing that possibility from the man page. Here is a document that describes one possible approach.

Frankly it's very unclear what problem is being solved here. It already breaks libuv if the async handle is ever copied and used; generally on C/POSIX, if copying a structure is forbidden, so too is changing the base address of the structure. Exceptions can exist, but if they aren't documented and promised to the downstream user, the downstream user must stick with the convention, as indeed most any library on Linux will break when trying to use a shared structure -- which is probably entangled with other structures and pointers -- from a separate thread with inconsistent memory addresses. The reference documentation isn't promising any differently to anyone; supporting threads with unique memory mappings doesn't seem to be part of the libuv "contract of behavior" (although perhaps it should, if you know of some particular user depending on this to work and it's important that everybody be aware). As it is, changing the implementation to depend on consistent pointers wouldn't be breaking any promises made by the documentation.

I do have a morbid curiosity as to what use case is creating all of these constraints that gave rise to such an inefficient cross-thread signaling implementation, as the vast majority of the world's software developers would prioritize having a messaging call work in O(1) time far above having it work when memory is shuffled around. But I'm no longer personally invested in having a faster async implementation; as I said before, I've already gone through all of the trouble of implementing a workaround for this pitfall, so upstream improvements wouldn't benefit me at this point. I was only hoping I could spare someone else using libuv from the same misery.

**Comment by bnoordhuis** [comment]
> I do have a morbid curiosity as to what use case is creating all of these constraints that gave rise to such an inefficient cross-thread signaling implementation, as the vast majority of the world's software developers would prioritize having a messaging call work in O(1) time far above having it work when memory is shuffled around.

I think you're committing the myopia fallacy here, reasoning too much from your own narrow use case.

Libuv is a popular library and used under a wide range of circumstances. We try to accommodate that as much as is reasonably possible and try to keep the door open for widening that range further still.

Example: `uv_async_send()` is not only safe to use from another thread, but also from a signal handler.

That brings its own set of constraints because a) there is little you can do safely from a signal handler, and b) it may now be racing not just with other threads but also with its own.

Example of a possible future extension: libuv has (limited) fork support. It's not out of the question that we may support cross-process async handles someday.

**Comment by CFSworks** [comment]
> I think you're committing the myopia fallacy here, reasoning too much from your own narrow use case.

You are mistaken. I don't even have a use case anyone. I'm only curious about what circumstance would cause such a break from the usual convention of requiring pointer consistency on types that may not be copied. Try playing this memory rearrangement game with any of the "big name" C libraries (ones that have the same goal of supporting everyone's diverse use case) and you'll encounter segfaults when they try to access nested pointers. What's so important that it's worth sacrificing performance to achieve?

> Example: uv_async_send() is not only safe to use from another thread, but also from a signal handler.

Well now I know you're confused indeed: I know for a fact that Linux doesn't touch memory mappings at all during a signal handler.

> Example of a possible future extension: libuv has (limited) fork support. It's not out of the question that we may support cross-process async handles someday

You do realize fork copies the address space... right? (You could be forgiven for not knowing this as immediately after the fork call the respective memory spaces do appear identical.) The async mechanism breaks on copy, unless it's changed.

Although I do have a suggestion for that in my last comment. If your mouse has a scroll wheel, try rotating it either up or down while the cursor is over the page - it should allow you to read more of what I had written than just the final paragraph. 👍

**Comment by bnoordhuis** [comment]
> I know for a fact that Linux doesn't touch memory mappings at all during a signal handler.

I was - rather clearly, IMO - talking about design constraints. If you want to talk about confused: he who fits the shoe.

> You do realize fork copies the address space...

It sounds like you're not familiar with shared memory mappings? I don't think this issue is the place to explicate but try a google search for 'fork mmap'.
