### ISSUE TITLE
uv_fs_poll_t internal uv_fs_t prevents event loop close

### ISSUE THREAD

**Issue by addaleax** [libuv/libuv#1869]
* **Version**: Current v1.x head
* **Platform**: At least all UNIX

`uv_fs_poll_t` uses stat requests internally. However, such an internal request may be pending even when the close callback for `uv_fs_poll_t` is called; that doesn’t seem right to me? In particular, after the `close` callback, from a library user’s point of view it looks like the event loop can be closed, but that fails because the stat req is still active.

There’s also this `TODO` comment by @bnoordhuis that seems very related: https://github.com/libuv/libuv/blob/0cdb4a5b4b706d0e09413d9270da28f9a88dc083/src/fs-poll.c#L37

I’m not sure how exactly that would look like, though.

https://github.com/addaleax/libuv/commit/78ea58351132a610682c4a0f30795105339f8298 has a regression test for this.

**Comment by bnoordhuis** [comment]
I think that can be fixed by postponing the close callback until the internal timer handle and fs request have closed/finished.

Right now `uv_close()` calls `uv__make_close_pending()` (`uv_want_endgame()` on Windows) immediately but that needs to be delayed.
