### ISSUE TITLE
recipe for target 'check-am' failed

### ISSUE THREAD

**Issue by ddrmorais** [libuv/libuv#1870]
Makefile:4579: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/dario/opencvdependencies/libuv-v1.20.3'
Makefile:4835: recipe for target 'check-am' failed
make: *** [check-am] Error 2

* **Version**: 
* **Platform**:

**Comment by ddrmorais** [comment]
I am trying to install libuv packet. However, I have had this error.

**Comment by addaleax** [comment]
Can you show more output, or upload it somewhere?

**Comment by ddrmorais** [comment]
Sure
[file.txt](https://github.com/libuv/libuv/files/2082072/file.txt)

**Comment by santigimeno** [comment]
The test failures are:

```
not ok 196 - spawn_fails
# exit code 6
# Output from process `spawn_fails`:
# Assertion failed in test/test-spawn.c on line 188: r == UV_ENOENT || r == UV_EACCES
not ok 197 - spawn_fails_check_for_waitpid_cleanup
# exit code 6
# Output from process `spawn_fails_check_for_waitpid_cleanup`:
# Assertion failed in test/test-spawn.c on line 208: r == UV_ENOENT || r == UV_EACCES
```

@ddrmorais what os are you running the tests on? Can you print the value of `r` after [this line](https://github.com/libuv/libuv/blob/v1.x/test/test-spawn.c#L187)? (you can add something like this: `fprintf(stderr, "r: %d\n", r);`)

**Comment by ddrmorais** [comment]
Thank you very much.
But I have found that my error was happening because of something else.
