### ISSUE TITLE
libuv-1.20.2 build fails one of its tests.

### ISSUE THREAD

**Issue by qolii** [libuv/libuv#1871]
In my build log, I get:
```
make[1]: Entering directory '/build/source'
1..320
ok 1 - platform_output
...
<all happy>
...
not ok 177 - shutdown_close_pipe
# exit code 6
# Output from process `shutdown_close_pipe`: (no output)
Output from process `shutdown_close_pipe`:
# Assertion failed in test/test-shutdown-close.c on line 55: status == 0
...
<all happy>
...
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:4803: check-TESTS] Error 1
make[1]: Leaving directory '/build/source'
make: *** [Makefile:5063: check-am] Error 2
builder for '/nix/store/xykhnyz1pbwzddban6fn20ngdib2bcin-libuv-1.20.2.drv' failed with exit code 2
```

* **Version**: `1.20.2`
* **Platform**: `Linux aaa 4.16.13 #1-NixOS SMP Wed May 30 06:17:45 UTC 2018 armv7l GNU/Linux`

**Comment by qolii** [comment]
Note, I'm on NixOS Linux, and ARMv7. Is this expected?

**Comment by bnoordhuis** [comment]
It's probably a permissions issue.  That test tries to connect to a UNIX socket created by a helper process.

**Comment by cjihrig** [comment]
@qolii any response to the last comment?

**Comment by qolii** [comment]
@cjihrig, sorry about the delay here. I'm not sure. It failed for me multiple times in a row (when I posted the Issue), and I tried it again now just the same and it passed. All times, the build was done as root, so I'm not sure permissions are the problem.

Feel free to close as spurious!

**Comment by cjihrig** [comment]
Thanks!

**Comment by qolii** [comment]
Hm. Is there a chance there is a race condition in this test? I'm seeing the build failure again (my hardware is 8-core, and I'm building essentially with `make -j8`). Changing it to build on only one core has made it succeed again. Not proof, I know, but this behavior seems like a prime candidate for a race: it has failed 9/10 times on an 8-core build and passed 1/1 times on a 1-core build.

**Comment by bnoordhuis** [comment]
The test suite doesn't runs tests in parallel, only sequentially, so that's probably not it.
