### ISSUE TITLE
About escape processing of TTY on Windows.

### ISSUE THREAD

**Issue by erw7** [libuv/libuv#1874]
For the neovim I have created a [patch](https://github.com/neovim/neovim/pull/8462/files#diff-78fd1ba9241d591774d61be0766558e0) to handle `CSI Ps SP Q` Set Cursor Style in libuv escape sequence processing on Windows. At that time I found the following problems.

1. Up to the next final final byte after the normal sequence like `CSI [` is not output.
2. An invalid sequence such as `CSI ? ? parameter bytes final byte` is processed as a normal sequence.
3. Number of arguments not strictly verified.
4. `CSI 25 h` operates as Show Cursor. `CSI 25 l` operates as Hide Cursor.
5. It works even though `CSI ? PS J` etc does not support Selective Erase.

I'd like to submit this patch upstream. How much should the above problem be corrected? I think that `1.` is a pug and should be corrected. But I do not know if `2.` to `5.` should be fixed or not. I want an opinion on what to do.

Ref neovim/neovim#8462

**Comment by bzoz** [comment]
Im guessing you want to add this: https://github.com/neovim/libuv/commit/d595ef307fc4d8b9232fdd0f9cc5005fd1b1badb? It generally LGTM, maybe some style nits. It would be great if you would fix the issues you found though.

**Comment by erw7** [comment]
I have created a PR(#1884). So I will close this.
