### ISSUE TITLE
uv_fs_realpath doesn't respect DOS and subst mounts

### ISSUE THREAD

**Issue by manuelnp** [libuv/libuv#1877]
As stated in uv_fs_realpath documentation, there is a caveat with subst'd drives in Windows which is now hurting in cmake codebase. Instead of following the same path as Node and coding a custom workaround, I would like to come up with a solution here but I don't know if anybody has this issue in his backlog.

**Comment by bnoordhuis** [comment]
No one is working on that.  What do you propose?

**Comment by manuelnp** [comment]
I don't have a solution yet, but let me dig into the code to look for a generic solution or a special case for handling this particular issue, I would like to avoid rewriting uv_fs_realpath in cmake source code only to handle this.

**Comment by bzoz** [comment]
What issues exactly are you facing?

**Comment by manuelnp** [comment]
Dealing with "Resolved path bypasses subst’d drives." caveat stated [in uv_fs_realpath](http://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_realpath).

libuv was introduced in CMake to handle IO oparations, specifically uv_fs_realpath came to replace an old custom implemantion to resolve real paths which relyed on Windows built-in fstat function.

fstat has an issue by which does not resolve symlinks but it handles subst'd drives properly. On the other hand, uv_fs_realpath (which uses Windows GetFinalPathNameByHandle) resolves properly symlinks but also bypasses subst’d drives.

I hadn't yet the oportunity to spare some time to look into the code but I would like to come up with a solution of some kind, maybe an hybrid implementation betweet fstat and GetFinalPathNameByHandle and/or a precheck for dealing with subst’d drives specifically.

In the worst scenario, where I couldn't/shouldn't change uv_fs_realpath behaviour, adding another interface function with this functionality would be handy.

**Comment by bzoz** [comment]
I remember reverting `uv_fs_realpath` usage in Node. Basically, if any path element is a symlink to a subst'd location  you will get wrong result . I don't think there is any other solution than to check each path element. See discussion here: https://github.com/nodejs/node/pull/7559

I don’t think we can change current `uv_fs_realpath` behavior, at least in v1.x . Some libuv could depend on current implementation. Besides that performance could be an issue.

So, maybe `uv_fs_walkpath`? 

For reference, Node implementation: https://github.com/nodejs/node/blob/master/lib/fs.js#L1356-L1488

**Comment by piscisaureus** [comment]
The downside of walking all individual path components is that it is pretty slow, and it might fail if the user doesn't have list access to some parent directory of the realpath'ed path.

A simpler solution might be to extract the drive letter from the input path, and also realpath the root directory of it, and see if they share common suffix.

In javascript-ish pseudo-code:

```js
function realpath(path) {
  // Resolve path to an absolute path by applying current working directory, but not resolving symlinks.
  var abs_path = get_abs_path(path); 
  // Get drive letter (note: might not have a drive letter at all.)
  var orig_drive_letter = get_drive_letter(path);
  // Resolve symlinks.
  var resolved_path = GetFinalPathName(path);
  // Check if resolved path has a different drive letter.
  if (orig_drive_letter != null && orig_drive_letter !== get_drive_letter(resolved_path)) {
    // Resolve the root directory on the original drive.
    var resolved_root = GetFinalPathName(orig_drive_letter + ":\\");
    // If they share a common prefix, replace the common prefix by the original drive letter.
    if (resolved_path.startsWith(resolved_root)) {
      resolved_path = orig_drive_letter + ":\\" + resolved_path.slice(resolved_root.length);
    }
  }
return resolved.path;
}
```

The only caveat I can think of is that if there is an *absolute* symbolic link or junction in the path and it points somewhere within the directory that subst'ed drive letter points at, resolution would be slightly different. Example:

```
mklink /d c:\foo\link c:\foo\bar
subst d: c:\foo
realpath c:\foo\link\file
# with the strategy above, realpath = d:\bar\file
# resolving each component individually, realpath = c:\foo\bar\file
```

...but that might be desirable too, depending on how you look at it.

For extra credit, resolution of the root-dir can be implemented with NtOpenSymbolicLinkObject/NtQuerySymbolicLinkObject, this sidestepping any actual I/O and access checks on the root dir.
