### ISSUE TITLE
Utilize lock-free queue for worker thread pool

### ISSUE THREAD

**Issue by jnicholls** [libuv/libuv#188]
I think it would be far more efficient to utilize a lock-free queue (e.g. using compare-and-swap) to hand work off to the worker threads rather than using a mutex. Has this even been considered and/or benchmarked against a lock-free queue for applications that are heavily utilizing the worker thread pool for blocking file I/O, etc.?

mirror of https://github.com/joyent/libuv/issues/1598

**Comment by bnoordhuis** [comment]
Atomic operations may be helpful for uv_async_send() (avoiding a system call when the target thread is awake) but workers in the thread pool should suspend when there is no work.  That means you're going to need some kind of synchronizing primitive to sleep on, like the current mutex + condition variable.

A lock-free list may or may not help as a fast path but you'd have to convince me with numbers. :-)

**Comment by jnicholls** [comment]
I'm happy to replace the current list with a lock-free list in a fork and run some benchmarks.  I agree the threads should sleep when not busy; we can still have a wait condition when the queue is empty, but when the queue is not empty the wait condition can be skipped.  The condition can be signaled every time an entry is added to the queue.

I agree this is more for a fast path when the queue is never empty.  For never-ending blocking I/O requests, I am confident (but again am happy to provide results to be certain) CAS would be far more performant than the syscalls on the mutex.  I'll report results soon.

**Comment by saghul** [comment]
Closing as this is not really an issue. Please open a PR if you manage to implement what you proposed and have some numbers to share! :-)
