### ISSUE TITLE
Is it okay I create a pr to add circle ci ?

### ISSUE THREAD

**Issue by gengjiawen** [libuv/libuv#1894]
RT

**Comment by bnoordhuis** [comment]
Thanks but no, we don't use it.

**Comment by gengjiawen** [comment]
Is it okay we add github action ? cc @richardlau @cjihrig

**Comment by cjihrig** [comment]
Do you mean to run the CI, or something else? I'm not opposed to GitHub actions personally (I actually like them a lot), but they won't be able to fully replace Jenkins due to lack of platform support.
