### ISSUE TITLE
stdbool.h is not present on MSVC 9/2008 or 10/2010

### ISSUE THREAD

**Issue by jamadden** [libuv/libuv#1900]
I am trying to update gevent to use libuv 1.21 and the Windows builds for [Python 2.7](https://ci.appveyor.com/project/denik/gevent/build/1.0.1820/job/0uul6tqiayv7gbsh#L753) (which requires MSVC 9) and [Python 3.4](https://ci.appveyor.com/project/denik/gevent/build/1.0.1820/job/jj22l3hsikylm92b#L712) (which requires MSVC 10) failed:

```
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 
    /GS- /DNDEBUG -D_GNU_SOURCE=1 -DWIN32=1
     -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NONSTDC_NO_DEPRECATE=1 -D_CRT_SECURE_NO_WARNINGS=1 
    -D_WIN32_WINNT=0x0600 -DWIN32_LEAN_AND_MEAN=1 
    -IC:\projects\gevent\src\gevent\libuv -IC:\projects\gevent\deps\libuv\include 
    -IC:\projects\gevent\deps\libuv\src -IC:\Python34-x64\include -IC:\Python34-x64\include 
    /Tcdeps\libuv\src\win/pipe.c /Fobuild\temp.win-amd64-3.4\Release\deps\libuv\src\win/pipe.obj
pipe.c
deps\libuv\src\win/pipe.c(24) : fatal error C1083: Cannot open include file: 'stdbool.h':
     No such file or directory
error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```
 The use of `stdbool.h` was added to pipe.c in https://github.com/libuv/libuv/commit/4e53af9120094adefe5db67fbbeda8ebde28a93d ; wikibooks says [it's part of C99](https://en.wikibooks.org/wiki/C_Programming/stdbool.h) and MSDN says it was [only added in MSVC 2013](https://blogs.msdn.microsoft.com/vcblog/2013/07/19/c99-library-support-in-visual-studio-2013/).

The [docs](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md) say that MSVC 2008 is still a supported compiler. Is that meant to be true? It looks like the usage of `bool` is extremely minimal, I could create a PR that removes it?

**Comment by addaleax** [comment]
Is this being fixed by https://github.com/libuv/libuv/pull/1885 ?

**Comment by jamadden** [comment]
Yup, looks like #1885 would fix this. I searched *issues* but not PRs so I didn't see that, my bad.
