### ISSUE TITLE
make `statbuf` field a pointer

### ISSUE THREAD

**Issue by winterland1989** [libuv/libuv#1902]
In my application, i have a memory pool for various `uv_req_t` struct,  I never release them so that i don't have to pay for malloc /free cost. but somehow `uv_fs_t` 's size is much larger (440B) than other request type (~96B). By looking into source i find `uv_state_t statbuf` is kept in `uv_fs_t` instead of a `uv_stat_t*` pointer, and it has many 64bits fields which makes it a very large struct. So why this design choice is made? We only use `statbuf` field for stat related  functions, why don't use a pointer field instead?

**Comment by bnoordhuis** [comment]
Where would the pointer point to when we need to store a `uv_stat_t`?

Libuv's philosophy is to avoid mallocing memory when at all possible.  Avoiding malloc is certainly possible here by embedding the struct, and therefore that is what we do.

**Comment by winterland1989** [comment]
Isn't `uv_req_cleanup` suppose to somewhat a complementary way to manage dynamic memory if needed?

I should state my problem more clearly, since our goal is the same: avoid mallocing memory when at all possible. In my application i have a grow only memory pool with unified size item to make `uv_req_t` 's allocation fast. Thus i have to pre-allocate this array with the largest `uv_req_t` size possible. The problem is 1) `uv_fs_t` is far larger than other request struct , 2) the `uv_stat_t` is seldom used.

From what i understand, static allocation(stack/memory pool) or dynamic allocation is always a trade off, so maybe my use case can make you reconsider this decision?
