### ISSUE TITLE
can you provide a multi thread tcp server  sample?  uv_write2 only works only  with multi processes ? 

### ISSUE THREAD

**Issue by fatihwk** [libuv/libuv#1903]
uv_write2 can't send file handle to pipe between threads? 

I get hints from other posts: 

"There is no way to accept a client on another loop. There are a number of things you can do:
1. create the listener handle, then create X new loops, send the handle to them using uv_write2 and listen in all of them
2. if you're on Linux (> 3.9 IIRC), create X new loops and bind a handle to the same IP and port using SO_REUSEPORT
3. have a single loop accept all incoming connections and send them to other loops using uv_write2." 

but it doesn't figure out it's in multi threads or multi processes.

**Comment by bnoordhuis** [comment]
Can you post questions to libuv/help?  This issue tracker is only for bug reports.  Thanks.
