### ISSUE TITLE
make check fail in Cygwin environment

### ISSUE THREAD

**Issue by dk1013** [libuv/libuv#1906]
* **Version**: 1.21.0
* **Platform**:  Cygwin, gcc v7.3.0
* **Error msg**: 
not ok 170 - poll_oob
\# exit code 134
\# Output from process `poll_oob`:
\# Assertion failed in test/test-poll-oob.c on line 99: n == 4
...
FAIL: test/run-tests.exe
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:4608: check-TESTS] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/***/CLionProjects/uWebSockets/libuv/libuv'
make: *** [Makefile:4865: check-am] Error 2

**Comment by matzeri** [comment]
How you configured libuv ? I just test the 1.22.0 on cygwin and I see not only this but 11 failures in total

**Comment by cjihrig** [comment]
Can anyone comment on the current state of the test suite on Cygwin?

**Comment by matzeri** [comment]
The current 1.30.1 tests do not build as uv_get_constrained_memory is missing a definition...

make[1]: Entering directory '/cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/build'
  CCLD     test/run-tests.exe
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: test/test_run_tests-test-get-memory.o: in function `run_test_get_memory':
/usr/src/debug/libuv-1.30.0-1/test/test-get-memory.c:28: undefined reference to `uv_get_constrained_memory'

**Comment by cjihrig** [comment]
@matzeri thanks for reporting that. Can you give https://github.com/libuv/libuv/pull/2361 a shot? I don't have any way to test it.

**Comment by matzeri** [comment]
with that the tests are feasible and 

$ grep "not ok" libuv-1.30.0-1-check.log
not ok 9 - barrier_serial_thread
not ok 27 - dlerror
not ok 87 - fs_read_bufs
not ok 105 - fs_utime
not ok 138 - ipc_closed_handle
not ok 188 - poll_oob
not ok 326 - udp_connect

**Comment by cjihrig** [comment]
Thanks. I'll leave this issue open since it appears that there are still issues with the test suite on Cygwin. Unfortunately, I think we have to wait for someone using Cygwin to work on the failures.

**Comment by matzeri** [comment]
Is it possible to test one at time ? It will help to trace and understand where the problems are.

**Comment by cjihrig** [comment]
> Is it possible to test one at time ?

Yes: `./test/run-tests <test_name>` where `<test_name>` would be `barrier_serial_thread`, etc. You can also run the test in the foreground: `./test/run-tests <test_name> <test_name>`.

I see that you ran `grep` on a log file. I think the failing tests should have additional output if they actually print anything.

**Comment by matzeri** [comment]
Most are failed assertions

$ ./test/run-tests.exe barrier_serial_thread
not ok 1 - barrier_serial_thread
# exit code 134
# Output from process `barrier_serial_thread`: (no output)
$ ./test/run-tests.exe barrier_serial_thread
not ok 1 - barrier_serial_thread
# exit code 134
# Output from process `barrier_serial_thread`: (no output)

not ok 1 - dlerror
# exit code 134
# Output from process `dlerror`:
# Assertion failed in /cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/src/libuv-1.30.0/test/test-dlerror.c on line 45: strstr(msg, path) != NULL

$ ./test/run-tests.exe fs_read_bufs
not ok 1 - fs_read_bufs
# exit code 134
# Output from process `fs_read_bufs`:
# Assertion failed in /cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/src/libuv-1.30.0/test/test-fs.c on line 2730: 0 <= uv_fs_open(NULL, &open_req1, "test/fixtures/lorem_ipsum.txt", O_RDONLY, 0, NULL)

$ ./test/run-tests.exe fs_utime
not ok 1 - fs_utime
# exit code 134
# Output from process `fs_utime`:
# Assertion failed in /cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/src/libuv-1.30.0/test/test-fs.c on line 2310: r == 0

$ ./test/run-tests.exe ipc_closed_handle
not ok 1 - ipc_closed_handle
# timeout
# Output from process `ipc_closed_handle`:
# Assertion failed in /cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/src/libuv-1.30.0/test/test-ipc.c on line 865: r == 0
# exit_cb
# Assertion failed in /cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/src/libuv-1.30.0/test/test-ipc.c on line 106: term_signal == 0

 $ ./test/run-tests.exe poll_oob
not ok 1 - poll_oob
# exit code 134
# Output from process `poll_oob`:
# Assertion failed in /cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/src/libuv-1.30.0/test/test-poll-oob.c on line 99: n == 4

$ ./test/run-tests.exe udp_connect
not ok 1 - udp_connect
# exit code 134
# Output from process `udp_connect`:
# Assertion failed in /cygdrive/d/cyg_pub/devel/libuv/libuv-1.30.0-1.x86_64/src/libuv-1.30.0/test/test-udp-connect.c on line 150: r == UV_ENOTCONN

**Comment by cjihrig** [comment]
Yea, it looks like none of those tests print any helpful debugging information. If you want to try to debug things, you can add `printf`s  wherever you think is helpful. Anything you log will show up under the `# Output from process` lines.

**Comment by matzeri** [comment]
I have a major problem in debugging libuv under Cygwin as the breakpoints seem ineffective.
https://cygwin.com/ml/cygwin/2019-12/msg00303.html

trying to debug dlerror
`# Assertion failed in ../libuv-1.34.0/test/test-dlerror.c on line 45: strstr(msg, path) != NULL`

I added a printf just before the code
```
  msg = uv_dlerror(&lib);
  /* added as break does not work */
  printf("DEBUG msg=%s, path=%s, dlerror_no_error=%s \n", msg,path,dlerror_no_error);

  ASSERT(msg != NULL);
  ASSERT(strstr(msg, path) != NULL);
  ASSERT(strstr(msg, dlerror_no_error) == NULL);
```
and the output is

`# DEBUG msg=Permission denied, path=test/fixtures/load_error.node, dlerror_no_error=no error`

no clue why the Permission is denied as
```

$ ls -l  test/fixtures/load_error.node
lrwxrwxrwx 1 Marco Kein 51 Dec 29 07:46 test/fixtures/load_error.node -> ../../../libuv-1.34.0/test/fixtures/load_error.node
$ cat   test/fixtures/load_error.node
foobar

```
