### ISSUE TITLE
#1826 broke ABI compat without SONAME bump

### ISSUE THREAD

**Issue by fsateler** [libuv/libuv#1908]
* **Version**: 1.21
* **Platform**: Linux  4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux

https://github.com/libuv/libuv/pull/1826 broke ABI compat by adding an enum member in the middle. This causes any binary using UV_FS_REALPATH or UV_FS_COPYFILE to become broken, as the values now point to UV_FS_LCHOWN and UV_FS_REALPATH, respectively.

This needs either a soname bump, or moving the enum back to the end.

This appears to be the root case behind https://github.com/yarnpkg/yarn/issues/6043

**Comment by santigimeno** [comment]
I think moving the enum to the end would be a good idea. Would you open a PR with the change?

**Comment by cjihrig** [comment]
Apologies for not catching this while reviewing #1826. I can make a patch release anytime if you want to send a PR.

**Comment by cjihrig** [comment]
Yes: https://github.com/libuv/libuv/issues/1914

**Comment by fsateler** [comment]
Thank you all very much for the quick fix! Very much appreciated

Saludos,
Felipe Sateler
