### ISSUE TITLE
`uv_cond_wait_helper' linker error

### ISSUE THREAD

**Issue by strrchr** [libuv/libuv#191]
libuv/src/win/thread.c:664: undefined reference to `uv_cond_wait_helper'

I compiled libuv as a static library using MinGW on Windows 7.

I think uv_cond_wait_helper should not be declared inline, because it is too big.
When I remove the inline keyword from it, the linking process is OK.

**Comment by bnoordhuis** [comment]
Fixed by 454688d.

**Comment by Keno** [comment]
Just for the reference of anybody looking at this later, adding `static` on that line fixes the immediate compilation failure as well.
