### ISSUE TITLE
Failures on OSX 12

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#1910]
* **Version**: 1.x
* **Platform**: osx 12

Failure when trying to add osx12 to the test matrix:
https://ci.nodejs.org/view/All/job/libuv-test-commit-osx/959/nodes=osx1012/

Not sure if they are real failures or something to do with the machine.

```
not ok 16 - condvar_3
# exit code 6
# Output from process `condvar_3`:
# Assertion failed in ../test/test-condvar.c on line 161: 0 == wc.wait_cond(&wc, &wc.posted_1)
ok 17 - condvar_4

not ok 49 - fs_event_error_reporting
# timeout
# Output from process `fs_event_error_reporting`: (no output)

not ok 116 - hrtime
# exit code 6
# Output from process `hrtime`:
# Assertion failed in ../test/test-hrtime.c on line 50: diff < (uint64_t) 80 * NANOSEC / MILLISEC
```

**Comment by cjihrig** [comment]
@mhdawson what is the status of adding this to the CI? Has it been put on hold?

**Comment by refack** [comment]
Similar three (https://ci.nodejs.org/view/All/job/libuv-test-commit-osx/984/nodes=osx1012/)
18 and 115 seem timing related.
48 seems FS related, which is not surprising.
```
not ok 18 - condvar_5
# exit code 6
# Output from process `condvar_5`:
# Assertion failed in ../test/test-condvar.c on line 262: elapsed <= 1.5 * timeout

not ok 48 - fs_event_error_reporting
# timeout
# Output from process `fs_event_error_reporting`: (no output)

not ok 115 - hrtime
# exit code 6
# Output from process `hrtime`:
# Assertion failed in ../test/test-hrtime.c on line 50: diff < (uint64_t) 80 * NANOSEC / MILLISEC
```

P.S. The node test suite does not hit these edge cases...

**Comment by mhdawson** [comment]
@cjihrig I did not add it to the CI to avoid making it consistently red.  1010 and 1011 are in, we can enable 1012 any time we are ready.

**Comment by copumpkin** [comment]
FWIW, I'm getting `condvar_5` failures on macOS 10.13 too

**Comment by davisjam** [comment]
@copumpkin What is the assert for `condvar_5`?

**Comment by copumpkin** [comment]
Are you asking which assert fails? It's this one:

```
  ASSERT(elapsed <= 1.5 * timeout); /* 1.1 too small for OSX. */
```

I haven't added any instrumentation yet to figure out what the `actual` elapsed was though. Happens fairly consistently for me though; not sure if it's a real issue or if my machine is just under heavy load.

**Comment by davisjam** [comment]
@copumpkin If you could let me know what `elapsed` and `timeout` are, that would be swell.

**Comment by copumpkin** [comment]
I'll see if I can track it down, gimme a bit 😄

**Comment by copumpkin** [comment]
And now it seems to be passing consistently again... not exactly reassuring 😕

**Comment by copumpkin** [comment]
Got it to fail:

```
elapsed = 173798319
timeout = 100000000
```

**Comment by davisjam** [comment]
@copumpkin Take a look [at this PR](https://github.com/libuv/libuv/pull/1990).

**Comment by mhdawson** [comment]
Tried to re-enable 12 for libuv testing today but there are 2 failures:

https://ci.nodejs.org/view/libuv/job/libuv-test-commit-osx/1039/nodes=osx1012/console

```
not ok 115 - hrtime
# exit code 6
# Output from process `hrtime`:
# Assertion failed in ../test/test-hrtime.c on line 50: diff < (uint64_t) 80 * NANOSEC / MILLISEC

not ok 48 - fs_event_error_reporting
# timeout
# Output from process `fs_event_error_reporting`: (no output)
```

**Comment by mhdawson** [comment]
So seems like the condvar one is resolved, but the other 2 are still there.

**Comment by davisjam** [comment]
Sounds like `115 - hrtime` may also be a time-based issue like condvar was.

**Comment by mhdawson** [comment]
Yes, created job to make that easier :)

**Comment by mhdawson** [comment]
If you are going to need a lot of runs we can also ask to get you temporary access to be able to kick off jobs if you can't do that now.

**Comment by davisjam** [comment]
I opened #1998 to try to figure out what's happening in `fs_event_error_reporting`.

**Comment by davisjam** [comment]
> If you are going to need a lot of runs we can also ask to get you temporary access to be able to kick off jobs if you can't do that now.

I have the ability to start Node.js builds on Jenkins.
It does not look like I have the power to start libuv jobs.
I would be delighted to acquire this power.
