### ISSUE TITLE
Error when run make check

### ISSUE THREAD

**Issue by trungkstn** [libuv/libuv#1917]
* **Version**: 1.21.0 
* **Platform**: UNIX
ok 333 - we_get_signals
ok 334 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:4622: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/trungtq/Downloads/libuv-1.21.0'
Makefile:4878: recipe for target 'check-am' failed
make: *** [check-am] Error 2

What did i get error? How to fix it?

Thank :)

**Comment by santigimeno** [comment]
@trungkstn can you paste the full output somewhere so we find out what test is failing? Thanks!

**Comment by trungkstn** [comment]
```
not ok 103 - getaddrinfo_fail
# exit code 134
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
not ok 104 - getaddrinfo_fail_sync
# exit code 134
# Output from process `getaddrinfo_fail_sync`:
# Assertion failed in test/test-getaddrinfo.c on line 117: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy.", NULL, NULL)
```
this is error. help me :(
