### ISSUE TITLE
[BUG] A lot of debugging symbols in the release mode

### ISSUE THREAD

**Issue by michal037** [libuv/libuv#1924]
* **Version**: 1.22.0
* **Platform**: MinGW (Tier 3) | Probably all platforms!

**In both attempts I set the release mode.**
Both GYP and Autotools, have badly configured flags for the release mode.
I could not check CMake, because it does not work for me.

GYP uses flags: `-g -O3 -DNDEBUG`
Autotools uses flags: `-g -O2` without `-DNDEBUG`

Do not use this configuration in the release!
Please set `-DNDEBUG` flag for Autotools and remove both `-g` flags, or use `strip --strip-debug libuv.a`.

Read this: [Options for debugging your program](https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html)
```
To tell GCC to emit extra information for use by a debugger, in almost all cases you need only to add -g to your other options.

GCC allows you to use -g with -O. The shortcuts taken by optimized code may occasionally be surprising: some variables you declared may not exist at all; flow of control may briefly move where you did not expect it; some statements may not be executed because they compute constant results or their values are already at hand; some statements may execute in different places because they have been moved out of loops. Nevertheless it is possible to debug optimized output. This makes it reasonable to use the optimizer for programs that might have bugs.

If you are not using some other optimization option, consider using -Og (see Optimize Options) with -g. With no -O option at all, some compiler passes that collect information useful for debugging do not run at all, so that -Og may result in a better debugging experience.
```

---

### GYP
_C:\Programy\msys2\home\Michal\libuv-gyp\out\Release\.deps\out\Release\obj.target\libuv\src\version.o.d_
```
cmd_out/Release/obj.target/libuv/src/version.o := cc '-DWIN32' '-D_CRT_SECURE_NO_DEPRECATE' '-D_CRT_NONSTDC_NO_DEPRECATE' '-D_WIN32_WINNT=0x0600' '-D_GNU_SOURCE' '-DNDEBUG' -Iinclude -Isrc  -fvisibility=hidden -g --std=gnu89 -pedantic -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections  -MMD -MF out/Release/.deps/out/Release/obj.target/libuv/src/version.o.d.raw   -c -o out/Release/obj.target/libuv/src/version.o src/version.c
out/Release/obj.target/libuv/src/version.o: src/version.c include/uv.h \
 include/uv/errno.h include/uv/version.h include/uv/win.h \
 include/uv/tree.h include/uv/threadpool.h
src/version.c:
include/uv.h:
include/uv/errno.h:
include/uv/version.h:
include/uv/win.h:
include/uv/tree.h:
include/uv/threadpool.h:
```

### Autotools
_C:\Programy\msys2\home\Michal\libuv-autotools\Makefile_
```
CFLAGS = -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes
libuv_la_CFLAGS = -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes $(am__append_1) $(am__append_14) \
```

## Sources
[1] https://groups.google.com/forum/?hl=pl#!topic/wren-lang/LgzckCW3HVE

**Comment by genio** [comment]
CMake will work for Windows with MinGW: https://github.com/genio/Alien-libuv/blob/cmake/alienfile#L101-L129

We're doing that to build LibUV for Perl 5 on Windows, using MinGW and gmake.

**Comment by michal037** [comment]
@genio

LibUV compiled with mingw has bugs. Check the tests!
Mingw destroy the correct functionality of some functions.
I recommend you to use a Microsoft compiler.

**Comment by genio** [comment]
Can’t in this situation.

**Comment by michal037** [comment]
I am very happy! In that case, I'm interested in it.
