### ISSUE TITLE
some compiler errors when -O2: MinGW, libuv-v1.4.0, Windows 7

### ISSUE THREAD

**Issue by strrchr** [libuv/libuv#193]
libuv/src/win/fs.c:208:5: error: 'path_len' may be used uninitialized in this function [-Werror=maybe-uninitialized]

libuv/src/win/tty.c:199:8: error: 'flags' may be used uninitialized in this function [-Werror=maybe-uninitialized]

**Comment by bnoordhuis** [comment]
I checked and they look to be false positives.  A compiler bug, in other words, not a libuv bug.

**Comment by saghul** [comment]
Closing then, as it's not an issue.
