### ISSUE TITLE
Messaging and decisions regarding 2.0

### ISSUE THREAD

**Issue by gabrielschulhof** [libuv/libuv#1931]
Here's me trying to summarize a discussion we've just had at Node Summit:

Messaging:
- On the N-API side, emphasize in our talks that usage of any part of Node.js other than N-API voids our ABI stability promise.
- On the libuv side, be explicit about what will break, so module maintainers can count their modules in our out of the things that will break, and potentially
  - commit after 2.0.0 to ABI stability

Potential ways forward:
- Cover more of libuv with N-API
  - It makes no sense to cover things one-to-one, because that's just another indirection. If not though, then what usage patterns shall we cover? This requires API design.
- Promise ABI stability before 2.0.0

Most importantly, we need to decide which solutions to not pursue, so we may concentrate on the solutions we should pursue. Now is the perfect time to get this conversation going (again).

@nodejs/collaborators please chime in, because I'm certain I left out many perspectives we discussed.

**Comment by addaleax** [comment]
I’d love it if libuv could promise somewhat permanent ABI stability for functions.

Doing it for object layout seems unrealistic, but I think that since 0d6525acae3b9 a lot of the reliance on struct layout is gone (or at least that was the intention behind it). Maybe we could go through the API and see which public fields for the individual classes should have getters/setters?

**Comment by gireeshpunathil** [comment]
I missed the conversation, but here are my thoughts:

 - committing ABI stability indefenitely can potentially cripple developmental evolution
 - Ideally I would wish libuv to focus on performance and platform abstraction and let consuming code to adapt to that
 - On the other hand, the main use case for N-API being ABI stability, I acknowledge the concern
 - So following how Node keeps itself up with libuv, I guess wrapping (libuv) APIs with N-API looks to be a practical path to me

**Comment by addaleax** [comment]
@gireeshpunathil Providing ABI stability for C libraries is generally not nearly as hard as it is for C++ libraries, so I don’t think it’s entirely fair to compare this to Node/V8.

This is especially true if the API is mostly function-based and one accepts that sometimes that means introducing a newer variant of the same API.

**Comment by gabrielschulhof** [comment]
FWIW I have created a [chart](https://docs.google.com/spreadsheets/d/1fYy_DqkOeBElpVGOC_a1TlyWC0rc2C-J-YL3nwpIE8Q/edit#gid=0) showing which are the most-used libuv APIs among npm packages. There's a 
[dump](https://github.com/libuv/libuv/files/2236338/addons.sqlite.dump.txt) of the data from which the chart was created.

![libuv-usage](https://user-images.githubusercontent.com/976081/43330436-345690a0-9191-11e8-889f-f83bb97b20b0.png)

The data was created as follows:
1. google site:github.com binding.gyp 
2. Use FF regex find plugin on each page: `https://github.com/[^/]*/[^/]*/`
3. For each repo found, do:
    ```
    REPO=$1
    echo $REPO
    git clone $REPO tmp > /dev/null 2>&1 &&
    cd tmp &&
    git grep -nH '\buv_' \
        | sed -r 's/(\buv_[^ ]*)/\n\1\n/g' \
        | grep '^uv_' \
        | sed 's/[(].*$//' \| sed 's/[.)*;]//g' \
        | sort -u \
        | grep '_t$' \
        | while read; do echo "${REPO} ${REPLY}"; done &&
    cd .. &&
    rm -rf tmp
    ```
4. For each repo found:
    ```
    git clone ${REPO} tmp && \
    echo -n ${REPO} "" && \
    node -e 'let x; try { x = require("./tmp/package.json"); } catch(something) {x = {};} console.log(x.name || "");'
    ```
5. For each package name found, open its npm page and, if found, record the dependents
6. Store in a sqlite db the following tables:
  * project -> APIs used
  * project -> npm name
  * npm name -> dependents
7. sum dependents and group by APIs used

**Comment by gireeshpunathil** [comment]
@gabrielschulhof - awesome work, and great to see the numbers. Discussions easily converge when we have data at hand!

@addaleax - thanks, and I agree about functions serving as APIs can hide everything beneath it while allowing major changes without disturbing consumers.

so given the data and its revelation: large (~10K range) number of structure access from consumers, are we looking / aiming at:
 - request libuv to wrap everything under getter / setters
 - request libuv to ensure stability on APIs including getter / setters
 - or both
 - discourage modules from accessing public structures directly
?

**Comment by saghul** [comment]
> Promise ABI stability before 2.0.0

This is already the case for the v1.x series (modulo involuntary mistakes). Do you mean, having 2.0.0 ABI compatible with v1.x ?

v2 was always seen as the opportunity to break the ABI and remove cruft. In fact if you look at master I did some of that a couple of years ago already. So they are not ABI compatible as it stands.

I'd be -1 to making that promise. I think it would tie our hands too much IMHO. c-ares had this policy (not sure if they still do) and it made impossible to add new features at some point, without resorting to hacks.

In the end that would just add up to the tech debt and eventually make the project not that enticing for potential future contributors.


My 2 cents.

**Comment by saghul** [comment]
It's not only about APIs, but also about structure layout.

**Comment by addaleax** [comment]
@saghul What I’d be looking for is ABI/API compatibility from v1.x, but only as far as functions are concerned, not struct layout. That the latter changes over time is very much to be expected, imo :)

**Comment by mhdawson** [comment]
@gabrielschulhof from your data is it possible to call which ones people can already avoid using with the APIs we provide in N-API, versus those for which those are no options ?

**Comment by saghul** [comment]
@addaleax Even then, I'd disagree. There is an open PR which renames `uv_idle_t` to `uv_spin_t`. Making that promise would mean we cannot land it. Ever. And I would very much want to have it landed because `uv_idle_t` is a constant source of confusion, due to its name.

So I'd say it's N-APIs responsibility to make those promises, not those of downstream libraries such as libuv.

Following a reasonably common practice for C libraries we have not bumped the major (and SONAME) because the ABI has not been broken, but the whole point of v2 was (I can't say if this has changed, because alas I haven't been able to be as active as I was in the past year) to make those changes.

Ping @libuv/core

**Comment by saghul** [comment]
@seishun Youc an choose to believe me or not, the email archives are public. Last I checked [this patch](https://c-ares.haxx.se/mail/c-ares-archive-2013-07/0005.shtml) couldn't be incorporated because it broke the ABI. Also @indutny had to jump though a few hoops because of this, when adding support the parsing multiple chunks in TXT replies.

I'm not making this up.

**Comment by indutny** [comment]
Locking ABI of a library is a really bad idea that results in terrible hacks (as @saghul just mentioned). I'd rather not do it. If there needs to be a separate compatibility layer, then I don't mind it if it'll try to cover up for the differences.

Libuv lets users allocate their handles and other objects. Regardless of having API for getters/setters, the allocation would still not be ABI compatible.

**Comment by addaleax** [comment]
> Making that promise would mean we cannot land it. Ever.

@saghul You can always keep aliases around. I realize that that comes with some overhead, but generally, it’s doable and not all that expensive, especially if you do keep the liberty to change struct layouts (as your linked c-ares patch does).

And even in the most extreme case of abandoning a function completely, there’s usually still the option of returning `UV_ENOSYS`, right?

> Libuv lets users allocate their handles and other objects. Regardless of having API for getters/setters, the allocation would still not be ABI compatible. 

Again, that’s not a concern here (imo) – there are APIs to provide the required allocation size for libuv objects at runtime.

**Comment by saghul** [comment]
> You can always keep aliases around. I realize that that comes with some overhead, but generally, it’s doable and not all that expensive,

We can try to do this, but I'm on the fence because, as I said before, v2 was the opportunity to cleanup a bunch of things, and we'd be unable to do that. Say we want to add a `length` parameter to `uv_pipe_bind|connect` so it works with abstract sockets. We'll end up with a bunch of `uv_xxx_ex` or `uv_xxx2` functions with no clear path for their removal.

I don't see why thsi cannot be part of N-API itself.

> And even in the most extreme case of abandoning a function completely, there’s usually still the option of returning UV_ENOSYS, right?

Same, N-API could do this.

Side question: what is the current approach with other libraries such as OpenSSL or c-ares?

**Comment by gabrielschulhof** [comment]
From https://wiki.openssl.org/index.php/ABI_Tracker it looks like they break ABI with every minor version, and backwards compatibility isn't 100% even from one micro version to the next.

**Comment by gabrielschulhof** [comment]
Aside: [Looks like](https://wiki.openssl.org/index.php/Binary_Compatibility) OpenSSL some fairly systematic way of checking ABI integrity.

**Comment by mhdawson** [comment]
@saghul the discussion around wrapping/not wrapping with N-API has generally been about coverage. I think it makes sense if a smaller portion of the libuv surface area needs to be exposed but much less so if is just a wrapper around all of it.  So far we've exposed some portion wrapped in N-API methods so part of the discussion is related to how much of the libuv functionality should be available to add-ons.

**Comment by gabrielschulhof** [comment]
@mhdawson with the biggest hitter, node-sass, it seems fairly straight-forward to convert to `napi_create_async_work` - they [use](https://github.com/sass/node-sass/blob/napi/src/sass_context_wrapper.cpp) precisely `uv_work_t` and `uv_async_t` - both on master, and on the napi branch.

**Comment by gabrielschulhof** [comment]
fsevents looks like a perfect fit for `napi_threadsafe_function`.

**Comment by gabrielschulhof** [comment]
sqlite3 also looks like it will work with `napi_threadsafe_function`.

**Comment by mhdawson** [comment]
@gabrielschulhof when you say biggest hitter, I'm guessing you mean the most used/downloaded module ?

**Comment by gabrielschulhof** [comment]
@mhdawson yes, sorry, I meant the project with the most dependents that uses the most-used libuv API - `uv_async_t`.

**Comment by mhdawson** [comment]
I'm hoping our port of sqlite3, already using napi_create_async_work.

**Comment by cjihrig** [comment]
Closing after 9 months of inactivity. v2 doesn't seem to be happening anytime soon.
