### ISSUE TITLE
A lot of errors during the test [libuv-1.22.0; vs2017]

### ISSUE THREAD

**Issue by michal037** [libuv/libuv#1932]
* **Version**: 1.22.0
* **System**: Windows 10 [64-bits]
* **Platform**: Windows [Visual Studio 2017]

I meet the requirements: `README.md > Build Instructions > Windows > Prerequisites`
Everything is in the log file: [libuv-1.22.0.log](https://github.com/libuv/libuv/files/2239238/libuv-1.22.0.log)

Error summary:
```
not ok 24  - dlerror
not ok 35  - fs_copyfile
not ok 47  - fs_event_watch_dir_short_path
not ok 52  - fs_event_watch_file_twice
not ok 80  - fs_scandir_file
not ok 146 - pipe_connect_to_file
not ok 162 - poll_bad_fdtype
```

**Comment by bzoz** [comment]
This should not happen. Is the E drive maybe special (subst)? What is your exact Windows version? Do the tests fail every time you run them? Does plain `vcbuild test` produce different output?

**Comment by bzoz** [comment]
Ok, I was able to reproduce the failures if I chdir to the `test\Release` folder. Can you test if running tests from `E:\workspace\libuv-1.22.0` works?

**Comment by michal037** [comment]
@bzoz 

1. **Is the E drive maybe special (subst)?**

No, my `E:\` is a regular NTFS data disk mounted to the motherboard.

2. **What is your exact Windows version?**

The result of the systeminfo.exe program: [systeminfo.log](https://github.com/libuv/libuv/files/2257408/systeminfo.log)


3. **Do the tests fail every time you run them?**

Yes, for everyone.

4. **Does plain `vcbuild test` produce different output?** **Can you test if running tests from `E:\workspace\libuv-1.22.0` works?**

I can not check the answers for you to these questions at this moment. I uninstalled VS2017. I needed the LibUV library to compile a program that I just wanted to test. Since I encountered errors in LibUV, I took care of something else. Precisely learning Java language. I only needed VS2017 to compile only one program, so I uninstalled it later. If these tests are very important to you, I can install VS2017 and perform them.

**Comment by matzeri** [comment]
Some of these failures are also visible on Cygwin

not ok 25 - dlerror
not ok 45 - fs_copyfile
not ok 84 - fs_scandir_file
not ok 102 - getaddrinfo_fail
not ok 103 - getaddrinfo_fail_sync
not ok 148 - pipe_connect_to_file
not ok 169 - poll_oob

**Comment by bnoordhuis** [comment]
@bzoz Is there anything actionable here?

**Comment by bzoz** [comment]
We can fix this by making the runner change cwd to the root of libuv sources. I'll try to give it a shot this week
