### ISSUE TITLE
infinite loop in uv_loop_close()

### ISSUE THREAD

**Issue by 1st1** [libuv/libuv#1933]
* **Version**: v1.20.3
* **Platform**: MacOS 10.13.5

**Update:** See https://github.com/libuv/libuv/issues/1933#issuecomment-409769018

------------

While working on fixing https://github.com/MagicStack/uvloop/issues/185 bug in uvloop, I encountered a problem: I can't write a regression test because `uv_loop_close()` hits an infinite loop.

The original issue is that uvloop didn't close FDs it opened prior to calling `uv_spawn()` when the call failed.  This is a bug in uvloop that I'll fix.  Writing a regression test for this bug revealed that `uv_loop_close()` loops forever in this loop:

```c
  QUEUE_FOREACH(q, &loop->handle_queue) {
    h = QUEUE_DATA(q, uv_handle_t, handle_queue);
    if (!(h->flags & UV__HANDLE_INTERNAL))
      return UV_EBUSY;
  }
```

Adding a `printf("%p\n", h);` revealed that the loop iterates over the same handle.  The handle appears to be in a broken state, but it's one of `uv_process_t` handles that uvloop allocates for `uv_spawn`.

Here's Python code that I use to reproduce the broken `uv_loop_close()` behaviour:

```python
import asyncio
import subprocess
import uvloop

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

async def main(n):
    for i in range(n):
        try:
            # call `ls1111` command to fail with UV_ENOENT
            await asyncio.create_subprocess_exec(
                'ls1111 ', stdout=subprocess.DEVNULL, loop=loop)
        except FileNotFoundError:
            print(i)
            pass
        await asyncio.sleep(0, loop=loop)

loop = asyncio.get_event_loop()
loop.run_until_complete(main(10))
loop.run_until_complete(main(10))
print('before close')
loop.close()
print('after close')
```

(usually takes 5-10 runs to fail)

I'm trying to write a unittest in C to reproduce this but so far I can't find how to trigger this.  Any suggestions how to debug this further?

**Comment by 1st1** [comment]
I only get infinite loops on debug builds of Python though.  On production builds I usually get SIGSEGV, which suggests that libuv's loop somehow keeps a reference to a deallocated `uv_process_t` handle.

**Comment by cjihrig** [comment]
Is this related to #551?

**Comment by 1st1** [comment]
Yeah, seems to the same issue.

FWIW, it seems that `uv_close()` after `uv_spawn()` w/ error works OK.  But this is undocumented and it feels that it should be fixed in libuv.

**Comment by 1st1** [comment]
Calling `uv_close()` manually did help, although this should be either documented or fixed in libuv. Feel free to close this issue if #551 is enough to track it.

**Comment by cjihrig** [comment]
I meant if you build libuv with the linked commit, does it fix the issue you were encountering? It closes the handle on error, instead of requiring you to close it manually.

**Comment by 1st1** [comment]
The patch as is doesn't work for me :(

Looks like in addition to calling `uv_process_close()` on error, we also need to add the following:

```C
  uv__process_close(process);

  process->flags |= UV_HANDLE_CLOSED;
  uv__handle_unref(process);
  QUEUE_REMOVE(&process->handle_queue);

  return err;
```

Without the above additional code, the semi-broken process handle is still visible to `uv_walk()`; freeing the handle right after failed `uv_spawn()` seems to be a bad idea too.

**Comment by cjihrig** [comment]
Another alternative instead of calling `uv__process_close(process)` (and the extra code you listed) would be to just call `uv_close((uv_handle_t*) process, NULL)`.

Whatever we decide, I think we need to explicitly document what is expected of the user in the error case. If we close the handle for them, and they call `uv_close()` in their own code, they'll hit an abort.

**Comment by vtjnash** [comment]
seems like stalebot was a bit too eager there
