### ISSUE TITLE
[PSA] platform refresh in the CI cluster

### ISSUE THREAD

**Issue by refack** [libuv/libuv#1935]
The Build WG is looking for feedback regarding support for EOL platforms and 32 linux (https://github.com/nodejs/build/issues/885#issuecomment-409362796)
The Build WG is considering retiring the 32bit linux workers when node8 goes EOL (December 2019). Specifically we have a problem with centos5-32 since our sponsored cloud providers do not offer those images anymore.
We currently run the libuv CI on these old/32bit platforms, and at some point we might have to retire those as well:
* centos5-64 (GCC4.8 & GCC4.1)
* ubuntu1204-64
* ubuntu1404 (32 & 64 with both automake and GYP)

**Comment by cjihrig** [comment]
@refack is this still an issue, or can it be closed?
