### ISSUE TITLE
Feature proposal: add `uv_listen_stop()`

### ISSUE THREAD

**Issue by 1st1** [libuv/libuv#1937]
We are considering to add new API to Python asyncio to make servers only accept a certain number of connections. Naturally I decided to see if we can implement that in [uvloop](https://github.com/MagicStack/uvloop) too (it's built on top of libuv) and it looks like there's no way to stop a `uv_stream` from listening.

Would it be possible to add a function for `uv_stream` to cancel listening: `int uv_listen_stop(uv_stream_t*)`?  If everybody is OK with the idea I can work on a PR.

**Comment by santigimeno** [comment]
@1st1 what would `uv_listen_stop()` really do?
1) Just close the server socket? I guess `uv_close()` would work for this.
2) Close the new incoming connections just after being accepted? This logic could be implemented in the `uv_connection_cb`, right?

**Comment by 1st1** [comment]
For (1) I can always just call `uv_close`.  (2) I can implement myself with the existing APIs.

Whan I want `uv_listen_stop()` to do is to remove the server socket from epoll/kqueue/etc, so that libuv doesn't accept new connections on this socket **at all**. If at later time I want to resume accepting I can call `uv_listen()`.

**Comment by santigimeno** [comment]
But wouldn't this cause that incoming connections would we indeed established from the client POV but enqueued in the kernel of the server (depending on the backlog value) until they are accepted? Would this behavior be desirable?

**Comment by 1st1** [comment]
Right, I've just checked with various docs and it seems that it's not possible (at least on Linux/Unix) to set the backlog to 0. So even if we stop accepting new connections and call `listen(1)` it's still not possible to make the kernel to reject all new connections for us *reliably*.

That said I still think that there's some value in this new API.  With it we can keep the server socket open, but, during crunch time, let the kernel use the backlog and potentially reject new connections, which is more efficient than accepting and closing connections at the application level.  While the QoS might be suboptimal for some new clients, the server won't waste CPU cycles rejecting them manually.

We need this in EdgeDB (uses uvloop) to have a limit for a maximum number of DB connections.

Here's additional context:

* https://github.com/python/asyncio/pull/448 -- the original PR that explains the motivation to add `pause_server()` method to asyncio server objects

* https://bugs.python.org/issue33840 -- a feature request from Instagram engineers

**Comment by awiddersheim** [comment]
Sorry to bump this but I recently became interested in a similar feature which obviously brought me here but also found a few mailing list items from a few years ago that I though might be helpful in adding more context.

https://groups.google.com/d/msg/libuv/irHB6Agnulw/KfCtaey3mewJ
https://groups.google.com/d/msg/libuv/ZlRxNB6Ql2U/oZz59PJXaZEJ
https://groups.google.com/d/topic/libuv/LYW_5eILaVk/discussion

So this feature has been something people have wanted for a few years and a lot of the proposed solutions and API implementations details match pretty closely with what @1st1 has suggested here.

@1st1 Have you managed to implement something already? Anything I can help with? I'm sure you can whip up something much faster than I can but let me know.

**Comment by 1st1** [comment]
Hi @awiddersheim, no, I didn't have time to implement this, unfortunately.  I still think that the this is a valid use case and ideally libuv should have this though.

**Comment by awiddersheim** [comment]
@1st1 I agree. Would be nice to have a mechanism to create backpressure built-in. To be clear, this isn't on your radar to do any time soon? If not I _may_ try and take a stab at it as long as no one else wants to and it'll be accepted. @bnoordhuis Looking at the mailing list posts I added, seems that you have some opinions about doing this as well and seem to be a current maintainer. Any opinions on the matter?

**Comment by bnoordhuis** [comment]
@awiddersheim I'd say we're open to pull requests assuming the details can be hashed out. It's been covered in the mailing list posts that you linked to but it probably wouldn't hurt to review one more time.

* I think for libuv v2 (if/when it happens) our preferred approach is still request-based: queue up one or more `uv_accept_t` requests. No lined up request == stop accepting new connections.

* For v1.x, the request-based approach is hard or impossible to retrofit so a kind of `uv_listen_stop()` would have to be devised.

I _think_ for deactivation it would suffice to simply remove the listen fd from the pollset and optionally (?) call `listen(fd, 0)` to shrink the accept queue.

**Comment by 1st1** [comment]
I don't think this should be closed.
