### ISSUE TITLE
Consider updating CMake build target usage requirements

### ISSUE THREAD

**Issue by tusharpm** [libuv/libuv#1938]
* **Version**: 1.22.0
* **Platform**: unix, Darwin

Please consider making the `include` directory `PUBLIC` to allow using libuv targets in other projects. I tried the change in 90723966262e42d54d4e0eac148844a3d4f987b1. The tests passed on my machine.

Another example is the `USING_UV_SHARED` macro for the DLL in Windows.

**Comment by bnoordhuis** [comment]
Apologies, I must've overlooked this. It's a reasonable request, I'll open a PR shortly.
