### ISSUE TITLE
multiple `uv_async_t` notifications can corrupt `loop->pending_requests_tail` list

### ISSUE THREAD

**Issue by ssfrr** [libuv/libuv#1951]
When `uv_async_send` is called it [calls `POST_COMPLETION_FOR_REQ(loop, &loop->async_req)`](https://github.com/libuv/libuv/blob/33b6db3909dca45fa543ab6405b934f1333fd213/src/win/async.c#L63) If there are two different `uv_async_t` handles that both get triggered, this will happen for both of them and you end up with two different completions that share the same request. When the event loop wakes up and `GetQueuedCompletionStatusEx` is called, it [calls `uv_insert_pending_req`](https://github.com/libuv/libuv/blob/7284adfa7a833264fc67d68d39610da27ecbab7c/src/win/core.c#L396-L412) twice with the same request pointer, which corrupts the pending requests list `loop->pending_requests_tail`. It [looks like](https://github.com/libuv/libuv/blob/87df1448a48fb64c2b9ebe37e3344f7e5b81dd88/src/win/req-inl.h#L93-L102) the possibility of this type of corruption is known.

I came across this while trying to figure out why my callbacks weren't getting called reliably in an application that has pretty high-frequency async notifications from a separate thread. I don't have a separate MWE at the moment - LMK if the issue doesn't seem clear and maybe I can put something together.

This is on windows, using the Julia fork of libuv.

**Comment by bzoz** [comment]
So.. if you call `uv_async_send` two times before the loop gets a chance to run, it will corrupt the pending requests list, right? If I call `uv_async_send` twice before calling `uv_run` it should reproduce this?

**Comment by ssfrr** [comment]
`uv_async_send` needs to be called with two different `uv_async_t` handles. [This check](https://github.com/libuv/libuv/blob/33b6db3909dca45fa543ab6405b934f1333fd213/src/win/async.c#L61) makes sure it only pushes one wakeup request per handle.

**Comment by ssfrr** [comment]
I put a full MWE in [this gist](https://gist.github.com/ssfrr/ca4a36428c4985cfe329bfad2d9b2a3c).

You can see here that the 2 async callbacks are called, but not the write callback. If you remove the two `uv_async_send` calls then the write callback is called. If you set a breakpoint in `uv__loop_poll` and inspect `loop->pending_reqs_tail` after each call to `uv_insert_pending_req` you'll see that after the 3 insertions there's only one item in the queue.

I'm not sure what the best strategy is to fix this. As I understand the async processing chain:

1. the `loop` has a single `async_req` (a `uv_req_t`) that acts as a per-loop request indicating that at least one async handle has been triggered.
2. async handles (`uv_async_t`) are added to `loop->async_handles` during `uv_async_init`. Each handle has an `async_sent` flag for whether it's been triggered
3. `uv_async_send` sets the handle's `async_sent` flag, and if it wasn't already set we post a completion request using the loops `async_req`.

So we could try to avoid ever sending multiple `async_req` requests to the event loop, but that seems like it would require an excessive amount of coordination in `uv_async_send`, which is supposed to be lightweight. The other option would be to have a flag while we're processing the requests to make sure that we only add the `UV_WAKEUP` request to the queue once. That's the approach I took in PR #1960.

**Comment by bzoz** [comment]
This does not reproduce in `v1.x`, I think it would be reasonable to investigate what PR broke that for master

**Comment by bzoz** [comment]
This is a regression caused by https://github.com/libuv/libuv/pull/980

/cc @saghul @bnoordhuis
