### ISSUE TITLE
Crash when using dat-gateway

### ISSUE THREAD

**Issue by edsilv** [libuv/libuv#1953]
* **Version**: node v8.11.1
* **Platform**: Ubuntu 16.04.4 LTS

https://github.com/datproject/dat/issues/871#issuecomment-393887188

It sounds like this could be related to an interaction with their utp library, but thought I'd better post it here in case it's libuv-related.

**Comment by santigimeno** [comment]
Do you have a way to reproduce the issue?

**Comment by edsilv** [comment]
It happens consistently for me after running [dat-gateway](https://github.com/pfrazee/dat-gateway) on Ubuntu 16.04.4 LTS for about 5 or 10 minutes while requesting dats e.g. http://174.138.105.19:3000/7bfac40ac3ee31c634efe139ceb950c9beb992262574c0477abea78f9d12e5ec/abyssinian.jpg

**Comment by edsilv** [comment]
cc @mafintosh

**Comment by edsilv** [comment]
I just created a fresh Ubuntu 16.04.4 x64 instance on Digital Ocean with node v8.11.4 and after about 5 or 10 mins running dat-gateway I got the same error:

```
[dat-gateway] Now listening on port 3000
node: ../deps/uv/src/unix/udp.c:67: uv__udp_finish_close: Assertion `!uv__io_active(&handle->io_watcher, 0x001 | 0x004)' failed.
Aborted (core dumped)
```

I've tested this requesting only dats I've created (in case there's something wrong with them), and dats others have published - same result.

**Comment by edsilv** [comment]
(with ports 3000 and 3282 exposed using `ufw allow`)

**Comment by edsilv** [comment]
Also, if I just leave it running without requesting any dats, it doesn't crash (have waited ~30 mins).

**Comment by edsilv** [comment]
Same issue with node v10.9.0

**Comment by edsilv** [comment]
@santigimeno How strange - now I can't get it to crash, without having changed anything... I'm using the cheapest $5/pm DO droplet (1 GB Memory, 1 CPU, 25 GB SSD)

**Comment by edsilv** [comment]
@santigimeno I think the upgrade to node v10.9.0 must have done it, but it required a reboot or something to take effect? I updated the original server to v10.9.0 and rebooted it and it has been running all day seemingly without an issue. Hopefully that's it solved...

**Comment by cjihrig** [comment]
I'm going to go ahead and close this. If the problem resurfaces, please provide a reproducible test case. Thanks!
