### ISSUE TITLE
Threadpool meta-issue

### ISSUE THREAD

**Issue by davisjam** [libuv/libuv#1959]
# Summary
This is a meta-issue to describe the landscape of proposals around the libuv threadpool. 

As has been observed [since ancient times](https://github.com/nodejs/node-v0.x-archive/issues/7256), using a single threadpool for file I/O, DNS, and user-defined tasks leads to performance problems, [Node refusing to die cleanly](https://github.com/nodejs/node-v0.x-archive/issues/25349), etc.

Where possible I have cited relevant issues, PRs, etc. Let me know if I missed anybody.

# Proposed designs

1. *BYO*. Use the libuv threadpool for I/O, but pretend `uv_queue_work` does not exist. Use an application-level threadpool for CPU-intensive tasks. I don't know if anyone has seriously proposed this, since it would require a lot of refactoring for embedders. One suggestion along these lines from @btrask [here](https://github.com/libuv/libuv/issues/267#issuecomment-126524725).
2. *Giant TP*. As suggested by @bnoordhuis [here](https://github.com/joyent/libuv/issues/1181#issuecomment-36954098) and with a sketch in #382.
    - May have performance issues. `uv_queue_work` calls with CPU-bound work will contend for a limited set of cores.
3. *TP Throttling*. Use throttling policies to prevent certain kinds of work from dominating a shared threadpool. This is the current approach thanks to @addaleax's #1845, with the implementation throttling DNS requests in favor of FS and user-defined tasks. It was also suggested by @bminer [here](https://github.com/libuv/libuv/issues/28#issuecomment-65481026), by @zhaozg [here](https://github.com/libuv/libuv/issues/660#issue-123136498) (with a policy throttling user-defined tasks), and by @CurlyMoo [here](https://github.com/libuv/libuv/issues/267#issuecomment-274330648) (with a more general policy to balance between different classes of work).
    - Could be used in conjunction with the *Giant TP* approach.
4. *TP Handles*. Any API that registers work to be performed by a thread other than the event loop should indicate the threadpool in which this work should be performed. Also suggested by @bminer [here](https://github.com/libuv/libuv/issues/28#issuecomment-65481026) and with a rough draft by @saper in #319.
    - As championed by @saghul in #7 ([LEP #4](https://github.com/libuv/leps/pull/4)). 
    - Not considered ABI compatible for v1.x.
5. *Opaque/Pluggable TP*. Let the embedder determine how asynchronous work should be performed, by providing "submit work" and "work done" function pointers by which to communicate with the event loop. This enables maximum flexibility in threadpool design and permits experimentation by different embedders for what works best for them.
    - As championed by @bnoordhuis in #267.  
    - Should be ABI compatible for v1.x.

# Desired features

1. Ability to cancel running tasks. [joyent/libuv #1181](https://github.com/joyent/libuv/issues/1181), #7, #203, #364, Node.js [#795](https://github.com/nodejs/node/issues/795).
2. Task prioritization. @bnoordhuis #7, @CurlyMoo #267.
3. Good default behavior for folks who don't want to write their own TP. @beevik, #7.
4. Scale TP on-demand. #382.
5. Monitor-ability of queue, Workers: #1144, #1528, #1764.
    - This could be used, for example, for a [backpressure](https://en.wikipedia.org/wiki/Back_pressure) mechanism. If the event loop queues work faster than the threadpool can complete it, the event loop will "steal cores" from the threadpool threads. Also, this can result in memory pressure. Not good.

# Recommended approach

@saghul said [here](https://github.com/libuv/leps/pull/4#issuecomment-248154867) that: "The libuv core team...gathered...and decided to...focus on a pluggable API for threaded operations".

As @bnoordhuis has argued, this approach should be able to support all of the desired features with the right API and structs.

# Ongoing work

I am working on an implementation of the *Pluggable TP* design in #1726.

**Comment by davisjam** [comment]
> There’s a lot of issues around this topic

Haha yeah, apparently 4 years' worth, across several repositories!

> but tbh, I don’t remember where past conversations happened here. 

Sorry, I'm having trouble interpreting this! Are you saying you literally don't remember / weren't around for the original conversations, or are you saying that you think this is a non-issue (not worth remembering/the conversations never happened)?

> I do think that libuv should provide a thread pool implementation out of the box that doesn’t have issues like one kind of operations starving out other types of operations (like dns vs fs).

As I understand it, we don't currently have one of these. #1845 prevents DNS from clogging the threadpool, but not user-submitted requests or FS queries. I can put #1845 back into #1726, but it's not clear to me which types of embedder behaviors the default threadpool should try to optimize for. For a policy perspective I'm hoping to hear from @bnoordhuis and @saghul, etc. who have expressed a lot of opinions about the various TP designs over the years.

**Comment by addaleax** [comment]
@davisjam What I meant was, you had a comment somewhere about reverting #1845 and I literally don’t know where it is, so I can’t reply to it directly…

**Comment by davisjam** [comment]
> I wouldn't change that unless there's good reason to.

Right, in #1726 there's still a default libuv executor that uses UV_THREADPOOL_SIZE. I just removed the DNS throttling from #1845 to simplify things in my PR, though I can put it back if we decide that that is good default behavior. Or I can extend the default executor beyond #1845, e.g. as @addaleax suggested [earlier](https://github.com/libuv/libuv/issues/1959#issuecomment-417766225): "I do think that libuv should provide a thread pool implementation out of the box that doesn’t have issues like one kind of operations starving out other types of operations (like dns vs fs)."

**Comment by davisjam** [comment]
@addaleax 

> you had a comment somewhere about reverting #1845 and I literally don’t know where it is

It's over in #1726. Starts [here](https://github.com/libuv/libuv/pull/1726#issuecomment-416309826).

**Comment by davisjam** [comment]
>  it's not clear to me which types of embedder behaviors the default threadpool should try to optimize for

I spent some time to try to flesh this out a bit more.

## Summary

I went through the [list of projects that use libuv](https://github.com/libuv/libuv/wiki/Projects-that-use-libuv) that we maintain to see whether/how different embedders use the libuv threadpool.

Unsurprisingly, I think Node.js is the most interesting embedder from that list. Within Node.js there are many use cases (e.g. [this list](https://github.com/nodejs/benchmarking/blob/master/docs/use_cases.md) from nodejs/benchmarking).

## Details

After sorting by GitHub star count, the projects with >100 stars that extensively use the libuv threadpool are:
- [Node.js](https://github.com/nodejs/node): DNS, FS, crypto, zlib, and arbitrary user operations via napi_queue_async_work
- [julia](https://github.com/JuliaLang/julia): DNS. Also has an experimental Threadcall feature that uses `jl_queue_work` -> `uv_queue_work` under the hood
- [luvit](https://github.com/luvit/luvit): Usage similar to Node.js, unsurprising given the aims of this project
- [libstorj](https://github.com/Storj/libstorj): Lots of internal operations directed to uv_queue_work. The GitHub repo says development is on hold though.

Other `star>100` projects use the libuv threadpool via asynchronous DNS resolution and/or FS accesses:
- [uvloop](https://github.com/MagicStack/uvloop)
- [cjdns](https://github.com/cjdelisle/cjdns)
- [wren](https://github.com/munificent/wren)
- [urbit](https://github.com/urbit/urbit)
- [node.native](https://github.com/d5/node.native)
- [libnode](https://github.com/plenluno/libnode)
- [phastlight](https://github.com/phastlight/phastlight)
- [luaw](https://github.com/raksoras/luaw)

**Comment by CurlyMoo** [comment]
Don't forget pilight as a 230 star project. I'm using libuv for various network and file io. I'm very willing to test new threadpool implementations.

**Comment by davisjam** [comment]
@CurlyMoo Thanks for the tip. I will add pilight to the list of projects.

**Comment by davisjam** [comment]
> The meta-discussion is not just about fs io right?

Correct. I'm looking for any embedders that use the libuv threadpool, so we can better understand (1) the potential *impact* of changes to the default libuv threadpool implementation; and (2) the potential *interest* in a pluggable threadpool.

I am just confused because you said
> I'm using libuv for various network and file io

and I couldn't find any `uv_fs` in the pilight repo:

```bash
$ grep -R uv_fs pilight/ | grep -v libs/libuv | wc -l
0
```

**Comment by CurlyMoo** [comment]
Maybe i was mistaking about the file io part.
