### ISSUE TITLE
uv_dirent_t type always UV_DIRENT_UNKNOWN on windows

### ISSUE THREAD

**Issue by creationix** [libuv/libuv#196]
I just hit a nasty but in luvit caused by uv_scandir_next's dirent always having a type of unknown.

The docs mention several parts of the fs api that don't work on windows, but there are no such notes for type on dirents.  Is this a bug or a documentation issue?

I can work around it by doing a sync fs_stat when .type is missing in my code, but that's nasty.

**Comment by bnoordhuis** [comment]
> Is this a bug or a documentation issue?

I suspect it's a documentation issue.  I wasn't involved with the PR that added uv_fs_scandir() but if I had to venture a guess, I'd say the current implementation is what it is because the Windows file API doesn't give you the metadata.  Libuv would have to stat the directory entry to find out what kind of object it is.

**Comment by creationix** [comment]
I was afraid that was the case.  Good to know though. If someone confirmn this I would be willing to send a PR for the docs.

**Comment by saghul** [comment]
The type field is supposed to be filled on Windows too: https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L914-922

What type of file is giving you trouble?

**Comment by creationix** [comment]
I'm just trying to scandir a normal directory containing a mix of files and directories.  All have type unknown.

My bindings don't set the type property in case of UNKNOWN and thus fail this unit test https://ci.appveyor.com/project/racker-buildbot/luv/build/1.0.30#L496

**Comment by saghul** [comment]
Hum, I see the tests check for either file or unknown... Will have to dig deeper!

**Comment by trevnorris** [comment]
@saghul Could it be because `uv_fs_scandir_next()` has an `ifdef` to check for `HAVE_DIRENT_TYPES` (here https://github.com/libuv/libuv/blob/fab7459/src/uv-common.c#L414-L442) , but `HAVE_DIRENT_TYPES` is only defined in `include/uv-unix.h`?

**Comment by piscisaureus** [comment]
@trevnorris is on the money.

**Comment by txdv** [comment]
no one tested this on windows?

**Comment by saghul** [comment]
@trevnorris good find!

@txdv the test is actually bogus.

**Comment by saghul** [comment]
Created https://github.com/libuv/libuv/pull/201 lets see what Jenkins has to say.

**Comment by creationix** [comment]
@saghul if I pull in your patch to luv, it fixes my broken test!

**Comment by saghul** [comment]
#201 landed, closing. Thanks for testing @creationix! :cake:
