### ISSUE TITLE
Linux syscall interception incompatibility (Open Onload)

### ISSUE THREAD

**Issue by ollie299792458** [libuv/libuv#1969]
I had some issues running Node.js with [Open Onload](https://www.openonload.org/). Open Onload is a network stack that runs in user mode and intercepts system calls, allowing for very low latency networking, it is developed by [Solarflare](http://solarflare.com/) where I am currently interning.

Libuv uses [syscall(2)](http://man7.org/linux/man-pages/man2/syscall.2.html) to make system calls, this results in Onload being bypassed.  A call to [write(2)](https://linux.die.net/man/2/write) instead ends up as `syscall(WRITE_SYSCALL_ID, args)`.  I have forked Node.js and edited [linux-syscalls.c](https://github.com/libuv/libuv/blob/v1.x/src/unix/linux-syscalls.c) to call the system calls directly (when an environment variable is set) and Onload works without issue with node.js (with my modified libuv).

I have two main questions
* Was the decision to use syscall(2) over named system calls made for any particular reason?
* Would an edit to linux-syscalls.c to allow named system calls to be used (either selected at compile time, or some other method) be amenable?

Edit: I believe this is related: #1950

**Comment by santigimeno** [comment]
See: 
https://github.com/libuv/libuv/issues/1880
https://github.com/libuv/libuv/pull/1950

**Comment by ollie299792458** [comment]
Thanks, I found this #1372 pull request, however it still appears to use syscall(2) for accept(4)?

What I read from those two issues is that: This is something people want to do, this is something that has (almost - bar accept(4)) been done), but has yet to make it into libuv, and there is no eta on when/if it ever will. Is this correct?
