### ISSUE TITLE
should we Replace getenv/GetEnvironmentVariableW with uv_os_getenv everywhere?set uv_threadpool_size  doesnot work

### ISSUE THREAD

**Issue by kenash54845** [libuv/libuv#1977]
hi,
the following program wont mix character 'm' and 'Q' if putenv works.
calling putenv directly doesnot work in my program,    
loadlibrary and getprocaddress and then calling putenv works.
i believe if u build libuv and the following code with different version of ms visual studio ,this issue appears.  see here http://siomsystems.com/mixing-visual-studio-versions/

on my machine,
libuv is built with ms visual studio 2012,the following piece of code is compile and built with ms visual studio 2017. 

```
#include<iostream>
#include<uv.h>
#include<Windows.h>

#pragma comment(lib,"C:\\apis\\libuv-1.18.0\\Debug\\libuv.lib")
void uv_work_cb_test(uv_work_t* req)
{
	char c = (char)req->data;
	for (int i = 0; i < 100; i++)
		std::cout << c;
}

int main(int c,char *v[])
{
	putenv("UV_THREADPOOL_SIZE=1");
	HMODULE hdll = LoadLibraryA(
#ifdef _DEBUG
		"msvcr110d.dll"
#else
		"msvcr110.dll"
#endif
	);
	FARPROC proc = GetProcAddress(hdll, "_putenv");
	typedef int(*pf)(const char *);
	pf _pf = (pf)proc;
	//comment next line,character 'm' mixed with character 'Q'
	//_pf("UV_THREADPOOL_SIZE=1");
	
	uv_work_t vts[2];
	vts[0].data = (void *)'m';
	vts[1].data = (void *)'Q';
	for (auto &a : vts)
	{
		uv_queue_work(uv_default_loop(), &a, uv_work_cb_test, nullptr);
	}
	uv_run(uv_default_loop(), UV_RUN_DEFAULT);	
	FreeLibrary(hdll);
	return 0;
}

```

**Comment by kenash54845** [comment]
@bzoz  i tried this,but character 'm' and 'q' is still mixed .
```
int main(int c,char *v[])
{
	//putenv directly doesnot work .
	//libuv is built with ms visual studio 2012,this cpp is compile and built with ms visual studio 2017
	uv_os_setenv("UV_THREADPOOL_SIZE", "1");
	//putenv("UV_THREADPOOL_SIZE=1");
	HMODULE hdll = LoadLibraryA(
#ifdef _DEBUG
		"msvcr110d.dll"
#else
		"msvcr110.dll"
#endif
	);
	FARPROC proc = GetProcAddress(hdll, "_putenv");
	typedef int(*pf)(const char *);
	pf _pf = (pf)proc;
	//comment next line,character 'm' mixed with character 'Q'
	//_pf("UV_THREADPOOL_SIZE=1");
	
	uv_work_t vts[2];
	vts[0].data = (void *)'m';
	vts[1].data = (void *)'Q';
	for (auto &a : vts)
	{
		uv_queue_work(uv_default_loop(), &a, uv_work_cb_test, nullptr);
	}

	uv_run(uv_default_loop(), UV_RUN_DEFAULT);
	
	FreeLibrary(hdll);
	return 0;
}
```

**Comment by bzoz** [comment]
You can try changing `threadpool.c` to use [uv_os_getenv](http://docs.libuv.org/en/v1.x/misc.html#c.uv_os_getenv) and see if this helps in your case? This should be changed anyway, PRs are always welcome.

**Comment by bnoordhuis** [comment]
General observation: it sounds like libuv and your program may be linked to different C runtimes.  That would explain why the call to putenv() isn't visible to libuv.

**Comment by kenash54845** [comment]
@bnoordhuis  yes,i think ur right.  different versions of c runtime dont talk to each other,
i select Multi-threaded (Debug) DLL (/MD(d)) as run time library

**Comment by davisjam** [comment]
Is it possible for this problem to manifest in other places in the code where getenv is called? I see calls in these files:
- src/unix/core.c
- src/unix/tcp.c
- src/unix/os390.c
- src/unix/aix-common.c

Should we change this issue to "Replace `getenv` with `uv_os_getenv` everywhere" and do that in #1982?

**Comment by kenash54845** [comment]
i read unix/core.c ,line 1259,definition of `uv_os_getenv` ,and  think it is almost identical to calling getenv.
but  if getenv works well on unix systems , donot change is better choice ,am i right?  since calling getenv  directly is more concise

**Comment by davisjam** [comment]
@kenash54845 I was just thinking that, since we *have* an API for this (which does consistent setup and error checking, etc.), we might as well use it instead of rolling our own each time.

There are analogous "rogue" calls to get environment variables in `src/win/process.c` using `GetEnvironmentVariableW` instead of `uv_os_getenv`.

These calls are presumably sound in `src/unix/` and `src/win/`, respectively, whereas in `src/threadpool.c` it was problematic to assume one over the other. But the benefits of consistent API usage and error checking are still valuable in the OS-specific contexts.

**Comment by kenash54845** [comment]
should we Replace getenv/GetEnvironmentVariableW with uv_os_getenv everywhere?
the benefits of consistent API usage and error checking are both valuable in the OS-specific and os-independent contexts.

**Comment by cjihrig** [comment]
> should we Replace getenv/GetEnvironmentVariableW with uv_os_getenv everywhere?

Probably where it makes sense and would improve the code.

**Comment by cjihrig** [comment]
I'm going to close this. Updates to use `uv_os_getenv()` are welcome where they make sense, but not strictly necessary. Patches welcome.
