### ISSUE TITLE
win: uv_fs_stat does not work for "special" files (e.g. pagefile.sys)

### ISSUE THREAD

**Issue by bzoz** [libuv/libuv#1980]
* **Version**:  v1.x
* **Platform**:  win

See https://github.com/nodejs/node/issues/22577.

`CreateFile` call for `pagefile.sys` fails with `EBUSY`, thus one cannot stat that file with libuv.

**Comment by seishun** [comment]
One solution would be to use [FindFirstFile](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findfirstfilea) instead.

**Comment by bzoz** [comment]
Looks like `ZwQueryDirectoryFile` (like in [here](https://stackoverflow.com/questions/3878517/how-to-get-fileindex-without-using-file-handle)) would yield almost the same info we are getting now, we can try that. OTOH, maybe `ZwCreateFile` (like in [here](https://www.osronline.com/showthread.cfm?link=177754)) can open those files?

**Comment by piscisaureus** [comment]
> Looks like `ZwQueryDirectoryFile` (like in [here](https://stackoverflow.com/questions/3878517/how-to-get-fileindex-without-using-file-handle)) would yield almost the same info we are getting now, we can try that. OTOH, 

That seems like a good idea. I don't know for sure you can get all the information you need though.

> maybe `ZwCreateFile` (like in [here](https://www.osronline.com/showthread.cfm?link=177754)) can open those files?

That seems unlikely; after all, CreateFileW is just a wrapper for NtCreateFile.

PS: in user mode you can't call the ZwXXX class of functions; you have to use the NtXX versions, which are really the same.

**Comment by vtjnash** [comment]
https://github.com/nodejs/node/issues/22577 was closed, but seems to reference that this is still an issue?

**Comment by bnoordhuis** [comment]
Is the conclusion that there's no reasonable workaround? If yes, then we should probably document it in order to close out this issue?

**Comment by vtjnash** [comment]
It seems like the only bit lost would be the number of hard links (st_nlink). Reparse points are also extremely inconvenient to implement (https://community.osr.com/discussion/105613), but probably not expected (it looks like we can check if it is a reparse point, just not examine the destination conveniently).
