### ISSUE TITLE
Windows build failed

### ISSUE THREAD

**Issue by Pummelchen** [libuv/libuv#1983]
* **Version**: 
1.23 and latest Master

* **Platform**: 
Windows Server 2019 17744.1001 & VS2017 15.8.3

Issue:

X:\Dropbox\Projects\Test\Code\Libraries\LibUV>vcbuild vs2017
git clone https://chromium.googlesource.com/external/gyp build/gyp
Cloning into 'build/gyp'...
remote: Total 18079 (delta 12715), reused 18079 (delta 12715)
Receiving objects: 100% (18079/18079), 7.95 MiB | 70.00 KiB/s, done.
Resolving deltas: 100% (12715/12715), done.
Traceback (most recent call last):
  File "gyp_uv.py", line 21, in <module>
    import gyp
  File ".\build\gyp\pylib\gyp\__init__.py", line 37
    print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
                         ^
SyntaxError: invalid syntax
Failed to create vc project files.

**Comment by addaleax** [comment]
It’s hard to be sure, but it the error seems like you use Python 3 – libuv needs Python 2 to build… can you try that?

**Comment by Pummelchen** [comment]
Fixed using py 2
