### ISSUE TITLE
min heap performance optimize

### ISSUE THREAD

**Issue by number201724** [libuv/libuv#1984]
heap-inl.h

`
  for (k = 0, n = heap->nelts; n >= 2; k += 1, n /= 2)
    path = (path << 1) | (n & 1);
`

to

`
  for (k = 0, n = heap->nelts; n >= 2; k += 1, n >>= 1)
    path = (path << 1) | (n & 1);
`

**Comment by cjihrig** [comment]
So basically, replace `n /= 2` with `n >>= 1`? The compiler should be able to use strength reduction to accomplish the same thing.

**Comment by number201724** [comment]
yes, some compilers don't optimize this, like MSVC

**Comment by davisjam** [comment]
This change decreases the readability of the code. Is the corresponding performance improvement worthwhile?
