### ISSUE TITLE
TCP RST : "simulate" connection failure

### ISSUE THREAD

**Issue by mikuso** [libuv/libuv#1991]
Currently, there is no way for libuv to terminate a TCP connection with a RST packet (simulating a connection failure).  This is a feature request.

Use case
---------
The need for this feature arises from how different web browsers handle incomplete downloads from HTTP servers.  For example, if a file download ends prematurely (such as when the Content-Length header does not match the size of the file which was transferred), some browsers will still consider this to be a successful transfer (looking at you Chrome & Edge) so long as the TCP connection is ended gracefully.

Similarly, some web browsers will also consider an non-terminated chunked transfer to be "complete" too, so long as the connection terminates gracefully.

This has been [discussed on the Chromium bugs board](https://bugs.chromium.org/p/chromium/issues/detail?id=501384) for years, and they've had [a potential "fix" in their queue](https://codereview.chromium.org/2832223004) for over a year.

Today, the only universally reliable way for web browsers to "understand" that a transfer has failed is when a TCP connection is dropped ungracefully (i.e. with a RST packet).

I maintain a reverse HTTP proxy server written in NodeJS.  If an end-user is downloading a file via the proxy when suddenly a back-end file-serving web server goes down, the proxy has no reliable way to communicate to the end-user that the download has been interrupted.  Dropping the TCP connection gracefully will often result in the end-user being erroneously informed that the download has completed successfully (when it hasn't).

It also makes sense to me that if a proxy server experiences a RST from an upstream server, then it should be able to "pass" this down to the end-user.

How
-----
In Winsock, I believe this can be achieved by [enabling `SO_LINGER` (using `setsockopt()`) with a zero second linger time](https://docs.microsoft.com/en-gb/windows/desktop/api/winsock/ns-winsock-linger), before closing the connection as normal.

I don't know enough to offer any advice for how to achieve this on other platforms.

**Comment by bnoordhuis** [comment]
Zero SO_LINGER works on Unices too, so it should be possible to implement `uv_tcp_close_reset()`, or whatever a good name for it is.

That said, the interaction between zero SO_LINGER and shutdown() is not consistent across platforms.  Mixing of `uv_tcp_close_reset()` and `uv_shutdown()` would need to be avoided.

**Comment by DDoSolitary** [comment]
😕

**Comment by santigimeno** [comment]
I have a branch somewhere with this implemented. I’m AFK until next week.
I’ll create a PR then.

**Comment by vtjnash** [comment]
Oooh, it sounds like this could be just the thing I wanted for writing JuliaLang socket tests too! (simulating network failures, to run the error code handling paths)
