### ISSUE TITLE
Grammatical mistake in libuv documentation on page 8

### ISSUE THREAD

**Issue by kartikchauhan** [libuv/libuv#2000]
On page no. 8, in section 3.1.3 File I/O, last line says "libuv currently uses a global thread pool on which all loops can queue work on". According to me it should be "libuv currently uses a global thread pool on which all loops queue can work on."

**Comment by crazymerlyn** [comment]
I believe the original phrasing is correct. Queue in that sentence is a verb not a noun. The loops are queuing work on different thread pools.

**Comment by davisjam** [comment]
@crazymerlyn is correct, though the original phrasing could be improved to

"libuv currently uses a global thread pool on which all loops can queue work ~~on~~."

**Comment by cjihrig** [comment]
Would someone like to open a PR dropping the trailing "on"?

**Comment by bnoordhuis** [comment]
I'm... wait for it... on it! #2010
