### ISSUE TITLE
uv_getaddrinfo crash on some android device

### ISSUE THREAD

**Issue by gyh007** [libuv/libuv#2004]
my libuv version is 1.20.3, i call uv_getaddrinfo to resolve dns, it runs normally on most devices but lg-f600s, it crash. below is the logcat output:

13309-18 20:38:00.715 22535 11044 D libc-netbsd: [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
13409-18 20:38:00.715 22535 11044 D libc : getaddrinfo called from pid =22535
13509-18 20:38:00.715 22535 11044 D libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
13609-18 20:38:00.775 22535 10745 D libc-netbsd: [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
13709-18 20:38:00.775 22535 10745 D libc : getaddrinfo called from pid =22535
13809-18 20:38:00.775 22535 10745 D libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
13909-18 20:38:00.775 22535 11058 D libc : remote DNS query failed we don't need to try local DNS query result_code =401
14009-18 20:38:00.775 22535 11058 D libc : dnsproxy getaddrinfo returns 401
14109-18 20:38:00.775 22535 11058 F libc : /buildbot/arm-android/libuv/1.20.3/src/unix/getaddrinfo.c:92: int uv__getaddrinfo_translate_error(int): assertion "!"unknown EAI_* error code"" failed

maybe we should not assert and abort in function uv__getaddrinfo_translate_error?

**Comment by bnoordhuis** [comment]
Aborting is the right thing to do in that function.  Can you add a printf statement to find out what the error code is?

**Comment by gyh007** [comment]
the error code seems to be 401 from the log

**Comment by bnoordhuis** [comment]
It's been two months with no other reports so I'm going to close this out. Thanks anyway for taking the time to report it.
