### ISSUE TITLE
Give @davisjam ability to launch some libuv tests

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#2006]
Would it be ok to temporarily give @davisjam the ability to start some libuv jobs to help investigate: https://github.com/libuv/libuv/pull/1998#issuecomment-424926583

**Comment by addaleax** [comment]
:+1:

**Comment by cjihrig** [comment]
I'm 👍 to that.

**Comment by davisjam** [comment]
Would also be helpful for #1726.

**Comment by refack** [comment]
👍

**Comment by santigimeno** [comment]
:+1:

**Comment by mhdawson** [comment]
Seems like there is good support, if I don't hear any objections by end of day today, I'll enable the ability to run the osx jobs

**Comment by davisjam** [comment]
Confirmed. Thanks, folks.

**Comment by cjihrig** [comment]
Closing, as this has been completed.
