### ISSUE TITLE
tty: read callback is called after closing

### ISSUE THREAD

**Issue by neoxic** [libuv/libuv#2012]
I have encountered an inconsistency when closing tty handles on UNIX and Windows. Please see the following code:

```C
#include <uv.h>

uv_tty_t tty;
uv_signal_t sig;

static char BUFFER[10];

static void alloc_cb(uv_handle_t *handle, size_t size, uv_buf_t *buf) {
	*buf = uv_buf_init(BUFFER, sizeof BUFFER);
}

static void close_cb(uv_handle_t *handle) {
	printf("close_cb(%p)\n", handle);
}

static void read_cb(uv_stream_t *handle, ssize_t size, const uv_buf_t *buf) {
	printf("read_cb(%p, %d)\n", handle, (int)size);
	if (size < 0) uv_close((uv_handle_t *)handle, close_cb); /* We MUST close the handle on error */
}

static void signal_cb(uv_signal_t *handle, int signum) {
	printf("*** Closing tty...\n");
	uv_close((uv_handle_t *)&tty, close_cb);
}

int main() {
	uv_loop_t *loop = uv_default_loop();
	uv_tty_init(loop, &tty, 0, 1);
	uv_signal_init(loop, &sig);
	uv_unref((uv_handle_t *)&sig);
	uv_read_start((uv_stream_t *)&tty, alloc_cb, read_cb);
	uv_signal_start(&sig, signal_cb, SIGINT);
	uv_run(loop, UV_RUN_DEFAULT);
	uv_loop_close(loop);
	return 0;
}
```

Compile, run and press CTRL+C.

UNIX:
```
^C*** Closing tty...
close_cb(0x5571ebccf0c0)
```
Everything works as it is supposed to.

WINDOWS:
```
read_cb(00843F60, 0)
*** Closing tty...
read_cb(00843F60, 0)
close_cb(00843F60)
```
Note that `read_cb` is called **twice**. Umm.... I am probably okay with the first (dummy) invocation, but I definitely do not expect another call to `read_cb` **after** the handle was closed.

**libuv 1.23.1**

**Comment by addaleax** [comment]
I think the very recently merged https://github.com/libuv/libuv/pull/2005 might be a fix for this issue? Can you check with the v1.x branch here?

**Comment by neoxic** [comment]
Just checked. The issue is relevant for v1.x HEAD as for now.

I also tried explicitly calling `uv_read_stop` before `uv_close` with the same outcome.

**Comment by bzoz** [comment]
The first read callback is for `Ctrl-C` itself. It is fired before the signal handler has a chance to stop the read. `ReadConsoleW` successfully reads 0 bytes, so it reports it. We then cancel the read in `uv_close`, by sending fake Enter key. It gets also reported because of https://github.com/libuv/libuv/blob/ee87f34474605b5c2db2870621e8cb72c2043cae/src/win/tty.c#L954-L957

I'm not sure if this is a bug. The docs say that the read callback can be called with 0 size, but it also says that `this is equivalent to EAGAIN or EWOULDBLOCK under read(2)`, which is not the case here. It is for sure confusing, so I think we should remove both 0-size read callbacks.

**Comment by bzoz** [comment]
Fix in https://github.com/libuv/libuv/pull/2014

**Comment by neoxic** [comment]
I don't mind zero-sized callbacks before a handle is closed. I know they can happen. The real problem here is that a second callback is fired **after** the handle has been closed as it becomes troublesome for a higher layer (a binding) to ever be ready for such a situation by adding checks for `uv_is_closing` in every callback. Also, a supporting infrastructure for a callback to happen might have already been dismantled right after a call to `uv_close`.

**Comment by neoxic** [comment]
I'll confirm the fix later. Thanks!
