### ISSUE TITLE
A  memory error occured yesterday

### ISSUE THREAD

**Issue by cynron** [libuv/libuv#202]
Hi,

libuv v0.11.28
Debian kernel 3.2.63 x86_64

Our service is out of control suddenly yesterday.
First, I use `strace` to get  syscalls, and found:

```
clock_gettime(0x54db3899 /* CLOCK_??? */, 0x7f4800730e00) = -1 EINVAL (Invalid argument)
epoll_wait(9, {{EPOLLOUT, {u32=14, u64=14}}}, 1024, 2147483647) = 1
clock_gettime(0x54db3899 /* CLOCK_??? */, 0x7f480072dd80) = -1 EINVAL (Invalid argument)
writev(14, [], 0)                       = 0
clock_gettime(0x54db3899 /* CLOCK_??? */, 0x7f4800730e00) = -1 EINVAL (Invalid argument)
epoll_wait(9, {{EPOLLOUT, {u32=14, u64=14}}}, 1024, 2147483647) = 1
clock_gettime(0x54db3899 /* CLOCK_??? */, 0x7f480072dd80) = -1 EINVAL (Invalid argument)
writev(14, [], 0)                       = 0
clock_gettime(0x54db3899 /* CLOCK_??? */, 0x7f4800730e00) = -1 EINVAL (Invalid argument)
epoll_wait(9, {{EPOLLOUT, {u32=14, u64=14}}}, 1024, 2147483647) = 1
clock_gettime(0x54db3899 /* CLOCK_??? */, 0x7f480072dd80) = -1 EINVAL (Invalid argument)
writev(14, [], 0)                       = 0
```

So, i use gdb to catch what happened, then I got the following:

```
Breakpoint 4, uv__hrtime (type=UV_CLOCK_FAST) at deps/uv/src/unix/linux-core.c:331
331	  if (type == UV_CLOCK_FAST && fast_clock_id == -1) {
(gdb) p fast_clock_id
$5 = 1423653017
(gdb) n
340	  clock_id = CLOCK_MONOTONIC;
(gdb) n
341	  if (type == UV_CLOCK_FAST)
(gdb) n
342	    clock_id = fast_clock_id;
(gdb) n
344	  if (clock_gettime(clock_id, &t))
(gdb) n
345	    return 0;  /* Not really possible. */
(gdb) n
348	}
(gdb) c
Continuing.

Breakpoint 3, uv__write (stream=0x1f63c90) at deps/uv/src/unix/stream.c:704
704	  assert(uv__stream_fd(stream) >= 0);
(gdb) n
706	  if (QUEUE_EMPTY(&stream->write_queue))
(gdb) n
709	  q = QUEUE_HEAD(&stream->write_queue);
(gdb) n
710	  req = QUEUE_DATA(q, uv_write_t, queue);
(gdb) n
711	  assert(req->handle == stream);
(gdb) n
718	  iov = (struct iovec*) &(req->bufs[req->write_index]);
(gdb) n
719	  iovcnt = req->nbufs - req->write_index;
(gdb) n
721	  iovmax = uv__getiovmax();
(gdb) s
uv__getiovmax () at deps/uv/src/unix/stream.c:686
686	  if (iovmax == -1)
(gdb) n
688	  return iovmax;
(gdb) p iovmax
$6 = 0
(gdb) n
692	}
(gdb) n
uv__write (stream=0x1f63c90) at deps/uv/src/unix/stream.c:724
724	  if (iovcnt > iovmax)
(gdb) p iovcnt
$7 = 1
(gdb) n
725	    iovcnt = iovmax;
(gdb) n
```

This is unbelievable, `iovmax` and `fast_clock_id` are static varibles within static functions.
The value of `fast_clock_id` is `1423653017`, which likes a timestamp and can be convert to `2015/2/11 19:10:17`, and since that time, the service became out of control.

The service runs on a virtual mechine, does this matter? I have no idea why it happened.

Thanks!

Xy

**Comment by saghul** [comment]
AFAIS, `clock_gettime` would give EINVAL if the given clock id is not supported, but that doesn't explain why it ever worked. Was anything in the system updated while this was running?

**Comment by cynron** [comment]
@saghul  After restarting the service, it is running well now.

I guess there should be wrong pointers unexpectedly pointing to `fast_clock_id` and `iovmax`, but now we can not reproduce it. we will try to reproduce it.

**Comment by cynron** [comment]
The issue occured once again recently.

Now, we have start our service in our test evironment with being attached by gdb, and setting 2 watchpoints to trace the value changing of `fast_clock_id` and `iovmax`. we are waiting for next re-production.

**Comment by cynron** [comment]
@saghul  I am sorry to tell you that this issue is our own problem. Thanks!

**Comment by saghul** [comment]
Thanks for the heads up!
