### ISSUE TITLE
Main loop deadlocks if only active handle is a uv_check_t

### ISSUE THREAD

**Issue by Qix-** [libuv/libuv#2022]
Perhaps this is intended functionality but there is nothing in the documentation that indicates this is the case.

The following simple case will cause the main loop to deadlock upon the first iteration:

```c
#include <stdio.h>
#include "uv.h"

void on_check(uv_check_t *h) {
	puts("check");
}

int main(void) {
	uv_loop_t loop;
	uv_loop_init(&loop);

	uv_check_t ch;
	uv_check_init(&loop, &ch);
	uv_check_start(&ch, &on_check);

	uv_run(&loop, UV_RUN_DEFAULT);

	return 0;
}
```

Understandably, checks are only fired after polling occurs. That part is clear. However, what's not clear is that the loop is blocking in the poll state even though there are no file descriptors registered to poll. I figured since no descriptors were added to actually poll, therefore there was nothing to cause the polling stage to block.

This means that if the `uv_check_t` is the only handle, the loop will immediately deadlock.

The use case here is that I know other handles will be added later on, but the check is the first one and will need to come after poller handles added later on in execution. It was entirely unexpected that the loop deadlocked entirely.

This is intended functionality? If so, could a large, red warning be placed on the documentation that indicates this? It's caused 24 hours of headaches and a bit of tracker noise on a couple of repositories.

Worth mentioning this happens both on master as well as the v1.x branch.

**Comment by Qix-** [comment]
> You commonly call uv_unref() on check and prepare handles to prevent that from happening.

Is this practice documented anywhere?

> We don't have red warnings in our docs

http://docs.libuv.org/en/v1.x/loop.html#c.uv_default_loop

**Comment by bnoordhuis** [comment]
Yes, it's mentioned in http://docs.libuv.org/en/v1.x/handle.html#reference-counting

Interesting, I didn't know `warning::` items were rendered that way (but I guess that makes sense, them being warnings.)

**Comment by Qix-** [comment]
That's not really what I'm after, though. I don't want the loop to exit. I want the loop to _run_, and be able to insert events _after_ the polling stage, even when nothing is being polled.

> The user can force the loop to exit early by unreferencing handles which are active

It sounded like you meant unref-ing was some magic way to keep the loop running but not polling. But alas this would cause my program to exit, unless I put the `uv_run()` call itself in a loop - at which point, why use libuv for a main loop? :)

**Comment by Qix-** [comment]
Doesn't `UV_RUN_NOWAIT` only run once, though?

**Comment by bnoordhuis** [comment]
Yes, `UV_RUN_NOWAIT` runs once.  It polls but doesn't sleep.

> I'm still confused as to which fd libuv is waiting for when there's only a check handle

It suspends on an empty poll set. The use case here is e.g. sleeping until a timer expires.

A lone check handle isn't that useful but a check handle + unref'd timer is (or async handle, or signal handle, or...)

Please send a pull request if you think the documentation can be improved. Maybe a note in loop.rst?

**Comment by bnoordhuis** [comment]
Closing, no follow-up.
