### ISSUE TITLE
test: add EISDIR test

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#2026]
> I couldn't find tests that check for the presence/absence of EISDIR. If the CI run turns up green, I'll see about adding some.

As https://github.com/libuv/libuv/pull/2025 already landed just a reminder.

**Comment by thefourtheye** [comment]
I have a test in #2023, would that be good enough?

**Comment by bnoordhuis** [comment]
@thefourtheye You want to open a PR for that?

**Comment by thefourtheye** [comment]
@bnoordhuis Sure, I have created #2029
