### ISSUE TITLE
Windows uv_process_tcp_read_req (win/tcp.c) can loop forever 

### ISSUE THREAD

**Issue by llint** [libuv/libuv#2027]
* **Version**: 1.22.0 (Stable) 
* **Platform**: Windows 10 x64 

* **Desc**: when a sender is flooding the receiver with data, `uv_process_tcp_read_req` (`win/tcp.c`) could get stuck inside the `while (handle->flags & UV_HANDLE_READING)` loop following the comment line `/* Do nonblocking reads until the buffer is empty */` - we have hit a case that a furious sender is constantly sending a large amount of data in its game loop, causing the receiver getting stuck inside `uv_loop`, where `uv_process_tcp_read_req` never returns due to the infinite loop mentioned. In our case, the read `bytes` from the `WSARecv` did always return `65536`, filling the read buffer. We understand that a well behaving sender should not flood the receiver, but on the wild Internet, a nasty hacker can easily get us DOS'ed.

**Comment by bzoz** [comment]
You can use `uv_read_stop` to terminate the read, do other stuff and resume reading from the socket later. After every read you regain the controll over your app, so I would not say that tou can easily get DOS'ed.
