### ISSUE TITLE
udp connect feature, that can restrict the peer address from which receive packet

### ISSUE THREAD

**Issue by ticty** [libuv/libuv#2031]
* **Version**: master
* **Platform**: any

I have noticed that liuv not support udp connect. Am I right ?

By calling `connect` on a udp client socket, dst ip:port is determined, and it will **only** receive packet from dst. 

If not support, then it will receive packet from any peer.

How to solve it ? or why udp connect not enabled ?

**Comment by santigimeno** [comment]
This feature is already implemented in the `master` branch. See https://github.com/libuv/libuv/commit/70d437130393dc8d9d01f2758b9b3c23a4dccedb.
