### ISSUE TITLE
uv_timer callback with Custom Context ?

### ISSUE THREAD

**Issue by Merethiel** [libuv/libuv#2036]
I'd like to integrate libuv into my project; however I noticed that the callback for the libuv timer didn't have a void* argument for user data or context. 
uv_timer_start takes an argument to the callback, is there a function I can use that takes a void* argument as well where I can pass my own data into the timer handler?
Something like : 
`uv_timer_start(&sendtimer, timercallback,customcontext, 1000,1000);`

`void timer(uv_timer_t* handle, void* context)`
Is this possible?

**Comment by davisjam** [comment]
Did you check whether the uv_timer_t type (or its ancestors) has a `data` member?

**Comment by Merethiel** [comment]
It does not as far as I'm aware. 
It doesn't look like a structure to me. But I can't possibly be the only one who's had this issue.

**Comment by bnoordhuis** [comment]
It does, all handle types have a `.data` field. Access it with `handle->data`.

**Comment by Merethiel** [comment]
I looked through the documentation but I coundn't see a data field in the handle. But thank you that did work.

**Comment by davisjam** [comment]
http://docs.libuv.org/en/v1.x/timer.html?highlight=uv_timer_t#public-members

**Comment by Merethiel** [comment]
Yes but nothing in that documentation mentions a data member..
