### ISSUE TITLE
In file included from /usr/include/uv.h:62:0,              from test.c:2: /usr/include/uv-unix.h:61:30: fatal error: pthread-barrier.h: No such file or directory # include "pthread-barrier.h"  I am trying to compile using Nix. have installed the packeges. Getting this error while compiling with the h2o package. 

### ISSUE THREAD

**Issue by mrunalsanghvi** [libuv/libuv#2037]
* **Version**: 
compiling with h2o nix package in Centos OS. 

In file included from /usr/include/uv.h:62:0,              from test.c:2: /usr/include/uv-unix.h:61:30: fatal error: pthread-barrier.h: No such file or directory # include "pthread-barrier.h"  I am trying to compile using Nix. have installed the packeges. Getting this error while compiling with the h2o package.

**Comment by bnoordhuis** [comment]
> compiling with h2o nix package in Centos OS

This means nothing to me. You should report it to the downstream project (h2o? nix?) if it's not an official libuv release.

If it is an official release, please post the complete build output of a clean build.

**Comment by bnoordhuis** [comment]
Closing, no follow-up.
