### ISSUE TITLE
no longer 2.6.18（centos 5）？

### ISSUE THREAD

**Issue by ugenehan** [libuv/libuv#2047]
when i complie libuv1.23.2 on centos5 (2.6.18),Encountered an error：
linux-core.c:88: error: ‘EPOLL_CLOEXEC’ undeclared
EPOLL_CLOEXEC is supported above 2.6.27
but 1.23.0 can complied successful.
why it can not support 2.6.18?

**Comment by bnoordhuis** [comment]
From https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md:

> Linux >= 2.6.32 with glibc >= 2.12

Support for older kernels was dropped recently.
