### ISSUE TITLE
Anonymous structs in uv-win.h cause compile errors on MinGW GCC w/ -pedantic

### ISSUE THREAD

**Issue by justinddunlap** [libuv/libuv#205]
Anonymous structs, such as the one defined in UV_REQ_PRIVATE_FIELDS and other struct defines inside unions in uv-win.h, cause the following error: "ISO C++ prohibits anonymous structs". Naming all structs, even if they are inside unions, fixes these compile errors.

**Comment by saghul** [comment]
They show as warnings here, but yeah, pretty annoying. Would you mind submitting a patch?

**Comment by TomCrypto** [comment]
Is anyone currently working on this? I can have it done and submit a patch if no-one is. (the problem affects us as well, and so far we've had to drop the -pedantic flag for our C windows builds, which is less than optimal).

**Comment by bnoordhuis** [comment]
@TomCrypto No one is working on it AFAIK.  Patches are welcome and appreciated.

**Comment by saghul** [comment]
#239 landed, closing.
