### ISSUE TITLE
need uv_write_stop function

### ISSUE THREAD

**Issue by patrickkh7788** [libuv/libuv#2051]
I setup a write request like 10M data,  before the write is finished the timeout callback is run. need a function like uv_read_stop to prevent the write done callback is execute late.

not sure this is a bug or not.

* **Version**: latest 
* **Platform**: all

**Comment by bnoordhuis** [comment]
Can you talk more about what your application does? What do you do when the timer expires? Close the connection? You don't need a stop function in that case, just call `uv_close()`.

**Comment by patrickkh7788** [comment]
not just close the connection, I need to free the memory or decrease the pointer count.  

so when the callback is call,  the data pointer already reused in other context.  will create silent error.

**Comment by bnoordhuis** [comment]
> so when the callback is call, the data pointer already reused in other context

That sounds like you need to rethink your application's logic. How would a stop function help here?

> I also may reuse the connection to resend other package head.

As a workaround, don't send one big chunk, send small chunks. :-)

In theory, it's possible to teach `uv_cancel()` about write requests, except:

1. `uv_cancel()` is for cancelling requests that haven't started work yet. If we lift that restriction, then:

2. there is no way to tell the callback how much data was sent with the current `uv_write_cb` function signature (and changing the signature can't happen in libuv v1.x)

**Comment by patrickkh7788** [comment]
@bnoordhuis 

If I need use this with a private patch for myself, how do I implement this ?

just modify m_write_req ? or I has to add a uv_write_stop method for windows/unix ?

**Comment by bnoordhuis** [comment]
If you're going to float a patch, it's really up to you. Do what's easiest. Me, personally, I'd extend `uv_cancel()`.

**Comment by patrickkh7788** [comment]
If I call the close on the timeout, then the write callback will not run any more ?

is this one work for stop write ?

UV_EXTERN void uv_write_stop(uv_write_t* req, uv_stream_t* stream, int err){
    req->error = err;
    uv__write_req_finish(req);
    uv__io_stop(stream->loop, &stream->io_watcher, POLLOUT);
    uv__stream_osx_interrupt_select(stream);
}

**Comment by patrickkh7788** [comment]
@bnoordhuis 
If I call the uv_close, will the write callback be execute late ?

**Comment by bnoordhuis** [comment]
Yes. It's called with `status == UV_ECANCELED`.
