### ISSUE TITLE
need get down interface phys_addr from uv_interface_addresses

### ISSUE THREAD

**Issue by patrickkh7788** [libuv/libuv#2053]
can we add one more param to allow uv_interface_addresses skip the uv__ifaddr_exclude check ?
so we can get the phys_addr of down interface.

* **Version**: all
* **Platform**: all

**Comment by bnoordhuis** [comment]
That's probably acceptable for libuv v2. You're welcome to open a PR that targets the master branch.

**Comment by cjihrig** [comment]
I think this is more or less covered by the feature request in https://github.com/libuv/libuv/issues/158. I'll close this as a duplicate.
