### ISSUE TITLE
uv_pipe_open/uv_read_start regression in v1.23.1 and later

### ISSUE THREAD

**Issue by 1st1** [libuv/libuv#2058]
* **Version**: v1.23.1
* **Platform**: macOS 10.14

The following few lines (added in 40498795a and pushed to `v1.23.1`) seem to break `uv_pipe_open()` for pipes created with `pipe2()` / `pipe()`:

https://github.com/libuv/libuv/blob/6dd44caa35b4697d7e8c1b9fa0ba8e95d73355de/src/unix/pipe.c#L143-L148

I found this problem trying to upgrade [uvloop](https://github.com/MagicStack/uvloop) to `v1.23.2`; the [`test_write_pipe`](https://github.com/MagicStack/uvloop/blob/5f2e014dee922fff31a264ee148bfda22f5dcd55/tests/test_pipes.py#L137-L147) test crashes with "[Errno 57] Socket is not connected".  With the above few lines commented out everything works as expected.

**Comment by vtjnash** [comment]
Do you have a callstack or something more minimal? Perhaps `uvloop` is accidentally attempting to call `poll(readable)` on the pipe? macOS doesn't have a `pipe2` function, but I had tested `pipe` to check that it set these flags correctly:

```julia
julia> r = fill(Base.INVALID_OS_HANDLE, 2);
julia> @assert ccall(:uv_pipe, Cint, (Ref{RawFD}, Cint, Cint), r, 0, 0) == 0;
julia> r
2-element Array{RawFD,1}:
 RawFD(0x00000012)
 RawFD(0x00000015)

julia> const F_GETFL = 3;

julia> mode = ccall(:fcntl, Cint, (RawFD, Cint), r[1], F_GETFL)
0 # == RDONLY

julia> mode = ccall(:fcntl, Cint, (RawFD, Cint), r[2], F_GETFL)
1 # == WRONLY
```

**Comment by 1st1** [comment]
Yes, you're right, it's not those few lines that cause the error, it's an attempt to start receiving on the write-end of the pipe.  IIRC receiving on write-end is useful to receive a notification of the pipe being closed, right?

P.S. That julia repl stuff is cool!

**Comment by 1st1** [comment]
Following up on this:

The error indeed occurs when uvloop is calling `uv_read_start()` on the write end of the pipe.  It does so to get a signal (`UV_EOF`) via the `uv_read_cb` when the pipe is closed.  This seems to no longer work, which is a regression, and shouldn't have been committed to a bug-fix release.

What would be the next step? Should https://github.com/libuv/libuv/commit/40498795ab457dfa3a00a5aad45ba9db3bf71588 be reverted?  Or should `uv_read_start()` be allowed (again!) to be called on write-only FDs in `1.23.3`?  Or there's some workaround for me to use in uvloop?

**Comment by 1st1** [comment]
Ping...

**Comment by vtjnash** [comment]
We could perhaps add that functionality, but—aside from seeming like that usage would thwart flow-control—that doesn't sound like it would be a very portable assumption. If I try just a naive test, I see that the lowest-common-denominator (a simple blocking `read`) immediately returns with `EBADF`, as I would have expected (and as that commit tries to help now implement more uniformly):

```julia
julia> r = fill(Base.INVALID_OS_HANDLE, 2);

julia> @assert ccall(:uv_pipe, Cint, (Ref{RawFD}, Cint, Cint), r, 0, 0) == 0;

julia> r
2-element Array{RawFD,1}:
 RawFD(0x00000013)
 RawFD(0x00000014)

julia> ccall(:write, Cint, (Cint, Cstring, Csize_t), r[2], "abc\n", 4)
4

julia> b = "0000"; ccall(:read, Cint, (Cint, Cstring, Csize_t), r[1], b, 4), b
(4, "abc\n")

julia> b = "0000"; ccall(:read, Cint, (Cint, Cstring, Csize_t), r[2], b, 4), b, ccall(:jl_errno, Cint, ())
(-1, "0000", 9)
```

**Comment by 1st1** [comment]
Sure, but I need some solution to detect if write end is disconnected, otherwise libuv is forever broken for uvloop :(

> aside from seeming like that usage would thwart flow-control

Could you please elaborate on this?

> that doesn't sound like it would be a very portable assumption.

But... it always worked just fine up until bugfix v1.23.1 release.  Did we have a portability issue in libuv for all these years? IMO, v1.23.1 breaks backwards compat in a big way without offering any solution to how unbreak it.

I'll copy a few other devs just in case they can help us here: @saghul @bnoordhuis

**Comment by 1st1** [comment]
A kind ping.  I'm not sure why this issue is being ignored.  Uvloop is a critical piece of infrastructure and it's now stuck on an old version of libuv.  Maybe I'm not understanding something clearly, but to me it looks like there's a regression that needs to be taken care of.

**Please, libuv maintainers, reply to this thread.**  cc @cjihrig

**Comment by bnoordhuis** [comment]
I don't think it's a regression. You were relying on something that was underspecified and stopped working.

Let me see if I understand your workflow correctly. You:

1. have a file descriptor that's `O_WRONLY`.
2. pass it to `uv_pipe_open()`
3. then call `uv_read_start()` to check for EOF?

Wouldn't `uv_poll_start(handle, UV_READABLE|UV_DISCONNECT, cb)` work?

**Comment by 1st1** [comment]
Thank you so much for replying!

> You were relying on something that was underspecified and stopped working.

Yeah, it's not documented for libuv.  But waiting for disconnect events on `O_WRONLY` pipes is something that's allowed by select/poll/epoll, right?  Why is this isn't allowed in `uv_read_start` anymore?

> Let me see if I understand your workflow correctly. You:

Correct.

> Wouldn't uv_poll_start(handle, UV_READABLE|UV_DISCONNECT, cb) work?

Can I pass `uv_pipe_t` handle to `uv_poll_start`?  

Ideally I'd like to use stream handles for pipes because they are faster (and more convenient) than using `uv_poll*` APIs manually.  A lot of code in uvloop is shared between different types of streams (TCP/Unix/Pipes); using `uv_poll*` for pipes would require a lot of code rewrite.

**Comment by 1st1** [comment]
ping.

**Comment by 1st1** [comment]
I'm sorry to be that guy, but is it possible to grab attention of one of the libuv maintainers for one hour to either fix this issue or close it?  I can't update libuv in uvloop and I'm pretty much forced to fork libuv at this point.

@bnoordhuis @saghul

**Comment by saghul** [comment]
> > Wouldn't uv_poll_start(handle, UV_READABLE|UV_DISCONNECT, cb) work?
> 
> Can I pass `uv_pipe_t` handle to `uv_poll_start`?
> 
> Ideally I'd like to use stream handles for pipes because they are faster (and more convenient) than using `uv_poll*` APIs manually. A lot of code in uvloop is shared between different types of streams (TCP/Unix/Pipes); using `uv_poll*` for pipes would require a lot of code rewrite.

Have you tested it? You can get the fd out of a handle with uv_fileno and use a uv_poll_t disposable handle just for that check. I think that would work.

**Comment by 1st1** [comment]
> Have you tested it? You can get the fd out of a handle with uv_fileno and use a uv_poll_t disposable handle just for that check. I think that would work.

I remember libuv crashing in the early days of uvloop when I tried that.  I'll try again, thanks.

**Comment by 1st1** [comment]
Looks like it's indeed working. Thanks so much @bnoordhuis and @saghul. Closing this now.

**Comment by fantix** [comment]
Refs MagicStack/uvloop#317, the solution @bnoordhuis and @saghul suggested is not always working. I wrote a script below for testing, with all 3 solutions, none of them worked:

* A: `uv_poll_start` with a new `uv_poll_t` on the same fd
* B: `uv_read_start` on the same `uv_pipe_t` (commented out)
* C: `uv_poll_start` on the same `uv_pipe_t` (commented out)

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <uv.h>

uv_loop_t *loop;

void poll_cb(uv_poll_t* handle, int status, int events) {
    printf("poll_cb status=%d events=%d\n", status, events);
}
void alloc_cb(uv_handle_t* stream, size_t suggested_size, uv_buf_t* uvbuf) {
    uvbuf->base = malloc(suggested_size);
    uvbuf->len = suggested_size;
}


void read_cb(uv_stream_t* stream, ssize_t nread, const uv_buf_t* buf) {
    printf("read_cb nread=%zd\n", nread);
}

int main() {
    loop = uv_default_loop();

    int pipefd[2];
    if (pipe(pipefd) == -1) {
        perror("pipe");
        exit(EXIT_FAILURE);
    }

    uv_pipe_t tx;
    if (uv_pipe_init(loop, &tx, 0) < 0) {
        perror("uv_pipe_init");
        exit(EXIT_FAILURE);
    }
    if (uv_pipe_open(&tx, pipefd[1]) < 0) {
        perror("uv_pipe_open");
        exit(EXIT_FAILURE);
    }

    // A: This fails with:
    // Assertion failed: (loop->watchers[w->fd] == w), function uv__io_stop, file src/unix/core.c, line 935.
    // Abort trap: 6
    uv_poll_t poll;
    if (uv_poll_init(loop, &poll, pipefd[1]) < 0) {
        perror("uv_poll_init");
        exit(EXIT_FAILURE);
    }
    if (uv_poll_start(&poll, UV_READABLE | UV_DISCONNECT, poll_cb) < 0) {
        perror("uv_poll_start");
        exit(EXIT_FAILURE);
    }

    // B: This fails with: uv_read_start: Socket operation on non-socket
    // if (uv_read_start((uv_stream_t *)&tx, alloc_cb, read_cb) < 0) {
    //     perror("uv_read_start");
    //     exit(EXIT_FAILURE);
    // }

    // C: This fails with: Segmentation fault: 11
    // if (uv_poll_start((uv_poll_t *)&tx, UV_READABLE | UV_DISCONNECT, poll_cb) < 0) {
    //     perror("uv_poll_start");
    //     exit(EXIT_FAILURE);
    // }

    int r;
    uv_buf_t buf;
    buf.base = malloc(3);
    buf.len = 3;
    for (int i = 0; i < 65536; i++) {
        r = uv_try_write((uv_stream_t *)&tx, &buf, 1);
        if (r == 3) {
            printf("%d\n", i);
        } else {
            printf("RC %d\n", r);
            break;
        }
    }

    return uv_run(loop, UV_RUN_DEFAULT);
}
```

I might've done something terribly wrong here, but please kindly advise or maybe there's a solution D?

cc @1st1

**Comment by bnoordhuis** [comment]
@fantix Polling the same fd with two different `uv_poll_t` handles isn't supported at the moment, see #1172. I'd be open to a pull request that adds support for it but it's not trivial to implement, see the discussion in that issue.

There's an open pull request that makes `uv_poll_start()` return `UV_EEXIST` rather than have it fail with an assert, see #2686. That will probably show up in a libuv release in the near future.

**Comment by fantix** [comment]
@bnoordhuis thank you so much for the response! 

> 1. have a file descriptor that's O_WRONLY.
> 2. pass it to uv_pipe_open()
> 3. then call uv_read_start() to check for EOF?
>
> Wouldn't uv_poll_start(handle, UV_READABLE|UV_DISCONNECT, cb) work?

So if `uv_poll_start()` doesn't work for now, should we aim for making `uv_read_start()` work for `O_WRONLY` file descriptors again, or try to implement option 2 of #1172 still? After all, the last thing we want to do I think is to develop some custom implementation in uvloop to fork libuv in certain ways.

**Comment by bnoordhuis** [comment]
@fantix Multiplexing support is welcome anyway so yes, please. :-)

I'm not adamantly opposed to making `O_WRONLY` file descriptors work again with `uv_pipe_open()`, provided it doesn't need too many hacks and won't cause maintenance hassle down the road.

"Too many" is somewhat subjective but if you open a conversation starter PR, we'll take it from there.

**Comment by fantix** [comment]
Thanks for the suggestion! I'll try to create at least the 2nd PR to continue the discussion.
