### ISSUE TITLE
Windows: uv_exepath does not return resolved symbolic link

### ISSUE THREAD

**Issue by am11** [libuv/libuv#206]
//cc: @piscisaureus

[Redirected from: https://github.com/iojs/io.js/issues/851]

I think the solution is to replace the usage of `GetModuleFileNameW` at [util.c#L132](https://github.com/libuv/libuv/blob/f2bb8d394c06d06ee45e884600466321455751b6/src/win/util.c#L132) with either [`GetFinalPathNameByHandle`](http://msdn.microsoft.com/en-us/library/windows/desktop/aa364962.aspx), `GetFinalPathNameByHandleA` (ANSI variant of the previous) or (if required) even the low-level IOCTRL struct: [`DeviceIoControl`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364571.aspx).

Also See:
- https://msdn.microsoft.com/en-us/library/windows/hardware/ff552012.aspx
- http://www.opensource.apple.com/source/tcl/tcl-87/tcl84/tcl/win/tclWinFile.c <sub>(search for 'symbolic' and 'symlink')</sub>
- https://msdn.microsoft.com/en-us/library/cc232006.aspx
- http://stackoverflow.com/a/18792477

References:
- http://www.microsoft-questions.com/microsoft/Win32-Kernel/35464990/how-to-read-a-symbolic-link-is-there-a-posix-readlink-equivalent.aspx
- http://svn.python.org/projects/external/tcl-8.5.2.0/win/tclWinFile.c

**Comment by saghul** [comment]
Closing in favor of the PR in #293.
