### ISSUE TITLE
Failed test process_title_threadsafe

### ISSUE THREAD

**Issue by gireeshpunathil** [libuv/libuv#2063]
* **Version**: v1.x
* **Platform**: AIX, OS X

Reported earlier in #2041, seem to be failing in OS X too. Opening here to detach from #2041 that addressed a different issue from this one 

```
not ok 182 - process_title_threadsafe
# exit code 393222
# Output from process `process_title_threadsafe`:
# Assertion failed in test/test-process-title-threadsafe.c on line 50: 0 == strcmp(buffer, titles[0]) || 0 == strcmp(buffer, titles[1]) || 0 == strcmp(buffer, titles[2]) || 0 == strcmp(buffer, titles[3])
```

**Comment by gireeshpunathil** [comment]
the test logic is thus:

 - spawn 4 threads
 - run loops in each of those
 - keep changing the process title, values picked up from a static string list
 - run a loop that check the process title to be one among the list

intention seem to ensure data integrity at heavy multi-thread contention sites, and looks reasonable to me.

failure is very pronounced in CI systems, so I printed the expected and actual of the assert, got this:

```
9niCI5icXGFS72XudhXqo5alftmZ1tpE7B3cwUmrq0CCDjC84FzBNB8XAHqvpNQfI2QAQG6ztT
nniCI5icXGFS72XudhXqo5alftmZ1tpE7B3cwUmrq0CCDjC84FzBNB8XAHqvpNQfI2QAQG6ztT
```

first byte is corrupt!

ran several times, and observed the same pattern - single byte corruption, that attacking the first byte.

**Comment by gireeshpunathil** [comment]
reduced the title strings to 4 byte strings; still the test fails.

**Comment by gireeshpunathil** [comment]
if I eliminate the need of [process_title_ptr]( https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/src/unix/aix.c#L73) then the test passes, in several hundred iterations. don't know what compiler bug it could be.

**Comment by gireeshpunathil** [comment]
```patch
diff --git a/src/unix/aix.c b/src/unix/aix.c
index 92de814..6cf1051 100644
--- a/src/unix/aix.c
+++ b/src/unix/aix.c
@@ -70,7 +70,6 @@ static uv_once_t process_title_mutex_once = UV_ONCE_INIT;
 static void* args_mem = NULL;
 static char** process_argv = NULL;
 static int process_argc = 0;
-static char* process_title_ptr = NULL;
 
 static void init_process_title_mutex_once(void) {
   uv_mutex_init(&process_title_mutex);
@@ -866,15 +865,7 @@ int uv_set_process_title(const char* title) {
   uv_once(&process_title_mutex_once, init_process_title_mutex_once);
   uv_mutex_lock(&process_title_mutex);
 
-  /* If this is the first time this is set,
-   * don't free and set argv[1] to NULL.
-   */
-  if (process_title_ptr != NULL)
-    uv__free(process_title_ptr);
-
-  process_title_ptr = new_title;
-
-  process_argv[0] = process_title_ptr;
+  process_argv[0] = new_title;
   if (process_argc > 1)
      process_argv[1] = NULL;
```

this leaks memory, as we lose track of the existing title when setting a new one, but it resolves the  corruption; everything seem to be streamlined through the `process_title_mutex`.

trying to reason out on the behavior.

**Comment by richardlau** [comment]
Is it safe to `strlen(process_argv[0])` outside of the mutex in https://github.com/libuv/libuv/blob/e4087dedf837f415056a45a838f639a3d9dc3ced/src/unix/aix.c#L889?

**Comment by gireeshpunathil** [comment]
that may be rac-y, but given all the titles are of equal length (in this case), that does not look to be a problem source - for example, whether we got the length of the previous title or the next tile, it is always going to be the same.

**Comment by gireeshpunathil** [comment]
```patch
diff --git a/src/unix/aix.c b/src/unix/aix.c
index 92de814..64d78c4 100644
--- a/src/unix/aix.c
+++ b/src/unix/aix.c
@@ -856,15 +856,18 @@ char** uv_setup_args(int argc, char** argv) {
 int uv_set_process_title(const char* title) {
   char* new_title;
 
+  uv_once(&process_title_mutex_once, init_process_title_mutex_once);
+  uv_mutex_lock(&process_title_mutex);
+
   /* We cannot free this pointer when libuv shuts down,
    * the process may still be using it.
    */
   new_title = uv__strdup(title);
-  if (new_title == NULL)
+  if (new_title == NULL) {
+    uv_mutex_unlock(&process_title_mutex);
     return UV_ENOMEM;
+  }
 
-  uv_once(&process_title_mutex_once, init_process_title_mutex_once);
-  uv_mutex_lock(&process_title_mutex);
 
   /* If this is the first time this is set,
    * don't free and set argv[1] to NULL.
```

this patch caused the test to pass consistently for 2K iterations.  Though, TBH, I am not confident on the reason and the outcome. Can someone make an opinion? Is `uv__strdup` thread unsafe?

**Comment by gireeshpunathil** [comment]
disregard the previous comment  - prolonged run proved that this is also broken.

did this patch and saw alarming result:
```patch
diff --git a/src/unix/aix.c b/src/unix/aix.c
index 92de814..8dc66c7 100644
--- a/src/unix/aix.c
+++ b/src/unix/aix.c
@@ -895,7 +896,8 @@ int uv_get_process_title(char* buffer, size_t size) {
   uv_once(&process_title_mutex_once, init_process_title_mutex_once);
   uv_mutex_lock(&process_title_mutex);
 
-  memcpy(buffer, process_argv[0], len + 1);
+  memcpy(buffer, process_argv[0], len);
+  buffer[len] = NULL;
 
   uv_mutex_unlock(&process_title_mutex);
 ```

```trace
not ok 1 - process_title_threadsafe
# exit code 393350
# Output from process `process_title_threadsafe`:
# 
# Assertion failed in test/test-process-title-threadsafe.c on line 56: 0 == strcmp(buffer, titles[0]) || 0 == strcmp(buffer, titles[1]) || 0 == strcmp(buffer, titles[2]) || 0 == strcmp(buffer, titles[3])
997
```

at failing site, I had placed a printf of the buffer that receives the title on `uv_get_process_title` and see that it is empty!

so basically the memcpy did not copy anything, what we were seeing earlier were stale values in process_argv[0].

will debug further.

**Comment by gireeshpunathil** [comment]
I guess now I know what is happening. So @richardlau, your original [question]( https://github.com/libuv/libuv/issues/2063#issuecomment-435322487) seem to be valid, and very much relevant to the issue. This is the sequence I figured out that led to this one byte corruption:

 - so many `uv_set_process_title` and `uv_get_process_title` are being called, with the former on many threads, and the later on the main.
 - modification as well as retrieval of the title string is carried out under the cover of a mutex
 - the title string itself is a static non-local variable for persistence across calls.

 - in `uv_get_process_title` we calculate the length of the title string before entering the mutex. In the problematic scenario, this can cause:

    - A thread acquires the mutex and wants to modify the title
    - It sees the title has a value, so it frees it, before attaching the new one.
    - after it frees but before it could attach a new value, main thread calls getter method
    - main thread calculates the length of an already freed data, which it gets as 0.
    - later, when it acquires the lock, the other thread would have written the new string, but the length computed was 0.
    - so memcpy is attempted with (0+1 = 1) byte on the new string.
    - by +1 our intention was to copy NULL byte, but in this case as we are not copying the null, the one byte string continues through the remnant of the previous string, upto its length.

and hence this result. 

test case remains in tact, and a comprehensive fix IMO should be:

```patch
diff --git a/src/unix/aix.c b/src/unix/aix.c
index 92de814..e41b31d 100644
--- a/src/unix/aix.c
+++ b/src/unix/aix.c
@@ -886,16 +887,23 @@ int uv_set_process_title(const char* title) {
 
 int uv_get_process_title(char* buffer, size_t size) {
   size_t len;
-  len = strlen(process_argv[0]);
   if (buffer == NULL || size == 0)
     return UV_EINVAL;
-  else if (size <= len)
-    return UV_ENOBUFS;
 
   uv_once(&process_title_mutex_once, init_process_title_mutex_once);
   uv_mutex_lock(&process_title_mutex);
 
-  memcpy(buffer, process_argv[0], len + 1);
+  len = strlen(process_argv[0]);
+
+  if (size <= len) {
+    uv_mutex_unlock(&process_title_mutex);
+    return UV_ENOBUFS;
+  }
+
+  assert(len > 0);
+  
+  memcpy(buffer, process_argv[0], len);
+  buffer[len] = NULL;
 
   uv_mutex_unlock(&process_title_mutex);
 
```
Ran a 2K times and did not see any failure. I will raise a PR for this, but would appreciate if someone agrees to my theory.

**Comment by bnoordhuis** [comment]
Looks correct to me but the `len == 0` case shouldn't assert because why is that a bug?

`buffer[len] = NULL;` should be `buffer[len] = '\0';`.

**Comment by gireeshpunathil** [comment]
thanks @bnoordhuis 

> the len == 0 case shouldn't assert because why is that a bug?

sure, agree.

**Comment by bnoordhuis** [comment]
Was it timing out? Because #2064 might fix that.
