### ISSUE TITLE
memory leak after stop the loop

### ISSUE THREAD

**Issue by kelvin7feng** [libuv/libuv#2078]
* **Version**: libuv version 1.20.3
* **Platform**:Windows 7 64bit

I find that my application leaks memory after I stop it.
Visual Leak Detector detected 2 memory leaks.

The sample code:
`
#pragma comment(lib,"ws2_32.lib")
#pragma comment(lib,"Iphlpapi.lib")
#pragma comment(lib,"Psapi.lib")

#include <vld.h>
#include <stdio.h>
#include <uv.h>

void on_new_connection(uv_stream_t *server, int status) {
	printf("nothing");
}

static void callback(uv_timer_t *handle) {
	printf("stop the loop");
	uv_stop(uv_default_loop());
}

int main() {
	uv_loop_t* loop = uv_default_loop();
	
	uv_timer_t timer_req;
	uv_timer_init(loop, &timer_req);
	uv_timer_start(&timer_req, callback, 1000, 1000);

	uv_tcp_t server;
	struct sockaddr_in addr;
	uv_tcp_init(loop, &server);
	uv_ip4_addr("0.0.0.0", 7000, &addr);
	uv_tcp_bind(&server, (const struct sockaddr*)&addr, 0);

	int r = uv_listen((uv_stream_t*)&server, 128, on_new_connection);
	if (r) {
		fprintf(stderr, "Listen error %s\n", uv_strerror(r));
		return 1;
	}
	
	uv_run(loop, UV_RUN_DEFAULT);
	if (NULL == loop) {
		printf("nullptr");
	}
	else {
		printf("not null");
		uv_loop_close(loop);
		uv_close((uv_handle_t*)(&timer_req), NULL);
		uv_close((uv_handle_t*)(&server), NULL);
	}
	return 0;
}
`

I have colsed all the uv_handle_t.
What's the problem with this?

Thanks in advance.

**Comment by cjihrig** [comment]
I'm not sure what is reported as leaking, but does adding something similar to [`MAKE_VALGRIND_HAPPY()`](https://github.com/libuv/libuv/blob/32cccbc9f00696a4d07fa3b56d8b94ecbebb94a7/test/task.h#L108-L115) help?

**Comment by kelvin7feng** [comment]
> This looks bad to me:
> 
> ```
> 	uv_loop_close(loop);
> 	uv_close((uv_handle_t*)(&timer_req), NULL);
> 	uv_close((uv_handle_t*)(&server), NULL);
> ```
> You cannot close a loop before:
> 
> 1. Closing all handles;
> 2. Wait until their resources were freed, i.e. their closing callbacks have fired;
> 
> Instead, do something like that:
> 
> ```
> static void walk_cb(uv_handle_t *handle, void *arg) {
>   uv_close(handle, 0);
> }
> 
>   ...
>   uv_walk(loop, walk_cb, 0); /* Close all handles */
>   uv_run(loop, UV_RUN_DEFAULT); /* Run pending callbacks */
>   uv_loop_close(loop);
>   ...
> ```

Yes, you're right. I have fixed it and it can exit safely without memory leaks.
