### ISSUE TITLE
uv_interface_addresses doesn't list all interfaces

### ISSUE THREAD

**Issue by gremaudc** [libuv/libuv#208]
Hello everybody and thank for your work on libuv. I'm trying to use the function "uv_interface_addresses" to list all my network interfaces but this function has some problem. Firstly, it doesn't view the virtual interfaces like eth0:0, eth0:1 etc. For exemple, in my Ubuntu server, I have these interfaces : 

root@tntest:~/monitoring/nms_proxy# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:0c:29:19:f7:c8
          inet addr:192.168.10.1  Bcast:192.168.255.255  Mask:255.255.0.0

eth0:1    Link encap:Ethernet  HWaddr 00:0c:29:19:f7:c8
          inet addr:192.168.0.1  Bcast:192.168.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1

eth0:2    Link encap:Ethernet  HWaddr 00:0c:29:19:f7:c8
          inet addr:192.168.0.2  Bcast:192.168.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1

eth0:3    Link encap:Ethernet  HWaddr 00:0c:29:19:f7:c8
          inet addr:192.168.0.3  Bcast:192.168.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1

eth1      Link encap:Ethernet  HWaddr 00:0c:29:19:f7:d2
          inet addr:192.168.109.163  Bcast:192.168.109.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe19:f7d2/64 Scope:Link

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host

And the output of the following code : 

//Get informations about local interfaces
	uv_interface_address_t* inet_info;
	uv_interface_addresses(&inet_info, &count);
	
	int x;
	for(x = 0; x < count; x++)
	{
		uv_interface_address_t interface = inet_info[x];
		if (interface.address.address4.sin_family == AF_INET) 
		{
            uv_ip4_name(&interface.address.address4, buf, sizeof(buf));
            INFO("NMS_proxy: IPv4 address %s (%s) is available on the system\n", interface.name, buf);
        }
        else if (interface.address.address4.sin_family == AF_INET6) 
		{
            uv_ip6_name(&interface.address.address6, buf, sizeof(buf));
            INFO("NMS_proxy: IPv6 address %s (%s) is available on the system\n", interface.name, buf);
        }
	}
	uv_free_interface_addresses(inet_info, count);
	printf("\n");

return this output

NMS_proxy: IPv4 address lo (127.0.0.1) is available on the system
NMS_proxy: IPv4 address eth1 (192.168.109.163) is available on the system
NMS_proxy: IPv6 address lo (::1) is available on the system
NMS_proxy: IPv6 address eth1 (fe80::20c:29ff:fe19:f7d2) is available on the system

**Comment by saghul** [comment]
Please follow https://github.com/libuv/libuv/issues/158
