### ISSUE TITLE
freebsd: not ok 247

### ISSUE THREAD

**Issue by damon-kwok** [libuv/libuv#2080]
* **Version**:  git-v1.x  2018-1118
* **Platform**:freebsd
````
# uname -a
FreeBSD bsd 12.0-BETA1 FreeBSD 12.0-BETA1 r339435 GENERIC  amd64
````
```
ok 246 - tcp_connect_error_fault
not ok 247 - tcp_connect_timeout
# exit code 134
# Output from process `tcp_connect_timeout`:
# Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
ok 248 - tcp_create_early
```

**Comment by bnoordhuis** [comment]
Pull request welcome if you figure out the cause.

**Comment by ptlomholt** [comment]
I was not able to reproduce this on any of the FreeBSD 12 RC (RC1, RC2) builds, all tests were passing on these later builds. BETA1 that was used above is quite old, so @damon-kwok, can you try again with RC1 or RC2?

**Comment by damon-kwok** [comment]
@ptlomholt   the current os of my laptop is GhostBSD( FreeBSD-CURRENT)
````
# uname -a
FreeBSD damon.ghostbsd.home 12.0-CURRENT FreeBSD 12.0-CURRENT #0 7ad4fada6(HEAD): Thu Aug  2 11:37:15 EDT 2018     root@hydra:/usr/obj/root/jenkins/workspace/TrueOS_-_Stable_-_Complete/TrueOS_Stable/amd64.amd64/sys/GENERIC  amd64
````

```
ok 246 - tcp_connect_error_fault
not ok 247 - tcp_connect_timeout
# exit code 6
# Output from process `tcp_connect_timeout`:
# Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
ok 248 - tcp_create_early
```

**Comment by damon-kwok** [comment]
The behavior of 247 may be because I am in China, and often cannot access Google's DNS server，In my local connection test program, tcp connect_timeout not appear。
but 231 is a new failure.

**Comment by ptlomholt** [comment]
Looks like the tcp_connect_timeout issue was observed before; issue #1339 was resolved by @cjihrig as a network issue. The question is, is there a 'better' IP address that can be used, e.g. 254.254.254.254 or 0.42.42.42? I guess the trick is to choose one that is sure not to refuse the connection right away... It's not my area of expertise, maybe someone else can chime in here... 

You should probably open a new ticket for your other issue, `not ok 213 - spawn_setgid_fails` just to keep things separate.

**Comment by damon-kwok** [comment]
> issue #1339

**Comment by damon-kwok** [comment]
issue #2101
