### ISSUE TITLE
Potential dup'ing of a send_handle file descriptor in uv_write2()

### ISSUE THREAD

**Issue by neoxic** [libuv/libuv#2086]
Hello everybody,

Studying the code, I stumbled across a (potential) bug that leads to duplication of a file descriptor that is being sent via `uv_write2()`. Please consider the following scenario:

1) `req->send_handle` contains a file descriptor which is sent via `sendmsg()`;
2) Under load, `sendmsg()` returns the number of bytes actually written that is less than the overall length of `req->bufs`;
3) After adjusting `bufs` accordingly, the code goes back to `start:` and retries which leads to re-sending `send_handle` once again;

I assume `req->send_handle` must be nullified after the first successful write both in UNIX and Windows routines.

It's really hard to write a test-case for that since one needs to generate lots of load, and it still will be machine/OS dependent. To see the problem, one can simply emulate it like this:
```C
    do {
      n = sendmsg(uv__stream_fd(stream), &msg, 0);
      if (n > 0) n = 1; /* Emulate I/O oversubscription */
    }
```
This obviously leads to the same data being sent multiple times, but that's irrelevant. I can confirm that I observe dup'ed handles in my setup with this.

**libuv 1.x HEAD**

**Comment by bnoordhuis** [comment]
Are you using `UV_HANDLE_BLOCKING_WRITES`? That's the only way I could see that happening.

If the answer is 'no', then maybe we should just remove that flag. It's undocumented, untested and probably unloved.

If the answer is 'yes', I'd be curious to know what you're using it for.

**Comment by neoxic** [comment]
Oh, sorry, you probably got me too literally. By *the code goes back to start and retries*, I didn't mean right away. It obviously sets up a watcher a retries next time the watcher fires. But it's largely irrelevant since `req->send_handle` isn't reset or otherwise marked anywhere in the code to have been already sent. That causes it to be sent again the next time we reach `uv__write`.

**Comment by neoxic** [comment]
To put the issue another way, `req->bufs` is adjusted in `uv__write` for progressive re-entry through the use of `req->write_index`, pointer arithmetics, etc. whereas `req->send_handle` is never dealt with in the same way. That means that data is written properly in increments while `send_handle` is simply duplicated in case of  incomplete writes.

**Comment by bnoordhuis** [comment]
Yep, I see the issue. I have a fix in the works.
