### ISSUE TITLE
macos: UV_FS_COPYFILE_FICLONE_FORCE can fail without error

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2088]
From the documentation:

> `UV_FS_COPYFILE_FICLONE_FORCE`: If present, `uv_fs_copyfile()` will attempt to create a copy-on-write reflink. If the underlying platform does not support copy-on-write, then an error is returned.

Compile libuv on macos 10.12, execute on 10.11 and `UV_FS_COPYFILE_FICLONE_FORCE` doesn't error because:

1. `COPYFILE_CLONE_FORCE` was defined at compile time, but
2. the 10.11 version of copyfile() ignores the flag; it doesn't return an error

There doesn't seem to be a good way around it except:

1. Reimplementing copyfile() from scratch (bad idea imo), or
2. Detecting the macos version at runtime and adjust accordingly. I think this can be done by looking at the `kern.version` or `kern.osrelease` sysctls.

Option 2 can also be used to fix https://github.com/nodejs/node/issues/24521 because then we no longer have to #ifdef on the COPYFILE flags, we can hard-code their values.

Refs: https://github.com/nodejs/node/issues/24521#issuecomment-441116694

**Comment by cjihrig** [comment]
> 1. Reimplementing copyfile() from scratch (bad idea imo)

Agreed that we probably don't want to reimplement it, but maybe an option 1.b. would be to eliminate [this `#ifdef`](https://github.com/libuv/libuv/blob/0813f5b97afe086a7b4d827774605b1f2e99191c/src/unix/fs.c#L794-L817) and just use the Linux implementation. Option 2 is probably the better way to go though.
