### ISSUE TITLE
docs: provide types overview outlining inheritance relationship

### ISSUE THREAD

**Issue by thlorenz** [libuv/libuv#209]
Overview of all types and their relations like in the [TOC here](https://github.com/thlorenz/libuv-dox/blob/master/types.md) would help devs the type system better which is especially important when casting specific request types.

A list of all possible callback types would also be useful in my opinion. Similar [to this TOC](https://github.com/thlorenz/libuv-dox/blob/master/callbacks.md)

As well as a breakdown of methods by data/protocol type (streams, tcp, udp) as [in this TOC](https://github.com/thlorenz/libuv-dox/blob/master/methods.md).

**Comment by saghul** [comment]
> Overview of all types and their relations like in the TOC here would help devs the type system better which is especially important when casting specific request types.
> 

Agreed.

> A list of all possible callback types would also be useful in my opinion. Similar to this TOC
> 

I'd rather see this in the context of each handle, like we do now.

> As well as a breakdown of methods by data/protocol type (streams, tcp, udp) as in this TOC.

Same here.
