### ISSUE TITLE
build fail with gyp on macOS

### ISSUE THREAD

**Issue by lcw0622** [libuv/libuv#2093]
System:  macOS
Version: 10.13.6 (17G65)

I build libuv with this sequence of command as instruction in README:
```bash
git clone https://github.com/libuv/libuv.git
cd libuv
git clone https://chromium.googlesource.com/external/gyp build/gyp
./gyp_uv.py -f xcode
xcodebuild -ARCHS="x86_64" -project uv.xcodeproj \
     -configuration Release -target All
```
When I execute `./gyp_uv.py -f xcode`, console echos such information: 
```bash
['-f', 'xcode', '-I', 'common.gypi', 'test/test.gyp', '--depth=.', '-Goutput_dir=/Users/username/Fet/libuv/out', '--generator-output', '/Users/username/Fet/libuv/out', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Duv_library=static_library']
```
and then I execute: 
```bash
xcodebuild -ARCHS="x86_64" -project uv.xcodeproj \
     -configuration Release -target All
```
echo from console:
```shell
User defaults from command line:
    ARCHS = x86_64

xcodebuild: error: 'uv.xcodeproj' does not exist.
```
At last I found `uv.xcodeproj` has been generated at directory `out` from `gyp_uv.py`.
It seems the README should be updated to fix  incorrect build file directory ?
Or my environment has something wrong?

Thanks for reading. I'm not good at speaking English...

**Comment by bnoordhuis** [comment]
Yes, `out/` is the expected location; the README is wrong. Do you want to send a pull request?

**Comment by bnoordhuis** [comment]
I... think so? I don't use xcode myself.

**Comment by refack** [comment]
> -target All

`xcodebuild` [FAQ](https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-WHAT_KEYS_CAN_I_PASS_TO_THE_EXPORTOPTIONSPLIST_FLAG_) seems to hint at using `-alltargets` instead.
(But I don't use XCode either)

**Comment by lcw0622** [comment]
@refack Your right, and the build command will be this: 
```
xcodebuild -ARCHS="x86_64" -project out/uv.xcodeproj -configuration Release -alltargets
```
Now I know why such obvious error could be found in README....
T_T
