### ISSUE TITLE
revert "win,fs: retry if uv_fs_rename fails"

### ISSUE THREAD

**Issue by jorangreef** [libuv/libuv#2098]
https://github.com/libuv/libuv/commit/e94c184c7c4a18f3de569c97caeb83f4ff98a4b2 should be reverted for the following reasons:

1. It makes policy decisions at too low a layer, where it has insufficient information. What if the embedder of libuv wants to know when a rename is blocked by antivirus?

2. It adds up to 1 second of latency through 4 retry attempts of 250ms each, instead of doing what the user expects it to do, i.e. issue a single rename instruction to the file system.

3. We already have retry logic baked into our application to handle antivirus interference. Should we now remove this?

4. This antivirus issue is not limited to rename but affects other fs calls too. Should libuv apply the same logic there too?

5. In any event, 4 retry attempts of 250ms is hardly sufficient. We have seen instances of Panda antivirus preventing renames for up to 2 seconds and longer.

6. This papering over only serves to make a fairly common event rarer, encouraging developers not to think about these things... until they happen, and they will, except now they will be much more surprising. It would be better to surface these errors and educate developers, rather than "hide them and surprise them".

**Comment by jorangreef** [comment]
https://github.com/libuv/libuv/pull/1981/files#diff-aa0127b468d5b4716e070fce75ecdc54R1356 is also a recipe for disaster.

I work on a sync app which depends on knowing when a rename failed because of concurrent user action (e.g. a user copied a whole lot of files/directories at the same time as we try to sync the same content from another device).

libuv just deciding to randomly delete directories (even empty directories) is not cool.

**Comment by cjihrig** [comment]
cc @bzoz

**Comment by refack** [comment]
IMO we make it opt-in behind a flag.

**Comment by bnoordhuis** [comment]
Libuv doesn't really do flags. I wasn't a big fan of the change, I'd be okay with reverting it.

**Comment by refack** [comment]
> Libuv doesn't really do flags.

I already had been working on it https://github.com/libuv/libuv/pull/2100, but if no one likes it ¯\\_(ツ)_/¯
