### ISSUE TITLE
Android crash due to SYS_SECCOMP (illegal syscalls)

### ISSUE THREAD

**Issue by HormyAJP** [libuv/libuv#2105]
We've just started noticing crashes on Android x86_64 devices. We've never seen these before likely because there are hardly any such devices on the market. The device in question was Pixle Slate, but the following can be reproduced on the x86_64 simulator with Android 9 (and probably Android 8).

*REPRO*
* Create AVD with Android 9 and x86_64
* Run any code using libuv
* Observe crash with the following stack trace

```
Build fingerprint: 'google/sdk_gphone_x86_64/generic_x86_64:9/PSR1.180720.075/5124027:user/release-keys'
Revision: '0'
ABI: 'x86_64'
pid: 6144, tid: 6190, name: Thread-8  >>> XXX.XXX.XXX <<<
signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
Cause: seccomp prevented call to disallowed x86_64 system call 232
```

N.B. I can't provide our code but any libuv usage should crash.

The cause of this is due to new secuiryt features in android/linux:  https://android-developers.googleblog.com/2017/07/seccomp-filter-in-android-o.html

The offending code is `uv__epoll_wait` which makes the sys call `syscall(__NR_epoll_wait, epfd, events, nevents, timeout);`. The Android bionic source code shows the allowed list of syscalls here:

https://android.googlesource.com/platform/bionic.git/+/master/libc/SYSCALLS.TXT

Note that `epoll_wait` is not whitelisted, only `epoll_pwait` is. Android libc actually defines `epoll_wait` in terms of `epoll_pwait`:

```
int epoll_wait(int fd, struct epoll_event* events, int max_events, int timeout) {
  return epoll_pwait64(fd, events, max_events, timeout, nullptr);
}
```
(see https://android.googlesource.com/platform/bionic/+/master/libc/bionic/sys_epoll.cpp)

This is why users using libc rather than making direct syscalls will not be affected.

I believe the fix (at least for Android) is simply to use `__NR_epoll_pwait` rather than `__NR_epoll_wait`.

The only thing I'm not clear on here is why we don't see crashes on e.g. arm64 devices running Android 9. In theory this code should just not work on Android. I can only chalk that down to either seccomp not being enabled yet on those devices or Google have a bug in their implementation.

Note that the libuv code is also technically using the following illegal APIs:

* __NR_epoll_create
* __NR_inotify_init

However, these are only called as fallbacks if `__NR_epoll_create1` and `__NR_inotify_init1` fail for any reason. I might suggest also removing those fallbacks on Android as failures in those calls will crash Android apps.

**Comment by bnoordhuis** [comment]
Libuv 1.23.1 and up no longer make direct epoll syscalls.

(It still makes other direct syscalls so YMMV.)

**Comment by HormyAJP** [comment]
Ah, my bad. I thought I had master checked out but I was actually on some tagged 1.x branch.

**Comment by bnoordhuis** [comment]
Can this be closed then?

**Comment by HormyAJP** [comment]
Yes, I assume so. It'll take us a while to update to latest version but I'd assume that if you're not making direct sys calls then there'll be no issue 👍
