### ISSUE TITLE
not ok 119 - hrtime (aarch64)

### ISSUE THREAD

**Issue by mcepl** [libuv/libuv#2107]
* **Version**: 1.24.0
* **Platform**: Linux, SLE-12-P4 (architecture aarch64)
```
[   54s] not ok 119 - hrtime
[   54s] # exit code 6
[   54s] # Output from process `hrtime`:
[   54s] # Assertion failed in test/test-hrtime.c on line 50: diff < (uint64_t) 80 * NANOSEC / MILLISEC
```
[Complete build log](https://github.com/libuv/libuv/files/2658048/_log.txt)

**Comment by mcepl** [comment]
It fails rather consistently on this particular (enterprise, so a bit older, perhaps) version of the distribution.

**Comment by mcepl** [comment]
Hmm, I cannot reproduce it any more. Thank you for your patience.

**Comment by mcepl** [comment]
So, now I have introduced regular testing of 25-times running hrtime and I got [this log](https://github.com/libuv/libuv/files/2833566/_log.txt) and error:
```
++ seq 25
[  102s] + for i in $(seq 25)
[  102s] + test/run-tests hrtime hrtime
[  105s] + for i in $(seq 25)
[  105s] + test/run-tests hrtime hrtime
[  109s] + for i in $(seq 25)
[  109s] + test/run-tests hrtime hrtime
[  112s] + for i in $(seq 25)
[  112s] + test/run-tests hrtime hrtime
[  115s] + for i in $(seq 25)
[  115s] + test/run-tests hrtime hrtime
[  118s] Assertion failed in test/test-hrtime.c on line 50: diff < (uint64_t) 80 * NANOSEC / MILLISEC
[  118s] /var/tmp/rpm-tmp.d9JUjB: line 29: 18150 Aborted                 test/run-tests hrtime hrtime
```

**Comment by cjihrig** [comment]
I'm going to close this. It should have been addressed by https://github.com/libuv/libuv/commit/cdee607d482ad8b9f665541d3f092dd11f72e508.
