### ISSUE TITLE
Windows tty: duplicate key with alt modifier

### ISSUE THREAD

**Issue by parkovski** [libuv/libuv#2111]
* **Version**: Latest neovim / node
* **Platform**: Win10, 18298 

When pressing a key combo with alt, the non-alt key is duplicated. Because of some quirks in the way event messages are generated, this only appears when using libuv under a ConPTY. Probably the easiest way to see this is to start a Windows exe in tmux in WSL. I see the problem both in neovim and nodejs.

Here is a nodejs program that demonstrates the issue:
```javascript
process.stdin.setEncoding('utf8');
process.stdin.setRawMode(true);

process.stdin.on('data', x => {
  // Ctrl-C to quit
  if (x[0] == '\u0003') { process.exit(0); }
  console.log(x.length, x);
});

process.stdin.resume();
```
In a regular Windows console, or in a Linux terminal with or without a PTY, pressing for example, `Alt+a` will show `2 '\u001ba'`. In a ConPTY however, it shows `3 '\u001baa'`. This affects neovim, where a `<M-*>` keybinding also duplicates the key, breaking these bindings.

More info is [here](https://github.com/Microsoft/console/issues/320), including a screenshot of the difference in generated console events and the place in libuv where I think the problem is.

[This C++ program](https://gist.github.com/parkovski/940da5de5458df35f93db443936bdc54) will print all the generated console events, if it helps. Compile with C++17 (`cl /EHsc /std:c++17 console.cpp`).

**Comment by bzoz** [comment]
Thanks for the report. The line you suspected was to blame, fix for the issue is in https://github.com/libuv/libuv/pull/2114
