### ISSUE TITLE
cmake confgiure error

### ISSUE THREAD

**Issue by ohyeee** [libuv/libuv#2115]
* **Version**: 
* **Platform**: 
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-/libuv/1.9.1.tar.gz...
CMake Error at cmake/mason.cmake:95 (message):
  [Mason] Failed to download
  https://mason-binaries.s3.amazonaws.com/linux-/libuv/1.9.1.tar.gz: "HTTP
  response code said error"
Call Stack (most recent call first):
  cmake/mason-dependencies.cmake:8 (mason_use)
  CMakeLists.txt:75 (include)

I use cmake configure project,the prompt cannot download 1.9.1.tar.gz

**Comment by bnoordhuis** [comment]
I think you're reporting this to the wrong project. That URL is not maintained by us. Try reporting this to the Mason project.
