### ISSUE TITLE
not ok - fs_event_watch_dir_recursive and hrtime (MacOS)

### ISSUE THREAD

**Issue by frol** [libuv/libuv#2117]
```
not ok 58 - fs_event_watch_dir_recursive
# timeout
# Output from process `fs_event_watch_dir_recursive`: (no output)
...
not ok 120 - hrtime
# exit code 6
# Output from process `hrtime`:
# Assertion failed in test/test-hrtime.c on line 50: diff < (uint64_t) 80 * NANOSEC / MILLISEC
```

https://travis-ci.org/conda-forge/libuv-feedstock/jobs/468732638

* **Version**: 1.24.1
* **Platform**: TravisCI / Mac OS X 10.13.3 (Build Version: 17D102)

1.24.1 on Linux/MacOS and 1.24.0 on MacOS releases work just fine.

**Comment by bnoordhuis** [comment]
Some of the tests are timing-sensitive by nature, so some failures are expected if the machine is under high load. Is there a possibility for you to re-run the test suite a few times to see if they're persistent failures?

**Comment by frol** [comment]
I have re-run them 3 times (twice yesterday and once today just before I posted the issue) and the results are the same. This CI is [part of Conda Forge package manager](https://github.com/conda-forge/libuv-feedstock) and libuv test suite has been successfully passing all its tests since 1.6.1 release.

**Comment by bnoordhuis** [comment]
I've been going through the changes in the last few releases but there are no clear candidates that could be responsible. Is there a way for you to bisect?

**Comment by frol** [comment]
@bnoordhuis I will try to do that once I have some free time.

**Comment by frol** [comment]
@bnoordhuis I haven't had a chance to bisect the issue, so I only state the obvious facts here:

* 1.25.0 and 1.26.0 releases did not fix the issue (`hrtime` still fails on MacOS while passes no Linux)
* the same issue has been hit by NixOS maintainers on Linux: https://github.com/NixOS/nixpkgs/pull/54323#issuecomment-456906895

**Comment by bnoordhuis** [comment]
Looking at the test, I think it's simply making a bad assumption. I've opened #2186 to fix that.
