### ISSUE TITLE
Libuv dll compiled normally, exe uses this dll, run prompts can not find entry point！

### ISSUE THREAD

**Issue by cjl3230** [libuv/libuv#2119]
* **Version**: 1.24.1
* **Platform**: Windows xp

I compiled a libuv dll library on win10, then I compiled an exe on the xp machine to call this dll library, and the compiled is normal. But run this exe 
![default](https://user-images.githubusercontent.com/2327445/50131276-6e59d900-02bc-11e9-9733-fc93dea19212.png)

Unable to locate program input point GetQueueCompletionStatusEx on dynamic link library KERNEL32.dll

**Comment by bzoz** [comment]
Windows XP is not supported by libuv. See https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md for more details
