### ISSUE TITLE
New API proposal: uv_os_uname()

### ISSUE THREAD

**Issue by cjihrig** [libuv/libuv#2126]
I'm proposing adding `uv_os_uname(uv_utsname* buf)`. On non-Windows, it could be a wrapper around `uname(3)`. The Windows implementation would be more artisanal, but we could probably leverage previous work (https://github.com/gagern/gnulib/blob/master/lib/uname.c, https://github.com/python/cpython/blob/2.7/Lib/platform.py).

I'm willing to do the work if it seems feasible and a good idea. Thoughts?

**Comment by refack** [comment]
I think it makes a lot of sense. For example ATM the Node.js build infrastructure uses python in several places ([via the above mentioned code](https://github.com/python/cpython/blob/2.7/Lib/platform.py)) to abstract platform queries.

Might be out-of-scope, but IMO it will be helpful to be able to also distinguish between the various Linux distributions, and the various Windows POSIX like environments (cygwin, MinGW/MSYS and WSL). I'd be happy to help with that part.
