### ISSUE TITLE
not ok 103 - get_passwd seen on Debian test system

### ISSUE THREAD

**Issue by dod38fr** [libuv/libuv#2131]
* **Version**: 1.24.0
* **Platform**: 
Package: libuv1
Version: 1.24.0-1
Source Version: 1.24.0-1
Distribution: unstable
Machine Architecture: amd64
Host Architecture: amd64
Build Architecture: amd64
Build Type: full

A test has failed once during Debian automatic tests:
```
> ok 102 - get_osfhandle_valid_handle
> not ok 103 - get_passwd
> # exit code 6
> # Output from process `get_passwd`:
> # Assertion failed in test/test-get-passwd.c on line 41: len > 0
```

This is not systematic as the package was built with success (this build performs the same tests). I do not know what could have triggered this test failure.

For more details, please see:
* [Debian bug #917718](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917718)
* The full [test log](aws-logs.debian.net/2018/12/29/libuv1_1.24.0-1_unstable.log)

All the best

**Comment by cjihrig** [comment]
That line asserts that the current user's shell in the password file is greater than zero. Do you happen to know what that particular password file entry looks like?

**Comment by dod38fr** [comment]
@lnussbaum, since you submitted this [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917718)  on Debian side, do you have the answer to @cjihrig  question ?

All the best

**Comment by dod38fr** [comment]
Luces replied:

> I can confirm that this bug is a false positive: when I setup the build
> environment, I created the user without a shell, which apparently caused
> this failure.
> 
> I can confirm that it builds fine now. I'm closing the bug (and I'm
> looking into other bugs I filed in the same process).

Sorry for the noise.

All the best
