### ISSUE TITLE
ipc_listen_before_write macos CI failure

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#2132]
```
not ok 127 - ipc_listen_before_write
# timeout
# Output from process `ipc_listen_before_write`:
# got 6 bytes
# got 20 bytes
# exit_cb
```

https://ci.nodejs.org/job/libuv-test-commit-osx/1144/nodes=osx1011/console

**Comment by cjihrig** [comment]
@vtjnash have you (or anyone else) run into this again? I don't think I've ever observed this while working on a mac. If it's no longer an issue, I'd like to close this out.

**Comment by vtjnash** [comment]
Did something change in the last couple months? I've done very few CI runs since then, so I couldn't really say.

**Comment by cjihrig** [comment]
> Did something change in the last couple months?

Nothing specifically targeting this that I'm aware of. All of the recent macOS CI runs have been green though - https://ci.nodejs.org/job/libuv-test-commit-osx/.

**Comment by bnoordhuis** [comment]
I can make this test fail very sporadically on my MBA with the exact same error message:
```
$ uname -a
Darwin hermes.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

```
$ for i in {1..250}; do ./out/Debug/run-tests ipc_listen_before_write || break; done
# ...
k 1 - ipc_listen_before_write
ok 1 - ipc_listen_before_write
ok 1 - ipc_listen_before_write
not ok 1 - ipc_listen_before_write
# timeout
# Output from process `ipc_listen_before_write`:
# got 6 bytes
# got 20 bytes
# exit_cb
```
