### ISSUE TITLE
OpenBSD: IPv6 tests are skipped

### ISSUE THREAD

**Issue by ptlomholt** [libuv/libuv#2137]
On OpenBSD most IPv6 tests are skipped because `uv__ifaddr_exclude()` only filters IPv4 addresses for this platform, resulting in `can_ipv6()` returning 0. After letting `uv__ifaddr_exclude()` also filter IPv6 addresses, unit tests run and pass except for the `udp_options6` test, which fails because of failures from `uv_udp_set_multicast_ttl(`) and `uv_udp_set_multicast_loop()`.

#2136 should address those issues - all IPv6 tests pass after applying this change. (Note, there are still some other tests that are failing on OpenBSD!)

* **Version**: 1.24.1
* **Platform**: OpenBSD openbsdholt.localdomain 6.4 GENERIC.MP#364 amd64

**Comment by cjihrig** [comment]
This should be closed by https://github.com/libuv/libuv/pull/2136.
