### ISSUE TITLE
Error building Arangodb on Nixos 18.0.3

### ISSUE THREAD

**Issue by wpoosanguansit** [libuv/libuv#2146]
I am trying to build Nixos with arangodb and I have got the following error:

* **Version**: libuv-1.19.2
* **Platform**: Nixos 18.0.3

FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:4578: check-TESTS] Error 1
make[1]: Leaving directory '/tmp/nix-build-libuv-1.19.2.drv-0/source'
make: *** [Makefile:4835: check-am] Error 2
builder for '/nix/store/szgra10rm8hghapn13wls8h98wrjwxc1-libuv-1.19.2.drv' failed with exit code 2
cannot build derivation '/nix/store/fdrfqwzxapxnhfshdq6gjdllqlqaiskf-cmake-3.10.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2wc4rqxxvl1xwaw0c6jca0ywlivyddzk-arangodb-3.3.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4gywvkzqg41l7yj8fv89srqh30kj3g8b-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8jd5vkcvlpdypp1szbq89cvqw58rh8vi-nixos-system-nixos-18.03.133311.5d19e3e78fb.drv': 1 dependencies couldn't be built
error: build of '/nix/store/8jd5vkcvlpdypp1szbq89cvqw58rh8vi-nixos-system-nixos-18.03.133311.5d19e3e78fb.drv' failed

**Comment by wpoosanguansit** [comment]
I do not have any other information than:

ok 314 - walk_handles
ok 315 - watcher_cross_stop
ok 316 - we_get_signal
ok 317 - we_get_signal_one_shot
ok 318 - we_get_signals
ok 319 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:4578: check-TESTS] Error 1
make[1]: Leaving directory '/tmp/nix-build-libuv-1.19.2.drv-0/source'
make: *** [Makefile:4835: check-am] Error 2
builder for '/nix/store/szgra10rm8hghapn13wls8h98wrjwxc1-libuv-1.19.2.drv' failed with exit code 2
cannot build derivation '/nix/store/fdrfqwzxapxnhfshdq6gjdllqlqaiskf-cmake-3.10.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2wc4rqxxvl1xwaw0c6jca0ywlivyddzk-arangodb-3.3.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4gywvkzqg41l7yj8fv89srqh30kj3g8b-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8jd5vkcvlpdypp1szbq89cvqw58rh8vi-nixos-system-nixos-18.03.133311.5d19e3e78fb.drv': 1 dependencies couldn't be built
error: build of '/nix/store/8jd5vkcvlpdypp1szbq89cvqw58rh8vi-nixos-system-nixos-18.03.133311.5d19e3e78fb.drv’ failed

Hope this helps ping things down.

**Comment by bnoordhuis** [comment]
One or more of the tests should say 'not ok'.

**Comment by bnoordhuis** [comment]
No follow-up, closing.
