### ISSUE TITLE
Proposal: Perform stat requests using statx on Linux

### ISSUE THREAD

**Issue by fer22f** [libuv/libuv#2152]
So last year in August [glibc 2.28 was released](https://www.sourceware.org/ml/libc-alpha/2018-08/msg00003.html) with a new function: `statx`. It's rather new but it brings some niceties:

* Fixes the [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem) in regards to file systems. `stat` returns a `timespec` which is 32 bits long, but `statx` returns 64 bits even if the kernel doesn't yet support `statx` (using `fstatat64`)
* Birthtime finally works correctly in ext4, which previously required `debugfs` and other hacks as previously discussed in https://github.com/libuv/libuv/pull/481#issuecomment-131730337 and https://github.com/libuv/libuv/issues/499#issuecomment-137717464
* Adds some useful flags for remote filesystem synchronization which may be useful to expose
* Returns some extra file attributes like encrypted, compressed, immutable, etc.

Overall, it's a positive change, however, I don't know how closely `libuv` requires `glibc` to be versioned and related problems with ABI, so I don't know how that could be addressed.

**Comment by bnoordhuis** [comment]
We can't easily change `uv_fs_t` in v1.x without breaking ABI so birthtime would be the most compelling reason to switch.

It's probably less hassle to make the system call directly than go through glibc because the run-time and compile-time baseline for libuv is glibc 2.12.
