### ISSUE TITLE
would you consider maintaining support for macOS < 10.7 as Tier 3?

### ISSUE THREAD

**Issue by kencu** [libuv/libuv#2157]
On MacPorts we make reasonable efforts to keep older system versions in the mix, if we can. There are still a number of older Apple systems running < 10.7 due to hardware issues, etc. 

libuv is used by many packages now (kudos!) and up until v 1.24.1 it compiled nicely and passed all tests on 10.5 and up.

But now `fsevents.c` has removed the < 10.7 fallback code, so the build fails. This will mean whole classes of older hardware become unusable soon. Time goes by, sooner or later those systems must die, certainly, but ...

I can patch libuv to put that support back in again, but I'm wondering -- given how close you are to supporting those systems already and if it's not felt to be unreasonable extra work -- you might consider  leaving the < 10.7 fallbacks in place, even as a Tier 3 system? 

It's really the mac-only SDK support we're talking about, as we have current compilers and thread_local storage all working on these systems so there are no toolchain constraints there.

**Comment by bnoordhuis** [comment]
If it helps you out and it's not too much hassle for us maintainers, I think we'd be open to that.

Do you have usage numbers though? If it's only 5 people, figuratively speaking, it's arguably not worth the effort.

**Comment by bnoordhuis** [comment]
@kencu Do you want to open a PR to reinstate support for pre-10.7?

**Comment by kencu** [comment]
I will, and thank you!

**Comment by kencu** [comment]
@emcrisostomo -- given your demonstrated skills in this area, would you be at all interested in helping make sure I get this right? I would plan to use "fs_events" for 10.7+, and fallback to BSD kqueue on 10.4 to 10.6. Most of the  details are already in place. I would disable the fs_events.c for older MacOS (as it is already disabled for iphoneOS), and then try to institute/retain as much as possible in the kqueue.c subsystem.

**Comment by bnoordhuis** [comment]
I'm going to close out this issue because there isn't anything actionable right now for us maintainers but a pull request is of course still welcome. Thanks!
