### ISSUE TITLE
benchmark-multi-accept failed in Windows

### ISSUE THREAD

**Issue by pony5551** [libuv/libuv#2158]
* **Version**: 1.x
* **Platform**: windows10

Is there any final solution to this problem?

Or multi-accept without pipe?

**Comment by bnoordhuis** [comment]
Describe 'failed'? Can you post the output?

**Comment by pony5551** [comment]
> Describe 'failed'? Can you post the output?


Assertion failed in d:\svncheck\libuv\test\benchmark-multi-accept.c on line 126: 0 == uv_accept(ipc_pipe, (uv_stream_t*) &pc->peer_handle)

uv_accept returns UV_EAGAIN


The same question was raised here! https://github.com/libuv/libuv/issues/394



Is this problem unsolvable? Or please give an example of multi accept without pipe!

Thank you for your reply!

**Comment by pony5551** [comment]
But something did go wrong! You can test it yourself!

thanks

**Comment by wupeka** [comment]
I'm trying to use code similar to benchmark-multi-accept and hit the same issue - in a callback from uv_listen on uv_pipe I'm calling uv_accept and getting EAGAIN - which, according to the documentation, should never happen (uv_accept should always succeed).
