### ISSUE TITLE
Should uv_os_uname also provide the processor (-p) info?

### ISSUE THREAD

**Issue by ugexe** [libuv/libuv#2159]
Should `uv_os_uname` also provide the processor information?
```
ugexe@Nicholass-MBP:~/repos$ uname -p
i386
```
Or is this not portable enough to include?

**Comment by cjihrig** [comment]
> Or is this not portable enough to include?

I haven't looked into this. If the information is available on all (or at least most) of the platforms we support, we could expose it.

**Comment by saghul** [comment]
This information is already available in the `machine` field. On the platforms that fill it in, that is.

**Comment by ugexe** [comment]
It may not always be derived from the `machine` field:

```
ugexe@Nicholass-MBP:~/repos/zef$ uname -m
x86_64
ugexe@Nicholass-MBP:~/repos/zef$ uname -p
i386
```

What I gathered was that some distros patch `uname -p`, and so there isn't a good way to provide this in libuv.

**Comment by saghul** [comment]
Oh, my bad, sorry about that. TBH I'm not sure why it reports i386 on a modern mac.
