### ISSUE TITLE
Compilation errors with g++ and clang

### ISSUE THREAD

**Issue by informer2000** [libuv/libuv#216]
I'm trying to compile some C++ examples that use libuv. However, the compiler keeps complaining about the function `uv_tty_set_mode()` in `uv.h`. The error I'm getting is the following.

```
uv.h:648: error: declaration of C function 'int uv_tty_set_mode(uv_tty_t*, int)' conflicts with inline int uv_tty_set_mode(uv_tty_t* handle, int mode).

uv.h:641: error: previous declaration 'int uv_tty_set_mode(uv_tty_t*, uv_tty_mode_t mode)' here
UV_EXTERN int uv_tty_set_mode(uv_tty_t*, uv_tty_mode_t mode);
```

Any ideas on how to resolve this? I faced the same error on Yosemite with clang.

**Comment by bnoordhuis** [comment]
Shrug.  Works for me.  I don't see a reason why it wouldn't either.

**Comment by informer2000** [comment]
I'm still unable to overcome this. The compilers I've checked were:

* gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
* Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)

**Comment by bnoordhuis** [comment]
Does io.js build for you?  It bundles a version of libuv that has the new uv_tty_init() prototype.

**Comment by informer2000** [comment]
Yes, I was able to build io.js without any problems. What is confusing me is that I am able to build and install libuv itself without issues. It's the example code that I have (from libh2o) which includes `uv.h` that does not want to compile and the compiler complains about that declaration in `uv.h`. Below is the compilation command and the passed flags.

```
g++ -c -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIE -DQT_CORE_LIB -I/opt/Qt5.4.0/5.4/gcc_64/mkspecs/linux-g++ -I../TestH2O -I/usr/local/include -I/usr/local/include/klib -I/opt/Qt5.4.0/5.4/gcc_64/include -I/opt/Qt5.4.0/5.4/gcc_64/include/QtCore -I. -I. -o main.o ../TestH2O/main.cpp
```

**Comment by informer2000** [comment]
Hmm.. I just created some test code with an empty main function and including `uv.h` only. It seems to compile without any errors. I guess it must be something related to the `h2o.h` file which includes `uv.h`.

**Comment by saghul** [comment]
Closing since it doesn't seem to be a libuv issue. Please ask for a reopen in case you do find libuv doing something wrong.
