### ISSUE TITLE
Would it be wise to come up with some kind of standardisation effort for libuv?

### ISSUE THREAD

**Issue by EdSchouten** [libuv/libuv#2164]
Experience has shown that if a new feature is added to C++, discussions often take place to add the fundamentals necessary to facilitate those features on the OS side. Those discussions either take place in the C working group or the POSIX working group. A prime example is threading and atomics, which got added to C++11. Intrinsics for those are part of C11. The rationale being that without a C counterpart, it's hard(er) to implement those features in C++ and to have proper interoperability between those two languages (and other languages that build on top of C runtimes, like Rust).

C++2a will feature support for coroutines. To be able to use coroutines to their full extent, there will likely be an increase in demand for a standardized event loop. Preferably, such an event loop would work well from within C and C++ code. If no event loop is standardised, we should at least see if we could finally get some kind of scalable polling framework is added. POSIX's `poll()` and `select()` are close to useless at his point.

Some time ago I contacted the people from the POSIX working group, asking whether they share my opinion. In particular, I asked them whether standardising libevent, libev or libuv would be within scope:

http://austingroupbugs.net/view.php?id=1165

A couple of minutes ago, they responded this:

> The Austin Group would welcome a fully formed proposal along these lines, including support from the current maintainers of whatever package is selected. See also https://www.opengroup.org/austin/docs/austin_sd6.txt for guidelines on submitting new material.

So there you have it. Apparently the POSIX folks are open to the idea of standardising an event loop. Considering that libuv is the most popular one (merely counting stargazers/watchers on GitHub), I thought I'd reach out to you folks first. Is there any support for doing something like this within your community?

**Comment by bnoordhuis** [comment]
I'll need to think through the ramifications for a bit but anything that makes my life easier long-term, I'll be glad to support. :)

**Comment by gireeshpunathil** [comment]
this is exciting! to see the loop under a standard.

 - will it make sense for `libuv` to be forming as part of a language such as C or C++?
 - will it make sense to use the master version of `libuv` to be used as the reference impl?
 
I guess the current `libuv` has a lot of code that is used to abstract the underlying platform differences, to aid the embedders. When standardized, those can go away and what could be exposed is the core of the event machinery that might look like:

```c
uv_loop_t* loop = uv_loop_init();
uv_loop_add(uv_req_t* request);
uv_loop_del(uv_req_t* request);
uv_loop_start(uv_loop_t* loop);
uv_loop_stop((uv_loop_t* loop);
```
where `uv_req_t` is an abstraction of all the standardized events. thoughts?

**Comment by saghul** [comment]
> where `uv_req_t` is an abstraction of all the standardized events. thoughts?

And where are the handles? I'm all for turning as much as we can into requests, but many requests would refer to handles, like a write request which is sent through a handle.

**Comment by gireeshpunathil** [comment]
@saghul - I admit I did not go (or think) to that level of detail.

IMO if handles are exposed I guess these abstractions bloat up considerably? If that is something which these APIs can reflect and process under the cover, I think that makes it more flexible.

**Comment by bnoordhuis** [comment]
I still think this is a good idea, reopening.
