### ISSUE TITLE
Build error on Android api level 19

### ISSUE THREAD

**Issue by BillHoo** [libuv/libuv#2167]
* **Version**: 1.24.1
* **Platform**: Android API 19

Hi there,

I'm port libuv to Android using Android Studio + cmake.
Our android app must support API 19, when I build libuv, it gives me following errors:

`libuv\libuv-1.24.1\src\unix\linux-core.c:88:22: error: use of undeclared identifier 'EPOLL_CLOEXEC'
  fd = epoll_create1(EPOLL_CLOEXEC);`

I've already googled and it seems a bug in libuv when handling EPOLL_CLOEXEC:

https://stackoverflow.com/q/53195673/2010078

https://github.com/android-ndk/ndk/issues/394

Could libuv support Android API 19 in the feature? if so when?

Thanks

**Comment by saghul** [comment]
I don't think we support 19. The compile scripts we have have 24 listed, so I assume that's what we support.

We should put this in SUPPORTED_PLATFORMS.md.

**Comment by bnoordhuis** [comment]
API 19 corresponds to Android 4.4 and that ships kernel 3.10. That's new enough to know about the `EPOLL_CLOEXEC` flag so this sounds like a problem with the Android SDK, not libuv.

Android is self-support but if there's an easy fix (like ifdef-ing `EPOLL_CLOEXEC`) you're welcome to send a pull request.

**Comment by bnoordhuis** [comment]
I'm going to close this out but a pull request is still welcome!

**Comment by kyze8439690** [comment]
@BillHoo Api level 21 is not fully supported because there is some method not supported like below:

Not supported until api level 24
```
preadv()
pwritev()
```

Not supported until api level 28
```
getrandom()
```

Not supported at all
```
preadv()
pwritev()
```
