### ISSUE TITLE
Windows tty: duplicate special keys

### ISSUE THREAD

**Issue by Ezekiel-DA** [libuv/libuv#2168]
* **Version**: 1.25.0
* **Platform**: Windows (10, x64 - would likely affect all version of Windows)

Hi,

I have been investigating an issue with a command line Node tool that I maintain; after tracking it down through issues in [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/issues/778) and [Node.js](https://github.com/nodejs/node/issues/25875), I believe the issue originates in libuv 1.25.0.

This minimal Node.js script will reproduce the problem:
```javascript
const readline = require('readline')
const process = require('process')

let rl = readline.createInterface({terminal: true, input: process.stdin, output: process.stdout})
rl.resume()
rl.input.on('data', (chunk) => {
  console.log(`Received ${chunk.length} bytes of data - content was: ${chunk}`)
})
```
Run it, press a special key (e.g. down arrow) and see that two events are received. Revert to Node pre updgrade to libuv 1.25.0 (e.g. 11.7.0) to see the expected behavior.

I believe this is a regression introduced by d2e59bb6003d707bdebd7a381f5a7e1d0cc3fd3b, which was attempting to fix https://github.com/libuv/libuv/issues/2111 and was merged as https://github.com/libuv/libuv/pull/2114.

Specifically, this new code in `src/win/tty.c` is problematic:
```cpp
/* Ignore keyup events, unless the left alt key was held and a valid
 * unicode character was emitted. */
if (!KEV.bKeyDown &&
    KEV.wVirtualKeyCode != VK_MENU &&
    KEV.uChar.UnicodeChar != 0) {
  continue;
}
```

it replaces this test:
```cpp
if (!KEV.bKeyDown && !(((KEV.dwControlKeyState & LEFT_ALT_PRESSED) ||
    KEV.wVirtualKeyCode==VK_MENU) && KEV.uChar.UnicodeChar != 0)) {
  continue;
}
```

But does not have equivalent behavior because the grouping together of the condition on the menu key and on the emitted character was dropped. On key up of a special key without menu held, the third clause is `false`, so the `continue` is not hit and a spurious event is emitted.

Simplifying for the test on `LEFT_ALT_PRESSED` apparently being useless (according to that PR), the old code was:
```cpp
if (!KEV.bKeyDown && !(KEV.wVirtualKeyCode==VK_MENU && KEV.uChar.UnicodeChar != 0)) {
  continue;
}
```
which, in keeping with the attempt to simplify by removing the negation of the parenthesized group, would boil down to:
```cpp
if (!KEV.bKeyDown && (KEV.wVirtualKeyCode!=VK_MENU || KEV.uChar.UnicodeChar == 0)) {
  continue;
}
```

I'm happy to create a PR with the above but I'm not familiar with this repo at all so it might take longer for me to do so than it would for a maintainer 😁 

Let me know if my logic makes sense and if you'd like a PR!

**Comment by erw7** [comment]
Regarding this problem I already created PR on #2160.

**Comment by bnoordhuis** [comment]
Paging @bzoz. FWIW, I came to the same conclusion, that it's caused by d2e59bb60.

**Comment by cjihrig** [comment]
@Ezekiel-DA are you (or anyone else on Windows) able to apply [this two line change](https://github.com/libuv/libuv/pull/2160/files#diff-16746be892849b2c5daf1be3613ed28c), rebuild Node.js, and see if it fixes the problem?

**Comment by Ezekiel-DA** [comment]
@cjihrig it does, that is literally the same code I arrived at in the post above. I should have mentioned that I did rebuild Node with it and my basic test passed 😁
