### ISSUE TITLE
`uv_stop()` doesn't stop immediately

### ISSUE THREAD

**Issue by leonerd** [libuv/libuv#2173]
Situation: I have a `SIGINT` handler in which I call `uv_stop()`. But the loop doesn't stop quite yet; it waits until the end of whatever timeout or other IO events it is waiting on first, and then stops. This could be many seconds away. In particular, I know my signal handler runs in a timely fashion because I put a printf in it, which appears at the right time on the terminal. The problem is that libuv hasn't stopped yet.

A solution to this is simply to add an empty `uv_async_t` with no callback function, which I `send` to after calling `uv_stop()`; this wakes the loop up and then finds it has to stop, so it stops promptly.

Most other event systems (e.g. GLib) don't need this sort of workaround; calling `g_main_quit()` is instant even from inside a signal handler.

I suspect this one may be related to incorrect handling of `EINTR` from the underlying `epoll_pwait()` call; I shall have a read of source code to investigate.

**Comment by leonerd** [comment]
I suspect this issue may be easily fixed by inspecting `loop->stop_flag` after we observe that an `EINTR` has happened, and returning early.

Basically just insert

```c
    if(loop->stop_flag)
      return;
````

around the point

https://github.com/libuv/libuv/blob/v1.x/src/unix/linux-core.c#L305

**Comment by leonerd** [comment]
Indeed it is. With the code adjusted as per my PR, my example program now stops immediately on `SIGINT`

**Comment by vtjnash** [comment]
The system might deliver a `SIGINT` (indeed, I believe I've seen that it is documented to be more likely on linux than on a typical unix system), but it's not required to do so. It seems you already mentioned one correct solution (involving uv_async_t), libuv also can register to listen for the signal events directly and report those directly back to you in the form of callbacks.

**Comment by leonerd** [comment]
Oh sure; there's various reasons why `SIGINT` might or mightnot happen. My bug isn't really about that though, it's about `uv_stop()` not being immediate and needing that workaround. The bug comes from the fact that none of the looping functions check the value of `loop->stop_flag` after `EINTR`

**Comment by vtjnash** [comment]
Why should they? It's not a reasonable expectation for that EINTR to even happen—the kernel may also decide not to wake the thread up either (and that's definitely not a libuv bug).

**Comment by vtjnash** [comment]
As you mentioned in the initial post, `uv_stop` doesn't work because it is the wrong function to call, while calling the correct function (`uv_async_send`) works as intended.

**Comment by saghul** [comment]
@leonerd Am I right assuming your signal handler is not a libuv `uv_signal_t` handle? `uv_stop` is not thread-safe, you must call it from the loop thread. If you are not in the loop thread you can use an async handle and call `uv_stop` in the `uv_async_send` callback.

Basically, you seem to want `uv_stop` to be thread-safe, but it's not (and I don't think it'll ever be, unless we make the entire API thread-safe).

**Comment by leonerd** [comment]
>  1. @leonerd wants `uv_stop()` to be instantaneous(ish). Currently it's not, it's only checked at the "edge" of the event loop tick, but that could be changed. However, there is a minor performance trade-off that we may feel isn't worth it.

My PR (#2174) fixes this with, what I believe is a very minimal performance impact; it simply changes code in the case when an `EINTR` happens. That won't affect any other occasion, and restarting after `EINTR` is already sufficiently involved that a single extra integer load/test isn't going to make a big difference there.

Overall it does seem a shame that libuv isn't making use of `EINTR` in this way, given as this is precisely the situation that `EINTR` was added into UNIX in the first place. The idea of having some sort of global flag that a signal handler (such as `SIGINT`) would adjust is exactly why blocking system calls can stop with `EINTR` - that value is a clue to the calling code to go check that flag again before restarting. For example, this blog post outlines basically the same situation I'm in:

http://250bpm.com/blog:12

On a more practical appeal, my workaround by using a `uv_async_t` also consumes another filehandle to provide this ability, whereas when I use most other event systems systems (e.g. GLib, or any of the nonblocking event systems often found in other languages, as well as the "simple" cases using direct `poll` you'd probably write in a small C program) I can get by without it because they either explicitly pay attention to `EINTR`, or else just recheck the "stop flag" on every loop iteration anyway.

**Comment by leonerd** [comment]
@saghul:
> @leonerd Am I right assuming your signal handler is not a libuv `uv_signal_t` handle? `uv_stop` is not thread-safe, you must call it from the loop thread. If you are not in the loop thread you can use an async handle and call `uv_stop` in the `uv_async_send` callback.

Indeed; a plain POSIX signal handler.

> Basically, you seem to want `uv_stop` to be thread-safe, but it's not (and I don't think it'll ever be, unless we make the entire API thread-safe).

This isn't really about threads - I don't have any other threads in my code, except for the case of the signal handler itself. The case of simple integer flags like this one is observed to be safe across a vast range of other programs and systems. Furthermore, I am able to fix this bug simply by checking the `loop->stop_flag` as part of `EINTR` handling in the main `uv__io_poll()` functions - see my PR #2174.

**Comment by leonerd** [comment]
>     2\. `uv_stop()` is not thread-safe or async-signal-safe. That could be addressed by using atomic loads and stores (modulo compiler bugs around struct RMW cycles, always a thorny topic.)

You can declare `stop_flag` as a `sig_atomic_t` type; which is guaranteed to be atomic for loads and stores across signal handlers, for exactly this sort of purpose.

**Comment by saghul** [comment]
Oh, I see. Out of curiosity: is using a `uv_signal_t` a possibility for you?

**Comment by leonerd** [comment]
@saghul:
> Oh, I see. Out of curiosity: is using a `uv_signal_t` a possibility for you?

*Potentially* but I'd prefer not; most of the other systems work without it.

My program in question is a demonstration of using my C library libtickit, using libuv as the event loop backend:

https://bazaar.launchpad.net/~leonerd/libtickit/trunk/view/head:/examples/evloop-libuv.c

In particular, note the `el_stop()` function at:

https://bazaar.launchpad.net/~leonerd/libtickit/trunk/view/head:/examples/evloop-libuv.c#L244

This gets invoked by the core during a `SIGINT`, by the code at

https://bazaar.launchpad.net/~leonerd/libtickit/trunk/view/head:/src/tickit.c#L223

which is a structure which works just fine on both its own internal `poll(2)`-based loop, and against the GLib example also found in the `examples/` directory. The core of the library works to catch `SIGINT` immediately when using these other event systems, because both of them reïterate immediately on `EINTR` and thus find their own local equivalent of the stop flag without needing to wait out the remaining interrupted timeout interval.

**Comment by bnoordhuis** [comment]
> You can declare stop_flag as a sig_atomic_t type; which is guaranteed to be atomic for loads and stores across signal handlers, for exactly this sort of purpose.

That only addresses async-signal-safety, not thread safety. Thread safety is relevant here because you don't always control what thread the signal is delivered to.

**Comment by leonerd** [comment]
> That only addresses async-signal-safety, not thread safety. Thread safety is relevant here because you don't always control what thread the signal is delivered to.

Oh sure; I accept that in an intentionally-multithreaded program extra complications would arise. But since I'm not multithreading my program, I shouldn't have to pay any costs of multithread complications that I myself am not introducing.

In addition were I using threads, it would be fairly simple to just ask that `SIGINT` be delivered to the "main loop" thread which is the one that called `uv_run()` anyway.

**Comment by spectras** [comment]
@leonerd the signal handler of your project is invalid from its very first line:
```c
static Tickit *running_tickit;

static void sigint(int sig)
{
  if(running_tickit)
    tickit_stop(running_tickit);
}

void tickit_run(Tickit *t)
{
  /* ... */
  running_tickit = NULL;
}
```
There is no guarantee on what value the signal handler would see if invoked roughly when `tickit_run` exits. It might see NULL. It might still see the pointer after the `Tickit` has been destroyed. And it might see a garbage value if pointer type is not atomic on target architecture.

By the way, about the workaround of calling `uv_async_send`: it is not guaranteed by libuv API to be [signal-safe](http://man7.org/linux/man-pages/man7/signal-safety.7.html). It *happens to be* right now in current version of libuv, but unless that guarantee is added, it could change anytime and you would never know why the random crash once in a blue moon.

Just because it appears to be working does not mean it's correct or it will keep working. Why not just use `uv_signal_t`, its very purpose is to handle this for you?
