### ISSUE TITLE
Consistently enable or disable TCP_NODELAY on all platforms

### ISSUE THREAD

**Issue by piscisaureus** [libuv/libuv#218]
https://github.com/iojs/io.js/issues/906
https://github.com/joyent/node/issues/9235

**Comment by silverwind** [comment]
Is this something that should be fixed in libuv rather than io.js? We could call `setNoDelay(true)` on every TCP handle, but that seems a bit hackish to me.

**Comment by bnoordhuis** [comment]
I don't think it's for libuv to decide whether TCP_NODELAY should be the default.  Linux system administrators can override the default through a sysctl and there are valid use cases for either setting.  Applications that feel strongly about it can always manually select one or the other.

One aspect where libuv could improve is to better remember the `UV_TCP_NODELAY` or `UV_HANDLE_TCP_NODELAY` setting when `uv_tcp_nodelay()` is called before the socket has been allocated.  The setting is retroactively applied when `on=1` but not when `on=0`.

**Comment by saghul** [comment]
I agree with @bnoordhuis here. About remembering the value, there are others like keep-alive we'd need to remember, and I secretly hope/wish we don't need to do anything because everything will be fixed when/if we switch to creating the sockets in uv_*_init :-)

**Comment by saghul** [comment]
Shall we close this then?

**Comment by silverwind** [comment]
@saghul I'm not too familiar with uv's socket API, but would one need to set flags for things like keep-alive and nodelay on every socket or is there a way to specify these once and have them apply to all future sockets automatically?

Regarding remembering options, we landed https://github.com/nodejs/io.js/commit/85d99830096a48b7d50cc3b0e5c3fba4172c2d02 a while ago, which works around that issue.

**Comment by saghul** [comment]
It's a per socket option, not global. Applications need to take care of
that.

**Comment by silverwind** [comment]
Well in that case, I think there's nothing to do on the uv side, so you can close this issue.

I'll continue working on platform consistency on iojs's side, but am a bit blocked by having to figure out a working test for TCP_NODELAY first.

**Comment by saghul** [comment]
Done. Feel free to reach out if there is any doubt I can help you with.
