### ISSUE TITLE
Twice accept, twice descriptor add/del

### ISSUE THREAD

**Issue by ddosoff** [libuv/libuv#2181]
* **Version**: lastest from github
* **Platform**: ubuntu 18.04 64 bit

First time I noticed strange syscals in the project that uses libuv: https://github.com/uNetworking/uSockets/issues/34

Then I downloaded lastest libuv and started proxy sample:

```
libuv/samples/socks5-proxy$ strace ./build/Debug/s5-proxy
```

Telnet to 1080 in another console and see:

```
accept4(10, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 11
accept4(10, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(3, EPOLL_CTL_ADD, 11, {EPOLLIN, {u32=11, u64=11}}) = 0
epoll_pwait(3, [{EPOLLIN, {u32=11, u64=11}}], 1024, 59999, NULL, 8) = 1
read(11, "\4", 2048)                    = 1
write(2, "./build/Debug/s5-proxy:error: ha"..., 69./build/Debug/s5-proxy:error: handshake error: Bad protocol version.
) = 69
epoll_ctl(3, EPOLL_CTL_DEL, 11, 0x7ffe9a51aa2c) = 0
close(11)                               = 0
epoll_ctl(3, EPOLL_CTL_DEL, -1, 0x7ffe9a51aa2c) = -1 EBADF (Bad file descriptor)
```

Why libuv use accept4 and EPOLL_CTL_DEL twice?

**Comment by bnoordhuis** [comment]
The two calls to accept4() are correct: libuv accepts incoming connections until the operating system's accept queue is empty, i.e., until it fails with EAGAIN.

The second EPOLL_CTL_DEL call (with fd=-1) is a buglet, see #2182.
