### ISSUE TITLE
zos,ci: threadpool_multiple_event_loops fails frequently

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2183]
Example:
```
not ok 288 - threadpool_multiple_event_loops
# timeout
# Output from process `threadpool_multiple_event_loops`:
# CEE5205S The signal SIGTERM was received.
```
Some non-scientific statistics suggest it fails more often than it passes.

cc @libuv/zos

**Comment by bnoordhuis** [comment]
@mhdawson aside: who should be in @libuv/zos now that @jBarz no longer works on it?

**Comment by mhdawson** [comment]
Oops opened a duplicate https://github.com/nodejs/build/issues/1685.  @miladfarca is looking at this one.

**Comment by mhdawson** [comment]
duplicate off [nodejs/build#1685](https://github.com/nodejs/build/issues/1685).

**Comment by cjihrig** [comment]
I think this has been resolved. Closing out.
