### ISSUE TITLE
1.26.0: dsist and distcheck targets are failing

### ISSUE THREAD

**Issue by kloczek** [libuv/libuv#2190]
dist and distcheck targets suppose to be used to generate release tar balls but they are failing
[tkloczko@domek libuv-v1.26.0]$ make distcheck
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make  distdir-am
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make[2]: *** No rule to make target 'android-configure', needed by 'distdir-am'.  Stop.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make[1]: *** [Makefile:5066: distdir] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make: *** [Makefile:5143: dist] Error 2

[tkloczko@domek libuv-v1.26.0]$ 
[tkloczko@domek libuv-v1.26.0]$ make dist
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make  distdir-am
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make[2]: *** No rule to make target 'android-configure', needed by 'distdir-am'.  Stop.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make[1]: *** [Makefile:5066: distdir] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libuv-v1.26.0'
make: *** [Makefile:5143: dist] Error 2

**Comment by saghul** [comment]
Looks like this needs to be adjusted: https://github.com/libuv/libuv/blob/v1.x/Makefile.am#L124 since we now have multiple `android-configure` scripts.

**Comment by bnoordhuis** [comment]
#2198 

@refack Would it be possible to set up build jobs that (also?) run `make distcheck` to help catch such issues? It's been broken since at least June of last year.
