### ISSUE TITLE
docs.libuv.org not updating?

### ISSUE THREAD

**Issue by squeek502** [libuv/libuv#2194]
- http://docs.libuv.org/en/stable/ has `libuv 1.24.1` in its header
- http://docs.libuv.org/en/latest/ and http://docs.libuv.org/en/v1.x/ have `libuv 1.24.2-dev` in their headers

And it's not just the headers, e.g. [the changes to the misc page in this commit](https://github.com/libuv/libuv/commit/8865e72e25fc8aba94da7c9e18c3b5629d288ecc#diff-94fc2db807b521d9622eb8dcb8f6892f) are not reflected [in the docs](http://docs.libuv.org/en/v1.x/misc.html)

**Comment by bnoordhuis** [comment]
Ping @cjihrig - did something perhaps go wrong during the v1.25.0 release?

**Comment by cjihrig** [comment]
Not that I noticed or am aware of. Is there any chance that it's related to the recent hosting issues (https://github.com/libuv/libuv/issues/2178 and https://github.com/nodejs/build/issues/1680)?

**Comment by saghul** [comment]
We use Read The Docs for that, maybe the build didn't trigger. I can take a look.

**Comment by saghul** [comment]
Ok, I triggered a manual build so the docs are updated and configured RTD as a webhook. We were using the old GH services integration, and it seems to have stopped working.

**Comment by cjihrig** [comment]
Thanks @saghul
