### ISSUE TITLE
x/os failures

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#2196]
* **Version**: 1.x
* **Platform**:z/OS

Probably should have opened this in this repo, but at least so people know we are working on it:

https://github.com/nodejs/build/issues/1685

**Comment by richardlau** [comment]
Duplicate of https://github.com/libuv/libuv/issues/2183.

**Comment by bnoordhuis** [comment]
Yep, closing as duplicate. Nice to know it's being worked on though.
