### ISSUE TITLE
Warning on Linux with -Wunused-but-set-variable

### ISSUE THREAD

**Issue by zhaozg** [libuv/libuv#2203]
* **Version**: 1.26.0
* **Platform**: Linux kylin 4.4.58-20170818.kylin.5.desktop-generic #5 SMP Fri Aug 18 10:19:03 CST 2017 aarch64 aarch64 aarch64 GNU/Linux

/home/zhaozg/work/luaclibs/luv/deps/libuv/src/unix/signal.c: In function ‘uv__signal_stop’:
/home/zhaozg/work/luaclibs/luv/deps/libuv/src/unix/signal.c:542:7: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
   int ret;
       ^

**Comment by bnoordhuis** [comment]
You should probably take that up with luv because I suspect said project is building libuv with `-DNDEBUG`, which disables asserts. With asserts enabled, `ret` is used.
