### ISSUE TITLE
process_title test case failing

### ISSUE THREAD

**Issue by miladfarca** [libuv/libuv#2207]
* **Version**: 1.26.1
* **Platform**: OS/390 S0W1 25.00 04 2964 

The `process_title` test cases is failing on `zOS, s390x` platform. 
Looking at the source, it appears that a process title struct is initialized in `uv_set_process_title` under `unix/proctitle.c`:

```
       if (process_title.len != 0) {
 99     /* No need to terminate, byte after is always '\0'. */
100     strncpy(process_title.str, title, process_title.len);
101     uv__set_process_title(title);
102   }
```
`process_title.len` is fetched from the length of the` argv[0]` when running this test case. Having a short command line argument, or a short path to where `libuv` is on disk will cause this to be a small integer, which in turn will copy fewer characters to `process_title.str`.

The test cases is setting the `title` as this fixed string:
```
set_title("%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s");
```
and later tries to run an ASSERT by `strcmp(buffer, title) == 0`.

A short ` argv[0]` will in turn make the `buffer` have fewer characters than expected hence the ASSERT fails.

There are a few ways to fix this but first I like to understand the reason for having this test case, why it's being initialized with command line arguments and how it tests setting process title.

**Comment by bnoordhuis** [comment]
The preceding comment explains the reason for that test: `Check for format string vulnerabilities.`

See also commit a9f6f06feaf02ebb48d4b41bd2ac47fcb2096a00.

**Comment by miladfarca** [comment]
@bnoordhuis Thank you, but can't `process_title.str` get initialized with a string with an equal length to`"%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s"` ?

**Comment by bnoordhuis** [comment]
Maybe I misunderstand your question but a string without "%s%s%s..." in it wouldn't test for format string vulnerabilities.

**Comment by miladfarca** [comment]
@bnoordhuis that's right, what I'm asking is, let's say I start the tests with "/home/libuv/run-test".
upon initialization of the `process_title` test case, `process_title.str` will be set to `home/libuv/run-test` which has fewer characters than "%s%s%s..." above, hence `strcmp(buffer, title) == 0` will fail. The string above has a fixed length whereas `process_title.str` length depends on the command line argument length.

**Comment by bnoordhuis** [comment]
Right, I understand now. I think the answer to your question is that on most platforms it isn't an issue because there's always more room available than just `argv[0]`; z/os is the outlier, see commit f9484cf51: https://github.com/libuv/libuv/blob/09ba4778d8a8d36b652c714c2cc6557b7e945ee2/src/unix/proctitle.c#L62-L70

A simple fix would be to use a shorter string in the test, perhaps conditionally on `#ifdef __MVS__`.

**Comment by miladfarca** [comment]
@bennoleslie Thanks you, so can I make a PR with this fix? I will add some other minor zos fixes to it also

**Comment by bnoordhuis** [comment]
Wrong at-mention, I think? :-)

A PR is welcome, just don't put unrelated changes in the same commit.

**Comment by miladfarca** [comment]
@bnoordhuis my bad, got it right this time :D, thank you.

**Comment by miladfarca** [comment]
Link for downloading the zip file:
https://ibm.box.com/s/wzbo9dbuair5e4eaqkjl3dgrz1fko8ax

Instructions for unzipping and exporting path:
https://github.com/nodejs/build/blob/master/jenkins/scripts/select-compiler.sh

**Comment by bnoordhuis** [comment]
@miladfarca Please open a pull request if you still want to. I'll close out this issue due to inactivity.
