### ISSUE TITLE
__FreeBSD_kernel_ may be an error

### ISSUE THREAD

**Issue by Laobe** [libuv/libuv#2212]
File src/unix/fs.c in line 50 defined(\_\_FreeBSD_kernel\_) may should be (\_\_FreeBSD_kernel\_\_), two underlines after kernel. In line 656 is (\_\_FreeBSD_kernel\_\_).
Because I am not familiar with FreeBSD, I are not sure which header is right.

**Comment by cjihrig** [comment]
Seems like a typo to me. Looks like there is one instance of `__FreeBSD_kernel_` in the codebase, and 18 instances of `__FreeBSD_kernel__`.
