### ISSUE TITLE
 timer never remove from handle_queue?

### ISSUE THREAD

**Issue by b-xiang** [libuv/libuv#2222]
timer add to handle_queue by call QUEUE_INSERT_TAIL in uv__handle_init in uv_timer_init function, but there is no any timer function to remove it from handle_queue?Thanks!

**Comment by addaleax** [comment]
Timers, like all libuv handles, can be closed through `uv_close()`, if that’s what you’re looking for?

**Comment by b-xiang** [comment]
I get it! Thank you very much!This's my fault!
