### ISSUE TITLE
1 make check failed

### ISSUE THREAD

**Issue by cadoiz** [libuv/libuv#2227]
* **Version**: 
* **Platform**: 

Building like written in README.md.
make was successful, make check gives:

Assertion failed in test/test-fs.c on line 1107: s->st_atim.tv_nsec == 0
=============================================================
[% 100|+ 247|-   1|T   0|S   0]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:3808: check-TESTS] Fehler 1

**Comment by bnoordhuis** [comment]
Can you fill out the issue template? We ask it for a reason.

**Comment by cjihrig** [comment]
No follow up. Closing.
