### ISSUE TITLE
test: fs birth time failure

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2235]
https://ci.nodejs.org/job/libuv-test-commit-linux/1376/nodes=fedora-latest-x64/console
```
not ok 72 - fs_fstat
# exit code 134
# Output from process `fs_fstat`:
# Assertion failed in test/test-fs.c on line 1259: s->st_birthtim.tv_nsec == 0 || s->st_birthtim.tv_nsec == t.st_ctim.tv_nsec
```
https://github.com/libuv/libuv/blob/99440bb6734bc7edfea108f6eb6914982e9f8cf7/test/test-fs.c#L1252-L1260
So apparently the assumption that birth time equals change time isn't always true? Or is there some kind of concurrent modification going on that updates the change time?

**Comment by vtjnash** [comment]
Yep, reproduces locally occasionally:
```
not ok 1 - fs_fstat
# exit code 6
# Output from process `fs_fstat`:
# birth  1578588523.411535470
# change 1578588523.415535461
# Assertion failed in ../test/test-fs.c on line 1420: s->st_birthtim.tv_nsec == 0 || s->st_birthtim.tv_nsec == t.st_ctim.tv_nsec
```

IIUC, the ordering here should be change time > modification time > birth time, since that write to the file implies a change to the metadata data which implies an update to the change time:
https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python/367166#comment78136607_39501288

**Comment by vtjnash** [comment]
I thought about saying it should be after the current time, but that too is occasionally failing:
```
now    1578590026.1812000   // uv_gettimeofday prior to uv_open
birth  1578590025.996949689 // st_birthtim
modify 1578590025.996949689 // st_mtim
change 1578590025.996949689 // st_ctim
```

**Comment by vcunat** [comment]
Are you sure that Linux or POSIX guarantees this asserted equality?  I just saw this error (dis)appear randomly on our build farm, with libuv 1.42.0 (i.e. after the commit closing this issue):
```
# Assertion failed in test/test-fs.c on line 1417: s->st_birthtim.tv_nsec == 0 || s->st_birthtim.tv_nsec == t.st_ctim.tv_nsec
```
(on aarch64-linux; I suspect it might've been on ZFS)

**Comment by bnoordhuis** [comment]
@vcunat can you open a new issue and provide as much info as possible? FWIW, you're the first one to report this in two years.

**Comment by vcunat** [comment]
Opening an issue would be easy, but I'm afraid I don't have more useful information than I posted already.

**Comment by vcunat** [comment]
Now I noticed the same on i686-linux.

I'm adding it to our local list of flaky libuv tests, so that it doesn't keep blocking other builds: https://github.com/NixOS/nixpkgs/commit/173de4efbf4
