### ISSUE TITLE
uv_copyfile could check `equivalent(from, to)`

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#2237]
The C++17 standard proposes that copy_file should have the following two error checks prior to the copy:

> Report an error if any of the following is true:
> - to and from are the same as determined by equivalent(from, to);
> - to is not a regular file as determined by !is_regular_file(to)

I'm not sure of the intent of the second one, but the first one seems like a good check to add. There's already a call to fstat on the src, so it would not be hard to add this check. The check itself is defined elsewhere and is not difficult:

> For POSIX, this means that the st_dev and st_ino members of their POSIX stat structure, obtained as if by POSIX stat, are equal.
> In particular, all hard links for the same file or directory are equivalent, and a symlink and its target on the same file system are equivalent.

Observe too that this is how `cp` works:
```
$ cp file_link file ; echo $?
cp: file and file_link are identical (not copied).
1
```

**Comment by bnoordhuis** [comment]
@vtjnash Do you want to follow up with a PR?

**Comment by vtjnash** [comment]
Is there anything left to do here? I know that #2298 only implemented the first part, but I'm also not sure why the second part was added in the C++17 standard.

**Comment by saghul** [comment]
CLosing seems reasonable.
