### ISSUE TITLE
Use liburing

### ISSUE THREAD

**Issue by jimmyjones2** [libuv/libuv#2238]
Linux 5.1 has a new, more efficient API for asynchronous IO - io_uring (see [LWN](https://lwn.net/Articles/776703/)) with a userspace library [liburing](http://git.kernel.dk/cgit/liburing/)

Could using this make libuv more efficient?

**Comment by rektide** [comment]
Possible dupe of #1947.

Mods- I would like to see #1947 actually mention the specific "new kernel polling interface" in the title (io_uring or liburing), to avoid this confusion in the future.

**Comment by saghul** [comment]
Done.
