### ISSUE TITLE
tcp connect callback never being ran

### ISSUE THREAD

**Issue by cleverca22** [libuv/libuv#2239]
while debugging a problem in an electron app, i have traced the problem down into the depths of libuv

at the electron level, the problem occurs when doing an https request immediately after another https request finishes
the 2nd request just hangs forever, and wireshark finds that it opened the tcp connection, but never sent or received a single byte over it

poking around within the internals of nodejs with the electron devtools reveals that `internalConnect` from `net.js` is being ran both times (and gdb/strace/wireshark confirm it opened a socket and connected both fimes)
but, `net.js`'s `afterConnect` is only ran for the 1st connection, and the 2nd connection never gets the callback

further debug with gdb reveals that `node::ConnectionWrap<node::TCPWrap, uv_tcp_s>::AfterConnect(uv_connect_s*, int)` is never ran for the 2nd connection

and strace then reveals:
```
[root@amd-nixos:~]$ strace -f -p 17601 -e connect,select,poll,recvfrom,epoll_ctl
strace: Process 17601 attached with 26 threads
strace: [ Process PID=17601 runs in x32 mode. ]
strace: [ Process PID=17601 runs in 64 bit mode. ]
[pid 17601] connect(75, {sa_family=AF_INET, sin_port=htons(39323), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid 17601] epoll_ctl(3, EPOLL_CTL_ADD, 75, {EPOLLOUT, {u32=75, u64=75}}) = 0
[pid 17601] epoll_ctl(3, EPOLL_CTL_ADD, 75, {EPOLLIN, {u32=75, u64=75}}) = -1 EEXIST (File exists)
[pid 17601] epoll_ctl(3, EPOLL_CTL_MOD, 75, {EPOLLIN, {u32=75, u64=75}}) = 0
[pid 17601] epoll_ctl(3, EPOLL_CTL_MOD, 75, {EPOLLIN, {u32=75, u64=75}}) = 0
[pid 17601] epoll_ctl(3, EPOLL_CTL_MOD, 75, {EPOLLIN, {u32=75, u64=75}}) = 0
[pid 17601] epoll_ctl(3, EPOLL_CTL_DEL, 75, 0x7ffd1e380ae8) = 0
[pid 17601] connect(75, {sa_family=AF_INET, sin_port=htons(39323), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
```
the first connection is made, registered within epoll, the ssl handshand happens (omited) and request ends normally
then the 2nd connection is made, but never registered in epoll, so libuv never hears about it finishing, and never runs the callback, causing everything to hang
* **Version**: electron version 3.0.14, nodejs version 10.2.0
* **Platform**: linux

**Comment by bnoordhuis** [comment]
Can you add `read,write,epoll_wait,epoll_pwait,getsockopt` to the list of system calls to trace? That would help.

**Comment by cleverca22** [comment]
https://gist.github.com/b20097268b76b5f8ca4583f472eaaef2
line 2, the `connect` syscall
5 `EPOLL_CTL_ADD`
6, the `epoll_wait` signaling that it connected, kicking off tls and https
220, `EPOLL_CTL_DEL`
221, `close()`
235, `connect()` again
i waited several seconds before stopping the strace

**Comment by cleverca22** [comment]
https://gist.github.com/2167988ed0ac4065743e633dfff26271
`strace -p 32026 -o logfile -e connect,select,poll,recvfrom,epoll_ctl,read,write,epoll_wait,epoll_pwait,getsockopt,close -ttt -T`

a second trace with timestamps added

**Comment by bnoordhuis** [comment]
In your gists, I don't see a subsequent call to epoll_wait() after the second connect() call.

That suggests control never returns to the libuv event loop, e.g. because the corresponding uv_tcp_t handle is unref'd (doesn't keep the event loop alive), something called uv_stop(), or the application blocks somewhere.

So far I don't see anything that indicates a libuv issue.

**Comment by cleverca22** [comment]
ahh, good point
but what is doing the write of `"\0"` at regular intervals..., that feels like a libuv timer or something, will need to investigate the source more

**Comment by bnoordhuis** [comment]
I suppose it could be an electron thing. If that file descriptor is indeed controlled by libuv, then something in the application is probably continuously posting one-byte writes to a `uv_tcp_t` or `uv_pipe_t` handle.

If you pass `-y` to strace, it'll print the file descriptor type.

**Comment by cleverca22** [comment]
```
1554173229.015319 epoll_ctl(3<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 49<socket:[37065391]>, 0x7ffd3834cda8) = 0 <0.003796>
1554173229.020056 close(49<socket:[37065391]>) = 0 <0.000542>
1554173229.025820 write(28<pipe:[37068266]>, "\0", 1) = 1 <0.000014>
...
1554173229.028575 write(28<pipe:[37068266]>, "\0", 1) = 1 <0.000024>
1554173229.029482 epoll_wait(3<anon_inode:[eventpoll]>, [{EPOLLIN, {u32=22, u64=22}}], 1024, 0) = 1 <0.000012>
1554173229.029546 read(22<anon_inode:[eventfd]>, "\3\0\0\0\0\0\0\0", 1024) = 8 <0.000013>
1554173229.031659 write(28<pipe:[37068266]>, "\0", 1) = 1 <0.000044>
...
1554173229.855145 write(28<pipe:[37068266]>, "\0", 1) = 1 <0.000056>
1554173229.856020 connect(49<socket:[37068673]>, {sa_family=AF_INET, sin_port=htons(37719), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress) <0.000091>
1554173229.856442 write(28<pipe:[37068266]>, "\0", 1) = 1 <0.000047>
1554173229.870858 write(28<pipe:[37068266]>, "\0", 1) = 1 <0.000034>
```
yep, its a pipe
```
[root@amd-nixos:~]$ ls -l /proc/17051/fd/28
l-wx------ 1 clever users 64 Apr  1 23:47 /proc/17051/fd/28 -> 'pipe:[37068266]'
[root@amd-nixos:~]$ ls -l /proc/*/fd/* | grep 37068266
lr-x------ 1 clever    users    64 Apr  1 23:47 /proc/17051/fd/27 -> pipe:[37068266]
l-wx------ 1 clever    users    64 Apr  1 23:47 /proc/17051/fd/28 -> pipe:[37068266]
```
the read end is fd 27 in the same process
thread 17063 in this run is reading each null byte, and otherwise "idle", but i notice all of the `epoll_wait` calls are not blocking...
going to re-run without the syscall filter...

**Comment by cleverca22** [comment]
yeah, something is strange, `epoll_wait` never blocks, and always finds something active
i suspect electron (or nodejs) is using `UV_RUN_NOWAIT` and doing the actual blocking in its own event loop
and the bug must be over there, where it decides to just never call `uv_run(loop, UV_RUN_NOWAIT)`, causing this issue

**Comment by cleverca22** [comment]
https://github.com/electron/electron/blob/v3.0.14/atom/common/node_bindings.cc#L354-L378
https://github.com/electron/electron/blob/v3.0.14/atom/common/node_bindings_linux.cc#L39

when things are functioning normally, `atom::NodeBindingsLinux::PollEvents()` will detect activity on the `uv_backend_fd(uv_loop_)` and then run `atom::NodeBindings::WakeupMainThread()` which triggers `atom::NodeBindings::UvRunOnce()` that then does `uv_run(uv_loop_, UV_RUN_NOWAIT)`

but when things fail, i only get a single breakpoint triggering in `PollEvents` and it never calls `WakeupMainThread`

i'll see about building electron from source and then debug symbols can make things less fuzzy

**Comment by cleverca22** [comment]
after building electron master from source, before i even reproduce the main issue, it fails with:
```
Found a corrupted memory buffer in MallocBlock (may be offset from user ptr): buffer index: 0, buffer ptr: 0x2339916e1120, size of buffer: 128
Buffer byte 104 is 0x00 (should be 0xcd).
Buffer byte 105 is 0x00 (should be 0xcd).
Buffer byte 106 is 0x00 (should be 0xcd).
Buffer byte 107 is 0x00 (should be 0xcd).
Buffer byte 108 is 0x00 (should be 0xcd).
Buffer byte 109 is 0x00 (should be 0xcd).
Buffer byte 110 is 0x00 (should be 0xcd).
Buffer byte 111 is 0x00 (should be 0xcd).
Deleted by thread 0x7f69450b2bc0
*** WARNING: Cannot convert addresses to symbols in output below.
*** Reason: Cannot find 'pprof' (is PPROF_PATH set correctly?)
*** If you cannot fix this, try running pprof directly.
...
Memory was written to after being freed.  MallocBlock: 0x2339916e1120, user ptr: 0x2339916e1140, size: 128.  If you can't find the source of the error, try using ASan (http://code.google.com/p/address-sanitizer/), Valgrind, or Purify, or study the output of the deleter's stack printed above.
Received signal 11 SEGV_MAPERR 000000000039
#0 0x7f697b1b62f1 base::debug::CollectStackTrace()
...
#13 0x7f697b23ce93 tc_free
#14 0x7f697b1d204d (anonymous namespace)::TCFree()  
#15 0x7f697b1e95f3 ShimCppDelete
#16 0x7f697b1b6c55 operator delete()
#17 0x55f9da1a30d5 std::__Cr::_DeallocateCaller::__do_call()
...
#24 0x55f9da1d9e52 std::__Cr::vector<>::~vector()   
#25 0x55f9db0d5840 mate::internal::V8FunctionInvoker<>::Go()
#26 0x55f9db0d5ad9 base::internal::FunctorTraits<>::Invoke<>()
#27 0x55f9db0d5a51 base::internal::InvokeHelper<>::MakeItSo<>()
#28 0x55f9db0d59cd _ZN4base8internal7InvokerINS0_9BindStateIPFbPN2v87IsolateERKN4mate8internal14SafeV8FunctionENS3_5LocalINS3_5ValueEEEiEJS5_S8_EEEFbSD_iEE7RunImplIRKSF_RKNSt4__Cr5tupleIJS5_S8_EEEJLm0ELm1EEEEbOT_OT0_NSM_16integer_sequenceImJXspT1_EEEEOSD_Oi
#29 0x55f9db0d5930 base::internal::Invoker<>::Run() 
#30 0x55f9db0d4425 _ZNKR4base17RepeatingCallbackIFbN2v85LocalINS1_5ValueEEEiEE3RunES4_i
#31 0x55f9db0d1f04 atom::api::Menu::IsCommandIdEnabled()
#32 0x7f6974ac80df ui::SimpleMenuModel::IsEnabledAt()
#33 0x7f6963df0df0 views::MenuModelAdapter::IsCommandEnabled()
#34 0x55f9db07c660 atom::MenuDelegate::IsCommandEnabled()
#35 0x7f6963dea30e views::MenuItemView::Init()
#36 0x7f6963dedc15 views::MenuItemView::MenuItemView()
#37 0x7f6963deb175 views::MenuItemView::AddMenuItemAt()
...
```
the failure occurs after closing any menu from the menu bar

**Comment by bnoordhuis** [comment]
Since it doesn't look like this is a libuv issue, I'll take the liberty of closing it out. Cheers.
