### ISSUE TITLE
Use native UTF-8 option on Windows 10

### ISSUE THREAD

**Issue by davidanthoff** [libuv/libuv#2242]
It should be possible to just write UTF-8 strings directly to the console on modern Windows machines, skipping the whole UTF-8 decoding and converting to UCS-2 to that is happening in `tty.c`.

It should be enough to 1) set the code page for the console to UTF-8 by calling `SetConsoleOutputCP` with `CP_UTF8`, and 2) then using `WriteConsoleA` and passing a pointer to the UTF-8 string directly to that one. I assume this would significantly simplify the whole code, in particular in combination with the support for VT sequences that also landed in newer Windows releases.

A very helpful discussion of these new features from the console team is at https://github.com/Microsoft/console/issues/396.

I'm not clear how one can reliably detect at runtime whether a given Windows version supports this feature or not, but I'm sure one could follow up on the issue that I linked to and get an answer to that question.

**Comment by bnoordhuis** [comment]
> I assume this would significantly simplify the whole code

I expect it's the opposite. We'd still have to support emulation for older Windows versions so we'd end up with two code paths instead of one.

From a maintenance perspective, unless there are significant benefits (improved interop or security, better performance in a way that matters, etc.), it's probably not a change worth making.

**Comment by vtjnash** [comment]
I agree with bnoordhuis. Furthermore, even if we could break all compatibility and drop all old code, I think the maintenance burden of trying to modify the code-page would be higher than continuing to use an API that doesn't have to deal with code pages. The additional state would require more effort to manage, and might fail to change—requiring us to keep the existing code as a fallback—or could be changed by an outside program—requiring adding the ability to restore and resynchronize the state, plus choosing when and how to manage that hand-off.

**Comment by davidanthoff** [comment]
Sounds good. I had originally thought that there are already two code paths, and that one could modify [this](https://github.com/libuv/libuv/blob/99440bb6734bc7edfea108f6eb6914982e9f8cf7/src/win/tty.c#L1662) one here to be the one that only kicks in on modern Windows, and then simplify that one (and leave the other path around for legacy Windows versions), but of course https://github.com/libuv/libuv/pull/1965 would actually remove that and get things back to one code path, so that is kind of moot.
