### ISSUE TITLE
linux: read /proc/meminfo in uv_get_total_memory()

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2249]
https://github.com/nodejs/node/issues/27170 - it was reported that `uv_get_total_memory()` reports the wrong value inside an lxc container.

Libuv calls sysinfo(2) but that isn't intercepted by lxc; /proc/meminfo however is - /proc is a FUSE fs inside the container.

It could also be argued that this is an lxc bug that should be fixed there and not here. No strong opinion.

**Comment by Qix-** [comment]
> It could also be argued that this is an lxc bug that should be fixed there and not here

Is there a ticket open for it over there? I'd be interested to see what the lxc folks say.

**Comment by bnoordhuis** [comment]
I didn't open one but there are a bunch of issues about reported memory usage being off.

LXC doesn't intercept system calls so I wouldn't expect them to fix it anyway. Perhaps it's the system call itself that needs to be made cgroup aware. I'm not volunteering however. ^^
