### ISSUE TITLE
make check fail on test-fs-copyfile.c

### ISSUE THREAD

**Issue by markos28** [libuv/libuv#2257]
*Version :1.27 patch1
*Platform :  Linux  4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:03:40 UTC 2019 i686 i686 i686 GNU/Linux
 
make check fail on test-fs-copyfile.c

#   sysname: Linux
#   release: 4.15.0-47-generic
#   version: #50~16.04.1-Ubuntu SMP Fri Mar 15 16:03:40 UTC 2019
#   machine: i686
ok 2 - active
ok 3 - async
ok 4 - async_null_cb
ok 5 - async_ref
ok 6 - barrier_1
ok 7 - barrier_2
ok 8 - barrier_3
ok 9 - barrier_serial_thread
ok 10 - barrier_serial_thread_single
ok 11 - callback_stack
ok 12 - check_ref
ok 13 - close_fd
ok 14 - close_order
ok 15 - closed_fd_events
ok 16 - condvar_1
ok 17 - condvar_2
ok 18 - condvar_3
ok 19 - condvar_4
ok 20 - condvar_5
ok 21 - connect_unspecified
ok 22 - connection_fail
ok 23 - connection_fail_doesnt_auto_close
ok 24 - cwd_and_chdir
ok 25 - default_loop_close
ok 26 - delayed_accept
ok 27 - dlerror
ok 28 - eintr_handling
ok 29 - embed
ok 30 - emfile
ok 31 - env_vars
ok 32 - error_message
ok 33 - fork_fs_events_child
ok 34 - fork_fs_events_child_dir
ok 35 - fork_fs_events_file_parent_child
ok 36 - fork_signal_to_child
ok 37 - fork_signal_to_child_closed
ok 38 - fork_socketpair
ok 39 - fork_socketpair_started
ok 40 - fork_threadpool_queue_work_simple
ok 41 - fork_timer
ok 42 - fs_access
ok 43 - fs_async_dir
ok 44 - fs_async_sendfile
ok 45 - fs_chmod
ok 46 - fs_chown
not ok 47 - fs_copyfile
# exit code 134
# Output from process `fs_copyfile`:
# Assertion failed in test/test-fs-copyfile.c on line 194: req.result == UV_EACCES
ok 48 - fs_event_close_in_callback
ok 49 - fs_event_close_with_pending_event
ok 50 - fs_event_error_reporting
ok 51 - fs_event_getpath
ok 52 - fs_event_immediate_close
ok 53 - fs_event_no_callback_after_close
ok 54 - fs_event_no_callback_on_close
ok 55 - fs_event_ref
ok 56 - fs_event_start_and_close
ok 57 - fs_event_watch_dir
ok 58 - fs_event_watch_dir_recursive # SKIP Recursive directory watching not supported on this platform.
ok 59 - fs_event_watch_file
..

**Comment by santigimeno** [comment]
Are you running the tests as root? If so, it might fail. In principle, the tests should be run with a regular user.

**Comment by markos28** [comment]
> Are you running the tests as root? If so, it might fail. In principle, the tests should be run with a regular user.

yup is under root account , i will test using regular user

**Comment by santigimeno** [comment]
No follow-up. Feel free to re-open if it's still an issue
