### ISSUE TITLE
accumulating error in timers

### ISSUE THREAD

**Issue by Roman-Koshelev** [libuv/libuv#2259]
Timers in free swimming. Why are they not adjusted? Or are they designed for one-time launch with a long timeout? Why is silent documentation about this?

* **Version**: last
* **Platform**: Linux standvm-stretch 4.4.98-3-pve #1 SMP PVE 4.4.98-102

**Comment by bnoordhuis** [comment]
It's unclear to me what your question is. I'm not even sure where to start asking for clarification. Perhaps you can post some example code and summarize the expected and actual behavior?

**Comment by Roman-Koshelev** [comment]
we will start the timer with periodicity 1s, and we will display time of a function call.
Waited 780.565 ms
Waited 781.566 ms
Waited 782.584 ms
Waited 783.614 ms
Waited 784.615 ms
Waited 785.62 ms
Waited 786.622 ms
Waited 787.629 ms
Waited 788.647 ms
Waited 789.649 ms
Waited 790.663 ms
Waited 791.666 ms
Waited 792.669 ms
Waited 793.67 ms
Waited 794.671 ms
Waited 795.72 ms
Waited 796.724 ms
Waited 797.727 ms
Waited 798.731 ms
Waited 799.737 ms
Waited 800.738 ms
Waited 801.744 ms

error accumulates. (lower results libev)

Waited 1170.91 ms
Waited 1171.89 ms
Waited 1172.9 ms
Waited 1173.89 ms
Waited 1174.89 ms
Waited 1175.89 ms
Waited 1176.89 ms
Waited 1177.89 ms
Waited 1178.89 ms
Waited 1179.89 ms
Waited 1180.89 ms
Waited 1181.89 ms
Waited 1182.89 ms

**Comment by bnoordhuis** [comment]
Is your question why libuv doesn't compensate for the time spent inside the callback? The short answer is "because it doesn't" - it's a design decision we made at the time.

**Comment by Roman-Koshelev** [comment]
Not certainly in that way. it turns out that we tell the timer to call the function every 100 seconds. He calls her through 103 and gets her to run at 203. And so every time. Why do you need a timer where the error accumulates (and even so fast)?

**Comment by bnoordhuis** [comment]
Can you post your code? I need to see what exactly you're doing to get those numbers.

**Comment by Roman-Koshelev** [comment]
https://ideone.com/WgLiuc

**Comment by Roman-Koshelev** [comment]
https://github.com/Roman-Koshelev/libuv 
Did a couple of komitov.  In my opinion, productivity and accuracy have been increased at no extra cost.

?

**Comment by vcunat** [comment]
I think, it's not too hard to use a non-repeating timer with a callback that additionally computes the remaining time and calls `uv_timer_start()` on itself.  I already have code like that, because it's a bit more flexible and robust (especially if you want some relation to "real" time), and it wasn't too performance-critical code.

**Comment by Roman-Koshelev** [comment]
I still do not understand, why not improve this moment?

**Comment by vcunat** [comment]
To be clear, I didn't mean to imply that.  I have no permissions :-) and I don't even know the implementation, so I can't judge whether it's worth it.
