### ISSUE TITLE
win: x64: lots of warnings when compiling tests because size_t is assumed DWORD

### ISSUE THREAD

**Issue by fpiette** [libuv/libuv#2275]
Hello,

When compiling libuv tests for Windows x64 using MSVC2010, there are a lot of warnings because size_t is assumed to be a DWORD. For Win x64 platform, size-t is an unsigned int64 which is twice the size of a DWORD.

The code should be fixed to consistently use size_t type when applicable and use a cast when using a size_t variable where another type is expected.

An example of such warning is in the call of ReadFile, passing buffer_len - 1 as third argument. ReadFile expect a DWORD (32 bits) but buffer_len is defined as a size_t and as such is 64 bits.
That call is in runner-win.c at line 268 inside function process_read_last_line.

Regards,
François Piette

**Comment by vtjnash** [comment]
https://github.com/libuv/libuv/pull/2091#issuecomment-441489815, and also https://github.com/libuv/libuv/issues/708

**Comment by fpiette** [comment]
Answered there https://github.com/libuv/libuv/issues/708#issuecomment-485501711

**Comment by mgaf** [comment]
https://github.com/libuv/libuv/issues/2275#issuecomment-485502015

**Comment by bnoordhuis** [comment]
I'm closing this as a duplicate but thanks for the report.
