### ISSUE TITLE
Feature request: Get usable memory from cgroups, etc.

### ISSUE THREAD

**Issue by kjin** [libuv/libuv#2286]
As cgroups (and possibly other kernel-level resource limits) may specify a limit on the amount of memory a process can consume, it would be useful for this library to expose an API like `uv_get_usable_memory` (in addition to `total` and `free`). Node.js would be able to then use this to set a memory limit for V8 isolates (see https://github.com/nodejs/node/pull/27508).

I've put something together for linux/cgroups [here](https://github.com/kjin/libuv/tree/cgroups-mem). I wanted to get feedback before taking time to flesh it out more. In particular, I think if we introduce this API, that we could iteratively implement it for other OS's besides Linux, and in the meantime just return a very high value as a place holder (cgroups itself uses a value of `0x7FFFFFFFFFFFF000` to represent no memory limit).

**Comment by kjin** [comment]
cc/ @ofrobots, @bnoordhuis, @mscdex

**Comment by cjihrig** [comment]
I'm not opposed to such an API. If we do add it, we might want to label it as experimental for a few releases though.
