### ISSUE TITLE
Test for stream: ignore EINVAL for SO_OOBINLINE on OS X

### ISSUE THREAD

**Issue by rvagg** [libuv/libuv#229]
Test(s) needed to cover #228

**Comment by vtjnash** [comment]
Is this still a io.js (nodejs) issue from https://github.com/libuv/libuv/pull/228#issuecomment-76054870? It almost sounds like it was release blocking at the time.

**Comment by saghul** [comment]
I'd say let's close this. This issue is about writing a test which was no easy task IIRC.
