### ISSUE TITLE
not ok get_memory

### ISSUE THREAD

**Issue by tcely** [libuv/libuv#2297]
https://github.com/libuv/libuv/blob/c4e9657d59723a6273ce68bda935680e1b3596c5/test/test-get-memory.c#L37

This assert is not reliable because each function calls `sysinfo` at different times. The `sysinfo` for free then the `sysinfo` for total happening at different times means that the total might be less than or equal to free.

See https://github.com/alpinelinux/aports/pull/7895#issuecomment-493313642 which excerpts from https://cloud.drone.io/alpinelinux/aports/3728

**Comment by bnoordhuis** [comment]
Did this start with v1.29.0? That would implicate #2258, a fix/workaround for lxc - which you seem to be using? Does v1.28.0 show the same behavior?

**Comment by tcely** [comment]
Here is the build log from `v1.28.0`: https://build.alpinelinux.org/buildlogs/build-edge-x86_64/main/libuv/libuv-1.28.0-r0.log

It's on different machines, so I'll try the CI again on cloud.drone.io for that version a bit later.

**Comment by tcely** [comment]
@bnoordhuis It does appear this started with `v1.29.0` as you suspected.

**Comment by bnoordhuis** [comment]
> # free_mem=3420033024, total_mem=2837901312, constrained_mem=9223372036854771712

Interesting... I wonder if this is an lxcfs bug. Libuv reads from /proc/meminfo now and that's emulated/intercepted by lxc.

Do you have access to the machine where it fails? It would be interesting to see what `grep ^Mem /proc/meminfo` prints at different times.

`MemFree < MemTotal` should be true at all times but apparently it isn't. Does lxc have facilities for changing the memory reservation at run-time? That's the only reason I can think of for that condition to be false.

**Comment by tcely** [comment]
I added `cat /proc/meminfo` to a few steps.

https://cloud.drone.io/alpinelinux/aports/4390

**Comment by tcely** [comment]
The test passed on 64bit machines. I'm wondering about an overflow now.

**Comment by bnoordhuis** [comment]
Thanks. Yeah, I think I made a critical thinking error - I didn't consider the possibility of a 32 bits application running on a 64 bits machine. Fix coming up.
