### ISSUE TITLE
VCBuild.bat generate uv.sln with end-of-line CRCRLF (Double carriage return)

### ISSUE THREAD

**Issue by fpiette** [libuv/libuv#2299]
When running VCBUILD.BAT, the uv.sln file is generated with end-of-line being "\r\r\n" (Double carriage return). This confuse MSVC2010. Manually editing uv.sln to remove the extra carriage return solves the issue.

* **Version**: 1.29.1
* **Platform**: Windows 7, MSVC2010

**Comment by refack** [comment]
Hello @fpiette,
This is most probably a bug in GYP, I'll try to look into this, but it's not simple to get hold of MSVS2010...
Might be helpful if you open an issue at https://github.com/refack/GYP, and if possible try to run the test suite.

**Comment by fpiette** [comment]
Done. See [https://github.com/refack/GYP/issues/46](url)

**Comment by bnoordhuis** [comment]
I'll close this out as it doesn't appear to be a libuv issue.
