### ISSUE TITLE
x86 not ok ipc_closed_handle

### ISSUE THREAD

**Issue by tcely** [libuv/libuv#2307]
https://github.com/libuv/libuv/blob/f0ed5df5e8c567cf97f5b0d64d1123940c1e394d/test/test-ipc.c#L870-L895

https://github.com/libuv/libuv/blob/f0ed5df5e8c567cf97f5b0d64d1123940c1e394d/test/test-ipc.c#L601

I have no idea why but our CI is failing on this test.

libuv-v1.28.0 - https://cloud.drone.io/alpinelinux/aports/3759
libuv-v1.29.1 - https://cloud.drone.io/alpinelinux/aports/4498

**Comment by ncopa** [comment]
This seems to only happen in a docker container on 32 bit x86.

**Comment by santigimeno** [comment]
I haven't been able to reproduce it with the `i386/alpine:edge` image. Do you have a way to reproduce it?

**Comment by dod38fr** [comment]
I've a the same failure while building a package for Debian on mips arch.

For more details, see [full mips build log](https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=mips&ver=1.30.1-1&stamp=1564136419&raw=0)

All the best

Dod (for Debian)

**Comment by bnoordhuis** [comment]
There's at least one bug in the test:
https://github.com/libuv/libuv/blob/ecff27857dafe3f5d30a6ab8646ea69a93e4940a/test/test-ipc.c#L602
Note that insidious single `=`.

**Comment by vtjnash** [comment]
FWIW, still failing on CI:
```
not ok 140 - ipc_closed_handle
# timeout
# Output from process `ipc_closed_handle`:
# Assertion failed in test/test-ipc.c on line 601: status == 0
```
https://ci.nodejs.org/job/libuv-test-commit-linux/1748/nodes=centos7-arm64-gcc48/console

**Comment by vtjnash** [comment]
https://github.com/libuv/libuv/runs/974332547```
not ok 142 - ipc_closed_handle
# exit code 134
# Output from process `ipc_closed_handle`:
# uv_run_tests_a: /home/runner/work/libuv/libuv/src/unix/core.c:255: uv__finish_close: Assertion `!(handle->flags & UV_HANDLE_CLOSED)' failed.
# qemu: uncaught target signal 6 (Aborted) - core dumped
# exit_cb
# Assertion failed in /home/runner/work/libuv/libuv/test/test-ipc.c on line 106: `term_signal == 0` (6 == 0)
# qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by bnoordhuis** [comment]
> `# uv_run_tests_a: /home/runner/work/libuv/libuv/src/unix/core.c:255: uv__finish_close: Assertion `!(handle->flags & UV_HANDLE_CLOSED)' failed.`

I think that's a double close of the `tcp_server` handle in test/test-ip.c. `send_handle_and_close()` is called twice when enough data queues up:
https://github.com/libuv/libuv/blob/953f901dd2330a9979838cd43ff04eacde71b25a/test/test-ipc.c#L610-L611
https://github.com/libuv/libuv/blob/953f901dd2330a9979838cd43ff04eacde71b25a/test/test-ipc.c#L895-L896
Specifically, the order of events is this:
1. Handle is closed
2. In-flight write request completes, callback closes handle again

**Comment by bnoordhuis** [comment]
My system appears to be too fast to hit the `channel.write_queue_size > 0` code path reliably.

I observe that sometimes the `ASSERT_EQ(status, UV_EBADF)` in `closed_handle_write_cb()` fails because `status == 0`, i.e., the write completes before the `channel` handle is closed.

I've been poking at the test for 30 minutes now and I'm increasingly of the opinion that it's very rickety. I'm moving to remove it. I'll open a PR.
