### ISSUE TITLE
unix: optionally accept() on dedicated thread

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2311]
This would be an opt-in (e.g. through `uv_loop_configure()`) to tell libuv to start a dedicated thread for accepting new connections with the goal of increasing the accept rate.

edit: I forgot to mention another important reason for doing this: fairer load distribution in multi-process setups! Blocking accept() is also immune to the thundering herd problem.

Libuv currently mixes poll/epoll_pwait/etc. with accept() on the event loop thread. This has somewhat unpredictable latency because:

1. It might be any of the `N` events that the kernel reports, and

2. Requires two system calls rather than just one. In fact, it requires at least three because libuv calls accept() in a loop until it sees EAGAIN or the application tells it to stop.

Moving accept() to a dedicated thread has the following advantages:

1. Predictable latency (hopefully - CPU scheduler vagaries could be an issue)

2. Doesn't require extraneous system calls.

Communicating the new connections back to the event loop thread has some issues:

1. Unpredictable latency. It would probably be implemented by means of a `uv_async_t`, bringing us back to the "any of `N` events" issue - but I think we can mitigate that by adding an atomic "have pending async handles?" check around poll/epoll_pwait/etc. calls. (edit: #2312)

2. Unchecked accepting. There needs to be some rate limit mechanism to slow down the accept thread when it's accepting faster than the event loop thread can process them.

Communicating from the event loop thread to the accept thread also has some issues:

1. Waking up from accept(). Could either be done through:

    1. Signals. Problematic since libuv doesn't own the signal handler.

    2. `setsockopt(SO_RCVTIMEO)` with a `N` ms timeout and then check-and-loop. Inelegant?

    3. `pthread_cancel()`. Doesn't wake, just terminates the thread, but that might be sufficient for our needs.

General problems/issues:

1. What to do when thread creation fails? I vote for reverting to the old poll+accept behavior.

2. It may not be faster at all, or have better throughput but worse latency. Needs careful benchmarking. A throughput/latency trade-off may still be worth it for some applications.

**Comment by santigimeno** [comment]
From what I understand it looks like something worth to explore. I have some questions:

Considering `uv_async_t` is used:
- Wouldn't still be necessary 2 syscalls in the dedicated thread (`accept()` and `write()`)?
- How would the _accepted  fd_ would be sent to the event loop thread? Using the `uv_handle_t.data` field? What if multiple `accept()` succeed before the `async_cb` is called?

> Signals. Problematic since libuv doesn't own the signal handler.

Do you mean that the embedded does or something else? :man_shrugging: `pthread_kill()` wouldn't work either right?

> What to do when thread creation fails? I vote for reverting to the old poll+accept behavior.

:+1:

**Comment by bnoordhuis** [comment]
> Wouldn't still be necessary 2 syscalls in the dedicated thread (accept() and write())?

Only in the worst case scenario. If the `uv_async_t` handle is already pending, the write() system call is elided.

In fact, we should be able to elide more write() calls than we do now if we switch from a per-handle "is pending?" flag to a per-loop flag.

> How would the accepted fd be sent to the event loop thread?

Libuv would malloc some internal struct that contains a queue or list.

> Do you mean that the embedder does or something else? 🤷‍♂ pthread_kill() wouldn't work either right?

That's right, the embedder owns signal handlers.

**Comment by gireeshpunathil** [comment]
@bnoordhuis - great idea. how about the peer thread manage the entire kernel interfacing part of the loop? i.e., preparing the I/O, polling and supplying the result? with both the threads communicating at two discrete points: watcher queues, and at the result set.

**Comment by bnoordhuis** [comment]
@gireeshpunathil Hi Gireesh, sorry for the delay.

It's something I've prototyped a few times but there are performance problems with some workloads. Anything that does lots of small reads and writes tends to suffer because of the synchronization overhead.

Part of that is self-inflicted - e.g., the libuv API contract stipulates that `uv_alloc_cb` and `uv_read_cb` are called on the main thread - but synchronization to propagate state changes still has to happen even without the self-inflicted parts.

**Comment by bnoordhuis** [comment]
I'll close this out for now because I'm not going to get around to it in the near future.
