### ISSUE TITLE
uv_get_constrained_memory does not seem to work? (checked under cgroup2)

### ISSUE THREAD

**Issue by ChALkeR** [libuv/libuv#2315]
* **Version**: 1.29.1
* **Platform**: `Linux yoga 5.1.5-arch1-2-ARCH #1 SMP PREEMPT Mon May 27 03:37:39 UTC 2019 x86_64 GNU/Linux`

Running on Node.js master (libuv 1.29.1).

`uv_get_constrained_memory()` does not seem to work, it returns 0 when there was a limit set via cgroups.

To clarify — this does not work under `unified` cgroup hierarchy, i.e. when `/sys/fs/cgroup` has been mounted with type=`cgroup2`.

I do not know if this works under `legacy` or `hybrid` hierarchies (I have not tested those), but those two are deprecated and upstream is migrating off them. And they don't allow controlling resource limits from user, that requires root access.

To test:
* Boot the system with `systemd.unified_cgroup_hierarchy=1` option
* Run node (from user) with `systemd-run --user --scope --property=MemoryMax=100M ./node`
* Observe the return value of `uv_get_constrained_memory()`, which is 0. It shouldn't be zero.
  E.g.,  `Buffer.alloc(100e6).fill(0),0` fails.

Refs:
* https://github.com/libuv/libuv/pull/2289
* https://github.com/nodejs/node/pull/27508
* https://github.com/nodejs/node/pull/27805
* https://github.com/systemd/systemd/blob/master/docs/CGROUP_DELEGATION.md#three-different-tree-setups-
* https://fedoraproject.org/wiki/Changes/CGroupsV2

/cc @kjin @evanlucas

**Comment by bnoordhuis** [comment]
Libuv reads `/sys/fs/cgroup/memory/memory.limit_in_bytes`. I expect it's in `/sys/fs/cgroup` (i.e., one level up) on your system?

PR to look in different locations welcome.

**Comment by ChALkeR** [comment]
@bnoordhuis No, the correct location is different.

Here is how it could be retrieved:

```console
$ cat /proc/`pidof node`/cgroup
0::/user.slice/user-1000.slice/user@1000.service/run-rd4588fe8a4124b61a713b7995d317c31.scope
$ cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/run-rd4588fe8a4124b61a713b7995d317c31.scope/memory.max
104857600
```

**Comment by kjin** [comment]
Thanks for taking the time to test this -- I will look into this as well.

**Comment by kjin** [comment]
I do remember seeing in the cgroups docs that one should use `/proc/self/cgroup` to look up the directory in which the control group params should be found, but this didn't seem to work in docker containers. It does seem like the right approach as long as we can figure out what to do when the linked directory doesn't exist (like in docker's case):

```
root@23179ace7ef2:/home# cat /proc/self/cgroup
(...)
5:memory:/docker/23179ace7ef243dbf35bd5ccabb172ca7971e0aa29af1763fc53b21aa73622b2
(...)
root@23179ace7ef2:/home# ls /sys/fs/cgroup/memory/docker/23179ace7ef243dbf35bd5ccabb172ca7971e0aa29af1763fc53b21aa73622b2
ls: cannot access '/sys/fs/cgroup/memory/docker/23179ace7ef243dbf35bd5ccabb172ca7971e0aa29af1763fc53b21aa73622b2': No such file or directory
```

**Comment by ChALkeR** [comment]
@kjin, I don't think that the system you are testing this on uses unified hierarchy.

What does `mount | grep cgroup` show?

**Comment by kjin** [comment]
Right, it doesn't. It's a different issue that I mentioned because it seems clear that reading `/proc/$pid/cgroup` is a reliable way to get the directory in which the correct params were located, but that issue was a case where I wasn't sure how we should proceed using that directory, since it doesn't exist.

Ok, the format of `/proc/$pid/cgroup` makes sense, where `:memory:` would indicate legacy hierarchy location, `::` would suggest a unified hierarchy.

**Comment by ChALkeR** [comment]
@kjin https://github.com/systemd/systemd/blob/master/docs/CGROUP_DELEGATION.md#three-different-tree-setups- lists a better way to check which cgroup version is used:

> If you wonder how to detect which of these three modes is currently used, use
`statfs()` on `/sys/fs/cgroup/`. If it reports `CGROUP2_SUPER_MAGIC` in its
`.f_type` field, then you are in unified mode. If it reports `TMPFS_MAGIC` then
you are either in legacy or hybrid mode. To distinguish these two cases, run
`statfs()` again on `/sys/fs/cgroup/unified/`. If that succeeds and reports
`CGROUP2_SUPER_MAGIC` you are in hybrid mode, otherwise not.

**Comment by kjin** [comment]
Ok, thanks. So it seems like the following process is necessary:

1. Determine whether we are in `unified`/`legacy`/`hybrid` mode
1. In `/proc/$pid/cgroup`, treat each line as of the form `$1:$2:$3` and read the line where `$2` is:
  * is blank (for `unified`),
  * contains `memory` (for `legacy`)
  * is `unified` (for `hybrid`)
1. Read the value of `/sys/fs/cgroup/$2/$3/memory.limit_in_bytes`. `$3` might need to be resolved according to [this document](http://man7.org/linux/man-pages/man7/cgroup_namespaces.7.html) (I just learned that this is why docker shows non-existent hierarchies).

If that seems right, I'll go ahead and open a second PR to fix this.

**Comment by ChALkeR** [comment]
@kjin There is no `memory.limit_in_bytes` in cgroup2 controllers.
There are `memory.max` and `memory.high`, defined as:

```
  memory.high
	A read-write single value file which exists on non-root
	cgroups.  The default is "max".

	Memory usage throttle limit.  This is the main mechanism to
	control memory usage of a cgroup.  If a cgroup's usage goes
	over the high boundary, the processes of the cgroup are
	throttled and put under heavy reclaim pressure.

	Going over the high limit never invokes the OOM killer and
	under extreme conditions the limit may be breached.

  memory.max
	A read-write single value file which exists on non-root
	cgroups.  The default is "max".

	Memory usage hard limit.  This is the final protection
	mechanism.  If a cgroup's memory usage reaches this limit and
	can't be reduced, the OOM killer is invoked in the cgroup.
	Under certain circumstances, the usage may go over the limit
	temporarily.

	This is the ultimate protection mechanism.  As long as the
	high limit is used and monitored properly, this limit's
	utility is limited to providing the final safety net.
```

Ref: https://www.kernel.org/doc/Documentation/cgroup-v2.txt

**Comment by kjin** [comment]
Oops, missed that earlier. I've been running everything with various docker containers (which seems to stick to cgroups v1) so I wasn't aware that the memory params changed in v2.

**Comment by ChALkeR** [comment]
I am not exactly sure what uv_get_constrained_memory should report on v2, but my guess would be that it should be the minimum of those two? What do you think?

**Comment by kjin** [comment]
I think that makes sense. It might also be true (the documentation suggests this, but not concretely) that `high` is guaranteed to be not higher than `max`, in which case we would just need to look at `high`.

**Comment by ChALkeR** [comment]
@kjin Another thing re: https://github.com/libuv/libuv/issues/2315#issuecomment-497066499 — I am not observing `:unified:` entries in `/proc/*/cgroup` files in hybrid mode (i.e. when `/sys/fs/cgroup` is v1, but `/sys/fs/cgroup/unified` is present with v2), I am observing `:memory:`, like in legacy mode.

**Comment by kjin** [comment]
Ok, I think that is in line with what your linked doc (about the three modes) says about hybrid mode -- that when v1 and v2 co-exist, v2 usually has no controllers because they are exclusively used by v1. It's a little curious though that `memory.pressure` exists on its own, though. Is that the only param in the entire `unified` directory, or are there others (that aren't memory-related)?

**Comment by kjin** [comment]
In addition -- do you think it's a sound assumption that `systemd` will exclusively be in charge of mounting cgroups vfs's in their expected directories? It's possible that a user would boot a system without cgroups on by default and enable it themselves, in which case it's not necessarily true that cgroups will be mounted on `/sys/fs/cgroup` or otherwise according to how `systemd` does it. It's very much an edge case, but we can support either way by reading `/proc/*/mountinfo` to check where cgroups is mounted, rather than assume that it will be one of the three `systemd` modes.

**Comment by ChALkeR** [comment]
> Is that the only param in the entire unified directory, or are there others (that aren't memory-related)?

There are others, but they are not memory-related as far as I remember. I'm from my other system atm and can't check, but it's easy to reproduce simply with booting in with `systemd.unified_cgroup_hierarchy=1` option in any recent Linux distro =).

> And my guess is that /proc/*/mountinfo shows cgroup2 mounted on /sys/fs/cgroup/unified, hence why "unified" isn't in /proc/*/cgroup?

I don't think that I understand the question.

> do you think it's a sound assumption that systemd will exclusively be in charge of mounting cgroups vfs's in their expected directories?

On systemd-enabled systems -- yes, in general -- no. There is also Android, for example, but it should have a similar layout (in `/sys/fs/cgroup`), I think? I haven't checked. Ref: [android sources](https://android.googlesource.com/platform/system/core/+/master/rootdir/init.rc#14).


I am not sure if any more logic is needed to determine the mount location of the cgroup hierarchy, `/sys/fs/cgroup` should be fine, I guess (unless someone points out a commonly used system where it is configured differently or is going to be configured differently).

**Comment by ChALkeR** [comment]
Could this be reopened, please?

**Comment by ChALkeR** [comment]
@cjihrig I don't think that `no-stale` works.

**Comment by kjin** [comment]
@cjihrig (+ @bnoordhuis) Is there anything we can do about the stalled PR #2323? I'm afraid the longer it languishes the less context I will have on it (I've stopped working on Node-related stuff for a while now).

**Comment by cjihrig** [comment]
AFAIK, #2323 just needs sign off from Ben. It's not a tiny PR, so I imagine he just hasn't had the time.
