### ISSUE TITLE
uv_os_tmpdir, uv_os_homedir  behavior on windows when TMP is empty string 

### ISSUE THREAD

**Issue by musm** [libuv/libuv#2328]
On windows it seems that `uv_os_tmpdir`'s behavior when the environment variable `TMP` is set to an empty string is  incorrect, the function returns fine and no error is raised, even though the sz and buffer look to contain random chars.

**Comment by bnoordhuis** [comment]
I have no way to test right now but`uv_os_tmpdir()` calls out to [`GetTempPath()`](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-gettemppatha). If what you're saying is true, that would indicate a bug in that function but that seems unlikely.

Perhaps you can add some debug printfs and see what it says? It's in src/win/util.c.

**Comment by musm** [comment]
I would check  the  size of the buffer returned by `uv_os_tmpdir` , since `nBufferLength` returns 1 when calling ` GetTempPath()` directly, but when calling `uv_os_tmpdir` the `size` argument returns `6` for some reason?

**Comment by vtjnash** [comment]
I tested from nodejs (12.4.0), and `os.tmpdir()` seems to behave correctly (returns 'C:\\Windows\\temp')

**Comment by musm** [comment]
@vtjnash  is this with `TMP` set to the empty string?  I tested both of these function within julia, and changed the environment variable within Julia as well; i.e. `ENV["TMP"]=""`.

**Comment by vtjnash** [comment]
Yes, do you perhaps have another influential environment variable set (or not set)?

**Comment by musm** [comment]
```
julia> ENV["USERPROFILE"] = ""
""

julia> ENV["TEMP"] = ""
""

julia> ENV["TMP"] = ""
""

# the following uses GetTempPath

julia> tempdir()
"剈"

julia> tempdir()
"\0"

julia> tempdir()
"ఠ"

```
But it seems unlikely that GetTempPath has a bug

**Comment by cjihrig** [comment]
> I tested from nodejs (12.4.0), and `os.tmpdir()` seems to behave correctly (returns 'C:\Windows\temp')

Node doesn't use `uv_os_tmpdir()`.

**Comment by vtjnash** [comment]
Ah, ok. I can confirm that GetTempPathW does return garbage.

```
julia> path = ones(UInt16, 1024); ccall(:GetTempPathW, stdcall, UInt32, (UInt32, Ptr{UInt16}), length(path), path)
0x00000001

julia> transcode(String, path)
"\x01\x01\x01\x01\x01\x01..."
```

**Comment by musm** [comment]
So looks like a `GetTempPathW ` bug? Pretty odd since when all those environment variables are unset it should return option 4. The Windows directory, according to their docs.

**Comment by musm** [comment]
OTOH the function is not guaranteed to return a valid path.

**Comment by bnoordhuis** [comment]
So, what do we do? According to the docs a value > 0 means success but since the path is terminated by a backslash (and thus must be at least two chars long), should we also treat 1 as an error?

**Comment by musm** [comment]
Does it make sense to either:
1. Return the empty string
2. Return `The Windows directory.` (see https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-gettemppatha#remarks)

**Comment by musm** [comment]
In fact if someone sets the `TMP` variable to an empty string I think it would be the most consistent to just return  an empty string instead of error. For one, `GetTempPathW` doesn't error so it is consistent with that behavior. And since `GetTempPathW` returns gargbage, it seems ok to just return an empty string, since the docs say  the path is not guaranteed to be valid.

**Comment by vtjnash** [comment]
yes, seems like it's an unintentional error in it's attempt to form an absolute path, so anything less than `X:\` (3 char) is actually invalid

**Comment by bnoordhuis** [comment]
Who is volunteering to PR a fix and regression test? :-)

<sup>/me steps away</sup>

**Comment by musm** [comment]
`uv_os_homedir` has a similar problem when `USERPROFILE` or `HOME` is the empty string

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
not stale
