### ISSUE TITLE
uv_chdir fails for long paths  on windows

### ISSUE THREAD

**Issue by musm** [libuv/libuv#2331]
MAX_PATH is 260 ANSI version of SetCurrentDirectory. However since libuv is using the unicode version the maximum path can be  32767.   

> To extend this limit to 32,767 wide characters, call the Unicode version of the function and prepend "\\?\" to the path. For more information, see Naming a File.

see https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#win32-file-namespaces 

The function also doesn't handle UNC paths and spits `ENOENT`, but I guess that has been a TODO 
https://github.com/libuv/libuv/blob/c4e9657d59723a6273ce68bda935680e1b3596c5/src/win/util.c#L264 ?

**Comment by musm** [comment]
Bump, there seems to be other API functions where long path support here doesn't work.

**Comment by santigimeno** [comment]
@libuv/windows

**Comment by musm** [comment]
For reference in my application I followed 
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

however libuv throws an errors when using function that support the extended path API (such as chdir)

**Comment by bnoordhuis** [comment]
If there is a way to transparently support that, I think we'd be open to that.

Checking the registry is easy but I don't know how libuv could divine whether the manifest contains that `longPathAware` key. Maybe it's possible to inspect the errors and retry?

**Comment by musm** [comment]
From my understanding libraries should transparently work for long paths as long as the user enables the flag in the registry? It's not 100% clear to me if that's how this works.

**Comment by musm** [comment]
not stale

**Comment by vtjnash** [comment]
PR's welcome to reduce dependence on MAX_PATH (or at least change it to a large value)

**Comment by musm** [comment]
thanks @bzoz !

**Comment by bzoz** [comment]
Thanks for reporting the issue and basically providing a solution 😃
