### ISSUE TITLE
uv_os_tmpdir bug on Windows when TMP variable is 260 chars

### ISSUE THREAD

**Issue by musm** [libuv/libuv#2336]
On Windows:

When `TMP` environment variable is 260 chars (without the trailing slash) or 261 chars (with the trailing slash), `uv_os_tmpdir` throws an `UV_EIO ` error which it shouldn't, since the total buffer size allowable for this function  is `PATH_MAX + 1` chars so in principle it is fine  to have `TMP` set to a directory of length 261 chars (including the trailing slash). 

Here's the issue:

- Set the environment variable `TMP` to a `MAX_PATH` length char (total `MAX_PATH`+1, including the trailing slash which is added automatically even if `TMP` does not include it)
- set the input buffer size to `GetTempPathW`  to length `MAX_PATH+1`
- `GetTempPathW`  reports that the required buffer size is 262 instead of 261

Fix
- Set the input buffer size to `GetTempPathW`  to length `MAX_PATH+2`

I think the documentation should say that the max variable size is `PATH_MAX+1` (including the trailing slash) and  not including the null terminator.

There must be a typo with the return value in MSDN as well:  "The maximum possible return value is MAX_PATH+1 (261)." Clearly this is false (see the following post).  

There is another typo in the documentation 

> A pointer to a string buffer that receives the null-terminated string specifying the temporary file path. The returned string ends with a backslash, for example, "C:\TEMP". 

Which is again false. It should be  "C:\Temp\"  (see https://github.com/MicrosoftDocs/feedback/issues/898)

This gives me hope that there is just a problem in the documentation.

**Comment by musm** [comment]
The following Julia code demonstrates this 

```julia
const MAX_PATH = 260
function tempdir1()
    temppath1 = Vector{UInt16}(undef, MAX_PATH+1)
    println("input buffer length $(length(temppath1))")
    lentemppath = ccall(:GetTempPathW, stdcall, UInt32, (UInt32, Ptr{UInt16}), length(temppath1), temppath1)
    println("returned buffer length $lentemppath")
    resize!(temppath1, lentemppath)
    return transcode(String, temppath1)
end

function tempdir2()
    temppath2 = Vector{UInt16}(undef, MAX_PATH+2)
    println("input buffer length $(length(temppath2))")
    lentemppath = ccall(:GetTempPathW, stdcall, UInt32, (UInt32, Ptr{UInt16}), length(temppath2), temppath2)
    println("returned buffer length $lentemppath")
    resize!(temppath2, lentemppath)
    return transcode(String, temppath2)
end


# Maximum possible length is  MAX_PATH + 1 = 261 not including the null!
# I.e. max string length without trailing backslash is 260
PATH_PREFIX = "C:\\"
tmp = PATH_PREFIX * "x"^((MAX_PATH + 1) - length(PATH_PREFIX) - 1) # subtract 1 for null-terminator
println("length of TMP env var is $(length(tmp))")
ENV["TMP"] = tmp
@show tempdir1()
@show length(tempdir1())
@show tempdir2()
@show length(tempdir2())


```

**Comment by santigimeno** [comment]
I think this was fixed by https://github.com/libuv/libuv/pull/2341.
