### ISSUE TITLE
thread safety of misc utils

### ISSUE THREAD

**Issue by musm** [libuv/libuv#2339]
Apparently `uv_os_homedir` is thread safe, but the docs say otherwise https://github.com/libuv/libuv/blob/master/docs/src/misc.rst . 

Suggestion: Double-check https://github.com/libuv/libuv/blob/master/docs/src/misc.rst to verify thread safety warnings for `uv_os_homedir,uv_os_tmpdir`  and the functions `uv_os_getenv,uv_os_setenv,uv_os_unsetenv`  are correct.

**Comment by cjihrig** [comment]
`uv_os_homedir()` was labeled as not MT-safe [here](https://github.com/libuv/libuv/pull/350#discussion_r30496653). I believe similar reasoning applies to the other functions as well.
