### ISSUE TITLE
Can libuv be port to ARM Cortex-M4 MCUs?

### ISSUE THREAD

**Issue by hankchan** [libuv/libuv#235]
I want to use a project on an ARM Cortex-M4 MCU ,but the project depends on libuv.

I want to known,is it possible to port libuv to ARM Cortex-M4 or do you have any plan for that?

Thanks.

**Comment by saghul** [comment]
I don't know how portling libuv to that platform would go, but there are definitely no plans for it.

**Comment by bnoordhuis** [comment]
I can't think of a reason why libuv wouldn't work as-is.  Cortex-M4 is basically ARMv7.  FreeBSD/ARM might need some work (stress on 'might') but Linux should be no problem.

**Comment by fivdi** [comment]
Given that the Cortex-M4 is a microcontroller rather than an application processor, typically with 1 or 2 megabytes of flash and less than 1 megabyte or RAM, I'd imagine that this would be a very challenging task.

**Comment by bnoordhuis** [comment]
That's true, but libuv by itself doesn't use much memory.  I have a simple libuv based web server running on and old MIPS router that uses just over 500 kB virtual memory (i.e. code, data, stack and heap.)

**Comment by hankchan** [comment]
I think it is worth doing that work,especial in IoT(Internet Of Things) field. 
Nowadays the ARM Cortex-Mx(M0/M0+/M3/M4) MCUs are very popular in Iot.
With Libuv ,it will be possible to do many thing interesting as fast as possible.

**Comment by saghul** [comment]
Closing since it's not an issue. Please feel free to open new ones if specific issues arise!
