### ISSUE TITLE
linux: `uv_cpu_info()` online/offline CPU race

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2351]
`uv_cpu_info()` on Linux:

1. First consults `/proc/stat` to get the number of online CPUs, then

2. Reads the CPU info from `/proc/cpuinfo`, then

3. Reads idle/irq/nice/user/sys from `/proc/stat`

There is a time window between (1) and (2) and (2) and (3) where a CPU could come online or go offline.

Libuv should handle that, probably by:

4. Meticulously checking if the number of observed CPU entries in (2) and (3) matches the expected number of CPUs, and

5. Restart from (1) if that isn't the case.

**Comment by ktrongnhan** [comment]
Looks great for my vacation. May I have the job?

**Comment by saghul** [comment]
Go for it!

**Comment by ktrongnhan** [comment]
I would appreciate it if someone can help review the proposed solution here https://github.com/libuv/libuv/pull/2359
