### ISSUE TITLE
test: there is a test failed when running "make check"

### ISSUE THREAD

**Issue by caixiangyue** [libuv/libuv#2356]
* **Version**: v1.x
* **Platform**: Ubuntu 18.04.2 LTS x86_64 
* **gcc version:** gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

```
not ok 117 - getaddrinfo_fail
# timeout
# Output from process `getaddrinfo_fail`: (no output)
```

**Comment by bnoordhuis** [comment]
Thanks for the report. That test makes a DNS query for `xyzzy.xyzzy.xyzzy.` (not expected to resolve to anything) which seems to time out on some people's networks.

Suggestions on how to improve that welcome. Otherwise we should probably just close this out.
