### ISSUE TITLE
Is there a way to detach uv_stream_t from FD?

### ISSUE THREAD

**Issue by eugeneo** [libuv/libuv#2365]
I have two threads with two event loops. I need to path TCP connections and/or pipes between them (I may also need to pass files at a later point).

My understanding is that it is not directly supported. Is there a way to "detach" uv_tcp_t from the FD so `uv_tcp_open` could be used on another thread?

**Comment by vtjnash** [comment]
Use `dup` (the syscall, although I think I'd like a `uv_dup` some day: https://github.com/libuv/libuv/pull/1994) or `uv_write2`. This isn't really a good place to ask questions though.
