### ISSUE TITLE
rfc: always poll for I/O in uv_run()?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2370]
Refs: https://github.com/nodejs/node/issues/28502

Libuv does not poll for I/O when there are no ref'd handles. In the linked issue that causes Node.js to miss the SIGTERM event because the `uv_signal_t` is unref'd and it's the only active handle.

We can do 1 of 3 things:

1. Do nothing. It's the documented behavior.

2. Special case : poll with a zero timeout when any signal handles are active, ref'd or unref'd. Complicated because `uv_loop_t` doesn't track them explicitly.

3. General case: always poll for I/O in `uv_run()`. It's an easy fix but a change in behavior. Maybe it's the behavior most people expect though.
```diff
diff --git a/src/unix/core.c b/src/unix/core.c
index 202c75bb..2d15a934 100644
--- a/src/unix/core.c
+++ b/src/unix/core.c
@@ -351,8 +351,11 @@ int uv_run(uv_loop_t* loop, uv_run_mode mode) {
   int ran_pending;

   r = uv__loop_alive(loop);
-  if (!r)
+  if (r == 0) {
     uv__update_time(loop);
+    mode = UV_RUN_NOWAIT;
+    r = 1;
+  }

   while (r != 0 && loop->stop_flag == 0) {
     uv__update_time(loop);
```
Makes the check_ref, idle_ref and prepare_ref tests fail because they don't expect to have their callbacks called.

Has a minor inefficiency calling `uv__update_time()` twice when `loop->stop_flag == 0` but that can be fixed.

**Comment by saghul** [comment]
I'd go for 1) and err on the side of caution.

**Comment by santigimeno** [comment]
> I'd go for 1) and err on the side of caution.

I agree.

**Comment by cjihrig** [comment]
I agree as well.

**Comment by bnoordhuis** [comment]
So decided then. :-)

**Comment by bnoordhuis** [comment]
Belated: this issue is a duplicate of #276 from 2015, also reported by yours truly.
