### ISSUE TITLE
API to distinguish types of symlinks on Windows

### ISSUE THREAD

**Issue by tniessen** [libuv/libuv#2384]
* **Version**: master
* **Platform**: Windows

It is already possible to control the type of a symlink that is created using `uv_fs_symlink` on Windows using the `UV_FS_SYMLINK_DIR` and `UV_FS_SYMLINK_JUNCTION` flags. However, it does not appear to be possible to retrieve the same information about an existing symlink. Would it make sense to add such an API?

(This feature was requested in https://github.com/nodejs/help/issues/1520.)

**Comment by bnoordhuis** [comment]
Libuv doesn't do platform-specific APIs. If you can rephrase it as something that's meaningful across platforms, then it's something we could consider.

The first one that comes to mind is teaching `uv_fs_lstat()` about junctions-vs-symlinks, although I'm not sure if that could be done in a backwards compatible manner.

The relevant logic is here in case you're interested in working on that:
https://github.com/libuv/libuv/blob/ecff27857dafe3f5d30a6ab8646ea69a93e4940a/src/win/fs.c#L1660-L1670

**Comment by tniessen** [comment]
> Libuv doesn't do platform-specific APIs.

That was my understanding as well, until I stumbled upon `UV_FS_SYMLINK_JUNCTION`.

> The relevant logic is here in case you're interested in working on that:

What about `st_flags`?

https://github.com/libuv/libuv/blob/ecff27857dafe3f5d30a6ab8646ea69a93e4940a/src/win/fs.c#L1719-L1722

**Comment by bnoordhuis** [comment]
It's a rule but even the best rules are sometimes broken. :-)

No strong opinion on `st_flags` but maybe @bzoz or @joaocgreis does.

**Comment by bzoz** [comment]
I'm OK with using `st_flags` for that.
