### ISSUE TITLE
@libuv/windows team?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2385]
We have a number of teams for different platforms but not `@libuv/windows`.

@bzoz @joaocgreis Do you want me to create one and add you? Anyone else who should be part of it?

**Comment by bzoz** [comment]
Sure!

**Comment by vtjnash** [comment]
I'd like to be added too.

**Comment by fpiette** [comment]
What is the responsibility/work for team member? I ask because I could be interested being a member.

**Comment by saghul** [comment]
maybe @refack ?

**Comment by joaocgreis** [comment]
@bnoordhuis yes, please add me. Thanks!

**Comment by bnoordhuis** [comment]
@bzoz @joaocgreis @vtjnash Added!

@fpiette Basically maintainership: provide feedback, review code, answer questions.

@saghul Is he still active? @refack?

**Comment by saghul** [comment]
> @saghul Is he still active? @refack?

Not sure :-) I just remembered he used to know windows things.

**Comment by bnoordhuis** [comment]
Closing, the team has been created.
