### ISSUE TITLE
win,tty: Confusion over who will handle ANSI escape sequences

### ISSUE THREAD

**Issue by mcnameej** [libuv/libuv#2389]
* **Version**: 1.30.2
* **Platform**: Windows 10

I've been trying to chase down strange Windows console behavior observed with node. Some programs display colored output correctly, while others display uninterpreted ANSI escape sequences.

Here's what I found...

uv_tty_init() calls uv__determine_vterm_state() to find out if Windows can handle ANSI escape sequences itself.

uv__determine_vterm_state() tries setting the ENABLE_VIRTUAL_TERMINAL_PROCESSING console mode flag bit.  If Windows allows it to be set, it means Windows can handle ANSI escape sequences itself.  uv__vterm_state is set to UV_SUPPORTED in this case.

uv_tty_write_bufs() checks if uv__vterm_state is UV_SUPPORTED. If it is, the output string is converted from UTF-8 to UTF-16, and then passed directly to Windows (via FLUSH_TEXT macro, which eventually calls WriteConsoleW).

This all looks correct to me.  Here's the problem...

uv_tty_set_mode() changes the console mode, but doesn't include the ENABLE_VIRTUAL_TERMINAL_PROCESSING flag.  Net result is that after uv_tty_set_mode() is called, Windows no longer processes ANSI escape sequences.  However, uv_tty_write_bufs() doesn't know this, and keeps sending strings directly to Windows.

I think the fix would be to add this...

```
  if (uv__vterm_state == UV_SUPPORTED)
    flags |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
```

...after the switch statement in uv_tty_set_mode().

This is just theoretical, based on code review.  I'm not set up to build node at the moment, so I can't change it and see what happens.  Sorry, just a bug report, not a PR. ☹️

**Comment by bzoz** [comment]
The `uv_tty_set_mode` is for stdin, it only works with [readable ttys](https://github.com/libuv/libuv/blob/79c2d7405886c8171b268f40604d87b9e5dbdeab/src/win/tty.c#L331-L333). Changing it does not affect the output buffer terminal code processing. Nodes REPL does that all the time: it runs in raw mode and switches to line mode when executing the commands, yet the colors keep working.

If however, you found some Node/libuv code that breaks this color processing, let us know. We will investigate it.

**Comment by mcnameej** [comment]
Ah!  I missed that check in the `uv_tty_set_mode` code.  I will close this issue.

So I did some more digging, and have a new suspect.  The node program that's acting strangely is calling out to an external program.  That external program is probably resetting the console mode. ☹️
