### ISSUE TITLE
i can not compile under windows

### ISSUE THREAD

**Issue by sherifomran** [libuv/libuv#2391]
I have tried compiling libuv using msys2 under windows, but i get
ISO C90 does not support unnamed structure and all these are in winapi.h

then i get error
src/win/fs.c:1950:9: warning: unused variable 'error' [-Wunused-variable]
 1950 |   DWORD error;

**Comment by saghul** [comment]
What shell are you on, the MSYS2 shell or the MinGW-w64 shell? The former is not supported and it's not really supposed to be used to compile things other than the toolchain itself IIRC.

**Comment by liyoubdu** [comment]
there are no uv_last_error,  what function can i use instead.

**Comment by saghul** [comment]
@liyoubdu Your problem is unrelated. You seem to be using a very old libuv API, please check the documentation.

**Comment by bnoordhuis** [comment]
This issue seems to have run its course. Closing.
