### ISSUE TITLE
Tests failing over PowerPC and x86_64

### ISSUE THREAD

**Issue by josecgon** [libuv/libuv#2393]
Hello.

I'm using the last stable release: v1.30.1

I'm crosscompiling your library for PowerPC, and while executing the tests I have found some tests failing, here you have the info about the machine and the failing tests

```
# uv_os_uname:
#   sysname: Linux
#   release: 4.14.67-ic500
#   version: #8 SMP PREEMPT Wed Feb 13 12:09:40 CET 2019
#   machine: ppc64

not ok 48 - fs_copyfile
# exit code 134
# Output from process `fs_copyfile`:
# Assertion failed in /home/jgonzalez/UVW/release/libuv-1.30.1/test/test-fs-copyfile.c on line 133: r == 0

not ok 63 - fs_event_watch_file_twice
# exit code 134
# Output from process `fs_event_watch_file_twice`:
# Assertion failed in /home/jgonzalez/UVW/release/libuv-1.30.1/test/test-fs-event.c on line 635: 0 == uv_fs_event_start(watchers + 0, fail_cb, path, 0)

not ok 87 - fs_read_bufs
# exit code 134
# Output from process `fs_read_bufs`:
# Assertion failed in /home/jgonzalez/UVW/release/libuv-1.30.1/test/test-fs.c on line 2730: 0 <= uv_fs_open(NULL, &open_req1, "test/fixtures/lorem_ipsum.txt", O_RDONLY, 0, NULL)

not ok 92 - fs_readdir_file
# exit code 134
# Output from process `fs_readdir_file`:
# Assertion failed in /home/jgonzalez/UVW/release/libuv-1.30.1/test/test-fs-readdir.c on line 244: r == UV_ENOTDIR

not ok 99 - fs_scandir_file
# exit code 134
# Output from process `fs_scandir_file`:
# Assertion failed in /home/jgonzalez/UVW/release/libuv-1.30.1/test/test-fs.c on line 2541: r == UV_ENOTDIR

not ok 167 - pipe_connect_to_file
# exit code 134
# Output from process `pipe_connect_to_file`:
# Assertion failed in /home/jgonzalez/UVW/release/libuv-1.30.1/test/test-pipe-connect-error.c on line 53: status == UV_ENOTSOCK || status == UV_ECONNREFUSED
```

I thought it was because of the crosscompilation process, so I ran the same release over a x86_64 and I got the same tests failling, here is the machine info:

```
# uv_os_uname:
#   sysname: Linux
#   release: 4.15.0-55-generic
#   version: #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019
#   machine: x86_64
```

Do you have any idea about why those tests are failing?

Thanks a lot! :)

**Comment by josecgon** [comment]
I have also tried over an ARM 64 board, with the same failing tests, here is the machine info:

```
# uv_os_uname:
#   sysname: Linux
#   release: 4.9.79-ic103
#   version: #1 SMP PREEMPT Wed Oct 24 14:32:00 CEST 2018
#   machine: aarch64
```

**Comment by josecgon** [comment]
One last test, I have tried now for an ARM 32 board, and I have the same tests failing, but there are two more tests that fails, here you have the machine info and the new failing tests:

```
# uv_os_uname:
#   sysname: Linux
#   release: 4.0.0-xilinx
#   version: #4 SMP PREEMPT Mon Oct 8 13:02:58 CEST 2018
#   machine: armv7l

not ok 122 - getnameinfo_basic_ip6
# exit code 6
# Output from process `getnameinfo_basic_ip6`:
# Assertion failed in /home/jvico/Documentos/libuv/test/test-getnameinfo.c on line 42: status == 0

not ok 195 - process_title_threadsafe
# exit code 6
# Output from process `process_title_threadsafe`:
# Assertion failed in /home/jvico/Documentos/libuv/test/test-process-title-threadsafe.c on line 46: 0 == strcmp(buffer, titles[0]) || 0 == strcmp(buffer, titles[1]) || 0 == strcmp(buffer, titles[2]) || 0 == strcmp(buffer, titles[3])
```

**Comment by josecgon** [comment]
I have tried running it with a regular user (with no permissions), and the failing tests are the same

**Comment by ptlomholt** [comment]
Which folder are you running the tests from? See https://github.com/libuv/libuv/issues/2251#issuecomment-481837132 for a similar issue, can you try run the tests from the _parent_ folder?

**Comment by josecgon** [comment]
Ok, now I'm executing it from the parent folder and it does work for x86 with no tests failing

I've tried again over my other architectures and:

1. Over PowerPc 64, I have two possible results:

* If I run it with a root user

```
not ok 48 - fs_copyfile
# exit code 134
# Output from process `fs_copyfile`:
# Res.result 0
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-copyfile.c on line 205: req.result == UV_EAC
``` 

PS: The req.result variable has a value of 0

* And if I run it with an user with no permissions, the test 48 does work, but I get more tests failing

```
not ok 49 - fs_event_close_in_callback
# exit code 134
# Output from process `fs_event_close_in_callback`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-event.c on line 86: r >= 0
not ok 50 - fs_event_close_with_pending_event
# exit code 134
# Output from process `fs_event_close_with_pending_event`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-event.c on line 86: r >= 0
not ok 54 - fs_event_no_callback_after_close
# exit code 134
# Output from process `fs_event_no_callback_after_close`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-event.c on line 86: r >= 0
not ok 55 - fs_event_no_callback_on_close
# exit code 134
# Output from process `fs_event_no_callback_on_close`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-event.c on line 86: r >= 0
not ok 58 - fs_event_watch_dir
# exit code 134
# Output from process `fs_event_watch_dir`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-event.c on line 86: r >= 
not ok 60 - fs_event_watch_file
# exit code 134
# Output from process `fs_event_watch_file`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-event.c on line 86: r >= 0
not ok 62 - fs_event_watch_file_exact_path
# exit code 134
# Output from process `fs_event_watch_file_exact_path`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-fs-event.c on line 86: r >= 0
not ok 167 - pipe_connect_to_file
# exit code 134
# Output from process `pipe_connect_to_file`:
# Assertion failed in /home/jgonzalez/UVW/libuv/test/test-pipe-connect-error.c on line 53: status == UV_ENOTSOCK || status == UV_ECONNREFUSED
```

2. Over the ARM, I have the same situation than in the PowerPc

Thanks a lot! :)

**Comment by mhdawson** [comment]
@miladfarca FYI.  These do run in the internal CI which should just be running as the iojs user as opposed to root.

**Comment by miladfarca** [comment]
@josecgon It is related to the `user` you are logged in with, it also happens when compiling and testing master. 
When using `root` on PPC, I do get the `not ok 48 - fs_copyfile` failure, but when created a new user with `useradd -m test` and compiled and ran tests, they all passed.

**Comment by josecgon** [comment]
Hello.

I'm sorry for being so late answering.

First of all, it is not possible for me to compile the tests in the target device, I need to crosscompile it because I use several platforms, so I do not install the toolchain in the device

So, what I tried was to crosscompile it in my machine, and executing it in the target platform as a regular user (with no permissions)

It should work even if I compile it in my machine and I execute it in the target as a regular user, isn't it?

Thanks a lot

**Comment by miladfarca** [comment]
I tried cross compiling `v1.30.1` as well as `master` using `powerpc64le-linux-gnu-gcc-6` on an x86 machine, zipped the whole libuv folder and moved it to a `ppcle` machine. Created a new user with  `useradd -m test` and all the tests are passing. Please note that tests need to run from the `libuv` folder and the user should not have root privileges.

**Comment by vtjnash** [comment]
OK, I think I recognize those as `make dist` and out-of-tree build issues that have been since addressed. Since you say it's working, please make a new issue clarifying any continuing or new issues.
