### ISSUE TITLE
not ok 48 - fs_copyfile

### ISSUE THREAD

**Issue by giovannimanzoni** [libuv/libuv#2394]
Hello, on Raspberry Pi 2 B , on Raspbian OS ,I get this error: not ok 48 - fs_copyfile with autotools

**Comment by giovannimanzoni** [comment]
the full error is :

not ok 48 - fs_copyfile
# exit code 6
# Output from process `fs_copyfile`:
# Assertion failed in /home/pi/libuv/test/test-fs-copyfile.c on line 202: req.result == UV_EACCES

**Comment by santigimeno** [comment]
Are you running the tests as `root`? If it's the case, that's the reason of the failure. Make sure you run the tests as a regular user.

**Comment by giovannimanzoni** [comment]
yes as root. ok. I will try as normal user.

**Comment by giovannimanzoni** [comment]
hello, now as normal user, the test passed ! Thanks.

**Comment by jacob008** [comment]
what ？ do it in normal user？ why？ l just have a root user！
