### ISSUE TITLE
Req: Retrieve all environment variables

### ISSUE THREAD

**Issue by jdonaldson** [libuv/libuv#2400]
I made a request for getting/setting individual environment variables earlier: https://github.com/libuv/libuv/pull/1234, https://github.com/libuv/libuv/issues/1198 

Thanks again!  It works like a charm.  I have one more request : could libuv retrieve *all* environment variables?  This is actually non-trivial to get 100% correct across all OS and variable contents by simply parsing `printenv`.

FWIW We're starting to use libuv more as a base sys framework across various Haxe platforms (e.g. Lua, C++, various other VMs).  I really like the idea of using libuv more there for consistency's sake.

E.g. here's the Haxe Sys library, with the "environment" method: https://api.haxe.org/Sys.html

**Comment by bnoordhuis** [comment]
Windows has `GetEnvironmentStrings()` and Unices have `extern char** environ` (which libuv already uses in `src/unix/process.c`) so go ahead if you want to open a pull request.

What kind of API did you have in mind?

**Comment by saghul** [comment]
I actually found myself wanting this yesterday :-P

Here is a strawman proposal:

```
typedef stryct uv_env_entry_s {
    char *name;
    char *value;
} uv_env_entry_t;

int uv_os_environ(uv_env_entry_t **);
void uv_os_free_environ(uv_env_entry_t *)
```

WDYT? I can volunteer to write it.

**Comment by santigimeno** [comment]
:+1 SGTM

**Comment by cjihrig** [comment]
SGTM

**Comment by jdonaldson** [comment]
I'll ping @creationix for this since I will be using his lua wrappers for this feature.  I think what @saghul has here looks pretty straightforward though, thank you again for the interest and effort!

**Comment by saghul** [comment]
PR (WIP) https://github.com/libuv/libuv/pull/2404

**Comment by creationix** [comment]
Sounds good to me.  When this lands in a libuv release, we can update luv to use it.
