### ISSUE TITLE
Install Failed in UBUNTU 18.04

### ISSUE THREAD

**Issue by josephmiller2000** [libuv/libuv#2401]
* **Version**:  v1.30.1 
* **Platform**: Linux sockschat 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

![Snap_Shot_00068](https://user-images.githubusercontent.com/24210340/62124049-e4a8ca00-b2e6-11e9-9656-29aec049952e.png)

**Comment by saghul** [comment]
can you show the failing test?

**Comment by josephmiller2000** [comment]
I tried this method 

$ sh autogen.sh
$ ./configure
$ make
$ make check >>> this is where i got the test error.
$ make install

**Comment by saghul** [comment]
Which one? There are over 300 as you can see. The one without "ok" at the start should be the culprit.

Note that you can ignore test failures and libuv will be installed no problem.

**Comment by bnoordhuis** [comment]
No follow-up. Closing.

**Comment by josephmiller2000** [comment]
ok here it is.
![Snap_Shot_00111](https://user-images.githubusercontent.com/24210340/62916891-d2835d00-bdb7-11e9-8bf7-51451a00a97a.png)

**Comment by bnoordhuis** [comment]
Are you running the tests as root or as a user with elevated permissions?

**Comment by josephmiller2000** [comment]
Yup, im running the test using root user.

from the extracted directory from the original file.

/root/"directory where the files extracted"

https://github.com/libuv/libuv/archive/v1.31.0.tar.gz

**Comment by saghul** [comment]
There are known issues if you run tests as the root user, please don't.
