### ISSUE TITLE
Use of try-except within MinGW/Clang on Windows

### ISSUE THREAD

**Issue by Crunkle** [libuv/libuv#2407]
Neither GCC nor Clang fully support the try-except MSVC extension and so any builds as of 2c27950 fail in non-MSVC Windows environments. I have seen some dirty hacks to implement SEH outside of MSVC but they are far from portable.

See the use of `__try` and `__except` within [win/fs.c](https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L789), also [see here](https://docs.microsoft.com/en-us/cpp/cpp/try-except-statement?view=vs-2019) for reference.

I am not sure what the best solution is, but I don't see reason for the `memcpy` to fail. For that reason I want to propose something simple:

```diff
diff --git a/src/win/fs.c b/src/win/fs.c
index 83dfdca9..b2835628 100644
--- a/src/win/fs.c
+++ b/src/win/fs.c
@@ -786,6 +786,7 @@ void fs__read_filemap(uv_fs_t* req, struct uv__fd_info_s* fd_info) {
     int err = 0;
     size_t this_read_size = MIN(req->fs.info.bufs[index].len,
                                 read_size - done_read);
+#ifdef _MSC_VER
     __try {
       memcpy(req->fs.info.bufs[index].base,
              (char*)view + view_offset + done_read,
@@ -797,6 +798,11 @@ void fs__read_filemap(uv_fs_t* req, struct uv__fd_info_s* fd_info) {
       UnmapViewOfFile(view);
       return;
     }
+#else
+    memcpy(req->fs.info.bufs[index].base,
+           (char*)view + view_offset + done_read,
+           this_read_size);
+#endif
     done_read += this_read_size;
   }
   assert(done_read == read_size);
@@ -978,6 +984,7 @@ void fs__write_filemap(uv_fs_t* req, HANDLE file,
   done_write = 0;
   for (index = 0; index < req->fs.info.nbufs; ++index) {
     int err = 0;
+#ifdef _MSC_VER
     __try {
       memcpy((char*)view + view_offset + done_write,
              req->fs.info.bufs[index].base,
@@ -989,6 +996,11 @@ void fs__write_filemap(uv_fs_t* req, HANDLE file,
       UnmapViewOfFile(view);
       return;
     }
+#else
+    memcpy((char*)view + view_offset + done_write,
+           req->fs.info.bufs[index].base,
+           req->fs.info.bufs[index].len);
+#endif
     done_write += req->fs.info.bufs[index].len;
   }
   assert(done_write == write_size);
```

Reproducible on almost all non-MSVC Windows builds. Possibly fixes or related to #2391?

**Comment by saghul** [comment]
Yeah, I don't see why we need those either. We are not using this anywhere else IIRC.

Ping @libuv/windows 

@cjihrig We may want to fix this before release.

**Comment by bzoz** [comment]
One of the buffers is a memory-mapped file. If something fails while accessing the hard drive, it will be reported as an exception.

I'm OK with removing the __try block for non-MSVS compilers, with a note in the documentation that using memory mapped files can crash the program when libuv is compiled with those.

**Comment by saghul** [comment]
SGTM. Didn't we have a thing to disable CRT exceptions? Or is that something else?

**Comment by cjihrig** [comment]
I'm currently blocking the 1.31.0 release on this and one other patch. Is anyone currently working on (or planning to work on) this?

**Comment by saghul** [comment]
I think @Crunkle 's proposal is good. If they are not able to PR it I can.

**Comment by Crunkle** [comment]
PR created, thanks!

I'm not too familiar with the possible exceptions but I agree, either a warning pragma or, even better, a small note in the docs could be a good addition.
