### ISSUE TITLE
Windows: uv_os_getenv() with empty (but defined) variable

### ISSUE THREAD

**Issue by justinmk** [libuv/libuv#2413]
* **Version**: 1.30.0
* **Platform**: Windows 7, building with MSVC 2017 ([appveyor](https://www.appveyor.com/docs/windows-images-software/))

If an env var is defined as empty:

    SetEnvironmentVariable( "foo", "" );

The libuv Windows impl of `uv_os_getenv` returns `-4094` (`UV_UNKNOWN`).  

According to [this post](https://stackoverflow.com/a/22488103/152142),

> When GetEnvironmentVariable return 0, it may be that the variable doesn't exist, or that is exists with an empty content. In the later case, GetLastError returns 0.

But libuv checks `GetEnvironmentVariableW() == 0`, then returns `uv_translate_sys_error(0)`.

https://github.com/libuv/libuv/blob/8ed9112f50cfa1cb857070460f842a93dfd6753e/src/win/util.c#L1484-L1505

It should instead return `0` with `buffer` size of `0`.

**Comment by cjihrig** [comment]
So, I wrote https://github.com/cjihrig/libuv/commit/3377726c367d191548fb41f95c1c7619012d156d, which I expected to be a straightforward fix.

But, there seems to be a second issue. While trying to write a test for this issue, I set an environment variable to the empty string. Windows seems to delete the environment variable instead. There's a good chance I'm doing something wrong, and I don't have a Windows setup to test on, but that's where I'm at currently.

**Comment by saghul** [comment]
@cjihrig What Ruby does looks sensible IMHO.  I do have a Windows laptop up and running if you want me to test stuff.

**Comment by erw7** [comment]
@cjihrig https://github.com/cjihrig/libuv/commit/3377726c367d191548fb41f95c1c7619012d156d and the following patch seems to have fixed the neovim issue. I think `GetEnvironmentVariable()` doesn't set the last error code to 0 on success.

Ref. https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror

```diff
diff --git a/src/win/util.c b/src/win/util.c
index 54cf4f42..2fef4c5c 100644
--- a/src/win/util.c
+++ b/src/win/util.c
@@ -1412,13 +1412,13 @@ int uv_os_getenv(const char* name, char* buffer, size_t* size) {
   if (r != 0)
     return r;

+  SetLastError(ERROR_SUCCESS);
   len = GetEnvironmentVariableW(name_w, var, MAX_ENV_VAR_LENGTH);
+  r = GetLastError();
   uv__free(name_w);
   assert(len < MAX_ENV_VAR_LENGTH); /* len does not include the null */

   if (len == 0) {
-    r = GetLastError();
-
     if (r == ERROR_ENVVAR_NOT_FOUND)
       return UV_ENOENT;
```

> I set an environment variable to the empty string. Windows seems to delete the environment variable instead.

I don't know how you set the environment variable to empty string, but the following code appears to create an empty environment variable.

```c
SetEnvironmentVariableW(L"FOO", L"");
uv_os_setenv("BAR", ""); 
```

**Comment by cjihrig** [comment]
Thanks @erw7 - calling `SetLastError()` did the trick. Fix for this issue in https://github.com/libuv/libuv/pull/2419.
