### ISSUE TITLE
signal: closing callback never arrives which causes 'uv_loop_close' to fail

### ISSUE THREAD

**Issue by neoxic** [libuv/libuv#2415]
* **Version**: 1.29.1, 1.30.1
* **Platform**: Linux, macOS

Hello everybody!

It looks like a race condition takes place in signal handling that might sporadically cause a closing signal handle to never complete closing when multiple signals are received.

Please see the following code snippet:

```c
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <unistd.h>
#include <uv.h>

#define SHOT_COUNT 10

static void close_cb(uv_handle_t *handle) {
    fprintf(stderr, "[%d] closed %s %p\n", uv_os_getpid(), uv_handle_type_name(handle->type), handle);
}

static void walk_cb(uv_handle_t *handle, void *arg) {
    fprintf(stderr, "[%d] closing %s %p...\n", uv_os_getpid(), uv_handle_type_name(handle->type), handle);
    uv_close(handle, close_cb);
}

static void signal_cb(uv_signal_t *handle, int signum) {
    uv_walk(handle->loop, walk_cb, 0); /* Close all handles */
}

int main(int argc, char **argv) {
    uv_loop_t *loop = uv_default_loop();
    uv_signal_t sig;
    uv_process_t proc;
    int i;

    uv_signal_init(loop, &sig);
    uv_signal_start(&sig, signal_cb, SIGINT);

    i = argc == 2 ? atoi(argv[1]) : 0; /* Number of children */
    if (i < 2) {
        char seq[32];
        uv_process_options_t opts;
        uv_stdio_container_t stdio[3];
        sprintf(seq, "%d", i + 1);
        memset(&opts, 0, sizeof opts);
        memset(&stdio, 0, sizeof stdio);
        opts.file = argv[0];
        opts.args = (char **)argv;
        opts.stdio_count = 3;
        opts.stdio = stdio;
        for (i = 0; i < 3; ++i) {
            stdio[i].flags = UV_INHERIT_FD;
            stdio[i].data.fd = i;
        }
        argv[1] = seq;
        argv[2] = 0;
        assert(!uv_spawn(loop, &proc, &opts));
    }
    
    if (argc == 1) { /* Root process */
        usleep(100000); /* Let all children prepare */
        for (i = 0; i < SHOT_COUNT; ++i) uv_kill(0, SIGINT); /* Kill the whole group with a shotgun */
    }

    /* Run the show */
    uv_run(loop, UV_RUN_DEFAULT);
    if (uv_loop_close(loop)) fprintf(stderr, "[%d] uv_loop_close() failed! WTF?\n", uv_os_getpid());

    return 0;
}
```

The code is slightly esoteric by itself, so I'll explain what it does.
1. First, it initializes a SIGINT handler that closes all handles.
2. Then, the root process (child 0) spawns its child 1 which in turn spawns its child 2.
3. Finally, a series of `uv_kill(0, SIGINT)` is done in the root process to kill the whole group.

This is a simplified test-case of the environment where I first encountered the bug. Process nesting seems to be important. In my case, the bug seems to be more easily reproduced on macOS than Linux using this code.

From time to time on Linux:
```
$ ./a.out
[1110] closing signal 0xff8b5e6c...
[1110] closed signal 0xff8b5e6c
[1112] closing signal 0xffb8570c...
[1112] closing process 0xffb856c8...
[1112] closed process 0xffb856c8
[1112] uv_loop_close() failed! WTF?   <------------------
[1111] closing signal 0xff94f08c...
[1111] closing process 0xff94f048...
[1111] closed signal 0xff94f08c
[1111] closed process 0xff94f048
[1113] closing signal 0xff86837c...
[1113] closed signal 0xff86837c
```

From time to time on macOS:
```
$ ./a.out
[22180] closing signal 0x7ffee683fd30...
[22179] closing signal 0x7ffee5c11d30...
[22179] closing process 0x7ffee5c11ca8...
[22180] uv_loop_close() failed! WTF?   <------------------
[22179] closed process 0x7ffee5c11ca8
[22179] uv_loop_close() failed! WTF?   <------------------
[22178] closing signal 0x7ffeef357630...
[22178] closing process 0x7ffeef3575a8...
[22178] closed signal 0x7ffeef357630
[22178] closed process 0x7ffeef3575a8
```

*Observed behaviour*

Despite being sent multiple times, a signal is correctly received only once because the signal handler immediately closes all handles (including itself). However, after `uv_run(loop, UV_RUN_DEFAULT)` exits (which means that all closing callbacks have been processed), a call to `uv_loop_close()` unexpectedly fails which indicates there are open handles. The above output also shows that a closing callback for the signal handle never arrives.

*Expected behaviour*

After `uv_run(loop, UV_RUN_DEFAULT)` exits, a call to `uv_loop_close()` must always succeed provided all handles have been closed.

**Comment by bnoordhuis** [comment]
Thanks for the report. Is it a duplicate (or variant) of #2398?

**Comment by neoxic** [comment]
I've checked that one too. They might be related indeed and have the same underlying cause, though they are slightly different on the surface. In this issue, the bug is visible *only* if multiple `uv_kill` calls are executed in a row for a process group. Maybe that's what introduces need "irregularity" for the bug to resurface once in a while, I don't know, but if a single `uv_kill` is performed, there's no problem.

**Comment by santigimeno** [comment]
@neoxic can you check if https://github.com/libuv/libuv/pull/2423 fixes this?

**Comment by neoxic** [comment]
No, it does not (at least, for macOS).

**Comment by neoxic** [comment]
@santigimeno Have you checked against the above test case?

**Comment by santigimeno** [comment]
>  Have you checked against the above test case?

@neoxic yes, and it seems to fix the issue on a linux box.

**Comment by neoxic** [comment]
You mean without the fix you can steadily reproduce the bug whereas with the fix applied the bug goes away, right? I'll try to confirm the same for Linux although the bug is very sporadic for me on Linux.

Nonetheless, the bug is still present with the fix on macOS. I'll check for FreeBSD as well.

**Comment by santigimeno** [comment]
Tested on `FreeBSD` in the test case fails most of the time without the patch but doesn't with the patch.

**Comment by neoxic** [comment]
> Nonetheless, the bug is still present with the fix on macOS.

Tested properly on macOS - does NOT fail with the patch. Sorry, I was too tired to check properly before. In other words, confirmed for macOS.

**Comment by santigimeno** [comment]
Thanks for the confirmation @neoxic
