### ISSUE TITLE
timer: restarting a closing timer succeeds and leads to a limbo

### ISSUE THREAD

**Issue by neoxic** [libuv/libuv#2416]
* **Version**: 1.29.1, 1.30.1
* **Platform**: All

Calling `uv_timer_start()` on a closing timer unexpectedly succeeds and leads to a limbo (`uv_run()` does not exit).

```c
#include <uv.h>

static void close_cb(uv_handle_t *handle) {
    printf("close_cb(%p)\n", handle);
}

static void timer_cb(uv_timer_t *handle) {
    printf("timer_cb(%p)\n", handle);
    if (uv_is_closing((uv_handle_t *)handle)) {
        uv_print_all_handles(handle->loop, stderr);
        return;
    }
    uv_close((uv_handle_t *)handle, close_cb);
    uv_timer_start(handle, timer_cb, 1000, 0);
}

int main() {
    uv_loop_t *loop = uv_default_loop();
    uv_timer_t timer;

    uv_timer_init(loop, &timer);
    uv_timer_start(&timer, timer_cb, 1000, 0);

    uv_run(loop, UV_RUN_DEFAULT);

    /* Omit cleanup */
    return 0;
}
```

Output:
```
$ ./a.out
timer_cb(0xfffaa7f4)
close_cb(0xfffaa7f4)
timer_cb(0xfffaa7f4)
[--I] signal   0xf7ede2f4
[-AI] async    0xf7ede200
^C
```

**Comment by vtjnash** [comment]
Sounds like `uv_timer_start` needs a check for `uv_is_closing`? Would you be interested in submitting a PR? It looks like you essentially already have the test written there! 🙂

**Comment by neoxic** [comment]
Ok, done.

On the side note, it appears there's no clear error policy as to where an assertion (compile time error) is preferred rather than returning an error code (runtime error). Some handle starting routines make an assertion that a handle isn't closing, some return `EINVAL` whereas others don't bother checking at all. Some housekeeping is probably required.
