### ISSUE TITLE
1.31.0: compile time warnings

### ISSUE THREAD

**Issue by kloczek** [libuv/libuv#2418]
<pre>src/unix/linux-core.c: In function &apos;uv__io_poll&apos;:
src/unix/linux-core.c:326:5: warning: converting a packed &apos;struct epoll_event&apos; pointer (alignment 1) to a &apos;uv__io_t&apos; {aka &apos;struct uv__io_s&apos;} pointer (alignment 8) may result in an unaligned pointer value [-Waddress-of-packed-member]
  326 |     loop-&gt;watchers[loop-&gt;nwatchers] = (void*) events;
      |     ^~~~
In file included from src/unix/linux-core.c:38:
/usr/include/sys/epoll.h:83:8: note: defined here
   83 | struct epoll_event
      |        ^~~~~~~~~~~
In file included from ./include/uv.h:62,
                 from src/unix/linux-core.c:26:
./include/uv/unix.h:94:8: note: defined here
   94 | struct uv__io_s {
      |        ^~~~~~~~
</pre>

**Comment by saghul** [comment]
What compiler are you using?

**Comment by kloczek** [comment]
<pre>$ rpm -q gcc
gcc-9.1.1-2.fc31.1.x86_64
</pre>

**Comment by blueyed** [comment]
Also with gcc (GCC) 9.1.0.

But OK with:
```
clang version 8.0.1 (tags/RELEASE_801/final)
Target: x86_64-pc-linux-gnu
```

(on 4ed2a78 (v1.x))
