### ISSUE TITLE
osx: not ok 214 - spawn_empty_env

### ISSUE THREAD

**Issue by frol** [libuv/libuv#2421]
* **Version**: 1.31.0 (tests suite passed on previous versions, i.e. <=1.30.1)
* **Platform**: OS X only (Linux passes tests suite fine)

```
not ok 214 - spawn_empty_env
# exit code 6
# Output from process `spawn_empty_env`:
# exit_cb
# Assertion failed in test/test-spawn.c on line 72: exit_status == 1
```

Full log: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=61019&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b

Reference PR on Conda-Forge libuv package: https://github.com/conda-forge/libuv-feedstock/pull/31

**Comment by bnoordhuis** [comment]
Interestingly I can reproduce this locally today even though the test used to pass a few days ago... I'll take a look.

**Comment by bnoordhuis** [comment]
Seems I accidentally removed a letter from `DYLD_LIBRARY_PATH` between two incarnations of PR #2408... :face palm:

PR on the way.
