### ISSUE TITLE
uv_poll not detecting EOF on file descriptor?

### ISSUE THREAD

**Issue by timwoj** [libuv/libuv#2428]
* **Version**: 1.30.1
* **Platform**: `Darwin coregeek 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`

I'm attempting to use libuv and libpcap in conjuction to read a trace file and process the packets individually. I ran into a problem where `uv_poll` isn't detecting an EOF on the file descriptor that I get from libpcap, so it never knows that it's out of data to process and the loop hangs forever. I wrote up an example using both libuv's `uv_poll` as well as one that uses a bare call to `poll` and the bare `poll` version works as I'd expect it to. Is this something with `uv_poll` or am I just holding it wrong?

I attached the samples below. I've also tried passing both `UV_DISCONNECT` and `UV_PRIORITIZED` to `uv_poll_start` but that doesn't make any difference.

`uv_poll` version: [uv-pcap.cc.txt](https://github.com/libuv/libuv/files/3510865/uv-pcap.cc.txt)
`poll()` version: [poll-pcap.cc.txt](https://github.com/libuv/libuv/files/3510862/poll-pcap.cc.txt)

You'll need libpcap installed and a sample trace file (https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=http.cap is a good small one)

**Comment by timwoj** [comment]
Note that I also wrote the same two samples above just using a plain file descriptor opened via `open()` and read via `read()` and I got the same results as with pcap.

**Comment by vtjnash** [comment]
Is ‘fd’ a real file in this case? That’s not usually supported. I maintain a patch that might work for your case, so I’d be interested to know if it does: https://github.com/JuliaLang/libuv/commit/cd28c97f0962230c00c2a07d5a20acc932986381

**Comment by saghul** [comment]
Epoll doesn’t work wit files IIRC, so that is unsupported de facto AFAICT.

**Comment by timwoj** [comment]
> Is ‘fd’ a real file in this case? That’s not usually supported.

It appears so: https://github.com/the-tcpdump-group/libpcap/blob/master/pcap.c#L3285-L3302

I'll give your patch a spin. What would actually be really useful is a way to use the FS events system, but pass it an existing file handle instead of a path.

> Epoll doesn’t work wit files IIRC, so that is unsupported de facto AFAICT.

I've been testing on macOS which is kqueue, but we have to run on Linux as well so that would definitely be an issue.

**Comment by saghul** [comment]
> I'll give your patch a spin. What would actually be really useful is a way to use the FS events system, but pass it an existing file handle instead of a path.

That sounds reasonable to me. Maybe an alternative to `uv_fs_event_start` which takes an `uv_os_fd_t` instead.

**Comment by bnoordhuis** [comment]
I don't think that could work. Not all backends are fd-based. The inotify backend isn't.

It might become possible through io_uring once #2322 lands but only with (very) recent kernels.

**Comment by saghul** [comment]
Damn, too good to be true I guess. On the flip side, good to know io_uring would help!

**Comment by timwoj** [comment]
Closing this out since there doesn't seem like a good solution from the libuv side. I ended up using an idle handle.
