### ISSUE TITLE
Stale bot

### ISSUE THREAD

**Issue by genio** [libuv/libuv#2429]
Whoever added stale bot: both my email inbox and I dislike you a great deal.

Both a good and absolutely TERRIBLE idea!

**Comment by saghul** [comment]
I’ll take the credit 😎

**Comment by bnoordhuis** [comment]
If you're following nodejs/node as well - we'll probably enable stalebot there too in the near future and it's going to be at least 10x as bad as this. Stalepocalypse!

I don't like it either but it's either this or closing everything manually.
