### ISSUE TITLE
linux: open(O_CLOEXEC) logic broken with old kernels

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2450]
https://github.com/libuv/libuv/blob/43c74a6ee92a8e646201eef1fd056799cdccbfde/src/unix/fs.c#L261-L271

Problem: Old kernels don't report EINVAL when O_CLOEXEC is passed, they just ignore the flag. This might be true for other Unices too.

1. Solution: Check afterwards with `fcntl(F_GETFD)` whether the `FD_CLOEXEC` flag is set and remember the result.

2. Solution: Rip out the broken code. Such old kernels aren't supported anyway.

There may be more places where we use O_CLOEXEC that are affected.

Tangential: The code looks broken in general. It should grab the cloexec_lock until it's been established that O_CLOEXEC is actually supported.

**Comment by saghul** [comment]
How old are we talking about here?

**Comment by bnoordhuis** [comment]
Pre-2.6.27.

**Comment by saghul** [comment]
Older than what we list in SUPPORTED_PLATFORMS.md, so option 2 IMHO.
