### ISSUE TITLE
aix: CI only builds on 6.1 using GCC

### ISSUE THREAD

**Issue by apaprocki** [libuv/libuv#2456]
Wasn’t sure where to have this discussion, so starting here. I noticed when looking at the CI for a recent job that it was testing on AIX 6.1 using GCC, presumably on a host/LPAR provided by the OSU OSL. This OS/compiler combo is just one possible configuration and 6.1 is already very old at this point. 7.1/7.2 are not being tested and the vendor XL C/C++ compiler aren’t being tested.

- What configuration went into setting up the existing CI host?
- Is there any possibility of getting a 7.x host/LPAR executor from the same lab?
- Is there any possibility of getting a modern XL version installed on the current and any future hosts?
- Can we help configure the extra CI runs so that either additional OS versions and/or vendor compiler builds are performed?

@bnoordhuis @libuv/aix

**Comment by richardlau** [comment]
> 
> 
> Wasn’t sure where to have this discussion, so starting here. I noticed when looking at the CI for a recent job that it was testing on AIX 6.1 using GCC, presumably on a host/LPAR provided by the OSU OSL. This OS/compiler combo is just one possible configuration and 6.1 is already very old at this point. 7.1/7.2 are not being tested and the vendor XL C/C++ compiler aren’t being tested.

The CI is part of the Node.js CI infrastructure, https://github.com/nodejs/build/, so that's probably the best place for requirements. As far as I know we've never tested on XL C/C++ because we've always used gcc/g++ to build Node.js on AIX.

https://github.com/nodejs/build/tree/master/setup/aix61 contains the steps used to set up the AIX 6.1 LPARs. This was separate from the ansible scripts used to set up the other hosts (https://github.com/nodejs/build/tree/master/ansible) -- https://github.com/nodejs/build/commit/85c9a8635cbf35569f7e6a222608313ef8527f1c added support for AIX 7.1 to the main ansible scripts but as yet they've not been deployed/tested. I've been attempting internally at IBM to verify the scripts work but it's slow going as I'm new to setting up (as opposed to just using) AIX and new to ansible.

**Comment by mhdawson** [comment]
We are working to get ansible setup so that we can add a 7.2 host. I'd wished we had this in place earlier but other priorities have been getting in way.

To answer some of the questions"

>What configuration went into setting up the existing CI host?
* The instructions for how to configure are here: https://github.com/nodejs/build/blob/master/setup/aix61/manualBootstrap.md.  After than manual setup (which is quite a bit of work) then the existin ansible script will be run.  In contrast most of the consiguration will be in ansible for 7.X (its integrated into the scripts in: https://github.com/nodejs/build/tree/master/ansible)

>Is there any possibility of getting a 7.x host/LPAR executor from the same lab?
* Working on it, just taking longer to get it done. FYI @sam-github who would have the latest status.

>Is there any possibility of getting a modern XL version installed on the current and any future hosts?
* We investigated an XL port at one point for Node.js itself, but it was not straightforward and decided it was better to stick to gcc.  That might change as I understand the newer XL versions will be clang based, just not sure those are ready yet.

>Can we help configure the extra CI runs so that either additional OS versions and/or vendor compiler builds are performed?
  * which "vendor compiler builds" are you referring to?  XL or something else?  Can you add some 
    more context around your need/interest in this. I'd like to understand the context.  Guessing 
    maybe you are using AIX at your employer but wondering if it is for Node.js or something else 
    that you are interested in additional support for libuv.

**Comment by apaprocki** [comment]
> We investigated an XL port at one point for Node.js itself, but it was not straightforward and decided it was better to stick to gcc. 

> Guessing
maybe you are using AIX at your employer 

Correct, but if libuv is also riding atop the Node AIX CI infra... the library does “support” XL in the sense that I (and others?) ensure it works because we build it with XL on AIX, use, and depend on it in production not in any way related to Node. libuv has the benefit of not really requiring any changes on top of existing AIX/GCC support for Node. I just want XL builds in CI so that future commits don’t regress its currently clean state.

> I understand the newer XL versions will be clang based, just not sure those are ready yet.

V16.1 contains xlclang and is GA, so I’m sure they’d appreciate the feedback if it works or you find bugs :)

> which "vendor compiler builds"

Concretely, I’m asking if IBM could contribute working installs of XL C/C++ V12.1, 14.x, 16.x to the Node CI images so that maybe I and/or others could code up libuv CI jobs to use them alongside existing GCC builds.

**Comment by mhdawson** [comment]
My first priority at this point is getting some AIX 7.x machines into the CI. After we complete we'll look at the feasibility of getting XL on to the machines for libuv testing.

I'll also reach out to you directly to discuss as well.

**Comment by sam-github** [comment]
@apaprocki I have XL installed on AIX 7.2, but I wasn't able to get a sucessful build. I've these versions: /opt/IBM/xlC/13.1.3  /opt/IBM/xlC/16.1.0  /opt/IBM/xlc/13.1.3  /opt/IBM/xlc/16.1.0

How do you `./configure; make test` with XL? I'm willing to add some CI jobs if I have sucessful builds.

**Comment by sam-github** [comment]
f9c35197 helped a bit, but the CFLAGS is still pretty GNU: `-g -pedantic -g -std=gnu89`

xlc warns (I think) about "-std=gnu89":

> /opt/IBM/xlC/13.1.3/bin/.orig/xlc: 1501-210 (W) command option t contains an incorrect subargument

and for `ld` "-std=gnu89" is invalid, and "-pe dantic" is misunderstood:

> ld: 0711-327 WARNING: Entry point not found: dantic

```
$ (git clean -x -d -f; PATH=/opt/freeware/bin:$PATH sh autogen.sh; PATH=/opt/IBM/xlC/16.1.0/bin:$PATH CC=xlc ./configure --disable-dependency-tracking && gmake V=1 -j8 CFLAGS="-g" LIBS="-lpthread -lperfstat" check)
....
PASS: test/run-tests                                                   
=============                                         
1 test passed                                                                                                                                                                 =============                                                              
gmake[1]: Leaving directory '/home/iojs/libuv'
```

I'll see if I can teach automake to test better, its misguessing some stuff:
```
configure:4092: checking if xlc supports -pedantic flag
configure:4108: xlc -c -g -pedantic  conftest.c >&5
configure:4108: $? = 0
configure:4125: result: yes

configure:4293: checking if xlc supports -std=gnu89 flag
configure:4308: xlc -c -g -pedantic -g -std=gnu89  conftest.c >&5
/opt/IBM/xlC/16.1.0/bin/.orig/xlc: 1501-210 (W) command option t contains an incorrect subargument
configure:4308: $? = 0
configure:4325: result: yes

configure:4137: checking for xlc way to treat warnings as errors
configure:4152: xlc -c -g -pedantic -Werror  conftest.c >&5
/opt/IBM/xlC/16.1.0/bin/.orig/xlc: 1501-210 (S) command option Werror contains an incorrect subargument
configure:4152: $? = 40
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libuv"
| #define PACKAGE_TARNAME "libuv"
| #define PACKAGE_VERSION "1.32.0"
| #define PACKAGE_STRING "libuv 1.32.0"
| #define PACKAGE_BUGREPORT "https://github.com/libuv/libuv/issues"
| #define PACKAGE_URL ""
| #define PACKAGE "libuv"
| #define VERSION "1.32.0"
| /* end confdefs.h.  */
| int a;
configure:4176: xlc -c -g -pedantic -errwarn=%all  conftest.c >&5
configure:4176: $? = 0
configure:4195: result: -errwarn=%all
configure:4200: checking if xlc supports -fvisibility=hidden
```

... the broken link then causes many things to be misunderstood.

I'll see if I can convince automake to do the right thing. @apaprocki I'd still like to know how you got a built with xlc.

**Comment by sam-github** [comment]
@bnoordhuis any ideas?

I think what is happening is that autotools thinks that -c and -o work at same time, and they do, kindof, except that `xlc -o out out.c` warns on a bunch of flags that are errors for `xlc -o out out.o`, and that the linking failures made LDLIB detection fail.

gxlc advertises itself as the tool to use for this situation, and it does suceed much better, until:
```
$ (PATH=/opt/IBM/xlC/16.1.0/bin:$PATH CC=gxlc gmake V=1 -j1 check)  
/bin/sh ./libtool  --tag=CC   --mode=compile gxlc -DPACKAGE_NAME=\"libuv\" -DPACKAGE_TARNAME=\"libuv\" -DPACKAGE_VERSION=\"1.32.0\" -DPACKAGE_STRING=\"libuv\ 1.32.0\" -DPACKAGE_BUGREPORT=\"https://github.com/libuv/libuv/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libuv\" -DVERSION=\"1.32.0\" -DSUPPORT_FLAG_VISIBILITY=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBDL=1 -DHAVE_LIBNSL=1 -DHAVE_LIBPERFSTAT=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBRT=1 -D_LARGE_FILES=1 -DHAVE_SYS_AHAFS_EVPRODS_H=1 -I.  -I./include -I./src  -I./src/unix  -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wstrict-prototypes  -D_ALL_SOURCE -D_XOPEN_SOURCE=500 -D_LINUX_SOURCE_COMPAT -D_THREAD_SAFE -DHAVE_SYS_AHAFS_EVPRODS_H         -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wstrict-prototypes -c -o src/libuv_la-idna.lo `test -f 'src/idna.c' || echo './'`src/idna.c
libtool: compile:  gxlc -DPACKAGE_NAME=\"libuv\" -DPACKAGE_TARNAME=\"libuv\" -DPACKAGE_VERSION=\"1.32.0\" "-DPACKAGE_STRING=\"libuv 1.32.0\"" -DPACKAGE_BUGREPORT=\"https://github.com/libuv/libuv/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libuv\" -DVERSION=\"1.32.0\" -DSUPPORT_FLAG_VISIBILITY=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBDL=1 -DHAVE_LIBNSL=1 -DHAVE_LIBPERFSTAT=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBRT=1 -D_LARGE_FILES=1 -DHAVE_SYS_AHAFS_EVPRODS_H=1 -I. -I./include -I./src -I./src/unix -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wstrict-prototypes -D_ALL_SOURCE -D_XOPEN_SOURCE=500 -D_LINUX_SOURCE_COMPAT -D_THREAD_SAFE -DHAVE_SYS_AHAFS_EVPRODS_H -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wstrict-prototypes -c src/idna.c  -fPIC -DPIC -o src/.libs/libuv_la-idna.o
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -pedantic is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wall is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wextra is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wno-long-long is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wstrict-prototypes is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -pedantic is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wall is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wextra is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wno-long-long is not recognized.  Option will be ignored.
/opt/IBM/xlC/16.1.0/bin/.orig/gxlc: 1501-257 Option -Wstrict-prototypes is not recognized.  Option will be ignored.
    1500-016: (W) WARNING: Compiler problem occurred while compiling uv__utf8_decode1: Error writing src/.libs/libuv_la-idna.o : A system call received a parameter that is not valid..
    1500-034: (S) Cannot create object file.
/opt/IBM/xlC/16.1.0/bin/.orig/xlc -D__GNUC__=3 -D__GNUC_MINOR__=3 -D__GNUC_PATCHLEVEL__=4 -D__VERSION__="3.3.4" -Dinline=__inline__ -D__inline=__inline__ -qnokeyword=__inline -qkeyword=typeof -qbitfields=signed -F/opt/IBM/xlc/16.1.0/etc/xlc.cfg.72 -DPACKAGE_NAME="libuv" -DPACKAGE_TARNAME="libuv" -DPACKAGE_VERSION="1.32.0" -DPACKAGE_STRING="libuv 1.32.0" -DPACKAGE_BUGREPORT="https://github.com/libuv/libuv/issues" -DPACKAGE_URL="" -DPACKAGE="libuv" -DVERSION="1.32.0" -DSUPPORT_FLAG_VISIBILITY=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_LIBDL=1 -DHAVE_LIBNSL=1 -DHAVE_LIBPERFSTAT=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBRT=1 -D_LARGE_FILES=1 -DHAVE_SYS_AHAFS_EVPRODS_H=1 -I. -I./include -I./src -I./src/unix -g -qdbgfmt=dwarf4 -O2 -g -qdbgfmt=dwarf4 -qlanglvl=extc89 -qinfo=nopar -D_ALL_SOURCE -D_XOPEN_SOURCE=500 -D_LINUX_SOURCE_COMPAT -D_THREAD_SAFE -DHAVE_SYS_AHAFS_EVPRODS_H -g -qdbgfmt=dwarf4 -O2 -g -qdbgfmt=dwarf4 -qlanglvl=extc89 -qinfo=nopar -c src/idna.c -qpic=large -DPIC -o src/.libs/libuv_la-idna.o
gmake: *** [Makefile:2358: src/libuv_la-idna.lo] Error 1
```

This creates a zero-size .o file, and its why I originally tried to use CC=xlc, but that runs into the other problems where autoconf doesn't work well with it.

**Comment by apaprocki** [comment]
@sam-github I maintain this library in our org. I have patches to `Makefile.am` and `configure.ac` to build cleanly with XL. You do not want to invoke `gxlc` because autotools already knows about XL and that will just confuse it. You want to just invoke `xlc` (or `xlc_r` if you weren't already passing `-D_THREAD_SAFE`). I can open up a separate PR for the patches to constrain the GCC-only flags to GCC.

**Comment by sam-github** [comment]
@apaprocki I'd apreciate you PRing the XL support, thanks.

**Comment by sam-github** [comment]
Folks, `CC=xlc ./configure --disable-dependency-tracking && gmake V=1 -j8 CFLAGS="-g" LIBS="-lpthread -lperfstat" check` passes, I have credentials to modify the CI to add xlc builds to https://ci.nodejs.org/job/libuv-test-commit-aix/.

Do I also have the OK from the project? Are there any objections?

**Comment by saghul** [comment]
I don't think there are any objections. 👍  FWIW!

**Comment by sam-github** [comment]
https://ci.nodejs.org/job/libuv-test-commit-aix/1665/  <--- green AIX 7.2 with XL compiler builds.

This can be closed.

wrt https://github.com/libuv/libuv/issues/2456#issuecomment-542511455  @apaprocki might PR autogen improvements. If that happens, I might be able to simplify the build job definition a little.
