### ISSUE TITLE
struct ip_mreq_source and group_source_req are not available on NetBSD

### ISSUE THREAD

**Issue by moubctez** [libuv/libuv#2463]
* **Version**: 1.32.0
* **Platform**: NetBSD
`struct ip_mreq_source` and `struct group_source_req` are not available on NetBSD, so compilation fails (**src/unix/udp.c**: _uv__udp_set_source_membership4()_ and _uv__udp_set_source_membership6()_ introduced in libuv 1.32.0).
Please, fix.

**Comment by bnoordhuis** [comment]
Pull request welcome. NetBSD is a tier 3 platform, i.e., self-support.

**Comment by bnoordhuis** [comment]
#2458 attempts to fix this for OpenBSD, perhaps you can piggy-back off that. (cc @devnexen)

**Comment by devnexen** [comment]
seems they have exact same issue for build what is mentioned and also the statvfs data part. Will update the PR.
