### ISSUE TITLE
MCAST_JOIN_SOURCE_GROUP is not available in MinGW

### ISSUE THREAD

**Issue by rezamahdi** [libuv/libuv#2464]
When compiling libuv 1.32.0 whit MinGW 8.1.0 the following error is encountered in win/udp.c:

```
libuv-v1.32.0/src/win/udp.c:793:15: error: 'MCAST_JOIN_SOURCE_GROUP' undeclared (first use in this function); did you mean 'ERROR_NO_SUCH_GROUP'?
     optname = MCAST_JOIN_SOURCE_GROUP;
               ^~~~~~~~~~~~~~~~~~~~~~~
               ERROR_NO_SUCH_GROUP
```

The MSDN syas that it is located in ```ws2ipdef.h```, So it may not be a problem but when adding ```#include <ws2ipdef.h>``` the error remains... So the MinGW headers may havn't it

**Comment by cjihrig** [comment]
This should be fixed by https://github.com/libuv/libuv/pull/2461.

**Comment by rezamahdi** [comment]
According to [this](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.14393.0/shared/ws2ipdef.h), value of ```MCAST_JOIN_SOURCE_GROUP``` is ```45```, And ```MCAST_LEAVE_SOURCE_GROUP``` is ```46```

```c
#define MCAST_JOIN_GROUP            41	// Join all sources for a group.
#define MCAST_LEAVE_GROUP           42  // Drop all sources for a group.
#define MCAST_BLOCK_SOURCE          43	// Block IP group/source.
#define MCAST_UNBLOCK_SOURCE        44	// Unblock IP group/source.
#define MCAST_JOIN_SOURCE_GROUP     45	// Join IP group/source.
#define MCAST_LEAVE_SOURCE_GROUP    46	// Leave IP group/source.
```
