### ISSUE TITLE
not ok - udp_ipv6_only

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#2467]
```
not ok 341 - udp_ipv6_only
# exit code 134
# Output from process `udp_ipv6_only`:
# Assertion failed in test/test-udp-ipv6.c on line 92: 0 && "this function should not have been called"
```
https://ci.nodejs.org/job/libuv-test-commit-linux/1617/nodes=centos6-64/console

**Comment by vtjnash** [comment]
I'm thinking we should keep this open so that google can better index it in case anyone is able to later investigate it. Unless someone thinks it was a buildbot configuration issue and is now fixed?

**Comment by bnoordhuis** [comment]
> Unless someone thinks it was a buildbot configuration issue and is now fixed?

There was some tweaking of firewall rules not too long ago (I think that was you, @sam-github?) so I expect this is fixed now.

**Comment by vtjnash** [comment]
Hm, still seems to be bad https://ci.nodejs.org/job/libuv-test-commit-linux/1745/nodes=centos6-64/console
