### ISSUE TITLE
Test 372 KO

### ISSUE THREAD

**Issue by syndrael** [libuv/libuv#2475]
Hello,
* **Version**: the lastest 1.32.0
* **Platform** : Linux umax2 2.6.32-042stab133.2 #1 SMP Mon Aug 27 21:07:08 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

as root, when i start make checks, there's an error on test 372.

> 

>not ok 344 - udp_multicast_join
> timeout
> Output from process `udp_multicast_join`: (no output)
>ok 345 - udp_multicast_join6 # SKIP No external IPv6 interface available
>ok 346 - udp_multicast_ttl
>ok 347 - udp_no_autobind
>ok 348 - udp_open
>ok 349 - udp_open_bound
>ok 350 - udp_open_connect
>ok 351 - udp_open_twice
>ok 352 - udp_options
>ok 353 - udp_options6
>ok 354 - udp_ref
>ok 355 - udp_ref2
>ok 356 - udp_ref3
>ok 357 - udp_send_and_recv
>ok 358 - udp_send_hang_loop
>ok 359 - udp_send_immediate
>ok 360 - udp_send_unix
>ok 361 - udp_send_unreachable
>ok 362 - udp_try_send
>ok 363 - uname
>ok 364 - unref_in_prepare_cb
>ok 365 - utf8_decode1
>ok 366 - walk_handles
>ok 367 - watcher_cross_stop
>ok 368 - we_get_signal
>ok 369 - we_get_signal_one_shot
>ok 370 - we_get_signals
>ok 371 - we_get_signals_mixed
>FAIL: test/run-tests
>1 of 1 test failed
>Please report to https://github.com/libuv/libuv/issues
>Makefile:4968: recipe for target 'check-TESTS' failed
>make[1]: *** [check-TESTS] Error 1
>make[1]: Leaving directory '/home/syndrael/libuv'
>Makefile:5224: recipe for target 'check-am' failed
>make: *** [check-am] Error 2
>
>What can i give you more ?
>Thanks for your answer.
>Kind regards

**Comment by saghul** [comment]
We discourage users from running tests as root, as unexpected errors tend to manifest. Can you please try to repro as a user? (I don't think it's relevant in this specific case, but hey).
