### ISSUE TITLE
ci,macos: flaky process_title_threadsafe test

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2479]
It times out frequently again after 00c6b1649d13fdd94bedbfe7ad26c9269c80b32c was reverted in 97e86dde84198208984b4ed107adb76b8632409f:
```
not ok 195 - process_title_threadsafe
# timeout
# Output from process `process_title_threadsafe`: (no output)
```
<hr>

Observation by @cjihrig in https://github.com/libuv/libuv/pull/2405#issuecomment-517972086:

> moving the `pSetApplicationIsDaemon(1) != noErr` check out of `uv__set_process_title()`, and into `uv__set_process_title_platform_init()` seems to fix https://github.com/nodejs/node/issues/28945 for me.

<sup>(edit: removed comment that was me misinterpreting the statement above :-))</sup>

**Comment by cjihrig** [comment]
Duplicate of https://github.com/libuv/libuv/issues/2453?

**Comment by bnoordhuis** [comment]
Indeed ^^

Closed the other one.

**Comment by vtjnash** [comment]
Still happening (e.g. https://ci.nodejs.org/job/libuv-test-commit-osx/1703/nodes=osx1011/console). IIUC, that's because #2480 needed to be reverted in https://github.com/libuv/libuv/pull/2568.

**Comment by bnoordhuis** [comment]
#2593 should have taken care of this so I'll go ahead and close this out. Please reopen if the test still fails.

Note: there are some recent failures but that was with a PR that hadn't been updated to include the commit from #2593.

**Comment by bnoordhuis** [comment]
Still happens... https://ci.nodejs.org/job/libuv-test-commit-osx/1735/nodes=osx1011/console

**Comment by vtjnash** [comment]
I think I've identified this as a bug in the test itself (https://github.com/libuv/libuv/pull/2853#issuecomment-665259082), if someone wants to take a crack at fixing that (and to re-re-land the optimization)

**Comment by bnoordhuis** [comment]
#2946
