### ISSUE TITLE
can't cancel a uv_getaddrinfo request

### ISSUE THREAD

**Issue by edgeofmagic** [libuv/libuv#2481]
uv_cancel returns EBUSY when called with a uv_getaddrinfo_t request that is in progress. The documentation for uv_cancel says the uv_getaddrinfo callback should be invoked with status == UV_ECANCELED.

I'm attaching a short C++ program that illustrates the problem. It creates a timer that calls uv_cancel on the getaddrinfo request when it fires, then starts the timer and the request. The program prints elapsed times when the timer callback and the getaddrinfo callback are invoked. You might have to play with the hostname and the timer delay in order to get the timer to fire before the request completes, depending on your configuration and whether the host address is cached locally.

Typical output for me is:
---------------------------------
timer_callback at 6 msecs
error in cancel: EBUSY
resolve callback at 19 msecs
address: 172.217.0.46
---------------------------------

-->
* **Version**: 

* **Platform**: 

[main.cpp.zip](https://github.com/libuv/libuv/files/3618176/main.cpp.zip)

**Comment by cjihrig** [comment]
Old, related thread: https://github.com/libuv/libuv/issues/203

**Comment by edgeofmagic** [comment]
Sorry for the formatting goofs. My version and platform are:

libuv version: 2019.09.10, Version 1.32.0 (Stable), 697bea87b3a0b0e9b4e5ff86b39d1dedb70ee46d

platform: macOS 10.14.6 -- Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by saghul** [comment]
This is known. Requests cannot be cancelled once they have started. You can cancel it before it starts, but once it's in motion there is no cancel possible.

**Comment by saghul** [comment]
> Old, related thread: #203

Not quite the same IMHO. In this case the user wants to clancel the request, vs letting the loop exit regardless of the request being in-flight.

**Comment by edgeofmagic** [comment]
Ok, I read the other issue, and I get it--can't really do anything if the thread has started. I guess I was taking a narrow reading of the documentation: do X and Y will happen. Maybe this should just be clarified in the documentation.

**Comment by saghul** [comment]
A PR adding some more info to the documentation would be most welcome, if you're up for it.

**Comment by edgeofmagic** [comment]
It will be my first such attempt, but I'll take a shot at it.
