### ISSUE TITLE
uv_fs_write vs UV_FS_O_APPEND

### ISSUE THREAD

**Issue by neoxic** [libuv/libuv#2482]
Hello!

If `uv_fs_write` is equivalent to `pwritev(2)` according to the manual, it seems to be incompatible with `UV_FS_O_APPEND` on POSIX-compliant systems.

https://stackoverflow.com/questions/22268115/using-pwrite-to-append-to-a-file

Please note that on Linux `pwritev(2)` ignores offset when a file is opened with `O_APPEND` only due to a bug in the kernel - https://bugzilla.kernel.org/show_bug.cgi?id=43178

libuv does not seem to deal with this issue internally, for example, using `writev(2)` instead of `pwritev(2)` when a `uv_file` was opened with `UV_FS_O_APPEND`.

As a side note, why not just use `writev(2)` and have an `lseek(2)` equivalent like `uv_fs_lseek` to avoid the above issue along with the hassle to track file position when writing? It's always possible to have a separate `uv_fs_pwrite` for seek&write requests if preferred.

**Comment by vtjnash** [comment]
lseek has a separate issue already: https://github.com/libuv/libuv/issues/2378

> using writev(2) instead of pwritev

Wouldn't that exhibit exactly the same behavior on Linux, and only diverge if that issue (from 2012) got closed?

Given how we set the flags in CreateFile, it looks like libuv-on-Windows may follow Linux here:

> If the caller sets only the FILE_APPEND_DATA and SYNCHRONIZE flags, it can write only to the end of the file, and any offset information about write operations to the file is ignored. The file will automatically be extended as necessary for this type of operation.
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntcreatefile

Anyone know what happens on macOS (and other platforms)?

**Comment by neoxic** [comment]
Yes, I can see now that `lseek(2)` is a bad idea given the thread pooled nature of libuv's file operations. Forget the side note then.

**Comment by neoxic** [comment]
Nevertheless, the use of `writev(2)` instead of `pwritev(2)` seems inevitable to reliably support `O_APPEND`.

**Comment by neoxic** [comment]
```c
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>

int main() {
	int fd = open("a.txt", O_CREAT | O_TRUNC | O_WRONLY | O_APPEND, 0755);
	if (fd == -1) {
		perror("open()");
		return 1;
	}
	pwrite(fd, "aaa\n", 4, 0);
	pwrite(fd, "bbb\n", 4, 0);
	close(fd);
	return 0;
}
```

On Linux and FreeBSD (!!!):
```
$ cat a.txt
aaa
bbb
```

On macOS:
```
$ cat a.txt
bbb
```

**Comment by bnoordhuis** [comment]
xnu's vfs layer passes the O_APPEND flag to the fs driver so I suppose it's possible that different file systems exhibit different behavior.

The nfs client driver, for example, simply forwards the flag to the server (when it speaks nfsv4.)
