### ISSUE TITLE
uv_fs_copyfile(): using FICLONE results in EINVAL

### ISSUE THREAD

**Issue by st-bender** [libuv/libuv#2483]
Hi,
I observed that the `fs_copyfile` test failed onthe system I used.
It seems that on some platforms/setups the `ioctl()` call in
https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L1055-L1078 failes with `EINVAL` and gets elevated such that `uv_fs_copyfile()` fails.
I believe this was introduced with  libuv/libuv#1491 and libuv/libuv#1863.
The following patch fixed it for me:

```diff
diff --git a/src/unix/fs.c b/src/unix/fs.c
index 0f68a40..ec69503 100644
--- a/src/unix/fs.c
+++ b/src/unix/fs.c
@@ -1059,7 +1059,8 @@ static ssize_t uv__fs_copyfile(uv_fs_t* req) {
       /* If an error occurred that the sendfile fallback also won't handle, or
          this is a force clone then exit. Otherwise, fall through to try using
          sendfile(). */
-      if (errno != ENOTTY && errno != EOPNOTSUPP && errno != EXDEV) {
+      if (errno != ENOTTY && errno != EOPNOTSUPP && errno != EXDEV &&
+          errno != EINVAL) {
         err = UV__ERR(errno);
         goto out;
       } else if (req->flags & UV_FS_COPYFILE_FICLONE_FORCE) {
```

I ended up here because of jupyterlab/jupyterlab#6969 and yarnpkg/yarn#7440, yarnpkg/yarn#7152 seems to be related as well. They all have trouble when using the `FICLONE`, so you may consider to add `EBADF` and `EFAULT` as well.

Please note that on linux, `FICLONE` gets defined in the header of the same file
https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L62-L67 :
```c
#if defined(__APPLE__)
# include <sys/sysctl.h>
#elif defined(__linux__) && !defined(FICLONE)
# include <sys/ioctl.h>
# define FICLONE _IOW(0x94, 9, int)
#endif
```
I am not sure if that is a good idea, what happens if that `_IOW` setting has a completely different meaning on some systems? Is it documented somewhere and wouldn't this be better handled by `configure`?

* **Version**: 1.32.1
* **Platform**: linux

Cheers.

**Comment by saghul** [comment]
>  Is it documented somewhere and wouldn't this be better handled by `configure`?

I can't comment on the rest, but I can on this: we use runtime detection rather than build time. This allows for libuv to work best on recent kernels, while being built in al older one, for example. In addition, we support 3 build systems, autotools being just 1 of them.

Thanks for the report!

**Comment by st-bender** [comment]
> > Is it documented somewhere and wouldn't this be better handled by `configure`?
> 
> I can't comment on the rest, but I can on this: we use runtime detection rather than build time. This allows for libuv to work best on recent kernels, while being built in al older one, for example. In addition, we support 3 build systems, autotools being just 1 of them.

Thanks.
Good point, although I think the build system issue could be solved for all three of them. But I agree that runtime detection is a different issue.

Btw. I found that the `IOW` setting was introduced as `BTRFS_IOC_CLONE` with btrfs, and now apparently also handles more general cases.
I am still wondering if there is a cleverer approach, maybe ignoring any error thrown by `ioctl()` and only failing if `FICLONE_FORCE` is set, leaving all the other cases to `sendfile()`?

Something along the lines:
```c
if ((ioctl(...) == 0)) {
    /* COW supported and succeeded */
    goto out;
}
if (req->flags & UV_FS_COPYFILE_FICLONE_FORCE) {
    /* some error occurred but it force clone was requested */
    err = UV_ENOSUPP;
    goto out;
}
/* else use sendfile */
```
But I don't know if that would have more/other unwanted side-effects.
Cheers.
