### ISSUE TITLE
Artificial time?

### ISSUE THREAD

**Issue by timwoj** [libuv/libuv#2484]
I’m working on the Zeek project (https://github.com/zeek/zeek) to rewrite our internal I/O loop and timers to use libuv. One of the features of our existing hand-written loop is that we can trigger it using an artificial time base, which allows us to move time forward based on the timestamps of packets in a packet capture. Timers can then fire based on that “pseudo-time” instead of wall-clock time. I looked through the libuv code little bit today and it appears that all of the time is based on whatever the host system’s time is.

Does something like what I’m trying to do already exist? Would adding a feature where a loop could have a callback to set the current time be of use to anyone else, before I start down the road to implementing this?

**Comment by saghul** [comment]
Can you give some more examples on this use case? I’ve personally never heard of it before and am curious!

I think what you’d want is some setter for uv_now? Or maybe a “time source” callback which defaults to uv_now.

**Comment by timwoj** [comment]
> Can you give some more examples on this use case? I’ve personally never heard of it before and am curious!

Zeek is a program for reading packet data and generating a large amount of data about what is happening on the network at any given time. We also have the ability to read packet files and process them as if they were live data. With live data, we can rely on the wall clock to keep track of what time it is in relation to events happening in the data, since packets arrive as they're generated including timers firing for various events. 

When reading packet data though, we can't just read them as quickly as we can, since we still want the events and timers to fire as if it was live data. In the existing code, there's the concept of psuedo-time, where the internal clock for Zeek gets updated based on the timestamps in the packets as they're received. This allows the clock to advance along with the data, and everything works as if the data was live.

> I think what you’d want is some setter for uv_now? Or maybe a “time source” callback which defaults to uv_now.

That's pretty much it, I think. I just need some way to set the time in libuv artificially instead of relying on the system's clock.

**Comment by saghul** [comment]
I see. I am not familiar with this usecase so it's hard for me to say if it makes sense for libuv to accomodate it or not. Thankfully, we do have @libuv/collaborators :-) Thoughts?

**Comment by timwoj** [comment]
Digging through the code a bit, I think this might work:

1. Add a callback/variable to `uv_loop_t`that returns a `unit64_t` representation of the current time in milliseconds. The documentation for the callback should be that it always returns monotonically increasing values.
2. In `uv_update_time`, check whether the loop has a callback for time. If it does, use the return value from that. If not, set the time as it's currently being set.

`uv_update_time` is called from `uv_loop_init`, so the callback just needs to be set prior to that.

**Comment by saghul** [comment]
> uv_update_time is called from uv_loop_init, so the callback just needs to be set prior to that.

Given that uv_loop_init is the first thing one would call in a freshly allocated chunk of memory, I’m not sure how that would work.

**Comment by timwoj** [comment]
I was able to implement it by adding a second `uv_init` method that takes a time callback method. Unfortunately in digging through all of this I also realized that libuv only does millisecond resolution. We need it to do at least microsecond since that's what Wireshark will store in a pcap file.
