### ISSUE TITLE
Use CreateDirectoryW   instead of  _wmkdir for uv_fs_mkdir

### ISSUE THREAD

**Issue by musm** [libuv/libuv#2499]
At least then `modes` can be passed.

**Comment by saghul** [comment]
This would indeed be a welcome addition! Generally speaking we try to get away from CRT functions.

**Comment by cjihrig** [comment]
It looks like @saghul suggested this before in https://github.com/libuv/libuv/pull/2375#discussion_r302484232, but the comment got missed prior to landing that PR.

**Comment by musm** [comment]
no
