### ISSUE TITLE
Feature request: sigqueue

### ISSUE THREAD

**Issue by JacksonTian** [libuv/libuv#25]
In linux, `sigqueue` can send signal with attached data.

**Comment by piscisaureus** [comment]
No opposition from me to sigqueue per se, but indeed this can never work on windows. 
I wonder what the benefit of adding it to libuv is though; if you want to use sigqueue() just call sigqueue() :)

**Comment by saghul** [comment]
What @piscisaureus said. Closing.

**Comment by JacksonTian** [comment]
Thanks.
