### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by swinghu** [libuv/libuv#250]
=============================================================
[%  10|+  26|-   0|T   0|S   0]: pipe_set_non_blocking
`pipe_set_non_blocking` failed: exit code 134
Output from process `pipe_set_non_blocking`:
Assertion failed in test/test-pipe-set-non-blocking.c on line 51: n == 0
=============================================================
[%  22|+  55|-   1|T   0|S   0]: tcp_connect_timeout
`tcp_connect_timeout` failed: exit code 134
Output from process `tcp_connect_timeout`:
Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
=============================================================
[% 100|+ 248|-   2|T   0|S   0]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] 错误 1
make[1]:正在离开目录 `/opt/libuv'

**Comment by saghul** [comment]
The first failure is being handled in #248, and the second one is probably a timing, host issue, since it doesn't fail in our CI.
