### ISSUE TITLE
1 task in 'LIBUV' failed exit status

### ISSUE THREAD

**Issue by Fauveboy** [libuv/libuv#2500]
In the PKGBUILD for the serialosc git files (a protocol to communicate with the monome hardware interface), after running #makepkg -si.
the result was: 1 task in 'LIBUV' failed exit status.
So I thought LIBUV was a library that is perhaps missing that the serialosc PKGBUILD needs.

I then got git clone https://aur.archlinux.org/libuv-git.git, ran the PKGBUILD for that but an error occurs in check(). 

I'm not fully confident about what im looking for here but heres the output to the command:
strace make check

that I ran on  /home/joel/libuv-git/src/libuv.

The output is here. LINK: http://ix.io/1WBX

at the end it says 1 of 1 tests failed, which I believe is an issue?

________
Next I have the output for makepkg on libuv-git :

http://ix.io/1WJU

...definitely ends with ERROR: A failure occurred in check().
    Aborting..

which again i believe is an issues.

If anyone can shed some light on this issue, or is happy to query me over this issue, please do....

**Comment by saghul** [comment]
Looks like your resolver might be returning invalid responses:

```
not ok 118 - getaddrinfo_fail
# exit code 134
# Output from process `getaddrinfo_fail`:
# Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
not ok 119 - getaddrinfo_fail_sync
# exit code 134
# Output from process `getaddrinfo_fail_sync`:
# Assertion failed in test/test-getaddrinfo.c on line 112: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy.", NULL, NULL)
```

`xyzzy.xyzzy.xyzzy.` is an invalid domain which we use to test a `getaddrinfo` failure. It doesn't fail on your system.

**Comment by Fauveboy** [comment]
getaddrinfo is failing. Meaning that it can't return an addinfo structure of some sort?...This is because xyzzy.xyzzy.xyzzy is an invalid domain. As its used to test getaddrinfo does this mean I need to remove it, or replace it with something else?...A valid domain perhaps?

When you say, at the end there, "It doesnt fail on your system" what are you referring to there?

**Comment by bnoordhuis** [comment]
The "doesn't fail" means the domain name is not supposed to resolve to anything but some networks have DNS servers that serve up addresses for non-existing domains (e.g., to serve up ads) and that's what making the test fail on your system.

**Comment by Fauveboy** [comment]
So where it says "not ok 118 - getaddrinfo_fail" and "not ok 119 - getaddrinfo_fail_sync" means that the domain name resolves to "something", when it shouldn't? This is because the DNS server I have is creating a domain name where one doesn't exist?

I think systemd is providing network name resolution to local apps on my system. Does this mean its possibly responsible for the DNS server's domain name? Perhaps its something to do with how systemd is configured that could prevent the DNS from creating a domain name? 

...That's my initial thoughts at this stage...What do you think to that?

**Comment by bnoordhuis** [comment]
It's possible that systemd-resolved is responsible but it could also be an upstream DNS server, e.g., your ISP's.

**Comment by Fauveboy** [comment]
If its an upstream DNS server: I could try running makepkg for the libuv-get PKGBUILD on a different internet providers?...Cafe hop one morning try different wifi's ? :D ...Or is it possible to prevent an upstream DNS server from "upstreaming" a domain name?

Also it sounds like its worth doing some research around systemd-resolved?

At this moment it seems to be the case that a domain name is produced somehow that should be produced? So finding a way to prevent this may help avoid the failing errors with getaddrinfo_fail and getaddrinfo_fail_sync.

Does that sound about right?

**Comment by saghul** [comment]
I'd say the easiest is to try to use a different resolver. 8.8.8.8 or 1.1.1.1 perhaps.

You are more than welcome to poke around systemd-resolved, but there is not much libuv can do it it runs on a broken resover. It's not libuv's job to "fix" it.

Also note that in the case of that specific test, it's not libuv the entity at fault, so you can ignore it safely.

This last bit makes me wonder if we should either remove it or skip it if it fails, since all I see are false positives...

**Comment by Fauveboy** [comment]
i get the error running makepkg on the PKGBUILD  after cloning the git file found here here: https://aur.archlinux.org/packages/serialosc-git/. Where can I set a differnt resolver ?
