### ISSUE TITLE
macos: report EINVAL as ECONNREFUSED?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2503]
macOS doesn't let TCP sockets self-connect and reports that as EINVAL. Perhaps true for other platforms too.
```c
uv_ip4_addr("127.0.0.1", 1234, &addr);
uv_tcp_bind(&conn, (const struct sockaddr*) &addr, 0);
uv_tcp_connect(&conn, &req, (const struct sockaddr*) &addr, cb);  // EINVAL
```
For OpenBSD, we map EINVAL to ECONNREFUSED. Maybe we should do the same on macOS?
https://github.com/libuv/libuv/blob/bee1bf5dd7de8da316821c32411425f7cf7ab49c/src/unix/tcp.c#L238-L247
Are there other legitimate reasons for encountering EINVAL? That is, do we need additional checks to find out whether this EINVAL is because of self-connecting or something else?

**Comment by santigimeno** [comment]
On their `man` page it states:

> [EINVAL] An invalid argument was detected (e.g., address_len is
                        not valid for the address family, the specified
                        address family is invalid).

with those 2 cases already handled on `uv_tcp_connect()` itself. So making this change would be probably fine, but who knows what other `EINVAL` uses might there be.
