### ISSUE TITLE
meta: forever v1.x

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2506]
> We are now trapped in v1.x for a while but IIRC someone proposed to change the major cadence once we hit v2.

At the risk of derailing... I kind of like the thought of v1.x forever. Stable APIs are nice! With some thought and care, I think it could be made to work in a way that isn't too onerous/restrictive.

_Originally posted by @bnoordhuis in https://github.com/libuv/libuv/pull/2498#issuecomment-539892497_

**Comment by bnoordhuis** [comment]
@saghul's comments from https://github.com/libuv/libuv/pull/2498#issuecomment-539896621:

>  we forgot to add reserved fields to uv_loop_t

I think that can be addressed by malloc-ing memory.

> Windows file handles vs fds

I admit I'm not entirely sure what this refers to. ^^

**Comment by cjihrig** [comment]
> Windows file handles vs fds

That might be referring to the change from `uv_file` in v1.x to `uv_os_fd_t` in master.

**Comment by saghul** [comment]
> I think that can be addressed by malloc-ing memory.

Sure, but it's more cumbersome, isn't it?



> I admit I'm not entirely sure what this refers to. ^^



> That might be referring to the change from `uv_file` in v1.x to `uv_os_fd_t` in master.

^ this.

I think having strong backwards compatibility guarantees is a Great Goal, but breaking the ABI every blue moon is not that bad in order to pay some tech debt, IMHO.

Also, if we stay like this, what do we do with curent master?

**Comment by addaleax** [comment]
Personally, I’d be a big fan of being API- and ABI-stable indefinitely. I’d still be okay with breaking changes if they don’t affect that.

**Comment by saghul** [comment]
Here are the current differences between master and v1: https://github.com/libuv/libuv/compare/v1.x...master?expand=1 (nothe that some of those have been backported already, but it's not a long list to go through). 

Disclaimer: I did many cleanups in master (as you can see above), so I have a bias.

> I can live with more cumbersome. I already carry the weight of the world on my shoulders, a little more won't hurt. Call me Atlas. ^^

🤣 



> I understand the `uv_file` / `uv_os_fd_t` thing better now. Do you feel that's an important change?

I think so yeah. Also note that if we choose to dump it we'd be forcing Julia to fork libuv forever, which is not nice.

> If yes, we can think about some kind of versioning for v1.x APIs.

What shape would that take? The entire fs API needs adjusting, I hope you don't mean to have a parallel `uv_fs2_xxx` universe.



> I remember a relatively recent discussion about `HANDLE` vs. `int` but try using GH's search with those keywords... Can we start accepting `HANDLE` where we accept `int` now?
> 
> It's pointer-sized IIRC but from an ABI perspective that isn't an issue for function arguments. Or are there 64 bits architectures (that Windows supports) with arguments-in-registers ABIs where setting the lower half of a register doesn't clear the upper half? Not ARM and x64.

Only the lower 32bits of a `HANDLE` are used, these are the references I keep: https://www.viva64.com/en/k/0005/ https://docs.microsoft.com/en-us/previous-versions/ms810720(v=msdn.10)?redirectedfrom=MSDN

I don't know if the new Windows on ARM universe changed this, but given Windoes's strong backwards compatibility history, I'd say it doesn't.

> Back-port what we deem is useful and shelf what isn't?

That's ok, but what do we do with the accumulated cruft?

I fear that if we go down this road libuv will become harder (or at least more daunting) to maintain, use and contribute to.

We already have "ex" or "2" variants of certain functions. Inevitably, we'll need a third or fourth, who knows. We can add documentation, sure, but why not remove what's broken? As an example, there is a ton of dead code in structures we needed for OS versions we no longer support, but if we commit to forever ABI stability, we cannot ever remove it.

I have changed my stance with regards to how I personally envision v2 and future versions. The current API is fine, there is no need to change everything (ie "pull based event loop", what we have is good enough and we can add many improvements) but it would be nice to be able to have a new major to "take out the garbage" every once in a while.

> Personally, I’d be a big fan of being API- and ABI-stable indefinitely. I’d still be okay with breaking changes if they don’t affect that.

We currently claim to adhere to semver, and so far I think libuv has done a pretty good job at it, modulo bugs. What you sugests breaks that, and arguably users expect semver from libuv.

**Comment by santigimeno** [comment]
> I think so yeah. Also note that if we choose to dump it we'd be forcing Julia to fork libuv forever, which is not nice.

> but what do we do with the accumulated cruft?
> I fear that if we go down this road libuv will become harder (or at least more daunting) to maintain, use and contribute to.

:+1: to these.

Ideally I would love going for a `v2.x` version that:
1. Solves the design flaws we carry from `v1.x`. My understanding is that this would make `v2.x` not too different from `v1.x` but would make it easier to maintain going forward. Maybe then make a _forever v2x_?
2. Don't _fail_ to downstream projects that had the expectation of a `v2` some time in the future.

The main problem to solve though, and a good reason not to do it would be that it will be **more** work for quite a long time and we're not that many active maintainers (I'm barely active myself as of late).

**Comment by saghul** [comment]
>     1. Maybe then make a _forever v2x_?

👍

**Comment by vtjnash** [comment]
I don't know that v2_forever is any better than v1_forever. That puts a lot of pressure on v2 to be perfect. But Inevitably there'll be reasons eventually to fix something. I hope it'll live long and prosper, but I don't wish it to live forever.

But so to move us towards having v2 releases, can I ask folks to review any outstanding API issues and make sure they have issues opened and tagged with `v2`? The next time I get a solid week to work on libuv, I'm hoping to go through and complete as much of the breaking ABI changes as will lay the groundwork for starting making actual v2 releases off master.

**Comment by saghul** [comment]
v1 has been pretty good at being “perfect” in the sense that we have able to evolve it a lot without breaking the ABI. There are, however a few rough spots still, and the whole uv_file change, so I think a v2 may be a good idea.
