### ISSUE TITLE
uv-common.c:75: uv_err_name: Assertion `0' failed.

### ISSUE THREAD

**Issue by marty-buly** [libuv/libuv#251]
When running 'npm install -g bower' or 'npm install -g q', it fails with following message:
../deps/uv/src/uv-common.c:75: uv_err_name: Assertion `0' failed.

This behaviour is not constant, as after some time I was able to install bower with the same command, but then q failed internally, when installing bower. Now I tried to install q separately and I see the same error.

Next, when running 'bower install'  it shows the same error.

Node: v0.12.0
npm: 2.5.1

**Comment by saghul** [comment]
Are you on OSX by any chance?

**Comment by marty-buly** [comment]
Nope. 

Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (x86_64)
Release:        11

**Comment by saghul** [comment]
Hum. I wonder if its EHOSTDOWN, can you check with gdb?

**Comment by marty-buly** [comment]
I apologise, but gdb is unknown for me. Could you assist? Thnx

**Comment by saghul** [comment]
Open the core file with gdb:

gdb node path_to_the_core_file

In the gdb CLI:

f 1
print err

That should give a negative number, paste it here please. If no core file is generated, do:

ulimit -c unlimited

before launching node.

**Comment by marty-buly** [comment]
Here you go:
Reading symbols from /usr/local/bamboo/build/tools/node-v0.12.0/bin/node...done.

warning: core file may not match specified executable file.
[New LWP 16598]
[New LWP 16606]
[New LWP 16604]
[New LWP 16607]
[New LWP 16608]
[New LWP 16605]
[New LWP 16602]
[New LWP 16601]
[New LWP 16603]
Missing separate debuginfo for /lib64/librt.so.1
Try: zypper install -C "debuginfo(build-id)=682e4f7a27ee294a58f17249a0717861db546f2d"
Missing separate debuginfo for /lib64/libdl.so.2
Try: zypper install -C "debuginfo(build-id)=32c1c7a7a20b54ac3af6b2f436b3375ffeb12f0b"
Missing separate debuginfo for /usr/lib64/libstdc++.so.6
Try: zypper install -C "debuginfo(build-id)=2f51a06469a025d507534fe292dcf4e02235bd18"
Missing separate debuginfo for /lib64/libm.so.6
Try: zypper install -C "debuginfo(build-id)=d4191084441e39a7b480fc4b41f67083812e9811"
Missing separate debuginfo for /lib64/libgcc_s.so.1
Try: zypper install -C "debuginfo(build-id)=3b149eccd897f1f37dce50ad22614043eba757a2"
Missing separate debuginfo for /lib64/libpthread.so.0
Try: zypper install -C "debuginfo(build-id)=91334fd8105f0b62c0bdbbec14b45a9fd043f4c3"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libc.so.6
Try: zypper install -C "debuginfo(build-id)=4aee0c3923838575483ebd16be6db85ecb6f0b75"
Missing separate debuginfo for /lib64/ld-linux-x86-64.so.2
Try: zypper install -C "debuginfo(build-id)=a95c0ce9f9752baf052d3b55b3b8ce19f662d2eb"
Missing separate debuginfo for /lib64/libnss_files.so.2
Try: zypper install -C "debuginfo(build-id)=4f3dc8efbe18b50a6abe70d8b2f862ce185542d6"
Missing separate debuginfo for /lib64/libnss_dns.so.2
Try: zypper install -C "debuginfo(build-id)=3a135cbeb4736b6ff6698d9b83d8fe0445c47ffe"
Missing separate debuginfo for /lib64/libresolv.so.2
Try: zypper install -C "debuginfo(build-id)=0b092b85c7afea01072849200d7f7ad4442b3add"
Core was generated by `npm                                                                           '.
Program terminated with signal 6, Aborted.
#0  0x00007f8299878885 in raise () from /lib64/libc.so.6
(gdb) f 1
#1  0x00007f8299879e61 in abort () from /lib64/libc.so.6
(gdb) print err
$1 = {<text variable, no debug info>} 0x7f8299920910 <err>

**Comment by saghul** [comment]
Hum, it might be on another frame, can you do

bt

First?

**Comment by marty-buly** [comment]
(gdb) bt
#0  0x00007f709d115885 in raise () from /lib64/libc.so.6
#1  0x00007f709d116e61 in abort () from /lib64/libc.so.6
#2  0x00007f709d10e740 in __assert_fail () from /lib64/libc.so.6
#3  0x0000000000e0f8e9 in uv_err_name (err=<optimized out>) at ../deps/uv/src/uv-common.c:75
#4  0x0000000000c9eb0e in node::UVException(v8::Isolate*, int, char const*, char const*, char const*) ()
#5  0x0000000000cafde1 in node::After(uv_fs_s*) ()
#6  0x0000000000e0e30b in uv__work_done (handle=0x15f2030 <default_loop_struct+176>) at ../deps/uv/src/threadpool.c:236
#7  0x0000000000e0fe8d in uv__async_event (loop=0x15f1f80 <default_loop_struct>, w=<optimized out>, nevents=<optimized out>) at ../deps/uv/src/unix/async.c:89
#8  0x0000000000e10193 in uv__async_io (loop=0x15f1f80 <default_loop_struct>, w=0x15f2148 <default_loop_struct+456>, events=<optimized out>) at ../deps/uv/src/unix/async.c:160
#9  0x0000000000e1f23f in uv__io_poll (loop=0x15f1f80 <default_loop_struct>, timeout=34) at ../deps/uv/src/unix/linux-core.c:305
#10 0x0000000000e111d6 in uv_run (loop=0x15f1f80 <default_loop_struct>, mode=UV_RUN_ONCE) at ../deps/uv/src/unix/core.c:323
#11 0x0000000000ca3fc1 in node::Start(int, char**) ()
#12 0x00007f709d101c36 in __libc_start_main () from /lib64/libc.so.6
#13 0x00000000006ad069 in _start ()

**Comment by saghul** [comment]
do:

f 3
print err

**Comment by marty-buly** [comment]
(gdb) f 3
#3  0x0000000000e0f8e9 in uv_err_name (err=<optimized out>) at ../deps/uv/src/uv-common.c:75
75      ../deps/uv/src/uv-common.c: No such file or directory.
(gdb) print err
$1 = <optimized out>

**Comment by marty-buly** [comment]
last line in the comment above is actually '$1 = <optimized out>'

**Comment by saghul** [comment]
Damn. Did you build Node yourself? If so, can you make a Debug build instead of a Release one?

**Comment by marty-buly** [comment]
Nope, I've took the tar file from the www.nodejs.org.

**Comment by saghul** [comment]
Then I'm afraid you'll have to manually build it, since I know no other way of knowing what errno is not mapped. I'm reasonably sure it's EHOSTDOWN, which we added recently, but Node hasn't updated its bundled libuv yet. Any chance you can test it out with iojs?

**Comment by saghul** [comment]
The libuv update landed in Node: https://github.com/joyent/node/pull/9179 can you build the v0.12 branch and test again? I'm reasonably sure it will be fixed now.

**Comment by marty-buly** [comment]
I'm not experiencing this issue anymore, even I did no update. I really don't know what happened and why it works now. Anyway, thnx for your help, but this issue can be closed.
