### ISSUE TITLE
a compiling warning about -Wmaybe-uninitialized

### ISSUE THREAD

**Issue by zhaozg** [libuv/libuv#2518]
* **Version**:  Head v1.x
* **Platform**:  Linux holy-build-docker
```
[ 93%] Building C object luv.dir/libuv/CMakeFiles/uv_a.dir/src/idna.c.o
/root/work/portable/libuv/src/idna.c: In function 'uv__idna_toascii_label':
/root/work/portable/libuv/src/idna.c:127:13: warning: 'c' may be used uninitialized in this function [-Wmaybe-uninitialized]
     else if (c == (unsigned) -1)
             ^
```

**Comment by bnoordhuis** [comment]
Thanks for the report. I reviewed the code and no action is necessary. It's a false positive, your compiler isn't able to infer that `c` is always assigned to in the code paths leading up to that line.
