### ISSUE TITLE
Compilation using Android NDK

### ISSUE THREAD

**Issue by julien33** [libuv/libuv#252]
When using the android NDK with intel target, in src/unix/fs.c, the function uv__to_stat don't have the right parameters in struct stat* src.

I don't know if there is a specific #define ANDROID but the stat structure is as follow (NDK platform API>=9)

dst->st_atim.tv_sec = src->st_atime;
dst->st_atim.tv_nsec = src->st_atime_nsec;
dst->st_mtim.tv_sec = src->st_mtime;
dst->st_mtim.tv_nsec = src->st_mtime_nsec;
dst->st_ctim.tv_sec = src->st_ctime;
dst->st_ctim.tv_nsec = src->st_ctime_nsec;

currently it goes through the following code : (line 664)

#elif !defined(_AIX) && (       \
    defined(_BSD_SOURCE)     || \
    defined(_SVID_SOURCE)    || \
    defined(_XOPEN_SOURCE)   || \
    defined(_DEFAULT_SOURCE))
  dst->st_atim.tv_sec = src->st_atim.tv_sec;
  dst->st_atim.tv_nsec = src->st_atim.tv_nsec;
  dst->st_mtim.tv_sec = src->st_mtim.tv_sec;
  dst->st_mtim.tv_nsec = src->st_mtim.tv_nsec;
  dst->st_ctim.tv_sec = src->st_ctim.tv_sec;
  dst->st_ctim.tv_nsec = src->st_ctim.tv_nsec;

By the way, I used android-configure setup script for ARM as a reference and changed it to intel :

#!/bin/bash

export TOOLCHAIN=$PWD/android-toolchain
mkdir -p $TOOLCHAIN
$1/build/tools/make-standalone-toolchain.sh \
--toolchain=x86-4.8 \
--arch=x86 \
--install-dir=$TOOLCHAIN \
--platform=android-9
export PATH=$TOOLCHAIN/bin:$PATH
export AR=i686-linux-android-ar
export CC=i686-linux-android-gcc
export CXX=i686-linux-android-g++
export LINK=i686-linux-android-g++

./configure \
--without-snapshot \
--dest-cpu=ia32 \
--dest-os=android

mv $TOOLCHAIN/bin/python2.7 $TOOLCHAIN/bin/oldpython2.7
ln -s /usr/bin/python2.7 $TOOLCHAIN/python2.7

**Comment by bnoordhuis** [comment]
Does the patch below fix it?  If not, can you write up a patch of your own and submit it?

```diff
diff --git a/src/unix/fs.c b/src/unix/fs.c
index 91e5d4e..cc0cd91 100644
--- a/src/unix/fs.c
+++ b/src/unix/fs.c
@@ -662,6 +662,7 @@ static void uv__to_stat(struct stat* src, uv_stat_t* dst) {
   dst->st_flags = src->st_flags;
   dst->st_gen = src->st_gen;
 #elif !defined(_AIX) && (       \
+    defined(__ANDROID__)     || \
     defined(_BSD_SOURCE)     || \
     defined(_SVID_SOURCE)    || \
     defined(_XOPEN_SOURCE)   || \
```

**Comment by julien33** [comment]
As the content of the structure `stat` differ, I would propose a full `__ANDROID__` section :

```diff
diff --git src/unix/fs.c src/unix/fs.c.bak
index 91e5d4e..d0b3257 100755
--- a/src/unix/fs.c.bak
+++ b/src/unix/fs.c
@@ -661,6 +661,17 @@ static void uv__to_stat(struct stat* src, uv_stat_t* dst) {
   dst->st_birthtim.tv_nsec = src->st_birthtimespec.tv_nsec;
   dst->st_flags = src->st_flags;
   dst->st_gen = src->st_gen;
+#elif defined(__ANDROID__)
+  dst->st_atim.tv_sec = src->st_atime;
+  dst->st_atim.tv_nsec = src->st_atime_nsec;
+  dst->st_mtim.tv_sec = src->st_mtime;
+  dst->st_mtim.tv_nsec = src->st_mtime_nsec;
+  dst->st_ctim.tv_sec = src->st_ctime;
+  dst->st_ctim.tv_nsec = src->st_ctime_nsec;
+  dst->st_birthtim.tv_sec = src->st_ctime;
+  dst->st_birthtim.tv_nsec = src->st_ctime_nsec;
+  dst->st_flags = 0;
+  dst->st_gen = 0;
 #elif !defined(_AIX) && (       \
     defined(_BSD_SOURCE)     || \
     defined(_SVID_SOURCE)    || \

```

**Comment by saghul** [comment]
@julien33 yeah, that would probably do. Can you send a PR with your change?

**Comment by julien33** [comment]
@saghul I'm totally new to github, and not sure about the right procedure to do so, you can do it in your name if you want to.
