### ISSUE TITLE
libuv 1.33.0 compilation failure on aarch64

### ISSUE THREAD

**Issue by sgallagher** [libuv/libuv#2522]
* **Version**: 1.33.0
* **Platform**: Fedora Linux on aarch64 (fails on all current releases)

Attempting to build libuv on the aarch64 architecture results in a compilation error:
```
src/unix/random-sysctl.c: In function 'uv__random_sysctl':
src/unix/random-sysctl.c:69:17: error: 'SYS__sysctl' undeclared (first use in this function); did you mean 'SYS_keyctl'?
   69 |     if (syscall(SYS__sysctl, &args) == -1)
      |                 ^~~~~~~~~~~
      |                 SYS_keyctl
src/unix/random-sysctl.c:69:17: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:2904: src/unix/libuv_la-random-sysctl.lo] Error 1
```

From [`sysctl(2)`](https://www.mankier.com/2/sysctl):
"[U]se of this system call has long been discouraged, and it is so unloved that **it is likely to disappear in a future kernel version**. Since Linux 2.6.24, uses of this system call result in warnings in the kernel log. Remove it from your programs now; use the /proc/sys interface instead."

Attn: @bnoordhuis

**Comment by bnoordhuis** [comment]
#2524 and thanks for the report.

**Comment by sgallagher** [comment]
Thanks for the quick fix!
