### ISSUE TITLE
2 test failures on CentOS-7-1908

### ISSUE THREAD

**Issue by jcem** [libuv/libuv#2527]
* Version: libuv-v1.33.1.tar.gz

* Platform
   $ uname -a # cent-os 64, 1908 as a virtaul box guest.
   Linux *** 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* logs
  [libuv.txt](https://github.com/libuv/libuv/files/3749567/libuv.txt)

* $ make test ### failed running as a normal user not root.
// ... 
ok 346 - udp_multicast_interface6
not ok 347 - udp_multicast_join
timeout
Output from process `udp_multicast_join`: (no output)
not ok 348 - udp_multicast_join6
timeout
Output from process `udp_multicast_join6`: (no output)
// ...

**Comment by santigimeno** [comment]
Those failures usually happen due to your firewall rules (iptables, firewalld). Disable them and it should be fine.

**Comment by vtjnash** [comment]
Closing due to lack of followup info
