### ISSUE TITLE
tests 121-123 (getnameinfo_basic_ip*) fail on Guix System

### ISSUE THREAD

**Issue by amiloradovsky** [libuv/libuv#2531]
* **Version**: 1.33.1, 1.30.1
* **Platform**: Linux guix 5.2.11-gnu #1 SMP 1 x86_64 GNU/Linux
```
not ok 121 - getnameinfo_basic_ip4
# exit code 6
# Output from process `getnameinfo_basic_ip4`:
# Assertion failed in test/test-getnameinfo.c on line 42: status == 0
not ok 122 - getnameinfo_basic_ip4_sync
# exit code 6
# Output from process `getnameinfo_basic_ip4_sync`:
# Assertion failed in test/test-getnameinfo.c on line 75: 0 == uv_getnameinfo(uv_default_loop(), &req, NULL, (const struct sockaddr*)&addr4, 0)
not ok 123 - getnameinfo_basic_ip6
# exit code 6
# Output from process `getnameinfo_basic_ip6`:
# Assertion failed in test/test-getnameinfo.c on line 42: status == 0
```

**Comment by saghul** [comment]
What does your /etc/hosts file contain?

**Comment by amiloradovsky** [comment]
Roughly this:
```
127.0.0.1 localhost guix
::1       localhost guix
192.168.1.1 node-1
192.168.1.2 node-2
192.168.1.3 node-3
192.168.1.4 node-4
192.168.2.1 local-gitlab
192.168.2.2 local-time
```

**Comment by saghul** [comment]
And /etc/nsswitch.conf?

**Comment by amiloradovsky** [comment]
```
group:	files
hosts:	files mdns_minimal [NOTFOUND=return] dns mdns
networks:	files dns [!UNAVAIL=return]
passwd:	files
shadow:	files
```

**Comment by saghul** [comment]
Hum, that looks fine. I'm afraid I'm out of ideas for now... :-(

**Comment by amiloradovsky** [comment]
This isn't critical, I just thought I could update the `libuv` package in Guix to, say, 1.33.2, and enable the tests back, since these three are the only failed now (in Guix, package builds perform the tests by default, unless explicitly disabled).

**Comment by bnoordhuis** [comment]
Can you perhaps check what the return value/variable values are at the points of failures (either through gdb or some printf statements)? That might provide a clue.

**Comment by amiloradovsky** [comment]
@bnoordhuis From what I can see looking at the sources: `uv_getnameinfo` (`src/unix/getnameinfo.c`) submits `getnameinfo_req` (`test/test-getnameinfo.c`) as work to a loop, and from there it is called with non-zero second argument.

I'm not ready to dig it up further, ATM. Especially given I'm not very familiar with libuv's inner machinery. However I may have seen some other loop & work related issues on this system in another application, so may need to do it anyway, but later.

**Comment by amiloradovsky** [comment]
`status == -1`, `%m = Success`

```diff
diff --git a/test/test-getnameinfo.c b/test/test-getnameinfo.c
index b1391616..eb3c83c6 100644
--- a/test/test-getnameinfo.c
+++ b/test/test-getnameinfo.c
@@ -39,6 +39,7 @@ static void getnameinfo_req(uv_getnameinfo_t* handle,
                             const char* hostname,
                             const char* service) {
   ASSERT(handle != NULL);
+  if (status) warn ("error %u: %m", status);
   ASSERT(status == 0);
   ASSERT(hostname != NULL);
   ASSERT(service != NULL);
```
exact output
```
not ok 121 - getnameinfo_basic_ip4
# exit code 6
# Output from process `getnameinfo_basic_ip4`:
# run-tests: error 4294964295: Success: Success
# Assertion failed in test/test-getnameinfo.c on line 43: status == 0
not ok 122 - getnameinfo_basic_ip4_sync
# exit code 6
# Output from process `getnameinfo_basic_ip4_sync`:
# Assertion failed in test/test-getnameinfo.c on line 76: 0 == uv_getnameinfo(uv_default_loop(), &req, NULL, (const struct sockaddr*)&addr4, 0)
not ok 123 - getnameinfo_basic_ip6
# exit code 6
# Output from process `getnameinfo_basic_ip6`:
# run-tests: error 4294964295: Success: Success
# Assertion failed in test/test-getnameinfo.c on line 43: status == 0
```
P.S. Shouldn't use `%m`, because tautology, but anyway.

**Comment by bnoordhuis** [comment]
Thanks. That 4294964295 status code is -3001 or `UV_EAI_AGAIN`, a.k.a. temporary failure. That normally comes directly from the DNS resolver, it's probably not a libuv issue.

**Comment by amiloradovsky** [comment]
Oops. I should print it with `%d`.
And the test should then indeed try again several times before failing, right?

**Comment by bnoordhuis** [comment]
I'm reluctant to commit to anything stronger than "possibly maybe." :-)

If retrying makes the tests pass locally for you in a reasonable amount of time, please send a pull request with your changes and we'll take it from there.
