### ISSUE TITLE
Use {0} instead of memset

### ISSUE THREAD

**Issue by Hirrolot** [libuv/libuv#2534]
We could use the `struct my_struct object = { 0 }` syntax instead of `memset(&object, 0, sizeof(object))`. It has several advantages:
 1. Simpler, cleaner syntax;
 2. `memset` can potentially lead to UB if a structure contains types that cannot be represented as all-zeroed bits (for example, `float` on some platforms).

For instance, we could change [this](https://github.com/libuv/libuv/blob/v1.x/src/win/udp.c#L518) piece of code to something like this:

```c
struct sockaddr_storage from = { 0 };
```

I can take this issue if it's necessary.

**Comment by saghul** [comment]
Is that C89 legal? I can’t remember off the top of my head.

**Comment by vtjnash** [comment]
Yes. Source: https://en.cppreference.com/w/c/language/struct_initialization. The downside is that it could generate different code, iirc (it might skip over padding) and that the choice of `0` there assumes that the first field of a sockaddr_storage is of primitive type (non struct or array). In C++, this idiom is a bit better, because `{}` is valid.

**Comment by vtjnash** [comment]
Actually, rereading that source, it appears that a struct or array is generally OK, it may only be an issue for `union`.

**Comment by Hippolot** [comment]
@vtjnash, yes, because unions are not aggregated types.

**Comment by Hippolot** [comment]
@vtjnash, we can use `{0}` if the first member of a structure is not a primitive type:
```
$ cat main.c
struct Foo {
	int a[10];
};

int main(void) {
	struct Foo foo = { 0 };
}

$ gcc main.c -std=c90 -Wall -pedantic
main.c: In function ‘main’:
main.c:6:13: warning: unused variable ‘foo’ [-Wunused-variable]
  struct Foo foo = { 0 };
             ^~~
main.c:7:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

**Comment by Hippolot** [comment]
@vtjnash, I also think that we shouldn't care about structure padding because it's generally considered a garbage data used only to satisfy the alignments of data types. Can you provide an example where values of padding make sense?

**Comment by bnoordhuis** [comment]
Valgrind will sometimes complain about uninitialized padding when passing a struct to a system call, see e.g. commit 0813f5b9 for an example.
