### ISSUE TITLE
FAIL: test/run-tests

### ISSUE THREAD

**Issue by jacob008** [libuv/libuv#2549]
ok 373 - we_get_signals
ok 374 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory `/root/c++/libuv/libuv'
make: *** [check-am] Error 2
[root@localhost libuv]# 

我也不知道是干什么，它叫我report 到这里 ，我也不知道有什么用！

**Comment by jacob008** [comment]
ok 47 - fs_chown
not ok 48 - fs_copyfile
# exit code 6
# Output from process `fs_copyfile`:
# Assertion failed in test/test-fs-copyfile.c on line 202: req.result == UV_EACCES
ok 49 - fs_event_close_in_callback

补充一下。。

**Comment by sffc** [comment]
+1, this is reproducible on CentOS 7 with unmodified code built with autotools from the v1.x branch:

```
...
ok 46 - fs_chmod
ok 47 - fs_chown
not ok 48 - fs_copyfile
# exit code 134
# Output from process `fs_copyfile`:
# Assertion failed in test/test-fs-copyfile.c on line 202: req.result == UV_EACCES
ok 49 - fs_event_close_in_callback
ok 50 - fs_event_close_with_pending_event
...
```

**Comment by sffc** [comment]
The test failure reproduces on v1.32.0 but not v1.24.1.  I didn't check all the versions between v1.24.1 and v1.32.0.

**Comment by cjihrig** [comment]
Are you able to provide the value of `req.result` [here](https://github.com/libuv/libuv/blob/2ab3dc1567d67924b634be6f478d25f4528ce574/test/test-fs-copyfile.c#L202)? That test was added in https://github.com/libuv/libuv/commit/c7b87b0d51dd1d1a8629832daecd060b5d316123, when it was discovered that macOS wasn't respecting file permissions in its `copyfile()` function. Hopefully you're just bumping into a different error code.

**Comment by richardlau** [comment]
> make[1]: Leaving directory `/root/c++/libuv/libuv'

I think test failures are expected if running as root?

**Comment by cjihrig** [comment]
> I think test failures are expected if running as root?

Yes, that too. The [issue template](https://raw.githubusercontent.com/libuv/libuv/v1.x/.github/ISSUE_TEMPLATE.md) explicitly calls that out, and has since before this issue was created.
