### ISSUE TITLE
Android x86 build: linker fails (libuv_la-stream.o): relocation R_386_GOTOFF

### ISSUE THREAD

**Issue by therock24** [libuv/libuv#2554]
Hello everyone.
I've been compiling libuv for the 4 android architectures (arm-v7a, arm64-v8a, x86 and x86_64), because i need this dependency to compile **libwebsockets for Android**. The latest libuv version **compiles fine for ARM architectures but fails for x86 architectures** with the following error:
<I have removed some unnecessary parts of the output, containing other libraries>

> /Users/vitorfernandes/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=i686-none-linux-android24 --gcc-toolchain=/Users/vitorfernandes/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/vitorfernandes/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -shared -Wl,-soname ...<arguments cut>... -llog -landroid -latomic -lm && :
> /Users/vitorfernandes/Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: **error: ...libwebsockets/x86/lib/libuv.a(libuv_la-stream.o): relocation R_386_GOTOFF against preemptible symbol uv_try_write_cb cannot be used when making a shared object**
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> 

- **Libuv Version:** v1.33.1 and probably others
- **Platform**: Android x86 and Android x86_64
- **Android API version**: 24 and below
- **Compiler:** clang
- **Using a toolchain generated by NDK 18 to compile the library. Then the  linking to my project is done with NDK 20** I don't think this could be an issue. It works for arm and arm64.

However, I've tested compiling **libuv version 1.9.1** and **it worked**, this error didn't show on the linking stage. Any clue what this might be? This is possibly a bug for the latest releases.

Thanks in advance.

**Comment by saghul** [comment]
1.9.1 is really really old. Many things have changed since... IIRC someone recently compiled it with NDK r19. Any chance you can try that?

**Comment by therock24** [comment]
> 1.9.1 is really really old. Many things have changed since... IIRC someone recently compiled it with NDK r19. Any chance you can try that?

I have tried compiling with Android NDK 20, but the same error shown. This is a linking failure, the library compiles fine for x86. But at the time of linking this error comes up. I will try to build it with NDK r19

**Comment by bnoordhuis** [comment]
Can you show the exact (and full) output of a clean build? Thanks.

**Comment by bnoordhuis** [comment]
Closing, no follow-up.
