### ISSUE TITLE
Feature request:  mkstemp  

### ISSUE THREAD

**Issue by musm** [libuv/libuv#2555]
libuv provides a cross-platform `uv_os_tmpdir` function. We are still missing some important os manipulation functions, in particular: 

Add cross-platform   tempnam, mkstemp functions

**Comment by cjihrig** [comment]
There is a PR for mkstemp: https://github.com/libuv/libuv/pull/2074. As for tempnam, the first sentence of the Description section from http://man7.org/linux/man-pages/man3/tempnam.3.html says "Never use this function."

**Comment by musm** [comment]
good point
