### ISSUE TITLE
VS 2019

### ISSUE THREAD

**Issue by maddinthegreat** [libuv/libuv#2560]
Hello,

could you please provide a VS 2019 compatible vcbuild.bat?

Regards
Martin

**Comment by bnoordhuis** [comment]
What specifically isn't working? Please provide the full output.

**Comment by maddinthegreat** [comment]
I got the static libs from another source, nonetheless your batch does not work for VS 2019. It didn't compile. I looked into vcbuild.bat and saw only VS 2017 handled correctly.

Regards

**Comment by saghul** [comment]
I think we need to add it to the paths we try load vcvarsall.bat from.

**Comment by maddinthegreat** [comment]
Yes, please test it on VS 2019 thoroughly.
Thanks in advance!

**Comment by Dream-Mgy** [comment]
I want it toooooo!!! Thank you very much!

**Comment by ValoWaking** [comment]
yes, isn't work. Can any one download libuv.lib compiled with VS2019 v16.4.1?

**Comment by zoushaoyun** [comment]
Mine is vs2019. So same question to me!

**Comment by kamronbatman** [comment]
I got this to work with VS2019 by doing the following:
Generate the SLN files.
Go to VS 2019 installer and make sure to install the x86/x64 **v141** C++ build components and the Windows 10 SDK.
Open uv.sln with visual studio 2019. Download any required files. Migrate the project and build.
I got the same libuv.dll output file as running the batch file.
You may have to change the type of output in the project settings.

**Comment by richardlau** [comment]
For reference, in Node.js the changes to add VS2019 to its version of vcbuild.bat were done in https://github.com/nodejs/node/pull/30022.

**Comment by saghul** [comment]
Yeah, porting those over should be the way to go.

**Comment by Himself65** [comment]
Does anyone work on this?

**Comment by bnoordhuis** [comment]
@Himself65 I don't think so. You're welcome to take this up.

**Comment by gengjiawen** [comment]
VS 2019 support cmake, you can try this way.

**Comment by saghul** [comment]
Now that https://github.com/libuv/libuv/commit/53f3c687fc288708721a5a3d9563febda1b9d2c1 is in and GYP is out, there is no need to do anything in libuv AFAICT, CMake takes care of it: https://cmake.org/cmake/help/git-stage/generator/Visual%20Studio%2016%202019.html
