### ISSUE TITLE
This function may have a memory leak

### ISSUE THREAD

**Issue by xhqxhq** [libuv/libuv#2562]
* **Version**: master
* **Platform**: windows

at uv_fs_read function,as follows:
  if (nbufs > ARRAY_SIZE(req->fs.info.bufsml))
    req->fs.info.bufs = uv__malloc(nbufs * sizeof(*bufs));
When the conditions are established,libuv use uv_malloc to allocate memory,
libuv don't free   allocateed memory after read file operation completed; if Reapated read operation on this req, The previously assigned memory leaks

**Comment by xhqxhq** [comment]
sory , my English is poor, this is first launched issue at github

**Comment by saghul** [comment]
You must call `uv_fs_req_cleanup` after each request is complete. The buffers are freed right there, amongst other cleanup: https://github.com/libuv/libuv/blob/5500253cac6fb4918aa75bde875794a7bfbdb2f0/src/win/fs.c#L2737
