### ISSUE TITLE
darwin: cannot get window size after get/set proc title

### ISSUE THREAD

**Issue by legendecas** [libuv/libuv#2566]
* **Version**: 1.34.0
* **Platform**: macOS

After setting the process as a daemon, the windows' size could not be retrieved anymore.
<details>
<summary>Minimal codes to reproduce: </summary>

```cpp
#include <stdio.h>
#include <dlfcn.h>
#include <ApplicationServices/ApplicationServices.h>

#define S(s) pCFStringCreateWithCString(NULL, (s), kCFStringEncodingUTF8)

static CFStringRef (*pCFStringCreateWithCString)(CFAllocatorRef,
                                                 const char *,
                                                 CFStringEncoding);
static CFBundleRef (*pCFBundleGetBundleWithIdentifier)(CFStringRef);
static void *(*pCFBundleGetDataPointerForName)(CFBundleRef, CFStringRef);
static void *(*pCFBundleGetFunctionPointerForName)(CFBundleRef, CFStringRef);
static CFTypeRef (*pLSGetCurrentApplicationASN)(void);
static OSStatus (*pLSSetApplicationInformationItem)(int,
                                                    CFTypeRef,
                                                    CFStringRef,
                                                    CFStringRef,
                                                    CFDictionaryRef *);
static void *application_services_handle;
static void *core_foundation_handle;
static CFBundleRef launch_services_bundle;
static CFStringRef *display_name_key;
static CFDictionaryRef (*pCFBundleGetInfoDictionary)(CFBundleRef);
static CFBundleRef (*pCFBundleGetMainBundle)(void);
static CFBundleRef hi_services_bundle;
static CFDictionaryRef (*pLSApplicationCheckIn)(int, CFDictionaryRef);
static void (*pLSSetApplicationLaunchServicesServerConnectionStatus)(uint64_t,
                                                                     void *);

int main()
{
  OSStatus (*pSetApplicationIsDaemon)(int);
  CGDirectDisplayID displayID;

  application_services_handle = dlopen("/System/Library/Frameworks/"
                                       "ApplicationServices.framework/"
                                       "Versions/A/ApplicationServices",
                                       RTLD_LAZY | RTLD_LOCAL);
  core_foundation_handle = dlopen("/System/Library/Frameworks/"
                                  "CoreFoundation.framework/"
                                  "Versions/A/CoreFoundation",
                                  RTLD_LAZY | RTLD_LOCAL);

  if (application_services_handle == NULL || core_foundation_handle == NULL)
    goto out;

  *(void **)(&pCFStringCreateWithCString) =
      dlsym(core_foundation_handle, "CFStringCreateWithCString");
  *(void **)(&pCFBundleGetBundleWithIdentifier) =
      dlsym(core_foundation_handle, "CFBundleGetBundleWithIdentifier");
  *(void **)(&pCFBundleGetDataPointerForName) =
      dlsym(core_foundation_handle, "CFBundleGetDataPointerForName");
  *(void **)(&pCFBundleGetFunctionPointerForName) =
      dlsym(core_foundation_handle, "CFBundleGetFunctionPointerForName");

  if (pCFStringCreateWithCString == NULL ||
      pCFBundleGetBundleWithIdentifier == NULL ||
      pCFBundleGetDataPointerForName == NULL ||
      pCFBundleGetFunctionPointerForName == NULL)
  {
    goto out;
  }

  launch_services_bundle =
      pCFBundleGetBundleWithIdentifier(S("com.apple.LaunchServices"));

  if (launch_services_bundle == NULL)
    goto out;

  *(void **)(&pLSGetCurrentApplicationASN) =
      pCFBundleGetFunctionPointerForName(launch_services_bundle,
                                         S("_LSGetCurrentApplicationASN"));

  if (pLSGetCurrentApplicationASN == NULL)
    goto out;

  *(void **)(&pLSSetApplicationInformationItem) =
      pCFBundleGetFunctionPointerForName(launch_services_bundle,
                                         S("_LSSetApplicationInformationItem"));

  if (pLSSetApplicationInformationItem == NULL)
    goto out;

  display_name_key = (CFStringRef *)pCFBundleGetDataPointerForName(launch_services_bundle,
                                                                   S("_kLSDisplayNameKey"));

  if (display_name_key == NULL || *display_name_key == NULL)
    goto out;

  *(void **)(&pCFBundleGetInfoDictionary) = dlsym(core_foundation_handle,
                                                  "CFBundleGetInfoDictionary");
  *(void **)(&pCFBundleGetMainBundle) = dlsym(core_foundation_handle,
                                              "CFBundleGetMainBundle");

  if (pCFBundleGetInfoDictionary == NULL || pCFBundleGetMainBundle == NULL)
    goto out;

  /* Black 10.9 magic, to remove (Not responding) mark in Activity Monitor */
  hi_services_bundle =
      pCFBundleGetBundleWithIdentifier(S("com.apple.HIServices"));

  if (hi_services_bundle == NULL)
    goto out;

  *(void **)(&pSetApplicationIsDaemon) = pCFBundleGetFunctionPointerForName(
      hi_services_bundle,
      S("SetApplicationIsDaemon"));
  *(void **)(&pLSApplicationCheckIn) = pCFBundleGetFunctionPointerForName(
      launch_services_bundle,
      S("_LSApplicationCheckIn"));
  *(void **)(&pLSSetApplicationLaunchServicesServerConnectionStatus) =
      pCFBundleGetFunctionPointerForName(
          launch_services_bundle,
          S("_LSSetApplicationLaunchServicesServerConnectionStatus"));

  if (pSetApplicationIsDaemon == NULL ||
      pLSApplicationCheckIn == NULL ||
      pLSSetApplicationLaunchServicesServerConnectionStatus == NULL)
  {
    goto out;
  }

  /* Prevent crash when LaunchServices cannot be connected to. */
  pSetApplicationIsDaemon(1); /** comment out this line to make the following codes work */

  displayID = CGMainDisplayID();
  printf("{ width: %lu, height: %lu }\n", CGDisplayPixelsWide(displayID), CGDisplayPixelsHigh(displayID));
  fflush(stdout);
out:
  return 0;
}
```
</details>

Build Command: `clang minimal.cpp -framework ApplicationServices -o minimal`

Expected output:
```
{ width: 1920, height: 1080 }
```

Actual output:
```
{ width: 0, height: 0 }
```

Related: https://github.com/nodejs/node-gyp/issues/1981

**Comment by bnoordhuis** [comment]
I wonder if this is a problem with macos 10.15 because I can't reproduce with 10.14. Can you apply this patch and see if the test fails or passes?
```diff
diff --git a/test/test-tty.c b/test/test-tty.c
index 688711e5..958058d4 100644
--- a/test/test-tty.c
+++ b/test/test-tty.c
@@ -109,13 +109,21 @@ TEST_IMPL(tty) {
 
   printf("width=%d height=%d\n", width, height);
 
-  if (width == 0 && height == 0) {
+  if (width == 0 || height == 0) {
    /* Some environments such as containers or Jenkins behave like this
     * sometimes */
     MAKE_VALGRIND_HAPPY();
     return TEST_SKIP;
   }
 
+  r = uv_set_process_title("test");
+  ASSERT(r == 0);
+
+  r = uv_tty_get_winsize(&tty_out, &width, &height);
+  ASSERT(r == 0);
+  ASSERT(width != 0);
+  ASSERT(height != 0);
+
   /*
    * Is it a safe assumption that most people have terminals larger than
    * 10x10?
```
You can invoke the test individually with `./out/Debug/run-tests tty tty` (if you use the gyp build, the exact location of `run-tests` depends on the build system you use.)

**Comment by legendecas** [comment]
@bnoordhuis Seems the test works for me. But one thing different here is that the `uv_tty_get_winsize` output the line width and line height for the tty device, no the device pixel resolution.

**Comment by bnoordhuis** [comment]
Yes, valid observation. My best guess is that this is a bug in either CoreFoundation or ApplicationServices that libuv exposes rather than introduces.

Does your test case work when you revert the changes from #2480?

**Comment by legendecas** [comment]
#2480 made the issue expose with `uv_get_process_title`.

**Comment by legendecas** [comment]
08e0e63f3adecafeacaf09f519587c381c6e2ef2 introduced the `set_application_is_daemon` call. 🤔 does it still needed now? #966 in the commit message doesn't seem to be relavant.

**Comment by bnoordhuis** [comment]
I opened #2568 to revert.

**Comment by oktapodia** [comment]
Looks like the tests are passing 👍

**Comment by dhritzkiv** [comment]
Should this issue be closed?

It seems that the `printf("{ width: %lu, height: %lu }\n", CGDisplayPixelsWide(displayID), CGDisplayPixelsHigh(displayID));` part of the code still prints `{ width: 0, height: 0 }` when setting a process title beforehand (not present in the original example code). In fact, even before #2480, this was the behaviour. It's just that #2480 caused it to happen without calling `uv_set_process_title` explicitly, I think.

Both snippets reflecting behaviour as of 565cdd1 (after reverting #2480)

Without setting process title
```cpp
CGDirectDisplayID displayID;
//

displayID = CGMainDisplayID();
printf("{ width: %lu, height: %lu }\n", CGDisplayPixelsWide(displayID), CGDisplayPixelsHigh(displayID));
// prints { width: 2560, height: 1440 }
```

Setting process title before getting the display
```cpp
CGDirectDisplayID displayID;
//

uv_set_process_title("test");

displayID = CGMainDisplayID();
printf("{ width: %lu, height: %lu }\n", CGDisplayPixelsWide(displayID), CGDisplayPixelsHigh(displayID));
// prints { width: 0, height: 0 }
```

**Comment by bnoordhuis** [comment]
You can't see it but I'm throwing up my hands...

Was there anytime it worked for you? I.e., with older versions of node or macos? Can you try tweaking the code in `src/unix/darwin-proctitle.c`?

I'm guessing it's caused by the call by `SetApplicationIsDaemon()`. That's not something we can just remove, however, otherwise processes show up wrong in the task manager.

**Comment by dhritzkiv** [comment]
I don't blame you.

---

It has never worked for me, to my knowledge. The first time I came across this issue was 3.5 years ago when I was ripping my hair out because headless-gl wasn't working after I integrated it into a larger node project which had title-setting code. 

This would have been node 4 or 6 on macOS 10.9. After fixing the problem, I was simply happy that it was working again and didn't think much about it since (until experiencing the bug caused by #2480). I wasn't aware of libuv's role in all this at the time, either.

---

I'll try playing with the code in darwin-proctitle.c (even though I'm not super familiar with OS X framework code) later this evening.

---

Honestly, I'm just that glad that the regression was dealt with and headless-gl will work again in a near-future release of node.

**Comment by dhritzkiv** [comment]
Playing with darwin-proctitle and commenting-out the `SetApplicationIsDaemon` block at  https://github.com/libuv/libuv/blob/5cb8860b45b445ebb3e5961b0e06c720ae0d42f2/src/unix/darwin-proctitle.c#L170-L171 did lead to the correct display dimensions being reported after setting the process title.

All tests passed regardless, and I didn't notice any adverse side effects in Activity Monitor or elsewhere, and I'm not familiar with the LaunchServices problem as mentioned in an old commit here https://github.com/libuv/libuv/blob/038eacfbf466f0b51e80b6f5fa9026c7ed767dfb/src/unix/darwin-proctitle.c#L173-L175

Running on macOS 10.15.2

**Comment by bnoordhuis** [comment]
@libuv/collaborators Thoughts on removing the `SetApplicationIsDaemon()` call? For background, that was a workaround for a rare bug in a macos <= 10.8 release. I forgot the exact version but it was 10.8 at the latest.

10.7 and 10.8 are nominally still supported but I don't have any way to test on them anymore. I'm inclined to make the change because it fixes a known bug.

**Comment by cjihrig** [comment]
Is the issue just that the process will show up incorrectly in the task manager for certain old versions of macOS? If so, I'm OK with making the change.

**Comment by bnoordhuis** [comment]
Yes, the issue was that the process shows up as "not responding" in the Activity Monitor. However...

Chromium [does something similar](
https://cs.chromium.org/chromium/src/sandbox/mac/system_services.cc?l=26&rcl=a06d2fe5a279ddecd358d919d461080e2c53c92e) and has a comment claiming that HIServices aborts the process when it can't connect to launchservicesd: 
```c++
  // Allow the process to continue without a LaunchServices ASN. The
  // INIT_Process function in HIServices will abort if it cannot connect to
  // launchservicesd to get an ASN. By setting this flag, HIServices skips
  // that.
  OSStatus status = SetApplicationIsDaemon(true);
```
Libuv itself doesn't use HIServices but the libuv user could, of course... While calling `SetApplicationIsDaemon()` isn't really our responsibility, removing the call could lead to an observable change in behavior in existing programs.

I'll open a PR so we can discuss over code.
