### ISSUE TITLE
unix: memory leak

### ISSUE THREAD

**Issue by ssrlive** [libuv/libuv#2569]
* **Version**:  current version
* **Platform**: ubuntu 18.04
Memory leaking. Please fix it.
https://github.com/libuv/libuv/blob/v1.x/src/unix/core.c#L852

![image](https://user-images.githubusercontent.com/30760636/70417663-b315eb80-1a9c-11ea-8ad7-abd40a3bd7f5.png)

similes #140, but I don't think that is a solution.
I write a demo like:
```
int main(void) {
    uv_loop_t *loop = malloc(sizeof(uv_loop_t));
    uv_loop_init(loop);

    printf("Now quitting.\n");
    uv_run(loop, UV_RUN_DEFAULT);

    //uv_loop_close(loop);
    free(loop);

    return 0;
}
```
If I not call `uv_loop_close`, the leaking reproduce. but in [my case](https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/server/server.c#L240),  the `uv_loop_close` will cause crash. so I have to do it like:
```
    free(loop->watchers); //uv_loop_close(loop);
    free(loop);
```
The world looks become beautiful again. but the code is soooooo **stupid**.
Please fix it.

**Comment by bnoordhuis** [comment]
You should check the return value of `uv_loop_close()`. It probably returns `UV_EBUSY` to indicate that there are still active handles or requests.

If it crashes _inside_ `uv_loop_close()`, please post the backtrace.

**Comment by ssrlive** [comment]
you are right. thanks.
