### ISSUE TITLE
tty: closing tty handles does not restore tty

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#257]
I think this is a bug or at least unexpected behavior.  Test case:

``` c
#include <assert.h>
#include <stdlib.h>
#include "uv.h"

static void on_alloc(uv_handle_t* handle, size_t size, uv_buf_t* buf) {
  (void) &handle;
  buf->len = size;
  buf->base = malloc(size);
}

static void on_read(uv_stream_t* handle, ssize_t nread, const uv_buf_t* buf) {
  (void) &nread;
  (void) &buf;
  uv_close((uv_handle_t*) handle, NULL);
}

int main(void) {
  uv_loop_t loop;
  uv_tty_t tty;

  assert(0 == uv_loop_init(&loop));
  assert(0 == uv_tty_init(&loop, &tty, 0, 1));
  assert(0 == uv_tty_set_mode(&tty, UV_TTY_MODE_RAW));
  assert(0 == uv_read_start((uv_stream_t*) &tty, on_alloc, on_read));
  assert(0 == uv_run(&loop, UV_RUN_DEFAULT));
  assert(0 == uv_loop_close(&loop));

  return 0;
}
```

Compile and run, then press a key.  The program terminates cleanly but does not reset the tty to cooked mode.

Fixing that for a single uv_tty_t handle is relatively straightforward but because the tty state is global, it needs to be orchestrated between all open handles.

**Comment by odeke-em** [comment]
Just a suggestion off the top of my head, would it be reasonable to assign to every uv_tty_t handle its own `struct termios orig_termios` as well as a few state variables and on every shutdown restore these?

**Comment by odeke-em** [comment]
Never mind, I finally got home and got onto a computer to examine the code, (I made the previous suggestion while waiting for a meeting so sorry for the obvious stuff). I guess my suggestion alludes  to using each handle's termios in uv_tty_reset_mode instead of the global orig_termios.

**Comment by wavexx** [comment]
I'd argue this needs to be done by the upper layer. Changing the discipline on close might not always be warranted.
