### ISSUE TITLE
test fs_copyfile with root user fails

### ISSUE THREAD

**Issue by hamzakilic** [libuv/libuv#2571]
* **Version**:1.34.0 
* **Platform**:Linux  5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (ubuntu 19.10)

run make check as root

not ok 48 - fs_copyfile
#exit code 134
#Output from process `fs_copyfile`:
#Assertion failed in test/test-fs-copyfile.c on line 202: req.result == UV_EACCES

**Comment by cjihrig** [comment]
The issue template that you filled out says:

> If you are reporting a libuv test failure, please ensure that you are not
running the test as root.

The test suite is not intended to be run as root.

**Comment by hamzakilic** [comment]
oppps thanks.
