### ISSUE TITLE
[FR] Interface to get watched fd from uv_poll_t

### ISSUE THREAD

**Issue by icpz** [libuv/libuv#2575]
* **Version**: 1.31
* **Platform**:  *

Could you please consider adding an interface to retrieve the interested fd from an uv_poll_t handler? e.g.
```cpp
int uv_poll_get_fd(uv_poll_t *handle);
```

Thanks!

**Comment by saghul** [comment]
Hey there! This already exists! Checkout `uv_fileno`: http://docs.libuv.org/en/v1.x/handle.html#c.uv_fileno
