### ISSUE TITLE
how to uv_stop multithreading 

### ISSUE THREAD

**Issue by Mrzhuzy** [libuv/libuv#2576]
Can you give me an example？  thank you

**Comment by Mrzhuzy** [comment]
my code :
int shm_server_manager::stop()
{
  for (auto at : m_mapTh) {
    if (at.second != NULL) {
      //uv_stop(at.second->loop);
      uv_async_send(&at.second->stop);
    }
  }
  return 0;
}

but can't  normal stop thread

**Comment by saghul** [comment]
Please open an issue in the help repository or use the mailing this. The issue tracker is for issues or feature requests.
