### ISSUE TITLE
Add /utf-8 option for msvc in CMakeLists.txt

### ISSUE THREAD

**Issue by toddwong** [libuv/libuv#2581]
MS byte default detects utf8 encoding by the silly BOM, which libuv source code files don't have.

Simply change this line
https://github.com/libuv/libuv/blob/2ab3dc1567d67924b634be6f478d25f4528ce574/CMakeLists.txt#L15
to

```cmake
list(APPEND uv_cflags /W4 /utf-8)
``` 

would work.

This would avoids some errors (I think they were warnings treated as errors by some versions of msvs defautly)

**Comment by bnoordhuis** [comment]
Thanks for the suggestion but what warnings or errors would that fix specifically?

**Comment by bnoordhuis** [comment]
Closing, no follow-up.

**Comment by liyalei66** [comment]
its a bad idea
