### ISSUE TITLE
A lot of warnings upon build on Windows 10.

### ISSUE THREAD

**Issue by dmitigr** [libuv/libuv#2582]
Hi!

There are a lot of warnings upon build on Windows 10 with Visual Studio 2017 like these:

warning C4201: nonstandard extension used: nameless struct/union
warning C4245: 'return': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
warning C4100: 'w': unreferenced formal parameter
warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead.
warning C4232: nonstandard extension used: 'local_malloc': address of dllimport 'malloc' is not static, identity not guaranteed

etc etc.

Are fixes of these warnings welcome?

**Comment by bnoordhuis** [comment]
As long as they're unintrusive, sure. What's intrusive is somewhat subjective but anything that changes the API or ABI, is a functional change, or makes the code much harder to read/maintain likely fits the bill. :-)
