### ISSUE TITLE
Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1476

### ISSUE THREAD

**Issue by bobbrow** [libuv/libuv#2587]
* **Version**: 1.32.0
* **Platform**: Windows 10 18362 -->

libuv version 1.32.0 introduced a problem in node.js when packaging the [CMake Tools extension for VS Code ](https://github.com/microsoft/vscode-cmake-tools) with [vsce](https://github.com/microsoft/vscode-vsce) and [yarn]().  This first appears in node.js version 12.11 which merged libuv version 1.32.0.

I suspect the problem is with PR #2419 (since that's the only change I see around this section of code in 1.32.0 - https://github.com/nodejs/node/commit/df0e2e3625d1f72e8b04e05ffa13997a51e9f0d7#diff-3236653784e346138ede9f8b342eeae4)

**Repro steps:**
* **Prerequisites:**
  * Install node.js version 12.11 or newer ([download](https://nodejs.org/en/download/))
  * Install yarn ([download](https://yarnpkg.com/lang/en/docs/install/#windows-stable))
  * Run `npm install -g vsce` (anywhere is fine)
* Create a folder where you can clone the extension repository (e.g. `c:\git`)
* In that directory run: `git clone https://github.com/microsoft/vscode-cmake-tools.git`
* Run: `cd vscode-cmake-tools`
* Run: `vsce package --yarn`

**Expected Behavior:**
* vsce should create a cmake-tools-[version].vsix file in the `vscode-cmake-tools` folder

**Actual Behavior:**
* libuv crashes and the following output is displayed:
```
Executing prepublish script 'yarn run vscode:prepublish'...
ERROR  Command failed: yarn run vscode:prepublish
Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1476
error Command failed with exit code 3221226505.
```

**Comment by cjihrig** [comment]
Can you test if reverting https://github.com/libuv/libuv/pull/2419/commits/6c9c4fe9918a41d8d907c2b409d3a08992f6f543 makes a difference?

**Comment by cjihrig** [comment]
It's also worth noting that there were a few changes in Node 12.11.0 related to the handling of environment variables (https://github.com/nodejs/node/pull/27310, https://github.com/nodejs/node/pull/29188).

**Comment by bobbrow** [comment]
@cjihrig, you're right, this isn't caused by a change in libuv.  I built a debug version of node and found the issue.

node is now using libuv to get env variables, and yarn is stuffing the full contents of the NOTICE.md file into an env variable called `npm_package_noticeText`.  (related: https://github.com/yarnpkg/yarn/issues/5420).  I'll go file an issue in the yarn repo.

Thanks!

**Comment by vtjnash** [comment]
Even so, libuv should not assert

**Comment by bnoordhuis** [comment]
Libuv doesn't seem to be in the wrong though. From https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable:

> An environment variable has a maximum size limit of 32,767 characters, including the null-terminating character.

> If the function succeeds, the return value is the number of characters stored in the buffer pointed to by lpBuffer, not including the terminating null character.

And that's exactly what libuv is asserting: the buffer is 32767 characters big so the return value should be at most 32766.

I have no way to test myself (no Windows machine at hand) but can one of you check what the actual return value is? Thanks.

**Comment by bobbrow** [comment]
len = 37643 in our case.

**Comment by bnoordhuis** [comment]
Thanks. That's unexpected but I guess that'll teach us to never trust the documentation...

I'm not the resident win32 expert but I posted a tentative fix in #2589. It'd be great if you could try it.

**Comment by bobbrow** [comment]
It doesn't look like it crashes anymore, but I didn't have time to validate the end-to-end since I ran into this while trying to build the package:
```
error https-proxy-agent@2.2.4: The engine "node" is incompatible with this module. Expected version ">= 4.5.0". Got "14.0.0-pre"
```
I'll need to figure out how to change the node version and rebuild so that other packages don't freak out, but that is better than what I was seeing before.

I'm running on Windows 10, so I can't comment on whether the fix would be appropriate for earlier versions of Windows (if supported).

**Comment by lygstate** [comment]
```
yarn run v1.22.0
$ yarn run compile-production
Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1478
error Command failed with exit code 3221226505.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````
obviously len  are large than 32767
