### ISSUE TITLE
udp-dhcp code sample: receiving datagram causes main loop to stop

### ISSUE THREAD

**Issue by AB4EJ-1** [libuv/libuv#2606]
* **Version**: 1.x
* **Platform**: Ubuntu 18.04.3 LTS 64-bit

Using the example code for receiving (and replying to) UDP traffic [here:](https://github.com/libuv/libuv/tree/v1.x/docs/code/udp-dhcp) - after the program receives the first UDP packet (whether it tries to send back a reply or not), the main loop halts with a return code of 0.  It appears that something in  the code for uv_udp_recv is mishandling memory or inadvertently issuing a uv_stop. You can cope with this by putting the uv_run(loop, UV_RUN_DEFAULT) inside another loop of your own making, but this causes other issues with UDP port assignments.

**Comment by saghul** [comment]
Note that the example you linkedd was part of the uvguide we merged with not much scrutiny, so the examples might contain bugs.

**Comment by AB4EJ-1** [comment]
I just tried installing libuv on a different (CentOS this time), and ran check; some tests failed that sound like possibly related:

not ok 348 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
not ok 349 - udp_multicast_join6
# timeout
# Output from process `udp_multicast_join6`: (no output)

**Comment by vtjnash** [comment]
It explicitly exits with success after handling one packet: https://github.com/libuv/libuv/blob/6432886e0d1adb3f76eb0eee55584af4f18ae31f/docs/code/udp-dhcp/main.c#L39

**Comment by AB4EJ-1** [comment]
I did see that. But if you remove the uv_udp_recv_stop instruction, the program crashes with a segmentation fault.

**Comment by sewenew** [comment]
> I did see that. But if you remove the uv_udp_recv_stop instruction, the program crashes with a segmentation fault.

The reason for segmentation fault is that `addr` and `buf` are used without checking if these pointers are null.

```
void on_read(uv_udp_t *req, ssize_t nread, const uv_buf_t *buf, const struct sockaddr *addr, unsigned flags) {
    if (nread < 0) {
        fprintf(stderr, "Read error %s\n", uv_err_name(nread));
        uv_close((uv_handle_t*) req, NULL);
        free(buf->base);
        return;
    }

    // <-------- if nread == 0, `addr`, and `buf` might be NULL pointer.
    // <-------- However, the following code dereference these pointers without checking if they are NULL.

    char sender[17] = { 0 };
    uv_ip4_name((const struct sockaddr_in*) addr, sender, 16);
    fprintf(stderr, "Recv from %s\n", sender);

    // ... DHCP specific code
    unsigned int *as_integer = (unsigned int*)buf->base;
    // ... other code
}
```

**Comment by flcoder** [comment]
Yeah, it seams for every incoming message, `on_read` gets called twice, the first time with good data, and the second time with null data.  Seems kind of pointless.

**Comment by flcoder** [comment]
https://github.com/libuv/libuv/blob/c1128f3db3fe85039f9dc9423b353a3ad673a13a/src/unix/udp.c#L294

This is why the callback is getting called twice every time.  When you get EAGAIN or EWOULDBLOCK, I think you should just break. I don't see any reason to call the callback with null parameters.

**Comment by bnoordhuis** [comment]
The null callback tells you it's safe to release or reuse the memory you gave to libuv in your uv_alloc_cb callback.
