### ISSUE TITLE
Leap seconds/impact to libuv ?

### ISSUE THREAD

**Issue by mdawsonibm** [libuv/libuv#261]
In coordinated universal time (UTC) a day normally consists of 86400 seconds. However, every few years there is an extra second called a "leap second". The leap second is always added as the last second of the day, and always on December 31 or June 30. There will be a leap second on June 30 2015.

We've been asked what effect this could have on a Node application.  In may cases Node depends on libuv for time related functions so we'd like to ask if this has been considered and if its likely/possible that the insertion of the leap second will affect the correct operation of the calls made through the libuv API.

**Comment by bnoordhuis** [comment]
Libuv doesn't use `gettimeofday()` if that is what you're asking, it uses a monotonic clock (e.g. CLOCK_MONOTONIC).  Condition variables use a monotonic clock or relative timeouts for timed waits.
