### ISSUE TITLE
Is there bug uv__run_closing_handles function ?

### ISSUE THREAD

**Issue by ggandycong** [libuv/libuv#2629]
After  running  this line code as listed follow in **uv__run_closing_handles** function,  the pointer of **p**  will  also is NULL. So whatever the condition of **while** is forever  false,  right ?
```
  loop->closing_handles = NULL;
```
**uv__run_closing_handles** 
```
static void uv__run_closing_handles(uv_loop_t* loop) {
  uv_handle_t* p;
  uv_handle_t* q;


  p = loop->closing_handles;
  loop->closing_handles = NULL;

  while (p) {
    q = p->next_closing;
    uv__finish_close(p);
    p = q;
  }
}
```

**Comment by bnoordhuis** [comment]
No... `loop->closing_handles` is a linked list. `p` is a copy of the head-of-list pointer and is then iterated over to dispatch the items in the list.
