### ISSUE TITLE
One test fails when I run `make check`

### ISSUE THREAD

**Issue by greduan** [libuv/libuv#263]
http://sprunge.us/QHRU

That's the full paste, I and my friend use the [CRUX](https://crux.nu/) Linux distro, the paste is the output of compiling the `libuv` package I made real quick. (http://sprunge.us/daGM in case you're interested.)

CRUX uses glibc v2.19 ATM (in case that matters).

From the paste we can get the following:

```
[%  71|+ 178|-   0|T   0|S   0]: spawn_setuid_fails
`spawn_setuid_fails` failed: exit code 6
Output from process `spawn_setuid_fails`:
Assertion failed in test/test-spawn.c on line 1092: r == UV_EPERM
=============================================================
[2K
[%  71|+ 178|-   1|T   0|S   0]: spawn_setgid_fails
`spawn_setgid_fails` failed: exit code 6
Output from process `spawn_setgid_fails`:
Assertion failed in test/test-spawn.c on line 1123: r == UV_EPERM
```
Is this a problem? Is this test not implemented yet? For the record I'm compiling libuv as a dependency for NeoVim, which I was able to successfully compile and I haven't run across any problems with it, yet.

If you need any more information feel free to ask. :)

Also please feel free to change the title to something that is more descriptive. I didn't make it very descriptive because I'm not sure what to name it. :/

**Comment by therealromster** [comment]
I am the other person, I tested this in docker so i had a clean environment. https://registry.hub.docker.com/u/romster/crux-base/

**Comment by saghul** [comment]
I think this a false positive. What that test does is setuid to root and then try to execute a  subprocess. What user are you running your tests with?

**Comment by Greduan** [comment]
@saghul I'm running it with a normal user, not root. The user does have sudo access though.

I imagine it's the same with a friend but from his log it seems like he's running into an error *way* earlier.

**Comment by saghul** [comment]
Hum. No idea... can you print the value or 'r'?

**Comment by Greduan** [comment]
@saghul How do you mean? sorry

**Comment by saghul** [comment]
The 2 failing tests have an assert checking if "r" is UV_EPERM, can you print it before the assert so we see what result you got?

Assertion failed in test/test-spawn.c on line 1092: r == UV_EPERM
Assertion failed in test/test-spawn.c on line 1123: r == UV_EPERM

**Comment by Greduan** [comment]
Actually I just did:

```
git clone https://github.com/libuv/libuv/
cd libuv/
sh autogen.sh
./configure
make
make check
```

And all the tests passed. Which leads me to believe that the error happens because of this line in my Pkgfile:

```
	./configure --prefix=/usr \
		--libexecdir=/usr/lib \
		--mandir=/usr/man
```

Are some of those lines redundant?

**Comment by Greduan** [comment]
Modified Pkgfile to only have a plain `./configure` and see if the tests pass...

**Comment by Greduan** [comment]
Ah interesting. Running it with just a plain `./configure` makes 4 tests fail.

However, because of good practices when compiling the package using `pkgmk` I usually use `fakeroot pkgmk`, again because of good practices. That causes errors.

If I run it without fakeroot the tests pass without any problems.

Perhaps libuv has a problem with compiling as root? Or it could be because the test acts with root access even though fakeroot doesn't give it any access, it just makes it think it's root.

Worth checking out I guess...

**Comment by Greduan** [comment]
I ran a couple other tests with and without fakeroot and yes it seems what's causing the problem is fakeroot.

Still, would you like the values of  `r`?

**Comment by saghul** [comment]
> Perhaps libuv has a problem with compiling as root? Or it could be because the test acts with root access even though fakeroot doesn't give it any access, it just makes it think it's root.
> 
> Worth checking out I guess...

It's probably this. Doing setuid should fail in that test, but fakeroot probably makes it succeed, as you said.

**Comment by Greduan** [comment]
Should I close this? My friend gets different errors, BTW.
