### ISSUE TITLE
Unable to compile for iOS on macOS with Xcode

### ISSUE THREAD

**Issue by ssrlive** [libuv/libuv#2638]
Can not compile it because of the following lines.

https://github.com/libuv/libuv/blob/7a914e7f3d3d53ccbde50d0933cbaf576720c24e/src/unix/core.c#L536-L542

Since there NO `close$NOCANCEL$UNIX2003` function in iOS SDK, can we changed the first line to `#if defined(__LP64__) || defined(TARGET_OS_IPHONE)`? likes:
```
#if defined(__LP64__) || defined(TARGET_OS_IPHONE)
  extern int close$NOCANCEL(int);
  return close$NOCANCEL(fd);
#else
  extern int close$NOCANCEL$UNIX2003(int);
  return close$NOCANCEL$UNIX2003(fd);
#endif
```

**Comment by saghul** [comment]
Mind sending a PR?

**Comment by ssrlive** [comment]
Done #2639
