### ISSUE TITLE
Feature: setting IPv6 Flow Label

### ISSUE THREAD

**Issue by jasnell** [libuv/libuv#2647]
For both uv_tcp_t and uv_udp_t, it would be helpful to have an API for setting the IPv6 flow label (field sin6_flowinfo on sockaddr_in6). The immediate use case for me is a part of the QUIC implementation. 

Per the QUIC-24 spec (sorry, it's a PDF snippet)

![image](https://user-images.githubusercontent.com/439929/73027117-aac50600-3de7-11ea-9682-354eeb55b877.png)

An API like the following would be helpful.

```c
uv_tcp_set_flow_label(uv_tcp_t* handle, const uint8_t* label, size_t len)
uv_udp_set_flow_label(uv_udp_t* handle, const uint8_t* label, size_t len)
```

**Comment by bnoordhuis** [comment]
You can already set `.sin6_flowinfo` when you call `uv_tcp_bind()` or `uv_udp_bind()`, can't you?

**Comment by jasnell** [comment]
That's been unclear to me actually and the docs weren't helpful ;-) It's not clear *how* to do so.

**Comment by jasnell** [comment]
The QUIC requirements also suggest that it is necessary to be able to set the flow label independently of the bind operation. That is, with QUIC, the destination CID is not known until well *after* the UDP port has been bound, and in fact may (and likely would) change through the course of a QUIC connection, thereby requiring that the flow label would change.

So it's just not clear to me exactly how this should work with the libuv api. Suggestions welcome :-)

**Comment by bnoordhuis** [comment]
> It's not clear how to do so.

You pass in a `struct sockaddr_in6 *` cast to `struct sockaddr *`. In the `struct sockaddr_in6`, you set the `sin6_flowinfo` field to whatever you want.

It's a `uint32_t` for all practical purposes so you'd e.g. compute the sha256 hash of the things mentioned in the PDF and then take the first or last four bytes.

Caveat emptor though, the flow label field in the IPv6 packet header is only 20 bits, not 32 bits.

> with QUIC, the destination CID is not known until well after the UDP port has been bound, and in fact may (and likely would) change

Okay, so this is specific to UDP? In that case you pass a `struct sockaddr_in6` to `uv_udp_send()` or `uv_udp_try_send()`.

That won't work for TCP handles (`sendmsg(2)` with a custom `msghdr.msg_name` field is not a thing with connection-oriented protocols) but you can pass it to `uv_tcp_connect()`.

**Comment by jasnell** [comment]
Yep, with regards to QUIC it's absolutely specific to UDP... and WRT setting it only on the destination addr in `uv_udp_send()`, awesome, it really isn't clear that's where it needed to be set so that works perfectly. Thank you.
