### ISSUE TITLE
Big uv_async performance downgrade on single core linux  after upgrade to version >= libuv-1.29.0

### ISSUE THREAD

**Issue by frankfoxy** [libuv/libuv#2651]
I use libuv on ARM board with single Cortex-A7 processor, and found performance downgrade about 40% after upgrade from libuv-1.23.0 to the latest 1.34.2.

After check out and try each version in the repo, I found this commit #2231 (belongs to version 1.29.0) causes the performance downgrade on my single-core system.

I guess that the spin-wait in uv__async_io may downgrade the performance when other threads invoke uv_async_send too often, especially on the single-core system.

I modify the [repo test case](https://gist.github.com/josephg/d646cc4fdbb89ff0a19ec6c5c5550969) related with #2231, and publish [a new test case](https://gist.github.com/frankfoxy/55df6297535b3712b97aa7cf5990a7b6) to reproduce the issue.

I also provide [a patch](https://gist.github.com/frankfoxy/4b549e612ed83a10ec99f973ed720a19) on this issue (not use spin-wait in uv__async_io, only spin-wait in uv__async_close). 

I run [the test case](https://gist.github.com/frankfoxy/55df6297535b3712b97aa7cf5990a7b6) with released libuv-1.34.2 and libuv-1.34.2 with my patch on the arm board. Following is the output:

```
// this is the output of case with libuv-1.34.2
 uv_send_async benchark @ handler keepalive
net thread running
completed 733 iterations [speed: 0.00 iter/sec]
completed 1468 iterations [speed: 147.00 iter/sec]
completed 2206 iterations [speed: 147.60 iter/sec]
^C
```

```
// this is the output of case with libuv-1.34.2 and the patch
root@arm-linux:data[130]# ./test_uv_async2_1.34.2_patched
 uv_send_async benchark @ handler keepalive
net thread running
completed 84455 iterations [speed: 0.00 iter/sec]
completed 167741 iterations [speed: 16657.20 iter/sec]
completed 251791 iterations [speed: 16810.00 iter/sec]
^C
```
There's 100x speed difference, could somebody help to confirm this issue? @bnoordhuis

Thanks
 
ZY

* **Version**: >=1.29.0
* **Platform**: Linux arm-linux 3.10.104 armv7l GNU/Linux

**Comment by bnoordhuis** [comment]
Can you open a pull request with your changes? The general shape looks okay to me but I see some issues with it that are easier to comment on inline.

FWIW, I was quite surprised to find there was no discernible performance difference on x86_64 after #2231. That other architectures didn't fare so well is something I could've expected, I suppose. :-)

**Comment by frankfoxy** [comment]
I use virtual machine to emulate single-core environment on PC and also reproduced this issue.

uname of the VM is :
`inux osboxes 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

the output is as following:
```
// 1.34.2 without patch
uv_send_async benchark @ handler keepalive
net thread running
completed 1838 iterations [speed: 0.00 iter/sec] 
completed 3688 iterations [speed: 370.00 iter/sec] 
completed 5590 iterations [speed: 380.32 iter/sec] 
completed 7702 iterations [speed: 422.32 iter/sec] 
^C
```

```
// 1.34.2 with patch
 uv_send_async benchark @ handler keepalive
net thread running
completed 693412 iterations [speed: 0.00 iter/sec] 
completed 1388346 iterations [speed: 138986.80 iter/sec] 
completed 2107335 iterations [speed: 143797.80 iter/sec] 
completed 2843914 iterations [speed: 147198.04 iter/sec] 
completed 3598366 iterations [speed: 150890.40 iter/sec] 
```

about 400x performance difference

**Comment by frankfoxy** [comment]
> Can you open a pull request with your changes? The general shape looks okay to me but I see some issues with it that are easier to comment on inline.
> 
> FWIW, I was quite surprised to find there was no discernible performance difference on x86_64 after #2231. That other architectures didn't fare so well is something I could've expected, I suppose. :-)

PR is submitted, please check #2652

**Comment by bnoordhuis** [comment]
a9d9d4e stands a pretty good chance of fixing this. Let me know if you're still experiencing issues.
