### ISSUE TITLE
improve debug capability when testing Cygwin

### ISSUE THREAD

**Issue by matzeri** [libuv/libuv#2659]
This a feature request regarding testing.

Currently it is very hard to debug test failures of libuv on Cygwin
as GDB does not follow child so any break requested near the failure 
or assert point is not effective.

https://cygwin.com/ml/cygwin/2019-12/msg00311.html

It will be simpler to debug if every test has it own binary without any fork.

**Comment by saghul** [comment]
Are you trying to debug a specific test? You can do so by passing the test name twice to the test executable: ./run-tests test-foo test-foo

This way there will be no forking.

**Comment by bnoordhuis** [comment]
What Saúl said. Some tests have helpers that run in separate processes (but most don't.)

You can find them in test/test-list.h:
```
$ grep tcp_ping_pong_vec test/test-list.h 
TEST_DECLARE   (tcp_ping_pong_vec)
  TEST_ENTRY  (tcp_ping_pong_vec)
  TEST_HELPER (tcp_ping_pong_vec, tcp4_echo_server)

$ out/Debug/run-tests tcp_ping_pong_vec tcp4_echo_server &
[1] 6880

$ out/Debug/run-tests tcp_ping_pong_vec tcp_ping_pong_vec
# ...

$ fg
out/Debug/run-tests tcp_ping_pong_vec tcp4_echo_server
```
