### ISSUE TITLE
uv_read_start / stop cross-platform consistency

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#266]
See discussion in https://github.com/libuv/libuv/commit/873b02607c8dd29e7dd8918d661dbd734fc180f6#commitcomment-10179989

**Comment by vtjnash** [comment]
IIRC, there's been some developments in this area since 2015. Anyone know if this was addressed or has another issue/PR working on it?

**Comment by saghul** [comment]
I don't think the Windows "limitation" of being able to call start multiple times was addressed.
