### ISSUE TITLE
uv_fs_mkdir returns UV_ENOENT rather than UV_ENOTDIR on Windows

### ISSUE THREAD

**Issue by bcoe** [libuv/libuv#2661]
When you call `us_fs_mkdir` on a nested file path, e.g.,

```
vcbuild.bat/foo/bar
```

Where `vcbuild.bat` is a file and not a directory, OSX/Linux returns `ENOTDIR`:

```
 errno: -20,
 syscall: 'mkdir',
 code: 'ENOTDIR',
 path: 'vcbuild.bat/foo/bar'
```

whereas Windows 2012 Server edition returns:

```
 errno: -4058,
 syscall: 'mkdir',
 code: 'ENOENT',
 path: 'vcbuild.bat/foo/bar'
```

This is resulting in some slight inconsistencies in how errors are reported in Node.js' recursive mkdir behavior, see: https://github.com/nodejs/node/pull/31607

* **Version**: 1.34.2
* **Platform**:  Windows Server 2012 64 Bit

**Comment by musm** [comment]
Does this only occur on Windows 2012? Or do you also get this on newer versions of Windows 10.

**Comment by bcoe** [comment]
@musm I'm not sure what VM I was using when I opened this. Having landed our work around `mkdir` recursive, I haven't seen many complaints about this issue, let's close unless this crops up again in the future.
