### ISSUE TITLE
2 jpg images contain propriatry ICC profiles

### ISSUE THREAD

**Issue by dod38fr** [libuv/libuv#2670]
* **Version**: 1.34.2
* **Platform**: all

Hello

While reviewing copyright information to package new version for Debian, I've noticed that 2 files contain proprietary ICC profile information:
```
$ for i in $(find . -name *.jpg); do echo $i; exiftool $i | grep Profile; done
./docs/src/static/diagrams.key/preview-web.jpg
./docs/src/static/diagrams.key/Data/st0-311.jpg
Profile CMM Type                : Linotronic
Profile Version                 : 2.1.0
Profile Class                   : Display Device Profile
Profile Connection Space        : XYZ
Profile Date Time               : 1998:02:09 06:49:00
Profile File Signature          : acsp
Profile Creator                 : Hewlett-Packard
Profile ID                      : 0
Profile Copyright               : Copyright (c) 1998 Hewlett-Packard Company
Profile Description             : sRGB IEC61966-2.1
./docs/src/static/diagrams.key/Data/st1-475.jpg
Profile CMM Type                : Linotronic
Profile Version                 : 2.1.0
Profile Class                   : Display Device Profile
Profile Connection Space        : XYZ
Profile Date Time               : 1998:02:09 06:49:00
Profile File Signature          : acsp
Profile Creator                 : Hewlett-Packard
Profile ID                      : 0
Profile Copyright               : Copyright (c) 1998 Hewlett-Packard Company
Profile Description             : sRGB IEC61966-2.1
./docs/src/static/diagrams.key/preview.jpg
./docs/src/static/diagrams.key/preview-micro.jpg
```

According to [this](http://www.gballard.net/psd/save_for_web_embed_ICC_profile.html), embedding a color profile in a image is not necessary when color accuracy is not important.

I'd suggest to strip the profile from these image with `convert -strip` from imagemagick:
```
convert -strip docs/src/static/diagrams.key/Data/st0-311.jpg docs/src/static/diagrams.key/Data/st0-311.jpg
convert -strip docs/src/static/diagrams.key/Data/st1-475.jpg docs/src/static/diagrams.key/Data/st1-475.jpg
```
This would get libuv1 rid of some proprietary data.

All the best

**Comment by saghul** [comment]
Wow, I had no idea about that! IIRCC those images come with the keynote presentation, we didn't necessarily embed them.

Any chance you could submit a Pull Request?

**Comment by dod38fr** [comment]
I'm on it ...

**Comment by TexaSean** [comment]
> * **Version**: 1.34.2
> * **Platform**: all
> 
> Hello
> 
> While reviewing copyright information to package new version for Debian, I've noticed that 2 files contain proprietary ICC profile information:
> 
> ```
> $ for i in $(find . -name *.jpg); do echo $i; exiftool $i | grep Profile; done
> ./docs/src/static/diagrams.key/preview-web.jpg
> ./docs/src/static/diagrams.key/Data/st0-311.jpg
> Profile CMM Type                : Linotronic
> Profile Version                 : 2.1.0
> Profile Class                   : Display Device Profile
> Profile Connection Space        : XYZ
> Profile Date Time               : 1998:02:09 06:49:00
> Profile File Signature          : acsp
> Profile Creator                 : Hewlett-Packard
> Profile ID                      : 0
> Profile Copyright               : Copyright (c) 1998 Hewlett-Packard Company
> Profile Description             : sRGB IEC61966-2.1
> ./docs/src/static/diagrams.key/Data/st1-475.jpg
> Profile CMM Type                : Linotronic
> Profile Version                 : 2.1.0
> Profile Class                   : Display Device Profile
> Profile Connection Space        : XYZ
> Profile Date Time               : 1998:02:09 06:49:00
> Profile File Signature          : acsp
> Profile Creator                 : Hewlett-Packard
> Profile ID                      : 0
> Profile Copyright               : Copyright (c) 1998 Hewlett-Packard Company
> Profile Description             : sRGB IEC61966-2.1
> ./docs/src/static/diagrams.key/preview.jpg
> ./docs/src/static/diagrams.key/preview-micro.jpg
> ```
> 
> According to [this](http://www.gballard.net/psd/save_for_web_embed_ICC_profile.html), embedding a color profile in a image is not necessary when color accuracy is not important.
> 
> I'd suggest to strip the profile from these image with `convert -strip` from imagemagick:
> 
> ```
> convert -strip docs/src/static/diagrams.key/Data/st0-311.jpg docs/src/static/diagrams.key/Data/st0-311.jpg
> convert -strip docs/src/static/diagrams.key/Data/st1-475.jpg docs/src/static/diagrams.key/Data/st1-475.jpg
> ```
> 
> This would get libuv1 rid of some proprietary data.
> 
> All the best

Hey, yes im the guy who asks questions on comments years later. I was wondering if you could tell me exactly what this means? Specifically this "Copyright (c) 1998 Hewlett-Packard Company", my question has nothing to do with your discussion, I am just a guy with way too much time on his hands, and was researching a photograph I found, and that exact same line was written within the Metadata, I have never come across it before, and this comment you made came up in my search for more info. I hope I am not breaking any rules or intruding in any way, just looking for an answer to something that driving me crazy. I am pretty sure the image I am looking at has nothing to do with the two .jpg you are discussing, and that has me even more curious as to the meaning of this line in the metadata.  Thanks!

**Comment by saghul** [comment]
I II think it was some kind of stock image that Keynote embedded in the key file.

**Comment by dod38fr** [comment]
>  I was wondering if you could tell me exactly what this means? Specifically this "Copyright (c) 1998 Hewlett-Packard Company", 

This question highlights not a technical, but a legal problem. According to the copyright above, the color profile is owned by HP and there's no mention of a license that authorize its usage in libuv. Hence this request to remove it.

See https://opensource.stackexchange.com/questions/297/whats-the-difference-between-copyright-and-licensing for more info on this legal topic.

**Comment by saghul** [comment]
It was already removed.

**Comment by TexaSean** [comment]
Thanks for answering so quick, I thought I would be waiting a year or so. Let me ask another weird question, is there any chance I could see what .jpg images the original post was about?

**Comment by saghul** [comment]
Checkout the tag of the originally reported version, they should still be there.
