### ISSUE TITLE
Building libuv in nixpkgs on darwin fails during tests

### ISSUE THREAD

**Issue by basvandijk** [libuv/libuv#2675]
More details in: https://github.com/NixOS/nixpkgs/issues/79331

* **Version**: `1.34.1`, `1.34.2` and `master` (https://github.com/libuv/libuv/commit/24d73d065ff3ae43f63db87901dcea64cc504527). 
* **Platform**: 
```
uname -a
Darwin bassbox 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
```

**Comment by santigimeno** [comment]
Adding the output of the error: 
```
not ok 294 - udp_send_unix
# exit code 6
# Output from process `udp_send_unix`:
# Assertion failed in test/test-udp-open.c on line 325: 0 == bind(fd, (const struct sockaddr*)&addr, sizeof addr)
```

 @basvandijk  can you modify the test to print the return value of the `bind()` call?

**Comment by basvandijk** [comment]
I ran `nix-build -A libuv --check` on my macbook again and it suddenly passed the test suite. So I think some flakiness is going on or maybe I'm clicking "Allow" quickly enough on these firewall popups.

I tried printing the return value of `bind()`:

```diff
diff --git a/test/test-udp-open.c b/test/test-udp-open.c
index dee408ba..854a5ac7 100644
--- a/test/test-udp-open.c
+++ b/test/test-udp-open.c
@@ -322,7 +322,9 @@ TEST_IMPL(udp_send_unix) {
   ASSERT(fd >= 0);

   unlink(TEST_PIPENAME);
-  ASSERT(0 == bind(fd, (const struct sockaddr*)&addr, sizeof addr));
+  int b = bind(fd, (const struct sockaddr*)&addr, sizeof addr);
+  fprintf(stderr, "bind(...) = %i\n", b);
+  ASSERT(0 == b);
   ASSERT(0 == listen(fd, 1));

   r = uv_udp_init(loop, &handle);
```

However, I don't see its output when building the package:

```
$ nix-build -A libuv
...
ok 293 - udp_send_immediate
ok 294 - udp_send_unix
ok 295 - udp_send_unreachable
...
PASS: test/run-tests
=============
1 test passed
=============
...
/nix/store/307h6wyidrsbbgvckra8937hix7mv5h1-libuv-1.34.1
```

**Comment by santigimeno** [comment]
Not sure what happened, it might be a permissions issue with `TEST_PIPENAME` path.

> However, I don't see its output when building the package:

Yes, this is expected. The output is only printed if the test fails.

**Comment by basvandijk** [comment]
I'm pretty sure it has to do with the system's firewall. When I run the test and click in the [popup](https://github.com/NixOS/nixpkgs/issues/79331) on "Allow" quickly enough the test succeeds. When I click "Deny" or don't click at all the test fails.

**Comment by basvandijk** [comment]
Note that `libuv`'s Nix expression has [`__darwinAllowLocalNetworking` set](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libuv/default.nix#L65). This should allow the build to access the local network.

**Comment by basvandijk** [comment]
It also fails in another test now:

```
not ok 279 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
```

**Comment by santigimeno** [comment]
> not ok 279 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)

This one is usually a firewall issue.

**Comment by basvandijk** [comment]
RIght. After setting some print statements I see the `udp_multicast_join` test doesn't get passed [this line](So https://github.com/libuv/libuv/blob/24d73d065ff3ae43f63db87901dcea64cc504527/test/test-udp-multicast-join.c#L173) then timeouts:

```
  /* run the loop till all events are processed */
  uv_run(uv_default_loop(), UV_RUN_DEFAULT);
```
 
This is when I deny incoming connections to the test.

**Comment by basvandijk** [comment]
Another interesting observation. When I neither click on "Allow" nor "Deny" more tests fail:

```
...
not ok 279 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
ok 280 - udp_multicast_join6
ok 281 - udp_multicast_ttl
ok 282 - udp_no_autobind
ok 283 - udp_open
ok 284 - udp_open_bound
not ok 285 - udp_open_connect
# exit code 6
# Output from process `udp_open_connect`: (no output)
Output from process `udp_open_connect`:
# Assertion failed in test/test-udp-open.c on line 278: r == 0
ok 286 - udp_open_twice
not ok 287 - udp_options
# exit code 6
# Output from process `udp_options`:
# Assertion failed in test/test-udp-options.c on line 44: r == 0
ok 288 - udp_options6
ok 289 - udp_ref
ok 290 - udp_ref2
ok 291 - udp_ref3
not ok 292 - udp_send_and_recv
# exit code 6
# Output from process `udp_send_and_recv`:
# Assertion failed in test/test-udp-send-and-recv.c on line 172: r == 0
not ok 293 - udp_send_immediate
# exit code 6
# Output from process `udp_send_immediate`:
# Assertion failed in test/test-udp-send-immediate.c on line 109: r == 0
ok 294 - udp_send_unix
ok 295 - udp_send_unreachable
not ok 296 - udp_try_send
# exit code 6
# Output from process `udp_try_send`:
# Assertion failed in test/test-udp-try-send.c on line 93: r == 0
ok 297 - uname
ok 298 - unref_in_prepare_cb
ok 299 - utf8_decode1
ok 300 - walk_handles
ok 301 - watcher_cross_stop
ok 302 - we_get_signal
ok 303 - we_get_signal_one_shot
ok 304 - we_get_signals
ok 305 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
```

I'm not sure why it mentioned that only 1 test failed because I see multiple "not ok"s.

**Comment by santigimeno** [comment]
> I'm not sure why it mentioned that only 1 test failed because I see multiple "not ok"s.

Yeah, that's quirk of the test suite. Whether 1 or multiple tests fail it always returns that.

Isn't it possible for you to give those permissions permanently to the `run-tests` executable to avoid these issues?

**Comment by basvandijk** [comment]
> Yeah, that's quirk of the test suite. Whether 1 or multiple tests fail it always returns that.

Ok good to know.

> Isn't it possible for you to give those permissions permanently to the run-tests executable to avoid these issues?

Maybe I could, I'll do some reading. I'm not sure how to refer to the `run-tests` executable though because it's stored in a constantly changing temporary build directory, i.e. its absolute path changes for every nix-build.

But the real issue is not on my laptop. I have a build farm in a data center containing a bunch of headless Macs. I first noticed the build failure on them. When I now run the build in the DC I get the following errors:

```
not ok 42 - fs_event_error_reporting
# timeout
# Output from process `fs_event_error_reporting`: (no output)
...
not ok 111 - hrtime
# timeout
# Output from process `hrtime`: (no output)
```

Do you folks also notice this much flakiness when running the test suite in your CI?

**Comment by basvandijk** [comment]
Note BTW that the Mac in the DC has its firewall disabled:

```
$ sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
Firewall already disabled
```

**Comment by santigimeno** [comment]
> Do you folks also notice this much flakiness when running the test suite in your CI?

Not really, it's mostly green.

```
not ok 42 - fs_event_error_reporting
# timeout
# Output from process `fs_event_error_reporting`: (no output)
```

This one has been fixed [recently](https://github.com/libuv/libuv/commit/c8a3f5c93c0bd10c82bd4c4fb57886bd62fde0fb). If you run it with current master it should have that fix in.

```
not ok 111 - hrtime
# timeout
# Output from process `hrtime`: (no output)
```
This one has been flaky in the past and if IIRC it's very much time dependent so on certain conditions it might fail.

**Comment by santigimeno** [comment]
> If you run it with current master it should have that fix in.

I meant current `v1.x`

**Comment by basvandijk** [comment]
> This one has been fixed [recently](https://github.com/libuv/libuv/commit/c8a3f5c93c0bd10c82bd4c4fb57886bd62fde0fb). If you run it with current master it should have that fix in.

That's great! Then I'll just patch the version in nixpkgs with that [patch](https://github.com/libuv/libuv/commit/c8a3f5c93c0bd10c82bd4c4fb57886bd62fde0fb.patch) until you folks publish a new release with that commit included.

> This one has been flaky in the past and if IIRC it's very much time dependent so on certain conditions it might fail.

Then I'll go ahead and disable the `hrtime` test in nixpkgs.

**Comment by santigimeno** [comment]
@basvandijk I've noticed that commit was already published in `1.34.2`. Was that version already failing for you?

**Comment by basvandijk** [comment]
> @basvandijk I've noticed that commit was already published in 1.34.2. 

Great.

> Was that version already failing for you?

No [`nixpkgs` has 1.34.1](https://github.com/NixOS/nixpkgs/blob/c4402ea388b3b2e2af709e72d53544696958417e/pkgs/development/libraries/libuv/default.nix#L4). I'll update it to 1.34.2.

**Comment by basvandijk** [comment]
I can confirm that the following fixes my issue:
https://github.com/NixOS/nixpkgs/pull/79372

**Comment by santigimeno** [comment]
I guess this can be closed now. @basvandijk feel free to re-open if that's not the case
