### ISSUE TITLE
Builds on slow arch need a way to disable timing sensitive tests

### ISSUE THREAD

**Issue by dod38fr** [libuv/libuv#2678]
* **Version**: 1.34.2
* **Platform**: Linux 4.19.0-6-loongson-3 SMP PREEMPT Debian 4.19.67-2+deb10u2 (2019-11-11) mipsel (mips64)

Hi

`tcp_writealot` test often fails on timeout while building on Debian mipsel ([see build log](https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=mipsel&ver=1.34.2-1&stamp=1581089155&file=log)).

Could you setup a test option (or an environment variable) to disable time-sensitive tests ? So that only (more) robust tests would be run on Debian (or other) build systems ? (See #1615 #1744 for similar issues)

All the best

Dod (for Debian)

**Comment by bnoordhuis** [comment]
I don't think disabling them entirely is a good idea but can you check if #2679 works for you?
