### ISSUE TITLE
uv_fs_statfs fails for paths to files on Windows

### ISSUE THREAD

**Issue by SheikhSajid** [libuv/libuv#2683]
uv_fs_statfs does not work on Windows if the path passed to it points to a file. However, it works for directory or root paths. This is not consistent with Unix statfs.

This is happening because on Windows uv_fs_statfs is using [GetDiskFreeSpaceW](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdiskfreespacew), which only accepts a _root directory_ path as input (according to the docs). It seems to be working with _regular directory_ paths as well on my Windows 10 Pro machine, but fails for paths to files.

`uv_fs_statfs(loop, req, "C:\\", cb); // works for root directories`
`uv_fs_statfs(loop, req, "C:\\path\\to\\directory", cb); // works for regular directories`
`uv_fs_statfs(loop, req, "C:\\path\\to\\file.ext", cb); // fails for files`

Refs: https://github.com/nodejs/node/pull/31351#pullrequestreview-344860172

* **Version**: 1.34.2
* **Platform**: Windows 10 x86-64

**Comment by cjihrig** [comment]
I'm not sure if there is a better way to do it on Windows, but libuv could detect the error and retry with the directory portion (`GetFullPathNameW()` could help there). Alternatively, we could always try to detect the directory portion first.

**Comment by erw7** [comment]
I've tried, but `uv_fs_statfs()` succeeds with:

```C
uv_fs_statfs(loop, req, "\\\\?\\C:\\Windows\\", cb);
uv_fs_statfs(loop, req, "\\\\192.168.1.xxx\\C$\\Windows\\", cb);
uv_fs_statfs(loop, req, "..\\", cb);
```

So what if we try again in the parent directory if it fails?

**Comment by SheikhSajid** [comment]
Extracting the parent directory from the path could work but Microsoft's doc says that the GetDiskFreeSpaceW function only accepts the root directory of a disk. Not sure if passing the parent instead of the root will work on all versions of windows.

**Comment by cjihrig** [comment]
> So what if we try again in the parent directory if it fails?

I think we're suggesting the same thing.

> Not sure if passing the parent instead of the root will work on all versions of windows.

I'm not sure either.
