### ISSUE TITLE
ibmi: failed test case poll_duplex & poll_unidirectional

### ISSUE THREAD

**Issue by dmabupt** [libuv/libuv#2698]
* **Version**: all
* **Platform**: ibmi

They are the last two failed test cases on IBMi PASE.

Debugging shows below code related to the errors --
https://github.com/libuv/libuv/blob/v1.x/test/test-poll.c#L221-L237
https://github.com/libuv/libuv/blob/v1.x/test/test-poll.c#L296-L316

I added some traces in the action 0&1 code and found the `Connection reset by peer` error happened in recv() every time when the received bytes exceeds 256.

```
not ok 1 - poll_duplex
# exit code 393350
# Output from process `poll_duplex`:
# write bytes(0)
# write bytes(103)
# read bytes(0)
# write bytes(0)
# read bytes(0)
# write bytes(206)
# read bytes(74)
# write bytes(103)
# read bytes(74)
# write shutdown (0)
# read bytes(148)
# write bytes(206)
# read bytes(222)
# write shutdown (0)
# read bytes(148)
# read bytes(222)
# read bytes(256)
# read error: Connection reset by peer
# Assertion failed in ../test/test-poll.c on line 228: r >= 0
```

I tried to write a simplified C program to recreate the issue but failed.  Currently I have to skip action 0&1 on IBMi PASE.

Could someone give me some clue how to find the root cause?

**Comment by bnoordhuis** [comment]
I don't know if they're the cause of the failures you're seeing but I spotted at least two bugs in the test. Can you see if #2713 helps?

**Comment by dmabupt** [comment]
> I don't know if they're the cause of the failures you're seeing but I spotted at least two bugs in the test. Can you see if #2713 helps?

Unfortunately it does not fix the failure on IBMi. 

Seems the failure related to the different [shutdown()](https://github.com/libuv/libuv/blob/v1.x/test/test-poll.c#L404) behavior. In PASE, when the socket has been `shutdown()`, API `recv()` showed `Connection reset by peer` error. But on some other platform, there is no such an error.
This error makes [this assertion](https://github.com/libuv/libuv/blob/v1.x/test/test-poll.c#L229) failed,  and the `context->got_fin` flag can not be set.

Detailed trace --
```
not ok 1 - poll_duplex
# exit code 393350
# Output from process `poll_duplex`:
# socket(11) [0]sent [0]received. now send (103) bytes, isServer(0)
# socket(11) [103]sent [0]received. now send (103) bytes, isServer(0)
# socket(12) [0]sent [0]received. now recv (74) bytes, isServer(1)
# socket(12) [0]sent [74]received. now send (103) bytes, isServer(1)
# socket(11) [206]sent [0]received. now recv (74) bytes, isServer(0)
# socket(11) [206]sent [74]received. now send (50) bytes, isServer(0)
# socket(12) [103]sent [74]received. now recv (74) bytes, isServer(1)
# socket(12) [103]sent [148]received. now send (103) bytes, isServer(1)
# socket(11) [256]sent [74]received. now recv (74) bytes, isServer(0)
#  -- nothing to send, shutdown socket (11)
# socket(12) [206]sent [148]received. now recv (74) bytes, isServer(1)
# socket(12) [206]sent [222]received. now send (50) bytes, isServer(1)
# socket(12) [256]sent [222]received. now recv (34) bytes, isServer(1)
#  -- nothing to send, shutdown socket (12)
# socket(11) [256]sent [148]received. now recv (74) bytes, isServer(0)
# socket(11) [256]sent [222]received. now recv (34) bytes, isServer(0)
# socket(12) [256]sent [256]received. now recv (-1) bytes, isServer(1)
# recv() failed: Connection reset by peer
# Assertion failed in ../test/test-poll.c on line 231: r >= 0
```

**Comment by dmabupt** [comment]
Based on the document https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/apis/shutdn.htm , we may skip these tests on IBM i -- 

> Issuing a shutdown() with a how parameter of 1 results in all output functions being failed with an error of [epipe]. The process issuing the output operation will receive a synchronous sigpipe signal. This also sends a normal **close** sequence to the partner program. Receive operations issued by the partner program receive a return value of 0 once all previous data has been received. If the socket is being shared across multiple processes or threads, any blocking output functions are deblocked with a return value of -1 and an error code of [epipe].

**Comment by dmabupt** [comment]
The PR has been laneded. We may reopen this when necessary.
