### ISSUE TITLE
unix,fs: returning error on partial writes

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#2699]
At the moment, `uv_fs_write()` returns success (as it should) when partial writes happen, but it'd be nice being able to also propagate the possible error returned by the `write()` syscall in some scenarios such as with `ENOSPC` so we can avoid an extra `write()` call by the library consumer. Also, not breaking the ABI would be a plus. Wdyt?

Refs: https://github.com/nodejs/node/issues/31908

**Comment by bnoordhuis** [comment]
I'm not sure what extra write() you mean. We don't know a partial write is going to be followed by ENOSPC until we try to write again.

**Comment by santigimeno** [comment]
If you look at the referenced example, calling `uv_fs_write()` with a size larger than the underlying disk space, results in 2 consecutive `write()` syscalls. A successful with with the partial write and a second one returning the `ENOSPC` error. If this `ENOSPC` error could be somehow returned, the consumer could avoid having to call `uv_fs_write()` again to retrieve the specific error. Does it make sense?

**Comment by vtjnash** [comment]
`uv_fs_write` shouldn't return until the content is fully written, or there's a repeatable error (https://github.com/libuv/libuv/pull/1742)

**Comment by santigimeno** [comment]
> uv_fs_write shouldn't return until the content is fully written, or there's a repeatable error

Sorry, I'm not sure I follow. That's the behaviour I'm observing with `ENOSPC`.

**Comment by bnoordhuis** [comment]
> A successful with with the partial write and a second one returning the ENOSPC error. If this ENOSPC error could be somehow returned, the consumer could avoid having to call uv_fs_write() again to retrieve the specific error.

Right, I'm following now. :-)

But then the libuv user won't know a partial write took place, right?

**Comment by santigimeno** [comment]
Yeah, the idea was, in the case of partial writes, trying to return both the number of bytes successfully written and the error in the `uv_fs_t` request. I don't know if there are some space there for an _error-on-partial-write_ field.

**Comment by bnoordhuis** [comment]
I don't think that can work. `req->result` is used to signal both errors and bytes written.

Besides, it's a rather big yet subtle change in behavior so I don't think it's a good idea even if it were possible to retain backwards ABI compatibility.

**Comment by santigimeno** [comment]
Probably I'm not explaining myself or I am talking nonsense but I'll try one last time and drop the issue as it hasn't any importance.
With what I have in mind, `req->result` would behave exactly the same, as it will return the number of bytes written. The only change would be adding a new field in `uv_fs_t` that would report the error that caused the partial write (as we already know it) and that the user could check to know what provoked that partial write.
