### ISSUE TITLE
PR# 2486 breaks Android builds

### ISSUE THREAD

**Issue by interj** [libuv/libuv#2702]
Hi, since https://github.com/libuv/libuv/pull/2486/commits/c4a9c2c7daffcad160c87e8528653c103a0d4f0c Android-28+ uses function `uv__random_getentropy`, but `src/unix/random-getentropy.c` is not built on Android and resulting library has an undefined reference.
I have tested it with android-ndk toolchain (27 works, 28+ does not link), but it looks like `src/unix/random-getentropy.c` isn't built by any buildsystem supposedly supporting Android.

* **Version**: 1.33+
* **Platform**: Android

**Comment by saghul** [comment]
What build system are you using, GYP? CMake?

**Comment by interj** [comment]
CMake, with Android-ndk 20

**Comment by bnoordhuis** [comment]
@interj Thanks for the report. Can you check that #2704 fixes the build for you?

**Comment by interj** [comment]
It fixes the problem, at least for CMake builds.
