### ISSUE TITLE
uv_get_process_title and uv_set_process_title should be MT-safe

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#271]
Proposal: I move that `uv_get_process_title()` and `uv_set_process_title()` should be safe to call from multiple threads without requiring explicit synchronization from the host program.

Rationale: synchronization might be difficult or impossible to orchestrate and it's not obvious that those functions require synchronization in the first place when e.g. uv_hrtime() does not.

I'm volunteering to do the work.

**Comment by saghul** [comment]
Sounds good, go for it :-)

**Comment by mtharrison** [comment]
I'm very interested in contributing to libuv. Any pointers on where to start with this? Is it just a case of using a mutex in those functions to ensure they can't be executed my multiple threads or am I vastly oversimplifying things?

**Comment by bnoordhuis** [comment]
@mtharrison Yes, a mutex would be a good first step.

**Comment by mtharrison** [comment]
If my understanding is correct `uv_get_process_title()` is ok to call concurrently from multiple threads as long as there's no concurrent `uv_set_process_title()` happening, so would a rwlock be more appropriate in this case?

**Comment by bnoordhuis** [comment]
Probably, but there are implementations for several platforms.  You'd have to look at each one individually.

Performance-wise, mutex vs. rwlock probably doesn't matter that much in practice since the critical section is small, and mutexes don't have writer starvation issues.
