### ISSUE TITLE
Can libuv listen to network changes in windows. Such as switching networks, disconnecting networks

### ISSUE THREAD

**Issue by meixi1203** [libuv/libuv#2711]
* **Version**: 
* **Platform**:

**Comment by meixi1203** [comment]
Can libuv listen to network changes in windows
Such as switching networks, disconnecting networks

**Comment by saghul** [comment]
Nope, sorry.

PS: Please use libuv/help for questions next time.

**Comment by meixi1203** [comment]
> Nope, sorry.
> 
> PS: Please use libuv/help for questions next time.

OK, thank you
