### ISSUE TITLE
warning: incompatible pointer types passing 'int (uv__dirent_t **, uv__dirent_t **)' (aka 'int (struct dirent **, struct dirent **)') to parameter of type 'int (*)(const struct dirent **, const struct dirent **)'

### ISSUE THREAD

**Issue by DeepakArora76** [libuv/libuv#2715]
Another category of warning. I am compiling for iOS 64 and 32 bit systems armv7 and arm64.

CompileC /Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/Objects-normal/armv7/fs.o /Users/dnasystems.io/Development/MetePoint/LibUV/src/unix/fs.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'libuv' from project 'uv')
    cd /Users/dnasystems.io/Development/MetePoint/LibUV
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target armv7-apple-ios8.0 -fmessage-length=362 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE=1 -D_DARWIN_UNLIMITED_SELECT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -fstrict-aliasing -Wdeprecated-declarations -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -fembed-bitcode-marker -iquote /Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/uv-generated-files.hmap -I/Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/uv-own-target-headers.hmap -I/Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/uv-all-target-headers.hmap -iquote /Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/uv-project-headers.hmap -I/Users/dnasystems.io/Development/MetePoint/LibUV/build/Release-iphoneos/include -Iinclude -Isrc -I/Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/DerivedSources-normal/armv7 -I/Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/DerivedSources/armv7 -I/Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/DerivedSources -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -F/Users/dnasystems.io/Development/MetePoint/LibUV/build/Release-iphoneos -g --std=gnu89 -MMD -MT dependencies -MF /Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/Objects-normal/armv7/fs.d --serialize-diagnostics /Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/Objects-normal/armv7/fs.dia -c /Users/dnasystems.io/Development/MetePoint/LibUV/src/unix/fs.c -o /Users/dnasystems.io/Development/MetePoint/LibUV/build/uv.build/Release-iphoneos/libuv.build/Objects-normal/armv7/fs.o
/Users/dnasystems.io/Development/MetePoint/LibUV/src/unix/fs.c:519:34: warning: incompatible pointer types passing 'int (uv__dirent_t *)' (aka 'int (struct dirent *)') to parameter of type 'int (*)(const struct dirent *)' [-Wincompatible-pointer-types]
  n = scandir(req->path, &dents, uv__fs_scandir_filter, uv__fs_scandir_sort);
                                 ^~~~~~~~~~~~~~~~~~~~~
In file included from /Users/dnasystems.io/Development/MetePoint/LibUV/src/unix/fs.c:29:
In file included from /Users/dnasystems.io/Development/MetePoint/LibUV/include/uv.h:66:
In file included from include/uv/unix.h:28:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/dirent.h:150:11: note: passing argument to parameter here
    int (*)(const struct dirent *), int (*)(const struct dirent **, const struct dirent **)) __DARWIN_INODE64(scandir);
          ^
/Users/dnasystems.io/Development/MetePoint/LibUV/src/unix/fs.c:519:57: warning: incompatible pointer types passing 'int (uv__dirent_t **, uv__dirent_t **)' (aka 'int (struct dirent **, struct dirent **)') to parameter of type 'int (*)(const struct dirent **, const struct dirent **)' [-Wincompatible-pointer-types]
  n = scandir(req->path, &dents, uv__fs_scandir_filter, uv__fs_scandir_sort);
                                                        ^~~~~~~~~~~~~~~~~~~
In file included from /Users/dnasystems.io/Development/MetePoint/LibUV/src/unix/fs.c:29:
In file included from /Users/dnasystems.io/Development/MetePoint/LibUV/include/uv.h:66:
In file included from include/uv/unix.h:28:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/dirent.h:150:43: note: passing argument to parameter here
    int (*)(const struct dirent *), int (*)(const struct dirent **, const struct dirent **)) __DARWIN_INODE64(scandir);

**Comment by bnoordhuis** [comment]
See the logic here:

https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L497-L511

The conditional define probably needs some tweaking for ios. PR welcome.

**Comment by DeepakArora76** [comment]
@bnoordhuis Thank you for your prompt reply.

Here is the fix to resolve the reported warning. Kindly create the PR on my behalf as I do not have necessary permissions(access rights) to push a new branch to origin.

```c
#if defined(__APPLE__) && defined(TARGET_OS_MAC) && !defined(TARGET_OS_IPHONE) && !defined(MAC_OS_X_VERSION_10_8)
#define UV_CONST_DIRENT uv__dirent_t
#else
#define UV_CONST_DIRENT const uv__dirent_t
#endif
```

**Comment by bnoordhuis** [comment]
Just fork the repo and create a branch in your fork, then PR that. :-)

**Comment by kencu** [comment]
have to be careful. TARGET_OS_IPHONE is actually defined to "0" on MAC.
