### ISSUE TITLE
Updated Windows CMake CI job

### ISSUE THREAD

**Issue by joaocgreis** [libuv/libuv#2728]
@libuv/collaborators 

I updated the Windows CMake job to include all Windows and Visual Studio versions available in CI. Please let me know if there's any issue.

First run: https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/1/

**Comment by cjihrig** [comment]
There have been a few runs now, and everything seems normal, so I'm going to close this issue. Thanks for the heads up though.
