### ISSUE TITLE
advapi32 module is not loaded

### ISSUE THREAD

**Issue by vekkuli** [libuv/libuv#2733]
Using sample code (e.g. docs\code\pipe-echo-server\main.c) in a fresh Visual Studio 2017 (Release x64 build) fails at runtime in src\win\winapi.c:
```
advapi32_module = GetModuleHandleA("advapi32.dll");
if (advapi32_module == NULL) {
  uv_fatal_error(GetLastError(), "GetModuleHandleA");
}
```
It seems that the advapi32 module is not loaded. Replacing `GetModuleHandleA` with `LoadLibraryA` seems to fix the issue in this case. The issue does not come up in provided tests. I'm not able to figure out what gets the module loaded in the tests project but not in my own Visual Studio project.

**Comment by bnoordhuis** [comment]
You need to link with the following libraries:
```
$ grep -A6 advapi32 uv.gyp 
              '-ladvapi32',
              '-liphlpapi',
              '-lpsapi',
              '-lshell32',
              '-luser32',
              '-luserenv',
              '-lws2_32'
```

**Comment by vekkuli** [comment]
All of those are included in the Additional Dependencies. Linking wouldn't pass without it. Or am I missing something even more explicit about the linker configuration?

**Comment by bnoordhuis** [comment]
Possibly, but I don't know what. :-)

You're the first one to bring this up, to the best of my knowledge, so it's probably something on your end but I'm not sure what.

cc @libuv/windows, just in case.

**Comment by vekkuli** [comment]
Just to further invalidate the issue: I only get the issue when cloning the repo and building the library from source—not when installing through vcpkg.

**Comment by bnoordhuis** [comment]
For triaging purposes, it might be helpful if you describe exactly how you clone the repo, create the project and build the sources.

**Comment by vekkuli** [comment]
I'm going to brush it as some quirk in my setup until someone else runs into the same problem.

**Comment by bnoordhuis** [comment]
Thanks for the heads-up. I'll close out the issue until further notice.
