### ISSUE TITLE
Tests passes on Debug and Release with VS2019 on x64

### ISSUE THREAD

**Issue by famastefano** [libuv/libuv#2740]
* **Version**: Release 1.34.2
* **Platform**: Windows 10
```
> [System.Environment]::OSVersion
 Win32NT 10.0.18363.0 Microsoft Windows NT 10.0.18363.0

> vswhere.exe
installationName: VisualStudio/16.4.6+29905.134
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
installationVersion: 16.4.29905.134
productId: Microsoft.VisualStudio.Product.Community
displayName: Visual Studio Community 2019
channelId: VisualStudio.16.Release
```

I just wanted to let you know that LibUV 1.34.2 can be built on VS2019 with CMake without any changes: `cmake ../.. -G "Visual Studio 16 2019" -A x64 -DBUILD_TESTING=ON`

Tests run successfully with Debug or Release configuration without any issue.

I've checked both Private and Public networks when the Firewall prompt showed up for both the tests uv_test and uv_test_a.

**Comment by bnoordhuis** [comment]
Thanks for the heads-up, Stefano! Much appreciated.
