### ISSUE TITLE
handle->name is not being passed correctly from uv_pipe_connect to pipe_connect_thread_proc

### ISSUE THREAD

**Issue by vasubabukandimalla** [libuv/libuv#2750]
* **Version**: 
* **Platform**: 
Version: 0.10.20
Platform: Windows 10

**Comment by vasubabukandimalla** [comment]
While using libuv version 0.10.20 on windows observed that pipe_name is correctly set to handle->name in uv_pipe_connect, but when WaitNamedPipeW call from pipe_connect_thread_proc generating core dump because handle->name is NULL.

**Comment by bnoordhuis** [comment]
The v0.10.x release line has been _long_ out of support. Try upgrading to the latest, v1.35.0.
