### ISSUE TITLE
ibmi:  isatty(55555) returns true on IBMi PASE

### ISSUE THREAD

**Issue by dmabupt** [libuv/libuv#2752]
* **Version**: v1.35.0
* **Platform**: IBM i

The issue was found in the failed test of Node.js --> [pseudo-tty/test-tty-isatty](https://github.com/nodejs/node/blob/master/test/pseudo-tty/test-tty-isatty.js#L12)
`AssertionError [ERR_ASSERTION]: 55555 reported to be a tty, but it is not`

On IBMi PASE, the libuv API `isatty` is implemented [as below](https://github.com/nodejs/node/blob/master/test/pseudo-tty/test-tty-isatty.js#L12) --
```
  if (!ioctl(file, TXISATTY + 0x81, NULL) || errno != ENOTTY)
    return UV_TTY;
```
The problem is the `errno != ENOTTY` part. When `fd = 55555`, the errno is not **ENOTTY** but **EBADF** (Bad file number) on IBMi PASE. Then the code return true and say it is a TTY.

I am wondering if the errno checking is necessary here?

**Comment by richardlau** [comment]
There was some discussion in https://github.com/libuv/libuv/pull/2565#discussion_r355158948 when the IBMi implementation was added.

**Comment by dmabupt** [comment]
> There was some discussion in [#2565 (comment)](https://github.com/libuv/libuv/pull/2565#discussion_r355158948) when the IBMi implementation was added.

Seems adding the check is not a good idea. @kadler , what is your opinion?

**Comment by kadler** [comment]
Let's refactor the ioctl call in to its own `isatty` function. That way the main codepath is the same for all POSIX platforms and we can implement the local static isatty function to implement the correct behavior wrt errno handling. Doing it inline will just make things more complicated.

**Comment by kadler** [comment]
Looking at the code for isatty, we definitely need to handle EBADF distinctly from other errno values.

**Comment by kadler** [comment]
I've created #2753 for this issue

**Comment by kadler** [comment]
@dmabupt can you test my changes with Node to see if the Node test fails. @richardlau should we add a similar test to libuv?

**Comment by richardlau** [comment]
> @richardlau should we add a similar test to libuv?

If it can be tested reliably I don't see why not.

**Comment by dmabupt** [comment]
> @dmabupt can you test my changes with Node to see if the Node test passes now?
> 
> @richardlau should we add a similar test to libuv?

PR #2753 has been tested. It works as expected. I will close this issue once the PR landed. Thanks.
