### ISSUE TITLE
 GetModuleHandleA("advapi32.dll") equals null

### ISSUE THREAD

**Issue by exellian** [libuv/libuv#2759]
Libuv 1.35 built on source with vs2017 option:
Windows 10 1904 (Build 18362.720):
On Visual Studio 2017 I link all the required libs:
ws2_32.lib
advapi32.lib
iphlpapi.lib
psapi.lib
shell32.lib
user32.lib
userenv.lib
libuv.lib
And I dont have a compile error, but for some reason GetModuleHandleA("advapi32.dll") returns null which leads to an fatal error in uv_winapi_init(), but only in Release mode of Visual Studio.
I already tried to reinstall Windows 10 SDK and also tried to manually set lib paths to advapi32.lib. But everything leads to the same error.

**Comment by bnoordhuis** [comment]
That sounds suspiciously like #2733. We never established the root cause there but #2748 might help.

**Comment by exellian** [comment]
Yes I already read this issue but the things described there didn't help.
Yesterday evening I found a workaround solution by calling LoadLibraryA("advapi32.dll") manually and it worked. But I don't know if I should really do it that way

**Comment by bnoordhuis** [comment]
You're saying debug builds work but release builds don't, unless you call LoadLibrary? Are you using the gyp or the cmake build?

Pure speculation on my part but perhaps the linker sees that libuv doesn't use anything from advapi32.lib directly (only through `GetProcAddress()` but the linker can't see that) and therefore drops it from libuv's list of dependencies?

I'll open a PR that switches to LoadLibrary for discussion.

**Comment by exellian** [comment]
1. I am using vcbuild.bat vs2017 to build libuv and vcbuild.bat release vs2017 for release.
2. That could be the root cause, but I don't really know either
3. Ok

**Comment by bnoordhuis** [comment]
@exellian Can you check if #2762 fixes the issue for you?

**Comment by exellian** [comment]
I rebuild it and did a tets run and everything seems working now! Thanks alot!
