### ISSUE TITLE
FR: ability to shutdown libuv manually

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2763]
If I try to write an extension for PHP, and I may use Zend Memory Manager, and the memory manager always exit before UV_DESTRUCTORS, unless Zend Memory Manager also use the `__attribute__((destructor))`
![image](https://user-images.githubusercontent.com/25978241/77927096-7daa3d80-72d9-11ea-96c5-37aa7fdddbc6.png)
![image](https://user-images.githubusercontent.com/25978241/77927250-a6323780-72d9-11ea-9aa2-1e94ccd6850f.png)

So I think that if it is possible to destruct these things through an API instead of compiler ways?
Otherwise we will never be able to use the memory pool that runs on user runtime.

_Originally posted by @twose in https://github.com/libuv/libuv/pull/2760#issuecomment-606051589_

**Comment by bnoordhuis** [comment]
@twose Can you check if #2764 suits your needs?

**Comment by twose** [comment]
@bnoordhuis Yes, Thank you for your efficient work!

**Comment by twose** [comment]
I found another problem, the design may not work in programs with multiple runtimes.
For example, the life cycle of a PHP program might look like this:
```php
module_init(); // memory pool init (now we can alloc persistent memory)
while (recv_request()) {
    runtime_init(); // now we can alloc runtime memory
    main();
    runtime_shutdown(); // runtime memory will be freed (includes memory leak detection)
   // but thread pool may use runtime memory after runtime_shutdown, and we can't shutdown it
}
module_shutdown(); // memory pool shutdown
```

of course, I can also use persistent memory
but I think we can init and shutdown multiple times (better design)

**Comment by bnoordhuis** [comment]
That'd be hard to support - it'd need a massive refactoring - and it'd probably be too slow for your use case anyway, if I understand it correctly.

Libuv has a lot of global state (threads, mutexes, init-once variables, etc.) that would need to be reinitialized every time. I'm not even sure if it'll work on all platforms.

If #2764 is sufficient for your needs, I'm happy to land that. Otherwise I'm going to close this out as a wontfix.

If you _really_ need this kind of load/unload behavior, you could experiment with loading/unloading libuv through `dlopen()` and `dlclose()`.

Note though that musl libc's `dlclose()` never actually unloads shared objects, only glibc does.

**Comment by twose** [comment]
Thank you for your help and patience :)
#2764 is sufficient for my needs (I can use persistent memory in fpm mode), and I think it (`uv_library_shutdown`) is better than the original way
