### ISSUE TITLE
request to remove the aix 6.1 builds, and add aix 7.1

### ISSUE THREAD

**Issue by sam-github** [libuv/libuv#2765]
We'd like to retire the AIX 6.1 machines, its not a supported OS level since Node.js 8.x went EOL.

libuv-test-commit-aix currently builds on 6.1/gcc, and 7.2/xlc.

We'd like to
1. Drop the AIX 6.1 build
2. Add an AIX 7.1 gcc build (7.1 is what currently supported Node.js minimally supports).

Are there any concerns about this?

I did a quick trial, it will take a few more build deps installed (gm4 is needed for autotools), so won't happen more towards end of this week, or early next.

**Comment by bnoordhuis** [comment]
I don't see a problem with that. No objections.

**Comment by richardlau** [comment]
No objections from me.

**Comment by richardlau** [comment]
> I did a quick trial, it will take a few more build deps installed (gm4 is needed for autotools), so won't happen more towards end of this week, or early next.

I'm assuming the quick trial was https://ci.nodejs.org/view/libuv/job/libuv-test-commit-aix/1864/nodes=aix71-ppc64/console:
```
+ export OBJECT_MODE=64
+ sh autogen.sh
+ libtoolize --copy
libtoolize:   error: One of these is required:
libtoolize:                 gm4 gnum4 m4
libtoolize:   error: Please install GNU M4, or 'export M4=/path/to/gnu/m4'.
```

On `test-ibm-aix71-ppc64_be-1` it does look like we have m4 installed (`m4-1.4.17-1.ppc`):
```
$ rpm -qa
yum-metadata-parser-1.1.4-2.ppc
yum-3.4.3-7.noarch
cyrus-sasl-2.1.26-3.ppc
libgcc-8.3.0-1.ppc
libffi-3.2.1-3.ppc
ncurses-6.1-2.ppc
libxml2-2.9.9-1.ppc
glib2-2.56.1-2.ppc
info-6.6-2.ppc
sqlite-3.28.0-1.ppc
p11-kit-tools-0.23.16-1.ppc
gdbm-1.18.1-1.ppc
python-2.7.16-1.ppc
python-pycurl-7.43.0-1.ppc
python-devel-2.7.16-1.ppc
gmp-6.1.2-1.ppc
libmpc-1.1.0-1.ppc
gcc-8.3.0-1.ppc
less-551-1.ppc
libstdc++-devel-8.3.0-1.ppc
git-2.20.1-1.ppc
tar-1.32-1.ppc
m4-1.4.17-1.ppc
automake-1.16.1-1.noarch
pcre-8.42-1.ppc
libtool-2.4.6-2.ppc
libgcc6-6.3.0-1.ppc
gcc6-6.3.0-1.ppc
libstdc++6-devel-6.3.0-1.ppc
gdb-8.1.1-3.ppc
bzip2-1.0.8-2.ppc
expat-2.2.9-1.ppc
sudo-1.8.28-1.ppc
perl-5.28.1-2.ppc
vim-enhanced-8.1.2130-2.ppc
curl-7.67.0-1.ppc
cmake-rpm-macros-3.14.3-1.ppc
cmake-data-3.14.3-1.ppc
AIX-rpm-7.1.5.30-1.ppc
python-iniparse-0.4-1.noarch
python-urlgrabber-3.10.1-1.noarch
openldap-2.4.48-1.ppc
yum-utils-1.1.31-2.noarch
zlib-1.2.11-1.ppc
libstdc++-8.3.0-1.ppc
libssh2-1.8.2-1.ppc
xz-libs-5.2.4-1.ppc
libunistring-0.9.9-2.ppc
bash-5.0-1.ppc
readline-8.0-2.ppc
p11-kit-0.23.16-1.ppc
ca-certificates-2019.01.10-2.ppc
db-6.2.38-1.ppc
pysqlite-2.8.3-2.ppc
python-tools-2.7.16-1.ppc
mpfr-4.0.2-1.ppc
gcc-cpp-8.3.0-1.ppc
rsync-3.1.3-4.ppc
gcc-c++-8.3.0-1.ppc
unzip-6.0-3.ppc
autoconf-2.69-1.noarch
grep-3.3-1.ppc
cpio-2.12-2.ppc
gcc6-cpp-6.3.0-1.ppc
libstdc++6-6.3.0-1.ppc
gcc6-c++-6.3.0-1.ppc
libiconv-1.14-2.ppc
krb5-libs-1.16.1-3.ppc
sed-4.5-3.ppc
gettext-0.19.8.1-5.ppc
vim-common-8.1.2130-2.ppc
make-4.2.1-5.ppc
cmake-filesystem-3.14.3-1.ppc
cmake-3.14.3-1.ppc
$
```

```
$ whoami
iojs
$ which m4
/usr/bin/m4
$
```

I'll dig further into this.

**Comment by richardlau** [comment]
Right this is `PATH` issue. AIX supplies its own version of [`m4`](https://www.ibm.com/support/knowledgecenter/ssw_aix_71/m_commands/m4.html) which is in `/usr/bin/m4`. We do have GNU m4 installed (via `m4-1.4.17-1.ppc`) and that appears to be in `/opt/freeware/bin/m4`.

```
bash-5.0$ /usr/bin/m4 --version
/usr/bin/m4: Not a recognized flag: -
Usage: m4 [-els] [-B Number] [-D Name[=Value]]... [-H Number]
       [-I Directory] [-S Number] [-T Number] [-U Name]... [File...]
bash-5.0$ /opt/freeware/bin/m4 --version
m4 (GNU M4) 1.4.17
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.
bash-5.0$
```

**Comment by richardlau** [comment]
Test CI (with aix71-ppc64 added): https://ci.nodejs.org/view/libuv/job/libuv-test-commit-aix/1876/ (✔️)

Passed, so removing aix61-ppc64.

**Comment by richardlau** [comment]
New CI (with aix61-ppc64 removed): https://ci.nodejs.org/view/libuv/job/libuv-test-commit-aix/1877/

**Comment by richardlau** [comment]
All passed so this can be considered done. 

For the record on AIX we now build and test on:
job | build and test on
---|---
[libuv-test-commit-aix](https://ci.nodejs.org/view/libuv/job/libuv-test-commit-aix) | aix71 (gcc) and aix72 (xlc) with autoconf+automake
[libuv-test-commit-aix-cmake](https://ci.nodejs.org/view/libuv/job/libuv-test-commit-aix-cmake/) | aix71 (gcc) with cmake
