### ISSUE TITLE
ANSI color values are being remapped in Node

### ISSUE THREAD

**Issue by Undercat** [libuv/libuv#2766]
I have an issue sending ANSI escape sequences to CygWin's console, mintty, as described in issue mintty/mintty#981

I'm starting to think this may be actually be a libuv issue. Does this sound like something your tty code could be doing when talking to the Windows pty driver, or does the problem lie farther downstream?

**Comment by erw7** [comment]
If Windows has `ENABLE_VIRTUAL_TERMINAL_PROCESSING`, then libuv will output the given output as is. Therefore, I don't think this is a problem with the libuv.

In fact, I've tried it with the following program and I get the same problem.

```c
#include <stdio.h>
#include <windows.h>

int main(void)
{
  HANDLE handle_stdout = GetStdHandle(STD_OUTPUT_HANDLE);
  if (handle_stdout == INVALID_HANDLE_VALUE) {
    return 1;
  }

  DWORD mode;
  if (!GetConsoleMode(handle_stdout, &mode)) {
    return 1;
  }

  mode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
  if (!SetConsoleMode(handle_stdout, mode)) {
    return 1;
  }

  wchar_t *buff = L"\x1b[48;2;117;117;117m \x1b[48;2;118;118;118m \x1b[48;2;119;119;119m \x1b[m\n"
                  L"\x1b[48;5;242m \x1b[48;5;243m \x1b[48;5;244m \x1b[m\n"
                  L"\x1b[38;5;7;48;5;243m test \x1b[m\n"
                  L"\x1b[38;5;7;48;5;244m test \x1b[m\n";
  DWORD num_of_written;
  if (!WriteConsoleW(handle_stdout, buff, wcslen(buff), &num_of_written, NULL)) {
    return 1;
  }

  return 0;
}
```

**Comment by Undercat** [comment]
Interesting. Thanks for the insight.

I suppose it makes sense that Microsoft would be doing the remapping, since the values being remapped correspond specifically to the RGB intensity values chosen by Windows to make their SGR primary colors "more visible," like everybody else does...with different intensity values. I'll see if I can't find the right place to post this issue with them.

Cheers.
