### ISSUE TITLE
unix: uv_async_send takes long latency on single core CPU

### ISSUE THREAD

**Issue by Parallel-Hao** [libuv/libuv#2769]
* **Version**: v1.x
* **Platform**:  Linux 4.15.0-74-generic

I use libuv to manage socket communication in my process including two threads, one event loop thread from libuv and one thread sending event requests. It is found that the uv_async_send function takes long latency (~10 ms) occasionally when the process is pinned (via taskset) to one CPU core. 

Looking into uv_async_send code, I found spin_lock is used for synchronizing the event loop thread and the event requesting threads. For single CPU core case, the CPU is occupied by the event loop thread running uv__async_spin, so that the event requesting thread cannot be scheduled just after write eventfd in uv__async_send. I guess this kind of deadlock is released when the event loop thread finished one time slice, which is around 10 ms.

Based on my understanding, the spin mechanism here is for decreasing the overhead of the redundant write syscall. This spin could be beneficial when a large number of event requesting threads exist. However, as my process includes only one requesting thread, the spin code can be removed.  My new uv_async_send function is following:
```
int uv_async_send(uv_async_t* handle) {
  /* Do a cheap read first. */
  if (ACCESS_ONCE(int, handle->pending) != 0)
    return 0;

  /* Wake up the other thread's event loop. */
  uv__async_send(handle->loop);

  return 0;
}
```
Correspondingly, uv__async_spin is deleted in uv__async_io function.
This modification tests well for my case, and the long latency disappears. Are there any problems?

An alternative solution could be limiting spin times. If the spin reaches the max number, say 100, the event loop thread should yield CPU to others, though this solution leads to context switch overhead. And a spin max number is difficult to determine.

The first solution may be just for my case, which contains only one requesting thread. The second solution may works for more general cases. I am wondering whether my understanding is correct.

**Comment by bnoordhuis** [comment]
Your analysis sounds right.

Libuv spins because otherwise performance is atrocious when there are many active `uv_async_t handles. Removing the spin loop is therefore not an option but limiting the number of iterations sounds sensible to me.

Want to send a PR? There are some async handle benchmarks you can use for testing performance:

https://github.com/libuv/libuv/blob/0ed9692a80b2f310ad52060a8cb400f2a963d09c/test/benchmark-list.h#L67-L77

If you're using the cmake build, see #2771.

**Comment by frankfoxy** [comment]
This issue may be similar to #2651.
