### ISSUE TITLE
windows: uv_close destroys stdio handles on Windows

### ISSUE THREAD

**Issue by petkaantonov** [libuv/libuv#277]
The equivalent [unix code explicitly checks for stdio fds before closing them](https://github.com/libuv/libuv/blob/v1.x/src/unix/stream.c#L1564). 

/cc @bnoordhuis : this makes it not possible to use stdio inside workers in windows.

**Comment by petkaantonov** [comment]
I propose implementing something like this and calling it instead of calling `CloseHandle` directly:

```cpp
void uv__close_win_handle(HANDLE handle) {
  if (handle->handle != GetStdHandle(STD_INPUT_HANDLE) &&
      handle->handle != GetStdHandle(STD_OUTPUT_HANDLE) &&
      handle->handle != GetStdHandle(STD_ERROR_HANDLE)) {
    CloseHandle(handle);
  }
}
```

**Comment by petkaantonov** [comment]
I can start working on the PR myself to do the work if you acknowledge this is ok

**Comment by bnoordhuis** [comment]
I'm not the right person to ask.  Handing off to @piscisaureus.

**Comment by piscisaureus** [comment]
Just for my understanding, is the problem that uv- win closes stdio handles when it shouldn't? Or do we just need these checks as a means to catch bugs?

**Comment by petkaantonov** [comment]
The checks are so that stdio handles are never closed both to match unix and allow them to be used globally in a process.  CloseHandle is called from like 40 different places that dont check for stdio, hence the indirection

**Comment by piscisaureus** [comment]
@petkaantonov I'm cool with it, but since closing handles is not too uncommon maybe it'd make sense to cache the `GetStdHandle()` return values somewhere instead of calling them every time.

Another thing is that streams that were opened from a crt fd should really be closed with `close()` and not `CloseHandle()`, otherwise the fd allocation is leaked. Libuv doesn't really do that at the moment.

**Comment by petkaantonov** [comment]
The values can change so the result cannot be cached, but I really doubt they have any performance effect.

**Comment by saghul** [comment]
Closing since this https://github.com/libuv/libuv/pull/396 landed.
