### ISSUE TITLE
libuv fails to build on RHEL 5

### ISSUE THREAD

**Issue by wiggin15** [libuv/libuv#2770]
RHEL 5 is old, but technically still supported.

libuv fails to build on this platform for two reasons:
* `O_CLOEXEC` is not defined. There are several places across libuv which check for this flag's availability using `#ifdef O_CLOEXEC` but some places check it differently and compilation on RHEL 5 fail there:
    * In `core.c`, `uv__dup2_cloexec` checks using `#if defined(__FreeBSD__) || defined(__NetBSD__) || defined(__linux__)` (the function above this one, `uv__open_cloexec`, uses the correct `#if defined(O_CLOEXEC)` and their implementations are a little similar)
    * In `linux-core.c`, `uv__platform_loop_init` checks for Android API version instead of the flag's availability
* More recently, commit dfd64933d55fee97c329a1c13b5d6dac874e295c added a dependency on a more recent kernel version ("Assume the presence of the eventfd2()")

The commit mentioned above says about the kernel version that "our baseline is 2.6.32.". Even if so, the checks for O_CLOEXEC at least can still be unified. And please do consider keeping support for RHEL 5 - it can still work with only a few changes.

**Comment by bnoordhuis** [comment]
We dropped support for kernels < 2.6.32 three years ago and we have no interest in reviving that support. I mean, even 2.6.32 is 11 years old by now.
