### ISSUE TITLE
CPU times/read_times on Linux is multiplied by clock ticks wrong

### ISSUE THREAD

**Issue by twpol** [libuv/libuv#2773]
* **Version**: 1.19.2 (NodeJS 8.17.0)
* **Platform**: Linux db8e824e7490 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux

Firstly, apologies for the old version above, it's what I happened to have been debugging, however, the issue I think I've found exists in the latest code linked below.

The function `read_times` appears to contain a small but critical error in its calculations on Linux only - namely that it multiplies the `/proc/stat` counters with `_SC_CLK_TCK` instead of dividing them (and multiplying by the `1000` needed for milliseconds). Compare the code:

Linux: https://github.com/libuv/libuv/blob/02e7a78628e5373a17b6b19d0c81cc1d12739aa4/src/unix/linux-core.c#L782
FreeBSD: https://github.com/libuv/libuv/blob/3d7136639a39db46bc4a9074922559a564e49514/src/unix/freebsd.c#L199-L200
Mac: https://github.com/libuv/libuv/blob/2ab3dc1567d67924b634be6f478d25f4528ce574/src/unix/darwin.c#L175-L176
Etc.

I came across this because my code was receiving CPU times that looked 10x of what was measured by system tools, and that looks to be because this code on Linux is multiplying by 100 (clock tick rate) instead of by 1000 / 100 (milliseconds per clock tick).

I hope I've not missed something obvious, and many apologies if I have, because this really feels like I should have!

**Comment by twpol** [comment]
https://github.com/libuv/libuv/commit/54bfb66806a3f94f44243030ad51a10db6c9eb29 appears to be where this was broken (or at least diverged from other platforms).

**Comment by bnoordhuis** [comment]
Thanks for the report. The libuv documentation doesn't really say what units are used but Node's docs claim they're in milliseconds. Let's assume for now Node is right.

Values reported in `/proc/stat` are in increments of 1/100th of a second. Libuv multiplies them by `sysconf(_SC_CLK_TCK)`, which coincidentally is always 100 on linux.

On e.g. macos and freebsd we multiply them by `1000 / sysconf(_SC_CLK_TCK)` and that's probably what we should do on linux too.

Want to open a PR? Clarifying the docs would be good too.

**Comment by twpol** [comment]
I'll have a go at a PR, sure.

> Values reported in `/proc/stat` are in increments of 1/100th of a second. Libuv multiplies them by `sysconf(_SC_CLK_TCK)`, which coincidentally is always 100 on linux.

To be clear, I don't believe this is a coincidence. https://linux.die.net/man/5/proc says:

> The amount of time, measured in units of USER_HZ (1/100ths of a second on most architectures, use sysconf(_SC_CLK_TCK) to obtain the right value), that the system spent in various states:

**Comment by bnoordhuis** [comment]
Indeed it's not. :-)

musl libc hard-codes `sysconf(_SC_CLK_TCK)` to 100 but glibc reads it from the auxv on start-up so it's _technically_ possible for it to be something else - but that was only the case on alpha and ia64 and both of those are long dead.
