### ISSUE TITLE
Persistent fs_event_error_reporting CI failures on macOS 10.15

### ISSUE THREAD

**Issue by richardlau** [libuv/libuv#2775]
To support https://github.com/libuv/libuv/pull/2682 a [cmake based job was added for macOS](https://github.com/libuv/libuv/pull/2682#issuecomment-601186644). The first CI macOS hosts to have cmake added to them were 10.15 (as we were setting those up from scratch). There's a persistent failure in the CI with v1.x on the 10.15 hosts that we're not seeing on 10.11:

e.g. https://ci.nodejs.org/view/libuv/job/libuv-test-commit-osx-cmake/26/nodes=osx1015/console
```
not ok 48 - fs_event_error_reporting
# timeout
# Output from process `fs_event_error_reporting`: (no output)
```

FWIW @bnoordhuis [wasn't able to reproduce on macOS 10.14](https://github.com/libuv/libuv/pull/2682#issuecomment-601200466).

**Comment by santigimeno** [comment]
Couldn't reproduce the issue locally on `macOS 10.15.3`

**Comment by richardlau** [comment]
As a test I temporarily added macOS 10.14 into the test matrix for the libuv-test-commit-osx-cmake job and it had a similar failure: https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/nodes=osx1014/105/console

So maybe it's something to do with how the CI machines are set up? We're seeing the failure on the macOS 10.15 CI machines both in macstadium (the Orka environment) and the machine at NearForm.

**Comment by cjihrig** [comment]
FWIW, I can't reproduce this locally on macOS 10.14 either.

**Comment by richardlau** [comment]
cc @AshCripps for awareness

**Comment by AshCripps** [comment]
The 10.15 macs in CI are `10.15.4` so maybe theres some bug in that version, where is the test code/what do they do so I can take a quick look

**Comment by richardlau** [comment]
@AshCripps it's the libuv test suite, so you'd need to build libuv then run its tests (https://github.com/libuv/libuv#build-instructions, we're using cmake in the CI).

**Comment by AshCripps** [comment]
Im being spammed with accept firewall connection running the test suite, is there something im supposed to do to stop that? (like how node has the macos-firewall.sh script)

**Comment by AshCripps** [comment]
Strangly following the build instructions Richard linked I cant even replicate the issue on both the failing machines in CI 👀.

**Comment by genio** [comment]
It's happening for me as well in CI https://github.com/p5-UV/Alien-libuv/runs/702109220#step:8:548

**Comment by cjihrig** [comment]
I did some printf debugging in the CI, and it looks like the test is legitimately timing out. I was able to get the [test passing in the CI](https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1917/) by [bumping the timeout](https://github.com/cjihrig/libuv/commit/e085e625af14aa237c89ff6d95a855a054ed4315). It looks like the `hrtime` test is timing out as well.

**Comment by genio** [comment]
Should I put in another issue for the other test failures that seem to happen on every CI run?

**Comment by bnoordhuis** [comment]
@cjihrig If that's all it takes to get it to pass then let's do it.

@genio Legitimate failures, sure, but I think those failures may be caused by Actions disallowing (some kinds of) UDP traffic? I'd be okay with skipping those tests if there's a good way to detect that.

**Comment by cjihrig** [comment]
OK: https://github.com/libuv/libuv/pull/2865

**Comment by genio** [comment]
@bnoordhuis The same tests ran fine on the linux Actions, so I'll try checking the macos firewall on the machine running to see if that yields better results and go from there.

**Comment by genio** [comment]
No difference. I doubt they have different policies set for each OS, but who knows. You might be right and they may be blocking some things that we have no control over.
