### ISSUE TITLE
Windows: Use GetCurrentThreadId for uv_thread_self

### ISSUE THREAD

**Issue by gabrielschulhof** [libuv/libuv#2784]
* **Version**: 1.35.0
* **Platform**: Windows 10, virtualbox
Could we use `GetCurrentThreadId()` at https://github.com/libuv/libuv/blob/335e8a6d128646e5a19d39dfc677f5a5a555f7cc/src/win/thread.c#L184-L187 and remove the need for storing the thread ID in thread-local storage? This would also address the issue at https://github.com/nodejs/node/pull/32823.

**Comment by vtjnash** [comment]
Then we can't call `uv_thread_join`, since we need a thread handle for that. Though we could perhaps allocate one on demand and stash it here.

**Comment by gabrielschulhof** [comment]
@vtjnash if we cannot drop the thread-local storage, we can maybe wrap `uv_key_get(&uv__current_thread_key)` in a function that calls `GetCurrentThreadId()` and saves the value at `uv_current_thread_key` if it finds that the value stored there is zero and only then returns the value.

**Comment by bnoordhuis** [comment]
> we could perhaps allocate one on demand

You mean with `OpenThread(SYNCHRONIZE, FALSE, tid)`? I think that could work.

@gabrielschulhof Want to give that a try? The type of `uv_thread_t` can't change for API/ABI reasons but that can be solved by casting. It's a typedef for `HANDLE` while a thread id is a `DWORD`.

**Comment by gabrielschulhof** [comment]
@bnoordhuis I'd love to, but, unfortunately, I don't think I have the cycles 🙁
