### ISSUE TITLE
Some warning from MinGW under Windows

### ISSUE THREAD

**Issue by escherstair** [libuv/libuv#2790]
* libuv v1.35.0
* Windows 7 SP1 x64
* MinGW - GCC 7.3.0

Here is the list of some warnings I get from MinW:

https://github.com/libuv/libuv/blob/3e5d26144085bd709a0de24dd744bee8142bae5f/src/win/fs-fd-hash-inl.h#L63
comparison between signed and unsigned integer expressions [-Wsign-compare]

https://github.com/libuv/libuv/blob/3e5d26144085bd709a0de24dd744bee8142bae5f/src/win/fs.c#L705
comparison between signed and unsigned integer expressions [-Wsign-compare]

https://github.com/libuv/libuv/blob/3e5d26144085bd709a0de24dd744bee8142bae5f/src/win/fs.c#L784
unused variable 'err' [-Wunused-variable]
- should be included inside `#ifdef _MSC_VER` / `#endif`

**Comment by escherstair** [comment]
Shuold I provide a PR?

**Comment by bnoordhuis** [comment]
@escherstair Yes, please!

**Comment by escherstair** [comment]
Give me some time and I'll do it.

**Comment by escherstair** [comment]
I've just added the PR #2854

**Comment by escherstair** [comment]
One thing is not clear to me:
variable `zero`
https://github.com/libuv/libuv/blob/36549815eed297c74448ff580b5c84713245ec5d/src/win/fs.c#L941
is set, but never used.
If it's not needed I can delete it, otherwise I need to know where it should be used.

**Comment by bnoordhuis** [comment]
@escherstair `zero` can be removed, that was an oversight in 2c279504f.

**Comment by escherstair** [comment]
I pushed a commit that removes it
