### ISSUE TITLE
Rscript.exe crashing after window resized when using R package "fs" (based on libuv)

### ISSUE THREAD

**Issue by ismirsehregal** [libuv/libuv#2794]
I thought maybe someone here is interested in this [issue](https://github.com/r-lib/fs/issues/261). Or knows what's going on.

Cheers!

**Comment by bnoordhuis** [comment]
What version of libuv is that?

**Comment by ismirsehregal** [comment]
fs [mentions commit](https://github.com/r-lib/fs/tree/master/src/libuv) 8a6dc9b9cef69f48ae342c51fc4f5ec61dcffee0

**Comment by jimhester** [comment]
This is almost certainly not an issue with upstream libuv, I would suggest just closing this issue.

**Comment by bnoordhuis** [comment]
Sounds like it's old anyway, if it was merged two years ago. Can you try with the latest release?

**Comment by bnoordhuis** [comment]
Comments crossed. :-) I'll close this out then, thanks.
