### ISSUE TITLE
Planned outage for test-osuosl-aix72-ppc64_be-2

### ISSUE THREAD

**Issue by sam-github** [libuv/libuv#2804]
See https://github.com/nodejs/build/issues/2305, duplicated below.

-----

This coming Monday, April 27th, test-osuosl-aix72-ppc64_be-2 will be taken down so that the hardware its running on can get some routine maintenance. Its predicted it will occur sometime during the day, Oregon (US) time, and take about 4 hours.

libuv-test-commit-aix uses this machine for xlc builds, and is the only user.

https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-2/builds

Sorry for the disruption, it should be fairly brief.

**Comment by sam-github** [comment]
Much of the work happened, but more will be done this coming thursday, see https://github.com/nodejs/build/issues/2305#issuecomment-620691902

**Comment by richardlau** [comment]
https://github.com/nodejs/build/issues/2329

> 
> 
> https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-2/ will be down for a few hours on Monday May 25th, 0600 GMT.
> 
> Planned work is:
> 
> > Basically, all that is going to happen is a rootvg clone, then reboot to the clone; cleanup the old rootvg (i.e., remove from ODM so the disk can be removed).
> > Ideally, systems should be up and running in less than 2 hours after I start.
>

**Comment by mhdawson** [comment]
@richardlau, I believe the outage has already taken place and this can be closed right?

**Comment by richardlau** [comment]
> 
> 
> @richardlau, I believe the outage has already taken place and this can be closed right?

@mhdawson I have no idea as I was not included in any of the emails. @sxa is this something you were aware of?

**Comment by mhdawson** [comment]
@richardlau ok, believe it is done, but I can't close the issue in this repo.
