### ISSUE TITLE
In Windows: uv_udp_init_ex() with UV_UDP_RECVMMSG fails with "invalid argument"

### ISSUE THREAD

**Issue by ibc** [libuv/libuv#2806]
* **Version**: v1.37.0
* **Platform**: Window 10 x64

I don't have a Windows host. I got this report from a Windows user using my libuv based application.

It seems that `uv_udp_init_ex()` with the new `UV_UDP_RECVMMSG` flag fails in Windows. Usage is as follows:

```c++
uv_handle_t* handle = reinterpret_cast<uv_handle_t*>(new uv_udp_t());
int err = uv_udp_init_ex(loop, reinterpret_cast<uv_udp_t*>(handle), UV_UDP_RECVMMSG);
```

It fails with `uv_strerror(err)`: "invalid argument"

**Comment by squeek502** [comment]
Running into this as well. Relevant code:

https://github.com/libuv/libuv/blob/002fe6e5f2d084fc12fee3d6e5a3fdffe491b7e8/src/win/udp.c#L128-L137

**Comment by bnoordhuis** [comment]
Yep, that's an oversight. Passing the flag should be a no-op on Windows, not an error.
