### ISSUE TITLE
Makefile:5080: recipe for target 'check-TESTS' failed

### ISSUE THREAD

**Issue by miradox** [libuv/libuv#2813]
* **Version**: Last
* **Platform**: Linux Server 5.3.0-1022-raspi2 #24~18.04.1-Ubuntu SMP aarch64 aarch64 aarch64 GNU/Linux
Hi,
I've done this as indicated in Build Instructions
```
$ sh autogen.sh
$ ./configure
$ make
```
And all is good. But the output of the next command `$ make check` is : 
```
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:5080: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/miradox/libuv'
Makefile:5336: recipe for target 'check-am' failed
make: *** [check-am] Error 2
```
I didn't run this as root as mentioned. Anyone know the solutions ?
Have a good day : )

**Comment by bnoordhuis** [comment]
Can you include the actual test failures?

**Comment by miradox** [comment]
> Can you include the actual test failures?

**Comment by miradox** [comment]
Hi, 
sorry for disturbance.I still tried to execute the make command and everything went well.
Have a good day
