### ISSUE TITLE
win: investigate GetSystemTimePreciseAsFileTime()

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2820]
I'm researching Windows clock sources in order to make progress on #1633 and supersede #2814. Summary: stop using QPC in `uv_hrtime()`.

If `QueryPerformanceCounter()` is out, then `GetSystemTimePreciseAsFileTime()` (Windows 8) seems like the best replacement.

Good: high resolution, unlike its non-precise counterpart `GetSystemTimeAsFileTime()` (can be as coarse as 15 milliseconds apparently.)

Bad: system time is not monotonic. It's affected by time adjustments (DST, leap seconds.)

@libuv/windows I'd like your input. Are there better ways to go about this?

**Comment by bnoordhuis** [comment]
Relatedly, more than you ever wanted to know about Windows high-resolution timers:

* http://www.windowstimestamp.com/description
* https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamp (really good article)

**Comment by bzoz** [comment]
Would it be any better? Wouldn't the DST, syncing time, etc. cause the same clock-drift issue we are having with QPC() now, but for almost all users instead of the selected few that have the new Intel CPUs?

On a side note, the underlying Windows issue that is causing all this could also affect `GetSystemTimePreciseAsFileTime`.

**Comment by erw7** [comment]
I don't think `GetSystemTimePreciseAsFileTime()` can be used to solve this problem.

https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps

> GetSystemTimePreciseAsFileTime when you want to time-stamp events across multiple machines, provided that each machine is participating in a time synchronization scheme such as Network Time Protocol (NTP).

From the above description, `GetSystemTimePreciseAsFileTime()` is considered to be affected by `NTP`. In `NTP`, it should be possible for the time to go backwards when synchronizing the time in step mode. Therefore, I believe that the use of `GetSystemTimePreciseAsFileTime()`, far from solving the problem, can cause similar problems on systems that are not having problems.

**Comment by bnoordhuis** [comment]
Right, I feared that might be the outcome. Then what is a good alternative for QPC? Windows seems to have a dearth of stable monotonic clocks.

**Comment by erw7** [comment]
As long as I read the [Acquiring high-resolution time stamps](https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps), there doesn't seem to be anything else appropriate for QPC.

Those who have a problem with `assert` termination are using debug built binaries, aren't they? If that is the case, they should know what they are doing. Therefore, I don't see the need to fix the problem of ending with an `assert`. Or are the binaries officially distributed by Node.js being debug built?

**Comment by bnoordhuis** [comment]
They're release builds but with asserts deliberately enabled.

Okay, so it seems the conclusion is that there's no way around QPC. I'll close this then.

**Comment by soraryu** [comment]
@erw7 just to clarify - this assert is crashing in released software by large corporations, e.g. the Package Manager from Unity3D (built on electron). I have no influence on the source of that but I doubt it's a debug build.
