### ISSUE TITLE
Usability of UV_UDP_RECVMMSG

### ISSUE THREAD

**Issue by squeek502** [libuv/libuv#2822]
While writing [a test case for UV_UDP_RECVMMSG](https://github.com/libuv/libuv/pull/2818) and thinking about [how to bind uv_udp_init_ex in a garbage collected language](https://github.com/luvit/luv/pull/487), I'm realizing that users of libuv will likely need some way of knowing whether or not `mmsg` is actually used/supported at buffer-allocation-time, due to how `UV_UDP_RECVMMSG` relies on buffer allocation size as mentioned [in this comment](https://github.com/libuv/libuv/pull/2818#issuecomment-620846742):

> * `UV_UDP_RECVMMSG` has no real effect unless the allocated buffer size is large enough to handle > 1 max size dgrams
> * When `UV_UDP_RECVMMSG` is used, the number of possible messages recv'd at once is limited to (buffer size / max dgram size). ([relevant libuv code](https://github.com/libuv/libuv/blob/2bbf7d5c8cd070cc8541698fe72136328bc18eae/src/unix/udp.c#L194-L208))

As an example use case, this would allow users to allocate a single dgram-sized buffer on platforms that don't support `recvmmsg`, but allocate a multi-dgram-sized buffer when using `recvmmsg`:

```c
static void alloc_cb(uv_handle_t* handle, size_t suggested_size, uv_buf_t* buf) {
  size_t num_dgrams = is_mmsg ? 16 : 1;
  // suggested size happens to match up with UV__UDP_DGRAM_MAXSIZE
  buf->base = malloc(suggested_size * num_dgrams);
  buf->len = suggested_size * num_dgrams;
}
```

Not exactly sure how best this sort of thing would be implemented, though. One possibility would be to add a getter for [the `UV_HANDLE_UDP_RECVMMSG` flag](https://github.com/libuv/libuv/blob/4d3779c08c54b142680c9394f19346735b696c99/src/uv-common.h#L107) and only set that flag when
1. `recvmmsg` is supported on the current platform
2. `UV_UDP_RECVMMSG` was set when creating the udp handle

(note that right now [`UV_HANDLE_UDP_RECVMMSG` is set regardless of whether or not `recvmmsg` is supported on the current platform](https://github.com/libuv/libuv/blob/4d3779c08c54b142680c9394f19346735b696c99/src/uv-common.c#L313-L315))

---

One other thing is that, due to how the number of dgrams read via `recvmmsg` is reliant on multiples of [`UV__UDP_DGRAM_MAXSIZE`](https://github.com/libuv/libuv/blob/2bbf7d5c8cd070cc8541698fe72136328bc18eae/src/unix/udp.c#L35), it might be helpful to make that constant public in some way, or guarantee that `alloc_cb`'s `suggested_size` will always equal `UV__UDP_DGRAM_MAXSIZE` for `recv` buffer allocations.

**Comment by squeek502** [comment]
Before I write a PR for this stuff, anyone have any thoughts on it? Am I thinking about this wrong?

**Comment by squeek502** [comment]
One more thing I'm unsure about:

When using `UV_UDP_RECVMMSG`, `recv_cb` gets called once for each message with the `UV_UDP_MMSG_CHUNK` flag set and then [once with `nread=0`, `addr=NULL`, and without the `UV_UDP_MMSG_CHUNK` flag set to free the buffer](https://github.com/libuv/libuv/blob/e7ebae26247d2fee0a04547eb7f9aa8f78d4a642/src/unix/udp.c#L234-L236).

For binding this function in a garbage collected language, passing that last callback on seems somewhat strange, as the garbage collected language shouldn't care about it, and it would cause a discrepancy in the number of callbacks called when using `mmsg` and when not using it. That is, using the test added in #2818 as an example, where using `mmsg` leads to 2 allocs for 8 messages:

- When not using `UV_UDP_RECVMMSG`, `recv_cb` would be called 8 times (once for each message)
- When using `UV_UDP_RECVMMSG`, `recv_cb` would be called 10 times (once for each message, and then 2 for freeing the mmsg buffers)

Not passing these 'free-only' callbacks on would be no problem except that there doesn't seem to be a way to distinguish these 'free-only' callbacks from things like [`EAGAIN` or `EWOULDBLOCK`](https://github.com/libuv/libuv/blob/e7ebae26247d2fee0a04547eb7f9aa8f78d4a642/src/unix/udp.c#L292-L293), which doesn't seem ideal. But, again, I might be thinking about this wrong, so any feedback is appreciated.

**Comment by vcunat** [comment]
Wouldn't it be better for `suggested_size` to reflect the recvmmsg state automatically?  I mean... it's probably not difficult for libuv users to guess that UDP can be (theoretically) up to 64kB long, so without recvmmsg there's not much information in the parameter.

**Comment by squeek502** [comment]
@vcunat that would be another option. Not sure which would be better.
