### ISSUE TITLE
Test failure udp_multicast_join on Catalina

### ISSUE THREAD

**Issue by krisbudhram-mc** [libuv/libuv#2827]
Download and unpack v1.37.0.tar.gz 
./autogen.sh && ./configure && make && make check

```
...
ok 350 - udp_multicast_interface6
not ok 351 - udp_multicast_join
# exit code 6
# Output from process `udp_multicast_join`:
# Assertion failed in test/test-udp-multicast-join.c on line 160: r == 0
ok 352 - udp_multicast_join6
...
ok 378 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] Error 1
make: *** [check-am] Error 2
```

* **Version**: v1.37.0, v1.34.2
* **Platform**: Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 / OSX Catalina

**Comment by bnoordhuis** [comment]
That test requires that your firewall accepts multicast traffic. In particular, that `239.255.0.1` is unblocked. Can you check that?

**Comment by krisbudhram-mc** [comment]
I was unable to specifically allow multicast traffic through the firewall, but disabling it temporarily allowed the test to pass.

**Comment by bnoordhuis** [comment]
Glad to hear it. I'll go ahead and close this out then.
