### ISSUE TITLE
win: Optionally customize process-wide error/debug hooks

### ISSUE THREAD

**Issue by bradking** [libuv/libuv#2829]
On Windows, libuv currently configures process-wide error handling and debug hooks in code [here](https://github.com/libuv/libuv/blob/v1.37.0/src/win/core.c#L177-L194) with calls to `SetErrorMode`, `_set_invalid_parameter_handler`, and `_CrtSetReportHook`.  This prevents applications from adding their own handlers/hooks or producing [WER](https://docs.microsoft.com/en-us/windows/win32/wer/about-wer) dumps.  Since libuv is a library, it may not be the only infrastructure within an application that wants to have such hooks.

In general the top-level application code should be in control of process-wide error handlers and debug hooks.  We need a way for applications to install their own handlers/hooks that call into libuv's functions (in addition to equivalents for other libraries).  This would need to be done as part of libuv's initialization so that there is never a point in the process where libuv has unconditionally overridden anything from the application.

**Comment by bradking** [comment]
For reference, this came up in CMake work [here](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4052) and [here](https://gitlab.kitware.com/cmake/cmake/-/issues/20115#note_749073).

**Comment by bnoordhuis** [comment]
@libuv/windows 

I expect that the biggest hurdle is that removing those calls is a potentially breaking change for existing libuv users, they'd have to update their code to make those calls themselves.

**Comment by vtjnash** [comment]
FWIW, 2 of the 3 of these are already gone if you're using libuv master.

**Comment by ptlomholt** [comment]
fwiw, I submitted a similar issue, #1327, a while back ...

**Comment by bzoz** [comment]
I guess we could have a `uv_configure` which could be used to disable setting the error handlers.

**Comment by pgroke-dt** [comment]
To enable the "automatic crash dump creation" use case with CTest we'd also need to get rid of the `JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION` flag that's used in `uv__init_global_job_handle`.

> I guess we could have a `uv_configure` which could be used to disable setting the error handlers.

That sounds good. The rules would probably have to be to call it before calling any other libuv functions?

Something like this?
```
enum uv__global_option { ... };
int uv__configure(uv__global_option option, va_list ap);
```

And what should the options and their defaults be? One possibility would be to simply make an option for suppressing the `SetErrorMode` call and another one for the suppress use of the `JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION` flag.

Or we could try to figure out some platform independent abstract concept for those options. Which would probably look "nicer" but may also make it harder for libuv users to exactly control what libuv does. Plus of course it sounds like it would require a lot more work figuring out what those options should be upfront.
E.g. a "don't interfere with crash handling" option would have to remove the `SEM_NOGPFAULTERRORBOX` and `JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION` flags but leave the `SetErrorMode` call in place with `SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX`. Or it could be broadened to a "don't interfere with error handling" option which would then have to suppress `SetErrorMode` completely plus remove the `SEM_NOGPFAULTERRORBOX` and `JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION` flag.

Another possibility would be to just provide an option to suppress any process-global changes, and expose functions that can be used to let the application explicitly make them. But that could also be a lot of work to implement, I don't know how many other changes of process-global settings libuv does.

**Comment by bnoordhuis** [comment]
`uv_configure()` sounds like a good way forward. I'd not over-engineer it and simply add a flag that makes libuv skip the code here:

https://github.com/libuv/libuv/blob/7ccea60b1f576de2e65e8891b76165b8048aaac8/src/win/core.c#L177-L194

`_CrtSetReportHook()` is mildly problematic but it's up to the libuv user (cmake) to deal with that.

**Comment by bnoordhuis** [comment]
> To enable the "automatic crash dump creation" use case with CTest we'd also need to get rid of the `JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION` flag

I'm curious, does libuv actually need to specify that flag? My (admittedly limited) googling didn't turn up a conclusive answer.

**Comment by pgroke-dt** [comment]
@bnoordhuis I don't know if libuv needs it/should use it either.

The documentation says:
```
Forces a call to the SetErrorMode function with the SEM_NOGPFAULTERRORBOX flag for each process associated with the job. 
```

However what it really seems to do if force the _effect_ of `SEM_NOGPFAULTERRORBOX` on the associated processes, without them being able to change that. Because as I wrote, we tried calling `SetErrorMode` in the child processes to remove `SEM_NOGPFAULTERRORBOX` and it did not help. Furthermode `GetErrorMode` in the child processes did not even report `SEM_NOGPFAULTERRORBOX` so I think the documentation is incorrect.

**Comment by bnoordhuis** [comment]
Does someone want to move this forward and open a pull request?

W.r.t. `JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION`, I think we can just remove it and see what happens in the CI.

**Comment by bradking** [comment]
Can someone please add `feature-request` or one of the other stale-exempt labels to this issue?

**Comment by vtjnash** [comment]
This is entirely fixed on libuv v2 now (since https://github.com/libuv/libuv/pull/3838)
