### ISSUE TITLE
Windows error codes differ from the UNIX once.

### ISSUE THREAD

**Issue by txdv** [libuv/libuv#283]
When I am compiling under unix I push all the error codes into enum in C#.

Now I went back to windows and tried to run libuv and found out that the error codes all differ (I guess they use the native once?).

This is very unhandy for FFI bindings, since the error codes will differ on all system (I guess the only difference being on Windows and UNIX systems). Nevertheless, I need to keep now 2 sets of error codes, windows error codes and UNIX error codes.

It did work before as far as I recall (the Windows error codes were probably mapped to the UNIX error codes).

I don't know what to do. Should I create another set of error codes in my C# project so I can use them accordingly under the different systems? Or maybe a libuv function which translates them to UNIX error codes?

**Comment by saghul** [comment]
Error handling changed between 0.10 and 1.x: https://github.com/libuv/libuv/commit/3ee4d3f183331a123ce35edd0d32268a2bb22aa5

Previously we had our own error codes defined and mapped both Unix and Windows errors to them. Now Unix errors are basically -errno and Windows is just a custom defined set of them.

Now, does C#'s FFI load incomplete enums? If so, you could load this one: https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L172-L177

Python's CFFI and luaJIT's seem to be able to do so. The alternative would be to define the 2 sets of errnos, but I'm afraid there might be some not-so-standard ones that vary across Unixes.

**Comment by txdv** [comment]
I use a script https://github.com/txdv/LibuvSharp/blob/master/generate.c#L8-L16 to create the errno enum. Now the integer values of fields on windows differ on Unix and Windows.

EAGAIN on windows is -4088 or something(can't check, since changes are at home) while on UNIX it is -11.

How is Pythons CFFI and luaJit handling it?

**Comment by saghul** [comment]
> I use a script https://github.com/txdv/LibuvSharp/blob/master/generate.c#L8-L16 to create the errno enum. Now the integer values of fields on windows differ on Unix and Windows.
> 
> EAGAIN on windows is -4088 or something(can't check, since changes are at home) while on UNIX it is -11.
> 

I know, that's intentional.

> How is Pythons CFFI and luaJit handling it?

No idea, you'll have to dig into those tools...

**Comment by txdv** [comment]
Can you link me to the projects? I can search them myself but maybe you know the links directly out of your memory.

**Comment by saghul** [comment]
http://cffi.readthedocs.org/en/latest/ there are no markers, so search for "enum".

Also http://luajit.org/ext_ffi_semantics.html

**Comment by txdv** [comment]
Well I don't understand what you want me to search for. This is some generic FFI documentation, not a specific ffi binding for libuv. I mean, the values of the error messages are ultimately encoded in the C headers. Using FFI one won't be able to access them, so assigning a meaning to them if the error codes differ on various systems is impossible.

So if I get an error message and I want to check whether it is an EAGAIN, I currently need to to get the uv_strerror and check whether the string is equal to  ["resource temporarily unavailable"](https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L71) ...

**Comment by saghul** [comment]
> Well I don't understand what you want me to search for. This is some generic FFI documentation, not a specific ffi binding for libuv. I mean, the values of the error messages are ultimately encoded in the C headers. Using FFI one won't be able to access them, so assigning a meaning to them if the error codes differ on various systems is impossible.
> 

Python's CFFI module can use a compiler to "fill in the blanks", in the verify phase. As I said, I haven't looked at how it works internally.

> So if I get an error message and I want to check whether it is an EAGAIN, I currently need to to get the uv_strerror and check whether the string is equal to "resource temporarily unavailable" ...

No. You can use http://docs.libuv.org/en/v1.x/errors.html#c.uv_err_name and you'll get "UV_EAGAIN" back. That's what luv does, for example: https://github.com/luvit/luv/blob/master/src/util.c#L42-L49

**Comment by txdv** [comment]
I didn't notice that this one exists, that will be good enough for me.

**Comment by bnoordhuis** [comment]
> How is Pythons CFFI and luaJit handling it?

They have a built-in minimalistic C parser and preprocessor.

**Comment by txdv** [comment]
I don't have that luxury, I am dependent on what my the C functions give me. But they give me enough - I totally forgot that uv_err_name exited, which is enough!
