### ISSUE TITLE
consider use ebtree instead rbtree

### ISSUE THREAD

**Issue by phpstatic** [libuv/libuv#2832]
https://www.infoq.com/presentations/ebtree-design/

EBtree is design for scheduler,  maybe LIBUV can use it to improve performance ?

**Comment by bnoordhuis** [comment]
Convince us with numbers?

FWIW, I doubt the rbtrees in libuv are bottlenecks except maybe in extremely pathological cases.

**Comment by phpstatic** [comment]
No number yet, maybe I will do some simple compare late.

Haproxy design EBtree to replace Rbtree to get better performance.

> FWIW, I doubt the rbtrees in libuv are bottlenecks except maybe in extremely pathological cases.

still it is better to get more performance if possible.

**Comment by ptlomholt** [comment]
Wouldn't the LGPL licensing terms for EBtree be a problem for incorporating it into libuv?

**Comment by bnoordhuis** [comment]
@ptlomholt Good point. Copying it verbatim from haproxy isn't possible but a clean room reimplementation should be acceptable.

@phpstatic I'm going to close this out for now but let me know when there is more to discuss.
