### ISSUE TITLE
Compilation problems in windows

### ISSUE THREAD

**Issue by FlowerFerry** [libuv/libuv#2834]
Version: 1.37.1
Platform: Windows 10 x64
IDE: vs 2017

I hope I do n’t have to manually modify it every time I update the version.

src\win\fs-event.c(117): error C4996: 'wcsdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _wcsdup. See online help for details.
win\fs.c(485): error C4996: 'umask': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _umask. See online help for details.
win\fs.c(486): error C4996: 'umask': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _umask. See online help for details.
win\pipe.c(198): error C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _close. See online help for details.
win\process.c(520): error C4996: 'wcsrev': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _wcsrev. See online help for details.
win\tty.c(2257): error C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _close. See online help for details.

**Comment by bnoordhuis** [comment]
How exactly are you building libuv? Not using any of the supported build methods apparently, otherwise you wouldn't be getting those errors.

**Comment by FlowerFerry** [comment]
> How exactly are you building libuv? Not using any of the supported build methods apparently, otherwise you wouldn't be getting those errors.

I am sorry for not expressing clearly, I included the code directly in the vs project.

**Comment by bzoz** [comment]
CMake will generate proper VS files

**Comment by FlowerFerry** [comment]
> CMake will generate proper VS files

I get it, thank you

**Comment by UMU618** [comment]
I think you should replace these deprecated POSIX functions with the ISO one on Windows.
