### ISSUE TITLE
testing on additional platforms using QEMU

### ISSUE THREAD

**Issue by cjihrig** [libuv/libuv#2842]
We currently test libuv on the Node.js CI, which has a fair number of platforms. However, we still get consistent bug reports for platforms that we don't test. One solution could be to run the libuv test suite via QEMU on GitHub Actions. For reference, the [wasm3 project does this](https://github.com/wasm3/wasm3/blob/640bf0cc2671f1725234536c3cd4be50de6cc19e/.github/workflows/tests.yml) with apparent success.

One caveat worth noting: @bnoordhuis has pointed out that QEMU is not always perfect, but hopefully it will work out in our favor.

I'm labeling this as help wanted, in case any champions from currently untested platforms would like to see this happen.

Your move stalebot.

**Comment by gengjiawen** [comment]
QEMU has perf problem, any other pitfalls ?

**Comment by cjihrig** [comment]
I think the biggest pitfall would be correctness on the QEMU side. If there are issues related to that though, we don't need to include a platform in our tests. This is all just a bonus on top of the existing CI.

**Comment by mhdawson** [comment]
For interest, which are the platforms that we are seeing bug reports on the most?

**Comment by cjihrig** [comment]
I think popular platforms in this category would be MinGW, Android, and to a lesser extent NetBSD and OpenBSD.

**Comment by gengjiawen** [comment]
Looks like android is also viable, I will try to add it when integrated qemu is finished.
