### ISSUE TITLE
RFC: fail gracefully in uv_{get,set}_process_title when uv_setup_args is not called

### ISSUE THREAD

**Issue by squeek502** [libuv/libuv#2845]
Currently, on platforms that require `uv_setup_args` to be called, calling `uv_{get,set}_process_title` will attempt to [use uninitialized pointers](https://github.com/libuv/libuv/blob/55dede5b6f730882d79f994138f0f23a7b28b119/src/unix/proctitle.c#L115-L117) if `uv_setup_args` wasn't called beforehand. However, for bindings like [luv](https://github.com/luvit/luv), we don't always control `main` and don't have access to the `argv` memory from Lua's main, so providing bindings for, or ensuring that `uv_setup_args` is always called is not feasible.

This means that `uv_{get,set}_process_title` will sometimes crash, but there's also no way of knowing if it will crash ahead-of-time as far as I can tell, so we don't have good options for avoiding a crash on some platforms.

The proposal here is to do something like this (`args_mem` is set when `uv_setup_args` succeeds):

```diff
 src/unix/proctitle.c | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)

diff --git a/src/unix/proctitle.c b/src/unix/proctitle.c
index 4ee991fc..64c69ad7 100644
--- a/src/unix/proctitle.c
+++ b/src/unix/proctitle.c
@@ -35,7 +35,7 @@ extern void uv__set_process_title(const char* title);
 static uv_mutex_t process_title_mutex;
 static uv_once_t process_title_mutex_once = UV_ONCE_INIT;
 static struct uv__process_title process_title;
-static void* args_mem;
+static void* args_mem = NULL;
 
 
 static void init_process_title_mutex_once(void) {
@@ -100,6 +100,9 @@ int uv_set_process_title(const char* title) {
   struct uv__process_title* pt;
   size_t len;
 
+  if (args_mem == NULL)
+    return UV_ENOBUFS:
+
   pt = &process_title;
   len = strlen(title);
 
@@ -126,6 +129,9 @@ int uv_get_process_title(char* buffer, size_t size) {
   if (buffer == NULL || size == 0)
     return UV_EINVAL;
 
+  if (args_mem == NULL)
+    return UV_ENOBUFS:
+
   uv_once(&process_title_mutex_once, init_process_title_mutex_once);
   uv_mutex_lock(&process_title_mutex);
```

and add similar checks in other `uv_{get,set}_process_title` implementations that require `uv_setup_args`.

Not sure exactly what error should be returned, `UV_ENOBUFS` is just used as an example. Also worth noting that the implementation in `no-proctitle.c` returns `0`:

https://github.com/libuv/libuv/blob/36549815eed297c74448ff580b5c84713245ec5d/src/unix/no-proctitle.c#L35-L45

**Comment by cjihrig** [comment]
What about adding a separate flag variable in that file? I think that would make the intent more clear to people looking at the code in the future.

**Comment by squeek502** [comment]
Sure, that'd work too. Note that there are a few different proctitle implementations for different platforms, and only some of them actually require `uv_setup_args` to be called.

If the concept of returning an error (or just returning early) if `uv_setup_args` hasn't been called on platforms where it is needed seems okay, then I'll draft up a PR for this.

**Comment by cjihrig** [comment]
I can't speak for anyone else, but returning an error seems preferable to crashing to me.

**Comment by bnoordhuis** [comment]
I agree. PR welcome. `UV_ENOBUFS` seems as good as any for the error code.
