### ISSUE TITLE
uv_getaddrinfo() suddenly never got a callback

### ISSUE THREAD

**Issue by Blankwonder** [libuv/libuv#2850]
* **Version**: 1.37.0
* **Platform**: Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

I found my personal proxy server program stopping working one hour ago. Luckily I enabled the debug log so that I can dig into the problem.

From the log file, I discovered that starting from a particular moment all uv_getaddrinfo() invokes never got a callback, no result and no error.

Therefore I tried ping and dig commands on the system, and everything seemed normal. After restarting the program, the problem went away immediately.

My program has running on the server for about a year, and I never encountered this issue before. The difference is that I upgraded libuv to 1.37.0 recently. Sorry, I didn't collect more useful information. Please let me know if there is any other thing I may collect if I reencounter the issue.

**Comment by bnoordhuis** [comment]
Next time it happens, can you attach gdb to the process and run `thread apply all backtrace full`? That should show where it's blocking/hanging.

I'll close this for now but let me know if you have more information.

**Comment by Blankwonder** [comment]
It happened again. Here is the result of thread apply all backtrace full.

[thread_apply_all_bt.txt](https://github.com/libuv/libuv/files/4648240/thread_apply_all_bt.txt)

**Comment by bnoordhuis** [comment]
I don't see a bug here. Libuv called out to `getaddrinfo(3)` from libc and that function is waiting on a reply from the DNS server. The domain names it's trying to resolve are `68375aa58e11424fb1f75208051c36ec.fp.measure.office.com` and `def14f84fb4c4ac3ac4eba009b038d11.fp.measure.office.com`.

I also see a query to `cebf502e.jddebug.com` and that domain name (and `jddebug.com`) fail with SERVFAIL when I try to look them up with dig(1).

**Comment by Blankwonder** [comment]
Sorry, I lost the log file after restarting. I may provide you a more detailed description next time.

Is it possible that libc getaddrinfo() blocked infinitely and caused all subsequent uv_getaddrinfo() calls to fail to get results?

**Comment by bnoordhuis** [comment]
No, but requests can pile up if you submit them faster than the thread pool can dispatch them.
