### ISSUE TITLE
AARC64 fail with random_sync

### ISSUE THREAD

**Issue by hmaarrfk** [libuv/libuv#2867]
* **Version**: 1.38
* **Platform**: Not too sure. Centos 7 on aarch64 bit.

![image](https://user-images.githubusercontent.com/90008/82838734-f369fa00-9e81-11ea-8891-cfc29bd6badc.png)
https://cloud.drone.io/conda-forge/libuv-feedstock/2/1/2

**Comment by bnoordhuis** [comment]
Is it possible for you to strace the process like this?
```
$ strace -s 256 -f build/uv_run_tests_a random_sync random_sync
```

**Comment by hmaarrfk** [comment]
Follow progress here

https://github.com/conda-forge/libuv-feedstock/pull/42

**Comment by hmaarrfk** [comment]
sorry, i don't have this locally, so I would be obliged if you could give me the exact path to the binary to strace

The build commands are here:
https://github.com/hmaarrfk/libuv-feedstock/blob/aarch_reproduce/recipe/build.sh

**Comment by bnoordhuis** [comment]
It's usually in `/usr/bin`. You may need to install the strace package first.

**Comment by hmaarrfk** [comment]
I don't htink it was able to find `build/uv_run_tests_a`. `strace` was found correctly. 

I am going to try to use ls to find the test file.

**Comment by bnoordhuis** [comment]
Sorry, for some reason I thought conda was using the cmake build. The autotools build puts the binary at `test/.libs/run-tests` (on my system anyway.)

**Comment by hmaarrfk** [comment]
Alright, finally got it.

Here is a build with strace running
https://cloud.drone.io/conda-forge/libuv-feedstock/20/1/2

**Comment by bnoordhuis** [comment]
Thanks, the error is this:
```
syscall_0x180(0xfffff7e216f8, 0x100, 0, 0xffffbf0b26c0, 0, 0) = -1 EPERM (Operation not permitted)
write(2, "Assertion failed in test/test-random.c on line 86: 0 == uv_random(NULL, NULL, buf, sizeof(buf), 0, NULL)\n", 105Assertion failed in test/test-random.c on line 86: 0 == uv_random(NULL, NULL, buf, sizeof(buf), 0, NULL)
```
`syscall_0x180` is 384, the right system call for aarch/arm64, but the kernel is returning `EPERM`, _not_ an expected error for `getrandom(2)`.

(Expected errors, like `ENOSYS` or `EAGAIN`, are of course handled by libuv.)

My guess is that either conda is using some kind of frankenkernel that does something funky with system call numbers (unlikely but it wouldn't be the first bug report I receive), or that there is an outdated seccomp2 filter active that's blocking the system call.

Either way, it's something to fix on the affected system, not in libuv. I'll close this out but let me know if you have follow-up questions.
