### ISSUE TITLE
autotools build fail

### ISSUE THREAD

**Issue by Koceto1973** [libuv/libuv#2871]
* **Version**:  1.38.0
* **Platform**: Ubuntu 18.04.4 LTS

make check failed on :
not ok 376 - watcher_cross_stop
# exit code 134
# Output from process `watcher_cross_stop`:
# Assertion failed in test/test-watcher-cross-stop.c on line 87: 0 == uv_udp_bind(&sockets[i], (const struct sockaddr*) &addr, UV_UDP_REUSEADDR)

**Comment by ipbeegle** [comment]
I was getting the same error while building multiple versions. Turns out, the test in question attempts to open 2500 UDP sockets. For me, the fix was to update fs.file-max in /etc/sysctl.conf.

**Comment by Koceto1973** [comment]
Thanks!

Turns out tweaking open sockets capability is quite interesting topic.
