### ISSUE TITLE
C2001 error on chinese windows and vs2019 when using cmake.

### ISSUE THREAD

**Issue by sanjusss** [libuv/libuv#2887]
* **Version**:  Branch 1.x(commit 20756b1) or early
* **Platform**: Windows 10 Pro 2004(Chinese)
* **Compiler**: MSVC2019

On chinese windows, cmake project has an error when compile `test-idna.c`.
![image](https://user-images.githubusercontent.com/8220722/84904000-62351e80-b0e1-11ea-8d86-5bb40f95c5ae.png)
If I take advice of #2581, and add following line in cmakelists.txt:
```cmake
list(APPEND uv_cflags /utf-8 )
```
This will compile successfully.
![image](https://user-images.githubusercontent.com/8220722/84904717-39f9ef80-b0e2-11ea-93a8-922598bd1198.png)

Maybe we can add the following line in cmakelists.txt ?
```cmake
check_c_compiler_flag(/utf-8 UV_LINT_UTF8_MSVC)
set(lint-utf8-msvc $<$<BOOL:${UV_LINT_UTF8_MSVC}>:/utf-8>)
list(APPEND uv_cflags ${lint-utf8-msvc} )
```

**Comment by addaleax** [comment]
@sanjusss Would you mind opening a PR with that suggestion?

**Comment by liyalei66** [comment]
Its a bad idea, /utf-8 option modify execution-charset at the same time, /source-charset:utf-8 option may be better

**Comment by TsXor** [comment]
> Its a bad idea, /utf-8 option modify execution-charset at the same time, /source-charset:utf-8 option may be better

It should be a good idea because libuv need utf-8 parameter for filesystem APIs. (On Windows, these utf-8 parameters are reencoded to utf-16 and passed to wide-character Win32 APIs) If you insist on using your local encoding for execution charset, you will encounter some weird problem.
