### ISSUE TITLE
SIGWINCH sometimes is not delivered to the event loop on OSX 

### ISSUE THREAD

**Issue by tarruda** [libuv/libuv#289]
Neovim uses a small libuv program to test its own terminal emulator: https://github.com/tarruda/neovim/blob/d7e8cd3e30f50f0b335c6675d1704528d80db078/test/functional/job/tty-test.c

When running the functional tests on OSX, I  experience random failures due to the signal callback not being invoked by libuv. I'm sure the signals are being delivered to the program, because the test failures stop when I replace the libuv handler by a sigaction handler.

I have peeked into libuv signal watcher code, and suspect that the problem is related to #217(blocking read to pipe that delivers signals to main thread). Unlike #217, this is much easier to debug(I will see what else I can find out)

**Comment by saghul** [comment]
Now that the TTY bug got fixed in #365 can you re-test this @tarruda ? Thanks!

**Comment by tarruda** [comment]
> Now that the TTY bug got fixed in #365 can you re-test this @tarruda ? Thanks!

I lost my OSX VM with my broken laptop, will do as soon as I reinstall it.

**Comment by saghul** [comment]
No rush! And thanks for the help!

**Comment by whitlockjc** [comment]
I'm running OS X so I'll give this a quick test and update you.

**Comment by whitlockjc** [comment]
When I run the `tarruda/neovim` test suite (`make cmake && make test`)*, I get:

```
Test results:
ALL DONE
```

Here is the patch I used for `tarruda/neovim` to build with a version of `libuv` that has #365's fix in it:

```diff
diff --git a/scripts/get-libuv.sh b/scripts/get-libuv.sh
index 9f3eceb..e33bc57 100644
--- a/scripts/get-libuv.sh
+++ b/scripts/get-libuv.sh
@@ -1,9 +1,9 @@
 . scripts/common.sh
 
-uv_repo=joyent/libuv
-uv_ver=v0.11.19
+uv_repo=libuv/libuv
+uv_ver=v1.7.0
 uv_dir="$deps/uv-$uv_ver"
-uv_sha1=5539d8e99e22b438cf4a412d4cec70ac6bb519fc
+uv_sha1=285d867590157f554e4c17cbbd2dc2153ad11261
 
 rm -rf "$uv_dir"
 

```

I hope this helps.

**Comment by tarruda** [comment]
@whitlockjc I think you used a very old branch(I don't make any effort to keep tarruda/neovim master branch in sync with neovim/neovim), but thanks anyway.

In any case, I have setup a mavericks VM and will try to test this later today.

**Comment by whitlockjc** [comment]
I'll try another branch, that was just the link in the original issue.  I'll update you shortly.

**Comment by whitlockjc** [comment]
Okay, building/testing `neovim/neovim` with `libuv@v1.7.0` results in this appearing to be fixed:

```
549 successes / 0 failures / 0 errors / 5 pending : 4.443104 seconds

Pending → /tmp/neovim/test/functional/job/job_spec.lua @ 326
jobs will only emit the "exit" event after "stdout" and "stderr"

Pending → /tmp/neovim/test/functional/provider/python3_spec.lua @ 5
python3 (or the python3 neovim module) is broken or missing

Pending → /tmp/neovim/test/functional/provider/python_spec.lua @ 5
python (or the python neovim module) is broken or missing

Pending → /tmp/neovim/test/functional/shell/viml_system_spec.lua @ 189
system() with a program that doesn't close stdout skipped (missing xclip)

Pending → /tmp/neovim/test/functional/shell/viml_system_spec.lua @ 368
systemlist() with a program that doesn't close stdout skipped (missing xclip)
[100%] Built target functionaltest
```

I used `make && make test` to perform the build/test and here is the patch I used to test this:

```diff
diff --git a/third-party/CMakeLists.txt b/third-party/CMakeLists.txt
index ff4a11b..9165980 100644
--- a/third-party/CMakeLists.txt
+++ b/third-party/CMakeLists.txt
@@ -69,8 +69,8 @@ endif()
 
 include(ExternalProject)
 
-set(LIBUV_URL https://github.com/libuv/libuv/archive/v1.5.0.tar.gz)
-set(LIBUV_SHA256 f9c6ad4b7a2c90d93c8e09d2e739bb46d199639c4d884ba30323359521b09367)
+set(LIBUV_URL https://github.com/libuv/libuv/archive/v1.7.0.tar.gz)
+set(LIBUV_SHA256 27a66f944c8cf1baf0fb53f5cfe11f01035cc80622d8ecc8e18bd1b2ae35ef5f)
 
 set(MSGPACK_URL https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz)
 set(MSGPACK_SHA256 afda64ca445203bb7092372b822bae8b2539fdcebbfc3f753f393628c2bcfe7d)

```

**Comment by tarruda** [comment]
@whitlockjc there's one more thing: You need to reactivate the libuv signal watcher in the tty test program. The master version switched to `sigaction` to work around the problem so the tests will always pass on OSX. This patch should do it:

```diff
diff --git a/test/functional/fixtures/tty-test.c b/test/functional/fixtures/tty-test.c
index 40ba131..bc75574 100644
--- a/test/functional/fixtures/tty-test.c
+++ b/test/functional/fixtures/tty-test.c
@@ -31,21 +31,14 @@ static void walk_cb(uv_handle_t *handle, void *arg) {
   }
 }

-static void sigwinch_handler(int signum)
+static void sigwinch_cb(uv_signal_t *handle, int signum)
 {
   int width, height;
-  uv_tty_get_winsize(&tty, &width, &height);
+  uv_tty_t *tty = handle->data;
+  uv_tty_get_winsize(tty, &width, &height);
   fprintf(stderr, "rows: %d, cols: %d\n", height, width);
 }

-// static void sigwinch_cb(uv_signal_t *handle, int signum)
-// {
-//   int width, height;
-//   uv_tty_t *tty = handle->data;
-//   uv_tty_get_winsize(tty, &width, &height);
-//   fprintf(stderr, "rows: %d, cols: %d\n", height, width);
-// }
-
 static void alloc_cb(uv_handle_t *handle, size_t suggested, uv_buf_t *buf)
 {
   buf->len = BUF_SIZE;
@@ -130,20 +123,15 @@ int main(int argc, char **argv)
   uv_prepare_t prepare;
   uv_prepare_init(uv_default_loop(), &prepare);
   uv_prepare_start(&prepare, prepare_cb);
-  // uv_tty_t tty;
+  uv_tty_t tty;
   uv_tty_init(uv_default_loop(), &tty, fileno(stderr), 1);
   uv_tty_set_mode(&tty, UV_TTY_MODE_RAW);
   tty.data = &interrupted;
   uv_read_start((uv_stream_t *)&tty, alloc_cb, read_cb);
-  struct sigaction sa;
-  sigemptyset(&sa.sa_mask);
-  sa.sa_flags = 0;
-  sa.sa_handler = sigwinch_handler;
-  sigaction(SIGWINCH, &sa, NULL);
-  // uv_signal_t sigwinch_watcher;
-  // uv_signal_init(uv_default_loop(), &sigwinch_watcher);
-  // sigwinch_watcher.data = &tty;
-  // uv_signal_start(&sigwinch_watcher, sigwinch_cb, SIGWINCH);
+  uv_signal_t sigwinch_watcher;
+  uv_signal_init(uv_default_loop(), &sigwinch_watcher);
+  sigwinch_watcher.data = &tty;
+  uv_signal_start(&sigwinch_watcher, sigwinch_cb, SIGWINCH);
   uv_run(uv_default_loop(), UV_RUN_DEFAULT);

   return 0;
```

Since you seem interested in helping, here's what you could do:

1 - Apply this patch without upgrading libuv version(rm -rf .deps to reinstall dependencies) and run the test a few times to see if the problem appears.
2 - Upgrade libuv(apply your patch) and run the tests a few times to ensure the problem goes away.

**Comment by whitlockjc** [comment]
Sounds like a plan.  I'll update you when I get this tested.  *(Should be by EOD)*

**Comment by whitlockjc** [comment]
So, with your patch in place to activate using libuv, the test suite failed every time I ran it.  With my patch in place to upgrade libuv to `v1.7.0` which includes the fix @saghul referenced in #365, the test suite runs without failure: `549 successes / 0 failures / 0 errors / 5 pending : 4.824798 seconds`.

**Comment by tarruda** [comment]
@whitlockjc thanks for your help!

@saghul closing as the issue has been fixed.

**Comment by whitlockjc** [comment]
@tarruda Feel free to reopen if you find otherwise.  I'll be glad to help.

**Comment by saghul** [comment]
Thanks for the confirmation folks! :heart_eyes:
