### ISSUE TITLE
document more precise semantics for uv_async_send

### ISSUE THREAD

**Issue by jfirebaugh** [libuv/libuv#29]
The documentation for uv_async_send states:

> calling this function may not wakeup the event loop if it was already called previously within a short period of time

"within a short period of time" does not meaningfully strengthen the contract of uv_async_send; based on this documentation, one must assume that the following is a possible sequence of execution:

| Event loop thread | Second thread |
| --- | --- |
|  | uv_async_send |
| callback execution begins |  |
| callback execution completes |  |
|  | uv_async_send |
| (callback never executed a second time) |  |

Is that indeed a possible sequence of execution? If so, I suggest replacing the text "within a short period of time" with "for the given async handle", making it clearer that the strongest guarantee made is that the callback will be executed once, ever.

If uv_async_send actually makes stronger guarantees, then please document them precisely. For example, a useful stronger guarantee would be that the callback is executed consistent with a model where uv_async_send atomically sets a "needs execution" flag, and the event loop atomically resets this flag before running the callback. That would rule out the sequence of execution above.

**Comment by saghul** [comment]
@jfirebaugh can you have a look at #122 ?
