### ISSUE TITLE
Can the non-cmake osx ci job be removed?

### ISSUE THREAD

**Issue by AshCripps** [libuv/libuv#2903]
https://ci.nodejs.org/job/libuv-test-commit-osx/ doesn't seem to be used anymore.

as part of https://github.com/nodejs/build/issues/2315#issuecomment-652919983 I need to decomission the old osx1010 osx1011 machines and remove them from the CI so as part of that I can clean up some jobs whilst im at it.

**Comment by richardlau** [comment]
Yeah, it's the old gyp-based build. I thought I had disabled it (obviously have not, or it was reenabled).

I'd like to say we could get rid of it but we still have gyp files in `master` so cc @libuv/collaborators just to make sure.

**Comment by bnoordhuis** [comment]
It's fine to remove. The master branch isn't tested right now and it's overdue for a sync with v1.x in any case.

**Comment by AshCripps** [comment]
Ok ill remove the job later today

**Comment by AshCripps** [comment]
Job deleted
