### ISSUE TITLE
The windows console does support UTF-16 surrogate pairs now

### ISSUE THREAD

**Issue by DHowett** [libuv/libuv#2909]
* **Version**: 032f2b1251be842438bfed6e688ef874bf85254c
* **Platform**: Windows 10.0.10240+

There's an assertion in src/win/tty.c above a block of code that destroys high unicode, to the effect of ...

https://github.com/libuv/libuv/blob/032f2b1251be842438bfed6e688ef874bf85254c/src/win/tty.c#L2125-L2130

According to blame, that comment was written nine years ago. It handily predates Windows 10 and unfortunately puts an arrow in the knee of any application that wants to take advantage of our much-expanded UTF-16 (and UTF-8!) support. :smile:

**Comment by bnoordhuis** [comment]
Thanks for bringing that to our attention. Can you take a look at #2910?

**Comment by DHowett** [comment]
(Keeping the issue fresh so stalebot doesn't close it.)

**Comment by nu8** [comment]
As a workaround, this works as expected:

~~~
PS C:\> deno.exe
Deno 1.3.2
exit using ctrl+d or close()
> '📕📙' + '📒📗'
📕📙📒📗
~~~

https://github.com/denoland/deno
