### ISSUE TITLE
uv_cpu_info fails on Darwin ARM64

### ISSUE THREAD

**Issue by Keno** [libuv/libuv#2911]
Darwin ARM64 appears to be missing the `hw.cpufrequency` sysctl, causing uv_cpu_info to fail.
I'm thinking this might just be an oversight, so I've submitted a ticket with Apple (FB7917120),
but I figured it would be worth filing an issue here as well to track the issue.

**Comment by bnoordhuis** [comment]
Related: https://github.com/nodejs/node/pull/34238 - that PR is currently floating a libuv patch to work around this issue.

**Comment by bnoordhuis** [comment]
I've opened #2912 with a possible workaround. Can you take a look?

cc @evanlucas

**Comment by evanlucas** [comment]
I opened https://github.com/libuv/libuv/pull/2914 in addition. 

cc @bnoordhuis @Keno

**Comment by cjihrig** [comment]
Are there any other known issues on Apple Silicon? In other words, do we think it's OK to claim support in the next release?

**Comment by Keno** [comment]
No known issues on our end with libuv, though our test suite is not 100% functional yet on Apple Silicon, so we may have missed something.

**Comment by evanlucas** [comment]
With V8 8.5, node's full test suite passes as well. From what I've seen, this was the only thing that didn't work.
