### ISSUE TITLE
fs: clobber req->path on uv_fs_mkstemp() error

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2913]
Refs: https://github.com/nodejs/node/pull/33549
```c
if (-1 === mkstemp(req->path)) {
  // req->path can contain garbage now
}
```
POSIX allows (but doesn't mandate) the input/output buffer to get clobbered on error, and AIX indeed does so.

To flush out portability bugs in downstream users, make libuv always clobber the buffer on error.

Alternatively, preserve `req->path` by operating on a copy, but that needs dynamic memory allocation and incurs the (probably minor) performance hit of two memcpys.

**Comment by tjarlama** [comment]
@bnoordhuis I would like to work on this. Can I go ahead with the first solution?
Have some doubts
- req->path should be clobbered regardless of the errno (EEXIST or EINVAL, man(3) mkstemp) in unix 
- By clobbering, you mean the entire string to be rewritten or just the first character to '\0' is fine 
- This needs to be done for both unix and windows

**Comment by bnoordhuis** [comment]
@tjarlama

1. Correct.
2. Either is fine.
3. Correct.
