### ISSUE TITLE
test: fix double evaluation in ASSERT macros

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2916]
https://github.com/libuv/libuv/blob/e0cb4f06c9c171028092f3cb515e4523eb824066/test/task.h#L179-L182

https://github.com/libuv/libuv/blob/e0cb4f06c9c171028092f3cb515e4523eb824066/test/task.h#L114-L130

`a` and `b` are evaluated twice in case of failure which can make for confusing errors:
```c
int evil(void) {
  static int x;
  return x++;
}

void test(void) {
  ASSERT_EQ(1, evil());  // fails but prints "(1 == 1)"
}
```
cc @santigimeno

**Comment by tjarlama** [comment]
@bnoordhuis If no one else is working on this, I can pick this up.
I can think of 2 solutions:
- Removing a and b from fprintf statement. This will be a minor change and won't affect anything, but might make debugging harder.
- Redefine `ASSERT_BASE` without `expr` and declare 2 variables inside do-while block to store results of a and b. I don't think this will violate any contribution guidelines and can print result of both a and b. But this require update on all the places where `ASSERT_BASE` macro is directly called.

**Comment by bnoordhuis** [comment]
@tjarlama I'd go for option 2. There are only a handful of direct `ASSERT_BASE` uses.

**Comment by tjarlama** [comment]
@bnoordhuis Submitted a fix for this on above mentioned pull request, review whenever you are free
