### ISSUE TITLE
half of qemu bots appear to be broken

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#2937]
https://github.com/libuv/libuv/runs/933150970
```
not ok 118 - getaddrinfo_basic
# exit code 139
# Output from process `getaddrinfo_basic`:
# qemu: uncaught target signal 11 (Segmentation fault) - core dumped
ok 119 - getaddrinfo_basic_sync # SKIP Test does not currently work in QEMU
not ok 120 - getaddrinfo_concurrent
# exit code 139
# Output from process `getaddrinfo_concurrent`:
# qemu: uncaught target signal 11 (Segmentation fault) - core dumped
not ok 121 - getaddrinfo_fail
# exit code 139
# Output from process `getaddrinfo_fail`:
# qemu: uncaught target signal 11 (Segmentation fault) - core dumped
ok 122 - getaddrinfo_fail_sync # SKIP Test does not currently work in QEMU
```

@gengjiawen Any idea what's happening here, as it looks like you had marked some of the other nearby tests as skipped.

**Comment by gengjiawen** [comment]
Looks like ubuntu update qemu to `qemu-user-static_4.2-3ubuntu10_amd64.deb` [(ci)](https://github.com/libuv/libuv/runs/933150789#step:3:14), we may lock qeme version to prevent this issue (like `qemu-user-static_4.2-3ubuntu9_amd64.deb`).

**Comment by gengjiawen** [comment]
Looks ubuntu doesn't keep old version like `qemu-user-static_4.2-3ubuntu9_amd64.deb` or `qemu-user-static_4.2-3ubuntu8_amd64.deb`.
