### ISSUE TITLE
node.js crash on OS X Mavericks in threadpool.c, "assertion failed", from node v0.10.35

### ISSUE THREAD

**Issue by vielmetti** [libuv/libuv#294]
I'm running this:

Darwin edwards-air 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
OS X 10.9.5
27 Mar 23:51:33 - [info] Node-RED version: v0.10.4
27 Mar 23:51:33 - [info] Node.js  version: v0.10.35
and after some period of time running, node crashes unexpectedly with

Assertion failed: (uv__has_active_reqs(req->loop)), function uv__queue_done, file ../deps/uv/src/unix/threadpool.c, line 236.
Abort trap: 6
It seems to be coming from libuv, related to this discussion

https://groups.google.com/forum/#!topic/libuv/2ia9S7wuZX0

I'm going to post something similar to http://github.com/node-red/node-red and see what they know about it.

**Comment by vielmetti** [comment]
Also noted at https://github.com/node-red/node-red/issues/601

**Comment by saghul** [comment]
Please paste a minimal test case (with no dependencies) which reproduces
the problem.

**Comment by vielmetti** [comment]
Thanks @saghul.  I think I've isolated it down to one particular library, and opened https://github.com/sandeepmistry/node-xpc-connection/issues/7 to track the detail there; still no minimal test case available yet.

**Comment by vielmetti** [comment]
Thanks to @saghul we identified the underlying problem at https://github.com/sandeepmistry/node-xpc-connection/issues/7#issuecomment-87578397 which boils down to 

"handleEvent calls uv_queue_work, which is not thread-safe, so things will eventually blow up"

Closing this issue here, we'll track it there. thanks!

**Comment by sarkiroka** [comment]
Can you show a *simple* example for a native trigger (for example posix message queue, or any interrupt, or timer, or anything) send an event to nodejs thread safe way?
I use uv_queue_work too, and sometimes my code are core dumped.
