### ISSUE TITLE
One of tests fails (not ok 275 - tcp_connect_timeout) on Ubuntu 20.04

### ISSUE THREAD

**Issue by vvidovic** [libuv/libuv#2940]
* **Version**:
libuv-v1.38.1

* **Platform**:
```
$ uname -a
Linux box 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

After building libuv as a local user and running `make check` one of the tests failed. Here is (cut) output with error messages:
```
$ make check
make  test/run-tests
...
not ok 275 - tcp_connect_timeout
# exit code 134
# Output from process `tcp_connect_timeout`:
# Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
...
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5353: check-TESTS] Error 1
make[1]: Leaving directory '/home/***/libuv-v1.38.1'
make: *** [Makefile:5613: check-am] Error 2
```

Please let me know if I need to send more info.

**Comment by bnoordhuis** [comment]
That test connects to 8.8.8.8:9999, an address that's normally unreachable and times out after a while. However, if you have something in your network topology (firewall, router, etc.) that cuts the TCP handshake short, the test fails.

You can check with `nc 8.8.8.8 9999` - it should time out but only after several minutes have passed.

**Comment by vvidovic** [comment]
Hi, after testing few times network connectivity with nc, I can confirm that this test sometimes timeout and sometimes succeed:
```
$ time nc -v 8.8.8.8 9998
Connection to 8.8.8.8 9998 port [tcp/*] succeeded!

real	0m3,076s
user	0m0,003s
sys	0m0,000s
...
$ time nc -v 8.8.8.8 9999
nc: connect to 8.8.8.8 port 9999 (tcp) failed: Connection timed out

real	2m10,335s
user	0m0,003s
sys	0m0,000s
```

When I run `make check` for the third time, all tests passed (after that they were mostly but not always failing).

I am not sure why would a connection to port 9999 on Google DNS sometimes succeed but it is obviously something specific with my environment.
I will close this since it seems it is something specific to my local network environment, thanks.
