### ISSUE TITLE
Using libuv with node-gyp on Windows

### ISSUE THREAD

**Issue by MadLittleMods** [libuv/libuv#295]
I was able to get libuv working in a Visual Studio project and I wrote up an article, [*Using libuv with Windows and Visual Studio: Getting Started*](http://ericeastwood.com/blog/24/using-libuv-with-windows-and-visual-studio-getting-started), explaining how I got it all set up and working.

I am now wanting to build with [node-gyp](https://www.npmjs.com/package/node-gyp) but I am running into some issues.

I am getting syntax errors when building with node-gyp like `..\..\uv\src\win\tty.c(173): error C2146: syntax error : missing ')' before identifier 'mode'`

*[Full verbose build output pastebin](http://pastebin.com/wyXT0wRQ): `node ../node_modules/node-gyp/bin/node-gyp.js build --verbose`*

I am using the latest code from the v1.x branch. I also tried the [1.4.2 release on libuv.org](http://libuv.org/dist/v1.4.2/). I have also tried with and without running vcbuild.bat.

What do I need to do to get a successful build?

I checked the [io.js source](https://github.com/iojs/io.js/blob/5094a0fde3c3e8925f6f9cb7ff0e65e527a4845e/node.gyp), etc to try to find what they are doing but nothing jumped out at me.

---

### `binding.gyp`
```
{
	"targets": [
		{
			'target_name': 'test',
			'type': 'executable',
			'sources': [
				'main.cpp'
			],
			"dependencies": [
				"uv/uv.gyp:libuv"
			]
		}
	]
}
```

### `main.cpp`

```
#pragma comment (lib, "libuv.lib")
#pragma comment (lib, "ws2_32.lib")
#pragma comment (lib, "psapi.lib")
#pragma comment (lib, "Iphlpapi.lib")


#include <iostream>
//#include <stdio.h>
#include <string.h>
//#include <unistd.h>
//#include <io.h>
#include <uv.h>

#include <regex>


std::string stripAnsiEscapeCodes(std::string input) {
	// from: https://github.com/sindresorhus/ansi-regex/blob/47fb974630af70998157b30fad6eb5e5bd7c7cd6/index.js
	std::regex reg("(?:(?:\033\\[)|\233)(?:(?:[0-9]{1,3})?(?:(?:;[0-9]{0,3})*)?[A-M|f-m])|\033[A-M]");
	std::string output = std::regex_replace(input, reg, "");

	return output;
}

void ccout(std::string message, uv_write_t* req, uv_stream_t* handle) {
	// If the terminal doesn't support ANSI, strip it for clarity
	if (uv_guess_handle(1) != UV_TTY) {
		message = stripAnsiEscapeCodes(message);
	}

	uv_buf_t buf;
	buf.base = (char*)message.c_str();
	buf.len = strlen(buf.base);
	uv_write(req, handle, &buf, 1, NULL);
};



uv_loop_t *loop;
uv_tty_t tty;
int main() {
	loop = uv_default_loop();

	uv_tty_init(loop, &tty, 1, 0);
	uv_tty_set_mode(&tty, UV_TTY_MODE_NORMAL);

	ccout("\033[41;37mHello TTY\n\033[0m", &uv_write_t(), (uv_stream_t*)&tty);
	ccout("asdf\n", &uv_write_t(), (uv_stream_t*)&tty);
	ccout("qwer\n", &uv_write_t(), (uv_stream_t*)&tty);

	// To be called when the program exits. Resets TTY settings to default values for the next process to take over.
	uv_tty_reset_mode();
	return uv_run(loop, UV_RUN_DEFAULT);

	return 0;
}
```

**Comment by saghul** [comment]
What libuv version are you using? Please use latest code from the v1.x branch, this should be fixed and will be part of the next release.

**Comment by MadLittleMods** [comment]
I have been using the latest code form the v1.x branch that I checked out two days ago. I have also tried the [1.4.2 release on libuv.org](http://libuv.org/dist/v1.4.2/). I have also tried with and without running vcbuild.bat.

**Comment by rmg** [comment]
@MadLittleMods at the moment there have been [30 commits since 1.4.2 was released](https://github.com/libuv/libuv/compare/v1.4.2...v1.x). I believe @saghul is suggesting you use git or a GitHub generated snapshot such as https://github.com/libuv/libuv/archive/v1.x.zip to get the latest unreleased version.

**Comment by MadLittleMods** [comment]
@rmg I tried that and this is what I mean by "Full verbose build output from latest code from v1.x branch". 

I also just tried the release you linked and got a bunch of errors as well: http://pastebin.com/cVr6jcjC

**Comment by rmg** [comment]
Sorry, misread your comment.

Are you able to build the sample app? https://github.com/libuv/libuv/tree/v1.x/samples/socks5-proxy

**Comment by MadLittleMods** [comment]
@rmg The socks5-proxy sample produces a lot of errors when trying to build with node-gyp: http://pastebin.com/A2Lp2BnS

**Comment by saghul** [comment]
Maybe @piscisaureus can help?

**Comment by piscisaureus** [comment]
If you build a node addon, the version of libuv that ships with that particular version of node is automatically included. However you're trying to link in *another* version of libuv, so the function and type definitions that you're trying to get from `uv.h` conflict with those that are automatically included.

In other words, don't include libuv as part of your node addon. Just include <node.h> and you'll be able to use the libuv functions that you.

My guess is that the socks5 example may be a little outdated and needs updating to match the latest libuv api.

**Comment by MadLittleMods** [comment]
@piscisaureus I am using node-gyp to build a C++ project (not make a node addon).

I want to build that `main.cpp` file in the original issue message.

**Comment by piscisaureus** [comment]
@MadLittleMods 

You probably shouldn't be using node-gyp to build something that's not an addon (I think there are other tools on npm similar to node-gyp that support this use case). 

But if you insist, please try putting the full path to `uv.h` in the `#include` statement. I think node-gyp is setting up your include path such that main.cpp pick the wrong uv.h.

**Comment by MadLittleMods** [comment]
@piscisaureus I tried out [`gypjs`](https://www.npmjs.com/package/gypjs) and [`notnode-gyp`](https://www.npmjs.com/package/notnode-gyp). `gypjs` does the same thing as `node-gyp` but it is just a fork. `notnode-gyp` just doesn't work and errors out no matter what (problem with the package itself).

Back to `node-gyp`: I am not sure how get the full path to `uv.h` because I am using the including it as a gyp module in binding.gyp `"uv/uv.gyp:libuv"`. Should I be using the `include` folder and `libuv.lib` file?

**Comment by piscisaureus** [comment]
@MadLittleMods 

1) Did you try [gypjs](https://www.npmjs.com/package/gypjs)

In the log files you posted, see the following line:
```
 C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\CL.exe /c /I"C:\Users\madli_000\.node-gyp\0.12.1\src" /I"C:\Users\madli
  _000\.node-gyp\0.12.1\deps\uv\include" /I"C:\Users\madli_000\.node-gyp\0.12.1\deps\v8\include" /I..\..\uv\include /I..\..\uv\src /Zi /nologo
   /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D BUILDING_V8_SHARED=1 /D BUILDING_UV_
  SHARED=1 /D _WIN32_WINNT=0x0600 /D _GNU_SOURCE /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /GR- /Fo"Release\obj\libuv\\" /Fd"R
  elease\obj\libuv\vc120.pdb" /Gd /TC /wd4351 /wd4355 /wd4800 /wd4251 /errorReport:queue /MP ..\..\uv\src\win\getaddrinfo.c ..\..\uv\src\win\tty.c
```

As you can see, the include directories as specified on the command line are:
* `/I"C:\Users\madli
  _000\.node-gyp\0.12.1\deps\uv\include"`
* `/I..\..\uv\include`

In other words, the include directory for libuv as bundled with node 0.12 is added *before* the include directory of your own libuv checkout. That means that when you're compiling libuv itself it'll still pick up the wrong `uv.h` file.

I don't know how to fix that. My suggestion would be to try gypjs and if that doesn't work just use gyp proper.

**Comment by MadLittleMods** [comment]
@piscisaureus Thank you the insight and pointing out exactly what is going wrong! *I tried `gypjs` and same problems (see results in earlier post).*

I tried to stop fighting node-gyp and not use my libuv dependency(remove from gyp config) and instead try to piggyback off of their version. Found out that [node-v0.12.1 uses libuv-v1.0.2 stable](https://github.com/joyent/node/blob/0034086b49f22cfde765a7e9f55db25f8eb310b6/deps/uv/ChangeLog#L1). I get a `UV_TTY_MODE_NORMAL` undeclared identifier error which assume is just a API change and I have no idea what the equivalent would be in 1.0.2. [Haven't tried but maybe this (old uvbook commit)](https://github.com/nikhilm/uvbook/blob/8d9e10b0363302a86f7d8e5a35998c29d7d50825/code/tty/main.c)

Another thing I tried was removing the libuv included from `node-gyp` by going into `./node_modules/node-gyp/addon.gypi` and commenting out(use hash/pound `#`) the `include_dirs`. Then adding back the dependency to my libuv version. **This results in a successful build but outputs nothing?**

```
{
  'target_defaults': {
    'type': 'loadable_module',
    'product_prefix': '',
    'include_dirs': [
      #'<(node_root_dir)/src',
      #'<(node_root_dir)/deps/uv/include',
      #'<(node_root_dir)/deps/v8/include'
    ],
# more gyp after this ....
````

**Comment by saghul** [comment]
Closing, since it's not a libuv issue.

**Comment by MadLittleMods** [comment]
I am still interested in a solution but I understand the close.

**Comment by aazavid** [comment]
Did you manage to solve the problem?

**Comment by MadLittleMods** [comment]
@aazavid I don't think so, just used Visual Studio
