### ISSUE TITLE
Get time left from timer

### ISSUE THREAD

**Issue by ulrikstrid** [libuv/libuv#2950]
I wanted to implement a debounce function using a timer but it seems like we can't get the time left.
Am I missing something or is it not possible with the current API?

**Comment by bnoordhuis** [comment]
I think a pull request implementing that functionality is welcome.

The catch is that the timeout is stored as the event loop's idea of the current time + the timeout, i.e., as absolute time. To derive the remaining time, you have to compute `handle->timeout - loop->time` and check it's >= 0.

**Comment by richardlau** [comment]
For reference, diagnostic report in Node.js and its predecessor `node-report` do just that to derive the remaining time but the `timeout` field (`due` on older versions of libuv on Windows) on the timer handle isn't public.

https://github.com/nodejs/node/blob/84b35b286769758610173291c6e9fd9eebdaaf1f/src/node_report_utils.cc#L150-L157

https://github.com/nodejs/node-report/blob/b19df9b4f8f3fce58c7fa2408b2bf2060781515e/src/utilities.cc#L468-L490

There's a previously abandoned attempt at adding an API: https://github.com/libuv/libuv/pull/1255
