### ISSUE TITLE
build in（windows subsystem for linux)WSL error

### ISSUE THREAD

**Issue by kaonicaoni** [libuv/libuv#2958]
* **Version**: 
* **Platform**: 

error tips:

not ok 46 - fs_chmod
not ok 47 - fs_chown
not ok 58 - fs_event_watch_dir
not ok 61 - fs_event_watch_file_current_dir
not ok 67 - fs_file_nametoolong
not ok 77 - fs_mkdtemp
not ok 78 - fs_mkstemp
not ok 105 - fs_statfs
...

FAIL: test/run-tests

make[1]: *** [Makefile:5454: check-TESTS] Error 1
make[1]: Leaving directory '/mnt/e/myth/libuv1.x/libuv-1.x'
make: *** [Makefile:5714: check-am] Error 2

**Comment by bzoz** [comment]
`make[1]: Leaving directory '/mnt/e/myth/libuv1.x/libuv-1.x'`

Can you try running the build and tests on a Linux filesystem?

Also - please provide Windows version, WSL version and libuv version you are trying to build.
