### ISSUE TITLE
Stdio redirection with UV_CREATE_PIPE on Cygwin doesn't work when spawning non-Cygwin child processes

### ISSUE THREAD

**Issue by DDoSolitary** [libuv/libuv#2961]
* **Version**: 1.38.1
* **Platform**: Cygwin

Currently when `uv_spawn()` is called with `uv_stdio_flags` set to `UV_CREATE_PIPE`, `socketpair()` is used to create "pipes" to communicate between parent and child. However, it seems that on Cygwin the underlying socket handles are opened with "OVERLAPPED" flags set. It means that normal Win32 programs, expecting normal stdio handles, will fail to read from/write to them.

<details>
<summary>Minimal working example</summary>
The following simple programs can demonstrate how this will fail. They're not written with libuv but they work in the same way as libuv regarding stdio redirection and can show how libuv will fail.

- `parent.c`: Compile with Cygwin

  ```c
  #include <assert.h>
  #include <string.h>
  #include <stdbool.h>
  #include <sys/types.h>
  #include <sys/socket.h>
  #include <sys/wait.h>
  #include <unistd.h>
  #include <fcntl.h>
  
  int main() {
  	int fds[2];
  	assert(-1 != socketpair(AF_UNIX, SOCK_STREAM, 0, fds));
  	int pid = fork();
  	assert(-1 != pid);
  	if (pid == 0) {
  		assert(-1 != close(fds[0]));
  		assert(-1 != dup2(fds[1], STDIN_FILENO));
  		assert(-1 != close(fds[1]));
  		char exe[] = "./child.exe";
  		execl(exe, exe, (char *)NULL);
  		assert(false);
  	}
  	assert(-1 != close(fds[1]));
  	char data[] = "foo";
  	assert(-1 != write(fds[0], data, strlen(data)));
  	int stat;
  	assert(-1 != waitpid(pid, &stat, 0));
  	assert(WIFEXITED(stat));
  	assert(0 == WEXITSTATUS(stat));
  }
  ```

- `child.c` Compile with MSVC or MinGW

  ```c
  #include <assert.h>
  #include <stdio.h>
  #include <Windows.h>
  #include <io.h>
  
  int main() {
  	HANDLE h = GetStdHandle(STD_INPUT_HANDLE);
  	assert(h != INVALID_HANDLE_VALUE);
  	char buf[1024];
  	DWORD len = 0;
  	// Most runtimes do this indirectly to read from stdin. Just to be explicit
  	// here.
  	ReadFile(h, buf, 1024, &len, NULL);
  	// Will give 87 (ERROR_INVALID_PARAMETER) here because Cygwin gives it an
  	// "OVERLAPPED" handle but ReadFile is called with lpOverlapped = NULL.
  	printf("%d\n", GetLastError());
  }
  ```
  </details>

**Comment by DDoSolitary** [comment]
It seems that if I change `socketpair()` to `pipe()`, the child process will be able to access it normally. While unnamed pipes can only send data in one direction, it is acceptable for stdio redirection, and we can check if the user requests a unidirectional pipe (when only one of `UV_READABLE_PIPE` and `UV_WRITABLE_PIPE` is set) and use `pipe` in that case.

(I'm happy to send a PR it this change is acceptable)

**Comment by DDoSolitary** [comment]
@vtjnash It seems that the PR you linked doesn't change the current behavior but exports the pipe and socketpair functions. Does it mean that users are expected to call uv_pipe and pass the created fd to uv_spawn if they want unnamed pipes for stdio redirection?

**Comment by vtjnash** [comment]
Yes, `UV_CREATE_PIPE` is only capable the most basic use cases. Those cases are common, but inflexible, so JuliaLang eventually stopped using it entirely (though it's still useful for `ipc`, which is its primary design use case).

**Comment by DDoSolitary** [comment]
@vtjnash Got it. Thanks for the explanation.
