### ISSUE TITLE
test: switch to ASSERT_EQ etc. macros

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#2974]
Wanted to discuss this before opening a PR: is everyone okay with a bulk conversion from the old-style ASSERT macro to the new-style ASSERT_EQ, ASSERT_NE, etc. macros?

It'll cause a bit of churn in `test/` but it should make debugging tests a lot easier.

**Comment by santigimeno** [comment]
I'm all for it. 👍

**Comment by cjihrig** [comment]
Also +1

**Comment by richardlau** [comment]
+1 for making it easier to debug test failures.

**Comment by bnoordhuis** [comment]
I haven't had time to work on this. For anyone wanting to pick this up, it should be a fairly mechanical translation - just try to ensure lines stay <= 80 columns. :-)

**Comment by tjarlama** [comment]
Picking this up

**Comment by leonerd** [comment]
Unknowingly, I have mostly done this in #3042; though it seems I still have to do some different macros for unsigned int or pointer tests.

**Comment by Pleuvens** [comment]
I'm thinking of picking this up if it is okay for everyone

**Comment by Pleuvens** [comment]
There will be a lot of changes in this issue and I was thinking about doing this progressively. I would you like to review ?

**Comment by bnoordhuis** [comment]
I'd do it in one fell swoop because reviewing e.g. one PR per file is uber tedious. The test suite doesn't change so often that merge conflicts should be a big issue.
