### ISSUE TITLE
possible typo for UV__EPROTO defined in include/uv/error.h

### ISSUE THREAD

**Issue by Gyumeijie** [libuv/libuv#2977]
* **Version**:  43c74a6 
* **Platform**:  UNIX

file: [include/uv/errno.h](https://github.com/libuv/libuv/blob/fa8b4f27c023638918e645ef997c3b56a3a5e681/include/uv/errno.h#L320)
line: 317-321 
```cpp 
#if defined(EPROTO) && !defined(_WIN32)
# define UV__EPROTO UV__ERR(EPROTO)
#else
# define UV__EPROTO UV__ERR(4046)
#endif
```

I notice that all errors defined in  `errno.h` are negative except the above one, is it intented or just a typo?

**Comment by cjihrig** [comment]
It looks like a typo in https://github.com/libuv/libuv/commit/89cbbc895bb459c6ab5319fa86a32a9fecbf8744. Do you want to send a PR?

**Comment by Gyumeijie** [comment]
Yes, I have already created a PR https://github.com/libuv/libuv/pull/2979, and all checks have passed
