### ISSUE TITLE
uv__threadpool_cleanup non-op on Windows?

### ISSUE THREAD

**Issue by jasnell** [libuv/libuv#2980]
In Node.js, it looks like we've had a long standing bug when running threadpool jobs. See https://github.com/nodejs/node/pull/35021 for discussion. Calling `uv_library_shutdown()` resolves the problem on non-Windows systems by ensuring that threadpool jobs are shutdown properly. However, I notice that `uv__threadpool_cleanup()` is currently a [non-op on `_WIN32`](https://github.com/libuv/libuv/blob/v1.x/src/threadpool.c#L163-L185) and it's not entirely clear why.

Removing the `#ifndef _WIN` guards in `uv__threadpool_cleanup()` fixes the bug for me locally (Windows 10, VS19). I can open a PR but before I do I wanted to see if there was a specific reason the function was a made a non-op.

/cc @bnoordhuis @cjihrig @addaleax

**Comment by addaleax** [comment]
c8abb29f68abf64bacf2dc5a483eedab84b52428 changed this in 2014, but since we’re using `__attribute__((destructor))` on `uv_library_shutdown()`, I’m assuming that this isn’t being automatically run on Windows anyway.

I think just removing the `#ifdef` should be fine.

**Comment by richardlau** [comment]
https://github.com/libuv/libuv/commit/c8abb29f68abf64bacf2dc5a483eedab84b52428 is one of two commits from https://github.com/joyent/libuv/pull/1381.

**Comment by jasnell** [comment]
@addaleax :
> I think just removing the #ifdef should be fine.

Yeah, not seeing anything in local testing that would suggest otherwise. I'll get a PR opened.
