### ISSUE TITLE
Does uv_poll_t can monitor the same fd with different events  at the same time? (linux os)

### ISSUE THREAD

**Issue by lucas-law** [libuv/libuv#2987]
for example:
fd : 5
uv_poll_init(loop, uv_poll_handler, fd);
uv_poll_start(uv_poll_handler, UV_READ_EVENT, on_read_event_cb);

uv_poll_init(loop, uv_poll_handler, fd);
uv_poll_start(uv_poll_handler, UV_WRITE_EVENT, on_write_event_cb);

**Comment by vtjnash** [comment]
No, you need to use the same uv_poll_t and one uv_poll_start call. You may wish to handle that with your wrapper library for convenience.

**Comment by lucas-law** [comment]
ok, thank you.
