### ISSUE TITLE
pkg-config returning wrong data for static linking

### ISSUE THREAD

**Issue by hmel** [libuv/libuv#2988]
The cmake build creates a static library with the name libuv_a.a, but running with `pkg-config --static --libs libuv` returns -luv which then is not found by linker.

**Comment by bnoordhuis** [comment]
Right, that's something I overlooked when switching to cmake.

CMakeListst.txt has two library targets, `uv` and `uv_a`, to allow building the shared and the static library at the same time.

Unfortunately, I don't know of a good way to inform pkg-config that the static library has a different name. I don't think it has e.g. a `Libs.static:` field.

I'm open to suggestions, as long as they're not variations on "drop the `uv_a` target." :-)

**Comment by hmel** [comment]
I'm no expert myself, but pkg-config has Libs.private which I think is what is needed in the .pc file.
On my system, for example, I have in vulcan.pc
```prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: Vulkan-Loader
Description: Vulkan Loader
Version: 1.2.141
Libs: -L${libdir} -lvulkan
Libs.private:  -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
Cflags: -I${includedir}
```
and the output is

```
$ pkg-config --libs --static vulkan.pc
-lvulkan -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
```
and
```
$ pkg-config --libs vulkan.pc
-lvulkan
```

**Comment by bnoordhuis** [comment]
`Libs.private:` is for additional libraries that should be linked in when `--static` is specified, not for providing an alternative library name. I think pkg-config always uses `Libs:` for that.

**Comment by hmel** [comment]
After reading up some more on pkg-config I think the only option is to have two .pc files: libuv.pc and libuv-static.pc

**Comment by bnoordhuis** [comment]
You know, that's not a bad idea. Want to open a PR?
