### ISSUE TITLE
failed make check

### ISSUE THREAD

**Issue by hsarraf** [libuv/libuv#2996]
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:5177: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/hsarraf/libuv/libuv'
Makefile:5433: recipe for target 'check-am' failed
make: *** [check-am] Error 2

* **Version**: libuv 1.6.1
* **Platform**: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-117-generic x86_64)

**Comment by hsarraf** [comment]
also not root while make check

**Comment by bnoordhuis** [comment]
> Version: libuv 1.6.1

Please upgrade to the latest libuv version, v1.6.1 is from five years ago...
