### ISSUE TITLE
filed under heavy load

### ISSUE THREAD

**Issue by bosstjann** [libuv/libuv#300]
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) object.wrapper_native_0x7432563c (Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle,int) <0xffffffff>
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.run (Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle,int) <0x00043>
  at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Run (int) <0x00027>
  at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart (object) <0x001b7>
  at System.Threading.Thread.StartInternal () <0x000d7>
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

Debug info from gdb:

Mono support loaded.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x735ff440 (LWP 2383)]
[New Thread 0x728ff440 (LWP 2381)]
[New Thread 0x71eff440 (LWP 2380)]
[New Thread 0x725ff440 (LWP 2379)]
[New Thread 0x72aff440 (LWP 2299)]
[New Thread 0x737ff440 (LWP 2297)]
[New Thread 0x743f1440 (LWP 2296)]
[New Thread 0x76abb440 (LWP 2295)]
0x76ec9504 in pthread_cond_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
  Id   Target Id         Frame
  9    Thread 0x76abb440 (LWP 2295) "Finalizer" 0x76ecb770 in sem_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
  8    Thread 0x743f1440 (LWP 2296) "Threadpool moni" 0x76eeb894 in clock_nanosleep () from /lib/arm-linux-gnueabihf/librt.so.1
  7    Thread 0x737ff440 (LWP 2297) "Threadpool work" 0x76ecc840 in read () from /lib/arm-linux-gnueabihf/libpthread.so.0
  6    Thread 0x72aff440 (LWP 2299) "mono" 0x76ecdaac in waitpid () from /lib/arm-linux-gnueabihf/libpthread.so.0
  5    Thread 0x725ff440 (LWP 2379) "Threadpool work" 0x76ec9504 in pthread_cond_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
  4    Thread 0x71eff440 (LWP 2380) "Threadpool work" 0x76ec9504 in pthread_cond_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
  3    Thread 0x728ff440 (LWP 2381) "Threadpool work" 0x76ec9504 in pthread_cond_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
  2    Thread 0x735ff440 (LWP 2383) "Threadpool work" 0x76ecb9c4 in sem_timedwait () from /lib/arm-linux-gnueabihf/libpthread.so.0
* 1    Thread 0x76fa1000 (LWP 2287) "mono" 0x76ec9504 in pthread_cond_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0

Thread 9 (Thread 0x76abb440 (LWP 2295)):
#0  0x76ecb770 in sem_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0x002277b8 in mono_sem_wait (sem=0x2fae1c, alertable=1) at mono-semaphore.c:101
#2  0x001aef78 in finalizer_thread (unused=<optimized out>) at gc.c:1093
#3  0x0018fe74 in start_wrapper_internal (data=<optimized out>) at threads.c:664
#4  start_wrapper (data=<optimized out>) at threads.c:711
#5  0x0022dcf0 in inner_start_thread (arg=<optimized out>) at mono-threads-posix.c:96
#6  0x76ec4c00 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#7  0x76e31728 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
#8  0x76e31728 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (Thread 0x743f1440 (LWP 2296)):
#0  0x76eeb894 in clock_nanosleep () from /lib/arm-linux-gnueabihf/librt.so.1
#1  0x0021a720 in wapi_SleepEx (ms=<optimized out>, alertable=1) at wthreads.c:272
#2  0x001922f0 in monitor_thread (unused=<optimized out>) at threadpool.c:856
#3  0x0018fe74 in start_wrapper_internal (data=<optimized out>) at threads.c:664
#4  start_wrapper (data=<optimized out>) at threads.c:711
#5  0x0022dcf0 in inner_start_thread (arg=<optimized out>) at mono-threads-posix.c:96
#6  0x76ec4c00 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#7  0x76e31728 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Cannot access memory at address 0x542e6d5c

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted

**Comment by saghul** [comment]
Kestrel does use libuv, but don't see it here in the backtrace.
