### ISSUE TITLE
illumos: event ports -> epoll

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3008]
See: https://illumos.org/man/5/epoll

Idea: move logic from src/unix/linux-core.c to src/unix/epoll.c and share that between Linux and Illumos.

Motivation:

* removes 250-300 lines of code from src/unix/sunos.c
* switches to much more battle-hardened code
* makes libuv more efficient because it no longer has to accommodate this event ports quirk:
```diff
diff --git a/src/unix/core.c b/src/unix/core.c
index 5b0b64dd..ade03c51 100644
--- a/src/unix/core.c
+++ b/src/unix/core.c
@@ -880,14 +880,8 @@ void uv__io_start(uv_loop_t* loop, uv__io_t* w, unsigned int events) {
   w->pevents |= events;
   maybe_resize(loop, w->fd + 1);
 
-#if !defined(__sun)
-  /* The event ports backend needs to rearm all file descriptors on each and
-   * every tick of the event loop but the other backends allow us to
-   * short-circuit here if the event mask is unchanged.
-   */
   if (w->events == w->pevents)
     return;
-#endif
 
   if (QUEUE_EMPTY(&w->watcher_queue))
     QUEUE_INSERT_TAIL(&loop->watcher_queue, &w->watcher_queue);
```
(Whoever designed event ports seemingly wasn't able to break free from the `poll(2)` mindset...)

**Comment by tjarlama** [comment]
@bnoordhuis I would like to work on this, but I'm not sure if I understood the problem, since it's the first time working on solaris.
1. SUNOS is exclusively reserved for illumos and event ports can be replaced with epoll
OR
2. SUNOS remains the same and add special case for illumos to compile epoll.c instead of event ports
OR
3. All derivatives of solaris support epoll and can replace event ports

**Comment by bnoordhuis** [comment]
@tjarlama I think it's fair to say that SUNOS means Illumos nowadays so options (1) and (3). The market share of Illumos is already marginal, let alone that of the other Solaris offspring.

**Comment by vtjnash** [comment]
We ended up restoring the event_ports code, for various reasons, in https://github.com/libuv/libuv/pull/3242
