### ISSUE TITLE
14 tests fail on AIX

### ISSUE THREAD

**Issue by trex58** [libuv/libuv#3014]
Version: 1.40.0
Platform: AIX 7.2 TL3
Compiler: GCC v8.4.0 - 32bit and 64bit

On AIX 7.2 TL3, compiling with GCC v8.4.0, both with 32bit and 64bit, there are 14 tests failing out of 388.
Though, on Fedora32/x86_64 and Fedora32/PPC64LE, 100% of 389 tests are OK.
Tested as not-root.

Failing tests on AIX are:
not ok 33 - fork_fs_events_child
not ok 49 - fs_event_close_in_callback
not ok 50 - fs_event_close_with_pending_event
not ok 52 - fs_event_getpath
not ok 53 - fs_event_immediate_close
not ok 54 - fs_event_no_callback_after_close
not ok 55 - fs_event_no_callback_on_close
not ok 57 - fs_event_start_and_close
not ok 58 - fs_event_watch_dir
not ok 60 - fs_event_watch_file
not ok 61 - fs_event_watch_file_current_dir
not ok 62 - fs_event_watch_file_exact_path
not ok 63 - fs_event_watch_file_twice
not ok 140 - ip6_addr_link_local

**Comment by aixtools** [comment]
Doing backup now, but what is status on system I am about to retire #3013 

Test can be run in about an 15 minutes. Backup will finish by then.

**Comment by richardlau** [comment]
@trex58 At least for the `fs_event_*` tests you'll need `bos.ahafs` installed: https://github.com/libuv/libuv#aix-notes

**Comment by trex58** [comment]
bos.ahafs : Thanks !

However, this LPP is installed on my machine (7200-03-03-1913):
   # lslpp -l | grep bos.ahafs
     bos.ahafs                 7.2.3.15  COMMITTED  Aha File System
     bos.ahafs                 7.2.3.15  COMMITTED  Aha File System

Maybe these issues are due to the compiler I used (GCC v8.4)? I'll try with XLC.

Anyway, where can I find tests results of building/testing libvu as part of NodeJS? I've just spent 10mn trying to find tests results of an AIX machine but was unable to find them. Please help.

**Comment by trex58** [comment]
I've got the same 14 tests failures (for both 32 & 64bit) with:
  GCC 9.3.0
  XLC v16.1.0.6

With XLCLANG v16.1.0.6, build breaks in 32bit (at least).

It does not seem to be a C compiler issue.
All tries were done with NO -O option. Only -g.

When trying again with -O2 -g and GCC 8.4.0 , same result.

**Comment by trex58** [comment]
Details of some tests failures:

```
not ok 33 - fork_fs_events_child
# exit code 393350
# Output from process `fork_fs_events_child`:
# Assertion failed in test/test-fork.c on line 431: r == 0

not ok 49 - fs_event_close_in_callback
# exit code 393350
# Output from process `fs_event_close_in_callback`:
# Assertion failed in test/test-fs-event.c on line 942: r == 0

not ok 50 - fs_event_close_with_pending_event
# exit code 393350
# Output from process `fs_event_close_with_pending_event`:
# Assertion failed in test/test-fs-event.c on line 906: r == 0

not ok 140 - ip6_addr_link_local
# exit code 393350
# Output from process `ip6_addr_link_local`:
# Assertion failed in test/test-ip6-addr.c on line 75: 0 == uv_if_indextoname(iface_index, scoped_addr, &scoped_addr_len)
```

Probably that the IPv6 related test failure is due to some mis-configuration of IP on my machine. To Be Checked.

I've found no log file with more details about failures. Are there some?

Test 49 above fails at:

  r = uv_fs_event_init(loop, &fs_event);
  ASSERT(r == 0);
  r = **uv_fs_event_start**(&fs_event, fs_event_cb_close, "watch_dir", 0);
  **ASSERT(r == 0);**

**Comment by trex58** [comment]
I'm new to libuv. Waiting for you to check if this is reproducible in your environment or if that is specific to my own environment.

**Comment by richardlau** [comment]
> Anyway, where can I find tests results of building/testing libvu as part of NodeJS? I've just spent 10mn trying to find tests results of an AIX machine but was unable to find them. Please help.

We don't run the libuv tests as part of Node.js, we run them separately prior to updating libuv in Node.js.

We run libuv tests in Jenkins: https://ci.nodejs.org/job/libuv-test-commit/
Specifically for AIX this is under sub-jobs:
- https://ci.nodejs.org/job/libuv-test-commit-aix/ (using autotools)
- https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/ (using cmake)

The latest build (from 14 days ago) passed all the tests: https://ci.nodejs.org/job/libuv-test-commit-aix/2066/
e.g. 
- with gcc: https://ci.nodejs.org/job/libuv-test-commit-aix/2066/nodes=aix71-ppc64/console
- with xlc: https://ci.nodejs.org/job/libuv-test-commit-aix/2066/nodes=aix72-xlc-ppc64/console

> 
> 
> I've found no log file with more details about failures. Are there some?
> 

Unfortunately, no.

> Test 49 above fails at:
> 
> r = uv_fs_event_init(loop, &fs_event);
> ASSERT(r == 0);
> r = **uv_fs_event_start**(&fs_event, fs_event_cb_close, "watch_dir", 0);
> **ASSERT(r == 0);**

There's an open issue (https://github.com/libuv/libuv/issues/2974) about switching the ASSERT macros to newer ones that are more informative when they fail. For example replacing:
```
ASSERT(r == 0);
```
with
```
ASSERT_EQ(r, 0);
```
would print the value of `r` when the assertion fails.

**Comment by trex58** [comment]
You're right !
I should have read all the page...
Out of the 14 failing tests, only 1 remains:
   not ok 140 - ip6_addr_link_local
And, as I said, this one probably is due to some missing IPv6 configuration.
Thanks a lot !
