### ISSUE TITLE
TCP_KEEPALIVE in uv__tcp_keepalive() under Windows Server 2003

### ISSUE THREAD

**Issue by ac** [libuv/libuv#302]
setsockopt(socket, IPPROTO_TCP, TCP_KEEPALIVE....) always fails under Windows Server 2003.
Seems the socket option TCP_KEEPALIVE is not implemented in old Windows. So any libuv-based software wan't work there.

Libuv should ignore the error after this call.

**Comment by ac** [comment]
Btw, WinSock error code 10042=WSAENOPROTOOPT (in this case of wrong setsockopt option) is not known by libuv. It translated into 'unknown'.

**Comment by bnoordhuis** [comment]
@piscisaureus @saghul Do we still consider Windows XP and Server 2003 to be supported platforms?  I don't think that silently ignoring setsockopt() errors is a good idea, by the way.

**Comment by saghul** [comment]
As far as I'm concerned we do support them on v1.x.

If setting TCP keepalive is not supported on 2k3 we should just return the
appropriate error, not ignore it, IMHO.

**Comment by piscisaureus** [comment]
Is TCP_KEEPALIVE significantly different than SO_KEEPALIVE? Because all versions of Windows *do* support the latter.

https://msdn.microsoft.com/en-us/library/windows/desktop/ee470551(v=vs.85).aspx

**Comment by amurzeau** [comment]
SO_KEEPALIVE can only enable or disable keepalive, TCP_KEEPALIVE is used to set timers (tcp.c code)
SIO_KEEPALIVE_VALS IOCTL seems to be another way to set keepalive timers. Rust-lang use the latter (https://doc.rust-lang.org/net2-rs/net2/trait.TcpStreamExt.html#tymethod.set_keepalive_ms)
