### ISSUE TITLE
timeout value not init, will report uninitialised value when check with valgrind

### ISSUE THREAD

**Issue by zhaozg** [libuv/libuv#3020]
handle->timeout should set to 0 in 
https://github.com/libuv/libuv/blob/30ff5bf2161257921f3a3ce5655804f7cb282aa9/src/timer.c#L58-L63

If not, it will cause 
https://travis-ci.org/github/luvit/luv/jobs/735591007#L960

**Comment by bnoordhuis** [comment]
Thanks for the report. Fix underway in #3038.
