### ISSUE TITLE
Is it possible to introduce wepool as libuv Windows backend?

### ISSUE THREAD

**Issue by VGGX** [libuv/libuv#3022]
@piscisaureus released an epoll-like library for Windows, called [wepoll](https://github.com/piscisaureus/wepoll/tree/master), that wraps IOCP APIs. [libevent](https://github.com/libevent/libevent) has already use wepoll as Windows backend. (https://github.com/libevent/libevent/pull/1006)
With wepoll, we can
- use epoll-like API achieve the same goal but with more readable code
- avoid the tricky implementation on Windows
- multiple threads can poll the same epoll port
- sockets can be added to multiple epoll sets

**Comment by bzoz** [comment]
libuv already uses IOCP and we have most of Windows kinks worked out - a lot was done by @piscisaureus himself. What would be the benefit of using this new library?

**Comment by bnoordhuis** [comment]
There's some overlap with #3008 (sharing code across operating systems) but the difference of course is in the popularity of the two platforms.

**Comment by VGGX** [comment]
> I know - I am one of the authors of libuv. However libuv is pretty big and imposes its own asynchronous i/o model onto your application.
Later I discovered that it is possible to do efficient epoll emulation on windows so then I wrote wepoll. With it you can just stick to the good ol' epoll/kqueue model and still support windows. 

@piscisaureus himself gives an brief answer about libuv Windows backend and wepoll difference. See the comment: https://news.ycombinator.com/item?id=15978372

**Comment by vtjnash** [comment]
Right the main difference is that libuv is a complete library capable of much more, while wepoll only handles sockets.
