### ISSUE TITLE
uv_pipe_connect after uv_pipe_bind,uv_read_start will return socket not connect

### ISSUE THREAD

**Issue by simonxiao80** [libuv/libuv#3023]
when i want bind client pipe with a local path,it failed 
in the function uv_pipe_connect:
 if (new_sock) {
    err = uv__stream_open((uv_stream_t*)handle,
                          uv__stream_fd(handle),
                          UV_HANDLE_READABLE | UV_HANDLE_WRITABLE);
  }
the handle was not a new socket after bind,so the UV_HANDLE_READABLE flag not be enabled, it makes the function uv_read_start return error

**Comment by sychaichangkun** [comment]
@simonxiao80 Hi,  I meet the same problem. 

I think it's not necessary to check whether it's a new sock or not when setting READABLE and WRITABLE flag. `pipe_connect` need to set these 2 flags.
The sock may be created by `uv_pipe_open` which has READABLE and WRITABLE flags.
But may also be created by 'uv_pipe_bind' which have no these flags.

the commit that add `if (new_sock)` assumes the handle created by `uv_pipe_open` regardless of `uv_pipe_bind`
https://github.com/libuv/libuv/commit/ff59525c7e70b0c1c1ba11ed65ad3f1c6ddf92f1
