### ISSUE TITLE
uv_stdio_flags not documented on uv_process page

### ISSUE THREAD

**Issue by leonerd** [libuv/libuv#3025]
The documentation page

  http://docs.libuv.org/en/v1.x/process.html

briefly mentions the `uv_stdio_flags` type, but doesn't go into detail about its possible values and their semantics. The type name isn't turned into a link to some documentation anywhere else.

The actual `uv.h` file contains the following definition:

```c
/* uv_spawn() options. */
typedef enum {
  UV_IGNORE         = 0x00,
  UV_CREATE_PIPE    = 0x01,
  UV_INHERIT_FD     = 0x02,
  UV_INHERIT_STREAM = 0x04,

  /*
   * When UV_CREATE_PIPE is specified, UV_READABLE_PIPE and UV_WRITABLE_PIPE
   * determine the direction of flow, from the child process' perspective. Both
   * flags may be specified to create a duplex data stream.
   */
  UV_READABLE_PIPE  = 0x10,
  UV_WRITABLE_PIPE  = 0x20,

  /*
   * Open the child pipe handle in overlapped mode on Windows.
   * On Unix it is silently ignored.
   */
  UV_OVERLAPPED_PIPE = 0x40
} uv_stdio_flags;
```

so maybe that just needs explaining somehow in docs?

**Comment by bnoordhuis** [comment]
Yes, that seems like an omission. Pull request welcome!

**Comment by leonerd** [comment]
This information in the `.h` file isn't sufficient for me to work out what words to write though. I don't have a good feel for how `UV_INHERIT_STREAM` works, especially when combined with the `UV_CREATE_PIPE` flag. Maybe there are some examples somewhere I can use?

**Comment by bnoordhuis** [comment]
I can see how their numeric values could lead you to believe that they can be combined but `UV_IGNORE`, `UV_CREATE_PIPE`, `UV_INHERIT_FD` and `UV_INHERIT_STREAM` are all mutually exclusive.

**Comment by leonerd** [comment]
Well then I'm still stuck for what words to actually write as I don't know what any these options actually do - which is rather the point of why I was looking for the docs in the first place :)

I'll write a PR with some dummy words in it and perhaps someone who knows more about it can suggest some better words.

**Comment by vtjnash** [comment]
It looks like the sphinx-build version is too old. The documentation is present (limited, but present), however when I updated to address warnings on the latest version of sphinx and improve formatting and cross-linking(https://github.com/libuv/libuv/commit/707dd7f17d9d84d972282666fee47dd3b216349b), I used an annotation only added in v3.0.0 (released Apr 06, 2020) while the page is building with v1.8.5 (released Mar 10, 2019)

**Comment by leonerd** [comment]
A draft PR here: https://github.com/libuv/libuv/pull/3039

I've still yet to work out how `UV_CREATE_PIPE` works or what it does with the result.

**Comment by leonerd** [comment]
> I've still yet to work out how UV_CREATE_PIPE works or what it does with the result.

Update: Having read some code in `src/unix/process.t`, I believe how this works is that `UV_CREATE_PIPE` asks it to create a bidirectional PF_UNIX/SOCK_STREAM socket (i.e. not a pipe at all), keeping one end for itself and giving the other end to the child process. The `data.stream` field must point at an initialised `uv_pipe_t`, into which the parent's end of the socket will be given. As far as I can tell, the only side-effect of the `UV_WRITABLE_PIPE` or `UV_READABLE_PIPE` flags is to set the corresponding `UV_HANDLE_WRITEABLE/_READABLE` flags on the opened handle, which causes it to reject certain kinds of operation. The actual OS-level filehandle that gets created is identical in all cases.

Which slightly poses the question of why it does this; and in particular why it doesn't just create a unidirectional real pipe in the likely scenario where only one direction flag was specified.

**Comment by leonerd** [comment]
> Which slightly poses the question of why it does this; and in particular why it doesn't just create a unidirectional real pipe in the likely scenario where only one direction flag was specified.

Ahah. It seems like that *used to be* the behaviour before c0081f0e6 where it got lost. Before that, there was a call to `uv__make_pipe()` in there, but that commit lost it favour of always just calling `uv__make_socketpair()`.

I wonder if it should be put back again - use `uv__make_pipe()` in the common case that only one of `UV_WRITABLE_PIPE` or `UV_READABLE_PIPE` is specified; and only call `uv__make_socketpair()` if they both are. An interesting cornercase question comes on what if neither, though.

**Comment by bnoordhuis** [comment]
> and in particular why it doesn't just create a unidirectional real pipe

So, one reason is that a socketpair is strictly more useful: it's bidirectional (2 > 1) and it lets you transmit file descriptors.

A secondary reason is that some programs out there expect bidirectional stdio (probably unintentionally) - e.g., that you can write to stdin and read from stdout - because most of the time that just works: the file descriptors refer to the same file description, the tty.

I remember we actually made some changes to Node.js five or six years ago to accommodate such programs.

**Comment by leonerd** [comment]
Certainly, `socketpair()` is the way to create these things if both READABLE + WRITABLE flags are specified. I was just suggesting using `pipe()` when only one flag is present.
