### ISSUE TITLE
Code highlighting is off in a few code snippets in docs

### ISSUE THREAD

**Issue by RaisinTen** [libuv/libuv#3033]
I was going through the docs and suddenly I realised that the code highlighting is off in a couple of snippets.
Ref: last snippet [here](http://docs.libuv.org/en/latest/guide/filesystem.html)
[This](https://groups.google.com/g/sphinx-users/c/DxkVZavwT94) discussion will come handy in solving this I guess.

**Comment by RaisinTen** [comment]
_Ping!_ Is this worth working on? Don't want any work to go waste, so I'm seeking for approval.

**Comment by santigimeno** [comment]
@RaisinTen Sorry for the delay. Anything that improves the documentation is indeed welcome. Thanks!

**Comment by RaisinTen** [comment]
_ping!_

**Comment by RaisinTen** [comment]
> _ping!_
