### ISSUE TITLE
changing the process name works only partially in Linux

### ISSUE THREAD

**Issue by mmomtchev** [libuv/libuv#3037]
* **Version**: Since <https://github.com/libuv/libuv/commit/7b28d36056d947e74e2c3347ee9bb04a1f5388c6#diff-061ff4a1f558b9316c85e332cfe90b66b3b5b612455249bfc1bb19a24e7f28e1>
* **Platform**: Linux

There are two "process titles" in Linux
* one is the so-called command line that you see when you do `ps uaxw`, it comes from `/proc/<pid>/cmdline` and this one is still modified by `process.title`
* the other one is the thread name that you see when you do `ps -p <pid>`, that one comes from `/proc/<pid>/comm` and it was broken by libuv 1.35.0 that was added in Node 12.17

#3019 
<https://github.com/nodejs/node/issues/35503>

**Comment by silverwind** [comment]
It's also wrong in `/proc/pid/status`, but I guess that may be a pointer to `/proc/pid/comm`.

```
$ cat /proc/28032/cmdline
myname
$ cat /proc/28032/comm
node
$ cat /proc/28032/status | head -1
Name: node
```

Some more info on this in https://stackoverflow.com/a/14176059/808699
