### ISSUE TITLE
Add note to the documentation about checking uv_read_stop return value

### ISSUE THREAD

**Issue by skissane** [libuv/libuv#3041]
* **Version**: master branch
* **Platform**: all platforms

uv_read_stop has an int return type and yet most code never checks the return value.

The answer is that, in most cases, the return value is always going to be zero so there is no need to check.

The exception is for uv_tty_t on Windows only, where uv_read_stop may return an error. On other platforms it always returns zero, and the same for everything other than uv_tty_t on Windows. (I guess there is always the possibility that in the future, some new platform or new feature may be added in which uv_read_stop can return non-zero in other cases.)

I think it is true though that even if uv_read_stop returns an error on a Windows tty_t, it still will stop the read callback from being called?

This topic confused me, I found the answer reading the code, but I suggest the documentation should be extended, so other people don't have to read the code to find the answer.

**Comment by vtjnash** [comment]
Looks like it. Perhaps document that this is always zero, and fix uv_tty_read_stop to also return zero (since it has successfully stopped, it just might be waiting for the user to hit a key to finish running our cleanup steps and release the resources)

**Comment by skissane** [comment]
I created a PR to fix this #3076

**Comment by skissane** [comment]
I don't think an issue should be marked as stale if it has an open PR attached to it.

**Comment by skissane** [comment]
not stale

**Comment by skissane** [comment]
not stale
