### ISSUE TITLE
Is reading from a pipe fd supported in file mode on Windows

### ISSUE THREAD

**Issue by mmomtchev** [libuv/libuv#3043]
* **Version**: 1.40 (node-master)
* **Platform**: Windows 10

<https://github.com/nodejs/node/issues/35997>
Should an `ERROR_BROKEN_PIPE` be considered a valid `EOF` on Windows? When `stdin` is a pipe, most of the time it will be closed before the process exits?

```c
--- a/deps/uv/src/win/fs.c
+++ b/deps/uv/src/win/fs.c
@@ -918,7 +918,7 @@ void fs__read(uv_fs_t* req) {
     SET_REQ_RESULT(req, bytes);
   } else {
     error = GetLastError();
-    if (error == ERROR_HANDLE_EOF) {
+    if (error == ERROR_HANDLE_EOF || error == ERROR_BROKEN_PIPE) {
       SET_REQ_RESULT(req, bytes);
     } else {
       SET_REQ_WIN32_ERROR(req, error);
```

Should libuv consider that is a normal close without errors?

**Comment by bughit** [comment]
> Should an ERROR_BROKEN_PIPE be considered a valid EOF on Windows?

According to [ReadFile docs](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile), yes:

> If an anonymous pipe is being used and the write handle has been closed, when ReadFile attempts to read using the pipe's corresponding read handle, the function returns FALSE and GetLastError returns ERROR_BROKEN_PIPE.

**Comment by bughit** [comment]
https://github.com/libuv/libuv/blob/master/src/win/error.c#L156

even explicitly maps ERROR_BROKEN_PIPE to UV_EOF which is how you end up with an EOF readSync exception

@mmomtchev Could you submit a PR with your patch?

**Comment by santigimeno** [comment]
This was fixed a while back by https://github.com/libuv/libuv/commit/df78de04e46a8dbe341f418052238da0141a69af
