### ISSUE TITLE
uv_buf_t members are not (officially) readable.

### ISSUE THREAD

**Issue by coreyfarrell** [libuv/libuv#305]
Though it is possible to read uv_buf_t members base and len, it is not officially documented that this is allowed.  Directly reading these members does not seem like it would cause a problem for cross platform sources.  Can we either:
* Comment in uv-unix.h / uv-win.h that the members are read-only, list them in docs/src/misc.rst.
* Create accessor functions to retrieve the base and len.

Access to these members is useful.  I have code that parses a config file with uv_fs_*.  I have a 1024 character buffer, and in the openreq callback I initialize a uv_buf_t to point to the whole buffer.  If the config file is larger than 1024 bytes there will be a line that crosses the buffer boundary.  So when I reach the end of the buffer I copy the current line in progress to the start of the buffer.  If this is 15 bytes, I run uvbuf = uv_buf_init(&buffer[15], sizeof(buffer) - 15).  In the next callback for uv_fs_read buffer[req->result] is not the last byte in the buffer, uvbuf.base[req->result] is the last byte.  Otherwise req->result + (sizeof(buffer) - uvbuf.len) would tell us the number of bytes to be read starting at buffer[0].  The whole point of this is to avoid wasting memory by storing two copies of the same information.

I'm willing to make the changes and submit a pull request for either documentation or accessors, I just need to know which option is preferred.

**Comment by bnoordhuis** [comment]
It's okay to reference the fields directly.  A pull request is welcome.

**Comment by saghul** [comment]
+1. If you send a PR, please document the fields in misc.rst. Thanks!

**Comment by saghul** [comment]
#307 landed, closing, thanks Corey.
