### ISSUE TITLE
C99 compliance / user side

### ISSUE THREAD

**Issue by fperrad** [libuv/libuv#306]
`libuv` could be compiled with `--std=c90`, `--std=c99` or `--std=c11` (the default is `--std=gnu89`).
That is great.

But it is not possible, on the user side (same error with c90, c99 or c11):
```
$ gcc --std=c99 include/uv.h
In file included from include/uv.h:61:0:
include/uv-unix.h:135:1: error: unknown type name 'pthread_rwlock_t'
 typedef pthread_rwlock_t uv_rwlock_t;
 ^
include/uv-unix.h:152:1: error: unknown type name 'pthread_barrier_t'
 typedef pthread_barrier_t uv_barrier_t;
 ^
include/uv.h:309:42: warning: 'struct addrinfo' declared inside parameter list [enabled by default]
                                   struct addrinfo* res);
                                          ^
include/uv.h:309:42: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
```

I found the following workaround :
```
$ cat user.c
#include <sys/socket.h>
#define __USE_POSIX /* struct addrinfo */
#include <netdb.h>

#define __USE_XOPEN2K /* pthread_rwlock_t & pthread_barrier_t */
#define __USE_XOPEN_EXTENDED /* siginfo_t */
#include "include/uv.h"

int main() {}
$ gcc --std=c99 user.c
```

Is it possible, that `uv.h` *uses* symbols only there are defined ?

**Comment by bnoordhuis** [comment]
When you compile your project with `-std=c99`, you tell the compiler to restrict itself to C99 only, no POSIX extensions.  You normally add `-D_XOPEN_SOURCE=500` or higher (or `-D_GNU_SOURCE` on Linux) to make POSIX definitions available again.

Libuv could hide uv_barrier_t, uv_rwlock_t, etc. when the related native definitions are not visible but then you're just swapping one set of compile errors for another (at least, when you use libuv's treading functions.)

**Comment by fperrad** [comment]
`_XOPEN_SOURCE=500` is not enough, but the following commands work:
```
$ gcc -std=c99 -D_XOPEN_SOURCE=600 include/uv.h
```
```
$ gcc -std=c99 -D_GNU_SOURCE include/uv.h
```

Thanks for your help.
