### ISSUE TITLE
how to resolve interlockedOr error in windows platform?

### ISSUE THREAD

**Issue by xiaoqingnianbudadun** [libuv/libuv#3073]
* **Version**: 1.x
* **Platform**: windows

**Comment by bzoz** [comment]
Please use the issue template.

**Comment by xiaoqingnianbudadun** [comment]
where can i have the method of compile uv.dll in windows platform, win10 system



---Original---

**Comment by bzoz** [comment]
https://github.com/libuv/libuv#build-instructions

CMake will build both .lib and .dll.

**Comment by xiaoqingnianbudadun** [comment]
I use the command in the piceture to build uv，but i cant find the files include .exe,.lib and dll,how can i get the files?

---Original---
