### ISSUE TITLE
Weird behaviour of `uv__io_check_fd`

### ISSUE THREAD

**Issue by zbroyar** [libuv/libuv#3078]
Hi,

Under heavy load on OS X `uv__io_check_fd` fails at the attempt to delete EVFILT_READ here: https://github.com/libuv/libuv/blob/v1.39.0/src/unix/kqueue.c#L106

The strange thing is the function creates EVFILT_READ without any problem and immediately after it aborts the process on inability to remove it.

I would be grateful for any ideas/suggestions. 

* **Version**: 1.39 (commit 25f4b8b8a3c0f934158cd37a37b0525d75ca488e)
* **Platform**: Darwin taran.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

**Comment by santigimeno** [comment]
How does it fail? Can you print the `errno`  value when if fails:
```c
if (kevent(loop->backend_fd, &ev, 1, NULL, 0, NULL)) {
  fprintf(stderr, "errno: %d\n", errno);
  abort();
}
```

**Comment by zbroyar** [comment]
In my case it returns errno = ENOENT. Man says it mean "The event could not be found to be modified or deleted."

**Comment by santigimeno** [comment]
Is it possible to provide code that reproduces the issue?

**Comment by vtjnash** [comment]
The purpose of this code is to check whether epoll/kevent/etc. are able to handle a particular fd. If the user is abusing it to check for data-race bugs in their code, it can abort here. That is not precisely libuv's fault however.

I recommend @zbroyar runs his code with the TSan analyzer. And without testcase to reproduce, I am going to close this.

The docs state this requirement already in http://docs.libuv.org/en/v1.x/poll.html#c.uv_poll_start, but only in the context of `uv_poll_start` ("The user should not close the socket while the handle is active"). Should we move this error check into that function, or duplicate that documentation in the description of `uv_poll_init`?
