### ISSUE TITLE
Error When Running Make Test

### ISSUE THREAD

**Issue by nathaliamota** [libuv/libuv#3093]
Running make test gives me the following error:

FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5431: check-TESTS] Error 1
make[1]: Leaving directory '/home/me/gitClones/libuv-v1.40.0'
make: *** [Makefile:5691: check-am] Error 2

**Comment by cjihrig** [comment]
Can you provide any additional information, such as the operating system and the test(s) that are failing.

**Comment by nathaliamota** [comment]
Sure! I am running Ubuntu Linux 20.04.
