### ISSUE TITLE
official example  locks/main.c executes abnormally during use 

### ISSUE THREAD

**Issue by wenlongkang** [libuv/libuv#3102]
First of all, thank you very much for opening up such an excellent project. I found that the locks/main.c program of the official example executes abnormally during use. The specific exception is as follows:

lm@bogon vector % ./main
Reader 1: acquired lock
Reader 1: shared num = 0
Reader 2: acquired lock
Reader 2: shared num = 0
Reader 2: released lock
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 1
Writer 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 1
Reader 2: released lock
Reader 1: acquired lock
Reader 1: shared num = 1
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 2
Writer 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 2
Reader 2: released lock
Reader 1: acquired lock
Reader 1: shared num = 2
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 3
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 3
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 3
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 4
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 4
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 4
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 5
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 5
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 5
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 6
Writer 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 6
Reader 2: released lock
Reader 1: acquired lock
Reader 1: shared num = 6
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 7
Writer 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 7
Reader 2: released lock
Reader 1: acquired lock
Reader 1: shared num = 7
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 8
Writer 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 8
Reader 2: released lock
Reader 1: acquired lock
Reader 1: shared num = 8
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 9
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 9
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 9
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 10
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 10
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 10
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 11
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 11
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 11
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 12
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 12
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 12
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 13
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 13
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 13
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 14
Writer 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 14
Reader 2: released lock
Reader 1: acquired lock
Reader 1: shared num = 14
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 15
Writer 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 15
Reader 2: released lock
Reader 1: acquired lock
Reader 1: shared num = 15
Reader 1: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 16
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 16
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 16
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 17
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 17
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 17
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 18
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 18
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 18
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 19
Writer 1: released lock
Reader 1: acquired lock
Reader 1: shared num = 19
Reader 1: released lock
Reader 2: acquired lock
Reader 2: shared num = 19
Reader 2: released lock
Writer 1: acquired lock
Writer 1: incremented shared num = 20
Writer 1: released lock
**Assertion failed: (b->out == 0), function uv_barrier_destroy, file /Users/lm/CLionProjects/vector/deps/libuv-1.39.0/src/unix/thread.c, line 125.
zsh: abort      ./main**

* **Version**: libuv-1.39.0
* **Platform**:   macos 10.15.4 (19E287)
lm@bogon vector % uname -a
Darwin bogon 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
lm@bogon vector % 

CMakeLists:

cmake_minimum_required(VERSION 3.15)
project(main)

add_subdirectory(deps/libuv-1.39.0)

set(CMAKE_CXX_STANDARD 11)

include_directories(deps/libuv/include)

link_directories(deps/libuv)

add_executable(main main.cpp people/People.cpp people/People.h)

target_link_libraries(main uv)

set(CMAKE_CXX_COMPILER      "clang++" )        

set(CMAKE_CXX_FLAGS   "-std=c++11")
set(CMAKE_CXX_FLAGS   "-g")                
set(CMAKE_CXX_FLAGS   "-Wall")           

set(CMAKE_CXX_FLAGS_DEBUG   "-O0" )             
set(CMAKE_CXX_FLAGS_RELEASE "-O2 -DNDEBUG " )

**Comment by wenlongkang** [comment]
Has anyone encountered the same problem?

**Comment by bnoordhuis** [comment]
I can reproduce and I know what the cause is:

- there are four threads serializing on the barrier
- the main thread calls `uv_barrier_destroy()` as soon as the `uv_barrier_wait()` call returns
- sometimes it's destroyed before `uv_barrier_wait()` in the other threads returns
- because other threads call `uv_cond_wait()`, releasing the internal mutex
 
It's essentially a race condition in libuv's barrier implementation.

**Comment by bnoordhuis** [comment]
I should add that the test neglects to check the return value of `uv_barrier_wait()` - the barrier musn't be destroyed until non-zero is returned to a waiting thread - but let's treat it as a quality-of-implementation issue: other barrier implementations do better and therefore libuv should to.

**Comment by wenlongkang** [comment]
Test this example on centos successfully executed, but there is this problem on macos

**Comment by bnoordhuis** [comment]
Libuv on linux uses libc's `pthread_barrier_t`, on macos we shim it. The issue is in the shim.

**Comment by cabelitos** [comment]
Hello @bnoordhuis , I've created a fix for the problem. If possible, could you please take a look?

https://github.com/libuv/libuv/pull/3162 
Ty.
