### ISSUE TITLE
Compile libUV for Microsoft Game Development Kit - Scarlett

### ISSUE THREAD

**Issue by jzer0** [libuv/libuv#3105]
Hi LibUV,

I'm looking to build uv libs for use with applications compiled using the Microsoft Game Development Kit (https://www.microsoft.com/en-us/software-download/gdk) for the Gaming.Desktop.x64 and Gaming.Xbox.Scarlett.x64 platform configurations. Installing this package provides for the following configurations in Visual Studio:

![image](https://user-images.githubusercontent.com/8395705/106265963-19714680-6228-11eb-897d-5759a0aeaf97.png)

I was able to compile for the Gaming.Desktop.x64 configuration but not for Scarlett due to some references to Windows Kit headers (i.e. typedef EXPLICIT_ACCESSA EXPLICIT_ACCESS; in C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\AccCtrl.h).  I'd like to know whether building for these platforms is possible or supported.

**Comment by bnoordhuis** [comment]
>  I'd like to know whether building for these platforms is possible or supported.

"I don't know" and "no", in that order. :-)

It's not a configuration we test (nor support) but if you manage to make it work, then please send a pull request.

I can't promise we'll accept it but if it doesn't require intrusive changes to libuv and it makes your life easier, then I don't see why not.
