### ISSUE TITLE
CopyFile on Windows is Slow

### ISSUE THREAD

**Issue by jasnell** [libuv/libuv#3116]
See original issue and associated discussion in Node.js issue tracker here: https://github.com/nodejs/node/issues/36158

/cc @asklar, @aduh95, @bzoz

**Comment by asklar** [comment]
Is there any interest from the libuv maintainers to pursue this?

**Comment by bnoordhuis** [comment]
I've added labels. Pull request welcome.

**Comment by RaisinTen** [comment]
PR: https://github.com/libuv/libuv/pull/3135

**Comment by cjihrig** [comment]
I think this should be closed out. The original Node.js issue didn't provide any real reasoning about performance, and suggested using an approach that wouldn't really work with how Node.js+libuv do things. Then, #3135 was opened and closed.
