### ISSUE TITLE
Data race when using `uv_queue_work`

### ISSUE THREAD

**Issue by JaSpa** [libuv/libuv#3118]
* **Version**: 1.41.0
* **Platform**: Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

## Description

Running a loop with `UV_RUN_DEFAULT` and using the threadpool with `uv_queue_work` results in a race condition, leading potentially to early terminations of `uv_run` or hangs. I attached a sample program which allows to observe the wrong behaviour, see [hang-test.c](https://github.com/libuv/libuv/files/6037134/hang-test.c.txt).

The race occurs in the increment and decrement operations of `active_reqs.count` in the `uv_loop_s` structure and the reads via `uv__has_active_reqs`. I could verify this by using the C11 atomics library (see attached [atomic.diff](https://github.com/libuv/libuv/files/6037133/atomic.diff.txt)) with `memory_order_relaxed` operations. I understand though that this is not fully portable as the C11 atomics library is not a required feature and the actual solution will probably use a different API.

## Sample program

Overall `uv_queue_work` is called 1000 times recursively. It should print

```
1000 enqueued
1000 running
 999 enqueued
 999 running
...
   0 enqueued
   0 running
```

and exit successfully. Instead sometimes it doesn't exit the event loop after printing `0 running` as can be seen by `event loop: exited` missing from the output.

## Attached files

* [hang-test.c](https://github.com/libuv/libuv/files/6037134/hang-test.c.txt) sample program which triggers the data race.
* [atomic.diff](https://github.com/libuv/libuv/files/6037133/atomic.diff.txt) my take on how to resolve the race using C11 atomics.

**Comment by bnoordhuis** [comment]
There is a bug in your test case: you call `uv_queue_work()` from your `uv_work_cb` (the function called `work_a()`) but you're not allowed to do that, it runs on another thread. From the documentation:

> Note that even though a global thread pool which is shared across all events loops is used, the functions are not thread safe.

(Documentation elsewhere uses even stronger wording: "[..] not thread safe unless explicitly mentioned otherwise".)

Move the call to your `uv_after_work_cb`, and everything should be okay.

I'll close this but I can move it to libuv/help if you have follow-up questions.

**Comment by santigimeno** [comment]
By looking at the example, you're calling `uv_queue_work()` from the threadpool too which I'm not sure it's guaranteed to work. IIUIC, `uv_queue_work()` can only be called from the same thread the loop is running on. See the Note in http://docs.libuv.org/en/v1.x/threadpool.html
