### ISSUE TITLE
how to compile a dynamic libuv library (linuv.so)

### ISSUE THREAD

**Issue by ddnionio** [libuv/libuv#312]
I need to build a linuv.so for nodejs to dynamic link to. 
The instruction in "https://github.com/libuv/libuv#build-instructions" lead to libuv.a instead of .so

**Comment by saghul** [comment]
What operating system and what build system are you using? If you are using autoconf on Unix, both libuv.a and libuv.so are created.

**Comment by ddnionio** [comment]
@saghul Thx, it works. I used the gyp method before, and it would lead to only libuv.a in out/Debug

But I need to build ia32 version in x64 machine. Do you know how to set the target version with autoconf.

**Comment by saghul** [comment]
If you are used to GYP, you still can:

~~~~
./gyp_uv.py -Duv_library=shared_library
make -C out
ls out/Debug/obj.target/
~~~~

**Comment by ddnionio** [comment]
@saghul Thanks! But if I want to use autoconf method, how to set the target version.

**Comment by saghul** [comment]
Please use the mailing list for questions, we try to limit the issue tracker to just issues.
