### ISSUE TITLE
Smartos 15 and 16 machines will no longer be available

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#3121]
The smartos 15 and 16 machines will go offline and not come back Wednesday March 3rd.

Any libuv CI jobs using them will need to be updated before then.

**Comment by richardlau** [comment]
Updated https://ci.nodejs.org/view/libuv/job/libuv-test-commit-smartos/ to remove smartos 15 and 16 but keep 17 and 18.

Before:
![image](https://user-images.githubusercontent.com/5445507/109531229-8ab64a80-7aaf-11eb-98d7-82fd2d19fc41.png)

After:
![image](https://user-images.githubusercontent.com/5445507/109531310-a4579200-7aaf-11eb-853a-515ddbd3ade5.png)

**Comment by richardlau** [comment]
https://ci.nodejs.org/view/libuv/job/libuv-in-node/ calls https://ci.nodejs.org/job/node-test-commit/ so will end up calling https://ci.nodejs.org/job/node-test-commit-smartos/ but that's a Node.js job, not libuv.
