### ISSUE TITLE
uv_fs_copyfile is missing chgrp and other attributes

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#3125]
On Windows, the file attributes are fulled copied over (per https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfilew), but on unix, it appears only the file mode attribute, and not others (`cp --preserve` specifies ownership, timestamps, context, links, xattr) are handled:
```
> fs.copyFileSync("vcbuild.bat", "cpbuild", )

$ ls -l vcbuild.bat cpbuild 
-rw-rw-r-- 1 vtjnash vtjnash 30492 Mar  2 13:27 cpbuild
-rw-rw-r-- 1 vtjnash sudo    30492 Nov 13 14:32 vcbuild.bat
```

**Comment by juanarbol** [comment]
I can work on this one

**Comment by juanarbol** [comment]
Just for clarification, do you think that a new option is required for the `uv_fs_copyfile`? If this lands w/out changing the API but the implementation could be considered as a breaking change?

**Comment by cjihrig** [comment]
No, I don't think we need a new option. This is a bug fix.

**Comment by vtjnash** [comment]
That said, it might be nice to have the bugfix as an option though (preserve=yes/no), after going through the work to implement the bugfix, to give users the option of which of the semantics (esp. utimes or current time) are desired

**Comment by cjihrig** [comment]
Would that option be platform specific like the bug though? It seems like it might be more hassle than it's worth. Your call though.

**Comment by vtjnash** [comment]
The main question is whether Unix or Windows behavior is currently "correct". The total fix would this be to implement the opposite behavior from whatever is currently default on that platform, on both platforms, with a flag. The half fix is to implement the consistent behavior only on one platform, with a flag, and leave the bug unresolved for the other platform, which is no worse than current behavior.

**Comment by cjihrig** [comment]
I think most users probably want a full copy (data + metadata), or as close as we can get. I would try to solve that before adding more flags, which would probably also complicate the Windows implementation.

**Comment by juanarbol** [comment]
Just in case you miss this one out https://github.com/libuv/libuv/pull/4396
