### ISSUE TITLE
Add Vasili as a member to AIX and IBMi platforms on libuv

### ISSUE THREAD

**Issue by miladfarca** [libuv/libuv#3143]
Vasili (@V-for-Vasili) has recently joined IBM and is a contributor to V8 on AIX and IBMi.
It would be great if he could also be added as a member of the following groups as his expertise could
be helpful on solving platform specific issues:
https://github.com/orgs/libuv/teams/aix
https://github.com/orgs/libuv/teams/ibmi

Request for adding him to same groups within nodejs:
https://github.com/nodejs/admin/issues/595

**Comment by cjihrig** [comment]
Invites sent to @V-for-Vasili for the AIX and IBMi teams. I'll close this out.
