### ISSUE TITLE
Out of bound reads

### ISSUE THREAD

**Issue by EricSesterhennX41** [libuv/libuv#3147]
Hello, during an audit of the ExpressVPN code by Cure53, some out-of-bound reads have been identified in the libuv code. These kind of errors might lead to crashes or information leaks. How do you prefer the details for such issues to be submitted?
Regards, Eric

**Comment by bnoordhuis** [comment]
If you have reason to believe it's a security vulnerability, not a regular bug, then it's probably best to get in touch over email. Mine's info@bnoordhuis.nl.
