### ISSUE TITLE
uv_get_process_title()  is unsafe

### ISSUE THREAD

**Issue by farblue68** [libuv/libuv#315]
case1:
In the case of "strlen(process_title.str)  => size ", buffer is not '\0' terminated.
https://github.com/libuv/libuv/blob/v1.x/src/unix/proctitle.c#L91

case2:
In the case of arg buffer is null, strncpy raise SEGV

Is this specification ?

I suppose this behavior is bug.
Is it good I want to fix as follows ?

case1:
force  '\0' terminate  similar uv__pthread_setname_np()
https://github.com/libuv/libuv/blob/v1.x/src/unix/darwin-proctitle.c#L47

case2:
In the case of "buffer == NULL" or "size >= 0", return -EINVAL.

**Comment by cjihrig** [comment]
Is there a reason that `uv_get_process_title()` doesn't return `ENOBUFS` and `EINVAL` in these cases? I can work on it, if we want to go that route.

**Comment by saghul** [comment]
@cjihrig I'd say go for it!
