### ISSUE TITLE
search_path_join_test and network path with forward slash

### ISSUE THREAD

**Issue by earnal** [libuv/libuv#3159]
I detected an issue in libuv that affect CMake, see original CMake [issue](https://gitlab.kitware.com/cmake/cmake/-/issues/22141).
It seems that the libuv function **search_path_join_test** fail with network path formatted like this "//shared-folder/aplication.exe".

Here is the fix I suggest (it fixed the issue saw on ctest side):
```diff
diff --git a/Utilities/cmlibuv/src/win/process.c b/Utilities/cmlibuv/src/win/process.c
index 04718dbdb2..8807593141 100644
--- a/Utilities/cmlibuv/src/win/process.c
+++ b/Utilities/cmlibuv/src/win/process.c
@@ -169,7 +169,9 @@ static WCHAR* search_path_join_test(const WCHAR* dir,
                                     size_t cwd_len) {
   WCHAR *result, *result_pos;
   DWORD attrs;
-  if (dir_len > 2 && dir[0] == L'\\' && dir[1] == L'\\') {
+  if (dir_len > 2 &&
+      ((dir[0] == L'\\' && dir[1] == L'\\') ||
+       (dir[0] == L'/' && dir[1] == L'/'))) {
     /* It's a UNC path so ignore cwd */
     cwd_len = 0;
   } else if (dir_len >= 1 && (dir[0] == L'/' || dir[0] == L'\\')) {
```

**Comment by vtjnash** [comment]
AFAICT, it seems like Win32 usually allows even mixed usages (though `/` is less reliable and more inconsistent)

```
cmd.exe>dir "\/localhost/C$"
 Volume in drive \\localhost\C$ has no label.
 Volume Serial Number is 2C4D-567B

 Directory of \\localhost\C$

03/29/2021  05:38 AM    <DIR>          AMD
...
```

Even `\\?\` and `\\.\` seem to somewhat still work when written as `//?/` and `//./`, though `//?/` doesn't disable further normalization, unlike `\\?\`.

**Comment by mathstuf** [comment]
Bump. I don't see why this issue would be invalid today yet (with #3167 still unmerged).

**Comment by earnal** [comment]
@vtjnash I don't know what to do to promote the fix... Any change to push it ?

**Comment by mathstuf** [comment]
Still relevant :) .

**Comment by mathstuf** [comment]
The associated PR has had activity…so bumping again.

**Comment by mathstuf** [comment]
The PR has had activity again…bumping again.
