### ISSUE TITLE
IPC with socket sharing under Windows Server 2003 issues

### ISSUE THREAD

**Issue by wisz** [libuv/libuv#317]
Socket connection after receiving the main process by uv_write 2 shared child process, the child process after receiving it can not read the contents can not release resources.The same code under Win7 is normal, but there is a problem in Win2003 below.

My English is not very good, do not know if I have expressed clearly, it is best to leave E_Mail, I put it to you the source code. THX.

**Comment by saghul** [comment]
Sorry, I'm afraid I don't understand your problem. Can you please attach some code which shows the problem?

**Comment by wisz** [comment]
The main process in the main code:

void on_new_connection(uv_stream_t *server, int status) {
   uv_tcp_t *client;
   if (status == -1) {
      // error!
      return;
   }

   client = (uv_tcp_t*) malloc(sizeof(uv_tcp_t));
   uv_tcp_init(loop, client);
   if (uv_accept(server, (uv_stream_t*) client) == 0) {
      struct child_worker *worker = &workers[round_robin_counter];
      uv_write_t *write_req = (uv_write_t*) malloc(sizeof(uv_write_t));
      dummy_buf = uv_buf_init(".", 1);
      uv_write2(write_req, (uv_stream_t*) &worker->pipe, &dummy_buf, 1, (uv_stream_t*) client, NULL);
      round_robin_counter = (round_robin_counter + 1) % child_worker_count;
   }
   else {
      uv_close((uv_handle_t*) client, NULL);
   }
}

-----------------------------------------------------------
The main sub-process code:

void echo_read(uv_stream_t *client, ssize_t nread, const uv_buf_t* buf) {
   uv_write_t *req;

   fprintf(stderr, "Into Read : Size -- %d \n", nread, uv_strerror(nread));

   if (nread < 0) {
        if (nread != UV_EOF)
			fprintf(stderr, "Read error: %s - %s\n", uv_err_name(nread), uv_strerror(nread));
        uv_close((uv_handle_t*) client, NULL);

		fprintf(stderr, "%d -> %d Exit------- -> %s\n", tmpCount, nread, buf->base);

        return;
   }
   if (nread = 0) {
	   free(buf->base);
	   return;
   }

   req = (uv_write_t *) malloc(sizeof(uv_write_t));
   req->data = (void*) buf->base;
  // buf->len = nread;

   tmpCount += 1;
   fprintf(stderr, "Wisz: %d -> %d ?? -> %s\n", tmpCount, nread, buf->base);

   uv_write(req, client, buf, 1, echo_write);
}
                       
void on_new_connection(uv_stream_t *q, ssize_t nread, const uv_buf_t* buf) {
	uv_tcp_t *client;
    client = (uv_tcp_t*) malloc(sizeof(uv_tcp_t));
    uv_tcp_init(loop, client);
    if (uv_accept(q, (uv_stream_t*) client) == 0) {
        fprintf(stderr, "Worker %d: Accepted a socket \n", getpid());
        uv_read_start((uv_stream_t*) client, alloc_buffer, echo_read);
    }
    else {
        uv_close((uv_handle_t*) client, NULL);
		free(client);
    }
}

int main() {
    tmpCount = 0;
    loop = uv_default_loop();
    uv_pipe_init(loop, &queue, 1);
    uv_pipe_open(&queue, 0);
    uv_read_start((uv_stream_t*)&queue, alloc_buffer, on_new_connection);
    return uv_run(loop, UV_RUN_DEFAULT);
}

---------------------------------
Remark:
Win7: echo_read function can be executed
Win2003:echo_read function not be executed

HTX.

**Comment by wisz** [comment]
I tested was found in Win2003 below：
Libuv tcp.c file, in uv_tcp_queue_read function:
RegisterWaitForSingleObject(&req->wait_handle, req->event_handle, post_completion, (void*) req, INFINITE, WT_EXECUTEINWAITTHREAD);
>>: post_completion callback function is not executed.

**Comment by saghul** [comment]
Please fix the formatting or use a gist, the code is pretty unreadable otherwise :-(

**Comment by wisz** [comment]
The main process in the main code:

void on_new_connection(uv_stream_t *server, int status) {
 uv_tcp_t *client;

 ...
 if (uv_accept(server, (uv_stream_t) client) == 0) {
 ...
 uv_write2(write_req, (uv_stream_t) &worker->pipe, &dummy_buf, 1, (uv_stream_t) client, NULL);
 ...
 }
 else {
   ...
 }
 }

--------------------------------------------------------------------------------

The main sub-process code:

void echo_read(uv_stream_t client, ssize_t nread, const uv_buf_t buf) {
  uv_write_t *req;

  ...

  uv_write(req, client, buf, 1, echo_write);
 }

void on_new_connection(uv_stream_t q, ssize_t nread, const uv_buf_t buf) {
 uv_tcp_t client;
 ...
 if (uv_accept(q, (uv_stream_t) client) == 0) {
 uv_read_start((uv_stream_t) client, alloc_buffer, echo_read);
 }
 else {
   ...
 }
 }

int main() {
 ...
 uv_pipe_open(&queue, 0);
 uv_read_start((uv_stream_t*)&queue, alloc_buffer, on_new_connection);
 ...
 }

**Comment by wisz** [comment]
The main process: When the client has new connections
Call on_new_connection 
 ==> uv_write2(write_req, (uv_stream_t) &worker->pipe, &dummy_buf, 1, (uv_stream_t) client, NULL);

The sub-process: Start and open pipe
Call uv_read_start((uv_stream_t*)&queue, alloc_buffer, on_new_connection); 
==> on_new_connection 
==> accept 
==> uv_read_start((uv_stream_t) client, alloc_buffer, echo_read); 
==> echo_read

**Comment by cynron** [comment]
Hi @saghul,

I may understand this issue.

@wisz means a `uv_tcp_t` which is `uv_write2'ed` by parent process via a pipe doesn't work in child process on windows server 2003, but it works on windows 7.

btw, I guess @wisz is a Chinese, ^_^.

**Comment by wisz** [comment]
@cynron 
You are awesome!  I'm Chinese. ^o^.

child process:
The echo_read function cannot be called on windows server 2003.

How to solve this problem? Thank you.

**Comment by wisz** [comment]
On windows server 2003：
Libuv tcp.c file:
 RegisterWaitForSingleObject(&req->wait_handle, req->event_handle, post_completion, (void*) req, INFINITE, WT_EXECUTEINWAITTHREAD);

It looks like req->event_handle has been a no signal state.

**Comment by bnoordhuis** [comment]
Closing, issue has been idle for > 2 years.
