### ISSUE TITLE
incorrect errno handling in uv__getpwuid_r

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#3174]
Noticed that https://github.com/libuv/libuv/blob/95f88f47f28b4686a6959377c8d2c31daa40bd64/src/unix/core.c#L1197 should be UV__ERR while browsing the code

Also, shouldn't we be handling EINTR there?

**Comment by RaisinTen** [comment]
PR: https://github.com/libuv/libuv/pull/3177
