### ISSUE TITLE
Why use JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK on child_process spawn on Windows?

### ISSUE THREAD

**Issue by runminlook** [libuv/libuv#3179]
I found JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK make the grandchild process escape from job control.
The grandchild process would not be killed when the node process is killed.
Only the child process would be killed when the node process is killed.

**Comment by bnoordhuis** [comment]
There's a comment with an explanation in src/win/process.c:
https://github.com/libuv/libuv/blob/ac5b21a2c900a3fa33cb49acf637039d7c8af28e/src/win/process.c#L75-L81
