### ISSUE TITLE
Range Locked File Access

### ISSUE THREAD

**Issue by tracker1** [libuv/libuv#318]
Range-locked read/write access...  related to: https://github.com/iojs/io.js/issues/1426

Would be nice to be able to do range-locked access with files.  [Cross-platform range locking implementation](http://cvs.synchro.net/cgi-bin/viewcvs.cgi/src/xpdev/filewrap.c?view=markup) for an example.  I really don't know C/C++ well at all, but the synchronet xpdev developers are pretty open-friendly.

You can find Deuce or DigitalMan on `irc.synchro.net` in `#synchronet`

**Comment by saghul** [comment]
Hi @tracker1, I'm not familiar with range-locked file access myself, maybe someone can chime in and/or provide an implementation.

One thing to note is that the code you linked is LGPL, which I don't think we can look at.

**Comment by tracker1** [comment]
@saghul understandable...

Here's some references:

* windows - https://msdn.microsoft.com/en-us/library/windows/desktop/aa365204(v=vs.85).aspx
* linux - http://man7.org/linux/man-pages/man2/mlock.2.html
* flock unix/solaris - http://www.perkin.org.uk/posts/solaris-portability-flock.html

Most environments seem to give you a `flock` interface that lets you specifically lock a byte range... Windows is the odd one out.  The only issues in real-world use is under some network sharing configurations, it doesn't work (and doesn't error out).  I've seen this with older SAMBA versions, as well as with some NFS shares.  In general people working in these configurations are aware, and I think a notation in the documentation would be sufficient.

**Comment by piscisaureus** [comment]
I'd be okay with this feature. 
I think `node-fs-ext` already has a working cross-platform `flock()` implementation: https://github.com/baudehlo/node-fs-ext/blob/master/fs-ext.cc

**Comment by tracker1** [comment]
Started related request to license the `filewrap.c` file referenced above under a more permissive license.

http://www.roughneckbbs.com/msgs/msg.ssjs?msg_sub=dove-syncprog&message=514

@piscisaureus @saghul  Has there been any progress on this?  I really wish I knew C well at all, or would love to make a PR to support this myself.

**Comment by saghul** [comment]
@tracker1 There has not been any progress on this. Anyone is pretty much free to take it on.

**Comment by tracker1** [comment]
@saghul thanks... I'm so far out of my depth here, but if I get any time this weekend may clone the repo and try hacking at it.  :-/

**Comment by saghul** [comment]
Closing, see reasons here: https://github.com/libuv/libuv/pull/657#issuecomment-165408626
