### ISSUE TITLE
crash when using uv_fs_sendfile and uv_fs_copyfile on ios device

### ISSUE THREAD

**Issue by lemon4ex** [libuv/libuv#3187]
Crashing with SIGSYS on sendfile

System: Darwin
Version: Darwin Kernel Version 20.2.0: Fri Nov 13 01:00:11 PST 2020; root:xnu-7195.62.1~4/RELEASE_ARM64_S8000
Machine: iPhone8,1

**Comment by RaisinTen** [comment]
Does Darwin even have the `copy_file_range()` syscall?
