### ISSUE TITLE
IRC location probably shouldn't say "Freenode" any more

### ISSUE THREAD

**Issue by leonerd** [libuv/libuv#3208]
Your repo's `README.md` says that the IRC location is on Freenode. Currently that network is in the middle of dying a huge and violent death. Perhaps this location needs updating?

Most channels / projects / communities have moved over to libera.chat. I have had a peek in the same-named channel there, though there's only four lurkers and no topic set, so I suspect this isn't a very official place yet. Perhaps you've moved to OFTC instead?

Either way, the README probably needs updating.

**Comment by vtjnash** [comment]
I think we can delete the line, as there is no active IRC community, as far as I know

**Comment by cspotcode** [comment]
There is also a link on the website's navbar which can be deleted at the same time as the README.md deletion.
