### ISSUE TITLE
windows  tcp uv_read_start  Receiving data cannot trigger a callback

### ISSUE THREAD

**Issue by ggglivw** [libuv/libuv#3213]
Now I am using libuv TCP to receive data. I am a Client. The server sends multiple 8-byte packets, which may be more than 200 times.
I couldn't trigger the callback of uv_read_start. Wireshark captured the packet and showed that the data had been received. When the problem occurred, I waited 6 seconds.
Then use UV_Fileno handle to force IOCTLSocket FIONREADmode to obtain buffer data, show data, forced to call socket Recv receive and can receive,
Why is uv_read_start not triggered?

**Comment by vtjnash** [comment]
Questions should go to https://github.com/libuv/help

**Comment by ggglivw** [comment]
https://github.com/libuv/help  There is no new issue button.

**Comment by bnoordhuis** [comment]
You can use https://github.com/libuv/libuv/discussions as of today.
