### ISSUE TITLE
when uv_poll_start is started, the associated callback is not executed immediately

### ISSUE THREAD

**Issue by Junbo-Zheng** [libuv/libuv#3218]
I found a very strange question about the use of `uv_poll_start`, please see my next description:
First, I use the `mq_open` function to create a message queue and get a fd handle, and then I call the `uv_poll_init` function and the fd handle as an input parameter. In addition, I also call `uv_timer` functions to close and restart some periodic timers to perform some special functions. In the actual work process, I call `uv_poll_start` function to start the poll associated with it to ensure that the callback function can be executed in the uv loop. 

**The test scenario is:**
- Init
1. uv_timer_init(&bt_loop, timer_handle);
2. uv_timer_start(timer_handle, sdk_init_callback, 6000, 0);
3. int fd = mq_open(name, O_RDWR | O_CREAT | O_NONBLOCK, mode, &attr);
4. uv_poll_init(loop, &msq->poll, fd);
5. uv_poll_start(&poll->poll, UV_READABLE, msg_queue_pollin_cb);
> The function of **msg_queue_pollin_cb** is to read the content of the message queue through the mq_receive function and perform subsequent processing.
- work process
1. There will be a periodic close timer, re-create a new timer and start the timer, the period of the timer is 6s.
2. An application will call the `mq_send` function to send a message. What we expect is that uvloop(`uv_run`) can check the change of the fd handle and execute the `msg_queue_pollin_cb` function(Read the content of the message queue via `mq_receive` and perform subsequent processing. This subsequent processing includes the call `uv_poll_stop` and perform some business processing at the same. When the business processing ends, `uv_poll_start` will be executed again to restart).
- test result
When doing some tests, it will appear that the application calls the `mq_send` function to send a message successfully, uvloop(`uv_run`) should call the `msg_queue_pollin_cb` function quickly, but the test result that uvloop(`uv_run`) will wait about 6s before called the `msg_queue_pollin_cb` function. The `msg_queue_pollin_cb` function was not executed immediately.

Of course, in response to this problem, I also conducted a scenario test, which is to start a 1s periodic timer during initialization. This timer is executed periodically and will not be closed. (Because at first I suspected that `msg_queue_pollin_cb` was not executed because of the uvloop function(`uv_run`) was blocked.) I tested it again, but the result was that when the application sent a message via `mq_send`, the `msg_queue_pollin_cb` function will be executed after the timer callback is executed instead of waiting for about 6s. I also tried to modify the timer cycle, the timer cycle increases to 2s or 3s. The phenomenon is that the 2s or 3s `msg_queue_pollin_cb` function is executed after the timer is executed when the message is sent via `mq_send`. Of course, this problem does not occur every time, but it is likely to occur on my side. I don’t know if anyone else has encountered similar problems, I have not found a solution to the problem.

**Let me summarize my problem:**
when `uv_poll_start` is started, the associated callback is not executed immediately, but the `uv_poll_start` has succeeded, and the value of **activity_handlers** for uvloop has been increased by 1.

The libuv is release v1.41 , and libuv is used on the nuttx system.

**Comment by Junbo-Zheng** [comment]
I have found a solution, it is the problem of our method of use, thank you all.

**Comment by amitgithub1** [comment]
please let now the exact problem and how you solved it?
