### ISSUE TITLE
uv_poll_init used in conjunction with uv_socketpair possible bug(windows10)

### ISSUE THREAD

**Issue by X-Crack** [libuv/libuv#3223]
```
#include "uv.h"
#include <stdio.h>
#include <stdlib.h>
static uv_os_sock_t fd[2];

void  poll_callback(uv_poll_t* handler, int status, int events)
{
    char buf = 0;
    recv(fd[1],&buf, 1, 0);
    printf("buf: %d", buf);
}
int main()
{

    uv_loop_t* loop = uv_default_loop();
    uv_poll_t poll;
    uv_socketpair(SOCK_STREAM, 0, fd, UV_NONBLOCK_PIPE, UV_NONBLOCK_PIPE);

    uv_poll_init(loop, &poll, fd[1]);

    uv_poll_start(&poll, UV_READABLE, poll_callback);

    char buf = 1;
    send(fd[0],&buf, 1, 0);
    
    uv_run(loop, UV_RUN_DEFAULT);
    return 0;
}
```

* **Version**: 1.41
* **Platform**: vs2019 windows10 20H1

INLINE static HANDLE uv__get_osfhandle(int fd)
{
  /* _get_osfhandle() raises an assert in debug builds if the FD is invalid.
   * But it also correctly checks the FD and returns INVALID_HANDLE_VALUE for
   * invalid FDs in release builds (or if you let the assert continue). So this
   * wrapper function disables asserts when calling _get_osfhandle. */

  HANDLE handle;
  UV_BEGIN_DISABLE_CRT_ASSERT();
  **_handle = (HANDLE) _get_osfhandle(fd);_**
  UV_END_DISABLE_CRT_ASSERT();
  return handle;
}

![QQ截图20210701093825](https://user-images.githubusercontent.com/45416520/124052003-2224ad80-da50-11eb-8cde-8a2fa9343d9c.png)

**Comment by vtjnash** [comment]
`uv_poll_init` doesn't accept a uv_os_sock_t (aka SOCKET) as an argument in v1.x. You need `uv_poll_init_socket` (this will be fixed in libuv v2)
