### ISSUE TITLE
double free in uv_uptime

### ISSUE THREAD

**Issue by perfnurt** [libuv/libuv#323]
**Problem:** There is a double free situation in uv_uptime

    ...
    uv__free(malloced_buffer);

    buffer_size *= 2;
    /* Don't let the buffer grow infinitely. */
    if (buffer_size > 1 << 20) {
      goto internalError;
    }
    ...

Since the first thing done in internalError is calling 
    uv__free(malloced_buffer);
malloced_buffer is free'd twice which results in memory corruption.

**Suggestion:** Move  

    uv__free(malloced_buffer);

to after the growth check.

**Comment by saghul** [comment]
Fixed by #324.
