### ISSUE TITLE
version 1.41.1 tagged commit is not on any branch

### ISSUE THREAD

**Issue by kanavin** [libuv/libuv#3237]

**Comment by vtjnash** [comment]
Tag commits don't need to be on a branch–that is partly why they are tags. What is the request here?

**Comment by kanavin** [comment]
The request is to push to the branch where the commit is supposed to be. Dangling tags are problematic, as any pull requests can potentially contain conflicts or target the wrong branch.

**Comment by vtjnash** [comment]
The commit is not supposed to be targeted by any pull requests. Can a tag be dangling? The glossary on git terms (https://git-scm.com/docs/gitglossary/#def_unreachable_object) appears to define unreachable as being not tagged or other reference.

**Comment by kanavin** [comment]
I had assumed that 1.41.1 was made on 1.x branch and the branch was not pushed while the tag was. Or that it merits a '1.41-stable' branch for any subsequent 1.41.x releases.

1.41.1 is actually a hotfix release for a single commit, which I guess is fine to exist without a branch.
