### ISSUE TITLE
udp modules not found during make check

### ISSUE THREAD

**Issue by SpookyPinkyTux** [libuv/libuv#3240]
* **Version**: <v1.14.1>
* **Platform**: <Linux palex 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux>

```
1) udp_multicast_join module not found and says not ok 368
2) # Output from process `udp_multicast_join`: (no output)
3) # Output from process `udp_multicast_join6`: (no output)

Error output: 

FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5541: check-TESTS] Error 1
make[1]: Leaving directory '/home/sandro/libuv'
make: *** [Makefile:5801: check-am] Error 2
```

**Comment by santigimeno** [comment]
It seems like the multicast tests are timing out. That's usually caused by the local firewalld/iptables configuration. Anyway, can you copy somewhere the full output of the tests?

**Comment by SpookyPinkyTux** [comment]
Here is the file where is stored output of make check. 
And the error code at the end of the program was: 

# Output
make[1]: *** [Makefile:5541: check-TESTS] Error 1
make: *** [Makefile:5801: check-am] Error [2[](url)](url)


# Here is the log.txt file.
[log.txt](https://github.com/libuv/libuv/files/6831479/log.txt)

**Comment by vtjnash** [comment]
Seems like your networking stack is blocking connections for most tests. Try running in a sandbox with networking enabled.

**Comment by vtjnash** [comment]
Open a discussion if you have further questions. I'm going to close, as this is unlikely to be a libuv bug.
