### ISSUE TITLE
Solaris build failure - sys/epoll.h: No such file or directory

### ISSUE THREAD

**Issue by citrus-it** [libuv/libuv#3241]
I'm setting up some new Solaris DNS servers using ISC Bind, and libuv is a pre-requisite for that. With the upcoming release of 1.42.0, I tried building the head of the v1.x branch, and it fails as shown below. v1.41.1 is fine.

```
  CC       src/unix/libuv_la-epoll.lo
src/unix/epoll.c:25:10: fatal error: sys/epoll.h: No such file or directory
   25 | #include <sys/epoll.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
gmake: *** [Makefile:2852: src/unix/libuv_la-epoll.lo] Error 1
```

```
$ uname -a
SunOS dns01 5.11 11.4.34.94.4 i86pc i386 i86pc
```

Doing a search through the issues and commits, I saw https://github.com/libuv/libuv/pull/3046 which moves to using epoll for illumos, but Solaris does not appear to have epoll.

**Comment by bnoordhuis** [comment]
I suppose that means we have to revert that change. Want to open a pull request?

**Comment by citrus-it** [comment]
Will do.
