### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by MSE99** [libuv/libuv#3252]
* **Version**: 1.x
* **Platform**: N/A

#### Description

I'm still new to systems programming so this may be due to the lack of knowledge on my end feel free to immediately close this issue if it is, i was reading through the [basics](https://github.com/libuv/libuv/blob/v1.x/docs/src/guide/basics.rst#event-loops) guide and came across this paragraph:

> One of the standard solutions is to use threads. Each blocking I/O operation is started in a separate thread (or in a thread pool). When the blocking function gets invoked in the thread, the processor can schedule another thread to run, which actually needs the CPU.

It says that the processor schedules another thread,  but isn't scheduling mainly done by the operating system not the processor ?, i know the OS virtualizes the CPU by time sharing it between multiple threads from different processes according to a scheduling policy doesn't this mean that the CPU only runs instructions until an exception occurs (fault, trap, abort, interrupt) and after which the CPU runs an exception handler from the trap table and the OS can then give control to whatever thread it wants ?.

**Comment by bnoordhuis** [comment]
You're not wrong. It's the operating system that decides what thread to schedule next when the current thread is blocked.

(_Technically_, it's possible to have a user-mode thread scheduler but in practice practically no one does that.)

Want to send a pull request to improve that section of the documentation?
