### ISSUE TITLE
Cannot stop fs event from start fs event callback 

### ISSUE THREAD

**Issue by 5415nofar1** [libuv/libuv#3258]
* **Version**: 1.39.0
* **Platform**: Windows (debug mode)

I am listening to changes on a particular file. When the file changes I stop listening and do some things.

It runs and works fine...

But in case of debugging in Windows I get an assertion here:
`static void uv_fs_event_queue_readdirchanges(uv_loop_t* loop, uv_fs_event_t* handle) { assert(handle->dir_handle != INVALID_HANDLE_VALUE);`

My code looks like this:

`uv_fs_event_start(&fs_event_req, OnChangeCb, file_path, 0);`

`void OnChangeCb(uv_fs_event_t* req, const char* filename, int events, int status){ .... uv_fs_event_stop(&fs_event_req); .... do some things }`

I noticed that the problem is related to the fact that at the beginning of the function `uv_process_fs_event_req` the request handle is active and after the callback `OnChangeCb` which call to `uv_fs_event_stop` function, the request is no longer active and despite this the function `uv_fs_event_queue_readdirchanges` is called and the assert goes up... 

Did I miss something?
Thank you!
Nofar

**Comment by bnoordhuis** [comment]
Thanks for the report. Can you check if #3259 fixes the issue for you?

**Comment by 5415nofar1** [comment]
Yes, Thank  you!
