### ISSUE TITLE
Loop exit exception caused by socket binding failure

### ISSUE THREAD

**Issue by basenumber** [libuv/libuv#3272]
**Problem**

Loop exit exception caused by socket binding failure

**Environment**

libuv version: 1.42.0 and previous version

OS version: win10 x64

**Phenomenon**

In `uv_async_send` callback method, we use `uv_udp_bind` (or `uv_tcp_bind`, as example, udp later), binds a native non-existent IP to the handle (created by "`new udp_handle_t`") represented by `uv_udp_t` , after the binding returns failure, immediately `delete` the handle(free resource), and then, an exception occurs during the exit of loop.
Note: Because of the presence of business operations such as human modification of host IP, the application profile does not change synchronously, and such problems do exist in the real world.

**Analysis**

1. When binding the existing IP on this machine, there is no abnormality when exit application;

2. Before exiting loop, we use `uv_walk` iteration to close the handle(belongs to libuv's internal queue), and find that there is a handle whether it is a normal or abnormal binding (although there may be other handle, such as the `uv_async_t` in the test demo, but we can focus on the problem-related one). we suspected that this handle is the corresponding type of udp handle. In the case of binding failure, after entering the uv_walk, the type of the handle is a random invalid value(number);

3. After viewing the src/win/udp .c file in the libuv source code, we find in the `uv_udp_maybe_bind` method, when bind fails, directly returned the `WSAGetLastError()` method returned the error value;

4. Step 3 caused a problem is that, before the bind operation, we has used `uv_udp_init` to associate handle with libuv loop; if bind failed, libuv did not close `handle->socket`, and did not remove the association between handle and loop (using `QUEUE_REMOVE`); resulting in the loop'queue has a udp handle. But we has released the handle resource in application when bind fails;

5. When application wants to exit loop, `uv_walk` still found that there is a handle in the queue, however, in previous step, we have released the corresponding address of the handle (even this address already contains another new object), resulting in a chain exception.

**Possible solutions**

One

If developer has no libuv source code (cannot complete the source code modification), we can only be carefully design the application of the implementation, release process, to avoid the bind failure, or immediate memory release operation; we should wait the loop completely exit, and then release the memory occupied by handle (although, it feels a little uncomfortable, in addition, the loop also maintains an invalid handle in its lifecycle);

TWO

the libuv source code `src/uv-common .c` in line 341:

`return uv__udp_bind(handle, addr, addrlen, flags);`

Revised to:

`int ret = uv__udp_bind(handle, addr, addrlen, flags);
if (ret != 0) {
    closesocket(handle->socket);    //need?
    QUEUE_REMOVE(&handle->handle_queue);
}
return ret;`

after the modification, recompile and generate libuv library;

test demo
[UvTests.zip](https://github.com/libuv/libuv/files/7004298/UvTests.zip)

**Comment by bnoordhuis** [comment]
> immediately delete the handle(free resource)

This is wrong: call `uv_close()` first and wait for the callback to be called before freeing the memory.

Closing, expected and documented behavior.
