### ISSUE TITLE
hidden symbol `pthread_atfork'

### ISSUE THREAD

**Issue by kjeldflarup** [libuv/libuv#3289]
I'm trying to build latest version bind9 on an older embedded Linux system.

The I encounter this error when building named:
```
/bin/ld: .libs/named: hidden symbol `pthread_atfork' in libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO
```
I tracked the error down to libuv using `pthread_atfork` in these threee files:  
src/threadpool.c  
src/unix/os390-syscalls.c  
src/unix/signal.c

Commenting out `pthread_atfork` in these files makes bind build.

On my ubuntu system `pthread_atfork` does not seem to exist anymore, but yet libuv builds.

```
$ objdump -t /usr/lib/x86_64-linux-gnu/libpthread.a | grep pthread_atfork
old_pthread_atfork.o:     file format elf64-x86-64
0000000000000000 l    df *ABS*	0000000000000000 old_pthread_atfork.c
```

My build chain identifies it self as arm-cortexa7hft-linux-gnueabi

How do I proceed on this problem?

**Comment by vtjnash** [comment]
The `pthread_atfork` calls are unnecessary, so you can simply delete them, if that works for you.

**Comment by bnoordhuis** [comment]
You're trying to link statically? I think this is a bug in some glibc versions - it should still be available in libpthread.so:
```
$ nm /lib/x86_64-linux-gnu/libpthread.so.0 | grep pthread_atfork
00000000000115b0 t __dyn_pthread_atfork
00000000000115b0 T pthread_atfork@GLIBC_2.2.5
```

**Comment by kjeldflarup** [comment]
I will stick to the explanation with the glibc version, and just patch until I can upgrade glibc.
