### ISSUE TITLE
Gitkraken doesn't use the macOS setting for double-clicking a window title bar

### ISSUE THREAD

**Issue by davenicoll** [libuv/libuv#3290]
* **Version**: 7.7.2
* **Platform**: macOS 11.4

When "Double click a window's title bar to..." is set to "Minimize" in macOS, double clicking the gitkraken title bar does not minimize the window - instead it resizes it. This is particularly jarring when every other window minimizes.

![image](https://user-images.githubusercontent.com/690117/131441793-0866740d-ee26-45e6-b292-cd59c6ec0242.png)

Ideally, gitkraken should respect the macOS setting, or allow the behaviour to be set independently in the gitkraken preferences.

**Comment by bnoordhuis** [comment]
Wrong bug tracker, I assume?
