### ISSUE TITLE
Use __attribute__((__may_alias__)) instead of asking for -fno-strict-aliasing

### ISSUE THREAD

**Issue by Matheus28** [libuv/libuv#3294]
Instead of requiring projects built with libuv use -fno-strict-aliasing, it might be desirable to apply `__attribute__(__may_alias__)` to libuv structs instead (platforms that support it should be the same as the ones that support -fno-strict-aliasing anyway). This way, libuv is not placing that burden on projects that depend on it.

Here's an example that shows this might suffice: https://godbolt.org/z/bGMKxKoTW (if you remove the attribute, it causes the function to always return 5). On MSVC it always seems to assume they might alias and does not require the attribute.

**Comment by bnoordhuis** [comment]
I'm open to the idea but are you 100% confident `-fno-strict-aliasing` and `__may_alias__` are interchangeable? I'm not.

gcc had (and some quick googling suggests may still have) bugs around correctly threading through `__may_alias__`. `-fno-strict-aliasing` is kind of a blunt force weapon but at least it's reliable.

**Comment by Matheus28** [comment]
I'm not a gcc developer so I can't be that confident. But it doesn't hurt to have that attribute AND the flag, for those who are paranoid. Libuv could be compiled with the flag (plus attribute on the public headers), while those daring enough could rely only on the attribute in the public headers.

**Comment by bnoordhuis** [comment]
Fair point. Want to open a PR?

**Comment by Matheus28** [comment]
Done https://github.com/libuv/libuv/pull/3295
