### ISSUE TITLE
uv_udp_send did not send the packet until he receive two packets

### ISSUE THREAD

**Issue by ydanzige** [libuv/libuv#3296]
* **Version**:   1.39.0 
* **Platform**:   linux 18.04  

When we sent a packet with uv_udp_send this is not really send until the second packet will came and then two packets together sent to the network.

When you open Wireshark you can see it easily - after two packages arrive they are sent together to the network

This cause latency issues.

In my small program I just receive messages from network on port 18080 and send it to port 18083 and as you can see in the wireshark, insted to recive one message and send it ,the libuv wait until he has two messages and then send them,

the code:
#include <stdio.h>
#include <string.h>

#include <iostream>
#include <memory>

#include "uv.h"

uv_udp_t socket = {};
int SendMsg(const uv_buf_t* buf);

static void PrintLibuvErrorMsg(int err_num) {
  char err_message[250] = {0};
  uv_strerror_r(err_num, err_message, sizeof(err_message));
  printf("Udp Filter: Error - %s\n", err_message);
}

void AllocBufferCb(uv_handle_t* /* handle*/, size_t /*suggested_size*/,
                   uv_buf_t* buf) {
  unsigned int size = 9000;
  char* data = new char[size];

  *buf = uv_buf_init(data, size);
}

void OnReceiveCb(uv_udp_t* /*req*/, ssize_t nread, const uv_buf_t* buf,
                 const struct sockaddr* addr, unsigned /* flags*/) {
  if (buf->base == nullptr) {
    printf("Error - No buffer recived\n");
    return;  // no buffer, so nothing to do
  }

  // error
  if (nread < 0) {
    PrintLibuvErrorMsg((int)nread);
    return;
  }

  // there is no more data to read
  if (addr == nullptr) {
    return;
  }

  SendMsg(buf);
}

void OnSendCb(uv_udp_send_t* req, int status) {
  char* buf = (char*)req->data;
  delete buf;
  delete req;  // delete the send request

  if (status) {
    PrintLibuvErrorMsg(status);
    return;
  }
}

int SendMsg(const uv_buf_t* buf) {
  uv_udp_send_t* send_req{nullptr};
  struct sockaddr_in send_addr = {};
  uv_buf_t msg = {};

  std::string dst_ip{"127.0.0.1"};
  uint16_t dst_port{18083};

  int res{0};

  send_req = new (std::nothrow) uv_udp_send_t;
  if (!send_req) {
    printf(": Error on memory allocation\n");
    goto exit_on_error;
  }
  memset(send_req, 0, sizeof(uv_udp_send_t));

  res = uv_ip4_addr(dst_ip.c_str(), dst_port, &send_addr);
  if (res != 0) {
    PrintLibuvErrorMsg(res);
    goto exit_on_error;
  }

  send_req->data = buf->base;
  msg = uv_buf_init(buf->base, (unsigned int)buf->len);
  
  res = uv_udp_send(send_req, &socket, &msg, 1,
                    (const struct sockaddr*)&send_addr, OnSendCb);
  if (res != 0) {
    PrintLibuvErrorMsg(res);
    goto exit_on_error;
  }

  return res;

exit_on_error:
  if (send_req != nullptr) {
    if (send_req->data != nullptr) {
      delete (char*)send_req->data;
    }
    delete send_req;
  }

  return res;
}

int main(int /*argc*/, char** /*argv*/) {
  setvbuf(stdout, NULL, _IONBF, 0);
  uv_loop_t* loop = uv_default_loop();
  int res = uv_udp_init(loop, &socket);
  if (res != 0) {
    PrintLibuvErrorMsg(res);
    return res;
  }

  struct sockaddr_in recv_addr;
  res = uv_ip4_addr("0.0.0.0", 18080, &recv_addr);

  if (res != 0) {
    PrintLibuvErrorMsg(res);
    return res;
  }

  res = uv_udp_bind(&socket, (const struct sockaddr*)&recv_addr, 0);
  if (res != 0) {
    PrintLibuvErrorMsg(res);
    return res;
  }

  res = uv_udp_recv_start(&socket, AllocBufferCb, OnReceiveCb);
  if (res != 0) {
    PrintLibuvErrorMsg(res);
    return res;
  }
  (void)uv_run(loop, UV_RUN_DEFAULT);  
  return 0;

* **The pcap**:
![pcap_libuv](https://user-images.githubusercontent.com/32995650/132125775-c2602940-07e3-4181-ae7f-fc5502a48e2d.png)

* **The code**:
[main.txt](https://github.com/libuv/libuv/files/7111523/main.txt)

**Comment by bnoordhuis** [comment]
You're the author of #3274, right? I'm going to close this as a duplicate, please continue in the other issue.
