### ISSUE TITLE
KERN_PROTECTION_FAILURE at address: 0x000000010001ba48

### ISSUE THREAD

**Issue by gbalakrishnan** [libuv/libuv#330]
Hi,
   I was trying to run the following program on my system (OS X 10.7.2) using the latest libuv.a built from source. 
```
int64_t counter=0;
void wait_for_a_while(uv_idle_t* handle){
        counter++;
        printf("%lld", counter);
        uv_idle_stop(handle);
}
int main(){
        uv_idle_t idler;
        uv_idle_init(uv_default_loop(), &idler);
        uv_idle_start(&idler, (uv_idle_cb)wait_for_a_while);
        printf("Idling \n");
        uv_run(uv_default_loop(), UV_RUN_DEFAULT);
        uv_loop_close(uv_default_loop());
        return 0;
}
```

Compiled it using the command (copied the lib file to current directory):
```
    
cc libuvsample.c -I/Users/girishbalakrishnan/Documents/mycode/nodejs/node-v0.10.35/deps/uv/include -L. -luv -framework CoreFoundation -framework CoreServices -g
```

On running a.out got the following error:
```
    
Idling 
Bus error: 10
```

On gdb I found the following error:
```
    
(gdb) n
22		uv_loop_close(uv_default_loop());
(gdb) n
23		return 0;
(gdb) n
0x000000010001ba48 in default_loop_struct ()
(gdb) n
Single stepping until exit from function default_loop_struct, 
which has no line number information.
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x000000010001ba48
0x000000010001ba48 in default_loop_struct ()
```
Any help is appreciated.
Thanks
Girish

**Comment by saghul** [comment]
uv_loop_close has an assert, in order to check if there are any handles in the loop. In your case the idle handle was not closed with uv_closed, so it would blow up.

I addition, didn't you get any compilation warnings? I see your idle callback doesn't have a 'status' argument, which was the case in libuv 0.10.

**Comment by gbalakrishnan** [comment]
I just copy pasted the code from "An Introduction to libuv". Not sure what you meant in your reply but I figured out that I was using the UV include files from Node-v0.10.35 and using the library from Libuv-1.x. When I changed that to include folder of Libuv-1.x it started working! No idea why though!
Thanks for the help.
