### ISSUE TITLE
An improper locking due to the unreleased lock before program exit

### ISSUE THREAD

**Issue by ryancaicse** [libuv/libuv#3300]
Hi developers, in the below codes, the lock `&b->mutex` could be not released before program's exit  `abort();`  when `b->in != 0` . I think there is no harm to write **uv_mutex_unlock(&b->mutex);**  before the `abort();` for better resource management and code symmetry. Thanks!

https://github.com/libuv/libuv/blob/e49ef4f309e631e2ecbeb7ff4397b0b073da681c/src/unix/thread.c#L121-L128

**Comment by vtjnash** [comment]
`abort()` will atomically free the lock, along with all other resources, at program exit
