### ISSUE TITLE
compile and check libuv on CentOS 6.6

### ISSUE THREAD

**Issue by allspace** [libuv/libuv#331]
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

./autogen.sh
./configure
make
make check

Get the following output:

=============================================================
[%  10|+  26|-   0|T   0|S   0]: pipe_set_non_blocking
`pipe_set_non_blocking` failed: exit code 6
Output from process `pipe_set_non_blocking`:
Assertion failed in test/test-pipe-set-non-blocking.c on line 51: n == 0
=============================================================
[%  76|+ 190|-   1|T   0|S   0]: spawn_setuid_setgid
`spawn_setuid_setgid` skipped
Output from process `spawn_setuid_setgid`:
user 'nobody' cannot access the test runner
=============================================================
[% 100|+ 248|-   1|T   0|S   1]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory `/root/libuv-1.4.2'
make: *** [check-am] Error 2

I also observed many following message during compile:

In file included from test/test-udp-multicast-ttl.c:23:
test/task.h:80:13: warning: anonymous variadic macros were introduced in C99
test/task.h:86:14: warning: anonymous variadic macros were introduced in C99

Let me know if I need provide more information.

**Comment by saghul** [comment]
Can you please try latest v1.x branch? Both problems should have been
solved already.

**Comment by allspace** [comment]
I am using libuv-1.4.2.

**Comment by saghul** [comment]
Those problems where solved after 1.4.2. You can just fetch latest v1.x or
wait for a release.
