### ISSUE TITLE
Windows fs__symlink creates invalid junctions when targeting soft directory links

### ISSUE THREAD

**Issue by andreasdamm** [libuv/libuv#3329]
Creating the following link under Windows results in a "File not found" error when trying to use it:

mkdir a
mklink /d b a
node -e fs.symlinkSync('b','c','junction')

Running

dir c

results in 'File Not Found'.

When using mklink instead of node to create link c, no errors occur:

rmdir c
mklink /j c b

The main difference between the link created by node (via libuv) and mklink can be seen from the output of fsutil.

For libuv the output of "fsutil reparsePoint query c" is

Reparse Tag Value : 0xa0000003
Tag value: Microsoft
Tag value: Name Surrogate
Tag value: Mount Point
Substitue Name offset: 0
Substitue Name length: 76
Print Name offset:     78
Print Name Length:     66
Substitute Name:       \??\C:\Users\Andreas\Documents\test\b\
Print Name:            C:\Users\Andreas\Documents\test\b

For mklink it is

Reparse Tag Value : 0xa0000003
Tag value: Microsoft
Tag value: Name Surrogate
Tag value: Mount Point
Substitue Name offset: 0
Substitue Name length: 74
Print Name offset:     76
Print Name Length:     66
Substitute Name:       \??\C:\Users\Andreas\Documents\test\b
Print Name:            C:\Users\Andreas\Documents\test\b

Notice the trailing slash of substitute name in the libuv link. That trailing slash is added by fs__symlink in src/win/fs.c and doesn't appear to cause any problems when targeting actual directories, but for a soft directory link (mklink /d) it does not work. The soft link doesn't have to be the actual target but can be anywhere on the targeted path for the problem to exhibit.

Should the trailing slash be removed? What was its original purpose? There is no mention in the Windows API documentation that requiring it.

* **Version**: 1.41.0
* **Platform**: Windows, 10.0.19043 Build 19043
* **Node Version**: v14.17.6

**Comment by bnoordhuis** [comment]
Your analysis sounds plausible, pull request welcome. I think the relevant code is around here (might also be about 20 lines lower):
https://github.com/libuv/libuv/blob/6564ccc90073296769ac17319bba3f3357005603/src/win/fs.c#L2419-L2433

**Comment by andreasdamm** [comment]
It would we important to first establish why the trailing backslash was added in the first place.
