### ISSUE TITLE
Using libuv to read from serial port

### ISSUE THREAD

**Issue by gbalakrishnan** [libuv/libuv#333]
I am new to programming using libuv and also not really an expert with C/C++. I was trying to use libuv since it allows asynchronous callbacks to read from serial port. I got a simple program from net that allows me to read from serial port and tried to integrate it with libuv so that I can access serial port from JavaScript in Node.js. I use OS X 10.7.2 as my OS. There are two methods I saw online. 
1) Using uv_file_*: When I used this technique I was getting "Read Error: Resource temporarily unavailable". When I debugged it was on a condition that it was failing pthread_cond_wait(). From here on I could not debug so not sure why it was failing. 
2) Using uv_pipe_*: When I used this technique everything was working fine except read() method would not return anything just nothing in the buffer. I guess this read() is the same from std C. The program which I got from net uses the same read() and it works fine. Again I could not debug it furher.

Is this an issue with libuv? What more info will you need to confirm it?
Thanks in advance.

**Comment by bnoordhuis** [comment]
> Is this an issue with libuv?

Yes and no but mostly no.  Once you have a file descriptor that refers to the serial port, you need to make ioctl() calls to set the line rate, parity, etc.  Libuv won't (and can't) do that for you.

Maybe have a look at https://github.com/voodootikigod/node-serialport?
