### ISSUE TITLE
[v0.10] General regression on arm64

### ISSUE THREAD

**Issue by lucab** [libuv/libuv#334]
libuv 0.10.28 was building and passing all tests on arm64 debian autobuilders (last tried on 2015-02-25).

With the latest upload of 0.10.36, the testsuite is now failing in multiple places (~150 tests failing):
 * https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=arm64&ver=0.10.36-1&stamp=1430172460
 * https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=arm64&ver=0.10.36-1&stamp=1430050989

This regression seems limited to arm64, as other arch are built fine.
Can anybody try on a different aarch64 machine, to confirm the regression?

**Comment by saghul** [comment]
Hi @lucab can you try applying this patch? https://github.com/libuv/libuv/commit/1d8332f7e6afb43daa08d643166c9e0cbdfa51a2

It made it to v1.x, but wasn't backported to v0.10. If tests pass I'll apply it there as well.

**Comment by lucab** [comment]
I'll do as soon as I've access to the arm64 porterbox, thanks for the hint.

**Comment by lucab** [comment]
```
[% 100|+ 197|-   0|T   0|S   0]: Done.
```

All tests passing on arm64 with above patch. Please backport, I'll wait for it in the next release.

**Comment by saghul** [comment]
Landed the backport in 8f931a2.
