### ISSUE TITLE
On BSDs,windows,z/OS the uv__udp_disconnect will error with EINVAL if the socket handle is ipv6

### ISSUE THREAD

**Issue by halx99** [libuv/libuv#3344]
https://github.com/libuv/libuv/blob/5246ce458af0a8ab90e896470789da1bb16e9106/src/unix/udp.c#L660

That caused by incorrect addrlen.

**Comment by bnoordhuis** [comment]
The code doesn't look wrong to me but please feel free to send a pull request with a fix. It wouldn't be the first time libuv hits a kernel bug on macos.

**Comment by halx99** [comment]
> The code doesn't look wrong to me but please feel free to send a pull request with a fix. It wouldn't be the first time libuv hits a kernel bug on macos.

Done.
