### ISSUE TITLE
z/OS test failures unmasked by https://github.com/libuv/libuv/pull/3323

### ISSUE THREAD

**Issue by richardlau** [libuv/libuv#3349]
* **Version**: v1.x
* **Platform**: z/OS

Looks like there are several tests consistently failing on z/OS since 10 Oct:
![image](https://user-images.githubusercontent.com/5445507/139918254-3724dd99-1ea5-4c8a-b685-63bd902e7cb5.png)

I've done some bisecting and narrowed it down to 6564ccc90073296769ac17319bba3f3357005603 (https://github.com/libuv/libuv/pull/3323):
Passing on c273d8b9cf4b3cbd4c896dc484c30c3e18a02d6e: https://ci.nodejs.org/job/libuv-test-commit-zos-cmake/1018/
Failing on 6564ccc90073296769ac17319bba3f3357005603: https://ci.nodejs.org/job/libuv-test-commit-zos-cmake/1019/

At first glance it seems confusing as the z/OS builds should not have any of the ASAN defines, but I think what has happened is the enumeration change in https://github.com/libuv/libuv/commit/6564ccc90073296769ac17319bba3f3357005603#diff-e57c72083d6a9b7bb10c57702f244f8c3770e2fa066008c3a3d80f4ac168c85a to renumber `TEST_SKIP` exit code has unmasked failures that were previously treated as skips.

Could someone from @libuv/zos take a look?

**Comment by richardlau** [comment]
Failure details:
```console
not ok 47 - fs_copyfile
# exit code 1
# Output from process `fs_copyfile`: (no output)
...
not ok 105 - fs_statfs
# exit code 1
# Output from process `fs_statfs`: (no output)
...
not ok 155 - loop_alive
# exit code 1
# Output from process `loop_alive`: (no output)
...
not ok 332 - threadpool_multiple_event_loops
# exit code 1
# Output from process `threadpool_multiple_event_loops`: (no output)
...
```
Previously exit code 1 was treated as `TEST_SKIP`.

**Comment by vtjnash** [comment]
Bump. Is there an active team for @libuv/zos?

I ran a new CI run for all platforms on v1.x: https://ci.nodejs.org/job/libuv-test-commit/2209/

**Comment by bnoordhuis** [comment]
@richardlau Can you coordinate with other IBM'ers?

**Comment by richardlau** [comment]
> @richardlau Can you coordinate with other IBM'ers?

I'll try reaching out in the shared IBM - Red Hat Slack workspace.

**Comment by IgorTodorovskiIBM** [comment]
@vtjnash, I'm a developer on the Node.js for z/OS team.  Can I be added to the https://github.com/orgs/libuv/teams/zos team?  
@zsw007 on my team is in the process of upstreaming our Node.js z/OS libuv changes, and will likely be the one looking into this issue.

**Comment by richardlau** [comment]
FWIW @IgorTodorovskiIBM did reach out to me about being added to the zos team here but I don't have permissions to invite/add people.

**Comment by zsw007** [comment]
I am currently looking into this issue.

**Comment by bnoordhuis** [comment]
@IgorTodorovskiIBM Added. I think you may have been a member before? I have a distinct recollection of adding you and GH, instead of sending an invite, added you immediately.

@richardlau I've made you team maintainer.

**Comment by richardlau** [comment]
Fixed by https://github.com/libuv/libuv/pull/3376 and setting an environment flag (https://github.com/libuv/libuv/pull/3376#issuecomment-985724894).
