### ISSUE TITLE
uv_loop_configure regression on mips/mipsel

### ISSUE THREAD

**Issue by lucab** [libuv/libuv#335]
A new `loop_configure` test has been recently backported into v0.10 branch.

With the latest upload of 0.10.36, this test seems to be failing on debian mips and mipsel autobuilders:
- https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=mips&ver=0.10.36-1&stamp=1430173093
- https://buildd.debian.org/status/fetch.php?pkg=libuv&arch=mipsel&ver=0.10.36-1&stamp=1430177717

As this is reliably failing the same way on 4 different machines, I suspect this new test uncovered a real issue somewhere. All other tests are fine.

**Comment by bnoordhuis** [comment]
Hard to tell.  I speculate that the epoll_pwait() system call fails but I don't have the hardware at hand to verify.

**Comment by lucab** [comment]
I can perform some specific checks as soon as I have access to the mips/mipsel porterboxes. Otherwise, we can manage to get you direct access to the machines as described here https://dsa.debian.org/doc/guest-account/

**Comment by bnoordhuis** [comment]
If you can get the test (not the test runner) strace'd, that should hopefully reveal the issue.  That's `strace test/.libs/run-tests loop_configure loop_configure` with the autotools build.

**Comment by lucab** [comment]
This is v0.10, building directly from Makefile. I tried on a fifth (mips64) porterbox machine, and it reliably fails there too. Kernel and glibc are as follow:
```
Linux eder 3.16.0-0.bpo.4-loongson-2e #1 Debian 3.16.7-ckt9-2~bpo70+1 (2015-04-21) mips64 GNU/Linux
eglibc | 2.13-38+deb7u6
```

I straced the test as follow (which I think it's equivalent to what you were asking):
```
strace -f ./run-tests loop_configure
```

This is the central part of the strace (runner startup omitted):
```
[pid 28196] set_thread_area(0x777a4cf0) = 0
[pid 28195] pipe([4294967295, 4294967295]) = 4
[pid 28195] mmap(NULL, 8388608, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x76584000
[pid 28195] mprotect(0x76584000, 16384, PROT_NONE) = 0
[pid 28195] clone(child_stack=0x76d83000, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x76d83508, tls=0x76d8a930, child_tidptr=0x76d83508) = 28197
[pid 28195] _newselect(5, [4], NULL, NULL, {5, 0}Process 28197 attached
 <unfinished ...>
[pid 28197] set_robust_list(0x76d83510, 12) = 0
[pid 28197] waitpid(28196,  <unfinished ...>
[pid 28196] mprotect(0x776b0000, 16384, PROT_READ) = 0
[pid 28196] munmap(0x777a0000, 12336)   = 0
[pid 28196] set_tid_address(0x7779d8c8) = 28196
[pid 28196] set_robust_list(0x7779d8d0, 12) = 0
[pid 28196] rt_sigaction(SIGRT_0, {0x77691bc8, [], SA_SIGINFO}, NULL, 16) = 0
[pid 28196] rt_sigaction(SIGRT_1, {0x77691ce4, [], SA_RESTART|SA_SIGINFO}, NULL, 16) = 0
[pid 28196] rt_sigprocmask(SIG_UNBLOCK, [RT_0 RT_1], NULL, 16) = 0
[pid 28196] getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=2147483647}) = 0
[pid 28196] rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTART}, {SIG_IGN, [], 0}, 16) = 0
[pid 28196] brk(0)                      = 0x6cc000
[pid 28196] brk(0x6f0000)               = 0x6f0000
[pid 28196] syscall(0x10e8, 0x55ada0, 0x80000, 0x6cc042, 0x47b1f0, 0x7778c0f8, 0x55adac) = 0
[pid 28196] write(5, "*", 1)            = 1
[pid 28196] futex(0x55adac, FUTEX_WAKE_PRIVATE, 2147483647) = 0
[pid 28196] clock_gettime(CLOCK_MONOTONIC, {130419, 380808584}) = 0
[pid 28196] syscall(0x10e6, 0x80000, 0xa350000, 0xf424, 0x47b1f0, 0x1fd73, 0x16b2ad88) = 6
[pid 28196] syscall(0x10e8, 0x55ace0, 0x80080, 0, 0x47b1f0, 0x55ac94, 0x55ad08) = 0
[pid 28196] syscall(0x10e5, 0, 0x80080, 0x55ac50, 0x47b1f0, 0x1, 0x560000) = 9
[pid 28196] clock_gettime(CLOCK_MONOTONIC, {130419, 381342065}) = 0
[pid 28196] syscall(0x1099, 0x6, 0x1, 0x7, 0x7f88aea8, 0, 0x47b1f0) = 0
[pid 28196] syscall(0x1099, 0x6, 0x1, 0x9, 0x7f88aea8, 0, 0x47b1f0) = 0
[pid 28196] syscall(0x10d9, 0x6, 0x7f88af38, 0x400, 0x9, 0x7f88ae78, 0x8) = -1 EINVAL (Invalid argument)
[pid 28196] clock_gettime(CLOCK_MONOTONIC, {130419, 381879706}) = 0
[pid 28196] rt_sigprocmask(SIG_UNBLOCK, [IOT], NULL, 16) = 0
[pid 28196] tgkill(28196, 28196, SIGIOT) = 0
[pid 28196] --- SIGIOT {si_signo=SIGIOT, si_code=SI_TKILL, si_pid=28196, si_uid=2891} ---
[pid 28196] +++ killed by SIGIOT +++
[pid 28195] <... _newselect resumed> )  = ? ERESTARTNOHAND (To be restarted if no handler)
[pid 28195] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=28196, si_uid=2891, si_status=SIGIOT, si_utime=0, si_stime=0} ---
[pid 28195] _newselect(5, [4], NULL, NULL, {4, 991810} <unfinished ...>
[pid 28197] <... waitpid resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGIOT}], 0) = 28196
[pid 28197] write(5, "\0", 1 <unfinished ...>
[pid 28195] <... _newselect resumed> )  = 1 (in [4], left {4, 991597})
[pid 28195] close(4)                    = 0
[pid 28195] close(5)                    = 0
[pid 28195] write(2, "\n`loop_configure` failed: exit code 6"..., 38
```

According to the [current linux-mips syscall table](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/mips/include/uapi/asm/unistd.h), above anonymous syscalls should map as follow:
 * 0x10e6 -> epoll_create1
 * 0x10e8 -> pipe2
 * 0x10e5 -> eventfd2
 * 0x1099 -> epoll_ctl
 * 0x10d9 -> epoll_pwait

So it looks like `epoll_pwait()` is indeed failing with a EINVAL.

**Comment by lucab** [comment]
Bumping, as this regression is currently blocking newer libuv0.10 migration across debian suites.

I collected some facts, but as I'm new to these internals, I'd like someone to double check my findings.

Commit fa0b08ff switched epoll_pwait sigmask size calculation from using portable types to an hardcoded uint64_t. mips signal are a bit weird (eg. SIGPROF is 27 everywhere, but 29 on mips). In particular, it looks like kernel headers define `_NSIG ` as 128.

This is what I have on a mips system:
```
/usr/include/signal.h:200:# define NSIG _NSIG
/usr/include/signal.h:303:extern const char *const _sys_siglist[_NSIG];
/usr/include/signal.h:304:extern const char *const sys_siglist[_NSIG];
/usr/include/mips-linux-gnu/asm/signal.h:14:#define _NSIG               128
/usr/include/mips-linux-gnu/asm/signal.h:15:#define _NSIG_BPW   (sizeof(unsigned long) * 8)
/usr/include/mips-linux-gnu/asm/signal.h:16:#define _NSIG_WORDS (_NSIG / _NSIG_BPW)
/usr/include/mips-linux-gnu/asm/signal.h:19:    unsigned long sig[_NSIG_WORDS];
/usr/include/mips-linux-gnu/asm/signal.h:61:#define SIGRTMAX    _NSIG
/usr/include/mips-linux-gnu/bits/signum.h:67:#define _NSIG              128     /* Biggest signal number + 1
/usr/include/mips-linux-gnu/bits/signum.h:76:#define __SIGRTMAX (_NSIG - 1)
/usr/include/asm-generic/signal.h:6:#define _NSIG               64
/usr/include/asm-generic/signal.h:7:#define _NSIG_BPW   __BITS_PER_LONG
/usr/include/asm-generic/signal.h:8:#define _NSIG_WORDS (_NSIG / _NSIG_BPW)
/usr/include/asm-generic/signal.h:51:#define SIGRTMAX   _NSIG
/usr/include/asm-generic/signal.h:88:   unsigned long sig[_NSIG_WORDS];
```

I see the kernel having an [explicit check](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/eventpoll.c#n2019) for the length parameter to be exactly `sizeof(sigset_t)`.

Thus, I suspect the syscall is being rejected as the sigmask length on mips doesn't match.

**Comment by saghul** [comment]
Nice find! I guess that could be it. I think @bnoordhuis is a bit swamped these days, he'll probably come back to this when he's got the time.

**Comment by bnoordhuis** [comment]
Sorry, I think I missed the notification for @lucab's second-to-last comment.  I don't have much time at the moment but I would be okay with a patch that drops the epoll_wait/epoll_pwait system call wrappers for their glibc equivalents.  I originally added them as workarounds for ancient 2.6.x installs with broken system headers.

**Comment by lucab** [comment]
@bnoordhuis from what I understood, something like lucab/libuv@de298f5. Not touching `epoll_wait` as I have no issues with it.

**Comment by bnoordhuis** [comment]
@lucab That looks alright to me at a quick glance although I'd be perfectly fine with dropping the system call wrappers altogether.  Can you PR your changes?

**Comment by milani** [comment]
What is the status of this issue?

**Comment by lucab** [comment]
To the best of my knowledge, this issue is still open and affect both 0.10.x and 1.x. I'm still carrying an [ad-hoc patch](https://sources.debian.net/src/libuv1/1.9.1-1/debian/patches/mips-epoll_pwait.diff/) (the one proposed in #351) in Debian for it.

**Comment by milani** [comment]
Thanks!
