### ISSUE TITLE
inet: inet_ntop6 get inconsistent value from `src` and set into `dst`

### ISSUE THREAD

**Issue by duskmoon314** [libuv/libuv#3366]
* **Version**: libuv/master
* **Platform**: Linux 5.11.0-40-generic 20.04.2-Ubuntu SMP x86_64 GNU/Linux

I'm trying to implement a `uv_ip_name` function to handle both IPv4 and IPv6 names as I suggested in #3365. And I find this issue when trying to build a test.

When calling `inet_ntop6` on the same `sockaddr_in6* src` more than once, it sets inconsistent values:

```c
ASSERT(0 == uv_ip6_addr("fe80::1", TEST_PORT, addr6));

ASSERT(0 == uv_ip6_name(addr6, dst, INET6_ADDRSTRLEN));
fprintf(stderr, "test ip6 name 1 %s\n", dst);
// This prints: test ip6 name 1 fe80::1

ASSERT(0 == uv_ip6_name(addr6, dst, INET6_ADDRSTRLEN));
fprintf(stderr, "test ip6 name 2 %s\n", dst);
// This prints: test ip6 name 2 fe80::6665:3830:3a3a:3100

ASSERT(0 == uv_ip6_name(addr6, dst, INET6_ADDRSTRLEN));
fprintf(stderr, "test ip6 name 3 %s\n", dst);
// This prints: test ip6 name 3 fe80::6665:3830:3a3a:3636
```

I checked and found that in `inet_ntop6`, the `tmp` value is inconsistent that is copied into `dst` is inconsistent.

**Comment by duskmoon314** [comment]
Weirdly, I can not reproduce this on macOS (M1) when I copy uv_ip6_name and related functions out of the lib. 😢

**Comment by bnoordhuis** [comment]
I can't reproduce with the tip of the v1.x branch on a Linux system similar to yours. Note the master branch is not where active development takes place.

**Comment by duskmoon314** [comment]
I found out that the reason was that I had mistakenly overlapped the `src` and `dst` spaces. 🤕
