### ISSUE TITLE
clang-format or bust?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#338]
I think we all agree that pointing out style issues during code review is tedious, time consuming and off-putting to new contributors.

I propose we start using clang-format from now on and initial churn be damned.  It should not affect existing pull requests because we can just run those through git-clang-format.

We'll need to agree on the clang version to use.  I suggest the latest stable, 3.6.0, because clang-format has seen some significant improvements since the 3.5.x series.

Opinions?

Refs #61.

/cc @piscisaureus @saghul

**Comment by saghul** [comment]
When we tried results where mixed, but having a consistent style would be A Good Thing (TM). So +1 from me. FWIW I'm using Debian Sid and I have clang 3.4-3.7 in the repos, so 3.6 works for me.

**Comment by llafuente** [comment]
+1

I prefer a batch file that update format like: https://github.com/llafuente/string.c/blob/master/format.sh
Reasons:
* Available when cloning
* Version check if needed
* Exclude files/path

**Comment by saghul** [comment]
Bust, I guess?

(feel free to bring it up again, I'm just house-keeping)
