### ISSUE TITLE
reported bad windows version on Windows 11

### ISSUE THREAD

**Issue by nassau-t** [libuv/libuv#3381]
It seems that windows 11 version is not well returned. The keys that should be read:

// CurrentMajorVersionNumber present in registry starting with Windows 10
// If CurrentMajorVersionNumber not present in registry then use CurrentVersion
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentMajorVersionNumber
// CurrentMinorVersionNumber present in registry starting with Windows 10
// If CurrentMinorVersionNumber not present in registry then use CurrentVersion
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentMinorVersionNumber

on windows 10 I have
CurrentMajorVersionNumber 10
CurrentMinorVersionNumber 0

**Comment by bnoordhuis** [comment]
Pull request welcome. Node's `os.version()` is the result of reading the `version` field after calling `uv_os_uname()`.

The `version` is populated from the `SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName` registry key. I suppose that has to change somehow.

**Comment by gengjiawen** [comment]
@joaocgreis I want to take a poke on this, can you setup an win11 machine for me.
