### ISSUE TITLE
uv_write returns error synchronously on Windows

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#339]
Ref: https://github.com/iojs/io.js/pull/1563#issuecomment-97716588
Patch: https://gist.github.com/saghul/e05b99b1b16a7c9c15e9

I'll work on a test, shouldn't be hard to write.

/cc @piscisaureus

**Comment by alexlamsl** [comment]
iojs/io.js#1512 still reproducible in `iojs 2.0.0` - may be it is waiting for this to be fixed as well?

**Comment by saghul** [comment]
I don't know if the patch linked here got floated in iojs, it's not yet
included in libuv.

**Comment by silverwind** [comment]
It didn't, and as far as I understand, @indutny did include only a partial change of the io.js-side so far wich alone wasn't enough as a fix.

I'd be great if this fix could be included in 1.5.0.

**Comment by saghul** [comment]
@silverwind I will include it.

**Comment by saghul** [comment]
Landed in f880023. CI run showind a green Windows build: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/91/

**Comment by silverwind** [comment]
Awesome, thanks!

**Comment by indutny** [comment]
@saghul may I ask you to send a PR once you'll do a release?

**Comment by indutny** [comment]
Sure, thank you very much!
