### ISSUE TITLE
Add OS info preceding tests

### ISSUE THREAD

**Issue by jbergstroem** [libuv/libuv#34]
Currently, interface and cpu/memory information precedes test output. In order to simplify submitting test failures, the info could benefit from os/architecture information as well (see for instance #30).

Another option would be writing fail output and a summary to a markdown document for easier pasting. Come to think of it, this sounds like a pretty nifty C library :)

**Comment by sztomi** [comment]
@saghul, is this something you would still add to libuv? If so, I would take look.

**Comment by saghul** [comment]
I'm open to suggestions :-)

**Comment by sztomi** [comment]
I'm thinking something along the lines of uv_cpu_info_t, but for OS information. 

```c

typedef enum { android, aix, win, unix, darwin } uv_sys_kind_t;

typedef struct uv_kernel_version_s {
  int major;
  int minor;
  int patch;
  int build;
  char* extra_string;
} uv_kernel_version_t;

typedef struct uv_os_info {
  uv_sys_kind_t sys;
  char* sysname_string; /* "Windows", "Android" etc. */
  char* release_string; /* "Vista", "XP", "trusty" etc.*/
  uv_kernel_version_t kernel_version; /* structure to allow testing the versions numerically */
} uv_os_info_t;

/* Retrieve OS information */
int uv_os_info(uv_os_info_t*);

/* Pretty print OS information */
int uv_strosinfo(char*, uv_os_info_t*);
```
(just as a quick sketch, I need to familiarize myself with the project more, but you get the idea)

It might make sense to return the kernel version in a struct. As for the implementation, GetVersion&friends on Windows, uname on posix-friendly systems, plus trying to read /etc/lsb-release or issue etc. files. (I think it would be nice if the implementation detected the distributions on *nix).

Is this something like what you had in mind?

**Comment by saghul** [comment]
@sztomi thios is good work, thanks! I'll need a few days to work through the mail pile, but this is a good start IMHO.

**Comment by zhaozg** [comment]
Need this feature thanks

**Comment by sztomi** [comment]
@saghul cool, then I'll try to whip out an initial implementation on my fork and let you know here when I have something to show.

**Comment by saghul** [comment]
No follow-up, closing. Feel free to open a PR when ready.
