### ISSUE TITLE
Broken release tarball in dist.libuv.org/dist/v1.43.0/

### ISSUE THREAD

**Issue by Mno-hime** [libuv/libuv#3401]
The release tarball in https://dist.libuv.org/dist/v1.43.0/ looks broken, it's just 20 bytes:
```
Index of /dist/v1.43.0/

../
libuv-v1.43.0.tar.gz                               04-Jan-2022 14:21                  20
libuv-v1.43.0.tar.gz.sign                          04-Jan-2022 14:21                 874
```

**Comment by bnoordhuis** [comment]
Paging @cjihrig - I guess something went wrong with the release tool?

@Mno-hime Thanks for the report. You can use https://github.com/libuv/libuv/releases/tag/v1.43.0 in the interim.

**Comment by cjihrig** [comment]
Yea I'm not sure exactly what happened. There were some hiccups with the release. I regenerated the artifacts and uploaded them manually.

@Mno-hime can you take another look?

**Comment by Mno-hime** [comment]
Looks good to me now. Thanks!
