### ISSUE TITLE
doc: documentation on uv_fs_cb is missing

### ISSUE THREAD

**Issue by LBPHacker** [libuv/libuv#3402]
I'm opening this issue prepared to be declared blind and pointed at the relevant bit of documentation, but I've looked far and wide, and it's definitely not in this repo, not in a form that a `grep` can find.

**Comment by bnoordhuis** [comment]
Seems it's indeed not documented anywhere. Pull request welcome, the type is `void (*)(uv_fs_t*)` (and `uv_fs_t` _is_ documented.)

**Comment by LBPHacker** [comment]
Alright, thanks for confirming. I opted for an issue because I wasn't sure *what* to say about this callback; does it boil down to

> Callback called when a request is completed asynchronously.

?

**Comment by bnoordhuis** [comment]
Pretty much, yes. :-)

**Comment by LBPHacker** [comment]
Great, I'll open a PR as soon as I figure out how to generate the current documentation. (README.md seems outdated regarding how this is done.)

**Comment by LBPHacker** [comment]
I hadn't realized you're supposed to use the Makefile in doc/ until I read the README for a second time jus tnow later. Will make a PR soon.
