### ISSUE TITLE
Assertions fail for "udp_multicast_interface" and "udp_no_autobind" during multi-arch docker builds

### ISSUE THREAD

**Issue by basarsoker** [libuv/libuv#3404]
I try to build a single image for multiple architectures _(arm64 and amd64)_  with docker buildx, but unfortunately, it fails during the tests. Here is the output,

> #9 1338.5 not ok 366 - udp_multicast_interface
#9 1338.5 # exit code 6
#9 1338.5 # Output from process `udp_multicast_interface`:
#9 1338.5 # Assertion failed in test/test-udp-multicast-interface.c on line 78: r == 0
#9 1338.5 # qemu: uncaught target signal 6 (Aborted) - core dumped
#9 1338.6 ok 367 - udp_multicast_interface6 # SKIP IPv6 not supported
#9 1338.6 ok 368 - udp_multicast_join
#9 1338.6 ok 369 - udp_multicast_join6 # SKIP No external IPv6 interface available
#9 1338.6 ok 370 - udp_multicast_ttl
#9 1338.6 not ok 371 - udp_no_autobind
#9 1338.6 # exit code 6
#9 1338.6 # Output from process `udp_no_autobind`:
#9 1338.6 # Assertion failed in test/test-udp-options.c on line 135: UV_EBADF == uv_udp_set_multicast_interface(&h, "0.0.0.0")
#9 1338.6 # qemu: uncaught target signal 6 (Aborted) - core dumped

I am pretty sure this is particular to the multi-arch builds since I built an image successfully with the same Dockerfile without docker buildx. 

I follow the "build with autotools" method for the installation. 

Any help would be appreciated.

**libuv version:** 1.42.0

**Comment by bnoordhuis** [comment]
Those tests don't work under qemu because it doesn't implement the requisite socket options.

The cmake build has a `-DQEMU=ON` switch that disables them and a few others; do a `grep __QEMU__ test/` to see which.

For the autotools build, setting `CPPFLAGS=-D__QEMU__=1` may work (untested however.)

**Comment by basarsoker** [comment]
`CPPFLAGS=-D__QEMU__=1` works like a charm 😃  thanks a lot!

**Comment by vtjnash** [comment]
FWIW, that QEMU flag is a workaround for a problem with our docker configuration that is used in CI, not libuv itself

I have a PR awaiting review to fix the CI configuration and remove the workaround (https://github.com/libuv/libuv/pull/2941)

**Comment by basarsoker** [comment]
So do you mean after the PR is merged, the flag will become idle?

**Comment by vtjnash** [comment]
Yes, it not an issue with qemu, but an issue with the docker environment being used
