### ISSUE TITLE
Tilde paths are not interpreted (e.g. ~/.yarn/bin) by uv_spawn

### ISSUE THREAD

**Issue by erahhal** [libuv/libuv#3409]
* **Version**: 1.42.0 (or whatever version is in NeoVim 0.6.1)
* **Platform**: Linux thinkpad-t490s 5.15.11 #1-NixOS SMP Wed Dec 22 08:32:52 UTC 2021 x86_64 GNU/Linux

I'm using the LSP server in NeoVim, and couldn't get it to work. It turns out that the language server binary path in my PATH variable was using tilde paths (e.g. ~/.yarn/bin) and according to NeoVim IRC at Libera, they mentioned that uv_spawn doesn't support tilde paths.

**Comment by bnoordhuis** [comment]
Tilde expansion is a feature of the shell, not of execve(). The latter is the primitive underlying uv_spawn().

Instead of calling (pseudo syntax):
```c
uv_spawn("~/.yarn/bin/lsp", ["script.js"]);
```
Call:
```c
uv_spawn("/bin/sh", ["~/.yarn/bin/lsp", "script.js"]);
```
