### ISSUE TITLE
android: use libc getifaddrs

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3411]
Android natively supports `getifaddrs()` since 7.0 (NDK >= 24), released in 2016. I propose removing our homegrown implementation in favor of libc's.

<hr>

SUPPORTED_PLATFORMS.md says NDK >= 15b (why the 'b'?) works but I'm reasonably confident it's been NDK >= 21 for years.

**Comment by gengjiawen** [comment]
It's true they have a weird version

https://developer.android.com/ndk/downloads/revision_history
