### ISSUE TITLE
UDP recvmmsg broken with MUSL 1.2.2

### ISSUE THREAD

**Issue by oerdnj** [libuv/libuv#3416]
* **Version**: 1.35.0-1.43.0
* **Platform**: Linux alpine-3-14 5.10.43-0-lts #1-Alpine SMP Fri, 11 Jun 2021 07:41:12 +0000 x86_64 Linux
* **Libc**: musl-1.2.2-r7

I don't have a simple reproducer (yet), but after I fixed our code (BIND 9) to explicitly enable UDP_RECVMMSG by passing the correct flags to `uv_udp_init_ex()`, our unit test no longer passes on Alpine 3.15 (it does pass correctly on every other Linux and all the BSDs).

So far, this is just a heads up that there might be something wrong with MUSL and `recvmmsg()` and I'll be filling more details as I'll further debug the issue.

**Comment by oerdnj** [comment]
Ok, first fact, the MUSL can't handle bigger buffer, this patch will make the `make check` fail:
```
diff --git a/test/test-udp-mmsg.c b/test/test-udp-mmsg.c
index fb241151..401c4f33 100644
--- a/test/test-udp-mmsg.c
+++ b/test/test-udp-mmsg.c
@@ -29,9 +29,9 @@
 #define CHECK_HANDLE(handle) \
   ASSERT((uv_udp_t*)(handle) == &recver || (uv_udp_t*)(handle) == &sender)

-#define BUFFER_MULTIPLIER 4
+#define BUFFER_MULTIPLIER 20
 #define MAX_DGRAM_SIZE (64 * 1024)
-#define NUM_SENDS 8
+#define NUM_SENDS 40
 #define EXPECTED_MMSG_ALLOCS (NUM_SENDS / BUFFER_MULTIPLIER)

 static uv_udp_t recver;
 ```

Such big buffer works just perfectly fine with Linux and glibc and/or BSDs, so it's something related to MUSL (or something else in the Alpine Linux 3.15).

**Comment by oerdnj** [comment]
FTR the `20` is taken from `src/unix/udp.c:UV__MMSG_MAXWIDTH`

**Comment by santigimeno** [comment]
It seems initializing `struct mmsghdr` to zero similarly as what we do in the `recvmsg` path fixes the `EMSGSIZE` error.
```
diff --git a/src/unix/udp.c b/src/unix/udp.c
index aee8d639..9208e319 100644
--- a/src/unix/udp.c
+++ b/src/unix/udp.c
@@ -194,6 +194,7 @@ static int uv__udp_recvmmsg(uv_udp_t* handle, uv_buf_t* buf) {
   int flags;
   size_t k;
 
+  memset(&msgs, 0, sizeof(struct uv__mmsghdr) * UV__MMSG_MAXWIDTH);
   /* prepare structures for recvmmsg */
   chunks = buf->len / UV__UDP_DGRAM_MAXSIZE;
   if (chunks > ARRAY_SIZE(iov))
```
Now the modified test fails with an assertion I haven't had a chance to look into.

**Comment by oerdnj** [comment]
I can't reproduce this using simple test program that uses `recvmmsg()` libc call instead of the kernel call, but there are obviously some quirks related to the interaction between the kernel and MUSL: https://git.musl-libc.org/cgit/musl/commit/?id=7168790763cdeb794df52be6e3b3

And in fact, I have verified, that setting the extra padding to NULL makes the problem go away:
```
diff --git a/src/unix/udp.c b/src/unix/udp.c
index aee8d639..66fe6b20 100644
--- a/src/unix/udp.c
+++ b/src/unix/udp.c
@@ -202,6 +202,8 @@ static int uv__udp_recvmmsg(uv_udp_t* handle, uv_buf_t* buf) {
     iov[k].iov_base = buf->base + k * UV__UDP_DGRAM_MAXSIZE;
     iov[k].iov_len = UV__UDP_DGRAM_MAXSIZE;
     msgs[k].msg_hdr.msg_iov = iov + k;
+    msgs[k].msg_hdr.__pad1 = 0;
+    msgs[k].msg_hdr.__pad2 = 0;
     msgs[k].msg_hdr.msg_iovlen = 1;
     msgs[k].msg_hdr.msg_name = peers + k;
     msgs[k].msg_hdr.msg_namelen = sizeof(peers[0]);
```

I think the easiest solution here would be either to use the libc `recvmmsg` call instead of the direct syscall or to copy `struct msghdr` to `struct uv__msghdr` and use `size_t` (double-check with glibc and BSDs):

```
diff --git a/src/unix/internal.h b/src/unix/internal.h
index 12d4da93..e670bcfa 100644
--- a/src/unix/internal.h
+++ b/src/unix/internal.h
@@ -334,20 +334,38 @@ int uv__getsockpeername(const uv_handle_t* handle,
                         struct sockaddr* name,
                         int* namelen);

-#if defined(__linux__)            ||                                      \
-    defined(__FreeBSD__)          ||                                      \
+#if defined(__linux__)
+#define HAVE_MMSG 1
+struct uv__msghdr {
+       void *msg_name;
+       socklen_t msg_namelen;
+       struct iovec *msg_iov;
+       size_t msg_iovlen;
+       void *msg_control;
+       size_t msg_controllen;
+       int msg_flags;
+};
+
+struct uv__mmsghdr {
+  struct uv__msghdr msg_hdr;
+  unsigned int msg_len;
+};
+#elif defined(__FreeBSD__)        ||                                       \
     defined(__FreeBSD_kernel__)   ||                                       \
     defined(__DragonFly__)
 #define HAVE_MMSG 1
+
 struct uv__mmsghdr {
   struct msghdr msg_hdr;
   unsigned int msg_len;
 };
+#else
+#define HAVE_MMSG 0
+#endif

+#if HAVE_MMSG
 int uv__recvmmsg(int fd, struct uv__mmsghdr* mmsg, unsigned int vlen);
 int uv__sendmmsg(int fd, struct uv__mmsghdr* mmsg, unsigned int vlen);
-#else
-#define HAVE_MMSG 0
 #endif

 #if defined(__sun)
```

Do you want me to turn this into PR?

**Comment by oerdnj** [comment]
@santigimeno Just read your comment. Yes, this aligns with my findings, but would this reduce the performance since you need to clear quite a chunk of memory only to be overwritten a second later?

It's a shame that libuv is sticking with C89. Designated initializers would be a very elegant solution to this.

**Comment by vtjnash** [comment]
> would this reduce the performance since you need to clear quite a chunk of memory only to be overwritten a second later?

No, compilers should happily handle that

**Comment by oerdnj** [comment]
Ok then. Zeroing the struct should work too. As a matter of fact it should be done for all use of struct msghdr. Also struct cmsghdr suffers from the same padding problem if you ever use it.
