### ISSUE TITLE
Improve uv_getrusage with Windows Performance Data Helper <pdh.h>

### ISSUE THREAD

**Issue by ghost** [libuv/libuv#342]
* http://www.microsoft.com/msj/1299/pdh/pdh.aspx (1999)
* https://msdn.microsoft.com/en-us/library/windows/desktop/aa373088.aspx
* http://stackoverflow.com/a/64166/863980

Please make use of `<pdh.h>` to get fields matching those obtained from `getrusage()` on Unix, so to avoid this kind of disparity: https://github.com/iojs/io.js/pull/1568/files#diff-b8683bd937113f052f1698c61ed8c10d.

Thank you.

**Comment by saghul** [comment]
Mind sending a PR? That would be great! At any rate, thanks for the links!

**Comment by jasonwilliams200OK** [comment]
@lodejard,

https://github.com/nodejs/node/pull/1568#issuecomment-132076551

can you provide some help to filling the gap in implementation for windows?
The Unix code lives in src/unix/core.c, which gets all the performance and process-info related fields from `sys/resource.h`. In windows those can be fetched from `pdb.h` in a bit different manner.

**Comment by iWuzHere** [comment]
I don't think anyone is currently working on this, I don't mind giving it a try, but it wont be high priority for me and will probably take a while since I'm not too used to windows dev.

**Comment by jasonwilliams200OK** [comment]
@iWuzHere, @orangemocha mentioned here: https://github.com/nodejs/node/pull/1568#issuecomment-132157405 that they have this ticket as a task in their TODO queue. Perhaps someone has already started working on it?

> I'm not too used to windows dev.

That's like a national anthem of node.js community :stuck_out_tongue_winking_eye:  (jk)

**Comment by iWuzHere** [comment]
Alright so began looking at the issue, here is the current information that is not being populated

```
  //Things that are missing
  long   ru_ixrss;         /* integral shared memory size */		(unmaintained)
  long   ru_idrss;         /* integral unshared data size */		(unmaintained)
  long   ru_isrss;         /* integral unshared stack size */		(unmaintained)
  long   ru_minflt;        /* page reclaims (soft page faults) */
  long   ru_nswap;         /* swaps */								(unmaintained)
  long   ru_inblock;       /* block input operations */
  long   ru_oublock;       /* block output operations */
  long   ru_msgsnd;        /* IPC messages sent */					(unmaintained)
  long   ru_msgrcv;        /* IPC messages received */				(unmaintained)
  long   ru_nsignals;      /* signals received */					(unmaintained)
  long   ru_nvcsw;         /* voluntary context switches */
  long   ru_nivcsw;        /* involuntary context switches */
```

Some fields have been marked as `(unmaintained)` as those are not populated in linux (may be populated in other operating systems).

Been reading up on the `<pdh.h>` stuff and it doesn't (at least from what I've seen) seem to give total numbers but mostly per second numbers, i.e. if I want to monitor context switching (don't know to differentiate between voluntary and involuntary) I would have to add a counter using pdh for `“Thread(<process-name>/<thread-number>)/Context Switches/sec”` which only gives a per thread number of context switches per second. Compared to linux/unix which just has `int getrusage(int who, struct rusage *usage);` that gives us all the information we care about quite nicely and easily, this is going to be quite complicated I don't know if its going to be possible either (at least for some of the data).

**Comment by iWuzHere** [comment]
![filesystem reads and write](https://i.imgur.com/UAVOXCy.png)

I guess that's how we would go about getting `ru_inblock` and `ru_outblock` but again this is per second data not total. I wonder if multiplying by process run time in seconds would give us the data we are interested in

**Comment by iWuzHere** [comment]
Just leaving this here as a probably useful link
http://www.appadmintools.com/documents/windows-performance-counters-explained/

**Comment by jasonwilliams200OK** [comment]
Another useful resource: https://github.com/openvswitch/ovs/blob/master/lib/getrusage-windows.c

**Comment by iWuzHere** [comment]
As for the remaining 3 values (`ru_minflt`, `ru_nvcsw` and `ru_nivcsw`) I do not see a way to get the required information on windows.

That being said, unless unless someone knows how to get that information, I think this issue should be closed.

**Comment by saghul** [comment]
Agreed, @iWuzHere feel free to close it. Maybe make a documentation PR indicating the unsupported fields?

**Comment by iWuzHere** [comment]
I'll do that tonight!
