### ISSUE TITLE
compilation warning on libuv 

### ISSUE THREAD

**Issue by deleisha** [libuv/libuv#343]
Perhaps, happens when assert is not enabled.   

CC(target) out/Release/obj.target/libuv/deps/libuv/src/uv-common.o
../deps/libuv/src/uv-common.c: In function âuv_loop_deleteâ:
../deps/libuv/src/uv-common.c:535:7: warning: variable âerrâ set but not used [-Wunused-but-set-variable]
   int err;
       ^

**Comment by saghul** [comment]
We could stick a (void)err; to squelch it, I guess.

**Comment by saghul** [comment]
Fixed in 710fcf7, thanks!
