### ISSUE TITLE
inconsistent return type of uv_uptime

### ISSUE THREAD

**Issue by lal12** [libuv/libuv#3447]
Since commit b2ccbbb8a4b66a718298df65ac283e2056e211fa on linux uv_uptime will (in most cases) return a fractional uptime. In itself this is fine and I personal would prefer that, but apparently an extra `floor` was added in the windows implementation to get same behavior on all platforms (61a8d97ad9eff8a5e8b0d05d3b421062cd5427de). So this at least should be discussed.

Edit: there is an related NodeJS issue for this https://github.com/nodejs/node/issues/41636

**Comment by bnoordhuis** [comment]
I'd say it's okay to remove the floor() call. Want to send a PR?

**Comment by lal12** [comment]
I have no windows setup to test this, but yeah I could do a PR.

Just wanted to clarify: This change will lead to inconsistent behavior for some (maybe more rare) systems. However this is not really problematic IMO since if you expect a double / fractional number you still are able to work with an integer / ".0".

**Comment by bnoordhuis** [comment]
> I have no windows setup to test this

Me neither, but that doesn't have to be a problem with CI-driven development. :-)

> This change will lead to inconsistent behavior for some (maybe more rare) systems.

Yes, understood. I don't think it'll be a problem. Worst case, someone complains and we'll revert it again.

**Comment by lal12** [comment]
Just created PR. Apparently some systems already returned fractional seconds anyway, so it is not a new inconsistency anyway.
