### ISSUE TITLE
Feature request: uv wrappers for dup() and dup2() primitives

### ISSUE THREAD

**Issue by zackw** [libuv/libuv#3448]
libuv should expose wrappers for the [dup() and dup2()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/dup.html) system calls.

See https://github.com/nodejs/node/issues/41733 for rationale.

**Comment by vtjnash** [comment]
I have these (in an old PR here), and been meaning to get around to this for years. You want F_DUPFD specifically though here.

**Comment by bnoordhuis** [comment]
I've read through nodejs/node#41733 but I don't understand why dup2() is needed for stdio. It's not going to solve the problem of intermingled logging.

**Comment by bnoordhuis** [comment]
Closing, no clear use case and no follow-up.
