### ISSUE TITLE
uv_loop_fork does not fix received signals

### ISSUE THREAD

**Issue by SmorkalovG** [libuv/libuv#3483]
* **Version**: 1.41.0
* **Platform**: `Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux`

After fork a child process goes in infinite loop using 100% cpu if a signal was received just before fork.
```
#include <uv.h>
#include <unistd.h>

void nosignal(uv_signal_t* h, int s){}
void nohandle(uv_handle_t* h){}

int main(int argc, char** argv)  {
    uv_loop_t loop;
    uv_loop_init(&loop);

    uv_signal_t sig;
    uv_signal_init(&loop, &sig);
    uv_signal_start(&sig, &nosignal, SIGHUP);

    int pid = getpid();
    kill(pid, SIGHUP);
    if (!fork()) {
        uv_loop_fork(&loop);
        uv_close((uv_handle_t*)&sig, &nohandle);
    }
    uv_run(&loop, UV_RUN_DEFAULT);
    return 0;
}

```
This code is the simplest way I found to reproduce the bug. In real life code fork was called right inside the signal handler.

Original process does nothing after fork. It runs loop and waits for signal. It is ok.
Child process should exit from loop after dispatching the close event, but it does not do so. It runs loop without any timeout using 100% of cpu.

This happens because libuv cannot close the signal handler. In uv__finish_close (unix/core.c) there is a check `if (sh->caught_signals > sh->dispatched_signals) {` that leads to uv__make_close_pending of signal. In normal case signal event is dispatched on the next loop iteration but after fork it would never happen. Signal should be read from loop->signal_pipefd that was closed and recreated in uv_loop_fork. So caught_signals is always bigger than dispatched_signals and loop keep running. And closing handles leads to epoll_wait timeout being 0 and it leads to 100% cpu load.

I think that uv_loop_fork should reset `caught_signals` and `dispatched_signals` for all signals in all loops. Signals written to loop->signal_pipefd was sent to master process, so child should not receive them. I can make a PR with this fix.

**Comment by vtjnash** [comment]
Sounds reasonable. Though I would strongly suggest not using `fork`, as it is very hard to reset all state correctly, and likely impossible in a program that uses threads or signals.
