### ISSUE TITLE
libuv install error

### ISSUE THREAD

**Issue by lianzishu** [libuv/libuv#3491]
I install libuv in ubuntu, when I use root to execute "make check", got error as this:
The libuv test suite cannot be run as root.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:5277: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: 离开目录“/usr/src/libuv”
Makefile:5533: recipe for target 'check-am' failed
make: *** [check-am] Error 2

when I use normal user to execute "make check", I got error:
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:5277: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: 离开目录“/usr/src/libuv”
Makefile:5533: recipe for target 'check-am' failed
make: *** [check-am] Error 2

please tell me, what should I do? Thanks!

**Comment by AnyFlyGuy** [comment]
same here:
```
ok 401 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5554: check-TESTS] Fehler 1
```
