### ISSUE TITLE
uv_tcp_bind and uv_listen do not fail if the handle is being closed

### ISSUE THREAD

**Issue by nickappleton** [libuv/libuv#3503]
**Version**: 1.43.0
**Platform**: Tested on Windows 10 and OS X

Hello, thanks for a great library and apologies if this is noise/expected-behavior.

If `uv_close()` is invoked on a TCP socket followed by `uv_tcp_bind()` and `uv_listen()`:
* `uv_tcp_bind()` and `uv_listen()` both succeed on both Windows and OS X. I expect them to fail.
* On Windows, `uv_run()` will block and listen for a connection. `on_connect()` in the code to reproduce below will be called if a connection is made.
* On OS X, `uv_run()` will assert with the message in the code to reproduce below.

```c
#include "uv.h"
#include <stdlib.h>
static void on_connect(uv_stream_t* server, int status) {
	/* I don't expect to ever be able to hit this, but I can */
	abort();
}
int main(int argc, char *argv[]) {
	uv_loop_t loop;
	uv_tcp_t tcp;
	struct sockaddr_in addr;

	memset(&addr, 0, sizeof(addr));
	addr.sin_addr.s_addr = htonl(INADDR_ANY);
	addr.sin_port        = htons(7999);
	addr.sin_family      = AF_INET;

	if (uv_loop_init(&loop)) abort();
	if (uv_tcp_init(&loop, &tcp)) abort();
	uv_close((uv_handle_t *)&tcp, NULL);
	/* I don't expect this to return zero */
	if (uv_tcp_bind(&tcp, (struct sockaddr *)&addr, 0)) abort();
	/* I also don't expect this to return zero */
	if (uv_listen((uv_stream_t *)&tcp, 5, on_connect)) abort();
	/* I expect this to terminate immediately, but it hangs on Windows (on OSX it fails with an assertion).
	 *
	 * Assertion failed: (!uv__io_active(&stream->io_watcher, POLLIN | POLLOUT)), function uv__stream_destroy, file stream.c, line 459. */
	(void)uv_run(&loop, UV_RUN_DEFAULT);

	return 0;
}
```

**Comment by bnoordhuis** [comment]
That's indeed an oversight. Want to send a pull request with a fix?

**Comment by nickappleton** [comment]
Yes sure. Been juggling kids+work but will do this as soon as I get some downtime :)
