### ISSUE TITLE
Add OpenBSD/FreeBSD to CI

### ISSUE THREAD

**Issue by jamessan** [libuv/libuv#3510]
> Regarding OpenBSD CI - is that something we could incorporate into the GitHub Actions CI?

After a little searching, I found https://github.com/cross-platform-actions/action which looks promising.

_Originally posted by @jamessan in https://github.com/libuv/libuv/issues/3452#issuecomment-1059280887_

**Comment by cjihrig** [comment]
Copying part of my comment from the other issue:

> We already have a [QEMU based CI](https://github.com/libuv/libuv/blob/c40f8cb9f8ddf69d116952f8924a11ec0623b445/.github/workflows/CI.yml#L69-L118) that we might be able to extend.

I think if possible, we should go that route.

**Comment by qbit** [comment]
There is also: https://github.com/mario-campos/emulate
