### ISSUE TITLE
timer.c heap for timers: unix only?

### ISSUE THREAD

**Issue by cyisfor** [libuv/libuv#357]
I was looking at the (rather large) amount of code differing between the windows and the unix versions, expecting to see things like IOCP and #include <windows.h> and Wsaapietc, but in timer.c I noticed that the unix version had been converted to use a heap instead of an RB tree back around 2013, but the windows version had not. Using a heap makes sense because of the O(1) lookup for the first timer to expire, but was it just convenience that prevented both unix and MS from using the same timer.c code, or is something about src/heap-impl.h not workable in Microsoft? It only includes stddef.h...

Just something I noticed. Doesn't break anything, just a possible future simplification.

**Comment by bnoordhuis** [comment]
I think we simply never came around to updating the Windows code.  @piscisaureus Does that sound about right?

**Comment by cynron** [comment]
https://github.com/joyent/libuv/pull/1476

**Comment by piscisaureus** [comment]
What @bnoordhuis said sounds about right. Also, I don't recall looking at @cynron's PR ever, should we land that?

**Comment by saghul** [comment]
IIRC the numbers weren't great, but I think the tests exhibited the worst
case scenario.

I'd be +1 to landing if there is no performance penalty, but might have to
dance around the ABI compatibility.

**Comment by cyisfor** [comment]
No hurry or anything. It was just something curious I noticed. Thanks for the quick response!

**Comment by txdv** [comment]
@saghul you can close this now, since https://github.com/libuv/libuv/commit/912d42b7285fc29869472106d1c736f34ac91521
