### ISSUE TITLE
win: uv_pipe_connect() + uv_close() race condition

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3578]
Refs: https://github.com/nodejs/node/issues/42496

uv_pipe_connect() runs pipe_connect_thread_proc() in a separate thread.

uv_close() clears `handle->name` in uv_pipe_cleanup(), which pipe_connect_thread_proc() reads.

**Comment by vtjnash** [comment]
Semi-relatedly, it looks like we also have various thread functions (e.g. pipe_shutdown_thread_proc) that access the `handle` field, and not lock around it, while it appears to often be closed quite eagerly.
