### ISSUE TITLE
Question: user data pointer in callback functions

### ISSUE THREAD

**Issue by allspace** [libuv/libuv#361]
libuv uses callback functions to give user a chance to run his/her own code for some events.

but, in those callback functions, there is no parameter for transferring user data.

So, how to transfer data across different functions?

this may be especially an issue when I have to encapsulate libuv using c++ where I have to transfer "this" pointer across different functions.

**Comment by bnoordhuis** [comment]
Can you direct questions to [the mailing list](http://groups.google.com/group/libuv)?  Cheers.
