### ISSUE TITLE
Embed test broken on IBM i

### ISSUE THREAD

**Issue by richardlau** [libuv/libuv#3614]
* **Version**:  v1.x
* **Platform**: IBM i

https://github.com/libuv/libuv/pull/3608 rewrote the embed test but this is now timing out consistently on IBM i in the CI, 

e.g.
https://ci.nodejs.org/view/libuv/job/libuv-test-commit-ibmi-cmake/1008/BUILDTYPE=Release,nodes=ibmi73-ppc64/console
https://ci.nodejs.org/view/libuv/job/libuv-test-commit-ibmi/558/nodes=ibmi73-ppc64/console
```
not ok 29 - embed
# timeout
# Output from process `embed`: (no output)
```

cc @libuv/ibmi

**Comment by bnoordhuis** [comment]
Before #3608 the test was a no-op on IBM i so it's probably not so much that the PR broke the test but exposed that embedding is broken.
