### ISSUE TITLE
test-callback-order.c     may be wrong ?

### ISSUE THREAD

**Issue by aladeng555** [libuv/libuv#3618]
``
/* idle_cb should run before timer_cb */
static void idle_cb(uv_idle_t* handle) {
  ASSERT(idle_cb_called == 0);
  ASSERT(timer_cb_called == 0);
  uv_idle_stop(handle);
  idle_cb_called++;
}

static void timer_cb(uv_timer_t* handle) {
  ASSERT(idle_cb_called == 1);
  ASSERT(timer_cb_called == 0);
  uv_timer_stop(handle);
  timer_cb_called++;
}

// ? 应该是timer_cb 先执行吧
static void next_tick(uv_idle_t* handle) {
  uv_loop_t* loop = handle->loop;
  uv_idle_stop(handle);
  uv_idle_init(loop, &idle_handle);
  uv_idle_start(&idle_handle, idle_cb);
  uv_timer_init(loop, &timer_handle);
  uv_timer_start(&timer_handle, timer_cb, 0, 0);
}
``

**Comment by aladeng555** [comment]
idle_cb should run before timer_cb ?  or,  timer_cb first ?

**Comment by bnoordhuis** [comment]
I've opened #3619 to remove the test. The test is wrong, that's why it's disabled - timer_cb comes first.
