### ISSUE TITLE
I have some questions with the macro QUEUE in the queue.h

### ISSUE THREAD

**Issue by Coder-chen** [libuv/libuv#362]
In the src :
  #define QUEUE_NEXT(q)    (* ( QUEUE  **  )  &((*(q))[0]))
  Why cast the pointer &((*(q))[0]) to the ( QUEUE** ) ? 
  could i just  #define QUEUE_NEXT(q)   (*(q))[0]) .

**Comment by bnoordhuis** [comment]
See commit 05204648 for the reasons why.  Can you post questions to the mailing list next time?  Thanks.

**Comment by Coder-chen** [comment]
oh,I am sorry, If i have questions next time,I will use mailing list.I am a newer to use github,sorry to disturb you!!! thanks to solve the problems!!!

**Comment by bnoordhuis** [comment]
No problem. :-)

**Comment by Coder-chen** [comment]
hi,sorry to distrub you again,
Could you give me the address of mailing list of the libuv? I cannot find it in this project...thanks a lot.

**Comment by bnoordhuis** [comment]
Of course.  It's http://groups.google.com/group/libuv or libuv@googlegroups.com.

**Comment by Coder-chen** [comment]
Thanks very much !!!
