### ISSUE TITLE
Add CMake configuration option to disable shared library build

### ISSUE THREAD

**Issue by KivApple** [libuv/libuv#3637]
I am using libuv in the project which targets multiple platforms including WebAssembly (in this case a large networking part of my project is disabled, but I still use libuv for multithreading and synchronization primitives). I include libuv using add_subdirectory and use static linking, but there are no way to disable shared library building and for WASM platform (which doesn't support shared libraries) I got annoying warnings:

```
CMake Warning (dev) at lib/libuv/CMakeLists.txt:391 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Is it possible to add an option to disable shared library building (many other libraries have that)?

**Comment by justinmk** [comment]
Not stale, we are waiting on https://github.com/libuv/libuv/pull/3698
