### ISSUE TITLE
uv_cpu_info() gives wrong frequency on Apple M1 Pro

### ISSUE THREAD

**Issue by fxcoudert** [libuv/libuv#3642]
* **Version**: 1.44.1
* **Platform**: `Darwin meau.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64`

```
$ cat a.c
#include <uv.h>
#include <stdio.h>

int main (void) {
  uv_cpu_info_t *x;
  int n;
  uv_cpu_info (&x, &n);
  printf("%d\n", x[0].speed);
  uv_free_cpu_info (x, n);
  return 0;
}
$ clang a.c -I/opt/homebrew/opt/libuv/include -L/opt/homebrew/opt/libuv/lib -luv && ./a.out
24
```

Seems to be saying 24 MHz, which is, well, not the real frequency.

**Comment by gbaraldi** [comment]
The fun thing is, it's technically the right one, it's what `sysctl hw.cpufrequency` gives back on a rosetta terminal:
```shell
❯ uname -a
Darwin Gabriels-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 x86_64

~ 
❯ sysctl hw.cpufrequency
hw.cpufrequency: 2400000000
```
 and it's probably the same place where libuv get's it. I haven't found a way to query the actual cpu frequency outside of `powermetrics` which requires `sudo`

**Comment by vtjnash** [comment]
That gives 2.4 GHz, so that is the right answer

**Comment by vtjnash** [comment]
But we don't use that since https://github.com/libuv/libuv/pull/2914, since it was apparently unavailable

**Comment by giordano** [comment]
But the maximum clock of the performance cores should be 3.2 GHz, not 2.4 GHz

**Comment by gbaraldi** [comment]
`uv__get_cpu_speed` gives 24000000 as the speed which is where the error comes from, now i don't know enough about IOKit to know if we get the wrong address or if for some reason it returns it on multiples of 100hz.
