### ISSUE TITLE
Logic error for function uv__fs_to_timespec

### ISSUE THREAD

**Issue by JesseCodeBones** [libuv/libuv#3672]
currently I am testing uvwasi `uvwasi_path_filestat_set_times` function.
I found I cannot get the correct response, and I tried to trace the process flow and I found the code under:
https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c
with function `uv__fs_to_timespec`
and in the code block I found:
```C
UV_UNUSED(static struct timespec uv__fs_to_timespec(double time)) {
  struct timespec ts;
  ts.tv_sec  = time;
  ts.tv_nsec = (time - ts.tv_sec) * 1e9;
//......
}
```
the issue is, it provides `time` parameter to `ts.tv_sec`, but use `(time - ts.tv_sec)` as the value of `ts.tv_nsec` which is always be 0.
is this a mistake or by design, can you advise? thank you.

* **Version**: 1.44.1
* **Platform**: 42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bnoordhuis** [comment]
There's no bug. `ts.tv_sec  = time` converts from double to integer. Read it as `ts.tv_sec  = trunc(time)`.

Another way of writing it would've been this:
```c
struct timespec ts;
double secs;
double frac;
frac = modf(time, &secs);
ts.tv_sec = secs;
ts.tv_nsec = frac * 1e9;
```

**Comment by JesseCodeBones** [comment]
@bnoordhuis 
Thank you for the rapid explanation, I got it.
