### ISSUE TITLE
documentation should identify offset < 0 feature of uv_fs functions

### ISSUE THREAD

**Issue by schveiguy** [libuv/libuv#3676]
* **Version**: v1.x
* **Platform**: N/A

I am just starting to use libuv, and was perplexed that there isn't a function to read from a file descriptor without seeking in the file. However, seeing some example code online, and upon examining the code, I've found that if `-1` is used as the offset, then it does exactly this. However, this is not mentioned in the documentation at all. It just says "same as preadv".

**Comment by cjihrig** [comment]
PRs to improve the docs are always welcome - they are admittedly sparse in some places.

**Comment by schveiguy** [comment]
Will gladly do it if you point me at a file!

**Comment by cjihrig** [comment]
Sure thing: https://github.com/libuv/libuv/blob/v1.x/docs/src/fs.rst
