### ISSUE TITLE
Convert code to use C11 atomics

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#3683]
Switching our hand-rolled atomics implementations to use the "new" C11-standard versions would be better supported for compilers and tools (such as TSAN), which would be helpful for testing and maintenance in the future.

Refs: https://github.com/libuv/libuv/issues/3622

**Comment by bnoordhuis** [comment]
#3688. There's an InterlockedOr8 I could stil replace in src/win/async.c but I'm unclear on the status of C11 atomics support on Windows.
