### ISSUE TITLE
trace the elapsed time of every phase of event loop

### ISSUE THREAD

**Issue by theanarkh** [libuv/libuv#3687]
Hi, will Libuv support tracing the elapsed time of every phase of event loop(like `uv_metrics_idle_time`) ? Libuv can notify user(maybe by a callback which is set by user ?) the elapsed time after running every phase.

**Comment by vtjnash** [comment]
I recommend using perf. There used to be dtrace hooks in here, but this wasn't that useful

**Comment by theanarkh** [comment]
Thanks for reply. I think `perf` is good for analyzing problems but i hope i can get the elapsed time in runtime for `APM`.
