### ISSUE TITLE
Setting `UV_INHERIT_FD` when calling `uv_spawn()` makes child process inherit all file descriptors

### ISSUE THREAD

**Issue by fabinader** [libuv/libuv#3716]
Hi,

   I'm trying to spawn a child process (some legacy app which does not use `libuv`) and use an anonymous pipe between the two processes to exchange messages between them:

````
         ┌──────┐            ┌──────┐
      ┌──►stdout│            │stderr◄───┐
      │  └────▲─┘            └──▲───┘   │
      │       │                 │       │
      │       └─────────────────┼────┐  │
      │                         │    │  │
      │  ┌──────────────────────┘    │  │
      │  │                           │  │
  ┌───┴──┴─┐                     ┌───┴──┴─┐
  │        │      ┌───────┐      │        │
  │        ├──────►pipe_in├──────►        │
  │        │      └───────┘      │        │
  │ parent │                     │ child  │
  │        │      ┌────────┐     │        │
  │        ◄──────┤pipe_out◄─────┤        │
  │        │      └────────┘     │        │
  └───▲────┘                     └────▲───┘
      │                               │
      │                               │
      │                               │
      │           ┌─────┐             │
      └───────────┤stdin├─────────────┘
                  └─────┘
````

   If I write the client in `python3`, I can use e.g. `subprocess.Popen()` with the parameter `pass_fds=(pipe_in_r, pipe_out_w)`, and pass two environment variables `FD_IN` and `FD_OUT` to indicate the values of `pipe_in_r` and `pipe_out_w`, and the child process will be created only inheriting the reading side of `pipe_in` and the writing side of `pipe_out`, and everything works smoothly.
   However, if I do this with a C application using `libuv`, the child process is created with both reading and writing sides of the pipe from the parent process, i.e. even if I only specify `UV_INHERIT_FD` for fd_in_pipe[0] and fd_out_pipe[1], the child process will also inherit the file descriptors for `fd_in_pipe[1]` and `fd_out_pipe[1]`:
[pipe_parent.c.zip](https://github.com/libuv/libuv/files/9307999/pipe_parent.c.zip)

   However, the documentation in the documentation in http://docs.libuv.org/en/v1.x/process.html#c.uv_stdio_flags clearly states that `The child process will be given a duplicate of the parent's file descriptor given by 'data.fd'`, i.e. only the specified file descriptors will be inherited.

   Is this a bug or expected behavior?

* **Version**:  1.24.1
* **Platform**:  Debian 10

**Comment by bnoordhuis** [comment]
Can you try with v1.44.2? Your copy of libuv is almost 4 years old now.

**Comment by bnoordhuis** [comment]
Closing, two weeks with no follow-up.
