### ISSUE TITLE
tcp socket buffer size

### ISSUE THREAD

**Issue by theanarkh** [libuv/libuv#3722]
Should not we set `SO_SNDBUF` or `SO_RCVBUF` on TCP socket by `uv_xxx_buffer_size` ?

**Comment by bnoordhuis** [comment]
Depends. Do you know what the right value for your send and receive buffers is? The kernel probably knows better than you do.

**Comment by theanarkh** [comment]
Yes, The kernel will adjust it, I'm just curious what the point of this API is. Because I'm going to add it to Node.js, Do you think it's necessary ?

**Comment by bnoordhuis** [comment]
It works for both protocols but the point still stands that the kernel almost always has better insight than you, the application programmer. I've been writing networked programs for 25 years now and I don't think I've ever had a legitimate use case for tweaking send/receive buffers.

**Comment by theanarkh** [comment]
Thank you for your explanation !
