### ISSUE TITLE
uv_os_homedir broken on Windows XP

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#374]
https://github.com/libuv/libuv/issues/11#issuecomment-106295168

**Comment by cjihrig** [comment]
I'll try to set up an XP VM today and work on this.

**Comment by bnoordhuis** [comment]
Do we still care about Windows XP?  Maybe it's time to drop support for it.

**Comment by saghul** [comment]
**I** don't personally, but I recall briefly talking with @piscisaureus about it and we kind of agreed we'd keep it in the v1.x series as long as it didn't make things super-hard.

Since the fix here is (hopefully) just an *ifdef* I'd say we keep support for it.

When we dump support for XP and 2k3 we can potentially delete a ton of code from src/win :-)

FWIW, does Node (officially or not) work on / support XP?

**Comment by cjihrig** [comment]
I believe the support is unofficial at this point. See this recent [comment](https://github.com/joyent/node/pull/25367#issuecomment-104743959). It looks like there was some confusion in that thread as to whether or not libuv even supported XP anymore :-)

**Comment by piscisaureus** [comment]
> FWIW, does Node (officially or not) work on / support XP?

Node v0.12 was broken for a while, io.js still works.

> When we dump support for XP and 2k3 we can potentially delete a ton of code from src/win :-)

One thing to note is that dropping XP support doesn't really make a difference unless we also drop Server 2003 support. Extended support for 2k3 ends [July 14th](https://www.microsoft.com/en-us/server-cloud/products/windows-server-2003), which is 6 weeks from now. 

What amazes me though is that (when disregarding mobile operating systems), [XP still has a bigger market share than all non-windows operating systems combined](http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0).

**Comment by cjihrig** [comment]
@piscisaureus there is a warning in the comments of https://msdn.microsoft.com/en-us/library/bb762494.aspx stating that `CSIDL_PROFILE` on Windows XP can be translated to the wrong directory under certain scenarios. They commenter suggests using `GetUserProfileDirectory()`. What do you suggest?

**Comment by saghul** [comment]
Oh, nice find @cjihrig!

**Comment by saghul** [comment]
Closing, lets continue in #375
