### ISSUE TITLE
threadpool: the number of tasks

### ISSUE THREAD

**Issue by theanarkh** [libuv/libuv#3741]
Can Libuv add a function to get the number of tasks waiting to be processed in the thread pool ?

**Comment by bnoordhuis** [comment]
It could but what would you use it for?

**Comment by theanarkh** [comment]
I'm not sure whether it is useful to know the status of the thread pool, such as the number of `UV__WORK_FAST_IO`, and `UV__WORK_SLOW_IO` tasks. I think the info can be printed in the Node.js diagnostic report.

**Comment by bnoordhuis** [comment]
I suspect that the number of tasks is a pretty irrelevant metric. Knowing how long they stay in the queue is probably a lot more useful.

If you have a single task that's stuck for an hour, that's a problem. If you have a million tasks that are all gone the next millisecond, there's no problem.

**Comment by theanarkh** [comment]
Thanks for explanation, I will collect the cost time of task in Node.js.
