### ISSUE TITLE
libuv timer list node not delete after  uv_timer_stop

### ISSUE THREAD

**Issue by zhangzhiming865** [libuv/libuv#3750]
* **Version**: v1.x
* **Platform**: ubuntu 20.02
* 

code path:
uv_timer_init->uv__handle_init->QUEUE_INSERT_TAIL(&(loop_)->handle_queue, &(h)->handle_queue); 
uv_timer_stop->(none any QUEUE_REMOVE) ?
thanks

**Comment by bnoordhuis** [comment]
The timer is not removed from loop->handle_queue until it's closed with uv_close().

**Comment by zhangzhiming865** [comment]
> 

ok，thanks，so uv_close is async for delete a timer ?

**Comment by zhangzhiming865** [comment]
> The timer is not removed from loop->handle_queue until it's closed with uv_close().

what if just QUEUE_REMOVE in uv_timer_stop?

**Comment by bnoordhuis** [comment]
Then you're using libuv in a way it's not supposed to be used. If it breaks, you get to keep both pieces.
