### ISSUE TITLE
Pipes created uv_pipe cannot be opened uv_pipe_open on ipc mode

### ISSUE THREAD

**Issue by number201724** [libuv/libuv#3763]
* **Version**: 1.44.2
* **Platform**: Windows 
```

	uv_loop_t slave_loop;
	uv_pipe_t slave_pipe;
	uv_pipe_t master_pipe;

	
	uv_loop_init(&slave_loop);
	uv_pipe_init(uv_default_loop(), &master_pipe, 1);

	int rc = uv_pipe(fds, UV_NONBLOCK_PIPE, UV_NONBLOCK_PIPE);
	if (rc != 0)
		abort();

	rc = uv_pipe_init(&slave_loop, &slave_pipe, 1);
	if (rc != 0)
		abort();

	rc = uv_pipe_open(&master_pipe, fds[1]);  // wtf
	if (rc != 0)
		abort();

	rc = uv_pipe_open(&slave_pipe, fds[0]);
	if (rc != 0)
		abort();

```

src\win\pipe.c
```
  if (pipe->ipc) {
    if (!(access.AccessFlags & FILE_WRITE_DATA) ||
        !(access.AccessFlags & FILE_READ_DATA)) {
      return UV_EINVAL;
    }
  }
```

Possible fixes:
1. Use undocumented UV_READABLE_PIPE and UV_WRITABLE_PIPE (http://docs.libuv.org/en/v1.x/pipe.html)
2. Modify the check in src\win\pipe.c

**Comment by vtjnash** [comment]
`ipc` expects a bi-directional pipe, which may mean a `socketpair` elsewhere, so it may be inconsistent what you need

**Comment by number201724** [comment]
> `ipc` expects a bi-directional pipe, which may mean a `socketpair` elsewhere, so it may be inconsistent what you need

Pipelines created with uv_pipe do not explicitly bi-directional.

Perhaps you need to add uv_pipe and UV_READABLE_PIPE to UV_WRITABLE_PIPE documents.
In addition uv_pipe_open need to indicate that a bi-directional pipe is required.

**Comment by number201724** [comment]
It seems that the ipc pipe under the windows platform needs bi-directional pipe?
But maybe not under *nix?
Because libuv example seems to fill only one direction.
https://github.com/delaemon/libuv-tutorial/blob/master/multi-echo-server-worker.c

**Comment by bnoordhuis** [comment]
I think there is nothing to do for us here? I'm going to close the issue but @number201724, if you feel the documentation can be improved somehow, then please open a pull request with your suggestions.
