### ISSUE TITLE
Feature request: add way to get total cores per system

### ISSUE THREAD

**Issue by dead-claudia** [libuv/libuv#3775]
`uv_cpu_info` is great for getting an idea how to distribute I/O-bound workloads, but CPU-bound workloads tend to not gain much from SMT (and sometimes even *lose* performance), so I'd like a way to get the total *cores* instead so I can more effectively balance them.

As an implementation note, most devices only support 1-2 threads per core, but this isn't universal - IBM's Power series chips generally do nowadays with the decade-old POWER7 supporting 4 threads per core and all subsequent iterations supporting 8 threads per core (including the Power10 released last year). So you can't just check if SMT is available and double the core count.

**Comment by bnoordhuis** [comment]
It's not wholly clear to me if you're asking for physical or logical core count. Either has the problem that not all cores may be available to your program.

Libuv has a `uv_available_parallelism()` function as of v1.44.0, see #3493 for background. Is that perhaps what you're looking for?

**Comment by dead-claudia** [comment]
@bnoordhuis Specifically physical core count. `uv_cpu_info` returns only logical cores, and it doesn't include any field for physical core IDs (I could just count uniques with that). A way to get the true number of physical cores available to the program would technically be ideal, of course, but that's beyond my immediate needs.

Of course, I could also just parse `/proc/cpuinfo` to get this information too (as I also happen to control the OS it runs on), and it's not that hard to loop through. If this is preferred to actually implementing it in libuv, feel free to close this.

**Comment by bnoordhuis** [comment]
Sounds reasonable, I think. I don't plan on working on it myself but if you send a pull request, I'll be happy to review it.

**Comment by bnoordhuis** [comment]
I'll go ahead and close this out but you're still welcome to send a PR.
