### ISSUE TITLE
Possibly unsafe check in test

### ISSUE THREAD

**Issue by trevnorris** [libuv/libuv#3785]
In the test https://github.com/libuv/libuv/blob/v1.x/test/test-udp-send-hang-loop.c there is the assignment:
```
req->handle = NULL;
```
followed later by:
```
ASSERT_NULL(send_req.handle);
```
I wanted to verify if this check is actually safe since I believe `uv_udp_send_t::handle` is a private field and shouldn't be manually set by the user.

**Comment by cjihrig** [comment]
Looks like it's documented as public - https://docs.libuv.org/en/v1.x/udp.html#public-members

**Comment by trevnorris** [comment]
Thanks. I had extended the `/* private */` comment in `UV_REQ_FIELDS` into the `uv_udp_send_t` struct. So it looked private after resolving the macros.
