### ISSUE TITLE
Allow minimum stack size to be specified for pool threads

### ISSUE THREAD

**Issue by Colengms** [libuv/libuv#3786]
We're seeing an issue due to the limited stack size of pool threads.

I guess RLIMIT_STACK can be used to set the stack sizes on Mac and Linux, but what about Windows?

**Comment by bnoordhuis** [comment]
RLIMIT_STACK is a glibc-ism; musl libc for example ignores it. Libuv papers over that difference. It honors RLIMIT_STACK but if that's set to infinity, it makes a best guess.

(That's on Linux. On other platforms, it leaves it up to the pthreads implementation.)

I've opened #3787 to give threads a predictable stack size.
