### ISSUE TITLE
question about kqueue

### ISSUE THREAD

**Issue by theanarkh** [libuv/libuv#3790]
Hi, i have a question about `kqueue`. The code is as follows. 
```
for (i = 0; i < nfds; i++) {
  ev = events + i;
  fd = ev->ident;
  w = loop->watchers[fd];

  if (w == NULL) {
    struct kevent events[1];

    EV_SET(events + 0, fd, ev->filter, EV_DELETE, 0, 0, 0);
    if (kevent(loop->backend_fd, events, 1, NULL, 0, NULL))
      if (errno != EBADF && errno != ENOENT)
        abort();

    continue;
  }
```
When `w` is NULL, and filter is `EVFILT_READ & EVFILT_WRITE`, can we delete the two events in one `kevent` call ? I read some example code of `kqueue`, it seems the `kevent` should be called for each event.

**Comment by bnoordhuis** [comment]
You can pass two `struct kevent` calls, one for `EVFILT_READ`, one for `EVFILT_WRITE`, in a single `kevent()` system call.

It happens to work on my machine but it's something of an open question how portable that is.

**Comment by theanarkh** [comment]
Hi, Ben, thanks for the reply. I wonder if it's possible to delete two events in one struct, it seems it is impossible.
