### ISSUE TITLE
uv_translate_sys_error translates ENODATA to unknown system error

### ISSUE THREAD

**Issue by romayalon** [libuv/libuv#3795]
* **Platform**: linux/mac

uv_translate_sys_error doesn't translate ENODATA thrown from getxattr system call as it should. instead, it's translated to `Unknown system error -61`.
would be happy if it can be added to the code, thanks

**Comment by bnoordhuis** [comment]
Pull request welcome, I suppose, but do I understand correctly this is somewhat self-inflicted? Libuv doesn't use getxattr() so I'm wondering how that ENODATA error ends up inside libuv.

**Comment by theanarkh** [comment]
It seems the error is triggered by `SetSyscallError` in `GetSingleXattr::Work `([code](https://github.com/romayalon/noobaa-core/blob/d7d6a4f3440fdaabcd8733e1ae2b88da9acad238/src/native/fs/fs_napi.cpp)).

**Comment by romayalon** [comment]
@bnoordhuis @theanarkh correct, it's self-inflicted, ENODATA is not thrown out of uv_translate_sys_error but uv_translate_sys_error & uv_err_name are used for translation of general error codes

**Comment by bnoordhuis** [comment]
Right. Exporting `uv_translate_sys_error()` was a mistake IMO (used to be internal) but since it's there, I suppose it's reasonable to handle ENODATA. I've opened #3802.
