### ISSUE TITLE
uv_poll_cb getting status == -9 (UV_EBADF), not UV_DISCONNECT

### ISSUE THREAD

**Issue by jensbjorgensen** [libuv/libuv#3796]
* **Version**: 1.44.1
* **Platform**: Linux host 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I have a program which registers for events on tcp sockets with uv_poll_*. There are cases where "something" happens with a tcp socket (don't have a packet trace to see exactly what) that seems to result in the TCP connection closing. I'm registered for UV_READABLE and UV_DISCONNECT at the time and I get a uv_poll_cb call with status == -9. After this has happened the socket looks like this in the lsof output:

xxxxxxxx 393026 xxxxxxxx   16u     sock                0,8      0t0 13454832 protocol: TCPv6

This was indeed a connected socket prior to this, I received an HTTP request over it. 

And looking at the info for the epoll file descriptor I can see it's no longer being polled:

$ cat /proc/393026/fdinfo/5
pos:    0
flags:  02000002
mnt_id: 15
ino:    12694
tfd:       12 events:     2019 data:                c  pos:0 ino:cc6c14 sdev:8
tfd:       13 events:     2019 data:                d  pos:0 ino:cc6c15 sdev:8
tfd:       15 events:     2019 data:                f  pos:0 ino:cc6c1a sdev:8
tfd:        4 events:     2019 data:                4  pos:0 ino:cc6c0e sdev:8
tfd:        8 events:       19 data:                8  pos:0 ino:cc6c13 sdev:d
tfd:       10 events:       19 data:                a  pos:0 ino:3196 sdev:e
tfd:       14 events:     2019 data:                e  pos:0 ino:cc6c1c sdev:8

Of course realizing that the status is EBADF it seems pretty obvious that the TCP connection has gone bad, however the documentation seems to suggest that UV_DISCONNECT will try to let you know about this sort of thing, seems like a good update to have it map EBADF into UV_DISCONNECT. 

In general status < 0 is a murky place to be since it isn't clear if the socket is still good. Should I:

1) always assume the socket is now bad
2) understand that the socket might be bad and try to run some other call on the socket to check (getremoteaddr?)

If the right answer is 2 then maybe that would be a great thing to do inside of libuv?

**Comment by bnoordhuis** [comment]
UV_DISCONNECT means the other end hung up (in epoll terms: EPOLLRDHUP) whereas UV_EBADF stands in for POLLERR a.k.a. "generic error". Libuv doesn't know more than you do at that point.

**Comment by jensbjorgensen** [comment]
thanks, understood. FWIW I'm pretty sure here the other end *did* hang up (or RST, or something). I didn't close the file handle (which is kinda the problem it just sits there). Note in the lsof output that it doesn't show any local or remote address info. It just says it's a TCPv6 socket. For quite some time I was convinced that I had created this socket and never connected it. But I've added lots of diagnostics and I know this was a TCP socket that I accept()ed and in fact I received a request over it. 

In any case, I did locate the place in the source of interest:

`  if ((events & POLLERR) && !(events & UV__POLLPRI)) {
    uv__io_stop(loop, w, POLLIN | POLLOUT | UV__POLLRDHUP | UV__POLLPRI);
    uv__handle_stop(handle);
    handle->poll_cb(handle, UV_EBADF, 0);
    return;
  }
`
So I totally get it that the libuv logic can't really know what happened with the file descriptor. However what it does know is: "libuv has stopped polling for this file descriptor, you will never again get an event for it, so now it's your problem to figure out what to do about that." The documentation simply says only:

> If an error happens while polling, status will be < 0 and corresponds with one of the UV_E* error codes (see [Error handling](https://docs.libuv.org/en/v1.x/errors.html#errors)).

Would've saved me many hours to have known that (yeah, I should've read the source at lot sooner in the process). Perhaps you'd accept a documentation PR to indicate this important fact?

**Comment by jensbjorgensen** [comment]
Also: thanks very much for this excellent open source library :-)

**Comment by jensbjorgensen** [comment]
Documentation PR? https://github.com/libuv/libuv/pull/3797

**Comment by jensbjorgensen** [comment]
While I have your attention also maybe you could look at my other PR again: Linux abstract namespace socket for uv_pipe_connect, uv_pipe_bind

I went over the code again, rebased against v1.x, and added another test plus the corresponding connect function.

**Comment by bnoordhuis** [comment]
Documented in 821b0ba.
