### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by wxx422** [libuv/libuv#380]
I downloaded the zip (ChangeLog shows 2015.05.07, Version 1.5.0 (Stable) ) to my virtual machine (VMware WorkStation, 10.0.2.46408), CentOS 6.6, gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) . when I "make", there are many warnings. Ignore the warnings, "make check" finally shows as below:

```
[%  60|+ 157|-   0|T   0|S   0]: getaddrinfo_fail
`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
Assertion failed in test/test-getaddrinfo.c on line 43: status < 0

[%  61|+ 157|-   1|T   0|S   0]: getaddrinfo_fail_sync
`getaddrinfo_fail_sync` failed: exit code 134
Output from process `getaddrinfo_fail_sync`:
Assertion failed in test/test-getaddrinfo.c on line 108: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy", NULL, NULL)

[%  76|+ 196|-   2|T   0|S   0]: spawn_setuid_setgid
`spawn_setuid_setgid` skipped
Output from process `spawn_setuid_setgid`:
user 'nobody' cannot access the test runner

[% 100|+ 255|-   2|T   0|S   1]: Done.
FAIL: test/run-tests

1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues

make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory `/root/Desktop/Linux_c/libuv-1.x'
make: *** [check-am] Error 2
```

**Comment by bnoordhuis** [comment]
Thanks for the report.  The failures look benign to me.

I speculate that the getaddrinfo tests fail because your local DNS resolver returns _something_ even when there is no record; you can probably verify that with `nslookup` or `dig`.  The spawn_setuid_setgid failure is self-explanatory.

I'll close this but let me know if you think there is something worth investigating.

**Comment by wxx422** [comment]
Thank you for your answer.

**Comment by luckyjoou** [comment]
I am sorry that I have the same trouble, but I do not know how to do with `nslookup` or `dig` @@

**Comment by bnoordhuis** [comment]
@luckyjoou `dig xyzzy.xyzzy.xyzzy` should print `status: NXDOMAIN` (among other things.)

**Comment by luckyjoou** [comment]
Thanks a lot!
