### ISSUE TITLE
Expose FindFirstFileEx/FindNextFile/CloseFind and opendir/readdir/closedir

### ISSUE THREAD

**Issue by domenic** [libuv/libuv#381]
It would be nice to experiment in io.js with streaming directory listing. As far as I can tell this is supported on both Windows and POSIX in fairly similar ways, and so shouldn't be too much trouble to wrap up into agnostic wrappers.

**Comment by Fishrock123** [comment]
dupe of https://github.com/libuv/libuv/pull/175

**Comment by domenic** [comment]
Damn, I checked all the open issues, but not the PRs :P
