### ISSUE TITLE
mulitple async calls to uv_fs_write() corrupts file

### ISSUE THREAD

**Issue by pinheadmz** [libuv/libuv#3820]
* **Version**: 1.19.2
* **Platform**: Ubuntu 20 and OSX 12 

I have a program that saves a small file to disk repeatedly, automatically over time. Especially in testing, these writes can be in very quick succession. I'm trying out libuv to write the file asynchronously but I think the multiple writes are corrupting the file. I'm not sure if this a bug or just expected behavior (bad practice to use libuv this way?)

All the code for opening writing and closing the file are in this file: https://github.com/pinheadmz/hnsd/blob/c160627ee45d41772df00bb10903ccfe03b57a73/src/store.c

This code won't fail, but the file the program produces is invalid and upon deep inspection, appears to indeed be a messy combination of multiple write cycles.

By making write->close synchronous in [this commit](https://github.com/pinheadmz/hnsd/commit/4ce299bcce7b691b414277313afe9d9dad867161) everything works fine.

I guess my expectation was that libuv would queue up the writes for the same file in such a way that they wouldn't overlap but execute atomically in sequence?

**Comment by vtjnash** [comment]
You seem to start all of the writes from offset 0, writing and overwriting parts of the file essentially at random from all of the open file handles to the same file, depending on the order in which the writes are serviced
https://github.com/pinheadmz/hnsd/blob/c160627ee45d41772df00bb10903ccfe03b57a73/src/store.c#L190

If you need to atomically replace a file, you need to use the O_EXCL flag when opening the new one, then rename it over the old one when finished writing

**Comment by vtjnash** [comment]
Ah, I see that now. It was not clear in the first description. Where are the multiple writes coming from then, since I seem to only see one open and one write call for it

**Comment by pinheadmz** [comment]
The multiple writes come from here:

https://github.com/pinheadmz/hnsd/blob/fd4650b8bf55172ffb776f20674271e89cbcb18a/src/chain.c#L747
 
 and then here:

https://github.com/pinheadmz/hnsd/blob/fd4650b8bf55172ffb776f20674271e89cbcb18a/src/chain.c#L292


we are parsing a blockchain and every 2000 blocks we save an updated state to disk. During boot there could be 100000 blocks parsed in a minute so a lot of these writes get called. Once that phase is over, we only write once every two weeks or so.

**Comment by vtjnash** [comment]
I don't follow. Are you repeatedly reopening the same temp file and overwriting starting at offset 0, or opening a new temp file each time? It sounds a bit like you have forgotten to synchronize your writers so that a new temp file is not started until the last one is flushed to disk.

**Comment by bnoordhuis** [comment]
> I guess my expectation was that libuv would queue up the writes for the same file in such a way that they wouldn't overlap but execute atomically in sequence?

Libuv doesn't do that because it doesn't (and can't) know if the writes go to the same file. Two different file descriptors can refer to the same file.

(In other words, you're responsible for serializing writes to the same file.)

**Comment by pinheadmz** [comment]
> (In other words, you're responsible for serializing writes to the same file.)

Got it thanks, ill use a mutex or sync writes instead
