### ISSUE TITLE
linux: update kernel+glibc requirements?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3822]
Our documentation currently states this:
https://github.com/libuv/libuv/blob/64669fdd8de8fce478e6ce1f7c954905f682c75b/SUPPORTED_PLATFORMS.md#L5
IOW, what RHEL 6 ships - but that distro has been EOL for two years now.

I want to suggest updating that to kernel 3.10 and glibc 2.17 respectively, what RHEL 7 ships (supported until June 2024.)

There's no pressing need to update at this time but:

1. it would let us delete a (guesstimated) few hundred lines of conditional code, and

2. it seems unlikely anyone is still running a 2.6.32 kernel in this day and age. It was released almost 13 years ago.

<hr>

On a related note, I also suggest updating our freebsd baseline from 10 to 12: https://www.freebsd.org/releases/

**Comment by santigimeno** [comment]
I'm ok with both suggestions

**Comment by cjihrig** [comment]
SGTM

**Comment by richardlau** [comment]
> IOW, what RHEL 6 ships - but that distro has been EOL for two years now.
> I want to suggest updating that to kernel 3.10 and glibc 2.17 respectively, what RHEL 7 ships (supported until June 2024.)

+1. 

FYI For downstream, no supported version of Node.js supports RHEL 6. Node.js 18 moved to RHEL 8. Node.js 16 remains on RHEL 7 until it goes End-of-Life next September, although I forget how far behind Node.js 16 is wrt libuv and whether it would be feasible/desired to update libuv there.

> On a related note, I also suggest updating our freebsd baseline from 10 to 12: https://www.freebsd.org/releases/

For the [Jenkins CI](https://ci.nodejs.org/job/libuv-test-commit-freebsd/), we currently only have FreeBSD 12: https://ci.nodejs.org/label/freebsd/
Digital Ocean actually dropped the ability to create new FreeBSD droplets earlier this year (you'd now have to supply your own custom image).

**Comment by bnoordhuis** [comment]
#3830
