### ISSUE TITLE
New release, please!

### ISSUE THREAD

**Issue by dbkaplun** [libuv/libuv#383]

**Comment by dbkaplun** [comment]
There are very important bugfixes on `master` that should be released *immediately* as the bugs they fix are *severe*.

**Comment by saghul** [comment]
The next libuv release will happen when it's ready, and right now its not.

There are important bugfixes in the v1.x branch, not master. They are important, yes, but not urgent. There is a difference.

You can of course disagree.

**Comment by dbkaplun** [comment]
I don't see what's so difficult about creating a new point release in the interim.

I understand it may not seem important to some members of the libuv team, but please understand that the thousand or so users of [slap-editor/slap](https://github.com/slap-editor/slap) are forced to run Node v0.10 (!) because of this unfixed bug.

**Comment by dbkaplun** [comment]
To reiterate, NodeJS 0.11+ is utterly broken on OSX as the event loop gets blocked. Please release.

**Comment by cjihrig** [comment]
See #384
