### ISSUE TITLE
Drop kfreebsd support?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3833]
kfreebsd support was added in 2016 in #960 but:

- kfreebsd seems dead

- libuv's support likely bitrotted over time

I want to suggest removing it unless it's actually still in use.

cc @h0tw1r3 as the author of the linked PR.

**Comment by h0tw1r3** [comment]
I can confirm kfreebsd is dead.

**Comment by saghul** [comment]
:axe:

**Comment by bnoordhuis** [comment]
#3835
