### ISSUE TITLE
provide posix semantics for uv_fs_unlink on Windows

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#3839]
Possibly due to C++20, there are now documented flags that force posix-compliant behavior on Windows when deleting a file. It is not documented when this was added to the Windows kernel. (It is also possible the behavior of DeleteFile and/or DeleteFileEx has changed according to random user comments on the internet, although the documentation for those functions still claim not to provide posix-behavior here.) But while browsing the documentation site, I discovered it is now possible to request posix-compatible deletion semantics via:

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/ns-ntddk-_file_disposition_information_ex

We can infer some of the dates where this is first available from the comments on the official C++20 STL implementation (apache-2 license), such as https://github.com/microsoft/STL/pull/1559

1809 | Redstone 5 | October 2018 Update (added FILE_DISPOSITION_FLAG_IGNORE_READONLY_ATTRIBUTE)
1607 | Redstone | Anniversary Update (added FILE_DISPOSITION_FLAG_POSIX_SEMANTICS)

It is then possible to detect the error if these functions/types are not available at runtime for the filesystem or operating system, and fallback to the current code.

**Comment by bnoordhuis** [comment]
Interesting find. My Cliffs notes:

- they're set on the HANDLE with `SetFileInformationByHandle(FileDispositionInfoEx)`, like fcntl/ioctl
- GetLastError is ERROR_NOT_SUPPORTED when it's, er, not supported
- FileDispositionInfoEx == 21
- FILE_DISPOSITION_INFO_EX is a single DWORD
- FILE_DISPOSITION_FLAG_POSIX_SEMANTICS == 2
- FILE_DISPOSITION_FLAG_IGNORE_READONLY_ATTRIBUTE == 16

**Comment by vtjnash** [comment]
Possibly also a similar change for rename using SetFileInformationByHandle with FileRenameInfoEx and FILE_RENAME_FLAG_POSIX_SEMANTICS, though curiously the microsoft employees rejected using it to fix their stl bugs listed here https://github.com/microsoft/STL/issues/2053 for being less-posix-compliant than our current implementation

**Comment by IanButterworth** [comment]
Just adding @vtjnash's helpful comment from [here](https://github.com/JuliaLang/julia/issues/34700#issuecomment-1900747069)

> The Rust implementation of that change was here https://github.com/rust-lang/rust/commit/5ab67bff1e2230217ce133165605f8dc0d588178#diff-e8df55f38a9a224cf1cfd40e6c535535aa66e8073cc8d9b959308659ba1de1f9R572-R577
