### ISSUE TITLE
Prepare 1.6.0 release

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#384]
I landed all PRs which I had "scheduled" for this release. I did fuckup the Windows build after the allocator commit, but I just fixed it and we're now good.

CI run: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/103/

Build is as green / red as usual, so unless someone speaks up I plan to make the release tomorrow night.

/cc @bnoordhuis, @piscisaureus

**Comment by Fishrock123** [comment]
\o/

**Comment by saghul** [comment]
Ok, there have been no objections, so I'm moving forward with this.
