### ISSUE TITLE
Flaky build-cross-qemu-alpha buildbot

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3843]
```
not ok 84 - fs_partial_read
# timeout
# Output from process `fs_partial_read`: (no output)
not ok 85 - fs_partial_write
# timeout
# Output from process `fs_partial_write`: (no output)
```
It's always the same two tests. Seems to happen frequently as of today (yesterday?), I've been able to repeat it three times in a row.

The .deb from http://archive.ubuntu.com/ubuntu/pool/universe/q/qemu/ hasn't changed recently. There's also no v1.x commit that's an obvious culprit.

**Comment by richardlau** [comment]
One difference between, e.g. 
- https://github.com/libuv/libuv/actions/runs/3578637576/jobs/6019001850 (passed)
- https://github.com/libuv/libuv/actions/runs/3591703370/jobs/6050221769 (failed)

is that the runs are now on the Ubuntu 22.04 runner whereas they were previously running on Ubuntu 20.04. That's part of a rolling update by GitHub: https://github.com/actions/runner-images/issues/6399
