### ISSUE TITLE
udp_multicast_join and udp_multicast_join6 test cases times out.

### ISSUE THREAD

**Issue by xiaoge1001** [libuv/libuv#3849]
![image](https://user-images.githubusercontent.com/103323735/206337161-239da5fc-dafc-4f99-8083-8576fe46f417.png)
What's the reason for this?

**Comment by vtjnash** [comment]
Usually a firewall or misconfigured network on your machine

**Comment by xiaoge1001** [comment]
thanks.
How am I supposed to check what the problem is?

**Comment by xiaoge1001** [comment]
I find that the firewall is running using command "firewall-cmd --state".

**Comment by xiaoge1001** [comment]
I found that Fedora skipped these test cases.

https://src.fedoraproject.org/rpms/libuv/blob/rawhide/f/0001-Fedora-Skip-tests-that-can-t-run-in-Koji.patch

**Comment by xiaoge1001** [comment]
OpenSUSE also not execute these test cases.

https://build.opensuse.org/package/view_file/openSUSE:Factory/libuv/fix_tests.patch?expand=1

**Comment by xiaoge1001** [comment]
After the firewalld.service is stopped, the test case is executed successfully.
