### ISSUE TITLE
error running "make check"

### ISSUE THREAD

**Issue by xiaopangju** [libuv/libuv#3854]
* **Version**: the latest one
* **Platform**: Linux xiaopangju-K84LY 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* I use the autotools to install libuv, but it reported an error running "make check" command.
* outputs are here:https://pastebin.com/p34NwsEz
* Can anyone help with me?

**Comment by santigimeno** [comment]
Can you run the test using strace and paste the output somewhere:
```
$ strace -f test/run-tests tcp_connect_timeout tcp_connect_timeout
```

**Comment by santigimeno** [comment]
Also, if you could modify https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-connect-timeout.c#L42 to be:
```
ASSERT_EQ(status, UV_ECANCELED);
```

**Comment by xiaopangju** [comment]
> strace -f test/run-tests tcp_connect_timeout tcp_connect_timeout

https://pastebin.com/6KNKFZ15

**Comment by xiaopangju** [comment]
> Also, if you could modify https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-connect-timeout.c#L42 to be:
> 
> ```
> ASSERT_EQ(status, UV_ECANCELED);
> ```

You mean I need to edit this line on github? Or on my local computer?

**Comment by wxkj123** [comment]
> > Also, if you could modify https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-connect-timeout.c#L42 to be:
> > ```
> > ASSERT_EQ(status, UV_ECANCELED);
> > ```
> 
> You mean I need to edit this line on github? Or on my local computer?

Of course locally modify and compile.

**Comment by xiaopangju** [comment]
> Also, if you could modify https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-connect-timeout.c#L42 to be:
> 
> ```
> ASSERT_EQ(status, UV_ECANCELED);
> ```

I edited it. but it still report errors.
https://pastebin.com/hyMLiTTr

**Comment by santigimeno** [comment]
It seems the connection is successful, which shouldn't. Maybe something in your local network?
```
connect(10, {sa_family=AF_INET, sin_port=htons(9999), sin_addr=inet_addr("8.8.8.8")}, 16) = -1 EINPROGRESS (操作现在正在进行)
epoll_ctl(3, EPOLL_CTL_ADD, 6, {events=EPOLLIN, data={u32=6, u64=6}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 8, {events=EPOLLIN, data={u32=8, u64=8}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 10, {events=EPOLLOUT, data={u32=10, u64=10}}) = 0
epoll_wait(3, [{events=EPOLLOUT, data={u32=10, u64=10}}], 1024, 50) = 1
getsockopt(10, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
write(2, "Assertion failed in test/test-tc"..., 87Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
```

**Comment by xiaopangju** [comment]
> It seems the connection is successful, which shouldn't. Maybe something in your local network?
> 
> ```
> connect(10, {sa_family=AF_INET, sin_port=htons(9999), sin_addr=inet_addr("8.8.8.8")}, 16) = -1 EINPROGRESS (操作现在正在进行)
> epoll_ctl(3, EPOLL_CTL_ADD, 6, {events=EPOLLIN, data={u32=6, u64=6}}) = 0
> epoll_ctl(3, EPOLL_CTL_ADD, 8, {events=EPOLLIN, data={u32=8, u64=8}}) = 0
> epoll_ctl(3, EPOLL_CTL_ADD, 10, {events=EPOLLOUT, data={u32=10, u64=10}}) = 0
> epoll_wait(3, [{events=EPOLLOUT, data={u32=10, u64=10}}], 1024, 50) = 1
> getsockopt(10, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
> write(2, "Assertion failed in test/test-tc"..., 87Assertion failed in test/test-tcp-connect-timeout.c on line 42: status == UV_ECANCELED
> ```

I have restarted my router. What do I need to do next? I am willing to cooperate.
