### ISSUE TITLE
Add support for SO_REUSEPORT to uv_tcp_t?

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#386]
Evaluate if we want to do this. It's now supported on Linux >= 3.9 and RedHat seems to have backported it.

This would add a new flag to `uv_tcp_bind`:

~~~~
...
r = uv_tcp_bind(handle, addr, UV_TCP_REUSEPORT);
...
~~~~

Note that we already take flags in `uv_tcp_bind`.

This would help create a multi-threaded server in which the Kernel does the load balancing.

References:

https://lwn.net/Articles/542629/
http://nginx.com/blog/socket-sharding-nginx-release-1-9-1/
http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

**Comment by saghul** [comment]
Well, crap. The nice-load-balancing-thingy is a Linux-ism. I'll keep this open for a bit, food for thought.

https://lists.freebsd.org/pipermail/freebsd-net/2013-July/036131.html

**Comment by bnoordhuis** [comment]
For reference, I explicitly disabled it in 3d2c820 ("linux: don't turn on SO_REUSEPORT socket option".)

**Comment by yosuke-furukawa** [comment]
I'm +1 on this.
I have already benchmarked SO_REUSEPORT and cluster using this branch : https://github.com/yosuke-furukawa/libuv/tree/feature_turn_on_reuseport

```
Simple Compare: 
SO_REUSEPORT 2113.25 req/sec
cluster 1431.47 req/sec
47% faster.
```

The detail is here. https://gist.github.com/yosuke-furukawa/e3d593db8f8963518b19

I know SO_REUSEPORT has the different behavior on BSD and linux. http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

But I want to use SO_REUSEPORT on the linux kernel >= 3.9 only.

If you can accept the behavior, I want to send a pull request.

**Comment by saghul** [comment]
I'm not sure, to be honest. The problem is that this behavior cannot be amulated on platforms which don't support it (yet?) so this would exclusively work on Linux >= 3.9 and **only** there. That's not cross-platform enough, by eny measure.

Now, it shouldn't be hard to use `uv_fileno`, extract the fd and set the option manualy, BUT we create the sockets late, which means that we currently don't have a way to get the fd *before* calling `uv_tcp_bind`.

I've started to experiment with all of this as a libuv + http_parser thingy (hopefully to be published soon) and the only way to do it currently is to create the socket manually, set SO_REUSE{ADDR,PORT}, use `uv_tcp_open` and then use the tcp handle normally.

This would be much easier if we created the sockets early, oh well! :-)

So, I myself am -0.1 at the moment. I hope that experiment I'm working on might give me some more thoughts on what to do here.

PS: In my experiment I'm using multiple threads not processes, FWIW.

**Comment by yosuke-furukawa** [comment]
Yes. That is not cross-platform enough. I guess it is hard to explain the specification for libuv. And that is hard to emulate.

I don't need to turn on `SO_REUSEPORT` by default. It is no problem to add a flag like `UV_TCP_REUSEPORT`. :-) 

> So, I myself am -0.1 at the moment. I hope that the experiment I'm working on might give me some more thoughts on what to do here.

Yes, I agree. We need more experiments on this.

**Comment by vavrusa** [comment]
I'd like to use this as well (+on UDP as well). I understand the motivation behind 3d2c820 so I guess it's best if there's a `UV_{TCP|UDP}_REUSEPORT` flag (that is ignored if the platform doesn't support it).
It's somewhat *meh* going the `uv_{udp|tcp}_open()` way.

**Comment by saghul** [comment]
After thinking about this some more for the past few days, I came to the conclusion that it's not a good idea to provide an API for this at the moment, since the platform differences are irreconciliable. It's not the fact that some platforms have SO_REUSEPORT and other don't, it's the fact that even if it's called the same it can mean different things.

So, I think the right thing to do here is to make it easy to set if from the outside. In order to achieve this we need to create the sockets early, because right now they are created too late (when binding). This was planned for a while: https://github.com/libuv/leps/pull/5, so I started implementing it here: https://github.com/libuv/libuv/pull/400 (look at that beautiful round number!)

Usage (pseudocode-ish) example:
~~~~
uv_tcp_init_ex(loop, handle, AF_INET);
uv_fileno(handle, &fd);
setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, &on, sizeof(on));
uv_tcp_bind(...)
/* profit! */
~~~~

**Comment by yosuke-furukawa** [comment]
+1
In NodeConf, I talked about `SO_REUSEPORT` with libuv contributors.
SO_REUSEPORT is really confusing feature for cross platform environment. 
`libuv` does not support the `SO_REUSEPORT`. Sounds reasonable.

And creating sockets earlier is good idea. 

> (look at that beautiful round number!)

cool!!

**Comment by vavrusa** [comment]
That would work for me as well.

**Comment by saghul** [comment]
I'm going to close this then, since we seem to ha A Plan :-) Let's continue over at #400.
