### ISSUE TITLE
[Makefile:5628: check-TESTS] Error 1

### ISSUE THREAD

**Issue by ellenkampguus** [libuv/libuv#3860]
* **Version**: 
* **Platform**: 

ok 420 - we_get_signals_mixed
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5628: check-TESTS] Error 1
make[1]: Leaving directory '/home/guus/git/libuv'
make: *** [Makefile:5894: check-am] Error 2

**Comment by bnoordhuis** [comment]
Can you include the output from the failing tests? Look for "not ok".
