### ISSUE TITLE
libuv uses a fd per watched file on OS X

### ISSUE THREAD

**Issue by cgyarvin** [libuv/libuv#387]
File watching without using an fd per watched file is possible on many back ends, including OS X from 10.7 up with kFSEventStreamCreateFlagFileEvents.  libuv on OS X, all versions, still uses kqueue to watch for file modifications.

The use case for this feature is anything that wants to watch an arbitrarily large file tree - eg, a dropbox style sync app.  The problem is exacerbated by the ridiculously small file tables that OS X ships with, but Apple doesn't take github issues ;-)

**Comment by bnoordhuis** [comment]
For cross-reference: https://groups.google.com/forum/#!topic/libuv/IlZlhWilF5E

**Comment by vtjnash** [comment]
#1572 reversed some ifdef logic and left out the primary change, so it didn't actually end up doing it's intended / stated purpose
