### ISSUE TITLE
[feature request] Support of Reliable User Datagram Protocol (RUDP) 

### ISSUE THREAD

**Issue by flashultra** [libuv/libuv#3881]
UDP is very good for  highly time-sensitive  data, but sometimes higher reliability is required. 
So RUDP is the solution where UDP is required with the data reliability and confirmation.
I think ,if RUDP is part of Libuv, it will bring new possibilities for NodeJS and other network libraries. 
RFC : https://www.ietf.org/proceedings/44/I-D/draft-ietf-sigtran-reliable-udp-00.txt

**Comment by vtjnash** [comment]
RUDP was drafted, but never standardized or implemented. Instead, TCP is the standard way to do this.
