### ISSUE TITLE
`tty` test - intermittent failures on musl-based Linux systems

### ISSUE THREAD

**Issue by awilfox** [libuv/libuv#3894]
* **Version**: 1.44.1, 1.44.2
* **Platform**: `Linux gwyn.foxkit.us 5.15.44-mc2-easy #1 SMP Sat Jul 2 18:33:37 CDT 2022 ppc64 GNU/Linux`
  Also occurs on aarch64, ppc, x86_64.

We are seeing this problem while auto-building packages for the Adélie Linux distribution, using musl libc.  Intermittently, libuv fails its `tty` test because `height` is below 10:

```
...
ok 354 - tmpdir
not ok 355 - tty
# exit code 6
# Output from process `tty`:
# width=53 height=6
# Assertion failed in test/test-tty.c on line 124: height > 10
ok 356 - tty_file
...
```

I am not sure how to debug this properly, since it is an intermittent failure.  We will be happy to provide any further information needed.

**Comment by bnoordhuis** [comment]
I've opened #3895 to fix the bad assumption in the test.
