### ISSUE TITLE
openbsd: flaky condvar_5 test

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3896]
The test sporadically hits this check on the openbsd buildbot:
```
1: not ok 20 - condvar_5
1: # exit code 134
1: # Output from process `condvar_5`:
1: # Assertion failed in /Users/runner/work/libuv/libuv/test/test-condvar.c on line 262: elapsed <= 5.0 * timeout
```
I.e., `uv_cond_timedwait(100 ms)` is taking > 500 ms.

**Comment by vtjnash** [comment]
Seems like that constraint just needs to be relaxed. 500 ms is a perfectly reasonable result for a 1ms timeout request.

**Comment by bnoordhuis** [comment]
100 ms but yeah... that was sarcasm, right? :-)

**Comment by vtjnash** [comment]
No, that is serious. That would be well within tolerances expected for standard kernels

**Comment by bnoordhuis** [comment]
Your tolerance for kernel tolerances is clearly higher than mine! I'll open a PR to increase the limit.

**Comment by bnoordhuis** [comment]
#3899 - I decided to remove the check altogether.
