### ISSUE TITLE
`fs_rename` can't rename only casing of files on case-insensitive systems

### ISSUE THREAD

**Issue by martin-braun** [libuv/libuv#3902]
`fs_rename` will error when you try to rename `File.txt` to `file.txt` on MacOS, which has a case-insensitive file system by default. I assume this is, because it checks if the file exists, before attempting to rename it. If there is a file `file.txt`, also `File.txt` will return true for the check, since the file system is case-insensitive.

* **Platform**: Darwin Martins-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
* 
Ref: https://github.com/nvim-tree/nvim-tree.lua/issues/914

**Comment by bnoordhuis** [comment]
`uv_fs_rename()` straight up calls rename(2) so whatever error you're seeing comes directly from the operating system, not from any extra leg work that libuv is doing.

That said, I can't reproduce what you're describing. It simply renames the file. I run an older version of macOS, though.

**Comment by vtjnash** [comment]
I can't reproduce this in any form either. And I am on the absolute latest release (13.2–22D49) with standard APFS settings

**Comment by martin-braun** [comment]
Ok this is weird. It's a problem in Neovims nvim-tree and it's said that renaming a file or directory is done using `uv.fs_rename()`. Maybe `rename` is structured this way and Finder is circumventing this issue? Since `mv` also seem to not have this problem it probably also circumvents the edge case?
