### ISSUE TITLE
PIPE connection success under Windows uv_read_start failure

### ISSUE THREAD

**Issue by bitxx** [libuv/libuv#3914]
Version: v1.44.2: 2022.07.12, Version 1.44.2 (Stable)
Platform: Windows10 VS2022-x86

Using multi-threaded concurrent mode during PIPE connection will cause the PIPE READ event setting to fail.

It is unclear if this is a design flaw and can only be fed back to the author for testing first.

The following is a minimal example under WIN32.

**uv_read_start -> error_name: ENOTCONN error: socket is not connected thread id: 25872**

```c
#include <stdio.h>
#include <uv.h>

#if defined(_WIN32)
#   pragma comment(lib, "ws2_32.lib")
#   pragma comment(lib, "iphlpapi.lib")
#   pragma comment(lib, "userenv.lib")
#endif

# define TEST_PIPENAME "\\\\?\\pipe\\uv-test"

uv_loop_t* loop[100];
uv_pipe_t clientpipe[100];
uv_pipe_t serverpipe;
uv_connect_t connect_req[100];

void alloc_buffer(uv_handle_t* handle, size_t suggested_size, uv_buf_t* buf)
{
    buf->base = (char*)malloc(suggested_size);
    buf->len = suggested_size;
}

void child_on_new_connection(uv_stream_t* q, ssize_t nread, const uv_buf_t* buf)
{
    if (nread < 0) {
        uv_close((uv_handle_t*)q, NULL);
        return;
    }
}

static void connect_cb(uv_connect_t* req, int status)
{
    int r;
    int i = *(int*)uv_req_get_data((uv_req_t*)req);
    r = uv_read_start((uv_stream_t*)&clientpipe[i], alloc_buffer, child_on_new_connection);

    if (r != 0) {
        printf("error_name: %s error: %s thread id: %u\n", uv_err_name(r), uv_strerror(r), GetCurrentThreadId());
    }
}

void new_thread_handle_connection(void* arg)
{
    int i = *(int*)arg;
    int r;
    loop[i] = (uv_loop_t*)malloc(sizeof(uv_loop_t));
    r = uv_loop_init(loop[i]);
    r = uv_pipe_init(loop[i], &clientpipe[i], 1);

    uv_req_set_data((uv_req_t*)&connect_req[i], arg);

    uv_pipe_connect(&connect_req[i], &clientpipe[i], TEST_PIPENAME, connect_cb);
  
    uv_run(loop[i], UV_RUN_DEFAULT);
}
static void connection_cb(uv_stream_t* server, int status)
{
    int r;
    uv_pipe_t *conn = (uv_pipe_t*)malloc(sizeof(uv_pipe_t));
    r = uv_pipe_init(server->loop, conn, 1);
    r = uv_accept(server, (uv_stream_t*)conn);

    if (r != 0) {
        printf("%s\n", uv_strerror(status));
    }
}

int main()
{
    int r;
    loop[0] = (uv_loop_t*)malloc(sizeof(uv_loop_t));
    uv_loop_init(loop[0]);
    r = uv_pipe_init(loop[0], &serverpipe, 0);
    r = uv_pipe_bind(&serverpipe, TEST_PIPENAME);
    r = uv_listen((uv_stream_t*)&serverpipe, 128, connection_cb);

    for (int i = 1; i < 32; ++i)
    {
        int* val = (int*)malloc(sizeof(int));
        *val = i;
        r = _beginthread(new_thread_handle_connection, 0, (void*)val);
    }
    uv_run(loop[0], UV_RUN_DEFAULT);
    return 0;
}
```

**Comment by vtjnash** [comment]
libuv is not threadsafe

**Comment by bitxx** [comment]
> libuv is not threadsafe

I'm just simulating a process through threads, I know loop is not thread safe, but I'm using PIPE to simulate process communication, then I'll use uv_wirte2 to cast events between threads, for example uv_tcp_t https://github.com/libuv/libuv/blob/v1.x/ docs/code/multi-echo-server/main.c

**Comment by bitxx** [comment]
> libuv is not threadsafe

**I believe this is a bug in libuv_pipe, I tried to modify the source code for debugging, if I do this then all the threads on PIPE they will all connect successfully**

···c
static HANDLE open_named_pipe(const WCHAR* name, DWORD* duplex_flags) {
  HANDLE pipeHandle;

  /*
   * Assume that we have a duplex pipe first, so attempt to
   * connect with GENERIC_READ | GENERIC_WRITE.
   */
  while (1)
  {
      pipeHandle = CreateFileW(name,
                               GENERIC_READ | GENERIC_WRITE,
                               0,
                               NULL,
                               OPEN_EXISTING,
                               FILE_FLAG_OVERLAPPED,
                               NULL);
      if (pipeHandle != INVALID_HANDLE_VALUE) {
          *duplex_flags = UV_HANDLE_READABLE | UV_HANDLE_WRITABLE;
          return pipeHandle;
      }

      WaitNamedPipeW(name, 2000);
  }


  /*
   * If the pipe is not duplex CreateFileW fails with
   * ERROR_ACCESS_DENIED.  In that case try to connect
   * as a read-only or write-only.
   */
  if (GetLastError() == ERROR_ACCESS_DENIED) {
    pipeHandle = CreateFileW(name,
                             GENERIC_READ | FILE_WRITE_ATTRIBUTES,
                             0,
                             NULL,
                             OPEN_EXISTING,
                             FILE_FLAG_OVERLAPPED,
                             NULL);

    if (pipeHandle != INVALID_HANDLE_VALUE) {
      *duplex_flags = UV_HANDLE_READABLE;
      return pipeHandle;
    }
  }

  if (GetLastError() == ERROR_ACCESS_DENIED) {
    pipeHandle = CreateFileW(name,
                             GENERIC_WRITE | FILE_READ_ATTRIBUTES,
                             0,
                             NULL,
                             OPEN_EXISTING,
                             FILE_FLAG_OVERLAPPED,
                             NULL);

    if (pipeHandle != INVALID_HANDLE_VALUE) {
      *duplex_flags = UV_HANDLE_WRITABLE;
      return pipeHandle;
    }
  }
  return INVALID_HANDLE_VALUE;
}
```

**Comment by bitxx** [comment]
Therefore, in systems above Windows 10, there are different specifications for PIPE names.

Windows 10, version 1709:  Pipes are only supported within an app-container; ie, from one UWP process to another UWP process that's part of the same app. Also, named pipes must use the syntax \\.\pipe\LOCAL\ for the pipe name.

**Comment by bitxx** [comment]
> libuv is not threadsafe
WaitNamedPipe has a requirement for the pipe name, which is different in different systems.

So the reason for the error and the failure of the connection part is from

```c
  /* We're here because CreateFile on a pipe returned ERROR_PIPE_BUSY. We wait
   * up to 30 seconds for the pipe to become available with WaitNamedPipe. */
  while (WaitNamedPipeW(handle->name, 30000)) {
    /* The pipe is now available, try to connect. */
    pipeHandle = open_named_pipe(handle->name, &duplex_flags);
    if (pipeHandle != INVALID_HANDLE_VALUE)
      break;

    SwitchToThread();
  }
```

See: https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-waitnamedpipew for details

**Comment by vtjnash** [comment]
Ah, that was not clear. Can you say more about what the goal is, where the errors are reported, and what you've tried that did work?

**Comment by bitxx** [comment]
> Ah, that was not clear. Can you say more about what the goal is, where the errors are reported, and what you've tried that did work?

```
Windows 10, version 1709:  Pipes are only supported within an app-container; ie, from one UWP process to another UWP process that's part of the same app. Also, named pipes must use the syntax \\.\pipe\LOCAL\ for the pipe name.
```

Due to Windows 10, version 1709+ or higher, the PIPE name needs to start with \\. \ instead of \\? \ so the official uv documentation does not specifically state this, which is why, in some cases, connections fail in multi-threaded applications.

UV_PIPE is multi-threaded and there is no problem to use multi-threaded to simulate multiple processes.

**Comment by vtjnash** [comment]
The name has always had to be of the form `\\.\pipe` (the libuv guide in docs/src/guide/processes.rst is not entirely official, has never been fully reviewed by libuv devs, and incorrectly claims it should be a `?`). Is that doc error what you are meaning to report is wrong?

**Comment by bitxx** [comment]
> The name has always had to be of the form `\\.\pipe` (the libuv guide in docs/src/guide/processes.rst is not entirely official, has never been fully reviewed by libuv devs, and incorrectly claims it should be a `?`). Is that doc error what you are meaning to report is wrong?

Yes, the documentation doesn't spell out the difference between windows and other platforms, maybe \\\\? There is no problem in linux, but there is a problem using it under windows. The specific Microsoft documentation is also written very clearly.
