### ISSUE TITLE
doc: inconsistent use of single vs. double backticks

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#3928]
I don't know what the preferred sphinx syntax is but mixing styles gives me feelings of FUD.

As an aside: sometimes we don't use backticks at all. I spotted at least one plain UV_EINVAL in docs/src/misc.rst.

**Comment by jazelly** [comment]
Double backticks (code snippet) and single backtick (hyperlink) are different in reStructuredText, which is unlike markdown. See [this doc](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) and [this answer](https://stackoverflow.com/a/57302493). 

>  sometimes we don't use backticks at all. I spotted at least one plain UV_EINVAL in docs/src/misc.rst.
Happy to address this, and some misusages of single backtick
