### ISSUE TITLE
benchmark-multi-accept failed in Windows

### ISSUE THREAD

**Issue by hh9527** [libuv/libuv#394]
Compiler: VS2013 Prof V12.0.21005.1 REL
OS: Windows 7 Prof with SP1 32bits
Build step: vcbuild.bat

```
C:\home\src\libuv-1.6.0\Release>run-benchmarks.exe
uv_shutdown_t: 68 bytes
uv_write_t: 92 bytes
uv_connect_t: 68 bytes
uv_udp_send_t: 68 bytes
uv_tcp_t: 168 bytes
uv_pipe_t: 320 bytes
uv_tty_t: 196 bytes
uv_prepare_t: 60 bytes
uv_check_t: 60 bytes
uv_idle_t: 60 bytes
uv_async_t: 116 bytes
uv_timer_t: 96 bytes
uv_fs_poll_t: 52 bytes
uv_fs_event_t: 140 bytes
uv_process_t: 136 bytes
uv_poll_t: 256 bytes
uv_loop_t: 256 bytes
loop_count: 2000000 ticks in 6.71s (297928/s)
loop_count: 1514515 ticks (302903 ticks/s)
ping_pongs: 4943 roundtrips/s

...

`tcp_multi_accept2` failed: exit code 3
Output from process `tcp_multi_accept2`:
Assertion failed in test\benchmark-multi-accept.c on line 126: 0 == uv_accept(ipc_pipe, (uv_stream_t*) &pc->peer_handle)

=============================================================

`tcp_multi_accept4` failed: exit code 3
Output from process `tcp_multi_accept4`:
Assertion failed in test\benchmark-multi-accept.c on line 126: 0 == uv_accept(ipc_pipe, (uv_stream_t*) &pc->peer_handle)

=============================================================

`tcp_multi_accept8` failed: exit code 3
Output from process `tcp_multi_accept8`:
Assertion failed in test\benchmark-multi-accept.c on line 126: 0 == uv_accept(ipc_pipe, (uv_stream_t*) &pc->peer_handle)

...

```

**Comment by hh9527** [comment]
Is it caused by my environment or a commen problem?

**Comment by saghul** [comment]
It's a known issue on Windows.

**Comment by hh9527** [comment]
> It's a known issue on Windows.

So, is there a plan to fix? Or is there a way to transfer uv_tcp_t between loops?

**Comment by saghul** [comment]
> So, is there a plan to fix?

There is always a plan to fix everything! Nobody knows when though :-)

> Or is there a way to transfer uv_tcp_t between loops?

Sure, you can use uv_write2 for that, but on Windows it only works across processes, not threads.

**Comment by hh9527** [comment]
Thank you for reply.

> Sure, you can use uv_write2 for that, but on Windows it only works across processes, not threads.

uv_write2 needs a pre-connected connection, should I use stdin/stdout wrapped as uv_pipe_t?

And, if I still need transfering uv_tcp_t between threads, will the following approach works?
- Create a **raw** SOCKET in background thread, bind and listen to this SOCKET
- In this thread, use poor stupid `select` and `accept` to get connection SOCKET
- Use uv_async_send and a synchronized queue to deliver the connection SOCKET to the worker thread/loops
- In the worker thread, use `uv_tcp_open` to wrap the received SOCKET, and add the loop

**Comment by saghul** [comment]
> uv_write2 needs a pre-connected connection, should I use stdin/stdout wrapped as uv_pipe_t?

You can create a new pipe for IPC when you spawn the new process with uv_spawn and use that one. See UV_CREATE_PIPE here: http://docs.libuv.org/en/v1.x/process.html?highlight=uv_spawn#uv-process-t-process-handle you can also browse through the tests for usage examples.

> And, if I still need transfering uv_tcp_t between threads, will the following approach works?
> 
>     Create a raw SOCKET in background thread, bind and listen to this SOCKET
>     In this thread, use poor stupid select and accept to get connection SOCKET
>     Use uv_async_send and a synchronized queue to deliver the connection SOCKET to the worker thread/loops
>     In the worker thread, use uv_tcp_open to wrap the received SOCKET, and add the loop

Yes, that should work. But watch out, `uv_async_send` coalesces calls: http://docs.libuv.org/en/v1.x/async.html?highlight=uv_async_send#c.uv_async_send

**Comment by hh9527** [comment]
Further more, is it possible to use `uv_listen(&tcp)` to listen, but with raw `accept(&tcp->socket, addr, addr_len)` instead of `uv_accept(&tcp, &conn)` to get the raw SOCKET? If this works, I will be much simpler that reinvent the whole uv_xxx things with raw `select`.

**Comment by saghul** [comment]
I don't think so. You'd need to put the socket back in blocking mode, and it's already associated with an IOCP.

PS: Please use the mailing list for questions, we try to keep the issue tracker mainly for issues.

**Comment by kellabyte** [comment]
Is this the same issue as #325?

**Comment by saghul** [comment]
@kellabyte I believe so. I'll leave it open just in case. The benchmarks are alas not in great shape... :-(
