### ISSUE TITLE
Regression: copyfile on macOS copies symbolic links

### ISSUE THREAD

**Issue by clason** [libuv/libuv#3940]
https://github.com/libuv/libuv/pull/3654 changes behavior on macOS: before, cloning a symbolic link copied the _target_; now it copies the link instead. This leads to test failures on Neovim (see https://github.com/neovim/neovim/pull/22833).

The culprit is here:
https://github.com/libuv/libuv/blob/28b9f1e68b399d3052b0f6b7a2fad9530f486518/src/unix/fs.c#L1256-L1257

From `man copyfile`:
> This flag is equivalent to `(COPYFILE_EXCL | COPYFILE_ACL | COPYFILE_STAT | COPYFILE_XATTR | COPYFILE_DATA | COPYFILE_NOFOLLOW_SRC)`.  
> [...]  
> **Since this flag implies `COPYFILE_NOFOLLOW_SRC`, symbolic links themselves will be cloned instead of their targets.**

Replacing the above line with 
```c
  if (req->flags & UV_FS_COPYFILE_FICLONE)
    flags |= COPYFILE_EXCL | COPYFILE_ACL | COPYFILE_STAT | COPYFILE_XATTR | COPYFILE_DATA;
```
fixes the issue; unfortunately, as there is no separate `COPYFILE_FORCE` flag, the same fix does not work for https://github.com/libuv/libuv/blob/28b9f1e68b399d3052b0f6b7a2fad9530f486518/src/unix/fs.c#L1259-L1260

**Comment by lewis6991** [comment]
One solution we've considered is to manually resolve a link when one of these flags is used:

```c
  char *src = (char *)req->path;
  if (flags & (COPYFILE_CLONE | COPYFILE_CLONE_FORCE)) {
    /* COPYFILE_CLONE_* implies COPYFILE_NOFOLLOW_SRC, so manually resolve the
     * file if it is a link. */
    if (!uv__fs_readlink(req)) {
      src = req->ptr;
    }
  }

  if (copyfile(src, req->new_path, NULL, flags))
```

**Comment by Artoria2e5** [comment]
The "replacing the above line with" probably does not work as intended: once you shamelessly dig into the bit that does the thing, you find:
https://github.com/apple-oss-distributions/copyfile/blob/ef8ca39c336c4c587b98ac8b33362409a122cb3e/copyfile.c#L1213-L1239

It is equivalent only in the sense that it falls back to the bunch of flags, which does the normal copy in `copyfile_data()`.

The reasoning for a forced nofollow is given as:

https://github.com/apple-oss-distributions/copyfile/blob/ef8ca39c336c4c587b98ac8b33362409a122cb3e/copyfile.c#L1009-L1010

(It's super confusing when the XNU itself has a copyfile system call in [bsd/vfs/vfs_syscalls.c](https://github.com/apple-oss-distributions/xnu/blob/5c2921b07a2480ab43ec66f5b9e41cb872bc554f/bsd/vfs/vfs_syscalls.c)... whatever.)

**Comment by clason** [comment]
@bnoordhuis Looks like this was not the only regression due to Apple `clonefile` having to be different just because: https://github.com/neovim/neovim/pull/22833#issuecomment-1519102944

(TL;DR: Apple `clonefile` doesn't overwrite existing files, unlike LibUV's generic implementation.)
