### ISSUE TITLE
`osx_select_many_fds` failed: exit code 6

### ISSUE THREAD

**Issue by gaollard** [libuv/libuv#3944]
[%  77|+ 222|-   1|T   0|S   0]: osx_selectgot some input
with a couple of lines
feel pretty happy
[%  77|+ 223|-   1|T   0|S   0]: osx_select_many_fds
`osx_select_many_fds` failed: exit code 6
Output from process `osx_select_many_fds`:
Assertion failed in test/test-osx-select.c on line 106: r == 0

* **Version**:  V1.9.1
* **Platform**: Darwin xiong 20.6.0 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64 x86_64

history:
  sh autogen.sh
  ./configure
  make
  make check

**Comment by bnoordhuis** [comment]
Thanks for the report bug that's not really a bug or something we can fix. The test tries to create a large number of localhost TCP listening sockets but it's running out of ephemeral ports. That's an OS issue, you may have to tweak a sysctl.

I mean, we could lower the number of TCP sockets but having a large number is really the point of the test.

**Comment by gaollard** [comment]
> Thanks for the report bug that's not really a bug or something we can fix. The test tries to create a large number of localhost TCP listening sockets but it's running out of ephemeral ports. That's an OS issue, you may have to tweak a sysctl.
> 
> I mean, we could lower the number of TCP sockets but having a large number is really the point of the test.

thanks for your reply
