### ISSUE TITLE
kqueue filter set to invalid value `EV_OOBAND`

### ISSUE THREAD

**Issue by tom-seddon** [libuv/libuv#3947]
* **Version**: 7a68f5ab4b3b7a4aada44ffa0f7addc295174c7b (but looks like it will apply to HEAD as well...)
* **Platform**: `Darwin tmbp.lan 20.6.0 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64 x86_64`

I noticed this while looking at the code, so the repro steps are reusing one of the existing tests.

Run test-oob-poll in the debugger, by launching the runner with args `poll_oob poll_oob`.

Put a breakpoint on this line:

https://github.com/libuv/libuv/blob/7a68f5ab4b3b7a4aada44ffa0f7addc295174c7b/src/unix/kqueue.c#L184

Start the program running.

When it hits the breakpoint, step through to the next `kqueue` call, and then on through the processing.

Note that for the entry with the `EV_OOBAND` "filter", its `EV_ERROR` flag is set and its data field is 22 (invalid argument). (This is as expected, as `EV_OOBAND` is a flag and not a filter. Valid filters are from the `EVFILT_` set... I assume the filter here should be `EVFILT_READ` and `EV_OOBAND` added to the flags.)

Luckily (?) this bit of code ignores errors when doing a pollpri, so I guess that's why the test passes: https://github.com/libuv/libuv/blob/7a68f5ab4b3b7a4aada44ffa0f7addc295174c7b/src/unix/poll.c#L47

But I suppose this means the poll might drop out earlier than you'd expect, which will be inefficient.

--Tom

**Comment by tom-seddon** [comment]
Hmm, ok, so `EV_OOBAND` appears not to do quite what I thought? The header implies you can do `EVFILT_READ` with `EV_OOBAND` in the flags, then check `EV_OOBAND` afterwards:

https://github.com/apple-oss-distributions/xnu/blob/rel/xnu-7195/bsd/sys/event.h#L303

But the obvious change to `kqueue.c` made poll_oob fail. I tried to figure out the xnu code via static inspection, and failed, because I'm one of those debugger people. But I did notice a reference to `EVFILT_EXCEPT`, and that does seem to work, just as is actually mentioned in the man page (which I hadn't noticed before):

```
     EVFILT_EXCEPT    Takes a descriptor as the identifier, and returns when-
                      ever one of the specified exceptional conditions has
                      occurred on the descriptor. Conditions are specified in
                      fflags.  Currently, this filter can be used to monitor
                      the arrival of out-of-band data on a socket descriptor
                      using the filter flag NOTE_OOB.
```

Patch below, made relative to 7a68f5a. Passes all libuv tests.

A PR could follow, if you lke the look of this.

--Tom

```
diff --git a/src/unix/kqueue.c b/src/unix/kqueue.c
index 857eb1d5..4ec3be50 100644
--- a/src/unix/kqueue.c
+++ b/src/unix/kqueue.c
@@ -181,7 +181,7 @@ void uv__io_poll(uv_loop_t* loop, int timeout) {
     }

    if ((w->events & UV__POLLPRI) == 0 && (w->pevents & UV__POLLPRI) != 0) {
-      EV_SET(events + nevents, w->fd, EV_OOBAND, EV_ADD, 0, 0, 0);
+      EV_SET(events + nevents, w->fd, EVFILT_EXCEPT, EV_ADD, NOTE_OOB, 0, 0);

       if (++nevents == ARRAY_SIZE(events)) {
         if (kevent(loop->backend_fd, events, nevents, NULL, 0, NULL))
@@ -335,7 +335,7 @@ void uv__io_poll(uv_loop_t* loop, int timeout) {
           revents |= UV__POLLRDHUP;
       }

-      if (ev->filter == EV_OOBAND) {
+      if (ev->filter == EVFILT_EXCEPT) {
         if (w->pevents & UV__POLLPRI) {
           revents |= UV__POLLPRI;
           w->rcount = ev->data;
```

**Comment by vtjnash** [comment]
That sounds logical to me

**Comment by juanarbol** [comment]
I can work on this. With some time

**Comment by juanarbol** [comment]
Is `POLLPRI` actually "doing nothing"? I mean, it notifies because of kevent, but it is not filtering anything.

The `EVFILT_EXCEPT` events will be ignored as written in: https://github.com/libuv/libuv/blob/7a68f5ab4b3b7a4aada44ffa0f7addc295174c7b/src/unix/poll.c#L47

Also OOB data is not being "handled/used".

_Introducing `EVFILT_EXCEPT` may cause some problems in BSD. (?)_. BSD seems to be a bit different compared w/ macOS.

Also, in macOS `EV_OOBAND` is a filter flag for `EVFILT_READ` (as mentioned by @tom-seddon)
https://github.com/apple-oss-distributions/xnu/blob/1b191cb58250d0705d8a51287127505aa4bc0789/bsd/sys/event.h#L334

I'll open a PR that may open a discussion about what libuv may need to do in case of `POLLPRI`. As `EVFILT_READ` filter is being used in `POLLIN`
