### ISSUE TITLE
uv_walk segmentation fault

### ISSUE THREAD

**Issue by cjreed121** [libuv/libuv#3962]
* **Version**: 1.43.0 (also tried build from sources on d4eb276eea7cb19a888fe97d7759d97c7092ad02)
* **Platform**: `Linux Desktop 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

Calling `uv_walk` can cause a seg-fault if you have created a poll, closed it, and freed the memory associated with the `uv_poll_t`. I would think that after I close the poll, I would be safe to free the memory. It seems to be that the poll never gets removed from the handler queue. I didn't see any specific comments in the documentation about this so I'm not sure if this is intentional behavior.

Below is a piece of code I wrote to demonstrate the seg-fault. You'll need to enter some string for it to trigger.
```c
#include <stdlib.h>
#include <stdio.h>
#include <uv.h>
#include <unistd.h>
#include <string.h>

void poll_callback(uv_poll_t* handle, int status, int events) {
    char buf[32] = {0};
    int r = read(0, buf, 32);
    printf("read returned %d with msg: %s\n", r, buf);

    uv_async_t* async = handle->data;
    uv_async_send(async);
}

void walk_callback(uv_handle_t* handle, void* arg) {
    // do something here
}

void async_callback(uv_async_t* handle) {
    uv_poll_t* poll = handle->data;
    uv_close((uv_handle_t*) poll, NULL);

    // memset so that memory is a different value as this can happen after free
    memset(poll, 0, sizeof(uv_poll_t));
    free(poll);

    // Seg-faults on next line
    uv_walk(uv_default_loop(), walk_callback, NULL);
}

int main() {
    uv_async_t* async = calloc(1, sizeof(uv_async_t));
    uv_poll_t* poll = calloc(1, sizeof(uv_poll_t));
    poll->data = async;
    async->data = poll;
    uv_poll_init(uv_default_loop(), poll, 0);
    uv_poll_start(poll, UV_READABLE, poll_callback);

    uv_async_init(uv_default_loop(), async, async_callback);

    uv_run(uv_default_loop(), UV_RUN_DEFAULT);

    free(async);
}
```

**Comment by bnoordhuis** [comment]
Not a bug and it's mentioned in the documentation: don't free the memory until the close callback. You don't provide one, you just free the memory immediately.
