### ISSUE TITLE
Windows: uv_read_start failed after uv_tcp_open

### ISSUE THREAD

**Issue by hh9527** [libuv/libuv#397]
OS: Windows 7 Pro 32bit

```c
uv_os_sock_t fd = accept(...);
uv_tcp_t conn;
assert(0 == uv_tcp_init(loop, &conn));
assert(0 == uv_tcp_open(&conn, fd));
assert(0 == uv_read_start(&conn, alloc_cb, read_cb));
/** FAILED at stream.c:76, related lines:
 if (!(handle->flags & UV_HANDLE_READABLE)) {
    return UV_ENOTCONN;
  }
**/
```

I found in passed test case `test-tcp-open.c`, the `sock` is a client socket. But in my case, the `sock` is fd from accept. This cause `uv_read_start` failed.

**Comment by saghul** [comment]
In hindsight we should have taken some flags to open. I'm afraid your usecase is not really supported on Windows, because we keep state flags.

**Comment by hh9527** [comment]
I have got a quick dirty solution to resolve this: add a new api `uv_tcp_open_stream` to replace `uv_tcp_open` in this case, and it just works.

```c
int uv_tcp_open_stream(uv_tcp_t* handle, uv_os_sock_t sock) {
  int r = uv_tcp_open(handle, sock);
  if (r == 0) {
    uv_connection_init((uv_stream_t*)handle);
    handle->flags |= UV_HANDLE_BOUND | UV_HANDLE_READABLE | UV_HANDLE_WRITABLE;
  }

  return r;
}
```

And, in unix, `uv_tcp_open_stream` is just a alias to `uv_tcp_open`.
```c
#ifdef _WIN32
# define uv_tcp_open_stream uv_tcp_open
#endif
```

This aproach have been tested in Window 7 and Ubuntu 14.04 with simple test-case.

**Comment by saghul** [comment]
Something like that, yeah. However I find the name very misleading, since it mentions a stream, but it actually takes a uv_os_sock_t.

**Comment by hh9527** [comment]
> Something like that, yeah. However I find the name very misleading, since it mentions a stream, but it actually takes a uv_os_sock_t.

I selected word `stream` because this API will import a socket as stream, not a server. But you are right, the meaning of  stream is not very clear. May you have any suggestion? `uv_tcp_open2`?

And if you could accept this aproach, I can submit a PR with test code in this week.

**Comment by saghul** [comment]
Feel free to send the PR so we discuss it there, thanks!

**Comment by saghul** [comment]
No follow-up, closing.
