### ISSUE TITLE
Race condition in libuv console causes crash (assertion failure) on Windows

### ISSUE THREAD

**Issue by sivadeilra** [libuv/libuv#3970]
* **Version**: Node.js v18.3.0 to all current versions, which I think is libuv v1.44.2 and up
* **Platform**: Windows 10, Windows 11, Windows Server 2022

I originally reported this to Node.js.   Here's the original bug report: https://github.com/nodejs/node/issues/47715

I represent a team using Node.js within Microsoft.  When running Node on machines under heavy load, we have found that some Node processes fail, due to an assertion failing within `/deps/uv/win/tty.c`.  This is the assertion that is failing (edited for brevity):

```c++
static void uv__tty_console_signal_resize(void) {
...
  uv_mutex_lock(&uv__tty_console_resize_mutex);
  assert(uv__tty_console_width != -1 && uv__tty_console_height != -1);      <-- this fails
  if (width != uv__tty_console_width || height != uv__tty_console_height) {
...
  }
}
```

I believe the root cause is that there is a race condition in `uv_console_init()`:

```c++
void uv_console_init(void) {
  if (uv_sem_init(&uv_tty_output_lock, 1))
    abort();
  uv__tty_console_handle = CreateFileW(L"CONOUT$",
                                       GENERIC_READ | GENERIC_WRITE,
                                       FILE_SHARE_WRITE,
                                       0,
                                       OPEN_EXISTING,
                                       0,
                                       0);
  if (uv__tty_console_handle != INVALID_HANDLE_VALUE) {
    CONSOLE_SCREEN_BUFFER_INFO sb_info;
    QueueUserWorkItem(uv__tty_console_resize_message_loop_thread,       <-- this starts a task in a thread pool
                      NULL,
                      WT_EXECUTELONGFUNCTION);
    uv_mutex_init(&uv__tty_console_resize_mutex);
    if (GetConsoleScreenBufferInfo(uv__tty_console_handle, &sb_info)) {
      uv__tty_console_width = sb_info.dwSize.X;
      uv__tty_console_height = sb_info.srWindow.Bottom - sb_info.srWindow.Top + 1;
    }
  }
}
```

This code starts a task in a thread pool, and then queries the console size.  If the thread pool task wakes up fast enough, then it will run the code that queries the console buffer size and attempts to resize it, before the first query of that console buffer succeeds, leading to the assertion failure.

Also, the worker thread can call `uv_mutex_lock(&uv__tty_console_resize_mutex);` before the mutex is even initialized, which would be another source of crashes.

We see this on build machines, where we spawn 140,000+ Node.js processes on machines with very large CPU counts (128 or more cores).  It is more common when running VMs than when running on bare metal (where we have rarely seen this).

We are running Node.js v18.13.0.  I have checked the sources, and this issue appears to be present in v18.13.0 and all later versions, up to and including main.

The fix should be to move the `QueueUserWorkItem` call after the `if (GetConsoleScreenBuffer(...)) { ... }` block.  That should guarantee that the mutex is properly initialized, and that the first call to `GetConsoleScreenBuffer` has occurred, before the resizing thread can win the race.

# Reproducing

It is not easy to reproduce this bug.  We see this when running Windows builds (as in, building Windows itself), where we run more than 140,000 Node.js processes.  Even then, the frequency of this bug is 1 or 2 instances per build. That's the frequency when running on builds within VMs; when running in a host OS (no VM), the repro rate is lower (only a few observed cases).

**Comment by vtjnash** [comment]
SGTM. Could you make a PR to move that `uv_mutex_init` to the top of that function?

**Comment by sivadeilra** [comment]
Also, I'm curious why those asserts are firing, at all.  Are asserts turned on or off in Node.js release builds?  The binary that we're running is the official release binary from the Node.js web site, v18.3.0, so it should be compiled in release mode, right?

**Comment by santigimeno** [comment]
> Sure, I'd be happy to. I'd like to get the fix into both "main" and the Node.js LTS branches. What's the right way to do that? 
> How do changes usually flow from libuv to Node.js?

Wait until a `libuv` release containing the fix is released. Then that will be added to the `nodejs` main line and will be going down to every LTS in due time.
