### ISSUE TITLE
Assertion hit by Node.js test

### ISSUE THREAD

**Issue by targos** [libuv/libuv#3975]
* **Version**: 1.44.2
* **Platform**: macOS 11, x64

I just found this by looking at a Node.js test run in Jenkins.
I can try to reproduce it on the test machine if needed.

```
04:42:11 not ok 3629 pummel/test-net-bytes-per-incoming-chunk-overhead
04:42:11   ---
04:42:11   duration_ms: 36582.18800
04:42:11   severity: crashed
04:42:11   exitcode: -6
04:42:11   stack: |-
04:42:11     Assertion failed: (timeout != -1), function uv__io_poll, file kqueue.c, line 257.
04:42:11   ...
```

https://github.com/nodejs/node/blob/8b66dc6ea979eca31e020c9385756c7be1be3e52/deps/uv/src/unix/kqueue.c#L257

Refs: https://ci.nodejs.org/job/node-test-commit-osx/51946/nodes=osx11-x64/

**Comment by bnoordhuis** [comment]
See nodejs/node#47241 - tl;dr known issue, already fixed. Not released yet but see #3887.
