### ISSUE TITLE
Docs website seems to be out-of-sync with repo

### ISSUE THREAD

**Issue by squeek502** [libuv/libuv#4006]
The docs don't seem to be in sync with what's in the repo. For example:

https://docs.libuv.org/en/v1.x/misc.html

does not contain `uv_clock_gettime` but the repository does:

https://github.com/libuv/libuv/blob/a4649f5078134a4ef7fa355c21eeca9f2d5db9b0/docs/src/misc.rst?plain=1#L624-L635

**Comment by santigimeno** [comment]
Yes, probably I missed that step on the release process. I'll look at it later

**Comment by vtjnash** [comment]
It looks like the first failing build was https://readthedocs.org/projects/libuv/builds/19207402/ (#3882), which was attempt to switch from deprecated options to match the documentation here: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python

**Comment by vtjnash** [comment]
Oh, I see later it now is failing with build.os is missing https://readthedocs.org/projects/libuv/builds/20755139/. It must exist now and contain the string "ubuntu-22.04"

**Comment by bnoordhuis** [comment]
Looks like it's been resolved? I'll close this but please reopen if needed.
