### ISSUE TITLE
Allocation based on a FileDescriptor Value ?

### ISSUE THREAD

**Issue by Manu-unaM** [libuv/libuv#4011]
Hey, 

I found out there was an allocation in libUV done from a file descriptor value, in the Linux version :
Here :
https://github.com/libuv/libuv/blob/4e766761d00759e9c53d37ca0c04e2872cba6006/src/unix/core.c#L911

Maybe_resize is called to create a allocation with w->fd + 1, and w->fd comes from :
https://github.com/libuv/libuv/blob/4e766761d00759e9c53d37ca0c04e2872cba6006/src/unix/async.c#L223
from a call to eventFd.

1) it looks really fragile to create an allocation where the length value is a FileDescriptor
2) I'm on an exotic platform (console), and the FileDescriptor value that is returned is more than 30 millions, creating an allocation of 500 Mo for each loop.

* **Version**: latest version , 1.45.0
* **Platform**: console / Linux

**Comment by trevnorris** [comment]
Have you confirmed that the allocation is happening? Can you provide more information about the platform you're using?

**Comment by bnoordhuis** [comment]
> it looks really fragile to create an allocation where the length value is a FileDescriptor

It works fine on posix-y platforms where a newly created fd is always the lowest available fd number. If your platform doesn't honor that convention, then you're in for a bad time, yes. What platform is it?

**Comment by Manu-unaM** [comment]
I can't tell anything more on the platform for NDA reasons.
the OS probably has a very loose implementation of posix.

Yes the allocation really occurs, and it's 500Mo for each loop at this point.

I still think making an allocation from a FD value is just terrible design and asking for future issues.
if a process updates the ulimit to open a lot of files, this will make a crazy allocation, just for nothing.

Also ( but I don't know this code at all, so I can be very wrong ) , I'm not sure what is the purpose of this allocation. It's only called once on the init / start of the loop, so it's just used to store 1 value, and to be able to access it as a hashmap ( loop->watchers[fd] ).

**Comment by bnoordhuis** [comment]
You're entitled to your opinion but well, that's all it is: your opinion. Get in touch with your vendor if their posix emulation is so shoddy.

**Comment by Manu-unaM** [comment]
No pb, I just feel it right to report it, but if you're ok with that, it's fine for me.
You know the code and its implication and I don't.
