### ISSUE TITLE
uv_getrusage return wrong ru_maxrss for android 

### ISSUE THREAD

**Issue by calvin2021y** [libuv/libuv#4025]
* **Version**:  v1.45.0
* **Platform**:  android arm64 samsung

ru_maxrss for android return KB,  not Byte.  not match the document

**Comment by calvin2021y** [comment]
In the ios this value show result in BYTE,  in android it shoud in KB.

**Comment by calvin2021y** [comment]
In android, the memory show in KB, I get result from libuv says app use 34M memory,  but use top -p from adb shell, show the same pid just use 8.2M RES.  

I guess the RES and ru_maxrss is same for apples os, not same for linux ?

**Comment by bnoordhuis** [comment]
ru_maxrss is in kilobytes, also on android (unless google really hacked up their kernel fork recently.)

My hunch is top reads from `/proc/<pid>/stat` and doesn't use getrusage(). The RSS field from that file (23rd when counting from zero) is computed somewhat differently than ru_maxrss.

I wouldn't call it a bug, more a platform quirk.

**Comment by calvin2021y** [comment]
ru_maxrss is in kilobytes for android and linux, but bytes for apple ios.  test confirmed.  

libuv should return them in same unit.

**Comment by bnoordhuis** [comment]
[Apple's own documentation](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrusage.2.html) claims otherwise:
>  ru_maxrss    the maximum resident set size utilized (in kilobytes).

**Comment by bnoordhuis** [comment]
That said, the xnu source code suggests it's indeed in bytes, not kilobytes. I'll open a pull request.
