### ISSUE TITLE
macos endless loop

### ISSUE THREAD

**Issue by xinkaven** [libuv/libuv#4029]
macos： ventura 13.0.1
libuv version : 1.45

![image](https://github.com/libuv/libuv/assets/6505204/3706c2da-1833-4d0b-b06f-b74f83589fd3)

 &h->pending is the same in long time  and can't  h->async_cb(h) for long time 

 i think there is endless loop

**Comment by vtjnash** [comment]
That is an address. Of course it is always constant.

**Comment by xinkaven** [comment]
I know it is an address ,but why always loop. and the queue isn't empty  for ever.

**Comment by xinkaven** [comment]
![image](https://github.com/libuv/libuv/assets/6505204/9c239f67-570d-4e54-b33f-7060675d8ff3)

and the value of pending is alwany 0

**Comment by vtjnash** [comment]
Sounds like you probably have a memory bug or thread race in your code. Libuv is single threaded.

**Comment by xinkaven** [comment]
I foud uv_async_init after the function: uv_run  , as follow: 

  r = uv_run(uv_default_loop(), UV_RUN_DEFAULT);
  r = uv_async_init(uv_default_loop(), &async, async_cb);

it ok ?
