### ISSUE TITLE
unix: don't malloc on sync uv_fs_read/uv_fs_write

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#4038]
Minor optimization:
https://github.com/libuv/libuv/blob/65c1402ee66a37d8cdd294f64bfd6def4b9fcf3f/src/unix/fs.c#L2005-L2008
When `cb == NULL` (sync read/write) don't malloc and copy but use the `bufs` argument directly.

**Comment by priya1011** [comment]
Hi @bnoordhuis,
I would like to contribute to it. Could you please assign it to me?

**Comment by bnoordhuis** [comment]
No cookie licking, just send a pull request. :-)

**Comment by ashutosh887** [comment]
I can take this if still not resolved @bnoordhuis @priya1011

**Comment by bnoordhuis** [comment]
You can always send a competing pull request. Best one wins and gets merged. :-)

**Comment by bnoordhuis** [comment]
Looking at the two open pull requests, I believe there is a chance to improve the code even more:

- android ndk 24 has preadv, no need for #ifdef guards
- macos 11 has preadv/prwitev, ditto

Let me open a pull request to see if we can get rid of all the conditionals.

**Comment by bnoordhuis** [comment]
> When cb == NULL (sync read/write) don't malloc and copy but use the bufs argument directly.

Mea culpa, I just realized that won't work for uv_fs_write() because it mutates the elements in `req->bufs`.

That's not normally a problem because it operates on a copy but it's user-visible when using the `bufs` argument directly.
