### ISSUE TITLE
No priority setting for threads created by uv_thread_create

### ISSUE THREAD

**Issue by hhu8** [libuv/libuv#4051]
Hello,

I am Node.js application developer and I found that we could take advantage of the Node.js worker thread feature. For some tasks like logging, event tracking and some CPU intensive tasks (with lower business value), we want to make them running in separate threads and with lower priority, so that they won't contend with the main thread, which is dealing with the user requests. For some more critical tasks like heat beating, we want to make them running with higher priority.
Node.js is calling the uv_thread_create() method in libuv to create worker thread, and there is no parameter or API to set priority.
Could we add this parameter or API in libuv?

Best regards,
Hao

**Comment by bnoordhuis** [comment]
This feature request has come up before but I can't find the issue anymore.

I'm not opposed but what would the API look like? You have to unify pthread_getschedparam() and SetThreadPriority() but how exactly would you do that?

**Comment by hhu8** [comment]
I think the simple way is to extend the structure uv_thread_options_t, by adding a field 'priority', so that to set priority in uv_thread_create_ex after thread is created with _beginthreadex, or with pthread_attr_t on thread creation time pthread_create in uv_thread_create_ex.
The other way is to provide an API for setting it after thread creation. To unify pthread_setschedparam() and SetThreadPriority(), we can name the API uv_thread_set_priority, then implement them in https://github.com/libuv/libuv/blob/v1.x/src/unix/thread.c and https://github.com/libuv/libuv/blob/v1.x/src/win/thread.c separately?

**Comment by bnoordhuis** [comment]
You misunderstand me. Setting the priority is not the issue (although you will also need to think about setting the scheduling policy), the challenge is coming up with a way to declare the priority in a cross-platform manner.

I mean, Unices don't even fully agree between themselves what priorities are possible and how they are numbered, never mind Windows. Libuv needs to abstract over those platform differences somehow.

**Comment by hhu8** [comment]
@bnoordhuis OK, I got it now. I think we can skip the scheduling policy/priority class setting, because it has no relevance to business, although it is related to thread priority. To declare priority in a cross-platform manner, I think from business point of view, we don't need much. I think we can define some enum (with several priority levels, we don't need to set all the numbers) as below, and then mapped them to different priority values or nice values for different platforms underneath. How do you think?

THREAD_PRIORITY_HIGHEST 2
THREAD_PRIORITY_ABOVE_NORMAL 1
THREAD_PRIORITY_NORMAL 0
THREAD_PRIORITY_BELOW_NORMAL -1
THREAD_PRIORITY_LOWEST -2

**Comment by hhu8** [comment]
I looked into the Java. Seems like Java is doing this, that mapping the library thread priority to underlying native thread priority.

https://docs.oracle.com/javase/8/docs/technotes/guides/vm/thread-priorities.html

**Comment by cjihrig** [comment]
FWIW, libuv already does something similar to that for `uv_os_setpriority()` and `uv_os_getpriority()`.

**Comment by hhu8** [comment]
@cjihrig Thank you. But seems like these two utilities are setting and getting priority for processes instead of threads. It says "On Windows, this function utilizes SetPriorityClass()." It doesn't give details on Linux but I guess it applies to threads on Linux. However what we need is to setting priority for threads inside a process (our own application).
If we change priority class for processes, it may impact other processes in the system, and it could happen that, as quote "Use extreme care ... a high-priority class application can use nearly all available CPU time." So setting priority class is another topic.

**Comment by cjihrig** [comment]
Sorry, I was not implying that we would adapt the existing functions to support threads. I was only pointing it out as an example in libuv where we used the approach you proposed in https://github.com/libuv/libuv/issues/4051#issuecomment-1593502906.

**Comment by hhu8** [comment]
@cjihrig Sorry I misunderstood it. Yes, you are right. Thank you so much.

**Comment by bnoordhuis** [comment]
Seems we have consensus about how to move forward? Pull request welcome in that case.

**Comment by hhu8** [comment]
Great. If no one will create a PR, I will do it.

**Comment by hhu8** [comment]
PR created. Don't know how to link to this issue.
https://github.com/libuv/libuv/pull/4062

**Comment by hhu8** [comment]
@bnoordhuis  May I ask who should I contact for reviewing the PR? Seems like it is there for a long time.
