### ISSUE TITLE
Release proposal: v1.46.0

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#4060]
There's been a [bit of disruption ](https://github.com/nodejs/node/issues/48444) with node.js docker images due some obscure bug in io_uring which hopefully has already been taken care of with https://github.com/libuv/libuv/pull/4059, so I'm proposing releasing `v1.46.0`. Any PR's you think we could squeeze into the new version?

**Comment by bnoordhuis** [comment]
I don't think there's anything that should hold up the release.

In fact, I'd be a-okay with just cherry-picking fixes from the v1.x branch and release that as v1.45.1 if anyone is concerned about any of the recent changes.

For reference:

1752791c linux: work around io_uring IORING_OP_CLOSE bug (#4059)
dde50f0e win: fix -Wpointer-to-int-cast warning
24d1d080 src: don't run timers if loop is stopped/unref'd (#4048)
6a9e4293 include: add EUNATCH errno mapping (#4047)
7ada448d unix: add loongarch support (#4054)
2f1614b1 unix,win: add UV_PIPE_NO_TRUNCATE flag (#4040)
b9b6db05 linux: support abstract unix sockets (#4030)
e8ec610f include: update outdated code comment (#4037)
65c1402e ios: fix uv_getrusage() ru_maxrss calculation (#4027)
e7b96331 linux: fs_read to use io_uring if iovcnt > IOV_MAX (#4023)
1b01b786 unix,win: replace QUEUE with struct uv__queue (#4022)
8f32a14a fs: use WTF-8 on Windows (#2970)
962b8e62 linux: add some more iouring backed fs ops (#4012)
281e6185 android: disable io_uring support (#4016)

I'd cherry-pick these:

1752791c linux: work around io_uring IORING_OP_CLOSE bug (#4059)
65c1402e ios: fix uv_getrusage() ru_maxrss calculation (#4027)
e7b96331 linux: fs_read to use io_uring if iovcnt > IOV_MAX (#4023)
281e6185 android: disable io_uring support (#4016)

Only 1752791c needs a small fix-up (uv__kernel_version() removal from fs.c)

**Comment by bnoordhuis** [comment]
https://github.com/bnoordhuis/libuv/commits/v1.45.1-proposal if you want to run with my suggestion :)

**Comment by santigimeno** [comment]
If we want to go via the semver-patch version, we definitely need to add:

24d1d080 src: don't run timers if loop is stopped/unref'd (#4048)

but I'd rather release `1.46.0` if you're ok with it.

**Comment by bnoordhuis** [comment]
I suppose that's fine. I'm a little worried about #2970 but we'll have to take the plunge sooner or later anyway.

**Comment by vtjnash** [comment]
It'd be great to land https://github.com/libuv/libuv/pull/4021 to more fully complete that work, but could use some review, particularly of whether to export those now, or to only have the helper functions internally for now.

**Comment by santigimeno** [comment]
It's looking good with current `v1.x`: https://ci.nodejs.org/view/libuv/job/libuv-in-node/228/
A lot of red, but expected as it's the `parallel.test-release-changelog` and on windows there's only a already flaky test failing: [test-child-process-pipe-dataflow](https://github.com/nodejs/node/pull/48334)

**Comment by caobug** [comment]
Don't consider https://github.com/libuv/libuv/pull/4046 and https://github.com/libuv/libuv/pull/4043? 

^_^

**Comment by santigimeno** [comment]
fyi, unless something comes up, I plan to cut the release tomorrow.

**Comment by santigimeno** [comment]
Still looking pretty good: https://ci.nodejs.org/view/libuv/job/libuv-in-node/229/
Only one aix failure which seems unrelated:
```18:36:39 not ok 3773 node-api/test_worker_buffer_callback/test-free-called
18:36:39   ---
18:36:39   duration_ms: 267.27700
18:36:39   severity: fail
18:36:39   exitcode: 1
18:36:39   stack: |-
18:36:39     node:assert:125
18:36:39       throw new AssertionError(obj);
18:36:39       ^
18:36:39     
18:36:39     AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
18:36:39     
18:36:39     1 !== 0
18:36:39     
18:36:39         at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/node-api/test_worker_buffer_callback/test-free-called.js:14:8)
18:36:39         at Module._compile (node:internal/modules/cjs/loader:1233:14)
18:36:39         at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
18:36:39         at Module.load (node:internal/modules/cjs/loader:1091:32)
18:36:39         at Module._load (node:internal/modules/cjs/loader:938:12)
18:36:39         at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
18:36:39         at node:internal/main/run_main_module:23:47 {
18:36:39       generatedMessage: true,
18:36:39       code: 'ERR_ASSERTION',
18:36:39       actual: 1,
18:36:39       expected: 0,
18:36:39       operator: 'strictEqual'
18:36:39     }
18:36:39     
18:36:39     Node.js v21.0.0-pre
```
