### ISSUE TITLE
[v1.x] testsuite failure (thread_create) on mips/mipsel

### ISSUE THREAD

**Issue by lucab** [libuv/libuv#408]
Even after applying a minimal patch for #335, there are still failures on debian mips and mipsel autobuilders:
 * https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=mipsel&ver=1.6.1-2&stamp=1434420361
 * https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=mips&ver=1.6.1-2&stamp=1434427616
 * https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=mipsel&ver=1.6.1-2~bpo8%2B1&stamp=1435008833

By the fact that identical failures happen on different machines, I suspect this may be a real bug even tough I haven't yet fully investigated it.

The fail-log is:
```
[%  96|+ 249|-   0|T   0|S   1]: thread_local_storage
[%  97|+ 250|-   0|T   0|S   1]: thread_mutex
[%  97|+ 251|-   0|T   0|S   1]: thread_rwlockpthread_create(): Cannot allocate memory
Fatal error in test/runner.c on line 286: process_wait failed
/bin/bash: line 5: 24493 Aborted                 ${dir}$tst
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
```

Those machines have either 4G or 8G of RAM, so I think this is not a real out-of-memory issue.
Opening this ticket to gather opinions, will provide some traces as soon as I have some time.

**Comment by saghul** [comment]
libuv does basically nothing other than call `pthread_create`: https://github.com/libuv/libuv/blob/v1.x/src/unix/thread.c#L55 I'm not sure why this can fail on MIPS, but I doubt there is something we can do in libuv to fix it :-S

**Comment by bnoordhuis** [comment]
I think the error comes from process_wait() in test/runner-unix.c.  @lucab Do you happen to know what ulimit there is in effect?

Also, wups; I completely forgot about #335.  Adding it to my TODO list.

**Comment by lucab** [comment]
@bnoordhuis you are probably right, as the testcases don' t fail when run individually.

The default limits on mips machines I have access to are:
```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3971
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 3971
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

"pending signals" and "max user processes" are lower than on other arch, while all the others values are the same. I'm not root there, so I can't try increasing the limits.

**Comment by lucab** [comment]
@bnoordhuis also, yes, you are correct that the pthread_create() in process_wait() is failing due to a mmap returning ENOMEM.

This is the strace:
```
write(2, "[%  99|+ 248|-   8|T   0|S   0]:"..., 41[%  99|+ 248|-   8|T   0|S   0]: ip4_addr) = 41
unlink("/tmp/uv-test-sock")             = -1 ENOENT (No such file or directory)
nanosleep({0, 250000000}, NULL)         = 0
stat64("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=155648, ...}) = 0
gettimeofday({1436273818, 836783}, NULL) = 0
open("/tmp/tmpftTubyq", O_RDWR|O_CREAT|O_EXCL|O_LARGEFILE, 0600) = 3
unlink("/tmp/tmpftTubyq")               = 0
fcntl64(3, F_GETFL)                     = 0x2002 (flags O_RDWR|O_LARGEFILE)
fstat64(3, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x77634000
_llseek(3, 0, [0], SEEK_CUR)            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x778a1d58) = 15470
pipe([4294967295, 4294967295])          = 4
mmap(NULL, 8388608, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 ENOMEM (Cannot allocate memory)
write(2, "pthread_create(): Cannot allocat"..., 41pthread_create(): Cannot allocate memory
) = 41
close(4)                                = 0
close(5)                                = 0
write(2, "Fatal error in test/runner.c on "..., 62Fatal error in test/runner.c on line 286: process_wait failed
) = 62
rt_sigprocmask(SIG_UNBLOCK, [IOT], NULL, 16) = 0
tgkill(14600, 14600, SIGIOT)            = 0
--- SIGIOT {si_signo=SIGIOT, si_code=SI_TKILL, si_pid=14600, si_uid=2891} ---
[pid 14600] +++ killed by SIGIOT +++
```

However I'm a bit puzzled by this, as all the others mmap() before with same size didn't fail, and ENOMEM should be due to hitting RLIMIT_AS, which is unlimited for this process.

What am I missing?

**Comment by bnoordhuis** [comment]
It's probably address space fragmentation.  Does this patch help?

```diff
diff --git a/test/runner-unix.c b/test/runner-unix.c
index 34de6dc..be921de 100644
--- a/test/runner-unix.c
+++ b/test/runner-unix.c
@@ -174,6 +174,7 @@ int process_wait(process_info_t* vec, int n, int timeout) {
   process_info_t* p;
   dowait_args args;
   pthread_t tid;
+  pthread_attr_t attr;
   unsigned int elapsed_ms;
   struct timeval timebase;
   struct timeval tv;
@@ -202,7 +203,17 @@ int process_wait(process_info_t* vec, int n, int timeout) {
     return -1;
   }
 
-  r = pthread_create(&tid, NULL, dowait, &args);
+  if (pthread_attr_init(&attr))
+    abort();
+
+  if (pthread_attr_setstacksize(&attr, 256 * 1024))
+    abort();
+
+  r = pthread_create(&tid, &attr, dowait, &args);
+
+  if (pthread_attr_destroy(&attr))
+    abort();
+
   if (r) {
     perror("pthread_create()");
     retval = -1;
```

**Comment by lucab** [comment]
Yes, it helps, all tests pass with your patch on the mips test machine I'm using. Let's keep this bug open while I push the patched package to all the autobuilders. I'll report back tomorrow if all builds are green.

Thanks for your assistance!

**Comment by lucab** [comment]
Built fine on mips/mipsel and everywhere else (almost, got a spurious failure on sparc, but looks unrelated). I think you can merge it and close this.
