### ISSUE TITLE
License incompatibility in test/test-thread-affinity.c file

### ISSUE THREAD

**Issue by dod38fr** [libuv/libuv#4080]
Hi

While packaging the new version of `libuv` for Debian, I've seen a [copyright statement](https://github.com/libuv/libuv/blob/c5644368b56872c4044946c35fa91f09adfadcec/test/test-thread-affinity.c#L1) which is not suitable for redistribution by Debian:
```
/* Copyright libuv project contributors. All rights reserved.
 */
```

This statement does not specify the distribution license, hence Debian cannot assume that this file is open-source.

I'm pretty sure this is a mistake, but, unfortunately, I cannot ship this file as is in Debian.

I'd suggest to either:
* add a license in this file, (e.g. like in `test/test-idna.c`)
* remove the "All rights reserved" sentence, in which case the license specified in main LICENSE file applies.

All the best

cc: @qdaoming

**Comment by bnoordhuis** [comment]
Fixed, thanks for the report.
