### ISSUE TITLE
https://dist.libuv.org/ server down 

### ISSUE THREAD

**Issue by ouya99** [libuv/libuv#4082]
Wanted to checkout dist files from https://github.com/libuv/libuv/releases 

but got HTTP Error 500: Internal Server Error

**Comment by johnsonjh** [comment]
Unfortunately, it's having problems again:

https://dist.libuv.org/dist/v1.46.0/libuv-v1.46.0.tar.gz:
2023-07-06 20:30:18 ERROR 500: Internal Server Error.

**Comment by johnsonjh** [comment]
@ouya99 Not sure if you want to re-open.

**Comment by bnoordhuis** [comment]
I'll close this in favor of #4081, it has more discussion.
