### ISSUE TITLE
Sign tarball releases

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#409]
Badically https://github.com/joyent/libuv/issues/1177

/cc @lucab

**Comment by saghul** [comment]
It's happening! https://github.com/libuv/libuv-release-tool/commit/6efb6d9d7260fab271bff7e791cc4e73cb0b2e8f

**Comment by saghul** [comment]
Done!

**Comment by lucab** [comment]
That's great, thanks a lot. I'm pushing signature verification into our packaging updating process. Just as a sidenote, you may want to start using [longer GPG ID](https://evil32.com/) in the MAINTAINERS.md instructions.

**Comment by saghul** [comment]
@lucab thanks for the heads up, fixed in 9daef1c
