### ISSUE TITLE
os390: missing a uv__malloc check in uv_cpu_info

### ISSUE THREAD

**Issue by void0red** [libuv/libuv#4102]
It looks like missing a uv__malloc check at here. It will cause a bug later when alloc fails.
https://github.com/libuv/libuv/blob/d09441ca03e399fe641da88624c8ea0476967187/src/unix/os390.c#L261

**Comment by bnoordhuis** [comment]
@libuv/ibmi

**Comment by kadler** [comment]
This seems specific to z/OS not IBM i. Maybe you meant to ping @libuv/zos?
