### ISSUE TITLE
`uv_spawn()` fails if `%PATH%` is not present

### ISSUE THREAD

**Issue by KyleFromKitware** [libuv/libuv#4115]
If `%PATH%` is not set when `uv_spawn()` is called, it fails to spawn the process, even if an absolute path is given to a file that exists. `uv_spawn()` should be able to handle this case without `%PATH%`. The following code is the culprit:

```c
  /* Get PATH environment variable. */
  path = find_path(env);
  if (path == NULL) {
    DWORD path_len, r;

    path_len = GetEnvironmentVariableW(L"PATH", NULL, 0);
    if (path_len == 0) {
      err = GetLastError();
      goto done;
    }

    alloc_path = (WCHAR*) uv__malloc(path_len * sizeof(WCHAR));
    if (alloc_path == NULL) {
      err = ERROR_OUTOFMEMORY;
      goto done;
    }
    path = alloc_path;

    r = GetEnvironmentVariableW(L"PATH", path, path_len);
    if (r == 0 || r >= path_len) {
      err = GetLastError();
      goto done;
    }
  }
```

* **Platform**: Windows

**Comment by vtjnash** [comment]
What we would probably expect is to use a default path: https://github.com/libuv/libuv/blob/30c3ef9f6feff054e6bc2734d448de34b284fa9b/src/unix/process.c#L712-L715

**Comment by vtjnash** [comment]
Note that PATH is considered mandatory though for Windows, as we expect applications will misbehave with it set incorrectly (since https://github.com/libuv/libuv/commit/2ce14cfab45eb62017e39017fd156e3cf1cd1060)

https://github.com/libuv/libuv/blob/30c3ef9f6feff054e6bc2734d448de34b284fa9b/src/win/process.c#L55

**Comment by KyleFromKitware** [comment]
Yes, it's true that you should never have `%PATH%` unset. However, in practice, CMake has at least one test case that unsets it, and I suspect there are probably others out in the wild as well. We are in the process of migrating from our own process-spawning library to libuv for all of CMake, and this corner case would cause a regression with the current behavior.
