### ISSUE TITLE
Warning of function declaration without a prototype on build

### ISSUE THREAD

**Issue by pmayur** [libuv/libuv#4118]
* **Version**: 
latest version: v1.9.1
* **Platform**:  
platform: macOS Darwin 22.6.0

while building libuv getting the following warning on the `make` stage:
```
src/unix/async.c:250:29: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
static int uv__async_eventfd() {
                            ^
                             void
1 warning generated.
```
issue present in the file: `src/unix/async.c` on line `250`

**Comment by bnoordhuis** [comment]
Ancient version. Fix it by upgrading.
