### ISSUE TITLE
uv_cpu_info can crash the whole program instead of returning an error code

### ISSUE THREAD

**Issue by SChernykh** [libuv/libuv#4121]
* **Version**: 1.46.1-dev
* **Platform**: Linux

This commit: https://github.com/libuv/libuv/commit/a939d643dd416e0705b56c0d551181859a56e4da has made it possible for 
`uv_cpu_info` to abort instead of returning a proper error code. The documentation doesn't mention it, and I think it's not necessary here - it's not so critical error.

**Comment by trevnorris** [comment]
Check https://github.com/libuv/libuv/pull/4056#discussion_r1260158057 for reference why it was written this way. Specifically:

> That aside, we're reading from a /proc pseudo-file where reads can't fail
