### ISSUE TITLE
Add new members for libuv/zos

### ISSUE THREAD

**Issue by richardlau** [libuv/libuv#4124]
@libuv/collaborators I've been asked by @zsw007 if we can add @gabylb and @laijonathan, who both work with him at IBM, to @libuv/zos. While I have maintainer role for that team, I cannot add them to it as they are not members of the libuv organization.

**Comment by bnoordhuis** [comment]
They should have received invitations just now.

**Comment by richardlau** [comment]
I can see they've now accepted and are in the team. Thank you.
