### ISSUE TITLE
Broken building on windows with CMake Ninja generator.

### ISSUE THREAD

**Issue by mizvekov** [libuv/libuv#4139]
Building on windows with Ninja generator is currently broken, caused by recent change: https://github.com/libuv/libuv/pull/2085

The changes in OUTPUT_NAME causes the rules for both shared and static libraries to try to generate a file with the same name, `uv.lib`, resulting in cmake generating an ill-formed build.ninja.

Ninja produces the following diagnostics:
```
ninja: error: build.ninja:1006: multiple rules generate uv.lib [-w dupbuild=err]
```

For reference, see the output of this failing job: https://github.com/libuv/libuv/actions/runs/6203070753/job/16843050538

**Comment by vtjnash** [comment]
Fixed by https://github.com/libuv/libuv/pull/4185
