### ISSUE TITLE
ibmi: test  failures

### ISSUE THREAD

**Issue by abmusse** [libuv/libuv#4143]
* **Version**: v1.46.0 (current latest release)
* **Platform**: IBM i 

The following test cases fail on the IBM i (running make check from local dev system):

- [x] platform_output

Resolved with https://github.com/nodejs/build/pull/3507
```text
...
# exit code 393350
...

# Assertion failed in test/test-platform-output.c on line 162: `err == 0` (1 == 0)
```

- [x] get_group

Resolved with https://github.com/nodejs/build/pull/3507
```text
# exit code 393350
# Output from process `get_group`:
# Assertion failed in test/test-get-passwd.c on line 186: `r == 0` (1 == 0)
```

- [x] get_passwd2

Resolved with https://github.com/libuv/libuv/pull/4154
```text
# exit code 393350
# Output from process `get_passwd2`:
# Assertion failed in test/test-get-passwd.c on line 138: `pwd2.username == "root"` (qsecofr == root)
```

~~- [ ] spawn_setgid_fails~~ See https://github.com/libuv/libuv/pull/4153#issuecomment-1739753253

```text
# exit code 393350
# Output from process `spawn_setgid_fails`:
# Assertion failed in test/test-spawn.c on line 1499: r == UV_EPERM
```

~~- [ ] spawn_setuid_fails~~ See https://github.com/libuv/libuv/pull/4153#issuecomment-1739753253

```text
# exit code 393350
# Output from process `spawn_setuid_fails`:
# Assertion failed in test/test-spawn.c on line 1454: r == UV_EPERM 
```

- [x] [tcp_write_in_a_row](https://github.com/libuv/libuv/issues/3821)

```text
# exit code 393350
# Output from process `tcp_write_in_a_row`:
# Assertion failed in test/test-tcp-write-in-a-row.c on line 75: `write_queue_size0 > 0` (0 > 0)
```

Currently looking to getting these resolved / documented the failures.

**Comment by richardlau** [comment]
> * **Version**: current master

@abmusse Just to check, are these actually on `master` or on `v1.x` (the default branch here is `v1.x`).
