### ISSUE TITLE
fial when make check

### ISSUE THREAD

**Issue by Ikaros-suki** [libuv/libuv#4145]
* **Version**: 
* **Platform**: 
make[1]: 离开目录“/root/libuv”
make  check-TESTS
make[1]: 进入目录“/root/libuv”
The libuv test suite cannot be run as root.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5622：check-TESTS] 错误 1
make[1]: 离开目录“/root/libuv”
make: *** [Makefile:5888：check-am] 错误 2

**Comment by vtjnash** [comment]
As the message says, do not run as root
