### ISSUE TITLE
[Bug] - unix available_parallelism does not handle container cpu limits

### ISSUE THREAD

**Issue by Ludo171** [libuv/libuv#4146]
## The Bug
I come after investigating flaky tests on my current project's CI. The root cause was that `require('os').availableParallelism()` returns the wrong result for a node process running on a container which has a cpu limit lower than the host machine.

We are using Node + Jest, which rely on libuv to set a parallelism amount (jest workers). The jobs are run on gitlab runners from a private Kubernetes cluster.
Turns out that available_parallelism returns the number of CPUs of the host machine, without taking into account the pods/containers resource limit (as we are many developers, we limit them to 1 cpu). The result is that our test framework (jest) over parallises and gets very slow.

## How to reproduce (and more details)
The bug is discribed in detail and reproducible on this repository : https://github.com/Ludo171/bug_jest_uses_to_many_cpus

## Proposal for a fix
Amongst my ideas to fix this bug, the best solution would be to improve [libuv/uv_available_parallism](https://github.com/libuv/libuv/blob/c811169f91b2101f7302e96de3d2dc366ade3a25/src/unix/core.c#L1743)
- Such utilitary node function is crucial in a time where containerized runtime has become very common. I have not found any alternative close to get the available Cpus for a node process, taking into account resource limits/quota so far.

- We can add an early condition that first, looks for cpu informations in /sys/fs/cgroup/cpu.cfs_quota_us and /sys/fs/cgroup/cpu.cfs_period_us for [linux kernel using cgroup v1](https://docs.kernel.org/scheduler/sched-bwc.html), or in /sys/fs/cgroup/cpu.max for [linux kernel using cgroup v2](https://docs.kernel.org/admin-guide/cgroup-v2.html#cgroup-v2-cpu). If they contain quantified limits, do the ratio to compute available parallelism. 
- Else, continue with existing behavior.

## Environment 
* **Version**: Node version 20.7.0  => libuv ??? 
* **Platform**: Linux 2205f4b7d256 6.3.13-linuxkit #1 SMP PREEMPT Thu Sep  7 07:48:47 UTC 2023 aarch64 Linux (node-alpine docker image)

**Comment by bnoordhuis** [comment]
PR welcome, just don't go overboard and try to keep it minimal. Have a look at src/unix/linux.c to see how the cgroups v1-vs-v2 dichotomy is currently handled in `uv_get_constrained_memory()`.

**Comment by bnoordhuis** [comment]
I looked into this a little bit but it's really not straightforward with cgroupsv2. Random notes:

- parsing cpuset.cpus or cpuset.cpus.effective works but they're usually unconstrained

- cpu.max looks like `<max> <duration>` and max/duration = numcpus (can be fractional, like 0.5 or 1.5) but max can also be the literal string "max"

- cpu.weight... unclear how to use in a parallelism estimate, it's a kind of soft limit for when there's resource contention

- cpu.uclamp.min and cpu.uclamp.max are... hard limits? Carve-outs? Unclear

- unclear which cpu.max and cpu.weight to use. The slice for my terminal for example doesn't have them, they're part of the parent slice. Is it okay to use those? If yes, why? If not, why not?
