### ISSUE TITLE
Signing keys not available

### ISSUE THREAD

**Issue by bkmgit** [libuv/libuv#4150]
Signing keys for
@trevnorris 
AEFC 279A 0C93 0676 7E58 29A1 251C A676 820D C7F3
and
@erw7 
5804 F999 8A92 2AFB A398 47A0 7183 5090 6134 887F
are not available at https://keys.openpgp.org or https://keyserver.ubuntu.com/

**Comment by vtjnash** [comment]
I don't think we consider that essential, though good practice. All keys are available here on github: https://github.com/libuv/libuv/blob/v1.x/MAINTAINERS.md. Is just anyone allowed to upload a key?
