### ISSUE TITLE
raspberry pi: blacklist io_uring on all 32-bit kernels up to current 6.1.54-v7l+

### ISSUE THREAD

**Issue by brubbel** [libuv/libuv#4158]
cfr. https://github.com/nodejs/node/issues/49937#issuecomment-1740490144

**Comment by bnoordhuis** [comment]
@santigimeno at this point you're probably better versed if good vs. bad kernels than I am. Thoughts?

**Comment by santigimeno** [comment]
Unfortunately I don't have much to add here. I was able to emulate with qemu a `raspios-bullseye-armhf-lite.img` with a 5.15.84 kernel using `node-v20.7.0-linux-armv6l` and couldn't reproduce the issue. Honestly I don't like the prospect of blacklisting all 32-bit kernels without investigating the issue, but lacking the hardware to do so, I don't have a better proposal.

**Comment by bnoordhuis** [comment]
https://github.com/libuv/libuv/pull/4187
