### ISSUE TITLE
QNX: Build fails, issue in src/unix/qnx.c

### ISSUE THREAD

**Issue by avrilzchen** [libuv/libuv#4168]
Hello, I'm trying to port libuv to QNX 8.0, but I ran into some issues in the `src/unix/qnx.cc` file. 

Specifically, I get the following error when building:

```
In file included from /home/avchen/libuv/src/unix/qnx.c:29:
/home/avchen/libuv/src/unix/qnx.c: In function 'uv_cpu_info':
/home/avchen/libuv/src/unix/qnx.c:128:57: error: 'struct syspage_entry' has no member named 'new_cpuinfo'; did you mean 'cpuinfo'?
  128 |     (struct cpuinfo_entry*)_SYSPAGE_ENTRY(_syspage_ptr, new_cpuinfo);
```

So I was wondering what the `new_cpuinfo` member  in the function `int uv_cpu_info(uv_cpu_info_t** cpu_infos, int* count)` is coming from. It is not a member present in  he `syspage_entry` structure, at least when I've looked into the `syspage.h` file, it has `cpuinfo` instead. 

I've tried changing this line:   
```
struct cpuinfo_entry* cpuinfo =
    (struct cpuinfo_entry*)_SYSPAGE_ENTRY(_syspage_ptr, new_cpuinfo);
```
to 
```
struct cpuinfo_entry* cpuinfo = SYSPAGE_ENTRY(cpuinfo);
```

and also 

```
struct cpuinfo_entry* cpuinfo =
    (struct cpuinfo_entry*)_SYSPAGE_ENTRY(_syspage_ptr, cpuinfo);
```

Both changes ends up building but I was wondering if it accomplishes the same thing as having `new_cpuinfo` and where is `new_cpuinfo` coming from?

* **Version**:  v1.46.0
* **Platform**:  
❯ uname -a
Linux BB78327197 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* **Target Platform**: `QNX 8.0 aarch64le and x86_64` 
* **Compiler**: The C compiler identification is QCC 12.2.0

**Comment by bnoordhuis** [comment]
Maybe @Arenoros or @mjvankampen know, they contributed the qnx port.
