### ISSUE TITLE
Failed tests after make.

### ISSUE THREAD

**Issue by jorge-imperial** [libuv/libuv#417]
uname -a
Darwin Jorges-MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
ç=============================================================
[%  61|+ 166|-   0|T   0|S   0]: getaddrinfo_fail
`getaddrinfo_fail` failed: exit code 6
Output from process `getaddrinfo_fail`:
Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
=============================================================
[%  62|+ 166|-   1|T   0|S   0]: getaddrinfo_fail_sync
`getaddrinfo_fail_sync` failed: exit code 6
Output from process `getaddrinfo_fail_sync`:
Assertion failed in test/test-getaddrinfo.c on line 108: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy", NULL, NULL)
=============================================================
[%  78|+ 210|-   2|T   0|S   0]: osx_selectgot some input
with a couple of lines
feel pretty happy
[%  79|+ 211|-   2|T   0|S   0]: osx_select_many_fdsgot some input
with a couple of lines
feel pretty happy
[% 100|+ 267|-   2|T   0|S   0]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
ç

**Comment by saghul** [comment]
Closing as it's an environment issue: your resolver says that  "xyzzy.xyzzy.xyzzy" is a valid address, when it's not.
