### ISSUE TITLE
Since the introduction of io_uring, CIFS write operations fall 

### ISSUE THREAD

**Issue by simatec** [libuv/libuv#4170]
We have a [backup plugin](https://github.com/simatec/ioBroker.backitup) in our ioT system [iobroker](https://www.iobroker.net/#en/statistics), which among others offers the possibility to backup via CIFS to a local NAS.

Since the introduction of io_uring and the update to libuv 1.45 in Node 20.3.0, the writes to the mounted CIFS drive are failing.

**Comment by bnoordhuis** [comment]
@simatec I'm going to close this because bifurcation doesn't help, let's keep the discussion in https://github.com/nodejs/node/issues/50061.
