### ISSUE TITLE
compile libuv from alpine error:queue.h:68:19: error: storing the address of local variable 'queue'

### ISSUE THREAD

**Issue by edgego** [libuv/libuv#4173]
In file included from /root/TDengine/contrib/libuv/src/uv-common.h:42,
                 from /root/TDengine/contrib/libuv/src/uv-common.c:23:
/root/TDengine/contrib/libuv/src/uv-common.c: In function 'uv_walk':
/root/TDengine/contrib/libuv/src/queue.h:68:19: error: storing the address of local variable 'queue' in '((void * (**)[2])MEM[(void *[2] * *)loop_13(D) + 16B])[1]' [-Werror=dangling-pointer=]
   68 |     QUEUE_PREV(q) = (n);                                                      \
      |                   ^
/root/TDengine/contrib/libuv/src/queue.h:78:7: note: in expansion of macro 'QUEUE_SPLIT'
   78 |       QUEUE_SPLIT(h, q, n);                                                   \
      |       ^~~~~~~~~~~
/root/TDengine/contrib/libuv/src/uv-common.c:507:3: note: in expansion of macro 'QUEUE_MOVE'
  507 |   QUEUE_MOVE(&loop->handle_queue, &queue);
      |   ^~~~~~~~~~
/root/TDengine/contrib/libuv/src/uv-common.c:503:9: note: 'queue' declared here
  503 |   QUEUE queue;
      |         ^~~~~
/root/TDengine/contrib/libuv/src/queue.h:40:27: note: '((void * (**)[2])loop)[2]' declared here
   40 |   ((const QUEUE *) (q) == (const QUEUE *) QUEUE_NEXT(q))
      |                           ^
/root/TDengine/contrib/libuv/src/queue.h:74:9: note: in expansion of macro 'QUEUE_EMPTY'
   74 |     if (QUEUE_EMPTY(h))                                                       \
      |         ^~~~~~~~~~~
/root/TDengine/contrib/libuv/src/uv-common.c:507:3: note: in expansion of macro 'QUEUE_MOVE'
  507 |   QUEUE_MOVE(&loop->handle_queue, &queue);
      |   ^~~~~~~~~~
cc1: all warnings being treated as errors

**Comment by bnoordhuis** [comment]
Upgrade, already fixed.

**Comment by edgego** [comment]
@bnoordhuis  would you tell which version for fixed?

**Comment by bnoordhuis** [comment]
Latest, v1.45.0. Please always test the latest version before opening bug reports.

**Comment by edgego** [comment]
tested v1.46.0 , compiling works fine.
