### ISSUE TITLE
New Windows CI job configurations

### ISSUE THREAD

**Issue by StefanStojanovic** [libuv/libuv#4174]
I'm working on updating [the test CI](https://ci.nodejs.org/) machines. One of the changes is getting rid of the Win2012r2 machines, which are EOL as of recently. I see [libuv-test-commit-windows-cmake](https://ci.nodejs.org/view/All/job/libuv-test-commit-windows-cmake/) uses Win2012r2 which will soon be unavailable.

What are the most important Windows and Visual Studio versions that need to be covered for the libuv project? We'll have Windows 2016, 2019, and 2022, as well as Windows 10 and 11. Visual Studio versions that will be present are VS2015 and above.

**Comment by bnoordhuis** [comment]
See discussion in https://github.com/libuv/libuv/issues/3889.  I personally don't have much of a problem with dropping pre-Windows 10 but VS2015 may be important because of python (more specifically: native python modules that use libuv.)

**Comment by bnoordhuis** [comment]
Sounds good to me. We have additional coverage through GH Actions.

**Comment by StefanStojanovic** [comment]
The new machines are set up and I'm in the process of changing jobs on Jenkins. As discussed, I changed [libuv-test-commit-windows-cmake](https://ci.nodejs.org/view/All/job/libuv-test-commit-windows-cmake/) to include new machines and I also added ARM64 machines (thanks for the idea @richardlau). In the following months, I'll be updating the Azure machine as well and then I'll probably add some Windows 11 machines to this job too.

Btw, is `UNSTABLE` the expected state when everything passes well?

**Comment by bnoordhuis** [comment]
Closing since I don't believe there's anything to do on our end?

> Btw, is UNSTABLE the expected state when everything passes well?

Not sure. Maybe @richardlau knows.

**Comment by richardlau** [comment]
No, UNTSABLE is not the expected state since libuv does not have the concept of a flaky test.
The configuration for `libuv-test-commit-windows-cmake` has:
```
echo TAP version 13 > out\test.tap
out\Debug\uv_run_tests.exe 2>&1 | tee -a out\test.tap
if errorlevel 1 exit /b
tap2junit -i out\test.tap -o out\test.xml
if errorlevel 1 exit /b

echo TAP version 13 > out\test_a.tap
out\Debug\uv_run_tests_a.exe 2>&1 | tee -a out\test_a.tap
if errorlevel 1 exit /b
tap2junit -i out\test_a.tap -o out\test_a.xml
if errorlevel 1 exit /b

:: The JUnit Plugin only marks the job as Unstable when it finds any kind of failure, including flaky tests.
:: We need to look for 'not ok' in the tap files below to fail the job when there are real failures.
```

If I look at the artifacts in https://ci.nodejs.org/view/All/job/libuv-test-commit-windows-cmake/nodes=win10-vs2019/ it looks like:
- The tap files have no failures, so the check in the job that searches for `^not ok` that would have failed the build is not triggered.
- The xml file is showing failures. A lot of failures. They look like:
```xml
		<testcase name="None">
			<failure type="failure" message=" (0)"/>
		</testcase>
```
which looks like a failure of tap2junit to convert the tap to xml.
