### ISSUE TITLE
Got compiling error from ubuntu

### ISSUE THREAD

**Issue by edgego** [libuv/libuv#4175]
/root/ekuiper-1.11.3/TDengine/contrib/libuv/src/unix/linux.c:1721:3: error: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
 1721 |   fgets(buf, sizeof(buf), fp);  /* Skip first line. */
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/ekuiper-1.11.3/TDengine/contrib/libuv/src/unix/linux.c:1732:5: error: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
 1732 |     fgets(buf, sizeof(buf), fp);  /* Skip rest of line. */
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/ekuiper-1.11.3/TDengine/contrib/libuv/src/unix/linux.c:1812:5: error: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
 1812 |     fscanf(fp, "%llu", &(*cpus)[cpu].freq);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* **Version**: 1.46.0
* **Platform**:  inux edgego 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux 

But compiling version 1.44.2 is fine, not get  error

**Comment by bnoordhuis** [comment]
Already fixed, not yet released: #4056

Don't compile third-party code with -Werror (or if you do, don't complain it doesn't build.)
