### ISSUE TITLE
Release v1.47.0

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#4186]
Seems like bugfixes and workarounds for kernel bugs are slowing down, so it seems like time to release a new version? I think this dropped support for some old platforms, so it would be a minor release in semver, and not just a patch release. Any thoughts or things people are eager to include?

Changes: https://github.com/libuv/libuv/compare/v1.46.0...v1.x

**Comment by bnoordhuis** [comment]
https://github.com/libuv/libuv/pull/4187 - hopefully uncontroversial

**Comment by bnoordhuis** [comment]
#4075 isn't ready, IMO. Left a review. Don't hold up the release for that, it can wait until v1.48.0.

**Comment by vtjnash** [comment]
II forgot only @bnoordhuis and @saghul and authorized to make releases now on the ftp server https://github.com/libuv/libuv/issues/4081#issuecomment-1628913340

**Comment by santigimeno** [comment]
I have access myself as well. From this comment it seems you should have access? https://github.com/nodejs/build/issues/3353#issuecomment-1547578054

**Comment by vtjnash** [comment]
Not sure, since I couldn't get past the firewall. But I think we publish to GitHub now, so I just need to update the release script next week to do that instead

**Comment by santigimeno** [comment]
Fair enough. Now that I remember, there was a jump host you have to point to to access the actual server. Let me know if you need that info and I'll send an email with the details

**Comment by AlttiRi** [comment]
1.47.0 was released a month ago, but it's still not included in Node.js because of some issues: https://github.com/nodejs/node/pull/50650

Will you release 1.47.1 with the fixes in this year?
To fix this bug https://github.com/nodejs/node/issues/48673 finally.
