### ISSUE TITLE
reconsidering recvmmsg() support

### ISSUE THREAD

**Issue by vavrusa** [libuv/libuv#419]
As you might know, Github ditched libuv based statsd an reimplemented Brubeck, citing some reasoning.

> The first thing we changed in Brubeck was the event-loop based approach of the original statsd. Evented I/O on a single socket is a waste of cycles; while receiving 4 million packets per second, polling for read events will give you unsurprisingly predictable results: there is always a packet ready to be read. Because of this, we replaced the event loop with several worker threads sharing a single listen socket.
- [Brubeck, a statsd-compatible metrics aggregator](http://githubengineering.com/brubeck/)

This is somewhat true, but the syscall overhead may be very well alleviated by libuv by:
- `recvmmsg()` which you rejected in [#414](https://github.com/joyent/libuv/issues/414), speaking for myself this helped to additional ~20% p/s in [Knot DNS](https://github.com/CZ-NIC/knot/blob/master/src/knot/server/udp-handler.c#L368), maybe others may chime in
- coalescing more reads for a single activity notification, i.e. if the polling on a socket results in activity, try to read it up to N times until it returns `EWOULDBLOCK` (presuming it's non-blocking), this mitigates the cost of polling/reading during contention

What are your opinions? I'm okay with contributing, not sure about the Windows side though.

**Comment by saghul** [comment]
Hey @vavrusa!

> As you might know, Github ditched libuv based statsd an reimplemented Brubeck, citing some reasoning.

I wasn't aware of this.

Re their reasoning: right now it's possible to create the sockets early with `uv_udp_init_ex` and manually set `SO_REUSEPORT` to achieve what they wanted, by running a loop on each thread. Of course nobody asked for this.

> recvmmsg() which you rejected in #414, speaking for myself this helped to additional ~20% p/s in Knot DNS, maybe others may chime in

Maybe things have changed, I have no idea. The best would be to give it a shot and use some of our benchmarks (or write a new one if the case is not covered) to see if there is such an inprovement across the board.

> coalescing more reads for a single activity notification, i.e. if the polling on a socket results in activity, try to read it up to N times until it returns EWOULDBLOCK (presuming it's non-blocking), this mitigates the cost of polling/reading during contention

We already read until we get EWOULDBLOCK: https://github.com/libuv/libuv/blob/v1.x/src/unix/udp.c#L185 but each packet gets it's own recv_cb called. The way things work now, alloc_cb gets called for the user to allocate a buffer for the packet, and then recv_cb gets called with it. Would you want a single recv_cb callback executed with multiple packets? I kind-of doubt that would improve things by much. Also, the API would need to change in order to allocate multiple buffers in order to differentiate packets...

At any rate, experiment with it, get some numbers, and then we can see the way forward :-)

**Comment by vavrusa** [comment]
Hey!

>Re their reasoning: right now it's possible to create the sockets early with uv_udp_init_ex and manually set SO_REUSEPORT to achieve what they wanted, by running a loop on each thread. Of course nobody asked for this.

Well I did :) Jokes aside, with REUSEPORT event-loop model makes a lot of sense since you can scale the application without the thundering herd issue with threads and locking tarpit.

> We already read until we get EWOULDBLOCK

Cool, I didn't check, looks okay :heavy_check_mark: 

> Would you want a single recv_cb callback executed with multiple packets? I kind-of doubt that would improve things by much. Also, the API would need to change in order to allocate multiple buffers in order to differentiate packets...

Hell no, this is all good, function call isn't that expensive. What I want is a different interface for the allocation callback (the libuv could hint "allocate me 5 bufs of this length", the caller could answer "here are 3 bufs of the requested length"). The libuv code could then use recvmmsg to request 3 packets at once, and pass them to the caller one by one as it is now.

> At any rate, experiment with it, get some numbers, and then we can see the way forward :-)

Okay, let's get some numbers first! Thanks for not rejecting me outright :)

**Comment by bnoordhuis** [comment]
> recvmmsg() which you rejected in #414, speaking for myself this helped to additional ~20% p/s in Knot DNS, maybe others may chime in

The behavior I observed with recvmmsg() is that it's sometimes faster when packets come in at a high rate but it's a net loss when there is just one datagram to read.  I don't remember the exact numbers but it was on the order of 1/3rd slower than recvmsg().

Maybe it's possible to build some kind of self-learning heuristic into src/unix/udp.c where it selects recvmsg() or recvmmsg() based on how often it's possible to read more than one datagram.

Another possible optimization is to call read() instead of recvmsg() when we don't care about metadata like the sender's address.  That probably requires a new flag, though.

**Comment by vavrusa** [comment]
> The behavior I observed with recvmmsg() is that it's sometimes faster when packets come in at a high rate but it's a net loss when there is just one datagram to read.

That's the case I'm trying to optimise, when the "packets come in at a high rate". You're worried about ultra-low latency when the server is sleeping most of the time or what use case?

> Another possible optimization is to call read() instead of recvmsg() when we don't care about metadata like the sender's address.

I think UDP servers are interested in sending back something most of the time. Maybe for some specific applications like log aggregator, but then this a case where greater throughput is more important.

So I've cooked up a benchmark (somewhat resembling busy DNS/NTP/DHCP) and some quick & dirty recvmmsg implementation:
* https://github.com/libuv/libuv/compare/v1.x...vavrusa:v1.x

And fired it up, first `recvmsg()`:
```bash
$ taskset -c 0,1 ./out/Release/run-benchmarks ping_udp1 # latency test (1 pinger)
ping_pongs: 1 pingers, ~ 35842 roundtrips/s
$ taskset -c 0,1 ./out/Release/run-benchmarks ping_udp10 # throughput test (10 pingers)
ping_pongs: 10 pingers, ~ 121800 roundtrips/s
$ taskset -c 0,1 ./out/Release/run-benchmarks ping_udp100 # throughput test (100 pingers)
ping_pongs: 100 pingers, ~ 121791 roundtrips/s
```

So the test saturates the `udp4_echo_server` with 10 pingers at around 120k pings/sec. I did just CPU pinning so it doesn't jump around the cores, otherwise nothing special.

Now for the `recvmmsg()`:
```bash
$ taskset -c 0,1 ./out/Release/run-benchmarks ping_udp1 # latency test (1 pinger)
ping_pongs: 1 pingers, ~ 37821 roundtrips/s
$ taskset -c 0,1 ./out/Release/run-benchmarks ping_udp10 # throughput test (10 pingers)
ping_pongs: 10 pingers, ~ 193163 roundtrips/s
$ taskset -c 0,1 ./out/Release/run-benchmarks ping_udp100 # throughput test (100 pingers)
ping_pongs: 100 pingers, ~ 201186 roundtrips/s
```

Same stuff, saturates the receiver at around 200k pings/sec, latency test is more/less the same (within 1 sigma) as with the recvmsg. The recvmmsg takes up to 10 pkts at once, and it's stupidly cleared and alloc'd on stack on every iteration.

I did more runs (10 per each test), it's pretty consistent with pinning (plot and data attached).
* https://gist.github.com/vavrusa/cb9ebbe134f3563d91ef

![recvmsg_recvmmsg](https://cloud.githubusercontent.com/assets/139311/8468195/43e5657e-2069-11e5-93ef-b89abf7f0dd4.png)

FWIW it's Linux 3.18, Xeon(R) CPU E5-2609

**Comment by bnoordhuis** [comment]
> That's the case I'm trying to optimise, when the "packets come in at a high rate". You're worried about ultra-low latency when the server is sleeping most of the time or what use case?

One use case I'm thinking of is many sockets, with individual sockets mostly idle, but in aggregate quite busy.

Libuv is a general purpose library, it can't optimize for one use case when it unduly pessimizes another.  That's why I suggested a self-learning approach: maintain a sliding window average of multi-packet read events and decide based on that whether to use recvmsg() or recvmmsg().

There should be room enough in `uv_udp_t.flags` to store the necessary state.  You probably don't need that many bits; if the last four or five read events all had multiple packets lined up, there's a good chance the next one will too.

**Comment by vavrusa** [comment]
Absolutely, 2 bit branch predictors had 90%+ accuracy, it would be enough to predict whether the receiver is loaded. OTOH do you measure any extra latency on your box? To me it's just jitter (recvmsg/recvmmsg).

**Comment by vavrusa** [comment]
I just had a different idea, after mucking with predictor, in https://github.com/libuv/libuv/compare/v1.x...vavrusa:v1.x
* If the caller provides a buffer with requested size (max UDP datagram size), it uses `recvmsg()`
* If the caller provides a buffer with a *multiple* of requested size, `recvmmsg()` is used
* The asynchronous sends can be coalesced with `sendmmsg()`

So the caller decides about his workload, it doesn't require `alloc_cb` signature change, and write coalescing is free.
Downsides - can't provide multiple `iovecs` with smaller sizes (if we know that the application works with <512B datagrams only for example). But that would require `alloc_cb` to change API.

Does that idea sound workable?

**Comment by fcelda** [comment]
Hello guys.

I would like to see the `recvmmsg` support in libuv as well. And I'm willing to help with this.

I've reviewed @vavrusa's code and it looks pretty well. The implementation is straightforward – nothing complicated. There is just one possible problem I see with the buffer allocation as a multiple of requested size. There is not mechanism to indicate whether the platform actually supports `recvmmsg`. As a result, the allocation function might waste memory which will never be used. In addition, I find it a bit counter-intuitive.

I think it might be better to enable `recvmmsg` support by default (if available) or to add a flag into `uv_udp_flags` requesting multi-message receiving (again, if available). In either case, the allocation callback should called with maximum buffer size libuv can handle.

**Comment by fcelda** [comment]
@saghul @vavrusa Any update on this?

**Comment by saghul** [comment]
No updates from my side, sorry. I've been busy with many things and didn't have the time to follow up on everything :-S

I'll add a label so I don't forget to re-check this.

**Comment by vavrusa** [comment]
It's been a while (🍂❄️🌱), any update on this by a chance?

**Comment by saghul** [comment]
I'm afraid not, sorry :-(

**Comment by mscdex** [comment]
I think this would be pretty good to have (for node at least).

@vavrusa Have you considered submitting a PR with your changes as a starting point?

**Comment by vavrusa** [comment]
I think I opened a PR 2 years ago, the code is still in my fork if you want to work on it. https://github.com/libuv/libuv/compare/v1.x...vavrusa:v1.x

**Comment by mscdex** [comment]
@vavrusa I saw the fork but no PR in this or the old joyent/libuv repo.

**Comment by vavrusa** [comment]
Maybe not, it's been a long time ago. There was an issue somewhere that proposed it and it was declined. Feel free to use the code in the fork however you want, it'd be nice if it were accepted, I just don't have the time nor an immediate use for it.

**Comment by pspacek** [comment]
@saghul Hello! It's been some years now so please let me ask again. Would you be willing to accept PR based on @vavrusa code? It would be very useful for us.

**Comment by oerdnj** [comment]
I can't reopen the bug, but there are at least two DNS implementations that would be willing to continue to work on this.  But it would be a lost work if we updated the code and it would be never merged as it happened with the TFO.

**Comment by santigimeno** [comment]
I think the best way to move this forward would be opening a new PR with the code mentioned in this thread (probably it'd need some work to update it to current `v1.x` branch). Hopefully it will go in this time.

> But it would be a lost work if we updated the code and it would be never merged as it happened with the TFO.

@oerdnj sorry about it, I remember starting reviewing it but forgot about it. I'll try to pick it up.

**Comment by oerdnj** [comment]
Thanks! I rebased @vavrusa's work on top of current v1.x, added a fixup commit that uses `uv__recvmmsg()` and `uv__sendmmsg()` conditionally.  That bit needs to be made better to avoid the extra syscall by storing the availability of the calls locally, but the general approach is fine.

The code in `uv__udp_sendmmsg()` might be overly too complicated, but I don't see any better way to support `sendmmsg()` while allowing to fail gracefully.

The PR is here: https://github.com/libuv/libuv/pull/2532

**Comment by oerdnj** [comment]
> @oerdnj sorry about it, I remember starting reviewing it but forgot about it. I'll try to pick it up.

Ah, no worries, I understand that there's only that much a single person and single team can handle. The TFO MR is largely outdated, so it might be better to just write it from the scratch again.

BIND 9.16+ is going to use libuv to replace the networking stack (so, big kudos! to you and other libuv contributors), so somebody from my team will probably occasionally submit an improvement or two.

**Comment by saghul** [comment]
https://github.com/libuv/libuv/pull/2532 is close to landing. CLosing this one.
