### ISSUE TITLE
Libuv handle -> IO/Event Handlle(r)

### ISSUE THREAD

**Issue by David00154** [libuv/libuv#4194]
Hello libuv team, this is just a question.
I have been trying to wrap my head around event loop and how libuv works for about 3 months now I just understood it just now and I think one major reason why I couldn’t understand it was the fact that you guys call it handle instead of event handler.

**Comment by bnoordhuis** [comment]
I'm missing the question. :-)

**Comment by David00154** [comment]
The question is why is the handle not called event handler
