### ISSUE TITLE
Assertion failed: 0, file src\uv-common.c, line 75

### ISSUE THREAD

**Issue by Crazy-Ivan** [libuv/libuv#420]
Hi, we have a problem during installation few modules via npm, like phantomJs. etc 
Does anybody could tell me what went wrong ? We have tried bunch of node versions. 0.12.14 and 0.12.15 and we still get the same issue "Assertion failed: 0, file src\uv-common.c, line 75" (however in different line - 75 is from node version 0.12.14). Maybe someone know what this code try to assert, so we could figure it out what to fix. 

We use Windows

**Comment by saghul** [comment]
The line numbers no longer match, but I believe the problem is caused by an unmapped error code. In order to know which one, we need a backtrace of the crashed process. It would be perfect if it could be reproducible with a simple test case.

**Comment by saghul** [comment]
No follow-up, closing.
