### ISSUE TITLE
v1.47.0 does not build on macOS due to missing preadv() / pwritev()

### ISSUE THREAD

**Issue by debohman** [libuv/libuv#4204]
FIrst:
```
src/unix/fs.c:434:11: warning: implicit declaration of function 'preadv' [-Wimplicit-function-declaration]
  434 |       r = preadv(fd, bufs, nbufs, off);
      |           ^
src/unix/fs.c:1113:11: warning: implicit declaration of function 'pwritev' [-Wimplicit-function-declaration]
 1113 |       r = pwritev(fd, bufs, nbufs, off);
      |           ^
```

Then:

```
  CCLD     libuv.la
Undefined symbols for architecture x86_64:
  "_preadv", referenced from:
      _uv__fs_work in libuv_la-fs.o
  "_pwritev", referenced from:
      _uv__fs_work in libuv_la-fs.o
ld: symbol(s) not found for architecture x86_64
```
* **Version**: 1.47.0
* **Platform**: macOS 10.12.6

**Comment by bnoordhuis** [comment]
We dropped support for macOS 10.x a few months ago.

(1.5 years ago in fact but we didn't drop all the support code immediately.)

**Comment by sryze** [comment]
But why though? It's not like 10.15 is 20 years old - it was release just 4 years ago..

**Comment by qianbinbin** [comment]
Although both Apple and Homebrew dropped support for Catalina, libuv seems the only formulae I've used that doesn't work for me, and unfortunately it's a dependence of node.

I have to pin it to avoid the error. Hope this won't cause any other issues.

```sh
brew pin libuv
```

**Comment by bnoordhuis** [comment]
@sryze because Apple. The rule of thumb we follow is that if the vendor won't provide support anymore, then neither do we.
