### ISSUE TITLE
test: flaky test udp_recv_in_a_row

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#4219]
```
not ok 412 - udp_recv_in_a_row
# exit code 6
# Output from process `udp_recv_in_a_row`:
# Assertion failed in /Users/runner/work/libuv/libuv/test/test-udp-recv-in-a-row.c on line 54: `sizeof(send_data) == nread` (10 == 0)
```
That's the consequent in this if statement:
https://github.com/libuv/libuv/blob/874363f652f0aafb3ed58a4da65940258e5ee713/test/test-udp-recv-in-a-row.c#L53-L57
And this comment may be relevant:
https://github.com/libuv/libuv/blob/874363f652f0aafb3ed58a4da65940258e5ee713/test/test-udp-recv-in-a-row.c#L63-L68

**Comment by juanarbol** [comment]
Also happens on macOS

**Comment by bnoordhuis** [comment]
No, _only_ on macos (so far anyway.) See also https://github.com/libuv/libuv/pull/4344#discussion_r1516908865.
