### ISSUE TITLE
run loop in a new thread,  the main thread ctrl+c signal not work anymore

### ISSUE THREAD

**Issue by calvin2021y** [libuv/libuv#4223]
I has the main thread run a library (not libuv) with ctrl+C graceful quit support.   

before I start main thread, I setup and new thread to run a libuv loop thread, in here no signal is setup.  (no uv_signal_start or uv__signal_start)

The problem is when The new libuv loop thread started, the main thread ctrl+c graceful shutdown not work anymore.   (the process quit without any action)

Is there a option to adjust libuv behavior in this case?  like limit libuv only handle thread signal and ignore stdio event? 

* **Version**:  v1.47.0
* **Platform**:  linux debian 12

**Comment by bnoordhuis** [comment]
That's probably not a libuv problem but a general threading problem if that other library is using a signalfd to catch SIGINT.

See if blocking SIGINT in the libuv thread with pthread_sigmask() helps.

**Comment by calvin2021y** [comment]
Thanks very much.  blocking SIGINT work.
