### ISSUE TITLE
test: pipe_overlong_path fails on AIX

### ISSUE THREAD

**Issue by abmusse** [libuv/libuv#4231]
* **Version**:  Current v1.x branch 
* **Platform**: AIX 

Discovered this failure while running the CI for a pull request:

Ref: https://github.com/libuv/libuv/pull/4229

https://ci.nodejs.org/job/libuv-test-commit-aix/nodes=aix72-ppc64/2279/console

```sh
not ok 199 - pipe_overlong_path
# exit code 393222
# Output from process `pipe_overlong_path`:
# Assertion failed in test/test-pipe-bind-error.c on line 175: `UV_EINVAL == uv_pipe_bind2(&pipe, path, sizeof(path), UV_PIPE_NO_TRUNCATE)` (-22 == -86)
```
https://github.com/libuv/libuv/blob/6be130e1b865af62e6509d4ead9da5c911af5e12/test/test-pipe-bind-error.c#L175

Looks like errno 86 maps to `ENAMETOOLONG` on AIX.

Looks like this passes as expected on IBM i: 

```ah
ok 199 - pipe_overlong_path
```

https://ci.nodejs.org/job/libuv-test-commit-aix/nodes=aix72-ppc64/2279/console

**Comment by bnoordhuis** [comment]
What is the size of `struct sockaddr_un.sun_path` on AIX?

**Comment by richardlau** [comment]
It looks like `ENAMETOOLONG` is not unexpected then, based on the value of `NAME_MAX`?
`ENAMETOOLONG` is listed as an error in the POSIX documentation for `bind` (so this is not AIX specific behaviour):
https://pubs.opengroup.org/onlinepubs/9699919799/functions/bind.html

> If the address family of the socket is AF_UNIX, then _bind()_ shall fail if:
> ...
> [ENAMETOOLONG]
> The length of a component of a pathname is longer than {NAME_MAX}.

**Comment by richardlau** [comment]
> It seems like AIX is using the `NAME_MAX` to determine what the max file name can be rather than the `saddr.sun_path size`.
> 
> ```shell
> $ getconf NAME_MAX /
> 255
> $ getconf PATH_MAX /
> 1024
> ```
> 

Rereading https://pubs.opengroup.org/onlinepubs/9699919799/functions/bind.html I'm actually now wondering if POSIX allows `PATH_MAX` length paths in `saddr.sun_path` BUT individual components of the path can only be `NAME_MAX` long.

> [ENAMETOOLONG]
> The length of a component of a pathname is longer than {NAME_MAX}.
> ...
> [ENAMETOOLONG]
>The length of a pathname exceeds {PATH_MAX}, or pathname resolution of a symbolic link produced an intermediate result with a length that exceeds {PATH_MAX}.

Could we confirm what happen on AIX if a path is used such that individual components of the path (i.e. between path separators (`/`)) is within `NAME_MAX`?
