### ISSUE TITLE
macOS stat performance

### ISSUE THREAD

**Issue by anonrig** [libuv/libuv#4239]
For reference, I recently saw a tweet mentioning Node.js and Bun stat performance. 

Is there anything possible to improve stat performance in libuv?

Ref: https://x.com/fabiospampinato/status/1727785195686748287?s=46

**Comment by bnoordhuis** [comment]
How do you know it's libuv and not node's binding to it?

**Comment by anonrig** [comment]
> How do you know it's libuv and not node's binding to it?

I don't know. That's why I addressed my question towards any possible optimizations in libuv. If you can give me some hints, I'll be happy to look into it and make my first contribution to libuv.

**Comment by bnoordhuis** [comment]
You should establish where the bottleneck is first. Optimizing libuv is useless - possibly even harmful - if the overhead was on the node side all along.

Write some micro-benchmarks and use a profiler like perf(1) to find out where CPU and wall clock time go to. Once you know that, we can talk about next steps.
