### ISSUE TITLE
Windows consoles with non-default colors

### ISSUE THREAD

**Issue by mcnameej** [libuv/libuv#424]
The ANSI terminal emulation code in src/win/tty.c assumes the console is using Windows default colors (white text on a black background). This results in a somewhat ugly output on consoles using different colors **and** it leaves the console in a bad state, affecting programs that run afterwards.

Note: The problem only occurs after some attempt is made to change the text color; programs that display only plain text are fine.

**Example:**

Everything looks good if the console text is white on black...

![screen shot - black background](https://cloud.githubusercontent.com/assets/173804/8514031/ab228384-2348-11e5-8942-0773913a62c3.png)

...but not so good with other colors (the console was set to bright white on blue in this example)...

![screen shot - blue background](https://cloud.githubusercontent.com/assets/173804/8514033/aeb894de-2348-11e5-97e0-fc48fd92647c.png)

(Note: The error shown in the screen shots is irrelevant; it was was deliberately created to demonstrate the color problem.)

**Comment by piscisaureus** [comment]
PR: #431, fixed in 517ade8.
