### ISSUE TITLE
Assertion failed: new_time >= loop->time, file src\win\core.c

### ISSUE THREAD

**Issue by apirila** [libuv/libuv#4249]
Libuv's event loop crashes due to an assert. This is because QueryPerformanceCounter does not always return a smaller number. For some reason this happens on my system when to PC is connected to a dock. 

The crash is easy to reproduce. I've wrote a test application and it seems the neither QueryPerformanceCounter and rdtsc doesn't always return values in increasing order.

I wrote a test application that checks this:

```C
    for (int i = 0; i < c; i++) {
        r = __rdtsc();

        if (r2 > r) {
            std::cout << "__rdtsc\n";
            std::cout << r2 << "\n";
            std::cout << r << "\n";

        }
        r2 = r;
    }
```

`__rdtsc` is compiled as `rdtsc` instruction. `GetSystemTimeAsFileTime` does is not effected on this issue. Could this behaviour be related to Spectre / Meltdown mitigation?

* **Version**: Node 20.9
* **Platform**: Windows 10, running on VirtualBox. Host machine Windows 11, AMD Ryzen 7 PRO 7840U

**Comment by bnoordhuis** [comment]
See #1633 and its duplicates. This issue has been reported before but it's not a libuv bug.

rdtsc can appear to go back in time when the process is rescheduled onto another core but QPC is immune to that. From [here](https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps#virtualization):

> Is the performance counter monotonic (non-decreasing)?
>
>    Yes. QPC does not go backward.

**Comment by apirila** [comment]
I think that the issue is that QPC doesn't work as documented. This leads to the situation where Node.js based (or other applications using libuv) application can't be reliable on Virtual Machines.

**Comment by bnoordhuis** [comment]
Sure, but you should report that to MS or Oracle.
