### ISSUE TITLE
Raw socket support

### ISSUE THREAD

**Issue by vaguue** [libuv/libuv#4252]
### Discussed in https://github.com/libuv/libuv/discussions/4251

<div type='discussions-op-text'>

<sup>Originally posted by **vaguue** December 16, 2023</sup>
I'm currently developing a Node.js application where I need support for raw sockets across various operating systems. I'm referencing libuv's code for this purpose. This has led me to wonder why libuv doesn't natively support raw sockets. Are there specific limitations or challenges that prevent this functionality from being implemented in libuv? Any insights would be greatly appreciated!

Thank you,
Seva D.</div>

**Comment by bnoordhuis** [comment]
Answered in the discussion thread.

I'll go ahead and close this; there are no plans to support raw sockets. You can integrate them using `uv_poll_t`.
