### ISSUE TITLE
FreeBSD: fs_event_watch_dir test fails

### ISSUE THREAD

**Issue by rhelmot** [libuv/libuv#4255]
```
not ok 62 - fs_event_watch_dir
# exit code 134
# Output from process `fs_event_watch_dir`:
# Assertion failed in test/test-fs-event.c on line 201: `filename == ((void *)0) || strncmp(filename, file_prefix, sizeof(file_prefix) - 1) == 0 != 0` (0 != 0)
```

Fails on 1.47 but succeeds on 1.46. printf debugging indicates that the value of filepath is `watch_dir` and the value of file_prefix is `fsevent-`.

Tested on FreeBSD 14.0.

**Comment by bnoordhuis** [comment]
Likely because of 004dfd2d4b2bc3c3f2ddda7ac72c9dd579ca4194, cc @devnexen.
