### ISSUE TITLE
uv_fs_scandir: support Unix specific files('.' and '..')

### ISSUE THREAD

**Issue by IvanGoncharov** [libuv/libuv#426]
I noticed that `.` and `..` deliberately exclude from scandir results:
https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L323

This cause problem in neovim/neovim/issues/2954
Could `uv_fs_scandir` be extended to support flag which enables listing of platform specific files?
This function already support [flags](https://github.com/libuv/libuv/blob/v1.x/include/uv.h#L1147) could it be used for such purpose?

**Comment by saghul** [comment]
I'm not sure why we have such a filter, maybe because Windows doesn't
include those? At any rate, I'm not opposed to having a flag (opt in,
keeping the default behavior as it is), but it needs to work on all
platforms :-)

**Comment by IvanGoncharov** [comment]
> but it needs to work on all platforms

@saghul Do you mean that I should add `.` and `...` on Windows?

My idea was actually to have a flag something like `SHOW_PLATFORM_SPECIFIC_FILES`.
Which will disable filtering done by  `libuv`.
Windows code doesn't have such filtering, so I just need to implement it Unix code.
Is it right?

**Comment by saghul** [comment]
I just did some git archeology. The current behavior has been consistent since before libuv even existed, because libeio does the same: https://github.com/libuv/libuv/blob/v0.6/src/unix/eio/eio.c#L1888

So, adding a flag now to introduce inconsistent behavior doesn't sound very appealing to me, to be honest.

**Comment by IvanGoncharov** [comment]
IMHO, there are two different compatibility layers:
  1) scandir abstraction from OS level API
  2) file layout abstraction

Right now `uv_fs_scandir` provide both.
But some clients like `neovim`, want only first without the second.
So solution is to make second layer optional.

Does this sound reasonable?

**Comment by IvanGoncharov** [comment]
It should be fairly typical scenario in which

**Comment by bnoordhuis** [comment]
Not really, to be honest.  If you want `.` and `..`, why don't you add them to the results from `uv_fs_scandir()`?  The current behavior is deliberate and stable, you can rely on it staying the same.

**Comment by saghul** [comment]
It's settled then. Closing since it wouldn't be an acceptable change, sorry.

**Comment by IvanGoncharov** [comment]
It should be at least noted in documentation.
Because for me it was complete surprise.

**Comment by saghul** [comment]
@IvanGoncharov sure thing: https://github.com/libuv/libuv/pull/427

**Comment by IvanGoncharov** [comment]
Thanks.
