### ISSUE TITLE
macOS: test udp_multicast_join fails on macOS 13 and above

### ISSUE THREAD

**Issue by mizvekov** [libuv/libuv#4263]
Fails with:
```
not ok 403 - udp_multicast_join
# exit code 6
# Output from process `udp_multicast_join`:
# Assertion failed in test/test-udp-multicast-join.c on line 163: `r == 0` (-8 == 0)
```

Failure happens on udp_set_membership / setsockopt call.

For reference, see: https://github.com/libuv/libuv/actions/runs/7277757514/job/19830481286#step:5:508

**Comment by bnoordhuis** [comment]
It's probably a firewall issue (common issue with the multicast tests) but that -8 error code is kind of odd, that's ENOEXEC.

**Comment by juanarbol** [comment]
I could work on this.

**Comment by bnoordhuis** [comment]
You're welcome to. Do you know what the root cause is?

**Comment by juanarbol** [comment]
No yet... I'm investigating

**Comment by juanarbol** [comment]
I think I found the problem, but I'm not sure why is happening:

```diff
diff --git a/src/unix/udp.c b/src/unix/udp.c
index c2814512..29742136 100644
--- a/src/unix/udp.c
+++ b/src/unix/udp.c
@@ -811,7 +811,7 @@ static int uv__udp_set_membership4(uv_udp_t* handle,
     mreq.imr_interface.s_addr = htonl(INADDR_ANY);
   }
 
-  mreq.imr_multiaddr.s_addr = multicast_addr->sin_addr.s_addr;
+  mreq.imr_multiaddr.s_addr = inet_addr("239.255.255.250");
 
   switch (membership) {
   case UV_JOIN_GROUP:

```

That diff will make the `setsockopt` works, but sure the test runner will hang.

Maybe the problem is in ` uv_ip4_addr(multicast_addr...)` https://github.com/libuv/libuv/blob/7b9e37c7da6730601edbf32f0ae6dae2a17ca03c/src/unix/udp.c#L1060, is the only function touching the `multicast_addr` struct.

Any hints? Or ideas?

**Comment by bnoordhuis** [comment]
The test tries to join the multicast group with address 239.255.0.1.

My best guess is _that_ address is completely blocked off, whereas 239.255.255.250 is available(ish) but not able to send or receive datagrams.

See if starts working when you disable the macos firewall completely.

**Comment by juanarbol** [comment]
I have my firewall disabled, It has been disabled this whole time

**Comment by juanarbol** [comment]
Ok, this is _really weird_; I'm using the next Node.js UDP server

```js
const dgram = require('dgram');

const MULTICAST_ADDR = '224.0.0.4';
const PORT = 1234;

const socket = dgram.createSocket({ type: 'udp4', reuseAddr: true });

socket.on('error', (err) => {
  console.error(`Socket error: ${err}`);
  socket.close();
});

socket.on('listening', () => {
  console.log(`Socket listening on ${socket.address().address}:${socket.address().port}`);
});

socket.on('message', (msg, rinfo) => {
  console.log(`Received message from ${rinfo.address}:${rinfo.port}: ${msg}`);
});

socket.bind(PORT, () => {
  socket.addMembership(MULTICAST_ADDR);
  console.log(`Joined multicast group ${MULTICAST_ADDR}`);
});
```

If I run that, and change the test to use that address, the test passes, normally. Now, If I kill that server and try to run that server again, I get the same `-8` error code that I get in libuv. Anyway, the test won't pass unless a run a UDP server.

**Comment by juanarbol** [comment]
It is a firewall issue.

https://github.com/libuv/libuv/pull/4314#issuecomment-2102064339
