### ISSUE TITLE
tty: flush on exit

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#428]
See https://github.com/nodejs/io.js/pull/1771 for background.  tl;dr non-blocking stdio sometimes loses messages at exit.

It would help if libuv had a way to flush pending stdio writes without processing other I/O.  Strawman:

```c
uv_loop_t *loop = /* ... */;
// ...
uv_run(loop, UV_RUN_DEFAULT);
// ...
uv_tty_flush(loop);
exit(0);
```

Where `uv_tty_flush()`:

1. Scans for open `uv_tty_t` handles,
2. Switches them to blocking mode, and
3. Writes out the pending data.

Issues:

1. How to maintain ordering between writes to stdout and writes to stderr?
2. What to do with messages that contain handles?  Just process as normal?
3. It doesn't help when data is written to the stdio pipe but the reader exits without reading it.
4. io.js exits from signal handlers.  Implementing an async-signal safe `uv_tty_flush()` is complicated and requires atomic operations everywhere data structures are accessed or mutated in libuv.

I can live with us saying "not going to do it" because it's probably possible to accomplish most of the functionality with the current API:

```c++
std::vector<uv_handle_t*> handles;
uv_walk(loop, not_tty_filter, &handles);
for (auto handle : handles) uv_close(handle, nullptr);
uv_run(loop, UV_RUN_DEFAULT);  // Wait for ttys to flush
```

**Comment by danielbprice** [comment]
@Fishrock123 I really hope you are able to land your fix for this.  The behavior clearly violates the documentation, and also common sense and common practice.  Invoking process.exit() is not exiting early or improperly.  The issue is that the stream should be synchronous in the event that it's a TTY and it isn't.  We found this after our upgrade from node 0.10 (where this worked properly) to 0.12 (where it does not).

**Comment by saghul** [comment]
Sorry for the delay, Ben.  My first hunch here would be to leave it up to to the application to handle it. What would we miss if we do it outside of libuv?

**Comment by Fishrock123** [comment]
Any status of this @bnoordhuis?

**Comment by bnoordhuis** [comment]
No status.  I'll close this.

**Comment by Fishrock123** [comment]
@bnoordhuis does @saghul's comment mean this is handle-able in node?

I mean given this silly ongoing stdio-not-flushing on fast process exit thing, if there is something reasonably do-able, I'd like my hand at it.

**Comment by bnoordhuis** [comment]
It should be, although it probably means a lot of dreary moving code around.  One edge case where it won't work is exiting from a signal handler.
