### ISSUE TITLE
Export "selected" CMake target for Libuv

### ISSUE THREAD

**Issue by anthonyalayo** [libuv/libuv#4282]
Can we have a consistent CMake library target exported?

For example with the curl project, if the standard CMake global variable `BUILD_SHARED_LIBS` is set, `LIB_SELECTED` will match accordingly: https://github.com/curl/curl/blob/master/CMakeLists.txt#L155-L159

```
# lib flavour selected for example and test programs.
if(BUILD_SHARED_LIBS)
  set(LIB_SELECTED ${LIB_SHARED})
else()
  set(LIB_SELECTED ${LIB_STATIC})
endif()
```

This is then used as an exported target (in addition to the fixed static/shared targets):
```
add_library(${LIB_NAME} ALIAS ${LIB_SELECTED})
add_library(${PROJECT_NAME}::${LIB_NAME} ALIAS ${LIB_SELECTED})
```

This makes pulling in curl quite clean. In comparison, I have to do the following when using `fetchcontent` with libuv:
```
set(LIBUV_LIBRARY uv_a)
if(BUILD_SHARED_LIBS)
  set(LIBUV_LIBRARY uv)
endif()
```

**Comment by bnoordhuis** [comment]
I don't think there's really any standard to follow, LIB_SELECTED is just something the curl people (curlies?) made up.

Having said that, standards have to start somewhere, so pull request welcome, I guess?

**Comment by anthonyalayo** [comment]
@bnoordhuis how's this? https://github.com/libuv/libuv/pull/4297

I just went with something simple (which is what I have in my own code).
