### ISSUE TITLE
Segment fault when run tty test 

### ISSUE THREAD

**Issue by hiiizxf** [libuv/libuv#4303]
When I run doc/code/tty/main.c, the process was terminated due to a segment  fault.
In doc/code/tty/main.c， the function "uv_write" is called twice, and req with the same address is used.
And then  uv__queue_insert_tail is called twice ，with the same address req->queue, causing some confusion in the stream->write_completed_queue.
It may be necessary to do the deduplication operation before the uv__queue_insert_tail.

* **Version**:  head
* **Platform**: Linux version 6.2.0-39-generic
* run the test as root

**Comment by bnoordhuis** [comment]
Pull request welcome. The libuv book was an external contribution and isn't quite at the same level as the reference documentation.

**Comment by abidjappie** [comment]
I’d like to take a look at this if nobody else has!

**Comment by abidjappie** [comment]
@bnoordhuis I fixed it on my branch (https://github.com/libuv/libuv/compare/v1.x...abidjappie:libuv:docs-tty-segment-fault)
It seems there's already a fix open by the OP, so I guess I shouldn't open a new one. 

Let's get it merged? https://github.com/libuv/libuv/pull/4322
