### ISSUE TITLE
potential perf regeressions due to io_uring `SQPOLL`

### ISSUE THREAD

**Issue by isilence** [libuv/libuv#4308]
`IORING_SETUP_SQPOLL` is an io_uring feature, where the kernel creates a thread, which busily polls the SQ. It appears `libuv` creates an SQPOLL io_uring instance for every single context

https://github.com/libuv/libuv/blob/08a1e7fd23a9b8c893932c1a0083fc703dfe51c0/src/unix/linux.c#L648

There is a high cost associated with it at runtime and also during setup/teardown. It's not recommended to use without precise fine tuning and good sharing as it'd likely backfire.  I'm looking at a perf regression, which I haven't yet confirmed is due to libuv, but it narrows down to someone creating tons of io_uring `SQPOLL` instances (and therefore additional threads) that are not even used. The turnaround is high enough to show up in profiles.

Is it right that every libuv instance would create an SQPOLL io_uring?
If so, it should really be conditional by request from the user.
In what cases it might be unused, i.e. nobody issues any requests to the SQPOLL io_uring instance?

**Comment by bnoordhuis** [comment]
> Is it right that every libuv instance would create an SQPOLL io_uring?

If "instance" means event loop a.k.a. uv_loop_t: yes

>  If so, it should really be conditional by request from the user.

I don't think so. I mean, I might see myself changing it to lazy initialization (create on first uv_fs_t request) but I don't plan on adding any knobs or overrides.

I'd first like to see conclusive evidence that sqpoll is indeed a big bottleneck though. The io_uring support in libuv has been around for a while now and you're the first to bring up setup performance. It can't be that prevalent or we'd have received reports much sooner.

One thing you will want to test is whether it's specific to your kernel. io_uring doesn't have a spotless track record when it comes to bugs and performance, see e.g. #4089. We blacklist a pretty wide range of known-bad kernels but it's definitely not comprehensive.

**Comment by isilence** [comment]
> > Is it right that every libuv instance would create an SQPOLL io_uring?
> 
> If "instance" means event loop a.k.a. uv_loop_t: yes
> 
> > If so, it should really be conditional by request from the user.
> 
> I don't think so. I mean, I could see myself changing it to lazy initialization (create on first uv_fs_t request) but I don't plan on adding any knobs or overrides.

Do all io_uring reads, writes and other fs requests are normally executed by SQPOLL?

> I'd first like to see conclusive evidence that sqpoll is indeed a big bottleneck though. The io_uring support in libuv has been around for a while now and you're the first to bring up setup performance.

Right, better to confirm before throwing in laziness, but defaulting to SQPOLL in generic libraries is a problem in itself. Perhaps there are some smart algorithms and/or conditional usage? but if done naively it'd be easy to craft a case wasting 90%+ of CPU busy polling, e.g. sending one request every half sqpoll_idle. And it's as easy to hit it in real apps with different degrees of waste unless finely tuned for each case, especially when mixing io_uring with epoll (IIUC, fs and net ops). And it's not that easy to spot, artificial benchmarks are not helpful, and with real apps the user needs to monitor cpu util rather than throughput/etc., as they might indeed get a boost but at expense of encumbering another core while thinking that it's free.

> It can't be that prevalent or we'd have received reports much sooner.

The overhead I talk about is under 0.5% of system's total, which still hurts at scale. But to reiterate, this problem is different from the rant above, the SQPOLL is apparently never used to issue any request.

> One thing you will want to test is whether it's specific to your kernel. io_uring doesn't have a spotless track record when it comes to bugs and performance, see e.g. #4089. We blacklist a pretty wide range of known-bad kernels but it's definitely not comprehensive.

I'd encourage to report such issues to io_uring / liburing if not already, it's always addressed and backported when there is a bug. At least I don't remember seeing this one.

**Comment by bnoordhuis** [comment]
> Do all io_uring reads, writes and other fs requests are normally executed by SQPOLL?

A subset (the most common file ops.)

Libuv also uses IORING_OP_EPOLL_CTL but that's a separate sq/cq pair that doesn't use sqpoll.

> I'd encourage to report such issues to io_uring / liburing

I don't remember bugs that were still unfixed but I didn't keep meticulous notes and I'm mostly acting on second-hand information (users reporting issues.)
