### ISSUE TITLE
test: udp_multicast_join, udp_multicast_join6 failed under loongarch64

### ISSUE THREAD

**Issue by fundawang** [libuv/libuv#4310]
* **Version**: 1.48.0
* **Platform**: loongarch64, openAnolis (fedora rawhide based distribution
https://build.openanolis.cn/kojifiles/work/tasks/802/790802/build.log

```
not ok 405 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
not ok 406 - udp_multicast_join6
# timeout
# Output from process `udp_multicast_join6`: (no output)
```

**Comment by fundawang** [comment]
I've increased `UV_TEST_TIMEOUT_MULTIPLIER=20`, but the result went same:
https://build.openanolis.cn/kojifiles/work/tasks/807/790807/build.log

**Comment by santigimeno** [comment]
Most likely this is a firewalld issue. Either you enable multicast traffic or disable it completely.

**Comment by juanarbol** [comment]
This may be related to https://github.com/libuv/libuv/issues/4263
