### ISSUE TITLE
Abstract socket namespace not work for 1.48

### ISSUE THREAD

**Issue by calvin2021y** [libuv/libuv#4312]
* **Version**: v1.48.0
* **Platform**:  linux

```diff
@@ -266,8 +234,11 @@ int uv_pipe_connect2(uv_connect_t* req,
-  if (*name == '\0')
-    addrlen = offsetof(struct sockaddr_un, sun_path) + namelen;
-  else
-    addrlen = sizeof saddr;
-
   do {
-    r = connect(uv__stream_fd(handle), (struct sockaddr*)&saddr, addrlen);
+    r = connect(uv__stream_fd(handle),
+                (struct sockaddr*)&saddr, sizeof saddr);
   }
   while (r == -1 && errno == EINTR);
 
```

why drop addrlen here?

**Comment by santigimeno** [comment]
I'm not sure I understand. I can see the `addrlen` just fine in `v1.48.0`: https://github.com/libuv/libuv/blob/v1.48.0/src/unix/pipe.c#L293-L301

**Comment by calvin2021y** [comment]
sorry for wrong description.

I find after upgrade I get error: "connect(/run/xseccomp1.sock) errno -22, invalid argument"

maybe problem inside uv_pipe_bind2, I will check more.

**Comment by santigimeno** [comment]
If you have a reproducer I'm happy to look

**Comment by calvin2021y** [comment]
confirm is my code not handle namelen correct
