### ISSUE TITLE
Mixed allocator usage with `realpath`

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#4329]
If a custom allocator is used, there is a problem with `realpath(3)` usage: it allocates memory using `malloc`, but we then free it with `uv__free` which may use the custom allocator. This happens in a number of places, for example `uv__fsevents_init`. 

Proposal: have some `uv__realpath` which will do `realpath(src, NULL)`, then `uv__strdup` the result, and last `free(3)` the result.

Thoughts?

* **Version**: Any
* **Platform**: Unix

**Comment by bnoordhuis** [comment]
I can guess the context in which you're opening this issue. https://github.com/saghul/txiki.js/pull/457, right? :)

The extra allocation could be avoided like this:
```diff
diff --git a/src/unix/fs.c b/src/unix/fs.c
index 3a74350f..99d42d4e 100644
--- a/src/unix/fs.c
+++ b/src/unix/fs.c
@@ -2127,6 +2127,13 @@ void uv_fs_req_cleanup(uv_fs_t* req) {
     uv__free(req->bufs);
   req->bufs = NULL;
 
+#if defined(_POSIX_VERSION) && _POSIX_VERSION >= 200809L
+  if (req->fs_type == UV_FS_REALPATH) {
+    free(req->ptr);  /* _Not_ uv__free() */
+    req->ptr = NULL;
+  }
+#endif
+
   if (req->fs_type != UV_FS_OPENDIR && req->ptr != &req->statbuf)
     uv__free(req->ptr);
   req->ptr = NULL;
```

**Comment by saghul** [comment]
> I can guess the context in which you're opening this issue. [saghul/txiki.js#457](https://github.com/saghul/txiki.js/pull/457), right? :)

Pretty much :-)

> The extra allocation could be avoided like this:

Not quite. We have other uses of realpath. The one that hit me first was: https://github.com/libuv/libuv/blob/a7c44d674833e8dec66b8730b5635fcad0f81162/src/unix/fsevents.c#L804

Which can also be fixed in a similar way.

After sleeping on it it's probably ok to just go through and fix the specific instances of this problem. Having a few small allocations on the system allocator is not too bad...
