### ISSUE TITLE
Test failure with 1.48.0 on OSX x86

### ISSUE THREAD

**Issue by SylvainCorlay** [libuv/libuv#4332]
We are seeing a new test failure when [packaging uvloop 1.48.0 on conda-forge](https://github.com/conda-forge/libuv-feedstock/pull/71).

```
2024-02-09T16:02:18.6479160Z ok 91 - fs_poll_ref
2024-02-09T16:02:18.6687650Z not ok 92 - fs_read_bufs
2024-02-09T16:02:18.6778920Z # exit code 6
2024-02-09T16:02:18.6780360Z # Output from process `fs_read_bufs`:
2024-02-09T16:02:18.6782050Z # Assertion failed in test/test-fs.c on line 3212: `446 == uv_fs_read(((void*)0), &read_req, open_req1.result, bufs + 0, 2, 0, ((void*)0))` (446 == 256)

```

**Comment by SylvainCorlay** [comment]
As per the logs, the test failure occurs on OS X x86.

**Comment by bnoordhuis** [comment]
What version of OS X? Per SUPPORTED_PLATFORMS.md, macos < 11 isn't supported.

**Comment by SylvainCorlay** [comment]
We use a recent version of OS X as build platform but buit against rather old MACOS SDK by default (10.9).

Is the SDK Version 11 required? (This seems like a big jump).

**Comment by vtjnash** [comment]
IIRC, this particular macro changed from a runtime detection to a compile-time detection, hence the resulting test failure you notice when compiling with older headers

**Comment by santigimeno** [comment]
> this particular macro changed from a runtime detection to a compile-time detection.

This was also a problem when trying to upgrade libuv for last Node.js 20 release: we couldn't do it because Node.js still supports macos 10.15 (also refs: https://github.com/nodejs/node/pull/51976#issue-2169794672). @bnoordhuis IIRC you were open to bring back support somehow at least until 20.x goes EOL?

**Comment by bnoordhuis** [comment]
Yes. I'll open a pull request. All this back and forth just wastes everyone's time. :)

**Comment by bnoordhuis** [comment]
#4345 - please refresh my memory: does that also apply to pwritev?

**Comment by santigimeno** [comment]
> #4345 - please refresh my memory: does that also apply to pwritev?

I *think* we're ok only with preadv as that's the one they kind of expose via the API.

**Comment by santigimeno** [comment]
> ~~I _think_ we're ok only with preadv as that's the one they kind of expose via the API.~~

That was completely wrong, we need to manually check for pwritev availability too, otherwise it'll fail on old macos. Don't think we need a fallback though because it's not exposed
