### ISSUE TITLE
MSVC compiler bug broke env_vars test in ASAN (x64 windows 2022+asan)

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#4338]
[build-Visual Studio 17 2022-x64-2022-ASAN](https://github.com/libuv/libuv/actions/runs/8122146490/job/22201274962#logs)
```
# exit code -1073740791
# Output from process `env_vars`:
# Assertion failed in D:\a\libuv\libuv\test\test-env-vars.c on line 96: `r == 0` (-4071 == 0)
```
That's this block:
https://github.com/libuv/libuv/blob/625d3d275a4a92fff2408a3e0a7bae6db0dbb200/test/test-env-vars.c#L91-L98
`uv_os_getenv()` failing with UV_EINVAL is a seemingly impossible condition but my hunch is it originates here, since the test is setting the environment variable to the empty string first:
https://github.com/libuv/libuv/blob/625d3d275a4a92fff2408a3e0a7bae6db0dbb200/src/win/util.c#L1283-L1289
~~My hypothesis is that an intermediate operation clobbers the thread-local error value. I have a tentative fix, pull request coming up.~~ - edit: nope, disproved

**Comment by vtjnash** [comment]
I did some investigation locally, and confirmed this is a compiler bug in MSVC introduced in their latest release. Here's the stacktrace when the error message gets incorrectly set:
![image](https://github.com/libuv/libuv/assets/330950/0a8f2fd0-1d22-423b-bec6-d85d3ec69017)

Unfortunately, it seems this is Microsoft bug that is not present in the the open source copy of the code, so I cannot do much more (https://github.com/llvm/llvm-project/tree/main/compiler-rt/lib). I guess we just disable the test?

**Comment by vtjnash** [comment]
Since this encounters a long standing bug report in dotnet and thus also many tools such as powershell, with multiple rejected bugfixes to address it, I assume this case doesn't see a whole lot of testing at Microsoft (e.g. https://github.com/dotnet/runtime/issues/34446, https://github.com/PowerShell/PowerShell/issues/21186)

**Comment by bnoordhuis** [comment]
Huh, I would not have guessed that. Okay, so land #4339 reworded as a cleanup, and disable the test under win32 + asan?

**Comment by vtjnash** [comment]
Sent a bug report to Microsoft: https://developercommunity.visualstudio.com/t/ASAN-clobbers-GetLastError/10610826
