### ISSUE TITLE
android: enable fdsan?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#4369]
https://android.googlesource.com/platform/bionic/+/master/docs/fdsan.md

Detects file descriptor double closes and use-after-close. Only available on Android and only starting with API level 29. We're currently on 24 and we only build tests, we don't actually run them.

An alternative, more cross-platform solution is a LD_PRELOAD/DYLD_PRELOAD shared object that hooks various libc functions. Possibly a useful project in its own right.

**Comment by geeksilva97** [comment]
Hey @bnoordhuis . I started studying libuv source code to understand more about IO in low levels. Even though I'm still a newbie I'd like to try some issues in this nice project.

Would you have any advice for me to start working on this issue?

**Comment by bnoordhuis** [comment]
@geeksilva97 a good first step is to try to get the test suite to run (and pass) on android. The file you're looking for is .github/workflows/CI-unix.yml

**Comment by geeksilva97** [comment]
Hello @bnoordhuis . I could get the emulator running but when I try to run execute tests I got a link error

```
CANNOT LINK EXECUTABLE "/data/local/tmp/build/uv_run_tests": library "libuv.so" not found
```

Here's what I did:

```
          adb push build /data/local/tmp

          adb shell ls -R /data/local/tmp # debugging purposes

          adb shell /data/local/tmp/build/uv_run_tests
```

Files are copied as expected. I can see the `libuv.so` in the `build` folder inside of the emulator. But it can't execute. Would you have a suggestion?

Is there a way - if feasible - we can statically build `uv_run_tests` for Android?

**Comment by geeksilva97** [comment]
> Hello @bnoordhuis . I could get the emulator running but when I try to run execute tests I got a link error
> 
> ```
> CANNOT LINK EXECUTABLE "/data/local/tmp/build/uv_run_tests": library "libuv.so" not found
> ```
> 
> Here's what I did:
> 
> ```
>           adb push build /data/local/tmp
> 
>           adb shell ls -R /data/local/tmp # debugging purposes
> 
>           adb shell /data/local/tmp/build/uv_run_tests
> ```
> 
> Files are copied as expected. I can see the `libuv.so` in the `build` folder inside of the emulator. But it can't execute. Would you have a suggestion?
> 
> Is there a way - if feasible - we can statically build `uv_run_tests` for Android?
> 
> (I'm not that familiar with CMake yet)

Quick update. For `uv_run_tests_a` it executes tests

<img width="536" alt="image" src="https://github.com/user-attachments/assets/0cb25c7f-d2e8-4d76-afa5-509a64312966">

**Comment by bnoordhuis** [comment]
I'd be okay with just running uv_run_tests_a for now, that's already a step up from the status quo.

Failing tests: I'm not surprised. Best would be to investigate on a case-by-case basis whether to fix the test or to skip it; see the RETURN_SKIP macro.

**Comment by geeksilva97** [comment]
> I'd be okay with just running uv_run_tests_a for now, that's already a step up from the status quo.
> 
> Failing tests: I'm not surprised. Best would be to investigate on a case-by-case basis whether to fix the test or to skip it; see the RETURN_SKIP macro.

Sounds good. Will check it.

**Comment by geeksilva97** [comment]
Good news, @bnoordhuis ! Most failures were due to the emulator be READ ONLY. I fixed it and now we have a few left.

The `emfile` test does not work. I wonder if we could skip it for Android as [for `__MVS__` and `__AIX`](https://github.com/libuv/libuv/blob/v1.x/test/test-emfile.c#L46-L52)

![image](https://github.com/user-attachments/assets/5bbf1f32-b6a6-465b-98fb-eceb89bf9f40)

A few TCP tests are failing due a timeout would you have any clue?

![image](https://github.com/user-attachments/assets/d607e422-1b1d-4fd1-9bae-b783fc0d3afa)

Here is the last build for reference: https://github.com/libuv/libuv/actions/runs/10582346314/job/29321801303?pr=4517

**Comment by geeksilva97** [comment]
So, @bnoordhuis @saghul . If we can merge that PR that sets up CI on Android, the next steps would then configure it for API Level 29 (or above) and only then enable the file descriptor sanitizer, correct?

**Comment by geeksilva97** [comment]
Guys. some tests on Android are somewhat flaky. I believe it's due to the emulator's architecture.

When the emulator starts this messages is printed

```
E0926 07:48:30.350660262    2468 socket_utils_common_posix.cc:201] check for SO_REUSEPORT: {"created":"@1727336910.350649231","description":"SO_REUSEPORT unavailable on compiling system","file":"/mnt/tmpfs/src/android/emu-master-dev/external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":169}
```

I'm trying to understand it better. Would you guys have any clue about it?

**Comment by saghul** [comment]
We detect it at compile time, you mean that while it looks like it's supported, it really isn't?

**Comment by geeksilva97** [comment]
> We detect it at compile time, you mean that while it looks like it's supported, it really isn't?

It might be the emulator itself. This message is shown right after the emulator's start.

```
![image](https://github.com/user-attachments/assets/f34c25ac-4be3-4e3e-90f2-4ad14977d5e9)
```

Ref: https://github.com/libuv/libuv/actions/runs/11047839563/job/30689876297

I suspect this is causing tests to interfere with each other. I made some experiments focusing on the tests that usually fail. Executing them isolatedly they work fine.

**Comment by geeksilva97** [comment]
How can I check this?

**Comment by saghul** [comment]
Perhaps hack together the test runner to do a runtime check?

**Comment by geeksilva97** [comment]
> Perhaps hack together the test runner to do a runtime check?

Nice! I will try it out.

**Comment by juanarbol** [comment]
@geeksilva97 Hey! re you still working on this one?

**Comment by geeksilva97** [comment]
> @geeksilva97 Hey! re you still working on this one?

Hi @juanarbol, I haven't looked into it yet—probably only next week. Would you like to try it?

**Comment by juanarbol** [comment]
> Would you like to try it?

Yeap :_). If you think it is ok, I can give u a hand on this one.

**Comment by juanarbol** [comment]
@bnoordhuis I think the tests are being ran.

https://github.com/libuv/libuv/blob/v1.x/.github/workflows/CI-unix.yml#L77
