### ISSUE TITLE
Send udp broadcast to 255.255.255.255 cause permission denied error

### ISSUE THREAD

**Issue by boybeak** [libuv/libuv#4370]
* **Version**: 1.48.0
* **Platform**:MacOS 14.4 (23E214) and Android 10.

Some code like below:
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <uv.h>

static uv_udp_t sender;
static uv_loop_t *loop;

void on_send(uv_udp_send_t *req, int status) {
    if (status < 0) {
        fprintf(stderr, "Send error: %s\n", uv_strerror(status));
    }
    // 清理请求结构体
    free(req);
}

int main() {
    loop = uv_default_loop();

    uv_udp_init(loop, &sender);

    struct sockaddr_in broadcast_addr;
    uv_ip4_addr("255.255.255.255", 3344, &broadcast_addr);

    uv_udp_set_broadcast(&sender, 1);

    uv_udp_send_t *send_req = (uv_udp_send_t*) malloc(sizeof(uv_udp_send_t));
    if (send_req == NULL) {
        fprintf(stderr, "Could not allocate memory for send_req\n");
        return 1;
    }

    char *message = "Hello, UDP broadcast!";
    uv_buf_t buffer = uv_buf_init(message, strlen(message));

    uv_udp_send(send_req, &sender, &buffer, 1, (const struct sockaddr*)&broadcast_addr, on_send);

    uv_run(loop, UV_RUN_DEFAULT);

    uv_close((uv_handle_t*)&sender, NULL);
    uv_loop_close(loop);

    return 0;
}
```
Run the code, prints an error message `Send error: permission denied`. If I change the ip to some other value, it works fine.
But I use kotlin to send a broadcast to 255.255.255.255, It also works fine on the same machine.
I also tried rust to send a udp broadcast, the same error happened. Why the low level languages have the same error?
I have searched for days, it seems no other people meet the problem. I asked ChatGPT, and it gives no valuable answers.

**Comment by bnoordhuis** [comment]
Try calling `uv_udp_bind()` before `uv_udp_set_broadcast()`.  Replacing `uv_udp_init()` with `uv_udp_init_ex(AF_INET)` should work as well.

Plain `uv_udp_init()` doesn't create the socket until first bind/send/receive. The `uv_udp_set_broadcast()` documentation gets that wrong; I'll open a pull request for that.

**Comment by boybeak** [comment]
> Try calling `uv_udp_bind()` before `uv_udp_set_broadcast()`. Replacing `uv_udp_init()` with `uv_udp_init_ex(AF_INET)` should work as well.
> 
> Plain `uv_udp_init()` doesn't create the socket until first bind/send/receive. The `uv_udp_set_broadcast()` documentation gets that wrong; I'll open a pull request for that.

It works.
