### ISSUE TITLE
fs_event_watch_dir test fails on alpine 3.19

### ISSUE THREAD

**Issue by benstadin** [libuv/libuv#4374]
I want to replace the libuv version which sips with alpine linux 3.19, though with the 1.48 source release the test fs_event_watch_dir fails.

**Comment by benstadin** [comment]
To reproduce:
- Environment: Alpine 3.19 Docker image with build tools installed
- Using the following APKBUILD file all tests but the mentioned pass: https://git.alpinelinux.org/aports/tree/main/libuv/APKBUILD
- There is currently no libuv 1.48 package for the current alpine 3.19. This is a security concern for me.

**Comment by bnoordhuis** [comment]
I'm not going to install alpine. What's the error message you got?

**Comment by benstadin** [comment]
No error message. It's just that `make check` report the failed test:

```
make[1]: Leaving directory '/root/libuv-v1.48.0'
make  check-TESTS
make[1]: Entering directory '/root/libuv-v1.48.0'
The libuv test suite cannot be run as root.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5647: check-TESTS] Error 1
make[1]: Leaving directory '/root/libuv-v1.48.0'
```

Even though you said you're not going to install alpine. A really fast way is to docker inside an alpine 3.19 image, install the dependencies mentioned in the APKBUILD file via apk add:

docker run -it alpine:3.19 /bin/sh

**Comment by bnoordhuis** [comment]
It says right there what the problem is....

> The libuv test suite cannot be run as root.
