### ISSUE TITLE
Support `underline` ANSI escape on Windows

### ISSUE THREAD

**Issue by sindresorhus** [libuv/libuv#438]
This is important for consistency between Unix-based systems and Windows in CLI tools.

## Info

https://en.wikipedia.org/wiki/ANSI_escape_code

Windows does support underline using the [Windows-specific way of styling console text](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682088(v=vs.85).aspx#_win32_character_attributes): `COMMON_LVB_UNDERSCORE`

## Test case

```
node -e "console.log('\u001b[4municorn\u001b[24m');"
```

## OS X

<img width="495" alt="screen shot 2015-07-13 at 13 39 02" src="https://cloud.githubusercontent.com/assets/170270/8648845/8ea51ef2-2964-11e5-9a30-70fd1fe6e3ef.png">

*Node.js 0.12.5, OS X 10.10, Terminal.app*

## Windows

<img width="959" alt="screen shot 2015-07-13 at 13 40 19" src="https://cloud.githubusercontent.com/assets/170270/8648864/c6ec5f50-2964-11e5-95b8-d08c81d58d1a.png">

*Node.js 0.12.5, Windows 8.1, cmd.exe*

**Comment by saghul** [comment]
I think this one should be an easy-ish fix. Magic should probably happen here: https://github.com/libuv/libuv/blob/v1.x/src/win/tty.c#L1238

**Comment by Qix-** [comment]
I'll snag these, along with #439 and #440; I added `[7m` and `[?25l`/`[?25h` a while back.

**Comment by saghul** [comment]
@Qix- fantastic, thanks!

**Comment by Qix-** [comment]
Just pointing out this is going to have *very little* support. [LVB flags](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682088(v=vs.85).aspx#_win32_character_attributes) in general aren't supported, and as far as I know are definitely not supported in the default command prompt.

**Comment by Qix-** [comment]
This is actually not possible - ever. [`COMMON_LVB_UNDERSCORE` is for CJK (chinese/japanese/korean) characters](http://www.siao2.com/2005/10/10/478911.aspx).

Sorry @sindresorhus :|

**Comment by sindresorhus** [comment]
:(

**Comment by stevemao** [comment]
#439 and #440 are also not possible?

**Comment by Qix-** [comment]
@stevemao #439 is, #440 is kinda useless, but it is.

**Comment by CherryDT** [comment]
I wonder how this happened then, though: https://github.com/Microsoft/BashOnWindows/issues/2168

**Comment by Qix-** [comment]
@CherryDT The new terminal appears to support underline, but the legacy (pre-windows 10) console do not support underline.

I'm not 100% on this but I think LibUV skips the windows TTY handling (at least for ansi codes) on supporting versions of the new Windows terminal, which means underline should work. Just a guess.
