### ISSUE TITLE
Improper Validation of Certificate Trust in certifi and dependent packages

### ISSUE THREAD

**Issue by haribugbounty** [libuv/libuv#4389]
https://github.com/libuv/libuv/blob/17219b8f39f7cd33472c94214010b603322bd0fa/docs/requirements.txt#L3C1-L3C14.    # Improper Validation of Certificate Trust in certifi and dependent packages

### Description

The vulnerability, known as "Improper Following of a Certificate's Chain of Trust", affects certain versions of the certifi package and its dependent packages, such as requests, Sphinx, and others. The issue is caused by the software not properly validating the trust of the certificates it is using, leading to potential security issues.

### Reproduction Steps

1. Ensure your project is using one of the affected versions of the certifi package, such as 2022.12.7.
2. The vulnerability is introduced through the following dependency paths:
   - `project@0.0.0 › certifi@2022.12.7`
   - `project@0.0.0 › requests@2.28.2 › certifi@2022.12.7`
   - `project@0.0.0 › sphinx@5.3.0 › requests@2.28.2 › certifi@2022.12.7`
   - And similar paths involving other packages that depend on the affected certifi version.
3. The vulnerability allows for potential man-in-the-middle attacks or other security issues due to the software not properly validating the trust of the certificates it is using.

### Impact

The improper validation of the certificate trust can lead to the software trusting and using potentially untrusted or revoked certificates, exposing the system to various security risks, such as eavesdropping, data manipulation, or impersonation attacks.

### Weakness

CWE-297: Improper Validation of Certificate with Host Mismatch

### Vulnerability Identifier

There is no publicly disclosed vulnerability identifier (such as a CVE, GHSA, or HackerOne report) for this specific issue.

### Scoring

**704** (Critical Severity)

### Remediation

To fix the issue, upgrade the `certifi` package to version `2023.7.22` or pin it to that version in your project's dependencies.

**Comment by saghul** [comment]
FTR: that is just a transitive dependency, it's not used for anything by the project.

**Comment by bnoordhuis** [comment]
Should we close this? Non-issue basically, right?

**Comment by saghul** [comment]
I think so yeah.
