### ISSUE TITLE
测试在Windows XP系统上运行时遇到RegGetValueW无法定位于ADVAPI32.dll的问题

### ISSUE THREAD

**Issue by Antruly** [libuv/libuv#4391]
# 项目地址
[VLibuv](https://github.com/Antruly/VLibuv)

# 项目描述
VLibuv是一个C++扩展库，旨在封装libuv的功能，为C++开发者提供更友好、更易用的接口，使得利用libuv构建高性能网络应用变得更加简单和便捷。

# 问题描述

最近，我尝试在Windows XP系统上测试项目VLibuv的运行情况，以确保其在旧版本Windows上的兼容性。然而，在测试过程中遇到了以下错误：
无法定位程序输入点 RegGetValueW 于动态链接库 ADVAPI32.dll

我已经尝试了检查编译选项和环境设置，但仍然无法解决这个问题。我在Windows XP上安装了适当的开发工具和依赖项，并确保了我使用的是合适的编译器和工具链版本。

## 背景信息

- 操作系统：Windows XP
- 编译环境：Visual Studio 2013
- libuv版本：1.33.0
- 编译器：Visual C++
- 其他相关信息：我是为了测试项目在Windows XP系统上的兼容性而遇到了这个问题。

## 复现步骤

1. 克隆项目VLibuv至本地。
2. 使用Visual Studio 2013打开项目。
3. 配置项目以使用Windows XP兼容的SDK和工具集。
4. 尝试在Windows XP系统上运行项目，遇到`RegGetValueW`无法定位于`ADVAPI32.dll`的问题。

## 其他信息

我尝试查找解决方案的线索，但目前还没有找到合适的方法来解决这个问题。是否有任何特定的编译选项或配置步骤，可以确保libuv在Windows XP系统上正常工作？

谢谢您的帮助！

**Comment by saghul** [comment]
Windows XP compatibility was dropped a long time ago.

Your only option is to stick with the last version that works.

**Comment by Antruly** [comment]
> Windows XP compatibility was dropped a long time ago.
> 
> Your only option is to stick with the last version that works.

Thank you for your reply, so which version of XP did the historical version last support

**Comment by Antruly** [comment]
> I don't remember right off the bat but I'm pretty sure it was captured in the changelog, so take a look there.

Okay, I'll go take a look now.
