### ISSUE TITLE
Support `dim` ANSI escape on Windows

### ISSUE THREAD

**Issue by sindresorhus** [libuv/libuv#440]
The `dim` ANSI escape (also known as `faint`) is used to dim the output. The inverse of `bright`.

This is important for consistency between Unix-based systems and Windows in CLI tools.
## Info

https://en.wikipedia.org/wiki/ANSI_escape_code

Unfortunately, this one isn't supported by any Windows API afaik.

I was thinking that it might be possible to just use a dimmer version of the existing foreground/background color, which is easily [calculable](https://css-tricks.com/snippets/javascript/lighten-darken-color/).
## Test case

```
node -e "console.log('\u001b[2municorn\u001b[22m');"
```
## OS X

<img width="493" alt="screen shot 2015-07-13 at 15 25 44" src="https://cloud.githubusercontent.com/assets/170270/8650520/8a651964-2973-11e5-974a-42b815b52fda.png">

_Node.js 0.12.5, OS X 10.10, Terminal.app_
## Windows

<img width="958" alt="screen shot 2015-07-13 at 15 26 50" src="https://cloud.githubusercontent.com/assets/170270/8650532/a06a4bee-2973-11e5-8687-d97efbb8e6a4.png">

_Node.js 0.12.5, Windows 8.1, cmd.exe_

**Comment by Qix-** [comment]
Skeptical on this. The only sequences that would *really* matter are gray and then already-bold (bright) colors.

- `[1;31;2m` -> `[31m`
- `[37;2m` -> `[30;1m` (potentially)
- `[91;2m` -> `[31m`

etc.

**Comment by sindresorhus** [comment]
Not sure exactly what you mean, but it *dims* the color, not just making it gray:

<img width="225" alt="screen shot 2015-07-13 at 16 45 21" src="https://cloud.githubusercontent.com/assets/170270/8652362/975bc45a-297e-11e5-89a2-1eca3a350745.png">

**Comment by Qix-** [comment]
@sindresorhus yes but on Windows there's no great way of doing it. The win32 API has R/G/B bits and then a bright bit. Dim would ultimately just have to bitwise-and-0 the bright bit, as that's really all you can do.

Although when it's `[37m` and dim is specified, we could alternatively do `[30;1m` which gives a "dim" default gray (since windows has black, dark-grey, grey, and then white). But that's optional.

**Comment by sindresorhus** [comment]
Ah, nvm, I forgot Windows doesn't support more than 16 colors...

> Although when it's [37m and dim is specified, we could alternatively do [30;1m which gives a "dim" default gray (since windows has black, dark-grey, grey, and then white). But that's optional.

:+1:

**Comment by Qix-** [comment]
@saghul, does that work?

**Comment by saghul** [comment]
No objections from me. @piscisaureus WDYT?

**Comment by piscisaureus** [comment]
Except for the 'grey' support, I don't see how this could be done on windows.
I have no objections otherwise.

**Comment by Qix-** [comment]
@piscisaureus it'd only affect already-bold codes on windows. `\e[31;1;2m Regular red \e[22m Bold red \e[21m Back to regular red`.

**Comment by piscisaureus** [comment]
go for it

**Comment by bnoordhuis** [comment]
Just to close the loop: I believe this was implemented by #889.

**Comment by Qix-** [comment]
@bnoordhuis Unless I'm mistaken I think that PR was just to support the new Bash on Windows subsystem and cmd.exe that supports ansi codes natively - not supporting older versions of windows that require the console winapi.
