### ISSUE TITLE
Suggestion: write back value of UV_THREADPOOL_SIZE to env

### ISSUE THREAD

**Issue by jorrit** [libuv/libuv#443]
In the future the default or maximum value of `UV_THREADPOOL_SIZE` may change. I suggest writing the value that is used by the library to the environment or making it available in another way so user code can take this into account.

**Comment by saghul** [comment]
Use code should not take this into account, it's an implementation detail. That said, the default will not change until we overhaul the threadpool or make it elastic (see open issues). What are you trying to accomplish?

**Comment by jorrit** [comment]
Thanks for your response.

I was thinking about a solution for an issue with node-sass: sass/node-sass#857. It hits the limit of `UV_THREADPOOL_SIZE` in some cases, so the implementation detail is in fact becoming something that the programmers at the javascript level are going to make assumptions about and take into account in their code.

I can imagine JS code to limit itself based on the actual value of `UV_THREADPOOL_SIZE` and have code like `max = Math.min(128, UV_THREADPOOL_SIZE || 4)`. To prevent this code to have to hard-code `128` and `4` and the calculation itself, I thought it would be a useful addition to expose the actual value of `UV_THREADPOOL_SIZE`. But this is all hypothetical.

**Comment by bnoordhuis** [comment]
I imagine that once we have an elastic threadpool, libuv will grow APIs to set the min and max size at run-time and io.js / node.js will in turn expose that to JS land.

**Comment by saghul** [comment]
Closing, @jorrit please feel free to leave a comment / track https://github.com/libuv/libuv/pull/382.

**Comment by jorrit** [comment]
Alright, thanks!
