### ISSUE TITLE
Missing symbols in the library file compared to the headers

### ISSUE THREAD

**Issue by dod38fr** [libuv/libuv#4436]
* **Version**: 1.48.0
* **Platform**: Linux 6.8.11-amd64  SMP PREEMPT_DYNAMIC Debian 6.8.11-1 (2024-05-26) x86_64 GNU/Linux

Hi

A debian user is reporting the following issue (see [Debian bug 1073595](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1073595)):

> While updating the ocaml-luv package, I stumbled upon missing symbols
> for uv_wtf8_length_as_utf16, uv_wtf8_to_utf16, uv_utf16_length_as_wtf8
> and  uv_utf16_to_wtf8.
> 
> After some poking around, they are declared in /usr/include/uv.h, but
> using objdump -T on /usr/lib/x86_64-linux-gnu/libuv.so.1.0.0 doesn't
> show them.
>
> So it looks like there's something wrong with the libuv1t64 package.

I don't know what to answer.

Could you shed some light ?

All the best

Dod (for Debian)

**Comment by bnoordhuis** [comment]
The comment in uv.h explains it:
```
/* String utilities needed internally for dealing with Windows. */
```
That's why they're not marked UV_EXTERN (a.k.a. `__attribute__((visibility("default")))`)

They should probably be in an internal header. Not sure why they're in uv.h. @vtjnash?

**Comment by vtjnash** [comment]
The lack of annotation was an oversight. While used internally by libuv, any external library should also be using them to correctly access libuv (if needing to do similar conversions on libuv data, such as correctly and safely interpreting system error codes returned by libuv), and to not use previous, incomplete and thus non-compliant algorithms such as that provided by Windows for this conversion

**Comment by saghul** [comment]
Should we ifdef them out on non-windows platforms then?

**Comment by bnoordhuis** [comment]
No, they're present everywhere, they live in src/idna.c. I'll open a PR to export them properly.
