### ISSUE TITLE
Issue with GetSystemTimePreciseAsFileTime on Windows Server 2008 in libuv 1.48.0 and Suggested Fix

### ISSUE THREAD

**Issue by linjifan** [libuv/libuv#4438]
Hello,

I encountered an issue while using the libuv library version 1.48.0 on Windows Server 2008. During runtime, an error message appears stating "Entry Point Not Found: GetSystemTimePreciseAsFileTime." After analyzing the code, I found that the issue lies in the uv_clock_gettime() function within the util.c file. This function uses GetSystemTimePreciseAsFileTime(), which is not supported on Windows Server 2008.

To ensure compatibility with Windows Server 2008, I suggest adding a check for the operating system version in the code: use GetSystemTimePreciseAsFileTime() on Windows 8 or Windows Server 2012 and later versions, and use GetSystemTimeAsFileTime() on earlier versions.

Here is my modified code, which has been tested successfully on Windows Server 2008:
```
int is_windows_8_or_greater() {
  OSVERSIONINFOEXW osvi;
  DWORDLONG conditionMask = 0;

  ZeroMemory(&osvi, sizeof(OSVERSIONINFOEXW));
  osvi.dwOSVersionInfoSize = sizeof(OSVERSIONINFOEXW);
  osvi.dwMajorVersion = 6;
  osvi.dwMinorVersion = 2;

  VER_SET_CONDITION(conditionMask, VER_MAJORVERSION, VER_GREATER_EQUAL);
  VER_SET_CONDITION(conditionMask, VER_MINORVERSION, VER_GREATER_EQUAL);

  return VerifyVersionInfoW(&osvi, VER_MAJORVERSION | VER_MINORVERSION, conditionMask);
}

int uv_clock_gettime(uv_clock_id clock_id, uv_timespec64_t* ts) {
  FILETIME ft;
  int64_t t;

  if (ts == NULL)
    return UV_EFAULT;

  switch (clock_id) {
    case UV_CLOCK_MONOTONIC:
      uv__once_init();
      t = uv__hrtime(0 /* UV__NANOSEC */);
      ts->tv_sec = t / 1000000000;
      ts->tv_nsec = t % 1000000000;
      return 0;
    case UV_CLOCK_REALTIME:
      if (is_windows_8_or_greater()) {
        GetSystemTimePreciseAsFileTime(&ft);
      } else {
        GetSystemTimeAsFileTime(&ft);
      }
      /* In 100-nanosecond increments from 1601-01-01 UTC because why not? */
      t = ((int64_t)ft.dwHighDateTime << 32) | ft.dwLowDateTime;
      /* Convert to UNIX epoch, 1970-01-01. Still in 100 ns increments. */
      t -= 116444736000000000ll;
      /* Now convert to seconds and nanoseconds. */
      ts->tv_sec = t / 10000000;
      ts->tv_nsec = (t % 10000000) * 100;
      return 0;
  }

  return UV_EINVAL;
}
```
I hope you find my suggestion helpful, and thank you for your hard work!

Best regards,
[linjifan]

**Comment by saghul** [comment]
Windows Server 2008 is no longer supported by libuv: https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md#supported-platforms

**Comment by nicolasnoble** [comment]
Semi-necro on this one, because I've been pointed at it by someone else, so there's some tracking on this, but the proposed change wouldn't work: it needs to dynamically import the symbol instead from Kernel32.dll, which would be more involved than just doing a simple if.
