### ISSUE TITLE
CMake build fails with FetchContent

### ISSUE THREAD

**Issue by tinkerbeast** [libuv/libuv#4439]
* **Version**:  v1.48.0
* **Platform**: Ubuntu 24.04 (Linux 6.8.0-35-genericUbuntu SMP PREEMPT_DYNAMIC x86_64 GNU/Linux)

### Issue
My CMake config is:
```
FetchContent_Declare(libuv
	URL "https://github.com/libuv/libuv/archive/refs/tags/v1.48.0.tar.gz"
)
FetchContent_MakeAvailable(libuv)
add_executable(uv_main ${CMAKE_CURRENT_SOURCE_DIR}/uv_main.c)
target_link_libraries(uv_main PUBLIC libuv::libuv)
```
When trying to build cmake configuration, I get the following error:
```
CMake Error at CMakeLists.txt:28 (target_link_libraries):
  Target "uv_main" links to:

    libuv::libuv

  but the target was not found.  Possible reasons include:
```

I clearly see that the alias target exists in the CMakeLists.txt file. What is going wrong?

**Comment by saghul** [comment]
Maybe this fixes that? https://github.com/libuv/libuv/commit/7b9e37c7da6730601edbf32f0ae6dae2a17ca03c

**Comment by bnoordhuis** [comment]
No follow-up, closing.
