### ISSUE TITLE
the child process (forked from parent process which use libuv) crash with abort() called 

### ISSUE THREAD

**Issue by ptnoodles** [libuv/libuv#4443]
A child process is forked from main process which use libuv to perform some IOs.

When the child process exits, the uv_library_shutdown is called since it has attribute destructor.

```
#if defined(__GNUC__) && !defined(_WIN32)
__attribute__((destructor))
#endif
```

uv__threadpool_cleanup is invoked in uv_library_shutdown. 
 in uv__threadpool_cleanup () at libuv/src/src/threadpool.c:179
```
178   for (i = 0; i < nthreads; i++)
179     if (uv_thread_join(threads + i))
180       abort();
```

The abort() is called because threads doesn't exists for child process.

* **Version**: 1.45
* **Platform**:  Linux sc2-10-186-96-16.eng.vmware.com 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vtjnash** [comment]
Since libuv is a multithreaded library, most documentation for `fork` will typically state that executing anything but execv is undefined behavior in the child process. There is some limited support via uv_loop_fork to support some continued operation, but it is not generally supported.

**Comment by ptnoodles** [comment]
Hi vtjnash, thanks for comments.
My use case is quite simple to fork (with fork()) a child process (no execv).
It looks like reasonable to just make uv_library_shutdown called by SDK user.

**Comment by vtjnash** [comment]
To reiterate, the documentation for `fork` points out that even continuing to use libc is not safe:
```
*  After a fork() in a multithreaded program, the child can safely call only async-signal-safe functions (see signal-safety(7)) until such time as it calls execve(2).
```
The libuv library may take some efforts to make some trivial programs work, but any non-trivial program, which uses libc, is already not safe after fork to do anything except execv

**Comment by ptnoodles** [comment]
thanks for further comments.
