### ISSUE TITLE
The uv__run_idle and uv__run_prepare stages of event loop are unclear

### ISSUE THREAD

**Issue by dSalieri** [libuv/libuv#4458]
Until now, nowhere and no one has explained what exactly the **idle/prepare** stage does; node.js generally says that: [only used internally](https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick#phases-overview). Still, I would like a clearer explanation of these steps. I would like to know the purpose of these two operations, in a clearer manner, with an explanation for what and why. I think it will not be difficult for libuv developers to explain the key purpose of these operations with probable examples (if they are applicable).

And in general, if you remove calls to the `uv__run_idle` and `uv__run_prepare` operations in `uv__run` , will the node.js environment not work correctly? How important are these operations when running a node.js program?

I’m asking this here because I’m not sure that anywhere they can answer the question regarding the implementation of libuv.

**Comment by saghul** [comment]
Take a look here: https://docs.libuv.org/en/v1.x/design.html

**Comment by dSalieri** [comment]
@saghul Yes, I read it, it’s a little better, but it’s still unclear when these operations work, what exactly they do.

> 5. Idle handle callbacks are called. Despite the unfortunate name, idle handles are run on every loop iteration, if they are active.
>6. Prepare handle callbacks are called. Prepare handles get their callbacks called right before the loop will block for I/O.

Any examples? How do these operations interact with the event loop? I would like to hear an explanation and examples in a language accessible to a non-libuv developer.

**Comment by bnoordhuis** [comment]
Closing in favor of https://github.com/libuv/libuv/discussions/4462 (questions go into Discussions, issues are for bug reports and feature requests.)
