### ISSUE TITLE
[RFC]threadpool: send notify signal to consumer only when queue is empty

### ISSUE THREAD

**Issue by chenttuuvv** [libuv/libuv#446]
In one of our server box, we notice that large amounts of cpu were consumed by libc function pthread_signal, which can be back traced to post()@threadpool.c. In order to make the producer/consumer implementation more symmetric, should we only send pthread signal to cosumer only when queue is empty? If yes, please let me send a PR.

**Comment by saghul** [comment]
That would not work (unless you requrite how work is queued, that is). We use `uv_cond_signal` to signal worker threads that work has been added to the queue, and thus they can consume it.

That said, feel free to experiment and send a PR with your improvements, if they enhance the current behavior while keeping the semantincs. Thanks!

**Comment by chenttuuvv** [comment]
worker wait for signal only when queue is empty, this mean we should send signal to them only when queue is empty, otherwise cpu cycle is wasted. Why this whould not work?

**Comment by saghul** [comment]
Doh, my bad, I was reading the code wrong there, apologies. Looke like it could indeed be improved, since we do hold the global mutex in post, so we could signal the condition only if the queue was empty before we inserted the item. Feel free to send a PR and I'll look at it.
