### ISSUE TITLE
unix: uv_udp_open invalid 

### ISSUE THREAD

**Issue by wangshangxiu** [libuv/libuv#4460]
After call some api  uv_udp_* with uv__udp_maybe_bind inner, it may create a new udp socket and random bind in unix platform.  It seems that uv__udp_maybe_bind ask conditon (handle->socket != INVALID_SOCKET), but api uv_udp_open has different implement between unix and win. 

### UNIX:
int uv_udp_open(uv_udp_t* handle, uv_os_sock_t sock) {
  int err;

  /* Check for already active socket. */
  if (handle->io_watcher.fd != -1)
    return UV_EBUSY;

  if (uv__fd_exists(handle->loop, sock))
    return UV_EEXIST;

  err = uv__nonblock(sock, 1);
  if (err)
    return err;

  err = uv__set_reuse(sock);
  if (err)
    return err;

  ### handle->io_watcher.fd = sock;
  if (uv__udp_is_connected(handle))
    handle->flags |= UV_HANDLE_UDP_CONNECTED;

  return 0;
}

### WINDOWS:
int uv_udp_open(uv_udp_t* handle, uv_os_sock_t sock) {
  WSAPROTOCOL_INFOW protocol_info;
  int opt_len;
  int err;

  /* Detect the address family of the socket. */
  opt_len = (int) sizeof protocol_info;
  if (getsockopt(sock,
                 SOL_SOCKET,
                 SO_PROTOCOL_INFOW,
                 (char*) &protocol_info,
                 &opt_len) == SOCKET_ERROR) {
    return uv_translate_sys_error(GetLastError());
  }

###   err = uv__udp_set_socket(handle->loop,
                           handle,
                           sock,
                           protocol_info.iAddressFamily);
  if (err)
    return uv_translate_sys_error(err);

  if (uv__udp_is_bound(handle))
    handle->flags |= UV_HANDLE_BOUND;

  if (uv__udp_is_connected(handle))
    handle->flags |= UV_HANDLE_UDP_CONNECTED;

  return 0;
}

**Comment by saghul** [comment]
Not sure I understand the question.

If you want to use an external fd as a UDP handle you need to use uv_udp_open first.

**Comment by bnoordhuis** [comment]
I'm going to assume this has been answered but let me know if there's reason to reopen.

**Comment by wangshangxiu** [comment]
> I'm going to assume this has been answered but let me know if there's reason to reopen.



> Not sure I understand the question.
> 
> If you want to use an external fd as a UDP handle you need to use uv_udp_open first.

Yes, the problem happend to here .  While we have a external fd , it means that we have just created a udp sockect ，  but using uv_udp_open , it will make a new upd socket !
