### ISSUE TITLE
I'm going to assume this has been answered but let me know if there's reason to reopen.

### ISSUE THREAD

**Issue by wangshangxiu** [libuv/libuv#4463]
I'm going to assume this has been answered but let me know if there's reason to reopen.

_Originally posted by @bnoordhuis in https://github.com/libuv/libuv/issues/4460#issuecomment-2241582571_

**Comment by wangshangxiu** [comment]
Yes, the problem happend to here . While we have a external fd , it means that we have just created a udp sockect ， but using uv_udp_open , it will make a new upd socket !

**Comment by saghul** [comment]
Please paste some sample code showing what you are doing.

**Comment by wangshangxiu** [comment]
> Please paste some sample code showing what you are doing.


int UvUdpClient::ResetLoop(uv_loop_t* loop) {
	uv_os_fd_t fd;
	int result = uv_fileno((const uv_handle_t*)&m_client, &fd);
	if (0 == result) {
		result = uv_udp_init(loop, (uv_udp_t*)&m_client);
		if (result == 0) {
			result = uv_udp_open((uv_udp_t*)&m_client, (uv_os_sock_t)fd);
			uv_handle_set_data((uv_handle_t*)&m_client, this);
			result = uv_udp_connect(&m_client, &m_remoteAddr);
		}
	}
	return result;
}

**Comment by saghul** [comment]
2 observations:

- You cannot take the fd out of a handle and use it in another, that will assert on Unix and it's not supported.

- You can make sure no socket is created before open by using uv_udp_init_ex and passing AF_UNSPEC in the flags field.

**Comment by wangshangxiu** [comment]
> 2 observations:
> 
> * You cannot take the fd out of a handle and use it in another, that will assert on Unix and it's not supported.
> * You can make sure no socket is created before open by using uv_udp_init_ex and passing AF_UNSPEC in the flags field.

Thanks.   Another question,  can I take the fd out of a handle and use it in another on Windows?

**Comment by saghul** [comment]
No, it cannot be used like that.

It might work on Windows, but it will crash on Unix.

It is not supported.

**Comment by saghul** [comment]
I guess the question is: if you already have a libuv UDP handle, why do you need to create another UDP handle?

**Comment by wangshangxiu** [comment]
> I guess the question is: if you already have a libuv UDP handle, why do you need to create another UDP handle?

I move it to another thread when program need.

**Comment by saghul** [comment]
> > I guess the question is: if you already have a libuv UDP handle, why do you need to create another UDP handle?
> 
> 
> 
> I move it to another thread when program need. 

Then you can send the handle over an IPC pipe handle. That will take care of the internal logistics.

**Comment by wangshangxiu** [comment]
> IPC

Oh, It's a good way.Thanks for your help , @saghul, @santigimeno .I think I know how to deal my problem with your tips.

**Comment by bnoordhuis** [comment]
Closing as answered.
