### ISSUE TITLE
aix: fs_* tests are failing

### ISSUE THREAD

**Issue by abmusse** [libuv/libuv#4483]
* **Version**: v1.x 
* **Platform**: AIX 

ref: https://ci.nodejs.org/job/libuv-test-commit-aix/nodes=aix72-ppc64/2401/console

```text
not ok 62 - fs_event_watch_delete_dir
# exit code 393222
# Output from process `fs_event_watch_delete_dir`:
# Assertion failed in test/test-fs-event.c on line 155: `events == UV_RENAME` (2 == 1)

not ok 97 - fs_posix_delete
# exit code 393222
# Output from process `fs_posix_delete`:
# Assertion failed in test/test-fs.c on line 1087: `r == UV_ENOTEMPTY` (-17 == -87)

not ok 99 - fs_read_dir
# exit code 393222
# Output from process `fs_read_dir`:
# Assertion failed in test/test-fs.c on line 512: `req->result == 0` (-17 == 0)

not ok 104 - fs_readdir_non_empty_dir
# exit code 393222
# Output from process `fs_readdir_non_empty_dir`:
# Assertion failed in test/test-fs-readdir.c on line 356: `r == 0` (-17 == 0)

not ok 113 - fs_stat_batch_multiple
# exit code 393222
# Output from process `fs_stat_batch_multiple`:
# Assertion failed in test/test-fs.c on line 4616: `r == 0` (-17 == 0)

not ok 117 - fs_symlink_dir
# exit code 393222
# Output from process `fs_symlink_dir`:
# r == 0
# Assertion failed in test/test-fs.c on line 2459: `2 == r` (2 == 3)
```

**Comment by richardlau** [comment]
This starts failing after 18266a69696349e9641871f55b88ad6e732a8789
- https://ci.nodejs.org/job/libuv-test-commit-aix/2411/nodes=aix72-ppc64/console with 18266a69696349e9641871f55b88ad6e732a8789
- https://ci.nodejs.org/job/libuv-test-commit-aix/2410/nodes=aix72-ppc64/console with 0c36b16d1b4c14ebc910b2de0112a258c01cf720 (the preceding commit) only fails pipe_overlong_path (which was later addressed by https://github.com/libuv/libuv/pull/4442)

At first glance it would suggest the new `fs_posix_delete` test fails and leaves the `test_dir` in a state that interferes with subsequent tests.

`fs_event_watch_delete_dir` was added later by badecdca14d30fbfea655b7d4b18bdb4b3518c5d and fails in https://ci.nodejs.org/job/libuv-test-commit-aix/2411/nodes=aix72-ppc64/console run against that commit.

**Comment by richardlau** [comment]
PR to update the tests: https://github.com/libuv/libuv/pull/4494
