### ISSUE TITLE
Write after ECONNRESET crash.

### ISSUE THREAD

**Issue by moteus** [libuv/libuv#45]
I write [Lua binding](https://github.com/moteus/lua-lluv) to libuv.
[Server](https://github.com/moteus/lua-lluv/blob/master/test/luasocket/ts.lua) just accept socket and close it. For this I use basic socket library(not libuv)

``` Lua
while true do
  local control = server:accept()
  control:close()
end
```

[Client](https://github.com/moteus/lua-lluv/blob/master/test/luasocket/tt.lua) just connect to server and call uv_write until it get error result or callback status.

``` Lua
local uv = require "lluv"

local host = host or "127.0.0.1"
local port = port or "8383"

local function write(s, data, cb)
  local ok, err = s:write(data, cb)
  if not ok then cb(s, err) end
  return true
end

local i = 1
local function on_write(cli, err)
  if err then
    print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
    print(cli, err)
    print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
    return
  end
  print("Write #" .. i .. " done.")
  i = i + 1
  write(cli, "hello", on_write)
end

uv.tcp():connect(host, port, function(cli, err)
  if err then
    cli:close()
    assert(false, tostring(err))
  end
  write(cli, "hello", on_write)
end)

uv.run()
```

This test case works on Windows but on Linux Mint 15 or on Travis it could just crash with error code 141. But some times it pass.
Also it crash every time if I try write after uv_write return ECONNRESET(on Linux not on Windows)
On windows I just get same error each time.

**Comment by vcunat** [comment]
For reference, this is [documented in the guide](http://docs.libuv.org/en/v1.x/guide/filesystem.html?highlight=SIGPIPE) &ndash; maybe it's a bit confusing that it's mentioned in the "filesystem" section, as you may get the same problem for network streams as well, but at least it's mentioned.
