### ISSUE TITLE
Compilation failure with current v1.x on DragonFly BSD; v1.48.0 release is working

### ISSUE THREAD

**Issue by johnsonjh** [libuv/libuv#4533]
Currently, when targeting DragonFly BSD (actually, cross-compilation from an IBM AIX machine using Clang 18.1.8 for target=x86_64-unknown-dragonfly, but the same failure occurs when building natively), libuv current v1.x fails to build.

There is no failure when building the v1.48.0 release.

The error is:

```c
In file included from src/unix/freebsd.c:29:
In file included from .../sysroot/usr/include/sys/user.h:75:
In file included from .../sysroot/usr/include/sys/proc.h:57:
.../sysroot/usr/include/sys/eventvar.h:60:17: error: field has incomplete type 'struct kqinfo'
   60 |         struct          kqinfo kq_kqinfo;       
      |                                ^
.../sysroot/usr/include/sys/eventvar.h:60:10: note: forward declaration of 'struct kqinfo'
   60 |         struct          kqinfo kq_kqinfo;       
      |                         ^
In file included from src/unix/freebsd.c:29:
In file included from .../sysroot/usr/include/sys/user.h:75:
.../sysroot/usr/include/sys/proc.h:281:15: error: field has incomplete type 'struct klist'
  281 |         struct klist    p_klist;        /* knotes attached to this process */
      |                         ^
.../sysroot/usr/include/sys/filedesc.h:66:8: note: forward declaration of 'struct klist'
   66 | struct klist;
      |        ^
2 errors generated.
```

While I understand that DragonFly BSD (a relative of FreeBSD) isn't *officially* supported, mainline current libuv has always built successfully on it, at least up until this point.

I'll try to find some time soon and bisect the "bad" commit and propose a workaround.

**Comment by bnoordhuis** [comment]
Note that we cut releases from the v1.x branch, not master.

Master is what someday may become libuv v2 - if we don't stick with v1.x forever, that is.

**Comment by johnsonjh** [comment]
@bnoordhuis I misspoke - it is the v1.x branch.

I've modified the report appropriately.

A quick fix seems to be:

```diff
diff --git a/src/unix/freebsd.c b/src/unix/freebsd.c
index 191bc8b..cabe9e3 100644
--- a/src/unix/freebsd.c
+++ b/src/unix/freebsd.c
@@ -19,21 +19,26 @@
  */
 
 #include "uv.h"
 #include "internal.h"
 
 #include <assert.h>
 #include <string.h>
 #include <errno.h>
 
 #include <paths.h>
+#if defined(__DragonFly__)
+#include <sys/event.h>
+#include <sys/kinfo.h>
+#else
 #include <sys/user.h>
+#endif
 #include <sys/types.h>
 #include <sys/resource.h>
 #include <sys/sysctl.h>
 #include <vm/vm_param.h> /* VM_LOADAVG */
 #include <time.h>
 #include <stdlib.h>
 #include <unistd.h> /* sysconf */
 #include <fcntl.h>
 
 #ifndef CPUSTATES
```

I will verify that it works on 6.4.0-RELEASE and 6.5-SYNTH (current) shortly.

**Comment by johnsonjh** [comment]
@bnoordhuis Tested and confirmed that this works and allows clean compilation on both CURRENT and last RELEASE.

Would you like a PR?

**Comment by santigimeno** [comment]
Please do

**Comment by johnsonjh** [comment]
@santigimeno 

PR at https://github.com/libuv/libuv/pull/4534
