### ISSUE TITLE
Ability to Retain file in constrained cache by adding `dup`

### ISSUE THREAD

**Issue by ackava** [libuv/libuv#4549]
I have seen this https://github.com/libuv/libuv/issues/3448, and here is the use case which is preventing me from creating disk cache for remote file storage.

All files are hosted on remote storage such as s3, blobs etc. And let's say I am using `/cache/` mount somewhere on disk to cache remote files locally. Now files regularly used will be downloaded to cache, cache will be smaller, like few GBs, where else remote storage is in TBs. Purpose of this cache is to retain files on reboot/restart. As files will be larger.

Cache would require regular cleaning. tmpfs isn't ideal as everything is deleted on restart of container or os reboot.

To use file, if file exists in `/cache/` folder, file has to copy entire file from `/cache/` to `/tmp/`, because cache cleaning process will delete old files to keep cache to an optimum size.  We cannot create hard link between `/cache/` and tmpfs. So there is risk of file being deleted while file handle is not opened. There is no way to lock file on Unix/Linux systems like on Windows.

Every time we want to open file from cache, cache copy has to be copied to tmpfs. This is huge time consuming process. And using single handle is not possible for different operation, for example one is extracting metadata from image, one is resizing it etc and they may run it in parallel. And there is a separate OCR engine that needs file or file handle as well.

Now if there is `dup` available, what we can do is, we can open a file and keep the handle till lifetime of the usage of file, and every other logic that needs to access the same file, can duplicate the handle and read from it.

So in that case if cache eviction happens, original file will still be available till the last handle is closed.

Renaming and keeping a separate hard link workarounds do not guarantee atomicity. If process/system fails/crashes, the hardlink will survive and writing logic to cleaning up hardlinks will impose similar constraints.

Using last use time is also not feasible as due to async nature of nodejs, it is not possible to guarantee that cache retrieval will win in race against cache eviction in multi process environment.

Currently I am using small database like sqlite to manage cache but I feel lack of `dup` is posing challenge to write many file level locking logic.

**Comment by bnoordhuis** [comment]
Can you explain in a few words why `uv_fs_open()` won't work for your use case? Rephrased: how is opening the file twice worse than cloning the file descriptor?

> I feel lack of dup is posing challenge to write many file level locking logic

I don't know what you understand "file level locking" to mean but dup() and flock/fcntl/lockf-style file locking is a _huge_ footgun. It's so broken it's near impossible to get it right.

Besides file locking, I'd argue dup() is also worse most of the time because it clones the file _descriptor_ but not the file _description_ (note the emphasis.)

That means both file descriptors share the same file offset - reading from one changes the offset of the other one - and that's rarely what you want.

It's definitely not what most people expect because it's one of those perennial UNIX pitfalls that keep tripping up new programmers.

**Comment by ackava** [comment]
@bnoordhuis This is interesting, I wasn't aware of offset being the same. Isn't there any way to duplicate file handle?

1. Process one opens a file handle.
2. Process two deletes the file.
3. Process one can read the file.
4. Process one should be able to duplicate the file handle and give it to process three which can read from beginning?

Is it possible? or not at all possible?

**Comment by bnoordhuis** [comment]
Like I said, one of those perennial pitfalls :-)

You can't do it in a portable manner. Opening `/proc/self/fd/<num>` works for most (but not all) file types but is Linux-only.

I'm going to close this out but I can convert it to a discussion if you have follow-up questions.
