### ISSUE TITLE
Test failure on armv7l GNU/Linux

### ISSUE THREAD

**Issue by hendrikdonner** [libuv/libuv#4550]
* **Version**: 1.49.0
* **Platform**: armv7l GNU/Linux

I see new test failures in 1.49.0:

```
not ok 96 - fs_read_bufs
# exit code 134
# Output from process `fs_read_bufs`:
# Assertion failed in test/test-fs.c on line 3206: `446 == uv_fs_read(((void *)0), &read_req, open_req1.result, bufs + 0, 2, 0, ((void *)0))` (446 == -22)
...
not ok 120 - fs_write_alotof_bufs_with_offset
# exit code 134
# Output from process `fs_write_alotof_bufs_with_offset`:
# Assertion failed in test/test-fs.c on line 3563: `r >= 0` (-22 >= 0)
not ok 121 - fs_write_multiple_bufs
# exit code 134
# Output from process `fs_write_multiple_bufs`:
# Assertion failed in test/test-fs.c on line 3328: `r >= 0` (-22 >= 0)
...
```
So a few `EINVAL`. First release i see those in.

According to git bisect it's because of cc23e204d76688053c63fd1698435bc4b68aab6a. Reverting that commit fixes the testsuite.

**Comment by hendrikdonner** [comment]
I'm on gcc 14.2 to add to the statistic.

**Comment by santigimeno** [comment]
Can you try if any of the options proposed there work?

**Comment by hendrikdonner** [comment]
So the `memcpy` fix is in `v1.49.0` and obviously doesnt' work, the `memory_order_seq_cst` attempt does not work for me, neither does the `volatile` function pointer i'm afraid.

**Comment by hendrikdonner** [comment]
Has this been reported to gcc?

**Comment by bnoordhuis** [comment]
Not by me, I couldn't get a working small reproducer.
