### ISSUE TITLE
uv_pipe_bind always fails with EACCESS on Windows 8.1

### ISSUE THREAD

**Issue by Tulrath** [libuv/libuv#458]
It looks like the lpName parameter for CreateNamedPipe() specifically requires that the pipe name be in the format **"\\\\.\pipe\pipename"** (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365150(v=vs.85).aspx).  However, it doesn't appear as though this format is being detected or enforced in pipe.c.  This seems to create a "Catch-22."

When attempting to use "r = uv_pipe_bind(&server, "echo.sock"), it always throws a EACCESS error, and when attempting to use "r = uv_pipe_bind(&server, "\\\\.\pipe\pipename"), it compiles, but also throws an error when run.

**Comment by saghul** [comment]
What do you expect libuv to do? I don't really understand the report. You can specify the pipe name you want, if it's bogus an error will be produced, as you can see. Same as if you try to bind to /path/that/does/not/exist on Unix.

Pipes on Windows are represented by those names, we cannot make them consistent.

**Comment by Tulrath** [comment]
What this means is, as a developer, I have to do something like this:

#ifdef _WIN32
string pathname = "\\\\.\\pipe\\pipename"
#else
string pathname = "pipename"

...which sort of defeats the purpose of trying to build a cross-platform library.  Since you already are using separate implementations for Win/Unix, it Would Be Nice (tm) if on the Windows-side of the house, you checked to see if the pathname being sent in was compliant, and if not either (a) add the requisite "\\\\.\\pipe\\" prefix, or (b) throw a UV_EINVAL error (same error thrown when the pathname is null - which is also invalid).

Currently, if the 2nd option is attempted (specifying the compliant \\\\.\\pipe\\pipename), the winapi throws an unspecified error.  To get it working, you actually have to use this instead: "\\\\\\\\.\\\\pipe\\\\pipename" due to backslash resolution rules.

**Comment by saghul** [comment]
> ...which sort of defeats the purpose of trying to build a cross-platform library.

Usually I would agree, but not on this one. Unix domain sockets and Windows named pipes are only equivalent up to a given extent. On Windows they live in some limbo, not the actual filesystem.

Now, I wouldn't object a patch which checks if the given name starts with the required prefix and fails with UV_EINVAL otherwise.

**Comment by saghul** [comment]
Closing, there is nothing actionable here. @Tulrath feel free to send a PR with the extra check I mentioned [here](https://github.com/libuv/libuv/issues/458#issuecomment-125644266).
