### ISSUE TITLE
vcbuild.bat doesn't work when run from a VS dev cmd prompt (VS2015)

### ISSUE THREAD

**Issue by DamianEdwards** [libuv/libuv#459]
I'm running into an issue trying to build libuv from a VS2015 dev command prompt.

It seems that `vcbuild.bat` assumes that if the `WindowsSDKDir` env variable is set then it can skip straight to the `select-target` step. Doing that however results in the `GYP_MSVS_VERSION` env variable not being set. That then produces a VS2010 sln file, which won't build on a machine that doesn't have the VS2010 build tools installed (e.g. on my machine that only has 2015 installed).

The workaround is to manually set the `GYP_MSVS_VERSION` env variable to 2015 before running `vcbuild.bat`.

**Comment by bnoordhuis** [comment]
I suspect it's at least in part a GYP problem.  It tries to auto-detect the MSVS version if GYP_MSVS_VERSION is not set but I don't think the heuristic for 2015 is fully baked yet.

**Comment by saghul** [comment]
gyp seems to prefer VS 2015 (if present) since [they added support for it](https://chromium.googlesource.com/external/gyp/+/ce7a555f1c58bb396f8b1fa304aa3977ec8d2b93%5E!/). @DamianEdwards can you please update gyp to the latest (and hopefully greatest) re-test?

**Comment by saghul** [comment]
Closing, see https://github.com/libuv/libuv/issues/705 for a similar problem and resolution.
