### ISSUE TITLE
uv_spawn always return 2

### ISSUE THREAD

**Issue by andyx666888** [libuv/libuv#4593]
* **Version**: 1.49.0
* **Platform**: win11 
* like this:
      try {
          let child = spawn('calc.exe', [], {
              stdio: 'ignore',
              detached: true,
              cwd: 'c:\windows\system32',
              windowsVerbatimArguments: true
          });
          child.unref()
      } catch {
      }

[int uv__create_nul_handle(HANDLE* handle_ptr,](https://github.com/libuv/libuv/blob/v1.x/src/win/process-stdio.c#L144)
uv__create_nul_handle always return 2, no such file or directory

**Comment by saghul** [comment]
What does "basename(processName)" contain? Is it in the path?

**Comment by andyx666888** [comment]
js code, most computer uv_spawn no problem, only one computer always return 2, that is not point ,the point is 
   uv_stdio_container_t stdio[3];
   stdio[0].flags = UV_IGNORE;
   stdio[1].flags = UV_INHERIT_FD; stdio[1].data.fd = 1;
   stdio[2].flags = UV_INHERIT_FD; stdio[2].data.fd = 2;
  options.stdio = stdio; options.stdio_count = 3;
UV_IGNORE will call uv__create_nul_handle
  handle = CreateFileW(L"NUL",
                       access,
                       FILE_SHARE_READ | FILE_SHARE_WRITE,
                       &sa,
                       OPEN_EXISTING,
                       0,
                       NULL);
and CreateFileW always return 2

**Comment by andyx666888** [comment]
CreateFileW "NUL" fail

**Comment by saghul** [comment]
I'm a bit confused here. Your first code snipped is from what looks like Node and the latter is libuv in C.

What parameters did you pass to spawn, in JS?

**Comment by andyx666888** [comment]
try {
let child = spawn('calc.exe', [], {
stdio: 'ignore',
detached: true,
cwd: 'c:\windows\system32',
windowsVerbatimArguments: true
});
child.unref()
} catch {
}

**Comment by andyx666888** [comment]
this code can run well on many computers , but only one computer no, perhaps  uv_spawn  should process 
CreateFileW "NUL" fail

**Comment by juanarbol** [comment]
If _one_ computer is failing, isn't that an environment issue? How could we debug that?

**Comment by bnoordhuis** [comment]
I'm getting strong https://github.com/nodejs/node/issues/55416 vibes here.

**Comment by leehark** [comment]
May your computer doesn't run NULL Service like here https://github.com/nodejs/node/issues/55416

**Comment by bnoordhuis** [comment]
I'm going to make the judgement call that it's not libuv's responsibility if users break their systems.

We open NUL for a reason. If someone can come up with an alternative approach for that, I might consider it, but for now I'm closing this as a wontfix.

**Comment by leehark** [comment]
> I'm going to make the judgement call that it's not libuv's responsibility if users break their systems.
> 
> We open NUL for a reason. If someone can come up with an alternative approach for that, I might consider it, but for now I'm closing this as a wontfix.

Sometimes it is not user's selection, but other unknown reason, maybe some other software break system, and it cause some application using nodejs(like electron app) can't run correctly.

**Comment by saghul** [comment]
Is there a legit reason for that service not to be there?

If the system is broken it's fine if node doesn't work. If the house is on fire why bother watering the plants? 😅
