### ISSUE TITLE
How to delete the timer handle from loop's handle_queue

### ISSUE THREAD

**Issue by qycyfjy** [libuv/libuv#4595]
* **Version**: 1.49.3-dev
* **Platform**: Linux 5.15.153.1-microsoft-standard-WSL2

`uv__queue_remove` not called near `uv_timer_stop`. So after `uv_timer_init` it stays in handle_queue, and then `uv_loop_close` returns UV_EBUSY directly after it executes there.
I would like to know if it is necessary to handle this situation, and if so, how to do it.

![image](https://github.com/user-attachments/assets/b6ce32fe-18ee-407a-abbb-c8894b7465c8)

**Comment by saghul** [comment]
That's because the timer is stopped but not closed. You need to uv_close the handle.

**Comment by qycyfjy** [comment]
> That's because the timer is stopped but not closed. You need to uv_close the handle.

Thanks, I solved the problem by adding uv_close in the timeout callback.
