### ISSUE TITLE
Tweak effect of UV_LOOP_USE_IO_URING

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#4616]
I'm thinking that it should work like this:

1. `UV_USE_IO_URING=0` disables io_uring completely
2. `UV_USE_IO_URING=1` enables epoll batching _and_ sqpoll
3. No `UV_USE_IO_URING` enables epoll batching but _not_ sqpoll
4. The loop flag works like (2)

The flag should have taken a boolean as an argument, in hindsight, but eh, live and learn.

Alternatively, we could leave epoll batching as an always-on thing and make the environment variable and loop flag only affect sqpoll. Because honestly, it's a pretty good optimization.

_Originally posted by @bnoordhuis in https://github.com/libuv/libuv/issues/4598#issuecomment-2466452579_

**Comment by bnoordhuis** [comment]
> Alternatively, we could leave epoll batching as an always-on thing and make the environment variable and loop flag only affect sqpoll. Because honestly, it's a pretty good optimization.

I think this is where the consensus is? @saghul was with me on this one, at least :)

**Comment by santigimeno** [comment]
> > Alternatively, we could leave epoll batching as an always-on thing and make the environment variable and loop flag only affect sqpoll. Because honestly, it's a pretty good optimization.
> 
> I think this is where the consensus is? @saghul was with me on this one, at least :)

+1 from me

**Comment by juanarbol** [comment]
I can work on this one

**Comment by bnoordhuis** [comment]
I have it pretty much finished already, the only thing we need to decide on is what gets highest priority: the environment variable, or the `UV_LOOP_ENABLE_IO_URING_SQPOLL` flag. I can see an argument for either.
