### ISSUE TITLE
The tcp_connect6_link_local test case failed in 1.49.2.

### ISSUE THREAD

**Issue by simon28li** [libuv/libuv#4619]
* **Version**:  1.49.2
* **Platform**: aarch64    openEuler 22.03 (LTS-SP3）
Hi. When I test the latest version 1.49.2, I encounter the same error as [#4211](https://github.com/libuv/libuv/issues/4211) The error content is as follows. Can you provide some help?
```
2: not ok 313 - tcp_connect6_link_local
2: # exit code 134
2: # Output from process `tcp_connect6_link_local`:
2: # Assertion failed in /home/stage/root/spack-stage-libuv-1.49.2-aclfalclg5xrmbc33b4kxwtluzkbcgyn/spack-src/test/test-tcp-connect6-error.c on line 119: `uv_tcp_connect(&req, &server, (struct sockaddr*) &addr, connect_cb) == 0` (-99 == 0)
```

**Comment by saghul** [comment]
Error 99 is EADDRNOTAVAIL. Does your system have an IPv6 link local address?

**Comment by simon28li** [comment]
Thank you very much. The test passed after ipv6 was disabled.
