### ISSUE TITLE
linux: don't retry dup2/dup3 on EINTR?

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#462]
The dup2 and dup3 wrappers in src/unix/core.c retry on EINTR.

I think (but am not 100% positive) that's subject to a race condition: the EINTR may indicate that the implicit close() was interrupted by a signal.

On Linux, close() should not be retried after an EINTR because the file descriptor was closed, despite the error.  A retry either fails with EBADF or ends up closing the wrong file descriptor.

Extending that logic to dup2/dup3, trying again seems dangerous.  However, although the man page states that the system call may fail with EINTR, I don't think the actual system call ever does.

**Comment by saghul** [comment]
> On Linux, close() should not be retried after an EINTR because the file descriptor was closed, despite the error. A retry either fails with EBADF or ends up closing the wrong file descriptor.

Back in the day we switched from close() to uv__close just to retry on EINTR: https://github.com/libuv/libuv/commit/1028a9c6a75fde47b848c09c450fc066249fac1b Does the comment on that commit still stand or should we not retry on EINTR at all? (for close, at least).

Then uv__close morphed in this: https://github.com/libuv/libuv/commit/359d6678930fbb25e612d290a2ff5114e10eda6f which sanity-checks the fd about to be closed, but we retained the EINTR behavior and actually added some compatibility thing by turning it into EINPROGRESS.

So, wouldn't dup2/3 suffer from the same problems in their implicit close? Where those fixes 2 years ago kinda incorrect?

At any rate, I trust you've become (even) better with age, just like good whiskey ;-)

**Comment by bnoordhuis** [comment]
1028a9c is incorrect depending on the platform: on Linux, the file descriptor is closed even on EINTR; other Unices have different behavior.

359d667 is correct in that it doesn't retry on EINTR.  Changing the return code to EINPROGRESS is for forward compatibility with the upcoming POSIX revision.  (We could change it to 0 is that's more convenient but it doesn't matter right now, I don't think the return value is checked anywhere.)

**Comment by saghul** [comment]
> 1028a9c is incorrect depending on the platform: on Linux, the file descriptor is closed even on EINTR; other Unices have different behavior.

Yay consistency!

> 359d667 is correct in that it doesn't retry on EINTR. Changing the return code to EINPROGRESS is for forward compatibility with the upcoming POSIX revision. (We could change it to 0 is that's more convenient but it doesn't matter right now, I don't think the return value is checked anywhere.)

Ah, I see. There is one single place which checks for it, AFAIS: https://github.com/libuv/libuv/commit/359d6678930fbb25e612d290a2ff5114e10eda6f#diff-993e2d1f75ebf418adfbe81df8050a95R234

So I say go for it! Because you volunteered, right? :-)

**Comment by bnoordhuis** [comment]
See #608.
