### ISSUE TITLE
test: flaky udp_reuseport on qemu-mipsel

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#4631]
Fails sporadically (but often enough that it's annoying):
```
not ok 425 - udp_reuseport
# exit code 134
# Output from process `udp_reuseport`:
# Assertion failed in /home/runner/work/libuv/libuv/test/test-udp-reuseport.c on line 272: `thread_loop2_recv > 0` (0 > 0)
```

**Comment by bnoordhuis** [comment]
I haven't seen this recently and I'm tentatively hopeful 3d0578e6ebe065836e3407388f6459e8fbefb312 fixes it.

**Comment by alls0rts** [comment]
Latest Solaris 11.4 sees this, though sometimes it's \`thread\_loop1\_recv\` that hits the assert.

I can confirm on Solaris that the other thread collects all the packets.

I did wonder if it was due setting of `reuseport-lbalg` (load
balancing algorithum), from the ipadm(8) manual page:

    reuseport-lbalg (TCP, SCTP, UDP)
     
        This option defines the algorithm used to select a socket using the
        SO_REUSEPORT socket option, load balancing mechanism to  deliver  a
        TCP/SCTP incoming connection request or an UDP datagram.

A little more information on load-balancing values in
[Administering TCP/IP Networks, IPMP, and IP Tunnels in Oracle® Solaris 11.4](https://docs.oracle.com/cd/E37838_01/html/E60991/gnklh.html)

Tried changing value to Round robin, but it didn't make any difference
`ipadm set-prop -p reuseport-lbalg=rr udp`

**Comment by alls0rts** [comment]
I've gotten more information for the failure on Solaris, I shall open a new issue as it is a different platform.
