### ISSUE TITLE
windows: uv_getaddrinfo() should return all registered addresses for host= '', not UV_EINVAL

### ISSUE THREAD

**Issue by lschoe** [libuv/libuv#4634]
On Windows, a call to `uv_getaddrinfo()` with host ='' (that is, argument `node` points to an empty string) returns an error `UV_EINVAL`.

However, it should return *all registered addresses on the local computer* as per [GetAddrInfoW function (ws2tcpip.h)](https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfow), which says under "Remarks":

``If the pNodeName parameter contains an empty string, all registered addresses on the local computer are returned.``

The relevant code is this part:
https://github.com/libuv/libuv/blob/c431bc39c396ce644b47367d415a2c869ee81941/src/win/getaddrinfo.c#L266-L276

To resolve this issue, the call to `uv__idna_toascii()` is skipped for an empty node string:
```c
  if (node != NULL) {
    if (node[0] == '\0') {
      nodesize = 1;
    } else {
      rc = uv__idna_toascii(node,
                            node + strlen(node),
                            hostname_ascii,
                            hostname_ascii + sizeof(hostname_ascii));
      if (rc < 0)
        return rc;
      nodesize = strlen(hostname_ascii) + 1;
      node = hostname_ascii;
    }
}
```

This change is important, for example, to get the same behavior as when calling `socket.getaddrinfo('', 0)`  in Python on Windows, which already returns all registered addresses on the local computer. We need it to make `Winloop` pass the same tests as `uvloop`: 
https://github.com/Vizonex/Winloop/blob/99926c1f7b05d91275aedf32febc5c69cf2005a7/tests/test_dns.py#L256-L266

**Comment by saghul** [comment]
libuv abstracts platform differences. We strive to get the same result on Unix and Windows. What does Linux do when called that way?

**Comment by lschoe** [comment]
Well, indeed, on Linux the call `socket.getaddrinfo('', 0)` gives an error in Python, which is consistent with libuv. 

The question is whether this particular platform difference should also be abstracted away by libuv. In Python the choice has been made to give the above Windows specific result for `socket.getaddrinfo('', 0)`. Also the `asyncio` event loop gives the same result for await `asyncio.get_event_loop().getaddrinfo('', 0)` for the default event loop on Windows.

**Comment by saghul** [comment]
libuv's _raison d'etre_ is abstracting away platform differences.

As someone using `uv_getaddrinfo`, which one is easier: having consistent errors, or having to do platform checks and different handling?

In case the answer is "but I only need Windows support" then why use libuv (or that API specifically) in the first place?

**Comment by lschoe** [comment]
Well, we need support for Linux, Windows, and macOS, as we are extending uvloop with support for Windows. 

In fact, uvloop already has a related issue with its call to `uv_getaddrinfo()`, see
https://github.com/MagicStack/uvloop/blob/7bb12a174884b2ec8b3162a08564e5fb8a5c6b39/uvloop/dns.pyx#L349-L357

So, in the case of `uv_getaddrinfo()` some platform dependent behavior may be useful.

**Comment by saghul** [comment]
IMHO you are looking at this backwards. Python lets some platform level subtlety surface, and uvloop wants to emulate that, while libuv makes the API consistent.

Your poposal makes libuv worse for libuv users.

**Comment by lschoe** [comment]
Not worse for all libuv users;)

A consistent API is certainly a good thing, but it need not always be clear what behavior is chosen for.

But I'll go with your judgment in these matters, as I don't see the big picture here (like when libuv still returns platform dependent results).

**Comment by saghul** [comment]
Barring the impossible, libuv tries very hard to be consistent across platforms.

**Comment by lschoe** [comment]
For the record. I've found an (almost) satisfactory solution to support asynchronous `getaddrinfo('', 0)` on Windows, without modifying libuv. Turns out that using b'..localmachine' is _almost_ equivalent to using an empty string as host. See https://github.com/Vizonex/Winloop/commit/e74de10a35c7d1a764ad0df3ae23a09d4202608e.

The results may differ slightly, depending on details for the local machine. This difference also shows for the synchronous calls 
`socket.getaddrinfo('', 0)` versus `socket.getaddrinfo(b'..localmachine', 0)`. On my machine, the latter call returns an extra registered address.

**Comment by saghul** [comment]
Given that libuv runs getaddrinfo on an internal thread pool, you could also just run socket.getaddrinfo with the loop executor.

That's what the default loop does anyway, last I checked.

**Comment by vtjnash** [comment]
There is a possibility we stop running this in the threadpool, since this Window's API is async already if we were passing the right arguments to GetAddrInfoExW (https://github.com/libuv/libuv/issues/4388)

**Comment by bnoordhuis** [comment]
I believe the consensus here is "we're not going to make that change", right? Closing then.

(FWIW, I agree; consistency is important.)
