### ISSUE TITLE
uv_udp_init_ex cost 20ms or  more time on linux

### ISSUE THREAD

**Issue by Lynnworld** [libuv/libuv#4642]
* **Version**: I tested on  v1.49.1 v1.48.0 
* **Platform**:  Linux   5.10.0

I use [mediasoup](https://github.com/versatica/mediasoup) as WebRTC SFU . However some request cost too much time.
Here is the Code sample:
```
MS_TIME_TRACE();
err = uv_udp_init_ex(DepLibUV::GetLoop(), reinterpret_cast<uv_udp_t*>(uvHandle), UV_UDP_RECVMMSG | AF_INET);
MS_TIME_TRACE();
```
it will cost 20~50ms for sometimes.  It's normal in most time.

**Comment by Lynnworld** [comment]
@ibc You should also be aware of this.

**Comment by saghul** [comment]
No idea, other than saving all tracing output and going through it when you spot the problem...

**Comment by Lynnworld** [comment]
it's turn out socket create cause the problem
```
/* Open a socket in non-blocking close-on-exec mode, atomically if possible. */
int uv__socket(int domain, int type, int protocol) {
  int sockfd;
  int err;

  uint64_t t1=uv_hrtime();

#if defined(SOCK_NONBLOCK) && defined(SOCK_CLOEXEC)
  sockfd = socket(domain, type | SOCK_NONBLOCK | SOCK_CLOEXEC, protocol);
  uint64_t t2=uv_hrtime();
  if (t2-t1>1000000)
    fprintf(stderr,"uv__socket SOCK_NONBLOCK %d\n",t2-t1);
  if (sockfd != -1)
    return sockfd;

  if (errno != EINVAL)
    return UV__ERR(errno);
#endif
```

log show
```
uv__socket SOCK_NONBLOCK 22497842  //22ms
uv__socket SOCK_NONBLOCK 42722081  //42ms
```

😭

**Comment by saghul** [comment]
That's one syscall so I guess you'll need to dive down to the kernel to find out why :-/

**Comment by bnoordhuis** [comment]
I'll go ahead and close this as not-our-bug. If you're using a LSM, that'd be where I'd start looking first, and otherwise it's time to whip out `perf record` or `perf top`.
