### ISSUE TITLE
FressBSD: gethostname is failing

### ISSUE THREAD

**Issue by juanarbol** [libuv/libuv#4654]
```
not ok 135 - gethostname
# exit code 134
# Output from process `gethostname`:
# Assertion failed in /home/juan/libuv/test/test-gethostname.c on line 46: `r == UV_ENOBUFS` (0 == -55)
```
* **Version**: 1.49.3
* **Platform**: FreeBSD  14.2-RELEASE FreeBSD 14.2-RELEASE releng/14.2-n269506-c8918d6c7412 GENERIC arm64

**Comment by juanarbol** [comment]
Apparently `uv_os_gethostname` is -literraly- broken in FreeBSD. I will work on this one.

**Comment by saghul** [comment]
Very weird. It claims to have succeeded, but that test an input of 1 so unless the hostname as the empty string (WTF) I don't know how it would succed! Are you able to debug it?

**Comment by juanarbol** [comment]
Yes. Sadly I just turned of my VM rn, buf the problematic thing seems this.

https://github.com/libuv/libuv/blob/beebf02cf6a69b78673182421445fcbc9b10c341/src/unix/core.c#L1506

The thing is, `gethostname` in FreeBSD expectes a `char*` instead of a `char[]`, for whatever reason, after `gethostname(buf, sizeof(buf))`, the content in buf still `\0\0\0\0\0...` then strlen will be `0`. And won't fall in this condition:
 https://github.com/libuv/libuv/blob/beebf02cf6a69b78673182421445fcbc9b10c341/src/unix/core.c#L1508
 
 That will return the expected `UV_ENOBUFS`

**Comment by saghul** [comment]
> The thing is, `gethostname` in FreeBSD expectes a `char*` instead of a `char[]`

That's the same really.

> for whatever reason, after `gethostname(buf, sizeof(buf))`, the content in buf still `\0\0\0\0\0...` then strlen will be `0`

Aha! Well that is weird. If that system dooes have a hostname (it does, right?) why would it not return it?

If it's possible to have no hostname (a quick search seems to suggest as much) then I guess there is nothing to fix here. 

What is that system's hostname?

**Comment by juanarbol** [comment]
@saghul, it's confirmed, the hostname of my vm is empty string. I'll proceed to close this as this is an environment issue and not a libuv issue.
