### ISSUE TITLE
Run loop stopping early due to streams regression

### ISSUE THREAD

**Issue by btrask** [libuv/libuv#468]
I recently updated the version of libuv my application is using and immediately noticed it was unexpectedly quitting. I used git bisect to trace the problem to commit 05a003a3f78d07185b7137601fe8e93561855a8d. I'm not sure why but setting `stream->flags |= UV_STREAM_DISCONNECT` causes the run loop to think there are no ref'd handles left.

The only thing that _should_ be ref'd in my application is a bound TCP socket. The disconnected stream is an HTTP stream that is unref'd while it is in keep-alive (between requests) and ref'd once a new request comes in.

Commenting out https://github.com/libuv/libuv/commit/05a003a3f78d07185b7137601fe8e93561855a8d#diff-c9c9805d800eb132a191a9e40da6d813R1236 src/unix/stream.c lines 1236 and 1237 fixes the problem. Line 1146 (`uv__stream_eof()`) never gets hit.

This is on Fedora.

**Comment by saghul** [comment]
Is your read callback executed with an error status? Any chance you can write a libuv test case exhibiting the problem?

**Comment by btrask** [comment]
I don't believe it is, but I'd double check. Even so, there's no reason for the run loop to stop.

I'll look into writing a test case. Thanks.

**Comment by saghul** [comment]
> Even so, there's no reason for the run loop to stop.

A bound socket doesn't keep the loop alive because it's not active, a listening socket is active and keeps the loop alive, though. And if a socket gets a read error it becomes inactive, so it also doesn't prevent the loop from exiting.

http://docs.libuv.org/en/v1.x/handle.html?highlight=active#c.uv_is_active

**Comment by btrask** [comment]
Sorry, you're right, the socket is bound and listening. The same application was working up until that commit, so I don't think I'm doing anything wrong, although I might be. I haven't had a chance to put together a test case yet.

**Comment by btrask** [comment]
I created a test case: https://gist.github.com/btrask/d3a2e5629ccf49706fe0

It behaves as I originally described. It's triggered by the combination of `uv_unref` and `UV_STREAM_DISCONNECT`.

**Comment by saghul** [comment]
@btrask can you try the patch in #474 ? It fixes the problem for me.

**Comment by saghul** [comment]
We reverted that in https://github.com/libuv/libuv/pull/475#issuecomment-128684848
