### ISSUE TITLE
Synchronous APIs should be completely stand-alone

### ISSUE THREAD

**Issue by btrask** [libuv/libuv#469]
I was told in #267 that synchronous APIs (like file system calls with NULL specified as the callback) aren't thread-safe because they touch the uv run loop. This isn't a problem for me personally, because I create a separate run loop for each thread, but fixing it might give libuv a bit more flexibility. I haven't noticed any performance impact, if there is one.

**Comment by bnoordhuis** [comment]
Fixed by df62b54, will be part of the next release.

**Comment by btrask** [comment]
Great, thanks!
