### ISSUE TITLE
EOL conversion code causes incorrect behaviour of \r (carriage return) on Windows

### ISSUE THREAD

**Issue by csnover** [libuv/libuv#471]
The code at https://github.com/libuv/libuv/blob/v1.x/src/win/tty.c#L1883-L1900 outputs `\r\n` whenever a `\r` (CR) or `\n` (LF) is seen in the character stream. This is OK for LF, which effectively includes an implicit CR on \*nix systems. However, on *all* supported OS (including Windows), CR returns to the start of the line *without* a corresponding line feed, and libuv is breaking this. (Refs theintern/intern#454.)

I have a patch ready for this issue, just looking to see if I can get tests in place before submitting a PR. I may not succeed but I will at least send the patch.

**Comment by saghul** [comment]
Continues in #472

**Comment by csnover** [comment]
@saghul What does that mean? Why is this closed? This bug still exists.

**Comment by saghul** [comment]
Since you opened the issue and then made a fix for it, let's continue the discussion over at #472, where we have some code to talk about :-)

**Comment by csnover** [comment]
What discussion?

**Comment by saghul** [comment]
Your PR is open and pending review, once someone with knowledge and time reviews it we can move forward.
