### ISSUE TITLE
Enable Fast TCP Loopback on Win

### ISSUE THREAD

**Issue by benaadams** [libuv/libuv#489]
For versions greater than or equal to Windows Server 2012 and Windows 8 enable Fast TCP Loopback on all sockets. This provides a x1.5 speed improvement for 127.0.0.1/localhost use

http://blogs.technet.com/b/wincat/archive/2012/12/05/fast-tcp-loopback-performance-and-low-latency-with-windows-server-2012-tcp-loopback-fast-path.aspx

Example code given:

``` c
int OptionValue = 1;
DWORD NumberOfBytesReturned = 0;

int status = 
    WSAIoctl(
        Socket, 
        SIO_LOOPBACK_FAST_PATH,
        &OptionValue,
        sizeof(OptionValue),
        NULL,
        0,
        &NumberOfBytesReturned,
        0,
        0);


if (SOCKET_ERROR == status) {
    DWORD LastError = ::GetLastError();

    if (WSAEOPNOTSUPP == LastError) {
        // This system is not >= Windows
        // Server 2012, and the call is not 
        // supported.
    }
    else {
        LogAMessageSomeWhere(
            "Loopback Fastpath WSAIoctl failed: ", 
            LastError);

    }
}
```

**Comment by 2ix** [comment]
@saghul Is this added to core or is there an example how to do this manually with `libuv`?

**Comment by saghul** [comment]
I'd be ok with adding this to core, should anyone volunteer to write a patch :-) If you want to enable it manually in the interim, have a look at `uv_fileno`.

**Comment by amurzeau** [comment]
while working on this issue, I found that enabling this feature slow down performance on Windows 10 unlike Windows 8 (I get better results only on Windows 8/8.1).
I get similar performance loss as here: http://stackoverflow.com/questions/31742501/fast-loopback-on-windows-10-with-weird-hyperthreading-results.

Has anyone got better loopback performance with this feature enabled on Windows 10 ?

(In a VM on Windows 10, I get 1,5 gbits/s without fastpath and 0.9 gbits/s with fastpath.)

**Comment by saghul** [comment]
Did you also perform the Windows 8/8.1 tests on a VM? I wonder if that had any impact on the results...

**Comment by amurzeau** [comment]
I did the test Windows 8.1 on a VM and got the performance boost. Both (Windows 8.1 and 10) are on Virtual Box with 2 virtualized CPU cores (and same physical host). (Also, Windows 10 is fully updated)

So I wonder if this is caused by Windows 10 itself or something else.

**Comment by saghul** [comment]
At any rate: can this option be set at any time after the socket was created? If so, we can leave it out of libuv and point users to `uv_fileno`, they can get the `SOCKET` and enable it manually.

**Comment by amurzeau** [comment]
It can be set but only before uv_connect / uv_listen.

The idea I have it to do the following:
- uv_tcp_init enable or disable fast path based on OS version (so enable it only on Windows 8/8.1)
- optionally the user call a new function like "uv_tcp_fastpath" so override the default (and for example enable fastpath on Windows 10)
- When calling uv_connect or uv_listen, do the IOCTL if the feature is enabled (and if connecting to loopback in uv_connect)
See also a beginning of implementation here: https://github.com/amurzeau/libuv/commit/win_fastpath_loopback

**Comment by saghul** [comment]
In that case, and given that this option only works in such a small subset of versions I'd rather not add a new API call for it. It's currently possible to do it outside of libuv: create the socket early with `uv_tcp_init_ex`, get the socket handle with `uv_fileno`, set the option, and Bob's your uncle!

**Comment by benaadams** [comment]
> While working on this issue, I found that enabling this feature slow down performance on Windows 10 unlike Windows 8 (I get better results only on Windows 8/8.1).

While I don't doubt your results; this feels like a  regression or O/S bug? Though it would need to be fixed before become default behaviour.

**Comment by amurzeau** [comment]
After several tests, I only get this regression with libuv benchmarks (and my modifications).
Using plain sockets + fastpath, I get better performance as expected (1.4 gbits/s without fastpath and 2.5 gbits/s with fastpath) (same Windows 10 VM).

**Comment by saghul** [comment]
Hum. libuv does not use synchronous sockets, so if this improvement is only seen in that case, should we dicth it? Or am I missing something here?

**Comment by benaadams** [comment]
> Hum. libuv does not use synchronous sockets, so if this improvement is only seen in that case, should we dicth it? Or am I missing something here?

The article suggests x1.4 improvement in latency for IOCP sockets (async) by bypassing the IP part of the networking stack for localhost when both endpoints have it enabled.

Obv at the same time wouldn't want regression with one side not using it or non localhost traffic - or oddly Win10 (Server2016)

**Comment by amurzeau** [comment]
Here are the benchmark I have done by mixing libuv's tcp_pump1_client benchmark and synchronous client and server (which use a loop of send() or recv()). I double checked these results as they are a bit weird ...

Windows 10 VM:

client | fastpath ? | server | fastpath ? | Performance test|
-------|------------|--------|------------|-----------------|
libuv  |   No       | sync   |   No       |  1.2 gbits/s    |
libuv  |   No       | sync   |   Yes      |  1.2 gbits/s    |
libuv  |   Yes      | sync   |   No       |  1.2 gbits/s    |
libuv  |   Yes      | sync   |   Yes      |  3.7 gbits/s    |
-------|------------|--------|------------|-----------------|
sync   |   No       | libuv  |   No       |  3.3 gbits/s    |
sync   |   Yes      | libuv  |   No       |  3.4 gbits/s    |
sync   |   No       | libuv  |   Yes      |  3.3 gbits/s    |
sync   |   Yes      | libuv  |   Yes      |  1.7 gbits/s    |
-------|------------|--------|------------|-----------------|
sync   |   No       | sync   |   No       |  3.7 gbits/s    |
sync   |   Yes      | sync   |   No       |  3.7 gbits/s    |
sync   |   No       | sync   |   Yes      |  3.5 gbits/s    |
sync   |   Yes      | sync   |   Yes      |  1.3 gbits/s    |
-------|------------|--------|------------|-----------------|
libuv  |   No       | libuv  |   No       |  1.3 gbits/s    |
libuv  |   Yes      | libuv  |   Yes      |  0.8 gbits/s    |

Windows 8 host:

client | fastpath ? | server | fastpath ? | Performance test|
-------|------------|--------|------------|-----------------|
libuv  |   No       | sync   |   No       |  3.6 gbits/s    |
libuv  |   No       | sync   |   Yes      |  3.6 gbits/s    |
libuv  |   Yes      | sync   |   No       |  3.6 gbits/s    |
libuv  |   Yes      | sync   |   Yes      |  7.4 gbits/s    |
-------|------------|--------|------------|-----------------|
sync   |   No       | libuv  |   No       |  6.4 gbits/s    |
sync   |   Yes      | libuv  |   No       |  6.3 gbits/s    |
sync   |   No       | libuv  |   Yes      |  6.3 gbits/s    |
sync   |   Yes      | libuv  |   Yes      |  32 gbits/s     |
-------|------------|--------|------------|-----------------|
sync   |   No       | sync   |   No       |  7.5 gbits/s    |
sync   |   Yes      | sync   |   No       |  7.5 gbits/s    |
sync   |   No       | sync   |   Yes      |  7.4 gbits/s    |
sync   |   Yes      | sync   |   Yes      |  34 gbits/s     |
-------|------------|--------|------------|-----------------|
libuv  |   No       | libuv  |   No       |  3.7 gbits/s    |
libuv  |   Yes      | libuv  |   Yes      |  8.9 gbits/s    |

I will continue to try to find the cause of this difference on Windows 10. Someone has a Windows 10 machine to see if I'm the only one in that case ?

(FYI here is the synchronous client & server I used: https://gist.github.com/amurzeau/a0a1b78483b035144d8a)

**Comment by benaadams** [comment]
Is this a Win10 VM on Win8? Have two different Win10 machines; will give a go, and try on cloud server VM

**Comment by benaadams** [comment]
I'm not seeing the degradation on Win10 raw (build 11082) though I had to change
`int r;`
to
`unsigned long r;`
to get it to compile; equally not getting a great jump in perf (minor). Investigating more

**Comment by amurzeau** [comment]
I changed the synchronous client & server buffer to 8KB I always get better performance with fastpath enabled on Windows 10 except when using libuv as both client and server.
When changing the tcp_pump1_client benchmark buffer from 8KB to 64KB, I get a performance boost with fastpath enabled (2.7 gbits/s without fastpath, 3.5 gbits/s with fastpath on the Windows 10 VM).
Also, with synchronous client & server with both 64KB buffers I get lower performance with fastpath but if the server use a 8KB buffer (and 64KB for the client), I get better performance with fastpath...

Also FYI, the numbers with both synchronous client and server using a 8KB buffer (to match libuv's tcp_pump1_client benchmark):
Windows 10 VM:

client | fastpath ? | server | fastpath ? | Performance test|
-------|------------|--------|------------|-----------------|
libuv  |   No       | sync   |   No       |  1.2 gbits/s    |
libuv  |   No       | sync   |   Yes      |  1.2 gbits/s    |
libuv  |   Yes      | sync   |   No       |  1.1 gbits/s    |
libuv  |   Yes      | sync   |   Yes      |  3.5 gbits/s    |
-------|------------|--------|------------|-----------------|
sync   |   No       | libuv  |   No       |  1.6 gbits/s    |
sync   |   Yes      | libuv  |   No       |  1.6 gbits/s    |
sync   |   No       | libuv  |   Yes      |  1.6 gbits/s    |
sync   |   Yes      | libuv  |   Yes      |  2.3 gbits/s    |
-------|------------|--------|------------|-----------------|
sync   |   No       | sync   |   No       |  1.4 gbits/s    |
sync   |   Yes      | sync   |   No       |  1.4 gbits/s    |
sync   |   No       | sync   |   Yes      |  1.4 gbits/s    |
sync   |   Yes      | sync   |   Yes      |  1.7 gbits/s    |
-------|------------|--------|------------|-----------------|
libuv  |   No       | libuv  |   No       |  1.1 gbits/s    |
libuv  |   Yes      | libuv  |   Yes      |  0.9 gbits/s    |

Windows 8.1 host:

client | fastpath ? | server | fastpath ? | Performance test|
-------|------------|--------|------------|-----------------|
libuv  |   No       | sync   |   No       |  3.4 gbits/s    |
libuv  |   No       | sync   |   Yes      |  3.5 gbits/s    |
libuv  |   Yes      | sync   |   No       |  3.5 gbits/s    |
libuv  |   Yes      | sync   |   Yes      |  7.8 gbits/s    |
-------|------------|--------|------------|-----------------|
sync   |   No       | libuv  |   No       |  3.5 gbits/s    |
sync   |   Yes      | libuv  |   No       |  3.5 gbits/s    |
sync   |   No       | libuv  |   Yes      |  3.7 gbits/s    |
sync   |   Yes      | libuv  |   Yes      |  10  gbits/s    |
-------|------------|--------|------------|-----------------|
sync   |   No       | sync   |   No       |  3.7 gbits/s    |
sync   |   Yes      | sync   |   No       |  3.7 gbits/s    |
sync   |   No       | sync   |   Yes      |  3.7 gbits/s    |
sync   |   Yes      | sync   |   Yes      |  9.3 gbits/s    |
-------|------------|--------|------------|-----------------|
libuv  |   No       | libuv  |   No       |  3.2 gbits/s    |
libuv  |   Yes      | libuv  |   Yes      |  7.9 gbits/s    |

I also made a single threaded simple client that use IOCP for the send call (using WSASend) but it has the same numbers as the synchronous client.

**Comment by benaadams** [comment]
How are you doing the libuv to libuv? It isn't hitting anything related to this? (probably not, but just checking)

https://groups.google.com/forum/#!topic/libuv/5DAW1hViw0Q

**Comment by amurzeau** [comment]
For libuv to libuv, I start `run-benchmarks.exe tcp_pump1_client` <hich spawn two process: one client and one server (the server is an helper: tcp_pump_server).
So I don't think it's related but I will check that anyway.
