### ISSUE TITLE
Feature Request: need actual idle handles

### ISSUE THREAD

**Issue by pmq20** [libuv/libuv#491]
`libuv` already have handles for false "idleness", i.e. uv_idle_t:

>    Despite the name, idle handles will get their callbacks called on every loop iteration,
>    not when the loop is actually "idle".

But we need an "actual idleness" for https://github.com/nodejs/node/issues/2543 

Actual Idle handles will run the given callback when the loop iteration satisfies both of the following conditions:

1) when there are no timers or all timers have yet not expired, i.e. when the loop is waiting for timers to expire
2) when there are no I/O handles or I/O is in progress, i.e. when the event loop polls for i/o but there are no pending callbacks yet.

**Comment by saghul** [comment]
When both of those conditions are satisfied the loop will block for i/o for the calculated timeout. How about using a `uv_prepare_t` handle, which runs right before polling for i/o and calling `uv_backend_timeout` there? If the returned value is != 0 it means the loop is about to block for the given amount of time, thus we could say it's "idle".

**Comment by bnoordhuis** [comment]
I commented on the node issue [here](https://github.com/nodejs/node/issues/2543#issuecomment-134945335) but to recap: I don't think libuv's continuous event loop model allows for a useful definition of "idle" outside of the "waiting for timers and only timers to expire" scenario.  As soon as I/O is involved, there are no longer predictable quanta of time; a quiescent period can end at any time.

**Comment by saghul** [comment]
@bnoordhuis Agreed. Feel free to close.
