### ISSUE TITLE
Strange state about uv_queue_work .

### ISSUE THREAD

**Issue by zhaozg** [libuv/libuv#492]
The load passed by uv_queue_work will assign to echo thread balancely, but when I give more press will change to only one thread works, and other not fetch task from queue.

how about this.
![Uploading 1.png…]()

![Uploading 2.png…]()

**Comment by bnoordhuis** [comment]
By the sound of it you've hit #490?  A fix for that will be in the next patch release.

**Comment by zhaozg** [comment]
@bnoordhuis thanks, update static void post(QUEUE* q) will solve the problem.

**Comment by bnoordhuis** [comment]
Fixed by da42780.
