### ISSUE TITLE
Non-obvious handling of EAGAIN in uv_read_cb

### ISSUE THREAD

**Issue by btrask** [libuv/libuv#495]
With `read(2)`, EOF is indicated by a read length of 0, and `EAGAIN` is set in `errno`.

In libuv, `uv_read_cb` indicates EOF with the `UV_EOF` error, and `EAGAIN` with a read length of 0.

I definitely see an argument for doing it libuv's way, but this can be a gotcha for careless libuv users (like myself!). I was handling `UV_EOF` but not zero-length reads, which were getting interpreted as EOF by another library (causing truncation and potentially data loss).

I consider this mainly a documentation bug since I don't expect the libuv API to change. The [documentation](http://docs.libuv.org/en/v1.x/stream.html) says:

> _nread_ is > 0 if there is data available, 0 if libuv is done reading for now, or < 0 on error.

Perhaps this could be clarified. In fact I would put in a warning to clarify the reversal from `read(2)` behavior.

I would also really like to see more comments in the uv.h header file.

Thanks.

**Comment by saghul** [comment]
> Perhaps this could be clarified. In fact I would put in a warning to clarify the reversal from read(2) behavior.

Mind sending a documentation PR?

> I would also really like to see more comments in the uv.h header file.

That's not happening. We now have the API docs in docs/. We used to have them in uv.h but they rot with time.

**Comment by btrask** [comment]
Okay, I will write something up. Thanks.

**Comment by saghul** [comment]
#500 landed, closing this then. Thanks!
