### ISSUE TITLE
Add btime argument to utimes for OS X and Windows

### ISSUE THREAD

**Issue by jorangreef** [libuv/libuv#499]
From: https://github.com/nodejs/node/issues/2600

Libuv exposes a file's birthtime but provides no way to set the btime on platforms which support it.

Setting the btime where supported by the file system, is especially important for backup programs which need to be able to restore a file's creation time. On platforms which don't support btime, then a no-op is fine and is to be expected by the user. But where it is supported, it should be supported, to avoid surprising the user (seeing the btimes on all their files reset).

Setting the btime on Windows is probably the easiest, as one could pass in a creation time instead of NULL in the current libuv utimes call:

`if (!SetFileTime(handle, NULL, &filetime_a, &filetime_m))`

https://msdn.microsoft.com/en-us/library/windows/desktop/ms724933(v=vs.85).aspx

Setting the birthtime is also possible on OS X via setattrlist() according to @bnoordhuis.

It's even currently possible to use libuv to set btime via utimes on OS X (and Linux systems which support btime), by passing an mtime lower than the current btime. The utimes system call will notice this and end up setting the btime as well as the mtime. A second utimes call can then be used to set the mtime. But this is a nasty hack prone to race conditions. It also does not really count since it cannot support the case where btime > current btime which is possible when data moves across machines with different clocks. Also, there should be an easy way to do it.

It would be really helpful if Node could set btime at least on Windows and OS X which support it, possibly as an extra argument to fs.utimes just before the callback, and make it a no-op on Linux:

`fs.utimes(path, atime, mtime, btime, callback)`

Then when Linux support comes along (if it ever does) for setting btime, this could be added, but without blocking the others.

This solution would be portable to Windows, OS X and Linux. On Linux, the no-op would be expected as much as a chmod would be expected to be a no-op on Windows. There's also no harm making it a no-op on Linux. But not being able to set btimes at all on any platform is a severe limitation on backup programs that want to use libuv to restore files correctly.

**Comment by whitlockjc** [comment]
I wouldn't mind doing the work for this but I'll wait for @saghul, @misterdjules and/or others to chime in before hand.

**Comment by saghul** [comment]
I'd like to see an API proposal at the libuv level. Right now all uv_fs_ apis match to their libc equivalents, but there is no consistent name for this one, since each platform does its own thing. Also extending uv_fs_utimes is not an option in v1.x because it would break the API.

**Comment by whitlockjc** [comment]
Makes sense.  Let me give this some thought and I'll get back to you.  If you have any suggestions, please share.

**Comment by whitlockjc** [comment]
While digging around, I've seen more references to `creation time`, `crtime` or `creation_time` than 'birth time` or `btime` but in `uv_stat_t` I see `birth time` being used.  That being said, I originally wanted to suggest `uv_fs_crtime` but for consistency with what is already available in `uv_stat_t`, maybe we should use `uv_fs_btime`.  If we go with `uv_fs_btime`, it would look something like this *(Very similar to `uv_fs_utimes`)*:

```c
UV_EXTERN int uv_fs_btime(uv_loop_t* loop,
                           uv_fs_t* req,
                           uv_file file,
                           double crtime,
                           uv_fs_cb cb);
```

This would likely end up looking like `fs.btime(path, btime, callback)` in node.js/io.js land.  From an initial implementation perspective, I'd say that OS X and Windows would be provided in the initial pass.  For other Unices, support would depend on the filesystem much like `getdents` does so I'm not sure how best to handle that.

**Comment by jorangreef** [comment]
Thanks @whitlockjc for doing the work on this. That would be great.

**Comment by saghul** [comment]
@whitlockjc The API looks fine to me! :+1: 

> From an implementation perspective, I'd say that OS X and Windows would be provided in the initial pass. For other Unices, support would depend on the filesystem much like getdents does so I'm not sure how best to handle that.

Now, given that Linux is a first class citizen here, we should at least have a story about it, that is, research a bit and see how it can be done.

**Comment by bnoordhuis** [comment]
A separate `uv_fs_btime()` function prevents atomic updates of more than just the birth time.  I think that would become a design decision we'd come to regret in due time.

> While digging around, I've seen more references to creation time, crtime or creation_time than birth time or btime but in uv_stat_t I see birthtime being used.

For background, we copied the name from the BSDs.  There was talk of incorporating birth time into the POSIX spec some years ago but I don't know how that panned out.

> given that Linux is a first class citizen here, we should at least have a story about it, that is, research a bit and see how it can be done.

I checked the Big Four (btrfs, ext4, jfs and xfs) in the kernel source tree and although they all have a concept of birth time (crtime with ext4 and xfs, otime with btrfs and jfs) I couldn't find an easy way to retrieve it through ioctls or xattrs.

To wit, `debugfs -R 'stat .'` works by parsing the ext4 superblock and following the chain of inodes... I don't think that's the path we want to take, if for no other reason because it requires root privileges.

**Comment by jorangreef** [comment]
Would this be alright?

```
UV_EXTERN int uv_fs_utimes2(uv_loop_t* loop,
                           uv_fs_t* req,
                           uv_file file,
                           double atime,
                           double mtime,
                           double btime,
                           uv_fs_cb cb);
```

That way, the existing API for `uv_fs_utimes` would not be broken, and the 3 timestamps could be set atomically in a single system call on Windows. Would OS X need 2 system calls to set all 3?

Would it be possible to pass in NULL for a timestamp to leave the existing timestamp as is?

**Comment by saghul** [comment]
> A separate uv_fs_btime() function prevents atomic updates of more than just the birth time. I think that would become a design decision we'd come to regret in due time.

I never thought of that. I guess we could have utimes2 or utimes_ex then.

**Comment by bnoordhuis** [comment]
> Would OS X need 2 system calls to set all 3?

Not with `setattrlist()`, it lets you set all three timestamps with a single call.

> Would it be possible to pass in NULL for a timestamp to leave the existing timestamp as is?

You could pass in `NAN` (although that's technically a C99-ism) or NULL if you change the function prototype to take `const double*`.  Alas, C has no sum types.

**Comment by whitlockjc** [comment]
I'm so glad you all chimed in, this is excellent.  After reading these, `utimes2` makes most sense to me as I think this is a perfect scenario where revving an API makes sense but since I do not know libuv's API revving strategy, I will defer to @bnoordhuis, @saghul and others.  *(Is there any documentation on libuv's API revving strategy?)*  As for Linux, I trust Ben's findings and I don't know of an option right now so it will require more digging.

**Comment by saghul** [comment]
> since I do not know libuv's API revving strategy, I will defer to @bnoordhuis, @saghul and others.

The strategy is that we cannot break it in v1.x. So if we want this in the current cycle, some other naming is needed. Ben wasn't a big fan of the "foo2" naming convention, so last I extended some API y added the "_ex" suffix: uv_tcp_init_ex. So there is that :-)

**Comment by whitlockjc** [comment]
Works for me.  I like `utimes_ex` if you do.  Seems like there is already a convention that backs that approach up.  Unless there are any objections, I could begin work on this over the weekend or early next week.  That should give this a little more soak time for Ben and others as well.

**Comment by bnoordhuis** [comment]
I'm okay with `uv_(f)utimes_ex()`.

**Comment by whitlockjc** [comment]
Thanks for the heads up.

**Comment by whitlockjc** [comment]
I've started work on this.

**Comment by jorangreef** [comment]
Thanks @whitlockjc

**Comment by whitlockjc** [comment]
First pass complete.

**Comment by whitlockjc** [comment]
I just realized that I made the signature `uv_fs_(f)utime(..., btime, atime, mtime, ...)` but with `uv_fs_(f)utime` looking like `uv_fs_(f)utime(..., atime, mtime, ...)`, I wonder if I should had made the signature like `uv_fs_(f)utime(..., atime, mtime, btime, ...)`.  Of course, I'll await review feedback.

**Comment by whitlockjc** [comment]
@jorangreef Do you have time to check this PR out and see if it works for you?  Unit tests show it's working as expected but if you have a few minutes, I'd be appreciative.

**Comment by jorangreef** [comment]
@whitlockjc Thanks Jeremy, I have looked through the PR. I don't have the libuv and C chops to test directly and haven't yet built Node with it. I am sorry I can't help much further.

@bnoordhuis what do you think?

**Comment by cjihrig** [comment]
This was fixed in https://github.com/libuv/libuv/commit/c51ead5c704cae957b9323feef97e842e1bdb033, but I guess it didn't autoclose because it landed on `master`, not `v1.x`.
