### ISSUE TITLE
why timer callback don't use "uv_queue_work"?

### ISSUE THREAD

**Issue by yjhjstz** [libuv/libuv#502]
Now, timer callbacks are called in sequence. One timer may blocked by another timer.
```c
void uv__run_timers(uv_loop_t* loop) {
  struct heap_node* heap_node;
  uv_timer_t* handle;

  for (;;) {
    heap_node = heap_min((struct heap*) &loop->timer_heap);
    if (heap_node == NULL)
      break;

    handle = container_of(heap_node, uv_timer_t, heap_node);
    if (handle->timeout > loop->time)
      break;

    uv_timer_stop(handle);
    uv_timer_again(handle);
    handle->timer_cb(handle);
  }
}
```
I think ,  to use `uv_queue_work ` to make it async may improve performance.

**Comment by saghul** [comment]
No it won't. `uv_queue_work` runs in the threadpool, and timer callbacks run in the loop thread. That code you pasted just runs the expired timers.

PS: Please use the mailing list for questions.
