### ISSUE TITLE
minor - alpine linux apk add downloading wrong version

### ISSUE THREAD

**Issue by JohnPittman** [libuv/libuv#506]
Just migrated to alpine linux for docker containers. apk add libuv and apk add libuv-dev both download v1.5.0. I tried to test repo as well but I guess it's only in the main one. The repo tag is displaying v1.7.0 but still gives v1.5.0.

Package listing:

https://pkgs.alpinelinux.org/packages?name=libuv&repo=all&arch=x86_64

**Comment by saghul** [comment]
We don't manage that repo, you need to ask the Alpine folks.
