### ISSUE TITLE
windows: xp rwlock fallback is unsound

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#515]
It was pointed out by Zhou Ran that the fallback write mutex can end up getting unlocked by a different thread than the one that locked it, resulting in undefined behavior.  Consider a rwlock that is initially unlocked:

Thread A: increments reader count at t0 -> acquires write lock at t0 -> decrements reader count at t2
Thread B: increments reader count at t1 -> decrements reader count at t3 -> releases write lock at t3

See also https://github.com/nodejs/node/pull/2723

**Comment by saghul** [comment]
Fixed by #516.

**Comment by bnoordhuis** [comment]
For posterity, this seems to have been a known issue since at least November 2014: https://groups.google.com/d/msg/libuv/KyNnGEXR0OA/NWb605ev2LUJ
