### ISSUE TITLE
API for polling uv_streams

### ISSUE THREAD

**Issue by btrask** [libuv/libuv#517]
Hi Saghul et al,

I've been using libuv in conjunction with another library (libtls) that does its own non-blocking I/O on a given file descriptor. I use `uv_fileno` to get the file descriptor from the existing `uv_tcp` object. This seems to work okay although I haven't tested it on Windows.

The problem is this library will report `EAGAIN` during either reading or writing and I'm expected to notify it when it can continue. libuv provides `uv_read_*` and `uv_write` but there is no stream function for polling that I can see.

I've tried using `uv_poll` on the file descriptor I get back from `uv_fileno` but I think libuv gets confused because it thinks I'm polling twice.

I came up with a workaround for reading where I call `uv_read_start` with a dummy `alloc_cb` that always fails. That way it polls until the socket is readable, then stops without actually reading anything. This seems to work just fine.

Unfortunately the same trick doesn't work with `uv_write`, because it expects a buffer up front and passing a zero-length buffer is a no-op. Right now I am working around it with timers, but that obviously isn't optimal.

There is already `uv_is_readable` and `uv_is_writable` but that doesn't help.

Proposals:

```
// Option 1: Extend uv_poll to support streams natively:
UV_EXTERN int uv_poll_init_stream(uv_loop_t* loop,
                                  uv_poll_t* handle,
                                  uv_stream_t *stream);

// Option 2: Extend uv_is_readable and uv_is_writable
UV_EXTERN int uv_wait_readable(uv_stream_t* handle, uv_readable_cb cb);
UV_EXTERN int uv_wait_writable(uv_stream_t* handle, uv_writable_cb cb);

// Option 3: Have a poll function directly on the stream
UV_EXTERN int uv_stream_poll(uv_stream_t* handle, int events, uv_poll_cb cb);

// Option 4: Have uv_write take an allocation callback
UV_EXTERN int uv_write3(uv_write_t* req,
                       uv_stream_t* handle,
                       uv_alloc_cb alloc_cb,
                       uv_write_cb write_cb);
```

This would also help to make writing more efficient, by allowing the application to defer allocation until after the stream becomes writable (instead of allocating first and then blocking with the buffer in memory). Similar to how `uv_read_start` works.

Sorry for spamming so many bug reports, I promise this will be the last one for a while!

Thanks!

**Comment by saghul** [comment]
I don't have much time now (I'll comment more thoroughly later), but this was already considered here: https://github.com/libuv/leps/pull/2 see the document and discussion.

**Comment by btrask** [comment]
Yeah, I saw that (via #5), but I didn't reference it because I was afraid it would muddy the waters. I just need something for interoperating with an existing library.

**Comment by btrask** [comment]
To clarify, I think something relatively simple can be added without changing any of the existing APIs or switching everything to use requests. (I'm not sure what happened to that previous issue, but it seems to have gotten bogged down in debating specifics.)

**Comment by markpotts123** [comment]
I would like to support this proposal. Enabling libtls under libuv would be very useful.

**Comment by kazuho** [comment]
+1 to having this feature.

In HTTP/2, it is generally a good idea to decide what to send _after_ the socket becomes writable, since the server might receive a request of a higher priority while the write side is blocked.  In such case, the server should send the response to new new request when the socket becomes writable.

Without this PR, HTTP/2 servers cannot be implemented that way.

**Comment by kangjoni76** [comment]
+1, 

cheers

**Comment by amurzeau** [comment]
The risk with polling based API is that this API won't be able to have good performances on Windows (as it differs from IOCP semantics), unless I'm mistaken.
