### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by 2ix** [libuv/libuv#518]
https://github.com/libuv/libuv/blob/v1.x/samples/socks5-proxy/client.c#L728

`uv_close(&c->handle.handle, conn_close_done);` how does `&c->handle.handle` reference the correct handle in the first place?

It appears to create a memory leak by not being able to close a handle create by `uv_tcp_init`, is anyone able to explain/fix please as we are using this sample to learn/write a libuv solution.

**Comment by yjhjstz** [comment]
> uv_handle_t is the base type for all libuv handle types.
`uv_close` closed handle depend on `handle->type`.

**Comment by saghul** [comment]
That's a union: https://github.com/libuv/libuv/blob/v1.x/samples/socks5-proxy/defs.h#L54 so we're closing the same handle as was initialized with `uv_tcp_init`.
