### ISSUE TITLE
add uv_ip_addr()

### ISSUE THREAD

**Issue by aberaud** [libuv/libuv#519]
To better abstract IPv4/IPv6 differences, uv_ip_addr should be added, writing back to sockaddr_storage.

```c
int uv_ip_addr(const char* ip, const char* port, struct sockaddr_storage* addr);
```

There is no technical reason to have different calls to parse IPv4 and IPv6 addresses, it makes supporting IPv6 cumbersome.

**Comment by saghul** [comment]
I wouldn't poose a PR, if you're up for it. Port should be an int or short though.

**Comment by saghul** [comment]
No follow-up, closing.
