### ISSUE TITLE
`uv_write` `uv_close` status == `UV_ECANCELED` bug

### ISSUE THREAD

**Issue by 2ix** [libuv/libuv#522]
https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-close.c#L60

If you add an additional `ASSERT` test to this code:
```
static void write_cb(uv_write_t* req, int status) {
  /* write callbacks should run before the close callback */
  ASSERT(status == UV_ECANCELED);
  ASSERT(close_cb_called == 0);
  ASSERT(req->handle == (uv_stream_t*)&tcp_handle);
  write_cb_called++;
  free(req);
}
```

Then the following error occurs:
```
=============================================================
[%  22|+  61|-   0|T   0|S   1]: tcp_close
`tcp_close` failed: exit code 134
Output from process `tcp_close`:
Assertion failed in ../test/test-tcp-close.c on line 61: status == UV_ECANCELED
=============================================================
```

This is causing issues with an application we are developing with libuv where we are calling `uv_close` on two connections where one connection may have already called `uv_write` before it's callback is called and even though we are trying to handle `UV_ECANCELED` it appears libuv no longer supports "In-progress requests, like uv_connect_t or uv_write_t, are cancelled and have their callbacks called asynchronously with status=UV_ECANCELED."

Was this feature removed for `uv_write_t` or perhaps with the test not being present, was overlooked? Any chance we could please have `UV_ECANCELED` added in for `uv_write_t` callbacks when their tcp handle is `uv_close`.

**Comment by saghul** [comment]
`uv_write_t` requests have never supported explicit cancellation using `uv_cancel`, but they do support implicit cancellation when the handle is closed via `uv_close`.

When you call `uv_write`, we try to write immediately, and often succeed, but the callback is made asynchronously. So even if you call `uv_write` and immediately after `uv_close`, the write miught have succeeded and the callback will be called with a successful error code. Which is why the assert you added blows up.

I'm not aware of any issue in this area. If you can write a test exhibiting the issue I can look into it, but what you're currently testing is incorrect.

**Comment by 2ix** [comment]
@saghul The libuv sample gives a similar situation we are experiencing in our application.

For example whether it be writing to the `client` or writing to the `upstream` when it's counterpart disconnects/timeout https://github.com/libuv/libuv/blob/v1.x/samples/socks5-proxy/client.c#L536 is called setting `c_dead` properties. As you said the `uv_write` callback is still called with a successful error code and thus https://github.com/libuv/libuv/blob/v1.x/samples/socks5-proxy/client.c#L715 is triggered due to `c_dead` being set.

This happens in the sample application and our own and we're not sure how to handle this as the same also indicated use of `UV_ECANCELED`.

Is the best solution just to return in the same callback if `c_dead` is set?

**Comment by saghul** [comment]
@2ix That sample hasn't been modified in the last couple of years, unfortunately. IIRC writing immediately in `uv_write` was added after, and the sample might have some builtin assumptions which no longer hold true.


> Is the best solution just to return in the same callback if c_dead is set?

I only had a quick look, but I'd say so.

**Comment by 2ix** [comment]
@saghul What are the reasons for `uv_write` not supporting `UV_ECANCELED` in the same way `uv_connect` does even if the write was successful it would be great to know it was cancelled when it's handle was `uv_close` in the same loop interation.

**Comment by 2ix** [comment]
Eg: https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-connect-timeout.c#L42

it's very elegant, even though connect may have succeeded because `uv_close` was called on the tcp handler, the connect callback sets the status to `UV_ECANCELED`.

Perhaps `uv_write` could behave in a similar fashion because even though it may have written, if we have `uv_close` and the callback is still called because we closed before the write callback completed, it would be great to know we have cancelled it in the same fashion?

**Comment by saghul** [comment]
> What are the reasons for uv_write not supporting UV_ECANCELED in the same way uv_connect does even if the write was successful it would be great to know it was cancelled when it's handle was uv_close in the same loop interation.

It does support it. You need to consider the fact that `uv_write` might succeed **immediately**, but the callback will always be async. So if you succeeded to write and then closed the connection it would incorrect to give a UV_ECANCELED error, because the write did succeed.

**Comment by saghul** [comment]
> Perhaps uv_write could behave in a similar fashion because even though it may have written, if we have uv_close and the callback is still called because we closed before the write callback completed, it would be great to know we have cancelled it in the same fashion?

I strongly disagree. The data arrived at the other end, we cannot say it didn't.

**Comment by 2ix** [comment]
I strongly disagree. The data arrived at the other end, we cannot say it didn't.

You make a very strong point. Okay, we will check for the `c_dead` property in the callback. Is having a `CONTAINER_OF` macro the right approach to pass a `struct` between callbacks as per the sample, or is there a new methodology since then?

**Comment by saghul** [comment]
I quickly browsed to the code, and I think I know where you're coming from.

Even if the connect succeeded immediately, we always defer its processing, so if `uv_close` is called we'll always say it was cancelled. When you call `uv_close` the socket is closed, so saying that the connection succeeded would be weird. Saying which which writes succeeded before the connection was closed is important, of course, because the data was actually received.

**Comment by saghul** [comment]
> Is having a CONTAINER_OF macro the right approach to pass a struct between callbacks as per the sample, or is there a new methodology since then?

It's a lot more elegant than storing pointers to containing elements in `data` :-)

**Comment by 2ix** [comment]
@saghul Great, thank you! :) Really loving libuv it's an amazing piece of engineering. Thank you for your help.

**Comment by saghul** [comment]
:heart_eyes:

**Comment by 2ix** [comment]
@saghul I'm not able to create a pull request from this machine currently but we will need to update https://raw.githubusercontent.com/libuv/libuv/v1.x/docs/src/handle.rst "In-progress requests, like uv_connect_t ~~or uv_write_t~~, are cancelled and have their callbacks called asynchronously with status=UV_ECANCELED."

**Comment by saghul** [comment]
But that is still correct. If the write request is in progress, that is. If it was immediately completed it will have the right status value. I you call `uv_write` 10 times in a row, you'll get UV_ECANCELED for 9 of them.

**Comment by 2ix** [comment]
Okay I see, I really misunderstood this in the documentation then. Thank you again.
