### ISSUE TITLE
UV_VERSION_IS_RELEASE is 1 in non-release builds

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#523]
Since commit feb2a9e6 ('`2014.11.21, Version 1.0.0 (Stable)`'), `UV_VERSION_IS_RELEASE` has always been set to 1.  Perhaps there is a bug in the release tool?

**Comment by saghul** [comment]
Oh. I think this is due to the fact that we no longer commit "working on X.Y.Z", because we bump the version at release o'clock.

We could make the release tool reset it back to 0 and commit the change as a last step of making the release.

**Comment by saghul** [comment]
FWIW, I pushed this: https://github.com/libuv/libuv/commit/e2db9240db78ba30f02fd130b170d08e0d9d6e62

**Comment by cjihrig** [comment]
Can this be closed? It looks like `UV_VERSION_IS_RELEASE` is [currently](https://github.com/libuv/libuv/blob/840a8c599ec1f138992a538f5b8109f91f31805e/include/uv-version.h#L36) `0`. The release process also has instructions [now](https://github.com/libuv/libuv-release-tool/blob/2236bc95fde5f710cca8afd317526b4dc9bf9118/README.md), including step 9, which makes sure this is set back to `0`.

**Comment by saghul** [comment]
Ideally I'd like to close this once it's automatic, as it was before.

**Comment by bnoordhuis** [comment]
I'm closing this because of 2.5 years without any activity but please reopen if needed.
