### ISSUE TITLE
libuv thinks any TTY is /dev/tty

### ISSUE THREAD

**Issue by Gottox** [libuv/libuv#526]
I'm the author of [child_pty](https://github.com/Gottox/child_pty) a pty API for node.js. It's my intend to keep the source as small as possible and reuse most of nodes own code.

To wrap input and output functions I discovered an interesting behavior of libuv: If I was using node tty.ReadStream or tty.WriteStream node seemed to ignore the fd (which was a PTYs master fd) and all output was printed to stdout instead.

Reading libuv's source I discovered the reason for this behavoir:

The tty.*Stream classes call `uv_tty_init` which checks the type of a the fd. For a pty this type is UV_TTY. Unfortunately libuv assumes, that an fd of the type UV_TTY is always its own tty and therefore reopens /dev/tty. [See this comment for the explaination](https://github.com/libuv/libuv/blob/v1.x/src/unix/tty.c#L54-L63)

This behavior may be true for most usages but when feeding a PTYs master fd into this function results in opening the wrong tty.

**Comment by bnoordhuis** [comment]
What do you suggest as a solution?  You can find the motivation for libuv's behavior in the commit log of b197515367d1a996dca9009483d202b306f9474e.

**Comment by Gottox** [comment]
libuv should only reopen /dev/tty if it's sure, that the given fd is bound to this tty.

A naive implementation would check if the fd is <= 3. But this would break all dup'ed fds.

**Comment by Gottox** [comment]
Speaking of dup... I'm not sure if this would have any side effects but would dup(fd) have the same effect as open("/dev/tty", ...)?

**Comment by Gottox** [comment]
Steps to reproduce
------------------------------

Compile this program and run it:

```c
// cc -luv -lutil pty_bug.c -o pty_bug

#include <uv.h>
#include <pty.h>
#include <stdlib.h>
#include <stdio.h>

void on_write(uv_write_t* req, int status) {
	printf("Write Done\n");
}

int main(int argc, char *argv[]) {
	int master, slave;
	struct winsize w;
	uv_loop_t *loop = uv_default_loop();
	uv_buf_t b = { .base = "This should go to the PTY\n", .len = 26 };
	uv_write_t req = { 0 };
	uv_tty_t tty = { 0 };

	openpty(&master, &slave, NULL, NULL, &w);
	uv_tty_init(loop, &tty, master, 1);
	uv_write(&req, (uv_stream_t*) &tty, &b, 1, on_write);
	uv_run(loop, UV_RUN_DEFAULT);
}
```

Expected behavior
------------------------------

The string `This should go to the PTY` should be written to the newly created PTY and therefore not be visible on the screen.

Actual behavior
-------------------------

The string appears on the tty of the current program.

**Comment by saghul** [comment]
We reopen it if `isatty` returns 1. @Gottox do you know what extra check would be required to know if the tty is (or isn't) the current one? Also, we'd have to be careful not to break existing behavior.

Alternatively, we could have some `uv_tty_open` which blindly takes the fd without checks, a la `uv_tcp/udp/pipe_open`.

**Comment by Gottox** [comment]
A naive implementation would just check fd <= 3. But as I said, this breaks dup'ed fds and is no real guarentee.

I just tested on Linux: You can fstat `0`, fstat `fd`, and compare its inodes. If they are the same, the fd is a dup of 0 (stdin). I don't know if that's portable.

**Comment by Gottox** [comment]
This should do the job: (pseudocode, unchecked)

```c
struct stat ttyStat, fdStat;
int tty_fd = 0; // or 1 or 2...
fstat(tty_fd, &ttyStat);
fstat(fd, &fdStat);

if(ttyStat.st_ino == fdStat.st_ino) {
  // fd points to /dev/tty, reopen.
}
```

**Comment by Gottox** [comment]
```c
int is_own_tty(int fd) {
	int tty_fd = 0;
	struct stat tty_stat, fd_stat;
	for(; tty_fd < 3 && !isatty(tty_fd); tty_fd++);
	if(tty_fd == 3)
		return 0;
	if(fstat(tty_fd, &tty_stat) < 0 || fstat(fd, &fd_stat) < 0)
		return 0;
	return tty_stat.st_ino == fd_stat.st_ino;
}
```

**Comment by bnoordhuis** [comment]
I think we'd entertain a pull request.  I do kind of worry it may end up fixing one use case while breaking another...

**Comment by brodybits** [comment]
I would favor the idea by @saghul to add another function such as `uv_tty_open` that handles this case.

**Comment by saghul** [comment]
Closing since this continues in #528
