### ISSUE TITLE
Assert in Windows tests

### ISSUE THREAD

**Issue by davencsas** [libuv/libuv#529]
I am seeing an assertion failure when running the benchmark tests on Windows at this location:

https://github.com/libuv/libuv/blob/v1.x/test/test-pipe-getsockname.c#L233

With release builds (64-bit) created with VS2015, the returned length from the preceding function call is 0 so the assert is actually checking 1 byte ahead of the buffer. Memory is zero whenever I execute the test with release builds so the assert fails. When I run with debug builds, this memory is filled with garbage so the assert passes even though it is actually checking outside the buffer.

Here is the specific test that fails and the output:

run-tests.exe pipe_getsockname_blocking pipe_getsockname_blocking

Assertion failed in test\test-pipe-getsockname.c on line 233: buf1[len1 - 1] != 0

*Note* - I disabled 'Whole Program Optimization' and 'Link Time Code Generation' in the release builds since our code will be built outside of Visual Studio and therefore cannot really leverage these features. Also, the VS2015 compiler was doing some strange things in this part of the test code when those options were enabled which is unnecessarily for debugging this issue. Disabling these options simplifies debugging and the assert fails in either case.

  -Dave

**Comment by whitlockjc** [comment]
I am unable to reproduce this.  I just built the latest `v1.x` branch with VS2015 on Windows 7 64-bit and the whole test suite runs without issue.

**Comment by whitlockjc** [comment]
I cannot reproduce this with VS2013.  In my attempt to test using VS2015, my Windows VM borked and now I don't have an environment for testing.  I'm afraid I'm unable to help until I get Windows back installed and setup.

**Comment by whitlockjc** [comment]
I got my environment back up.  I am not able to reproduce the failure with VS2013 or VS2015.

**Comment by orlp** [comment]
I can reproduce this using MSYS2.

    cd ~
    git clone https://github.com/libuv/libuv
    cd libuv
    ./autogen.sh
    ./configure
    make
    make check

After installing the proper packages (autoconf, automake, libtool, build-essential, probably others.

**Comment by t-mat** [comment]
Hi, I've got same assertion failure (Win7 Pro SP1, VS2015, x64 Release build).

```
`pipe_getsockname_blocking` failed: exit code 3
Output from process `pipe_getsockname_blocking`:
Assertion failed in test\test-pipe-getsockname.c on line 233: buf1[len1 - 1] != 0
```

In my environment, `uv_pipe_getsockname()` returns `len1 == 0` and second `ASSERT(buf1[len1 - 1] != 0);` have been failed (out of bounds).
Here, `uv_pipe_t.flags & UV_HANDLE_CONNECTION != 0`, it seems that `src/win/uv_pipe_getsockname()` [set `len1 = 0` and returns `0` intentionally](https://github.com/libuv/libuv/blob/baf700acdb58c1294b1d7a2403a3fde694ce50f0/src/win/pipe.c#L2089-L2093).
`src/unix/uv_pipe_getsockname() --> uv__pipe_getsockpeername()` also [sets `*size = 0` for the failure, but it always returns `-errno`](https://github.com/libuv/libuv/blob/baf700acdb58c1294b1d7a2403a3fde694ce50f0/src/unix/pipe.c#L223-L226).

So, I would like to change these `ASSERT`s something like this :

```C
TEST_IMPL(pipe_getsockname_blocking) {
  ...

  len1 = sizeof buf1;
  r = uv_pipe_getsockname(&pipe_client, buf1, &len1);
  ASSERT(r == 0);
- ASSERT(buf1[len1 - 1] != 0);
+ ASSERT(len1 == 0 || buf1[len1 - 1] != 0);

  ...

  len2 = sizeof buf2;
  r = uv_pipe_getsockname(&pipe_client, buf2, &len2);
  ASSERT(r == 0);
- ASSERT(buf2[len2 - 1] != 0);
+ ASSERT(len2 == 0 || buf2[len2 - 1] != 0);

  ...
}
```
