### ISSUE TITLE
Force "last" callback added via uv_async_send and uv_queue_work to be called immediately

### ISSUE THREAD

**Issue by webarchymeta** [libuv/libuv#533]
We are using [edge](https://github.com/tjanczuk/edge) that allows inter-calls between nodejs and .NET in a data service. "edge" uses `libuv's uv_async_send` to pass call messages between the two "worlds".

It works flawlessly using nodejs 0.10.* and problems start to appear after upgrading to nodejs 0.12.* which is bundled with a newer version of `uvlib`. The problems manifest in long delays between calls and responses in the "last" call in a sequence of calls which is followed by a idle period. It looks like the last one is invoked based on some kind of timeout mechanism which contradicts the event driven philosophy of the libuv. Otherwise it has to be manually flushed, but there appears to be no method of doing so within the libuv. I have tested in both Windows 64/32 bit systems and in a 64 bit Linux system. Their behavior are similar. I known `uv_async_send` does not have to invoke the callback immediately is a "feature" by design, but waiting for around 1 minute for an API type of service to response is many bits of toooo long! They become useless.

My question is: 1) is there a way to force immediate invocation of the callbacks after entering them into `uv_async_send` or `uv_queue_work` in the next loop tick? 2) if not, could I suggest a feature that allows API developers to do such kind of operation?

**Comment by saghul** [comment]
I don't know what edge does internally, but unless there is bug hidden somewhere (which would have probably manifested by now anyway) `uv_async_send` will wakeup the loop if it's busy polling for i/o. This means that the callback will be executed shorty, unless something (edge perhaps?) locks the i/o loop.

**Comment by webarchymeta** [comment]
The loop is not locked since the system is still responsive. The last callback, which has entered into the long waiting state, will be invoked immediately if there is another callback is added to the loop, the newly added one then may or may not enters the long waiting state. This is not the behavior of the loop been locking up but more like the last call to `uv_async_send` does not wakeup the loop ...

**Comment by saghul** [comment]
Unless you can make a test case demonstrating this I can't really check
anything :-S

On Sun, Sep 20, 2015 at 12:00 PM, Shuqian Ying <notifications@github.com>
wrote:

> The loop is not locked since the system is still responsive. The last
> callback, which has entered into the long waiting state, will be invoked
> immediately if there is another callback is added to the loop, the newly
> added one then may or may not enters the long waiting state. This is not
> the behavior of the loop been locking up but more like the last call to
> uv_async_send does not wakeup the loop ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libuv/libuv/issues/533#issuecomment-141768621>.
>



-- 
/Saúl
bettercallsaghul.com

**Comment by bnoordhuis** [comment]
I'm closing the issue because there isn't anything actionable right now.  If you have more information, please let us know.
