### ISSUE TITLE
libuv release

### ISSUE THREAD

**Issue by 2ix** [libuv/libuv#550]
Whenever I build on Windows/Unix with GYP it creates a `Debug` folder with the static file.
How can I build the `Release` version?

**Comment by saghul** [comment]
You can do `vcbuild.bat help`, which will tell you all the available options for building. `vcbuild.bat release` is the one you're after.

**Comment by 2ix** [comment]
I am able to create a `Release` version for windows with `vcbuild.bat` but how do I create a `Release` version for unix?

```
$ ./gyp_uv.py -f make
$ make -C out
```

I've checked the files, can't figure it out. Maybe update documentation with how to build Unix Release?

**Comment by saghul** [comment]
Hey Ryan, just sent a PR adding this :-) #722

**Comment by saixmh** [comment]
How to make static on Mingw?
I want to use static lib by it.

**Comment by saghul** [comment]
If you build it using autoconf, you'll have a resulting .a file in .libs/ you can link with that.

**Comment by saixmh** [comment]
Thank-you very much. It works well.
