### ISSUE TITLE
feature: add support for mTCP

### ISSUE THREAD

**Issue by mikeal** [libuv/libuv#552]
This is one of the coolest things I've seen. It was sent to me yesterday by @mabels and is pretty exciting.

http://shader.kaist.edu/mtcp/
https://github.com/eunyoung14/mtcp

Essentially, it's a userland TCP/IP stack. Most commercial routers and network applications are now just fancy linux boxes with userland TCP/IP stacks in order to avoid the memcopy between kernel and userland.

If an mTCP option was added to libuv our benchmarks would get incredibly impressive.

**Comment by mikeal** [comment]
This is also an option, it's a bit of a higher level API using C++ promises https://github.com/scylladb/seastar

**Comment by tingting-anne** [comment]
:+1:

**Comment by yjhjstz** [comment]
sounds good, but kernel driver depends.

**Comment by mabels** [comment]
There is a lot kernel stuff in, i'm currently try to figure out what and
how that works

**Comment by leodutra** [comment]
State?

**Comment by saghul** [comment]
I don't think anyone is working on this at the moment.

**Comment by mabels** [comment]
Hey,

I do working on it, it is slow but there are some solved, but I'm still far
away from a plugin play solution.

meno

**Comment by leodutra** [comment]
Great @mabels. I'd like to be good enough in `C`.
Is there any branch?

**Comment by saghul** [comment]
No follow-up, closing. If someone wants to work on this, feel free to send a PR with the API design / implementation.

**Comment by leodutra** [comment]
Oh God... please send Jesus to implement this.
