### ISSUE TITLE
win: uv_tcp_connect union timeout bug. Unix not effected.

### ISSUE THREAD

**Issue by 2ix** [libuv/libuv#556]
As I have been using a lot of the unit tests to learn libuv as well as the socks5-proxy sample I have come across a strange scenario that only effects Windows based builds but not Unix.

Consider the following example:
```
#include <stdio.h>
#include <uv.h>

typedef struct {
  union {
    uv_connect_t connect_req;
    struct sockaddr addr;
    struct sockaddr_in addr4;
    struct sockaddr_in6 addr6;
  } t;
} conn;

void conn_connect_done(uv_connect_t *req, int status)
{
  printf("connect done status: %d\n", status);
}

int main()
{
  uv_loop_t *loop = uv_default_loop();

  uv_tcp_t *socket = (uv_tcp_t *) malloc(sizeof(uv_tcp_t));
  uv_tcp_init(loop, socket);

  conn *outgoing = (conn *) malloc(sizeof(conn));

  memset(&outgoing->t.addr4, 0, sizeof(outgoing->t.addr4));
  outgoing->t.addr4.sin_family = AF_INET;
  outgoing->t.addr4.sin_addr.s_addr = inet_addr("209.213.221.170");
  outgoing->t.addr4.sin_port = htons(80);

  printf("connect to %d.%d.%d.%d:%d\n",
    outgoing->t.addr4.sin_addr.S_un.S_un_b.s_b1,
    outgoing->t.addr4.sin_addr.S_un.S_un_b.s_b2,
    outgoing->t.addr4.sin_addr.S_un.S_un_b.s_b3,
    outgoing->t.addr4.sin_addr.S_un.S_un_b.s_b4,
    ntohs(outgoing->t.addr4.sin_port));

  uv_tcp_connect(&outgoing->t.connect_req, socket, &outgoing->t.addr, conn_connect_done);

  if (uv_run(loop, UV_RUN_DEFAULT)) {
    abort();
  }

  return 0;
}
```

With regards to Unix `conn_connect_done` returns a status of `0`, however Windows returns `ETIMEOUT`. This is caused by the union's `connect_req` which is also demonstrated https://github.com/libuv/libuv/blob/v1.x/samples/socks5-proxy/defs.h#L65 in a similar fashion. When connect_req is removed outside the union, Windows behaves as expected.

Any idea or suggestion why Windows is having a problem with this implementation but not Unix? Is there quite a different implementation of how the `uv_connect_t` is handled for Windows?

**Comment by TomCrypto** [comment]
Take a look at https://github.com/libuv/libuv/blob/v1.x/src/win/tcp.c#L744 for windows (the unix code does not have this problem), you can see at line 780 it initializes `req` and later on at line 786 it's still using `addr`. Boom. I would personally not use this construct, it's quite dangerous and imposes quite a lot of implementation details on the internals of libuv (must be able to read parameters "in the correct order" and so on, which generally ends up translating to functions doing preventive copies all over the place...)

**Comment by 2ix** [comment]
Alright thank you, I will move `uv_connect_t` outside of the union. Appreciate the support :)

**Comment by saghul** [comment]
Since you're there, use `struct sockaddr_storage` for everything. Is guaranteed to be big enough, and you can cast it to `struct sockaddr*` as needed.

**Comment by 2ix** [comment]
@saghul Thank you for the great advice :D
