### ISSUE TITLE
Remain handle in loop's handle_queue.

### ISSUE THREAD

**Issue by nakdai** [libuv/libuv#560]
It looks that 'uv_udp_t' handle remains in loop's handle_queue.
So, `uv_loop_close` returns always UV_BUSY.
I searched `QUEUE_REMOVE` in libuv codes, but I couldn't find it to remove handle from loop's handel_queue.

```C++
uv_loop_init(uv_default_loop());
uv_udp_t udp;
uv_udp_init(uv_default_loop(), &udp);
uv_loop_run(uv_default_loop(), UV_RUN_DEFAULT);
uv_close((uv_handle_t*)&udp, NULL);
uv_stop(uv_default_loop());
uv_loop_close(uv_default_loop());
```

**Comment by bnoordhuis** [comment]
In your example, the handle isn't fully closed yet by the time you call `uv_loop_close()`.  If you drop the `uv_stop()` call and insert a second call to `uv_run()` after `uv_close()` but before `uv_loop_close()`, it should work like you want it to.

**Comment by nakdai** [comment]
Thank you for your reply.
I could confirm what you explained.

Regards.
