### ISSUE TITLE
fs: meet assert in uv__close 

### ISSUE THREAD

**Issue by yjhjstz** [libuv/libuv#563]
> node: ../deps/uv/src/unix/core.c:477: uv__close: Assertion `fd > 2' failed.
Aborted (core dumped)

fd value is 1. Probably, somewhere closed `stdout`.  I found windows platform handled close 0-2, but unix not. see https://github.com/piscisaureus/libuv-1/commit/c619f37c3986b0ec5d13fb7f2437dff0db41c72b 

here is pr: #562

**Comment by yjhjstz** [comment]
cc @saghul , could you please give some suggestion?

**Comment by saghul** [comment]
Closing, continues in #562.
