### ISSUE TITLE
`getaddrinfo_fail` failed: exit code 134  `getaddrinfo_fail_sync` failed: exit code 134 

### ISSUE THREAD

**Issue by rongp** [libuv/libuv#564]
i got this error on ubuntu15:
=============================================================
[%  61|+ 168|-   0|T   0|S   0]: getaddrinfo_fail
`getaddrinfo_fail` failed: exit code 134
Output from process `getaddrinfo_fail`:
Assertion failed in test/test-getaddrinfo.c on line 43: status < 0
=============================================================
[%  61|+ 168|-   1|T   0|S   0]: getaddrinfo_fail_sync
`getaddrinfo_fail_sync` failed: exit code 134
Output from process `getaddrinfo_fail_sync`:
Assertion failed in test/test-getaddrinfo.c on line 108: 0 > uv_getaddrinfo(uv_default_loop(), &req, NULL, "xyzzy.xyzzy.xyzzy", NULL, NULL)
=============================================================
[%  66|+ 182|-   2|T   0|S   0]: spawn_exit_code
[%  86|+ 236|-   2|T   0|S   0]: fs_event_watch_dir_recursive
`fs_event_watch_dir_recursive` skipped
Output from process `fs_event_watch_dir_recursive`:
Recursive directory watching not supported on this platform.
=============================================================
[% 100|+ 272|-   2|T   0|S   1]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:3984: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/rongp/src/libuv'
Makefile:4240: recipe for target 'check-am' failed
make: *** [check-am] Error 2

**Comment by bnoordhuis** [comment]
Am I right that `dig xyzzy.xyzzy.xyzzy` resolves to _something_ on your machine?  That's what is making the test fail.

**Comment by rongp** [comment]
@bnoordhuis 

$ dig xyzzy.xyzzy.xyzzy

; <<>> DiG 9.9.5-11ubuntu1-Ubuntu <<>> xyzzy.xyzzy.xyzzy
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48276
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;xyzzy.xyzzy.xyzzy.		IN	A

;; ANSWER SECTION:
xyzzy.xyzzy.xyzzy.	25	IN	A	124.232.132.94

;; Query time: 181 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Thu Oct 08 17:32:41 CST 2015
;; MSG SIZE  rcvd: 62

**Comment by bnoordhuis** [comment]
Right, that's what I expected.  I'm going to close this but thanks for taking the time to report the issue.
