### ISSUE TITLE
can it support embedded linux?

### ISSUE THREAD

**Issue by RuyiDu** [libuv/libuv#568]
You know the embedded linux use uclib always, but uclib don't implement "ifaddrs" api, it don't have ifaddrs.h and ifaddrs.c.

Thanks in advance.

**Comment by bnoordhuis** [comment]
What version of uclibc is that?  There is a uclibc check in src/unix/linux-core.c but apparently it's not working for you.

**Comment by TomCrypto** [comment]
Note that libuv works great with the musl libc which is also used in embedded linux environments, we're using it currently. If your uclibc doesn't have ifaddrs then maybe you should turn that on for libuv in your uclibc configuration...

**Comment by RuyiDu** [comment]
i haven't check my ulibc version carefully,  maybe it's old yet or have some configuration errors. I already find some third-code to implement it in the first and look like can work now, i don't wanna spend time on it until it can't work fine.

thank you guys, i like to present more information about it in my spare time.

**Comment by bnoordhuis** [comment]
I'm going to assume this is working for you now.  If not, please let us know.
