### ISSUE TITLE
multicore libuv tcp server

### ISSUE THREAD

**Issue by 2ix** [libuv/libuv#570]
I've written a singled threaded `uv_default_loop()` tcp server and I am curious if there are any examples out there how to expand this to use all available cores of the server? Multiple loops? How this may be achieved?

Any advice is much appreciated.

**Comment by willemt** [comment]
Hi, you might want to look into using a pipe to pass the listen socket to multiple threads. You might get mileage out these two projects as examples *(disclaimer: I wrote these)*:
https://github.com/willemt/uv_multiplex
https://github.com/willemt/pearldb

I think this is what Haywire does to get multiple threads working: https://github.com/kellabyte/Haywire/blob/master/src/haywire/connection_dispatcher.c
https://github.com/kellabyte/Haywire/blob/master/src/haywire/connection_consumer.c

**Comment by bnoordhuis** [comment]
Closing because it's answered.

@2ix Can you use the mailing list next time?  Thanks.

**Comment by saghul** [comment]
For completeness, if you are fine with your code working on Linux only and have a recent enough kernel (>= 3.9 IIRC) you can create the socket early with `uv_tcp_init_ex`, set `SO_REUSEPORT`, create multiple threads and let the kernel do the balancing.
