### ISSUE TITLE
windows vs unix performance

### ISSUE THREAD

**Issue by 2ix** [libuv/libuv#571]
I've written a test proxy similar to https://github.com/libuv/libuv/tree/v1.x/samples/socks5-proxy and I've been comparing performance between Windows and Unix.

I'm curious if https://github.com/libuv/libuv/blob/v1.x/samples/socks5-proxy/client.c#L668 `CONTAINER_OF` macro has any performance impact between Windows/Unix because on Unix I am able to max out at 100mb/s however using the exact same codebase Windows pulls around 35mb/s.

**Comment by bnoordhuis** [comment]
The short answer is no, it's not that macro.  If you want a longer answer, please use the mailing list. :-)
