### ISSUE TITLE
Usage of uv_ip6_name() is not reversible - looses sin6_scope_id/interface-name

### ISSUE THREAD

**Issue by lhecker** [libuv/libuv#582]
While trying to setup a multicast UDP socket on every network interface (which is required at least on OS X) I noticed a unfortunate problem:
`uv_interface_addresses(uv_interface_address_t**, int*)` returns a list of `sockaddr` structs which must be turned into strings for the use with `uv_udp_set_membership(uv_udp_t*, const char*, const char*, uv_membership)` using for instance `uv_ip6_name()`.

If you use uv_ip6_name()` the `sin6_scope_id` information will be lost though, since the function ignores it.

`uv_udp_set_membership()` then turns the string back into a `sockaddr_in6` struct using `uv_ip6_addr()`. Due to the previous `uv_ip6_name()` the interface name will be missing and the correct `sin6_scope_id` won't be set and thus multicast won't work on OS X.

To fix this I see 3 options:
- Don't fix it and require users to use `if_indextoname()` to append the interface name to the string returned by `uv_ip6_name()`.
- Modify `uv_ip6_name()` to add the correct interface name.
- Add another `uv_udp_set_membership_*()` method which makes it possible to pass a `sockaddr` directly instead. This could also be extended to do the same for other methods from the `uv_udp_*` set.

(I personally prefer the last option.)

Let me know what you guys think about this and I'd be willing to submit a PR as soon as I get to it. :smiley:

**Comment by bnoordhuis** [comment]
> Modify uv_ip6_name() to add the correct interface name.

I don't think that's an option.  It doesn't do I/O currently and I'd like to keep it that way.  Looking up the interface would add all kinds of failure modes.

What's more, I don't think it's currently mandatory to have the sin6_scope_id field set to a legal value.  That could break existing users.

> Add another `uv_udp_set_membership_*() `method which makes it possible to pass a sockaddr directly instead. This could also be extended to do the same for other methods from the uv_udp_* set.

I can live with that up to a point but a proliferation of uv_udp_foo2 functions would surely make me sad.

@saghul WDYT?

**Comment by lhecker** [comment]
BTW: The obvious solution is of course to just not use link local addresses coming from `uv_interface_addresses()`, but I'd still consider it a unneccessary flaw in libuv to use C strings as params instead of the "native" value - the `sockaddr` struct (e.g. the bind and listen functions accept `sockaddr` already just like the interface address method is returning those instead of strings).

**Comment by deleisha** [comment]
As read on some unmemorable RFC long back, I would prefer `uv_ip6_name` returning a string like 
`fe80:1%eth0` or `fe80:1%12` in case of link-local address. 

@bnoordhuis 
If it is not backward compatible, Are you open to consider it for main branch?

**Comment by bnoordhuis** [comment]
See my reply above about keeping it I/O-free.  A variant or flag might be acceptable though.

**Comment by deleisha** [comment]
Ohk, I am with @lhecker then to pass `sockaddr`

**Comment by deleisha** [comment]
Anyway uv_ip6_addr is zone id aware. Won't it be nicer to have the opposite in uv_ip6_name.

**Comment by lhecker** [comment]
**Offtopic**:
Might I note that @piscisaureus (snarky) comment at https://github.com/libuv/libuv/blob/a59085e140d52076960fd2ee84875577378abc62/src/inet.c#L70 is factually incorrect?
Types like `int16_t` not just guarantee to be of that exact size (padding is forbidden), but also for instance guarantee to use the two’s complement representation (which isn't for e.g. `int`). Otherwise they must not be specified by the stdlib of the system (see §7.18.1.1 of N1256).
Instead correct would be to say that e.g. on ARM architectures you can't read unaligned memory which might make pointer overlays a bad idea.

**Comment by saghul** [comment]
@lhecker that code was not written by him, look at the copyright notices at the top ;-)

**Comment by saghul** [comment]
> I can live with that up to a point but a proliferation of uv_udp_foo2 functions would surely make me sad.

Agreed. Now, when we branch v2.x we could make foo2 be the new foo, like we did with `uv_run|uv_run2` a long time ago.

**Comment by piscisaureus** [comment]
@lhecker my comment?

**Comment by lhecker** [comment]
Thanks for the clarification @saghul! :smiley: It's kinda strange for a organization like the ISC to make such an obvious mistake...

> Agreed. Now, when we branch v2.x we could make foo2 be the new foo, like we did with uv_run|uv_run2 a long time ago.
That would be great!

_By the way:_
For the time being I wrote my own `interface_addresses` method which is capable to filtering out temporary, link-local, etc. IPv6 addresses and thus I'm currently not really hitting this "bug":
* https://github.com/lhecker/libnodecc/blob/master/include/libnodecc/os/interface_addresses.h#L35
* https://github.com/lhecker/libnodecc/blob/master/src/os/interface_addresses.cc#L70

Unfortunately it's still BSD & Linux only, but I think that having blacklist/whitelist parameters like this would be a great addition to libuv too. Especially since the `uv_interface_addresses()` code is quite redundant between the different platforms. If you have interest in this I could rewrite it in plain C.

**Comment by lhecker** [comment]
@piscisaureus I'm not sure if I should apologize to you now for saying that "your" comment was snarky, but... It wasn't meant in a mean way - I said it because it catched my eye while reading the code. :smile:

**Comment by saghul** [comment]
@lhecker maybe you can provide some feedback here: https://github.com/libuv/libuv/pull/219

**Comment by saghul** [comment]
Nothing actionable here? Closing. Holler if we need to reopen this.
