### ISSUE TITLE
fs_event_watch_dir_recursive is failing with VS > 2010

### ISSUE THREAD

**Issue by whitlockjc** [libuv/libuv#587]
libuv on Windows builds with VS2010 by default so when we previously fixed `fs_event_watch_dir` and `fs_event_watch_dir_recursive` for #30 everything was fixed appropriately.  But when you attempt to build/test using VS2013/VS2015, you run into the same flakiness.

I'll look into this but I wanted to report this for tracking purposes.

**Comment by whitlockjc** [comment]
Realize that VS2013/VS2015 might not be officially supported but since you can't install old versions of VS anymore, it's all I have.  I'm currently trying to track down the Visual C++ 2010 compilers/libraries.

**Comment by whitlockjc** [comment]
@saghul Can we add the `windows` label?

**Comment by whitlockjc** [comment]
Also, I forgot to mention but the failure is a timeout with no extra details.

**Comment by whitlockjc** [comment]
After some digging around, I see the `uv_fs_event_cb` for the test is being called an extra 16 times.  I'm digging into it.  Might not be related to VS2013/VS2015 but my old VS2010 environment didn't have this issue.

**Comment by whitlockjc** [comment]
For grins I checkout out the fix to #30, which included work on Windows as well, and it fails to run the tests on VS2013/VS2015.

**Comment by whitlockjc** [comment]
[This thread](http://stackoverflow.com/questions/14036449/c-winapi-readdirectorychangesw-receiving-double-notifications) could be important.  I am trying to track down if this is a known change from the different versions of the C++ library used to compile.  If it is, it's a simple fix because the create and delete events are as expected but maybe the *extra* events are just shadow events showing that the directory changed.  Digging deeper.

**Comment by whitlockjc** [comment]
I've got some ideas but before I spend more time on this, I'd love to confirm this is an actual issue.  Any way to kick off a CI build for master?

**Comment by bnoordhuis** [comment]
Assuming you mean v1.x: https://ci.nodejs.org/view/libuv/job/libuv+any-pr+multi/166/

@nodejs/build Can you give @whitlockjc a CI account?

**Comment by bnoordhuis** [comment]
@jbergstroem @rvagg Can you give @whitlockjc a CI account?

**Comment by rvagg** [comment]
is @whitlockjc a libuv member? doesn't show up here as Collaborator or Owner.

**Comment by bnoordhuis** [comment]
He's not.  Does that matter?

**Comment by jbergstroem** [comment]
I can't figure out delegating access to only starting libuv jobs, so I guess where @rvagg might be going is a "trust" issue. I'll keep digging.

**Comment by whitlockjc** [comment]
@bnoordhuis @jbergstroem @rvagg No need to break protocol or go through a lot of extra effort for this.

This only seems to be an issue when building libuv with VS2013 or VS2015 *(extra `fs_event` created from creating files)* so until we officially support building on those environments, or at least have CI environments to build libuv using them, this likely isn't going to manifest or matter.

**Comment by whitlockjc** [comment]
Updated the issue to be any VS greater than 2010 as VS2012 fails as well.  I'm not sure if it's an OS configuration or what but this is the same VM I used to work on #30.  I do think the test is flawed and should be fixed regardless.  Long story short, `ReadDirectoryChangesW` can report multiple events for a single filesystem interaction and that is what's going on with this test.  Since the test closes the handle/timer after 32 fs events, we don't actually ensure that our 16 creates and 16 deletes were completed.  Updating the test to handle this should be idea.

**Comment by bnoordhuis** [comment]
That sounds quite plausible.  A pull request would be most welcome.

**Comment by whitlockjc** [comment]
Already on it.  :)

**Comment by whitlockjc** [comment]
Done.  No rush.

**Comment by whitlockjc** [comment]
For those following along, when using `ReadDirectoryChangesW` to watch a directory recursively, you can end up with overlapped events.  This is handled in libuv but the test was not written to expect *more* `fs_event_cb` invocations than the number of files created/removed.

When looking into this, I noticed that the current tests will pass even if not all create/remove requests are handled because of this so I updated the test logic to ensure all creates/removes are handled as well as handling these extra `fs_event_cb` invocations.  Based on my debugging, I'm not sure of a better, more isolated way to do this but I'm open to opinions.

**Comment by saghul** [comment]
Continues in #589
