### ISSUE TITLE
Replace EALREADY with EBUSY in udp_recv_start?

### ISSUE THREAD

**Issue by phillipj** [libuv/libuv#591]
Hi! I'm going through some of your `TODO`s and found this one from @bnoordhuis in [unix/udp.c#L847](https://github.com/libuv/libuv/blob/bf52579f92c30cb6ebb65a007b4f0dab9f135695/src/win/udp.c#L847):

```c
if (uv__io_active(&handle->io_watcher, UV__POLLIN))
  return -EALREADY;  /* FIXME(bnoordhuis) Should be -EBUSY. */
```

Guessing it would be a breaking change. Is this worth the effort changing or should the todo be removed?

**Comment by bnoordhuis** [comment]
It would be possible to change it for libuv v2.x but there is no ETA for that.  There are a few more places where EALREADY is returned where EUBUSY would be more appropriate, both in the UNIX code and the Windows code.

**Comment by phillipj** [comment]
Thanks for answering quickly! Is it too early to open a PR for changes meant for v2.x?

**Comment by bnoordhuis** [comment]
No, you're welcome to file one.  I'll review it but it may be a while before we can land it.

**Comment by phillipj** [comment]
:+1:
