### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [libuv/libuv#593]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/libuv/libuv/blob/455c4035d40cc60390cddff0b920da43c4b55cd4/configure.ac#L40 "Configuration checks")?

**Comment by bnoordhuis** [comment]
Bot.  Closing.
