### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [libuv/libuv#595]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [uv__getaddrinfo_done](https://github.com/libuv/libuv/blob/764877fd9e4ea67c0cbe27bf81b2b294ed33b0f5/src/win/getaddrinfo.c#L90)
* [uv_dlclose](https://github.com/libuv/libuv/blob/764877fd9e4ea67c0cbe27bf81b2b294ed33b0f5/src/unix/dl.c#L41)
* [uv_set_process_title](https://github.com/libuv/libuv/blob/764877fd9e4ea67c0cbe27bf81b2b294ed33b0f5/src/unix/openbsd.c#L163)

**Comment by deleisha** [comment]
+1 yup, free(NULL) does not do anything.

**Comment by saghul** [comment]
Thanks for the report! (I know this was written by a bot, but machines also deserve some love!). At any rate, continues in #604.
