### ISSUE TITLE
Selection of a directory for auxiliary build tools

### ISSUE THREAD

**Issue by elfring** [libuv/libuv#596]
I suggest to add [the call of the macro "AC_CONFIG_AUX_DIR"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Input.html#index-AC_005fCONFIG_005fAUX_005fDIR-58 "Storage for auxiliary build tools") to [your configuration script](https://github.com/libuv/libuv/blob/455c4035d40cc60390cddff0b920da43c4b55cd4/configure.ac#L17 "Build specification") so that auxiliary build tools will be stored in a dedicated directory.

**Comment by saghul** [comment]
We don't ship those anyway, so there is no need for them to be in a special directory. If someone wants to clean their tree they can do a `git clean -dfx`.
