### ISSUE TITLE
Typo in repository description 

### ISSUE THREAD

**Issue by Hrxn** [libuv/libuv#599]
> Cross-platform asychronous I/O

I guess it's asynchronous

Just landed on the page, that was the first thing I noticed. I'm sorry...

**Comment by deleisha** [comment]
Well, it does the async for all major platform. Hence, an apt description

**Comment by Hrxn** [comment]
?

The description is suitable, I guess.

asychronous
asynchronous

I think "typo" includes spelling, no? At least in common usage.

**Comment by TomCrypto** [comment]
Wow, it's quite remarkable that nobody spotted it until now. Nice find :)

**Comment by bnoordhuis** [comment]
Typo fixed, thanks. :-)
