### ISSUE TITLE
a uv_spawn issue

### ISSUE THREAD

**Issue by jiaqinghao2009** [libuv/libuv#607]
I want to spawn two different processes using uv_spawn, that means funcA will be invoked twice.
When I use libuv-0.11.27, the two processes will be both spawned successfully. When I update libuv to version 1.6.1, 
When I spawn the second process(B process). uv_spawn(loop, child_req, &options) function will invoke CreateProcessA 
and process B will be successfully spawned, but, when SpawnProcess return , process B is missing(or be killed). I do not know what may 
cause this phenomenon. Why libuv version update cause this problem? Tks.  Process A and B have no any relationship.
```c++
Static void funcA()  {
uv_process_t handle = { 0 };
int iRet = MySpawnProcess(command_line, &handle);
ASSERT(iRet == 0 && "error Spawn JobA");    

LOG_WARNING("##SpawnProcess, create JobA success with handle: %d",
                    handle.process_handle);
return;
}

static int MySpawnProcess(char *command_line[], uv_process_t *child_req)  {
  static uv_loop_t *loop = NULL;
  uv_process_options_t options = {0};
  memset(&options, 0, sizeof(uv_process_options_t));
  loop = loop ? loop : uv_default_loop();
  options.file = command_line[0];
  options.args = command_line;
  options.flags |= UV_PROCESS_DETACHED;
  return uv_spawn(loop, child_req, &options);
}
```

**Comment by jiaqinghao2009** [comment]
When uv_spawn return , handle.process_handle's value is 0x00000000(but in libuv source code process.c Line1096 process->process_handle = info.hProcess; this value is like this e.g. 0x000001fe). Then when funcA return, Microsoft Visio studio will pop a dialog box（I debug program）:  A buffer overrun has occurred in MySpawn.exe which has corrupted the program's internal state(dbghook.c Line 62).

**Comment by bnoordhuis** [comment]
`uv_process_t handle` has automatic storage in `funcA()`.  In other words, it ceases to exist once that function returns.  In _other_ other words, you have a bug in your code.

Closing, please use the mailing list next time.
