### ISSUE TITLE
fs.watch behaves differently watching directory on NFS versions 3 and 4

### ISSUE THREAD

**Issue by thinkingdust** [libuv/libuv#609]
Copy of https://github.com/nodejs/node/issues/3645

This behaviour was observed by cloning node on an NFSv4 mount then running the following test:
`./node test/sequential/test-fs-watch.js`
The test fails with a "change" event observed instead of "rename".

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: 'rename' == 'change'
    at FSWatcher.<anonymous> (/sandbox/cornacch/node4x/node/test/sequential/test-fs-watch.js:88:16)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1226:12) 
```

The difference also exists in libuv, visible by making libuv in the deps directory and running the libuv tests.
```
[%  86|+ 237|-   0|T   0|S   0]: fs_event_watch_dir
`fs_event_watch_dir` failed: timeout
Output from process `fs_event_watch_dir`: (no output)
```

On further investigation, I found a difference at the level of inotify on Linux. The attached c files can be used to add a watch on a directory using notify.c and in another shell delete and recreate a file in the directory using open.c. If the file is already existing and open.c is run again then the following difference appears.

With local file system and nfs v3 the events registered are the same:
```
  512 (#define IN_DELETE        0x00000200    /* Subfile was deleted */)
  256 (#define IN_CREATE        0x00000100    /* Subfile was created */)
```

With nfs v4:
```
  512 (#define IN_DELETE        0x00000200    /* Subfile was deleted */)
  2 (#define IN_MODIFY        0x00000002    /* File was modified */)
```

**Comment by saghul** [comment]
If the difference it at Linux inotify level I'm not sure what we can do about it at the libuv level.

**Comment by thinkingdust** [comment]
I thought that might be the case.
I was also unsure about the expected result for the test since creating a subfile in a watched directory seems more like a "change" than a "rename" to me.

**Comment by saghul** [comment]
Closing since there is nothing actionable from the libuv side.
