### ISSUE TITLE
Compile error on illumos/SmartOS

### ISSUE THREAD

**Issue by konobi** [libuv/libuv#612]
As part of the MoarVM build, I'm getting the following compile error on illumos/SmartOS:

3rdparty/libuv/src/unix/core.c:1060:5: error: too many arguments to function 'getpwuid_r'
In file included from 3rdparty/libuv/include/uv-unix.h:37:0,
                 from 3rdparty/libuv/include/uv.h:61,
                 from 3rdparty/libuv/src/unix/core.c:21:
/usr/include/pwd.h:191:23: note: declared here

**Comment by bnoordhuis** [comment]
Works alright with the node.js smartos builds but pull requests nevertheless welcome.

**Comment by saghul** [comment]
Some tests are failing, but compiling seems to work fine: https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=smartos14-64/181/console

**Comment by konobi** [comment]
Ugh... appears that this might be an illumos glitch...
https://www.illumos.org/issues/5363

**Comment by saghul** [comment]
Closing. @konobi since it works on our build bots, but you're welcome to send us a PR if there are some exotic cases that need to be covered.

**Comment by jbergstroem** [comment]
@konobi suggesting you stick with the base64-lts branch of smartos; currently at 14.4.4.
