### ISSUE TITLE
Fallback barrier implementations are not safe to destroy

### ISSUE THREAD

**Issue by richfelker** [libuv/libuv#615]
There seem to be two fallback barrier implementations in libuv, in pthread-fixes.c and threads.c, for systems that lack pthread barriers. Both have a serious class of flaw that can lead to memory corruption: there is no way to determine when it's safe to destroy them without an additional synchronization object to ensure that all waiters have actually left the barrier wait function and will not access its memory again.

The issue and one possible fix are described in detail here:
http://stackoverflow.com/questions/5886614/how-can-barriers-be-destroyable-as-soon-as-pthread-barrier-wait-returns

**Comment by bnoordhuis** [comment]
The Android barrier implementation was contributed from outside.  You're welcome to take a stab at improving it.  Android is not a tier 1 platform for us, it's mostly self-serve.

**Comment by richfelker** [comment]
I'm not using the code so I won't be working on it, but I noticed the issue and wanted to make sure there was a tracker item open for it. Hopefully someone interested in Android or Apple platforms will pick it up.

**Comment by saghul** [comment]
FWIW, I created a "help-wanted" label, which I'm assigning to this one. Anyone feel free to pick this one up. Thanks!

**Comment by kthelgason** [comment]
I took a look at this and it's possible to trigger this bug by introducing a `sleep(3)` in the correct place. It seems that this bug is quite common as I took a look at [OpenBSD's implementation](https://github.com/syuu1228/openbsd-src/blob/master/lib/librthread/rthread_barrier.c) and they seem to be susceptible to this as well.

**Comment by kthelgason** [comment]
I have fixed this issue (I think) in the android implementation in `pthread-fixes.c` but there is another completely different implementation of the same function for OS X in `thread.c`. Would it make sense to coalesce these so we don't have to maintain two different versions of the same code? @saghul

**Comment by bnoordhuis** [comment]
@kthelgason Code deduplication is (almost) always a good thing.

**Comment by kthelgason** [comment]
That was my thinking. It's not immediately obvious to me how to best go about this though. @bnoordhuis would you like to see a separate file with the barrier implementation that's just included on those architectures where it's not implemented by default?

**Comment by kthelgason** [comment]
also, does the CI do android builds? I don't have an android device handy and no way to test that part.

**Comment by bnoordhuis** [comment]
A separate file is probably easiest; it could be a header-only implementation that is included conditionally.

We don't test on Android, there are no Android devices in the CI matrix.
