### ISSUE TITLE
Proposal: Enter the Node.js Foundation

### ISSUE THREAD

**Issue by mikeal** [libuv/libuv#625]
This idea has been kicking around for a while so I've taken the liberty of writing up a draft of the an application for libuv to enter the Node.js Foundation.

https://github.com/nodejs/TSC/pull/17

Let me know if there are any questions. Once the maintainers are happy with the application please note your support in the PR.

**Comment by saghul** [comment]
Hey @mikeal, thanks for bringing this up. Quick question: how does this affect libuv? What are the implications?

Any links where we can read about it would be appreciated. Thanks!

**Comment by bnoordhuis** [comment]
I don't have a strong opinion.  Joining the Foundation would make it easier to obtain travel funds and such but that's not an issue that affects me personally (because I avoid travel and conferences whenever possible.)

**Comment by mikeal** [comment]
This would be the first project to enter the foundation's incubator, so there isn't a ton of information you'll see because this is our first time :)

The documentation we do have is here: https://github.com/nodejs/TSC/blob/master/Project-Lifecycle.md

The focus of incubation is to broaden the contributor base. By joining the project would get a few mentors working on improving contribution policies and process. There's also a ton of groups in the foundation that help support those efforts and improve the contribution, build and release process. There's a ton of build resources with a working group managing those assets. There's an evangelism group that helps promote activities and gets developers focused on any key issues you need contributors on, etc.

The exact process by which all this happens is something we'll figure out as we go along but we do have a ton of resources and a good track record so far of attracting contributors.

**Comment by mikeal** [comment]
We need to come to a decision about this this week. There will be a TSC meeting on Thursday, could the contributors here come to a decision before then?

**Comment by saghul** [comment]
Hi @mikeal, sorry for the belated response, I've been afk for the past week.

I'm onboard with this. The proposal you linked sounds reasonable to me. :+1: 

One note I'd like to make: for quite a while now, libuv has been managed pretty much 100% on volunteer time. I hope joining the foundation will help us get some more help, but I wouldn't want to add much overhead on our (already busy) shoulders.

Thanks for doing this Mikeal!

**Comment by piscisaureus** [comment]
Just for the record - I think we'd have to work out some details, but generally I'm in favor of joining the foundation.

**Comment by saghul** [comment]
@mikeal, can this be closed, now that https://github.com/nodejs/TSC/pull/17 landed?

**Comment by mikeal** [comment]
Yup! :)

BTW, the board approved this on Monday so we're all set :)

**Comment by saghul** [comment]
Kewl!
