### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#630]
I see there has not been a release for a couple of months and I'd like to get a libuv release which includes 
https://github.com/libuv/libuv/pull/539
so that it can be pulled into Node.

**Comment by saghul** [comment]
Hey Michael,

Yeah, things have been a bit slow lately. I opened
https://github.com/libuv/libuv/issues/617 to prepare the new release. A few
PRs are pending, but if we need no follow-up next week I might drop some.

Would that work for you?

On Wednesday, November 25, 2015, Michael Dawson <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I see there has not been a release for a couple of months and I'd like to
> get a libuv release which includes
> #539 <https://github.com/libuv/libuv/pull/539>
> so that it can be pulled into Node.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libuv/libuv/issues/630>.
>


-- 
/Saúl
bettercallsaghul.com
