### ISSUE TITLE
win: fs.watch on a directory omits path for removed and renamed paths

### ISSUE THREAD

**Issue by jorangreef** [libuv/libuv#634]
Apologies for the spew of fs.watch related issues in the last few days, hopefully this will be the last. The recent recursive watch support for Windows has otherwise been working well and is appreciated.

I think it's a known issue that if a file is deleted on Windows, an event is fired with a `NULL` path. If I recall correctly, this was by design, because ReadDirectoryChangesW might give a long form or an 8.3 short name for deleted paths and we wanted to avoid introducing an 8.3 short name some of the time, if we convert to a long name most of the time (https://github.com/libuv/libuv/blob/v1.x/src/win/fs-event.c#L384).

I am working on a backup tool which uses fs.watch to recursively monitor a working tree of 100,000 - 1,000,000 files on Windows. Because Windows may occasionally miss events, and because the tool may crash or not always be on, it keeps a saved state of the tree and scans this periodically to detect events. If any changes are detected by fs.watch, then these paths are passed to the scanner which scans just the relevant subset of the tree.

**The trouble with just setting the path to NULL for deleted events and ignoring the 8.3 short name (if it is provided by Windows), is that this makes it expensive to figure out where the delete happened.** We can't always rely on Windows to emit a change event for the parent folder (whose mtime would have changed) of the deleted path. Otherwise we could have used that to figure out where the delete occurred, and diff against known state for the parent folder to find the deleted child. But because we can't do this reliably (the parent folder changed event is often delayed for more than a minute by ReadDirectoryChangesW) and because the path is set to NULL, we have to do a full rescan of the entire tree.

If the path for a deleted or renamed event was set to the long form or 8.3 short name if available, this would really help, and provide useful information, since we could then scan only subsets of the tree which match against the long form or 8.3 short name, even if it's just a false positive match.

I might be mistaken that ReadDirectoryChangesW does in fact give the long form or 8.3 short name for deleted paths. But if it actually does, then this could be the difference between 50ms to detect a delete and +/- 50 seconds (for very large trees).

I understand it's introducing some craziness into the api (long names most of the time, short names some of the time), but most people using fs.watch understand it's a best-effort api and don't expect libuv to paper over the differences. It would be incredibly useful to have the long form or 8.3 short name if it is provided by ReadDirectoryChangesW.

**Comment by saghul** [comment]
I guess this solves it? https://github.com/libuv/libuv/pull/199

The author didn't continue with the PR, but if you can chime back in after testing it, it might help someone pick it up.

**Comment by jorangreef** [comment]
Thanks @saghul I completely forgot about that, I see I posted there in September already, as well as the same issue previously at https://github.com/joyent/libuv/issues/1479.

I have made a new pull request with updated comments, and commit message.
