### ISSUE TITLE
test thread_rwlock_trylock failing on OS X 10.11

### ISSUE THREAD

**Issue by evanlucas** [libuv/libuv#642]
`abort()` is being called in https://github.com/libuv/libuv/blob/v1.x/src/unix/thread.c#L161-L172.

After some debugging, it appears that `err` is set to `11` which translates to `EDEADLK`.

I looked through the CI and it seems to be failing there pretty often as well.

It looks like this patch fixes it on OS X, but I'm not sure if it will break things on other platforms:

```diff
diff --git a/src/unix/thread.c b/src/unix/thread.c
index c56a317..e6d7dd7 100644
--- a/src/unix/thread.c
+++ b/src/unix/thread.c
@@ -163,7 +163,7 @@ int uv_rwlock_tryrdlock(uv_rwlock_t* rwlock) {
 
   err = pthread_rwlock_tryrdlock(rwlock);
   if (err) {
-    if (err != EBUSY && err != EAGAIN)
+    if (err != EBUSY && err != EAGAIN && err != EDEADLK)
       abort();
     return -EBUSY;
   }
@@ -189,7 +189,7 @@ int uv_rwlock_trywrlock(uv_rwlock_t* rwlock) {
 
   err = pthread_rwlock_trywrlock(rwlock);
   if (err) {
-    if (err != EBUSY && err != EAGAIN)
+    if (err != EBUSY && err != EAGAIN && err != EDEADLK)
       abort();
     return -EBUSY;
   }
```

**Comment by bnoordhuis** [comment]
See the discussion on https://github.com/libuv/libuv/pull/545, our working assumption is a bug in the test.

**Comment by evanlucas** [comment]
Wow. I swear I searched for it. Sorry for the duplicate issue

**Comment by saghul** [comment]
No worries. This has been on my list for a while, I hope to get to it this
week.

**Comment by evanlucas** [comment]
I'll try and take a look this evening as well and see if can make any headway
