### ISSUE TITLE
Any chance of an Ubuntu PPA?

### ISSUE THREAD

**Issue by atrauzzi** [libuv/libuv#643]
Is there any chance that you guys might be able to publish an official PPA for Ubuntu with the latest builds?

Sometimes a tool or platform requires libuv and having to compile by hand can turn people away just due to the inconvenience.

**Comment by saghul** [comment]
I wouldn't personally oppose such an effort, but right now I'm afraid we don't have the time resources to get that going in an "official" capacity. Now, anyone is more than welcome to create a PPA and then we could try to find a way for making it official.

**Comment by atrauzzi** [comment]
Sounds great, I wish I knew of a place where debian packagers congregated so that I could at the very least put the idea out there.

Sadly, I'm just someone who uses the packages, making them seems like a very dark art!

**Comment by lucab** [comment]
libuv 0.10.x has been in ubuntu since Trusty, while libuv1 1.x since wily. If you need any of those in a previous release, I think you'd better request a backport to the ubuntu team so that they are officially distributed.

**Comment by atrauzzi** [comment]
Really?  I thought 1.x wasn't available at all?

**Comment by lucab** [comment]
Current status:
```
 libuv1 | 1.6.1-3 | wily/universe            | source
 libuv1 | 1.6.1-3 | xenial/universe          | source
 libuv1 | 1.8.0-1 | xenial-proposed/universe | source
```
and
```
 libuv | 0.10.22-2        | trusty/universe | source
 libuv | 0.10.28-6ubuntu1 | vivid/universe  | source
 libuv | 0.10.36-3        | wily/universe   | source
 libuv | 0.10.36-3        | xenial/universe | source
```

**Comment by atrauzzi** [comment]
:tada: 

Thanks @lucab!  I'll leave it to you guys to either close or defer this ticket.  I'm sure being packaged in the default releases is sufficient, but maybe there is still a compelling argument for offering a PPA in the future in case distros don't keep up.

**Comment by saghul** [comment]
Closing then!

**Comment by GazbonicAcid** [comment]
I need libuv.so.1 on the Xubuntu derivitive of Trusty 14.04.2
A game I want to play requires it.
14.04.2 is the latest lts that AMD supports for my laptop's apu's gpu drivers.
The latest non lts they support is 15, but 15's security support has expired so no thanks.
