### ISSUE TITLE
Endless loop in uv_write_callbacks()

### ISSUE THREAD

**Issue by vleschuk** [libuv/libuv#654]
Hello all,

we are using libuv v1.7.5 and we have faced the following issue: our server got stuck using 100% CPU. I have checked using debugger and it appeared that libuv enters endless loop trying to cleanup QUEUE. Somehow it happened that at the last moment queue consists of one element which links to itself.

![endless_loop](https://cloud.githubusercontent.com/assets/1045374/11809495/5791b094-a338-11e5-95c2-024359d22e73.png)
![Uploading endless_loop.png…]()

Could you please let me know if this can be a cause of an error in user code. What circumstances could lead to this? Anyway I think libuv internal queue should handle such cases.

I could fix it quickly in libuv by adding a simple check for such situation, but I don't think that's a proper way: it would be better to make this situation impossible to happen and add special assert for self-pointing elements.

Thanks in advance.

Victor

**Comment by bnoordhuis** [comment]
What does your code look like?  Usually when people hit an infinite loop, they've corrupted the memory of the handle or a request associated with the handle.

**Comment by vleschuk** [comment]
The main function performs the following work with libuv handles:

Initialize uv_tcp_t handle
```
    client = (uv_tcp_t*) xmalloc(sizeof(*client));                                                                      
    uv_tcp_init(loop, client);
```
Create a uv_write_t object:
```
write_req = (uv_write_t*) xmalloc(sizeof(*write_req));
```
Fill in the uv_buf_t structure:
```
pipe_buf = uv_buf_init(ip6_addr, strlen(ip6_addr));
```
Send the request and tcp handle to worker process:
```
uv_write2(write_req, (uv_stream_t*) &worker->pipe, &pipe_buf, 1, (uv_stream_t*) client, NULL);
```
Perform cleanup:
```
cleanup:                         
    // the need_close_client flag is true only if we haven't passed it to worker process                                                                                       
    if (need_close_client) {                                                                                           
        uv_close((uv_handle_t*) client, NULL);                                                                          
    }                                                                                                                   
    if (client) {                                                                                                       
        free(client);                                                                                                   
    }                                                                                                                   
    if (write_req) {                                                                                                    
        free(write_req);                                                                                                
    }
```

**Comment by bnoordhuis** [comment]
There is a bug in your cleanup code, it closes the handle and immediately frees the memory.  Free the memory in the callback, likewise for the write request.

**Comment by vleschuk** [comment]
Thanks a lot, I'll give it a try!
