### ISSUE TITLE
ACL operations in fs.c

### ISSUE THREAD

**Issue by Adam-K-P** [libuv/libuv#655]
Hi, 

I want to add ACL operations (set and get) into fs.c.

There is interest with the neovim project for these functions, so I'm wondering if there is interest here as well before I start working on them.

**Comment by saghul** [comment]
Can you sketch up an API proposal?

**Comment by Adam-K-P** [comment]
I just drafted this up; this is my first API proposal, so I'd be happy to clarify anything I'm missing.

**Overview:**

This API would allow for thread safe ACL file operations.  

**Implementation:**

I would include these functions in fs.c.  I'd  work with the fs API (uv_fs_t, INIT, PATH,  POST, etc.) as I believe they would be useful for implementing the ACL functions.  I'd first implement the acl_get_* and acl_set_* functions before attempting the rest of them as I believe they would be the most useful.

**Use-cases:**

These functions would be useful for anyone wanting to use thread safe ACL functions.  I haven't been able to find any implementations yet.  

**Comments:**

I'm open to any comments/suggestions as I am new to libuv and have just been messing around with the code for the past few days.

**Comment by bnoordhuis** [comment]
I think this is the related to or the same as https://github.com/libuv/libuv/issues/234?

**Comment by saghul** [comment]
Oh, looks like it indeed. @Adam-K-P mind dropping by #234?

**Comment by Adam-K-P** [comment]
Yes, I will start looking at it today, thanks for finding that.

**Comment by saghul** [comment]
Closing in favor of @234 then.
