### ISSUE TITLE
stdout redirection fails

### ISSUE THREAD

**Issue by cadrian** [libuv/libuv#658]
I have a simple program that writes to stdout using a `uv_poll_t` handle, then exits.

The program works well when I simply start it from a console; but it fails when I redirect the standard output to a file; it gets a SIGABRT signal.

Using strace, I see the following:
```
epoll_ctl(5, EPOLL_CTL_ADD, 1, {EPOLLOUT, {u32=1, u64=1}}) = -1 EPERM (Operation not permitted)
```

Full strace file attached.
[test_log.strace.zip](https://github.com/libuv/libuv/files/67421/test_log.strace.zip)

I use libuv 1.8.0 (from Debian unstable).

**Comment by bnoordhuis** [comment]
https://github.com/libuv/libuv/pull/659 for a possible fix.

**Comment by cadrian** [comment]
Well, #659 is a good step forward assuredly. If I understand the code (did not try yet), it propagates an error to the callback. That's great indeed and thank you; however to me it is "just" good behaviour to do that instead of crashing.

Now once I catch the error in my callback, how do I proceed? I really want to write to stdout using a libuv handle.

As I am new to this library, I may have missed something. Any pointer would be appreciated.

Anyway thanks for your work, it helps.

**Comment by bnoordhuis** [comment]
You would normally use `uv_tty_init()` instead of `uv_poll_init()` for stdio file descriptors.  That also unlocks functionality for switching to/from raw mode and getting the terminal size.

**Comment by cadrian** [comment]
I tried to use tty. If I understand correctly, except of polling I need to use `uv_write()` because tty is a stream. Is that right?

Here is what I get when I redirect stdout:

```
test_log.exe: src/unix/stream.c:1340: uv_write2: Assertion `(stream->type == UV_TCP || stream->type == UV_NAMED_PIPE || stream->type == UV_TTY) && "uv_write (unix) does not yet support other types of streams"' failed.
```

What do I miss? I don't understand how it is supposed to work.

Thanks

**Comment by bnoordhuis** [comment]
You need to make sure that you hand it a file descriptor that is pollable (tty, pipe, socket.)

If you look at how node.js implements `process.stdout` and friends, it sniffs the file descriptor with `uv_guess_handle()` and then creates a handle of the appropriate type.

If the file descriptor refers to a file, it uses `uv_fs_write()` instead.

**Comment by cadrian** [comment]
It works, thank you very much!
