### ISSUE TITLE
How to avoid all threads in pool blocked??

### ISSUE THREAD

**Issue by zhaozg** [libuv/libuv#660]
Hi all, please think this.
fs operation be worked in threadpool, and uv_queue_work maybe launch threads to use all idle threads and need long time to finish,  so main loop will never get async result of fs operation. This should be avoid, and now I don't know how to solve it.

Now I need do simple hack to check idle_threads > 1 before call uv_queue_work, that will sure keep a idle thread to do service for fs operation.

Please show me some solution or pattern and thanks a lot.

**Comment by fivdi** [comment]
One possible solution would be to increase the thread pool size by setting the UV_THREADPOOL_SIZE environment variable. See http://docs.libuv.org/en/latest/threadpool.html

**Comment by zhaozg** [comment]
Hi @fivdi thread pool size is not good idea, we can't control service scale to under UV_THREADPOOL_SIZE

**Comment by zhaozg** [comment]
Now I use a counter, inc it before queue work, and dec it after get result, keep counter less than UV_THREADPOOL_SIZE -1, so fs operation have chance to be done.
