### ISSUE TITLE
Portable atomics? 

### ISSUE THREAD

**Issue by gaoxiaojun** [libuv/libuv#663]
As awalton open issue #726 on 28 Feb 2013, we also think portable atomics library would be great.

**Comment by claam** [comment]
Old issue, but is there any plan for this ?

**Comment by bnoordhuis** [comment]
I don't think so.  It's probably still welcome if someone wants to work on it but it's also redundant in C11 and C++11 since atomic operations are part of the the standard library now.

I'll close this out but let me know if you have questions.

**Comment by claam** [comment]
Thanks the answer. As I see in the configure.ac file, libuv is build with c89. An atomic API could be a good alternative for those that cannot use c11.

**Comment by bnoordhuis** [comment]
To clarify, libuv itself is C89 (mostly) but that doesn't mean consumers can't be C11.
