### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cmsg_nxthdr" referenced by 

### ISSUE THREAD

**Issue by ywxzm** [libuv/libuv#664]
Hi, on my android device, has this error

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cmsg_nxthdr" referenced by ...

NDK Version:10e
SDK API 22
Device Version Android 4.4.4

and in Android NDK, Revision 10b (September 2014) History:
Made the following fixes to the Android-L headers:

Renamed cmsg_nxthdr to __cmsg_nxthdr.

**Comment by saghul** [comment]
How are you compiling / using libuv?

**Comment by ywxzm** [comment]
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

my Android.mk, Thanks

LOCAL_MODULE := uv_static

LOCAL_MODULE_FILENAME := libuv

LOCAL_SRC_FILES := 	src/unix/android-ifaddrs.c \
				    src/fs-poll.c \
					src/inet.c \
					src/threadpool.c \
					src/unix/async.c \
					src/unix/core.c \
					src/unix/dl.c \
					src/unix/fs.c \
					src/unix/getaddrinfo.c \
					src/unix/getnameinfo.c \
					src/unix/linux-core.c \
					src/unix/linux-inotify.c \
					src/unix/linux-syscalls.c \
					src/unix/loop-watcher.c \
					src/unix/loop.c \
					src/unix/pipe.c \
					src/unix/poll.c \
					src/unix/process.c \
					src/unix/proctitle.c \
					src/unix/pthread-fixes.c \
					src/unix/signal.c \
					src/unix/stream.c \
					src/unix/tcp.c \
					src/unix/thread.c \
					src/unix/timer.c \
					src/unix/tty.c \
					src/unix/udp.c \
					src/uv-common.c \
					src/version.c 
		   
				   
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include \
					$(LOCAL_PATH)/src \
					$(LOCAL_PATH)/src/unix
					
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include \
						   $(LOCAL_PATH)/src 

LOCAL_CFLAGS   := -D__ANDROID__ -D__linux__ -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64

include $(BUILD_STATIC_LIBRARY)

**Comment by ywxzm** [comment]
in API 15: socket.h, 
#define CMSG_NXTHDR(mhdr, cmsg) cmsg_nxthdr((mhdr), (cmsg))
and in API 21 
#define CMSG_NXTHDR(mhdr, cmsg) __cmsg_nxthdr((mhdr), (cmsg))

**Comment by saghul** [comment]
We just use `CMSG_NXTHDR`, so I'm not sure what libuv can do here. I'm going to close this, since it's a platform issue specific to Android. We support API level >= 14 (IIRC) on a best effort basis.

Alternatively, try to compile libuv using the provided android-configure script and see if that makes any difference.
