### ISSUE TITLE
How to uninstall libuv 1.4.2 in Archlinux?

### ISSUE THREAD

**Issue by aloisdg** [libuv/libuv#666]
Hello,

I installed through `make install` this old version of libuv in my Archlinux. I am looking to uninstall it but I dont know how. AFAIK, there is no checkinstall on Archlinux and I cant find a `make uninstall` in the libuv's Makefile. Any workaround to uninstall libuv?

If it matters, I installed it after reading this blog's [post](http://barocio.net/2015/08/getting-started-with-aspnet-5-on-linux/).

Thank you!

**Comment by aloisdg** [comment]
[found a solution](https://bbs.archlinux.org/viewtopic.php?id=56373). Sorry for the post. Thank you.

**Comment by Purgator** [comment]
How did you do ?
Your link is not the solution.

**Comment by aloisdg** [comment]
A copy/paste the wrong link. I don't remember what I did. Sorry.

**Comment by Purgator** [comment]
Ahahahah ! Don't mater, i did like this : 
download libuv, and make unistall from the makefile folder. Ez !
