### ISSUE TITLE
assert failed on "tv.tv_sec == timebase.tv_sec" on a xcode build

### ISSUE THREAD

**Issue by ljoaquin** [libuv/libuv#667]
I saw two lines in runer-unix.c like this:
    /* Check that gettimeofday() doesn't jump back in time. */
    assert(tv.tv_sec == timebase.tv_sec ||
           (tv.tv_sec == timebase.tv_sec && tv.tv_usec >= timebase.tv_usec));
which cause a assert failed in xcode.
Did you mean "tv.tv_sec >= timebase.tv_sec" at the first line?

**Comment by saghul** [comment]
We are not seeing this failure in the buildbots, how are you triggering it?

**Comment by bnoordhuis** [comment]
It does look like a logic error to me; it should be `>` instead of `==`: https://github.com/libuv/libuv/pull/670
