### ISSUE TITLE
Need help on closing sockets synchronously

### ISSUE THREAD

**Issue by septag** [libuv/libuv#668]
I'm trying to cleanup Tcp socket peers on application shutdown.
Currently I'm using ```uv_close``` / ```uv_shutdown``` and call a ```uv_run``` with ```UV_RUN_ONCE``` flag. But I guess there is no guarantee that the call to ```uv_run``` calls the callbacks right after issuing close/shutdown requests.  
What can I do to gracefully close the handles and wait for them to finish on program exit ?
thanks

**Comment by bnoordhuis** [comment]
Use `uv_walk()` to close all open handles, then call `uv_run(UV_RUN_DEFAULT)` again.

Aside, can you post questions to the mailing list?  We try to keep the bug tracker restricted to bug reports and feature requests.  Thanks!
