### ISSUE TITLE
Default worker thread stack size (Mac OS X mostly)

### ISSUE THREAD

**Issue by saper** [libuv/libuv#669]
When running a foreign C++ code in a worker thread (https://github.com/sass/node-sass/issues/1289) we have run into a [Mac OS X limitation](https://developer.apple.com/library/mac/qa/qa1419/_index.htm): a default stack size for `pthread_create()`'d threads seems to 512 kilobytes.

I am still not sure how to handle this properly, the symptom of a problem are crashes only when the application runs in a libuv worker thread on Mac OS X. When running standalone (8 MB limit applies) or on some other platform there are no issues.

What worries me here is that one platform is disadvantaged in some way and libuv does a fantastic work at making things cross-platform.

**Comment by saper** [comment]
Some random thoughts:

* Having a stack size configurable does not seem to be a good solution, since this is very platform specific (https://github.com/libuv/libuv/issues/408 fixed by https://github.com/libuv/libuv/pull/429).

* A knob (`UV_THREAD_LARGE_STACK`) in the environment? (ugly)

* Mac OS X-only `pthread_attr_setstacksize` call?

**Comment by saghul** [comment]
Hum, looks like the first thread is created with a default stack size of 8MB (or whatever was set with RLIMIT_STACK, check uname -s), but subsequent threads are created with 512 bytes: https://developer.apple.com/library/mac/qa/qa1419/_index.html

Maybe we should increase the stack size of worker threads to a higher value, or maybe even read RLIMIT_STACK and use that? WDYT @bnoordhuis ?

**Comment by bnoordhuis** [comment]
Basing the new thread's stack size on RLIMIT_STACK seems reasonable to me.

**Comment by saghul** [comment]
Ok, I'll cook a patch :+1:

**Comment by saghul** [comment]
@saper can you try #671 ?

**Comment by saper** [comment]
Thanks for pushing this forward, much appreciated @saghul !
