### ISSUE TITLE
Please report hangup to uv_poll_t callback

### ISSUE THREAD

**Issue by gabrielschulhof** [libuv/libuv#681]
Quoting @bnoordhuis from https://github.com/joyent/libuv/issues/623:

> Report AFD_POLL_DISCONNECT / EPOLLRDHUP / EV_EOF / (whatever event ports reports, if anything) as UV_DISCONNECT to the uv_poll_t callback.
> 
> Make it clear in the API documentation that it's an optional event in that it a) may not be reported, and b) the user is free to ignore it (but that it helps optimize the shutdown path because you avoid an extra read or write).
> 
> The event name is TBD but UV_DISCONNECT seems reasonable.

**Comment by santigimeno** [comment]
Probably related: https://github.com/libuv/libuv/pull/403 as it handled:  `EPOLLRDHUP / EV_EOF` to reduce the number of `ECONNRESET` events (it was initially merged but later on reverted as it was causing some false positives in nodejs).

**Comment by txdv** [comment]
@santigimeno Can you link to the commit which was merged/reverted?

**Comment by santigimeno** [comment]
Commit: https://github.com/libuv/libuv/commit/05a003a3f78d07185b7137601fe8e93561855a8d
Revert: https://github.com/libuv/libuv/commit/01544d861b9e11f844d482a80bc557dd9b803c8c

**Comment by santigimeno** [comment]
Also there was a bug in the commit that should've been resolved by https://github.com/libuv/libuv/pull/474/ but was dropped as the commit was finally reverted.

**Comment by saghul** [comment]
Fixed in #691.
