### ISSUE TITLE
Add PPC BE and PPC LE to CI runs

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#685]
I'm thinking we should add the PPC BE and PPC LE machines to 

https://ci.nodejs.org/job/libuv+any-pr+multi/

Like I did for the Node CI jobs.

Does this make sense ?

**Comment by saghul** [comment]
@mhdawson sure! and thanks!

**Comment by mhdawson** [comment]
Added PPC BE and PPC LE, latest run

https://ci.nodejs.org/job/libuv+any-pr+multi/231/

**Comment by mhdawson** [comment]
Interestingly on the #osuosl (where the PPC machines are hosted) channel I see some discussion that sounds like similar issues:

12:34 PM <•pwnguin> fatal: unable to access 'https://github.com/buildbot/buildbot-infra.git/': gnutls_handshake() failed: Error in the pull function.
12:35 PM ⇐ blueness quit (~blueness@gentoo/developer/blueness) Quit: blueness

So it might be related to a temporary issue.

**Comment by saghul** [comment]
Closing since these have been enabled now. Thanks @mhdawson!
