### ISSUE TITLE
pipe_close_stdout_read_stdin - Intermittent - PPC BE Fedora 20

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#686]
Intermittent - seen once since PPC BE added to regression CI job

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=ppcbe-fedora20/230/console

[%   9|+  26|-   0|T   0|S   0]: pipe_close_stdout_read_stdin
`pipe_close_stdout_read_stdin` failed: exit code 6
Output from process `pipe_close_stdout_read_stdin`:
Assertion failed in test/test-pipe-close-stdout-read-stdin.c on line 86: uv_run(uv_default_loop(), UV_RUN_NOWAIT) == 0
Assertion failed in test/test-pipe-close-stdout-read-stdin.c on line 97: WIFEXITED(status) && WEXITSTATUS(status) == 0

**Comment by iWuzHere** [comment]
The issues is caused when child process gets to 
```
uv_run(uv_default_loop(), UV_RUN_NOWAIT) == 0
```
before the parent has closed the write end of the pipe.

**Comment by iWuzHere** [comment]
Can this issue be closed?
( doesn't fail in CI https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/260/console and the fix has landed )

**Comment by saghul** [comment]
@iWuzHere you are mkaing me very happy today :-)
