### ISSUE TITLE
win: tcp-shutdown-after-write.c on line 69: r == 0

### ISSUE THREAD

**Issue by ujsxn** [libuv/libuv#703]
win10 vs 2012, the error msg is:

`tcp-shutdown-after-write.c on line 69: r == 0`

r = uv_write(&write_req, (uv_stream_t*)&conn, &buf, 1, write_cb);
ASSERT(r == 0);//the r is -4047

**Comment by ujsxn** [comment]
As the program connect a tcp handle without listen and accept.
I think this couldn't work on windows

**Comment by saghul** [comment]
Our CI runs Windows 7 and 2012 and we see no failures. Does it only happen on Windows 10 for you?

**Comment by ujsxn** [comment]
All right then, and there is no need to use it like that.>_<

**Comment by saghul** [comment]
I'm confused. Use it like what? It's possible that a test fails on a given version of Windows, but it's not clear to me how the test is failing for you...

**Comment by ujsxn** [comment]
I think tha there is no server in this test case :
connect without a listen and accept 
So, I think there is no need to do this .

**Comment by ujsxn** [comment]
I found that in **test-tcp-connect-error-after-write.c**
there is a comment:
```
/*
 * Try to connect to an address on which nothing listens, get ECONNREFUSED
 * (uv errno 12) and get connect_cb() called once with status != 0.
 * Related issue: https://github.com/joyent/libuv/issues/443
 */
```
I think the situaton is the same:
Try to connect to an address on which nothing listens

**Comment by saghul** [comment]
The test passes on platforms we test on. On what **specific** platform are you having problems?

**Comment by ujsxn** [comment]
win10 pro ,VS2012 ultimate(update 5)

**Comment by ujsxn** [comment]
No error when using the run-test program, I just test it manualy.
I will check the conf in the project.

**Comment by saghul** [comment]
No follow-up, closing.
