### ISSUE TITLE
uv_poll_t performance question

### ISSUE THREAD

**Issue by alexhultman** [libuv/libuv#704]
I'm looking at uv_poll_t which is the closest I can find for porting ev_io watchers over to uv. In libev these watchers are high perf and can use e.g. epoll. The libuv documentation warns about poor performance of uv_poll_t and much points towards it using poll as implementation.

This means my work in creating a Node.js wrapper for a high perf libev server is impossible without completely rewriting the original server to use uv_tcp_t, which is not going to happen.

Will you support epoll (and friends)?

**Comment by bnoordhuis** [comment]
I think you misread the documentation.  Libuv uses epoll or whatever the high-performance poll API is on the platform it runs on.

What the documentation warns about is using `uv_poll_t` when e.g. a `uv_tcp_t` would do, that prevents libuv from applying a number of optimizations.

**Comment by alexhultman** [comment]
So if a solution based on ev_io scales and performs very well - will a port to uv_poll_t perform similarly?

The doc is very fuzzy about this. You link directly to poll and state it will not scale as well as uv_tcp_t which made me very confused.

Thanks for clarification.

**Comment by bnoordhuis** [comment]
> So if a solution based on ev_io scales and performs very well - will a port to uv_poll_t perform similarly?

Yes, it should.  If you can rewrite you code so that libuv is responsible for reading and writing, it should scale even better.
