### ISSUE TITLE
vcbuild.bat doesn't work with Visual Studio 2015

### ISSUE THREAD

**Issue by foresterre** [libuv/libuv#705]
Hello,

I am trying to build libuv on Windows 8.1 with Visual Studio 2015 (Update 1).
My python environment variable is set to Python 2.7.11.
Unfortunately gyp seems to fail on creating Visual Studio projects.

Issue #459 mentions a possible similar issue. However, according to this issue when the environment variable GYP_MSVS_VERSION is set to 2015, it should work.
I've tested building with and without the above mentioned environment variable (with value 2015), and they result for me both in the following:

```powershell
PS X:\Build\libuv> .\vcbuild.bat
Using Visual Studio 2015
git clone https://chromium.googlesource.com/external/gyp build/gyp
Cloning into 'build/gyp'...
remote: Sending approximately 11.04 MiB ...
remote: Total 17460 (delta 11025), reused 17460 (delta 11025)R
Receiving objects: 100% (17460/17460), 11.04 MiB | 4.21 MiB/s, done.
Resolving deltas: 100% (11025/11025), done.
Checking connectivity... done.
['-Dtarget_arch=ia32', '-Duv_library=static_library', '.\\uv.gyp', '-I', '.\\common.gypi', '--depth=.', '-Dhost_arch=AMD64']
Failed to create vc project files.
```

The versions of libuv I've tried to build are:
* the branch v1.x at  76da68e.
* libuv release version 1.6.0 
* libuv release version 1.8.0

Both 1.6.0 and 1.8.0 also both fail (with the same error as the one mentioned above).

Notably, 1.8.0 exists with some additional output:
```powershell
PS X:\Build\libuv-1.8.0> .\vcbuild.bat
['-Dtarget_arch=ia32', '-Duv_library=static_library', '.\\uv.gyp', '-I', '.\\common.gypi', '--depth=.', '-Dhost_arch=AMD64']
gyp: name 'MSVS_VERSION' is not defined while evaluating condition 'MSVS_VERSION < "2015"' in uv.gyp
Failed to create vc project files.
```
The above suggests me that Visual Studio 2015 wasn't supported at version 1.8.0 (although I am not sure).

Additionally I've also tried updating gyp to the latest version available at: https://chromium.googlesource.com/external/gyp/ (currently: aa0301b)
Unfortunately the results did not change.

I've no experience with gyp whatsoever, and running `python .\gyp_uv.py -h` did not gave me really helpful options for more verbose log output (It seems the --debug option does not contain some log output option).

Any suggestions or help is very much appreciated.

Thank you in advance,

Foresterre

**Comment by saghul** [comment]
I compiled it with it the other day, though with an old version of GYP. I'll give it a shot with the latest GYP just in case there is a problem with that.

**Comment by bnoordhuis** [comment]
Does it work when you run `vcbuild.bat ia32` or `vcbuild.bat x64`?

Aside, I speculate this small patch to gyp_uv.py may be needed for an out-of-the-box build:
```diff
diff --git a/gyp_uv.py b/gyp_uv.py
index 39933f6..458e89e 100755
--- a/gyp_uv.py
+++ b/gyp_uv.py
@@ -27,6 +27,7 @@ except ImportError:
 def host_arch():
   machine = platform.machine()
   if machine == 'i386': return 'ia32'
+  if machine == 'AMD64': return 'x64'
   if machine == 'x86_64': return 'x64'
   if machine.startswith('arm'): return 'arm'
   if machine.startswith('mips'): return 'mips'
```

**Comment by foresterre** [comment]
`if machine == 'AMD64': return 'x64'`
I had tried that as well yesterday, but surprisingly enough changing this line does today indeed work for me.

The `vcbuild.bat ia32` and `vcbuild.bat x64` still error.

**Comment by foresterre** [comment]
Thanks for solving this issue!
