### ISSUE TITLE
How to set the source port in the UDP socket in libuv?

### ISSUE THREAD

**Issue by zhaishuai** [libuv/libuv#707]
How to set the source port in the UDP socket in libuv?

**Comment by saghul** [comment]
Just bind it, by using `uv_udp_bind`. 

Please use the mailing list for further questions (I approved your message now). Thanks!

**Comment by zhaishuai** [comment]
Thanks for your reply. I am a beginer of libuv.
I want to use port 6883(it's just a example) send a message, so i use
uv_udp_bind but get an "*Invalid argument*" error. Could you help me figure
out where i am wrong . Thanks a lot : )

        uv_udp_init(loop, &sendSocket);

        uv_ip4_addr(ipv4.c_str(), port, &sendAddr);

        uv_buf_t buffer = uv_buf_init((char *)msg.c_str(), (unsigned int
)msg.length());

        struct sockaddr_in temp;

        uv_ip4_addr("127.0.0.1", 6883, &temp);

        uv_udp_bind(&sendSocket, (const struct sockaddr*)&temp, 0);

        perror("here");

        int error = uv_udp_send(&sendRequest, &sendSocket, &buffer, 1, (
const struct sockaddr *)&sendAddr, send_callback);

2016-02-02 19:11 GMT+08:00 Saúl Ibarra Corretgé <notifications@github.com>:

**Comment by saghul** [comment]
Please, use the mailing list.

**Comment by zhaishuai** [comment]
thanks i have fix it

2016-02-02 23:35 GMT+08:00 Saúl Ibarra Corretgé <notifications@github.com>:
