### ISSUE TITLE
use uv_tcp_keepalive on windows xp will cause uv_tcp_connect fail

### ISSUE THREAD

**Issue by igoys** [libuv/libuv#71]
If I use uv_tcp_keepalive with argument on windows xp before uv_tcp_connect,
will cause uv_tcp_connect return -1, uv_last_error shows -1 unknow error.
This problem only on windows xp, not on windows 7 or later.

**Comment by cjihrig** [comment]
No follow up. @saghul can this be closed?

**Comment by bnoordhuis** [comment]
Let's close.
