### ISSUE TITLE
Add AIX to libuv testing

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#711]
We have added an AIX machine to the Node CI and I've got a job which runs the Node regression tests on that machine: https://ci.nodejs.org/job/node-test-commit-aix/

I'd like to add to the libuv regression tests as well. (https://ci.nodejs.org/job/libuv+any-pr+multi/)

The first thing to do is probably to figure out how long it will take to run on the machine as its temporary relatively small.

**Comment by mhdawson** [comment]
Seems like it only takes 5 mins

https://ci.nodejs.org/job/libuv+any-pr+multi-mdawson/3/nodes=aix61-ppc64/

so I think its reasonable to just add AIX to the existing job.

@saghul is it ok if I add it ?

**Comment by saghul** [comment]
:+1: Fine by me! Due to our limited manpower, we'll try our best, but chances are we occasionally break something so we'll request your help :-)

**Comment by mhdawson** [comment]
Understood.  At least we'll get a heads up.  There are currently a number of failures already which did not seem to affect our Node support but we already are have @iWuzHere working those.  I'll plan to open issues in this repo for tests that fail once I add AIX so that work is visible and if anybody else wants to jump in they can

**Comment by saghul** [comment]
Ack! Feel free to close this once you've added it. Thanks!

**Comment by mhdawson** [comment]
will do

**Comment by txdv** [comment]
Is it possible to get access to the machines? I might want to investigate those bugs in the future

**Comment by mhdawson** [comment]
@txdv I can give you temporary access when you want to debug.  Just open an issue on this repo (include @mhdawson)  with the ssh public key you want me to use and then I'll create a user you can log in with that key.

**Comment by mhdawson** [comment]
Closing this issue as AIX is added and I've created issues for all of the failures seen
