### ISSUE TITLE
AIX - condvar_1 and condvar_5 tests failing

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#712]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

<PRE>
`condvar_1` failed: timeout
Output from process `condvar_1`: (no output)
=============================================================
</PRE>

**Comment by hrektts** [comment]
I have similar failure at condvar_1 and condvar_5 on a ppc32 Linux box as follows:
```
=============================================================
[%   5|+  14|-   0|T   0|S   0]: condvar_1
`condvar_1` failed: timeout
Output from process `condvar_1`: (no output)
=============================================================
[%   6|+  17|-   1|T   0|S   0]: condvar_5
`condvar_5` failed: timeout
Output from process `condvar_5`: (no output)
=============================================================
```
It seems to be caused by deadlock because the worker thread is run before the remaining parent thread is executed.

The following patch fixes this problem. However, it means that uv_cond_wait and uv_cond_signal are not tested.
```
--- a/test/test-condvar.c
+++ b/test/test-condvar.c
@@ -63,7 +63,9 @@ TEST_IMPL(condvar_1) {
 
   uv_mutex_lock(&wc.mutex);
   uv_sleep(100);
-  uv_cond_wait(&wc.cond, &wc.mutex);
+  while (wc.posted == 0) {
+    uv_cond_wait(&wc.cond, &wc.mutex);
+  }
   ASSERT(wc.posted == 1);
   uv_mutex_unlock(&wc.mutex);
 
@@ -87,7 +89,9 @@ TEST_IMPL(condvar_2) {
   ASSERT(0 == uv_thread_create(&thread, worker, &wc));
 
   uv_mutex_lock(&wc.mutex);
-  uv_cond_wait(&wc.cond, &wc.mutex);
+  while (wc.posted == 0) {
+    uv_cond_wait(&wc.cond, &wc.mutex);
+  }
   uv_mutex_unlock(&wc.mutex);
 
   ASSERT(0 == uv_thread_join(&thread));
@@ -161,7 +165,9 @@ TEST_IMPL(condvar_5) {
 
   uv_mutex_lock(&wc.mutex);
   uv_sleep(100);
-  uv_cond_wait(&wc.cond, &wc.mutex);
+  while (wc.posted == 0) {
+    uv_cond_wait(&wc.cond, &wc.mutex);
+  }
   ASSERT(wc.posted == 1);
   uv_mutex_unlock(&wc.mutex);
```

**Comment by saghul** [comment]
@hrektts mind sending that as a Pull Request? Thanks!

**Comment by mhdawson** [comment]
Does it have anything to do with the sleep times ? 
uv_sleep(100);

ie would it pass if the sleeps were longer ?

**Comment by saghul** [comment]
I guess so, but generally we should wait for the condition to be set in a loop, to avoid spurious wakeups.

**Comment by mhdawson** [comment]
Agreed was just trying to understand if there was a better option than just disabling

**Comment by hrektts** [comment]
I was in the same situation as @mhdawson . Hope the PR resolve this problem. Please feel free to correcting any mistakes!

**Comment by iWuzHere** [comment]
Can this issue be closed?

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/274/console

Doesnt fail in latest CI against v1.x

**Comment by saghul** [comment]
Sure it can!
