### ISSUE TITLE
AIX - failure in test-pipe-close-stdout-read-stdin

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#713]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

<PRE>
`pipe_close_stdout_read_stdin` failed: exit code 393222
Output from process `pipe_close_stdout_read_stdin`:
Assertion failed in test/test-pipe-close-stdout-read-stdin.c on line 86: uv_run(uv_default_loop(), UV_RUN_NOWAIT) == 0
Assertion failed in test/test-pipe-close-stdout-read-stdin.c on line 97: WIFEXITED(status) && WEXITSTATUS(status) == 0
=============================================================
</PRE>

**Comment by iWuzHere** [comment]
This should be resolved as per pull request #688 and no longer fails in the build
https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/266/console

Can this issue be closed?

**Comment by saghul** [comment]
Happy to do that!
