### ISSUE TITLE
AIX - failure in test-tty.c

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#714]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

<PRE>
`tty` failed: exit code 393222
Output from process `tty`:
width=152 height=61
Assertion failed in test/test-tty.c on line 117: r == 0
=============================================================

[%  10|+  25|-   4|T   0|S   0]: tty_file
`tty_file` failed: exit code 393222
Output from process `tty_file`:
Assertion failed in test/test-tty.c on line 158: UV_EINVAL == uv_tty_init(&loop, &tty, fd, 1)
=============================================================
</PRE>

**Comment by mhdawson** [comment]
Looks like this was possibly supposed to fix:

**Comment by iWuzHere** [comment]
From the latest build this is a passing test

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/260/console

```
[%   9|+  28|-   0|T   0|S   0]: tty
`tty` skipped
Output from process `tty`:
Cannot open /dev/tty as read-only: No such device or address
=============================================================

[%  10|+  28|-   0|T   0|S   1]: tty_file
[%  10|+  29|-   0|T   0|S   1]: stdio_over_pipes
```
