### ISSUE TITLE
AIX - failure in test-stdio-over-pipes

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#715]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

<PRE>
[%  11|+  25|-   5|T   0|S   0]: stdio_over_pipes
`stdio_over_pipes` failed: exit code 393222
Output from process `stdio_over_pipes`:
exit_cb
Assertion failed in test/test-stdio-over-pipes.c on line 56: term_signal == 0
</PRE>

**Comment by mhdawson** [comment]
@saghul you can assign this one to @iWuzHere as he'll be looking it

**Comment by iWuzHere** [comment]
Test is non-failing in build
https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/260/console

```
[%  10|+  29|-   0|T   0|S   1]: stdio_over_pipes
[%  10|+  30|-   0|T   0|S   1]: ip6_pton
[%  11|+  31|-   0|T   0|S   1]: ipc_listen_before_write
[%  11|+  32|-   0|T   0|S   1]: ipc_listen_after_write
[%  11|+  33|-   0|T   0|S   1]: ipc_send_recv_pipe
```

**Comment by saghul** [comment]
Ack!
