### ISSUE TITLE
AIX - failure in udp_multicast_join6

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#716]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

<PRE>
`udp_multicast_join6` failed: exit code 393222
Output from process `udp_multicast_join6`:
Assertion failed in test/test-udp-multicast-join6.c on line 132: r == 0
</PRE>

I wonder if this one might be a machine setup issue.

**Comment by iWuzHere** [comment]
This is also non-issue in recent builds
https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/260/console

```
[%  33|+  92|-   2|T   0|S   1]: udp_multicast_interface6
[%  33|+  93|-   2|T   0|S   1]: udp_multicast_join
[%  34|+  94|-   2|T   0|S   1]: udp_multicast_join6
[%  34|+  95|-   2|T   0|S   1]: udp_multicast_ttl
[%  34|+  96|-   2|T   0|S   1]: udp_try_send
[%  35|+  97|-   2|T   0|S   1]: udp_open
```

Can this issue be closed?

**Comment by bnoordhuis** [comment]
Can and will.

**Comment by mhdawson** [comment]
We did apply an APAR so that might explain why some of these now pass
