### ISSUE TITLE
AIX - pipe_sendmsg failure

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#717]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

<PRE>
`pipe_sendmsg` failed: exit code 393222
Output from process `pipe_sendmsg`:
Assertion failed in test/test-pipe-sendmsg.c on line 86: pending == UV_NAMED_PIPE
=============================================================
</PRE>

**Comment by iWuzHere** [comment]
Looking into it.

**Comment by bnoordhuis** [comment]
Fixed by a7009a0.
