### ISSUE TITLE
AIX - process_title failure

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#718]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

`process_title` failed: exit code 393222
Output from process `process_title`:
Assertion failed in test/test-process-title.c on line 40: strcmp(buffer, title) == 0
=============================================================

**Comment by mhdawson** [comment]
Not sure if this is related to https://github.com/libuv/libuv/pull/616 but would have thought that disabled the test so not sure whey it is running/failing

**Comment by iWuzHere** [comment]
from test-process-title.c
```
TEST_IMPL(process_title) {
#if defined(__sun) || defined(_AIX)
  RETURN_SKIP("uv_(get|set)_process_title is not implemented.");
#else
```

So am equally confused to why it failed.

However in later builds it is being skipped.
https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/260/console

```
[%  58|+ 161|-   3|T   0|S   1]: process_title
`process_title` skipped
Output from process `process_title`:
uv_(get|set)_process_title is not implemented.
=============================================================
```

I guess this means that this issue can be closed?

**Comment by saghul** [comment]
Yep, I guess so!
