### ISSUE TITLE
AIX - fs related issues

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#719]
failure in newly added tests runs for AIX

https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=aix61-ppc64/250/console

The current fs watch functionality on AIX needs a feature configured and some configuration which is not in place for the tests.  We also plan to revamp it to make is easier to use.  

The first step in this issue is to confirm all the failures are related to the fs watch functionality and pull any which are not out of this issue into their own issues.

<PRE>
`fs_poll` failed: exit code 393222
Output from process `fs_poll`:
Assertion failed in test/test-fs-poll.c on line 103: status == UV_ENOENT
=============================================================

[%  75|+ 195|-  10|T   0|S   0]: emfile
`emfile` failed: exit code 393222
Output from process `emfile`:
Assertion failed in test/test-emfile.c on line 105: 0 == status
=============================================================

`fs_file_noent` failed: exit code 393222
Output from process `fs_file_noent`:
Assertion failed in test/test-fs.c on line 498: req->result == UV_ENOENT
=============================================================

`fs_file_nametoolong` failed: exit code 393222
Output from process `fs_file_nametoolong`:
Assertion failed in test/test-fs.c on line 505: req->result == UV_ENAMETOOLONG
=============================================================

fs_file_loop` failed: exit code 393222
Output from process `fs_file_loop`:
Assertion failed in test/test-fs.c on line 512: req->result == UV_ELOOP
=============================================================

Output from process `fs_chown`:
Assertion failed in test/test-fs.c on line 223: req->result == UV_EPERM
=============================================================

`fs_futime` failed: exit code 393222
Output from process `fs_futime`:
Assertion failed in test/test-fs.c on line 1931: r == 0
=============================================================

`fs_readlink` failed: exit code 393222
Output from process `fs_readlink`:
Assertion failed in test/test-fs.c on line 1541: req.result == UV_ENOENT
=============================================================

`fs_event_watch_dir` failed: exit code 393222
Output from process `fs_event_watch_dir`:
Assertion failed in test/test-fs-event.c on line 345: r == 0
=============================================================

`fs_event_watch_dir_recursive` skipped
Output from process `fs_event_watch_dir_recursive`:
Recursive directory watching not supported on this platform.
=============================================================

[%  87|+ 218|-  18|T   0|S   1]: fs_event_watch_file
`fs_event_watch_file` failed: exit code 393222
Output from process `fs_event_watch_file`:
Assertion failed in test/test-fs-event.c on line 425: r == 0
=============================================================

[%  87|+ 218|-  19|T   0|S   1]: fs_event_watch_file_twice
`fs_event_watch_file_twice` failed: exit code 393222
Output from process `fs_event_watch_file_twice`:
Assertion failed in test/test-fs-event.c on line 456: 0 == uv_fs_event_start(watchers + 0, fail_cb, path, 0)
=============================================================

[%  87|+ 218|-  20|T   0|S   1]: fs_event_watch_file_current_dir
`fs_event_watch_file_current_dir` failed: exit code 393222
Output from process `fs_event_watch_file_current_dir`:
Assertion failed in test/test-fs-event.c on line 484: r == 0
=============================================================

[%  88|+ 218|-  21|T   0|S   1]: fs_event_no_callback_after_close
`fs_event_no_callback_after_close` failed: exit code 393222
Output from process `fs_event_no_callback_after_close`:
Assertion failed in test/test-fs-event.c on line 526: r == 0
=============================================================

[%  88|+ 218|-  22|T   0|S   1]: fs_event_no_callback_on_close
`fs_event_no_callback_on_close` failed: exit code 393222
Output from process `fs_event_no_callback_on_close`:
Assertion failed in test/test-fs-event.c on line 560: r == 0
=============================================================

[%  88|+ 218|-  23|T   0|S   1]: fs_event_immediate_close
`fs_event_immediate_close` failed: exit code 393222
Output from process `fs_event_immediate_close`:
Assertion failed in test/test-fs-event.c on line 590: r == 0
=============================================================

[%  89|+ 218|-  24|T   0|S   1]: fs_event_close_with_pending_event
`fs_event_close_with_pending_event` failed: exit code 393222
Output from process `fs_event_close_with_pending_event`:
Assertion failed in test/test-fs-event.c on line 631: r == 0
=============================================================

[%  89|+ 218|-  25|T   0|S   1]: fs_event_close_in_callback
`fs_event_close_in_callback` failed: exit code 393222
Output from process `fs_event_close_in_callback`:
Assertion failed in test/test-fs-event.c on line 692: r == 0
=============================================================

[%  90|+ 218|-  26|T   0|S   1]: fs_event_start_and_close
`fs_event_start_and_close` failed: exit code 393222
Output from process `fs_event_start_and_close`:
Assertion failed in test/test-fs-event.c on line 733: r == 0
=============================================================

`fs_event_getpath` failed: exit code 393222
Output from process `fs_event_getpath`:
Assertion failed in test/test-fs-event.c on line 766: r == 0
=============================================================

`fs_scandir_file` failed: exit code 393222
Output from process `fs_scandir_file`:
Assertion failed in test/test-fs.c on line 469: req->result == UV_ENOTDIR
=============================================================

</PRE>

**Comment by whitlockjc** [comment]
Any way to collapse all of these into a single issue with a task like like we did with FreeBSD in #128?

**Comment by mhdawson** [comment]
I assume you mean the ones in this issue as well as the AIX specific issues ?

**Comment by whitlockjc** [comment]
I find it to be a little simpler to follow but it's not pertinent.  I just saw a number of AIX failures come in at the same time and figured I'd ask.  I'll let @saghul chime in.

**Comment by saghul** [comment]
I'd have probably gone with a single issue because seeing issues never shrink is kinda frustrating at times, but since they have already been filled let's leave it as is.

**Comment by iWuzHere** [comment]
Fixed a number of these issues in PR #739 and PR #776 

This requires ahafs to be mounted by running the following command as root:
```
mount -v ahafs /aha /aha
```

Output from make check

```
=============================================================
[%  58|+ 165|-   0|T   0|S   0]: process_title
`process_title` skipped
Output from process `process_title`:
uv_(get|set)_process_title is not implemented.
=============================================================
[%  75|+ 212|-   0|T   0|S   1]: emfile
`emfile` failed: exit code 393222
Output from process `emfile`:
Assertion failed in test/test-emfile.c on line 104: 0 == status
=============================================================
[%  83|+ 234|-   1|T   0|S   1]: fs_futime
`fs_futime` failed: exit code 393222
Output from process `fs_futime`:
Assertion failed in test/test-fs.c on line 2062: r == 0
=============================================================
[%  85|+ 241|-   2|T   0|S   1]: fs_event_watch_dir
`fs_event_watch_dir` failed: exit code 393222
Output from process `fs_event_watch_dir`:
Assertion failed: __EX, file  src/unix/aix.c, line 746
=============================================================
[%  86|+ 241|-   3|T   0|S   1]: fs_event_watch_dir_recursive
`fs_event_watch_dir_recursive` skipped
Output from process `fs_event_watch_dir_recursive`:
Recursive directory watching not supported on this platform.
=============================================================
[%  86|+ 241|-   3|T   0|S   2]: fs_event_watch_file
`fs_event_watch_file` failed: exit code 393222
Output from process `fs_event_watch_file`:
Assertion failed: __EX, file  src/unix/aix.c, line 746
=============================================================
[%  87|+ 242|-   4|T   0|S   2]: fs_event_watch_file_current_dir
`fs_event_watch_file_current_dir` failed: exit code 393222
Output from process `fs_event_watch_file_current_dir`:
Assertion failed: __EX, file  src/unix/aix.c, line 746
=============================================================
[%  89|+ 246|-   5|T   0|S   2]: fs_event_close_in_callback
`fs_event_close_in_callback` failed: timeout
Output from process `fs_event_close_in_callback`: (no output)
=============================================================
[%  90|+ 248|-   6|T   0|S   2]: fs_event_getpath
`fs_event_getpath` failed: exit code 393222
Output from process `fs_event_getpath`:
Assertion failed in test/test-fs-event.c on line 823: memcmp(buf, "watch_dir", len) == 0
=============================================================
[%  96|+ 265|-   7|T   0|S   2]: thread_stack_size
`thread_stack_size` skipped
Output from process `thread_stack_size`:
OSX only test
=============================================================
[% 100|+ 274|-   7|T   0|S   3]: Done.
FAIL: test/run-tests
====================================================== 
```

Note ```emfile``` and ```fs_futime``` are not fs watch related failures, and I am investigating them separately.

This brings us down to a total of 5 failures related to fs watch.

Not sure if this will show up in CI as I am not 100% the community AIX machine has ahafs installed/mounted.

**Comment by iWuzHere** [comment]
Fixed ```fs_event_getpath```

The only remaining fs watch related failure is ```fs_event_close_in_callback```

Output from make check:

```
=============================================================
[%  58|+ 165|-   0|T   0|S   0]: process_title
`process_title` skipped
Output from process `process_title`:
uv_(get|set)_process_title is not implemented.
=============================================================
[%  75|+ 212|-   0|T   0|S   1]: emfile
`emfile` failed: exit code 393222
Output from process `emfile`:
Assertion failed in test/test-emfile.c on line 104: 0 == status
=============================================================
[%  83|+ 234|-   1|T   0|S   1]: fs_futime
`fs_futime` failed: exit code 393222
Output from process `fs_futime`:
Assertion failed in test/test-fs.c on line 2062: r == 0
=============================================================
[%  86|+ 242|-   2|T   0|S   1]: fs_event_watch_dir_recursive
`fs_event_watch_dir_recursive` skipped
Output from process `fs_event_watch_dir_recursive`:
Recursive directory watching not supported on this platform.
=============================================================
[%  89|+ 249|-   2|T   0|S   2]: fs_event_close_in_callback
`fs_event_close_in_callback` failed: timeout
Output from process `fs_event_close_in_callback`: (no output)
=============================================================
[%  96|+ 269|-   3|T   0|S   2]: thread_stack_size
`thread_stack_size` skipped
Output from process `thread_stack_size`:
OSX only test
=============================================================
[% 100|+ 278|-   3|T   0|S   3]: Done.
FAIL: test/run-tests
=====================================================
```

**Comment by iWuzHere** [comment]
Can this issue be closed?
As of https://github.com/libuv/libuv/pull/838 there should only be the `emfile` and ``POLLRDHUP`` failures 
Current run on AIX: https://ci.nodejs.org/job/libuv-test-commit-aix/nodes=aix61-ppc64/41/console

**Comment by saghul** [comment]
Done! Great work on fixing all these AIX issues!

**Comment by mhdawson** [comment]
@iWuzHere I don't see other issues covering emfile and POLLRDHUP for AIX?  Can you point me to them ?  If they don't exist then I think we need either this Issue or some other issue tracking them.

**Comment by iWuzHere** [comment]
But the title of this issue states that this is for fs watch related functionality, which neither of those failing tests are related to.

I can open new issues for them

**Comment by mhdawson** [comment]
Thanks, new issues makes sense to me, just want to make sure they are tracked
