### ISSUE TITLE
Proposal: uv_getlogin()

### ISSUE THREAD

**Issue by cjihrig** [libuv/libuv#731]
If the maintainers are OK with it, I'd like to take a shot at implementing a `uv_getlogin()` function.

I talked to @saghul about this a while back on IRC ([logs](http://logs.nodejs.org/libuv/2015-12-14#20:57:41.595)). He suggested creating a `uv_uid_t` containing a `char *` for the username, and a `uid_t` for the uid, which would be -1 on Windows. He also suggested opening an issue here to get more input on the proposal.

Also refs https://github.com/libuv/libuv/issues/11.

**Comment by bnoordhuis** [comment]
The idea is to implement it as `getpwuid_(geteuid())`?  How are you going to copy out the username string when the `username` field is a `char*`?

Aside, I wouldn't call the struct `uv_uid_t` - it looks too similar to `uid_t`, which is not an aggregate type.

**Comment by cjihrig** [comment]
@bnoordhuis I had pictured it working like `uv_os_homedir()` which calls `getuid()`, `getpwuid_r()` then copies the `pw_dir` field using `memcpy()`. Is there something special about the username that I'm missing?

**Comment by bnoordhuis** [comment]
No, except that you mention "creating a `uv_uid_t` containing a `char *` for the username", which made me wonder who owns that memory.

**Comment by cjihrig** [comment]
Ah, I see what you mean. The `uv_uid_t` (pending official naming) should probably own it.

**Comment by bnoordhuis** [comment]
That could work but then we either need an accompanying `uv_getlogin_free()` or the username field should be a char array.

**Comment by cjihrig** [comment]
I think it would be more straightforward to use a char array of size `LOGIN_NAME_MAX` (`UNLEN + 1` on Windows).

**Comment by bnoordhuis** [comment]
I agree.  I don't think most platforms have a LOGIN_NAME_MAX constant (you'd have to call `sysconf(_SC_LOGIN_NAME_MAX)`) but you can probably get away with making it a `char username[257]`.

**Comment by cjihrig** [comment]
Sounds good. Is there anything else that you'd like to see hashed out here, or am I good to start working on this?

**Comment by bnoordhuis** [comment]
If the username and the uid are all that's needed, now and in the future, you should be good to go.  What about e.g. the gid?

**Comment by cjihrig** [comment]
I'm open to suggestions. Seems simple enough to grab the gid from `getpwuid()`. However, the API would be straying further from `getlogin()`. I believe @saghul's original motivation for including the uid was that it is the important piece on Unix.

**Comment by saghul** [comment]
I had a quick look at my usual source of inspiration: Python :-) Which provides the following: https://docs.python.org/2/library/pwd.html

So, /me wonders if we could make this return a complex object with a few fields (just for the current effective user):

- name
- uid
- gid
- shell
- homedir

"but we already have a way to get homedir!" I hear you say. Yes we do, but how about putting it all together and deprecating that?

A problem I see is that since usernames are not numeric on Windows, uid and gid should contain *some* value... I thought of -1, but a quick search shows that some unixes do (or did?) have them. Well, TIL, I guess.

**Comment by bnoordhuis** [comment]
> since usernames are not numeric on Windows, uid and gid should contain some value... I thought of -1, but a quick search shows that some unixes do (or did?) have them.

Factoid: `uid_t` and `gid_t` are unsigned on all UNIX platforms we support but some (the BSDs) store them as negative values in `/etc/passwd`, so e.g. -2 gets converted on load to 65534 or whatever the range of `uid_t` is.

**Comment by cjihrig** [comment]
@bnoordhuis what would you recommend as the dummy value on Windows? Does the value matter a lot if we document that it is just a placeholder on Windows?

@saghul what would the value of shell be on Windows? Would it always be cmd.exe?

**Comment by saghul** [comment]
@cjihrig it could be NULL to begin with, but there is cmd.exe, powershell, Windows SDK that I know of.

**Comment by bnoordhuis** [comment]
> what would you recommend as the dummy value on Windows?

I don't think it matters much.  -1 seems like a good value.

**Comment by cjihrig** [comment]
If we're going to move to this more complex object that @saghul mentioned, do you think I should reconsider using a matching free function instead of character arrays? Right now, with arrays, the data structure would look like:

```
typedef struct uv_passwd_s {
  char name[257];
  uv_uid_t uid;
  uv_gid_t gid;
  char shell[PATH_MAX];
  char homedir[PATH_MAX];
} uv_passwd_t;
```

**Comment by bnoordhuis** [comment]
I'd implement a free function, yes.

**Comment by saghul** [comment]
:+1:
