### ISSUE TITLE
linux: fopen() calls are not fork-safe

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#736]
```
$ git grep -nw fopen src/unix/
src/unix/linux-core.c:631:  fp = fopen("/proc/cpuinfo", "r");
src/unix/linux-core.c:717:  fp = fopen("/proc/stat", "r");
src/unix/linux-core.c:782:  fp = fopen(buf, "r");
```
Those should be using `open(filename, O_RDONLY | UV__O_CLOEXEC)` which can then optionally be passed to `fdopen()`.

For anyone wanting to work on this: keep in mind that the `open()` system call can fail with EINVAL on older kernels.  In that case you need to retry without the flag and call `uv__cloexec()` afterwards.  It's not race-free but it keeps the race window to a minimum.

**Comment by kthelgason** [comment]
I'd love to take this on if that's ok. Seems simple enough to start with :smile:

**Comment by bnoordhuis** [comment]
Of course, go for it.

**Comment by saghul** [comment]
Go for it, thanks for volunteering!

**Comment by saghul** [comment]
#743 landed, closing!
