### ISSUE TITLE
Rate-limiting plan in libuv

### ISSUE THREAD

**Issue by Cheedoong** [libuv/libuv#738]
Speed or rate limiting is very useful in a lot of scenarios, for such I/O libraries. 

One advantage of libev is the rate-limiting feature: 
http://www.wangafu.net/~nickm/libevent-book/Ref6a_advanced_bufferevents.html

So does libuv have any plan on such features?

**Comment by bnoordhuis** [comment]
You (as in: the libuv user) control that yourself through the speed by which you read or write.  It's not something that needs to be solved at the libuv level.

> One advantage of libev

That's libevent, libev is a different project.
