### ISSUE TITLE
uv_send_buffer_size does not allow you to set SO_SNDBUF to 0

### ISSUE THREAD

**Issue by mikinho** [libuv/libuv#74]
Using 0 to wrap getsockopt within uv__socket_sockopt prevents us from using uv_send_buffer_size to set SO_SNDBUF socket option to 0 (zero) which on Windows would allow the stack to send from your application buffer directly.

**Comment by cjihrig** [comment]
Closing as there hasn't been any activity here in almost 3 years. If anyone wants to start this work up again, just do it.
