### ISSUE TITLE
test-tcp-close-while-connecting.c failing on pLinux

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#741]
https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=ppcbe-fedora20/264/console
https://ci.nodejs.org/job/libuv+any-pr+multi/nodes=ppcle-ubuntu1404/264/console

Started failing on Feb 18, so only a few CI runs ago 

<PRE>
[%  22|+  62|-   0|T   0|S   1]: tcp_close_while_connecting
`tcp_close_while_connecting` failed: exit code 6
Output from process `tcp_close_while_connecting`:
Assertion failed in test/test-tcp-close-while-connecting.c on line 40: status == UV_ECANCELED
=============================================================
</PRE>

**Comment by iWuzHere** [comment]
Looking into it.

**Comment by iWuzHere** [comment]
Can this issue be closed? Should be resolved as of pull request #744.
Test is no longer failing in ci.

**Comment by bnoordhuis** [comment]
Fixed by e76e213.
