### ISSUE TITLE
Support for polling kernfs attribute files

### ISSUE THREAD

**Issue by aldehir** [libuv/libuv#774]
I would like to work on support for polling kernfs attribute files through the use of `uv_poll_t`. Before doing so, I'd like to get the blessing of the libuv maintainers for the proposed changes.

As documented [here](https://github.com/torvalds/linux/blob/master/fs/kernfs/file.c#L768-L781),

> Kernfs attribute files are pollable.  The idea is that you read
the content and then you use 'poll' or 'select' to wait for
the content to change.  When the content changes (assuming the
manager for the kobject supports notification), poll will
return POLLERR|POLLPRI, and select will return the fd whether
it is waiting for read, write, or exceptions.
Once poll/select indicates that the value has changed, you
need to close and re-open the file, or seek to 0 and read again.
Reminder: this only works for attributes which actively support
it, and it is not possible to test an attribute from userspace
to see if it supports poll (Neither 'poll' nor 'select' return
an appropriate error code).  When in doubt, set a suitable timeout value.

Certain kernfs attribute files can be polled for the event `POLLPRI | POLLERR`, or in terms of epoll, `EPOLLPRI | EPOLLERR`. Unfortunately, the existing implementation of `uv_poll_t` doesn't lend itself well to this use case for two reasons:

- `uv_poll_event` doesn't have an event mapped for `EPOLLPRI`.
- `uv__poll_io()` automatically removes the poll handle from the event loop upon receiving `EPOLLERR`.

I propose to add an additional event to `uv_poll_event`, say... `UV_PRIORITY`, or `UV_URGENT`. In addition, add poll specific flags to the `uv_poll_t` handle to support different behavior(s). A flag such as `UV_NOAUTOCLOSE` may be passed to prevent `uv__poll_io()` from cleaning up the poll handle when receiving an `EPOLLERR` event. Then have a pair of functions, `uv_set_poll_flags()` and `uv_get_poll_flags()`, for getting/setting the flags.

Please let me know your thoughts/concerns about my proposed modifications. If it seems like a good addition, then I'll follow up with a PR.

Thanks!

**Comment by bnoordhuis** [comment]
Hi @aldehir, thanks for getting in touch.  I'm personally leaning towards -1 as long as there is only a single, platform-specific use case, but perhaps the other maintainers feel differently.  @libuv/collaborators?

**Comment by saghul** [comment]
I agree with @bnoordhuis
