### ISSUE TITLE
proposal: support blocking/synchronous operations on Windows TCP/UDP streams

### ISSUE THREAD

**Issue by blitmap** [libuv/libuv#780]
Hi!

I'm currently trying to integrate libuv with a project that already abstracts socket engines and threading quite well.  I want to make use of libuv because we'd gain IOCP support on Windows, and it would improve this projects' separation of concerns.

I cannot entirely make use of libuv as blocking socket operations are not supported on Windows.  It's funny because the underlying `HANDLE` is set to be non-blocking as libuv's default behavior, but the associated function to reverse that (`uv_stream_set_blocking()`) only supports this on `uv_pipe_t`'s.

(Again, you can **ONLY** set blocking after being pre-set as non-blocking on pipes, on Windows)

https://github.com/libuv/libuv/blob/v1.x/src/win/stream.c#L239-L249

I realize what I'm asking for is needed by a very small minority.  You would avoid synchronous operations if using libuv and orient your code for callbacks.  I believe the project I'm working on uses synchronous/blocking writes for issuing databases queries.  The silly part is I think it's on a separate thread, making it deferred from the main thread like a non-blocking operation anyway.

All that said, I am requesting this because I believe it would be simple to support and make the transition to async-throughout easier.

I don't know where this would go:

``` c
unsigned blocking = 0;
ioctlsocket(uv_os_sock_t, FIONBIO, &blocking);
```

Please and thank you?

**Comment by saghul** [comment]
I guess a patch which which completes [uv_stream_set_blocking](http://docs.libuv.org/en/v1.x/stream.html?highlight=blocking#c.uv_stream_set_blocking) on Windows would be ok.

I really don't want to add the equivalent API for UDP though.

The good news is that you can take the fd/HANDLE of a uv handle with `uv_fileno` and do it yourself!

**Comment by saghul** [comment]
Closing since there is nothing actionable.
