### ISSUE TITLE
Building libuv without sphinx

### ISSUE THREAD

**Issue by fusion809** [libuv/libuv#781]
Hi,

Is it possible to build this library without sphinx? According to the README sphinx is used to build the documentation, well I don't need the documentation, so is it possible to disregard the sphinx dependency? I ask because I am creating a package for libuv in my Open Build Service Arch_Extra project (and no I can't just use the libuv package in the [community] repo of Arch Linux, due to OBS restrictions) and the sphinx dependency is the main thing that is stopping me, due to the dependency nightmare it would land me in. Is there some options I need to pass to the autogen.sh or configure script in order to build without documentation (hence, hopefully abolishing the sphinx requirement)?

Thanks for your time,
Brenton

**Comment by bnoordhuis** [comment]
I'm not sure what you mean.  `sh autogen.sh && ./configure && make` builds just the library, nothing else; no tests, no documentation.

**Comment by saghul** [comment]
Sphinx is only required for building the documentation, as the README says. Whether you build it with autotools or GYP, Sphinx is not required.
