### ISSUE TITLE
gyp: Undefined variable uv_library in deps/libuv/uv.gyp

### ISSUE THREAD

**Issue by ibc** [libuv/libuv#784]
I'm adding libuv as a dependency in a `gyp` based project:

* foo.gyp:

```js
{
  'targets': [
    {
      'target_name': 'foo',
      'type': 'executable',
      'dependencies': [
        'deps/libuv/uv.gyp:libuv'
      ]
    }
  ]
}
```

Then I run `gyp -d foo.gyp` and get this error:

```
INCLUDES:input.py:388:LoadTargetBuildFile Loading Target Build File 'foo.gyp'
INCLUDES:input.py:388:LoadTargetBuildFile Loading Target Build File 'deps/libuv/uv.gyp'
VARIABLES:input.py:745:ExpandVariables Matches: {'content': 'uv_library', 'is_array': '', 'replace': '<(uv_library)', 'type': '<', 'command_string': None}

gyp: Undefined variable uv_library in deps/libuv/uv.gyp
```

However `uv.gyp` clearly adds its own `common.gypi` (in `sources`) which clearly defines a default value for `uv_library`:

```
{
  'variables': {
    'uv_library%': 'static_library', # allow override to 'shared_library' for DLL/.so builds
```

NOTE: I'm running this stuff in OS X. Is it related to this [GYP bug](https://github.com/libuv/libuv/blob/v1.x/gyp_uv.py#L47):

```
  # GYP bug.
  # On msvs it will crash if it gets an absolute path.
  # On Mac/make it will crash if it doesn't get an absolute path.
  if sys.platform == 'win32':
    args.append(os.path.join(uv_root, 'uv.gyp'))
    common_fn  = os.path.join(uv_root, 'common.gypi')
    options_fn = os.path.join(uv_root, 'options.gypi')
    # we force vs 2010 over 2008 which would otherwise be the default for gyp
    if not os.environ.get('GYP_MSVS_VERSION'):
      os.environ['GYP_MSVS_VERSION'] = '2010'
  else:
    args.append(os.path.join(os.path.abspath(uv_root), 'uv.gyp'))
    common_fn  = os.path.join(os.path.abspath(uv_root), 'common.gypi')
    options_fn = os.path.join(os.path.abspath(uv_root), 'options.gypi')
```

If so, does it mean that I need to pass those args when I run `gyp` on my project?

**Comment by ibc** [comment]
I've also checked this similar old [issue](https://github.com/joyent/libuv/issues/609) and have created a `common.gypi` in my root folder and added it to the `sources` of my `foo.gyp`. It contains:

```
{
  'variables':
  {
    'uv_library%': 'static_library'
  }
}

```

It does not work, same error.

**Comment by ibc** [comment]
Sorry, according to the similar [issue](https://github.com/joyent/libuv/issues/609) I've should call `gyp -Icommon.gypi`. Indeed it works... Magic...

**Comment by bnoordhuis** [comment]
Sounds like it's resolved?  I'll close.

**Comment by ibc** [comment]
Yep. It seems that the magic under `common.gypi` is accepted as it is :)
