### ISSUE TITLE
Segfault when immediately closing async handle after init

### ISSUE THREAD

**Issue by cynecx** [libuv/libuv#786]
I am currently working on an addon for node and it requires libuv's async feature but somehow I am getting a segfault when creating an async handle and immediately destroying it.

    static uv_async_t asyncHandle;

    static void Callback(uv_async_t* handle) {
    }

    void Function(const Nan::FunctionCallbackInfo<v8::Value>& info) {
      uv_async_init(uv_default_loop(), &asyncHandle, Callback);
    }

    void Function2(const Nan::FunctionCallbackInfo<v8::Value>& info) {
      uv_close(reinterpret_cast<uv_handle_t*>(&asyncHandle), nullptr);
    }

**Comment by cjihrig** [comment]
Would you mind asking general questions like this on the mailing list?

**Comment by cynecx** [comment]
@cjihrig Sorry, this seemed like a bug to be that's why I opened this issue in the first place.

**Comment by bnoordhuis** [comment]
I've replied to your post on the mailing list.  Barring evidence to the contrary, I'll close this as not-a-bug.
