### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [libuv/libuv#789]
I would like to point out that identifiers like "[`__comp`](https://github.com/libuv/libuv/blob/ddd7e04fd6442ae0edba6fd64dbe416be5bca86b/include/tree.h#L160)" and "[`uv__work`](https://github.com/libuv/libuv/blob/8d11aacb79472009189c35e8953d0fa316bfd202/include/uv-threadpool.h#L30)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by bnoordhuis** [comment]
No thanks.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?
