### ISSUE TITLE
testing libuv applications

### ISSUE THREAD

**Issue by lperkov** [libuv/libuv#793]
Hi!

We are using libuv in a few projects and I'm curious what would be the best practices to properly implement unit testing on asynchronous functions with callbacks such as the case with libuv.

Specifically we have been using [cmocka](https://cmocka.org/) and have good experience with it. It would be awesome to somehow integrate libuv and cmocka!

It would be appreciated if somebody has already done something similar and can share the code :)

**Comment by cjihrig** [comment]
@lperkov can you move this question to the [mailing list](http://groups.google.com/group/libuv)?

**Comment by lperkov** [comment]
done.
