### ISSUE TITLE
[1.8.0] uv_write inconsistency on Windows

### ISSUE THREAD

**Issue by lucasterra** [libuv/libuv#794]
Hello, see the following code:

``` c++
uv_buf_t bufs[2];
bufs[0]->base = "Hello there!";
bufs[0]->len = 12;
bufs[1]->base = "Welcome";
bufs[1]->len = 7;

uv_write_t* writeReq = getWriteHandle();
uv_pipe_t* pipe = getPipeHandle(id);
int r;
if ((r = uv_write(writeReq, (uv_stream_t*)pipe, bufs, 2, nullptr)) != 0) {
   // This works on Unix, but not on Windows.
   cout << "Error: " << uv_strerror(r) << endl;
}
```

On Windows, if you call [uv_write](http://docs.libuv.org/en/v1.x/stream.html#c.uv_write) on a [pipe](http://docs.libuv.org/en/v1.x/pipe.html) stream with `nbufs > 1` it will return `ENOTSUP` (_operation not supported on socket_). The same code on Unix will work fine.

That's because [uv_pipe_write_impl(...)](https://github.com/libuv/libuv/blob/v1.x/src/win/pipe.c#L1216) only supports writing buffer at a time.

Sure, I can loop through my buffers and write them one by one, but I'm reporting this because it's making code non-cross-compatible.

Regards.

**Comment by saghul** [comment]
@piscisaureus do you know / remember if there was some system limitation here?

**Comment by piscisaureus** [comment]
Windows doesn't support writing multiple buffers to a pipe in a single syscall. Of course libuv could write the buffers one by one; we just never got around to implementing this, and node has no need for it.
A patch would be more than welcome.

**Comment by kroggen** [comment]
I had this same problem.

I wrote a [topic](https://groups.google.com/forum/#!topic/libuv/uZjKxU9kav0) to the libuv google group and now I found this.

I was analyzing the code...

For the cases in which the request is completed immediately we can just call `WriteFile` again.

But can we do the same for the cases in which the request was queued by the kernel?

And what about [here](https://github.com/libuv/libuv/blob/v1.x/src/win/pipe.c#L1377-L1385) with `uv_insert_non_overlapped_write_req`? I guess we would need a new request object.

**Comment by kroggen** [comment]
I thought about a workaround:

For those who want to use more than one buffer on a single write with pipes on Windows we could require the stream to be blocking using the `uv_stream_set_blocking` function, as it works for pipes on Windows.

So we can update the ` uv_pipe_write_impl` function to call `WriteFile` in a loop for each buffer.

If the ` uv_pipe_write_impl` function was called with `nbufs > 1` and the `UV_HANDLE_BLOCKING_WRITES` flag was not set, then we return `ERROR_NOT_SUPPORTED`:
```C
    if ((nbufs > 1) && ((handle->flags & UV_HANDLE_BLOCKING_WRITES) == 0))
      return ERROR_NOT_SUPPORTED;
```
Although I prefer to have the asynchronous version too.

Any ideas?

**Comment by txdv** [comment]
If it is blocking, writing with WriteFile in a loop is no problem, otherwise there needs to be a threadpool to pass the action to.

**Comment by piscisaureus** [comment]
This would be fixed by https://github.com/libuv/libuv/pull/1843

**Comment by addaleax** [comment]
@piscisaureus Ooooooh, I’ve been bumping my head against this issue so many times in the last year. I’ll try this out as soon as I can, thank you so much for taking care of this! :blue_heart:
