### ISSUE TITLE
Add linuxOne to libuv tests

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#795]
I'm adding linuxOne machines (Linux on System Z) to the CI for Node/libuv.  There is still some setup like ccache to be complete, however, the libuv tests are running/passing.

https://ci.nodejs.org/job/node-test-commit-linuxone-mdawson/nodes=rhel72-s390x/15/console

So I wanted to suggest we add to the regular libuv CI runs.    

If I get the ok I can go ahead and add.

**Comment by saghul** [comment]
Sure, go ahead!

Since we are here, can I ask for per-platform configurations as well, please? The idea being that if a patch only applies to OSX I could trigger a build only on the OSX machines, or windows, or Linux, etc. Thanks!

**Comment by mhdawson** [comment]
Thanks, added linuxOne to the existing job and created new jobs as described in:
