### ISSUE TITLE
`tcp_close_accept` test is flaky on `SmartOS`

### ISSUE THREAD

**Issue by santigimeno** [libuv/libuv#799]
The `tcp_close_accept` test has been flaky in `SmartOS` for a while. See https://ci.nodejs.org/job/libuv+any-pr+multi/297/:

```
`tcp_close_accept` failed: exit code 134
Output from process `tcp_close_accept`:
Assertion failed in test/test-tcp-close-accept.c on line 59: status != 0
```

I've been looking into it and have found what I think is inconsistent behavior of `SmartOS` handling `connect` errors. In this test, just after the last connection is tried, the server socket is closed (see [code](https://github.com/libuv/libuv/blob/v1.x/test/test-tcp-close-accept.c#L99-L108)). One would think the `connect_cb` should be called with an error but it does not happen all the time. At least on 50% of the test runs, it returns success. By debugging I've noticed the following:

- The execution order of the syscalls is the same in both cases.
- The `getsockopt` call [here](https://github.com/libuv/libuv/blob/v1.x/src/unix/stream.c#L1315) returns `ECONNRESET` when the test succeeds and 0 when the test fails.
- When the test succeeds (`ECONNRESET` is reported), the poll function reports `POLLIN` && `POLLOUT`, whereas when no error is returned, it returns only `POLLOUT`.

If my analysis is correct, what would be a proper solution for this? I've been thinking about trying some operation (`write` 0 bytes maybe?) to see if the connection is established and return an error if it is not.

Thanks in advance.

**Comment by santigimeno** [comment]
I have tried sending data in this connection, but strangely it didn't fail even though the connection has not been *accepted*  by the server. Running `netstat -an` prints an `ESTABLISHED` connection in only one direction:

```
127.0.0.1.43168      127.0.0.1.9123       32975      0 1048576      0 ESTABLISHED <---- these 2 are from the 1st connection that is already established
127.0.0.1.9123       127.0.0.1.43168      1055200      0 1055220      0 ESTABLISHED
127.0.0.1.53054      127.0.0.1.9123       1055200      0 1048576      0 CLOSE_WAIT <---- from the previously closed connection
127.0.0.1.49280      127.0.0.1.9123       32975      0 1055220      0 ESTABLISHED <---- from these last connection
```

**Comment by bnoordhuis** [comment]
I didn't test in great detail but does this patch work?
```diff
diff --git a/test/test-tcp-close-accept.c b/test/test-tcp-close-accept.c
index 5517aaf..d0533e3 100644
--- a/test/test-tcp-close-accept.c
+++ b/test/test-tcp-close-accept.c
@@ -96,6 +96,9 @@ static void read_cb(uv_stream_t* stream, ssize_t nread, const uv_buf_t* buf) {
   for (i = 1; i < got_connections; i++)
     uv_close((uv_handle_t*) &tcp_incoming[i], close_cb);
 
+  /* Close server, so no one will connect to it */
+  uv_close((uv_handle_t*) &tcp_server, close_cb);
+
   /* Create new fd that should be one of the closed incomings */
   ASSERT(0 == uv_tcp_init(loop, &tcp_check));
   ASSERT(0 == uv_tcp_connect(&tcp_check_req,
@@ -103,9 +106,6 @@ static void read_cb(uv_stream_t* stream, ssize_t nread, const uv_buf_t* buf) {
                              (const struct sockaddr*) &addr,
                              connect_cb));
   ASSERT(0 == uv_read_start((uv_stream_t*) &tcp_check, alloc_cb, read_cb));
-
-  /* Close server, so no one will connect to it */
-  uv_close((uv_handle_t*) &tcp_server, close_cb);
 }
 
 static void connection_cb(uv_stream_t* server, int status) {
```

**Comment by santigimeno** [comment]
Yes, I had already tried something similar but moving the `uv_close` after the `uv_tcp_init` so the last fd was reused and it worked, but I wasn't sure if it changed the purpose of the test.
If you consider the change valid I can send a PR. Thanks

**Comment by bnoordhuis** [comment]
I _think_ it still tests what it's supposed to test (adding a new file descriptor with the same value as one that's just been removed shouldn't produce events on the old handle) but now it reuses the server's file descriptor instead of one of the client connections.  Maybe @indutny can comment, he's the original author.

If it's not a good fix, I suggest we simply ditch the test.  It tests its invariants very implicitly; simple changes to libuv's event loop implementation would invalidate it.  Such tests are usually more trouble than they're worth.

**Comment by indutny** [comment]
@bnoordhuis I believe your description is correct.

**Comment by santigimeno** [comment]
Ok. I had misread @bnoordhuis comment. His proposed change also fixes the test. I'll close my PR.

**Comment by saghul** [comment]
So, should we close this then?

**Comment by santigimeno** [comment]
No, the test is still flaky, but applying the patch @bnoordhuis should fix it

**Comment by saghul** [comment]
Ah, ok.

**Comment by santigimeno** [comment]
Fixed by https://github.com/libuv/libuv/commit/4b58985370cd6aa13f10b390b7694e891abff974 that implements the solution proposed in https://github.com/libuv/libuv/issues/799#issuecomment-204658185 by @bnoordhuis
