### ISSUE TITLE
nodejs shows SIGABRT (Aborted) @ 0 (0) on x64 CentOS

### ISSUE THREAD

**Issue by aneek** [libuv/libuv#80]
As a followup to this issue in nodejs mailing list (https://groups.google.com/forum/#!topic/nodejs/3AUlFk_oLi8).

The original issue was,
While running nodejs installed via Python 2.75 in a 64 bit Centos (5.11) version showed "Aborted" Error.
![node_error](https://cloud.githubusercontent.com/assets/584583/5546432/31b76898-8b68-11e4-9b8f-17c43d7aec26.png)
The issue was submitted in nodejs mailing. As per, Ben Noordhuis, this deals with an error code (-293) which is not possible as the limit that is set for error code is (-133) to (-1).

As requested, the details of the Unix box as follows.
1. uname -a : Linux clms-uat-app1.unicon.net 2.6.18-xenU-ec2-v1.4 #1 SMP Wed Dec 2 05:20:19 UTC 2009 x86_64 x86_64 x86_64 GNU/Linux
2. cat /etc/*elease : CentOS release 5.11 (Final)

Talked with quite a few devs in IRC, and they suggested me to use the x86 binary. So I downloaded both x64 & x86 and tried to strace both node executable in bin directory. The diff is as: https://gist.github.com/aneek/10abdb5d1e91a21cfcd6

64 bit again showed the Abort while 32 bit started to work as expected.

**Comment by saghul** [comment]
Ping

**Comment by saghul** [comment]
No follow-up, closing.
