### ISSUE TITLE
[website] Use a responsive Sphinx theme

### ISSUE THREAD

**Issue by ibc** [libuv/libuv#801]
http://docs.libuv.org/en/v1.x/

Not an expert in Sphinx so I cannot help too much, but AFAIK there are responsive themes for Sphinx.

Or may be I'm the only who reads API documentations when traveling via subway :)

**Comment by kthelgason** [comment]
Site looks fine to me in mobile safari, text is nice and readable.

Then again my phone is huge so YMMV :)

**Comment by ibc** [comment]
This is NOT a responsive design. Two columns when in portrait mode is not "nice". Two completely different text sizes (in left and right column) is not "nice":

<img width="366" alt="captura de pantalla 2016-04-02 a las 23 49 29" src="https://cloud.githubusercontent.com/assets/16191/14229201/a1f65716-f92d-11e5-8ab6-ed8bd127e179.png">

The "search" field and "GO" button are not usable:

<img width="348" alt="captura de pantalla 2016-04-02 a las 23 53 10" src="https://cloud.githubusercontent.com/assets/16191/14229214/1ebd7752-f92e-11e5-93e5-fe48713ec5c2.png">

The hyper mini "previous | next" buttons behind another layer (with print options) is not "nice" not even usable: 

<img width="376" alt="captura de pantalla 2016-04-02 a las 23 49 40" src="https://cloud.githubusercontent.com/assets/16191/14229202/a1fa4d08-f92d-11e5-8361-8167a62ea56c.png">

**Comment by saghul** [comment]
I'll see is there is a better theme we can use. I initially chose this one
because it's built-in and color-matches well with the logo.

**Comment by saghul** [comment]
Check this one out: http://notes.saghul.net

**Comment by ibc** [comment]
> http://notes.saghul.net

Looks ugly but seems responsive :)
