### ISSUE TITLE
uv_os_homedir() in src/unix/core.c returns ENOENT for "fake" /etc/passwd file

### ISSUE THREAD

**Issue by nullimpex** [libuv/libuv#810]
I'am using [niutech/node.php](https://github.com/niutech/node.php.git). It allows running node.js apps via PHP scripts on shared hosting. It also allows running npm to install node.js packages.

npm uses libuv and here is the problem

uv_os_homedir() tries to determine user home directory. First it checks some environ vars, then it tries to read /etc/passwd file. Since the passswd file on my shared hosting service is fake, getpwuid_r call for current uid, sets result to NULL. And npm fails to execute :(

Maybe uv_os_homedir() could try to read some other environ vars? Like $PWD or $DOCUMENT_ROOT

**Comment by cjihrig** [comment]
Why not just set one of the environment variables that is already checked to a value that works for your application?

**Comment by nullimpex** [comment]
Apache configuration on my shared hosting limits setting values only to variables which names begin with PHP_ :( 
Hey, how about adding PHP_HOME to uv_os_homedir()? :)

**Comment by saghul** [comment]
libuv cannot guess your home directory if all it gets are lies :-) I'm closing this since there is nothing that we can do about such spartan environment.
