### ISSUE TITLE
Possible regression in 1.9.0 on sparc64, poll_* testcases

### ISSUE THREAD

**Issue by lucab** [libuv/libuv#816]
(Preliminary report, this still needs to be properly triaged)

It looks like 1.9.0 may have introduced a regression on sparc64, as the testsuite now reproducibly fails on multiple builders for that arch with the following trace:
```
[%  64|+ 183|-   0|T   0|S   2]: poll_duplex
`poll_duplex` failed: exit code 134
Output from process `poll_duplex`:
Assertion failed in test/test-poll.c on line 198: events & context->events
=============================================================
[%  65|+ 183|-   1|T   0|S   2]: poll_unidirectional
`poll_unidirectional` failed: exit code 134
Output from process `poll_unidirectional`:
Assertion failed in test/test-poll.c on line 198: events & context->events
=============================================================
```
For further inspection, full build log from Debian autobuilders is available [here](https://buildd.debian.org/status/fetch.php?pkg=libuv1&arch=sparc64&ver=1.9.0-1&stamp=1460091262).

Previous stable version (1.8.0) was building without any failures in the testsuite.

**Comment by santigimeno** [comment]
The regression was probably introduced by my commit https://github.com/libuv/libuv/commit/c7c8e916b86d2b168e97b04d7b4c8913322c8329 :(. Would it be possible adding some `fprintf` to try to find out what's going on?

**Comment by lucab** [comment]
@santigimeno I think your guess could be on-spot. Looking at the kernel, it looks like `POLLRDHUP` is defined everywhere as 0x2000, except for sparc{32,64} where it is 2048 (0x800): https://github.com/torvalds/linux/blob/master/arch/sparc/include/uapi/asm/poll.h

Can't we use the constant provided by libc/kernel if available, and only fallback to the hardcoded value if not?

**Comment by bnoordhuis** [comment]
https://github.com/libuv/libuv/pull/817
