### ISSUE TITLE
New use case

### ISSUE THREAD

**Issue by niyamaka** [libuv/libuv#818]
Hello. I have a use case not contemplated in libuv.
It's the case when you don't want accept a new connection (uv_listen, on_connection_db).
This is a possible patch:
int uv_not_accept(uv_stream_t* server) {
  if (server->accepted_fd == -1)
    return -EAGAIN;
  uv__close(server->accepted_fd);
  server->accepted_fd = -1;
  return 0;
}

Regards
Niyamaka

**Comment by saghul** [comment]
I don't think we want to support that usecase. I'm -1.

**Comment by cjihrig** [comment]
Also -1.

**Comment by bnoordhuis** [comment]
Can you explain why that approach is preferable over `uv_accept`+ `uv_close`?

**Comment by saghul** [comment]
To add to Ben's comment, note that the connection was already technically accepted.

**Comment by niyamaka** [comment]
In my use case, it's more clean don't accept the connection in on_connection_cb because the system has reached his maximum client connection permitted.
Call uv_accept + uv_close is less clean because in fact uv_accept is called in another function (accept_connection()).
Source in https://bitbucket.org/yuneta/c-core/src/51d18e20a910/src/c_tcp_s0.c?at=default&fileviewer=file-view-default

**Comment by bnoordhuis** [comment]
That's not very compelling.  Libuv has already accepted the connection when your callback is called; `uv_not_accept()` or `uv_reject()` would be cosmetic only, the underlying mechanism would still be the same.

Given Colin's and Saúl's -1s, I'll close.

**Comment by niyamaka** [comment]
For me it's logic. You have a positive action. You haven't got the negative action.
And you are forcing me to assign unnecessary resources (taking about millions actions).
But don't warry, I'm happy. I'll hack libuv again.
Great job anyway.

**Comment by fsantanna** [comment]
Hi,

Sorry for resurrecting this issue, but I reached here by searching Google for `uv_reject`.

If the symmetry argument by @niyamaka is not compelling, how should we properly simulate `uv_reject`?

I'm currently doing this:
```
uv_tcp_t client;
ceu_uv_tcp_init(&client);
uv_accept(&server, &client);
uv_close(&client, NULL);
```

With this intent:
```
uv_reject(&server);
```

Is this reasonable?

Thanks

**Comment by saghul** [comment]
@fsantanna Yes, that's correct.  The important part here is that by the time the connection callback is called the fd was already accepted in the background, so `uv_accept` just initializes the handle with the already accepted fd.
