### ISSUE TITLE
move PPC BE testing from fedora to ubuntu

### ISSUE THREAD

**Issue by mhdawson** [libuv/libuv#827]
We've moved the PPC BE machines for Node.js from fedora to ubuntu so I'll do the same for libuv as we will likely complete remove the fedora machines.  Opening this so that libuv contributors are aware I'm making this change.

**Comment by mhdawson** [comment]
Changes made, run to validate ok with change:

https://ci.nodejs.org/job/libuv-test-commit-linux/27/

**Comment by mhdawson** [comment]
Not yet complete but running ok an PPC platforms passed so closing

**Comment by saghul** [comment]
Thanks for the heads up!
