### ISSUE TITLE
Add `gecos` to `uv_passwd_t`

### ISSUE THREAD

**Issue by sindresorhus** [libuv/libuv#831]
Related: https://github.com/nodejs/node/pull/6104#issuecomment-207728469

On OS X and Linux the [`gecos` field](https://en.wikipedia.org/wiki/Gecos_field) contains the user's fullname. Like `username`, it would return `null` on Windows.

I personally need it for my [`fullname`](https://github.com/sindresorhus/fullname) module.

-

// @silverwind

**Comment by bnoordhuis** [comment]
That's an ABI change so I'm tagging this for v2.0.0.  Pull requests welcome, please link back to this issue.

**Comment by saghul** [comment]
Closing in favor of #834.
