### ISSUE TITLE
Request for a build on Cygwin platform

### ISSUE THREAD

**Issue by njman** [libuv/libuv#832]
Hi,

In the latest Cygwin release 2.5.0, the `pthread_barrier/pthread_barrierattr` has been supported. Please see <https://cygwin.com/ml/cygwin-announce/2016-04/msg00020.html>:

> - First implementation of pthread_barrier/pthread_barrierattr functions.
 New APIs: pthread_barrierattr_init, pthread_barrierattr_setpshared,
 pthread_barrierattr_getpshared, pthread_barrierattr_destroy,
 pthread_barrier_init, pthread_barrier_destroy, pthread_barrier_wait.
 
Can the Cygwin platform be supported for a build? Thanks

**Comment by saghul** [comment]
Is that the only thing that's required? If so feel free to send a PR, but I
don't think we can support it in an "official" capacity, as in, you'll have
to fix it if we accidentally break it.

**Comment by njman** [comment]
The Neovim will benefit this request if upstream would support it. See [Compiling under Cygwin](https://github.com/neovim/neovim/issues/873).
In principle, **libuv** should support as more platforms as possible if it will take much less effort.

**Comment by bnoordhuis** [comment]
We used to support (well, "support") cygwin until almost exactly three years ago (commit 7f8130a from April 2013), when we dropped it because it had been broken for almost a year without anyone complaining.  We concluded that the intersection of cygwin users and libuv users was a rounding error and not worth the effort.

Like @saghul said, we'll accept pull requests but we won't officially support it.  For one, we don't have cygwin machines in our CI infrastructure.

**Comment by njman** [comment]
Got it, thank you, both.

**Comment by tkelman** [comment]
You can run Cygwin on AppVeyor. Note that the pthread barrier isn't the only missing thing in Cygwin, it also doesn't support unix style async IO so you'd have to make a hybrid of unix style build with windows style asyncio.

**Comment by saghul** [comment]
We use IOCP on Windows, so that shouldn't be a problem. As @bnoordhuis
said, there was no critical mass to support Cygwin, and nobody stepped up
to maintain it.

**Comment by tkelman** [comment]
It would end up being a bit of an ugly hybrid between unix pieces and windows pieces, which makes the maintenance issue a bit worse. People do ask about running libuv (or node) on the Cygwin mailing list once in a while. Cross-compiling from Cygwin with `--host=x86_64-w64-mingw32` works great, we do that all the time for Julia.
