### ISSUE TITLE
libuv Windows CI: Win 10 + VCBT

### ISSUE THREAD

**Issue by joaocgreis** [libuv/libuv#839]
I suggest that the `libuv-test-commit-windows` should test 3 configurations:

- Windows 2008 R2 with Visual Studio 2013
- Windows 2012 R2 with Visual C++ Build Tools 2015
- Windows 10 with Visual Studio 2015

This covers the 3 OS's and the 3 compilers currently available in CI.

I started a test run for this at https://ci.nodejs.org/view/libuv/job/reis-libuv-windows/3/ . Windows 2008 is good (it's the only configuration already tested).

VCBT fails because there is a variable name conflict in `vcbuild.bat`, the variable `platform` should be renamed because it is used by `VCVarsAll.bat` (perhaps to something like `msbplatform`, to match https://github.com/nodejs/node/commit/a6935574dac90b1b78fcb7f4cd7a68b4b20a084d ). I can open a pull request if there are no objections to this.

Windows 10, however, fails 21 tests: https://ci.nodejs.org/view/libuv/job/reis-libuv-windows/3/nodes=win10-vs2015/console . If the tests are run from a console in that same machine, it fails only 1: `fs_event_watch_dir_recursive` (by timeout, and increasing the timeout does not help, the test seems blocked).  So, is this a known issue?

**Comment by saghul** [comment]
> I suggest that the libuv-test-commit-windows should test 3 configurations:
> 
>     Windows 2008 R2 with Visual Studio 2013
>     Windows 2012 R2 with Visual C++ Build Tools 2015
>     Windows 10 with Visual Studio 2015
> 
> This covers the 3 OS's and the 3 compilers currently available in CI.
> 

Sounds good to me!

> I started a test run for this at https://ci.nodejs.org/view/libuv/job/reis-libuv-windows/3/ . Windows 2008 is good (it's the only configuration already tested).
> 
> VCBT fails because there is a variable name conflict in vcbuild.bat, the variable platform should be renamed because it is used by VCVarsAll.bat (perhaps to something like msbplatform, to match nodejs/node@a693557 ). I can open a pull request if there are no objections to this.
> 

No objections.

> Windows 10, however, fails 21 tests: https://ci.nodejs.org/view/libuv/job/reis-libuv-windows/3/nodes=win10-vs2015/console . If the tests are run from a console in that same machine, it fails only 1: fs_event_watch_dir_recursive (by timeout, and increasing the timeout does not help, the test seems blocked). So, is this a known issue?

I don't think this is known.

**Comment by saghul** [comment]
Oh, and thanks, Joao! :+1:

**Comment by joaocgreis** [comment]
Moving forward here, now that https://github.com/libuv/libuv/pull/868 has landed, I can change the labels under https://ci.nodejs.org/job/libuv-test-commit-windows/ to `win2008r2-vs2013` and `win2012r2-vcbt2015`. @saghul can I go ahead and do it?

`win10-vs2015` still has to be considered as work in progress because of the failures in Windows 10.

**Comment by saghul** [comment]
@joaocgreis sounds good! even if there are some tests failing, IMHO it's a good idea to have `win10-vs2015` active to track the progress.

**Comment by joaocgreis** [comment]
@saghul adding Windows 10 means that every build from now on will be red. Collaborators might get used to Windows being always red and forget to check the other two configurations that should pass. Is that desirable?

**Comment by saghul** [comment]
The libuv team is a lot smaller than the Node team, it's easier to tell everyone what to look for :-) Also this puts the pressure on you folks to iron out the issues! :trollface:

**Comment by joaocgreis** [comment]
Done, added the 3 labels. Here is a test run: https://ci.nodejs.org/job/libuv-test-commit-windows/55/

**Comment by saghul** [comment]
Thanks Joao! Seems to be "working" (the Jenkins part, that is).
