### ISSUE TITLE
win: call uv_tcp_read_start is unsafe when libuv in UV__HANDLE_CLOSING trigger write_cb

### ISSUE THREAD

**Issue by esxgx** [libuv/libuv#842]
...
int uv_tcp_read_start(uv_tcp_t* handle, uv_alloc_cb alloc_cb,
    uv_read_cb read_cb) {
  uv_loop_t* loop = handle->loop;

  handle->flags |= UV_HANDLE_READING;
....
which crashes my program.
Is it undefined behaviour to call uv_read_start after uv_close?

**Comment by esxgx** [comment]
In my program, I call uv_close in httpconn_close, but I'm sure that another read_cb (EOF) received immediately after it called httpconn_close(uv_close).  I'm so confused about the problem.
....
httpconn_close: start http 26EC4B0 handle=0x26ec4c8   -> uv_close
httpconn_close: end http 26EC4B0 handle=0x26ec4c8
httpconn_close: start http 26EC4B0 handle=0x26ec4c8

Breakpoint 1, uv_close (handle=0x26ec4c8, cb=0x401750 <httpconn_close_cb>)
    at src/win/handle.c:71
71          assert(0);
(gdb) bt
#0  uv_close (handle=0x26ec4c8, cb=0x401750 <httpconn_close_cb>)
    at src/win/handle.c:71
#1  0x0000000000401a78 in httpconn_close (http=http@entry=0x26ec4b0)
    at httpconn.c:24
#2  0x00000000004049c9 in httpconn_release (http=http@entry=0x26ec4b0)
    at httpconnmgr.c:76
#3  0x0000000000404bf1 in tunnel_postconn_response_complete_cb (
    http=0x26ec4b0, iseof=<optimized out>) at tun_postconn.c:63
#4  0x0000000000401b2f in httpconn_response_read_cb (s=0x26ec4c8,
    nread=-4095, buf=0x23eb20) at httpconn.c:103
#5  0x0000000000422782 in uv_process_tcp_read_req (
    loop=0x44c0c0 <default_loop_struct>, handle=0x26ec4c8, req=0x26ec548)
    at src/win/tcp.c:1034
#6  0x0000000000407eb0 in uv_process_reqs (
    loop=0x44c0c0 <default_loop_struct>) at src/win/req-inl.h:162
#7  0x0000000000408afc in uv_run (loop=0x44c0c0 <default_loop_struct>,
    mode=UV_RUN_DEFAULT) at src/win/core.c:355
#8  0x0000000000404694 in tunnelmgr (e=0x44f240 <default_envir>,
    ip=ip@entry=0x43e748 <__FUNCTION__.90784+456> "0.0.0.0",
    port=port@entry=1080, setting=setting@entry=0x23f5f0) at tun.c:329
#9  0x000000000043cb2a in main (argc=1, argv=0x661930) at main.c:68
(gdb)

**Comment by saghul** [comment]
> Is it undefined behaviour to call uv_read_start after uv_close?

Yes.
