### ISSUE TITLE
porting to qnx

### ISSUE THREAD

**Issue by denzmenz** [libuv/libuv#865]
Hi,

Our requirement is to run node-js on QNX.
Is libuv the only dependency that is preventing node-js  to run on QNX?

node-0-10 previously supported QNX.

What would be the scope for porting libuv to QNX 6.6? Can this be implemented using select, poll or ionotify?

-Denzil

**Comment by saghul** [comment]
Context: https://groups.google.com/forum/#!topic/libuv/eYQNxm_7mlM

**Comment by bnoordhuis** [comment]
We'll accept patches that add QNX support (provided they meet our standards) but you'll be on the hook for maintaining it.

Same goes for node.js: if it's not part of the CI matrix, it's unsupported.  Maintenance falls on the shoulders of whoever steps up.  If it bitrots, it's going to get the ax sooner or later.

> What would be the scope for porting libuv to QNX 6.6?

Take a look at src/unix/aix.c to get a feeling of what a port entails.

> Is libuv the only dependency that is preventing node-js to run on QNX?

Presumably.  V8 is known to run on QNX, although I don't believe they support it in any official capacity.

> node-0-10 previously supported QNX.

Maybe someone did a one-off fork but upstream node.js never supported QNX.

**Comment by saghul** [comment]
Closing since there is nothing actionable from our side. I subscribe to what Ben said.
