### ISSUE TITLE
Prepare 1.9.1

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#867]
After https://github.com/libuv/libuv/pull/866 lands I want to make a release so Node 6 gets a working Windows console.

This is what we have so far (nothing is semver minor, AFAIK):

28d160f darwin: make thread stack multiple of page size
a8840fb darwin: work around condition variable kernel bug
e397caa win: remove unneeded condition
46d84ea win: simplified UTF16 -> UTF8 conversions
4c945f4 win: improve uv__convert_utf16_to_utf8
9386f2c build, mingw: set LIBS in configure.ac
337e9fd test: fix POLLHDRUP related failures for AIX
d43ee0e win: clarify fsevents handling code
2753bc1 test: fix -Wformat warnings in platform test
4844c75 build: always compile with -fvisibility=hidden
4b34255 build: bump android ndk version
f57bfd4 unix: fix bug in barrier fallback implementation
f617ccc unix: error on realpath if PATH_MAX is undefined
5c6c268 test: set a big send buffer size for tcp_write_queue_order
6f17a61 win: add maxrss, pagefaults to uv_getrusage()
faea76d test: skip fs_event_close_in_callback on AIX
b9324ac unix: remove unneeded SAVE_ERRNO wrappers
322de63 unix: guard against clobbering errno in uv__free()
d03abfd win: work around sharepoint scandir bug
70d5014 android: pthread_sigmask() does not set errno
4a5b3f9 unix: delay signal handling until after normal i/o
572d315 unix,fs: code cleanup of uv_fs_event_start for AIX
f28a112 test: fix fs_event_watch_file_current_dir for AIX
60ef1e7 linux: fix long lines in linux-core.c
732fb03 linux: don't abort on malformed /proc/stat
2bf7b38 linux: fix fd leaks in uv_cpu_info() error paths
be8e237 Revert "win,build: remove unused build defines"
3410974 doc: add ability to live reload and regenerate HTML
375ba2d unix: use POLL{IN,OUT,etc} constants directly
3819e48 win: fix var declaration to be C89 compliant
7acb6bd test: skip early bind tests if no IPv6 is supported
4aeed1a unix: implement uv__fs_futime for AIX 7.1
a84caf6 test: handle root home directories
d476185 Now working on version 1.9.1
4b444d3 Add SHA to ChangeLog

/cc @libuv/collaborators

**Comment by yjhjstz** [comment]
👍

**Comment by bnoordhuis** [comment]
Doesn't 6f17a61 ("win: add maxrss, pagefaults to uv_getrusage()") qualify as semver-minor?

**Comment by saghul** [comment]
Maybe... it just fill up a couple of fields that were previously unpopulated on Windows. We can make that 1.10, I'm fine with that.

**Comment by bnoordhuis** [comment]
Grey area, I agree.  I'll leave it up to you.

**Comment by cjihrig** [comment]
@saghul I'm interested in seeing how the release process goes. Is it documented somewhere?

**Comment by saghul** [comment]
It's basically using this tool: https://github.com/libuv/libuv-release-tool plus uploading the exe files generated by appveyor. We can do a screen-sharing session if you want!

**Comment by cjihrig** [comment]
Sure, that sounds good. It would probably be good if we put together something like https://github.com/nodejs/node/blob/master/doc/releases.md too.

**Comment by saghul** [comment]
Sure, let's do that on Monday then.

**Comment by saghul** [comment]
So, 1.9.1 is out. I'ma making the Node PR now.
