### ISSUE TITLE
windows installer silent / automated install

### ISSUE THREAD

**Issue by lws-team** [libuv/libuv#871]
Hi -

I want to add libuv to our Appveyor build testing for libwebsockets.

I found that you prepare windows packages already (thanks to Roger Light).

However testing them with wine, there doesn't seem to be any way to get them to install silently / with no prompts.  Openssl packages can be installed unattended in appveyor using "/silent /verysilent /sp- /suppressmsgboxes".

Can we maybe enable unattended install options in the installer so I can use them in appveyor?  Or is there another way?

Thanks.

**Comment by txdv** [comment]
7z can extract the libuv.dll contained in the installer

**Comment by saghul** [comment]
I have no idea how the insaller works, TBH, so I'm afraid I cannot help you there. I'd take a patch, if it's small enough.

PS: libwebsockets user here, thanks for your work!

**Comment by lws-team** [comment]
Ah glad you're getting something from lws.  For my part lws is increasingly using libuv both for epoll and for simple cross-platform support.

I'd be happy if I could provide a patch, but I don't have or want windows to try it out.

Although supporting unattended install would be best, txdv has a good point.  It should be enough to use 7z to get the dll out and then host the dll myself and fetch it from there.  There should be a way to get Appveyor to cp it somewhere workable.  I'll try this flow later and report back.

**Comment by lws-team** [comment]
I was able to use 7z to unpack your install image and use it as a zip in appveyor successfully.

Thanks a lot for the advice!
