### ISSUE TITLE
Watching a directory for file modification (ie. writing to a file) is unsupported on AIX

### ISSUE THREAD

**Issue by iWuzHere** [libuv/libuv#882]
While working on the fswatch related stuff for AIX I came across the following:

Currently with ahafs, if you watch a directory the only events you can get are the following:

```
AHAFS_MODDIR_CREATE -> A fs object was created under the watched dir
AHAFS_MODDIR_UNMOUNT -> watched dir was unmounted
AHAFS_MODDIR_REMOVE -> a fs object was removed under the watched dir
AHAFS_MODDIR_REMOVE_SELF -> the watched dir was renamed/deleted
```
([source](https://www.ibm.com/support/knowledgecenter/ssw_aix_71/com.ibm.aix.osdevice/aix_ev_in_predef_moddir.htm))

What this does not allow, how ever is the option of monitoring a file under the directory for a change,
ie. if I were to write to a file under the watched dir I would not receive any events for it.
To receive an event for writing to a file, I have to watching the file, not the directory.

Events receivable for a watched file ([source](https://www.ibm.com/support/knowledgecenter/ssw_aix_71/com.ibm.aix.osdevice/aix_ev_in_predef_modfl.htm)) 

```
AHAFS_MODFILE_WRITE -> file was written to
AHAFS_MODFILE_UNMOUNT -> fs that file was on was unmounted
AHAFS_MODFILE_MAP -> a portion of the file has mapped for writing by another process
AHAFS_MODFILE_REMOVE -> file has been removed
AHAFS_MODFILE_RENAME -> file has been renamed
AHAFS_MODFILE_FCLEAR -> fclear was called on file
AHAFS_MODFILE_FTRUNC -> ftrunc was called on file
AHAFS_MODFILE_OVERMOUNT -> the file has been mounted over
```

The question that arises is whether or not we want to emulate this feature for AIX (@mhdawson is in favour of emulating this behavior).

I have some WIP code which can be found under [here](https://github.com/iWuzHere/libuv/commits/fixwatchdir) (please excuse the highly uninformative commit messages, I usually rebase and sqaush all the changes into one commit with messages after im done :stuck_out_tongue: )

Issues:
* Can very easily run out of fd's for the process as we create and monitor a new .mon file for each filed under our watched directory.
* Have to maintain a list of all watched files under a directory and remove/add to it according to incoming events. This leads to increased memory usage, slow perf etc.
* (Havent done this part yet) Have to deal with multiple events produced for one change. Example:
  * Watch a directory, and thus all files underneath it
  * Delete a file under the watched directory
  * we now have both MODFILE_REMOVE event and a MODDIR_REMOVE event (which one do we ignore)
  * Does renaming a file get us both a MODFILE_RENAME and MODDIR_CREATE event?

Overall it seems very hacky(?) in nature.

Is this something worth continuing and creating a PR for?
Is there a better way to go about this?
Is there any of the other supported systems that have this issue?

Thoughts? 
/cc @saghul @bnoordhuis @cjihrig @indutny @piscisaureus

**Comment by bnoordhuis** [comment]
kqueue on the BSDs has more or less the same issue and we don't try to paper over that.  You quickly end up with a poor reimplementation of fam or gamin.

I think the contract is fairly well understood by libuv users:

1. `uv_fs_event_t` is efficient but a best-effort attempt.
2. `uv_fs_poll_t` is costlier but more accurate and portable.

**Comment by saghul** [comment]
Agreed with @bnoordhuis. A documentation PR would be nice to let other know about the limitation though.
