### ISSUE TITLE
FAIL: test/run-tests

### ISSUE THREAD

**Issue by niukey** [libuv/libuv#897]
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:4086: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/xing/fuwq/libuv'
Makefile:4342: recipe for target 'check-am' failed
make: *** [check-am] Error 2

**Comment by saghul** [comment]
Please paste the output of the actual failing test, ie, everything before this message.

**Comment by niukey** [comment]
=============================================================
[%  60|+ 175|-   0|T   0|S   0]: getaddrinfo_fail
`getaddrinfo_fail` failed: timeout
Output from process `getaddrinfo_fail`: (no output)
=============================================================
[%  74|+ 215|-   1|T   0|S   0]: poll_close_doesnt_corrupt_stack
`poll_close_doesnt_corrupt_stack` skipped
Output from process `poll_close_doesnt_corrupt_stack`:
Test only relevant on Windows
=============================================================
[%  75|+ 215|-   1|T   0|S   1]: poll_closesocket
`poll_closesocket` skipped
Output from process `poll_closesocket`:
Test only relevant on Windows
=============================================================
[%  86|+ 247|-   1|T   0|S   2]: fs_event_watch_dir_recursive
`fs_event_watch_dir_recursive` skipped
Output from process `fs_event_watch_dir_recursive`:
Recursive directory watching not supported on this platform.
=============================================================
[%  96|+ 275|-   1|T   0|S   3]: thread_stack_size
`thread_stack_size` skipped
Output from process `thread_stack_size`:
OSX only test
=============================================================
[% 100|+ 284|-   1|T   0|S   4]: Done.
FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
Makefile:4086: recipe for target 'check-TESTS' failed
make[1]: *** [check-TESTS] Error 1
make[1]: Leaving directory '/home/xing/fuwq/libuv'
Makefile:4342: recipe for target 'check-am' failed
make: *** [check-am] Error 2

**Comment by saghul** [comment]
> getaddrinfo_fail failed: timeout

This implies a problem with your system. The test tries to resolve a nonexistent domain, so it should fail immediately. We have seen networks where DNS resolvers return something even for this broken address. Nothing to worry about. Thanks for reporting though!
