### ISSUE TITLE
uv_translate_sys_error in v0.10 does not translate/propagate ENFILE

### ISSUE THREAD

**Issue by rmg** [libuv/libuv#899]
I'm not sure if there's any motivation to cut another v0.10.x release, so I haven't even bothered with the 1-line patch to fix this. I'm mostly reporting this for the benefit of people searching for it.

The giant switch statement in src/unix/error.c does not include a translation for `ENFILE` to `UV_ENFILE`, even though `UV_ENFILE` is defined.

Where I've seen this manifest is in node v0.10.x in a test that opens files in a loop in order to intentionally trigger an `EMFILE`. It works when it is run by itself. If the same test is run concurrently, the OS instead generates an `ENFILE` (hey, what do you know, they actually _are_ different errors!) instead, which ends up bubbling up as an `UNKNOWN` (aka `UV_UNKNOWN`).

Reported downstream in nodejs/node#7199, for completeness.

**Comment by saghul** [comment]
I'm not sure how other @libuv/collaborators feel, but unless Node really needs us to make a new release (I can do that), libuv 0.X is dead to me.

**Comment by cjihrig** [comment]
Unless it's causing real problems, I don't think we should bother for Node 0.10.

**Comment by indutny** [comment]
-0 from me.

**Comment by saghul** [comment]
Fixed in #904
