### ISSUE TITLE
unix: add uv_tcp_user_timeout fonction

### ISSUE THREAD

**Issue by msoula** [libuv/libuv#900]
Hi,

I'm working on a nodejs server that declares a tcp streaming endpoint. To detect dead peers, I needed to add a function that let dev set TCP_USER_TIMEOUT value that specifies the maximum amount of time in ms that transmitted data may remain unacknowledged before TCP will forcefully close the
corresponding connection and return ETIMEDOUT to the application.

For this, I had to modify both nodejs and libuv projects.

I though you guys could be interested.

**Comment by saghul** [comment]
FWIW, you can already do that without modifying libuv. You could even write a Node binary addon to do it: using `uv_fileno` you can get the real file descriptiptor (or Windows HANDLE) of a libuv handle, and then you can `setsockopt` on it.

On Node `foo._handle.fd` will give yout the fd, you're just missing setting the socket option part.

**Comment by msoula** [comment]
I thought I have to patch libuv to call system functions such as `setsockopt`.
Do you know how to do this in nodejs?

**Comment by saghul** [comment]
You need to write a binary addon for Node which takes the fd and calls `setsockopt` on it with the option you want.

**Comment by msoula** [comment]
Great, my addon is perfectly working. I didn't know about this mecanism.
So I guess we can close this issue since I've manage to modify socket option without having to patch libuv or nodejs.

Thanks for you help @saghul!
