### ISSUE TITLE
Make one more libuv 0.10 release

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#906]
- [x] https://github.com/libuv/libuv/pull/903
- [x] https://github.com/libuv/libuv/pull/904
- [x] https://github.com/libuv/libuv/pull/905

~~After these lands let's do one last 0.10 and call it a day. You've served us well, 0.10, we'll never forget you.~~ :fire: :fire: :fire:

**UPDATE**: we'll keep it in security-fixes-only mode until Node 0.10 is EOL.

/cc @libuv/collaborators @rvagg

**Comment by bnoordhuis** [comment]
I would like to keep it on life support until the end of the year, to coincide with the EOL of node.js v0.10, just in case a critical bug or security flaw shows up.

**Comment by saghul** [comment]
Oh, ok. I'll update #905.

**Comment by iWuzHere** [comment]
Sounds good to me!

**Comment by saghul** [comment]
I updated #905, PTAL.

**Comment by saghul** [comment]
PRs landed. I'll make the release on Monday. If anyone has comments or something else needs to be included, please let me know.

**Comment by saghul** [comment]
Release is a go! I'll close this and make a PR to Node.
