### ISSUE TITLE
in Linux why  the client loop must same as server loop

### ISSUE THREAD

**Issue by love19862003** [libuv/libuv#915]
i used per thread per loop. 
i used tcp listen in a thread with a loop ,and i want to run the client in another thread (another loop) for net io service.
but when i call function uv_accept . that is a assert with in the file  src\unix\stream.c . 
------------------------------------------------------------------------------
int uv_accept(uv_stream_t* server, uv_stream_t* client) {
  int err;

  /* TODO document this */
  assert(server->loop == client->loop);

  if (server->accepted_fd == -1)
    return -EAGAIN;

-----------------------------------------------------------------------------------

is that mean the client loop must same as server loop. in old version that is not have the assert.

**Comment by saghul** [comment]
This is by design. The libuv loop is not thread safe, so you can't initialize a handle that belongs to a loop from another. This was never possible. If you where relying on it because there was no assert at some point, that was a mistake, I'm afraid.

The behavior is now properly documented [here](http://docs.libuv.org/en/v1.x/stream.html#c.uv_accept) and has been since v1.0.

Note to self: remove that TODO note.

**Comment by love19862003** [comment]
OK。 thanks. i am now used it in the same loop .   but i am worry Inefficiency in the loop with so much client connections in the same loop to call read and write .

2016-06-15 

love19862003 



发件人：Saúl Ibarra Corretgé <notifications@github.com>
发送时间：2016-06-15 15:44
主题：Re: [libuv/libuv] in Linux why the client loop must same as server loop (#915)
收件人："libuv/libuv"<libuv@noreply.github.com>
抄送："fanny.wu"<love19862003@163.com>,"Author"<author@noreply.github.com>

This is by design. The libuv loop is not thread safe, so you can't initialize a handle that belongs to a loop from another. This was never possible. If you where relying on it because there was no assert at some point, that was a mistake, I'm afraid.
The behavior is now properly documented here and has been since v1.0.
Note to self: remove that TODO note.

**Comment by saghul** [comment]
Don't worry about that. The polling mechanisms we sue have been designed for high load. More threads won't necessarily help.

**Comment by love19862003** [comment]
OK . thanks very much  for you help.

2016-06-15 

love19862003 



发件人：Saúl Ibarra Corretgé <notifications@github.com>
发送时间：2016-06-15 15:44
主题：Re: [libuv/libuv] in Linux why the client loop must same as server loop (#915)
收件人："libuv/libuv"<libuv@noreply.github.com>
抄送："fanny.wu"<love19862003@163.com>,"Author"<author@noreply.github.com>

This is by design. The libuv loop is not thread safe, so you can't initialize a handle that belongs to a loop from another. This was never possible. If you where relying on it because there was no assert at some point, that was a mistake, I'm afraid.
The behavior is now properly documented here and has been since v1.0.
Note to self: remove that TODO note.

**Comment by williamhong163** [comment]
Maybe it is a flaw of libuv. I wrote a epoll test code in c using a single listening thread and multiple working threads, it is more effective than libuv dose. When forcing to a single working thread, it shows same results.

**Comment by saghul** [comment]
The behavior is that way by design and is documented: https://github.com/libuv/libuv/issues/915#issuecomment-226112652
