### ISSUE TITLE
A  confusion about uv_pipe_queue_read

### ISSUE THREAD

**Issue by paohui0117** [libuv/libuv#920]
line 1127 in win\pipe.c:

if (!RegisterWaitForSingleObject(&req->wait_handle,
            req->u.io.overlapped.hEvent, post_completion_read_wait, (void*) req,
            INFINITE, WT_EXECUTEINWAITTHREAD)) 
why use req->u.io.overlapped.hEvent instead of req->event_handle?Could someone tell me？
Thank you very much.

**Comment by bnoordhuis** [comment]
Can you use the mailing list for questions?  We try to keep the issue tracker restricted to bug reports, feature requests and pull requests, to keep the S/N ratio high.  Thanks.
