### ISSUE TITLE
fs: recursive mkdir

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [libuv/libuv#923]
I know this is gonna be a huge bike shed, but I wanted it to post at least for search engine visibility:

Have minimal recursive `mkdir` or `mkdir -p` for the API? There is a matching function in `shell32.dll`, [go has it](https://golang.org/src/os/path.go?s=488:535#L9), `make` has it buil-in, `gcc` doesn't, and JS implementations look clumsy.

Downstream, in node terms I wouldn't call it an addition to the "node standard library" rather fixing a unix shortsightedness (maybe). Also specific error handling seems to be more pleasant in C in this case, imo.

Close this quickly if needed :)

**Comment by saghul** [comment]
[Python also has it](https://docs.python.org/2/library/os.html#os.makedirs), FWIW.

**Comment by eljefedelrodeodeljefe** [comment]
Ah, also weirdly there is `uv__mkdir_p` for AIX [here](https://github.com/libuv/libuv/blame/b9324acb75153cfd386d4dd6433b19b69ff6d99e/src/unix/aix.c#L524-L548) (I had to look up what AIX is though, so please don't quote me).

**Comment by iWuzHere** [comment]
Yeah, that was added so that we could create directories so that we could properly use AHAFS for file watching stuff

**Comment by eljefedelrodeodeljefe** [comment]
Dragging in a critical voice I assume: @bnoordhuis

**Comment by bnoordhuis** [comment]
I'm not dead set against it but why?  The npm package works perfectly fine.  Why reinvent the wheel?

**Comment by eljefedelrodeodeljefe** [comment]
I knew you are not rigorously against it, but a wise mind anyhow :) Since it is avery basic task, something I believe usesr expect to work out of the box in the overall concept of `mkidr` in UNIX. Also take the libuv-case: the authors deemed it necessary to implement it theirselves, they have no `npm`.

The argument is: if it becomes customary it should be manifested to reduce intrinsic risk due to the complexity of dependency management.

**Comment by cjihrig** [comment]
Is the goal just to get this in libuv, or into Node as well. I think there is a decent chance of this getting into libuv, but you're going to meet a lot of resistance in Node.

**Comment by eljefedelrodeodeljefe** [comment]
libuv. If node wants to take, it would be a welcomed side effect.

**Comment by eljefedelrodeodeljefe** [comment]
FWIW, added a PR. Implementation is trivial, but the mkdir-API would be decently fixed, imo.

**Comment by bigeasy** [comment]
Curious as to why there isn't a way to build something like this as a package, add-on,etc. I'm getting (re-)oriented with `libuv`. I'm wondering if there's a project best-practice or package system that works well with it.

**Comment by cjihrig** [comment]
Since #935 was closed, I'm going to close this too.

**Comment by cjihrig** [comment]
@bigeasy you could be a pioneer for @saghul's libuv-extras idea.

**Comment by saghul** [comment]
Indeed!

**Comment by bigeasy** [comment]
Sounds like fun. I'll check back in on the weekend with it's my coder me time.

**Comment by bigeasy** [comment]
Did this ever happen using the extension mechanism?

**Comment by saghul** [comment]
I'm afraid not.
