### ISSUE TITLE
feature request: fs copy

### ISSUE THREAD

**Issue by ronkorving** [libuv/libuv#925]
Apple just announced a new file system that will have new system calls for optimized copies (they're instant, and don't require reading/writing all file/directory data). I think it would be a great opportunity for libuv (and by extension Node) to expose a copy API that can tap into that.

More info in this WWDC talk: https://developer.apple.com/videos/play/wwdc2016/701/

**Comment by bnoordhuis** [comment]
As a rule of thumb, libuv only exposes functionality that can be reasonably implemented on a majority of the supported platforms.

**Comment by ronkorving** [comment]
file copy can be implemented on all platforms, right? And the more file system knowledge you have, the more optimal it can be implemented (in the case of macOS Sierra, very optimally). That's where libuv can shine, right?

**Comment by saghul** [comment]
I think having a `uv_fs_copyfile` would be a good addition. Windows has CopyFile, but Unix is a jungle, as per usual. For example, see: http://stackoverflow.com/questions/2180079/how-can-i-copy-a-file-on-unix-using-c

OSX has copyfile(3) since 10.5, so I'd assume *they* take care of making it as fast as possible in their own file system.

@ronkorving you just volunteered to write the code, right? I volunteer to review it :-)

**Comment by ronkorving** [comment]
Challenge accepted :) (may take some time though)

**Comment by eljefedelrodeodeljefe** [comment]
@ronkorving I have a one and a decent setup for dev. If you do a PR I can submit a PR to your branch.
Always given that this is able to move forward...

**Comment by ronkorving** [comment]
Awesome, much appreciated! Let's make this happen!

**Comment by lucab** [comment]
For reference, Linux 4.5 gained [copy_file_range(2)](https://kernelnewbies.org/Linux_4.5#head-6df3d298d8e0afa8e85e1125cc54d5f13b9a0d8c).

**Comment by jinmel** [comment]
I am currently looking in to this issue. I think we should discuss what the interface would be for uv_fs_copyfile. copy_file_range(2) in unix has offset parameters whereas copyfile(3) in OSX and CopyFileEx in windows does not.

**Comment by jinmel** [comment]
I am currently looking in to this issue. I think we should discuss what the interface would be for uv_fs_copyfile. copy_file_range(2) in unix has offset parameters whereas copyfile(3) in OSX and CopyFileEx in windows does not.

**Comment by sam-github** [comment]
I'm not at all clear what this issue is discussing.

Is it for make a copy of actual files on-disk? That is what Windows `CopyFile()` does.

Or is it for zero-copy transfer of data between file *descriptors* (or their Windows equivalent)? That is what `sendfile()`, `splice(), and `copy_file_range()` do.

And I couldn't watch the WWDC link in the issue on Chrome on Linux, maybe its Mac-only?

**Comment by ronkorving** [comment]
It's for copying files on disk. Right now (in Node) you would open one file and through user land buffers of user-defined size copy data chunk-by-chunk. There are syscalls that should be able to do a better job at this. On top of that (and that was the trigger for this), on macOS with AppleFS file copy is *very* cheap as it's copy-on-write (meaning you can copy a 1 GB file in microseconds).

**Comment by jinmel** [comment]
When would kernel level copy file feature be introduced in bsd?
I am working on this issue but I am still wondering that I need to implement for all archs when I add a new uv_fs interface to get merged into main line

**Comment by llafuente** [comment]
don't need to be a syscall but need to be implemented so in those archs: read and write

**Comment by jinmel** [comment]
@llafuente you mean like uv_fs_sendfile_emul?

**Comment by llafuente** [comment]
I mean emulate what copy does, using uv_fs_read & uv_fs_write
maybe need to use uv_fs_chmod & uv_fs_chown if permissions are preserved, I don't know, just to summarize

**Comment by zkat** [comment]
fwiw, this would help _tremendously_ with stuff like npm and Yarn, which do some pretty heavy file copying tasks. Having this natively available would yield significant speed boosts on platforms where it's available without requiring npm to use native modules for this.

**Comment by saghul** [comment]
@ronkorving @eljefedelrodeodeljefe did any of you folks get around playing with this? (no pressure, if there is no time then 🤷‍♂️ )

**Comment by ronkorving** [comment]
@saghul I'm afraid not. With macOS High Sierra announced (with APFS support), I guess it's becoming more interesting ;)

**Comment by Daniel15** [comment]
> With macOS High Sierra announced (with APFS support), I guess it's becoming even more interesting

There's already ports of ZFS for Mac OS (not sure how reliable they are), and on Linux you can already use btrfs and zfs for copy-on-write. btrfs works pretty well with Docker too. No need to wait for some fancy new Apple thing to take advantage of it. 😉

**Comment by cjihrig** [comment]
Would it be useful to start with a PR for a simple implementation that could be iterated on? If so, I can probably start the work for this.

**Comment by saghul** [comment]
@cjihrig sure thing!

**Comment by cjihrig** [comment]
It's been a while, so I thought I'd check in on this issue. I'm making some progress at https://github.com/cjihrig/libuv/tree/copy. I still have to add the Windows bits, but `CopyFile()` doesn't seem horrible (*knocks on wood*). Right now, `copyfile(3)` is used on macOS, and existing libuv APIs are used on the other platforms.

The current function signature is shown below, but I think a `flags` argument might be helpful.

```
UV_EXTERN int uv_fs_copyfile(uv_loop_t* loop,
                             uv_fs_t* req,
                             const char* path,
                             const char* new_path,
                             uv_fs_cb cb);
```

**Comment by Daniel15** [comment]
@cjihrig  - I assume your current implementation wouldn't be able to take advantage of copy-on-write filesystems on Linux, since it's using a buffer to copy the file? Is there a way to copy the file in a way similar to what `cp --reflink=auto` would?

**Comment by Daniel15** [comment]
I took a look at the [source code for `cp`](https://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=blob;f=src/copy.c;h=a2eee1be5204630c33bb8d3008da3f7da018b8fe;hb=HEAD#l330), and it looks like it uses the `ficlone` ioctl if available. http://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html. Would be good to have this here too 😃

**Comment by cjihrig** [comment]
It would probably be possible. If anything, I'd suggest it as an option on platforms that support it. https://unix.stackexchange.com/questions/80351/why-is-cp-reflink-auto-not-the-default-behaviour makes some good arguments for not making it the default behavior.

**Comment by saghul** [comment]
Quick note (for @cjihrig or anyone who may work on this): we cannot event look at coreutils, it's GPL.

**Comment by eljefedelrodeodeljefe** [comment]
Thanks for the efforts @cjihrig 🎉

**Comment by mqudsi** [comment]
As the author of the "kernel mode file copy" answer in the linked stackoverflow question: even on platforms that don't have an "instant" copy (which is probably just using the fs' COW functionality), [there are still options that don't involve shuttling massive data between user and kernel space](https://stackoverflow.com/a/2180157/17027) (esp. bad after spectre/meltdown with the associated slowdowns). 

`fcopyfile` on BSD and `CopyFile(W)` on Windows are the easy ones, but `splice` and `sendfile` are also optimized to do that on certain versions of other platforms, too.

**Comment by bnoordhuis** [comment]
Libuv uses `CopyFile()` on Windows and (as a fallback) `sendfile()` on the Unices, FWIW.
