### ISSUE TITLE
Ask a question, how to post a task to main thread in node.Please my codes.

### ISSUE THREAD

**Issue by classfellow** [libuv/libuv#931]
void RcibHelper::PrintLogs(const std::string & info, async_req * req){
if (fp_){
std::string content = info + "\n";
fputs(content.c_str(), fp_);
}
//TODO use direct way
uv_queue_work(uv_default_loop(),
&req->req,
DoNopAsync,
(uv_after_work_cb)AfterAsync);
}

PrintLogs runs in a new thread that created when my c++ module required. But uv_queue_work actually only can be invoked on the main thread. 

Is there a way to do same thing safely?

**Comment by classfellow** [comment]
```c++
void RcibHelper::PrintLogs(const std::string & info, async_req * req){
if (fp_){
std::string content = info + "\n";
fputs(content.c_str(), fp_);
}
//TODO use direct way
uv_queue_work(uv_default_loop(),
&req->req,
DoNopAsync,
(uv_after_work_cb)AfterAsync);
}
```
`PrintLogs` runs in a new thread that created when my c++ module required. But uv_queue_work actually only can be invoked on the main thread.

Is there a way to do same thing safely?

**Comment by bnoordhuis** [comment]
Can you use the mailing list for questions?  We try to keep the bug tracker focused on development of libuv itself.

I'll give you a hint though: read up on `uv_async_send()`.  Good luck.
