### ISSUE TITLE
How to control the transmission speed under libuv?

### ISSUE THREAD

**Issue by metalwood** [libuv/libuv#933]
As we all know, libuv is an asynchronous network library, it will do its best to send out the data, however, in some cases, we can not take all the bandwidth, transmission speed needs to be controlled at the specified value, how to do this with libuv api?

**Comment by saghul** [comment]
You can stop writing in your application after a certain amount of bytes have been queued. You can check that with http://docs.libuv.org/en/v1.x/stream.html#c.uv_stream_t.write_queue_size

PS: Please use the mailing list for questions, we try to keep the issue tracker for bugs and feature requests.
