### ISSUE TITLE
libuv.org is empty

### ISSUE THREAD

**Issue by ruipacheco** [libuv/libuv#94]
The current website is almost empty with a simple folder called `dist` in it.

**Comment by tadman** [comment]
Why can't someone add, at the very least, an HTTP redirect to the GitHub page? Slapping something together in [GitHub Pages](https://pages.github.com/) with a `CNAME` file would plug this hole if someone can alter the DNS for it.

**Comment by saghul** [comment]
We'll get there, we've just been busy with other things.
