### ISSUE TITLE
Use `git-secure-tag` for releases

### ISSUE THREAD

**Issue by indutny** [libuv/libuv#945]
This provides stronger security guarantees for signed tags, will also make things more secure for `gypkg` 😉 

See: https://github.com/nodejs/node/pull/7603
See: https://github.com/indutny/git-secure-tag

cc @bnoordhuis @saghul @libuv/collaborators

**Comment by bnoordhuis** [comment]
This guy, always peddling his wares.

Saúl is our prime releaser, it's up to him.

**Comment by saghul** [comment]
I'll take a look.

**Comment by indutny** [comment]
Thank you!

**Comment by cjihrig** [comment]
I've used this before in Node. I'm fine with using it in libuv. You'd have to update the release tool I think. I'm going to close this, but feel free to update the release tool.
