### ISSUE TITLE
You need to install gyp in build/gyp first. See the README.

### ISSUE THREAD

**Issue by dragonahao** [libuv/libuv#946]
It occurred when i compile android  

Cleaning up...
Done. 
You need to install gyp in build/gyp first. See the README.

**Comment by dragonahao** [comment]
i add gyp in windows with python2.7 ,then it occurred 
gyp\__init__.py", line 37 print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
what happen ?

**Comment by saghul** [comment]
Can you please indicate the commands you're running and what the actual output really is? FWIW I don't think compiling for Android on Windows is supported.

**Comment by saghul** [comment]
no follow up, closing
