### ISSUE TITLE
uv_write_cb called repeatedly after uv_write

### ISSUE THREAD

**Issue by Zert** [libuv/libuv#947]
Hello
When I make multiple (5-10) uw_write calls for TCP sockets in the same time (well, may be milliseconds between them), sometimes I have a very strange behaviour of uw_write_cb callback: it seizes a whole loop and repeatedly called with status=0 (what is normal) until program interrupted by Ctrl+C.
What kind of information should I provide you to find what is wrong?

**Comment by cjihrig** [comment]
> What kind of information should I provide you to find what is wrong?

Ideally, code to reproduce the bug, as well as libuv version and OS info.

**Comment by saghul** [comment]
Are you using multiple threads? Reusing uv_write_t structures?

**Comment by Zert** [comment]
> Are you using multiple threads? Reusing uv_write_t structures?

Single thread

> Reusing uv_write_t structures?

No

**Comment by saghul** [comment]
Then that shouldn't happen. Can you make a test case which demonstrates the issue? Our test suite uses uv_write extensively and I'm not aware of such issue at the moment. Thanks!

**Comment by Zert** [comment]
Yes, I need to extract this code out of my project, it is not too easy though

**Comment by Zert** [comment]
I've corrupted memory, sorry :(
