### ISSUE TITLE
Wrong printf format specifier width when building windows x64

### ISSUE THREAD

**Issue by knopp** [libuv/libuv#955]
`libuv\src\win\fs-event.c(408): warning C4477: '_snwprintf' : format string '%.*s' requires an argument of type 'int', but variadic argument 2 has type 'std::size_t'`

`file_info->FileNameLength / sizeof(WCHAR)` is 64bit, but printf expects int precision

i.e. add extra cast
`file_info->FileNameLength / (DWORD)sizeof(WCHAR)`

**Comment by txdv** [comment]
Dont you want to write the patch?

**Comment by knopp** [comment]
Sorry, where I my manners :) I'll submit pull request later today.

**Comment by cjihrig** [comment]
@knopp friendly ping.

**Comment by knopp** [comment]
I thought I had forgotten something. 

https://github.com/libuv/libuv/pull/963
