### ISSUE TITLE
uv_accept in one thread and uv_read_start from other thread

### ISSUE THREAD

**Issue by tigranbs** [libuv/libuv#961]
Hi I'm trying to develop network application with `multithreaded` network read write requirement.
I've implemented a lot with `libuv`, but now I can't find any resource to solve multithreaded issue.

I have `thread A` which is running only server binded socket and I want to use it  only for accepting connections, and after having connection accepted I want to start reading from `thread B` which is running another libuv loop.
So the point is to have 1 loop just for accepting connections and another loop just for reading data from that connections.

Is there a way to do that ? (even by hacking something :) )

```c
    // Accept connection
    if(uv_accept(server, (uv_stream_t *)client) == 0) {

       ..................
       ..................

        // how can I call uv_read_start for a different loop ???
        int r = uv_read_start((uv_stream_t *)client, alloc_cb, on_read);
        if(r) {
            uv_close((uv_handle_t*) client, close_client);
            return;
        }

    } else {
        uv_close((uv_handle_t*) client, close_client);
    }
```

**Comment by saghul** [comment]
What you need to do is send the handle over to the other thread and start reading there. See [uv_write2](http://docs.libuv.org/en/v1.x/stream.html#c.uv_write2).

PS: In the future please use the mailing list for questions.
