### ISSUE TITLE
[v2] Learn / adjust based on the Electron integration

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#965]
I had looked into this long ago, but yesterday's [blog post](http://electron.atom.io/blog/2016/07/28/electron-internals-node-integration) prompted me to document this.

Electron integrates the libuv and Chromium event loops, by polling the libuv event loop in a thread.

They do, however, patch libuv to get notified about when an i/o handle is added to the loop, to restart the polling (on Unix): https://github.com/electron/node/commit/4629dde7c0df4bc12b4d1f1798f8d676f94f15ea

On Windows the polling is more artisanal, by accessing loop->iocp: https://github.com/electron/electron/blob/master/atom/common/node_bindings_win.cc

The embedding is done here: https://github.com/electron/electron/blob/master/atom/common/node_bindings.cc

On Windows, subprocesses are launched with `CREATE_NO_WINDOW`, maybe we can expose that flag: https://github.com/electron/node/commit/ae1cbcd7b7d71061ed0dc24256f2b962f258a132

Maybe we can incorporate some of the stuff they need. Electron is widely used project, so let's take this as a "seen used in the wild" to make libuv better.

**Comment by cjihrig** [comment]
Just out of curiosity, how would `CREATE_NO_WINDOW` interact with the existing `UV_PROCESS_WINDOWS_HIDE`?

**Comment by saghul** [comment]
One seems related to console apps and the other one to any application?

**Comment by cjihrig** [comment]
I believe this can be closed now.
