### ISSUE TITLE
Delete old branches if they can be

### ISSUE THREAD

**Issue by piscisaureus** [libuv/libuv#97]
- https://github.com/libuv/libuv/tree/cpp-ify (created by @bnoordhuis)
- https://github.com/libuv/libuv/tree/ipc_threads (created by @igorzi; I'll take responsibility for that)
- https://github.com/libuv/libuv/tree/no-linger (created by @bnoordhuis)
- https://github.com/libuv/libuv/tree/prefork (created by @piscisaureus)
- https://github.com/libuv/libuv/tree/threadpool-rework (@bnoordhuis again)

The windows branches can go; both ipc_threads and prefork are good ideas (both related to making single-process "cluster" easier/faster). I expect the ideas to re-emerge in future libuv, but the patches are stale and we can drop them.

**Comment by txdv** [comment]
lol, compared to what we had before, currently the branch list is very sleek and lean

**Comment by piscisaureus** [comment]
@bnoordhuis  ?

**Comment by bnoordhuis** [comment]
Yes, fine.  threadpool-rework is the only one with significant changes and I still have that one in my local fork.

**Comment by piscisaureus** [comment]
Ok, done.

> Yes, fine. threadpool-rework is the only one with significant changes and I still have that one in my local fork.

I don't have any problem in principle with WIP branches being part of the main libuv repo. I just noticed that some branches were incredibly stale and wanted to clean it up.

I've removed the threadpool-rework branch but feel free to put it back if you feel like it.
