### ISSUE TITLE
[v2] Remove Windows LSP support?

### ISSUE THREAD

**Issue by saghul** [libuv/libuv#972]
libuv seems to try very hard to work even when LSPs are in place. Apparently they are not so widely used these days and [deprecated](https://en.wikipedia.org/wiki/Layered_Service_Provider#Deprecation_and_LSP_bypass), so I guess we could drop support for those and delete some code. (I'm into deleting code lately).

@piscisaureus @orangemocha WDYT?

**Comment by orangemocha** [comment]
deferring to @joaocgreis

**Comment by piscisaureus** [comment]
That sounds like a good idea. 

You could make libuv always sidestep them by explicitly requesting the msafd provider when creating a socket. The WSASocket function takes an argument to specify the provider.

The question is what you would do if you got a non-afd socket handed to uv_tcp_open() or uv_poll_init(). I guess libuv should do a provider check and reject nonstandard sockets?

**Comment by saghul** [comment]
Hey Bert, thanks for chiming in!

> You could make libuv always sidestep them by explicitly requesting the msafd provider when creating a socket. The WSASocket function takes an argument to specify the provider.

Great, I'll check that.

> The question is what you would do if you got a non-afd socket handed to uv_tcp_open() or uv_poll_init(). I guess libuv should do a provider check and reject nonstandard sockets?

I'd say so, yes.

**Comment by saghul** [comment]
@piscisaureus Question: we need to find the right `WSAPROTOCOL_INFO` to pass to `WSASocket` in order to select the AFD provider. The only way I found to do that is to use `WSAEnumProtocols`, then filter the results by `iAddressFamily` and see if `ProviderId` matches one of the 3 magical GIDs. Is this the right way to go? If so, can we cache these structures? (As in, we can find them at startup time and then store them in static variables.)

**Comment by piscisaureus** [comment]
Hi @saghul,

I assumed even that the values for WSAPROTOCOL_INFO could just be a hard-coded, but after reading the docs again I'm not quite sure. But certainly the values should be looked up only once and then be cached.

I think you need to look up only two providers (tcp and udp). The third one mentioned in poll.c is for raw/ip sockets but libuv doesn't support creating those.

Last but not least, I would recommend avoiding ANSI-based APIs and to always explicitly use unicode variants. Practically speaking, use struct WSAPROTOCOL_INFOW and create sockets with WSASocketW.

👾

**Comment by saghul** [comment]
@piscisaureus Thanks Bert, will do! 👍

**Comment by joshgav** [comment]
@clca, sorry to bug you, but do you perhaps know what motivated including LSP to begin with?

@saghul - does this date from the original release of libuv or was it a later addition?

Doing due diligence to make sure we don't break something which depends on it.

**Comment by saghul** [comment]
It was there pretty early on if not from the get go.

This is for v2, and when we release it v1.x will still be maintained,
though we will switch the main focus to v2.

Microsoft has deprecated LSPs a while ago, and Windows 10 apps bypass them
anyway, so those still wanting to use them are ignoring the big sign on the
wall :-)

**Comment by saghul** [comment]
That was of course for those who come and read the issue. You know that already @joshgav :-)

**Comment by joshgav** [comment]
Thanks @saghul. I also contacted @clca out-of-band and he felt it was fine to remove it too. So LGTM!

**Comment by saghul** [comment]
Excellent! Can I thouble either of you for the code review once I finished the patch?

**Comment by joaocgreis** [comment]
@saghul you can trouble me as well!

**Comment by saghul** [comment]
Excellent! Thanks @joaocgreis!

**Comment by vtjnash** [comment]
I would be surprised if anyone knew whether they were actually depending on this code currently, since it should "just work". So it could be a unpleasant surprise for someone to have their app stop working on update. Reducing SLOC count in the abstraction layer doesn't seem like sufficient justification for that (isn't the point of the abstraction layer to make sure these cases don't surprise the downstream user?).

Anyways, I've had to work with customers who had the Sophos Firewall installed  (https://community.sophos.com/kb/en-us/116384), and know that it hits this case.
