### ISSUE TITLE
tty code changes controlling terminal

### ISSUE THREAD

**Issue by vtjnash** [libuv/libuv#973]
The explicit call to `open(tty)` may change the controlling terminal to the current process (on some platforms? observed on OS X, but not linux), even if that's not desirable for the caller. There should be no need to explicitly change the controlling terminal, since it'll inherit the original setting even if all of the fds are closed. Thus, I think we should add the explicit flag to disable this:

``` diff
diff --git a/src/unix/tty.c b/src/unix/tty.c
index 32fa37e..3727a83 100644
--- a/src/unix/tty.c
+++ b/src/unix/tty.c
@@ -87,7 +87,7 @@ int uv_tty_init(uv_loop_t* loop, uv_tty_t* tty, int fd, int readable) {
      * slave device.
      */
     if (uv__tty_is_slave(fd) && ttyname_r(fd, path, sizeof(path)) == 0)
-      r = uv__open_cloexec(path, O_RDWR);
+      r = uv__open_cloexec(path, O_RDWR | O_NOCTTY);
     else
       r = -1;
```

Then, if user wants to become the controlling terminal, they have the freedom of choice in their application to call `ioctl(STDIN_FILENO, TIOCSCTTY, 0)`.

More details on these behaviors can be found in BSD termios(4) under "The Controlling Terminal" (https://www.freebsd.org/cgi/man.cgi?query=termios&sektion=4)

(this caused https://github.com/JuliaLang/julia/issues/16398)

**Comment by bnoordhuis** [comment]
I realize libuv is depending on platform-specific behavior but I'm a little concerned O_NOCTTY might cause regressions when combined with the UV_PROCESS_DETACHED uv_spawn() flag.

Because it calls setsid(), O_NOCTTY means the child process would no longer get a controlling tty.  I have a hard time coming up with a fix that maintains compatibility under that scenario.

> Then, if user wants to become the controlling terminal, they have the freedom of choice in their application to call ioctl(STDIN_FILENO, TIOCSCTTY, 0).

That goes both ways, though.  The application can relinquish control again with `ioctl(STDIN_FILENO, TIOCNOTTY)`.

**Comment by vtjnash** [comment]
> That goes both ways, though. The application can relinquish control again with ioctl(STDIN_FILENO, TIOCNOTTY).

Yes, but the other session that was being controlled by this terminal can't reliably regain control, causing them to lose their STDIO when it exits.

@Keno proposed that we can add a flag to `uv_spawn` that specifies which fd (if any) should be used as the controlling terminal after the `setsid` call.

**Comment by bnoordhuis** [comment]
That sounds reasonable but anything that changes the API or ABI in a non-backwards compatible way can not land in v1.x, only v2.x.

**Comment by vtjnash** [comment]
Sure, I'm just hoping that by v2.x that we can land enough of the fixes from our Julia fork that we can start using master.

**Comment by saghul** [comment]
2.0 won't happen overnight, so I too hope we can get all your fixes in!

**Comment by vtjnash** [comment]
not stale—still a known issue that libuv conditionally might call `open` on the tty (added b197515367d1a996dca9009483d202b306f9474e, around v0.11.22) and cause this secondary effect. JuliaLang has been carrying a patch ever since then to avoid that regression.

**Comment by bnoordhuis** [comment]
Since v1.x is still going strong, perhaps we need a `uv_tty_init_ex()` that takes an additional flags argument? Then callers can indicate they want `O_NOCTTY` behavior.

**Comment by vtjnash** [comment]
I just bumped this to make the stale-bot happy. I don't really care if it doesn't get fixed until v2 (where we've already got an unused int parameter), since I need that for other reasons. Just seems unfortunate that this regression snuck into v1, so now you feel stuck in keeping it. But while I'm here, might as well try to clarify some points.

You mentioned above that a child detached from the terminal won't get a controlling TTY. Yes, that's the goal here, and is what some operating systems already do when you use libuv. The aim of this issue was to restore consistency.

 - FreeBSD makes it explicit in their documentation that NOCTTY is the default—and only possible—behavior there.
 - My observations of linux is that it usually acts like you passed NOCTTY. I think this would be the behavior I'd most expect from following the spirit of the posix standard.
 - However, it appears that mac OS interpret the standard differently and strips the parent process of its controlling terminal if you don't pass this flag. This is the bad case we ran into, so I added the flag to our fork make it work like other platforms.

**Comment by bnoordhuis** [comment]
Hm okay, if it's only macOS that's the outlier... I suppose we could try switching on `O_NOCTTY` and see if we get any bug reports. Want to open a PR?
