### ISSUE TITLE
Compilation Failing on MinGW (Windows 10)

### ISSUE THREAD

**Issue by Choonster** [libuv/libuv#982]
libuv: a6acc822452b07564c0440bdb7909b7edc805013 (latest commit on branch `v1.x`)
OS: MINGW32_NT-6.2 (MSYS shell on Windows 10)

Compilation errors:
```
  CCLD   libuv.la
src/win/.libs/libuv_la-tty.o: In function `uv_tty_line_read_thread':
C:\MinGW\msys\1.0\home\USER\libuv/src/win/tty.c:473: undefined reference to `_InterlockedOr'
src/win/.libs/libuv_la-tty.o: In function `uv__cancel_read_console':
C:\MinGW\msys\1.0\home\USER\libuv/src/win/tty.c:1041: undefined reference to `_InterlockedOr'
collect2.exe: error: ld returned 1 exit status
make: *** [libuv.la] Error 1
```

[Full test output](https://gist.github.com/Choonster/44ec6c4029f44ec5a908759255e56a5f)

Steps to reproduce:
```
git clone https://github.com/libuv/libuv.git
cd libuv
git checkout a6acc822452b07564c0440bdb7909b7edc805013
sh autogen.sh
./configure
make
make check &>testoutput.txt
```

**Comment by bnoordhuis** [comment]
Does it work with mingw64?  We dropped support for mingw32 last week, see commit 4613cc916a99674bc562090eacdb6259cafce765.

**Comment by saghul** [comment]
@bnoordhuis That's on master though, on v1.x we technically still support the older MinGW. That said, it's kind-of "support it yourself", so the PRs are welcome rule applies, I guess :-)

**Comment by saghul** [comment]
@Choonster any reason why you are not using / can't use MSYS2? It's so much better these days.

**Comment by Choonster** [comment]
I just reinstalled MinGW to confirm that #264 was fixed. There seem to be quite a few forks and related projects, so I wasn't sure which version of MinGW/MSYS to install.

I'll try this on MinGW-w64 and MSYS2.

**Comment by saghul** [comment]
@Choonster No worries. I can really recommend the MSYS2 installer: https://msys2.github.io/ It'll get you up and running in no time and it comes with pacman from ArchLinux ported to Windows so you can install stuff easily from the command line.

**Comment by Choonster** [comment]
What's the supported way to build libuv in MSYS2?

If I run this:
```
git clone https://github.com/libuv/libuv.git
cd libuv
git checkout a6acc822452b07564c0440bdb7909b7edc805013
git clone https://chromium.googlesource.com/external/gyp.git build/gyp
python2 ./gyp_uv.py -f make
make -C out
```

I get this error from `make`:
```
make: Entering directory '/c/Users/USER/Documents/libuv/MSYS2/libuv/out'
Makefile:317: ../run-tests.target.mk: No such file or directory
make: *** No rule to make target '../run-tests.target.mk'.  Stop.
make: Leaving directory '/c/Users/USER/Documents/libuv/MSYS2/libuv/out'
```

**Comment by saghul** [comment]
do `make -C out/Debug`

or use autoconf if you prefer.

**Comment by Choonster** [comment]
If I run `make -C out/Debug` instead of `make -C out`, I get this error:
```
make: *** out/Debug: No such file or directory.  Stop.
```

If I run this:
```
git clone https://github.com/libuv/libuv.git
cd libuv
git checkout a6acc822452b07564c0440bdb7909b7edc805013
sh autogen.sh
./configure
make
make check &>testoutput.txt
```

I get a [large number of compilation errors](https://gist.github.com/Choonster/bc8519949215cbdafb34d9a5b2056ac0).

Am I doing something wrong?

**Comment by saghul** [comment]
Hum, that's weird. What do you have in the out/ directory, when using GYP? (no need to specify -f make when generating, I think)

For the autoconf build, maybe you're missing the win32headers package? (I think it was called that way).

I'll try to test it myself in a pristine environment and let you know.

**Comment by Choonster** [comment]
The only file in the out/ directory after running GYP is [this Makefile](https://gist.github.com/Choonster/6e4b4d3ce5bf6b144f5097bc0ba7f06e).

**Comment by saghul** [comment]
Ok, I rebuilt my MSYS2 environment from scratch. Here is how to do it with autotools:

- Start the MinGW-w64 Win64 shell (this is important, the MSYS2 shell won't do)
- Install the gcc toolchain and development tools:  `pacman -S mingw-w64-x86_64-toolchain base-devel`
- Do the autoconf dance

Looks like GYP doesn't quite work (out of the box, that is) with MinGW, so you're better off using autotools.

**Comment by Choonster** [comment]
After installing those packages it now compiles using autoconf (with some warnings), but the `fs_symlink_dir` test is failing.

I've uploaded the build and test output [here](https://gist.github.com/Choonster/cbf095a1504c9a0f4e46d214e3692bc5).

**Comment by joaocgreis** [comment]
For anyone still looking for a solution for the original issue with MinGW, it may be to copy the implementation of `_InterlockedOr` from an old version of MinGW-w64: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/3d41592c81b83f383d85b2bd17aa0de8c791632a/tree/mingw-w64-crt/intrincs/ilockor.c to `src/win/tty.c`. But the tests fail, not sure if because of this.

**Comment by saghul** [comment]
I think this issue got derailed a bit, so I'm going to close it. @Choonster if you see tests fail, please open a new issue, since this one dealt with compilation related issues.  Thanks!
