### ISSUE TITLE
crash for help

### ISSUE THREAD

**Issue by zhjzjnb** [libuv/libuv#985]
Hello everyone.
We are using the libuv(uv_version_string:0.10.15,uv_version:2575) on ubuntu 12.04 and have recently encountered a problem. In some cases (haven't manage to localize yet: it's hard to reproduce and it happens only with high load) the following crash is triggered:
from gdb bt

Program terminated with signal 11, Segmentation fault.
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:39
39	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:39
#1  0x000000000050b1fa in uv__epoll_wait (epfd=<optimized out>, events=<optimized out>, 
    nevents=<optimized out>, timeout=<optimized out>) at ../src/unix/linux-syscalls.c:282
#2  0x0000000000509c3d in uv__io_poll (loop=0xbdf580, timeout=58) at ../src/unix/linux-core.c:160
#3  0x000000000050138c in uv_run (loop=0xbdf580, mode=<optimized out>) at ../src/unix/core.c:317
#4  0x00000000004106e9 in main (argc=1, argv=0x7ffff77e7c68) at src/main.cpp:81

Here is the part of code in src/main.cpp:81:
uv_loop_t*  defaultloop = uv_default_loop();
uv_run(defaultloop, UV_RUN_DEFAULT);

please help me
Thanks in advance.

**Comment by yjhjstz** [comment]
please generator a core file.

**Comment by bnoordhuis** [comment]
Is there any chance you can update to the latest v1.x release or at least the latest v0.10 release?  v0.10.15 was released three years ago, a lot of bug fixes have gone in since that time.

Note that the v0.10 release line is near its end of life.  If updating is a chore, you might as well target v1.x from the get go.

**Comment by saghul** [comment]
No follow-up, closing.
