### ISSUE TITLE
unix: non-async-signal-safe functions in child fork

### ISSUE THREAD

**Issue by bnoordhuis** [libuv/libuv#998]
From `man 2 fork`:

> After a fork(2) in a multithreaded program, the child can safely call only async-signal-safe functions (see signal(7)) until such time as it calls execve(2).

The following functions are called in `uv__process_child_init()` that are not marked async-signal-safe:
1. `ioctl()`, indirectly through `uv__nonblock()` - call `uv__nonblock_fcntl()` instead.
2. `setgroups()` - but unlikely to be an issue in the real world.
3. `execvp()` - problematic because it can do things like malloc memory.

Assigning to `environ` is in the "better don't" category too.

**Comment by bnoordhuis** [comment]
`execvp()` can be simulated by calling `getenv("PATH")` before calling `fork()` (if the path of the binary to spawn is relative), defaulting to `confstr(_CS_PATH)` if it's NULL.  Then, in the child fork,  try to `execve(component + argv0)` them in sequence.

**Comment by saghul** [comment]
All the actionable items have been fixed in #1167, closing!
